Charger Crusher Balance/Fixes
cmss13-devs/cmss13 pull request #1009
Opened 2022-09-06 19:00 UTC by PhantomEpicness

## About The Pull Request
This PR aims to fix a multitude of bugs and balance issues that have surfaced since the charger's merging.

Issue: Too much damage
- Nerfed slash damage from 40 to 30. This also nerfs stomp damage as it is slash damage + 15
- Nerfed runover damage from momentum * 10 to momentum * 6.
- Runover damage now takes armor into consideration and uses overall damage procs
- Charge now spreads to more limbs, 50% spread chance to 60%

Ram reworked
- Ram does not damage nor stun anymore, instead it knocks mobs back and slows them down for 4 seconds.
- Ram has been renamed to "Headbutt" to avoid confusion

Issue: Charger griefs the hive by charging
- Fixed by making charger immediately stop charging if they hit leaders/queen/boiler. They aren't stunned and it is now just as bad as normal body block instead of mowing down friendly xenos + queen.
- Boiler because they have long warmups/cd and can get griefed hard

Bugfixes/misc
- Fixes stomp not screen shaking properly.
- Fixes #990 
- Further cleans up code

## Why It's Good For The Game

## Changelog

:cl: totalepicness
balance: Reworked charger's RAM, it is now renamed to "headbutt" and slows down instead of stuns.
balance: Nerfed chargers slash damage and stomp damage 40 > 30.
fix: Fixed chargers duplicating machineguns.
fix: Fixed ram ignoring armor.
fix: Fixed charger stomp screenshake not working
fix: Charger will now stop charging to Queens,Leaders, and Boilers. 
/:cl:

2022-09-06 19:31 UTC, Carnage068 commented
Thank you, no more funny one shots now.

2022-09-06 20:56 UTC, Carnage068 commented
You forgot to mention that running over people also pushes them aside, similar to how being hit by charge pushes them aside. Unless that's something you decided to go back on between the time you told about it and the time you finished the PR.

2022-09-06 23:37 UTC, Carnage068 commented
Honestly why isn't this speedmerged LOL

2022-09-07 00:23 UTC, RadiationFan commented
R I P Sovlfvl charger, having an AP caste was fun while it lasted.

2022-09-07 01:12 UTC, Carnage068 commented
> R I P Sovlfvl charger, having an AP caste was fun while it lasted.

What does Sovlfvl mean? Just curious.

2022-09-07 01:24 UTC, RadiationFan commented
> > R I P Sovlfvl charger, having an AP caste was fun while it lasted.
> 
> What does Sovlfvl mean? Just curious.

Getting oneshot by a charger giving you IB+lethal organ damage was peak sovl.

2022-09-07 02:52 UTC, Wintermote commented
Don't really like the hand holdy IFF feature. Is that for all xeno castes or just the mentioned ones?

It's more interesting imo - and takes a little more brainpower - when you have to actually think about how you use your abilities instead of just being automatically assured that you can't hurt other xenos with them. 

Crusher knocking down a T1 that gets in its way just feels right.

2022-09-07 02:59 UTC, PhantomEpicness commented
> Don't really like the hand holdy IFF feature. Is that for all xeno castes or just the mentioned ones?
> 
> It's more interesting imo - and takes a little more brainpower - when you have to actually think about how you use your abilities instead of just being automatically assured that you can't hurt other xenos with them.
> 
> Crusher knocking down a T1 that gets in its way just feels right.

Charger only stops to important castes like queen, boiler and whoever the queen designates as important (leaders)

2022-09-07 03:00 UTC, Carnage068 commented
> Getting oneshot by a charger giving you IB+lethal organ damage was peak sovl.

Ah. Well, yeah, I guess it was, then, LOL.

2022-09-07 03:01 UTC, Carnage068 commented
> Charger only stops to important castes like queen, boiler and whoever the queen designates as important (leaders)

Imagine Leader Runner accidentally bumping into a Charger while it's trying to flank marines and completely screwing it over LOL. Would be awesome if something like that ever happened.

2022-09-07 21:40 UTC, stanalbatross approved these changes

2022-09-07 21:40 UTC, stanalbatross commented on code/modules/mob/living/carbon/xenomorph/abilities/crusher/crusher_abilities.dm
> +			//Mob.emote("pain")
delete unused line

2022-09-07 21:40 UTC, stanalbatross commented on code/modules/mob/living/carbon/xenomorph/abilities/crusher/crusher_powers.dm
> +			playsound(Human,"bone_break",50,TRUE)
may be deceptive

2022-09-07 21:50 UTC, stanalbatross requested changes
wrong button

2022-09-08 15:38 UTC, GoldenDarkness55 commented
Woulda been better if it only stopped on boilers/queens, can get annoying with leaders and it's rarely a big deal if you get pushed. Also the whole issue is possibly even worse if this merges because the crusher will just bodyblock you over pushing you to the side where you could continue walking unimpeded.

2022-09-10 06:38 UTC, Chainsawicus commented
While I agree that Charger is in an overtuned state, I feel that this PR doesn't really address the core issue with it - the charge is the worst part of its kit by far. You are unironically better off only using tumble, stomp, and ram than spending time setting up charging lines or co-ordinating with builders. It was never really an issue that the charge itself did so much damage because setting up a scenario where you hit it was so specific that the damage was entirely earned.

IMO you could shaft the Ram ability entirely to reduce Charger's ability to setup easy stomp + tail stab combos (as tail stab is basically guaranteed to get put in at this point) and make it so Tumble's effects are based off your momentum when using it, so using it from a standstill only moves you and doesn't affect others, while using it during charge will apply its current effects. From there I don't think any more changes would really be necessary but could easily see justification for giving Charger better movespeed than base so it fully fits into the "mobility crusher" role.

2022-09-10 23:04 UTC, Carnage068 commented
> 



> While I agree that Charger is in an overtuned state, I feel that this PR doesn't really address the core issue with it - the charge is the worst part of its kit by far. You are unironically better off only using tumble, stomp, and ram than spending time setting up charging lines or co-ordinating with builders. It was never really an issue that the charge itself did so much damage because setting up a scenario where you hit it was so specific that the damage was entirely earned.
> 
> IMO you could shaft the Ram ability entirely to reduce Charger's ability to setup easy stomp + tail stab combos (as tail stab is basically guaranteed to get put in at this point) and make it so Tumble's effects are based off your momentum when using it, so using it from a standstill only moves you and doesn't affect others, while using it during charge will apply its current effects. From there I don't think any more changes would really be necessary but could easily see justification for giving Charger better movespeed than base so it fully fits into the "mobility crusher" role.

Never thought I'd end up saying this, but I 100% agree with pretty much everything you've said. Tumble should be used as a tool to hit people who dodge your charge. It's a lot more skillful and balanced than just turning sideways and teleporting onto someone to combo them to death. It would kind of suck not being able to use it to avoid marines bodyblocking you after a charge, but the way I see it there's no way to remove the easy knockdown into stomp combo while keeping it as an escape option.
Just giving it higher base movement speed will allow it to maneuver more easily out of situations that it couldn't before. Also if it's desired, Fling could be kept as it is in this PR (preferably without the slow tho) to still help Charger get out of bodyblocking situations. More base movement speed will also make charging feel more fluid, and just make it faster in general, which, for a strain that's supposed to focus on mobility, it almost seems to be lacking in. Only potential issue is that this would make it impossible to do enough damage when Charger is running away, but this could be easily fixed by lowering the rear armor, which Bengus is pretty much already going to do.

2022-09-11 18:06 UTC, Carnage068 commented
> From there I don't think any more changes would really be necessary but could easily see justification for giving Charger better movespeed than base so it fully fits into the "mobility crusher" role.

Actually something to note is that Charger technically DOES have better movement speed than Base Crusher. The strain has fastmod tier 3, but that's such a tiny amount, even before considering that Base has a movement speed of tier 2 (0.2). The speed modifier puts it at 0.05, which doesn't make it faster than anything it already was before (Those two things being Boiler and Hedgehog), so honestly, it's pretty negligible. You'd have to put the speed modifier at tier 9 or 10 before you could easily spot the difference, which, imo, is what it should be set to. It would put it between Berserker (without stacks) and Oppressor/Warden.

2022-09-13 00:43 UTC, PhantomEpicness commented
> While I agree that Charger is in an overtuned state, I feel that this PR doesn't really address the core issue with it - the charge is the worst part of its kit by far. You are unironically better off only using tumble, stomp, and ram than spending time setting up charging lines or co-ordinating with builders. It was never really an issue that the charge itself did so much damage because setting up a scenario where you hit it was so specific that the damage was entirely earned.
> 
> IMO you could shaft the Ram ability entirely to reduce Charger's ability to setup easy stomp + tail stab combos (as tail stab is basically guaranteed to get put in at this point) and make it so Tumble's effects are based off your momentum when using it, so using it from a standstill only moves you and doesn't affect others, while using it during charge will apply its current effects. From there I don't think any more changes would really be necessary but could easily see justification for giving Charger better movespeed than base so it fully fits into the "mobility crusher" role.

Yeah, I have plans for a more in-depth balance fix that increases speed as well as further hp adjustments.

However, those will not be included as this PR is aimed to fix the critical balance/bugs quickly

2022-09-13 00:53 UTC, PhantomEpicness commented
I am considering removing the charge stop for the leaders. We'll see if it is problematic or not.

2022-09-14 14:18 UTC, stanalbatross requested changes

2022-09-14 14:18 UTC, stanalbatross commented on code/modules/mob/living/carbon/xenomorph/abilities/crusher/crusher_abilities.dm
> +	weaken_power = FALSE
zero and zero, these are not booleans they are integers

2022-09-18 09:08 UTC, stanalbatross requested changes

2022-09-18 09:08 UTC, stanalbatross commented on code/modules/mob/living/carbon/xenomorph/abilities/crusher/crusher_abilities.dm
> +			var/ram_dir = pick(ram_dirs)
```suggestion
			var/ram_dir = pick(get_perpen_dir(Xeno.dir))
```

2022-09-19 22:02 UTC, PhantomEpicness commented
ready

2022-09-20 17:23 UTC, stanalbatross approved these changes
just apply this and it's fine

2022-10-06 21:53 UTC, Carnage068 commented
the fact that it is taking so long to fix the disastrous, cancerous state charger is in kind of makes me wonder if i even WANT to be unbanned anytime within the next several months. maybe getting permabanned was a good thing??? it's probably easier on my mental health at least LOL

2022-10-16 13:34 UTC, merged