Firing flares into the air and signal flare QoL
cmss13-devs/cmss13 pull request #1014
Opened 2022-09-07 02:21 UTC by morrowwolf

## About The Pull Request

Flare guns can fire flares into the air now. It takes a one second wind up to fire into the air. It can only be fired in the open or places with glass ceilings.

The flare gun description is expanded to show the last fired signal flare's designation.

## Why It's Good For The Game

Neat functionality and QoL. Plus Nanu said it would be fine in a town hall: https://imgur.com/V3N8CZj

## Changelog

:cl: Morrow
add: Flare guns can now be fired into the air via unique action
qol: Signal flares fired by flare guns now show their designation in the flare gun's description.
/:cl:

2022-09-07 16:47 UTC, morrowwolf commented
> That a cool idea, but I do see a potential issue with xenos not being able to differentiate regular and CAS flares in the air. Unsure if this is an issue or not

Feature.

2022-09-07 22:41 UTC, stanalbatross requested changes

2022-09-07 22:41 UTC, stanalbatross commented on code/modules/projectiles/guns/specialist.dm
> +	if(!user || !istype(user.loc, /turf/) || !current_mag || !current_mag.current_rounds)
use isturf here instead of the istype

2022-09-07 22:41 UTC, stanalbatross commented on code/modules/projectiles/guns/specialist.dm
> +		return
to avoid this you should also do an if(user.action_busy) check before the do_after

2022-09-07 22:41 UTC, stanalbatross commented on code/modules/projectiles/guns/specialist.dm
> +		to_chat(user, SPAN_NOTICE("The [src] jams as it is somehow loaded with incorrect ammo!"))
```suggestion
		to_chat(user, SPAN_NOTICE("\The [src] jams as it is somehow loaded with incorrect ammo!"))
```

2022-09-07 22:41 UTC, stanalbatross commented on code/modules/projectiles/guns/specialist.dm
> +		last_signal_flare_name = signal_flare.name
better way than this exists, call a proc on the fired_flare instead of using the dreaded istype

2022-09-09 20:56 UTC, stanalbatross requested changes

2022-09-09 20:56 UTC, stanalbatross commented on code/modules/projectiles/guns/specialist.dm
> +		return
should be before breaking the ceiling and taking away rounds

2022-09-14 14:21 UTC, stanalbatross requested changes
looks fien

2022-09-14 14:21 UTC, stanalbatross commented on code/modules/projectiles/guns/specialist.dm
> +	fired_flare.invisibility = INVISIBILITY_MAXIMUM
mouse opacity needs to be false or you will still be able to right click it and melt it lol

2022-09-18 09:03 UTC, stanalbatross approved these changes

2022-09-23 11:43 UTC, Unknownity commented
was kinda hoping it would show the location of the flare to everyone in OB warning fashion telling you the bearings, to act like an actual feature to ask for assistance

2022-09-24 19:41 UTC, merged