More legacy sprite replacements
cmss13-devs/cmss13 pull request #1037
Opened 2022-09-10 01:18 UTC by Agameofscones

## About The Pull Request

Originally this was a port of YoutubeBoy's weapon sprites, but uh then they nuked their remote so I've gone and done this all from scratch and then some. Replaces weapon sprites, stock parts, etc. See the CL.

## Why It's Good For The Game

I fucking **hate** legacy sprites

## Changelog

:cl: Triiodine
imageadd: working on it
/:cl:

2022-09-17 02:46 UTC, nauticall requested changes
![image](https://user-images.githubusercontent.com/55491249/190837638-96a284c8-7d65-42de-9f7b-d143fd2a8be3.png)
Stray pixels on the toy hammer

2022-09-17 02:48 UTC, nauticall requested changes
![image](https://user-images.githubusercontent.com/55491249/190837682-e3330cb5-0d43-43fe-a4eb-b337d7731f1c.png)
books are a little bit inconsistent, if this is intentional then ignore but it's a bit weird to have every book except 1 or 2 be the same size

2022-09-18 07:18 UTC, nauticall approved these changes
That was all I had to say, approved now!

2022-09-18 08:55 UTC, stanalbatross approved these changes

2022-09-18 09:00 UTC, merged