Synth eating
cmss13-devs/cmss13 pull request #104
Opened 2022-04-20 03:37 UTC by nauticall

## About The Pull Request

"You sure you don't want some?"

What good is a synthetic at blending in if they can't even eat with humans?

This PR aims to give synthetics the ability to eat food. Until now whenever a synth tried to eat something, they'd be greeted by the clearly-taken-from-IPCs text "You have a monitor for a head, where are you gonna put that?". Does this make sense? Not really. But instead of just fixing that text I decided to go one further and let synths be able to consume stuff.

You might ask, is this realistic? Ask Ash and Bishop.

## Why It's Good For The Game

Synthetics were always stated in universe to be able to blend in almost flawlessly with humans, often not being able to find out if they're human or not except in certain conditions. A synth not being able to eat (you can only go "I'm not hungry" so many times) would eventually be a telltale sign that something's not right with them. So this PR aims to add immersion in that regard as well as just fostering more RP opportunities.

## Changelog

:cl:
add: Synthetics can now eat food.
/:cl:

2022-04-23 17:52 UTC, stanalbatross reviewed
also would be nice if you let them drink too

2022-04-23 17:52 UTC, stanalbatross commented on code/game/objects/items/reagent_containers/food/snacks.dm
> +				fullness = 200 //Synths never get full
```suggestion
		if(isSynth(C))
			fullness = 200 //Synths never get full
```
would be a bit of a nicer check here

2022-05-13 19:53 UTC, stanalbatross requested changes
now that synths can eat this stuff you should make it so that when `trans_to_ingest` is called (a proc that moves reagents that you eat into your bloodstream) it does nothing for synths - this will fix issues with them filling themselves up with nutriment and "tasting" stuff.

2022-05-30 18:23 UTC, Shad0vvs commented on code/modules/reagents/Chemistry-Holder.dm
> +		return
```suggestion
```

2022-05-30 18:23 UTC, Shad0vvs commented on code/modules/reagents/Chemistry-Holder.dm
> +
```suggestion
	if(isSynth(target))
		return
```

2022-05-30 18:24 UTC, Shad0vvs requested changes
approve above

2022-05-30 18:29 UTC, Shad0vvs commented on code/modules/reagents/Chemistry-Holder.dm
> +
```suggestion
```

2022-06-10 05:53 UTC, Shad0vvs approved these changes

2022-06-10 05:53 UTC, merged