Pill Packet QOL
cmss13-devs/cmss13 pull request #1044
Opened 2022-09-12 03:05 UTC by PhantomEpicness

## About The Pull Request
A small QoL PR for pill packets. 
The amount of pills left in them is now reflected in sprites, furthermore, empty pill packets are now trash.

![Screenshot_424](https://user-images.githubusercontent.com/42422230/189566520-8a002d77-07e5-4b0d-8806-7b66580e7fce.png)
![Screenshot_425](https://user-images.githubusercontent.com/42422230/189566523-2b95174b-2583-4f9d-a72e-87bf5a8406d9.png)

## Why It's Good For The Game
soul

## Changelog

:cl: TotalEpicness
qol: Pill packets now reflect the remaining amount of pills.
/:cl:

2022-09-12 03:10 UTC, morrowwolf requested changes

2022-09-12 03:10 UTC, morrowwolf commented on code/game/objects/items/storage/firstaid.dm
> +	icon_original = icon_state
This looks like it could be done with initial() rather than a var. Let me know if I am incorrect.

2022-09-12 03:37 UTC, morrowwolf requested changes
Getting some runtimes related to the qdel.

2022-09-13 00:36 UTC, PhantomEpicness commented
runtimes fixed

2022-09-13 00:36 UTC, PhantomEpicness commented
nvm forgot to push from desktop at home

2022-09-13 07:50 UTC, morrowwolf requested changes
This doesn't need to touch parent code to do this. This has a lot of implications that are unnecessary.

Override the attempt remove function from /obj/items/storage in /obj/item/storage/pill_bottle/packet and try getting that to work.

Should be a simple:
```
/obj/item/storage/pill_bottle/packet/whatever_the_remove_proc_is(arguments)
..() or if(..()) as applicable
check for nothing in contents then make your trash and qdel(src)
```

2022-09-13 23:00 UTC, PhantomEpicness commented
> 



> This doesn't need to touch parent code to do this. This has a lot of implications that are unnecessary.
> 
> Override the attempt remove function from /obj/items/storage in /obj/item/storage/pill_bottle/packet and try getting that to work.
> 
> Should be a simple:
> 
> ```
> /obj/item/storage/pill_bottle/packet/whatever_the_remove_proc_is(arguments)
> ..() or if(..()) as applicable
> check for nothing in contents then make your trash and qdel(src)

yeah when I was tweakin while making this

fixed

2022-09-16 06:00 UTC, Agameofscones requested changes
You should handle the individual sprites as a greyscale overlay. This amount of hardsprites is unacceptable and makes pill packets less modular for future content development

2022-10-02 00:45 UTC, closed without merging