ID locked item QoL
cmss13-devs/cmss13 pull request #1049
Opened 2022-09-12 22:35 UTC by PhantomEpicness

## About The Pull Request
ID locked items now unlock when swiped with their owner's ID card after a confirmation prompt.

## Why It's Good For The Game

Removes stupid situations where a spec doesnt want an item, but takes it out of the box, leading to the item being useless. This has notably screwed over many Sniper Spec spotters as their entire kit is useless because the spec touched it.

Yes I know command IDs override, but CO/XO have better things to do than to unlock spec gear.

Now the owner (whoever it is locked to) can swipe their ID to remove the ID locking altogether. 

## Changelog

:cl: TotalEpicness5
qol: ID locked items (ex: items in spec box) can now be unlocked by their owner swiping their ID on it.
/:cl:

2022-09-12 23:13 UTC, DylonBR commented
certified balance label moment

2022-09-14 14:12 UTC, stanalbatross requested changes

2022-09-14 14:12 UTC, stanalbatross commented on code/game/objects/items.dm
> +		if(((flags_item & MOB_LOCK_ON_EQUIP)) && (user == locked_to_mob))
flag check before istype please

2022-09-14 14:12 UTC, stanalbatross commented on code/game/objects/items.dm
> +				log_admin("[user] has removed the ID lock on \the [src]. Owner of the item was [locked_to_mob] (CKEY: ([user.ckey]))")
needs improving, this makes it look like the owner's ckey is the user's. Also include JMP link.

2022-10-05 10:35 UTC, stanalbatross requested changes

2022-10-05 10:35 UTC, stanalbatross commented on code/game/objects/items.dm
> +			to_chat_spaced(world,"A")
💢

2022-10-05 10:35 UTC, stanalbatross commented on code/game/objects/items.dm
> +			if (alert(user, "Would you like to disable the ID lock for \the [src]. This cannot be undone!", "Confirm", "Yes", "No") == "Yes")
```suggestion
			if (alert(user, "Would you like to disable the ID lock for \the [src]? This cannot be undone!", "Confirm", "Yes", "No") == "Yes")
```

2022-10-21 00:38 UTC, closed without merging