New old grab system and warrior lunge.
cmss13-devs/cmss13 pull request #105
Opened 2022-04-20 04:12 UTC by Binbers

## About The Pull Request
Hello. Please refer to these two links for full details on the changes.
https://gitlab.com/cmdevs/colonial-warfare/-/merge_requests/2849 and https://gitlab.com/cmdevs/colonial-warfare/-/merge_requests/2561

## Why It's Good For The Game

Returning and un-simplifying the variable grab levels and resist chances will provide plenty of RP potential as it had been as well as highlighting the teamwork aspect requiring humans to rely on each other furthermore OR understand the factors of aggressive grab in escalated RP situations.

As for the warrior change, this would distinguish the warrior caste as an individual caste it once was as opposed to being the average "click or macro combo until marine horizontal" clone of other castes that often times can't seem to decide how it wants to be balanced. It would slightly emphasize interesting and specialized gameplay over speed & competition and provide a separate medium for balancing the warrior instead of changing its health/armor/damage values upside-down every 3 months.

## Changelog

:cl:
tweak: Different levels of grab offer different chances for successful resisting and different CQC skillsets offer different speeds for attempting resists

tweak: Choke grab now deals less oxygen damage per ticks

tweak: Choke grab will not pull the puller and pullee onto the same time anymore (because you don't fireman carry someone you're choking on your shoulders). Only carry grab will now overlap the puller and pullee onto the same tile

bugfix: Warrior lunge grab level finally fixed from unintentionally being passive grab. GRAB_NECK level is re-added and explicit to warriors

bugfix: Warrior lunge can now move pullees again

bugfix: Choke grab can now move mobs over to other tiles
/:cl:

2022-04-20 15:29 UTC, usnpeepoo commented
The last time this was merged (before the tile click fix) marines who were lunged by warriors were stunned for an abnormal amount of time if they couldn’t resist out of it, predators sometimes getting one lunge devoured into a capture. Is this MR really just bringing back old warriors stun? The current lunge is pretty fine and balanced with what you get out of it but making it RNG will just be a massive buff to warrior.

2022-04-28 20:40 UTC, stanalbatross commented
I'll look at this tomorrow

2022-05-02 20:48 UTC, stanalbatross requested changes

2022-05-02 20:48 UTC, stanalbatross commented on code/modules/mob/living/living.dm
>  				if(GRAB_CARRY)
```suggestion
```
already a check for that above as you added

2022-05-02 20:48 UTC, stanalbatross commented on code/modules/mob/living/living_verbs.dm
> +			next_move = world.time
can be condensed into one with a comma like 
```suggestion
		if(SKILL_CQC_MASTER, SKILL_CQC_MAX)
			next_move = world.time
```
also MASTER and MAX go to the same number so it's not even needed

2022-05-02 20:50 UTC, stanalbatross requested changes
also you should not be trying to merge your master into dev, make a separate branch for each PR

2022-05-04 07:20 UTC, Binbers commented
> also you should not be trying to merge your master into dev, make a separate branch for each PR

I stuck w/ master cause I chose to. If I know I'll be frequenting the code often enough to make more than one PRs at a time, sure thing I would've done so

2022-05-06 06:20 UTC, Binbers commented
Ridding merely "if(GRAB_CARRY)" nuked the entire if else chain, fixed it and it's more cleaned up in addition to working now

2022-05-15 20:14 UTC, stanalbatross commented
resolve conflicts and I'll review again

2022-06-18 00:31 UTC, closed without merging