Player Panel human name reset and ban
cmss13-devs/cmss13 pull request #1059
Opened 2022-09-15 10:56 UTC by morrowwolf

## About The Pull Request

This adds a section to handle human names in the player panel punish panel. 
Human name reset will allow you to change the name manually or have a random name selected and will set the preference name correctly.
Human name ban will disallow people from using custom names but they can still randomize until they find something they like.

## Why It's Good For The Game

Admins no longer have to tell "BEST MARINE" to change their name preferences four rounds in a row.

## Changelog

:cl: Morrow
admin: Added human name reset and human name ban to player panel.
/:cl:

2022-09-18 08:44 UTC, stanalbatross requested changes

2022-09-18 08:44 UTC, stanalbatross commented on code/modules/admin/player_panel/actions/punish.dm
> +	if(istype(target_mob, /mob/living/carbon/human))
ishuman

2022-09-18 08:44 UTC, stanalbatross commented on code/modules/admin/player_panel/actions/punish.dm
> +	to_chat(target_mob, SPAN_DANGER("Warning: Your name has been reset by [user.ckey]."))
make this bigger and accompany with a sound

2022-09-18 08:44 UTC, stanalbatross commented on code/modules/admin/player_panel/actions/punish.dm
> +	message_staff("[user.ckey] has reset [target_mob.ckey] name")
```suggestion
	message_staff("[user.ckey] has reset [target_mob.ckey]'s name.")
```

2022-09-18 08:44 UTC, stanalbatross commented on code/modules/admin/player_panel/actions/punish.dm
> +/datum/player_action/reset_human_name/act(var/client/user, var/mob/target, var/list/params)
needs a check for if they have a client

2022-09-18 08:44 UTC, stanalbatross commented on code/modules/admin/player_panel/actions/punish.dm
> +		if(alert(user, "Are you sure you want to UNBAN [target.ckey] and let them use human names?", ,"Yes", "No") == "No")
null arg bad

alert()s can take a long time

requires another client check and ckey check after

2022-09-18 08:44 UTC, stanalbatross commented on code/modules/admin/player_panel/actions/punish.dm
> +		to_chat(target, SPAN_DANGER("Warning: You can use human names again."))
bigger

2022-09-18 08:44 UTC, stanalbatross commented on code/modules/admin/player_panel/actions/punish.dm
> +	to_chat(target, SPAN_DANGER("Warning: You were banned from using human names by [user.ckey]."))
as above

2022-09-18 08:44 UTC, stanalbatross commented on code/modules/admin/player_panel/actions/punish.dm
> +
alert()s can take a long time

requires another client check and ckey check after

2022-09-18 08:44 UTC, stanalbatross commented on code/modules/admin/player_panel/actions/punish.dm
> +	if(alert(user, "Do you want to manually set the name for [target_mob.ckey]?", , "Yes", "No") == "No")
alert()s can take a long time

requires another client check and ckey check after

2022-10-05 10:41 UTC, stanalbatross requested changes

2022-10-05 10:41 UTC, stanalbatross commented on code/modules/admin/player_panel/actions/punish.dm
> +		if(alert(user, "Are you sure you want to UNBAN [target.ckey] and let them use human names?", ,"Yes", "No") == "No")
null args

2022-10-23 11:46 UTC, stanalbatross requested changes

2022-10-23 11:46 UTC, stanalbatross commented on tgui/packages/tgui/interfaces/PlayerPanel.js
> +            onClick={() => act("ban_human_name")}
if they are already unbanned the button should show that by clicking it you'll unban them

2022-10-24 17:21 UTC, stanalbatross commented on code/modules/admin/player_panel/player_panel.dm
> +		.["client_name_banned_status"] = targetMob.client.human_name_ban
```suggestion
		.["client_name_banned_status"] = targetClient.human_name_ban
```

2022-10-26 16:31 UTC, Geevies requested changes

2022-10-26 16:31 UTC, Geevies commented on code/modules/admin/player_panel/actions/punish.dm
> +		to_chat(user, SPAN_WARNING("[target.name] does not have a client!"))
return

2022-10-26 16:31 UTC, Geevies commented on code/modules/admin/player_panel/actions/punish.dm
> +	if(alert(user, "Do you want to manually set the name for [target_mob.ckey]?", "Confirmation", "Yes", "No") == "No")
should add a third option here that lets em cancel out if they got this far and regret it

2022-10-26 16:31 UTC, Geevies commented on code/modules/admin/player_panel/actions/punish.dm
> +		to_chat(user, SPAN_WARNING("[target.name] does not have a client!"))
return

2022-10-26 17:01 UTC, merged