General tail stab
cmss13-devs/cmss13 pull request #1062
Opened 2022-09-15 11:18 UTC by morrowwolf

## About The Pull Request

Re-opening: https://github.com/cmss13-devs/cmss13/pull/954

With permission from Geeves I will be re-opening and maintaining some closed pull requests while he is on break.

## Why It's Good For The Game

"It's a cool-ish feature that sorta-ish used to exist, so this brings it back in a new-ish revamped-ish way. It's also something I loved using an AVP2010 when I kill my friends, so, nice to have."

## Changelog

:cl: Geeves
add: All xenos have a new generic ability, the Tail Stab, with a two tile range dealing 1.2 times the caste's maximum melee damage, making it more useful on the bigger xenos. It takes one second of being the selected ability before it can be used.
balance: Boilers have an advanced version of the tail stab, called the Toxic Tail Stab, where it injects the target with diluted molecular acid, causing burns and toxin damage.
/:cl:

2022-09-15 12:57 UTC, Chainsawicus commented
Copying my latest feedback on the original PR - 

> Defender should receive a Tail Stab equivalent, it not receiving one just because the sprite has its tail as a mace-like appendage rather than a spear-like is an extremely weak argument for its exclusion. All you have to do is change the name on Defender specifically to "Tail Strike" or "Tail Crush" and leave the rest of the ability's effects as-is and it's a perfectly justifiable, fitting ability.
>
>I've seen people say that "tail sweep" is their tail stab, but it's not an equivalent whatsoever. Tail Sweep is a point-blank small non-damaging stun, while Tail Stab is a short range damaging attack that dazes the opponent and hits your targeted limb, it's not unreasonable to have two abilities that use the tail.

Besides that, thank you for re-opening this.

2022-09-20 04:44 UTC, Wintermote commented
Didn't get to see it playtested, but I'd been hearing that this was giving xenos essentially a push-button free bone break on any given marine, is that intended?

2022-09-20 21:55 UTC, stanalbatross requested changes

2022-09-20 21:55 UTC, stanalbatross commented on code/modules/mob/living/carbon/xenomorph/abilities/boiler/boiler_powers.dm
> +		var/mob/living/carbon/target = .
bad for readability

2022-09-20 21:55 UTC, stanalbatross commented on code/modules/mob/living/carbon/xenomorph/abilities/general_powers.dm
> +	return target
above

2022-09-20 21:55 UTC, stanalbatross commented on code/modules/power/lighting.dm
> +		return TRUE
?

2022-10-03 09:11 UTC, stanalbatross approved these changes

2022-10-03 09:11 UTC, stanalbatross commented on code/modules/mob/living/carbon/xenomorph/abilities/xeno_action.dm
> +	return (cooldown_timer_id == TIMER_ID_NULL) && (charge_time == null || charge_ready)
!charge_time?

2022-10-07 16:29 UTC, stanalbatross approved these changes

2022-10-07 16:30 UTC, merged