Blowtorches no longer can be filled by non fueltanks and break
cmss13-devs/cmss13 pull request #1064
Opened 2022-09-15 17:04 UTC by PhantomEpicness

## About The Pull Request
Fixed #1052 

## Why It's Good For The Game
bugfix + social credit

## Changelog

:cl:
fix: Blowtorches no longer can be filled by non fueltanks and break
/:cl:

2022-09-16 16:32 UTC, stanalbatross requested changes

2022-09-16 16:32 UTC, stanalbatross commented on code/game/objects/items/tools/maintenance_tools.dm
> +	if (istypestrict(O, /obj/structure/reagent_dispensers/fueltank) && get_dist(src,O) <= 1)
check O.reagents not type

2022-09-17 21:05 UTC, PhantomEpicness commented
fixed

2022-09-17 21:19 UTC, stanalbatross requested changes

2022-09-17 21:19 UTC, stanalbatross commented on code/game/objects/items/tools/maintenance_tools.dm
> +	if (O.reagents == "fuel")
still needs to typecheck as a fueltank otherwise you will be able to fill it from beakers,  food, etc

2022-09-30 11:28 UTC, stanalbatross requested changes

2022-09-30 11:28 UTC, stanalbatross commented on code/game/objects/items/tools/maintenance_tools.dm
> +				tank.explode()
you should still be able to trigger explosions on all types of fueltank

2022-09-30 11:28 UTC, stanalbatross commented on code/game/objects/items/tools/maintenance_tools.dm
> +		if (tank.reagents == "fuel" || tank.chemical == "fuel")
error message needed

2022-10-15 00:42 UTC, closed without merging