Allows xenos with more than 300 hours to have a double letter postfix
cmss13-devs/cmss13 pull request #1079
Opened 2022-09-17 01:52 UTC by usnpeepoo

## About The Pull Request

Xenos with 300+ hours can now use another letter for their postfix, instead of a number.
"To clarify: Previously you could also use 2 characters as the postfix but the last of them had to be a number, This allows you to have two letters.

Allowed now:

BR-XXX-AD

XE-XXX-NO

Not Allowed:

HUM-XXX-AN

HU-XXX-3N

etc."
All credit to Nivrak, this is a port of their original MR which was architect/Nanu approved 6 months ago. You can find the link here. I've edited it to be 300 and not 500 as well.
https://gitlab.com/cmdevs/colonial-warfare/-/merge_requests/2623

## Why It's Good For The Game

A better reward for name tags, as well as letting xenos be able to have more freedom in their name choice. This change unlocks tags previously locked by being forced to come up with a number similar to it. It also helps with rule breaking tags being more clear if a player chooses to use the extra letter. QOL basically.

## Changelog
:cl:
add: Xenos with more than 300 hours of playtime (as xeno) can now use a double letter postfix.
/:cl:

2022-09-26 14:19 UTC, Shad0vvs requested changes
Sent some things in discord.

2022-09-27 21:54 UTC, PhantomEpicness commented
Xenos with 500 hours should have the option of switching the numbers and letters

like
12-XENO-45

2022-10-01 18:47 UTC, stanalbatross requested changes

2022-10-01 18:47 UTC, stanalbatross commented on code/modules/client/preferences.dm
> +										to_chat(user, SPAN_WARNING(FONT_SIZE_BIG("You need to play [time_left_until(300 HOURS, playtime, 1 HOURS)] more hours to unlock double letter xeno postfix.")))
needs to check for the length being TWO or this will let people have unlimited first prefixes

2022-10-05 20:42 UTC, Shad0vvs approved these changes

2022-10-05 20:43 UTC, merged

2022-10-05 21:31 UTC, usnpeepoo commented
> Your Fix/Feature pull request is currently below zero (-5). Maintainers may close future Feature/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.

FUCK YOU!!!!