Sedative rework + Tranq gun buff
cmss13-devs/cmss13 pull request #1085
Opened 2022-09-18 05:42 UTC by PhantomEpicness

## About The Pull Request
Reworks sedative so it's actually consistent and works as a sedative. It also is now balanced as its consistent and uses stamina damage to incapacitate rather than sleep due to sleep causing someone to be stunned for an unpredictably long period of time.

Also buffs tranquilizer gun to use a sedative chemical as currently it is shit as seen by Warfan's UPP event on 9/17, the UPP agents were robusted because the tranq gun dealt 30 stamina damage so it didn't even knock people down on one hit and even if they mag dumped them, they would go up in less than a minute

With this rework it now is more realistic in the following ways:

- Each round injects 4u of tranquilizer, lasting no more than one minute and twenty seconds before the victim starts to awake again.
- It takes a few seconds to kick in, meaning the victim can fight back in the precious few seconds they have left.
- It has an OD, causing oxyloss, critical OD causes brain damage.
- Medical can do something about it by flushing the victim's chems. This provides more RP opportunities.

## Why It's Good For The Game
Reworks an untouched and very inefficient chemical property. Makes tranq guns actually tranquilize people

## Changelog

:cl: Totalepicness5
add: Reworked sedative chemical property. It now consistantly 
balance: Rebalanced tranq gun to be more effective.
/:cl:

2022-09-18 08:34 UTC, stanalbatross requested changes

2022-09-18 08:34 UTC, stanalbatross commented on code/modules/projectiles/ammo_datums.dm
> +	M.reagents.add_reagent("tranq", amount, , , user)
use named args instead of null ones

2022-09-18 08:34 UTC, stanalbatross commented on code/modules/projectiles/ammo_datums.dm
> +	to_chat(M,SPAN_XENOHIGHDANGER("\The [src] injects something into you...."))
? span_warning

2022-09-18 08:34 UTC, stanalbatross commented on code/modules/reagents/chemistry_reagents/toxin.dm
> +	description = "A synthetic central nervous system depressant that is designed to quickly succumb victims into unconciousness."
> succumb victims into unconciousness

this does not make sense

2022-09-19 18:13 UTC, Mrrpip commented
Won't it just get purged by Tricordazine anyhow?

2022-09-19 19:08 UTC, PhantomEpicness commented
> Won't it just get purged by Tricordazine anyhow?
> 
> Edit:(Meaning they can premed or purge it during the few seconds of non-KO)

I dont think purge chems are standard issue, tricord doesn't purge chems either

2022-10-09 00:37 UTC, closed without merging