Immersive AA Sequence (3)
cmss13-devs/cmss13 pull request #11
Opened 2022-04-15 01:01 UTC by PhantomEpicness

## About The Pull Request

https://gitlab.com/cmdevs/colonial-warfare/-/merge_requests/2334#199ac99bb022d31cfd33a4cc3572ef30e96db9b9

This now 6 months on gitlab old PR is meant to make hijacks more immersive, as you can now hear the IX-50 MGAD firing upon its target and xenos/dchat can actually feel the ship getting rocked as they evade the AA fdire.

Added a variety of sounds for, well variety and incase devs don't like a few so I won't have to redo. 

Has an immersive sequence inside the dropship. Complete with sparks, explosions and the whole 9 yards!
(tested to be non lethal to larva)

Not really intended to rework the entire sound backend but ended up reworking a bit of it at the cost of some of my sanity

Also slightly reworked and fixed the soundbackend to support this, thanks @mekkiti for the massive help you lent me over hours of pain.

Reworking the entire sound system is not really the intention of this MR but it turned out that we needed to make a few tweaks here and there to support cool sounds. I do not want to remake the entire sound system because that's out of the scope of this MR and tweaking it to work was already painful enough.

I also filtered and improved the code a bit while porting.

## Why It's Good For The Game

- Cool and immersive sequence! Now you can experience being shredded by AA as a xenomorph or watch as dchat with a mouth full of popcorn!
- Unfortunately for the marines, it does next to no damage for balance purposes. The explosion effects, even if stacked on a single poor larva, couldn't even kill it.
- Immersion and RP fluff announcements. The announcements actually tell whats going on instead of "threat deflected lol". It actually tells players that the threat is still coming which is something that is missing from the current.

## Changelog

:cl: TotalEpicness
rscadd: Hijack now has an immersive AA deterrence sequence if hijacked dropship is crashing into protected area.

soundadd:  Added sounds for the IX-50 MGAD system when it activates. BRRRRT!!!!

add: Reworked alert.ogg (previous was a crappy game rip, now it's professionally cleaned up) Yay!

tweak: MGAD cannon description changed to something more appropriate and realistic.

rscadd: Reworked parts of the sound backend to support more complex sounds. Credit to Firartix for their massive help!

bugfix: Fixed playsound_z not working.

rscadd: Sound backend supports echo and offsetting for surround sound goodness.
/:cl:

2022-04-16 09:50 UTC, Watermelon914 commented on code/modules/cm_marines/anti_air.dm
>  var/obj/structure/anti_air_cannon/almayer_aa_cannon
remove this variable

You don't need GLOB.AAgunLocation because you can just make a global variable called GLOB.aa_gun and then do GLOB.aa_gun.loc

2022-04-16 09:53 UTC, Watermelon914 requested changes

2022-04-16 09:53 UTC, Watermelon914 commented on code/modules/cm_marines/anti_air.dm
> +GLOBAL_VAR_INIT(AAgunLocation,0)
Not how you do global variables, look at using GLOBAL_DATUM

2022-04-16 09:53 UTC, Watermelon914 commented on code/modules/shuttles/marine_ferry.dm
> +			INVOKE_ASYNC(src, .proc/AA_sequence, turfs_int)
make this snake_case

2022-04-16 09:53 UTC, Watermelon914 commented on code/modules/shuttles/marine_ferry.dm
> +	var/datum/effect_system/spark_spread/s3 = new
don't need to make 3 separate spark systems.

2022-04-16 09:53 UTC, Watermelon914 commented on code/modules/shuttles/marine_ferry.dm
> +	var/mob/M
Need more detailed variable names

2022-04-16 09:53 UTC, Watermelon914 commented on code/modules/shuttles/marine_ferry.dm
> +			to_chat(M, SPAN_HIGHDANGER("Lock-on alarms and missile warnings blare from the cockpit! Oh crap!"))
Improve your variable names please they should not be single-letter var names.

2022-04-16 09:53 UTC, Watermelon914 commented on code/modules/shuttles/marine_ferry.dm
> +	create_shrapnel(pick(turfs_int), rand(5,9), , ,/datum/ammo/bullet/shrapnel/light/effect/ver1, cause)
don't use sleep in code like this, you are literally using timers so just increment the time in which they get called

2022-04-16 10:05 UTC, Watermelon914 commented on code/modules/shuttles/marine_ferry.dm
> +			to_chat(M, SPAN_HIGHDANGER("Lock-on alarms and missile warnings blare from the cockpit! Oh crap!"))
This micro optimization is just not worth it. Just define M here instead of defining it early on

2022-04-26 06:16 UTC, PhantomEpicness commented
> This PR has been inactive for long enough to be automatically marked as stale. This means it is at risk of being auto closed in ~ 7 days, please address any outstanding review items and ensure your PR is finished, if these are all true and you are auto-staled anyway, you need to actively ask maintainers if your PR will be merged. Once you have done any of the previous actions then you should request a maintainer remove the stale label on your PR, to reset the stale timer. If you feel no maintainer will respond in that time, you may wish to close this PR youself, while you seek maintainer comment, as you will then be able to reopen the PR yourself

no u

2022-05-04 17:40 UTC, closed without merging