Anti pred slime
cmss13-devs/cmss13 pull request #1102
Opened 2022-09-20 15:13 UTC by Joelampost

## About The Pull Request
-stops preds form changing their SD size mid SD (this only works if someone tries to change it from small to big)
-reduces the amount of health gained from the first step of the medicomp by 10 and gave plus 5 to the following steps 
-stops preds stacking multiple mtend wound surgeries  

## Why It's Good For The Game
less slime good

## Changelog

/:cl: Joe lampost
fix: stops preds form changing their SD size mid SD (this only works if someone tries to change it from small to big)
fix: reduces the amount of health gained from the first step of the medicomp by 10 and gave plus 5 to the following steps 
fix stops preds stacking multiple mtend wound surgeries  
/:cl:

2022-09-20 15:47 UTC, stanalbatross requested changes

2022-09-20 15:47 UTC, stanalbatross commented on code/modules/cm_preds/yaut_bracers.dm
> +	if(explosion_type == 1 && exploding)
why the fuck are these integers make them defines

2022-09-20 21:27 UTC, stanalbatross requested changes
also there is no code in here that stops stacking surgeries

2022-09-20 21:27 UTC, stanalbatross commented on code/modules/cm_preds/yaut_bracers.dm
>  		explosion_type = 1
lampost when I make you add in defines you know you have to add it for the entire thing right?

2022-09-22 04:06 UTC, Joelampost commented
> also there is no code in here that stops stacking surgeries

it only works if you target chest now so it kinda does

2022-09-22 13:33 UTC, stanalbatross requested changes

2022-09-22 13:34 UTC, stanalbatross requested changes
you have fucked up

previously 0 was BIG and 1 was SMALL

swap the numbers and change every define you changed

2022-09-25 13:30 UTC, merged