Xeno Ability check state refractor
cmss13-devs/cmss13 pull request #1148
Opened 2022-09-30 06:18 UTC by PhantomEpicness

## About The Pull Request
This PR refractors Xeno ability checking so that checking obvious conditions like if xenos are dead, marked for deletion, busy or otherwise occurs at the parent rather than the abilities themselves, saving the headache of future coders having to include all of them so dumb bullshit doesn't happen.

It also fixes a bug that allowed xeno_action/activable abilities to skip their usual checks that other types like /onclick would fail.

In essence, abilities can no longer even be selected, let alone even activated, if you are in a state that you shouldn't be allowed to activate abilities.

This has potential issues as well as balance implications so please add a TM tag.

## Why It's Good For The Game
massive coding QoL
Coders no longer have to deal with the clusterfuck of copy + pasting code every time they want to make a new ability or deal with xenos using them while dead. 

## Changelog

:cl: totalepicness
fix: Fixed being able to select an ability despite being dead,crit,incapacitated, etc
refactor: Refractored Xeno ability selection and usage checks
/:cl:

2022-09-30 06:24 UTC, PhantomEpicness commented
**This is not in a merge-ready state.** 

While it is functional, I still need to refractor all Xeno abilities to now call their parents and remove the existing, now redundant checks from them among other things.

I made the PR as I need further dev input on what to check for on all abilities and what exceptions need to be made if necessary.

2022-10-01 11:29 UTC, stanalbatross requested changes

2022-10-01 11:29 UTC, stanalbatross commented on code/modules/mob/living/carbon/xenomorph/abilities/xeno_action.dm
> +		to_chat(X,SPAN_WARNING("You can't do that now USEABILITY."))
better tochat please

2022-10-01 11:29 UTC, stanalbatross commented on code/modules/mob/living/carbon/xenomorph/abilities/xeno_action.dm
> +		to_chat(X,SPAN_WARNING("You can't do that now CAN USE."))
better tochat

2022-10-01 11:29 UTC, stanalbatross commented on code/modules/mob/living/carbon/xenomorph/abilities/xeno_action.dm
> +	return
why does this even need to be a thing if behaviour is all handled in parent

2022-10-22 00:45 UTC, closed without merging