Removes clan sword parry
cmss13-devs/cmss13 pull request #1185
Opened 2022-10-06 21:54 UTC by Joelampost

## About The Pull Request

Predators are not jedi them being able to block super sonic bullets with a blade is LRP

## Why It's Good For The Game

It removes a win button from preds
This PR buffs the sharpness of the sword

## Changelog

:cl: Joe Lampost
add: buffs the sword sharpness
del: Removed 
/:cl:

2022-10-06 21:56 UTC, Shad0vvs requested changes
You removed the X.interference from the weapon line 197-199.

2022-10-06 22:46 UTC, DylonBR commented
entirety of the predcord coming to downvote this soon

2022-10-06 22:49 UTC, carlarctg commented
as the guy who added parry i approve

2022-10-06 22:49 UTC, carlarctg commented on code/modules/cm_preds/yaut_weapons.dm
> +/obj/item/weapon/melee/yautja/sword/attack(mob/living/target as mob, mob/living/carbon/human/user as mob)
you don't need this line, just remove the proc entirely

2022-10-06 23:12 UTC, carlarctg commented on code/modules/cm_preds/yaut_weapons.dm
> +/obj/item/weapon/melee/yautja/sword/attack(mob/living/target as mob, mob/living/carbon/human/user as mob)
This Is Now Fixeder

2022-10-08 08:43 UTC, stanalbatross approved these changes

2022-10-10 08:37 UTC, stanalbatross approved these changes
I will architect approve this because the clan sword parry is a quite unengaging and unforgiving mechanic. It's mainly used to cheese during fights and bait your opponent into being overly cautious when fighting you or they end up shooting themselves. I honestly can't say that it's balanced either, considering it allows preds to basically 1-hit their opponents via reflected PBs as well as make themselves invulnerable to gunfire.

2022-10-10 08:38 UTC, merged