fixes uniform vendor shutters being breakable
cmss13-devs/cmss13 pull request #1188
Opened 2022-10-07 15:15 UTC by stanalbatross

## About The Pull Request

These shutters are meant to be unbreachable, alongside the heavy r-walls around the vendors.

## Why It's Good For The Game

stops marines from accessing the larp vendors without the button being pressed

## Changelog

:cl:
fix: fixed an oversight with uniform vendor shutters that was allowing marines to break into them
/:cl:

2022-10-07 15:17 UTC, silencer-pl commented
I was literally just opening github to put this up lol

2022-10-07 15:17 UTC, usnpeepoo commented
You WILL roleplay and ASK CIC to open up the vendors

2022-10-07 18:06 UTC, Diegoflores31 commented
Clearly killing shipside RP -99

2022-10-07 18:24 UTC, DylonBR commented
YOU WILL NOT HAVE THE SERVICE JACKETS AND YOU WILL LIKE IT

2022-10-07 18:54 UTC, AGasCanister commented
this is unironically LRP, no one would make the uniform vendors the most secure place of the Almayer, just cope and seethe over the fact that marines wear jackets lol

2022-10-07 19:16 UTC, Don2137 commented
another L for jacketards

2022-10-07 19:33 UTC, stanalbatross commented
@DylonBR @Don2137 please refrain from making shitpost comments, iirc both of you have had to have comments hidden before, you are both on track for gitbans if you continue.

2022-10-07 19:34 UTC, silencer-pl commented
>this is unironically LRP, no one would make the uniform vendors the most secure place of the Almayer, just cope and seethe over the fact that marines wear jackets lol

No one would also drag a welder tank to blow open the sealed shutters of a non-combat uniform dispenser and that is exactly what's been happening (to the point of a player literally telling us outright to make them mechanically untouchable or this will continue) nor would a reasonable person weld through the wall of a space ship to get to their service jacket, so they can drop their regular armor and move faster so uh...

2022-10-11 18:24 UTC, Watermelon914 requested changes

2022-10-11 18:24 UTC, Watermelon914 commented on code/game/machinery/doors/shutters.dm
> +	ex_act(severity)
relative pathing = bad

2022-10-11 18:24 UTC, Watermelon914 commented on code/game/machinery/doors/shutters.dm
> +/obj/structure/machinery/door/poddoor/shutters/almayer/uniform_vendors/attackby(obj/item/C as obj, mob/user as mob)
C needs to be more descriptive.

2022-10-11 18:24 UTC, Watermelon914 commented on code/game/machinery/doors/shutters.dm
> +/obj/structure/machinery/door/poddoor/shutters/almayer/uniform_vendors/attackby(obj/item/C as obj, mob/user as mob)
you also don't need `as obj` here and `as mob`

2022-10-24 00:31 UTC, Agameofscones approved these changes
mapping is fine

2022-10-24 07:14 UTC, merged