Officer vendor stuff
cmss13-devs/cmss13 pull request #1190
Opened 2022-10-07 17:31 UTC by 4hands44

## About The Pull Request

Fills the SO vendors after almost a whole year of them being useless
Lets COs dual wield their pistol and can buy a wider selection of backpacks and belts
Honor Guard have a Phonepack for when Comms get eaten again......

## Why It's Good For The Game

CIC better, everyone happy

## Changelog

:cl:
add: COs may now Buy an additional of their Pistol instead of a rifle as their primary
add: COs now Have a Wider variety of Backpacks to Buy
add: SO Vendors now work and have similar items to the XO
add: Made a Bed for jones after his old one was deleted, along with some other cosmetic mapping in the CO/XOs rooms
qol: Put a Mini RTO Kit in the HG locker. This will help Field officers if comms go out
code: Vendor lists, see above
/:cl:

Jones has a bed again
Fills the SO vendors after almost a whole year of them being useless
Lets COs dual wield their pistol and can buy a wider selection of backpacks and belts
Honor Guard have a Phonepack for when Comms get eaten again......

2022-10-07 17:39 UTC, c4xmaniac commented
Has CO council approval btw

2022-10-07 17:45 UTC, stanalbatross requested changes

2022-10-07 17:45 UTC, stanalbatross commented on code/game/machinery/vending/vendor_types/crew/staff_officer.dm
> +GLOBAL_LIST_INIT(cm_vending_clothing_staff_officer, list(
changes to SO starting equipment also needed with this

2022-10-07 17:50 UTC, stanalbatross commented
You do not need to add a "code" cl entry like that. They are only for backend stuff.

2022-10-07 17:50 UTC, stanalbatross commented
Fix weird caps in your CL entry

2022-10-07 17:50 UTC, stanalbatross requested changes
"CIC better, everyone happy"

This is an absolutely insufficient explanation for the PR, please improve it.

2022-10-07 18:55 UTC, Geevies commented
I suggest making a couple bugfix PRs to raise your GBP before making another feature PR.

2022-10-07 18:55 UTC, closed without merging

2022-10-08 03:32 UTC, SexmasterWasTaken commented
:/