Ghost ERT message formatting
cmss13-devs/cmss13 pull request #12
Opened 2022-04-15 01:10 UTC by Shad0vvs

## About The Pull Request

## Why It's Good For The Game

Formatting:

Before and after:
![Untitled](https://user-images.githubusercontent.com/8772348/163502044-eeb73a7e-46b8-42e3-96c7-95d47d6304ba.png)

## Changelog

:cl:
fix: Fixed color formatting on ghost ERT alerts.
/:cl:

2022-04-15 08:46 UTC, stanalbatross approved these changes

2022-04-16 09:54 UTC, Watermelon914 requested changes

2022-04-16 09:54 UTC, Watermelon914 commented on code/datums/emergency_calls/emergency_call.dm
> +			to_chat(M, FONT_SIZE_LARGE("\n<span class='attack'>[ert_message]. >>> <a href='?src=\ref[M];joinresponseteam=1;'><b>Join Response Team</b></a> <<<</span>"))
you should not be putting in >>> and <<< in html statements, these should be &lt; and &gt;

2022-04-18 13:17 UTC, Watermelon914 commented on code/datums/emergency_calls/emergency_call.dm
> +			to_chat(M, FONT_SIZE_LARGE("\n<span class='attack'>[ert_message]. >>> <a href='?src=\ref[M];joinresponseteam=1;'><b>Join Response Team</b></a> <<<</span>"))
sorry this was a mistake because html memes, you need to use `&lt;` and `&gt;`

2022-04-18 22:58 UTC, stanalbatross requested changes
do walter's change

2022-04-18 23:36 UTC, stanalbatross approved these changes
even though it's in italics

2022-04-18 23:37 UTC, merged