Space Area Handling + Compression Suit Resprite
cmss13-devs/cmss13 pull request #1202
Opened 2022-10-08 11:52 UTC by Geevies

## About The Pull Request

Makes space deal oxy damage unless you have internals or a spacesuit helmet, and makes it deal brute damage unless you have a spacesuit suit on.

Additionally, touched up the compression suit to look a bit nicer.

## Why It's Good For The Game

Makes space more a part of the game, by reintroducing space damage and making the suits to deal with it look nicer.

## Changelog

:cl:
add: Space now deals oxy damage if you don't have internals or a spacesuit helmet on, and deals brute damage if you don't have a spacesuit suit on.
imageadd: Touched up the compression's suit sprites.
/:cl:

2022-10-08 12:02 UTC, stanalbatross requested changes

2022-10-08 12:02 UTC, stanalbatross commented on code/modules/mob/living/carbon/human/life/handle_breath.dm
> +			if(prob(15))
use a `world.time % 3` thing here to prevent le big spamgus

2022-10-08 12:02 UTC, stanalbatross commented on code/modules/mob/living/carbon/human/life/handle_breath.dm
> +			if(prob(15))
same

2022-10-14 00:06 UTC, Agameofscones requested changes
Revert the changes to the compression helmet. Everything else is OK.

2022-11-29 08:19 UTC, morrowwolf commented
Should have staled. Re-open on merge conflict fix and coder willing to review.

2022-11-29 08:19 UTC, closed without merging