Fix snack labeling
cmss13-devs/cmss13 pull request #1212
Opened 2022-10-09 00:45 UTC by DoomLaser9

## About The Pull Request

This allows you to label snacks without losing the prefixes generated from the `made_from_player` variable.

This solves #360.

## Why It's Good For The Game

Bugfix. (plus you can now label burgers that have custom meat names)

## Changelog

:cl: Laser9
fix: Burgers can now be labeled without losing custom meat names.
/:cl:

2022-10-11 16:02 UTC, Geevies requested changes

2022-10-11 16:02 UTC, Geevies commented on code/game/objects/items/tools/misc_tools.dm
> +	if (istype(src, /obj/item/reagent_container/food/snacks))
istype(src) is awful from an OOP perspective, you should make this a thing on `/obj/item/reagent_container/food/snacks/set_name_label(var/new_label)` instead

2022-10-12 04:42 UTC, DoomLaser9 reviewed
Implemented pattern friendlier to OOP

2022-10-13 20:18 UTC, stanalbatross requested changes

2022-10-13 20:18 UTC, stanalbatross commented on code/datums/recipe.dm
> +			if (istype(result_obj, /obj/item/reagent_container/food/snacks))
again this is shit from OOP make a proc that runs on the result obj and has diff behaviour dont use shitty istype checks

2022-10-23 13:28 UTC, stanalbatross approved these changes

2022-10-23 13:28 UTC, merged