Config Example Files Updates
cmss13-devs/cmss13 pull request #1215
Opened 2022-10-09 13:28 UTC by Kiara-Miller

## About The Pull Request

Updating the example config files. None of these changes should have any effect on the actual server, just new private servers, and only if the example config are used.
Fixing 1 bug in the role_whitelist example file, where the All option for the WLs is outdated and does not work as expected.
Minor update to the rank admins sample file, to better reflect the current position of senior mentor.
Added a few extra comments to various example files, to improve readability and documentation of what does what.
Updated the sample MOTD, with more CM relevant resources.

## Why It's Good For The Game

They should make it easier for contribs to learn how to set up a working private instance of the server.  Especially for WLs stuff.

2022-10-09 13:35 UTC, harryob requested changes

2022-10-09 13:35 UTC, harryob commented on config/example/role_whitelist.txt
> +#This document should be placed in Config to have effect. Lines starting with # are comments
```suggestion
# This document should be placed in /config/ to have effect. Lines starting with # are comments
```

2022-10-09 13:35 UTC, harryob commented on config/example/role_whitelist.txt
> +# Elder rank means Clan leader for  Yauja
```suggestion
# Elder means Clan Leader for Yautja
```

2022-10-09 13:35 UTC, harryob commented on config/example/role_whitelist.txt
> +# SEA flag is usually not necessay as it is given though the various staff/mentor ranks for now, but this may chage in the future.
```suggestion
# SEA flag is unnecessary as it is given though the various staff/mentor ranks
```

2022-10-09 13:35 UTC, harryob commented on config/example/role_whitelist.txt
> +# MENTOR FLAGS (this is just the SEA half not the mhelps half)
```suggestion
# MENTOR FLAGS (for access to the SEA role, not MHelps, MentorSay, etc)
```

2022-10-09 13:35 UTC, harryob commented on config/example/admins.txt
> +# This document should be placed in Config folder to have effect.    #
```suggestion
# This document should be placed in the /config/ folder to have effect.    #
```

2022-10-23 13:29 UTC, stanalbatross approved these changes

2022-10-23 13:29 UTC, merged