Lifeboats Simpe Edition
cmss13-devs/cmss13 pull request #1219
Opened 2022-10-09 22:41 UTC by ihatethisengine

## About The Pull Request
Lifeboats without too much feature creep.

Lifeboats are a round-end system used during evacuation on hijack. 'Lifeboats' refer to the two large escape pods located on the aft upper deck of the Almayer.

Once evacuation is called, traditional escape pods become active and lifeboats begin a 10-minute timer countdown. Marines can hold the area around the lifeboats (the "lifeboat lounge") by constructing defenses. Once the timer is complete, the bulkhead doors shut, the docking hatches are blasted off and the lifeboats launch. The Almayer **WILL NOT** automatically self-destruct after their launching.

Queen can prevent lifeboat from launching by interacting with the console inside. 

Not much other changes, no re-hauling of old systems. I (or someone else) may add more features in future PRs, but my goal with this PR is to keep lifeboats as simple as possible because previous PRs have been stuck in MR hell due to feature creep and overhaul of too many systems.

## Why It's Good For The Game

Lifeboats are designed in concept to replace Self-Destruct, allowing Marines to go out in a last stand while defending an area. This is meant to be a properly-defensible last stand that is still able to be broken through by Xenos with enough force.

Overall, lifeboats should improve the hijack game and allow Marines to defend a final objective.

## Changelog

:cl: BlackCrystalic, Ghostsheet, ihatethisengine2, Firartix, nauticall
expansion: Lifeboats have been given functionality and can now be used without staff intervention.
/:cl:

2022-10-11 15:58 UTC, Geevies commented
code looks good, i'll see about getting this testmerged ASAP

2022-10-12 22:19 UTC, morrowwolf commented
Basic functionality looks good, let's get this test merged!

2022-10-13 01:18 UTC, ihatethisengine commented
Added an additional 10 seconds for loading onto the lifeboats after confirming evacuation (in case Marines don't follow the timer), made camera consoles work

2022-10-13 02:32 UTC, morrowwolf requested changes
Both sets of doors should close when it lifts off. Feel free to close the inner doors slightly later than the inner door for coolness.

Check to make sure they work post-round and/or if no one is on them.

2022-10-13 03:57 UTC, ihatethisengine commented
Doors are fixed. 

Lifeboats do work if no one is on them.

Lifeboats don't work post-round for some reason. No idea why and not sure if it matters.

2022-10-13 16:59 UTC, morrowwolf requested changes
Should still launch post round as we discussed.

The lifeboat wall cabinets need sprites while vending. As it stands they disappear.

2022-10-13 20:54 UTC, ihatethisengine commented
All fixed

2022-10-13 20:54 UTC, ihatethisengine commented
All fixed @morrowwolf

2022-10-14 00:04 UTC, Agameofscones approved these changes
mapping is :+1:, sprites are OK, but personally I'd add a small animation (even just a color change on the white circle)

2022-10-14 06:31 UTC, ihatethisengine commented
Added some animation as @Agameofscones requested

2022-10-14 06:52 UTC, AnCopper commented
Is people getting yeeted into space when they stand next to the airlock after the boats leave intended? I saw a queen get sucked into space and deleted due to that.

2022-10-14 06:58 UTC, ihatethisengine commented
@AnCopper yes if they stuck in the umbilical section when lifeboat is leaving it throws them into space. Feature. Unless they weren't in the umbilical section...

2022-10-16 15:01 UTC, Geevies requested changes

2022-10-16 15:01 UTC, Geevies commented on code/modules/shuttle/lifeboats.dm
> +	. = ..()
```suggestion
	return ..()
```

2022-10-16 15:02 UTC, Geevies commented
code looks good other than these nitpicks, great job

2022-10-16 16:33 UTC, Geevies approved these changes
code

2022-10-16 23:07 UTC, ihatethisengine commented
MapDiffBot2 broke for no reason so I guess just ignore it

2022-10-18 22:04 UTC, morrowwolf requested changes

2022-10-18 22:04 UTC, morrowwolf commented on code/game/gamemodes/cm_self_destruct.dm
> +			var/obj/docking_port/mobile/lifeboat/lifeboat = SSshuttle.getShuttle("lifeboat1")
This needs to check both lifeboats.

2022-10-19 22:29 UTC, merged