STUI Perm changes
cmss13-devs/cmss13 pull request #1221
Opened 2022-10-10 01:12 UTC by realforest2001

## About The Pull Request

Changes perms for STUI logs
## Why It's Good For The Game
Lets mods see things they need

## Changelog

:cl:
tweak: Mods can see things on STUI now.
add: Added more things
del: Removed old things
qol: made something easier to use
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

2022-10-10 08:27 UTC, stanalbatross approved these changes

2022-10-11 15:47 UTC, Geevies requested changes

2022-10-11 15:47 UTC, Geevies commented on code/modules/admin/STUI.dm
>  		.["tabs"] += STUI_TEXT_ADMIN
i reckon it'd be better to rename these items to make them less confusing for future coders instead of just changing the perms

2022-10-21 15:53 UTC, stanalbatross approved these changes

2022-10-21 15:53 UTC, merged