Fixing Hedgehog abilities hurting dead, and related
cmss13-devs/cmss13 pull request #1233
Opened 2022-10-11 20:11 UTC by Kiara-Miller

## About The Pull Request
Should fix the issues in https://github.com/cmss13-devs/cmss13/issues/358
Base Runner and Hedgehog abilities have had some changes on their underlying code, that may impact how they work in edge cases.
Introduces a new bullet flag, AMMO_XENO_BONE in order to properly facilitate the fixes.
Fixes Xeno bone based abilities being able to hurt corpses if used while standing on them.
Fixes Xeno bone based abilities being able to hurt corpses if used on nearby vertical corpses.
Fixes Xeno bone based abilities from form being able to hurt caps.
Fixes shrapnel bypassing some checks, if created on top of a mob. Notably these checks will now happen when the 'shrapnel' is caused by Xeno abilities too. There may a small performance hit, this needs testing.
No significant balance impact is expected, tho in a few cases the above abilities may deal a bit less damage due to the bug fixes.

## Why It's Good For The Game
Bugfixes and standardizes bone based abilities into their own thing when it comes to bullet flags as they don't neatly fit into  either acid or toxic.

## Changelog

:cl:ito726
fix: Base Runner and Hedgehog Ravager form being able to hurt corpses and caps.
/:cl:

2022-10-11 23:57 UTC, Carnage068 commented
salt pr. just remove hedgehog from the fucking game at this point lmao

2022-10-12 00:31 UTC, usnpeepoo commented
> salt pr. just remove hedgehog from the fucking game at this point lmao. if you want to nerf it that's fine but don't fucking lie about it being a direct nerf, come on.

Hey, just so you know you're meant to leave feedback in the CM discord related to this PR. No longer allowed to leave feedback in the GitHub page/PR page.

2022-10-16 15:28 UTC, Geevies requested changes

2022-10-16 15:28 UTC, Geevies commented on code/modules/projectiles/ammo_datums.dm
> +		if(C.status_flags & XENO_HOST && HAS_TRAIT(C, TRAIT_NESTED) || C.stat == DEAD)
```suggestion
		if((HAS_FLAG(C.status_flags, XENO_HOST) && HAS_TRAIT(C, TRAIT_NESTED)) || C.stat == DEAD)
```

2022-10-16 15:28 UTC, Geevies commented on code/modules/projectiles/ammo_datums.dm
> +        if(C.status_flags & XENO_HOST && HAS_TRAIT(C, TRAIT_NESTED) || C.stat == DEAD)
```suggestion
        if((HAS_FLAG(C.status_flags, XENO_HOST) && HAS_TRAIT(C, TRAIT_NESTED)) || C.stat == DEAD)
```

2022-10-22 12:47 UTC, Geevies approved these changes

2022-10-22 13:23 UTC, merged