Yautja Anti-Vehicle HPCs
cmss13-devs/cmss13 pull request #124
Opened 2022-04-23 14:51 UTC by Geevies

## About The Pull Request

Gives the Yautja HPC the same anti-vehicle effect as the single use AT rockets.

## Why It's Good For The Game

Currently, preds have no real way to deal with vehicles that keep running them over. This'll help alleviate that.

## Changelog

:cl:
expansion: Yautja HPCs now have anti-vehicle effects.
/:cl:

2022-04-23 14:54 UTC, Git-Nivrak commented
based

2022-04-24 08:37 UTC, Diegoflores31 commented
yeah also give them a button that instantly kills the CO and ends the round instantly

2022-04-24 08:43 UTC, stanalbatross reviewed
you should also add a damage multiplier to it vs vehicles

2022-04-24 11:43 UTC, stanalbatross requested changes

2022-04-24 11:43 UTC, stanalbatross commented on code/modules/projectiles/ammo_datums.dm
> +		var/obj/vehicle/multitile/M = O
more detailed var name needed here

2022-04-24 11:43 UTC, stanalbatross commented on code/modules/projectiles/ammo_datums.dm
> +		var/turf/T = get_turf(M.loc)
why do you need this line when it isn't used

2022-04-24 14:01 UTC, stanalbatross approved these changes

2022-04-25 14:32 UTC, merged