Ambientocclusion
cmss13-devs/cmss13 pull request #1249
Opened 2022-10-14 04:39 UTC by harryob

## About The Pull Request

adds a faint dropshadow around The World, our lighting engine looks less obviously bad + is stored as a preference so soul enjoyers can have their original version. same ambient occlusion as used on TG 😨

## Why It's Good For The Game

improves the aesthetics with a new look that makes full bright less intense and partially darkened rooms much nicer

https://user-images.githubusercontent.com/55142896/195763651-df0dd022-f6e0-4d3f-9fe2-5d07f08e4360.mp4

https://user-images.githubusercontent.com/55142896/195763679-21c64508-4131-4773-87a6-5623d56ba6af.mp4

## Changelog

:cl:
add: Ambient occlusion is now an (enabled by default) preference.
/:cl:

2022-10-14 12:45 UTC, stanalbatross requested changes

2022-10-14 12:45 UTC, stanalbatross commented on code/_onclick/hud/rendering/plane_master.dm
> +	if(istype(mymob) && mymob.client.prefs.ambientocclusion)
sanity checks for client please

2022-10-14 12:45 UTC, stanalbatross commented on code/game/objects/items/explosives/plastic.dm
> +	if(istype(target, /obj/structure/ladder) || istype(target, /obj/item) || istype(target, /turf/open) || istype(target, /obj/structure/barricade) || isanimal(target))
?

2022-10-14 12:45 UTC, stanalbatross commented on code/modules/client/preferences.dm
> +				if("ambientocclusion")
consider a toggle verb in prefs too

2022-10-14 12:45 UTC, stanalbatross commented on code/modules/client/preferences_savefile.dm
> +	ambientocclusion	= sanitize_integer(ambientocclusion, 0, 1, initial(ambientocclusion))
FALSE/TRUE please

2022-10-15 04:19 UTC, Wintermote commented
Any performance impact/testing on performance?

2022-10-15 07:14 UTC, harryob commented
> Any performance impact/testing on performance?

it shouldn't, due to the filter being applied to a planemaster. if someone wishes to testmerge this, i can make a branch that doesn't mess with prefs and just stores the preference on the client temporarily

2022-10-16 15:20 UTC, Geevies requested changes

2022-10-16 15:20 UTC, Geevies commented on code/_onclick/hud/rendering/plane_master.dm
> +	if(istype(mymob) && mymob?.client.prefs.toggle_prefs & TOGGLE_AMBIENT_OCCLUSION)
confirm that client and prefs exists

2022-10-16 16:17 UTC, harryob commented on code/_onclick/hud/rendering/plane_master.dm
> +	if(istype(mymob) && mymob?.client.prefs.toggle_prefs & TOGGLE_AMBIENT_OCCLUSION)
i love question marks

2022-10-16 16:35 UTC, merged