Toxic sent
cmss13-devs/cmss13 pull request #1255
Opened 2022-10-14 17:47 UTC by aceroyuno

## About The Pull Request

(I accidentally did some unintended merging on the wrong branch and had to fix it)

This pull request is to add the new Sentinel strain Toxic Sentinel. At it's core it slashes enemies to deal toxic damage at the cost of plasma, it uses utility abilities to aid in this endeavor.
Further elaborated on in here https://docs.google.com/document/d/1Ez3sAHZ3RhoPE3K-Dnuq6pQTk3U8p_Rxm8qj7TqEeHs/edit?usp=sharing.
and on the design doc to be added to the repo https://github.com/cmss13-devs/cmss13-design-docs/pull/19

## Why It's Good For The Game

There are a lot of reasons that this is good for the game, adds a new T1 strain for a caste that does not have any.
As of right now, most marines carry ina, bica, and kelo auto injectors. This provides an indirect counter to that metaplay.
It allows xenos to have another type of damage source.

## Changelog

:cl:
qol: Xenos can now purchase the "Toxic" strain as a Sentinel
add: Added new strain for Sentinel "Toxic"
add: Added Sentinel blinding spit ability (Toxic Sentinel) - A ranged spit attack that causes a little over a second of blindness. It has a range of 5 tiles. Costs 40 plasma.
add: Added Sentinel sprint ability (Toxic Sentinel) - A movement speed stim that lasts 30 seconds and costs 40 plasma.
add: Added Sentinel toxic slash togglable ability (Toxic Sentinel) - A togglable passive that causes each slash to deal 10 toxic damage per slash. It costs 30 plasma to deal the 10 toxic damage.
balance: Sentinel gains 60 max health when becoming Toxic Sentinel
/:cl:

2022-10-24 13:01 UTC, carlarctg reviewed
i think the name is pretty bad. 'toxic?' if i may suggest it, you could rename it to 'scorpion' or 'scarab' or similar, reflavor the tox attack to be a tail swing, and maybe even give the regular tail stab tox too


balance -- 
i kind of like how this deals tox dmg, but imo it should come from an injected chemical? it'd just make sense. dont stress about it though  there's also the problem that tox dmg randomly stuns you from the vomit, which is an issue but a fixable one and somewhat out of scope

2022-10-24 21:41 UTC, aceroyuno commented on code/modules/mob/living/carbon/xenomorph/abilities/sentinel/sentinel_abilities.dm
> +	xeno_cooldown = 60
changed the format to seconds

2022-10-24 21:41 UTC, aceroyuno commented on code/modules/mob/living/carbon/xenomorph/abilities/sentinel/sentinel_abilities.dm
> +/datum/action/xeno_action/activable/blinding_spit
put them in order

2022-10-24 21:42 UTC, aceroyuno commented on code/modules/mob/living/carbon/xenomorph/abilities/sentinel/sentinel_macros.dm
> +/datum/action/xeno_action/verb/verb_blinding_spit()
put them in order

2022-10-24 21:50 UTC, aceroyuno commented on code/modules/projectiles/ammo_datums.dm
> +			return
this is supposed to be something that hits the player in the eyes, and is on the skin of the player. It would not make much sense as a chemical.

2022-10-26 21:01 UTC, aceroyuno commented
> i think the name is pretty bad. 'toxic?' if i may suggest it, you could rename it to 'scorpion' or 'scarab' or similar, reflavor the tox attack to be a tail swing, and maybe even give the regular tail stab tox too

Turns out the tail stab is already set up for toxic, I use behavior_delegate.melee_attack_additional_effects_target() for applying toxic, so it's all good to go on that front.

2022-10-28 17:25 UTC, morrowwolf requested changes
Sprites

2022-12-09 00:28 UTC, closed without merging