build mode 2
cmss13-devs/cmss13 pull request #1262
Opened 2022-10-16 02:26 UTC by harryob

## About The Pull Request

admin bus is now 10x as effective (in build mode)

https://cdn.discordapp.com/attachments/539898120431992862/1030974347046822028/CleanShot_2022-10-15_at_14.48.48.mp4 https://cdn.discordapp.com/attachments/539898120431992862/1030989280539066459/CleanShot_2022-10-16_at_00.40.04.mp4

## Why It's Good For The Game

the old build mode was horribly coded on the backend and was also ugly. this one is better (from tg with various authors throughout the years)

## Changelog

:cl:
admin: build mode 2 - a bunch of new buttons (and better existing buttons)
/:cl:

2022-10-16 02:27 UTC, harryob commented
idb2 fail making me look like a shitcoder

2022-10-16 02:33 UTC, harryob commented
<img width="729" alt="CleanShot 2022-10-16 at 03 32 56@2x" src="https://user-images.githubusercontent.com/55142896/196015125-ecc7c26b-7d41-4ac6-98bc-f8cdae3bdd89.png">
huh

2022-10-16 02:40 UTC, carlarctg commented
pretty suspicious to add in build mode when you wont even benefit from it as a nondev.....

2022-10-16 02:43 UTC, harryob commented
> pretty suspicious to add in build mode when you wont even benefit from it as a nondev.....

wait till he finds out the Wiki Maintainer is an admin

2022-10-16 12:14 UTC, nauticall approved these changes
sprites are fine! it's just admin tools anyway

2022-10-23 13:07 UTC, stanalbatross requested changes

2022-10-23 13:07 UTC, stanalbatross commented on code/modules/buildmode/submodes/variable_edit.dm
> +	var/type = tgui_input_list(usr,"Select variable type:" ,"Type", list("text","number","mob-reference","obj-reference","turf-reference"))
definesss

2022-10-23 13:07 UTC, stanalbatross commented on code/modules/buildmode/submodes/delete.dm
> +					for(var/Obj in world)
no caps in var names

2022-10-23 13:07 UTC, stanalbatross commented on code/modules/buildmode/submodes/delete.dm
> +					for(var/atom/Obj in world)
same

2022-10-23 13:07 UTC, stanalbatross commented on code/modules/buildmode/submodes/delete.dm
> +			if(tgui_alert(usr,"Second confirmation required. Delete?",,list("Yes","No")) != "Yes")
null args 💢

2022-10-23 13:07 UTC, stanalbatross commented on code/modules/buildmode/submodes/delete.dm
> +			var/action_type = tgui_alert(usr,"Strict type ([deleting.type]) or type and all subtypes?",,list("Strict type","Type and subtypes","Cancel"))
null args

2022-10-23 13:07 UTC, stanalbatross commented on code/modules/buildmode/submodes/boom.dm
> +	NOTE: Using the \"Launch Supplypod\" verb allows you to do this in an IC way (i.e., making a cruise missile come down from the sky and explode wherever you click!)"
isn't the actual name of the verb different

2022-10-23 13:07 UTC, stanalbatross commented on code/modules/buildmode/buttons.dm
> +	return 1
TRUE or defines, no magic numbers

2022-10-23 13:07 UTC, stanalbatross commented on code/modules/buildmode/buttons.dm
> +	return 1
same

2022-10-23 13:07 UTC, stanalbatross commented on code/modules/buildmode/buttons.dm
> +	return 1
same

2022-10-23 13:07 UTC, stanalbatross commented on code/modules/buildmode/buttons.dm
> +	return 1
same

2022-10-23 13:07 UTC, stanalbatross commented on code/modules/buildmode/buildmode.dm
> +	return 1
💢

2022-10-23 13:15 UTC, stanalbatross requested changes
BUILD BASIC
- make lmb + ctrl place a framed r-window not directional
- dir changing does not work with airlocks
- downgrading rwalls just deletes them
- you cannot upgrade rwalls to heavy rwalls
KABOOM
- help tip needs to be "right click on mode"
FILL MODE
- should be able to pick object type via right clicking ic object like with build advanced

2022-10-25 08:01 UTC, stanalbatross approved these changes

2022-10-25 08:01 UTC, merged