Changes to indestructible. No more immovable indestructibles
cmss13-devs/cmss13 pull request #1271
Opened 2022-10-16 20:33 UTC by Nanotrasen-Spy

## About The Pull Request

Makes it so indestructible objects can now be thrown around by explosions even without being deleted. Also a few changes so heads are indestructible so they don't get deleted when gibbed or by explosions (hooray RP hopeless synths and hooray being able to ID who inted into the center of the OB).

## Why It's Good For The Game

Makes indestructible items more "believable" instead of them being sitting fat rocks surviving multiple OB hits without moving an inch & makes it so synths have a little more to it if they get gibbed or exploded since most of the time when they lose their heads theyre for X reasons theyre deleted.

## Changelog

:cl: Nanotrasen-Spy
code: small changes to gibbing and limb objects, heads will no longer be deleted by gibbing (hooray synths)
code: Refactored explosion deletion code. Indestructible objects may also now be tossed around by explosions without being deleted.
/:cl:

2022-10-16 20:49 UTC, Watermelon914 commented
improve your title name, it gives barely any information right now

2022-10-17 17:13 UTC, Geevies requested changes

2022-10-17 17:13 UTC, Geevies commented on code/game/objects/items.dm
> +			explosion_throw(severity, explosion_direction)
since this is under every item of the switch, you can just put this above the switch so it always fires

2022-10-17 17:57 UTC, Watermelon914 commented
title is still not detailed enough. what is 'Changes to indestructible objects' supposed to mean? What have you done with indestructible objects? please include details

2022-10-26 13:53 UTC, fira commented
Walter's right, detail both changes separate on two lines in changelog or something

Been wondering about gib decap forever, but don't think it'll cause issues (maybe synths..)

2022-11-29 08:20 UTC, morrowwolf commented
Should have staled out. Re-open when merge conflicts are fixed and you have a coder to review it.

2022-11-29 08:20 UTC, closed without merging