Spitter Weakrefs
cmss13-devs/cmss13 pull request #1276
Opened 2022-10-17 00:08 UTC by Misttyy

## About The Pull Request

Changes Spitter Hardrefs to Weakrefs

## Why It's Good For The Game

Cleaner code, less HardDels, less HardRefs. Helps me learn refactoring on a basic scale

## Changelog

:cl: Mistfrag
refactor: Spitters no longer use HardRefs for their abilities, now use WeakRefs.
:cl:

2022-10-18 13:00 UTC, stanalbatross commented on code/modules/mob/living/carbon/xenomorph/castes/Spitter.dm
> +	dot_cooldown_atoms += WEAKREF (A)
```suggestion
	dot_cooldown_atoms += WEAKREF(A)
```

2022-10-18 13:02 UTC, stanalbatross reviewed
`dot_cooldown_atoms -= A`

should this not be weakref?

2022-10-22 15:40 UTC, Misttyy commented
> `dot_cooldown_atoms -= A`
> 
> 
> 
> should this not be weakref?

Will fix this tomorrow when I'm home.

2022-10-25 00:14 UTC, Misttyy commented
@stanalbatross Added

2022-10-25 00:17 UTC, Misttyy commented
a

2022-10-26 18:11 UTC, morrowwolf requested changes

2022-10-26 18:11 UTC, morrowwolf commented on code/modules/mob/living/carbon/xenomorph/castes/Spitter.dm
> +		return
At a quick glance I assume this return is meant to be indented so as it be in the if()

2022-11-09 22:06 UTC, harryob approved these changes

2022-11-11 11:36 UTC, harryob requested changes

2022-11-26 10:34 UTC, harryob approved these changes

2022-11-26 10:34 UTC, merged