Fixes Ledges Dropping Bodies
cmss13-devs/cmss13 pull request #1278
Opened 2022-10-17 00:36 UTC by Misttyy

## About The Pull Request

Changes it so you can fireman carry and pull bodies over ledges, windows and etc.

## Why It's Good For The Game

This beforehand was an unintentional bug wherein bodies were dropped going over windows due to how the code was written. This fixes that and removes a bit of jank from the game. Code done by Geeves originally, updated by Misty.

## Changelog
:cl: Geevies, Misty
add: Makes it so you can fireman carry/drag bodies over ledges.
refactor: Refactored code in living mobs and structures to fix a bug wherein people couldn't carry over ledges or windows.
/:cl:

2022-10-22 15:40 UTC, Misttyy commented
Will add missing line tomorrow when I'm home from Seattle.

2022-11-01 09:04 UTC, stanalbatross requested changes

2022-11-01 09:04 UTC, stanalbatross commented on code/game/objects/structures.dm
> +	for(var/obj/item/grab/G in list(user.l_hand, user.r_hand))
varname

2022-11-22 20:10 UTC, fira approved these changes

2022-11-22 20:13 UTC, morrowwolf requested changes

2022-11-22 20:13 UTC, morrowwolf commented on code/game/objects/structures.dm
> +	user.forceMove(TT)
I may be missing something but why is this forceMove necessary? It seems like it's doubled with the one above.

2022-11-26 07:04 UTC, Misttyy commented
All fixed, tested on local and works.

2022-11-26 08:23 UTC, ThePiachu requested changes
This works inconsistently:
- If you are crossing a ledge with a body, sometimes it drags the body onto your tile, sometimes it leaves be body behind. Maybe it's tied to directions or something?
- Dragging a body with you over a window frame doesn't drag the body to the window frame
- When you successfully drag a body over the ledge it moves 2 spaces, it should probably move only 1 space and with the next move you should be able to drag it over the ledge
- If you start moving over the ledge by holding the button down you will get moved 2 spaces which is jarring and probably not an intended behaviour

2022-12-11 00:31 UTC, closed without merging