moves /obj deconstructing into deconstruct
cmss13-devs/cmss13 pull request #1285
Opened 2022-10-18 01:30 UTC by harryob

## About The Pull Request

things should more uniformly use deconstruct() over destroy() (lowercase), destroy_airlock, destroy_window... etc.

## Why It's Good For The Game

there was confusion on how to get rid of an object. it's 2am as i do this and i've probably fucked up the logic in a bunch of places, but

## Changelog

:cl:
refactor: the code for deconstruction is now (somewhat) neater
/:cl:

2022-10-18 01:31 UTC, harryob commented
remembered i need to do all this for ex_act, too

2022-10-19 16:08 UTC, Watermelon914 requested changes

2022-10-19 16:08 UTC, Watermelon914 commented on code/game/objects/effects/decals/misc.dm
> +	if(disassembled)
should be negated

2022-10-19 16:08 UTC, Watermelon914 commented on code/game/objects/effects/decals/misc.dm
> +	. = ..()
always do `return ..()` at the end of a proc

2022-10-19 16:08 UTC, Watermelon914 commented on code/game/objects/structures/crates_lockers/largecrate.dm
> +	. = ..()
same as above here

2022-10-19 16:08 UTC, Watermelon914 commented on code/game/objects/structures/displaycase.dm
> +	. = ..()
same thing here

2022-10-19 16:08 UTC, Watermelon914 commented on code/game/objects/structures/displaycase.dm
> +/obj/structure/displaycase/deconstruct(disassemble = TRUE)
should be disassembled and not disassemble

2022-10-19 16:08 UTC, Watermelon914 commented on code/game/objects/structures/fence.dm
> +	. = ..()
same thing here

2022-10-19 16:08 UTC, Watermelon914 commented on code/game/objects/structures/girders.dm
> +	. = ..()
same thing here

2022-10-19 16:08 UTC, Watermelon914 commented on code/game/objects/structures/inflatable.dm
> +	. = ..()
same thing here

2022-10-19 16:08 UTC, Watermelon914 commented on code/game/objects/structures/lattice.dm
> +	. = ..()
same thing here, do this for the rest of them in your PR since I don't want to list them all out

2022-10-26 14:44 UTC, fira commented on code/game/atoms.dm
> +		CHECK_TICK
:waaaaa: why CHECK_TICK ? does this even pass static checking ??

2022-10-26 14:44 UTC, fira commented on code/game/machinery/telecomms/machine_interactions.dm
> +		F.forceMove(src.loc)
you can just pass the location as first arg in the new above

2022-11-05 12:08 UTC, fira commented
Waiting on rereview by Walter, fine by me

2022-11-05 12:09 UTC, fira approved these changes

2022-11-19 20:57 UTC, merged