Pred bug fix no.2
cmss13-devs/cmss13 pull request #1287
Opened 2022-10-18 14:56 UTC by Joelampost

## About The Pull Request
Resolves: https://github.com/cmss13-devs/cmss13/issues/106
Resolves: https://github.com/cmss13-devs/cmss13/issues/61

## Why It's Good For The Game
Because fix

## Changelog

:cl: Joe lampost
fix: Stops duplication of smart discs 
fix:Stops the skinning of synths 
/:cl:

2022-10-19 07:11 UTC, harryob requested changes

2022-10-22 21:53 UTC, Watermelon914 commented on code/game/objects/structures/tables_racks.dm
> +		var/obj/item/explosive/grenade/I = W
this variable name is not detailed whatsoever

2022-10-23 17:39 UTC, Diegoflores31 commented
i think it would be better to rather say that the synthethic is not worth it or something .. i really doubt a pred cant cut thru the synth skin .

2022-10-23 23:43 UTC, Joelampost commented
> i think it would be better to rather say that the synthethic is not worth it or something .. i really doubt a pred cant cut thru the synth skin .

tools break

2022-10-28 12:12 UTC, stanalbatross requested changes

2022-10-28 12:12 UTC, stanalbatross commented on code/game/objects/structures/tables_racks.dm
> +		return
```suggestion
			return
```
needs an extra indent here or it will ALWAYS return

2022-10-28 12:12 UTC, stanalbatross commented on code/modules/cm_preds/yaut_procs.dm
> +		to_chat(src, SPAN_WARNING("You would break your tools if you did this."))
```suggestion
		to_chat(src, SPAN_WARNING("You would break your tools if you did this!"))
```

2022-10-29 22:53 UTC, stanalbatross approved these changes

2022-10-29 22:54 UTC, merged