Weather Refactor + Big Red Weather
cmss13-devs/cmss13 pull request #1289
Opened 2022-10-19 17:13 UTC by Geevies

## About The Pull Request

Refactors the weather system to no longer rely on effects to deal damage or have weather messages, also improves the ambience code so hopefully it doesn't blast itself to death. All-in-all this should lead to less lag when weather is used on maps.

Additionally, added unique weather events to Big Red, which have a fairly low chance of triggering every twenty minutes.

## Why It's Good For The Game

Weather is cool, and spice up the gameplay loop with dynamic effects. Weather being laggy sucks.

## Changelog

:cl:
add: Added unique weather events to Big Red / Solaris Ridge.
refactor: Refactored weather code to hopefully be less laggy.
/:cl:

2022-10-29 09:39 UTC, fira commented
I don't see any particular issue but this shoudl probably be TM'ed on the relevant maps

2022-10-29 09:41 UTC, Geevies commented
> I don't see any particular issue but this shoudl probably be TM'ed on the relevant maps

this has been TM'd a couple times on both BR and LV with no issues, but I agree we should probably try it out on the new server as well

2022-10-31 12:54 UTC, fira commented
Oh, well that should be all good if it's already been tested on old

2022-11-01 13:30 UTC, stanalbatross requested changes

2022-11-01 13:30 UTC, stanalbatross commented on code/controllers/subsystem/weather.dm
> +		last_event_check_time = world.time
something something COOLDOWN_DECLARE

2022-11-01 13:30 UTC, stanalbatross commented on code/datums/weather/weather_event.dm
> +		for(var/mob/M as anything in GLOB.mob_list)
varname

2022-11-01 18:53 UTC, merged