Fixed resin spikes deleting on evolution
cmss13-devs/cmss13 pull request #1292
Opened 2022-10-19 22:39 UTC by carlarctg

## About The Pull Request

Title

Instead of deleting built_structures on the old xeno, evolution now simply transfers over the list to the new xeno

This means a drone could put 15 spikes in and deevo into a runner, resulting in THE ENTIRE HIVE being able to place resin spikes. this is obviously incredibly overpowered aside from the fact that it's a non-issue

## Why It's Good For The Game

its a bugfix

## Changelog

:cl:
fix: Fixed resin spikes deleting on evolution
/:cl:

2022-10-19 22:42 UTC, carlarctg commented
wha!!!

2022-10-19 23:31 UTC, ihatethisengine commented
But what if let's say hivelord builds available reflective walls and acid pillars and then de-evolves?

2022-10-20 15:00 UTC, carlarctg commented
then they wasted a t2 slot and 500 evo points to make two situational buildings?

2022-10-20 19:29 UTC, Geevies commented on code/modules/mob/living/carbon/xenomorph/Evolution.dm
> +		new_xeno.built_structures += built_structures[i]
can't you just do `built_structures.Copy()`? also QDEL_NULL_LIST it once you're done

2022-10-27 19:50 UTC, Geevies requested changes

2022-10-27 19:50 UTC, Geevies commented on code/modules/mob/living/carbon/xenomorph/Evolution.dm
> +		new_xeno.built_structures += built_structures[i]
when i said 'can't you just do' i meant remove this code and do the copy instead

2022-10-27 19:50 UTC, Geevies commented on code/modules/mob/living/carbon/xenomorph/Evolution.dm
> +		QDEL_NULL_LIST(L)
are you sure that this is right, because in theory this deletes the spikes. did you test it?

2022-10-27 19:50 UTC, Geevies commented on code/modules/mob/living/carbon/xenomorph/Xenomorph.dm
> -	built_structures = null
it should still null out

2022-10-28 17:42 UTC, merged