Adds New Varadero with minimal fishing code
cmss13-devs/cmss13 pull request #1297
Opened 2022-10-20 00:11 UTC by Agameofscones

## About The Pull Request

New map, fishing as a minimal system for building off of (no solid content yet, leaving it partially drafted)

## Why It's Good For The Game

New map, if I don't PR this I never will because fishing is way to large of a project even for a non-gameplay mechanic.

## Changelog

:cl: Triiodine
add: Added New Varadero, a re-detailed, but otherwise almost entirely unchanged Ice Colony LZ2 underground with some modern amenities as a standalone map.
code: Added fishing backend by Geeves. Not in normal gameplay, admin spawn only.
/:cl:

2022-10-20 04:53 UTC, AnCopper commented
Does this place only have one LZ?

2022-10-20 09:55 UTC, Unknownity commented
all the resin nodes need to be replaced with the setup/distress/xeno_weed_node spawners instead so the weeds don't spawn in extended for example

2022-10-20 19:43 UTC, morrowwolf commented
The areas around the LZ should also have the initial weed protection. It's a bit too close as it stands.

2022-10-20 21:10 UTC, morrowwolf commented
![image](https://user-images.githubusercontent.com/8919187/197058828-52121796-847c-4f71-a368-530adae04c8c.png)

2022-10-21 16:55 UTC, Segrain commented on maps/new_varadero.json
> +    }
```suggestion
    },
    "gamemodes": [
        "Distress Signal",
        "Hunter Games",
        "Hive Wars",
        "Faction Clash",
        "Infection"
    ]
```
![image](https://user-images.githubusercontent.com/4447185/197248859-b28e4273-589a-4f87-9233-926cb2650c18.png)

2022-10-22 09:02 UTC, nauticall requested changes
![image](https://user-images.githubusercontent.com/55491249/197330064-9ec0363d-5a68-4b67-9e23-cfead267e247.png)
![image](https://user-images.githubusercontent.com/55491249/197330362-b2afeee9-d4c6-4634-b292-1c8bb4e10aa4.png)

Inconsistent door floorings in security (blue to red, and green to yellow). Most doors have plating under them in this map so maybe put plating under the rest of the doors as well. Or do what other SS13 maps do and put normal flooring under them all instead, but that needs a bit more change.

![image](https://user-images.githubusercontent.com/55491249/197330461-5b61ccf7-767a-4af0-a029-4242bc0804ca.png)
Yellow: These are normal reinforced walls compared to the indestructible ones that line the LZ. Xenos can break through these. Don't know if intentional or not.
Orange: These are also easily breakable and give xenos a point of entry into the LZ via the water. Again, no idea if intentional or not.

![image](https://user-images.githubusercontent.com/55491249/197330620-917b6c46-b627-43d9-8992-52dc8b17d172.png)
Maybe furnish these rooms? They look a bit tacked-on without any furniture inside of them.

![image](https://user-images.githubusercontent.com/55491249/197330729-b9f4865d-c916-4cb4-ba5a-d0fc459df4cf.png)
Orange: Add a platform here for height consistency.
Yellow: Maybe put some sort of incinerator or recycler (like on the Almayer) connected to a conveyor here, SS13-style? Looks like garbage here would just pile up otherwise.

![image](https://user-images.githubusercontent.com/55491249/197330841-8ebf1be7-15d8-41da-9037-709952bbf32b.png)
Pretty, but admittedly a bit funky to grow dirty organic plants in the same room as sensitive electronic equipment. Maybe make the area a bit more sterile.

![image](https://user-images.githubusercontent.com/55491249/197330889-0a84ab28-35d0-4f4b-b566-97b7bbedcdb5.png)
Earmuffs in this area, maybe, for Responsible Shooting:tm:?

Think that's it (for now >:) ). Great map! Love the detail.

2022-10-23 00:58 UTC, Wintermote commented
Played once so far as IO, the compactness is very nice. Felt like there was a LOT of intel, but that may simply be due to the compact nature of the map. It definitely felt good pushing up and being able to grab a crapton of intel, but at the same time the compactness makes it hard to grab intel by going alone anywhere, so it probably balances itself out overall.

It's nice to see CM getting more maps

2022-11-27 13:04 UTC, Nanu308 requested changes

2022-11-27 14:29 UTC, Nanu308 approved these changes
lgtm map wise

2022-11-27 14:56 UTC, Nanu308 commented
Sprites approved by @monkeysfist101

2022-11-27 14:56 UTC, merged