Fixes Toxin damage trait doing nothing
cmss13-devs/cmss13 pull request #1298
Opened 2022-10-20 04:34 UTC by Diegoflores31

## About The Pull Request

Research warcrimes did an oppsie and Toxin damage was only being applied if you were wearing a mask ( yeah the one that SHOULD protect you btw)

## Why It's Good For The Game

bug bad .
PROOF that it was intended the way i am fixin : 
![image](https://user-images.githubusercontent.com/47069269/196857206-b973b8ac-bfa5-403e-823e-33d2fa1d31b6.png)

## Changelog

:cl:
fix: Toxic trait now applies Toxin damage on touch as intended
/:cl:

2022-10-20 19:22 UTC, Geevies requested changes

2022-10-20 19:22 UTC, Geevies commented on code/modules/reagents/chemistry_properties/prop_negative.dm
>  		return
```suggestion
	if(C.wear_mask) // Wearing a mask
		return
	C.apply_damage(potency, TOX)  // applies potency toxin damage
```

2022-10-20 22:55 UTC, Diegoflores31 commented on code/modules/reagents/chemistry_properties/prop_negative.dm
>  		return
Why?

2022-10-21 15:19 UTC, Geevies approved these changes

2022-10-22 11:54 UTC, stanalbatross approved these changes

2022-10-22 11:54 UTC, merged