Acid tower now hits enemies / xenos on top of it.
cmss13-devs/cmss13 pull request #1307
Opened 2022-10-22 03:38 UTC by Diegoflores31

## About The Pull Request

standing on top of acid pillars made the sound but the spit tracking was bugged . this PR fixes it

## Why It's Good For The Game

bug bad 

## Changelog

:cl:
fix: Acid Pillar now properly spits acid to Enemies or xenos on fire that are located on top of it .
/:cl:

2022-10-22 15:24 UTC, stanalbatross requested changes

2022-10-22 15:24 UTC, stanalbatross commented on code/modules/cm_aliens/XenoStructures.dm
> +	if(!info.distance_travelled == 0 && info.current_turf == info.target_turf )
```
	if(!value == 0)
```


this line makes absolutely zero sense please rewrite the check so it can be _understood_

2022-10-27 21:10 UTC, stanalbatross requested changes

2022-10-27 21:10 UTC, stanalbatross commented on code/modules/cm_aliens/XenoStructures.dm
> +	if(info.distance_travelled > 0 && info.current_turf == info.target_turf )
```suggestion
	if(info.distance_travelled && info.current_turf == info.target_turf )
```
if(thing > 0) is the same as checking if(thing)

2022-11-17 23:59 UTC, fira approved these changes

2022-11-19 13:25 UTC, merged