Ship Marines, an MP Aesthetic Overhaul
cmss13-devs/cmss13 pull request #1319
Opened 2022-10-23 19:16 UTC by Geevies

## About The Pull Request

Changes up the MP aesthetic to be more akin to Vietnam era MPs, via sprite and role name changes. MPs have been renamed to Ship Marines, and the CMP has been renamed to the Master-at-Arms. The 'MP' department has been reflavoured into the 'Security' department (up for discussion). Command roles no longer require Security hours (up for discussion). SMs are PFCs when they have less than 10 hours in the role, but become Cpls afterwards.

MP Cadets were removed in favour of folding them into SMs having ranks based on playtime, giving Ship Marine mains a way to see if a new SM is playing and show them the ropes.

The Warden has been removed as individual SMs can handle these duties on a case-by-case basis, or the MAT can assist.

A ship marine is just another boot, not a robot, a fellow marine making sure pandemonium doesn't break out on the ship via enforcing marine law. Their duty is to defend and keep order on the ship and the landing zones.

Ship Marine:
![image](https://user-images.githubusercontent.com/22774890/197408991-e59db1c8-c8e0-45a1-be3f-248a263726d2.png)

Master-at-Arms:
![image](https://user-images.githubusercontent.com/22774890/197409000-3dfce816-cb2a-4434-a31f-6a39a9ee7688.png)

## Why It's Good For The Game

There are various things we'd like to change about MPs to strengthen the bond between them and normal marines. Changing up the aesthetics is a good first step, with effective ML changes to follow, we can make the department a great part of the corps, which contributes both to keeping chaos on the ship to a minimum, and the security of the operation.

## Changelog

:cl: Geeves, Frans_Feiffer, Triiodine
add: Overhauled MP aesthetics, replaced MPs with Ship Marines, replaced CMPs with a Master-at-Arms.
del: Removed Wardens and MP cadets.
del: Command roles no longer need security/MP hours.
/:cl:

2022-10-23 20:13 UTC, carlarctg commented
id recommend going ahead and making the brig closer to other parts of the ship to be less isolated and away from marines, and maybe even reducing the red tint the floor and doors and whatever have so it's less isolated too

2022-10-23 20:17 UTC, Superreallycoolguy commented
Shipside marine is a stupid name, im not gonna lie G. Keep that shit as Military Police, it doesn't fit with the other ranks. also "Master-At-Arms" is (IM PRETTY SURE) the job title of Enlisted NAVY military police. If we had a whole rank rework to fit within similar IRL USMC ranks, this don't fit.

Everything else is baller tho

2022-10-23 20:21 UTC, carlarctg commented on code/game/machinery/vending/vendor_types/crew/ship_marine.dm
> +		list("Marine Combat Boots", 0, /obj/item/clothing/shoes/marine/knife, MARINE_CAN_BUY_SHOES, VENDOR_ITEM_MANDATORY),
boots aren't combat equipment 🤔

2022-10-23 20:22 UTC, carlarctg commented
> Shipside marine is a stupid name, im not gonna lie G. Keep that shit as Military Police, it doesn't fit with the other ranks. also "Master-At-Arms" is (IM PRETTY SURE) the job title of Enlisted NAVY military police. If we had a whole rank rework to fit within similar IRL USMC ranks, this don't fit.
> 
> Everything else is baller tho

i significantly prefer shipside marine to military police simply due to the blurring of the division between MPs and marines. if there was a less lame name, though, i would be in favor

2022-10-23 23:55 UTC, stanalbatross requested changes
and fix your conflicts PLEASE 💢

2022-10-23 23:55 UTC, stanalbatross commented on code/modules/mob/living/say.dm
> +	  ":p" = RADIO_CHANNEL_SECURITY ,			"#p" = RADIO_CHANNEL_SECURITY ,			".p" = RADIO_CHANNEL_SECURITY ,
if it's being called security channel change to .s imo

2022-10-24 02:05 UTC, nauticall requested changes
Keep titles to Military Police and CMP to prevent mass-confusion. As people said earlier this can be really easily confused with Squad Rifleman and people won't know the role of these people from a glance.

Also, "Master-at-Arms" is the name for Navy MPs, who are also enlisted. Calling the CMP an MAA would create even more confusion.

2022-10-24 02:09 UTC, nauticall requested changes
![image](https://user-images.githubusercontent.com/55491249/197434479-8f6708e2-9d28-4c2d-af2e-1a92acc3697b.png)
Helmet's white stripe breaks the silhouette. You can add an outline (bottom row) while still preserving the look of the helmet to be distinct.

2022-10-24 03:24 UTC, morrowwolf commented
Requesting internal discussion regarding these changes given there has been almost zero communication in the dev side of the house about the vast majority of this until about 6 hours ago.

2022-10-24 07:02 UTC, MusselMain commented
Nice, but can they have slightly more visible distinction (in their armour) from standard marines? (it makes it easier for off-ship players to easily identify MP's/Ship Marines, and follow their orders instead of having to examine them to examine them to make sure it's not some marine wearing a MP helmet).

2022-10-24 07:04 UTC, MusselMain commented
Hey, if I can't post here, where to I leave make comments on the discord?

2022-10-24 16:53 UTC, LoJoFan commented
> Shipside marine is a stupid name, im not gonna lie G. Keep that shit as Military Police, it doesn't fit with the other ranks. also "Master-At-Arms" is (IM PRETTY SURE) the job title of Enlisted NAVY military police. If we had a whole rank rework to fit within similar IRL USMC ranks, this don't fit.
> 
> Everything else is baller tho

I'm pretty sure USCMC ranks were fully refitted to be navy ones months ago.

2022-10-26 11:23 UTC, stanalbatross requested changes

2022-10-26 11:23 UTC, stanalbatross commented on code/game/machinery/vending/vendor_types/crew/mp.dm
> +		/obj/item/ammo_magazine/rifle/l42a/extended,
nooooooooooooooooooooooooooooooooo

2022-10-26 11:23 UTC, stanalbatross commented on code/modules/gear_presets/uscm_police.dm
> +	return paygrade
non-detailed var name detected 💢

2022-10-30 19:16 UTC, Sinbest commented
Love the aesthetic changes, the one thing I object to is the helmet, it staying black would be fine.

2022-10-31 23:56 UTC, Sinbest commented
This PR would be far better without the pointless changes to MP roles and such.

2022-11-01 05:05 UTC, SeeminglyTypicalUsername commented
The armor they get in-game doesn't appear to be what is shown in the PR images.

2022-11-02 00:54 UTC, Yellows91 commented
I really like it but...warden MP where?

Warden for MPs feels like it needs to be added back as it gives MP its special touch of having one person MAINLY assigned to brig.

2022-11-02 02:57 UTC, Pyrodes commented
Best change i've seen for MPs so far, silencer keep malding

2022-11-03 22:54 UTC, Yellows91 commented
A personal issue I have.

The green was bad and was removed which I approve of but...
why did you make it LIGHT RED (the same color of alpha squad) it makes it super hard to tell which is alpha and which is MP comms speaking.

Can we PLEASE get crimson red MP comms back

2022-11-10 03:34 UTC, nauticall approved these changes
okay, sprites look good now! approooooved

2022-11-10 03:50 UTC, hotimep commented
if this removes the mp jacket atleast make co able to have the mp jacket bcuz it looks fresh as fuck!!!

2022-11-10 17:38 UTC, Sabitix commented
cant they at least keep the old beret?

2022-11-14 22:34 UTC, Patrick81291 commented
Warden helped new players with brigging and guidance when there was no CMP.

2022-12-18 00:26 UTC, closed without merging