Contractor ERT fixes and minor additions
cmss13-devs/cmss13 pull request #1339
Opened 2022-10-26 23:57 UTC by CapCamIII

## About The Pull Request

Fixes, stuff I forgot to add before merge, and things I noticed after merge.

## Why It's Good For The Game

ERT was used in-game for the first(?) time, I noticed some issues(follow menu broken, hairstyles wacky, synth not having omni-language).
I fix these issues.
Also some changes to make them less of just differently clothed marines(IFF and languages).

## Changelog

:cl:
add: Contractors now have their own faction and IFF, instead of sharing with USCM
add: Contractors now have proper hairstyles
add: Contractors now speak english, spanish, and russian by default
add: Contractor IFF version of MD
fix: Contractor synthetics should now speak all languages, like other synthetic types
fix: Contractors should now show up in the correct section of the follow menu now
spellcheck: Fixes some left-behind lore-bits in contractor synthetic flavor-text
/:cl:

2022-10-29 00:57 UTC, CapCamIII commented on code/modules/gear_presets/contractor.dm
> +	languages = list(LANGUAGE_ENGLISH, LANGUAGE_RUSSIAN, LANGUAGE_JAPANESE, LANGUAGE_YAUTJA, LANGUAGE_XENOMORPH, LANGUAGE_WELTRAUMDEUTSCH, LANGUAGE_NEOSPANISH, LANGUAGE_CHINESE, LANGUAGE_TSL)
Accidentally added it, removed.
Also MARSOC have it too FYI.

2022-11-11 22:42 UTC, harryob requested changes

2022-11-11 22:42 UTC, harryob commented on code/datums/emergency_calls/contractor.dm
> +		to_chat(M, SPAN_BOLD("You were soon after bought by the Vanguard's Arrow Incorporated(VAI) to act as support personnel."))
```suggestion
		to_chat(M, SPAN_BOLD("You were soon after bought by Vanguard's Arrow Incorporated (VAI) to act as support personnel."))
```

2022-11-11 22:48 UTC, CapCamIII commented on code/datums/emergency_calls/contractor.dm
> +		to_chat(M, SPAN_BOLD("You were soon after bought by the Vanguard's Arrow Incorporated(VAI) to act as support personnel."))
Done.

2022-11-13 10:34 UTC, harryob approved these changes

2022-11-13 10:34 UTC, merged