Wiki Guide Integration
cmss13-devs/cmss13 pull request #1354
Opened 2022-10-28 01:02 UTC by Misttyy

## About The Pull Request

This PR adds new defines for every marine role I could find on the wiki that leads to them -- Expanding from this, every entry text for every marine role has had a wiki link to its respective page added. An entry body message has been added for Xeno larva and Queen, with larva linking to the quickstart and Queen linking to a guide.

## Why It's Good For The Game

Our wiki maintainer and contributors work hard. This should make it far easier for the average player to get to see their work and make a more enjoyable experience overall.

## Changelog

:cl: Mistfrag
qol: Linked respective wiki page to all Marine roles, alongside larva and Queen.
code: Added defines for every wiki page on marines.
/:cl:

2022-10-28 01:24 UTC, Misttyy commented
Got the errors ironed out. Could use help from a more experienced dev on adding a Xeno equivalent of entry_message for Larva and Queen since the var doesn't work.

2022-10-28 09:56 UTC, fira commented
Please don't use ////// as separators, three or more slashes are interpreted as DMDOC annotations and will be used as documentation for the define below

2022-10-28 09:58 UTC, fira commented
For Queen, you could use /datum/job/antag/xenos/queen/announce_entry_message

2022-10-28 22:35 UTC, Misttyy commented
Removed the xeno bits of this. I'm going to need to do some more codework than I thought to get them working and I'd rather not stall this PR for it.

2022-10-29 11:15 UTC, Geevies requested changes
echoing what fira said about ///

2022-10-29 11:35 UTC, Geevies requested changes

2022-10-29 11:35 UTC, Geevies commented on code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
> +	var/entry_message_intro
remove this stub

2022-10-29 11:35 UTC, Geevies commented on code/modules/mob/living/carbon/xenomorph/castes/Queen.dm
> -	spit_types = list(/datum/ammo/xeno/toxin/queen, /datum/ammo/xeno/acid/medium)
readd spit types

2022-10-30 01:19 UTC, Misttyy commented on code/modules/mob/living/carbon/xenomorph/castes/Queen.dm
> -	spit_types = list(/datum/ammo/xeno/toxin/queen, /datum/ammo/xeno/acid/medium)
I'm retarded

2022-11-01 15:57 UTC, Geevies requested changes

2022-11-01 15:57 UTC, Geevies commented on code/__DEFINES/urls.dm
> +/// Changelog ///
///

2022-11-02 05:03 UTC, Misttyy commented
should be good

2022-11-02 16:41 UTC, Misttyy commented
I'm going to fix the /// when I get home. 

I need better glasses.

2022-11-03 06:50 UTC, Misttyy commented
@fira @Geevies actually fixed now

2022-11-03 15:56 UTC, merged