Weaker Flares
cmss13-devs/cmss13 pull request #1364
Opened 2022-10-28 20:09 UTC by Geevies

## About The Pull Request

Nerfs flares to have less brightness and burn out quicker. Also changes them to not process but to use a timer instead.

Standard Flare | 4 Tiles (Orig: 5) | 45 - 75 Seconds (Orig: 1600 - 2000)
Flare-gun Flare | 5 Tiles (Orig: 7) | 45 - 75 Seconds (Orig: 1600 - 2000)
Signal Flare | 4 Tiles (Orig: 5) | 150 - 210 Seconds (Orig: 160 - 200)
Illumination Flare (Mortar) | 7 Tiles (Unchanged) | 480 - 720 Seconds (Orig: 800 - 1000)
Starshell Ash (M79) | 7 Tiles (Unchanged) | 20 - 60 Seconds (Orig: 5 - 60)
Chemical Light | Depends on Amount | Depends on Amount (Completely Unchanged)

## Why It's Good For The Game

It's an attempt to make the game more atmospheric, much like the AvP games of the past with their low life flares. Light is an extremely powerful tool, and being able to toss it around and have it last 30 minutes (one third of a good round) is waaaaay too powerful. This also makes mortar flares way more useful in comparison.

## Changelog

:cl:
balance: Nerfed flare brightness and burn time across the board.
/:cl:

2022-10-28 20:42 UTC, stanalbatross commented
This just means everyone will rely on suit lamps and flashlights and nobody will bring flares at all

Not liking this tbh as it cucks normal flares into uselessness (you CANNOT keep an area lit with them) while other light sources stay the same

2022-10-28 21:19 UTC, AnCopper commented
If we're talking about making the game more atmospheric, and making it just not dominated by suit lamps. Directional lightning?

2022-10-28 22:29 UTC, fira requested changes

2022-10-28 22:29 UTC, fira commented on code/game/objects/items/devices/flashlight.dm
> +	burnout_timer_id = addtimer(CALLBACK(src, .proc/burn_out), burn_time, TIMER_UNIQUE|TIMER_STOPPABLE)
deltimer() in Destroy() too, refs can be kept for a while if flare is destroyed (explosions etc)

2022-10-28 22:49 UTC, AGasCanister commented
I think flares should provide red light

2022-10-29 00:20 UTC, stanalbatross reviewed
your why it's good for the game fails to address the other infinite sources of light in the game which are far more of an issue from this standpoint than flares

I don't think this is a justified nerf and it will do little for atmosphere just like directional lighting, which was mostly just aids

2022-10-29 21:34 UTC, stanalbatross commented
marking as DNM as flares cannot be just changed by themselves with the rest of lighting remaining untouched and we need to have a proper discussion about this first

2022-11-10 16:50 UTC, JackieEstegado commented
Not sure of how this will help when edge of screen lurkers and warriors are already one of the biggest problems for marines.
This will also cause problems with marines being blind when running in a direction due to the slow light update timer.

2022-11-10 20:27 UTC, LoJoFan commented
> Standard Flare | 4 Tiles (Orig: 5) | 165 - 195 Seconds (Orig: 1600 - 2000)

While the flare time was indeed too long, up to slightly over 3 minutes feels pointless to even melt unless using medium-strength or stronger acid. Distance change unnecessary.

> Flare-gun Flare | 5 Tiles (Orig: 7) | 165 - 195 Seconds (Orig: 1600 - 2000)

Close to no one uses flare guns to begin with. What is the point of this? It was buffed to give people a reason to use it rather than just throwing them by hand. I've played a lot of RTO rounds focused on illuminating the battlefield and providing fire support, and most of the time both normal and CAS flares were melted with impunity.

> Signal Flare | 4 Tiles (Orig: 5) | 150 - 210 Seconds (Orig: 160 - 200)

Lighting range is fine, as it's got a different purpose. Time is fine either way.

> Illumination Flare (Mortar) | 7 Tiles (Unchanged) | 480 - 720 Seconds (Orig: 800 - 1000)

This is good. I would maybe suggest 6 tile range.

> Starshell Ash (M79) | 7 Tiles (Unchanged) | 20 - 60 Seconds (Orig: 5 - 60)

This is good. M79 pvt's with starshells are the unsung heroes of the push, but the duration always felt too short.

> Chemical Light | Depends on Amount | Depends on Amount (Completely Unchanged)

Can't give input on this as I have 0 experience regarding this.

> Additionally, nerfs suit and rail lights.

> Suit Light | 5 Tiles (Orig: 6)

6 was already very weak, allowing all xenos and especially lurkers an advantage unless geared with a rail flashlight.

> RTO Suit Light | 6 Tiles (Orig: 7)

I see nothing wrong with the original 7 tile range: no one took it to begin with.

> Rail Light | 5 Tiles (Orig: 7)

Makes the rail light completely redundant paired with other light changes. Usually, taking a rail light meant sacrificing your weapon's efficiency (certain attachments, i.e. : red dot sight on the MOU-53, reflex sight for the M41A MK1 burst fire, sights for pistols) or the weapon as a whole (magnetic harnesses) when it would inevitably get stolen, blown up or melted. This is especially true for restricted weaponry. All these costs made you, in turn, able to be more aware of your surroundings. It was a good trade.


> Why It's Good For The Game

> It's an attempt to make the game more atmospheric, much like the AvP games of the past with their low life flares. Light is an extremely powerful tool, and being able to toss it around and have it last 30 minutes (one third of a good round) is waaaaay too powerful. This also makes mortar flares way more useful in comparison.

A common pattern in your MR's has been to "make the game more atmospheric", while not taking into consideration the whole picture:  the AvP games are horror shooters where xenos also die in 1 or 2 M41 bursts. CM is a mosaic of tactics and counters that does not compare with AvP's monotonous "ok this drone is near you he's gonna pounce at you from like 3 meters but like there's a windup so you can shoot him yeah". 
Adding something like xenos dying in 1 or 2 M41 bursts to CM would ruin the game for the xenos, I will not delve too deep into your other MR's for the fear of peanut posting and this being marked off-topic (I'd much rather people read and saw my feedback on this!), but the "atmospheric change" in this PR negatively affects marines without considering the whole intricacy and balance of CM (see below for more info).


### EMPIRICAL EVIDENCE

After having played one round with the test merge, here is what happened, as well as my opinions on it:

- The backlines were unsafe in pairs, and groups of three was toeing the line (this is against 1 lurker); 3-minute flare timers (best case scenario) made it so that they would have to regularly be patrolled, which makes it tedious as chasing good lurkers and runners is already hard enough and more important than just flaring the same path 10 times over the span of 30 minutes. Furthermore, backline harassers already have means of avoiding detection or contact (lurker invisibility being hard to spot on certain tiles, half-darkness not being optimal for seeing them; runners having extra vision. Furthermore, with dynamic night vision, all xenos can easily avoid marine light and guesstimate amount and path).
- Xenos that weren't supposed to do well off weeds now walk around off weeds with impunity. Multiple times, sentinels, warriors, defenders, slow praetorians walked around t-fort on LV624 with absolute impunity with 4 marines actively patrolling it, and no weeds for at least well over 14 tiles (whole screen minimum). This is not good for obvious reasons.
- Marine push is gimped. The over-reliance on short-duration flares due to lack of potent rail/suit lights made pushes near impossible, unless one brave scapegoat marine decided to be prone to lunges, spits, pounces, or whatever other stuns or forms of damage (no one wants to be that guy). A good amount of the round marines were spending their time staring at the darkness waiting for something to happen when xenos already have doors and walls to cut off sightlines, as well as the means to quickly melt flares. Previous frontline flare usage allowed marines to push more confidently, while xenos still had means to melt them. Now there is almost no point. This is all with xenos all having thermals. 
If your intention was to make everyone carry only one weapon and a satchel full of flares, this will never happen, and I will gladly elaborate if you ask me to. However, it's a whole other can of worms, so I will leave it out of this comment.
- Over-reliance on the motion detector. I rocked a motion detector this round expecting the worst, and it barely kept me alive, mostly coupled with the fact that I had the grenadier's armor and I'm scary. Self explanatory. The motion detector shouldn't be necessary to merely stay alive.




P.S.: I assume your ranges include the tile the light spawns on. 
![image](https://user-images.githubusercontent.com/112346996/201192741-58e31b34-4570-413c-b124-2081fc857acc.png)
This is more than half your screen dark.


All in all, a poorly thought-out PR that fixes a non-existent problem and makes the game a lot less enjoyable for one side, contributing to something akin to a 70/30 win-rate.
The only merit it has is decreasing flare timers, which even then, are overtuned.

2022-11-10 20:30 UTC, stanalbatross commented
Don't delete the above comment the guy isn't in the discord :3

2022-11-10 21:00 UTC, RedStar929 commented
Really hard for us to push whit this update, becasue we have even less vision and all alien skills is 2x longer then the light sources. Its specially funny with spitters and praes that can basically stand still and spit for free into us from out of range.

Back lines becomes a death zones now becasue its almost impossible to kill lurker gangs AND now ton of other castes harass back lines. I saw warriors, lords, praes and drones all almost freely walking behind us. I know i can blame sniper/ scout for not hunting them down but its same as depending on RPG to stun all and every T3. Also why? Not only because lights is shorter but delay for lights to move with you is too long (ligh speed in CM slower then running?) so lurkers can ez dodge and walk into darkness. Basically when you move actual suit lights is shorter by 2-3 tiles in front of you. Didnt had that problem with rail light i put into my helmet or onto my gun and now its pointless). 

Overall this change is explained like a fluff one but it only gives aliens ton of undeserved advantages. And about excuse for why we have it. In that same AVP games flare throw has infinite ammo and we dont.

2022-11-11 21:23 UTC, Huffie56 commented
Here is my idea for more atmospherics lighting make it so that the further away you are from a light source the less you can see.
I can see some half light tile so my guess is that it's already implemented in part in the code.
A dumb down version would be to make it so that light source give two type of light half of it would be full light and the rest would be half light where xeno can hide a bit better but marine aren't in total darkness...
then you can reduce the range of full light if you want ...
It's not atmospherics to have your vision stop 4 meter in front of you it's just confusing because light spray and go weaker it doesn't form a whole.
I think if you want to change how light work you should go for the all system not just doing multiple items.

2022-12-09 00:28 UTC, closed without merging