Underground Zombie Landmarks
cmss13-devs/cmss13 pull request #1366
Opened 2022-10-28 22:00 UTC by Geevies

## About The Pull Request

Adds Zombie Landmarks that makes it easier to spawn in zombies for Dchat without them just... standing around. Comes in three variants, one that allows one zombie to spawn at it before it deletes itself, one that does the same but three times, and one that does it infinitely.

## Why It's Good For The Game

Last zombie event it kinda suffered because staff had to spawn zombies in bushes to hide them, so this'll hide them by making the spawnpoints invisible to everyone but observers.

## Changelog

:cl:
admin: Added zombie spawnpoints for events.
/:cl:

2022-10-29 07:05 UTC, fira commented
why the invis shenanigans?

2022-10-29 09:41 UTC, Geevies commented
> why the invis shenanigans?

it keeps regular landmarks hidden, and lets observers see the zombie landmarks dotted around the map. as for why it's set in /New, i have no idea and i think it's out of scope to change it here. i assume it's done for a reason

2022-11-01 19:57 UTC, stanalbatross requested changes

2022-11-01 19:57 UTC, stanalbatross commented on code/game/objects/effects/landmarks/landmarks.dm
> +		GLOB.zombie_landmarks -= src
not qdel?

2022-11-05 00:31 UTC, fira requested changes

2022-11-05 00:31 UTC, fira commented on code/game/objects/effects/landmarks/landmarks.dm
> +		GLOB.zombie_landmarks -= src
yeah you'd want it deleted i think

2022-11-06 19:31 UTC, Geevies commented on code/game/objects/effects/landmarks/landmarks.dm
> +		qdel(src)
qdel is handled here @stanalbatross @fira

2022-11-06 19:54 UTC, fira approved these changes

2022-11-06 21:36 UTC, FransFeiffer approved these changes
Sprites are fine :D

2022-11-06 21:47 UTC, merged