Squad Identification Fluff and Helmet Garb Buff
cmss13-devs/cmss13 pull request #1370
Opened 2022-10-29 09:58 UTC by Geevies

## About The Pull Request

Adds squad-colored scarves and headbands.
Adds a third slot to helmets that only accepts fluff helmet garb.

Additionally, expanded the helmet garb system to have object flags that determine whether the item needs a helmet band, and whether it should be considered a garb item for the garb slot.

## Why It's Good For The Game

Allows for more marine customization via the headbands and scarves, and also reinforces squad identity by making them match the squad's color.

## Changelog

:cl: Geeves, Frans_Feiffer
add: Added squad-colored scarves and headbands.
add: Added a third slot to helmets that only takes fluff helmet garb.
/:cl:

2022-10-29 09:59 UTC, Geevies commented
still waiting on a sprite or two

2022-10-29 12:53 UTC, stanalbatross requested changes

2022-10-29 12:53 UTC, stanalbatross commented on code/game/objects/items/storage/internal.dm
> +/obj/item/storage/internal/helmet/can_be_inserted(obj/item/W, stop_messages) //We don't need to stop messages, but it can be left in.
Var name!

2022-10-29 12:53 UTC, stanalbatross commented on code/game/objects/items/storage/internal.dm
> +/obj/item/storage/internal/helmet/_item_insertion(obj/item/W, prevent_warning = 0)
Var name also if arg is boolean use truefalse

2022-10-29 12:53 UTC, stanalbatross commented on code/game/objects/items/storage/internal.dm
> +/obj/item/storage/internal/helmet/_item_removal(obj/item/W, atom/new_location)
Var name

2022-11-14 15:31 UTC, harryob approved these changes
code looks good, soul verified

2022-11-19 15:03 UTC, nauticall approved these changes
sprites look goooood

2022-11-19 21:15 UTC, merged