Spell checks "huggers" to "facehugger", makes playable hugger join message clearer.
cmss13-devs/cmss13 pull request #1379
Opened 2022-10-30 19:43 UTC by usnpeepoo

## About The Pull Request

This PR adds "face" to huggers in the code. Huggers sounds really dumb, and it's a lot more consistent to call them "facehugger" and not just "huggers". Also, the spawn message for playable huggers was really short. This PR makes it more clearer.

## Why It's Good For The Game

Good spelling, consistency with "facehugger".

## Changelog

:cl:
spellcheck: Playable hugger join message is more clearer
code: Hugger is now called "facehugger" in the code
/:cl:

2022-10-30 19:44 UTC, usnpeepoo commented
idek if this is code improvement I am bad with tags
if you think this isn't please feel free to remove it

2022-11-01 09:16 UTC, stanalbatross requested changes

2022-11-01 09:16 UTC, stanalbatross commented on code/modules/cm_aliens/structures/special/egg_morpher.dm
> +	hugger.visible_message(SPAN_XENODANGER("A child suddenly emerges out of \the [src]!"), SPAN_XENODANGER("You emerge out of \the [src] and awaken from your slumber. For the Hive!"))
?

2022-11-02 11:15 UTC, stanalbatross approved these changes

2022-11-02 11:15 UTC, merged