Faction Comms Overhaul
cmss13-devs/cmss13 pull request #1380
Opened 2022-10-30 22:33 UTC by realforest2001

## About The Pull Request
I will preface this by saying that it will no longer be possible to use EITHER ':' or '.' for radio channels. USCM channels will all use ':' or ';' where appropriate.
The ONLY exception to this is Weyland Yutani comms (:Y & .Y)

UPP, PMCs and CLF all now have General, Engineering, Medical, CCT (JTAC) and Command comms.
UPP have Kommando comms also.
All three factions can now update comms towers properly and operate as actual factions rather than oversized ERTs.

## Why It's Good For The Game
Makes HvH a lot more dynamic rather than other factions being entirely on two channels. Also allows HvH where PMCs and UPP/CLF can be involved without all sharing the CCT network.
Tidies up some of the code for radios, removing nonfunctional keys (#'s).

## Changelog

:cl:
fix: Removed bloat/duplicate code in the contractors ERT while doing headset updates
add: Added Command, Engineering, Medical and CCT channels for PMCs, CLF and UPP.
add: Added headsets and encryption keys for the above, and a few other channels.
add: Added keys to talk on faction channels without needing to juggle keys to make :H work.
add: UPP channels mostly reflect the USCM channel allocations (command is .V compared to USCM :V) using V/M/N/J/U General/T Commando
add: CLF channels are A Med/B Engi/C Cmd/D CCT/G General
add: PMC channels are E Engi/F Med/P General/O CCT/Z Cmd /K Whiteout
/:cl:

2022-11-01 09:31 UTC, stanalbatross requested changes
`.-channel` for radios being removed is a major detriment to communication as it's way faster than pressing : and many people (including myself) are used to using . instead

no merge with this change still in it

2022-11-29 03:34 UTC, ThePiachu commented
As little as I use `#`s in my radio, I agree with Stan - we shouldn't be deprecating the functionality.

Maybe a better solution would be to let all the factions use the same comm schema, but connect to their individual departments. So if you used `:m` on UPP radio it would send a message to UPP Medbay, CLF would send to CLF Medbay, etc. It would make the radio keys not interoperable, but that's fine I guess?

Of course this would require a bigger code rewrite.

In the meantime you could merge some of the code refactor (the 1 to TRUE) separately so the next iteration of this would be a bit simpler.

2022-11-29 05:40 UTC, realforest2001 commented
> As little as I use `#`s in my radio, I agree with Stan - we shouldn't be deprecating the functionality.
> 
> Maybe a better solution would be to let all the factions use the same comm schema, but connect to their individual departments. So if you used `:m` on UPP radio it would send a message to UPP Medbay, CLF would send to CLF Medbay, etc. It would make the radio keys not interoperable, but that's fine I guess?
> 
> Of course this would require a bigger code rewrite.
> 
> In the meantime you could merge some of the code refactor (the 1 to TRUE) separately so the next iteration of this would be a bit simpler.

Prior to this PR, using # would not work anyway. It's been in the code for an extremely long time, but never actually worked. See carbon/human/say.dm

2022-12-20 21:28 UTC, stanalbatross requested changes

2022-12-20 21:28 UTC, stanalbatross commented on code/controllers/subsystem/communications.dm
> +var/const/SOF_FREQ		= 1472
out of order

2022-12-20 21:28 UTC, stanalbatross commented on code/game/machinery/telecomms/presets.dm
> +	freq_listening = list(UPP_FREQ, UPP_CMD_FREQ, UPP_ENGI_FREQ, UPP_MED_FREQ, UPP_CCT_FREQ, UPP_KDO_FREQ)
can use UPP_FREQS define here

2022-12-20 21:28 UTC, stanalbatross commented on code/game/machinery/telecomms/presets.dm
> +	freq_listening = list(PMC_FREQ, PMC_CMD_FREQ, PMC_ENGI_FREQ, PMC_MED_FREQ, PMC_CCT_FREQ, WY_FREQ)
same and same

2022-12-20 21:28 UTC, stanalbatross commented on code/game/machinery/telecomms/presets.dm
> +					freq_listening |= list(PMC_FREQ, PMC_CMD_FREQ, PMC_ENGI_FREQ, PMC_MED_FREQ, PMC_CCT_FREQ, WY_FREQ)
same same same

2022-12-22 21:26 UTC, stanalbatross commented
after this is merged now that I have actually learned map() procs in js I can take another look at making the UI show the channel key

2022-12-22 21:32 UTC, stanalbatross approved these changes

2022-12-22 21:32 UTC, merged