Charger Crusher Revived
cmss13-devs/cmss13 pull request #14
Opened 2022-04-15 02:00 UTC by PhantomEpicness

## About The Pull Request

"This is subject to change. Tumble might get tweaked and the strain may be given more passive and active abilities. However, the baseline is that you hold move key and you destroy shit."

Credit to original charger devs, lumdor and donk!

## Why It's Good For The Game

Reject zoomer crusher, embrace boomer charger crusher.
## Changelog

:cl: TheDonkified and Lumdor

rscadd: Charger strain for crusher.

experiment: Charger functions very similarly to old crusher. Hold movement key and after a while you gain momentum to ram humans and certain objects. Behavior upon collision with different things are subject to change.

experiment: Passive 1: Directional armor. Charger has 45 frontal armor, 30 side armor, and 20 rear armor. Because of this ability, charger crusher is unable to direction lock itself.

experiment: Active 1: Toggle Charging. Use this ability to toggle charging on and off.

experiment: Active 2: Tumble. Clicking to the side of where the crusher is facing will launch it 2 tiles to the side in the clicked direction. Hitting a human will knock them over. This ability can be used while charge to quickly offset yourself. However, it will reset your momentum to 0.

/:cl:

:cl: TotalEpicness

bugfix: Revived charger strain from MR hell. Fixed various bugs.

rscadd: Tumble now has cool sound effects and a spin.

wip: Added tumble ability sprites

tweak: Charger now takes 3 full hits to destroy a normal wall instead of destroying it in pretty much one. Xeno walls take half damage

experiment: Active 3: Charger stomp. Unlike the base crusher, it does not stun, but does heavy damage to any human unfortunate enough to be under the charger, it also applies a mild screen shake to any humans in view and can be used to help escape.

bugfix: Added dozens of handle_collision procs for pretty much every conceivable situation in which a charger will charge an item that should be breakable.

rscadd: Xenos blocking a charger's path when charger get pushed to the side, if no clear path to move to exists, they get flicker stunned so that charger may charge.

/:cl:

2022-04-15 02:05 UTC, PhantomEpicness commented
Darn, doing it the lazy well messed it up. Oh well.

2022-04-15 09:07 UTC, stanalbatross commented
you gotta use the new prefixes in the CL like "add" for the labels to get added properly

2022-04-15 11:26 UTC, Watermelon914 commented
two changelogs doesn't work anymore, combine them into 1

2022-04-15 11:27 UTC, Watermelon914 commented
please add a proper `Why It's Good For The Game` or I'm going to close this PR.
You should also write a design doc for this here: https://github.com/cmss13-devs/cmss13-design-docs

2022-04-15 18:52 UTC, PhantomEpicness commented
> please add a proper `Why It's Good For The Game` or I'm going to close this PR. You should also write a design doc for this here: https://github.com/cmss13-devs/cmss13-design-docs

on it

2022-04-16 10:15 UTC, Watermelon914 requested changes

2022-04-16 10:15 UTC, Watermelon914 commented on code/modules/mob/living/carbon/human/human_damage.dm
> +        parts += O
Use a more detailed variable name here instead of `O`. Use 'limb' if you have to.

2022-04-16 10:15 UTC, Watermelon914 commented on code/modules/mob/living/carbon/xenomorph/abilities/crusher/crusher_abilities.dm
> +/datum/action/xeno_action/onclick/charger_charge/proc/handle_movement(mob/living/carbon/Xenomorph/X, atom/oldloc, dir, forced)
Use a more descriptive variable name rather than X. Use 'user' or 'charger',

2022-04-16 10:15 UTC, Watermelon914 commented on code/modules/mob/living/carbon/xenomorph/abilities/crusher/crusher_abilities.dm
> +	X.speed += momentum * speed_per_momentum
Same thing here

2022-04-16 10:15 UTC, Watermelon914 commented on code/modules/mob/living/carbon/xenomorph/abilities/crusher/crusher_abilities.dm
> +	X.update_icons()
Same thing here

2022-04-16 10:15 UTC, Watermelon914 commented on code/modules/mob/living/carbon/xenomorph/abilities/crusher/crusher_abilities.dm
> +				return COMPONENT_LIVING_COLLIDE_HANDLED
More descriptive variable name here please. Is A the target that's being collided into? If it is, make it clear.
Same with X. Is that the charger or some different xeno?

2022-04-16 10:15 UTC, Watermelon914 commented on code/modules/mob/living/carbon/xenomorph/abilities/crusher/crusher_abilities.dm
> +		X.forceMove(target_turf)
Same thing here. is H mob the human target?

2022-04-16 10:15 UTC, Watermelon914 commented on code/modules/mob/living/carbon/xenomorph/abilities/crusher/crusher_abilities.dm
> +
Same thing here and anywhere else you have 1 letter variable names that you've defined

2022-04-16 10:15 UTC, Watermelon914 commented on code/modules/mob/living/carbon/xenomorph/abilities/crusher/crusher_powers.dm
> +	var/mob/living/carbon/V
You need more descriptive variable names here. What is V supposed to be? You're making life harder for future devs

2022-04-16 10:15 UTC, Watermelon914 commented on code/modules/mob/living/carbon/xenomorph/abilities/crusher/crusher_powers.dm
> +	var/will_charge = "[activated ? "now" : "no longer"]"
What is A supposed to be? the target? please specify

2022-04-16 10:15 UTC, Watermelon914 commented on code/modules/mob/living/carbon/xenomorph/abilities/crusher/crusher_powers.dm
> +	if(!action_cooldown_check())
Same thing with these single letter variable names. What is A supposed to be, the target?

2022-04-16 10:15 UTC, Watermelon914 commented on code/modules/mob/living/carbon/xenomorph/castes/Queen.dm
> +	Q.icon = Q.queen_standing_icon
Use a more descriptive variable name here, it shouldn't be Q it should be 'queen'

2022-04-18 10:09 UTC, stanalbatross commented
undraft once you do changes + ready for TM

2022-05-03 19:55 UTC, PhantomEpicness commented
progress ceased until summer due to uni finals

2022-05-04 12:46 UTC, Watermelon914 commented
close this PR then and re-open it when you can work on it again

2022-05-25 02:22 UTC, PhantomEpicness commented
merge conflicts fixed

2022-06-12 06:17 UTC, BKryth commented
> Forgot to put it here bet here is what is going to happen next TM:
> 
> -Base Crusher replacement -base Crusher AoE stun added to stomp at price of less damage for stomp -slightly faster move speed for slightly slower charge speed
> 
> Possible: A new ability, "Ram" that is essentially a short ranged fling that deals slightly more damage. Will likely put a condition to auto deconstruct an MG and stun if rammed.

I suggest instead of making it just a better version of crusher, keep it as a strain as both base and the charger have different gameplay

Also as it is, it has like 4 surviveability traits already, he has way too much surviveability

- Charging armor
- Tumble
- Mini ram
- Charging

It already has like 3 dashes, 2 of which can be used to avoid bodyblock, which is the main risk involved in charging, it shouldn't be risk free or be given so many abilities to deal with bodyblock when thats one way on how to deal with them. Personally prefer that crusher be remained as a tanky xeno than one that relies on dashes and speeds. Base crusher offers a more defensive capabilities with tankiness and aoe slashes, whereas Charger offers a more offensive role, theres really no need to replace it. Strains are used to give an alternative option for gameplay similar to how other strains are, crusher already lacks strains, why remove it in the first place. 

The crusher before the ram was already pretty good. 

As for the m2c issue, personally suggest just make it so that at a certain speed or maybe not even at a certain speed, it just breaks the turret(displacing them not breaking), and ram through the marine on a halt.

2022-06-12 07:24 UTC, Mammle2 commented
Plz fix hotkeys, xeno active 2 activates tumble when it's in the third spot, active 3 activates stomp when it's in the second spot (in the top left bar thing), while xeno active 4 doesn't toggle the mini charge at all.

2022-06-12 15:57 UTC, Segrain commented on code/modules/mob/living/carbon/xenomorph/abilities/crusher/crusher_abilities.dm
> +		var/lol = get_ranged_target_turf(charge_dir,momentum/2)
```suggestion
		var/lol = get_ranged_target_turf(Xeno, charge_dir, momentum/2)
```
> `/proc/get_ranged_target_turf(var/atom/A, var/direction, var/range)`
![image](https://user-images.githubusercontent.com/4447185/173241886-35939131-beb0-434b-9ced-ca2da9bec2e1.png)

2022-06-12 18:04 UTC, Segrain commented on code/modules/mob/living/carbon/xenomorph/castes/Crusher.dm
> +			to_chat(world, "TEST STEST")
```suggestion
```

2022-06-12 18:04 UTC, Segrain commented on code/modules/mob/living/carbon/xenomorph/castes/Crusher.dm
> +		to_chat(world, "TEST STEST")
```suggestion
```

2022-06-13 03:25 UTC, PhantomEpicness commented
Upcoming changes on next TM:

- total removal of charging front armor bonus
The charging bonus is just straight up unnecessary, especially since we are reaching 57 armor, that's good enough already.

- Potential Revisit to it being a strain again
 I have reconsidered this as both are different enough, a few changes and we can establish some roles like prae. Ram ability is likely to be completely removed and something else may take its place.
This will also result in the removal of ram and may or may not be replaced with another ability

I will also create a poll on the forums as this is pretty controversial whenever I have asked about it.

- Experiment: lowering average armor to 20 (-5)
This would punish failed charges even more and make the counterplay more viable. Will potentially upgrade side/front armor by a bit to compensate. Charger would still be very tanky front the front

- Make frenzy not affect charge speed/ possible toning down of charging speed
With frenzy, it reaches TGMC levels of charger which is nuts. Fun to the xenos but not really fun for the marines when they have 1.5 seconds to shoot them. This is unintended.

2022-06-13 14:01 UTC, Segrain commented on code/modules/mob/living/carbon/xenomorph/abilities/crusher/crusher_powers.dm
> +		Human.apply_armoured_damage(15, BRUTE) // random
```suggestion
		Human.apply_armoured_damage(15, ARMOR_MELEE, BRUTE) // random
```
> `/mob/living/proc/apply_armoured_damage(var/damage = 0, var/armour_type = ARMOR_MELEE, var/damage_type = BRUTE,`
![image](https://user-images.githubusercontent.com/4447185/173370805-0aa09d52-15e3-4bae-a718-cd1ff98bd5af.png)

2022-06-13 16:55 UTC, GoldenDarkness55 commented
The drift feels super unfair to play against. You see a crusher walk out, it walks 2 tiles towards you and suddenly begins charging. Just wat?? I dunno if it's not working as intended but its absolute aids. Frenzy charging speed needs to be gone too, you dont even get to react, just get mowed down.

In regards to M2C issue - pre-deployed m2c isnt the problem, the problem is that a marine can deploy it and just kill you before you even get the momentum to walk back.

2022-06-13 18:36 UTC, PhantomEpicness commented
> The drift feels super unfair to play against. You see a crusher walk out, it walks 2 tiles towards you and suddenly begins charging. Just wat?? I dunno if it's not working as intended but its absolute aids. Frenzy charging speed needs to be gone too, you dont even get to react, just get mowed down.
> 
> In regards to M2C issue - pre-deployed m2c isnt the problem, the problem is that a marine can deploy it and just kill you before you even get the momentum to walk back.

I am falling back to the initial idea for the third ability, a mini fling that can displace machineguns to replace ram. The reason is that ram is pretty much rarely used as its just a worse tumble.

2022-06-13 22:10 UTC, Carnage068 commented
> Other balance changes:
> 
> * Charging distance increase
>   Charging distance is actually shorter than old crusher as at the moment, its three tiles, which is cancer to play against and also results in a ton of unnecessary resin wall/door destruction from accidentally charging them.
> * Charging damage increases.
>   The charging damage will be increased to compensate somewhat for the slower charging (mentioned above) + the charging distance increases

Yeah, I was honestly gonna suggest that, lmao. Increasing the charge distance, I mean. It just comes out too early, and combined with drifting, it can just lead to situations that are absolutely bullshit for marines, LOL. I know I've mentioned this several times already, but now that its mobility has been slightly decreased (Charging takes longer), I think it would finally be fair game and not overpowered or overbearing to bump Charger's base movement speed up by one more tier. With the increase to charging distance, it will still begin its charge later than before, but this will help mitigate it somewhat while emphasizing its strength as a more durable, more mobile caste than Base Crusher was/is (depends on if it's gonna get replaced or not). I also think it would be fairer to play against for marines, since Charger already has a pretty damn solid amount of damage, I don't feel like it should have any more.
Either way though, the changes you made are still good. It'll definitely have more counterplay and feel fairer to play against than before.

2022-06-13 23:41 UTC, Diegoflores31 commented
I was looking at charger right now and its just an overall unstopable version of it and the only reliable way to stop him i have seen is he either gets trapped on cades or APC blocked .
 it has 800 Health , shield , armor , 2 dashes with STUN high damage and melts cades instantly ... really i dont know what role its suposed to fill but i think it is going too OP and you can notice that for the comical amount of crushers on rounds

2022-06-14 03:01 UTC, Carnage068 commented
> I was looking at charger right now and its just an overall unstopable version of it and the only reliable way to stop him i have seen is he either gets trapped on cades or APC blocked . it has 800 Health , shield , armor , 2 dashes with STUN high damage and melts cades instantly ... really i dont know what role its suposed to fill but i think it is going too OP and you can notice if you ghost on any LV round.

Since when did it have a shield???

2022-06-18 06:33 UTC, stanalbatross commented
conflicts plus pending issues as pointed out by segrain

2022-07-04 00:35 UTC, closed without merging

2022-07-07 05:52 UTC, PhantomEpicness commented
Also, I am having difficulty finding the commit where I replaced base so I can revert to it. Funny git fuckery moment

2022-07-09 04:06 UTC, Carnage068 commented
RIP, the dream is dead.

2022-07-11 08:45 UTC, PhantomEpicness commented
racist as fuck how I cant reopen this