Creates a new tile for the predator ship
cmss13-devs/cmss13 pull request #1400
Opened 2022-11-01 02:47 UTC by Joelampost

## About The Pull Request
Creates a new shuttle tile variant specifically for the pred ship that does not stop surgery.

## Why It's Good For The Game
Less confusion good 

## Changelog

:cl:
fix: Certain tiles on the pred ship now no longer stop you performing surgery.
/:cl:

2022-11-01 09:18 UTC, stanalbatross reviewed
code is fine

2022-11-01 09:18 UTC, stanalbatross approved these changes

2022-11-01 09:19 UTC, stanalbatross requested changes
![image](https://user-images.githubusercontent.com/66756236/199201380-0c2d3bba-932f-4453-8955-7efb2020687c.png)
misclicked tile here?

2022-11-03 08:26 UTC, Shad0vvs commented
Consider allow_construction = TRUE for consistency.

2022-11-03 17:45 UTC, Shad0vvs approved these changes

2022-11-03 17:47 UTC, merged