UPP Lore - UPP Assault Pioneers
cmss13-devs/cmss13 pull request #1401
Opened 2022-11-01 07:06 UTC by Misttyy

## About The Pull Request

This PR changes a lot of small naming conventions and the sort for the UPP. This is something I've discussed with fellow lore contributors Monkey and Lago. UPP Ranks now follow 1980s USSR ranks during the Soviet-Afghan war, with the Latinization removed and simply converted to English.

Additionally, UPP Kommandos have been renamed to UPP Assault Pioneers as apart of a lore project.

## Why It's Good For The Game

This sets the path for a feature UPP ERT to be added (non covert UPP Assault Pioneers). As well, this makes UPP ranks look far less silly and makes everything comply with the lore more.

## Changelog
:cl: Mistfrag
del: Removed UPP conscripts from the code.
spellcheck: Converts UPP Ranks to follow USSR ranks without the silly looking Latinization. Renames UPP Kommandos to UPP Assault Pioneers (Covert).
:cl:

2022-11-01 19:48 UTC, stanalbatross commented
UPP ERTs no longer default spawn them hostile, the UPP are not at war with the UA, this did not make sense. However, UPP Covert ERT still spawns hostile with specified instructions. 

pretty big thing not documented in cl

2022-11-01 21:29 UTC, Misttyy commented
> UPP ERTs no longer default spawn them hostile, the UPP are not at war with the UA, this did not make sense. However, UPP Covert ERT still spawns hostile with specified instructions. 
> 
> 
> 
> pretty big thing not documented in cl

I'm going to remove this tonight and wait to do it in another PR. I think, while a good change, it needs more framework to support it.

2022-11-13 16:18 UTC, Geevies requested changes
i'd say keep the UPP conscripts in, they're useful (and fun!) for weak event characters

2022-12-08 00:37 UTC, Misttyy commented
Fixed up merge conflicts, readded conscripts as an event role.

2022-12-12 18:22 UTC, carlarctg commented on code/game/machinery/computer/demo_sim.dm
> -				if(UPP_MODE)
why did you remove this

2022-12-12 18:22 UTC, carlarctg commented on code/game/objects/effects/landmarks/freed_mob_spawner.dm
> -/obj/effect/landmark/freed_mob_spawner/upp_conscript
why did you remove this

2022-12-12 18:22 UTC, carlarctg commented on code/game/objects/items/storage/backpack.dm
> -	uniform_restricted = list(/obj/item/clothing/suit/storage/marine/faction/UPP/commando) //Need to wear UPP commando armor to equip this.
i mean it still says commando in the subtype.................................

2022-12-12 18:22 UTC, carlarctg commented on code/modules/gear_presets/upp.dm
> -	//Sappers should have lots of gear and whatnot that helps them attack or siege marines
whye

2022-12-27 07:16 UTC, harryob requested changes
this is gonna stale if you don’t resolve carlarc’s threads

2023-01-08 00:29 UTC, closed without merging