Items being deleted in explosions now have a message
cmss13-devs/cmss13 pull request #1434
Opened 2022-11-05 02:58 UTC by PhantomEpicness

## About The Pull Request
No more thinking your shotgun went to brazil or PVT altard mcbaldface stole it because you were blown up, it now sends a message in chat when it is deleted.

Also made it red underline, so its more easily spottable in the sea of red combat logs

## Why It's Good For The Game
Quality of life, so people actually know what their shit was deleted to rather than it disappearing for no reason

## Changelog

:cl: TotalEpicness5
qol: Items destroyed by explosions now pop up a message saying they were destroyed
/:cl:

2022-11-05 12:00 UTC, fira requested changes

2022-11-05 12:00 UTC, fira commented on code/game/objects/items.dm
> +		return
This also prevents indestructible items from being tossed around, which is funnily enough going in the opposite direction of #1271

2022-11-16 21:22 UTC, PhantomEpicness commented
@fira did the funny thing and integrated #1271 into this by doing the chances to item ex_act that it did

2022-11-19 21:17 UTC, fira approved these changes
That's fine by me. Undraft when ready

2022-11-27 18:37 UTC, merged