Removes pooling bursted bodies
cmss13-devs/cmss13 pull request #1489
Opened 2022-11-10 09:57 UTC by Nanotrasen-Spy

Removes the pooling of chestbursted human bodies into the xenomorph spawn pool.

## About The Pull Request

Removes the pooling of chestbursted human bodies into the xenomorph spawn pool. Chestbursts now simply give an extra pooled larva to depict the hivemind as being empowered by a host bursting after a very short moment. The delay's about as equivalent to as long as it took for someone to be unbuckled and pooled before.

## Why It's Good For The Game

Deleting chestbursted bodies by being pooled is very soul less. This was apparently very much discussed in the discord [here.](https://discord.com/channels/150315577943130112/1039081406615277618/1039081406615277618) (I'm not in the discord so not actually sure what's in it or what was talked about, link sent by a friend)

It adds soul because the pooling itself is a meaningless and hollow interaction to begin with. It's meaningless for both sides. For xenos, they have no reason to care other than the extra larva it gives, and all it becomes is a soul less chore of a thorn if every xenos are or needed at the front and one of them have to bother running back to the hive to pool a body they have no reason to and don't care about. For marines, being captured and pooled is one of the most meaningless things that can happen in their rounds, coupled with the fact finding your buddies remains if the hive ever does get cleared out was used to be one of the most meaningful and Aliens-like moments you can experience within the game.

## Changelog

:cl:
del: Removes the pooling of chestbursted human bodies into the xenomorph spawn pool. Chestbursting now automatically grants an extra pooled larva that melting bodies down would formerly provide.
/:cl:

2022-11-10 11:55 UTC, Huffie56 commented
I can see why you would want that but three thing that could cause issue:
-this can nerf the xeno when they are loosing remove them any ability for them to take caps bursted or not away to pool them later if queen is doom for example.
-what happen when a marine outside of a nest burst?
-also what happen when marines burst ship side or not ground site? does it still give them an extra larva despite the global rule of limiting hive influence on other Z level?
-not sure if it matter a lot but it also destroy the body and all the items in it so it contribute to reducing lag... so not maybe a super idea to remove it in the current lag state of CM.....

2022-11-10 13:28 UTC, stanalbatross requested changes
Please give an actual reason in your "why it's good for the game", I fail to see why removing interaction adds soul

2022-11-10 15:46 UTC, usnpeepoo commented
Soulless

2022-11-11 10:36 UTC, LoJoFan commented
In my humble opinion, this is going to massively buff hives on the run and remove the task of having to secure bursted bodies when the hive was destroyed and late stage captures are bursting. The hive is meant to be at a disadvantage, not be effortlessly rewarded.

Furthermore, being able to pool bodies at a later date massively helps during highpop when the hive has lots of pooled larvae, as the queen tends to die (ergo delete all pooled larva) while the hive may still be able to make a comeback.

2022-11-11 21:38 UTC, stanalbatross commented
while I appreciate that finding your bursted buddies in the hive while clearing it out is cool, the balance ramifications of this PR (larvae guaranteed from shipside/frontline bursts (i.e. making xenos in containment)) (more bodies for eggmorpher) are more important and are undesirable.

2022-11-11 21:38 UTC, closed without merging