Metal Foam now plays the correct hitsound
cmss13-devs/cmss13 pull request #1509
Opened 2022-11-11 18:08 UTC by PhantomEpicness

## About The Pull Request
Metal Foam now plays the correct hit sound. 

## Why It's Good For The Game
No audible feedback from things that are expected to have Audible feedback bad. Audible feedback good.

## Changelog

:cl:totalepicness
fix: Metal Foam now plays the correct hitsound.
/:cl:

2022-11-11 22:42 UTC, fira commented
won't that double up with current or is there actually none?

2022-11-12 06:29 UTC, PhantomEpicness commented
> won't that double up with current or is there actually none?

Actually none. Apologies for the confusing PR description and name

2022-11-13 14:48 UTC, Geevies requested changes
not a fix, use soundadd instead

2022-11-19 13:19 UTC, fira approved these changes

2022-11-19 13:19 UTC, merged