Create new food category for ASRS.
cmss13-devs/cmss13 pull request #1538
Opened 2022-11-13 13:47 UTC by Huffie56

## About The Pull Request
Creating a new category for food in ASRS to simplify access to raw ingredient to cook. Those crates will start at the category with the lowest price.

## Why It's Good For The Game
With this new category people and cook will clearly see where to look if they want food items.

## Changelog

:cl:
add: Added a new category for ASRS : food.
/:cl:

2022-11-13 15:00 UTC, fira commented
You need to:
 1. Include the new file in the DME
 2. Assign cost to a variable (cost = probably)
 3. Put the rest of the food in that category (eg ingredients crate)
But yeah it's a good idea

2022-11-13 18:46 UTC, Huffie56 commented
> You need to:
> 
>     1. Include the new file in the DME
> 
>     2. Assign cost to a variable (cost = probably)
> 
>     3. Put the rest of the food in that category (eg ingredients crate)
>        But yeah it's a good idea

thanks : 
1-i didn't saw any dme file linked to ASRS code. can you clarify what file i need to modify? i added the category in supplypack.dm
2-their is a cost assign via cost = RO_PRICE_WORTHLESS variable . not sure what you mean there...
3-I just did remove all the food from misc category  and one from operation.
please help for 1 and 2.

2022-11-13 19:47 UTC, fira commented
well, most of these are missing the `cost =` part
also the new file mut be inside the main environment file `ColonialMarinesALPHA.dme`
i'd suggest running this through dreammaker and testing it to ensure it works

2022-11-13 20:08 UTC, Huffie56 commented
> well, most of these are missing the `cost =` part also the new file mut be inside the main environment file `ColonialMarinesALPHA.dme` i'd suggest running this through dreammaker and testing it to ensure it works

I am not sure when i manage to delete cost = . I corrected it.
I added the define in ColonialMarinesALPHA.dme fallowing the alphabetic order like it was.
Do i really need to run and test it via dreammaker? and if yes how?
thanks

2022-11-13 21:30 UTC, fira requested changes
The prefered way to test is to download VScode, get the game files, open the folder in VScode, then you can press F5 to build/launch the game and try things out. Don't hesitate to ask on discord if you need help with this

2022-11-13 21:30 UTC, fira commented on code/datums/supply_packs/food.dm
> +	/datum/supply_packs/funfood
indentation error here, there's one extra tab

2022-11-13 21:32 UTC, Huffie56 commented on code/datums/supply_packs/food.dm
> +	/datum/supply_packs/funfood
i see thanks

2022-11-13 21:49 UTC, Huffie56 commented
> The prefered way to test is to download VScode, get the game files, open the folder in VScode, then you can press F5 to build/launch the game and try things out. Don't hesitate to ask on discord if you need help with this

I will try and come to discord if needed.
thanks

2022-11-15 20:54 UTC, Huffie56 commented
tested it's working
ASRS menu and ordering food

![image](https://user-images.githubusercontent.com/117036822/202023265-339516a3-90dd-4759-9813-1486ad6ae6dd.png)

I changed the long ass description
Req result
![image](https://user-images.githubusercontent.com/117036822/202023023-49ac3b45-922a-4e61-81f3-7e7ff1278efb.png)

2022-11-19 20:53 UTC, fira approved these changes

2022-11-19 21:50 UTC, merged