Xeno blood is now finite
cmss13-devs/cmss13 pull request #1565
Opened 2022-11-15 03:13 UTC by ThePiachu

## About The Pull Request

While working on #1548 I got a comment how Xeno corpses produce infinite blood. That's obviously something that needs to be fixed if we want to do anything with Xeno blood products in the future (whether it's stims, exotic materials, equipment upgrades and so on). So I made the xeno blood actually tick down when you draw it out, and just to be sure I added a handle_blood() proc to xeno's Life() to make them regen blood while they are alive. You never know what ungas might do with a syringe...

Also fixed an edge case where you couldn't get the last drop of blood out of a mob if you were drawing too much. If that's the case we just take what's left.

## Why It's Good For The Game

If we want xeno blood to be useful for future development, it can't be a limitless resource.

## Changelog

:cl:
fix: Xeno blood is now a finite resource.
add: Living xenos now regenerate blood just in case some unga has the idea to attack one with a syringe.
/:cl:

2022-11-15 14:40 UTC, stanalbatross requested changes

2022-11-15 14:40 UTC, stanalbatross commented on code/modules/mob/living/blood.dm
> +	blood_volume = max(0, blood_volume - amount) // Removes blood if human
```suggestion
	blood_volume = max(0, blood_volume - amount)
```
this comment is wrong and so is its use in /carbon

2022-11-15 14:40 UTC, stanalbatross commented on code/modules/mob/living/blood.dm
> +		amount = blood_volume
should probably sanity check for blood volume here so you don't go through the entire proc with `amount` being zero, same for /carbon

2022-11-16 16:47 UTC, stanalbatross requested changes

2022-11-16 16:47 UTC, stanalbatross commented on code/modules/mob/living/blood.dm
> +	if(!O.reagents || amount <= 0)
```suggestion
	if(!O.reagents || amount <= 0 || blood_volume <= 0)
```

2022-11-16 16:47 UTC, stanalbatross commented on code/modules/mob/living/blood.dm
> +	if(!O.reagents || amount <= 0)
```suggestion
	if(!O.reagents || amount <= 0 || blood_volume <= 0)
```

2022-11-19 21:58 UTC, fira approved these changes

2022-11-20 21:00 UTC, harryob approved these changes

2022-11-20 21:00 UTC, merged