Changes MedHUD sprite to match the icon state
cmss13-devs/cmss13 pull request #157
Opened 2022-04-26 22:33 UTC by Diegoflores31

## About The Pull Request

This PR edits the sprite for the medHUD to match the icon state and its brother the SensorMate and also resolves some inconsistencies on the ON/OFF state

The MedHUD name has also been changed from "degoggles" to "healthhud_d" to be easily identifiable and aligned to the other HUD names

## Why It's Good For The Game

the last sprite was inconsistent and became barely visible when turned off . this should fix that issue
BEFORE:

https://user-images.githubusercontent.com/47069269/165403496-7a9c0f01-d72f-4a5a-82ac-789fa9a5a5f7.mp4

AFTER : 

https://user-images.githubusercontent.com/47069269/165403518-ae36c5aa-277b-4798-a1f4-c0a02bdef0f8.mp4

## Changelog

:cl:
fix: Fixed MedHUD to match its icon state
/:cl:

2022-04-27 01:38 UTC, nauticall requested changes
Personally I'd rather have it be the other way around - keep the onmob sprite as it is currently and have the MedHUD item sprite (icon state) have the green bit go completely invisible. That way you can both keep consistency and not have a giant gray thing obstructing people's eyes. I've talked to a few and they said they prefer the MedHUD onmob going away since people can see their character's face properly.

2022-04-27 04:59 UTC, stanalbatross requested changes

2022-04-27 04:59 UTC, stanalbatross commented on code/modules/clothing/glasses/hud.dm
> +	deactive_state = "healthhud_d"
Do not rename the degoggles icon state, it is used extensively for other HUDs as well

2022-05-02 16:28 UTC, nauticall approved these changes
looks good now! sprites approved 👍

2022-05-06 17:21 UTC, merged