Skills Refactor/Fix
cmss13-devs/cmss13 pull request #1578
Opened 2022-11-16 06:17 UTC by Misttyy

## About The Pull Request

This is a quick rewrite, including documentation of what's going on in mob_helpers in order to make it easier to read for the average joe. Fixes fireman carry being broken.

## Why It's Good For The Game

Fixes a bug and makes thing easier for the next-guy to have a go ahead.

## Changelog

:cl: Mistfrag
fix: Fixed fireman carry having the same speed to pick someone up with regardless of skill.
refactor: Made mob_helpers easier to read.
:cl:

2022-11-16 18:16 UTC, morrowwolf commented
CL needs to be updated properly, there are gameplay implications for some parts of the refactor that need to be logged.

2022-11-26 08:38 UTC, ThePiachu approved these changes

2022-11-26 10:34 UTC, harryob requested changes

2022-11-26 10:34 UTC, harryob commented on code/modules/mob/mob_helpers.dm
> +			else if(skillcheck(src, SKILL_CQC, SKILL_CQC_EXPERT))
undocumented rararrrgh

2022-11-29 06:55 UTC, ThePiachu approved these changes

2022-11-29 08:21 UTC, merged