Projectile Subsystem and misc adjustments
cmss13-devs/cmss13 pull request #1608
Opened 2022-11-18 18:30 UTC by fira

## About The Pull Request

What this does:
 * Adds a projectile subsystem for scheduling their movement. This replaces sleep()s in follow_flightpath() which are detrimental to the game smoothness. As a bonus, the controller runs at world.tick_lag, meaning bullets update twice as often.
 * Adds extra visual cues to gun firing. Together with above, bullet speed is randomly +- 15% to allow visual feedback in form of a proper bullet trail (otherwise they sync up). Bullet firing now takes into account scatter and clicked pixel to offset slightly bullet positions and wall bullet pings.
 * Decouples gun and projectile logic for good. In theory this should avoid (or just displace..) bugs we've had with gun firing for years.
 * Removes simple_mobs firing and AMMO_SCANS_NEARBY. They're defunct/broken.

## Why It's Good For The Game

Hopefully smoother, both performance wise (the bullets were scheduled by sleep(1) constantly) and due to increased visual feedback

## Changelog

:cl:
add: Added a small variation to bullet speed, and slight visual offsets based on clicked location and gun spread.
fix: Decoupled gun and projectile logic which should HOPEFULLY improve on a number of cases of guns breaking.
remove: Removed simple_mob-s shooting logic. It never actually worked with our projectile system.
/:cl:

2022-11-20 13:57 UTC, harryob approved these changes
this certainly looks good for a TM - i'm sure there's edge cases that i can't predict rn that'll come up then

2022-11-23 07:16 UTC, ManoPablo commented
mate, something needs to be done to rockets, it feels awful to use the Sadar while this is being tmerged, please remove the variation on Sadar rockets it throws the aim off bad, and you simply can't lead properly because you don't have a good idea on how fast the rocket is going, if you want to keep that on rockets add a balance tag because it really affects aim on the sadar making it much much harder for even experienced players to aim

2022-11-23 13:41 UTC, fira commented
Rocket speedup was super painful and unreliable to deal with when it came to variable speed and travel carryover so i just removed it entirely, giving them full speed all the time instead...

This impacts two situations:
 - It makes the RPG hit more reliably and slightly faster beyond PB range (max 15-20%) which should fall back in line with people expectations from before
 - It makes admin-spawned thermobaric launcher faster without having to fire offscreen for it, but that's basically never used

2022-11-24 09:59 UTC, Segrain commented on code/modules/projectiles/projectile.dm
> +		if (projectile_flags & PROJECTILE_SHRAPNEL)
```suggestion
		if (!(projectile_flags & PROJECTILE_SHRAPNEL))
```

2022-11-24 13:36 UTC, fira commented on code/modules/projectiles/projectile.dm
> +		if (projectile_flags & PROJECTILE_SHRAPNEL)
OOPS... Good catch

2022-11-25 12:54 UTC, Segrain requested changes

2022-11-25 12:54 UTC, Segrain commented on code/modules/projectiles/ammo_datums.dm
> +	if(M == P.original)
```suggestion
	if((P.projectile_flags & PROJECTILE_HOMING) && (M == P.original))
```

2022-11-25 12:54 UTC, Segrain commented on code/modules/projectiles/ammo_datums.dm
> +	if(M == P.original)
```suggestion
	if((P.projectile_flags & PROJECTILE_HOMING) && (M == P.original))
```

2022-11-25 12:54 UTC, Segrain commented on code/modules/projectiles/ammo_datums.dm
> +	if(M == P.original)
```suggestion
	if((P.projectile_flags & PROJECTILE_HOMING) && (M == P.original))
```

2022-11-25 12:54 UTC, Segrain commented on code/modules/projectiles/ammo_datums.dm
> +	if(M == P.original)
```suggestion
	if((P.projectile_flags & PROJECTILE_HOMING) && (M == P.original))
```

2022-11-25 12:54 UTC, Segrain commented on code/modules/projectiles/ammo_datums.dm
> +	if(M == P.original)
```suggestion
	if((P.projectile_flags & PROJECTILE_HOMING) && (M == P.original))
```

2022-11-26 14:44 UTC, fira commented
The sleep safety net isn't good enough, causing erroring bullets to be stuck in midair. This is a problem because it appears we still have sleeps in `/mob/living/bullet_act` somehow (i suspect heavily `/mob/living/carbon/Xenomorph/apply_damage`)

2022-11-28 15:04 UTC, Segrain commented on code/modules/projectiles/ammo_datums.dm
> +	if(M == P.original)
```suggestion
	if((P.projectile_flags & PROJECTILE_BULLSEYE) && M == P.original)
```
Missed one. Not that it is supposed to be used anyway.

2022-12-02 12:25 UTC, harryob approved these changes
code quality lgtm, still possible there's something being overlooked, but

2022-12-15 19:26 UTC, morrowwolf approved these changes
Code LGTM. Testmerges went well.

2022-12-15 19:26 UTC, merged