Re-added the Rescue Survivors Objective
cmss13-devs/cmss13 pull request #1613
Opened 2022-11-19 10:00 UTC by ThePiachu

## About The Pull Request

I noticed the Rescue Survivors Objective was not around anymore. After checking on Discord whether it was removed on purpose (apparently it was not), I re-added it:

![image](https://user-images.githubusercontent.com/964559/202845366-27077059-355e-44fd-bbc7-9faee0933269.png)

## Why It's Good For The Game

The objective was a neat way to incentivise Survivors to survive for as long as possible and for the Almayer crew not to dilly dally, deploy early and sweep the colony for survivors or their revivable corpses.

## Changelog

:cl:
add: Re-added the old objective of rescuing survivors. Now each survivor rescued alive and brought to Almayer will net the USCM a good deal of points for their Techweb.
/:cl:

2022-11-19 10:04 UTC, Huffie56 commented
If my memory serve me correctly we gain a bit of point for bringing them dead and a lot more if they just came on almayer and after that they could redeploy without loosing the points.

2022-11-22 20:05 UTC, fira requested changes

2022-11-22 20:05 UTC, fira commented on code/modules/objectives/mob_objectives.dm
> +	new /datum/cm_objective/move_mob/almayer/survivor(src)
please remove these if they're otherwise unused

2022-12-09 11:35 UTC, stanalbatross requested changes

2022-12-09 11:35 UTC, stanalbatross commented on code/modules/objectives/mob_objectives.dm
> +/datum/cm_objective/move_mob/New(var/mob/living/H)
var name

2022-12-28 20:14 UTC, merged