Adds SDQL2 and a backend VV refactor
cmss13-devs/cmss13 pull request #1620
Opened 2022-11-19 22:47 UTC by Zonespace27

## About The Pull Request
This PR does two things:

- Adds SDQL, the Structured Datum Query Language.
- Refactors a lot of the back end of VV since SDQL required it

## What is SDQL?

SDQL is a SQL-styled method of acting on large (or small) groups of datums, allowing for massively granular control over mass data collection, VVing, and proc calling.

For example, the following SDQL query is as basic as they get, but very effective:
`SELECT /obj/item/weapon/gun`
Which gets a list of every gun in the world and returns it in a list.
![image](https://user-images.githubusercontent.com/41448081/202874258-7a2f35b6-208f-4b69-820e-6ef297254ab6.png)

Next,
`SELECT /obj/item/weapon/gun WHERE src.x == 101`
Which gets a list of all guns that are at x 101, regardless of y or z.
![image](https://user-images.githubusercontent.com/41448081/202874405-e0de5b7d-a19e-4633-bada-e2d4931d8c85.png)

And finally,
`SELECT /obj/item/weapon/gun WHERE global._istype(src.loc, /turf/open/floor)`
Which will get a list of all guns whose loc is a floor tile.
![image](https://user-images.githubusercontent.com/41448081/202874443-5d01a254-59cb-464d-9dd7-92a4e38b6e0c.png)

But this is just SELECT, you can do fun stuff like:
`CALL gib() ON /mob/living/carbon/human`
Which'll gib everyone at once, fun.

For more details, please see:

- The extensive documentation in SDQL2.dm
- [This document I wrote for /tg/ codebases, that still mostly applies here.](https://hackmd.io/5yrXqD44SYqpzJULxXh5Rg)

## The refactor part

- Cut out a lot of repeat code from VV
- Preventing varedits is now per-type with `vv_edit_var()`

## Why It's Good For The Game
It's more admin tools (especially a very versatile one), and refactors are good

## Changelog

:cl:
admin: Added SDQL2 tools, allowing for more granular mass VV/proc calling/data collecting.
/:cl:

2022-11-22 20:08 UTC, harryob requested changes

2022-11-22 20:08 UTC, harryob commented on code/modules/admin/verbs/SDQL2/SDQL_2.dm
> +	for(var/i in 1 to lenght(input))
linter fail boop

2022-11-22 20:08 UTC, harryob commented on code/modules/admin/verbs/SDQL2/SDQL_2.dm
> +					a = final.loc
```suggestion
					gotten_area = final.loc
```

2022-11-22 21:11 UTC, Zonespace27 commented on code/modules/admin/verbs/SDQL2/SDQL_2.dm
> +	for(var/i in 1 to lenght(input))
```suggestion
	for(var/i in 1 to length(input))
```

2022-11-22 21:11 UTC, Zonespace27 commented on code/modules/admin/verbs/SDQL2/SDQL_2.dm
> +	for(var/i in 1 to lenght(input))
ty

2022-11-30 03:26 UTC, harryob approved these changes
😬 i’m probably still missing something but… i’d like a smidge of TM before merging for sanities sake

2022-12-09 07:47 UTC, Segrain commented on code/modules/admin/callproc.dm
> +/client/proc/callproc_datum(datum/called_datum)
```suggestion
/client/proc/callproc_datum(datum/called_datum as null|area|mob|obj|turf)
```
For whatever reason, Datum ProcCall does not appear on right click menu the way Atom ProcCall did. I know nothing about underlying Byond sorceries here, but any chance this difference between definitions might be responsible?

2022-12-09 22:47 UTC, Podrick-Equus commented
This PR seems to remove some functionality. I can no longer mass edit certain variables to certain values through the VV menu, such as mass editing "Hull = 1" to "Hull = 0"

2022-12-09 22:49 UTC, Zonespace27 commented
> This PR seems to remove some functionality. I can no longer mass edit certain variables to certain values through the VV menu, such as mass editing "Hull = 1" to "Hull = 0"

Unintended (callproc datum too), will look into later today

2022-12-10 09:00 UTC, Segrain commented
Github does not allow suggestions several lines away from code being modified by PR, so left one more in form of the commit above instead (which Github apparently allows allowing to do). Should not break anything.

2022-12-11 05:07 UTC, Zonespace27 commented
> This PR seems to remove some functionality. I can no longer mass edit certain variables to certain values through the VV menu, such as mass editing "Hull = 1" to "Hull = 0"

This bug has been fixed, queries have not yet

2022-12-12 13:56 UTC, fira commented on code/modules/admin/verbs/SDQL2/SDQL_2.dm
> +		CHECK_TICK
Oh yeah that's a good point
Can make this a `stoplag(world.tick_lag)`
This really looks like something that should be controller-backed

2022-12-17 12:23 UTC, harryob requested changes
per silicons, i have faith in their understanding of sdql here

2022-12-21 22:15 UTC, Zonespace27 commented on code/modules/admin/verbs/SDQL2/SDQL_2.dm
> +		CHECK_TICK
resolved

2022-12-31 18:39 UTC, harryob requested changes

2022-12-31 18:39 UTC, harryob commented on code/modules/admin/callproc.dm
> +/client/proc/callproc_datum(datum/called_datum as null|area|mob|obj|turf|datum)
ci fail here btw

2022-12-31 23:53 UTC, Zonespace27 commented on code/modules/admin/callproc.dm
> +/client/proc/callproc_datum(datum/called_datum as null|area|mob|obj|turf|datum)
```suggestion
/client/proc/callproc_datum(datum/called_datum as null|area|mob|obj|turf)
```

2022-12-31 23:53 UTC, Zonespace27 commented on code/modules/admin/callproc.dm
> +/client/proc/callproc_datum(datum/called_datum as null|area|mob|obj|turf|datum)
ty

2023-01-03 17:20 UTC, harryob approved these changes

2023-01-03 17:20 UTC, harryob commented
fuck it

2023-01-03 17:20 UTC, merged