Altered disarm flavor text depending on CQC skill.
cmss13-devs/cmss13 pull request #1628
Opened 2022-11-20 04:06 UTC by carlarctg

## About The Pull Request

As title says. Those with higher CQC skill will now 'tackle' on successful disarm.  Others will randomly 'shove' or 'push'.

## Why It's Good For The Game

Police IRL are trained to tackle suspects. Surely they can do so in CM as well?

## Changelog

:cl:
add: Altered disarm flavor text depending on CQC skill.
/:cl:

2022-11-21 10:41 UTC, harryob commented on code/modules/mob/living/carbon/human/human_attackhand.dm
> +				apply_effect(2 + skill_juice, WEAKEN)
undocumented mr carl arc...???

2022-11-22 00:09 UTC, carlarctg commented on code/modules/mob/living/carbon/human/human_attackhand.dm
> +				apply_effect(2 + skill_juice, WEAKEN)
GUH

2022-11-29 06:37 UTC, morrowwolf requested changes

2022-11-29 06:37 UTC, morrowwolf commented on code/modules/mob/living/carbon/human/human_attackhand.dm
> +			var/skill_juice = M.skills.get_skill_level(SKILL_CQC)
Change this variable name

2022-11-29 06:49 UTC, morrowwolf approved these changes

2022-11-29 06:49 UTC, merged