Facehugger Resprite
cmss13-devs/cmss13 pull request #1639
Opened 2022-11-20 17:12 UTC by kugamo

## About The Pull Request

This PR resprites the playable facehugger, now with creepy crawly animations! Also fixed a runtime when facehuggers tried scuttling under airlocks --> now allowing them to, but without the ability to pounce while doing so _(idk if thats a fix feature or qol but whatever)_.

## Why It's Good For The Game

Higher quality sprites for your viewing pleasure. 🙂 

![image](https://user-images.githubusercontent.com/16618648/202915825-36bdfecd-0a7b-4f3a-b97f-f329913ab640.png)

https://user-images.githubusercontent.com/16618648/202915469-eddc586e-efc1-4a12-952e-50666db69379.mp4

## Changelog

:cl:
imageadd: New playable facehugger sprites, now with creepy crawly animations.
code: Facehuggers can now scuttle under doors, but cannot pounce while doing so; Fixing a runtime.
/:cl:

2022-11-21 16:51 UTC, harryob requested changes

2022-11-21 16:51 UTC, harryob commented on code/modules/mob/living/carbon/xenomorph/abilities/facehugger/facehugger_powers.dm
> +		if(A.density) //if its CLOSED YOU"RE SCUTTLING AND CANNOT POUNCE!!!
```suggestion
		if(A.density) //if its CLOSED YOU'RE SCUTTLING AND CANNOT POUNCE!!!
```

2022-11-21 16:51 UTC, harryob commented on code/modules/mob/living/carbon/xenomorph/abilities/facehugger/facehugger_powers.dm
> +		if(A.density) //if its CLOSED YOU"RE SCUTTLING AND CANNOT POUNCE!!!
CM saved

2022-11-21 16:51 UTC, harryob commented on code/modules/mob/living/carbon/xenomorph/castes/Facehugger.dm
> +	forceMove(S.loc)
```suggestion
/mob/living/carbon/Xenomorph/Facehugger/proc/scuttle(var/obj/structure/current_structure)
	var/move_dir = get_dir(src, loc)
	for(var/atom/movable/atom in get_turf(current_structure))
		if(atom != current_structure && atom.density && atom.BlockedPassDirs(src, move_dir))
			to_chat(src, SPAN_WARNING("\The [atom] prevents you from squeezing under \the [current_structure]!"))
			return
	// Is it an airlock?
	if(istype(current_structure, /obj/structure/machinery/door/airlock))
		var/obj/structure/machinery/door/airlock/current_airlock = current_structure
		if(current_airlock.locked || current_airlock.welded) //Can't pass through airlocks that have been bolted down or welded
			to_chat(src, SPAN_WARNING("\The [airlock] is locked down tight. You can't squeeze underneath!"))
			return
	visible_message(SPAN_WARNING("\The [src] scuttles underneath \the [current_structure]!"), \
	SPAN_WARNING("You squeeze and scuttle underneath \the [current_structure]."), null, 5)
	forceMove(current_structure.loc)
```

i love descriptive var names

2022-11-21 16:52 UTC, harryob requested changes

2022-11-21 16:52 UTC, harryob commented on code/modules/mob/living/carbon/xenomorph/abilities/facehugger/facehugger_powers.dm
> +		if(A.density) //if its CLOSED YOU"RE SCUTTLING AND CANNOT POUNCE!!!
```suggestion
	for(var/obj/structure/machinery/door/airlock/current_airlock in get_turf(owner))
		if(current_airlock.density) //if its CLOSED YOU'RE SCUTTLING AND CANNOT POUNCE!!!
```
i forgor

2022-11-22 01:23 UTC, monkeysfist101 approved these changes
Disgusting. Approved.

2022-11-22 09:49 UTC, LoJoFan commented
https://user-images.githubusercontent.com/112346996/203282026-6a7f5181-2edf-4751-9b49-b1cf50907c8a.mp4

2022-11-23 22:29 UTC, merged