More automobiles
cmss13-devs/cmss13 pull request #1642
Opened 2022-11-20 20:44 UTC by Lengord

Added direction sprites for old car sprites and one new, and made them actual vehicles to drive them.

## About The Pull Request
I still had sprites from Cakey request for vehicles sprites, so why not to try. Copy-pasted some code, seems work ok'ish, you can drive them atleast. Also added cramped interriors for them.
Issues: 
1) When hardpoint damaged badly on treads it looks like one large black spot
2) After vehicle broken overlay updates only when you install new hardpoint or wrench it to 100%
3) Still moves after wheels hardpoint broken
4) Probably it unbalanced
5) Can't make spawner preset to choose different vehicle icons if it is available
(coding not my thing 100% i messed stuff, if you can do code, please!!! do)

## Why It's Good For The Game

If it's bad for game atleast can be used for existing props, or for events. 

## Changelog

:cl:

add: Added more vehicles to drive, and interrior maps
imageadd: added direction sprites for some vehicles

/:cl:

2022-11-20 21:37 UTC, monkeysfist101 approved these changes
Sprites LFTM

2022-11-20 22:49 UTC, harryob requested changes

2022-11-20 22:49 UTC, harryob commented on code/modules/vehicles/truck/civvan.dm
> +	desc = "A rather cheep hunk of metal with some wheels, you know what to do. Entrance on the sides."
cheap

2022-11-20 22:49 UTC, harryob commented on code/modules/vehicles/truck/civtruck.dm
> +	desc = "A rather cheep hunk of metal with some wheels, you know what to do. Entrance on the sides."
cheap

2022-11-20 22:49 UTC, harryob commented on code/modules/vehicles/truck/crane.dm
> +	desc = "A rather cheep hunk of metal with some treads, you know what to do. Entrance on the left side."
cheap

2022-11-21 03:51 UTC, Diegoflores31 commented on code/modules/vehicles/truck/civvan.dm
> +	desc = "A rather cheep hunk of metal with some wheels, you know what to do. Entrance on the sides."
typos are soul . CHEEP CAR

2022-11-29 04:33 UTC, ThePiachu requested changes
Okay, a few things:

1) Please rebase since I'm getting a black screen when trying to run this
2) I don't think the new vehicle files were included in the .dme so you can't test them as is
3) I think all the trucks start without wheels and you can't use the van wheels on them to repair them, so maybe it would be good to at least get the cars working by default, and maybe have broken down versions as a sub-type

Otherwise, I like the idea of having more civilian vehicles. Maybe one day we could have something to transport actual cargo and all! So even if we don't use them straight away, it would be nice to have them.

2022-11-29 11:24 UTC, closed without merging