Added a super snowflake vendor for devs and admins to play with
cmss13-devs/cmss13 pull request #1648
Opened 2022-11-21 03:34 UTC by ThePiachu

## About The Pull Request

I was doing some work on picking a set of clothes for a fun ERT when I realised we could use a vendor for admins / devs to figure out what kind of items look good together and so on before they spawn a bunch of mobs with them. So I added a few Super Snowflake Vendors that have all the items of a given type in them. The UI is a bit slow due to the number of items, and when I tried putting all of the items together into one vendor it lagged out the game, so I split them up into separate types.

## Why It's Good For The Game

It makes it easier to match interesting outfit combinations for ERTs and what have you. This can let admins communicate more clearly what they might want in a gear preset, and for devs to easier test how things look together.

## Changelog

:cl:
add: Added a set of Super Snowflake Vendors for admins and devs to play with.
/:cl:

2022-11-22 20:37 UTC, fira commented
I like the idea already but lemme put forward one even more crazy:
What if instead this was a blank vendor, and the adding functionality was a tool/verb rather than thru usage? So you can use it multiple times to make a custom vendor.
Might even be extended to other vendors, though i don't think most would support this properly...

2022-11-24 08:15 UTC, ThePiachu commented
Okay, so I changed the vendor like this:

1) It takes a list of objects in now, so it would be easy to dynamically make a vendor on the map or something
2) Admins got a verb to add items to the vendor, so they can create an empty vendor and populate it with stuff they want to give to people

This should be enough to make a custom vendor on the fly and have it dispense the needed items.

Not sure how we're handling such admin verbs, should it be in this file or somewhere else...

2022-12-02 12:18 UTC, ThePiachu commented
So @fira - is this how you wanted the vendor to function, or should I use some kind of different setup for admin adding new things to it?

2022-12-09 11:19 UTC, harryob approved these changes

2022-12-12 05:49 UTC, harryob requested changes

2022-12-12 05:49 UTC, harryob commented on code/game/machinery/vending/vendor_types/dress.dm
> +		to_world("item_types - [item_types.len]")
debug?

2022-12-12 08:42 UTC, ThePiachu commented on code/game/machinery/vending/vendor_types/dress.dm
> +		to_world("item_types - [item_types.len]")
debug...

2022-12-17 11:11 UTC, harryob approved these changes

2022-12-17 11:20 UTC, harryob requested changes
seems like every item is out of stock - regardless of if you use a preset vendor or add to one yourself?

2022-12-17 12:30 UTC, ThePiachu commented
Ah, my mistake, had to make it "use points" while still keeping everything at 0 points. Should be good now.

2022-12-17 13:11 UTC, harryob submitted a review, later dismissed
apologies - missed this the first time around: but if a type is selected with subtypes, every subtype is also added, and it's not possible to just add the specific type suggested, as far as i can tell. is this intentional?

2022-12-17 13:41 UTC, harryob approved these changes

2022-12-17 13:41 UTC, merged