Mapping fix shiva snow ball
cmss13-devs/cmss13 pull request #1680
Opened 2022-11-23 19:25 UTC by Huffie56

## About The Pull Request
-removed a door in the middle of an office
-remove a door in a room leading to a wall and replace it with a wall.

## Why It's Good For The Game
Removing items that are out of place is good

## Changelog

:cl:
del: Removed old things
/:cl:

2022-11-23 19:52 UTC, fira commented
The first is clearly a `fix` not `del`, though i'm not sure about second

2022-11-23 19:53 UTC, fira requested changes

2022-11-23 19:53 UTC, fira commented on maps/map_files/Ice_Colony_v3/Shivas_Snowball.dmm
> -	name = "Architectural oversight";
Yeah you can see in the name that this one is intended

2022-11-25 08:52 UTC, Huffie56 commented
no point doing a PR for one door....

2022-11-25 08:52 UTC, closed without merging