Warrior Knight Strain
cmss13-devs/cmss13 pull request #1683
Opened 2022-11-23 21:29 UTC by carlarctg

## About The Pull Request

https://hackmd.io/_GMmQVHvQESXPBlDFlTPfw?view

TL;DR: Warrior strain meant to focus on frontline combat. NEEDS SPRITES

Ability videos: coming soon

## Why It's Good For The Game

New strains good.

## Changelog

:cl:
add: Added a new warrior strain. Knight. Focuses on frontline combat.
/:cl:

2022-12-20 21:01 UTC, carlarctg commented
https://streamable.com/5dp68c

2022-12-25 03:52 UTC, carlarctg commented
I think it would be really cool if someone reviewed or testmerged this in less than a month after this comment. I think that would be really awesome!

2022-12-31 21:31 UTC, morrowwolf requested changes
Bugs and comments as per the PR-Feedback thread.

2023-03-15 17:18 UTC, harryob requested changes

2023-03-15 17:18 UTC, harryob commented on code/modules/mob/living/carbon/xenomorph/abilities/warrior/warrior_powers.dm
> +	return
is there a reason you're not returning ..()?

2023-03-15 17:18 UTC, harryob commented on code/modules/mob/living/carbon/xenomorph/abilities/warrior/warrior_powers.dm
> +	if(zenomorf.mutation_type != WARRIOR_KNIGHT) //why do we need these checks again? it's not like it wouldnt be a bug that needs looking into if they didnt exist. if anything this removes helpful runt
honestly i hate sanity checks

2023-03-15 17:18 UTC, harryob commented on code/modules/mob/living/carbon/xenomorph/abilities/warrior/warrior_powers.dm
> +		SPAN_DANGER("You try to [picked_attack_verb] [Knight] with \the [hitting_item], but your attack bounces right off its defensive shield!"), message_flags = CHAT_TYPE_MELEE_HIT)
```suggestion
		attacker.visible_message(SPAN_DANGER("[attacker] tries to [picked_attack_verb] [Knight] with [hitting_item], but the attack bounces right off its defensive shield!"),\
		SPAN_DANGER("You try to [picked_attack_verb] [Knight] with [hitting_item], but your attack bounces right off its defensive shield!"), message_flags = CHAT_TYPE_MELEE_HIT)
```

2023-03-15 17:18 UTC, harryob commented on code/modules/mob/living/carbon/xenomorph/mutators/strains/warrior/knight.dm
> +		bound_xeno.visible_message(SPAN_DANGER("\The [bound_xeno] begins faintly glowing purple."), SPAN_NOTICE("Tendrils from your hive's weeds connect you to the hive's psychic power. Your abilities are
```suggestion
		bound_xeno.visible_message(SPAN_DANGER("[bound_xeno] begins faintly glowing purple."), SPAN_NOTICE("Tendrils from your hive's weeds connect you to the hive's psychic power. Your abilities are now enhanced."))
```

2023-03-15 17:18 UTC, harryob commented on code/modules/mob/living/carbon/xenomorph/mutators/strains/warrior/knight.dm
> +	color += num2text(alpha, 2, 16)
shouldn't you just be assigning color here?

2023-03-15 17:18 UTC, harryob commented on code/modules/mob/mob.dm
> +
i know you're not by the absence of code touching it!!!!

2023-03-15 22:18 UTC, ondrej008 commented
I'm not sure whether we're supposed to use the forums, discord or this, so I'm doing it here.

1. Bug: The Pike ability seems to be silver colored on every tile.

2. What is the point of a frontline strain that gets stronger when fighting on weeds? I have never seen the frontline be on weeds, only time I can think of is when xenos are losing by a landslide and marines are a couple minutes from ending the round.

2023-03-17 09:41 UTC, cm13-github commented
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
CM13 Live Instance

##### Revision
Origin: 6a2cf07b91be24fbcbc651e8a46a8ae6445dd924
Pull Request: c70fbbd74bfa6b719cb80d8c2bae3e5a37bf9e13
Server: 0f1dac4dcb22794ac0797cee8eb9c5b0b7c5e7f8

##### Comment

</details>

2023-03-17 14:37 UTC, cm13-github commented
#### Test Merge Removed

2023-04-09 00:27 UTC, closed without merging