Feral tuning, burrower tremor can stun enemy xenos.
cmss13-devs/cmss13 pull request #1684
Opened 2022-11-24 01:00 UTC by carlarctg

## About The Pull Request

Added a new define for when nobody can designate hive structures, used for the feral hive to give them a proper indicator that it's intentional they can't make structures.

Ferals' initial T3 is now a hive leader.

Burrower tremor is able to stun enemy small xenos. Enemy large xenos will be slowed for a second.

## Why It's Good For The Game

Burrower's ability not affecting enemies is bad. Ferals seeing 'only qeuen can do this' when they cant get a queen is stupid. Ferals having a leader is cool.

## Changelog

:cl:
fix: Fixed burrower tremor not working on enemy xenos. Only slows large xenos.
add: Ferals get a hive leader now.
/:cl:

2022-12-01 10:43 UTC, ThePiachu approved these changes

2022-12-01 10:44 UTC, ThePiachu requested changes

2022-12-01 10:44 UTC, ThePiachu commented on code/game/objects/effects/aliens.dm
> +				M.apply_armoured_damage(damage_amount * XVX_ACID_DAMAGEMULT, ARMOR_BIO, BURN) // Deal extra damage when first placing ourselves down.
Undocumented change!

2022-12-02 06:12 UTC, carlarctg commented on code/game/objects/effects/aliens.dm
> +				M.apply_armoured_damage(damage_amount * XVX_ACID_DAMAGEMULT, ARMOR_BIO, BURN) // Deal extra damage when first placing ourselves down.
oversight

2022-12-02 22:48 UTC, ThePiachu approved these changes

2022-12-02 22:48 UTC, merged