adds a number (4) of tgs commands
cmss13-devs/cmss13 pull request #1689
Opened 2022-11-24 13:31 UTC by harryob

## About The Pull Request

adds @[botname] check, gameversion, testmerges and (admin only) status

## Why It's Good For The Game

uhh you can check some game data without being in game

## Changelog

:cl:
server: added new discord commands: check, gameversion, testmerges and status (for admins). check what these do with the help command
/:cl:

2022-11-24 13:35 UTC, fira commented
dont game ver & testmerges kinda double up?

2022-11-24 13:55 UTC, harryob commented
> dont game ver & testmerges kinda double up?

<img width="1042" alt="CleanShot 2022-11-24 at 13 50 57@2x" src="https://user-images.githubusercontent.com/55142896/203800961-d243cfb8-f061-4872-b143-d64e43556b58.png">
i figured the top two lines are kinda useless data if someone's just looking for testmerges - but i'm not particularly sold either way, can be ditched to avoid bloating our commands

2022-11-24 15:20 UTC, Zonespace27 commented on code/modules/discord/tgs_commands.dm
> +	var/message = "\
same here

2022-12-11 14:16 UTC, fira requested changes

2022-12-11 14:16 UTC, fira commented on code/modules/discord/tgs_commands.dm
> +/datum/tgs_chat_command/gameversion/Run(datum/tgs_chat_user/sender, params)
harry you didn't reanme the proc when copypasting it

2023-04-11 00:27 UTC, closed without merging