Changes the PR template.
cmss13-devs/cmss13 pull request #1698
Opened 2022-11-25 15:11 UTC by AnCopper

# Document the changes in your pull request.

Revises PR template to adding a testing and issue closer section.

Maintainability starts with the PR.

# Explain why it's good for the game.

Not user facing.

QOL for longer term DevOps. When dealing with unexpected behaviors in the wild, knowing if it is intended can be helpful in some cases.
Moreover, it provides a place for testing/images to be present without getting lost in long lines of commits/comments/etc.

This would also allow for a seamless way to keep a one stop place for documentation in cases of larger PRs.

# Testing Photographs and Procedure

<details>
<summary>![image](https://user-images.githubusercontent.com/82319489/204013285-7bb1e1ee-9368-41f2-addc-de211920cadc.png)</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl: Bilary
server: Revised the PR Template
/:cl:

2022-11-25 20:51 UTC, morrowwolf requested changes

2022-11-25 20:51 UTC, morrowwolf commented on .github/PULL_REQUEST_TEMPLATE.md
> +Prefix the PR title with [s] if you are fixing an exploit, so that it is not announced on the Yogstation Discord and the server.
bro, at least check your copy pastes.

2022-11-25 20:51 UTC, morrowwolf commented on .github/PULL_REQUEST_TEMPLATE.md
> +If you add a name after the ':cl', that name will be used in the changelog. Leave it empty to use your GitHub name. Be sure to properly mark your PRs to prevent unnecessary GBP loss. Maintainers free
This is mandated for CM. You must add your CKEY after the CL if your github name doesn't match.

2022-11-25 20:51 UTC, morrowwolf commented on .github/PULL_REQUEST_TEMPLATE.md
> +# Document the changes in your pull request.
Keep this as "about the pull request"

2022-11-25 20:51 UTC, morrowwolf commented on .github/PULL_REQUEST_TEMPLATE.md
> +<!-- Edit the changelog below to reflect the changes made by this PR, even if the changes are minor - required for every PR.
Keep the original line here

2022-11-26 02:29 UTC, fira reviewed
I just lost 3 days worth of zen budget reading non-sentence titles inconsistently ended with full stops.

2022-11-26 02:29 UTC, fira commented on .github/PULL_REQUEST_TEMPLATE.md
> +Prefix the PR title with [s] if you are fixing an exploit, so that it is not announced on the CMSS13 Discord and the server.
Do we actually have this in our tooling or is this just copypasting?

2022-11-26 03:37 UTC, morrowwolf commented on .github/PULL_REQUEST_TEMPLATE.md
> +Prefix the PR title with [s] if you are fixing an exploit, so that it is not announced on the CMSS13 Discord and the server.
Pretty sure it's just copy pasta.

2022-11-27 11:31 UTC, Unknownity commented
Changelog is not required, no player facing changes.

2022-12-03 00:36 UTC, harryob requested changes

2022-12-03 00:36 UTC, harryob commented on .github/PULL_REQUEST_TEMPLATE.md
> +Remember: something that is self-evident to you might not be to others. Explain your rationale fully, even if you feel it goes without saying.-->
```suggestion
Remember: something that is self-evident to you might not be to others. Explain your rationale fully, even if you feel it goes without saying. -->
```

2022-12-03 00:42 UTC, harryob commented
if this bugs someone enough they can make a new new PR template but i like this and i like mandated testing

2022-12-03 00:42 UTC, merged