Adds a preference for vendors vending directly into your hand.
cmss13-devs/cmss13 pull request #1766
Opened 2022-11-29 18:29 UTC by NoKohi

## About The Pull Request

This adds a preference (should be on by default) for vendors vending items directly into your hand when applicable. Toggling it off means you no longer have items vend into your hands.

## Why It's Good For The Game

Originally I wasn't going to PR this, but Stan said he'd be fine with it. A few people were complaining about the recent QOL change by ThePiachu, which gave vendors the VEND_TO_HAND flag. This preference lets those people have the option of doing things the old way. This is consistent with other preferences, and it's nice to let people have the option.

## Changelog

:cl:
qol: added a "Toggle Vendors Vending to Hands" to preferences
/:cl:

2022-11-30 11:12 UTC, ThePiachu commented
Some people don't know what's good for them. I'd almost want to wait a week before a change like this gets brought up to see if people don't start enjoying it after being exposed to it. There are often kneejerk reactions to any changes...

That being said, the code looks fine, tested it, it works, so have an approval...

2022-11-30 11:12 UTC, ThePiachu approved these changes

2022-12-01 12:25 UTC, fira commented
Uh hold on. This migration will only be applied to old savefiles right? What about new players?

2022-12-01 12:26 UTC, fira requested changes
Uh hold on. This migration will only be applied to old savefiles right? What about new players?

2022-12-01 18:00 UTC, NoKohi commented
> Uh hold on. This migration will only be applied to old savefiles right? What about new players?

you know I think I hallucinated adding that flag there because I actually went to that line when writing this and thought I modified it

i'm losing it

2022-12-10 12:28 UTC, fira approved these changes

2022-12-12 04:43 UTC, merged