More automobiles (reupload)
cmss13-devs/cmss13 pull request #1789
Opened 2022-12-01 13:56 UTC by Lengord

## About The Pull Request
I still had sprites from Cakey request for vehicles sprites, so why not to try. Copy-pasted some code, seems work ok'ish, you can drive them atleast. Also added cramped interriors for them. (i broke it, so reupload)

## Why It's Good For The Game
If it's bad for game atleast can be used for existing props, or for events. 

## Changelog

:cl:
add: Added more vehicles to drive, and interrior maps
imageadd: Added direction sprites for some vehicles
code: Changed some code
/:cl:

2022-12-01 16:57 UTC, harryob commented
make sure your changelog is descriptive as to what you're actually changing - not just changed some code

2022-12-08 16:20 UTC, Nanu308 reviewed
mapping lgtm

2022-12-28 22:56 UTC, stanalbatross requested changes

2022-12-28 22:56 UTC, stanalbatross commented on code/modules/vehicles/hardpoints/wheels/locomotion.dm
> +	return (new I(loc))
would be easier and better OOP wise to make this a subtype of spawner/random

2022-12-28 22:56 UTC, stanalbatross commented on code/modules/vehicles/hardpoints/wheels/truck.dm
> +	name = "Military wheels"
```suggestion
	name = "military wheels"
```
names need to be lower case

2022-12-28 22:56 UTC, stanalbatross commented on code/modules/vehicles/hardpoints/wheels/truck.dm
> +	name = "Crane treads"
same with all these names

2022-12-28 22:56 UTC, stanalbatross commented on code/modules/vehicles/truck/civtruck.dm
> +	name = "Civilian truck"
same

2022-12-28 22:56 UTC, stanalbatross commented on code/modules/vehicles/truck/civvan.dm
> +	name = "Civilian van"
same and for all other added names

2023-01-06 23:59 UTC, stanalbatross approved these changes
code good

2023-01-16 04:12 UTC, nauticall requested changes
![image](https://user-images.githubusercontent.com/55491249/212597120-6ef92e09-6e74-4b10-9a9f-1ae2a9f65eaa.png)
The only thing preventing me from giving my stamp is this van -- it's too bright red. Make it a darker red, get back to me, and we can get this baby finally merged aight?

2023-01-24 00:30 UTC, closed without merging