dir locking now slows you down
cmss13-devs/cmss13 pull request #179
Opened 2022-04-30 13:00 UTC by stanalbatross

Changing directional lock

## About The Pull Request
Changes how directional locking works so it adds a slowdown when you are directional locked.

## Why It's Good For The Game

Direction lock needs a drawback as plenty of people just do it for no apparent reason except to make their sprite smaller and so forth. It also makes little sense you can sprint backwards at full speed without issue and shoot etc. which leads to gameplay immersion being broken.

This PR intends to change it so direction locking no longer is only, or rather, more used to permaface a certain direction by adding a slowdown when you are directional locked.

## Changelog

:cl: nanu308, stan_albatross
balance: being direction locked will now slow you down a bit.
/:cl:

2022-04-30 13:19 UTC, hotimep commented
sucks

2022-04-30 13:55 UTC, FlamermanGrills commented
Depending on how much the slow is I’m sure heavy armor users will like another slow added to them

2022-05-01 16:03 UTC, Chainsawicus commented
Your reasoning for why it's "good for the game" make no sense to me. When direction-locking you are locking your sprite into one consistent unchanging sprite, meaning there's less variation to where your clickable area can be, which makes you _easier_ to click, rather than harder to click.

Better to just remove direction locking entirely than give it drawbacks for no real reason, half-measures like this leave nobody happy and are questionable at best.

2022-05-01 23:15 UTC, c4xmaniac commented
Kind of a silly nerf, the pounce resist buff only basically just matters to preds, synths, and GL armor. Just remove dir lock and make the pounce resist 360 degrees, it doesn’t really matter.

2022-05-02 00:19 UTC, Carnage068 commented
Uh, how much is 'a bit'? I don't really like direction lock, (it looks silly in a way that's barely even funny), but I don't want to see it gutted. Also this is going to make Crusher automatically slow itself after using its charge, unless that's an intended nerf.

2022-05-02 09:29 UTC, stanalbatross commented
please direct all concerns to nanu308 as this PR was made on his request after coming to a compromise of not removing dirlock

2022-05-04 07:46 UTC, ghostsheet commented
Not removing is dir-lock is good for directional based things like setting up bidpods and binocs,
Adding a slow removes the Warrior BS of locking north face so no one can tell if it's a normal warrior or a boxer (and waste 3 stuns on it)
so good enough for me

2022-05-04 20:43 UTC, trustscience1111 commented
The reason to use this as xeno is so you do not click your own hands when tackling a marine.  So that the bright yellow dots as lurker don't show where you are. The sprite is either effortless to see facing forward, or difficult without the yellow highlighting dots creating contrast. Stealth nerf really. As Chainsaw said the idea behind this makes no sense. Please state out logical points to how this is actually meaningful.

2022-05-04 23:08 UTC, Carnage068 commented
> The reason to use this as xeno is so you do not click your own hands when tackling a marine. So that the bright yellow dots as lurker don't show where you are. The sprite is either effortless to see facing forward, or difficult without the yellow highlighting dots creating contrast. Stealth nerf really. As marine this is not as important. As Chainsaw said the idea behind this makes no sense. Please state out logical points to how this is actually meaningful.
> 
> " plenty of people just do it for no apparent reason except to".
> 
> Tell me you don't play xeno, without telling me you don't play xeno.



> The reason to use this as xeno is so you do not click your own hands when tackling a marine. So that the bright yellow dots as lurker don't show where you are. The sprite is either effortless to see facing forward, or difficult without the yellow highlighting dots creating contrast. Stealth nerf really. As marine this is not as important. As Chainsaw said the idea behind this makes no sense. Please state out logical points to how this is actually meaningful.
> 
> " plenty of people just do it for no apparent reason except to".
> 
> Tell me you don't play xeno, without telling me you don't play xeno.

I've pretty much never clicked my own hands while tackling or slashing someone, much less have I seen anyone using directional facing when slashing or tackling someone. The ONLY time I see xenos use it is when they're running away or running towards somebody, which coincidentally, happens at the same time they're being fired at.

As for Lurker, they're not disabling direction facing altogether. You can still use it on them to avoid being seen by marines. Also, I see marines sometimes randomly using it too, and since it doesn't really change their hitbox/clickbox or whatever, I really have no idea why they do it, lol.

2022-05-05 22:26 UTC, trustscience1111 commented
> > The reason to use this as xeno is so you do not click your own hands when tackling a marine. So that the bright yellow dots as lurker don't show where you are. The sprite is either effortless to see facing forward, or difficult without the yellow highlighting dots creating contrast. Stealth nerf really. As marine this is not as important. As Chainsaw said the idea behind this makes no sense. Please state out logical points to how this is actually meaningful.
> > " plenty of people just do it for no apparent reason except to".
> > Tell me you don't play xeno, without telling me you don't play xeno.
> 
> > The reason to use this as xeno is so you do not click your own hands when tackling a marine. So that the bright yellow dots as lurker don't show where you are. The sprite is either effortless to see facing forward, or difficult without the yellow highlighting dots creating contrast. Stealth nerf really. As marine this is not as important. As Chainsaw said the idea behind this makes no sense. Please state out logical points to how this is actually meaningful.
> > " plenty of people just do it for no apparent reason except to".
> > Tell me you don't play xeno, without telling me you don't play xeno.
> 
> I've pretty much never clicked my own hands while tackling or slashing someone, much less have I seen anyone using directional facing when slashing or tackling someone. The ONLY time I see xenos use it is when they're running away or running towards somebody, which coincidentally, happens at the same time they're being fired at.
> 
> As for Lurker, they're not disabling direction facing altogether. You can still use it on them to avoid being seen by marines. Also, I see marines sometimes randomly using it too, and since it doesn't really change their hitbox/clickbox or whatever, I really have no idea why they do it, lol.

why even respond to me if you are going to argue yellow / black contrast is NOT easier to see than black / black contrast, you don't exist in the same reality we do, however for us humans here on earth, contrasted movement is a major part of how our eyes actually fucking work, in real life and staring at a monitor. 
Sorry if you are color blind.

its the same reason intelligent capable scouts do this shit. Does it affect people who do not understand? yes, even if they don't understand or realize it, because we all have the same fucking eyeballs.   

"and since it doesn't really change their hitbox/clickbox or whatever, I really have no idea why they do it, lol." 

You failed to provide a single point for the shit you are for.  no idea at all? i gave you one example. try spending a few minutes of your time thinking instead of replying with 'i dont know lol why do this'. this isnt reddit , actual wtf moment response.

2022-05-05 23:31 UTC, Carnage068 commented
> why even respond to me if you are going to argue yellow / black contrast is NOT easier to see than black / black contrast, you don't exist in the same reality we do, however for us humans here on earth, contrasted movement is a major part of how our eyes actually fucking work, in real life and staring at a monitor. Sorry if you are color blind.
> 
> Oh the giant fucking sprites doesn't cover up the other tiles. What sprites are you using? Sure it will take longer. How is taking longer not a nerf? Directional slashing....
> 
> its the same reason intelligent capable scouts do this shit. Does it affect people who do not understand? yes, even if they don't understand or realize it, because we all have the same fucking eyeballs.
> 
> "and since it doesn't really change their hitbox/clickbox or whatever, I really have no idea why they do it, lol."
> 
> You failed to provide a single point for the shit you are for. no idea at all? i gave you one example. try spending a few minutes of your time thinking instead of replying with 'i dont know lol why do this'. this isnt reddit , actual wtf moment response.

When the hell did I try to make the argument that black/black is harder to see than yellow/black? Also since when did Lurker, Sentinel, Drone, and Runner have giant sprites? What game are you playing? What the fuck are you even responding to? I didn't say ANYTHING about Lurkers. 

What's your problem with directional slashing, exactly? It feels accurate enough for me whenever I use it. It's definitely easier than trying to click on the tiny marine sprites, especially if you're a faster caste. Just saying 'Directional slashing...' and quite literally nothing else doesn't really give me a clear idea of how you feel about using it, or if you even hate the mechanic at all.

I did give a point, sort of. As I said, I've never seen a Xeno using directional facing for the purpose you're speaking of. Most people use directional slashing, so clicking on their own hands while trying to tackle someone isn't even an issue for them. Even if you DON'T use directional slashing while using directional facing, the second you click on a tile that's facing a different direction than the one you're facing, it will reset it, so I REALLY don't understand how this is such a vital strategy that's integral to the game, especially if you're the only one or even one of the only few people using it.

Also, where the FUCK did you give me an 'example' of marines using directional facing for a reason other than no reason at all? You haven't made a case for marines using directional facing AT ALL. Why the hell are you even trying to defend them? I thought you were upset about xenos getting nerfed, and not marines getting nerfed??? I don't get it, dude, I really don't. You almost seem like you're replying to things I never even said in the first place, and I don't really know what to say to that, sorry, lol.

2022-05-09 20:27 UTC, Geevies requested changes
slap in that code i gave you

2022-05-09 21:33 UTC, stanalbatross commented
> slap in that code i gave you

was slapped in earlier

2022-05-11 09:48 UTC, IngloriouslyBad commented
I use directional lock as marine as a nervous tick derived from the directional sight and lighting days. You'd walk back to back with your buddy towards your objective and light up a small 360 degrees area around the 2 of you as best as you can and quickly as you can while trying to stay in lockstep with eachother and not break formation. It's fun to use it to backpedal following behind a buddy dragging a downed marine and yell, GOGOGO I'll cover ! As you literally cover the retreat.

Removing it or punishing players for it seems sad, especially when it's only abused by a handful of people who try to game the system and sweatlord by hiding their pixels or whatever

2022-05-14 09:25 UTC, Geevies commented on code/modules/mob/mob.dm
> +			flags_atom &= ~DIRLOCK
afaik this isn't necessary because the above is a removal, not a toggle

2022-05-14 09:28 UTC, Geevies requested changes

2022-05-14 09:28 UTC, Geevies commented on code/modules/mob/mob_movement.dm
> +			move_delay += MOVE_REDUCTION_DIRECTION_LOCKED //by geeves
```suggestion
			move_delay += MOVE_REDUCTION_DIRECTION_LOCKED // by Geeves
```

2022-05-14 10:38 UTC, Geevies approved these changes

2022-05-14 10:39 UTC, merged

2022-05-15 03:00 UTC, Pyrodes commented
fucked up :dread: