Adds an extremely simple ingame netspeak notifier.
cmss13-devs/cmss13 pull request #1790
Opened 2022-12-01 16:36 UTC by AnCopper

## About The Pull Request

Sends a notification to the player when they engage in netspeak.

## Why It's Good For The Game

It's better than nothing.

https://streamable.com/jqh8q3

## Changelog

:cl:
server: Added an ingame netspeak notifier.
/:cl:

2022-12-01 18:37 UTC, stanalbatross requested changes

2022-12-01 18:37 UTC, stanalbatross commented on code/modules/mob/living/say.dm
> +	var/static/regex/netspeak = regex("\\b(lol|brb|wtf|lmao|sus|kek|idk|omg)\\b", "i")
No, the lowercase letter i is not netspeak

2022-12-01 18:37 UTC, stanalbatross commented on code/modules/mob/living/say.dm
> +	var/static/regex/netspeak = regex("\\b(lol|brb|wtf|lmao|sus|kek|idk|omg)\\b", "i")
Also this should pull from a list in a config file probably

2022-12-01 18:37 UTC, stanalbatross commented on code/modules/mob/living/say.dm
> +		to_chat(src, "<span class='warning'>Netspeak is not permitted in character!</span>")
<span> tags are not used in CM
We use macros such as SPAN_WARNING()

2022-12-07 16:49 UTC, harryob requested changes
also generally needs usage of the configuration datum to toggle on/off

2022-12-25 00:29 UTC, closed without merging