Added admin-only knife that makes you run faster.
cmss13-devs/cmss13 pull request #1821
Opened 2022-12-02 20:28 UTC by carlarctg

## About The Pull Request

Added admin-only knife that makes you run faster.

## Why It's Good For The Game

> Added admin-only knife that makes you run faster.

 My heart's beating, my hand's are shaking, but I'm STILL SHOOTING, and I'm STILL GETTING HEADSHOTS.

https://www.youtube.com/watch?v=olm7xC-gBMY

## Changelog

:cl:
add: Added admin-only knife that makes you run faster.
/:cl:

2022-12-06 04:28 UTC, harryob requested changes

2022-12-06 04:28 UTC, harryob commented on code/modules/projectiles/gun_attachables.dm
> +		var/rng =  rand(0, 100)
```suggestion
		var/rng = rand(0, 100)
```
don't worry guys just saved CM again

2022-12-08 10:21 UTC, harryob requested changes

2022-12-08 10:21 UTC, harryob commented on code/modules/projectiles/gun_attachables.dm
> +	 /// You run faster with a knife!
```suggestion
	/// You run faster with a knife!
```

2022-12-09 05:56 UTC, monkeysfist101 commented
Denying on the grounds that it’s a meme addition that has no use beyond, “haha CS:GO knife.”

2022-12-09 05:56 UTC, closed without merging