Cinematic Crit
cmss13-devs/cmss13 pull request #1841
Opened 2022-12-04 16:10 UTC by Geevies

# About the pull request

You can now hear people talking around you if you're in knocked-out, but only if they're right next to you. You can now talk while knocked-out, but you can only whisper. You cannot use the radio when speaking this way. Your sound environment changes when you're knocked out, making things sound more spooky. Stuttering no longer destroys your words.

Ported the stuttering code from: https://github.com/Aurorastation/Aurora.3/pull/7344 (not the markup fixes though, out of scope)

# Explain why it's good for the game

It makes the knocked-out experience way less painful by letting you at least talk to people to some degree, but only if they're right up against you, making it much more cinematic and meaningful.

Also obliterates the stupid stuttering because H-H-H-H, while funny, EXTREMELY funny, does get old after a while.

# Testing Photographs and Procedure

images taken before the stuttering port, and i'm not launching two clients again

![image](https://user-images.githubusercontent.com/22774890/205501956-a5109d1e-2eaa-478f-8e45-791aa2eb329b.png)
![image](https://user-images.githubusercontent.com/22774890/205501959-ac937f82-3663-4dc2-921d-72a6dd076339.png)

# Changelog

:cl:
add: You can now whisper while knocked out, but cannot use the radio this way.
add: You can now hear what people are saying while knocked out, but only if they're adjacent you.
add: Getting knocked-out now changes the sound environment to reflect your brain getting blasted.
add: Ported a change to stuttering which makes it less H-H-H-like.
/:cl:

2022-12-05 01:49 UTC, ihatethisengine commented
>says softly
I think you need to change it for knocked-out

2022-12-05 07:19 UTC, Merrgear commented
we have to manually He he helpa now. bad PR ban geeves for life

2022-12-06 12:22 UTC, Googles-Hands commented
Does the knocked out state include the normal sleep/chemically induced sleep state or just the crit state, because if it's both, thats a bit weird, you shouldn't be able to hear perfectly/whisper while asleep.

2022-12-08 10:56 UTC, harryob requested changes

2022-12-08 10:56 UTC, harryob commented on code/__HELPERS/type2type.dm
> +	while (found)
```suggestion
	while (found)
		found       = findtext(text, delimiter, last_found, 0)
		.          += copytext(text, last_found, found)
		last_found  = found + delim_len
```
goofy ass proc

2022-12-21 22:01 UTC, stanalbatross submitted a review, later dismissed

2023-01-05 00:28 UTC, closed without merging