D2 breaching hammer
cmss13-devs/cmss13 pull request #1859
Opened 2022-12-06 04:05 UTC by BeagleGaming1

# About the pull request

Admin Spawn item
A breaching hammer that is usable by marines.

# Explain why it's good for the game

Allows breaching hammers to be given to marines without all the additional problems connected to the trait needed for the B5 breaching hammer.

# Testing Photographs and Procedure

# Changelog

:cl:
admin: Event Item - D2 Breaching Hammer: A breaching hammer usable by anybody without any additional requirements
/:cl:

2022-12-06 04:33 UTC, Diegoflores31 commented
> # About the pull request
> Admin Spawn item A breaching hammer that is usable by marines.
> 
> # Explain why it's good for the game
> Allows breaching hammers to be given to marines without all the additional problems connected to the trait needed for the B5 breaching hammer.
> 
> # Testing Photographs and Procedure
> # Changelog
> 🆑 add: Admin Spawn Item - D2 Breaching Hammer: A breaching hammer usable by anybody without any additional requirements /🆑

wouldnt be more useful to make a Var that enables the usage on marines instead of adding a new item ?

2022-12-06 08:23 UTC, stanalbatross commented
If you are adding an admin spawn item use the admin: prefix

2022-12-06 11:17 UTC, stanalbatross requested changes
(forgot to press request changes whoops)
first, all the bool_var == FALSE checks should just be done as !bool_var instead
second, it is better coding practice to use inheritance
i.e. parent /breacher type
/synth subtype that has the /pickup and /attack special behaviour
/event subtype that does not

2022-12-17 03:22 UTC, ThePiachu approved these changes
Code looks good

2022-12-17 04:22 UTC, nauticall requested changes
note that the hammer's onmob sprites (the sprites shown on your person) are also orange, so you'd need to change those too for consistency. See `onmob/items_lefthand_0.dmi` and `onmob/items_righthand_0.dmi` and look for `breacher` in each.

while I do like that the color is different to be distinguishing I would prefer a less jarring color, like gray, to be used for the hammer stalk instead to give the impression that this is a regular hammer and not, well, a children's toy :P

2022-12-21 20:44 UTC, stanalbatross requested changes

2022-12-21 20:44 UTC, stanalbatross commented on code/game/objects/structures/girders.dm
> +		if(!(HAS_TRAIT(user, TRAIT_SUPER_STRONG)) && istype(W, /obj/item/weapon/melee/twohanded/breacher/synth))
I believe you can just remove this check because you can't attack with the synth hammer without being super strong. Unsure tho so test on local

2022-12-21 20:44 UTC, stanalbatross commented on code/game/turfs/walls/r_wall.dm
> +		if(!(HAS_TRAIT(user, TRAIT_SUPER_STRONG)) && istype(W, /obj/item/weapon/melee/twohanded/breacher/synth))
same

2022-12-21 20:44 UTC, stanalbatross commented on code/game/turfs/walls/walls.dm
> +		if(!(HAS_TRAIT(user, TRAIT_SUPER_STRONG)) && istype(W, /obj/item/weapon/melee/twohanded/breacher/synth))
same

2023-01-10 04:32 UTC, nauticall approved these changes
sprites look a-ok 👍

2023-01-10 08:25 UTC, morrowwolf approved these changes
Code is good

2023-01-10 08:25 UTC, merged