Research Nerfs
cmss13-devs/cmss13 pull request #1863
Opened 2022-12-06 19:43 UTC by Unknownity

# About the pull request

This PR brings in some changes to cut down a few things.
one monkey cube box has been removed to cut down the maximum xenomorphs researchers can make (from 21 xenomorphs total to 11, excluding CL monkey cubes and including pooled).

 A corrupted hive's biggest advantage over the regular hive is that they are teamed up with the marines, so if a corrupted hive managed to get ALL the monkey cubes for their hive, they would effectively be 1:1 with the rival hive with the addition of being allied to the marines, an USCM allied hive still has the advantage over the regular hive by being allied to marines and being able to plan out their castes for XvX than XvH. 

This change will now make the regular hive atleast have a chance fighting off the corrupted hive in a scenario with marines and be slightly better when the corrupted are alone (if the regular hive has more xenos).

If you are upset that you lost more monkeys to "experiment" on that isnt just infecting them with huggers, keep in mind that there is no way you can permamently lose a monkey unless you decapitate them or leave them for dead instead of reviving them. No I will not make special monkeys that cannot be infected, use your monkeys as intended for experiments, they are not only for making a corrupted hive.

second change is increasing the rarity of Musclestimulating (MST) and Nervestimulating (NST) from Uncommon to Rare (1 tier up). Lately if not for a very long time, Research seems to only ever make stimulants, we have cut down a lot of ways to get them (by removing Synaptizine and Hyperzine and other changes etc.) and currently you can still obtain them quite easily and the whole research meta was to always make NST MST instead of utilizing literally any other beneficial property and now with anti xenomorph interactions, they still make stimulants only because it has been ingrained in their brain for too long.

Increasing their rarity makes the properties no longer appear in botany chems, so you will now have to wait for colony vials/papers, a xeno corpse and max your clearance or buy a C3+ paper.

The final change is replacing the Ultrazine Pill Bottle the CL has with an Ultrazine Auto-Injector, the pill bottle contained 5 pills with 5u each, the new injector contains 25u of the stimulant and gives 5u each injection. The only difference being is that the Ultrazine the CL has is now in a liquid injection than pill form, it will begin affecting you instantly and the main reason I made this change, you can no longer obtain the chemical from it as you could with pills by dissolving them which granted an easy scan for MST, since we are making MST rarer, the CL should not have pills but an auto-injector.

# Explain why it's good for the game

Cuts down corrupted numbers to prevent easy stomps whenever marines get them

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl: Unknownity
del: Removed one monkey cube box from Research.
balance: Increased rarity of MST and NST from Uncommon to Rare.
balance: Replaced the Ultrazine Pill Bottle with an Ultrazine auto-injector in the CL Vendor Briefcase.
/:cl:

2022-12-06 20:05 UTC, Mister-moon1 commented
Just going to say this now, I don't think this is a good idea, research is already unfun as it is, being more labourous then enjoyable, looking at poppies for 30 minutes only for the round to end before you can do anything, nst and mst aren't even confirmed in custom chems with the only mst chem being runner blood which needs CL 5 X to use in chems, if greenos are able to be made by marines xenos have already fucked up big time, because not only have they let marines get an egg but they have also let marines get a praetorian or queen body, if they dont wish to be punished then they are within free will be be cautious, finally, the ultrazine change, MST is very much so available from runners, with 30u OD and being much more accessible than ultrazine

From what research started as and what you are pushing for, i doubt there will be any research mains if you are lucky

2022-12-09 10:36 UTC, stanalbatross requested changes
balance approved btw

2022-12-09 10:36 UTC, stanalbatross commented on code/game/objects/items/reagent_containers/autoinjectors.dm
> +/obj/item/reagent_container/hypospray/autoinjector/ultrazine
don't forget a maptext label!

2022-12-09 13:16 UTC, stanalbatross approved these changes

2022-12-09 13:16 UTC, stanalbatross commented on code/game/objects/items/reagent_containers/autoinjectors.dm
> +	desc = "An auto-injector loaded with a special illegal muscle stimulant, Do not administer more than twice at a time. Highly addictive."
```suggestion
	desc = "An auto-injector loaded with a special illegal muscle stimulant, do not administer more than twice at a time. Highly addictive."
```

2022-12-09 13:16 UTC, stanalbatross commented on code/game/objects/items/reagent_containers/autoinjectors.dm
> +	maptext_label = "??"
```suggestion
	maptext_label = "UZ"
```
since this is the clear version

2022-12-09 13:16 UTC, stanalbatross commented on code/game/objects/items/reagent_containers/autoinjectors.dm
> +
```suggestion
	maptext_label = "??"
	
```

2022-12-09 13:17 UTC, stanalbatross approved these changes

2022-12-10 15:12 UTC, merged