Predator Big SD Laugh (MOVIELIKE AF)
cmss13-devs/cmss13 pull request #19
Opened 2022-04-15 07:24 UTC by johnravioliUSA

## About The Pull Request

Predators on the BIG SD setting will now laugh when they activate it, it is awesome.
A little bit of shitcode is changed to just add it in

## Why It's Good For The Game

Predators can do the movielike thing and automatically have a different laugh when self destructing on the big setting. It is good for the game since it's movielike AF, hence the name. Unironically, actually good for the game because it will be awesome

## Changelog

:cl: johnravioli
add: Big SD now has a laugh when you activate it
soundadd: New laughing sound
/:cl:

2022-04-15 21:31 UTC, stanalbatross requested changes

2022-04-15 21:31 UTC, stanalbatross commented on code/modules/cm_preds/yaut_bracers.dm
> +		var/obj/item/clothing/gloves/yautja/hunter/bracer = M.gloves
why do you need this? it's not referenced anywhere.

2022-04-15 21:31 UTC, stanalbatross commented on code/modules/cm_preds/yaut_bracers.dm
> +		if(explosion_type == 0 && is_ground_level(z))
according to shaddeh this causes issues when trying to big SD

2022-04-16 19:23 UTC, stanalbatross requested changes
triio says give the SD sound a fadeout at the end because it sounds bad without one.

2022-04-16 20:19 UTC, johnravioliUSA commented
> triio says give the SD sound a fadeout at the end because it sounds bad without one.

its fixed

2022-04-16 20:20 UTC, stanalbatross approved these changes

2022-04-16 20:32 UTC, merged