Observers can now join as huggers from eggs and Carriers
cmss13-devs/cmss13 pull request #1908
Opened 2022-12-10 12:55 UTC by ThePiachu

# About the pull request

Recently we talked about how it would be nice for observers to be able to join as huggers from more than just egg morphers, so figured I'd implement it. Now Carriers function like mobile carriers for the huggers! :D

# Explain why it's good for the game

It makes vanilla Carriers more important and actually incentivises planting eggs, carrying huggers and all that.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

https://youtu.be/zNeva3l8gj4

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
add: Observers can now join as Facehuggers using any planted egg or a Carrier.
code: Refactored the code around joining as a Facehugger to be less Egg Morpher centric.
/:cl:

2022-12-10 13:45 UTC, Watermelon914 commented on code/modules/mob/dead/observer/observer.dm
> +mob/dead/observer/proc/can_spawn_as_hugger(var/hivenumber)
this needs / at the start and do this for all other definitions

2022-12-10 13:46 UTC, Watermelon914 requested changes

2022-12-10 13:46 UTC, Watermelon914 commented on code/modules/mob/dead/observer/observer.dm
> +	hugger.generate_name()
Endline is required at the end of a file

2022-12-10 13:46 UTC, Watermelon914 commented on code/modules/mob/living/carbon/xenomorph/castes/Carrier.dm
> +	huggers_cur--
Endline is required at the end of a file

2022-12-10 13:46 UTC, Watermelon914 commented on code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
> +	var/playable_hugger_limit = 4
These need doc comments

2022-12-18 11:48 UTC, stanalbatross commented on code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
> +	playable_hugger_limit = 2 + Ceiling(totalXenos.len / 8)
this value is pretty harsh, I would drop it down to / 4 or something

2022-12-18 11:50 UTC, stanalbatross requested changes

2022-12-18 11:50 UTC, stanalbatross commented on code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
> +	if(totalXenos.len == 0)
```suggestion
	if(totalXenos.len <= 0)
```

2022-12-18 11:50 UTC, stanalbatross commented on code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
> +	if(world.time - user.timeofdeath < 3 MINUTES)
use define for 3 minutes

2022-12-19 04:09 UTC, ThePiachu commented
Added a verb for ghosts to join as a Facehugger, it lists only Carriers and Morphers that have available huggers in them
![image](https://user-images.githubusercontent.com/964559/208345797-cc8b0d3e-2ad3-4cd0-a071-4b4652823089.png)

2022-12-20 03:17 UTC, ThePiachu commented
You can now set reserves for egg morpher as well if you're a Drone caste.

2022-12-24 14:39 UTC, harryob requested changes

2022-12-24 14:39 UTC, harryob commented on code/modules/mob/living/carbon/xenomorph/abilities/carrier/carrier_abilities.dm
> +	action_icon_state = "xeno_banish"
eol - editorconfig vsc plugin does this for you

2022-12-24 14:39 UTC, harryob commented on code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
> +	var/playable_hugger_limit = 0 //How many huggers can the hive support
```suggestion
	/// When can huggers join the round
	var/hugger_timelock = 15 MINUTES
	 /// How many huggers can the hive support
	var/playable_hugger_limit = 0
```
i think walter meant to dm doc these vars - so they show up on mouseover in vsc, but this is optional regardless

2022-12-26 09:47 UTC, harryob approved these changes

2022-12-26 13:46 UTC, merged