Yautja Customization Overhaul and Sprite Fixes
cmss13-devs/cmss13 pull request #192
Opened 2022-05-01 13:25 UTC by Geevies

## About The Pull Request

Added Yautja hairstyles, colorable capes (by clan rank), caster materials, and fixed various missing or malaligned sprites.

WARNING: The pred sprites in the art repo needs to be merged before this one is for everything to look right.

## Why It's Good For The Game

Customization is cool, malaligned sprites are not cool.

## Changelog

:cl: Geeves, Frans_Feiffer
add: Added pred hairstyles, sprited by Frans.
add: Added colorable pred capes, sprited by Frans.
add: Added plasma caster materials (retro still available), sprited by Frans.
imageadd: Fixed various pred weapons not being aligned correctly, body mesh on-mob and inventory state being mixed up, ceremonial dagger not having in-hand state, sprites by Geeves.
/:cl:

2022-05-07 21:00 UTC, Agameofscones approved these changes
mapping is fine, but this elder icon should be included as another cape type. It's still OK and greyscaled, so no reason not to make it a variant along with the other ones:

![image](https://user-images.githubusercontent.com/15992551/167271561-d728aff6-e040-42bf-ac6d-b092b821d75a.png)

2022-05-08 10:03 UTC, stanalbatross approved these changes
no problems found, n.b. sprites will need to go in the closed art repo too

2022-05-08 22:16 UTC, fira requested changes
just noting quick -- as mentioned internally, we had some concerns about forward compat' when it comes to usage of the cape types and savefiles (dont want it blowing up later)

everything else looks fine to me and pred-sprites PR is already ready and sprite-approved

2022-05-09 22:12 UTC, fira approved these changes

2022-05-09 22:19 UTC, merged