Mop Gameplay Overhaul
cmss13-devs/cmss13 pull request #193
Opened 2022-05-01 14:53 UTC by Geevies

## About The Pull Request

Added some cleaning gameplay improvements, by making the mop work faster, hold more water, have an animation when cleaning, and having a cleaning skill for MTs and Synths that makes cleaning faster

## Why It's Good For The Game

Maintenance technician is a dreadfully boring role. While many projects exist to add one gigantic massive feature that will totally revamp the way the game is played, it usually ends up dead in the water due to the massive weight dragging it down into the abyss that is the second page of pull requests.

That is why I set forth to introduce small, implementable features that increase the playability bit by bit. With enough effort, each small addition will become larger than the promised total revamp whole.

Cleaning is a big part of maintaining a vessel, especially one so far from human centres. After the recent battle that has left the Almayer and the first battalion scarred, it's up to the maintenance technicians to get the Akira class cruiser back into ship-shape, literally.

I have done many solo events where I've spawned myself in as a cleaning unit, and it simply isn't fun. There is almost no audio-visual feedback to the process of scrubbing the deck, which is solved by the changes contained within this branch.

## Changelog

:cl:
add: Added a cleaning skill, buffed mops. They now work faster, hold more water, and have visual feedback to its operation.
/:cl:

2022-05-01 15:02 UTC, JohnDoe50974 commented
Cool PR but I really would not make cleaning a skill, cleaning stuff is way too situational and completely tangential to the gameplay loop to justify making a *skill* out of it. It'd just be an extra line of text in the show skills menu that would confuse players more than anything else.

2022-05-02 02:49 UTC, neroisvcute commented
Yes. Remove shotgun juggling, make attachments obsolete, and add stimulating, roleplay friendly content that I’m sure players would love to do for hours like cleaning. Amazing, speedmerge.

2022-05-02 07:36 UTC, stanalbatross requested changes

2022-05-02 07:36 UTC, stanalbatross commented on code/__DEFINES/skills.dm
> +
this is the literal definition of a bloat skill, it interacts with only one incredibly inconsequential piece of side content. make it a broader skill (and justify its existence) or make it like a character trait or something

2022-05-15 20:26 UTC, stanalbatross commented on code/game/objects/items/tools/cleaning_tools.dm
> +		user.animation_attack_on(cleaning_turf)
this can look a bit odd but it's your decision to keep it in or not

2022-05-15 20:27 UTC, stanalbatross commented on code/modules/mob/mob_helpers.dm
> +				return 2
we need better duration multipilers

2022-05-15 20:28 UTC, stanalbatross approved these changes
code good, waiting on sprite review

2022-05-29 09:35 UTC, FransFeiffer approved these changes
Sprites are fine oorah

2022-05-29 09:36 UTC, merged