Updated round tips, added button to recieve random tip in character settings
cmss13-devs/cmss13 pull request #1936
Opened 2022-12-13 17:59 UTC by carlarctg

# About the pull request

Added more tips.

Removed redundant or outdated tips.

Removed the 'chain of command' and 'shiny medal' tips.

Added a button to get a random round tip in character settings.

# Explain why it's good for the game

> Removed the 'chain of command' and 'shiny medal' tips.

These tips don't really serve any purpose other than maybe riling up whoever read them, they're kind of just a middle finger. Especially since they appear so commonly in the 1/3rd chance meta tips section.

> Added a button to get a random round tip in character settings.

I remember watching a video on how unhelpful TF2 is to new players and how it said that the only actual mechanism new players have for learning any information in the game is the 'view random tip' button in class loadouts. 
It's not a great fact that we didn't even have that, and we don't have any other good ways to learn the game, but hey, still good.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
add: Added more tips of the round, and removed outdated, useless, or redundant ones.
add: Added a button to get a random round tip in character gameplay settings.
/:cl:

2022-12-17 11:06 UTC, harryob requested changes

2022-12-17 11:06 UTC, harryob commented on code/modules/client/preferences_toggles.dm
> +		to_chat(src, "<span class='purple'><b>Random Tip: </b>[html_encode(message)]</span>")
SPAN_PURPLE

2022-12-18 16:50 UTC, fira requested changes

2022-12-18 16:50 UTC, fira commented on code/modules/client/client_procs.dm
> +	/client/proc/receive_random_tip
you doubled it up

2022-12-18 16:50 UTC, fira commented on code/modules/client/preferences_toggles.dm
> +		message = pick(tip_list)
you can use SAFEPICK() for this (but erroring with a CRASH on failure is still good)

2022-12-18 16:50 UTC, fira commented on code/modules/client/preferences_toggles.dm
> +	var/list/types_to_pick = list(
/static/

2022-12-18 16:50 UTC, fira commented on strings/marinetips.txt
> +Armor has a randomized reduction in effectiveness, and does not protect the digits. Take the wiki damage values as a best case scenario.
Could add one about crit hits too :trol:

2022-12-18 16:50 UTC, fira commented on strings/metatips.txt
> +Embrace the suck.
huh

2022-12-21 14:28 UTC, carlarctg commented
erm the approvy?

2022-12-21 21:41 UTC, stanalbatross approved these changes
the approvy

2022-12-21 21:41 UTC, merged