Weather's effect on fire is lessened + Weather now effects acid >:)
cmss13-devs/cmss13 pull request #1941
Opened 2022-12-14 03:38 UTC by kugamo

# About the pull request

The numbers behind different weather events smothering fire has been nerfed across the board. While still strong, blizzards for example shouldn't INSTANTLY put out fires (this is the strongest weather on soro). Its more subtle now.

Xeno's acid is now effected by weather events too now: damaging less, lasting shorter, and with a very small chance to disappear on cades.

# Explain why it's good for the game

Expands weather effects disadvantages to actions of xenos when before it only hurt marines. B A L A N C E :0)

Muh environmental realism.

# Changelog

:cl:
add: Weather now effects acid, lasting shorter and damaging less.
balance: Weather's effects on fires have been nerfed by a few points.
/:cl:

2022-12-21 16:44 UTC, carlarctg commented on code/datums/effects/acid.dm
> +		duration = duration - (duration * (SSweather.weather_event_instance.fire_smothering_strength / 10))
you really should make these multipliers, into x * 0.1, it's usually not a concern but for procs that are ran more than once in a blue moon it's good practice

2022-12-21 16:44 UTC, carlarctg commented on code/game/objects/effects/aliens.dm
> +		acid_strength = acid_strength + (SSweather.weather_event_instance.fire_smothering_strength / 3) //smothering_strength is 1-10, acid strench is a multiplier
ditto

2022-12-21 16:44 UTC, carlarctg commented on code/game/objects/effects/aliens.dm
> +	var/area/A = get_area(src)
don't use single letter variables

2022-12-21 16:44 UTC, carlarctg commented on code/datums/effects/acid.dm
> +	var/area/A = get_area(src)
single leter

2022-12-27 06:44 UTC, harryob requested changes
per mr arc

2022-12-31 10:13 UTC, harryob approved these changes

2022-12-31 10:13 UTC, merged