Tweaked Smartpistol Stats
cmss13-devs/cmss13 pull request #1979
Opened 2022-12-18 20:16 UTC by carlarctg

# About the pull request

Increased amount of slots in the SU-6's belt from 6 to 7.

Smartpistol kit spawns with a full belt instead of two spare magazines.

Increased Smartpistol damage from 25 to 30, reduced armor-piercing from 25 to 20.

Increased amount of SU-6 magazine boxes in Requisitions.

# Explain why it's good for the game

> Increased amount of slots in the SU-6's belt from 6 to 7.

For some reason it had 1 less magazine than other holsters. Presumably as a balancing method which is unnecessary and just further restricts ammo availability for this gun.

> Smartpistol kit spawns with a full belt instead of two spare magazines.

This is a pretty pointless amount of magazines, as the smartistol's ROF means it eats through them, and squad prep magazines make it just a waste of people's time to fill it up.

> Increased Smartpistol damage from 25 to 30, reduced armor-piercing from 25 to 20.

Smartpistol underperformed against armorless enemies as it didn't have enough damage, and it still underperformed against armored enemies because of its low damage, even though it had full AP. This helps it get in line with the other pistols and makes it significantly stronger against armorless enemies without really impacting its strength against armored ones.

> Increased amount of SU-6 magazine boxes in Requisitions.

Now there's actually going to be a box there sometimes. Or not, I don't know how the stupid 'scale' amount of items works.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
balance: Increased amount of slots in the SU-6's belt from 6 to 7.

balance: Smartpistol kit spawns with a full belt instead of two spare magazines.

balance: Increased Smartpistol damage from 25 to 30, reduced armor-piercing from 25 to 20.

balance: Increased amount of SU-6 magazine boxes in Requisitions.
/:cl:

2022-12-23 13:15 UTC, stanalbatross requested changes

2022-12-23 13:15 UTC, stanalbatross commented on code/game/objects/items/storage/belt.dm
> +	has_gun = FALSE
schizophrenic code

2022-12-23 16:38 UTC, carlarctg commented on code/game/objects/items/storage/belt.dm
> +	has_gun = FALSE
fioxd

2022-12-27 08:34 UTC, harryob approved these changes

2022-12-27 08:34 UTC, merged