Queen Hiveweed Building
cmss13-devs/cmss13 pull request #199
Opened 2022-05-01 21:47 UTC by Geevies

## About The Pull Request

This makes it so that queens can only build thick structures on hiveweeds, like when she needs to build up the hive during the starting stages of the game, or protecting areas around hive clusters.

## Why It's Good For The Game

Queens being able to remote build thick resin structures directly at FOB was a bit nonsense, at least now you need to create a hive cluster there, which gives the marines a small objective to destroy.

## Changelog

:cl:
balance: Ovi'd queens can now only build thick walls/doors/membrane on hiveweeds, otherwise it'll just be normal. Building them costs an amount of plasma roughly in the middle of the two.
balance: Ovi'd queens can no longer be fed plasma by drones.
/:cl:

2022-05-01 21:51 UTC, Carnage068 commented
Why are we taking plasma feeding away from the Queen, again? If a drone wants to sit at hive and help out the queen it should be able to do that.

2022-05-02 07:06 UTC, Git-Nivrak commented
Queen builds hive cluster on frontline -> Spams thick resin walls -> Same problem.
IMO you should make it so it's only thick within 35 tiles of the Queen / Hivecore

2022-05-02 07:10 UTC, stanalbatross reviewed
This is a massive nerf to ovi building at all points in the round especially in the crucial predrop stage when the queen is vital to making good hive defences. In my opinion it's too much of a nerf for an easily avoidable and counter able thing especially since we removed it going under Cades. DNM for further discussion.

2022-05-02 16:59 UTC, Chainsawicus commented
> balance: Ovi'd queens can no longer be fed plasma by drones.

Remove this from the PR and it's a perfect change IMO.

2022-05-04 15:22 UTC, PalJohnson commented
Honestly, this is a really good chance. The only other alternative to consider is perhaps making thick walls longer to make in order to make it less spammy and encourage caste like the **_hivelord_** to be a lot more valuable as they can upgrade resin walls to thick walls. There are ways to continually build thick walls without the need of the queen using it via thick eye. No one really plays hive lord atm as they get outclassed by a longshot by the queen eye. Sure you can still build them but not as fast as before allowing for more time to be allocated to at least try to counter it. Being able to produce them so fast was a bit nuts, especially with flamer weapons not being readily available for it. I know as a survivor I've seen queen block people off with thick weeds in the thick of fighting or just stonewall holdouts so that Xenos could pickoff select areas of barricades with survivors not being able to counter them due to lack of flame or AP weapons.

2022-05-04 15:27 UTC, PalJohnson commented
> This is a massive nerf to ovi building at all points in the round especially in the crucial predrop stage when the queen is vital to making good hive defences. In my opinion it's too much of a nerf for an easily avoidable and counter able thing especially since we removed it going under Cades. DNM for further discussion.

Unless you have a flame weapon then countering the heavy wall spam can be rather difficult to counter especially when they are constructed as you would need a machete or master key to take them down quickly. Usually if you are on a barricade you are shooting constantly, especially during fob defense. In the case of the attacks, you can destroy weeds quicker but if you look away for a second then the walls begin to appear which really isn't fun to play against. At least its not total removal as hive clusters would still be needed. Hivelordss would be a little more valuable as they can upgrade walls.

2022-05-12 18:01 UTC, Watermelon914 requested changes

2022-05-12 18:01 UTC, Watermelon914 commented on code/modules/mob/living/carbon/xenomorph/castes/Queen.dm
> +	return FALSE
make this a signal instead

2022-05-12 18:01 UTC, Watermelon914 commented on code/modules/mob/living/carbon/xenomorph/resin_constructions.dm
> +			can_build_thick = FALSE
W needs a more descriptive variable name. The code is also duplicated and T also needs a more descriptive variable name

2022-05-12 18:01 UTC, Watermelon914 commented on code/modules/mob/living/carbon/xenomorph/resin_constructions.dm
> +	return new path(T)
T needs a more descriptive variable name and so does W

2022-05-12 18:01 UTC, Watermelon914 commented on code/modules/mob/living/carbon/xenomorph/abilities/ability_helper_procs.dm
> +			return
Q also needs a more descriptive variable name

2022-05-12 19:09 UTC, merged