Properly takes into account MOB_SIZE_XENO_SMALL.
cmss13-devs/cmss13 pull request #202
Opened 2022-05-02 01:41 UTC by Kaga-404

## About The Pull Request

Fix for Aimed Shot since I found there's actually a MOB_SIZE_XENO_SMALL tier exclusively for Runners below MOB_SIZE_XENO. Also cleans up the way the damage is calculated, so that it doesn't call the damage proc multiple times based on size.

## Why It's Good For The Game

Makes the functionality less binary, while also slightly cleaning up the ability code.

## Changelog

:cl: Kaga
fix: Fixed an unintended oversight where mobs were taking damage calculated for runners from the Aimed Shot ability. Normal-size Xenos now have their own tier for damage calculation.
/:cl:

2022-05-02 09:19 UTC, fira commented
Gonna sound stupid but why link this to Xenos at all ? The point of mob_size is that it's a common mob property

2022-05-07 10:32 UTC, Kaga-404 commented
> Gonna sound stupid but why link this to Xenos at all ? The point of mob_size is that it's a common mob property

Holdover from how Aimed Shots were coded, could generalize it by removing the isXeno() check portion if needed.

2022-05-14 09:43 UTC, stanalbatross requested changes

2022-05-14 09:43 UTC, stanalbatross commented on code/modules/projectiles/ammo_datums.dm
> +		L.apply_armoured_damage(damage*size_damage_mod, ARMOR_BULLET, BRUTE, null, penetration)
won't this do damage*0.8 and actually reduce the damage here?

2022-05-14 09:43 UTC, stanalbatross commented on code/modules/projectiles/ammo_datums.dm
> +			L.apply_armoured_damage(damage*size_damage_mod, ARMOR_BULLET, BRUTE, null, penetration)
same here - if it doesn't pass any of the checks (i.e. is a runner) won't it just get *0.5?

2022-08-01 10:38 UTC, stanalbatross approved these changes

2022-08-01 10:38 UTC, merged