Offhand Attachment Activation
cmss13-devs/cmss13 pull request #203
Opened 2022-05-02 04:45 UTC by PhantomEpicness

## About The Pull Request

Removes the requirement to have attachments in the active hand to activate them

## Why It's Good For The Game

This logically doesn't make any sense. Apparently, marines in CM somehow activate the grip light with the same hand that is holding the trigger of the gun. Rail lights have to annoyingly, be selected in order to be turned on.

There is kind of a point for attachments but what gives? It's literally only a very minor keypress and it wont have any balance implications since underbarrel weapons are trashy. ( if someone is low HP enough to be killed by an underbarrel, they have low enough HP to be killed by the gun its attached to)

## Changelog

:cl: TotalEpicness5

qol: Removed the off-hand limitation on attachments

/:cl:

2022-05-02 04:53 UTC, PhantomEpicness commented
Tested on dual weapons. The selected weapon's attachments get selected when using macros and there are activatable UI buttons for each gun's attachments.

2022-05-12 14:15 UTC, stanalbatross requested changes

2022-05-12 14:15 UTC, stanalbatross commented on code/modules/projectiles/gun_attachables.dm
> +		reload_attachment(I, user)
this will make attachments on guns reloadable when not in your offhand, which is not in the changelog. Remove.

2022-05-31 20:33 UTC, PhantomEpicness commented
> This PR has been inactive for long enough to be automatically marked as stale. This means it is at risk of being auto closed in ~ 7 days, please address any outstanding review items and ensure your PR is finished, if these are all true and you are auto-staled anyway, you need to actively ask maintainers if your PR will be merged. Once you have done any of the previous actions then you should request a maintainer remove the stale label on your PR, to reset the stale timer. If you feel no maintainer will respond in that time, you may wish to close this PR youself, while you seek maintainer comment, as you will then be able to reopen the PR yourself

racist

2022-06-17 19:00 UTC, stanalbatross approved these changes
code is good and functional

2022-06-17 19:01 UTC, merged