Damage flicker overhaul
cmss13-devs/cmss13 pull request #2041
Opened 2022-12-21 04:32 UTC by carlarctg

# About the pull request

Fixed the bug in which neurotoxin spits did not cause a red damage flicker on the target (It happened because it technically deals no damage.)

Added a new variable, hit_effect_color, that governs on if the ammo/projectile will, if not null, create a damage overlay on hit.

Implemented support for differently-colored hit overlays. Plasma casters have a blue hit flicker, tasers have a yellow one, neurotoxin has a green one, and acid has an acid-colored hit overlay. The CHIMP gun also has a brown overlay.

When a marine is hit by acid blood spray, a sizzling sound will play, alongside the blood visually splattering on them and causing an acid-colored hit overlay.

Flamethrowers will cause a flame-colored hit overlay to appear on the target if they've been directly ignited by it.

Shielded Xenomorphs will override hit colors and flicker yellow instead.

# Explain why it's good for the game

> Fixed the bug in which neurotoxin spits did not cause a red damage flicker on the target (It happened because it technically deals no damage.)

This is technically an oversight, but in practice it means that marines can't tell if they've been hit, and Sentinels can't tell if they hit something, especially since Slow spit's effect is subtle.

> Implemented support for differently-colored hit overlays. Plasma casters have a blue hit flicker, tasers have a yellow one, neurotoxin has a green one, and acid has an acid-colored hit overlay. The CHIMP gun also has a brown overlay.

It makes sense for a alien energy weapon that fires blue energy ion projectiles to have a cool and unique blue effect. Tasers are non-lethal bursts of electricity, so turning the sprite yellow makes sense and looks neat. Certainly makes a lot more sense than turning it red. Neurotoxin, similarly, does not damage but instead splashes targets with neurotoxin, so it gets a unique color. Acid splashes I'm less sure on, but it looks cool, so there's that.

> When a marine is hit by acid blood spray, a sizzling sound will play, alongside the blood visually splattering on them and causing an acid-colored hit overlay.

Tired of there being no feedback on being hit by acid blood. This will look cool.

> Flamethrowers will cause a flame-colored hit overlay to appear on the target if they've been directly ignited by it.

There's no feedback on directly flaming a target doing more damage - this might help.

> Shielded Xenomorphs will override hit colors and flicker yellow instead.

A visual indicator for shielded hits, alongside the shield plinking sound.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
fix: Fixed the bug in which neurotoxin spits did not cause a red damage flicker on the target (It happened because it technically deals no damage.)
code: Added a new variable, hit_effect_color, that governs on if the ammo/projectile will, if not null, create a damage overlay on hit.
add: Implemented support for differently-colored hit overlays. Plasma casters have a blue hit flicker, tasers have a yellow one, neurotoxin has a green one, and acid has an acid-colored hit overlay. The CHIMP gun also has a brown overlay.
qol: When a marine is hit by acid blood spray, a sizzling sound will play, alongside the blood visually splattering on them and causing an acid-colored hit overlay.
add: Flamethrowers will cause a flame-colored hit overlay to appear on the target if they've been directly ignited by it.
balance: Shielded Xenomorphs will override hit colors and flicker yellow instead.

/:cl:

2022-12-27 07:12 UTC, harryob approved these changes

2022-12-30 01:15 UTC, morrowwolf requested changes

2022-12-30 01:15 UTC, morrowwolf commented on code/modules/projectiles/guns/flamer/flamer.dm
> +	for(var/mob/living/ignited_morb in loc) //Deal bonus damage if someone's caught directly in initial stream
ignited morb

2023-01-11 10:06 UTC, harryob approved these changes
code is good + architect approved

2023-01-11 10:06 UTC, merged