Working Joe updates & Predator Spawning
cmss13-devs/cmss13 pull request #2045
Opened 2022-12-21 07:44 UTC by realforest2001

# About the pull request
Reorders checks for spawning as a Predator, so it tells you if you even can spawn BEFORE you confirm if you want to or not.

Updates the Working Joe skills to have SKILL_DOMESTIC.
Rebrands Binary language as Apollo Link, used by Legacy robots & drones, but also by Working Joes.
Added a verb for staff to send messages as ARES on the Apollo Link.

# Explain why it's good for the game
Adds a bit more depth to Working Joes, opening opportunities for events and allowing more coordination. Also opens the door for things using Maintenance Drones.
Makes joining the hunt run checks more effectively.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
code: Reordered checks for joining the hunt.
add: Rebranded Binary Language as Apollo Link, an ARES subprocessor that WY definitely did not steal from Seegson.
admin: Added a verb for staff to talk as ARES on the Apollo Link.
del: Removed Drone Talk as an unnecessary language. 
/:cl:

2022-12-21 08:20 UTC, ThePiachu commented
Make sure to update https://cm-ss13.com/wiki/Comms when merged

2022-12-21 12:24 UTC, stanalbatross requested changes

2022-12-21 12:24 UTC, stanalbatross commented on code/game/gamemodes/cm_initialize.dm
> +	if(show_warning && alert(pred_candidate, "Confirm joining the hunt. You will join as \a [lowertext(J.get_whitelist_status(RoleAuthority.roles_whitelist, pred_candidate.client))] predator", "Confirma
needs to be != "Yes"

also maybe switch to tgui alert

2022-12-21 12:24 UTC, stanalbatross commented on code/game/objects/items/devices/radio/encryptionkey.dm
> +	translate_apollo = 1
bools not ints

2022-12-21 12:24 UTC, stanalbatross commented on code/modules/admin/tabs/event_tab.dm
> +	for(var/obj/structure/machinery/computer/almayer_control/C in machines)
varname

2022-12-21 12:24 UTC, stanalbatross commented on code/modules/admin/tabs/event_tab.dm
> +		if(!(C.inoperable()))
early return + tochat here for readability pls

2022-12-21 12:24 UTC, stanalbatross commented on code/modules/mob/language/languages.dm
>  	for (var/mob/living/S in GLOB.alive_mob_list)
varnames...

2022-12-27 08:24 UTC, harryob requested changes

2022-12-27 08:24 UTC, harryob commented on code/game/jobs/job/civilians/support/working_joe.dm
> +	addtimer(CALLBACK(GLOBAL_PROC, .proc/ai_announcement, "[H.real_name] has been deployed to help with operations."), 1.5 SECONDS)
GLOBAL_PROC_REF macro

2022-12-28 17:19 UTC, harryob approved these changes

2023-01-01 22:49 UTC, stanalbatross approved these changes

2023-01-01 22:50 UTC, merged