m46c verbs -> hud buttons
cmss13-devs/cmss13 pull request #2052
Opened 2022-12-21 16:26 UTC by stanalbatross

# About the pull request

converted the m46c's verbs (toggle id lock and toggle iff) to hud buttons

![image](https://user-images.githubusercontent.com/66756236/208954411-97fd106d-c9bb-4063-bfa8-067ee6acd9ff.png)

like so

also added toggle iff hud button to the CO SG

and removed a stray nanoui file I missed earlier

# Explain why it's good for the game

hud buttons are significantly easier to use than verbs + fuck verbs

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
qol: converted the M46c's verbs to hud buttons. Sprites by Nauticall.
qol: added a "toggle id lock" hud button to the CO smartgun
/:cl:

2022-12-21 16:33 UTC, morrowwolf requested changes
Make a hotkey for IFF toggle.

2022-12-26 07:52 UTC, harryob requested changes

2022-12-26 07:52 UTC, harryob commented on code/modules/projectiles/guns/rifles.dm
> +	if(G.iff_enabled)
G 💢💢💢

2022-12-26 07:52 UTC, harryob commented on code/modules/projectiles/guns/rifles.dm
> +	if(G.is_locked)
💢💢💢

2022-12-26 07:52 UTC, harryob commented on code/modules/projectiles/guns/smartgun.dm
> +	if(H.is_mob_incapacitated() || G.get_active_firearm(H, FALSE) != holder_item)
protagonist_gun*, protagonist*

2022-12-26 07:52 UTC, harryob commented on code/modules/projectiles/guns/smartgun.dm
> +	if(G.is_locked)
as above

2022-12-27 08:20 UTC, harryob commented
imagine forgetting

2022-12-28 10:49 UTC, harryob approved these changes

2022-12-29 21:36 UTC, morrowwolf requested changes

2022-12-29 21:36 UTC, morrowwolf commented on code/modules/projectiles/guns/smartgun.dm
> +	actions_types = list(
List should be defined in Initialization.

2022-12-29 21:36 UTC, morrowwolf commented on code/modules/projectiles/guns/smartgun.dm
>  	RegisterSignal(linked_human, COMSIG_PARENT_QDELETING, .proc/remove_idlock)
Github won't let me go down any further but get_examine_text() (line 632) needs to be converted to the new system as it is only sending the to_chat() about registered user. See M46C for example.

2022-12-29 21:37 UTC, morrowwolf requested changes

2022-12-29 21:37 UTC, morrowwolf commented on code/modules/projectiles/guns/rifles.dm
> +	actions_types = list(
List declaration in initialization

2022-12-30 00:21 UTC, morrowwolf requested changes

2022-12-30 00:21 UTC, morrowwolf commented on code/modules/projectiles/guns/smartgun.dm
> +	LAZYADD(actions_types, /datum/action/item_action/co_sg/toggle_id_lock)
This is not initialize 👀

2022-12-30 00:27 UTC, stanalbatross commented on code/modules/projectiles/guns/smartgun.dm
> +	LAZYADD(actions_types, /datum/action/item_action/co_sg/toggle_id_lock)
my brain was on autopilot

2022-12-30 01:08 UTC, morrowwolf approved these changes

2022-12-30 01:18 UTC, merged