Char loadout balaclava
cmss13-devs/cmss13 pull request #2098
Opened 2022-12-24 23:13 UTC by CapCamIII

# About the pull request

Adds the balaclava and green balaclava as loadout items, also updates green balaclava's sprite.

# Explain why it's good for the game

Interesting loadout item, works for all factions, looks unique(its not a coif, or a reskin of coif like USCM Balaclava)

![image](https://user-images.githubusercontent.com/103988604/209452986-ad9ff505-46c3-42fa-b323-1859a05aaa68.png)

Also one step closer to this absolute beast of a look ^

# Testing Photographs and Procedure

<details>

![image](https://user-images.githubusercontent.com/103988604/209452936-2ba397ad-9ed5-48c5-b9aa-ccb94af68cb3.png)

![image](https://user-images.githubusercontent.com/103988604/209452941-e2c76586-f099-47ae-9fe2-23167327c346.png)

![image](https://user-images.githubusercontent.com/103988604/209452945-a9b0929c-b539-4769-91df-fa9e6e96eaa9.png)

![image](https://user-images.githubusercontent.com/103988604/209452969-54f847ad-2348-4f91-8d2f-250b527f4d13.png)

</details>

# Changelog

:cl:
add: Adds 2 new char setup loadout items, a black and green balaclava, 2 points each.
fix: Balaclava object sprite has a correct offset now.
/:cl:

2022-12-28 21:05 UTC, stanalbatross requested changes

2022-12-28 21:05 UTC, stanalbatross commented on code/modules/clothing/masks/miscellaneous.dm
> +	name = "Balaclava"
```suggestion
	name = "balaclava"
```

2022-12-28 21:05 UTC, stanalbatross commented on code/modules/clothing/masks/miscellaneous.dm
> +	name = "Green Balaclava"
```suggestion
	name = "green balaclava"
```

2022-12-28 22:24 UTC, stanalbatross approved these changes
code is fine

2023-01-05 22:24 UTC, kugamo approved these changes
Sprites will work. APPROVED

2023-01-05 23:05 UTC, merged