TGUI: Brig Timer
cmss13-devs/cmss13 pull request #2112
Opened 2022-12-26 14:45 UTC by Crowbar764

# About the pull request

Upgrades the brig cell timers to use TGUI.
Also fixes the pardon mechanic which was broken by the rank / paygrade overhaul.

Brig timers can now be:

- Started / Resumed
- Paused
- Stopped (Sets timer to the end)
- Reset (Resets timer to 0, removes pardoned status if set)
- Pardoned

COs, High Command, and PvI can pardon.

https://user-images.githubusercontent.com/59719612/209559615-219b243f-cdac-4f14-a572-8ced17460257.mp4

# Changelog

:cl: Casper
fix: fixes pardon mechanic
refactor: brig timer now uses TGUI
/:cl:

2022-12-27 08:54 UTC, harryob requested changes

2022-12-27 08:54 UTC, harryob commented on code/game/machinery/doors/brig_system.dm
> +	var/obj/item/paper/incident/active_report = null // The report currently ticking down the clock.
i’m aware it’s inconsistent w the rest of the vars here, but if you’re documenting them you might as well dmdoc them so it shows up in vsc hover
```suggestion
/// The report currently ticking down the clock.	var/obj/item/paper/incident/active_report = null```
the same for the vars you’ve touched here

2022-12-27 08:54 UTC, harryob commented on code/game/machinery/doors/brig_system.dm
> +		INVOKE_ASYNC(door, /obj/structure/machinery/door.proc/close)
TYPE_PROC_REF

2022-12-27 08:54 UTC, harryob commented on code/game/machinery/doors/brig_system.dm
> +	addtimer(CALLBACK(src, .proc/search_for_components), 20)
PROC_REF

2022-12-27 22:24 UTC, stanalbatross requested changes

2022-12-27 22:24 UTC, stanalbatross commented on code/game/machinery/doors/brig_system.dm
> +		var/time_left = get_time_left(incident)
calculate in-UI to reduce proc overhead

2022-12-27 22:24 UTC, stanalbatross commented on code/game/machinery/doors/brig_system.dm
> +		data["progress"] = 1 - (time_left / 60) / incident.brig_sentence
do in-UI

2022-12-27 22:24 UTC, stanalbatross commented on code/game/machinery/doors/brig_system.dm
> +		data["time_left"] = "[num2text((time_left / 60) % 60)]:[add_zero(num2text(time_left % 60), 2)]"
same

2022-12-27 22:24 UTC, stanalbatross commented on code/game/machinery/doors/brig_system.dm
> +		data["started"]	= (incident.time_served || data["active"]) // Has this timer been started at all?
```suggestion
		data["started"]	= (incident.time_served || (incident.status & BRIG_SENTENCE_ACTIVE)) // Has this timer been started at all?
```
readability

2022-12-27 22:24 UTC, stanalbatross commented on code/game/machinery/doors/brig_system.dm
> +			data["status_class"] = null
why not just send the incident_status to the UI and calculate these all in-UI? look at the escape pod tgui for implementation example

2022-12-27 22:24 UTC, stanalbatross commented on code/game/machinery/doors/brig_system.dm
> +	log_admin("[key_name(user)] has pardoned [viewed_report.incident.criminal_name] for [viewed_report.incident.charges_to_string()].")
JMP

2022-12-27 22:24 UTC, stanalbatross commented on code/game/machinery/doors/brig_system.dm
> +	log_admin("[key_name(user)] has paused the jail timer of [incident.criminal_name], [incident.charges_to_string()].")
JMP link should be included

2022-12-27 22:24 UTC, stanalbatross commented on code/game/machinery/doors/brig_system.dm
> +	to_chat(user, SPAN_NOTICE("You insert [W] into [name]."))
\the [w] into \the [name]

2022-12-27 22:24 UTC, stanalbatross commented on tgui/packages/tgui/interfaces/BrigCell.js
> +          {status_text !== 'PERMABRIG' && (
all these PERMABRIG checks could be done like `const Permabrig = status_text === 'PERMABRIG';`
would be a bit easier to read/write

2023-01-02 22:21 UTC, harryob requested changes

2023-01-02 22:21 UTC, harryob commented on code/game/machinery/doors/brig_system.dm
> +		if ("pardon")
check for if they can pardon. i know the button appears dependent on this - but you can exploit tgui to send whatever ui_acts you like

2023-01-06 10:36 UTC, harryob approved these changes

2023-01-06 10:36 UTC, merged