Removes non-combat 'click delay'
cmss13-devs/cmss13 pull request #2130
Opened 2022-12-28 05:05 UTC by carlarctg

# About the pull request

Removed next move addition from these things:
- Picking things up from the ground
- Yanking out objects (???)
- Transferring from stack to stack (????)
- Placing things on tables
- Item attack delay has been removed from click_adjacent() and moved to attackby() (means you'll only get that click delay when attacking something)

Clicking on the floor (open turfs) with an item will cause next_move addition to prevent this PR from impacting combat. 
Additionally, it will display a to_chat that can be disabled when disabling fluff actions in chat logs.

# Explain why it's good for the game

Every single other SS13 server has removed this, including, Stan hear me out, TG. The only thing this does is be an extremely fucking annoying nuisance that hinders anything that isn't shooting things, worsening the life of researchers, MTs, MSTs, Req (of course), and all other staff to various degrees. Even if it's 'realistic' that you can't quickly pick up and put down things (which isn't true, you can do so in a rush IRL), it's just a thoroughly unpleasant experience to sit there staring at the screen because you slightly misclicked/maybe even if you didn't, it makes everything slow and annoying.

This isn't an evil QOL addition that works towards the slow erosion of anything mechanically complex in the game, it's just updating the fucking game to 2022 SS13 server standards.

And yes, I've tested it. This won't result in infinite extremely fast knife stabs that kill xenos in a second.

**THIS ABSOLUTELY MUST BE TESTMERGED BEFORE MERGING**

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
del: Removed non-combat 'click delay', interacting with items not on your person should be significantly smoother.
balance: Added a to_chat for clicking on the ground, which will indicate you 'swinging the item through the air', causing you to be unable to attack for a moment. (This is pre-existing behaviour, all that is changed here is the addition of the message)
/:cl:

2022-12-29 15:34 UTC, stanalbatross commented
`And yes, I've tested it. This won't result in infinite extremely fast knife stabs that kill xenos in a second.`

well clearly you didn't test on closed turfs (i.e. resin walls) because there's no delay on attacking those

2022-12-29 17:34 UTC, carlarctg commented
> `And yes, I've tested it. This won't result in infinite extremely fast knife stabs that kill xenos in a second.`
> 
> well clearly you didn't test on closed turfs (i.e. resin walls) because there's no delay on attacking those

that's what testmerges are for

2023-01-01 21:15 UTC, harryob commented on code/modules/mob/living/living.dm
> +/mob/living/attack_hand(mob/user) // not recommended to be used - does not apply next move cooldown by default (how do i dmdoc procs?)
https://github.com/tgstation/tgstation/blob/master/.github/guides/AUTODOC.md#documenting-a-proc

2023-01-09 05:18 UTC, burgz1 commented
i'm no programmer, and i've never used github before. But i want to mention that the stunbaton is broken with this merge. you can just instantly stun people.

2023-01-12 03:15 UTC, carlarctg commented
ready for TM

2023-02-22 02:19 UTC, Herotitan772 commented
as a frequent player of Engineer, medic, doctor, researcher and OT this is the best thing since sliced bread. +1

2023-02-25 17:53 UTC, Superwelder commented
I am not 100% certain its related to this issue but now tables with a corner can be flipped and its causing a lot of headaches. For one, it makes no sense that a corner table can be magically separated into its horizontals and verticals when the sprite clearly shows it as connected. 2nd, it makes accidental table flips SUPER common because you now can accidentally flip any table. Please fix this! It also has slight balance implications because xenos can abuse the corner tables to flip and move into an area that clearly looks like movement would be blocked until the table was vaulted or smashed(flipping is instant).

2023-02-25 17:56 UTC, harryob commented
> I am not 100% certain its related to this merge but now tables with a corner can be flipped in any direction and its causing a lot of headaches. For one, it makes no sense that a corner table can be magically separated into its horizontals and verticals when the sprite clearly shows it as connected. 2nd, it makes accidental table flips SUPER common because you now can accidentally flip any table. Please fix this! It also has slight balance implications because xenos can abuse the corner tables to flip and move into an area that clearly looks like movement would be blocked until the table was vaulted or smashed(flipping is instant).

@Superwelder 
this is a bug in master, not this pr. feel free to make the issue report

2023-03-11 14:57 UTC, Herotitan772 commented
This doesn’t work for engineering, mainly wiring cades, adding metal/plas to girders, unscrewing stuff, deconing stuff, building stuff, hacking stuff or welding stuff

2023-03-14 08:06 UTC, Herotitan772 commented
can this get merged into master?

2023-03-21 12:08 UTC, Watermelon914 requested changes
Generally speaking, I think this implementation is flawed and you should really be having "after_attack_by" at the root level, aka /atom
Then, you should move all attackby calls to an override of after_attack_by whilst keeping attackby set to SHOULD_CALL_PARENT(TRUE) so that after_attack_by always gets called during attackby.
The current implementation you've done requires multiple definitions for after_attack_by on different types, which is non-ideal for maintainability.

2023-03-21 12:08 UTC, Watermelon914 commented on code/game/objects/structures.dm
> -	..()
Why remove the parent call? I think this should still be calling parent

2023-03-21 12:08 UTC, Watermelon914 commented on code/game/objects/structures/surface.dm
> +	return
You can remove this return.

2023-03-21 12:08 UTC, Watermelon914 commented on code/game/turfs/floor.dm
> +	if(!user.a_intent == INTENT_HARM|INTENT_DISARM)
```suggestion
	if(!user.a_intent == (INTENT_HARM|INTENT_DISARM))
```

2023-04-09 00:27 UTC, closed without merging