Adds soulful USCM SPF 50 sunscreen.
cmss13-devs/cmss13 pull request #2183
Opened 2023-01-01 20:16 UTC by somepersondunno

# About the pull request

This adds a soulful SPF 50 stick of sunscreen. It comes with a discounted cost to accommodate for the uselessness on night operations as well as the long term risk of heavy metal poisoning.

This is my first item added to the game, and I did test it. Sprites thanks to @thwomper 

# Explain why it's good for the game

This is a simple, soulful addition that marines will surely spend points on, and it diversifies the facepaint category as well as adding potential for other, even more useless items to be added for lore.

# Testing Photographs and Procedure

I spawned it in, and it works. This is a [peek](https://cdn.discordapp.com/attachments/948362058351656980/1058998160124563557/IMG_1537.jpg) at what it looks like, thanks to the spriter.

</details>

# Changelog

:cl:
add: Added sunscreen. Now you can enjoy those rays without risking damage from UV rays!
/:cl:

2023-01-02 07:16 UTC, nauticall requested changes
![image](https://user-images.githubusercontent.com/55491249/210202994-14d71318-d8b0-4335-80e9-7a3bad77be2b.png)

Having the stick right side up would make it look better when placed on a surface. 

![image](https://user-images.githubusercontent.com/55491249/210203070-b16061b4-e2b5-48c4-8267-1d867f3efab5.png)

The sunscreen application itself also looks a lil gray, maybe making it a bit lighter would make it look more like sunscreen too.

("Soulful" is used like 5 times in this PR, by the way. Tone it down a little bit please ;A;)

Otherwise, looks pretty good!

2023-01-03 07:02 UTC, NewyearnewmeUwu commented
The previous version of the sunscreen itself was transparent, I've now made it not-transparent.

2023-01-06 23:38 UTC, kugamo approved these changes
Sprites

2023-01-07 12:51 UTC, stanalbatross approved these changes

2023-01-07 12:51 UTC, merged