skills menu tgui
cmss13-devs/cmss13 pull request #2218
Opened 2023-01-04 22:40 UTC by stanalbatross

# About the pull request

converted the skills menu to tgui

normal version :
![image](https://user-images.githubusercontent.com/66756236/210663544-2dca6db4-8da3-4e8f-ade5-0baf760857f9.png)

admin version :
![image](https://user-images.githubusercontent.com/66756236/210663484-cf255087-faa4-4a3a-bb94-a67caf89294b.png)

(and yes I added a rights check in the ui act so you CANNOT EXPLOIT IT)

# Changelog

:cl:
ui: converted the check skills menu to TGUI
admin: changed the edit skills vv dropdown from a clunky series of input lists to the new check skills menu TGUI
/:cl:

2023-01-06 01:47 UTC, harryob approved these changes

2023-01-07 08:19 UTC, harryob requested changes

2023-01-07 08:19 UTC, harryob commented on tgui/packages/tgui/interfaces/SkillsMenu.js
> +        {capitalize(skill.name)}: {skill.level}/{skill.maxlevel}
```suggestion
        {capitalizeAll(skill.name)}: {skill.level}/{skill.maxlevel}
```
this prevents JTAC being converted to Jtac and makes sure Illegal Technology etc is properly uppercased

2023-01-07 08:19 UTC, harryob commented on tgui/packages/tgui/interfaces/SkillsMenu.js
> +import { capitalize } from 'common/string';
```suggestion
import { capitalizeAll } from 'common/string';
```

2023-01-07 08:19 UTC, harryob commented on code/datums/skills.dm
> +	readable_skill_name = SKILL_JTAC
```suggestion
	readable_skill_name = "JTAC"
```

2023-01-07 08:19 UTC, harryob commented on code/modules/mob/living/carbon/human/powers/check_skills.dm
> +	src.skills.tgui_interact(src)
https://github.com/tgstation/tgstation/pull/72499

asdad; laksf;la ks;dl aks;dl aksd 

```suggestion
	skills.tgui_interact(src)
```

2023-01-07 08:19 UTC, harryob commented on code/modules/mob/living/carbon/human/powers/check_skills.dm
> +			"name" = skilldatum.readable_skill_name,
```suggestion
			"name" = skilldatum.readable_skill_name ? skilldatum.readable_skill_name : skilldatum.skill_name
```
then we don't need to double up when readable_skill_name is just the same as skill_name, as in 90% of cases there

2023-01-07 11:47 UTC, stanalbatross commented on tgui/packages/tgui/interfaces/SkillsMenu.js
> +        {capitalize(skill.name)}: {skill.level}/{skill.maxlevel}
```suggestion
        {capitalizeAll(skill.name)}: {skill.level}/{skill.maxlevel}
```

2023-01-07 12:33 UTC, stanalbatross commented on code/modules/mob/living/carbon/human/powers/check_skills.dm
> +			"name" = skilldatum.readable_skill_name ? skilldatum.readable_skill_name : skilldatum.skill_name
```suggestion
			"name" = skilldatum.readable_skill_name ? skilldatum.readable_skill_name : skilldatum.skill_name,
```

2023-01-08 09:26 UTC, harryob requested changes

2023-01-08 09:26 UTC, harryob commented on code/datums/skills.dm
>  	skill_level = SKILL_FIREARMS_DEFAULT
```suggestion
	skill_name = SKILL_FIREARMS
	skill_level = SKILL_FIREARMS_DEFAULT
```

2023-01-08 09:26 UTC, harryob commented on code/datums/skills.dm
>  	skill_level = SKILL_ENDURANCE_WEAK
```suggestion
	skill_name = SKILL_ENDURANCE
	skill_level = SKILL_ENDURANCE_WEAK
```

2023-01-08 09:26 UTC, harryob commented on code/datums/skills.dm
>  	skill_level = SKILL_ENGINEER_DEFAULT
```suggestion
	skill_name = SKILL_ENGINEER
	skill_level = SKILL_ENGINEER_DEFAULT
```

2023-01-08 09:26 UTC, harryob commented on code/datums/skills.dm
>  	skill_level = SKILL_CONSTRUCTION_DEFAULT
```suggestion
	skill_name = SKILL_CONSTRUCTION
	skill_level = SKILL_CONSTRUCTION_DEFAULT
```

2023-01-08 09:26 UTC, harryob commented on code/datums/skills.dm
>  	skill_level = SKILL_LEAD_NOVICE
```suggestion
	skill_name = SKILL_LEADERSHIP
	skill_level = SKILL_LEAD_NOVICE
```

2023-01-08 09:26 UTC, harryob commented on code/datums/skills.dm
>  	skill_level = SKILL_DOMESTIC_NONE
```suggestion
	skill_name = SKILL_DOMESTIC
	skill_level = SKILL_DOMESTIC_NONE
```

2023-01-08 09:26 UTC, harryob commented on code/datums/skills.dm
>  	skill_level = SKILL_INTEL_NOVICE
```suggestion
	skill_name = SKILL_INTEL
	skill_level = SKILL_INTEL_NOVICE
```

2023-01-08 09:26 UTC, harryob commented on code/datums/skills.dm
>  	skill_level = SKILL_EXECUTION_DEFAULT
```suggestion
	skill_name = SKILL_EXECUTION
	skill_level = SKILL_EXECUTION_DEFAULT
```

2023-01-08 09:26 UTC, harryob commented on code/datums/skills.dm
>  	skill_level = SKILL_VEHICLE_DEFAULT
```suggestion
	skill_name = SKILL_VEHICLE
	skill_level = SKILL_VEHICLE_DEFAULT
```

2023-01-08 09:26 UTC, harryob commented on code/datums/skills.dm
>  	skill_level = SKILL_POWERLOADER_DEFAULT
```suggestion
	skill_name = SKILL_POWERLOADER
	skill_level = SKILL_POWERLOADER_DEFAULT
```

2023-01-08 09:26 UTC, harryob commented on code/datums/skills.dm
>  	skill_level = SKILL_POLICE_DEFAULT
```suggestion
	skill_name = SKILL_POLICE
	skill_level = SKILL_POLICE_DEFAULT
```

2023-01-08 09:26 UTC, harryob commented on code/datums/skills.dm
>  	skill_level = SKILL_PILOT_DEFAULT
```suggestion
	skill_name = SKILL_PILOT
	skill_level = SKILL_PILOT_DEFAULT
```

2023-01-08 09:26 UTC, harryob commented on code/datums/skills.dm
>  	skill_level = SKILL_RESEARCH_DEFAULT
```suggestion
	skill_name = SKILL_RESEARCH
	skill_level = SKILL_RESEARCH_DEFAULT
```

2023-01-08 09:26 UTC, harryob commented on code/datums/skills.dm
>  	skill_level = SKILL_SURGERY_DEFAULT
```suggestion
	skill_name = SKILL_SURGERY
	skill_level = SKILL_SURGERY_DEFAULT
```

2023-01-08 09:26 UTC, harryob commented on code/datums/skills.dm
>  	skill_level = SKILL_MEDICAL_DEFAULT
```suggestion
	skill_name = SKILL_MEDICAL
	skill_level = SKILL_MEDICAL_DEFAULT
```

2023-01-09 22:02 UTC, harryob approved these changes

2023-01-09 22:02 UTC, merged