Spellcheck Gaurds > Guards
cmss13-devs/cmss13 pull request #223
Opened 2022-05-05 17:51 UTC by PhantomEpicness

## About The Pull Request

Minor spellchecks found on discord. Currently trying to find more to bundle in.

## Why It's Good For The Game
social credit

## Changelog

:cl: TotalEpicness
spellcheck: fixed a typo
/:cl:

2022-05-05 17:56 UTC, PhantomEpicness commented
> You currently have a negative Fix/Feature pull request delta of -5. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

ratio

2022-05-05 18:02 UTC, Agameofscones approved these changes
thanks for saving us from this immersion breaking bug. 😩 

approved.

2022-05-05 18:39 UTC, stanalbatross commented
I reccommend searching up commonly mispelt words

2022-05-06 00:33 UTC, hotimep commented
immersion restored.....

2022-05-07 14:56 UTC, Geevies requested changes

2022-05-07 14:56 UTC, Geevies commented on code/modules/projectiles/guns/shotguns.dm
> +	desc = "The Weyland-Yutani MK221 Shotgun, a semi-automatic shotgun with a quick fire rate. Equipped with a red handle to signify its use with Military Police Honor Guards"
```suggestion
	desc = "The Weyland-Yutani MK221 Shotgun, a semi-automatic shotgun with a quick fire rate. Equipped with a red handle to signify its use with Military Police Honor Guards."
```

2022-05-07 14:56 UTC, Geevies commented
there's also one prae ability where it says "dashs" instead of "dashes"

2022-05-07 18:21 UTC, PhantomEpicness commented
> there's also one prae ability where it says "dashs" instead of "dashes"

I am having trouble finding this

2022-05-08 08:26 UTC, Geevies approved these changes

2022-05-08 08:26 UTC, merged