adds a dme validator
cmss13-devs/cmss13 pull request #2241
Opened 2023-01-07 08:45 UTC by harryob

makes sure everything in the game files is either included in the dme or deleted

2023-01-07 09:02 UTC, harryob commented
draft because although we should do this there's a bunch of things that i don't wanna just delete from the code yet (ie, the emote keybinds (we need to refactor emotes))

2023-01-09 01:42 UTC, stanalbatross requested changes
![image](https://user-images.githubusercontent.com/66756236/211229598-3e80da9c-7444-4469-848b-606d137f4c59.png)
#include these instead of removing, they're useful

2023-01-09 07:17 UTC, harryob commented
> ![image](https://user-images.githubusercontent.com/66756236/211229598-3e80da9c-7444-4469-848b-606d137f4c59.png)
> #include these instead of removing, they're useful

wait all of these work why weren't they included in the first place

2023-01-11 11:13 UTC, stanalbatross approved these changes

2023-01-11 11:14 UTC, merged