2 New Haircut
cmss13-devs/cmss13 pull request #2245
Opened 2023-01-07 13:13 UTC by Skegal

# About the pull request

This PR add 2 new haircut, row braid/croft.

Row Braid: Modification based on row_bun, where there is two rows going to the front, and change the bun to a an attached braid.
Croft: based upon the one in goon, i recreated a similar version working in CM (as goon haircut cant be copy pasted to CM due to how different they works)

# Explain why it's good for the game

It add two haircut for character creation.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

![Croft_RowBraid](https://user-images.githubusercontent.com/45800756/211152382-ba836949-ef52-496b-bb23-f423ded18892.png)

</details>

# Changelog

:cl: Skegal
add: Added two haircut
imageadd: added hair_row_braid_s / hair_croft_s in human_hair.dmi
/:cl:

2023-01-07 14:46 UTC, harryob requested changes

2023-01-07 14:46 UTC, harryob commented on code/modules/mob/new_player/sprite_accessories/hair.dm
> +	icon_state ="hair_croft_s"
```suggestion
/datum/sprite_accessory/hair/row_braid
	name = "Row Braid"
	icon_state = "hair_row_braid_s"

/datum/sprite_accessory/hair/croft
	name = "Croft"
	icon_state ="hair_croft_s"
```

you can't use spaces to indent with, it makes it inconsistent with the tabs below + we don't allow space indentation regardless

2023-01-17 09:09 UTC, nauticall approved these changes
hair's cute. looks good 👍

2023-01-17 10:13 UTC, harryob requested changes

2023-01-17 10:13 UTC, harryob commented on code/modules/mob/new_player/sprite_accessories/hair.dm
> +	icon_state ="hair_croft"
```suggestion
	icon_state = "hair_croft"
```

2023-01-17 10:24 UTC, merged