Gives queen an ability to sacrifice larva for evolution points
cmss13-devs/cmss13 pull request #2265
Opened 2023-01-09 08:07 UTC by morrowwolf

# About the pull request

Gives queen an ability to sacrifice larva for evolution points. There must be at least 3 larva. There is a 60 second cooldown. Can only be done while queen is on ovi (may change after testing).

# Explain why it's good for the game

Having a large amount of pooled larva due to lack of xeno players is a serious problem some rounds. This should help alleviate some of that stopping people who want to play from playing.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>
TESTED YEAAAAAAABOI

</details>

# Changelog

:cl: Morrow
balance: Gives queen an ability to sacrifice larva for evolution points
/:cl:

2023-01-10 16:29 UTC, Nanu308 commented
The feature itself is fine, we can tweak numbers down the line as we go a bit more

2023-01-11 09:54 UTC, harryob requested changes

2023-01-11 09:54 UTC, harryob commented on code/modules/mob/living/carbon/xenomorph/abilities/queen/queen_powers.dm
> +		if(html_encode(xeno.name) == html_encode(choice))
```suggestion
		if(xeno.name == choice)
```

2023-01-14 09:02 UTC, harryob approved these changes

2023-01-16 04:10 UTC, nauticall approved these changes
icon is good 👍

2023-01-16 04:11 UTC, merged