CL Banking issue fix
cmss13-devs/cmss13 pull request #2308
Opened 2023-01-13 19:41 UTC by Mister-moon1

# About the pull request
Hopefully fixes the CLs lack of bank codes along with more simplified code as opposed to the old CL system (why was it like this the div code isnt this important)

# Explain why it's good for the game
CL is the one job that actually has a use for ATMs and being barred out from using them is not fun

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
code: changed the way WY ranks are issued
admin: removed the div code from "select_equipment"
fix: fixed CL job codes
/:cl:

2023-01-13 23:03 UTC, morrowwolf commented
Removing flavor content is pretty lame.

2023-01-13 23:39 UTC, Mister-moon1 commented
it is also way too complicated for its own good and broke banking for all roles using it

2023-01-14 00:58 UTC, realforest2001 reviewed
Minor thing but can you rename it from CL1-10 to WYC1-10? WY Corporate?

2023-01-14 01:22 UTC, Mister-moon1 commented
yeah sure can do in a bit

2023-01-14 08:56 UTC, harryob requested changes

2023-01-14 08:56 UTC, harryob commented on code/modules/gear_presets/wy.dm
> -	..()
you removed the parent time for all the /manager subtypes so they won't get the proper equipment, access, id type, skills or headset. it didn't have a `flags` var defines so it didn't show up in game anyway - just set the paygrade to something else

2023-01-15 21:37 UTC, harryob approved these changes
division code was only ever an admin thing anyway

2023-01-16 12:32 UTC, merged