Zombie-powder-fix
cmss13-devs/cmss13 pull request #2315
Opened 2023-01-15 01:45 UTC by carlarctg

# About the pull request

Fixes Zombie Powder bugging the fuck out by slapping a ton of FAKEDEATH checks everywhere. It now properly shows the holder as dead on HUDs and scans.

Fixed an issue in which sometimes qdeleted reagents still procced on life.

Fixed examining things changing your direction if you're incapacitated.

Added FAKEDEATH to the mob_incapacitated() check.

# Explain why it's good for the game

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
fix: Fixes Zombie Powder bugging the fuck out by slapping a ton of FAKEDEATH checks everywhere. It now properly shows the holder as dead on HUDs and scans.
fix: Fixed an issue in which sometimes qdeleted reagents still procced on life.
fix: Fixed examining things changing your direction if you're incapacitated.
fix: Added FAKEDEATH to the mob_incapacitated() check.
/:cl:

2023-01-15 09:06 UTC, Huffie56 commented
will it fix that resurrect timer bug?https://github.com/cmss13-devs/cmss13/issues/2267

2023-01-16 18:12 UTC, harryob requested changes
you automatically check the pulse of really dead people, but not fakedead, because it checks for just stat atm

https://github.com/carlarctg/cmss13/blob/983f7fdbfeb20b243a07667fbb5e37d7b2a3fac2/code/modules/mob/living/carbon/human/examine.dm#L197

clicky

2023-01-19 19:01 UTC, harryob requested changes
change the if(stat) to if(stat == DEAD | |status_flags & FAKEDEATH) in the link above

2023-02-10 07:04 UTC, Zonespace27 requested changes

2023-02-10 07:04 UTC, Zonespace27 commented on code/modules/mob/living/living_healthscan.dm
> +/datum/health_scan/proc/get_death_value(mob/target_mob)
code doc

2023-02-10 07:04 UTC, Zonespace27 commented on code/modules/mob/living/living_healthscan.dm
> +	else
else not needed

2023-02-10 07:04 UTC, Zonespace27 commented on code/modules/mob/living/living_healthscan.dm
> +/datum/health_scan/proc/get_oxy_value(mob/target_mob)
codedoc

2023-02-11 02:18 UTC, merged