Fixes another bug with warrior pulling
cmss13-devs/cmss13 pull request #232
Opened 2022-05-07 04:44 UTC by Git-Nivrak

## About The Pull Request
Fixes a bug with warrior which would make every mob you stopped grabbing would have its `stunned` and `knockedDown` set to 0 regardless if it was lunged or not.

## Why It's Good For The Game
Bug bad.

## Changelog

:cl:
fix: Fixed a bug with warrior which would make you reset the stun timer on mobs you stop pulling that weren't lunged.
/:cl:

2022-05-07 14:43 UTC, Geevies requested changes

2022-05-07 14:43 UTC, Geevies commented on code/modules/mob/living/carbon/xenomorph/castes/Warrior.dm
>  /mob/living/carbon/Xenomorph/Warrior/stop_pulling()
instead of adding a lunging var, just remove this stop_pulling thing entirely, modern woyers don't really need it

2022-05-10 14:15 UTC, usnpeepoo commented
Will this affect punches dropping lunges or naw

2022-05-12 08:58 UTC, Git-Nivrak commented
> Will this affect punches dropping lunges or naw

It will yes, no more funny sadar baiting

2022-05-15 02:22 UTC, spookydonut approved these changes

2022-05-18 16:34 UTC, merged