Nerfs omnisentries, makes them rotate.
cmss13-devs/cmss13 pull request #2335
Opened 2023-01-17 05:12 UTC by NewyearnewmeUwu

# About the pull request
 
This PR nerfs omnisentries down to 250 rounds per sentry and makes them rotate. Each time they rotate, they have a delay, so that faster castes can outmaneuver it. Thanks to @carlarctg for da help.

# Explain why it's good for the game
Omnisentries are a pain to fight for most castes because of the fact that they're usually hidden in 1x1 wired cade boxes. They also have an _absurd_ 1500 ammo pool, which makes no sense. Why are airdroppable sentries carrying 3x more than the default ones comtechs use? Plus, it looks really cool, and emphasizes their role as positional harassment vs instant death lasers.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
balance: omnisentries now rotate, and have 250 rounds total.
/:cl:

2023-01-17 09:14 UTC, cuberound commented
if you want it to be used in certain way, what about instead of making it worse overall in every role. honestly, omnisentry SUCKS as position harassment, when single T3 can just walk to them and destroy them, when they are not protected by cades, eaven when there are marines around. it is not gona be used as frontline harassment with 4 tile range and now with rotate super long cooldown that makes anyone able to outmanuver them.

2023-01-19 01:07 UTC, mullenpaul requested changes
I've reviewed the code as presented but I'm not convinced that a 'battery life' is a good way of balancing this. If a battery charge is the path forward then this code should be reworked to use a battery, rather than a timer with an IC justification of an internal power store. It seems pretty gamey to put a battery life on this sentry when literally no other sentry does.

2023-01-19 01:07 UTC, mullenpaul commented on code/modules/defenses/sentry.dm
> +	if(has_lifespan == TRUE)
Same as above. This examine text can also be put into the subclasses get_examine_text

2023-01-19 01:07 UTC, mullenpaul commented on code/modules/defenses/sentry.dm
> +	if (has_lifespan == TRUE)
Same as above. I would also put this into the subclass

2023-01-20 02:37 UTC, closed without merging