Increased amount of prey cats can leap upon, including larva and facehuggers.
cmss13-devs/cmss13 pull request #2445
Opened 2023-01-22 04:21 UTC by carlarctg

# About the pull request

Increased amount of prey cats can leap upon, including larva and facehuggers. Others are bats, lizards, chicks, alien slugs, parrots.

Slightly updated cat hunting code. Very slightly. It was so bad man

# Explain why it's good for the game

It makes sense for cats to pounce on tiny critters. I also think this will lead to some very amusing hijinks.

It's just a little qol

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
qol: Increased amount of prey cats can leap upon, including larva and facehuggers.
/:cl:

2023-01-22 12:56 UTC, stanalbatross commented
This is add: not qol

2023-01-25 05:13 UTC, Ultimate-Fluff commented
Pounce kills small critters, right? Oof, rip facehuggers.

2023-01-26 13:53 UTC, carlarctg commented on code/modules/mob/living/simple_animal/friendly/cat.dm
> +			visible_message(pick("\the hisses and spits!","\the mrowls fiercely!","\the eyes [snack] hungrily."))
```suggestion
			visible_message(pick("\the [src] hisses at [snack]!", "\the [src] mrowls fiercely!", "\the [src] eyes [snack] hungrily."))
```

2023-02-03 11:21 UTC, harryob requested changes

2023-02-03 11:21 UTC, harryob commented on code/modules/mob/living/simple_animal/friendly/cat.dm
> +					visible_message(pick("\the [src] bites \the [prey]!","\the [src] toys with \the [prey].","\the [src] chomps on \the [prey]!"))
\the is implicit here

2023-02-06 20:00 UTC, Zonespace27 requested changes

2023-02-06 20:00 UTC, Zonespace27 commented on code/modules/mob/living/living_helpers.dm
> +/mob/living/proc/splat(mob/killer)
code doc

2023-02-06 20:00 UTC, Zonespace27 commented on code/modules/mob/living/simple_animal/friendly/cat.dm
> +	var/mob/living/movement_target
null on destroy; code doc all of these

2023-02-06 20:00 UTC, Zonespace27 commented on code/modules/mob/living/simple_animal/friendly/cat.dm
> +	var/list/hunting_targets = list(
static list

2023-02-06 20:00 UTC, Zonespace27 commented on code/modules/mob/living/simple_animal/friendly/cat.dm
> +		/mob/living/carbon/xenomorph/larva
trailing comma

2023-02-06 20:00 UTC, Zonespace27 commented on code/modules/mob/living/simple_animal/friendly/cat.dm
> +			for(var/mob/living/prey in view(1,src))
```suggestion
			for(var/mob/prey in view(1,src))
```
byond optimizes for the base types

2023-02-06 20:00 UTC, Zonespace27 commented on code/modules/mob/living/simple_animal/friendly/cat.dm
> +			for(var/mob/living/snack in oview(src))
```suggestion
			for(var/mob/snack in oview(src))
```

2023-02-11 02:19 UTC, Zonespace27 commented on code/modules/mob/living/simple_animal/friendly/cat.dm
> +	QDEL_NULL(movement_target)
don't QDEL_NULL; this'll delete whatever it's chasing if it gets deleted

2023-02-20 20:43 UTC, Zonespace27 approved these changes

2023-02-20 20:43 UTC, merged