the xm88 cursor now applies when it should, and has a preference
cmss13-devs/cmss13 pull request #2449
Opened 2023-01-22 21:41 UTC by harryob

moaning does work people, just look. i also added a preference if anyone wanted to added more tgmc-ification cursors in the future for the boomers to opt out of

:cl:
fix: the xm-88 mouse cursor was appearing when it shouldn't (without the scope), and you can now opt out of seeing custom mouse cursors entirely
/:cl:

2023-02-04 15:13 UTC, Zonespace27 requested changes

2023-02-04 15:13 UTC, Zonespace27 commented on code/__DEFINES/dcs/signals/atom/signals_item.dm
> +#define COMSIG_ITEM_ZOOM "item_zoom"
please do me a favor and code doc these defines with the args they take in

2023-02-04 15:13 UTC, Zonespace27 commented on code/modules/client/preferences.dm
> +	var/custom_cursors = TRUE
codedoc

2023-02-16 11:14 UTC, stanalbatross requested changes

2023-02-16 11:14 UTC, stanalbatross commented on code/modules/client/preferences.dm
> +
for maintainability reasons shouldn't this use a proc, since it's used in multiple places?

2023-02-27 12:20 UTC, merged