Explosion caps
cmss13-devs/cmss13 pull request #2471
Opened 2023-01-25 03:37 UTC by realforest2001

# About the pull request
Puts a hardcoded capacity on explosions.

# Explain why it's good for the game
Reduces the liklihood of accidental or otherwise death of server.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
code: Explosions are now hard-capped by code.
/:cl:

2023-01-25 07:19 UTC, Zonespace27 commented on code/datums/autocells/explosion.dm
> +	if(power > 5000)
This should probably be either a define or config

2023-01-27 03:22 UTC, morrowwolf requested changes
Zonespace comment

2023-01-28 02:28 UTC, morrowwolf requested changes

2023-01-28 02:28 UTC, morrowwolf commented on code/datums/autocells/explosion.dm
> +		log_debug("[explosion_cause_data.cause_name] exploded with force of [power]. Overriding to capacity of 5000.")
The 5000 here should be the define as well.

2023-02-02 02:23 UTC, merged