Adds a custom xeno builder
cmss13-devs/cmss13 pull request #2486
Opened 2023-01-26 22:15 UTC by Canohaaaaaaa

# About the pull request
Adds the verb ```Create Custom Xeno``` giving access to the **Gene Tailor**
Also included is a refactor of the majority of xeno powers and behaviour delegates.

The tool includes a variable editor in the **_stat_** tab with a few of them sorted for ease of use, an **_ability_** tab to add an unlimited amount of xeno abilities and passives.

![6zJb8qTQHv](https://user-images.githubusercontent.com/43523227/214959318-a1188bc3-9a30-42aa-bc23-308e20f78297.png)

The evolution tab allows the user to set what the custom xeno can evolve to, and critically what it can evolve FROM, since the ```apply genome``` button is here to create a new caste or strain at runtime, so future xeno can evolve into your custom creation without you having to spawn a bunch of them and fiddle with mind transfers.

The appearance tab is W.I.P and will not be done in this PR, it would require another refactor for very little benefits right now and this PR is large enough for my taste.

# Explain why it's good for the game

I think this is a good event and prototyping tool, xenomorphs getting an abomination or a few larvae as compensation for events gets old really fast, so that's something for admins to run their events with.

Here's what can be done with : 

![dreamseeker_sM1UTXRWGn](https://user-images.githubusercontent.com/43523227/214959484-3c3100b3-96d0-44d7-8d22-6a46e0d2f292.gif)

![dreamseeker_PZjvDJKTXY](https://user-images.githubusercontent.com/43523227/214960982-96b03fd0-9ff7-4c05-9a26-3a518bd99079.gif)
![dreamseeker_iglhih3plC](https://user-images.githubusercontent.com/43523227/214961001-a5c61cd1-f8bf-48f8-9cfd-17d6c93c8595.gif)

Note that multiple passives can be stacked, and combined with the behaviour delegate refactor it allows combinations of special ressource xeno abilties AND passives in a single carbon.
A defender with acider passive, hedgehod passive, berserker passive and a bunch of their abilities

![dreamseeker_2nGuIx72IA](https://user-images.githubusercontent.com/43523227/214961324-34fb3e1a-5358-424d-b891-a3f106785c6f.gif)

# Gene tailor guide
### W.I.P
# Testing Photographs and Procedure

<details>
Still W.I.P, every ability and delegate was tested during the refactors but I plan to do it again before un-drafting.
</details>

# Changelog

:cl:
add: Added a custom xeno builder under the "Create Custom Xeno" verb.
refactor: Most xeno powers related attributes were decoupled from behaviours delegate, allowing for better modularity.
refactor: Behaviour delegates are more generic, new ability hook procs added, allowing for better modularity.
fix: lurker : Crippling Strike properly indicates slows
fix: lurker : Invisibility is properly turned off when hitting an hostile xenomorph
/:cl:

2023-02-02 21:14 UTC, harryob requested changes
nothing much, excellent code all round

2023-02-02 21:14 UTC, harryob commented on code/modules/mob/living/carbon/xenomorph/mutators/behavior_delegate.dm
> +// This datum is meant to be M.O.D.U.L.A.R, you should NOT assume your delegate will be held by any specific xenomoprh.
```suggestion
// This datum is meant to be M.O.D.U.L.A.R, you should NOT assume your delegate will be held by any specific xenomorph.
```

2023-02-02 21:14 UTC, harryob commented on code/modules/mob/living/carbon/xenomorph/abilities/xeno_action.dm
> +	//TODO.. fix this
was this a todo for this pr or a later pr

2023-02-02 21:14 UTC, harryob commented on code/modules/mob/living/carbon/xenomorph/abilities/warrior/warrior_powers.dm
> +		return //this gives target little feedback on why your lunge didn't hit other than the lunge button going grey. Plus, it might spook marines that almost got lunged if they know why the message appe
find and replace?

2023-02-02 21:15 UTC, harryob commented
i have faith, but uh... just incase

2023-02-15 11:44 UTC, stanalbatross commented on code/modules/admin/gene_tailor/gene_tailor.dm
> +			if(!choice || choice == "No")
easier to just do if choice != "Yes"

2023-02-26 10:06 UTC, harryob requested changes
i tm'd this a week ago and completely forgot to say - this breaks rav speed

2023-03-14 00:26 UTC, closed without merging