Lets Xeno's unbuckle from Operating Tables
cmss13-devs/cmss13 pull request #2505
Opened 2023-01-28 07:33 UTC by BeagleGaming1

# About the pull request

Xenos attacking the Operating Table causes them to rip the anesthetic system away from the marine, unbuckling them, allowing them to either capture if alive or drag away chestbursted marines if dead.

# Explain why it's good for the game

Fixes issue #2453 and allows Xenos to actually cap people on operating tables

(I don't know if this is a fix or a feature, I asked and was told to just go with fix)
# Changelog

:cl:
fix: Xenos can unbuckle marines from Operating Tables
/:cl:

2023-01-29 01:16 UTC, Zonespace27 commented on code/game/machinery/OpTable.dm
> +		return
this return does nothing

2023-01-29 01:16 UTC, Zonespace27 commented on code/game/machinery/OpTable.dm
> +		playsound(alien.loc, "alien_claw_flesh", 25, 1)
```suggestion
		playsound(alien, "alien_claw_flesh", 25, 1)
```
playsound already performs a `get_turf()` operation

2023-01-29 23:55 UTC, stanalbatross requested changes

2023-01-29 23:55 UTC, stanalbatross commented on code/game/machinery/OpTable.dm
> +		unbuckle(user)
needs to call parent if there is no buckled mob

2023-01-30 14:06 UTC, harryob approved these changes

2023-01-31 07:46 UTC, merged