some extra keybinds
cmss13-devs/cmss13 pull request #2544
Opened 2023-02-02 16:54 UTC by harryob

adds keybinds for:
- joining as xeno from observe
- viewing hive status as xeno
- hiding as xeno
- evolving as xeno
- cancelling camera view

adds action buttons for:
- joining as xeno from observe
- evolving as xeno (appears when you can actually evolve)

:cl:
qol: added keybinds for joining as xeno, viewing hive status, hiding, evolving and cancelling camera view
qol: added actions buttons for evolving and joining as xeno
code: actions can listen for a keybind to activate the action
/:cl:

2023-02-02 19:06 UTC, Zonespace27 commented on code/datums/action.dm
> +	return
does nothing
~~also a codedoc comment for this proc would be pretty cool~~

2023-02-02 19:06 UTC, Zonespace27 commented on code/datums/keybinding/living.dm
> +	if(istype(used_mob, /mob/living))
```suggestion
	if(isliving(used_mob))
```

2023-02-02 19:06 UTC, Zonespace27 commented on code/datums/keybinding/xenomorph.dm
> +		return
```suggestion
	if(!current_xeno?.hive)
		return
```

2023-02-02 19:06 UTC, Zonespace27 commented on code/modules/mob/dead/observer/actions.dm
> +		owner.balloon_alert(owner, "game must start!")
probably should be one OR the other, not both

2023-02-02 19:06 UTC, Zonespace27 commented on code/modules/mob/dead/observer/actions.dm
> +	return TRUE
```suggestion
	return isobserver(user?.mob))
```

2023-02-10 04:19 UTC, kugamo approved these changes
Sprites are fine

2023-02-24 04:50 UTC, Agameofscones approved these changes
these'll do for now. Sprites approved

2023-03-16 07:20 UTC, morrowwolf approved these changes
Code looks fine.

2023-03-16 07:29 UTC, morrowwolf requested changes

2023-03-16 07:29 UTC, morrowwolf commented on code/datums/keybinding/xenomorph.dm
> +		to_chat(src, SPAN_WARNING("There is no Queen. You are alone."))
I lied, these need to be sent to the xeno rather than the datum.

2023-03-16 07:29 UTC, morrowwolf commented on code/datums/keybinding/xenomorph.dm
> +		to_chat(src, SPAN_WARNING("A headhunter temporarily cut off your psychic connection!"))
Same as above

2023-03-17 12:54 UTC, merged