mentors/admins can now appear to players as a ghostly SEA
cmss13-devs/cmss13 pull request #2548
Opened 2023-02-03 15:24 UTC by harryob

this doesn't get rid of the SEA role, but if a mentor wants to be able to help a player out without actually getting into the game, this might be useful

i'm not sure if we actually wanna do this or if it's -soul -lore -good but whatever

:cl:
add: mentors can now appear as an imaginary SEA to newer players in need of a hand
/:cl:

2023-02-10 04:17 UTC, kugamo approved these changes
sprites

2023-02-18 21:58 UTC, morrowwolf requested changes

2023-02-18 21:58 UTC, morrowwolf commented on code/modules/admin/tabs/admin_tab.dm
> +			var/mob/selected_mob = tgui_input_list(user, "Select a mob", "Imaginary Friend", GLOB.living_mob_list)
Probably want to remove clientless mobs from this list.

2023-02-18 22:17 UTC, morrowwolf requested changes

2023-02-18 22:17 UTC, morrowwolf commented on code/modules/mob/camera/imaginary_friend.dm
> +	ghost.mind.original = aghosted_original_mob
Possible mind check is required here, sometimes it doesn't seem to exist and I'm not certain why yet

2023-02-19 20:45 UTC, morrowwolf approved these changes

2023-02-19 20:45 UTC, merged