fixed a few random runtimes
cmss13-devs/cmss13 pull request #2580
Opened 2023-02-06 17:01 UTC by stanalbatross

# About the pull request
title

# Changelog

:cl:
fix: fixed some small or uncommon runtimes
/:cl:

2023-02-06 18:14 UTC, Zonespace27 requested changes

2023-02-06 18:15 UTC, Zonespace27 commented on code/modules/tgui/tgui.dm
> +	/// sanity...
I can't find the draft button on mobile so imagine I did

2023-02-06 23:26 UTC, stanalbatross commented on code/modules/tgui/tgui.dm
> +	/// sanity...
you cant draft on git mobile i hate it here

2023-02-07 16:08 UTC, Zonespace27 approved these changes

2023-02-07 16:08 UTC, merged