Uncommon ASRS monkey/dog/cat stowaway random event
cmss13-devs/cmss13 pull request #2584
Opened 2023-02-06 20:35 UTC by PhantomEpicness

# About the pull request
Random stowaway monkey/dog/cat/bat event. A small event to break up the boringness of req. When triggered, it will spawn between 1-2 creatures of:

- Monkey and Monkey subtypes
- Cat/Dog
- Bat

# Explain why it's good for the game
Breaking up shipside monotony.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

https://user-images.githubusercontent.com/42422230/217079259-e143077c-2bc2-4f83-8c02-37c86e980acd.mp4

# Changelog

:cl: Totalepicness5
add: Added an Uncommon ASRS monkey/dog/cat stowaway random event
/:cl:

2023-02-07 14:03 UTC, harryob requested changes

2023-02-07 14:03 UTC, harryob commented on code/game/supplyshuttle.dm
> +		to_chat(world,"spec spawntick")
remove this...

2023-02-07 14:03 UTC, harryob commented on code/game/supplyshuttle.dm
> +			to_chat(world,"spawntick")
¬¬¬¬

2023-02-07 14:03 UTC, harryob commented on code/modules/events/asrs_animals.dm
> +	to_chat(world,"ebent start")
dasdwad

2023-02-07 14:03 UTC, harryob commented on code/modules/events/asrs_animals.dm
> +	ai_announcement(input)
```suggestion
	ai_announcement("Unidentified lifesigns detected inside Automated Supply Retrieval System.")
```

2023-02-07 14:03 UTC, harryob commented on code/game/supplyshuttle.dm
> +/datum/controller/supply/proc/handle_animal_event()
ccccodeddddocc....

2023-02-07 14:03 UTC, harryob commented on code/game/supplyshuttle.dm
> +		for(var/i=0,i < rand(1,2),i++)
```suggestion
		for(var/i in rand(1,2))
```

2023-02-07 14:03 UTC, harryob commented on code/modules/events/asrs_animals.dm
> +	msg = "An ASRS animal event has been triggered!"
```suggestion
	var/msg = "An ASRS animal event has been triggered!"
```

2023-02-22 20:41 UTC, PhantomEpicness commented on code/modules/events/asrs_animals.dm
> +	to_chat(world,"ebent start")
whops sorry

2023-02-22 20:42 UTC, PhantomEpicness commented on code/game/supplyshuttle.dm
> +/datum/controller/supply/proc/init_animal_event()
so true thanks

2023-03-15 00:29 UTC, closed without merging