Nesting bug fix
cmss13-devs/cmss13 pull request #259
Opened 2022-05-09 19:07 UTC by Shad0vvs

## About The Pull Request

We must double check so that the dead xeno 2000 zlevels away does not do things.

## Why It's Good For The Game

Bugfix

## Changelog

:cl:
fix: Properly fixes an unnesting bug and now also logs the unnest on the unnesting mob as well.

/:cl:

2022-05-09 19:26 UTC, stanalbatross approved these changes

2022-05-12 16:49 UTC, Geevies requested changes

2022-05-12 16:49 UTC, Geevies commented on code/game/objects/structures/stool_bed_chair_nest/xeno_nest.dm
> +			if(!user.Adjacent(H) || user.stat || user.lying || user.is_mob_restrained())
this should also check if buckled_mod is still exists

2022-05-12 17:54 UTC, Geevies approved these changes

2022-05-12 17:54 UTC, merged