'Shards' now fly off sometimes when armor resists a slash
cmss13-devs/cmss13 pull request #2654
Opened 2023-02-15 00:58 UTC by carlarctg

# About the pull request

'Shards' now fly off sometimes when armor resists a slash.

What this means is that if armor absorbs (less than 34% of raw slash damage) or softens (66%), white 'sparks' will fly off with a 33 or 15 chance respectively, the amount being bigger on absorbed hits.

Added a subtype for spark effects that uses a recolored white spark effect.

# Explain why it's good for the game

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
add: 'Shards' now fly off sometimes when armor resists a slash
/:cl:

2023-02-16 06:49 UTC, harryob approved these changes
code fine

2023-02-21 15:29 UTC, Zonespace27 commented on code/game/objects/effects/effect_system/effect_system.dm
> +	var/spark_duration = 2 SECONDS
code doc

2023-02-21 20:44 UTC, carlarctg commented on code/game/objects/effects/effect_system/effect_system.dm
> +	var/spark_duration = 2 SECONDS
HUH??????]

2023-02-22 19:55 UTC, Zonespace27 requested changes

2023-02-22 19:55 UTC, Zonespace27 commented on code/game/objects/effects/effect_system/effect_system.dm
> +	var/sound_to_play = "sparks"
codedoc

2023-02-22 19:55 UTC, Zonespace27 commented on code/game/objects/effects/effect_system/effect_system.dm
>  // T.hotspot_expose(1000,100)
these may not be yours, but removing them would be nice

2023-02-22 19:55 UTC, Zonespace27 commented on code/game/objects/effects/effect_system/effect_system.dm
> +	var/obj/effect/particle_effect/sparks/sparks_type = /obj/effect/particle_effect/sparks
code doc + why is this a casted var when it's a type that never utilizes initial() anywhere

2023-02-22 19:55 UTC, Zonespace27 commented on code/modules/mob/living/carbon/xenomorph/attack_alien.dm
> +					var/datum/effect_system/spark_spread/armor_shards/effect = new /datum/effect_system/spark_spread/armor_shards
```suggestion
					var/datum/effect_system/spark_spread/armor_shards/effect = new
```

2023-02-22 19:55 UTC, Zonespace27 commented on code/modules/mob/living/carbon/xenomorph/attack_alien.dm
> +					var/datum/effect_system/spark_spread/armor_shards/effect = new /datum/effect_system/spark_spread/armor_shards
```suggestion
					var/datum/effect_system/spark_spread/armor_shards/effect = new
```

2023-02-24 04:21 UTC, Agameofscones commented
Cool system that improves information readability,*but* goofy ass particles. Recommending they get resprited

2023-03-15 18:31 UTC, harryob requested changes
ci fail

2023-03-15 18:31 UTC, harryob commented on code/modules/mob/living/carbon/xenomorph/attack_alien.dm
> +					var/datum/effect_system/spark_spread/armor_shards/effect = new
```suggestion
					var/datum/effect_system/spark_spread/armor_shards/effect = new()
```

2023-03-15 19:57 UTC, Zonespace27 commented on code/game/objects/effects/effect_system/effect_system.dm
> +	var/obj/effect/particle_effect/sparks/sparks_type
```suggestion
	var/obj/effect/particle_effect/sparks/sparks_type = /obj/effect/particle_effect/sparks
```
Stops flaky CI fails

2023-03-23 00:28 UTC, closed without merging