Research/CAS further colab/features
cmss13-devs/cmss13 pull request #2656
Opened 2023-02-15 02:09 UTC by kiVts

# About the pull request
Wooo
This adds super dirt cheap minirocket ammo to CAS which does absolutely nothing on its own but create a smoke screen
instead, this can accept any chemical to create a chemical smoke, No it wont allow for custom explosion chemical to be used.
this allows for 
Mass frontline stimming(this is deserved considering how hard is it to get for research)
Mass xeno disruption, 
Mass xeno armor debuff and so on
Mass marine healing????
phosphorus smoke????? 
can custom fuel be used in this case??? not sure.
this allows for other not research things like mass marine feeding(lmao)
chemicals can be mixed and they can be diluted
 Im still missing sprites(currently using inc, will draw them tmr) and probably lots of *bad* code so don't merge it
This generally simplifies the logistics problems research been facing since cave age
this also will encourage to get better OD levels as the numbers can get *very big* when marine is under smoke of stims, or dilute it with water.

# Explain why it's good for the game

More connections  with research to outside world is good 👍 

# Testing Photographs and Procedure

<details>

<summary>Screenshots & Videos</summary>

I did test this

</details>

# Changelog

:cl: KiVts
add: A chemical mini rocket ammo for CAS, Which can be used by research to rapidly deploy chemicals on the battlefield, with help of CAS
/:cl:

2023-02-15 02:19 UTC, LynxSolstice commented
+1 silly idea

2023-02-15 08:26 UTC, harryob requested changes

2023-02-15 08:26 UTC, harryob commented on code/modules/cm_marines/dropship_ammo.dm
> +				desc = initial(desc) + "\nThere is a chemical in the recepticle."
you can do this in the get_examine_text proc for certain states

2023-02-15 08:26 UTC, harryob commented on code/modules/cm_marines/dropship_ammo.dm
> +	var/chemical = null
null on destroy

2023-02-15 16:50 UTC, kiVts commented
![image](https://user-images.githubusercontent.com/48099872/219096988-4ea3e203-42cc-44dc-bf91-e772e6007b96.png)
sprite

2023-02-15 16:51 UTC, kiVts commented
fuick I forgot

2023-02-20 22:01 UTC, Zonespace27 requested changes

2023-02-20 22:01 UTC, Zonespace27 commented on code/modules/cm_marines/dropship_ammo.dm
> +				to_chat(user, SPAN_NOTICE("You insert the beaker into chemical recepticle"))
```suggestion
				to_chat(user, SPAN_NOTICE("You insert the beaker into chemical receptacle."))
```

2023-02-20 22:01 UTC, Zonespace27 commented on code/modules/cm_marines/dropship_ammo.dm
> +			if(istype(W, /obj/item/reagent_container/glass/beaker/large) && W.reagents.total_volume == 120)
why does this need to be very specifically a large beaker with == 120u

2023-02-20 22:01 UTC, Zonespace27 commented on code/modules/cm_marines/dropship_ammo.dm
> +		var/datum/effect_system/smoke_spread/S = new/datum/effect_system/smoke_spread()
```suggestion
		var/datum/effect_system/smoke_spread/smoke = new
```
change other vars too

2023-02-21 00:59 UTC, kiVts commented on code/modules/cm_marines/dropship_ammo.dm
> +		if(!ammo_count && loc)
literally copypasted from all other minirockets????? no? it doesnt work like that? do I remove it?

2023-02-21 01:34 UTC, Zonespace27 commented on code/modules/cm_marines/dropship_ammo.dm
> +		if(!ammo_count && loc)
if it's copypasted then sure ig

2023-02-26 12:57 UTC, Herotitan772 commented
i feel like cas has needed some love for a long long time, this is a good idea, i believe that it should be both an OT and research thing, possibly, research can make the (as you have described) chemical based effects and OT can make more explosive based ammunition.
I dont see this as an OP thing because as is OT is hamstrung by the hard explosive cap (WHICH IS DUMB), which limits the strength of OT explosives (the max strength is pitiful, can BARELY kill a tier 1 with a DIRECT hit from a maxcap mortar. everything else is unable to do enough damage, and the fire maxcap is basically to the level of greenfire from pyro (just without the slowing effect))

2023-03-02 16:01 UTC, harryob requested changes
one last bit and we should be good to go

2023-03-02 16:01 UTC, harryob commented on code/modules/cm_marines/dropship_ammo.dm
> +	var/state = ASSEMBLY_EMPTY /// current assembly state of the chemsmoke minircoket
```suggestion
	/// chemical(s) in the chemical minirocket
	var/chemical
	/// current assembly state of the chemsmoke minircoket
	var/state = ASSEMBLY_EMPTY 
```

2023-03-02 16:52 UTC, kiVts commented on code/modules/cm_marines/dropship_ammo.dm
> +	var/state = ASSEMBLY_EMPTY /// current assembly state of the chemsmoke minircoket
done

2023-03-15 14:37 UTC, kiVts commented
so there was already unused minirocket sprite meant for flares, so using that instead of drawing a new one. just renamed it for sake for being understandable, doesnt touch anything about sprites anymore

2023-03-17 05:35 UTC, Herotitan772 commented
Tested this today and have a few problems:
First being that the range is way to small, current is a 1 radius plus sign shaped smoke cloud, it should be at least a 3 radius smoke cloud

Seccond being as segrain said full beakers don’t seem to work (equality check???)

third being the major problem…. It doesn’t work… we tested it with a beaker of bi and Kelo and it did nothing…. Tested with a full volley of direct hits…. I suspect this is a problem with chem smoke in general and not specifically this TM but I could be wrong

2023-03-17 09:41 UTC, cm13-github commented
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
CM13 Live Instance

##### Revision
Origin: 6a2cf07b91be24fbcbc651e8a46a8ae6445dd924
Pull Request: 47fd4e96d9b63865f6bd25a97dc77f82d3827d43
Server: 0f1dac4dcb22794ac0797cee8eb9c5b0b7c5e7f8

##### Comment

</details>

2023-03-17 11:23 UTC, kiVts commented
> Tested this today and have a few problems: First being that the range is way to small, current is a 1 radius plus sign shaped smoke cloud, it should be at least a 3 radius smoke cloud
> 
> Seccond being as segrain said full beakers don’t seem to work (equality check???)
> 
> third being the major problem…. It doesn’t work… we tested it with a beaker of bi and Kelo and it did nothing…. Tested with a full volley of direct hits…. I suspect this is a problem with chem smoke in general and not specifically this TM but I could be wrong

ughm... yeah there should be an equality check...

2023-03-17 11:25 UTC, kiVts commented
> Tested this today and have a few problems: First being that the range is way to small, current is a 1 radius plus sign shaped smoke cloud, it should be at least a 3 radius smoke cloud
> 
> Seccond being as segrain said full beakers don’t seem to work (equality check???)
> 
> third being the major problem…. It doesn’t work… we tested it with a beaker of bi and Kelo and it did nothing…. Tested with a full volley of direct hits…. I suspect this is a problem with chem smoke in general and not specifically this TM but I could be wrong

on top of that can you tell about "doesnt work" part better ?

2023-03-17 12:29 UTC, Herotitan772 commented
> > Tested this today and have a few problems: First being that the range is way to small, current is a 1 radius plus sign shaped smoke cloud, it should be at least a 3 radius smoke cloud
> > Seccond being as segrain said full beakers don’t seem to work (equality check???)
> > third being the major problem…. It doesn’t work… we tested it with a beaker of bi and Kelo and it did nothing…. Tested with a full volley of direct hits…. I suspect this is a problem with chem smoke in general and not specifically this TM but I could be wrong
> 
> on top of that can you tell about "doesnt work" part better ?

Sorry I should have elaborated

So I put a beaker of kelo and bica (60 units of each in a 120 unit large beaker) in the smoke missile pod and loaded it (no issues apart from having to take 10 units out before we could load the beaker in (equality check)). I then went groundside and we tested firing a full volley at a signal flare I was standing on, the smoke was an orangy colour (so the chems were defiantly in the smoke (we had tested just the smoke rounds with no chems earlier and it was white)) and directly hit me and I stood in it for the entire duration, but sadly there was no effect, I scanned myself with a scanner and I had no chems in my system (I checked whilst I was in the smoke and every ~10 seconds after for about 2 minutes and no change)

I’ll keep testing it to see if I can get it working, I’ll keep you posted

2023-03-17 12:46 UTC, kiVts commented
> > > Tested this today and have a few problems: First being that the range is way to small, current is a 1 radius plus sign shaped smoke cloud, it should be at least a 3 radius smoke cloud
> > > Seccond being as segrain said full beakers don’t seem to work (equality check???)
> > > third being the major problem…. It doesn’t work… we tested it with a beaker of bi and Kelo and it did nothing…. Tested with a full volley of direct hits…. I suspect this is a problem with chem smoke in general and not specifically this TM but I could be wrong
> > 
> > 
> > on top of that can you tell about "doesnt work" part better ?
> 
> Sorry I should have elaborated
> 
> So I put a beaker of kelo and bica (60 units of each in a 120 unit large beaker) in the smoke missile pod and loaded it (no issues apart from having to take 10 units out before we could load the beaker in (equality check)). I then went groundside and we tested firing a full volley at a signal flare I was standing on, the smoke was an orangy colour (so the chems were defiantly in the smoke (we had tested just the smoke rounds with no chems earlier and it was white)) and directly hit me and I stood in it for the entire duration, but sadly there was no effect, I scanned myself with a scanner and I had no chems in my system (I checked whilst I was in the smoke and every ~10 seconds after for about 2 minutes and no change)
> 
> I’ll keep testing it to see if I can get it working, I’ll keep you posted

weird, last time I tested it on local CO had all the kind of chemicals in him that I fired.

2023-03-17 14:37 UTC, cm13-github commented
#### Test Merge Removed

2023-03-17 15:57 UTC, Herotitan772 commented
Alrighty sorry for the false information on my part, I just tested it again with a beaker full of bicard and it works a charm!

I am an idiot and didn’t realise I had an integrated gas mask on that’s on me….

so yeah I still believe that it needs to create a bigger cloud (my suggestion is a 3 radius cloud as opposed to the current 1 radius), but in terms of the functionality it works as intended

I also checked and after the recent update to this TM, full 120 unit beakers work

2023-03-25 00:44 UTC, kiVts commented
I consider this a failure

2023-03-29 15:46 UTC, kiVts commented
how did I not close this muh

2023-03-29 15:46 UTC, closed without merging