M276 Combat Toolbelt Rig
cmss13-devs/cmss13 pull request #2658
Opened 2023-02-15 06:00 UTC by Sulaboy

Adds the M276 pattern combat toolbelt rig as to the game as a new belt for combat engineers and some other roles.

"M276 pattern combat toolbelt rig"
The M276 is the standard load-bearing equipment of the USCM. It consists of a modular belt with various clips and pouches for tools along with a holster for a sidearm and additional magazines. This version is commonly used by engineers conducting repairs within combat zones."

The M276 pattern combat toolbelt is an improved version of the M276 pattern toolbelt with combat capabilities. This rig is capable of carrying the same amount of tools and has three additional slots intended for a handgun and magazines for said handgun. 

# Explain why it's good for the game

Squad Combat Technicians have a large amount of tools and equipment that they must bring into battle and are very limited by storage space. I have seen some engineers take toolboxes into battle because they're more space efficient. This belt lets engineers fit a sidearm into their builds and should hopefully give them some other space for that light replacer everyone tosses.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

![combatbelt showcase](https://user-images.githubusercontent.com/75421103/218943761-a188b2b2-2125-45eb-a15e-5eb9c7b02c95.png)

</details>

**Disclaimer, I barely know how to code. If I need to make any tweaks please be patient with me.**

# Changelog

:cl:
add: Added item M276 pattern combat toolbelt rig
change: Replaced option to vend M276 pattern toolbelt rig as belt with M276 pattern combat toolbelt rig in Vehicle Crewman Vendor, Squad Leader Vendor, Radio Telephone Operator Vendor, Combat Technician Vendor.
change: Replaced M276 pattern toolbelt rig with M276 pattern combat toolbelt rig on round start Whiskey Outpost Engineers
change: Tweaked the description of the M276 pattern toolbelt rig to now be the standard load bearing equipment of the USCM _Support Staff_
imageadd: Sprites for M276 pattern combat toolbelt rig
/:cl:

2023-02-15 06:03 UTC, Zonespace27 requested changes

2023-02-15 06:03 UTC, Zonespace27 commented on code/modules/projectiles/guns/pistols.dm
> +	desc = "An M4A3 Service Pistol, a stinky test pistol for testing changing code with a running server and being stinky."
.

2023-02-15 06:03 UTC, Zonespace27 commented on code/modules/projectiles/guns/rifles.dm
> +	desc = "Stinky Gun Test Gun Test Stinky. Commonly carried by most combat personnel. Uses 10x24mm caseless ammunition."
.

2023-02-15 06:04 UTC, Sulaboy commented on code/modules/projectiles/guns/pistols.dm
> +	desc = "An M4A3 Service Pistol, a stinky test pistol for testing changing code with a running server and being stinky."
That wasn't supposed to be there.

2023-02-15 06:15 UTC, Sulaboy commented on code/modules/projectiles/guns/rifles.dm
> +	desc = "Stinky Gun Test Gun Test Stinky. Commonly carried by most combat personnel. Uses 10x24mm caseless ammunition."
Fixed

2023-02-15 06:17 UTC, morrowwolf requested changes
GA review:

This is far too powerful and power creep in its current state. This belt needs to be balanced alongside other belts rather than be a straight upgrade.

2023-02-15 07:57 UTC, Sulaboy commented
> GA review:
> 
> This is far too powerful and power creep in its current state. This belt needs to be balanced alongside other belts rather 
than be a straight upgrade.

Didn't get this to you before you got off for the night. Here is the picture with the belt capacity comparisons. I'll definitely be cutting out a magazine and slot from the belt at least or both if you think that's the way to go. Let me know if you would like it to be a point buy as well. I'll make any changes to this on Friday.

![asdf](https://user-images.githubusercontent.com/75421103/218965935-ab3bfd5e-47f9-4ee3-8bfd-164e32a6924e.png)

2023-02-16 10:25 UTC, Sulaboy commented
Removed a slot from the belt to put it more in line with other belts, and added a point cost. Removed any addition of the belt from other vendors and WO spawns.

2023-02-19 22:33 UTC, morrowwolf reviewed
GA Approved. Usual disclaimer: maintainer team can and will change this item in whatever way (including completely reverted) if it effects balance in a way unforeseen.

2023-02-21 22:49 UTC, NewyearnewmeUwu commented
IMO, this should be the lifesaver bag to the medical rig or vice versa. A sidegrade, not an upgrade or a downgrade. There are some things the medical rig legitimately does better, but most of the time the livesaver is the nobrainer pick.

2023-02-24 04:20 UTC, Agameofscones requested changes
should be `+combatutility_half`. Current is incorrect as `+combatutility`. (sprite state names)

Otherwise sprites checkout. Ping me when you've fixed it and I'll approve.

2023-02-25 21:39 UTC, Zonespace27 commented on code/game/objects/items/storage/belt.dm
> +	icon_state = "combatutility"
```suggestion
	icon_state = "combatutility"
```

2023-02-25 21:39 UTC, Zonespace27 approved these changes

2023-02-25 21:40 UTC, Zonespace27 commented
Looks good

2023-02-25 21:40 UTC, merged