Makes braziers and torches craftable by Yautja
cmss13-devs/cmss13 pull request #2693
Opened 2023-02-20 06:30 UTC by carlarctg

# About the pull request

Braziers and torches can now be crafted with runed sandstone sheets by Yautja. Braziers need to be filled with wood and then lit. Torches just need to be lit.

# Explain why it's good for the game

More cool lodge detail

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
imageadd: Braziers and torches can now be crafted with runed sandstone sheets by Yautja. Braziers need to be filled with wood and then lit. Torches just need to be lit.
/:cl:

2023-02-20 06:42 UTC, Agameofscones approved these changes
Sprites are aight

2023-02-20 21:51 UTC, Zonespace27 requested changes

2023-02-20 21:51 UTC, Zonespace27 commented on code/game/objects/structures/props.dm
> +/obj/structure/prop/brazier/frame/attackby(obj/item/W, mob/user)
one letter vars bad

2023-02-20 21:51 UTC, Zonespace27 commented on code/game/objects/structures/props.dm
> +	wooden_boards.use(10)
requires 5, uses 10

2023-02-20 21:51 UTC, Zonespace27 commented on code/game/objects/structures/props.dm
> +/obj/structure/prop/brazier/frame_woodened/attackby(obj/item/W, mob/user)
one letter vars bad

2023-02-20 21:51 UTC, Zonespace27 commented on code/game/objects/structures/props.dm
> +/obj/structure/prop/brazier/torch/frame/attackby(obj/item/W, mob/user)
one letter vars bad

2023-02-20 21:51 UTC, Zonespace27 commented on code/game/turfs/walls/walls.dm
> +	if(istype(W, /obj/item/prop/torch_frame))
feels unnecessary, could be a desc/examine

2023-02-21 02:24 UTC, carlarctg commented on code/game/objects/structures/props.dm
> +	wooden_boards.use(10)
erm

2023-02-22 08:23 UTC, merged