LVV522: Chances Changes
cmss13-devs/cmss13 pull request #2695
Opened 2023-02-21 01:45 UTC by spartanbobby

# About the pull request

This PR makes numerous Changes to LV522 as well as adds more props to ease of mapper use

# Explain why it's good for the game

The areas changes and reasons why as are follows
**SW Reactor:** Entirely removed and replaced with a much more open containers area for the xenos to build up and defend, this area is now the linchpin of the map as marines have to push though it to get to other flanks inside the reactor meaning the xeno players should now have a much better understanding of where they need to defend instead of prior problems with the map of them being hard flanked and losing at 12:26

**LZ1:** LZ1 was moved slightly more north in an attempt to remove some deadspace and make the path from the front to the FOB slightly less long, more LZ1 tunnels and ways inside the FOB were added for xeno flankers aswell as LZ1 being locked down until the marines push a button to open it up

**Colony admin** A sensor tower was added to colony admin to encourage marines to go over there and investigate, along with a lockdown to the area being added 

**LZ3** a FORECON prop LZ housing the Tornado was re-added after being removed in an attempt to downsize the map, basically I figured out where I could put it

**props:** Alot of instanced props for the map were made into actual items such as, bedrolls and folded bedrolls, FORECON dogtags, used flares, jerry cans, used bandages and some weird gameboy thing

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:SpartanBobby
add: Made some instanced props on LV522 actual items for mapper ease of use
maptweak: tweaked LV522, removing the SW reactor and replacing it with a much more open container area once used as the FORECONS FOB
maptweak: tweaked LZ1 on LV522 making it start locked down and be slightly more north along with some extra tunnels and flanking routes for the xenos
maptweak: LV522, added a lockdown and moved the sensor tower to colony admin
maptweak: re-added the prop LZ in the NE of the colony
/:cl:

2023-02-21 07:37 UTC, harryob approved these changes
code looks good

2023-02-23 03:52 UTC, spartanbobby commented
Going to need another code review and sprite review because I managed to get the stuff for the FORECON patches

2023-02-23 15:48 UTC, harryob requested changes

2023-02-23 15:48 UTC, harryob commented on code/modules/gear_presets/forcon_survivors.dm
> +	var/random_pistol = rand(1,6)
does 5 get no pistol

2023-02-24 04:17 UTC, Agameofscones approved these changes
nice patch 😎

2023-02-25 00:20 UTC, merged