Much too creative changes to alcohol
cmss13-devs/cmss13 pull request #2706
Opened 2023-02-23 03:19 UTC by BeagleGaming1

# About the pull request

Turns alcohol into a proper property and adds a limit to the properties, you won't slur for 25 years from a single shot
(I will remove the drink if needed)
# Explain why it's good for the game

It really isnt

# Changelog

:cl:
add: Reworks alcohol and its property and makes it way too complicated
fix: Adds a limit to how long you will be slurring for after drinking alcohol
/:cl:

2023-02-23 04:54 UTC, Zonespace27 requested changes

2023-02-23 04:54 UTC, Zonespace27 commented on code/modules/reagents/chemistry_properties/prop_neutral.dm
> +		H.vomit()
this is all... completely unreadable
Please space it out (also no one letter variables)
Turning some of the numbers into defines wouldn't hurt

2023-02-23 04:54 UTC, Zonespace27 commented on code/modules/reagents/chemistry_reagents/alcohol.dm
> +	var/slur_start = 250 //This is when the properties are gonna hit. Drink in moderation.
code doc

2023-02-23 04:54 UTC, Zonespace27 commented on code/modules/reagents/chemistry_reagents/alcohol.dm
> +	var/booze_data = 0 //If it's a normal drink, let them drink a bit before they start feeling it.
Is this used anywhere anymore?

2023-03-01 22:43 UTC, harryob approved these changes
i looove properties wow!!

2023-03-01 22:43 UTC, merged