Fixes cats robusting larva
cmss13-devs/cmss13 pull request #2736
Opened 2023-02-26 21:52 UTC by PhantomEpicness

# About the pull request
Makes so huggers and larva can actually stand a chance against cats. 
Cats now do 20 damage and slugstun instead of instakill preys with clients

# Explain why it's good for the game
being instakilled isnt fun

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:totalepicness
fix: Fixes cats now do 20 damage and a flicker stun to prey instead of instakilling them.
/:cl:

2023-02-26 22:08 UTC, carlarctg commented
pusssy

2023-02-26 22:17 UTC, carlarctg commented
carlarc approved

2023-02-26 22:58 UTC, Diegoflores31 commented on code/modules/mob/living/simple_animal/friendly/cat.dm
> +	var/attack_damage = 15
you are not even using this var + it should be 25

2023-02-26 22:58 UTC, Diegoflores31 commented on code/modules/mob/living/simple_animal/friendly/cat.dm
> +						livingprey.apply_damage(25,BRUTE)
use the var here i guess

2023-03-01 14:01 UTC, harryob requested changes
diego's right

2023-03-07 07:49 UTC, harryob approved these changes

2023-03-07 07:49 UTC, merged