Adds the Maintenance Jack
cmss13-devs/cmss13 pull request #2746
Opened 2023-02-28 03:32 UTC by BeagleGaming1

# About the pull request

This PR gives the Maintenance Jack to ship synths in the experimental vendor and Working Joes for free.
Gives the Maintenance Jack bonus effects
(Had to give WJs Engi 3 for one of the Maintenance Jack's abilities, this shouldn't change much)

# Explain why it's good for the game

New tool for synths and WJs

# Changelog

:cl:
add: Added a Maintenance Jack for Synthetics (Experimental Vendor) and Working Joes (Standard Kit). It has two modes, being able to switch between a crowbar and a wrench. You can use it to unbolt doors, and, if strong enough, pry them open.
/:cl:

2023-02-28 06:04 UTC, Zonespace27 requested changes

2023-02-28 06:04 UTC, Zonespace27 commented on code/game/objects/items/weapons/weaponry.dm
> +/obj/item/weapon/melee/maintenance_jack //put here for unique action
why is this `/obj/item/weapon/melee`

2023-02-28 06:04 UTC, Zonespace27 commented on code/game/machinery/doors/airlock.dm
> +		if(current_jack.mode == "wrench")
have the string be a define or something

2023-02-28 06:04 UTC, Zonespace27 commented on code/game/machinery/doors/airlock.dm
> +			SPAN_NOTICE("You unbolt [src] airlock."))
how does this look in-game, considering the `[src] airlock` part

2023-02-28 06:04 UTC, Zonespace27 commented on code/game/objects/items/weapons/weaponry.dm
> +	var/mode = "crowbar"
code doc + put at bottom of type declaration

2023-02-28 06:04 UTC, Zonespace27 commented on code/game/objects/items/weapons/weaponry.dm
> +	set src in usr
this needs to be an actionbutton or use-in-hand functionality as well

2023-02-28 06:04 UTC, Zonespace27 commented on code/game/objects/items/weapons/weaponry.dm
> +	if(mode == "wrench")
else if?

2023-02-28 06:04 UTC, Zonespace27 commented on code/game/objects/items/weapons/weaponry.dm
> +	if(mode == "crowbar") //Wrench mode | Remove bolts if engi 3
use defines, as said before

2023-02-28 06:04 UTC, Zonespace27 commented on code/game/objects/items/weapons/weaponry.dm
> +	if(!(mode == "crowbar")) //Otherwise it lets you pry open right after unbolting
`!=` exists

2023-02-28 06:04 UTC, Zonespace27 commented on code/game/objects/items/weapons/weaponry.dm
> +	if(!(HAS_TRAIT(user, TRAIT_SUPER_STRONG))) //Only synths can force open doors, otherwise its a regular crowbar
extra set of brackets unneeded

2023-02-28 06:04 UTC, Zonespace27 commented on code/game/objects/items/weapons/weaponry.dm
> +/obj/item/weapon/melee/maintenance_jack/afterattack(obj, mob/living/user, proximity)
why is `obj` not typecasted
also change the var name

2023-02-28 06:04 UTC, Zonespace27 commented on code/game/objects/items/weapons/weaponry.dm
> +	if(get_dist(src, obj) > 1)
`proximity` arg?

2023-02-28 06:04 UTC, Zonespace27 commented on code/game/objects/items/weapons/weaponry.dm
> +		if(!(HAS_TRAIT(user, TRAIT_SUPER_STRONG))) //basically IS_PRY_CAPABLE_CROWBAR
second set of brackets not needed

2023-02-28 06:04 UTC, Zonespace27 commented on code/game/objects/items/weapons/weaponry.dm
> +					if(door.density)
is there really not a var for if the door is open or not

2023-02-28 06:04 UTC, Zonespace27 commented on code/game/objects/items/weapons/weaponry.dm
> +		if(do_after(user, 3 SECONDS, INTERRUPT_ALL, BUSY_ICON_HOSTILE))
early return

2023-03-03 01:48 UTC, carlarctg commented
improve your changelog it doenst say anything

2023-03-12 02:48 UTC, Agameofscones requested changes
These inhands are comically oversized. Consider designing around a modified crowbar inhand for a better scale.

2023-03-31 05:16 UTC, nauticall approved these changes
alright, good on ya for fixing em up, sprites approved now! 👍

2023-03-31 08:30 UTC, harryob requested changes

2023-03-31 08:30 UTC, harryob commented on code/game/objects/items/tools/maintenance_tools.dm
> +	. = ..()
can we do . = ..() at the start of the proc and return after the if(crowbar_mode) and removing the else block

2023-04-01 16:58 UTC, harryob approved these changes

2023-04-01 17:24 UTC, merged