New Steel Crest Ability: Soak
cmss13-devs/cmss13 pull request #2752
Opened 2023-03-02 00:19 UTC by DecemberIsHere

# About the pull request

This adds a new ability for the defender strain, Steel Crest called Soak. It is an ability that when activated, tracks damaged taken and once it reaches a threshold slightly heal the Steel Crest defender and reset the cooldown of its Tail Slam ability. The damage threshold needed to reach this state is 140 damage within 6 seconds, and will not do anything if it doesn't reach this cooldown.

# Explain why it's good for the game

Steel crest as a strain is extremely underwhelming, it's almost entirely dedicated to simply soaking damage. Its combat capabilities is withheld to headbutting from a corner and then going back in hiding. Its tail slam is underutilized as a result, and this PR will switch up gameplay and allow for steel crest to be a much more fun mix between its tanking ability, and its damage dealing aggressiveness. 

# Testing Photographs and Procedure

<details>
Tested against being hurt by a sentry while its active, it works. Will refresh your tail slam and slightly heal.
</details>

# Changelog
:cl: Usnpeepoo
add: Added a new ability to the Steel Crest strain, called Soak. It tracks your accumulated damage and once it reaches a threshold, reset your tail slam cooldown and slightly heal you.
/:cl:

2023-03-11 18:53 UTC, harryob requested changes

2023-03-11 18:53 UTC, harryob commented on code/modules/mob/living/carbon/xenomorph/abilities/defender/defender_abilities.dm
> +	var/damage_accumulated = 0 // Intially zero, gets damage added when the ability is activated
```suggestion
	/// Requires 140 damage taken within 6 seconds to activate the ability
	var/damage_threshold = 140
	/// Initially zero, gets damage added when the ability is activated
	var/damage_accumulated = 0
```

2023-03-11 18:53 UTC, harryob commented on code/modules/mob/living/carbon/xenomorph/abilities/defender/defender_powers.dm
> +	return
```suggestion
	return ..()
```

2023-03-11 18:53 UTC, harryob commented on code/modules/mob/living/carbon/xenomorph/abilities/defender/defender_powers.dm
> +	damage_accumulated += damage_taken
```suggestion
	damage_accumulated += damage_data["damage"]
```

2023-03-11 18:53 UTC, harryob commented on code/modules/mob/living/carbon/xenomorph/abilities/defender/defender_powers.dm
> +	to_chat(src, SPAN_XENONOTICE("You stop taking in oncoming damage."))
send this to the owner, src is the datum

2023-03-11 18:53 UTC, harryob commented on code/modules/mob/living/carbon/xenomorph/abilities/defender/defender_powers.dm
> +		slam_action.end_cooldown()
```suggestion
	var/datum/action/xeno_action/activable/tail_stab/slam/slam_action = locate() in owner.actions
	
	if (slam_action && !slam_action.action_cooldown_check())
		slam_action.end_cooldown()
```

2023-03-11 19:28 UTC, harryob approved these changes

2023-03-12 02:57 UTC, Agameofscones requested changes
the ability icon here is nearly identical to the pre-existing crest_defense.

It needs to be differentiated more heavily.

2023-03-13 05:44 UTC, morrowwolf reviewed
Looks cool balance-wise, let's see how it goes in testing though. Get the sprite changes sorted. In the meantime I'll testmerge and keep an eye on it.

2023-03-14 01:55 UTC, morrowwolf approved these changes
Balance seems fine and was functional. Maybe one day we'll get people to play steelcrest.

Sort the sprite stuff and we're good to go.

2023-03-25 00:24 UTC, sleepynecrons requested changes
The new icon is better but the glowing effect is a bit messy. Try something like this 

![5yjdHDT](https://user-images.githubusercontent.com/106241650/227666286-718bf11b-069f-4ada-9a9b-953ce4eeb83c.png)

You could also make the glowing effect a quarter-circle instead of following the silhouette of the head. It just needs to be a bit cleaner.

![image](https://user-images.githubusercontent.com/106241650/227666738-7674f1e3-2f09-415e-aa43-2ef3429e10fc.png)
(You can copypaste this one into whatever spriting software you're using if you want to use it)

2023-04-04 22:20 UTC, sleepynecrons approved these changes
icon looks good now 👍

2023-04-06 11:56 UTC, harryob approved these changes
code looks fine

2023-04-06 12:07 UTC, merged