Fixes missing donator sprites, fixes missing icon states
cmss13-devs/cmss13 pull request #2757
Opened 2023-03-02 20:48 UTC by Ultimate-Fluff

# About the pull request
This pull request fixes all of the missing icon states in #2755 except for the ```scarf_%SQUAD%``` icon state.

It also fixes a lint error with ```pdt_watch``` and removes the Death Commando Mask, which should have been removed long ago. 

# Explain why it's good for the game
Missing and broken donator items need fixing. They paid for the sprites, anyway.

# Changelog

:cl: Puckaboo2
code: pdt_watch will no longer make the linter angry.
code: Fixed some placeholder icon and item states triggering missing files
del: Death Commando Masks have been removed.
imageadd: JediJas can now use their white marine gloves.
fix: XXX's custom Cigar can now be flickered on and off.
fix: Lostmix can now use their Ghost Cigar.
fix: Ress can now use their armored sandals.
/:cl:

2023-03-06 22:04 UTC, Agameofscones approved these changes
donator sprites make me cringe. Sprite approved

2023-03-07 07:32 UTC, harryob requested changes

2023-03-07 07:32 UTC, harryob commented on code/game/objects/items/devices/personal_data_transmitter.dm
>  	icon_state = "pdt_watch"
remove the icon state definition here, in 

/obj/item/clothing/accessory/pdt_bracelet/Initialize()

change the [icon_state]

to [dummy_icon_state]

2023-03-08 00:03 UTC, harryob approved these changes

2023-03-08 00:03 UTC, merged