Combat Reporter
cmss13-devs/cmss13 pull request #2761
Opened 2023-03-03 18:13 UTC by morrowwolf

# About the pull request

This adds the role combat reporter. This role will be a primarily RP role. The role has an office just east of the memorial in the maintenance hallway. No nice spaces for silly civilians without connections.

For the time being they have the same restrictions as the CL:
They may deploy at will.
They report directly to the acting commander with regards to ML.
They are NOT to be fighting xenos or frontlining. They should be staying in safe areas or moving with escorts (making the area safe).

# Explain why it's good for the game

This is something that has been asked for quite a bit. I'm on the fence about it personally but was requested to get something running.

There is a good argument against "role bloat" which is generally misunderstood as "too many roles bad" which is not the case. Instead, role bloat involves creating extra roles that take away from the gameplay loop or takes away from other roles (specifically in this case the corporate liaison who is rather similar if they want to do a gimmick).

Anyways, we'll see how the testmerge goes, feedback, as well as other architect thoughts.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>
Tested a bit, we'll run into bugs I'm sure.
</details>

# Changelog

:cl: Morrow
add: Added the role Combat Reporter.
/:cl:

2023-03-03 18:26 UTC, BadAtThisGame302 commented on code/game/objects/items/devices/radio/headset.dm
> +	desc = "Used by the CL to convince people to sign NDAs. Channels are as follows: :v - marine command, :a - alpha squad, :b - bravo squad, :c - charlie squad, :d - delta squad, :n - engineering, :m -
Change up the description or something?

2023-03-03 19:53 UTC, RoboticVodka commented
As I'm aware this has been attempted multiple times one for an example(https://gitlab.com/cmdevs/colonial-warfare/-/merge_requests/2822) mainly denied because it was Civilian only and the proposed solution was to allow it to be both Civilian or Military with a toggle but never panned out. I'd also suggest you change the title of the job to Combat Correspondent, which is its real life equivalent 4341 https://en.wikipedia.org/wiki/List_of_United_States_Marine_Corps_MOS

2023-03-03 21:33 UTC, Nanu308 commented
> As I'm aware this has been attempted multiple times one for an example(https://gitlab.com/cmdevs/colonial-warfare/-/merge_requests/2822) mainly denied because it was Civilian only and the proposed solution was to allow it to be both Civilian or Military with a toggle but never panned out. I'd also suggest you change the title of the job to Combat Correspondent, which is its real life equivalent 4341 https://en.wikipedia.org/wiki/List_of_United_States_Marine_Corps_MOS

See this comment, same as prior issue.

2023-03-10 03:09 UTC, Mark9013100 commented
the press cap has no sprite when flipped

2023-03-12 03:13 UTC, Agameofscones requested changes
sprites check out fine (frans my beloved)

morrow my boy, integrate the office better. Don't stick it behind a maintenance door, remove that funny strip sitting in the middle of the way for reasons, and give the doors proper names.

2023-03-16 13:48 UTC, morrowwolf commented
Mapping good to review.

Working on code changes still.

2023-03-17 09:41 UTC, cm13-github commented
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
CM13 Live Instance

##### Revision
Origin: 6a2cf07b91be24fbcbc651e8a46a8ae6445dd924
Pull Request: e2d5f5d1bcdecf9f89bc650099d15ec1684dfa34
Server: 0f1dac4dcb22794ac0797cee8eb9c5b0b7c5e7f8

##### Comment

</details>

2023-03-17 14:37 UTC, cm13-github commented
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
CM13 Live Instance

##### Revision
Origin: a6615543269deafdf5ad1f04caa9db43ed653967
Pull Request: e2d5f5d1bcdecf9f89bc650099d15ec1684dfa34
Server: 566e2a7569e3c8fe4e83ec05f9b162d1c50e20d2

##### Comment

</details>

2023-03-17 17:56 UTC, cm13-github commented
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
CM13 Live Instance

##### Revision
Origin: a6615543269deafdf5ad1f04caa9db43ed653967
Pull Request: e2d5f5d1bcdecf9f89bc650099d15ec1684dfa34
Server: e03f29db11392a076bad2f02448b2f3a3ac49415

##### Comment

</details>

2023-03-17 18:14 UTC, cm13-github commented
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
CM13 Live Instance

##### Revision
Origin: a6615543269deafdf5ad1f04caa9db43ed653967
Pull Request: e2d5f5d1bcdecf9f89bc650099d15ec1684dfa34
Server: 542ea8b549aa5ebcdd25d522cabb8346d1e8d294

##### Comment

</details>

2023-03-17 20:26 UTC, cm13-github commented
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
CM13 Live Instance

##### Revision
Origin: a6615543269deafdf5ad1f04caa9db43ed653967
Pull Request: e2d5f5d1bcdecf9f89bc650099d15ec1684dfa34
Server: 8788b2e03f66def7fd5673bae9a940858fd43b6b

##### Comment

</details>

2023-03-17 22:02 UTC, cm13-github commented
#### Test Merge Removed

2023-03-17 23:58 UTC, cm13-github commented
#### Test Merge Deployed

<details><summary>Details</summary>

##### Server Instance
CM13 Live Instance

##### Revision
Origin: afc0a21cd466feb1aea83571d32fb955ff96ea5a
Pull Request: e2d5f5d1bcdecf9f89bc650099d15ec1684dfa34
Server: db68a422228a4ee3145ddefbd31174eac03b2d20

##### Comment

</details>

2023-03-18 00:38 UTC, cm13-github commented
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
CM13 Live Instance

##### Revision
Origin: 84c584f8a9e7f72c9dbf905625b4ef11866fe4ed
Pull Request: e2d5f5d1bcdecf9f89bc650099d15ec1684dfa34
Server: 3d3051ddf73fc40c1c69a3dcbb0a2ca63ce0d550

##### Comment

</details>

2023-03-18 02:03 UTC, cm13-github commented
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
CM13 Live Instance

##### Revision
Origin: f96439dea585696374f0f74eeaac0189748efd83
Pull Request: e2d5f5d1bcdecf9f89bc650099d15ec1684dfa34
Server: 409c13271a4f43dc98037fb6b72ac4c64fd2eab8

##### Comment

</details>

2023-03-18 12:13 UTC, cm13live commented
This pull request has been mentioned on **CM-SS13**. There might be relevant details there:

https://forum.cm-ss13.com/t/2761-combat-correspondent/811/1

2023-03-18 13:15 UTC, cm13-github commented
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
CM13 Live Instance

##### Revision
Origin: f96439dea585696374f0f74eeaac0189748efd83
Pull Request: e2d5f5d1bcdecf9f89bc650099d15ec1684dfa34
Server: 31dd7bac120691339519407fbaebb60be862f3c1

##### Comment

</details>

2023-03-18 13:46 UTC, cm13-github commented
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
CM13 Live Instance

##### Revision
Origin: f96439dea585696374f0f74eeaac0189748efd83
Pull Request: e2d5f5d1bcdecf9f89bc650099d15ec1684dfa34
Server: c331f6e0c309e380bfe1c0b92001ed78b994ddcf

##### Comment

</details>

2023-03-18 14:05 UTC, cm13-github commented
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
CM13 Live Instance

##### Revision
Origin: c121ee6752a4af8076dbce9aa63651c5802b098a
Pull Request: e2d5f5d1bcdecf9f89bc650099d15ec1684dfa34
Server: b951f3dbe2c5b84502bedc2316789f1b3ebf9abd

##### Comment

</details>

2023-03-18 15:06 UTC, cm13-github commented
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
CM13 Live Instance

##### Revision
Origin: cb2716a6f3a07dfcd234d64d21a54d46e6955408
Pull Request: e2d5f5d1bcdecf9f89bc650099d15ec1684dfa34
Server: 30b545f159c2cd382c9a9d84d80535401d456608

##### Comment

</details>

2023-03-18 16:37 UTC, cm13-github commented
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
CM13 Live Instance

##### Revision
Origin: cb2716a6f3a07dfcd234d64d21a54d46e6955408
Pull Request: e2d5f5d1bcdecf9f89bc650099d15ec1684dfa34
Server: 2a28b4aba52c786f6b9a56978af6f6e1ec5d6867

##### Comment

</details>

2023-03-18 18:07 UTC, cm13-github commented
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
CM13 Live Instance

##### Revision
Origin: 42bde1e0ccfeca19fcfcdd996a07e7ad42e1d623
Pull Request: e2d5f5d1bcdecf9f89bc650099d15ec1684dfa34
Server: db03b5326e26106c8c582b792adbd765dad1dd0f

##### Comment

</details>

2023-03-18 22:08 UTC, cm13-github commented
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
CM13 Live Instance

##### Revision
Origin: 46e938a9a59b7cf7b7f80392f1de3a6c3ed1f015
Pull Request: e2d5f5d1bcdecf9f89bc650099d15ec1684dfa34
Server: 9ff946aa5d61af4999e86d21ab1ab48e99fa9c34

##### Comment

</details>

2023-03-18 23:10 UTC, cm13-github commented
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
CM13 Live Instance

##### Revision
Origin: d61ac6d90c1ba3437c53b309b80e628098ae2c16
Pull Request: e2d5f5d1bcdecf9f89bc650099d15ec1684dfa34
Server: 15a5e154b257e998812c319dc1801712110330b1

##### Comment

</details>

2023-03-19 01:11 UTC, cm13-github commented
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
CM13 Live Instance

##### Revision
Origin: d010b1ac6502581f9c54fd5d9ab1e04bd72d2534
Pull Request: e2d5f5d1bcdecf9f89bc650099d15ec1684dfa34
Server: 58891f7ef62fd1ba5f776bea224bcd2f4ed37b2a

##### Comment

</details>

2023-03-19 02:12 UTC, cm13-github commented
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
CM13 Live Instance

##### Revision
Origin: 50f3bad1a51f71bf2c5d29e8236f663d2ca65441
Pull Request: e2d5f5d1bcdecf9f89bc650099d15ec1684dfa34
Server: 965ce05a44359009a22aa3c23fdab9d57af3556f

##### Comment

</details>

2023-03-19 03:13 UTC, cm13-github commented
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
CM13 Live Instance

##### Revision
Origin: 24ced9126768119f480e6a8d6d91ac4ba8f25119
Pull Request: e2d5f5d1bcdecf9f89bc650099d15ec1684dfa34
Server: 1d8fe425cd8dc8ec96a88e84fa97dfb04c7f6c47

##### Comment

</details>

2023-03-19 07:43 UTC, cm13-github commented
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
CM13 Live Instance

##### Revision
Origin: 24ced9126768119f480e6a8d6d91ac4ba8f25119
Pull Request: e2d5f5d1bcdecf9f89bc650099d15ec1684dfa34
Server: 49d1b8c0ff4d15efdbd4fd0cbecd571fb02623ee

##### Comment

</details>

2023-03-19 08:14 UTC, cm13-github commented
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
CM13 Live Instance

##### Revision
Origin: a712c10248439405f450f07ca7c7acf69bb848d7
Pull Request: e2d5f5d1bcdecf9f89bc650099d15ec1684dfa34
Server: fff4ba6badffbafa4be46c98823ac0c89df423b6

##### Comment

</details>

2023-03-19 12:08 UTC, cm13-github commented
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
CM13 Live Instance

##### Revision
Origin: 58a51e1246fd072d444ab6bf09944be5f02b92d6
Pull Request: e2d5f5d1bcdecf9f89bc650099d15ec1684dfa34
Server: 34f1cd3bb642446c355fb98cd2cf7255899d2fed

##### Comment

</details>

2023-03-19 13:15 UTC, cm13-github commented
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
CM13 Live Instance

##### Revision
Origin: d817dc374787ac3dcce4d37d7b5aaa6bf45aba9b
Pull Request: e2d5f5d1bcdecf9f89bc650099d15ec1684dfa34
Server: eba44f3e93548d2616501d9486bc358c491fdf14

##### Comment

</details>

2023-03-19 13:28 UTC, cm13-github commented
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
CM13 Live Instance

##### Revision
Origin: 4708853a780fe8dc72848aaef4a440011ac4490f
Pull Request: df0d065030e1adfb6d52c6d78d96761a2d821d98
Server: 00a5ba229c15728cc98656fec14ae59ca56c401b

##### Comment

</details>

2023-03-19 14:14 UTC, cm13-github commented
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
CM13 Live Instance

##### Revision
Origin: 4708853a780fe8dc72848aaef4a440011ac4490f
Pull Request: df0d065030e1adfb6d52c6d78d96761a2d821d98
Server: 2553f9eae54e1e8fba39250f1fbaef3aad25d1af

##### Comment

</details>

2023-03-19 15:20 UTC, cm13-github commented
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
CM13 Live Instance

##### Revision
Origin: 4708853a780fe8dc72848aaef4a440011ac4490f
Pull Request: df0d065030e1adfb6d52c6d78d96761a2d821d98
Server: cdd6fe2764fa15eae4632c12aeee0e9d5ece932e

##### Comment

</details>

2023-03-19 16:45 UTC, cm13-github commented
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
CM13 Live Instance

##### Revision
Origin: 40e1c33dd3db0c09405cfebc5c063f0bab3afab7
Pull Request: df0d065030e1adfb6d52c6d78d96761a2d821d98
Server: 51152bdccda4fb695b4f0e8f74f0a6ea3b01a813

##### Comment

</details>

2023-03-19 17:22 UTC, cm13-github commented
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
CM13 Live Instance

##### Revision
Origin: 40e1c33dd3db0c09405cfebc5c063f0bab3afab7
Pull Request: df0d065030e1adfb6d52c6d78d96761a2d821d98
Server: cddc03115ac4de96c00a534facfcfa14c9ba6b07

##### Comment

</details>

2023-03-19 18:17 UTC, cm13-github commented
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
CM13 Live Instance

##### Revision
Origin: 0dea5e168383a7e3de233f2e66e92049f13e139c
Pull Request: df0d065030e1adfb6d52c6d78d96761a2d821d98
Server: 7574a7f61af3be4dbaec4e7bb5f15e7a5932b17f

##### Comment

</details>

2023-03-19 20:46 UTC, cm13-github commented
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
CM13 Live Instance

##### Revision
Origin: 0dea5e168383a7e3de233f2e66e92049f13e139c
Pull Request: a83a784250d92ddde1b2af3050828c539bd14041
Server: 6bb9e7d49ab844c93c1c645dfa57f2ce22e924b2

##### Comment

</details>

2023-03-19 20:51 UTC, cm13-github commented
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
CM13 Live Instance

##### Revision
Origin: 0dea5e168383a7e3de233f2e66e92049f13e139c
Pull Request: 019e2401ad930505435cc90cc06d995ba16fc252
Server: 2f52ba8deba310a1f8ff051abba991e66698653d

##### Comment

</details>

2023-03-19 22:04 UTC, harryob requested changes

2023-03-19 22:04 UTC, harryob commented on code/modules/gear_presets/uscm_ship.dm
> +	var/backItem = /obj/item/storage/backpack/satchel
snake case

2023-03-19 22:04 UTC, harryob commented on code/modules/gear_presets/uscm_ship.dm
> +	H.equip_to_slot_or_del(new backItem(H), WEAR_BACK)
snakecase

2023-03-19 22:04 UTC, harryob commented on code/modules/gear_presets/uscm_ship.dm
> +	var/backItem = /obj/item/storage/backpack/satchel
snakecase

2023-03-20 02:18 UTC, cm13-github commented
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
CM13 Live Instance

##### Revision
Origin: e683278fb1d596c51e80f921a1810cbad53324db
Pull Request: 019e2401ad930505435cc90cc06d995ba16fc252
Server: 81966dcdc7a3f248e4a56037c647d30c9fcd8500

##### Comment

</details>

2023-03-20 07:43 UTC, cm13-github commented
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
CM13 Live Instance

##### Revision
Origin: e683278fb1d596c51e80f921a1810cbad53324db
Pull Request: 019e2401ad930505435cc90cc06d995ba16fc252
Server: 7a8d2996afeaaa238369233ecd3ee0aa0b4ec146

##### Comment

</details>

2023-03-24 07:32 UTC, harryob requested changes

2023-03-24 07:32 UTC, harryob commented on code/modules/admin/topic/topic.dm
i'm so unhappy

2023-03-24 07:32 UTC, harryob commented on code/modules/paperwork/notepad.dm
> +			to_chat(usr, SPAN_NOTICE("You rip out \the [ripped_out_page.name] from \the [src]."))
```suggestion
			to_chat(usr, SPAN_NOTICE("You rip out [ripped_out_page] from [src]."))
```

2023-03-24 07:32 UTC, harryob commented on code/modules/paperwork/notepad.dm
> +	var/n_name = strip_html(input(usr, "What would you like to label the notepad?", "notepad Labelling", null)  as text)
use tgui_input_text and get rid of the as text and stuff

2023-03-24 07:32 UTC, harryob commented on code/modules/paperwork/notepad.dm
> +	if((loc == usr && usr.stat == 0))
stat has defines

2023-03-24 07:32 UTC, harryob commented on code/modules/admin/topic/topic.dm
> +		announce_fax( ,msg_ghost)
named arguments

2023-03-24 07:32 UTC, harryob commented on code/game/jobs/job/civilians/other/reporter.dm
> +	var/military = FALSE
```suggestion
	/// If this job is a military variant of the reporter role
	var/military = FALSE
```
or something to that effect

2023-03-24 07:32 UTC, harryob commented on code/game/jobs/job/civilians/other/reporter.dm
> +	if(option != job_options[1])
hard coding based on the position in the list isn't ideal, if option == CIVILIAN_VARIANT would be fine (or associating the list of job options with gear presets or w/e)

2023-03-24 07:32 UTC, harryob commented on code/game/jobs/job/job.dm
> +	return
```suggestion
/// Intended to be overwritten to handle when a job has variants that can be selected.
/datum/job/proc/handle_job_options(option)
	return
```

2023-03-27 21:21 UTC, merged