Tradeoff Chems
cmss13-devs/cmss13 pull request #2794
Opened 2023-03-08 13:41 UTC by insertnamehere123

# About the pull request

Adds a trio of chems that heals and restores blood more efficiently at the cost of doing damage:
Alinox heals burns much quicker at the cost of doing oxygen damage.
Yarinox heals brute at the cost of doing toxin damage.
Omniblood restores blood quickly but causes burn damage.

# Explain why it's good for the game

Gives medbay and medics more stuff to play around with.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

![786af562ec37d49c3a6ec54ceb60a7d0](https://user-images.githubusercontent.com/57860759/223727233-a77a749a-d7c5-424f-8853-b1362ac01ac4.png)

</details>

# Changelog

:cl:
add: Added Omniblood, Yarinox and Alinox along with their chem recipes 
balance: New chems means stuff needs to be rebalanced
/:cl:

2023-03-08 13:50 UTC, kiVts commented
wouldnt you be better off creating a new property for each chem? Because we already have transformative which does in summary the same

2023-03-08 13:52 UTC, insertnamehere123 commented
> 

Probably, but I wanted to make a draft and get feedback on this to maybe improve it

2023-03-08 16:33 UTC, morrowwolf requested changes
Downsides are going to be a good bit more.

If it's too easy to offset then it's just literally better and a buff and that's what it is right now.

2023-03-08 21:22 UTC, CABSHEP commented
Might want to add conflict with common medicines (like paracetamol and tramadol) that combat the downsides. What is the "tradeoff" of a Omniblood when you pop a bicardine pill on top easly? It would be just a straight marine buff.

2023-03-08 22:07 UTC, insertnamehere123 commented
> Might want to add conflict with common medicines (like paracetamol and tramadol) that combat the downsides. What is the "tradeoff" of a Omniblood when you pop a bicardine pill on top easly? It would be just a straight marine buff.



> Downsides are going to be a good bit more.
> 
> If it's too easy to offset then it's just literally better and a buff and that's what it is right now.

Actually, that gives me an idea, what if I made it conflict with common meds to make chemicals that cause organ damage or clone damage?

2023-03-08 22:18 UTC, insertnamehere123 commented
That gives me another thought, what if the conflicts were made a little less obvious? Like Alinox could mix with Bica to make a chem that causes rapid bloodloss? or Yarinox to mix with tramadol or oxy to make a chem that makes causes more eye damage than Imialzadone (the first chem in IA) can heal?

2023-03-08 22:19 UTC, insertnamehere123 commented
that way one mistake can cause a cascade of failures that guarantees the patient would need to return shipside

2023-03-09 03:25 UTC, insertnamehere123 commented on code/modules/reagents/chemistry_reagents/medical.dm
> +	properties = list(PROPERTY_HEMOGENIC = 6, PROPERTY_BIOCIDIC = 1)
True, but that would make for an interesting drawback to punish overuse of the chem

2023-03-09 06:09 UTC, closed without merging

2023-03-09 06:11 UTC, insertnamehere123 commented
The more I think about it, the more it just seems like scope creep so I guess I'll just close it until I come up with something better