Adds two new traits: Air Sickness and Lactose Intolerance
cmss13-devs/cmss13 pull request #2795
Opened 2023-03-08 23:45 UTC by carlarctg

# About the pull request

Adds two new traits: Air Sickness and Lactose Intolerance.

Air Sickness will induce nausea when you're on a ship and it either moves or some other heavy impact happens.

Lactose Intolerance will cause milk and cheese (dairy) products to give you an increasingly bad set of effects. Note: There's a lot of diary products in places you might not even notice, including MREs...

Adds a new variable to reagents, current_cycle, that tracks how many times the reagent has been processed.

Fixed a runtime on the bad leg trait.

Added milk or cheese to the dairy products that did not contain it.

I think something's up with this PR, I kept getting endless loop errors because of the lactose property for some reason so please TM before merging.

# Explain why it's good for the game

> Adds two new traits: Air Sickness and Lactose Intolerance.

> Air Sickness will induce nausea when you're on a ship and it either moves or some other heavy impact happens.

People get sick sometimes when in air. POs cannot get this trait and neither can DCCs, but other marines can because, well, once the nausea passes they're still combat effective. This will add a little noticeable flavor to your character.

> Lactose Intolerance will cause milk and cheese (dairy) products to give you an increasingly bad set of effects. Note: There's a lot of diary products in places you might not even notice, including MREs...

None of these effects are deadly. Vomit, eye blurriness are as bad as they get. Realizing that you accidentally ate a honey flan or cheese spread from an MRE and then getting woozy with people noticing could be funny, same as some malicious person serving you 'lactose free' food.

> Adds a new variable to reagents, current_cycle, that tracks how many times the reagent has been processed.

Needed for over-time effects.

> Fixed a runtime on the bad leg trait.

It was annoying me!

>  Added milk or cheese to the dairy products that did not contain it.

Necessary consistency.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:

add: Adds two new traits: Air Sickness and Lactose Intolerance.
add: Air Sickness will induce nausea when you're on a ship and it either moves or some other heavy impact happens.
add: Lactose Intolerance will cause milk and cheese (dairy) products to give you an increasingly bad set of effects. Note: There's a lot of diary products in places you might not even notice, including MREs...
code: Adds a new variable to reagents, current_cycle, that tracks how many times the reagent has been processed.
fix: Fixed a runtime on the bad leg trait.
code: Added milk or cheese to the dairy products that did not contain it.
/:cl:

2023-03-09 06:00 UTC, carlarctg commented on code/game/objects/items/reagent_containers/food/snacks.dm
>  	reagents.add_reagent("sugar", 2)
```suggestion
	reagents.add_reagent("nutriment", 2)
```

2023-03-13 09:56 UTC, morrowwolf requested changes
Ahem, 1 point per trait.

2023-03-14 03:41 UTC, morrowwolf reviewed
Waiting for #2756 to be merged and then will get to this as it causes ship shakes. Remind me after.

2023-03-15 16:58 UTC, harryob requested changes
the thing above

2023-03-18 19:59 UTC, harryob approved these changes
looks fine but

2023-03-18 19:59 UTC, harryob commented on code/modules/shuttles/shuttle.dm
> -					to_chat(M, SPAN_WARNING("The floor lurches beneath you!"))
?

2023-03-21 12:18 UTC, Watermelon914 requested changes

2023-04-17 00:26 UTC, closed without merging