Ghosts can look at a paper bundle's current page
cmss13-devs/cmss13 pull request #280
Opened 2022-05-12 20:26 UTC by harryob

## About The Pull Request

Small QoL fix picked up from #ideas_guys, just shows ghosts the current page in a paper stack.

## Why It's Good For The Game

Ghosts wanna see what page people are looking at in a bundle

## Changelog

:cl:
qol: Observers can now look at the current page of a paper bundle.
/:cl:

2022-05-12 20:31 UTC, harryob commented
man, forgot i didn't build this uncommitted code from a few days back. one mo

2022-05-17 07:13 UTC, stanalbatross requested changes

2022-05-17 07:13 UTC, stanalbatross commented on code/modules/paperwork/paper_bundle.dm
> +	if(!(ishuman(user) || istype(user, /mob/dead/observer)))
```suggestion
	if(!(ishuman(user) || isobserver(user)))
```

2022-05-17 07:13 UTC, stanalbatross commented on code/modules/paperwork/paper_bundle.dm
> +	if(in_range(user, src) || istype(user, /mob/dead/observer))
```suggestion
	if(in_range(user, src) || isobserver(user))
```

2022-05-17 07:13 UTC, stanalbatross commented on code/modules/paperwork/paper_bundle.dm
> +	else if(istype(usr, /mob/dead/observer))
```suggestion
	else if(isobserver(usr))
```

2022-05-19 22:00 UTC, stanalbatross approved these changes

2022-05-19 22:01 UTC, merged