Adds Most Missing Clothing Icon States
cmss13-devs/cmss13 pull request #2813
Opened 2023-03-10 20:37 UTC by Ultimate-Fluff

# About the pull request

# Explain why it's good for the game

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
fix:
tweak:
code:
/:cl:

2023-03-12 01:26 UTC, Agameofscones approved these changes
this makes the linter happy. Sprites approved

2023-03-18 23:26 UTC, harryob requested changes

2023-03-18 23:26 UTC, harryob commented on code/modules/cm_tech/implements/armor.dm
> +	base_icon_state = "regular2"
```suggestion
```

2023-03-18 23:26 UTC, harryob commented on code/modules/cm_tech/implements/armor.dm
>  	var/base_icon_state
```suggestion
	var/base_icon_state = "regular2"
```

2023-03-18 23:37 UTC, Agameofscones commented
Of note, ceramic plates aren't supposed to be wearable. They're only supposed to be able to slot onto armor as an accessory

2023-03-21 19:20 UTC, merged