Hivemind available first 5 minutes of round
cmss13-devs/cmss13 pull request #2820
Opened 2023-03-11 18:41 UTC by morrowwolf

# About the pull request

Makes Hivemind available for the first 5 minutes of round even without a queen.

# Explain why it's good for the game

When a queen doesn't spawn at roundstart it is not enjoyable not being able to coordinate with fellow larva on who is taking over. This should have zero impact on overall balance.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>
yuh

</details>

# Changelog

:cl: Morrow
qol: Made Hivemind available for the first 5 minutes of round even without a queen.
/:cl:

2023-03-11 18:43 UTC, harryob requested changes

2023-03-11 18:43 UTC, harryob commented on code/modules/mob/living/carbon/xenomorph/say.dm
> +	if(!hive.living_xeno_queen && !SSticker?.mode?.hardcore && !hive.allow_no_queen_actions && world.time > SSticker.round_start_time + SSticker.mode.round_time_evolution_ovipositor)
ROUND_TIME macro

2023-03-11 19:49 UTC, morrowwolf commented on code/modules/mob/living/carbon/xenomorph/say.dm
> +	if(!hive.living_xeno_queen && !SSticker?.mode?.hardcore && !hive.allow_no_queen_actions && world.time > SSticker.round_start_time + SSticker.mode.round_time_evolution_ovipositor)
MAAAAAAAACROOOOOOOOOOOOOOOS

2023-03-11 22:53 UTC, Ultimate-Fluff commented
As a beno main, I approve.

2023-03-12 08:36 UTC, harryob approved these changes

2023-03-12 22:35 UTC, merged

2023-03-13 02:34 UTC, Drakyry commented
You should make it 10, or even 20 minutes. I have had rounds where the queen wouldn't appear until ~12:13 or so. I've only had 1 round where the queen died in the first 20 minutes, and that was before surv rushes on the hive were outlawed