Allows Predators to pick between weapon variations.
cmss13-devs/cmss13 pull request #2822
Opened 2023-03-12 05:13 UTC by carlarctg

# About the pull request

Allows Predators to pick between weapon variations, specifically the two-blades-on-one-end ripper scythe, and the long polearm-like glaive.

Sprited inhands for both scythes.

Added a cool spin to double hitting with the scythe.

![image](https://user-images.githubusercontent.com/53100513/224525669-c5776fff-0299-465c-aef7-931e3ec106e7.png)

# Explain why it's good for the game

Cool = Good

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
add: Allows Predators to pick between weapon variations, specifically the two-blades-on-one-end ripper scythe, and the long polearm-like glaive.
add: Sprited inhands for both scythes.
add: Added a cool spin to double hitting with the scythe.
/:cl:

2023-03-13 14:18 UTC, harryob approved these changes

2023-03-23 23:04 UTC, sleepynecrons requested changes
Some inconsistencies between the pre-existing object sprites and the inhands you made. Also for the double scythe in items_righthand, the north sprite is in the wrong hand.

![MpvyWnI](https://user-images.githubusercontent.com/106241650/227381676-1e11e698-5b59-4b7d-b07d-492f2e75643f.png)

The dual scythe inhand has a grip instead of the metal centerpiece, and the double scythe inhand has a new grip. (Which I think is neat but the object sprite should have one). If you want to keep the grip for the double scythe, the lighter shade should be outlined in the darkest shade like above.

![VjBbikG](https://user-images.githubusercontent.com/106241650/227381835-e10e9268-146a-4325-9627-1f5c67bd78a9.png)

Shading at the end of the double scythe's shaft should match with the object sprite.

![B8lzhwK](https://user-images.githubusercontent.com/106241650/227383030-636fa207-47f9-426d-bd5e-2345aa48fc46.png)

All of the south sprites need pixels where the scythe would pass behind the legs.

2023-04-02 02:43 UTC, sleepynecrons approved these changes
sprites are alright now 🙂👍

2023-04-05 14:41 UTC, morrowwolf approved these changes
Code looks fine, spin is kind of jarring but not awful. Will remove if people complain though.

2023-04-05 14:52 UTC, merged