Vehicle Elevator
cmss13-devs/cmss13 pull request #2824
Opened 2023-03-12 08:54 UTC by realforest2001

# About the pull request
Makes the elevator start raised. Fewer meme suicides.

# Explain why it's good for the game
Suicide bad.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
add: Vehicle Elevator now starts raised.
/:cl:

2023-03-12 08:57 UTC, harryob approved these changes

2023-03-13 15:57 UTC, mullenpaul approved these changes
I would prefer if the Almayer stationary dock and the admin level stationary docks are both subclasses. It would require a map change and isn't strictly necessary but it would be a cleaner solution.

2023-03-13 19:17 UTC, mullenpaul approved these changes
Code wise, perfect. This is the standard that I believe docking ports should be done.

2023-03-15 18:07 UTC, harryob requested changes

2023-03-15 18:07 UTC, harryob commented on code/modules/shuttle/vehicle_elevator.dm
> +	name = "Alamyer Vehicle Elevator Dock"
alamyer

2023-03-15 20:23 UTC, realforest2001 commented on code/modules/shuttle/vehicle_elevator.dm
> +	name = "Alamyer Vehicle Elevator Dock"
```suggestion
	name = "Almayer Vehicle Elevator Dock"
```

2023-03-16 14:28 UTC, merged