Unintended Feature Fix: Stops alacrit stacking
cmss13-devs/cmss13 pull request #2829
Opened 2023-03-12 19:44 UTC by Moonshanks

# About the pull request

Moves the check for Alacrit consumption so that the fruit no longer takes effect if you have already consumed alacrit.

The fruit is still consumed, and it still takes the full time to consume.

Tested this and it works.

# Explain why it's good for the game

Stops mach 12 drones.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

https://youtu.be/Yge37UMPYAU

</details>

# Changelog

:cl:
fix: The effects from the alacrit fruit no longer stack.
/:cl:

2023-03-12 19:46 UTC, Moonshanks commented
@BeagleGaming1 is the most patient saint known to man. His service should be rewarded with a good job sticker.

2023-03-12 19:49 UTC, Moonshanks commented on code/modules/cm_aliens/structures/fruit.dm
> +
Your mother.

2023-03-12 20:09 UTC, Moonshanks commented on code/modules/cm_aliens/structures/fruit.dm
>  		to_chat(xeno, SPAN_XENOWARNING("You're already under the effects of this fruit, go out and kill!"))
done... but I think I made one extra recipient. Let me go ahead and fix that.

2023-03-14 06:48 UTC, morrowwolf requested changes
As we discussed on discord: change it to stop all stacking of individual types of fruits please.

2023-03-14 10:54 UTC, Moonshanks commented
> As we discussed on discord: change it to stop all stacking of individual types of fruits please.

Yes boss

2023-03-15 21:46 UTC, Moonshanks commented
Fixed, tested, working on all fruits.

2023-03-21 12:21 UTC, Watermelon914 requested changes

2023-03-21 12:21 UTC, Watermelon914 commented on code/modules/cm_aliens/structures/fruit.dm
> +	can_consume_check(recipient)
This isn't exactly going to do anything, you need to return a boolean value and do an if check.
Then early return if the check does not pass.

Also, the name of your function is a bit verbose, `can_consume` is a good enough name.

2023-03-21 12:21 UTC, Watermelon914 commented on code/modules/cm_aliens/structures/fruit.dm
> +	can_consume_check(recipient)
Need to do this to the rest of them as well.

2023-04-06 00:25 UTC, closed without merging