Adds the M46 'Bolo' Tactical Dagger
cmss13-devs/cmss13 pull request #2834
Opened 2023-03-13 23:26 UTC by carlarctg

# About the pull request

Adds the M46 'Bolo' Tactical Dagger. The M46 is a medium-sized middle-ground between a bayonet and a machete, dealing intermediate damage with a faster attack speed than either. Intended for marines who cannot fit a machete with their kit but still want a resin-clearing weapon. Can be found in Req or in equipment vendors.

The Bolo can be attached to USCM weapons, but its large size and weight noticeably worsen handling and stability.

Reworks how Melee on resin structures is handled, see comment in the defines file, necessary to make sure the Bolo wasn't overpowered or underpowered. Of note, machetes now break resin doors in two hits, thick doors on three, and weak membranes in one hit.

Adds a variable for resin melee multiplier. Reduced sticky/fast resin and spikes health to 25 and gave them no melee multiplier.

# Explain why it's good for the game

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
imageadd: Adds the M46 'Bolo' Tactical Dagger. The M46 is a medium-sized middle-ground between a bayonet and a machete, dealing intermediate damage with a faster attack speed than either. Intended for marines who cannot fit a machete with their kit but still want a resin-clearing weapon. Can be found in Req or in equipment vendors.

add: The Bolo can be attached to USCM weapons, but its large size and weight noticeably worsen handling and stability.

balance: Reworks how Melee on resin structures is handled, see comment in the defines file, necessary to make sure the Bolo wasn't overpowered or underpowered. Of note, machetes now break resin doors in two hits, thick doors on three, and weak membranes in one hit.

code: Adds a variable for resin melee multiplier. Reduced sticky/fast resin and spikes health to 25 and gave them no melee multiplier.

/:cl:

2023-03-13 23:33 UTC, carlarctg commented on code/modules/clothing/clothing.dm
> +			if(istype(I, i) && I.w_class <= maximum_size)
wtf it copmpiled

2023-03-14 08:29 UTC, morrowwolf requested changes
I don't think this is necessary for standard USCM usage.

Maybe refit the sprite into a marsoc or other usage?

2023-03-14 18:31 UTC, Zonespace27 requested changes

2023-03-14 18:31 UTC, Zonespace27 commented on code/modules/cm_aliens/XenoStructures.dm
> +	var/melee_multiplier = RESIN_MELEE_DAMAGE_MULTIPLIER
code doc

2023-03-14 18:31 UTC, Zonespace27 commented on code/modules/projectiles/gun_attachables.dm
> +	..()
```suggestion
	. = ..()
```

2023-03-14 18:31 UTC, Zonespace27 commented on code/modules/projectiles/gun_attachables.dm
> +	desc_lore = "This bolo knife is not often seen on the field, and is mostly issued to troops in operations which would benefit from a machete to clear vegetation but due to their specialization canno
is "bolo" a proper noun?

2023-04-05 14:03 UTC, nauticall requested changes
imho the bolo knife looks WAY too similar to the preexisting bayonet that im not really comfortable with it as-is. try changing the color palette of it to be different (more blue, perhaps?) and also change the shape so it doesn't just look like an oversized knife. I get that you (or whoever sprited it) wanted to emulate a sort of "curve" but it doesn't look like that went far enough for it to be noticeable.

consider something like curving the _edge_ more, like this bolo:

![image](https://user-images.githubusercontent.com/55491249/230105008-23270f61-2c50-4e4f-8870-6b6e798a551e.png)

2023-04-20 00:25 UTC, closed without merging