Possible fix to evacuated personnel not ending the round
cmss13-devs/cmss13 pull request #2850
Opened 2023-03-16 01:21 UTC by morrowwolf

# About the pull request

Possible fix to evacuated personnel not ending the round.

# Explain why it's good for the game

Rounds not ending properly is bad.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>
I did not test this PR but I'm gonna TM it and see if it explodes.

</details>

# Changelog

:cl: Morrow
fix: Fix to evacuated personnel not ending the round
/:cl:

2023-03-16 07:37 UTC, morrowwolf commented
Seems to work correctly during TM.

2023-03-16 10:07 UTC, harryob requested changes

2023-03-16 10:07 UTC, harryob commented on code/game/gamemodes/cm_self_destruct.dm
> +	if(dest_status < NUKE_EXPLOSION_IN_PROGRESS && SSticker.mode && SSticker.mode.is_in_endgame)
```suggestion
	if(dest_status < NUKE_EXPLOSION_IN_PROGRESS && SSticker?.mode.is_in_endgame)
```

2023-03-17 09:12 UTC, merged

2023-03-17 09:41 UTC, cm13-github commented
#### Test Merge Removed