New Random Event: Cryopod Malfunction
cmss13-devs/cmss13 pull request #2852
Opened 2023-03-16 01:46 UTC by carlarctg

# About the pull request

Adds a new random event, Cryopod Malfunction.

This event will spawn a random pet or wild animal on a random hypersleep chamber on the Almayer.

Before the animal pops up, there will be a 5-second rumbling warning and animation.

# Explain why it's good for the game

More random events to spice up the round when they roll, without impacting gameplay negatively for anyone.

Is this LRP? No. The Almayer holding pets can be explained for a myriad of reasons, such as the marines sneaking a crab or dog into the Almayer last OP and Command taking the easy way out, putting it in cryo, and forgetting about it. The hijinks and RP that will happen from this will more than make up for any subjective slips in 'atmosphere', especially since there are no ethereal or unnatural possible animals from the selection.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
add: Adds a new random event, Cryopod Malfunction.
add: This event will spawn a random pet or wild animal on a random hypersleep chamber on the Almayer.
add: Before the animal pops up, there will be a 5-second rumbling warning and animation.
/:cl:

2023-03-16 10:04 UTC, harryob requested changes

2023-03-16 10:04 UTC, harryob commented on code/modules/events/cryopod_malfunction.dm
> +	new spawn_type(cryogenic_pod.loc)
get_turf

2023-03-17 00:29 UTC, carlarctg commented
> new pvt spawns into CM for the first time and gets greeted by getting beheaded by a hostile bear because le funny haha event? do we really want hostile NPC mobs to be attacking newly-spawned people (potentially pvt people) in CRYO of all places? wasn't there also a rule against lone xenos that snuck onto the ship attacking newspawns? isn't this the same thing but from NPCs?

Fixed!

2023-03-18 14:01 UTC, morrowwolf reviewed
Team thinks it's a bit too goofy. I think we should really be fueling random events with solid events before diluting it with stuff that's a bit sillier.

2023-03-18 14:01 UTC, closed without merging