Admin Yautja cloak var
cmss13-devs/cmss13 pull request #2856
Opened 2023-03-16 22:09 UTC by realforest2001

# About the pull request
Allows admins to change the effectiveness of Yautja cloaks. Also adds a variable to make the cloak provide true invisibility.

# Explain why it's good for the game
Allows admins to run more dynamic events with yautja, such as bad bloods or similar who's cloaks are degraded.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
add: Adds two variables to yautja cloaks for admin customisation. cloak_alpha and true_cloak, true cloak will make the invisibility 100% effective.
/:cl:

2023-03-16 22:18 UTC, Zonespace27 requested changes

2023-03-16 22:18 UTC, Zonespace27 commented on code/modules/cm_preds/yaut_bracers.dm
> +	var/true_cloak = FALSE
codedoc

2023-03-17 20:26 UTC, cm13-github commented
#### Test Merge Deployed

<details><summary>Details</summary>

##### Server Instance
CM13 Live Instance

##### Revision
Origin: a6615543269deafdf5ad1f04caa9db43ed653967
Pull Request: 92f32533eeaad9d2b81536345e6bb08484fce562
Server: 8788b2e03f66def7fd5673bae9a940858fd43b6b

##### Comment
lets see who's metacomming
</details>

2023-03-17 22:02 UTC, cm13-github commented
#### Test Merge Removed

2023-03-17 22:37 UTC, cm13-github commented
#### Test Merge Deployed

<details><summary>Details</summary>

##### Server Instance
CM13 Live Instance

##### Revision
Origin: afc0a21cd466feb1aea83571d32fb955ff96ea5a
Pull Request: 92f32533eeaad9d2b81536345e6bb08484fce562
Server: b5823ea42ad5d1ab44835291a9dd808891c69370

##### Comment

</details>

2023-03-17 23:58 UTC, cm13-github commented
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
CM13 Live Instance

##### Revision
Origin: afc0a21cd466feb1aea83571d32fb955ff96ea5a
Pull Request: 92f32533eeaad9d2b81536345e6bb08484fce562
Server: db68a422228a4ee3145ddefbd31174eac03b2d20

##### Comment

</details>

2023-03-18 00:38 UTC, cm13-github commented
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
CM13 Live Instance

##### Revision
Origin: 84c584f8a9e7f72c9dbf905625b4ef11866fe4ed
Pull Request: 92f32533eeaad9d2b81536345e6bb08484fce562
Server: 3d3051ddf73fc40c1c69a3dcbb0a2ca63ce0d550

##### Comment

</details>

2023-03-18 02:03 UTC, cm13-github commented
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
CM13 Live Instance

##### Revision
Origin: f96439dea585696374f0f74eeaac0189748efd83
Pull Request: 92f32533eeaad9d2b81536345e6bb08484fce562
Server: 409c13271a4f43dc98037fb6b72ac4c64fd2eab8

##### Comment

</details>

2023-03-18 13:15 UTC, cm13-github commented
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
CM13 Live Instance

##### Revision
Origin: f96439dea585696374f0f74eeaac0189748efd83
Pull Request: 92f32533eeaad9d2b81536345e6bb08484fce562
Server: 31dd7bac120691339519407fbaebb60be862f3c1

##### Comment

</details>

2023-03-18 13:46 UTC, cm13-github commented
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
CM13 Live Instance

##### Revision
Origin: f96439dea585696374f0f74eeaac0189748efd83
Pull Request: 92f32533eeaad9d2b81536345e6bb08484fce562
Server: c331f6e0c309e380bfe1c0b92001ed78b994ddcf

##### Comment

</details>

2023-03-18 14:05 UTC, cm13-github commented
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
CM13 Live Instance

##### Revision
Origin: c121ee6752a4af8076dbce9aa63651c5802b098a
Pull Request: 92f32533eeaad9d2b81536345e6bb08484fce562
Server: b951f3dbe2c5b84502bedc2316789f1b3ebf9abd

##### Comment

</details>

2023-03-18 15:06 UTC, cm13-github commented
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
CM13 Live Instance

##### Revision
Origin: cb2716a6f3a07dfcd234d64d21a54d46e6955408
Pull Request: 92f32533eeaad9d2b81536345e6bb08484fce562
Server: 30b545f159c2cd382c9a9d84d80535401d456608

##### Comment

</details>

2023-03-18 16:37 UTC, cm13-github commented
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
CM13 Live Instance

##### Revision
Origin: cb2716a6f3a07dfcd234d64d21a54d46e6955408
Pull Request: 92f32533eeaad9d2b81536345e6bb08484fce562
Server: 2a28b4aba52c786f6b9a56978af6f6e1ec5d6867

##### Comment

</details>

2023-03-18 18:07 UTC, cm13-github commented
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
CM13 Live Instance

##### Revision
Origin: 42bde1e0ccfeca19fcfcdd996a07e7ad42e1d623
Pull Request: 92f32533eeaad9d2b81536345e6bb08484fce562
Server: db03b5326e26106c8c582b792adbd765dad1dd0f

##### Comment

</details>

2023-03-18 22:08 UTC, cm13-github commented
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
CM13 Live Instance

##### Revision
Origin: 46e938a9a59b7cf7b7f80392f1de3a6c3ed1f015
Pull Request: 92f32533eeaad9d2b81536345e6bb08484fce562
Server: 9ff946aa5d61af4999e86d21ab1ab48e99fa9c34

##### Comment

</details>

2023-03-18 23:10 UTC, cm13-github commented
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
CM13 Live Instance

##### Revision
Origin: d61ac6d90c1ba3437c53b309b80e628098ae2c16
Pull Request: 92f32533eeaad9d2b81536345e6bb08484fce562
Server: 15a5e154b257e998812c319dc1801712110330b1

##### Comment

</details>

2023-03-19 01:11 UTC, cm13-github commented
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
CM13 Live Instance

##### Revision
Origin: d010b1ac6502581f9c54fd5d9ab1e04bd72d2534
Pull Request: 92f32533eeaad9d2b81536345e6bb08484fce562
Server: 58891f7ef62fd1ba5f776bea224bcd2f4ed37b2a

##### Comment

</details>

2023-03-19 02:12 UTC, cm13-github commented
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
CM13 Live Instance

##### Revision
Origin: 50f3bad1a51f71bf2c5d29e8236f663d2ca65441
Pull Request: 92f32533eeaad9d2b81536345e6bb08484fce562
Server: 965ce05a44359009a22aa3c23fdab9d57af3556f

##### Comment

</details>

2023-03-19 03:13 UTC, cm13-github commented
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
CM13 Live Instance

##### Revision
Origin: 24ced9126768119f480e6a8d6d91ac4ba8f25119
Pull Request: 92f32533eeaad9d2b81536345e6bb08484fce562
Server: 1d8fe425cd8dc8ec96a88e84fa97dfb04c7f6c47

##### Comment

</details>

2023-03-19 07:43 UTC, cm13-github commented
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
CM13 Live Instance

##### Revision
Origin: 24ced9126768119f480e6a8d6d91ac4ba8f25119
Pull Request: 92f32533eeaad9d2b81536345e6bb08484fce562
Server: 49d1b8c0ff4d15efdbd4fd0cbecd571fb02623ee

##### Comment

</details>

2023-03-19 08:14 UTC, cm13-github commented
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
CM13 Live Instance

##### Revision
Origin: a712c10248439405f450f07ca7c7acf69bb848d7
Pull Request: 92f32533eeaad9d2b81536345e6bb08484fce562
Server: fff4ba6badffbafa4be46c98823ac0c89df423b6

##### Comment

</details>

2023-03-19 12:06 UTC, merged

2023-03-19 12:08 UTC, cm13-github commented
#### Test Merge Removed