Fixes bad leg and ATM money laundering glitch
cmss13-devs/cmss13 pull request #2858
Opened 2023-03-17 01:58 UTC by carlarctg

# About the pull request

Laundering money through the ATM is now only 33% as effective.

Increased cane pacing sound a little.

Fixed not actually ever being harmed from walking around with a bad leg and no cane.

# Explain why it's good for the game

> Laundering money through the ATM is now only 33% as effective.

I love that people found this out but it was too strong, so now it's less effective, but still usable.

> Increased cane pacing sound a little.

It was too tiny

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:

fix: Laundering money through the ATM is now only 33% as effective.
fix: Increased cane pacing sound a little.
fix: Fixed not actually ever being harmed from walking around with a bad leg and no cane.
/:cl:

2023-03-17 09:14 UTC, harryob requested changes
beag's right bro!!

2023-03-21 12:27 UTC, Watermelon914 requested changes

2023-03-21 12:27 UTC, Watermelon914 commented on code/modules/economy/ATM.dm
> +			if(I:counterfeit)
Can you remove the `:` usage entirely? Do proper typecasting and then just use the `.` access operator.

2023-03-23 03:24 UTC, carlarctg commented on code/game/objects/items/misc.dm
> +/obj/item/weapon/melee/pole/fancy_cane/this_is_a_knife // https://www.youtube.com/watch?v=TSGIRFzmyyk
lrp

2023-03-23 07:44 UTC, harryob approved these changes

2023-03-23 07:59 UTC, merged