Allows Predators to make and wear bones
cmss13-devs/cmss13 pull request #2867
Opened 2023-03-17 21:02 UTC by BeagleGaming1

# About the pull request

This lets predators take limbs, use their knife on it, then turn those into bones that they can attach to their armor.
Also moves a bit of other pred stuff to its place (why was the globe with the turfs?)

Sprites by sleepynecrons
# Explain why it's good for the game

This gives predators another use for limbs they get.

and someone asked me to make it
# Changelog

:cl:
add: Allows Yautja to make bones from limbs and wear them
/:cl:

2023-03-17 21:08 UTC, carlarctg commented on code/modules/cm_preds/yaut_items.dm
> +	desc = "An astonishingly fine, hand-tailored piece of exotic cloth."
Give this a hint that it's used for bones, maybe as a pred only text in get_examine_tect

2023-03-17 21:08 UTC, carlarctg commented on code/modules/cm_preds/yaut_items.dm
> +	name = "leg bones"
either name them all bone or all bones

2023-03-17 21:08 UTC, carlarctg commented on code/modules/cm_preds/yaut_items.dm
> +	name = "rib"
ribcage

also the skull should still have the spine like in avp

2023-03-18 13:02 UTC, harryob requested changes

2023-03-18 13:02 UTC, harryob commented on code/modules/cm_preds/yaut_weapons.dm
> +	if(istype(potential_limb, /obj/item/limb)) //Not checking for torso and groin, if you somehow get those, good on you
early return if it's not of type

2023-03-18 13:02 UTC, harryob commented on code/modules/cm_preds/yaut_items.dm
> +	if(istype(potential_limb, /obj/item/clothing/accessory/limb/skeleton)) //Not checking for torso and groin, if you somehow get those, good on you
early return

2023-03-18 17:34 UTC, harryob requested changes

2023-03-18 17:34 UTC, harryob commented on code/modules/cm_preds/yaut_machines.dm
> +	var/base_state = "vat"
does this ever change? if not use initial()

2023-03-18 23:08 UTC, harryob approved these changes
sprites

2023-03-28 13:31 UTC, nauticall requested changes
sprites are all fine 'cept for the towel, that looks kinda blocky. would recommend using something like this if you would like, or you can make your own variation of it, up to you.......

that's the only thing this PR needs before the ole' rubber stamp (on the sprite side at least)

![image](https://user-images.githubusercontent.com/55491249/228253189-4535cb88-0e6a-42fe-a642-ade69bf3fcd4.png)

2023-04-12 16:20 UTC, nauticall commented
there is that pred gear dmi conflict though, might wanna look at that

2023-04-18 12:08 UTC, harryob approved these changes

2023-04-18 12:19 UTC, merged