WIP
cmss13-devs/cmss13 pull request #2868
Opened 2023-03-17 23:35 UTC by LynxSolstice

# About the pull request

This PR randomizes the local operation time.

# Explain why it's good for the game

I thought it was silly the rounds always start at say, noon or marines would always drop at the same times on different planets without accounting for local time, every planet was always the same time! However with this PR that changes, now you can have an operation briefing at 03:42, or maybe 02:28. It adds some minor immersion for me personally.

# Testing Photographs and Procedure

Functions properly when compared to the master branch (both start at 23:00 for round time? Not sure why but doesn't seem to be an issue.

</details>

# Changelog

:cl:LynxSolstice, Harryob
code: Changed the worldtime2text offset to be between 10 minutes and 4 hours.
/:cl:

2023-03-18 01:20 UTC, morrowwolf reviewed
I'm fine with this just make sure it's fully randomized for around the clock.

2023-03-18 06:01 UTC, LynxSolstice commented
> I'm fine with this just make sure it's fully randomized for around the clock.

Like 1 second to 24 hours?

2023-03-18 14:06 UTC, morrowwolf commented
> > I'm fine with this just make sure it's fully randomized for around the clock.
> 
> Like 1 second to 24 hours?

Correct

2023-03-19 02:46 UTC, Zonespace27 requested changes
Morrow's bit + a nit

2023-03-19 02:46 UTC, Zonespace27 commented on code/_globalvars/misc.dm
> +/proc/setup_offset()
code doc

2023-03-19 02:50 UTC, LynxSolstice commented on code/_globalvars/misc.dm
> +/proc/setup_offset()
![image](https://user-images.githubusercontent.com/112824777/226150968-c51c0f6d-a2f5-4f30-8c5d-3ad7b6eb2084.png)

2023-03-19 02:53 UTC, LynxSolstice commented on code/_globalvars/misc.dm
> +/proc/setup_offset()
Doc'd!

2023-03-19 02:53 UTC, Zonespace27 approved these changes

2023-03-19 03:02 UTC, merged