round traits framework + a few placeholders
cmss13-devs/cmss13 pull request #2876
Opened 2023-03-18 15:50 UTC by harryob

this allows for us to have randomised traits that will impact a whole round for a bit of variety. wouldn't that be nice?

:cl:
add: added the framework for random traits impacting the whole round
add: added a number of traits, including flu season, faulty piping, book balancing, illicit dealings, faulty cryogenics, economic boom/slump, temperature change and mismatched squads
/:cl:

these should (if i've done the weighting right) not appear enough to be annoying

also

# important

i would like to add more, especially for xenos and i'll be going through some ideas i curated prior to merge

2023-03-18 16:27 UTC, carlarctg commented on code/datums/round_traits/neutral.dm
> +	human_report_message = "ARES was flagging up some errors for a minor subsystem in the cryogenics pods. Should all be fine."
```suggestion
	human_report_message = "ARES was flagging up some errors for a minor subsystem in the cryogenics pods. Should be all fine."
```

2023-03-22 16:23 UTC, morrowwolf requested changes
Seemingly non-functional during tests on live.

2023-08-24 08:06 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2023-08-24 15:30 UTC, Zonespace27 commented on code/datums/round_traits/neutral.dm
> +	blacklist = list(/datum/round_trait/economic_boom)
This should be slump

2023-08-24 15:30 UTC, Zonespace27 commented on code/game/machinery/vending/vendor_types/squad_prep/squad_prep.dm
> +	if(HAS_TRAIT(SSround, TRAIT_ROUND_STANDARD_ISSUE))
Is this used?

2023-08-28 19:15 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2023-09-11 05:58 UTC, closed without merging