Adds in hoods + OWLF placeholder items
cmss13-devs/cmss13 pull request #2877
Opened 2023-03-18 19:05 UTC by NewyearnewmeUwu

# About the pull request
This adds in a new system for 'hoods' or integrated helmets akin to normal SS13's voidsuits. None of this has stats apart from the uniform, and this is meant to be a foundation for properly implementing OWLF in the future, as a possible replacement pred hunting ERT for DD.

# Explain why it's good for the game
It's cool, the code works, and this is soulful.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
add: Added OWLF placeholder items, none of which are properly statted yet.
code: CM's code now has support for integrated hoods for uniforms.
/:cl:

2023-03-18 19:50 UTC, harryob requested changes

2023-03-18 19:50 UTC, harryob commented on code/modules/clothing/under/under.dm
> +	if(flags_jumpsuit & UNIFORM_HOOD_EXISTS)
early return

2023-03-18 19:50 UTC, harryob commented on code/modules/clothing/under/under.dm
> +		if(!user.head || istype(user.head, hood_state))
early return

2023-03-18 19:50 UTC, harryob commented on code/modules/clothing/under/under.dm
> +			flags_jumpsuit ^= UNIFORM_HOOD_ACTIVE
remind me to teach you how to use traits

2023-03-18 19:50 UTC, harryob commented on code/modules/clothing/under/under.dm
> +			if(flags_jumpsuit & UNIFORM_HOOD_ACTIVE)
early return

2023-03-18 21:27 UTC, Agameofscones commented
oh god oh fuck I should probably finish the OWLF gun sprites soon

2023-03-18 22:20 UTC, harryob requested changes

2023-03-18 22:20 UTC, harryob commented on code/modules/clothing/under/under.dm
> +		to_chat(user, SPAN_WARNING("You can't wear a hood while also wearing the [user.head.name]!"))
```suggestion
		to_chat(user, SPAN_WARNING("You can't wear a hood while also wearing the [user.head]!"))
```

2023-03-19 13:29 UTC, harryob requested changes

2023-03-19 13:29 UTC, harryob commented on code/modules/clothing/under/under.dm
> +	///I coded this. It's weird, it's funky, but I can help.
this is the purpose of git blame

2023-03-26 09:50 UTC, harryob approved these changes
code

2023-03-31 04:01 UTC, nauticall approved these changes
sprites look good to me! approved

2023-03-31 09:28 UTC, merged

2023-04-13 15:22 UTC, cm13live commented
This pull request has been mentioned on **CM-SS13**. Please provide feedback here:

https://forum.cm-ss13.com/t/dutch-ert-suggestion/1403/3