Repaths all /obj/item/weapon/melee/ to /obj/item/weapon/
cmss13-devs/cmss13 pull request #2885
Opened 2023-03-19 06:40 UTC by BeagleGaming1

# About the pull request

There was no /obj/item/weapon/melee item, ctrl-clicking would just redirect to chloroform, this changes nothing

Wow writing this PR is lagging out my PC
# Explain why it's good for the game

It will do nothing but cause merge conflicts
The /melee segment doesn't change anything about the code, it is just there

# Changelog

:cl:
code: Repaths melee weapons
qol: You can see the melee and throw force of more items
/:cl:

2023-03-19 07:42 UTC, harryob approved these changes
yes boss conflict those prs

2023-03-20 00:42 UTC, Ultimate-Fluff commented
I thought _my_ PRs modified a lot of files...

2023-03-21 16:38 UTC, realforest2001 commented
![image](https://user-images.githubusercontent.com/41653574/226679436-a0054572-b34c-4bba-a44f-69db74ff4743.png)
this is what melee is for

2023-03-23 07:57 UTC, harryob requested changes

2023-03-23 07:57 UTC, harryob commented on code/game/objects/items/weapons/weapon.dm
> +	. += SPAN_INFO("[src] would be [strong_text] weapon if you were hit someone with it.")
make nothing show up if it's less than weak

2023-03-23 15:40 UTC, harryob commented on code/game/objects/items/weapons/weapon.dm
> +	. += SPAN_INFO("[src] would be [strong_text] weapon if you were hit someone with it.")
^ this guys an idiot btw

2023-03-28 16:18 UTC, merged