Healer Balance Changes
cmss13-devs/cmss13 pull request #2896
Opened 2023-03-19 23:24 UTC by Ultimate-Fluff

# About the pull request
This pull request addresses the boring and low-risk gameplay of the Healer drone, who spends half the round sitting about and recovering her health so she may use it again, then rinse and repeat.

By changing the cost of her ability to 50 health and 200 plasma, and changing her health from 600 to 500, she can still use her ability 5 times in succession, but she won't experience as much of a penalty that forces her to sit out or make a recovery node just to heal herself. 

# Explain why it's good for the game
Healer drone isn't fun. You run around and heal a bunch of T3s, then sit out for half the battle. You think, 'screw it, I'm going to make a recovery node and camp here until I heal', but by the time you finish healing, several T3s and a silly rouny just suicided into a wall of talls. Let's make healer fun by allowing her be a more front-line participant and actively run around and heal her sisters without having to incur such a harsh penalty.

Let this be a testmerge, please.

# Changelog

:cl:
balance: Healer Drone's health was reduced to 500 from 600.
balance: Healer Drone's Apply Salve ability costs 50 health and 200 plasma, down from 50 health and up from 0 plasma.
/:cl:

2023-04-03 08:00 UTC, morrowwolf requested changes

2023-04-03 18:56 UTC, Ultimate-Fluff commented on code/modules/mob/living/carbon/xenomorph/mutators/strains/drone/healer.dm
> +	if(plasma_stored > 200)
Woop sorry

2023-04-05 22:49 UTC, Ultimate-Fluff commented
> Once you figure that out I'm down to TM this. I think the current healer position is rather lame and making them more active would make it a more fun strain.

I have figured it out. I removed the health warning because  of course abilities are disabled whilst a xeno is unconscious. However, I did add a warning Healer is too low to plasma and another warning for when a xeno has 100 or less health from full and doesn't need heals.

2023-04-14 01:07 UTC, Ultimate-Fluff commented on code/modules/mob/living/carbon/xenomorph/mutators/strains/drone/healer.dm
> +
Thank you. I've fixed both issues!

2023-04-23 07:18 UTC, morrowwolf approved these changes
Architect approval.

I'll need to go over the code again. Remind me Monday if I haven't done it yet.

2023-04-24 03:30 UTC, morrowwolf approved these changes
Code looks fine

2023-04-24 03:45 UTC, merged