Generic solution for uniform_restriction
cmss13-devs/cmss13 pull request #296
Opened 2022-05-15 05:18 UTC by spookydonut

## About The Pull Request

Moves to a generic solution that covers all cases of required uniform/etc being removed.

## Why It's Good For The Game

Less oversight issues

## Changelog

:cl:
fix: Equipment that requires other things to be equipped will now be removed properly
/:cl:

Closes #273

2022-05-15 05:43 UTC, hotimep commented
no dont

2022-05-15 06:50 UTC, Watermelon914 requested changes

2022-05-15 06:50 UTC, Watermelon914 commented on code/__DEFINES/equipment.dm
> +	. = 0
Use the NONE define instead of 0, makes it more clear that this is a bitflag

2022-05-15 06:50 UTC, Watermelon914 commented on code/game/objects/items.dm
> +			A.give_to(user) //some items only give their actions buttons when in a specific slot.
use a more detailed variable name here

2022-05-15 06:50 UTC, Watermelon914 commented on code/game/objects/items.dm
> +				var/obj/item/restriction_type = t
```suggestion
			for(var/obj/item/restriction_type as anything in uniform_restricted)
```

2022-05-15 07:11 UTC, Watermelon914 approved these changes

2022-05-16 13:06 UTC, fira approved these changes

2022-05-16 21:38 UTC, merged