Ammo can imp rack
cmss13-devs/cmss13 pull request #2979
Opened 2023-03-29 23:10 UTC by LynxSolstice

# About the pull request

Adds a relatively scarce logistics backpack item to the req vendor, allows Marines to carry 3 of any obj/item/ammo_box/, increases the logistics capability of your standard Marine. (Special thanks to Sionnach for the sprites, and Bengus, Harry, and Beagle for help with the code!)

# Explain why it's good for the game

Instead of 400 boxes of ammo or mags remaining at the FOB, this new item encourages logistics and ammo-bearing (A lot of riflemen like wearing ammo boxes on their backs, this allows them to hold more boxes + MRE boxes/flare boxes as well, thanks to those being a subtype of /ammo_box/. Allows the movement of supplies easier if you can get your hands on this elusive, limited issue item!

# Testing Photographs and Procedure

![image](https://user-images.githubusercontent.com/112824777/228687315-0aee627b-d95b-45d3-b4bb-a1664739da52.png)
![image](https://user-images.githubusercontent.com/112824777/228687337-18a4ab38-c492-45d3-a663-1cd39a742a81.png)
![image](https://user-images.githubusercontent.com/112824777/228687350-e5bb82a2-8a3c-41fd-aed7-18d6fa795e99.png)
![image](https://user-images.githubusercontent.com/112824777/228687363-11770d83-1beb-49de-b7cb-bd41fbbfe1c0.png)

# Changelog

:cl:LynxSolstice, Bengus, Sionnach, Harry, Beagle
add: Adds a new IMP framed back item, the Ammo Rack.
balance: Added the new Ammo Rack to the Req vendor. At a scaling of (round*2), it should be pretty scarce.
imageadd: Added icons for Ammo_Pack_ and onmobs for each state (0, 1, 2, and 3)
/:cl:

2023-03-29 23:46 UTC, LynxSolstice commented
> ![image](https://user-images.githubusercontent.com/56142455/228688675-9eaee797-074c-4264-8442-c7cd631bd92e.png) ![image](https://user-images.githubusercontent.com/56142455/228688688-55af7d02-5c48-4d7a-a2a5-36dd74dca400.png) You messed up some sprites

Fixed!

2023-03-30 01:44 UTC, morrowwolf requested changes

2023-03-30 01:44 UTC, morrowwolf commented on code/game/machinery/vending/vendor_types/requisitions.dm
> +		list("IMP Ammo Rack", round(scale*2), /obj/item/storage/backpack/marine/ammo_rack, VENDOR_ITEM_REGULAR),
scale*1

2023-03-30 01:45 UTC, LynxSolstice commented on code/game/machinery/vending/vendor_types/requisitions.dm
> +		list("IMP Ammo Rack", round(scale*2), /obj/item/storage/backpack/marine/ammo_rack, VENDOR_ITEM_REGULAR),
You got it

2023-03-30 07:31 UTC, nauticall approved these changes
sprites look good!

2023-04-03 06:55 UTC, morrowwolf requested changes
Make it throw range 1, add additional slowdown when carrying or wearing it.

2023-04-03 14:02 UTC, Zonespace27 requested changes

2023-04-20 00:25 UTC, closed without merging

2023-05-21 19:53 UTC, cm13live commented
This pull request has been mentioned on **CM-SS13**. Please provide feedback here:

https://forum.cm-ss13.com/t/three-improvements-for-marine-combat/2233/4