Goonify chemical retrieval (round two)
cmss13-devs/cmss13 pull request #3011
Opened 2023-04-03 12:28 UTC by morrowwolf

# About the pull request

This PR aims to do the following:
Replace the current PMC chem team with a corporate security chem team led by a researcher.
The researcher can call a PMC team for assistance so we have escalation if required. (admin approved)

This should allow for escalation of force for what should be a fairly cooperative situation. Weyland Yutani and the USCM are close friends in the Neroid sector. There is no reason this should blow up as much as it does but there should be some tension.

# Explain why it's good for the game

Read above.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>
I briefly tested some features of this.

</details>

# Changelog

:cl: Morrow
add: Chemical retrieval is now primarily corporate goons with a backup team of PMCs if required.
/:cl:

2023-04-03 15:46 UTC, Ticker175 commented
+1

2023-04-08 21:38 UTC, sleepynecrons requested changes
![image](https://user-images.githubusercontent.com/106241650/230743485-2c07d2db-974c-477c-81a3-ebf0615101a8.png)

Feel like the beacon is a little flat compared to the other handhelds in-game. Tried making up a quick example to better show what I mean.

![image](https://user-images.githubusercontent.com/106241650/230743500-8548c5f6-45d0-4914-873e-158e00975b20.png)

Also the first frame of the beacon_active animation has these two almost invisible brighter shades that none of the other frames have.

2023-04-09 19:47 UTC, sleepynecrons approved these changes
Problems I had with the sprites are fixed. Approved :D

2023-04-10 06:15 UTC, harryob requested changes

2023-04-10 06:15 UTC, harryob commented on code/game/objects/items/handheld_distress_beacon.dm
> +	to_chat(usr, SPAN_NOTICE("A distress beacon request has been sent to the USCSS Royce."))
```suggestion
	to_chat(user, SPAN_NOTICE("A distress beacon request has been sent to the USCSS Royce."))
```

2023-04-10 06:15 UTC, harryob commented on code/game/objects/items/handheld_distress_beacon.dm
> +	message_admins("[key_name(usr)] has requested a PMC Distress Beacon! (<A HREF='?_src_=admin_holder;[HrefToken(forceGlobal = TRUE)];ccmark=\ref[usr]'>Mark</A>) (<A HREF='?_src_=admin_holder;[HrefToke
```suggestion
	message_admins("[key_name(user)] has requested a PMC Distress Beacon! (<A HREF='?_src_=admin_holder;[HrefToken(forceGlobal = TRUE)];ccmark=\ref[user]'>Mark</A>) (<A HREF='?_src_=admin_holder;[HrefToken(forceGlobal = TRUE)];distress_pmc=\ref[user]'>SEND</A>) (<A HREF='?_src_=admin_holder;[HrefToken(forceGlobal = TRUE)];ccdeny_pmc=\ref[user]'>DENY</A>) (<A HREF='?_src_=admin_holder;[HrefToken(forceGlobal = TRUE)];adminplayerobservejump=\ref[user]'>JMP</A>) (<A HREF='?_src_=admin_holder;[HrefToken(forceGlobal = TRUE)];CentcommReply=\ref[user]'>RPLY</A>)")
```

2023-04-10 06:15 UTC, harryob commented on code/datums/emergency_calls/pmc.dm
> +	objectives += "Assume at least 30 units are located within the department. If they can not make more that should be all. Cooperate with the onboard wey-yu researcher to ensure all who know the compl
```suggestion
	objectives += "Assume at least 30 units are located within the department. If they can not make more that should be all. Cooperate with the onboard Wey-Yu researcher to ensure all who know the complete recipe are kept silenced with a contract of confidentiality. All humans who have ingested the chemical must be brought back dead or alive. Viral scan is required for any humans who is suspected of ingestion. Full termination of the department is authorized if they do not cooperate, but this should be avoided UNLESS ABSOLUTELY NECESSARY."
```

2023-04-10 06:15 UTC, harryob commented on code/modules/admin/topic/topic.dm
> +/datum/admins/proc/accept_PMC_ert(mob/approver, mob/ref_person)
```suggestion
/datum/admins/proc/accept_pmc_ert(mob/approver, mob/ref_person)
```

2023-04-10 06:15 UTC, harryob commented on code/modules/admin/topic/topic.dm
> +		addtimer(CALLBACK(src, PROC_REF(accept_PMC_ert), usr, locate(href_list["distress"])), 10 SECONDS)
```suggestion
		addtimer(CALLBACK(src, PROC_REF(accept_pmc_ert), usr, locate(href_list["distress"])), 10 SECONDS)
```

2023-04-10 13:02 UTC, harryob approved these changes

2023-04-10 13:14 UTC, merged