Rare slam
cmss13-devs/cmss13 pull request #3026
Opened 2023-04-07 13:26 UTC by Waseemq1235

# About the pull request

I come forward with a new wall-slam that has an extremely low chance of triggering due to the fact that it's literally the metal pipe falling sound.

# Explain why it's good for the game

We have rare sounds that come from other games like TF2 that have a low chance of triggering. I believe that the metal pipe falling sound fits this category perfectly well. Moreover the sound itself does imitate being thrown at a big metal wall, so it only makes sense.
Yes it has been tested. Yes I got carpal tunnel from that.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
soundadd: Adds a wall-slam sound that has a very rare chance of triggering.
/:cl:

2023-04-07 15:08 UTC, foxymegneil commented
SPEEDMERGE

2023-04-18 21:06 UTC, harryob requested changes
just a bit less. also this isn’t on you but i hate this pick syntax

2023-04-18 21:06 UTC, harryob commented on code/game/sound.dm
> +				S = pick('sound/effects/slam1.ogg','sound/effects/slam2.ogg','sound/effects/slam3.ogg', 2;'sound/effects/slam_rare_1.ogg')
```suggestion
				S = pick('sound/effects/slam1.ogg','sound/effects/slam2.ogg','sound/effects/slam3.ogg', 0.1;'sound/effects/slam_rare_1.ogg')
```

2023-04-19 10:54 UTC, Waseemq1235 commented on code/game/sound.dm
> +				S = pick('sound/effects/slam1.ogg','sound/effects/slam2.ogg','sound/effects/slam3.ogg', 2;'sound/effects/slam_rare_1.ogg')
oh come on atleast 1

2023-04-20 11:59 UTC, Waseemq1235 commented
how unstale

2023-04-22 15:04 UTC, harryob commented
the funny thing is i think the changed syntax might make it more common. who knows

2023-04-22 15:14 UTC, merged