Globber balance overhaul
cmss13-devs/cmss13 pull request #3039
Opened 2023-04-10 01:45 UTC by PhantomEpicness

# About the pull request
Globber came out overtuned as shit and actually replicated some of the issues that we didn't want like the dreaded ChokePoint Boiler Torture
Rebalances some issues that weren't forseen during the development nor TM stage of globber. This should be TM'd

General changes:
- Globber C/D 25 seconds > 30 seconds ( the temp nerf PR didnt actually fix this correctly)
- Fire deals 2x damage instead of 1.5x damage ( this needs significant testing and will likely be toned down)
- Acid spray doesn't stun at full distances anymore

Depending on TM feedback, I might switch between these two variants of this overhaul:

Rework variance 1: Keep zoom and current design while maintaining a little toughness [currently on]
- Armor 25 > 20
-  Zoom halved 4 > 2
-  Dropped health a tier: 650 > 600
- Fire deals 2x damage instead of 1.25x damage
- Globber C/D

Rework variance 2: Embrace the zoom removal
- Directional armor 10 base armor + 20 at the front. Flank a globber to kill it!
- Slight windup increase 5s > 6s
- Fire damage 1.25x > 1.5x

Fixes:

# Explain why it's good for the game

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl: Totalepicness

balance: Rebalances globber, which has come out overtuned. Globber now has reduced health, armor and zoom along with higher fire damage multiplier.
/:cl:

2023-04-10 13:38 UTC, morrowwolf requested changes

2023-04-10 13:38 UTC, morrowwolf commented on code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
> +	/// if fire_immunity is set to be vulnerable, how much will fire damage be multiplied. Defines in xeno.dm
Either change how the damage calculation works (as it doubles damage at the multiplier being 1 currently per line 82 of .../carbon/xenomorph/life.dm) or change the description here to say it adds the regular damage again times this number.

2023-04-13 11:47 UTC, Segrain commented on code/modules/mob/living/carbon/xenomorph/castes/Boiler.dm
> +	armor_deflection = XENO_ARMOR_TIER_1
If you are changing armour of baseline caste, change the modifier for the trapper accordingly, or this happens.
![image](https://user-images.githubusercontent.com/4447185/231749243-3da7602a-e267-4b9e-8e17-c25f39356f67.png)

2023-04-21 05:24 UTC, morrowwolf approved these changes
Possibly more nerfs in the future.

2023-04-21 06:10 UTC, merged