[ROADMAP] tightens communications
cmss13-devs/cmss13 pull request #3060
Opened 2023-04-13 20:03 UTC by ItsVyzo

# About the pull request
Tightens communications as per roadmap #38

# Explain why it's good for the game
Balance

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl: LTNTS
balance: Limited communications for PO/DCC/CT/MST/CL/VC
/:cl:

2023-04-17 17:40 UTC, morrowwolf requested changes

2023-04-17 17:40 UTC, morrowwolf commented on code/game/objects/items/devices/radio/headset.dm
> +	initial_keys = list(/obj/item/device/encryptionkey/po)
They should be using their own key.

2023-04-18 01:26 UTC, SarahJohnson489 commented
Incredibly dumb PR that ignores req communicating with squads for their supplies, CAS dragnetting surviving marines with recovered binos/flares from permas, and transport sending out cycle notifications. Ignores that the presence of the channels helps a severely isolated role feel involved with the happenings in the round instead of a muffled NPC in a slave role filling boxes or pressing the funny transport button every so often in a void. PR helps nothing and just shows more retarded decision-making seeking to make problems where there were none.

2023-04-18 03:11 UTC, ItsVyzo commented
> Otherwise, I'd like to see how this effects things. I'm not sold one way or the other but let's see how it goes.

It will be an interesting change, however I think depending on how limited communication is it could either be good or bad. Also, with the new RTO changes, it might push people to use radiopacks more. Good portion of this really depends on marine competence.

2023-04-21 06:23 UTC, morrowwolf approved these changes
This along with radio backpacks being more distributed should allow for communications to be a bit tighter without issue.

2023-04-21 06:54 UTC, merged