Corrects the C02 to CO2 for the CO2 knife
cmss13-devs/cmss13 pull request #3064
Opened 2023-04-14 05:39 UTC by BeagleGaming1

# About the pull request

Dicarbon is in fact not Carbon Dioxide

# Explain why it's good for the game

it fixes a typo

# Changelog

:cl:
spellcheck: Corrects the C02 Knife to CO2
/:cl:

2023-04-14 07:01 UTC, Zonespace27 requested changes
`CO2` -> `co2`

2023-04-14 14:11 UTC, Zonespace27 requested changes

2023-04-14 14:11 UTC, Zonespace27 commented on code/modules/projectiles/gun_attachables.dm
> +	name = "CO2 cartridge"
improper

2023-04-14 14:11 UTC, Zonespace27 commented on code/modules/client/preferences_gear.dm
> +	path = /obj/item/storage/box/CO2_knife
lower case

2023-04-14 14:11 UTC, Zonespace27 commented on code/game/objects/items/storage/misc.dm
> +/obj/item/storage/box/CO2_knife/fill_preset_inventory()
lower case

2023-04-14 14:11 UTC, Zonespace27 commented on code/datums/supply_packs/black_market.dm
> +	contains = list(/obj/item/storage/box/CO2_knife)
lower case

2023-04-18 16:39 UTC, blackcrystall commented
Why do you think that incorrect name of knife (C02)???

2023-04-18 17:33 UTC, merged