Squad Team Leader
cmss13-devs/cmss13 pull request #3073
Opened 2023-04-15 01:42 UTC by morrowwolf

# About the pull request

This PR changes RTO to Team Leader.

This PR allows the radio backpack to be buyable by team leaders or squad leaders.

This PR allows the small radio backpack to be buyable by riflemen.

This PR changes the RTO icon to a new icon

# Explain why it's good for the game

RTO is a remnant of an old design and awkwardly sits as assistant squad lead as well as requiring you to take a phone backpack and also ordnance and engineering. It's just sort of bloated and all over the place. Separating the telephone backpack and the idea of a team leader/aSL seems like a prudent move that gives the role a more focused purpose and idea.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl: Morrow
add: Squad RTOs are now Squad Team Leaders
add: Radio telephones can be bought by team leaders or squad leaders
add: Small radio telephones can be bought by riflemen
/:cl:

2023-04-15 09:26 UTC, UntoldTactics commented
I'd argue this is a bit superflous. The RTO is a very valuable, useful role and fits rather well, opposed to awkwardly. Their engineering skill tied in with communications even when comms are down makes any RTO valuable for fire support and mortars. Hell, the RTOs themselves (such as in bravo) can also act as engineers + man the mortars, not only freeing up specialized engineers but also being able to use their phone backpack to be called directly to get cords etc. 

They fill a niche in that they're dedicated roles for fire support and communication, allowing CAS and mortar to be more effective than without, even during comms-blackouts. 

It's arguably more bloaty to add a role that's just a fireteam leader, we don't need such large hierarchies.

2023-04-15 09:29 UTC, N8-Toe commented
Agreed with untold. This is more bloaty as well the RTO is a very unique communications and support focused role. To loose it would be a shame.

2023-04-16 07:54 UTC, frozentsbgg commented
I'm a big fan of this role segmentation of RTO and I mostly like this PR.
That being said I'm really not a fan of the naming of the role, and I can see it being a bit confusing 
![74f996801dc3cb0a2f160c9691f6c371-png](https://user-images.githubusercontent.com/23017031/232283382-4355eec7-ae7b-4f53-ae00-93b93b2a5fd7.jpg)

Calling it Fire Team leader might be a better name - or just keep RTOs as a throwback. I prefer the later option but I can understand if we want a different name.

2023-04-16 23:08 UTC, Diegoflores31 commented
Squad Team leader name is kinda confusing with squad leader . it should be just "Team leader" or something like that

2023-04-19 03:22 UTC, 4hands44 commented
I like the idea but why not give it either the Real world name of Fire team lead, or Assistant SL  The current name is wordy and weird

2023-05-02 21:11 UTC, harryob requested changes

2023-05-02 21:11 UTC, harryob commented on code/game/jobs/job/marine/squad/tl.dm
> +	H.important_radio_channels += JTAC_FREQ
```suggestion
	spawning_human.important_radio_channels += JTAC_FREQ
```

2023-05-02 21:11 UTC, harryob commented on code/game/jobs/job/marine/squad/tl.dm
> +/datum/job/marine/tl/generate_entry_conditions(mob/living/carbon/human/H)
```suggestion
/datum/job/marine/tl/generate_entry_conditions(mob/living/carbon/human/spawning_human)
```

2023-05-03 19:53 UTC, harryob approved these changes
i promise to do some fun stuff with fireteams eventually

2023-05-03 20:12 UTC, merged