Maintenance Jack Tweaks
cmss13-devs/cmss13 pull request #3096
Opened 2023-04-19 01:42 UTC by BeagleGaming1

# About the pull request

- Adds prying flooring
- Gives more variables
- Breaks everything
- Adds wrench surgery

Sprites by sleepynecrons
# Explain why it's good for the game

These are changes I would have included in the original PR if I had received the feedback about it, 

# Changelog

:cl:
balance: Maintenance Jack can pry flooring and do wrench surgery
/:cl:

2023-04-19 14:05 UTC, Nanu308 commented
So it would be a all-in-one tool and also a useful weapon?

Sorry but no, that is extreme powercreep and even if its a synth tool too strong.

2023-04-19 20:26 UTC, Waseemq1235 reviewed
imo just make it an all-in-one tool but keep it the same size and make it deal the damage of a wrench. seems fair enough to me.

dont know if nanu agrees though D:

2023-04-22 10:34 UTC, Katskan commented
Going to weigh in because I think a "balance" call is being made here without applicable experience, and our other forums for feedback are gone. 

There is currently a very entrenched meta in synthetic tools whereby the baton is king, and mesons a close second. The baton is our focus here. There are a scarce few options for replacing the baton, the only really viable choice being a machete or B5 hammer. If you keep in mind that the original maintenance jack damage is the same as a machete, which is significantly weaker than the baton or the B5 hammer, and that it has greater attack delay and lower speed, it is the fourth strongest melee option for a shipside synthetic to carry. If you want to make it have lower damage, it will not change the meta picks at all. If you leave it as it was originally proposed on par with a machete, it has real potential to de-throne the baton by giving a viable pick that trades huge damage for more utility and soul. 

Also wrench damage is straight up a bad idea, synthetics punch with more damage than they hit things with tools for. At minimum boot knife damage would be appropriate.

2023-04-24 20:10 UTC, Zonespace27 requested changes
Not a full review

2023-04-24 20:10 UTC, Zonespace27 commented on code/game/machinery/doors/airlock.dm
> +	if(istype(C, /obj/item/weapon/maintenance_jack)) //Its got custom code but some parts of the attackby break it
This is what signals exist for

2023-04-24 20:10 UTC, Zonespace27 commented on code/game/objects/items/tools/maintenance_tools.dm
> +				if(!do_after(user, unskilled_unbolt_time SECONDS, INTERRUPT_ALL, BUSY_ICON_HOSTILE, src, INTERRUPT_ALL)) //Otherwise it takes an extra 15 seconds
Move the second defines to the variables

2023-05-06 20:30 UTC, Nanu308 commented
Lower dmg to little below bootknife and keep the size so it requires a spot

2023-05-13 17:33 UTC, FransFeiffer requested changes
I know it's nitpicky, but the handle outline and the bit at the top of the jack use (1,1,1,), please change it to something like the below picture. Otherwise the sprites are fire.
![image](https://github.com/cmss13-devs/cmss13/assets/44514761/eb006c9c-f484-49ee-af01-b30dc7323e7e)

2023-05-13 21:14 UTC, FransFeiffer approved these changes
ok we're good to go 👍

2023-05-22 23:12 UTC, harryob requested changes

2023-05-22 23:12 UTC, harryob commented on code/game/objects/items/tools/maintenance_tools.dm
> +	. = ..()
```suggestion
	return ..()
```

2023-05-22 23:12 UTC, harryob commented on code/game/machinery/doors/airlock.dm
> +
pseudocode but you can put this in airlock/attackby

```dm
if(SEND_SIGNAL(C, COMSIG_ITEM_ATTACK_AIRLOCK, src) & COMSIG_ITEM_CANCEL_AIRLOCK_ATTACK)
 return
 ```
 
then you can...

 ```dm
/obj/item/maintenance_jack/Initialize()
RegisterSignal(src, COMSIG_ITEM_ATTACK_AIRLOCK, PROC_REF(handle_airlock_attack))

/obj/item/maintenance_jack/proc/handle_airlock_attack(source, obj/structure/machinery/door/airlock/attacked_door)
    // you can do all your airlock specific code here
    return COMSIG_ITEM_CANCEL_AIRLOCK_ATTACK
```

2023-06-04 22:30 UTC, Nanu308 commented
No mapping file being touched in latest commit?

2023-06-05 21:19 UTC, BeagleGaming1 commented
> No mapping file being touched in latest commit?

Nope

2023-06-07 03:53 UTC, merged