Medicomp surgery can heal organ damage
cmss13-devs/cmss13 pull request #3097
Opened 2023-04-19 02:11 UTC by BeagleGaming1

# About the pull request

Yautja do not currently have any ways to heal their organs

# Explain why it's good for the game

This lets them actually fix their organs

# Changelog

:cl:
balance: Adds a way to heal organ damage via the medicomp
/:cl:

2023-04-19 14:07 UTC, Nanu308 commented
Actually on second thought, this should rather be added to the yautja self surgery tool, but i'd be fine with Thwei potentially working as Peri, depending on how long Thwei remains in the system

2023-04-19 18:09 UTC, Diegoflores31 commented
> Actually on second thought, this should rather be added to the yautja self surgery tool, but i'd be fine with Thwei potentially working as Peri, depending on how long Thwei remains in the system

pretty sure a shot of thwei can last like half an hour . so i think surgery is a better alternative

2023-04-20 22:10 UTC, harryob requested changes

2023-04-20 22:10 UTC, harryob commented on code/modules/surgery/mcomp_tendwounds.dm
> +			SPAN_NOTICE("[user] finished treating [target]'s damaged organs with \the [tool]."))
```suggestion
			SPAN_HELPFUL("You finish treating [target]'s damaged organs with [tool]."),
			SPAN_HELPFUL("[user] finished treating your damaged organs with [tool]."),
			SPAN_NOTICE("[user] finished treating [target]'s damaged organs with [tool]."))
```

2023-04-20 22:10 UTC, harryob commented on code/modules/surgery/mcomp_tendwounds.dm
> +	log_interact(user, target, "[key_name(user)] Treated some of [key_name(target)]'s organ damage with \the [tool].")
```suggestion
	log_interact(user, target, "[key_name(user)] treated some of [key_name(target)]'s organ damage with [tool].")
```

2023-04-20 22:10 UTC, harryob commented on code/modules/surgery/mcomp_tendwounds.dm
> +	log_interact(user, target, "[key_name(user)] failed to tend [key_name(target)]'s organ damage with \the [tool], possibly ending [surgery].")
```suggestion
	log_interact(user, target, "[key_name(user)] failed to tend [key_name(target)]'s organ damage with [tool], possibly ending [surgery].")
```

2023-04-21 04:28 UTC, morrowwolf requested changes
Issue design-wise: without damage you cannot start the surgery. Check line 17 of mcomp_tendwounds and add a check for organ damage. Otherwise, seems fine.

2023-04-24 03:49 UTC, morrowwolf approved these changes

2023-04-24 04:00 UTC, merged