Médicale Révolutionnaire - The comeback
cmss13-devs/cmss13 pull request #3106
Opened 2023-04-19 23:55 UTC by LC4492

# About the pull request

2023-04-19 23:56 UTC, LC4492 commented
...The Pull request explanation is not working, for some reason. Well

2023-04-26 13:46 UTC, Nanu308 requested changes
You broke a dict key for sure in your commits.

![bilde](https://user-images.githubusercontent.com/59782240/234595404-939ba168-bf4d-4b27-bba0-fc22ee1d220d.png)

2023-04-26 21:35 UTC, LC4492 commented
...Could you please explain further? I've tested the game and the status displays work flawlessly

2023-04-29 16:50 UTC, ItsVyzo requested changes

2023-04-29 16:50 UTC, ItsVyzo commented on code/game/jobs/job/logistics/engi/ordnance_tech.dm
You broke OT icon w/ this change

undo

2023-04-29 16:50 UTC, ItsVyzo commented on maps/map_files/USS_Almayer/USS_Almayer.dmm
Also, you have several changes unrelated to medical (new APCs around Almayer & Briefing - break them up)



What's with the dummy?
![image](https://user-images.githubusercontent.com/46250991/235314164-7ae93f99-04cb-42c3-a430-4f3c0ae49a6a.png)

2023-04-30 14:17 UTC, LC4492 commented on code/game/jobs/job/logistics/engi/ordnance_tech.dm
...Its not broken because isn't being used anymore, at least to my knowledge.

2023-04-30 14:19 UTC, LC4492 commented on maps/map_files/USS_Almayer/USS_Almayer.dmm
...I needed to do those "unrelated changes to medical" to change the parts "related to medical", I can't really "break them up". The dummy is certainly a mistake, will see what can be done.

2023-04-30 15:28 UTC, ItsVyzo commented on code/game/jobs/job/logistics/engi/ordnance_tech.dm
OT is still in use, you're literally reintroducing a bug I fixed by breaking OT landmarks again #2780 =.=

2023-04-30 18:53 UTC, LC4492 commented on code/game/jobs/job/logistics/engi/ordnance_tech.dm
...A bug that I reported, so that's kind of interesting. The changes that exist are remnants of what I tried to do to repair the bug before reporting it. Well, I will see what can be done.

2023-06-03 10:49 UTC, Watermelon914 commented
This PR has been inactive for some time, feel free to re-open (as a new PR so that it appears at the top of the tracker) when you decide to work on this again.

2023-06-03 10:49 UTC, closed without merging