Additional needhelp lines
cmss13-devs/cmss13 pull request #3108
Opened 2023-04-20 00:53 UTC by LynxSolstice

# About the pull request

Adds 8 new *medic lines. Each one either mentions Corpsman or Doc. Makes the TF2 easteregg lines more rare.

# Explain why it's good for the game

Extra voicelines, immersion (people will be calling for a Corpsman now, rather than a medic.), plus more variety in lines heard.

# Testing Photographs and Procedure

Compiles, runs, and works fine.

# Changelog

:cl:LynxSolstice
spellcheck: Changed the visible mentions of "Medic" to "Corpsman"
soundadd: Added 8 new lines for the *medic emote.
/:cl:

2023-04-20 08:54 UTC, harryob commented on sound/voice/Im_hit_get_doc_up_here.ogg
lowercase

2023-04-20 08:54 UTC, harryob commented on sound/voice/I_need_a_corpsman_1.ogg
lowercase

2023-04-22 07:49 UTC, harryob requested changes

2023-04-22 07:49 UTC, harryob commented on sound/voice/I_need_a_corpsman_1.ogg
these files are all still upper case btw

2023-04-22 23:18 UTC, LynxSolstice commented on sound/voice/I_need_a_corpsman_1.ogg
Renamed em in VSC but I guess I gotta do it in the explorer, I'll push it in a min or 2 once I get it done.

2023-04-22 23:21 UTC, LynxSolstice commented on sound/voice/I_need_a_corpsman_1.ogg
They don't seem to be uppercase in the file explorer OR VSC, they're just uppercase in github for some reason? 
![image](https://user-images.githubusercontent.com/112824777/233811578-f4ac6203-3c81-47d0-beae-f6d698e1947f.png)
![image](https://user-images.githubusercontent.com/112824777/233811588-89360dfc-ee3b-452f-9a3c-3dcaee2a3ad1.png)

2023-04-24 16:42 UTC, merged