Fixes Survivor radio access and Yautja emotes.
cmss13-devs/cmss13 pull request #3111
Opened 2023-04-20 12:21 UTC by realforest2001

# About the pull request
Survivors are not intended to be able to simply radio to the Almayer, the exception being deliberately placed USCM radio telephone packs. This PR fixes those who had almayer comms given to them.

Additionally, the Yautja loudroar emote overwrote a check that is causing some funky behaviour.

# Explain why it's good for the game
Bugs are bad. Also survivors with marine radios is counter intuitive.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
fix: Yautja loud roars are no longer fake-able.
fix: Survivors no longer have free marine comms as intended.
add: Changed the random supply kit picker contents to remove USCM specific kits (those with USCM comms).
add: Added a blackmarket subtype of the random supply kit to keep the USCM specific kits.
/:cl:

2023-04-20 20:17 UTC, morrowwolf requested changes

2023-04-20 20:17 UTC, morrowwolf commented on code/datums/supply_packs/black_market.dm
> +				new /obj/effect/spawner/random/supply_kit/market(loc)
undocumented change

2023-04-23 10:10 UTC, realforest2001 commented on code/datums/supply_packs/black_market.dm
> +				new /obj/effect/spawner/random/supply_kit/market(loc)
Forgot about that!

2023-04-24 11:22 UTC, morrowwolf approved these changes
Code LGTM

2023-04-24 11:34 UTC, merged