Fix hearing weather in space
cmss13-devs/cmss13 pull request #3145
Opened 2023-04-24 17:42 UTC by Huffie56

# About the pull request
added a muffle to space to avoid having rain sound not perfect but well i don't see how to fix it otherwise..
![image](https://user-images.githubusercontent.com/117036822/234074378-3d19eaa1-6370-40bc-b7c5-be4fb18af2aa.png)

# Explain why it's good for the game
no more rain in space always good because it never rain in space.

# Testing Photographs and Procedure

tested it it work fine

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:

fix: removed weather sound in space when weather is active.

/:cl:

2023-04-24 17:44 UTC, Huffie56 commented
please don't ask me to remove the comment as i think it will be needed if someone try to rework the code later.

2023-05-02 20:53 UTC, harryob requested changes

2023-05-03 13:41 UTC, harryob approved these changes

2023-05-03 13:42 UTC, harryob commented
and hell space should be quiet, right? no air n all

2023-05-03 13:55 UTC, merged