Dancer buff + Bug Fixes
cmss13-devs/cmss13 pull request #3179
Opened 2023-04-28 14:00 UTC by Git-Nivrak

# About the pull request
Removes the mini cooldown on missing dancer impale and tail trip

# Explain why it's good for the game
Will make more people play dancer, Makes it feel smoother to play.
Having your entire combo be interrupted by missing one click is extremely awkward, especially as a t3 with little health and armor being punished for that seems unreasonable.

If this turns out to make dancer too strong the cooldown can be reduced instead of completely removed.
# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog
:cl:
balance: Removed the cooldown on missing Dancer's impale and tail trip abilities.
fix: Dancer's slash tag no longer gets consumed by tail trip if the target is out of range.
/:cl:

2023-04-28 15:27 UTC, morrowwolf reviewed
I'm happy to try this. I'm not sold on it yet.

2023-04-29 03:12 UTC, Zonespace27 requested changes

2023-04-29 03:12 UTC, Zonespace27 commented on code/modules/mob/living/carbon/xenomorph/abilities/praetorian/praetorian_powers.dm
> +		for (var/datum/effects/dancer_tag/dancer_tag_effect in target_carbon.effects_list)
Use the locate(type) in list syntax instead of a loop

2023-04-29 22:28 UTC, TeDGamer commented
For changelog, it's "fix:" not "bugfix:"

2023-05-16 08:32 UTC, morrowwolf approved these changes
Usual disclaimer: if this causes issues it'll be changed blah blah blah.

TM a bit ago when decent without an crazy change in usage or becoming problematic.

Let's get it merged.

2023-05-16 08:52 UTC, merged

2026-01-10 17:34 UTC, Ammoniacres commented
This is merged but doesn't seem to work anymore? Removing the cooldown override codelines actually produces the intended effect of removing the cooldowns on miss-click. Should probably be logged as a bug.

2026-01-10 18:35 UTC, Git-Nivrak commented
Nice necropost
The code worked it was just reverted in a later pr