GAU buff.
cmss13-devs/cmss13 pull request #3185
Opened 2023-04-29 15:16 UTC by Tisx1

# About the pull request
For too long the GAU has been the joke of the CAS weapons, due to it's RNG and somewhat mediocre damage numbers, people tend to either ignore or hell even laugh at a GAU strike, as seen here: https://cdn.discordapp.com/attachments/458150341742166017/1052649816179626035/GAU.mp4

The goal of this buff, is simple; punish players who think they stand in a hellstorm of 30mm bullets and get away with it. Or in a more technical sense, actually make the GAU do what it is designed to do, area denial and suppression, you shouldn't be able to walk through the center of an active GAU fire mission and live to tell the tale, regardless of caste, armor, or species. 

The changes made are simple: instead of hitting a single tile per bullet, a single bullet will now affect a 3x3 area, as seen in the testing footage below. 

# Explain why it's good for the game

For POs, it will make the GAU worth it's price tag, as nothing will be able to match it's short term area denial and area suppression ability.

This buff will also give the GAU the atmosphere of fear that the other CAS weapons bring, no longer will immersion be broken by people literally standing in 30mm hell rain. 

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>
https://youtu.be/ZBrymhLBUNY

</details>

# Changelog

:cl:Tisx

balance: Turned a single GAU impact from 1x1 to 3x3. 

/:cl:

2023-04-29 15:29 UTC, morrowwolf reviewed
Alright, we're going to test this.

I am aware this is likely overtuned.

It will be tuned down as required.

2023-04-30 14:52 UTC, Tigerbottle commented
Well you made GAU so good that there is no point in choosing rockets. I guess that's nice.

2023-05-03 14:33 UTC, Tisx1 commented on code/modules/projectiles/ammo_datums.dm
> +
A part of my brain likes space I guess., it's been fixed

2023-05-04 16:56 UTC, nauticall commented
See #3185, might have to do with this PR but I'm not sure.

2023-05-07 04:34 UTC, morrowwolf requested changes
Even less impacts.

Silver bullet has to go.

No TM until this occurs.

2023-06-12 01:50 UTC, closed without merging