discord certification
cmss13-devs/cmss13 pull request #3192
Opened 2023-04-30 10:46 UTC by harryob

this does the backend in dm for discord certification, bringing with it an extensive world/Topic api, multikey checking and various database insanities

:cl:
server: the server can now support automated discord certification
/:cl:

2023-05-07 18:39 UTC, fira commented
Not really a big fan of BanFromFirewall X_X

2023-05-07 22:37 UTC, morrowwolf requested changes

2023-05-07 22:37 UTC, morrowwolf commented on code/datums/entities/login_triplets.dm
> +/proc/analyze_ckey(ckey)
This should really be a button usable by staff somewhere 👀

2023-05-08 09:28 UTC, harryob commented
> Not really a big fan of BanFromFirewall X_X

agreed, hangover from the bee world api. purged now, but i'll retain the ratelimiting aspect

2023-05-11 06:02 UTC, merged