CLF Ship Nightmare Changes
cmss13-devs/cmss13 pull request #3199
Opened 2023-05-01 09:22 UTC by toolmind

# About the pull request

updates the CLF ship's airlocks to new generic ones and adds one CLF medic and one CLF engineer.
(batu khan update coming soon)

# Explain why it's good for the game

The CLF ship should be very difficult to survive in, but not having anyone that can make folding cades/barricades quickly means the best option is to entirely ignore the cool new area of the map with potential for a cool holdout/last stand, and instead immediately abandon it to rush for a gap with the van. Having a medic also allows for the CLF survivors to have a chance at being revived instead of one death immediately putting them out of the game for good or meaning they'll spend the rest of the round in the permabrig if they get revived by the marines. I know a synth can spawn with them, but it's not a given at all that a person is going to be rolling synthvivor every round that the insert spawns in.

The doors were also outdated and took like 5 seconds to fully open, annoyance for survivors, xenos and marines alike.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl: IowaPotatoFarmer
maptweak: Switched the outdated CLF ship airlocks to new generic ones.
add: The CLF crashed ship insert on LV-624 now has one guaranteed medic and one guaranteed engineer.
/:cl:

2023-05-01 11:59 UTC, harryob requested changes

2023-05-01 11:59 UTC, harryob commented on code/game/objects/effects/landmarks/survivor_spawner.dm
> +	"<span class='notice'>You are NOT aware of the xenomorph threat.</span>",\
```suggestion
	SPAN_NOTICE("You are NOT aware of the xenomorph threat."),\
```

2023-05-01 11:59 UTC, harryob commented on code/game/objects/effects/landmarks/survivor_spawner.dm
> +	"<span class='danger'>Your primary objective is to heal up and survive. If you want to assault the hive - adminhelp.</span>")
```suggestion
	SPAN_DANGER("Your primary objective is to heal up and survive. If you want to assault the hive - adminhelp."))
```

2023-05-01 11:59 UTC, harryob commented on code/game/objects/effects/landmarks/survivor_spawner.dm
> +	story_text = "You are a soldier of Colonial Liberation Front. Your ship received a distress signal from a planet bordering the CLF controlled space under USCM control. Ready and willing to save poor
```suggestion
	story_text = "You are a soldier of Colonial Liberation Front. Your ship received a distress signal from a planet bordering the CLF controlled space under USCM control. Ready and willing to save poor colonists from parasitic tyrants, you and your team boarded small ship called Marie Curie. Unfortunately, right before you came close to a landing zone, a glob of acid hit the ship, damaging one of the engines. Despite all the efforts of the pilot, the ship went straight into nearby mountain. You were hurt pretty badly in the crash. Dumbfounded, you rose up and noticed that one of your limbs is at a weird angle, broken. You looked at other survivors, also limping and trying to fix their broken bones. [SPAN_RED("You also notice that sentry turrets on the ramp of your ship beep angrily, it seems their logic circuits got damaged. They will identify you as a foe, but at least they will identify everything as a foe.")]"
```

2023-05-01 11:59 UTC, harryob commented on code/game/objects/effects/landmarks/survivor_spawner.dm
> +	story_text = "You are a soldier of Colonial Liberation Front. Your ship received a distress signal from a planet bordering the CLF controlled space under USCM control. Ready and willing to save poor
```suggestion
	SPAN_NOTICE("You are NOT aware of the xenomorph threat."),\
	SPAN_DANGER("Your primary objective is to heal up and survive. If you want to assault the hive - adminhelp."))
	story_text = "You are a soldier of Colonial Liberation Front. Your ship received a distress signal from a planet bordering the CLF controlled space under USCM control. Ready and willing to save poor colonists from parasitic tyrants, you and your team boarded small ship called Marie Curie. Unfortunately, right before you came close to a landing zone, a glob of acid hit the ship, damaging one of the engines. Despite all the efforts of the pilot, the ship went straight into nearby mountain. You were hurt pretty badly in the crash. Dumbfounded, you rose up and noticed that one of your limbs is at a weird angle, broken. You looked at other survivors, also limping and trying to fix their broken bones. [SPAN_RED("You also notice that sentry turrets on the ramp of your ship beep angrily, it seems their logic circuits got damaged. They will identify you as a foe, but at least they will identify everything as a foe.")]"
```

2023-05-01 23:28 UTC, toolmind commented
harryOB GRIEFS my pr and cause check errors (evil). i'll see if i can fix it, probably going to remove that red spanned part about the sentries because they have CLF IFF now anyways.

2023-05-02 00:37 UTC, cm13live commented
This pull request has been mentioned on **CM-SS13**. Please provide feedback here:

https://forum.cm-ss13.com/t/nightmare-survivor-spawn-rework/1795/3

2023-05-06 17:48 UTC, harryob approved these changes

2023-05-07 22:04 UTC, merged