Night Vision Goggles
cmss13-devs/cmss13 pull request #32
Opened 2022-04-15 18:18 UTC by Diegoflores31

## Changelog

:cl: diegoflores31 , ihatethisengine

rscadd: Adds working Night Vision Goggles 

rscadd: adds MASORC variant for Nvgs

rscadd: adds Nvgs to SL and RTO vendors

rscadd: Adds Nvgs crate x3 to Req console

/:cl:

## Details

this code was made by @ihatethisengine all credits for his work ( [!1925](https://gitlab.com/cmdevs/colonial-warfare/-/merge_requests/1925#diff-content-945b6b76a648267a42d7b0998e0ba5ac5640fa14)

**M2 Night Vision Goggles**

-New Attachable for helmets that allows you to see in the dark with a green filter and with a rechargable battery that lasts for a limited amount of time and can be reloaded with normal battery cells

-Night Vision Goggles can be broken by slashing the head of the Talls

-NVGs can also be repaired at the cost of decreased battery life

-Cant be used with Binoculars / Scopes 

 **M2 Tactical Night Vision Goggles**

this is an special variant of the night vision goggles featuring a self recharging battery which makes its use unlimited commonly used by MARSOC forces in special operations

**IN-GAME IMAGE**

![image](/uploads/7dec2e4cf285339ccb620369c95321f8/image.png)

## Related Issues

Closes

2022-04-16 19:16 UTC, Agameofscones approved these changes
Map and icon changes are 👌

2022-04-18 20:44 UTC, Watermelon914 requested changes

2022-04-18 20:44 UTC, Watermelon914 commented on code/_onclick/click.dm
> +	if(SEND_SIGNAL(mob, COMSIG_MOB_CHANGE_VIEW, new_size) & COMPONENT_OVERRIDE_VIEW) return TRUE
```suggestion
	if(SEND_SIGNAL(mob, COMSIG_MOB_CHANGE_VIEW, new_size) & COMPONENT_OVERRIDE_VIEW) 
		return TRUE
```

2022-04-18 20:44 UTC, Watermelon914 commented on code/game/objects/items/props/helmetgarb.dm
> +		to_chat(user, "A small gauge in the corner reads: Power: [round(100.0*nvg_charge/nvg_maxcharge) ]%.")
Separate these out into different procs.
Your do_afters should use the SECONDS defines as well

2022-04-18 20:44 UTC, Watermelon914 commented on code/game/objects/items/props/helmetgarb.dm
> +	attached_mob = A
use a more detailed variable name for A

2022-04-18 20:44 UTC, Watermelon914 commented on code/game/objects/items/props/helmetgarb.dm
> +	if(check_zone(X.zone_selected) == "head" && user == attached_mob)
use a more detailed variable name for xenomorph X

2022-04-20 15:33 UTC, usnpeepoo commented
I recommend removing RTOs from purchasing this. Normally with only 4 players (SL) having Night vision  the impact on a round isn’t significant however on high pop there are 8 RTO slots available which immediately boosts the amount of marines having night vision to 16. The roles would just be taken to power game and abuse nightvisions and having it only set to SLs (who actually need love) would be preferable than having 16 night vision runners in a round.

2022-04-22 19:49 UTC, Diegoflores31 commented
changes applied

2022-04-24 22:38 UTC, closed without merging