fix change armour iteration to armor
cmss13-devs/cmss13 pull request #3200
Opened 2023-05-01 10:27 UTC by Huffie56

# About the pull request
fix change armour iteration to armor
need to choose one for the changelog.

# Explain why it's good for the game

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:

fix: fix change armour iteration to armor
spellcheck: fix change armour iteration to armor
code: fix change armour iteration to armor

/:cl:

2023-05-03 05:54 UTC, Zonespace27 requested changes

2023-05-03 05:54 UTC, Zonespace27 commented on tgui/packages/tgui/interfaces/WeaponStats.js
Find & replace made this file worse

2023-05-03 05:55 UTC, Zonespace27 commented on tgui/packages/tgui/interfaces/WeaponStats.js
also, make your PR title, desc, and CL better. The fact that I had to check the code to know what this was supposed to do is very much not a good thing

2023-05-03 12:52 UTC, Huffie56 commented
@Zonespace27  i changed the tittle but i don't know what you mean when you say that i made the file worse...
 can you explain ? should i just close this PR?

2023-05-03 14:53 UTC, Zonespace27 commented
You lower cased a bunch of armors that shouldn't be

2023-05-04 08:54 UTC, Huffie56 commented
i messed up the code and the quickest way would be to restart from the ground up so i am closing this PR and reopening a new one. i learned a bunch of stuff doing this one so not all is lost

2023-05-04 08:54 UTC, closed without merging