Almayer Fixes And Touchups
cmss13-devs/cmss13 pull request #3201
Opened 2023-05-01 10:55 UTC by spartanbobby

# About the pull request
This PR

1, Fixes misplaced objects/turfs around the Almayer that slipped past review
2, Fixes lights/fire alarms that were against glass
3, Removes the CEs personal cyropod to maintain consistency
4, Adjusts certain warning stripes to be flush with the walls

# Explain why it's good for the game

1, Self-explanatory, it's a bug it gets fixed
2, It doesn't look pretty or make much sense to me
3, The only reason the CL has his own hypersleep pod is that there isn't a hypersleep bay close enough to his room, the engineering bay is close enough to his office that he doesn't need his own and should wake up with his men
4, doesn't look nice having them be one pixel away from the wall when the apposite ones are flush with them

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl: SpartanBobby
maptweak: Various minor almayer mapping fixes involving warning stripes and misplaced turfs and objects
maptweak: the CE now spawns with his men again
maptweak: lights or firealarms that were once on windows have been moved to a wall or have had a wall replace the windows they were once on
/:cl:

2023-05-01 11:15 UTC, Huffie56 commented
![image](https://user-images.githubusercontent.com/117036822/235444577-aa137925-1e2a-4e50-aa45-49f811f11888.png)
if your making a fix for almayer look at the emergency shutters...
i advise you to make a private server and test all of them...

2023-05-02 21:45 UTC, Nanu308 requested changes
Dont run pipes under walls when you can do it differently
![bilde](https://user-images.githubusercontent.com/59782240/235792726-5ede7fa5-892e-4773-8d20-29e730055c3a.png)

2023-05-02 21:48 UTC, Nanu308 requested changes

2023-05-02 21:48 UTC, Nanu308 commented on maps/map_files/USS_Almayer/USS_Almayer.dmm
>  	},
Pipe under windows should be avoided
![bilde](https://user-images.githubusercontent.com/59782240/235793048-bf13b254-58df-4e20-8ace-1882a89ecc43.png)

2023-05-02 21:48 UTC, Nanu308 commented on maps/map_files/USS_Almayer/USS_Almayer.dmm
>  	},
rest lgtm

2023-05-03 17:27 UTC, merged