Armor blocks surgery
cmss13-devs/cmss13 pull request #3213
Opened 2023-05-02 22:55 UTC by BeagleGaming1

# About the pull request

Literally just copy pasted most of #2606 

# Explain why it's good for the game

I was told to do it

# Changelog

:cl:
balance: Most armor blocks surgery when worn
/:cl:

2023-05-02 23:03 UTC, morrowwolf approved these changes
Architect approved.

I feel you should have to take off a bit of gear to really do surgery on someone.

2023-05-03 05:52 UTC, Zonespace27 requested changes

2023-05-03 05:52 UTC, Zonespace27 commented on code/modules/mob/living/carbon/carbon_helpers.dm
> +/mob/living/carbon/proc/get_sharp_obj_blocker(obj/limb/limb)
code doc

2023-05-03 05:52 UTC, Zonespace27 commented on code/modules/mob/living/carbon/human/human_defense.dm
> +	return null
not a needed line

2023-05-03 05:52 UTC, Zonespace27 commented on code/modules/mob/living/carbon/human/human_defense.dm
> +	var/list/protective_gear = list(head, wear_mask, wear_suit, w_uniform, gloves, shoes, glasses)
put the list on line 81 instead of making it a var

2023-05-03 05:52 UTC, Zonespace27 commented on code/modules/mob/living/carbon/human/human_defense.dm
> +	for(var/obj/item/gear in protective_gear)
as anything

2023-05-03 05:52 UTC, Zonespace27 commented on code/modules/surgery/surgery_steps.dm
> +			to_chat(user, SPAN_WARNING("\The [blocker] \the [target] is wearing restricts your access to the surgical site, take it off!"))
\the is implicit

2023-05-04 08:53 UTC, harryob commented on code/modules/mob/living/carbon/human/human_defense.dm
> +	for(var/obj/item/gear in list(head, wear_mask, wear_suit, w_uniform, gloves, shoes, glasses))
yeah it would, there's no guarantee there aren't nulls in this list (if someone isn't wearing gloves, shoes, glasses, whatever)

2023-05-04 08:53 UTC, harryob approved these changes

2023-05-04 15:34 UTC, brjoaoed commented
Like the internal bleeding + QC removal wasn't good enough for devs, now we get this too ? Those are nerfs that no one have ever asked for, and serve no purpose, only takes valuable time from Squad Medics who may be in the middle of a conflict, while all xenos have to do is rest on weeds and replenish their health quickly.

If you plan to shove those nerfs down the player throats, at least have the decency to not include the 'balance tag' which for sure isn't 'balanced'.

2023-05-04 17:50 UTC, merged