added functionality for faxing photos, bundles.
cmss13-devs/cmss13 pull request #3221
Opened 2023-05-03 22:25 UTC by FreetoZ

# About the pull request

Added functionality for faxing photos and paper bundles, and also refactored some code in this domain.

# Explain why it's good for the game

Admins can now be harassed with multiple pages of paper and photos. 

# Changelog

:cl:
add: Added functionality for faxing photos and paper bundles
/:cl:

2023-05-04 19:24 UTC, FreetoZ commented
I think I fixed my blunder, should be good now.

2023-05-05 03:12 UTC, FreetoZ commented
linter be lintering, all good now.

2023-05-06 01:42 UTC, Drulikar requested changes
Images do not currently work on first transmission (atleast when sent to high command): Neither via IMG link nor via the page view: 
![image](https://user-images.githubusercontent.com/76988376/236590983-ac3978f5-3392-4398-ad64-859d37916782.png)

Faxing this same bundle to the brig resulted in the images to appear in page, but still not via IMG button. Also each time the bundle is re-transmitted, the photos are duplicated in the fax datum (this is the 2nd transmission of a fax with two images): 
![image](https://user-images.githubusercontent.com/76988376/236591013-2140e4a5-ea64-4940-9eb4-3236db02c40d.png)

If we're including photos in the faxes, its probably unnecessary to have an IMG button anyways

2023-05-06 01:42 UTC, Drulikar commented on code/modules/client/client_procs.dm
All changes to this file can be discarded if we remove the IMG link.

2023-05-06 01:42 UTC, Drulikar commented on code/game/machinery/fax_machine.dm
> +				to_chat(ui.user, SPAN_NOTICE("You put \the [original_fax.name] into \the [src]."))
Make the fax machine jam if more than 5 items are inserted in a bundle (different to_chat, maybe a sfx, disable send_fax (just need to check the length of the bundle if its a bundle).

2023-05-06 01:42 UTC, Drulikar commented on code/game/machinery/fax_machine.dm
> +			copy_fax_paper()
We probably only need to copy if the copy isn't set. Just be sure to clear the copy when original_fax is removed.

2023-05-06 01:45 UTC, Drulikar commented
I don't think view/sending photos need to be admin only either. If its abused moderators can handle it. If it is expensive to view a fax, we can optimize/revert.

2023-05-06 07:09 UTC, FreetoZ commented
still working on the duplication issue.

2023-05-07 04:21 UTC, Drulikar requested changes
I think all technical issues are solved. Here is a polish pass to fix messages, behavior, and anything else that stuck out to me.

There are a fair few places where the messages and examines are a bit wonky: My suggestions should address them. I also tweaked how jamming is handled because I think its more interactive and interesting to require unjamming the machine.

By the way, you don't need to manually add suggestions I provide, just batch them, try them out, and edit as needed:
![image](https://user-images.githubusercontent.com/76988376/236655828-f0b08eb2-d7c9-43fb-a427-5d940e09b744.png)

The examine text for bundles including images is also bit weird. Please fix that with this patch: 
[patch.diff.txt](https://github.com/cmss13-devs/cmss13/files/11413852/patch.diff.txt) See https://git-scm.com/docs/git-apply for information on how to apply a patch (e.g. `git apply PATH_TO_PATCH_FILE`)
![image](https://user-images.githubusercontent.com/76988376/236656594-059f9b9d-c51b-447a-b223-29bc59d6b9a1.png)

2023-05-07 04:21 UTC, Drulikar commented on code/game/machinery/fax_machine.dm
> +		fax_paper_copy.info  += "<img src='tmp_photo.png' width='100%'/>"
```suggestion
		fax_paper_copy.info  += "<img src='tmp_photo.png' width='192'/>"
```
100% just looks way too stretched and requires too much height when there's a fax that's wide (it also shouldn't be stretching on a printed piece of paper). We'll double it.

![image](https://user-images.githubusercontent.com/76988376/236657392-7de91cb3-b695-42cb-b4ab-b3784a5c832a.png)

2023-05-07 04:21 UTC, Drulikar commented on code/game/machinery/fax_machine.dm
> +			fax_paper_copy.info  += "<img src='tmp_photo[content].png' width='100%'/>"
```suggestion
			fax_paper_copy.info  += "<img src='tmp_photo[content].png' width='192'/>"
```
100% just looks way too stretched and requires too much height when there's a fax that's wide (it also shouldn't be stretching on a printed piece of paper). We'll double it.

2023-05-07 04:49 UTC, Drulikar commented on code/modules/paperwork/paper.dm
get_examine_text is only called if you examine the paper, not use the paper. But we still need to browse_rsc any images for anyone that views this paper. See how paper_bundle.dm is handling its images.
![image](https://user-images.githubusercontent.com/76988376/236658172-057241e5-624f-4e70-8f1c-fdb8870e2afe.png)

1. Create a bundle of photos
2. Fax those photos to a department
3. Use (or examine) the paper that prints out without viewing the fax in chat.

2023-05-07 06:46 UTC, Drulikar approved these changes

2023-05-07 07:02 UTC, merged