CMB Black Market Investigation
cmss13-devs/cmss13 pull request #3223
Opened 2023-05-03 23:06 UTC by BeagleGaming1

# About the pull request

Ordering black market goods can either lower or increase a number. At 100, the CMB gets called to investigate and disable the black market.

# Explain why it's good for the game

People can purchase unlimited goods such as weapons or CLF crates. This causes req to have to at least pay attention to what they are buying, and to buy stuff other than clothing or weapons from other factions.

# Changelog

:cl:
add: Adds a CMB ERT to investigate the Black Market
add: Adds a [cmb] logo for papers
/:cl:

2023-05-04 17:50 UTC, Diegoflores31 commented
Heat amount should lower itself over time OR you should be able to pay up a "Tax" to lower the heat 
because if not it just invalidates completely the fact that the crates cost money

2023-05-04 20:29 UTC, sleepynecrons requested changes
the yellowish area needs cleaning up it's currently a complete mess. should be 4-6 colors at most
![9WCW19t](https://user-images.githubusercontent.com/106241650/236320235-0e18b073-02c0-4a28-b87d-910bfa5cf420.png)

make the blue when it's turned on a bit brighter
![bGNyKWP](https://user-images.githubusercontent.com/106241650/236322003-5a40bd9e-6b33-4510-a564-8eb91f07fdfc.png)
something like this where the bars in the front contrast more with the background

2023-05-07 18:41 UTC, sleepynecrons approved these changes
sprites look alright now approved 👍

2023-05-17 17:18 UTC, morrowwolf commented
Let's get this TM'd.

2023-05-17 18:47 UTC, morrowwolf commented
Spoke on discord but:

The arrival and dispatch messages seems to have not gone off and the objectives seems to have not been displayed.
Heat needs to be displayed easily to admins somewhere

Potentially out of scope:
CMB need to be set to their own faction
USCM can be in their faction_group though

That's all for now. Fix up at least the top two and we'll TM again.

2023-05-24 16:37 UTC, morrowwolf requested changes

2023-05-24 16:37 UTC, morrowwolf commented on code/datums/emergency_calls/inspection.dm
> +/datum/emergency_call/inspection_cmb/black_market/create_member(datum/mind/M, turf/override_spawn_loc)
one letter var "M"

2023-05-24 16:37 UTC, morrowwolf commented on code/game/objects/items/circuitboards/computer.dm
> +
if(user.action_busy)
to_chat(user, "I'm already doing something moron")
return

Paraphrased of course

2023-05-24 16:37 UTC, morrowwolf commented on code/game/supplyshuttle.dm
> +	for(var/obj/structure/machinery/computer/supplycomp/computer as anything in supply_controller.bound_supply_computer_list)
I don't believe we need the "as anything" here

2023-05-24 16:37 UTC, morrowwolf commented on code/game/supplyshuttle.dm
> +			black_market_lockout = TRUE
Why are we looping but not referencing the computer

2023-06-07 02:51 UTC, morrowwolf requested changes

2023-06-07 02:51 UTC, morrowwolf commented on code/game/supplyshuttle.dm
> +		black_market_lockout = TRUE
I'm pretty sure this proc is supposed to black market lockout all the currently connected computers. The issue with it before was not the for loop but that the for loop wasn't actually interacting with the bound computers it is meant to be locking but instead just resetting the one computer's lockout value.

2023-06-07 02:51 UTC, morrowwolf commented on code/game/supplyshuttle.dm
> +		black_market_lockout = TRUE
Oh and document the proc please (if I'm correct)

2023-06-26 01:58 UTC, closed without merging