A.C.I.D
cmss13-devs/cmss13 pull request #3229
Opened 2023-05-04 16:30 UTC by Diegoflores31

# About the pull request

You can now add Beakers up to 60 units into ACID harnesses .
Cooldown for A.C.I.D health check reduced from 20 seconds X injection amount to a flat 20 seconds

# Explain why it's good for the game
ACID harness have been in the shadows for too long . this PR aims to give it more relevance and encourage research to create more of them acomplishing the objective of turning research into something more than a drug factory and instead giving them the option to provide marines with reliable gear.

# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog
:cl:
balance: A.C.I.D vest can now hold beakers up to 60 units.
balance: Reduced cooldown betwen A.C.I.D health check to a flat 20 seconds.
fix: Added storage restrictions to A.C.I.D harness . now it can only hold  batteries and beakers as intended
/:cl:

2023-05-11 16:34 UTC, Huffie56 commented
if you could take a look into this issue while your at it... thanks
https://github.com/cmss13-devs/cmss13/issues/2082

2023-05-21 18:12 UTC, Diegoflores31 commented
> if you could take a look into this issue while your at it since your touching the ACID code thanks #2082

separate PR :)

2023-05-28 18:51 UTC, BroseidonMOO requested changes
Nothing has been posting regarding testing, please add proof of testing.

2023-06-01 00:09 UTC, Diegoflores31 commented
> Nothing has been posting regarding testing, please add proof of testing.

its been tested ingame . i dont think a video is necesary since it doesnt touch at all the functionality of the item just allows it to hold beakers.

2023-06-09 13:51 UTC, Drulikar requested changes

2023-06-09 13:51 UTC, Drulikar commented on code/modules/clothing/under/ties.dm
>  /obj/item/clothing/accessory/storage/black_vest/attackby(obj/item/W, mob/living/user)
Single letter var names.

2023-06-09 13:51 UTC, Drulikar commented on code/modules/reagents/chemistry_machinery/acid_harness.dm
> +	for(var/datum/reagent/R in acid_harness.container.reagents.reagent_list)
Single letter var names.

2023-06-09 13:51 UTC, Drulikar commented on code/modules/reagents/chemistry_machinery/acid_harness.dm
> +			to_chat(usr, SPAN_NOTICE("[possible_beaker] is too big for the [src]."))
This should result in a message like: "The beaker is too big for the **the** harness."
Either remove "the" or make it "\the"

2023-06-17 01:38 UTC, closed without merging