Adds interactions with potted plants and fire alarms.
cmss13-devs/cmss13 pull request #3236
Opened 2023-05-04 21:48 UTC by NewyearnewmeUwu

# About the pull request
Fire alarms now announce who pulled them, and potted plants can now have small items hidden in them (barring important things like the command tablet and ID cards.)

# Explain why it's good for the game
It's funny and fire alarms currently don't show who pulled them.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
add: You can now hide small items in potted plants.
add: Fire alarms now announce who activates/deactivates them.
/:cl:

2023-05-05 12:23 UTC, harryob requested changes

2023-05-05 12:23 UTC, harryob commented on code/game/objects/structures/flora.dm
> +	var/list/forbidden_items = list(/obj/item/device/cotablet, /obj/item/card/id) //For things that might affect someone/everyone's round if hidden.
use a typecache

2023-05-05 12:23 UTC, harryob commented on code/game/objects/structures/flora.dm
> +	for(var/i in forbidden_items)
use is_type_in_typecache

2023-05-06 08:46 UTC, CGosling commented
It may be worth adding an alert box which allows the user to confirm if they want the item stashed. This will cover two potential issues.

1)Players unaware of the feature stashing an item when clicking a plantpot, and then having no clue where its gone, contacting staff asking where it is,

2) Players unaware of the feature, accidentally clicking it and being given the option will be made aware of its existence, making it a fun little discovery down the road when it's far down the change log to be noticeable by new or returning players.

Finally, I would recommend adding a slight windup to stash and/or a publicly viewable text alert stating you see the person put something in or out the plantpot.

Overall, a good MR.

2023-05-06 17:32 UTC, fira requested changes

2023-05-06 17:32 UTC, fira commented on code/game/objects/structures/flora.dm
> +		prestashed_item = new(src)
pardon my old DM rustiness but my understanding is that this will create an /obj, without the actual subtype you want.

2023-05-14 10:15 UTC, harryob requested changes

2023-05-14 10:15 UTC, harryob commented on code/game/objects/structures/flora.dm
> +	var/static/blocked_atoms = list(/obj/item/device/cotablet, /obj/item/card/id) //For things that might affect someone/everyone's round if hidden.
```suggestion
	/// For things that might affect someone/everyone's round if hidden.
	var/static/blocked_atoms = list(/obj/item/device/cotablet, /obj/item/card/id)
```

2023-05-14 10:15 UTC, harryob commented on code/game/objects/structures/flora.dm
> +/obj/structure/flora/pottedplant/Initialize()
```suggestion
/obj/structure/flora/pottedplant/Initialize(mapload)
```

2023-05-14 10:15 UTC, harryob commented on code/game/objects/structures/flora.dm
> +		user.visible_message("[user] puts something in [src].", "You hide [stash] in [src].")
```suggestion
		user.visible_message("[user] puts something in [src].", "You hide [stash] in [src].")
		return
```

2023-05-14 10:15 UTC, harryob commented on code/game/objects/structures/flora.dm
> +		to_chat(user, SPAN_WARNING("[stash] is too big to fit into [src]!"))
```suggestion
	to_chat(user, SPAN_WARNING("[stash] is too big to fit into [src]!"))
```

2023-05-24 22:56 UTC, harryob commented on code/game/objects/structures/flora.dm
> +	var/stashed_item
what happen on Destroy() and ex_act and all that fun stuff

2023-05-27 01:28 UTC, morrowwolf approved these changes

2023-05-27 01:36 UTC, merged