soloCup
cmss13-devs/cmss13 pull request #325
Opened 2022-05-19 00:59 UTC by PhantomEpicness

## About The Pull Request

Plastic cups that can be crushed

![Screenshot_1](https://user-images.githubusercontent.com/42422230/169179867-66384571-2a53-4c06-80a2-ad84005f1791.png)

## Why It's Good For The Game

New disposable cup yay. Requested by thwomper

## Changelog

:cl: TotalEpicness
add: Added new plastic cups! Credit to purplecloud for the sprites.
/:cl:

2022-05-19 01:23 UTC, Segrain requested changes

2022-05-19 01:23 UTC, Segrain commented on code/game/objects/items/reagent_containers/food/drinks.dm
> +/obj/item/crushed_cup
```suggestion
		new /obj/item/trash/crushed_cup(user.loc)
		qdel(src)

/obj/item/trash/crushed_cup
```
Can also move crushed one to `trash.dm`.

2022-05-19 01:23 UTC, Segrain commented on code/game/objects/items/reagent_containers/food/drinks.dm
> +		visible_message(SPAN_WARNING("[user] crushes the cup!"))
```suggestion
		user.visible_message(SPAN_WARNING("[user] crushes \the [src]!"), SPAN_WARNING("You crush \the [src]!"))
```

2022-05-19 07:35 UTC, stanalbatross requested changes

2022-05-19 07:35 UTC, stanalbatross commented on code/game/objects/items/reagent_containers/food/drinks.dm
> +			to_chat(user,SPAN_WARNING("\The contents of \the [src] spill!"))
```suggestion
			to_chat(user,SPAN_WARNING("The contents of \the [src] spill!"))
```
you do not need a backslash unless it's before a thing

2022-05-19 14:48 UTC, c4xmaniac commented
I love you, red solo cup, I lift you up, proceed to party, proceed to party. I’ve seen you in blue and I’ve seen you in yellow, but only you red will do for this fellow. You are the abbot to my Costello, and I’m hoping to get - lucky. Red solo cup, I lift you up

2022-05-19 21:01 UTC, MusselMain commented
Can't wait to get me a red Solo cup full of death juice so I can get the lethal sip after FOB falls and I'm abandoned at the office

2022-06-03 17:25 UTC, PhantomEpicness commented
ready

2022-06-04 15:55 UTC, Geevies requested changes

2022-06-04 15:55 UTC, Geevies commented on code/game/objects/items/reagent_containers/food/drinks.dm
> +	name = "Plastic Cup"
```suggestion
	name = "plastic cup"
```

2022-06-04 15:55 UTC, Geevies commented on code/game/objects/items/reagent_containers/food/drinks.dm
> +	attack_verb = list("bludgeoned", "whacked","slapped")
```suggestion
	attack_verb = list("bludgeoned", "whacked", "slapped")
```

2022-06-04 15:55 UTC, Geevies commented on code/game/objects/items/reagent_containers/food/drinks.dm
> +			to_chat(user,SPAN_WARNING("The contents of \the [src] spill!"))
```suggestion
			to_chat(user, SPAN_WARNING("The contents of \the [src] spill!"))
```

2022-06-04 15:55 UTC, Geevies commented on code/game/objects/items/reagent_containers/food/drinks.dm
> +	name = "Crushed cup"
```suggestion
	name = "crushed cup"
```

2022-06-04 15:55 UTC, Geevies commented on code/game/objects/items/reagent_containers/food/drinks.dm
> +	attack_verb = list("bludgeoned", "whacked","slaped")
```suggestion
	attack_verb = list("bludgeoned", "whacked", "slapped")
```

2022-06-17 19:47 UTC, stanalbatross commented
@Geevies please remember to draft when you request changes

2022-06-18 06:35 UTC, stanalbatross commented on code/game/objects/items/reagent_containers/food/drinks.dm
> +		new /obj/item/trash/crushed_cup(user.loc)
should this not go into your hand?

2022-07-04 18:55 UTC, Agameofscones reviewed
sprites LGTM

2022-07-12 07:16 UTC, stanalbatross requested changes

2022-07-12 07:16 UTC, stanalbatross commented on code/game/objects/items/reagent_containers/food/drinks.dm
> +		qdel(src)
```suggestion
		qdel(src)
		var/obj/item/trash/crushed_cup/C = new /obj/item/trash/crushed_cup(user)
		user.equip_to_slot_if_possible(C, (user.hand ? WEAR_L_HAND : WEAR_R_HAND))
```

2022-07-12 07:19 UTC, stanalbatross approved these changes

2022-07-12 07:19 UTC, merged