The Hazmat Joe
cmss13-devs/cmss13 pull request #3259
Opened 2023-05-07 13:02 UTC by QuickLode

# About the pull request
This pull request resprites the entire Working Joe from toes to head. It also gives two additional uniforms which are meant for hazardous use, and this PR should act as a foundation for future implementation of the Hazmat Joe into CM's gameplay. Additionally, I may just set this to draft and let it be reviewed while I work on the actual implementation.

They are complete with distinctive loadouts, which focus more on hazardous situations, repair, and firefighting. Though may tweak things depending on how its implemented.

# Explain why it's good for the game
This adds a fan favorite variation of your inexpensive, reliable friend! You've seen him in quite a few places, and now he's coming to CM!

Also, the resprite of the Joe fixes up some minor sprite issues that were encountered on previous models.

More content, more roleplay possibilities! ARES! Get me some Joes to put that reactor fire out ASAP!
# Testing Photographs and Procedure
https://cdn.discordapp.com/attachments/490668342357786645/1104748917398175795/image.png
https://media.discordapp.net/attachments/490668342357786645/1105643891107049572/image.png
Ran several tests and they went well.

# Changelog
:cl:QuickLoad,Frans_Feiffer,nauticall
add: Adds The Hazmat Joe with two minor variations. This is a Working Joe equipped to handle hazardous situations, dangerous repairs and firefighting! They are complete with their own gear, tasks, job and purpose. Forget the trashbag, get that wall fixed before we get spaced!
imageadd: Adds a new Working Joe model made by Frans Feiffer!
imageadd: Adds two variations of the Working Joe, aka the Hazmat Joe. Complete with accessories! Beautiful sprites by Frans Feiffer!
add: Android Maintenance Stations / Synthetic Repair Stations will remove shrapnel & fix organ damage. Working Joes no longer have knives, and should report to the stations for repair. Gigantic thanks to nauticall for her work on this!!
imagedel: Removes(replaces) the old Working Joe model.
add: Working Joes receive some basic equipment, and are slightly resilient to disarms.
add: Working Joes will start at 3, with a maximum of 6 depending on population.
add: Joes can access a Synthetic vendor to replace their uniform if it is damaged.
fix: Minor changes to PO Uniform.
/:cl:

2023-05-07 14:06 UTC, harryob approved these changes
otherwise looks good - there's the nitpick of the arguments being mob/living/carbon/human/H but that's just because you're using the inherited ones, so no big deal

2023-05-07 14:06 UTC, harryob commented on code/modules/gear_presets/synths.dm
> +	access = get_all_accesses()
you're calling parent here, any /datum/equipment_preset/synth/New() already gets all access, so this is redundant

2023-05-15 03:49 UTC, Diegoflores31 commented
![image](https://github.com/cmss13-devs/cmss13/assets/47069269/3fbafa79-2119-4d8f-b68d-676258f246db)
this should probably go into a different PR . :atom:

2023-05-18 22:44 UTC, Diegoflores31 commented on code/modules/clothing/gloves/marine_gloves.dm
> +	flags_inventory = CANTSTRIP
Dont do CANTSTRIP on limbs that can be delimbed

2023-05-23 23:31 UTC, harryob requested changes
job options stuff needs changing post-#3354

2023-06-09 20:12 UTC, BeagleGaming1 requested changes

2023-06-09 20:12 UTC, BeagleGaming1 commented on code/game/jobs/job/civilians/support/working_joe.dm
>  	spawn_positions = 3
This should be the same as `total_positions`

2023-06-09 20:12 UTC, BeagleGaming1 commented on code/game/jobs/job/civilians/support/working_joe.dm
> +	scaled = 1
You need to add the scaling formula and proc

2023-06-09 20:12 UTC, BeagleGaming1 commented on code/game/jobs/job/civilians/support/working_joe.dm
> +/datum/job/civilian/working_joe/generate_entry_message(mob/living/carbon/human/H)
You could add wiki links to these entry messages

2023-06-10 03:10 UTC, BeagleGaming1 requested changes

2023-06-10 03:10 UTC, BeagleGaming1 commented on code/modules/gear_presets/synths.dm
> +	languages = list(LANGUAGE_ENGLISH, LANGUAGE_APOLLO, LANGUAGE_RUSSIAN, LANGUAGE_JAPANESE, LANGUAGE_GERMAN, LANGUAGE_SPANISH, LANGUAGE_CHINESE)
Isn't most of this inherited from `/datum/equipment_preset/synth/working_joe`?

2023-06-10 03:10 UTC, BeagleGaming1 commented on code/__DEFINES/job.dm
> +#define JOB_HAZMAT_JOE "Hazmat Joe"
this define is unused

2023-06-12 01:33 UTC, BeagleGaming1 requested changes

2023-06-12 01:33 UTC, BeagleGaming1 commented on code/game/jobs/job/civilians/support/working_joe.dm
> +		. = {"You are a <a href='"+URL_WIKI_WJ_GUIDE+"'> Working Joe.</a> You are held to a higher standard and are required to obey not only the Server Rules but Marine Law, Roleplay Expectations and Synt
```suggestion
		. = {"You are a <a href='"+URL_WIKI_WJ_GUIDE+"'>Working Joe.</a> You are held to a higher standard and are required to obey not only the Server Rules but Marine Law, Roleplay Expectations and Synthetic Rules.  Your primary task is to maintain the cleanliness of the ship, putting things in their proper place. Alternatively, your primary task may be to assist with manual labor in limited capacity, or clerical duties. Your capacities are limited, but you have all the equipment you need, and the central AI has a plan! Stay in character at all times. Use the APOLLO link to communicate with your uplink!"}
```

2023-06-12 01:33 UTC, BeagleGaming1 commented on code/game/jobs/job/civilians/support/working_joe.dm
> +		. = {"You are a <a href='"+URL_WIKI_WJ_GUIDE+"'> Working Joe</a> for Hazardous Environments!  You are held to a higher standard and are required to obey not only the Server Rules but Marine Law, Ro
```suggestion
		. = {"You are a <a href='"+URL_WIKI_WJ_GUIDE+"'>Working Joe</a> for Hazardous Environments!  You are held to a higher standard and are required to obey not only the Server Rules but Marine Law, Roleplay Expectations and Synthetic Rules.  You are a variant of the Working Joe built for tougher environments and fulfill the specific duty of dangerous repairs or maintenance. Your primary task is to maintain the reactor, SMES and AI Core. Your secondary task is to respond to hazardous environments, such as an atmospheric breach or biohazard spill, and assist with repairs when ordered to by either an AI Mainframe, or a Commisioned Officer.  You should not be seen outside of emergencies besides in Engineering and the AI Core! Stay in character at all times. Use the APOLLO link to communicate with your uplink!"}
```

2023-06-12 01:33 UTC, BeagleGaming1 commented on code/game/jobs/job/civilians/support/working_joe.dm
>  	flags_whitelist = WHITELIST_JOE
```suggestion
	flags_whitelist = WHITELIST_JOE
	gear_preset = /datum/equipment_preset/synth/working_joe
```

2023-06-12 01:33 UTC, BeagleGaming1 commented on code/game/jobs/job/civilians/support/working_joe.dm
>  	flags_whitelist = WHITELIST_JOE
You need a defualt gear preset otherwise it goes with default colonist human

2023-06-12 01:55 UTC, BeagleGaming1 requested changes

2023-06-12 01:55 UTC, BeagleGaming1 commented on code/modules/gear_presets/synths.dm
> +	var/choice = rand(1,10)
![image](https://github.com/cmss13-devs/cmss13/assets/56142455/0fedf712-4181-451d-8ff1-44ffe8819ed4)
Why have 1-10 if theres only 2.
Why have so many different if all is the same except for the uniform

2023-06-12 02:21 UTC, BeagleGaming1 commented on code/modules/gear_presets/synths.dm
> +	switch(choice)
This needs to be before the other equips or it fails to equip it. 
![image](https://github.com/cmss13-devs/cmss13/assets/56142455/ac59b40a-08d8-45bc-9625-c0dc288657d9)

2023-06-12 03:06 UTC, BeagleGaming1 requested changes

2023-06-12 03:06 UTC, BeagleGaming1 commented on code/modules/clothing/under/marine_uniform.dm
> +	armor_internaldamage = CLOTHING_ARMOR_MEDIUMLOW
a lot of these vars are inherited and unneeded

2023-06-16 02:25 UTC, BeagleGaming1 requested changes

2023-06-16 02:25 UTC, BeagleGaming1 commented on code/game/machinery/rechargestation.dm
> +				for(var/obj/limb/L in humanoid_occupant.limbs)
single letter var

2023-06-16 02:25 UTC, BeagleGaming1 commented on code/game/machinery/rechargestation.dm
> +						for(var/obj/item/I in L.implants)
single letter var

2023-06-16 02:25 UTC, BeagleGaming1 commented on code/game/machinery/rechargestation.dm
> +				for(var/datum/internal_organ/I in humanoid_occupant.internal_organs)
single letter var

2023-06-16 02:25 UTC, BeagleGaming1 commented on code/game/machinery/rechargestation.dm
> +					if(I.robotic == ORGAN_ASSISTED||I.robotic == ORGAN_ROBOT) //this time the machine can *only* fix robotic organs
```suggestion
					if(I.robotic == ORGAN_ASSISTED || I.robotic == ORGAN_ROBOT) //this time the machine can *only* fix robotic organs
```

2023-06-19 00:41 UTC, merged