Throw Delay
cmss13-devs/cmss13 pull request #3284
Opened 2023-05-10 02:32 UTC by morrowwolf

# About the pull request

This adds a 0.25 second throw delay.

# Explain why it's good for the game

People throwing a knife 20 times in less than a second is not intentional gameplay.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl: Morrow
balance: Adds a throw delay of 0.25 seconds
/:cl:

2023-05-10 03:48 UTC, Drulikar approved these changes
Tested and works. I can no longer instantly kill a runner this way (though its still awfully fast).

Though in testing this, I managed to get the msg_admin_attack message to runtime if you throw a weapon causing the xeno to gib. This should address that (living_defense.dm in `/mob/living/hitby(atom/movable/AM)`):
```
			if(!istype(src,/mob/living/simple_animal/mouse))
				if(src.loc) // If we got gibbed by this attack, we have no loc
					msg_admin_attack("[key_name(src)] was hit by a [O], thrown by [key_name(M)] in [get_area(src)] ([src.loc.x],[src.loc.y],[src.loc.z]).", src.loc.x, src.loc.y, src.loc.z)
				else
					msg_admin_attack("[key_name(src)] was hit by a [O], thrown by [key_name(M)] in [get_area(M)] ([M.loc.x],[M.loc.y],[M.loc.z]).", M.loc.x, M.loc.y, M.loc.z)
```

2023-05-11 05:56 UTC, Zonespace27 requested changes

2023-05-11 05:56 UTC, Zonespace27 commented on code/__DEFINES/conflict.dm
> +#define THROW_DELAY 0.25 SECONDS
```suggestion
#define THROW_DELAY (0.25 SECONDS)
```
This is due to PEMDAS fuckery, and how this is actually `0.25 * 10`

2023-05-11 05:56 UTC, Zonespace27 commented on code/modules/mob/mob_defines.dm
> +	var/throw_delay = 0
we have the COOLDOWN_ macros

2023-05-12 03:45 UTC, Drulikar commented
Disregard my comment about thrown weapon runtimes, it will instead be addressed in #3301

2023-05-13 20:17 UTC, harryob approved these changes

2023-05-13 20:47 UTC, merged