Breaching charge
cmss13-devs/cmss13 pull request #33
Opened 2022-04-15 18:21 UTC by Diegoflores31

## Changelog

:cl: Diegoflores31

rscadd: Added M1 breaching Charge

rscadd: Added Breaching charge crate to req via ASRS and vendor

rscadd: Added Breaching charge to SL and Engineer vendors for 7 and 5 points each

/:cl:

## Details
The M1 breaching charge is an assault tool meant to be used for quick entry and damaging the enemies sitting in the other side of the wall while keeping the operator safe from the blast.

The breaching charge has a considerable lower explosion timer and shoots shrapnell to the other side of the wall on a 60 degree angle causing considerable damage to targets with multiple shrapnell.

It cannot be attached into mobs / objects / crates / machines / vendors and deals a very small explosive blast compared to the normal C4 but has a smaller fuse 

![image](/uploads/eeb7d09cc07f5f174b3c230604189bcd/image.png)

![-_LV624_2022-03-14_01-38-30__online-video-cutter.com_](/uploads/62399f52bb6620620b2a703d852aab65/-_LV624_2022-03-14_01-38-30__online-video-cutter.com_.mp4)

## Related Issues

Closes

2022-04-15 18:27 UTC, realforest2001 commented
You'll need to update your changelog to the new format.

2022-04-16 19:15 UTC, Agameofscones requested changes
you've been cursed by html/lengord_pouches.yml. You need to rebase onto the latest copy of master and discard / delete that file. Otherwise the sprites look good to me.

2022-04-17 01:15 UTC, Diegoflores31 reviewed
file deleted . i guess im free from the curse now

2022-04-17 19:40 UTC, Diegoflores31 reviewed
.

2022-05-07 12:26 UTC, stanalbatross commented
initial feedback so far seems to be that they take too long to detonate and are not useful enough. 

also fill out a more detailed changelog

2022-05-08 20:20 UTC, Katskan commented
I never saw anyone using them. Possibly having a faster plant time would give them an edge, most people I saw were just talking about them as "worse C4"

2022-05-08 20:28 UTC, c4xmaniac commented
I didn’t play much during the TM, but I never heard anyone using them and like Katskan said it seems to just be a worse C4. This being in combination with an intended master key nerf going in along side this MR, the plant time for the breaching charges should be decreased dramatically along with its point cost. I’m pretty sure I can buy c4 for the same price and it does basically the same thing with the addition of being able to blow tunnels.

2022-05-08 20:39 UTC, somepersondunno commented
Make breaching charges cost 3 and regular Plastic Explosives cost 5 and this will be a lot more viable. I had a lot of fun playing engineer and using these to destroy walls and, as the name implies, BREACH into enemy defenses. Additionally, making them take a little less time to set up would be nice, but overall a lot of fun IMO.

2022-05-08 22:30 UTC, IngloriouslyBad commented
Biggest problem with C4 and the new breaching charge is the set up times for both are just too long. Xenos aren't going to be surprised ever by C4 or breaching charges when you have to stand still ominously against a wall with a big red ring above your head, yelling C4 C4 C4. Xenos point at the wall before you're even done placing and get out of dodge or set up to counter you with the time it takes to set up and then go off. And good luck using either to widen a pre existing gap, a xeno will walk around the corner and push you 1 tile, stun you through the wall like you see with frontline burrowers, or just kill you in the case of T3s who turn the corner and tear you a new one, and retreat back inside.

2022-05-12 02:28 UTC, Sargeantmuffinman commented
Just from arm chair thoughts, reading other comments and me testing this thing a couple of times in the T-Dome.
Too long to plant, xenos knowing exactly what's going to happen due to 2 red circles over a marine and cost.

Frankly if you addressed the planting time and the cost, it'd make it more worth while.
My two cents.
Cent 1: Planting time is 2 seconds.
Cent 2: Cost is either reduced or the breaching charge comes in stacks of 2 or 3 so you can plant multiple.

2022-05-18 03:58 UTC, Diegoflores31 commented
added faster planting time
added a new sharpnel type with a more appealing view than the standard
fixed some issues with the explosion eating a good amount of shrapnell
reduced amount of shrapnel but increased the damage
Adjusted Shrapnel spawn turf to avoid collitions with the wall

2022-06-17 17:43 UTC, Nanu308 commented
Balance lgtm, might need supply cost tweaks later down the line but we'll see.

2022-06-17 18:18 UTC, Geevies approved these changes

2022-06-17 18:18 UTC, Geevies commented on code/game/objects/items/explosives/plastic.dm
> +	var/breachable = list(/obj/structure/window, /turf/closed, /obj/structure/machinery/door, /obj/structure/mineral_door)
```suggestion
	var/list/breachable = list(/obj/structure/window, /turf/closed, /obj/structure/machinery/door, /obj/structure/mineral_door)
```

2022-06-17 18:18 UTC, Geevies commented on code/datums/supply_packs/weapons.dm
> +	cost = RO_PRICE_NORMAL
```suggestion
					/obj/item/explosive/plastic/breaching_charge
	)
	cost = RO_PRICE_NORMAL
```

2022-06-18 04:56 UTC, merged