Adds a tracker for how many hugs a player facehugger has
cmss13-devs/cmss13 pull request #3311
Opened 2023-05-13 03:18 UTC by BeagleGaming1

# About the pull request

Adds total facehugs / facehugs to next age to status panel

(Note: I was unable to test this locally due to player_stats just not existing for me)
# Explain why it's good for the game

Better than them needing to manually record it

# Changelog

:cl:
qol: lets player facehuggers see their lifetime hugs on the status panel
/:cl:

2023-05-14 10:07 UTC, harryob requested changes

2023-05-14 10:07 UTC, harryob commented on code/modules/mob/living/carbon/xenomorph/castes/Facehugger.dm
> +			if(FACEHUG_TIER_3 to FACEHUG_TIER_4) // 100 - 999
let the people control click to figure out what the value of the define is, don't include it as a comment - they're defines so we can update them without worrying about it being outdated in other places

2023-05-14 15:47 UTC, Watermelon914 requested changes
this should really not be a verb. Include it in the statpanel if you want

2023-05-16 09:17 UTC, harryob approved these changes
update changelog + pr name

2023-05-16 11:02 UTC, Watermelon914 requested changes

2023-05-16 11:02 UTC, Watermelon914 commented on code/modules/mob/living/carbon/xenomorph/castes/Facehugger.dm
> +	var/total_facehugs = 0
You don't ever set this variable anywhere.

2023-05-20 12:34 UTC, merged