added drawing functionality to tactical maps
cmss13-devs/cmss13 pull request #3363
Opened 2023-05-19 09:27 UTC by Cthulhu80

# About the pull request

Added a drawing feature to tactical maps, this is not done by any means and there is still plenty to do. Javascript and TGUI functionality is mostly done however there are a few bugs and the access and retrieval of the images need to be heavily optimized as the current implementation was just getting the javascript part working. Once everything is correctly implemented cic should be able to announce the tactical map with the drawings to the marines.

# Explain why it's good for the game

drawing is fun

# Testing Photographs and Procedure

<img width="361" alt="drawingfunc" src="https://github.com/cmss13-devs/cmss13/assets/122310258/93621d1d-41c3-4e82-b81f-4a3b0450cd4e">

# Changelog

:cl:
add: added drawing functionality to tactical maps
/:cl:

2023-05-19 14:46 UTC, fira commented
drawing not sync'd across maps right?

i have minor concerns regarding map export being exploitable by sending any image if it's uploaded back from tgui. it's pretty cool if it can be done at all though

2023-05-19 18:21 UTC, FreetoZ commented
> drawing not sync'd across maps right?
> 
> i have minor concerns regarding map export being exploitable by sending any image if it's uploaded back from tgui. it's pretty cool if it can be done at all though

Toolbar selection is synced but the map itself is not, so if two users opened up the map and started drawing they would not be able to see the other's map but they would share the color selection which of course would cause problems although this is easily fixable.

2023-05-20 03:45 UTC, FreetoZ commented
I'm going to be busy for the next week so I won't be able to work on any requested changes until I get back. Ideally, it would be great if someone who is knowledgeable in JS and React/Inferno stuff can take a thorough look before I work on optimizing the access and retrieval of the pngs. Thanks.

2023-07-03 18:03 UTC, mullenpaul requested changes
Some parts are looking good. I think it could be greatly simplified if, instead of rebuilding the image on update - to change global state for the lines reference. This would allow the end user to get the line data, have their browser redraw it based upon the global state, and we wouldn't have to keep resending out images.

I feel that doing it this way (assuming recaching isnt an issue) - will result in a new image being sent out via the resource transit system. This will result in a delay between the map being generated and sent to the user, they will have a blank screen for a while.

I might be wrong in my thoughts - but this approach could alleviate the concerns the maintainer team have regarding uploading and forced distribution of images. All it takes is for one person to start doing it and we have a big problem on our hands.

2023-07-04 03:46 UTC, Cthulhu80 commented on code/controllers/subsystem/minimap.dm
> +			toolbar_updated_selection = "clear"
forgot to remove that comment, was for something else.

2023-07-04 03:54 UTC, Cthulhu80 commented on code/controllers/subsystem/minimap.dm
> +		img_ref = icon2html(map_icon, user, sourceonly = TRUE)
i'll ask around

2023-07-04 03:55 UTC, Cthulhu80 commented on tgui/packages/tgui/interfaces/CanvasLayer.js
> +    this.lineStack = [];
Sounds like a great idea, i'll give it a go.

2023-07-04 04:19 UTC, Cthulhu80 commented on tgui/packages/tgui/interfaces/TacticalMap.tsx
> -        <ByondUi
not so simple with byondui.

2023-07-17 08:37 UTC, Cthulhu80 commented on tgui/packages/tgui/interfaces/CanvasLayer.js
> +    this.lineStack = [];
Ended up just going the SVG route, sorry about the delay I was busy with other stuff.

2023-07-28 01:21 UTC, closed without merging