The Weave Resurgence
cmss13-devs/cmss13 pull request #3375
Opened 2023-05-19 21:35 UTC by realforest2001

# About the pull request

# Explain why it's good for the game

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
add: Stuff
/:cl:

2023-05-23 22:59 UTC, harryob requested changes

2023-05-23 22:59 UTC, harryob commented on code/__DEFINES/chemistry.dm
> +#define PLASMA_WEAVE_EXALTED	"weaveplasmaex"
```suggestion
#define PLASMA_WEAVE	"weaveplasma"
#define PLASMA_WEAVE_EXALTED "weaveplasmaex"
```

2023-05-23 22:59 UTC, harryob commented on code/__DEFINES/chemistry.dm
> +#define PROPERTY_WEAVING			"weaving" //Enslaves to The Weave
```suggestion
#define PROPERTY_WEAVING	"weaving" //Enslaves to The Weave
```

2023-05-23 22:59 UTC, harryob commented on code/__DEFINES/mobs.dm
> +#define WEAVE_NORMAL	"Normal"
```suggestion
#define WEAVE_NORMAL "Normal"
```

2023-05-23 22:59 UTC, harryob commented on code/datums/diseases/weave_mind.dm
> +				src.cure()
```suggestion
				cure()
```

2023-05-23 22:59 UTC, harryob commented on code/game/objects/items/weapons/blades.dm
> +	else ..()
```suggestion
	else 
		return ..()
```

2023-05-23 22:59 UTC, harryob commented on code/game/objects/items/weapons/blades.dm
> +/obj/item/weapon/weaveblade/attack(mob/living/target as mob, mob/living/carbon/human/user as mob)
```suggestion
/obj/item/weapon/weaveblade/attack(mob/living/target, mob/living/carbon/human/user)
```

2023-05-23 22:59 UTC, harryob commented on code/game/objects/items/weapons/blades.dm
> +		user.visible_message(SPAN_BOLDWARNING("[user] is repelled from \the [src] by the force of The Weave!"), SPAN_BOLDWARNING("The Weave repels your hand away from \the [src]! You cannot touch it!"))
```suggestion
		user.visible_message(SPAN_BOLDWARNING("[user] is repelled from [src] by the force of The Weave!"), SPAN_BOLDWARNING("The Weave repels your hand away from [src]! You cannot touch it!"))
```

2023-05-23 22:59 UTC, harryob commented on code/game/objects/items/weapons/blades.dm
> +		user.visible_message(SPAN_BOLDWARNING("[user] is repelled from \the [src] by the force of The Weave!"), SPAN_BOLDWARNING("The Weave repels your hand away from \the [src]! You cannot touch it!"))
```suggestion
		user.visible_message(SPAN_BOLDWARNING("[user] is repelled from [src] by the force of The Weave!"), SPAN_BOLDWARNING("The Weave repels your hand away from [src]! You cannot touch it!"))
```

2023-05-23 22:59 UTC, harryob commented on code/modules/gear_presets/other.dm
> +/datum/equipment_preset/other/weave_cultist
```suggestion
/datum/equipment_preset/other/weave_cultist
```

2023-05-23 22:59 UTC, harryob commented on code/modules/mob/living/carbon/human/human_abilities.dm
> +/datum/action/human_action/activable/cult/weave/speak_hivemind
```suggestion
//Weave
/datum/action/human_action/activable/cult/weave/speak_hivemind
```

2023-05-23 22:59 UTC, harryob commented on code/modules/mob/living/carbon/human/human_abilities.dm
> +		return FALSE
```suggestion
		return TRUE

	to_chat(owner, SPAN_XENOWARNING("The Weave is not strong enough here to do that!"))
	return FALSE
```

2023-05-23 22:59 UTC, harryob commented on code/modules/mob/living/carbon/human/human_abilities.dm
> +			return TRUE
```suggestion
			return FALSE

		cultist.blood_volume -= 100
		nexus.weave_energy += 100
		cultist.visible_message(SPAN_XENONOTICE("[cultist] exudes energy back into The Weave!"), SPAN_XENONOTICE("You release some of your energy into The Weave!"))
		enter_cooldown(cooldown)
		return TRUE
```

2023-05-23 22:59 UTC, harryob commented on code/modules/mob/living/carbon/human/human_abilities.dm
> +	if (do_after(cultist, 10 SECONDS, INTERRUPT_ALL | BEHAVIOR_IMMOBILE, BUSY_ICON_FRIENDLY))
early return

2023-05-23 22:59 UTC, harryob commented on code/modules/mob/living/carbon/human/human_abilities.dm
> +	if (do_after(cultist, 10 SECONDS, INTERRUPT_ALL | BEHAVIOR_IMMOBILE, BUSY_ICON_MEDICAL))
early return

2023-05-23 22:59 UTC, harryob commented on code/modules/mob/living/carbon/human/human_abilities.dm
> +		to_chat(owner, SPAN_WARNING("Error: Weave Hive not found. Ping forest2001."))
glare

2023-05-23 22:59 UTC, harryob commented on code/modules/mob/living/carbon/human/human_abilities.dm
> +		to_chat(owner, SPAN_WARNING("Error: Weave Hive not found. Ping forest2001."))
glare

2023-05-23 22:59 UTC, harryob commented on code/modules/mob/living/carbon/human/human_abilities.dm
> +			return TRUE
```suggestion
		cultist.visible_message(SPAN_XENONOTICE("[cultist] is wrapped in energies from The Weave as their wounds close!"), SPAN_XENONOTICE("Your wounds close as The Weave wraps around you!"))
		cultist.apply_damage(-20, BRUTE)
		cultist.apply_damage(-20, BURN)
		enter_cooldown(cooldown)
		return TRUE
```

2023-05-23 22:59 UTC, harryob commented on code/modules/mob/living/carbon/xenomorph/abilities/TheWeave/prime_powers.dm
> +	if	(!ishuman(human) || !human.allow_gun_usage)
```suggestion
	if(!ishuman(human) || !human.allow_gun_usage)
```

2023-05-23 22:59 UTC, harryob commented on code/modules/mob/living/carbon/xenomorph/abilities/TheWeave/prime_powers.dm
> +	if (do_after(self, activation_delay, INTERRUPT_ALL | BEHAVIOR_IMMOBILE, BUSY_ICON_HOSTILE))
early return

2023-05-23 22:59 UTC, harryob commented on code/modules/mob/living/carbon/xenomorph/abilities/TheWeave/prime_powers.dm
> +	self.frozen = 0
if this is a boolean it should be using TRUE/FALSE

2023-05-23 22:59 UTC, harryob commented on code/modules/mob/living/carbon/xenomorph/abilities/TheWeave/prime_powers.dm
> +				to_chat(target, SPAN_XENOBOLDNOTICE("You feel a ripple as energies pass over you!"))
```suggestion
				to_chat(target, SPAN_XENOBOLDNOTICE("You have been regenerated by the The Weave!"))
				continue
			
			to_chat(target, SPAN_XENOBOLDNOTICE("You feel a ripple as energies pass over you!"))
```

2023-05-23 22:59 UTC, harryob commented on code/modules/mob/living/carbon/xenomorph/abilities/TheWeave/prime_powers.dm
> +		self.visible_message(SPAN_XENOWARNING("[self] decides not to release their energy."), SPAN_XENOWARNING("You decide not to release your energy."))
early return this instead

2023-05-23 22:59 UTC, harryob commented on code/modules/mob/living/carbon/xenomorph/abilities/TheWeave/weave_powers.dm
> +		self.visible_message(SPAN_XENOWARNING("[self] decides not to release their energy."), SPAN_XENOWARNING("You decide not to release your energy."))
early return this instead

2023-05-23 22:59 UTC, harryob commented on code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
> +		return TRUE
```suggestion

	weave_energy -= cost
	return TRUE
```

2023-05-23 22:59 UTC, harryob commented on code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
> +		return TRUE
```suggestion

	return TRUE
```

2023-06-03 10:56 UTC, Watermelon914 requested changes
Needs a proper description, justification and changelog.

2024-08-04 22:07 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-08-05 17:33 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-10-17 03:10 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-11-27 20:20 UTC, closed without merging