Xeno directional attack no longer friendly fires their own resin walls and doors
cmss13-devs/cmss13 pull request #3386
Opened 2023-05-21 05:22 UTC by Hopekz

![dreamseeker_M0U60T6yV6](https://github.com/cmss13-devs/cmss13/assets/24533979/288f233d-58ae-4afd-835d-3deefebd2f92)

:cl: Hopek
fix: Xeno Directional attack no longer friendly fires their own walls and doors. You need to actually click on the sprite if you mean to destroy it
/:cl:

2023-05-21 20:36 UTC, Segrain commented
> their own walls and doors

What if it is another hive's wall?

2023-05-22 04:12 UTC, Hopekz commented
> > their own walls and doors
> 
> What if it is another hive's wall?

They can click on the sprite like in the example gif

2023-05-22 22:12 UTC, harryob requested changes

2023-05-22 22:12 UTC, harryob commented on code/_onclick/xeno.dm
> +				return FALSE
```suggestion
		if (T && ignores_resin) // Will not target resin walls and doors if this is set to true. This is normally only set to true through a directional attack.
			if(istype(T, /obj/structure/mineral_door/resin))
				var/obj/structure/mineral_door/resin/attacked_door = T
				if(hivenumber == attacked_door.hivenumber)
					return FALSE
			if(istype(T, /turf/closed/wall/resin))
				var/turf/closed/wall/resin/attacked_wall = T
				if(hivenumber == attacked_wall.hivenumber)
					return FALSE
```

2023-05-23 00:57 UTC, merged