Lore Accurate Blowtorches
cmss13-devs/cmss13 pull request #339
Opened 2022-05-21 20:01 UTC by Geevies

## About The Pull Request

Makes blowtorches with welding screens not cause eye damage.

## Why It's Good For The Game

In the movie Aliens, the marines use blowtorches to seal off bulkheads. They don't need welding goggles or technician helmets with shields, because their blowtorches have welding shields.

## Changelog

:cl:
balance: Blowtorches with welding shields no longer cause eye damage.
/:cl:

2022-05-21 20:03 UTC, Shad0vvs commented
Get a sprite for it possibly?

2022-05-21 20:12 UTC, Sargeantmuffinman commented
> Get a sprite for it possibly?

Already came with it WAAAAY BACK since 2017 from wiki image records.

2022-05-21 20:55 UTC, Waseemq1235 commented
> Get a sprite for it possibly?

isn't that part that flips up when you activate the torch a welding screen?

2022-05-21 22:05 UTC, PurpleCIoud commented
Can the welding helmet stay if this gets added?

2022-05-21 23:41 UTC, MusselMain commented
> Can the welding helmet stay if this gets added?

If you re-read what they say, they mention: "Makes Blowtorches with WELDING SCREENS not cause eye damage". I'm unsure if they're going to make these variants rarer, but I assume that if they were making all welders not cause eye damage they wouldn't mention the welding screens part, maybe I'm wrong though.

2022-05-22 01:44 UTC, PhantomEpicness commented
Suggestion:
Rename normal blowtorches to "Combat Blowtorch"
Make so industrial and highcap blowtorches need eye pro as to nerf them.

2022-05-25 02:15 UTC, Nanu308 commented
Fine with this by essence, but will need to look at tweaking capacity down the line.

2022-05-26 18:55 UTC, Shad0vvs commented
> > Get a sprite for it possibly?
> 
> isn't that part that flips up when you activate the torch a welding screen?

Depends, do you mind sparks flying in your eye and do you think that tiny screen would actually do anything involving that?

2022-06-26 19:47 UTC, sose96 commented
Makes sense, I did two years of welding at college and as long as you don't look at the actual arc you are fine. and as technician helmets are plentiful in REQ It's not going to upset the balance at all really.

2022-06-27 09:36 UTC, stanalbatross requested changes

2022-06-27 09:36 UTC, stanalbatross commented on code/game/objects/items/tools/maintenance_tools.dm
> +		return 1
```suggestion
		return TRUE
```

2022-06-27 23:22 UTC, stanalbatross approved these changes

2022-07-05 00:12 UTC, merged