Revival of #2979: Ammo Can IMP Rack
cmss13-devs/cmss13 pull request #3392
Opened 2023-05-21 23:54 UTC by LynxSolstice

# About the pull request

Adds a relatively scarce logistics backpack item to the req vendor, allows Marines to carry 3 of any obj/item/ammo_box/, increases the logistics capability of your standard Marine. (Special thanks to Sionnach for the sprites, and Bengus, Harry, and Beagle for help with the code!)

# Explain why it's good for the game

Instead of 400 boxes of ammo or mags remaining at the FOB, this new item encourages logistics and ammo-bearing (A lot of riflemen like wearing ammo boxes on their backs, this allows them to hold more boxes + MRE boxes/flare boxes as well, thanks to those being a subtype of /ammo_box/. Allows the movement of supplies easier if you can get your hands on this elusive, limited issue item!

# Testing Photographs and Procedure

![image](https://github.com/cmss13-devs/cmss13/assets/112824777/56d3ab1f-daec-4cf3-ac66-e6f08efe0162)
![image](https://github.com/cmss13-devs/cmss13/assets/112824777/59693ccc-6ad3-40f6-ae0a-f4a1afdfab01)
![image](https://github.com/cmss13-devs/cmss13/assets/112824777/25e67432-a63c-41a0-a53c-0a4183d17fe6)

# Changelog

:cl:LynxSolstice
add: Adds a new IMP framed back item, the Ammo Rack.
balance: Added the new Ammo Rack to the Req vendor. At a scaling of (round*1), it should be pretty scarce.
imageadd: Added icons for Ammo_Pack_ and onmobs for each state (0, 1, 2, and 3)
/:cl:

2023-05-21 23:56 UTC, cm13live commented
This pull request has been mentioned on **CM-SS13**. Please provide feedback here:

https://forum.cm-ss13.com/t/three-improvements-for-marine-combat/2233/6

2023-05-22 17:29 UTC, Diegoflores31 commented on code/game/objects/items/storage/backpack.dm
> +	. = ..()
remove that or it will try to find (base_icon)_half and (base_icon)_full

2023-05-22 17:29 UTC, Diegoflores31 commented on code/game/objects/items/storage/backpack.dm
> +/obj/item/storage/backpack/marine/ammo_rack/Initialize(mapload)
i dont think this is required

2023-05-26 01:55 UTC, fira requested changes

2023-05-26 01:55 UTC, fira commented on code/game/objects/items/storage/backpack.dm
> +	RegisterSignal(user, COMSIG_HUMAN_POST_MOVE_DELAY, /obj/item/storage/backpack/marine/ammo_rack/(handle_movedelay))
```suggestion
	RegisterSignal(user, COMSIG_HUMAN_POST_MOVE_DELAY, PROC_REF(handle_movedelay))
```

2023-05-26 01:55 UTC, fira commented on code/game/objects/items/storage/backpack.dm
> +	UnregisterSignal(user, COMSIG_HUMAN_POST_MOVE_DELAY, /obj/item/storage/backpack/marine/ammo_rack/proc/handle_movedelay)
```suggestion
	UnregisterSignal(user, COMSIG_HUMAN_POST_MOVE_DELAY)
```

2023-05-28 02:41 UTC, fira commented
I know Morrow said 1 scale was better but that means at most 1 or 2 backpacks in the round total for something that is already a niche item. I'd recommend raising it to 1.5 or 2. 

Regardless as said it's very niche and it didn't get much airtime on the TM'ed round so far...

2023-05-28 07:00 UTC, scoutskywalker commented
This seems like it would make ammo availability further out from FOB a one man job, so I'm not sure if 3 slots is best balance wise but definitely an idea worth doing.

2023-05-29 23:21 UTC, merged