Adds more money items, up to one million dollars.
cmss13-devs/cmss13 pull request #3393
Opened 2023-05-22 01:18 UTC by VashVandez

Adds more money items for events that call for amounts of cash that's larger than a thousand.

# About the pull request

Adds additional spacecash items to make it easier for staff to spawn in larger amounts of money for the purposes of RP events.

# Explain why it's good for the game

Who doesn't like money?

2023-05-22 01:31 UTC, DOC-surge commented
i think this is a good idea because it's some of the small things that can be useful like sometimes stacked money can sometimes be a pain and this a can. be a quick fix.

2023-05-22 23:22 UTC, harryob commented on code/modules/economy/cash.dm
> +	icon_state = "spacecash1000"
you might just wanna make some sprites for these, given the sprites should be incredibly easy to just,,, make bigger

2023-05-23 20:01 UTC, sleepynecrons requested changes
move the 10k and 100k piles closer to the center so they're not hugging the sprite border 
![image](https://github.com/cmss13-devs/cmss13/assets/106241650/eaf9b835-52e1-406a-a8ce-1520b24348d2)
stack up the 1 mil pile closer to the example on the far right so that it isn't also touching the top and bottom borders

2023-05-24 01:25 UTC, VashVandez commented
> move the 10k and 100k piles closer to the center so they're not hugging the top and bottom sprite border ![image](https://user-images.githubusercontent.com/106241650/240405282-eaf9b835-52e1-406a-a8ce-1520b24348d2.png) stack up the 1 mil pile closer to the example on the far right so that there's more of a progression and it isn't also touching the top and bottom borders

![jb3vHTY](https://github.com/cmss13-devs/cmss13/assets/132308648/22a56ae8-675a-4890-a6b2-324c7b3bdf11)
![N6nhF0a](https://github.com/cmss13-devs/cmss13/assets/132308648/d74d6ca7-83d0-4b36-98b4-d83096711892)
![xq50dx4](https://github.com/cmss13-devs/cmss13/assets/132308648/95f9b2d7-6490-461a-bf0f-8835375d76cd)

2023-05-24 20:20 UTC, sleepynecrons approved these changes
the 10k and 100k shapes themselves were fine but this works too. sprites approved

2023-05-26 05:24 UTC, Zonespace27 commented on code/modules/economy/cash.dm
>  		var/cash_type = text2path("/obj/item/spacecash/c[sum]")
this isn't your fault but i've only looked at two lines of this proc and i hate it already

2023-06-12 01:50 UTC, closed without merging