B12 padless
cmss13-devs/cmss13 pull request #3400
Opened 2023-05-22 22:02 UTC by LynxSolstice

# About the pull request

Adds a padless variant of the B12 Armor.

# Explain why it's good for the game

I wanted a variant of the B12 without shoulder padding so I made it an option.

# Testing Photographs and Procedure

Runs and compiles, shows up properly on-mob, in hand, and on snow maps.

# Changelog

:cl:LynxSolstice
add: Added the new variant of B12 armor to the appropriate vendors.
spellcheck: Added a new description for the B12 Padless Armor, changed the mention of "M3 B12" from the corpsman and engineer vendors.
imageadd: Cut the pads off the B12 armor for a subtype with no padding.
/:cl:

2023-05-22 22:08 UTC, DOC-surge commented
I
 think this is a cool idea variation of some armors can be cool and this could be the first step to that.

2023-05-26 02:01 UTC, fira approved these changes
code OK

2023-05-26 05:00 UTC, Zonespace27 requested changes

2023-05-26 05:00 UTC, Zonespace27 commented on code/modules/clothing/suits/marine_armor.dm
> +	specialty = "B12 pattern padless marine"
```suggestion
	specialty = "B12 pattern padless marine"
	
```

2023-05-26 16:39 UTC, HaultyAnonie commented on code/modules/clothing/suits/marine_armor.dm
> +	specialty = "B12 pattern padless marine"
what exactly did you suggest to change

2023-06-07 02:45 UTC, morrowwolf commented
I don't really like the look of this.

2023-06-07 02:45 UTC, closed without merging