Broken bones can now cause IB
cmss13-devs/cmss13 pull request #3411
Opened 2023-05-24 02:39 UTC by BeagleGaming1

# About the pull request

Unsplinted broken bones can cause IB in a similar way to organ damage

# Explain why it's good for the game

It only makes sense that loose bones in your limbs will cut you up.

# Changelog

:cl:
balance: Unsplinted broken bones can cause IB
/:cl:

2023-05-24 04:02 UTC, morrowwolf requested changes

2023-05-24 04:02 UTC, morrowwolf commented on code/modules/mob/living/carbon/human/life/handle_organs.dm
> +				if(E.is_broken() && prob(15))
Change prob to like 3

2023-05-24 16:29 UTC, morrowwolf approved these changes
code and balance approved

2023-05-24 21:01 UTC, MistChristmas commented
If this is here to stay might we add IBs visible to the normal health scanner. So that we can see when someone has 5 IBs and where. Cause playing the guessing game of which frac(s) have the IB(s) isn't exactly a fun time.

2023-05-24 21:33 UTC, BeagleGaming1 commented
> If this is here to stay might we add IBs visible to the normal health scanner. So that we can see when someone has 5 IBs and where. Cause playing the guessing game of which frac(s) have the IB(s) isn't exactly a fun time.

Right click, "Check Status", it shows you exactly which limb has the IB

2023-05-25 20:46 UTC, morrowwolf requested changes
Let's do non-hands/non-feet only and drop prob to 2.

2023-05-26 15:45 UTC, merged