Armor preferences???
cmss13-devs/cmss13 pull request #3415
Opened 2023-05-24 22:52 UTC by NewyearnewmeUwu

# About the pull request
This adds a preference option in the character preferences menu that allows you to pick which armor type your prep vendor will give you. 
Notably, this does NOT apply to surplus uniform vendors so you can still get a different type of armor if you want to.

# Explain why it's good for the game
Saves time on having to get armor you want first off the bat. If you want skull armor, you'll only get skull armor as your first vended armor type.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
add: Added armor preference as an option in the preferences menu
/:cl:

2023-05-26 05:19 UTC, Zonespace27 requested changes
Add proof of testing.

2023-05-26 05:19 UTC, Zonespace27 commented on code/_globalvars/global_lists.dm
> +var/global/list/armor_style_list = list("Padded", "Padless", "Ridged", "Carrier", "Skull", "Smooth", "Random")
this should be a managed global list

2023-05-26 05:19 UTC, Zonespace27 commented on code/game/machinery/vending/cm_vending.dm
> +			new_armor.post_creation_handling(istype(vendor, /obj/structure/machinery/cm_vending/sorted/uniform_supply/squad_prep) ? null : user)
i fundamentally do not like this code bleeding over into generic vend code, if you can't figure out a way to do it, gimme a ping tomorrow when i'm more awake and i'll think of something

2023-05-26 05:19 UTC, Zonespace27 commented on code/modules/client/preferences.dm
> +	var/preferred_armor = "Random"
code doc

2023-05-26 05:19 UTC, Zonespace27 commented on code/modules/clothing/suits/marine_armor.dm
> +	if(!user || !user.client)
```suggestion
	if(!user?.client?.prefs)
```

2023-05-26 05:19 UTC, Zonespace27 commented on code/modules/clothing/suits/marine_armor.dm
> +/obj/item/clothing/suit/storage/marine/proc/post_creation_handling(mob/user)
code doc

2023-05-26 05:19 UTC, Zonespace27 commented on code/modules/clothing/suits/marine_armor.dm
> +		if(new_look == 7)
i dislike this being a magic number, a better way of doing all this would be making the global list a dict of {"style name": armor number}

2023-05-26 21:55 UTC, NewyearnewmeUwu commented
> Add proof of testing.

Done.

2023-05-28 17:36 UTC, BroseidonMOO approved these changes
Test merge test successful on round ID:  17045, 5/28/2023.

2023-05-28 19:34 UTC, realforest2001 requested changes

2023-05-28 19:34 UTC, realforest2001 commented on code/game/machinery/vending/cm_vending.dm
> +		new_item.post_vendor_spawn_hook(user)
15:29:32]RUNTIME: undefined proc or verb /obj/effect/essentials_set/intelligence_officer/post vendor spawn hook(). - cm_vending.dm@1182
[15:29:45]RUNTIME: undefined proc or verb /obj/effect/essentials_set/medical/doctor/post vendor spawn hook(). - cm_vending.dm@1182
[15:30:06]RUNTIME: undefined proc or verb /obj/effect/essentials_set/medic/post vendor spawn hook(). - cm_vending.dm@1182
[15:30:08]RUNTIME: undefined proc or verb /obj/effect/essentials_set/engi/post vendor spawn hook(). - cm_vending.dm@1182
[15:30:36]RUNTIME: undefined proc or verb /obj/effect/essentials_set/leader/post vendor spawn hook(). - cm_vending.dm@1182
[15:30:58]RUNTIME: undefined proc or verb /obj/effect/essentials_set/tl/post vendor spawn hook(). - cm_vending.dm@1182
[15:31:05]RUNTIME: undefined proc or verb /obj/effect/essentials_set/random/uscm_light_armor/post vendor spawn hook(). - cm_vending.dm@1182
[15:31:10]RUNTIME: undefined proc or verb /obj/effect/essentials_set/po_alternate/post vendor spawn hook(). - cm_vending.dm@1182

2023-05-28 19:35 UTC, Segrain commented on code/game/objects/items.dm
> +/obj/item/proc/post_vendor_spawn_hook(mob/living/carbon/human/user)
```suggestion
/obj/proc/post_vendor_spawn_hook(mob/living/carbon/human/user)
```

2023-05-28 19:57 UTC, merged