Revive fun fact
cmss13-devs/cmss13 pull request #3430
Opened 2023-05-26 16:43 UTC by morrowwolf

# About the pull request

This PR adds a revives fun fact

This PR attempts to move fun fact code around to make it easier to make new stats (it will likely break something)

# Explain why it's good for the game

Stats are fun and my support bros gotta get some love :muscle:

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl: Morrow
add: Adds a revive fun fact
/:cl:

2023-05-26 19:01 UTC, fira approved these changes

2023-05-27 12:01 UTC, Drulikar commented on code/datums/statistics/random_facts/random_fact.dm
> +	message = "<b>[name]</b> earned <b>[stat_gotten] [statistic_name]</b> [additional_message]"
Earning damage is a bit of a weird way for this to be phrased now: 
![image](https://github.com/cmss13-devs/cmss13/assets/76988376/f57f9c18-ffcd-4c7e-a774-49aeba2e08a6)

2023-05-27 21:06 UTC, harryob requested changes

2023-05-27 21:06 UTC, harryob commented on code/datums/statistics/random_facts/random_fact.dm
> +	message = "<b>[name]</b> earned <b>[stat_gotten] [statistic_name]</b> [additional_message]"
earned should be [verb] with that being defined per /datum/random_fact

2023-05-29 12:57 UTC, harryob approved these changes

2023-05-29 13:16 UTC, merged