Hive core requirements for stored larva from latejoin and bursts
cmss13-devs/cmss13 pull request #3432
Opened 2023-05-26 22:59 UTC by morrowwolf

# About the pull request

This PR makes it so you must have a hive core to get extra larva for:
bursts
latejoin marines

Latejoin marine requirement is waived for the first 15 minutes after roundstart.

# Explain why it's good for the game

Nomad hive should not have larva waiting for them ready to go after they put the hive core down again. Losing your hive should be a horrific loss.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl: Morrow
balance: Without a hive core Xenos no longer get stored larva from latejoin marines or bursts
/:cl:

2023-05-27 02:47 UTC, Diegoflores31 commented
i think burst is fine but latejoin is a little too much considering latejoin marines are usually a large amount and punishes excesively for loosing the core making it borderline impossible for a hive from recovering from a casual unga rush

2023-05-27 23:10 UTC, harryob requested changes

2023-05-27 23:10 UTC, harryob commented on code/modules/mob/new_player/new_player.dm
> +				if(length(hive.totalXenos) && (hive.hive_location || world.time < (SSticker.mode.round_time_lobby + XENO_ROUNDSTART_PROGRESS_TIME_2)))
```suggestion
				if(length(hive.totalXenos) && (hive.hive_location || ROUND_TIME >  XENO_ROUNDSTART_PROGRESS_TIME_2)))
```

2023-05-28 06:49 UTC, harryob approved these changes

2023-05-28 06:56 UTC, merged