Marine Major, Ares Announcement
cmss13-devs/cmss13 pull request #3448
Opened 2023-05-28 12:15 UTC by ghostsheet

# About the pull request

Adds an Ares Announcement when a marine major happens.

Adding onto Morrow's Cursed PR, blame Morrow for how he did it in #3118, not me

# Explain why it's good for the game

Currently marines don't know when they've won, therefore adding the 3 extra minutes is pointless as they spend that time hunting for a supposed last xeno that doesn't even exist.

With this Announcement, Marines will know they don't need to hunt the last xeno down anymore and can RP a conclusion and
Even award medals before the final Marine Major declaration happens.

# Testing Photographs and Procedure

# Changelog

:cl: ghostsheet
add: Added ARES conclusion announcement for marine major.
/:cl:

2023-05-28 12:26 UTC, Drulikar requested changes
The way it was done was intentional to not give more time to EORG, but still an opportunity for the commander to issue awards if they choose to. If this announcement should occur at all, it should be only on the command channel.

2023-05-28 18:36 UTC, morrowwolf reviewed
What Drulikar said.

People were using the extra time to just start EORG early.

If we make it command channel only it may relieve some of that.

If that doesn't do it I'm likely just going to revert the delay which is a bummer

2023-05-29 03:49 UTC, ghostsheet commented
![ARES conclusion 2](https://github.com/cmss13-devs/cmss13/assets/43085828/0a9121b4-cb99-4001-a923-68522913e2f5)
I guess this works

2023-05-29 05:52 UTC, Drulikar approved these changes

2023-05-29 10:52 UTC, merged