Yautja Bracer Charging Rework
cmss13-devs/cmss13 pull request #3456
Opened 2023-05-28 19:08 UTC by realforest2001

# About the pull request
Changes how bracers recharge, requiring drain from APC in the field.

# Explain why it's good for the game
Balances out power usage and makes things more dynamic.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
add: Yautja bracers can now be recharged from APCs.
remove: Yautja bracers no longer naturally recharge on the colony.
/:cl:

2023-05-28 19:21 UTC, BeagleGaming1 requested changes

2023-05-28 19:21 UTC, BeagleGaming1 commented on code/modules/cm_preds/yaut_bracers.dm
> +	var/last_charge
code doc for the vars?

2023-05-28 19:21 UTC, BeagleGaming1 commented on code/modules/cm_preds/yaut_bracers.dm
> +	var/mob/living/carbon/human/hooman = loc
why "hooman"?

2023-05-28 19:21 UTC, BeagleGaming1 commented on code/modules/power/apc.dm
> +					var/datum/effect_system/spark_spread/s = new /datum/effect_system/spark_spread
single letter var

2023-05-28 19:21 UTC, BeagleGaming1 commented on code/modules/power/apc.dm
> +					var/datum/effect_system/spark_spread/s = new /datum/effect_system/spark_spread
single letter var

2023-05-30 08:54 UTC, harryob commented on code/modules/power/apc.dm
> +					var/datum/effect_system/spark_spread/spark = new /datum/effect_system/spark_spread
```suggestion
					var/datum/effect_system/spark_spread/spark = new()
```

2023-05-30 08:54 UTC, harryob commented on code/modules/power/apc.dm
> +				else if(cell && cell.charge > 0)
redundant
```suggestion

				if(cell && cell.charge > 0)
```

2023-05-30 08:59 UTC, harryob requested changes

2023-05-30 08:59 UTC, harryob commented on code/modules/power/apc.dm
> +					return FALSE
```suggestion
				if(!cell || !cell.charge <= 0)
					to_chat(user, SPAN_WARNING("There is no charge to draw from that APC."))
					return FALSE

				if(bracer.charge_max <= bracer.charge)
					to_chat(user, SPAN_WARNING("[bracer.name] is already fully charged."))
					return FALSE

				var/charge_to_use = min(cell.charge, bracer.charge_max - bracer.charge)
				if(!(cell.use(charge_to_use)))
					return FALSE
				playsound(src.loc, 'sound/effects/sparks2.ogg', 25, 1)
				bracer.charge += charge_to_use
				bracer.last_charge = (world.time + bracer.charge_cooldown)
				to_chat(grabber, SPAN_YAUTJABOLD("[icon2html(bracer)] \The <b>[bracer]</b> beep: Power siphon complete. Charge at [bracer.charge]/[bracer.charge_max]."))
				if(bracer.notification_sound)
					playsound(bracer.loc, 'sound/items/pred_bracer.ogg', 75, 1)
				charging = APC_CHARGING
				set_broken() // Breaks the APC

				return TRUE
```

2023-05-30 08:59 UTC, harryob commented on code/modules/power/apc.dm
> +			var/datum/effect_system/spark_spread/spark = new /datum/effect_system/spark_spread
```suggestion
			var/datum/effect_system/spark_spread/spark = new()
```

2023-06-04 11:06 UTC, harryob requested changes

2023-06-04 11:06 UTC, harryob commented on code/modules/cm_preds/yaut_bracers.dm
> +	var/last_charge
use the cooldown defines for managed cooldowns, either COOLDOWN_ or TIMER_COOLDOWN_

2023-06-04 11:06 UTC, harryob commented on code/modules/cm_preds/yaut_bracers.dm
> +	var/mob/living/carbon/human/hooman = loc
```suggestion
	var/mob/living/carbon/human/human_holder = loc
```

2023-06-04 11:06 UTC, harryob commented on code/modules/cm_preds/yaut_bracers.dm
> +		if(is_ground_level(hooman.z))
```suggestion
		if(is_ground_level(human_holder.z))
```

2023-06-04 11:06 UTC, harryob commented on code/modules/cm_preds/yaut_bracers.dm
> +		else if(is_mainship_level(hooman.z))
```suggestion
		else if(is_mainship_level(human_holder.z))
```

2023-06-04 11:06 UTC, harryob commented on code/modules/cm_preds/yaut_bracers.dm
> +		hooman.update_power_display(perc_charge)
```suggestion
		human_holder.update_power_display(perc_charge)
```

2023-06-04 11:06 UTC, harryob commented on code/modules/cm_preds/yaut_bracers.dm
> +		if(!HAS_TRAIT(hooman, TRAIT_YAUTJA_TECH) && !hooman.hunter_data.thralled)
```suggestion
		if(!HAS_TRAIT(human_holder, TRAIT_YAUTJA_TECH) && !human_holder.hunter_data.thralled)
```

2023-06-04 11:06 UTC, harryob commented on code/modules/cm_preds/yaut_bracers.dm
> +				decloak(hooman)
```suggestion
				decloak(human_holder)
```

2023-06-04 11:06 UTC, harryob commented on code/modules/cm_preds/yaut_bracers.dm
> +				shock_user(hooman)
```suggestion
				shock_user(human_holder)
```

2023-06-04 11:06 UTC, harryob commented on code/modules/cm_preds/yaut_bracers.dm
> +		if(hooman.stat == DEAD)
```suggestion
		if(human_holder.stat == DEAD)
```

2023-06-04 11:06 UTC, harryob commented on code/modules/cm_preds/yaut_bracers.dm
> +			decloak(hooman, TRUE)
```suggestion
			decloak(human_holder, TRUE)
```

2023-06-04 11:06 UTC, harryob commented on code/modules/power/apc.dm
> +				to_chat(grabber, SPAN_YAUTJABOLD("[icon2html(bracer)] \The <b>[bracer]</b> beep: Power siphon complete. Charge at [bracer.charge]/[bracer.charge_max]."))
```suggestion
				to_chat(grabber, SPAN_YAUTJABOLD("[icon2html(bracer)] <b>[bracer]</b> beeps: Power siphon complete. Charge at [bracer.charge]/[bracer.charge_max]."))
```

2023-06-05 10:58 UTC, realforest2001 commented on code/modules/power/apc.dm
> +				to_chat(grabber, SPAN_YAUTJABOLD("[icon2html(bracer)] \The <b>[bracer]</b> beep: Power siphon complete. Charge at [bracer.charge]/[bracer.charge_max]."))
They're pluralised bracerS 😔

2023-06-12 20:57 UTC, morrowwolf requested changes

2023-06-12 20:57 UTC, morrowwolf commented on code/modules/power/apc.dm
> +				if(!cell || !cell.charge <= 0)
if(!cell || cell.charge <= 0)

2023-06-17 17:25 UTC, realforest2001 commented on code/modules/power/apc.dm
> +				if(!cell || !cell.charge <= 0)
```suggestion
				if(!cell || cell.charge <= 0)
```

2023-07-13 17:59 UTC, Diegoflores31 commented on code/modules/cm_preds/yaut_bracers.dm
> +	//Non-Yautja have a chance to get stunned with each power drain
can research trait users get a little more leeway ?

2023-07-15 16:19 UTC, Mister-moon1 commented
During the original testing for the pred quality of life TM it was expressed by many that achieving power planetside was, although difficult, possible due to a couple APCs missed by the xenos.
The noticeable oversight was of course the fact of having near enough infinite power shipside due to being able to ping to and from the same APC, the "solution" given was to have the APC destroyed upon siphon along with a 5 minute cooldown

This has led to achieving power groundside almost impossible via siphoning power due to the fact of that one forgotten APC just being destroyed when the yautja gets power, leaving no source of power other than the 5 power per second or so from natural regeneration, when needing 1000 for a simple crystal this is a bit absurd. It also leaves the only other possible option to go shipside and deal with the better but still subpar power regeneration with the best solution to go afk and come back when it is done which i do not find very engaging.

I suggest that the groundside regeneration be doubled to 10 per tick and APCs be reverted to their state of not being broken upon siphon, i believe that the 5 minute cooldown should be enough to not warrant issues coming from this

2023-07-18 04:56 UTC, Diegoflores31 commented
Idea for "possible" solution . Add a self recharge device thingy that can be used like like AVP classic one . 10 minute cooldown or more . With a windup of dunno 10 seconds

2023-07-19 05:54 UTC, morrowwolf commented
Ping me once cloaking PR is merged if I forget.

2023-07-19 12:20 UTC, harryob requested changes

2023-07-19 12:20 UTC, harryob commented on code/modules/power/apc.dm
> +				bracer.last_charge = (world.time + bracer.charge_cooldown)
cooldown defines

2023-07-19 12:20 UTC, harryob commented on code/modules/cm_preds/yaut_bracers.dm
> +	//Non-Yautja have a chance to get stunned with each power drain
no

2023-07-19 12:20 UTC, harryob commented on code/modules/cm_preds/yaut_bracers.dm
> +	var/last_charge
cooldown defines

2023-07-19 12:20 UTC, harryob commented on code/modules/cm_preds/yaut_bracers.dm
> +	if(cloaked)
early return

2023-07-24 17:13 UTC, harryob requested changes
one last nit

2023-07-24 17:13 UTC, harryob commented on code/modules/power/apc.dm
> +					var/datum/effect_system/spark_spread/spark = new /datum/effect_system/spark_spread
```suggestion
					var/datum/effect_system/spark_spread/spark = new()
```

2023-07-24 17:49 UTC, harryob approved these changes

2023-07-24 19:24 UTC, merged