The nuclear option
cmss13-devs/cmss13 pull request #3470
Opened 2023-05-29 22:15 UTC by morrowwolf

# About the pull request

This PR adds a nuke as something buyable at the tier 4 level of intel. It takes 35 points in total to reach it. You cannot buy it before 90 minutes.

To use the nuke you must first decrypt the authorization codes on the surface. This requires holding both comms towers on the surface for 10 minutes.

After it's decrypted you are free to arm the nuke and it will detonate in 60 seconds.

# Explain why it's good for the game

Coming soonTM

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
add: Re-added the nuke that you can buy via intel at tier 4. Only purchasable past 90 minutes. Requires holding both groundside comms towers.
/:cl:

2023-05-29 22:20 UTC, morrowwolf commented
Some notes for reviewers:
I need an intel icon (sprites)
I need to announce when decryption is done
I need to make the timer the same as the other timer for both arming and destroying
Check if there's a double announce at the beginning of arming
Make window more in like height-wise

2023-05-29 22:39 UTC, harryob requested changes
initial

2023-05-29 22:39 UTC, harryob commented on code/game/machinery/nuclearbomb.dm
> +		explode()
```suggestion
		explode()
		return
```

2023-05-29 22:39 UTC, harryob commented on code/game/machinery/nuclearbomb.dm
> +	else if(timer_announcements_flags)
```suggestion
	if(!timer_announcements_flags)
		return
```

2023-05-29 22:39 UTC, harryob commented on code/game/machinery/nuclearbomb.dm
> +				return
```suggestion
	if(timer_announcements_flags & NUKE_SHOW_TIMER_HALF)
		if(timeleft <= initial(timeleft) / 2 && timeleft >= initial(timeleft) / 2 - 30)
			announce_to_players(NUKE_SHOW_TIMER_HALF)
			timer_announcements_flags &= ~NUKE_SHOW_TIMER_HALF
			return
	if(timer_announcements_flags & NUKE_SHOW_TIMER_MINUTE)
		if(timeleft <= 600 && timeleft >= 570)
			announce_to_players(NUKE_SHOW_TIMER_MINUTE)
			timer_announcements_flags = NUKE_SHOW_TIMER_TEN_SEC
			return
	if(timer_announcements_flags & NUKE_SHOW_TIMER_TEN_SEC)
		if(timeleft <= 100 && timeleft >= 70)
			announce_to_players(NUKE_SHOW_TIMER_TEN_SEC)
			timer_announcements_flags = 0
			return
```

2023-05-29 22:39 UTC, harryob commented on code/game/machinery/nuclearbomb.dm
> +
```suggestion
```

2023-05-29 22:39 UTC, harryob commented on code/game/machinery/nuclearbomb.dm
> +	return data
```suggestion
	. = ..()

	.["decrypting"] = decrypting
	.["decryption_time"] = decryption_time / (1 SECONDS)
```

2023-05-29 22:39 UTC, harryob commented on code/game/machinery/nuclearbomb.dm
> +				return
```suggestion
			var/area/current_area = get_area(src)
			if(!current_area.can_build_special)
				to_chat(ui.user, SPAN_INFO("You cannot deploy [src] here!"))
				return
```

2023-05-29 22:39 UTC, harryob commented on code/game/machinery/nuclearbomb.dm
> +	else if(timer_announcements_flags)
```suggestion
	if(!timer_announcements_flags)
```

2023-05-29 22:39 UTC, harryob commented on code/game/machinery/nuclearbomb.dm
> +				return
```suggestion
	if(timer_announcements_flags & NUKE_DECRYPT_SHOW_TIMER_HALF)
		if(decryption_time <= initial(decryption_time) / 2 && decryption_time >= initial(decryption_time) / 2 - 30)
			announce_to_players(NUKE_DECRYPT_SHOW_TIMER_HALF)
			timer_announcements_flags &= ~NUKE_DECRYPT_SHOW_TIMER_HALF
			return
	if(timer_announcements_flags & NUKE_DECRYPT_SHOW_TIMER_MINUTE)
		if(decryption_time <= 600 && decryption_time >= 570)
			announce_to_players(NUKE_DECRYPT_SHOW_TIMER_MINUTE)
			timer_announcements_flags &= ~NUKE_DECRYPT_SHOW_TIMER_MINUTE
			return
```

2023-05-29 22:39 UTC, harryob commented on code/game/machinery/nuclearbomb.dm
> +		var/warning
```suggestion
		var/warning = "Hive killer is almost prepared to be activated!"
```

2023-05-29 22:39 UTC, harryob commented on code/game/machinery/nuclearbomb.dm
> +			warning = "Hive killer is almost prepared to be activated!"
```suggestion
```

2023-05-29 22:39 UTC, harryob commented on code/game/machinery/nuclearbomb.dm
> +			xeno_announcement(SPAN_XENOANNOUNCE("The tallhosts have started the initial phase of a hive killer at [get_area_name(loc)]! Destroy their communications relays!"), hive.hivenumber, XENO_GENERAL_AN
```suggestion
			xeno_announcement(SPAN_XENOANNOUNCE("The tallhosts have started the initial phase of a hive killer at [get_area_name(loc)]! Destroy their communications relays!"), hive.hivenumber, XENO_GENERAL_ANNOUNCE)
			return
```

2023-05-29 22:39 UTC, harryob commented on code/game/machinery/nuclearbomb.dm
> +			xeno_announcement(SPAN_XENOANNOUNCE("The hive killer's initial phase has been halted! Rejoice!"), hive.hivenumber, XENO_GENERAL_ANNOUNCE)
```suggestion

	announcement_helper("ALERT.\n\nNUCLEAR EXPLOSIVE DECRYPTION HALTED.", "[MAIN_AI_SYSTEM] Nuclear Tracker", humans_USCM, 'sound/misc/notice1.ogg')
	announcement_helper("ALERT.\n\nNUCLEAR EXPLOSIVE DECRYPTION HALTED.", "HQ Intel Division", humans_other, 'sound/misc/notice1.ogg')
	yautja_announcement(SPAN_YAUTJABOLDBIG("WARNING!<br>The human Purification Device's signature has disappeared."))
	for(var/hivenumber in GLOB.hive_datum)
		hive = GLOB.hive_datum[hivenumber]
		if(!length(hive.totalXenos))
			continue
		xeno_announcement(SPAN_XENOANNOUNCE("The hive killer's initial phase has been halted! Rejoice!"), hive.hivenumber, XENO_GENERAL_ANNOUNCE)
```

2023-05-29 22:39 UTC, harryob commented on code/modules/cm_tech/techs/marine/tier4/nuke.dm
> +	supply_controller.shoppinglist += O
```suggestion
	var/datum/supply_order/new_order = new /datum/supply_order()
	new_order.ordernum = supply_controller.ordernum
	supply_controller.ordernum++
	new_order.object = supply_controller.supply_packs["Intel Operational Nuke"]
	new_order.orderedby = MAIN_AI_SYSTEM

	supply_controller.shoppinglist += new_order
```

2023-05-29 23:00 UTC, fira requested changes
SPAN_DANGERs weren't so bad given the magnitude and importance of this thing...

2023-05-31 04:06 UTC, morrowwolf commented
I'm not ignoring reviews FWIW just trying to settle if this is something I even want to finalize into a hard feature or not before I sink more time on serious polish. I appreciate you all 🙏

2023-06-01 05:38 UTC, frozentsbgg commented
90 Minutes is too short.
Probably needs to be 120.

Aiming for the 2:30-3:00 round stalemate breaker is the best function of the nuke.
Good changes making it buyable though!

2023-06-01 05:39 UTC, morrowwolf commented
90 minutes is for testing both feasibility and functionality.

We've already learned of a comms location on soro that absolutely needs moved.

2023-06-01 05:44 UTC, frozentsbgg commented
> 

Makes sense :) Appreciate the clarification.
Just wanted to state that I like the feature, all the criticism I've seen so far has been time-related, so that makes me feel better.

2023-06-08 11:20 UTC, morrowwolf commented
Basic review done, gonna finish up the above polish stuff when I get da sprite. 🙏

2023-06-16 07:25 UTC, harryob requested changes

2023-06-16 07:25 UTC, harryob commented on code/game/machinery/nuclearbomb.dm
> +		return
return PROCESS_KILL?

2023-06-17 18:00 UTC, harryob requested changes

2023-06-20 15:39 UTC, harryob requested changes

2023-06-20 15:39 UTC, harryob commented on code/game/machinery/nuclearbomb.dm
> +	. = ..()
```suggestion
	return ..()
```

2023-06-20 15:39 UTC, harryob commented on code/game/machinery/nuclearbomb.dm
> +	UnregisterSignal(SSdcs, COMSIG_GLOB_GROUNDSIDE_TELECOMM_TURNED_OFF)
should be unnecessary to handle signal cleanup in destroy

2023-06-20 15:39 UTC, harryob commented on code/game/machinery/nuclearbomb.dm
> +		.["decryption_complete"] = TRUE
```suggestion
	.["decryption_complete"] = decryption_time ? FALSE : TRUE
```

2023-06-20 15:47 UTC, harryob approved these changes

2023-06-20 17:45 UTC, merged