Overwatch Signals for QDEL: Less client disconnection?
cmss13-devs/cmss13 pull request #3477
Opened 2023-05-30 09:18 UTC by Drulikar

# About the pull request

This PR is sort of a stab in the dark to fix #3444 by making marine and xeno overwatching register a signal for qdeletion to end the overwatch faster. The actual source of this issue is apparently that the multithreaded map tick beta has an issue with crashing clients, so the changes made in this PR don't need to be permanent if the effect isn't as desirable when the beta is fixed.

Locally testing has not been able to reproduce the problem, but I can confirm I do not get the momentary blank screen when overwatching something that gets deleted.

# Explain why it's good for the game

Hopefully no more (or less) client disconnections when overwatching something that gets deleted.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

![qdel](https://github.com/cmss13-devs/cmss13/assets/76988376/2d9af325-3959-40ae-a36c-1fc8b2d950cf)

</details>

# Changelog

:cl: Drathek
fix: Clients should hopefully avoid disconnection when observing someone that is deleted.
/:cl:

2023-05-30 23:19 UTC, Wintermote commented
I haven't noticed disconnection when overwatching using the overwatch console in CIC, and that should be the same process as the ghost overwatch, shouldn't it?

2023-06-03 10:36 UTC, Watermelon914 requested changes

2023-06-03 10:36 UTC, Watermelon914 commented on code/modules/mob/living/carbon/xenomorph/XenoOverwatch.dm
> +	UnregisterSignal(deleted, COMSIG_PARENT_QDELETING)
this isn't necessary

2023-06-03 10:36 UTC, Watermelon914 commented on code/modules/mob/mob.dm
> +	UnregisterSignal(deleted, COMSIG_PARENT_QDELETING)
this isn't necessary, all signals get unregistered on deletion anyways

2023-06-04 11:17 UTC, harryob approved these changes
lets see

2023-06-04 11:31 UTC, Drulikar commented
#3525 might be a more comprehensive fix unless that's yet another different 515 flaw.

2023-06-04 12:27 UTC, merged