When you ghost as a zombie your body will become a free mob.
cmss13-devs/cmss13 pull request #3482
Opened 2023-05-30 21:54 UTC by Huffie56

# About the pull request
When you ghost as a zombie your body will become a free mob.

# Explain why it's good for the game
No more zombie wasted we recycle now.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
code: When you ghost as a zombie you body will become a free mob.
/:cl:

2023-05-30 21:57 UTC, harryob requested changes

2023-05-30 21:57 UTC, harryob commented on code/modules/mob/dead/observer/observer.dm
> +		src.free_for_ghosts()
```suggestion
		free_for_ghosts()
```

2023-05-31 12:17 UTC, Huffie56 commented
i need to make a test to check if someone is decap or as is head destroyed but i didn't found anything that match this so if you can help tag me. thanks.

2023-05-31 12:21 UTC, Huffie56 commented on code/modules/mob/dead/observer/observer.dm
> +		free_for_ghosts()
i need to add a check so that zombie without their head don't become free mob...
i tried multiple stuff nothing work....

2023-05-31 15:00 UTC, Huffie56 commented on code/datums/diseases/black_goo.dm
need to make sure this doesn't create a conflict and between old owner of the corpse being able to return back in while the new zombie is on join free mob list...

2023-05-31 22:40 UTC, Huffie56 commented
todo list : 
1-add a TGUI pop up for when a corpse is being turn into a zombie....
2-add a TGUI pop when a dead zombie get revive...

2023-06-01 21:14 UTC, Huffie56 commented
i tried to add other checks for revive or when you turn into zombie to get more free mob zombie but those haven't been reliable...

2023-06-05 10:02 UTC, Huffie56 commented
![image](https://github.com/cmss13-devs/cmss13/assets/117036822/bd0b2376-5dc9-43d4-959d-ee79c0342b0b)
it only work for living zombie right now as i didn't find the check ... oh i have an idea...

2023-06-08 20:22 UTC, BeagleGaming1 commented
How's this a "Code Improvement"?

2023-06-08 20:42 UTC, Huffie56 commented
> How's this a "Code Improvement"?

code is my way to go when i don't know what to pick.

2023-06-09 13:46 UTC, Drulikar requested changes

2023-06-09 13:46 UTC, Drulikar commented on code/modules/mob/dead/observer/observer.dm
> +	if(iszombie(src)&&stat == !DEAD)
Even when not inhabited by a client, a zombie can still be reviving (generally this should only not be occurring if we're decapitated); so you might want to either also check if we're reviving, or have the revival perform a check if we have a client and then also free_for_ghosts there if there is no client.

2023-06-14 03:56 UTC, Drulikar commented on code/modules/mob/dead/observer/observer.dm
> +	if(iszombie(src)&&stat == !DEAD)
See `/datum/species/zombie/handle_death(mob/living/carbon/human/zombie, gibbed)` in zombie.dm

The conditioons for whether they get a revive timer is: they must be a zombie, they must not be gibbed, they must have a head that isn't qdeleted, and they must have a head that is not LIMB_DESTROYED.

Alternatively, you can check if the zombie species has a weakref to this zombie in its to_revive; but the former checks would likely be preferable to handle situations where the client is disconnecting as their mob is undoing the revival process.

2023-06-14 07:43 UTC, Huffie56 commented on code/modules/mob/dead/observer/observer.dm
> +	if(iszombie(src)&&stat == !DEAD)
i will try.

2023-06-29 01:50 UTC, closed without merging