Nerfs lurker pounce movement and adds a cooldown for headbite.
cmss13-devs/cmss13 pull request #3496
Opened 2023-06-01 01:28 UTC by NewyearnewmeUwu

# About the pull request
I removed the fact that slashing as lurker allows you to move immediately after pouncing someone while in cloak, and headbite now has a 10 second CD. Both of these things have balance approval from Morrow.

# Explain why it's good for the game
The free movement thing was kind of ridicilous and headbite is an ability that seriously hurts whoever you use it against, so having a CD makes sense.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
balance: Slashing after pouncing while in cloak as normal lurker no longer lets you move immediately.
balance: Headbite has a 10 second cooldown.
/:cl:

2023-06-01 10:34 UTC, ihatethisengine commented
Lurker pounce freezers lurker for 1.5 seconds, so in meantime you're free target for PBs and regular shots. This change just makes hit & run tactic impossible, because you removed «run» part without giving anything in exchange. This is really weird for a dedicated ambush caste. And why was that a problem? You have to disengage anyway if there are marines before you can apply significant damage. And to disengage you need to directly click sprite covered by your sprite which is not that easy and you can fuck it up and get PBed anyway.

2023-06-01 19:43 UTC, Diegoflores31 commented
Headbite damage does little to no damage . its supposed to be a reward for a murder . 10 second cooldown is insane considering the only purpose of the ability is to reward with health for critting and enemy.

Lurker change literally just makes it unable to fight 2 marines . they are a T2 aggresive caste not a drone , they ARE supposed to do significant damage specially considering 70% of marines can just wake up after being pounced . eat a pill and be full health as they were before

2023-06-04 10:38 UTC, morrowwolf requested changes
I feel there's been some confusion.

I don't remember saying anything about lurker pounce/movement delay and have no intentions of touching it. I think what I meant was the pushing people while invisible but iunno.

The CD to headbite is fine.

2023-06-04 19:37 UTC, NewyearnewmeUwu commented
i think i misinterpreted something you said? been a bit so i forgot.

2023-06-04 20:12 UTC, merged