Automatic forsaken spawns groundside during hijack
cmss13-devs/cmss13 pull request #3508
Opened 2023-06-02 09:50 UTC by morrowwolf

# About the pull request

This PR automatically spawns forsaken at a 1.5:1 marine:xeno rate when marines are groundside during hijack.

The xenos are only tier 1/2s. With a 2:1 ratio of tier 1 to tier 2.

# Explain why it's good for the game

The planet is meant to still be an infested hellhole rather than empty once the hive leaves. You *should* fear it.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl: Morrow
add: Added automatic forsaken spawns groundside during hijack
/:cl:

2023-06-02 14:02 UTC, harryob requested changes

2023-06-02 16:14 UTC, Segrain commented on code/game/gamemodes/colonialmarines/colonialmarines.dm
> +		for(var/mob/groundside_mob in groundside_humans)
That is a number, not a list.

2023-06-04 07:05 UTC, MusselMain commented
hopefully these spawns won't extend rounds if marines win the hijack

2023-06-04 10:39 UTC, harryob requested changes

2023-06-04 10:39 UTC, harryob commented on code/datums/emergency_calls/forsaken_xenos.dm
> +/datum/emergency_call/forsaken_xenos/create_member(datum/mind/M, turf/override_spawn_loc)
```suggestion
/datum/emergency_call/forsaken_xenos/create_member(datum/mind/new_member, turf/override_spawn_loc)
```

2023-06-04 10:39 UTC, harryob commented on code/datums/emergency_calls/forsaken_xenos.dm
> +	var/mob/current_mob = M.current
```suggestion
	var/mob/current_mob = new_member.current
```

2023-06-04 10:39 UTC, harryob commented on code/datums/emergency_calls/forsaken_xenos.dm
> +	M.transfer_to(new_xeno, TRUE)
```suggestion
	new_member.transfer_to(new_xeno, TRUE)
```

2023-06-04 10:41 UTC, harryob approved these changes

2023-06-04 12:15 UTC, merged