FOB Tents
cmss13-devs/cmss13 pull request #3509
Opened 2023-06-02 13:30 UTC by fira

# About the pull request

Sprites stolen from thwomper!

Adds a few tents to be used in FOB building, mainly for organizational purposes but also providing small gameplay benefits. At current the main goal is to incentive usage to organize and liven up FOB, so the buffs are rather small.

There are 4 tent types:
 * The Command Tent is a 2x3 structure that comes bundled with an overwatch console, a phone, and two (2) chairs.
 * The Medical Tent is a 2x3 structure that comes with a NanoMED, 2 roller beds, and slightly buffs surgery (10% less time taken, and a very token pain/failure chance improvement)
 * The Requisitions Tent is a 4x3 structure that comes with a phone, rack, desks, and a variant of the old APC vendor that can stock materials and regular ammunition. The vendor starts empty, save for some tables/racks/paperwork for organization purposes. It is only useable with requisitions access.
 * The Big Tent is a bigger tent for all your organizational needs: 3x3. Get creative.

The tents also provide decent additional protection against cold environements. Unfortunately, rain/snow will visually pour through it, i can't do much about that.

The tents are extremely vulnerable to explosives and xeno claws. For simplicity and technical reasons, they are currently NON REDEPLOYABLE and NON REPLACEABLE. The tent destruction will destroy/disable linked objects (console/vendor etc). Be mindful of where you place them.

# Explain why it's good for the game

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

I'm lazyyy i forgot and already closed the game... If you actually want em bug me and i'll add em
</details>

# Changelog

:cl:
add: Added four types of tents to liven up FOB. They provide cold protection and benefits depending on their type. The tents spawn in Requisitions roundstart near the mortar. They're vulnerable to explosives and xenomorphs, and NON REPLACEABLE. Mind where you put them!
add: The Command tent comes equipped with an overwatch console and a phone.
add: The Medical tent provides a small boost to surgery speed/pain carried out inside it.
add: The Requisitions tent provides a restockable vendor, desk, and furniture for organization.
add: The Big tent is just a big tent, and provides you a slate to organize the way you want.
/:cl:

2023-06-02 14:15 UTC, fira commented
CI C&D errors are due to instanciating a tent-linked object without a tent for tests

Not sure how to handle these

2023-06-02 20:58 UTC, fira commented on code/modules/tents/folded_tents.dm
> +	name = "folded USCM Medical Tent"
Yup, fixed, thanks!

2023-06-02 22:34 UTC, nauticall commented
oi I made the original tent sprites credit me too

2023-06-03 04:53 UTC, GODdudesoyeah commented
soul +1

2023-06-03 09:53 UTC, Huffie56 commented
![image](https://github.com/cmss13-devs/cmss13/assets/117036822/9544e7d1-f98c-457d-ba89-b145a90fd726)

2023-06-03 09:58 UTC, fira commented on code/modules/tents/folded_tents.dm
> +	var/turf/starting_turf = locate(ref_turf.x, ref_turf.y, ref_turf.z)
fix this idiot wtf is this supposed to do???

2023-06-03 10:39 UTC, fira commented
One outstanding bug reported: when tent collapse while in, it doesn't revoke roof-seethru privileges to people so they can keep seeing inside forever (or until exiting another tent)

2023-06-04 11:14 UTC, harryob requested changes

2023-06-04 11:14 UTC, harryob commented on code/modules/tents/folded_tents.dm
> +		if(NORTH) deploy_turf = locate(deploy_turf.x + off_x, deploy_turf.y + 1, deploy_turf.z)
```suggestion
		if(NORTH) 
			 deploy_turf = locate(deploy_turf.x + off_x, deploy_turf.y + 1, deploy_turf.z)
```

2023-06-04 11:14 UTC, harryob commented on code/modules/tents/folded_tents.dm
> +		if(SOUTH) deploy_turf = locate(deploy_turf.x + off_x, deploy_turf.y - dim_y, deploy_turf.z)
```suggestion
		if(SOUTH) 
			 deploy_turf = locate(deploy_turf.x + off_x, deploy_turf.y - dim_y, deploy_turf.z)
```

2023-06-04 11:14 UTC, harryob commented on code/modules/tents/folded_tents.dm
> +		if(EAST)  deploy_turf = locate(deploy_turf.x + 1, deploy_turf.y + off_y, deploy_turf.z)
```suggestion
		if(EAST)  
			 deploy_turf = locate(deploy_turf.x + 1, deploy_turf.y + off_y, deploy_turf.z)
```

2023-06-04 11:14 UTC, harryob commented on code/modules/tents/folded_tents.dm
> +		if(WEST)  deploy_turf = locate(deploy_turf.x - dim_x, deploy_turf.y + off_y, deploy_turf.z)
```suggestion
		if(WEST)  
			 deploy_turf = locate(deploy_turf.x - dim_x, deploy_turf.y + off_y, deploy_turf.z)
```

2023-06-04 11:14 UTC, harryob commented on code/modules/vehicles/interior/interactable/vendors.dm
> +	desc =  "An automated restockable storage vendor for use in organizing FOB supplies."
```suggestion
	desc = "An automated restockable storage vendor for use in organizing FOB supplies."
```

2023-06-04 11:14 UTC, harryob commented on code/modules/vehicles/interior/interactable/vendors.dm
> +	var/obj/structure/tent/located_tent = locate(/obj/structure/tent) in src.loc
```suggestion
	var/obj/structure/tent/located_tent = locate(/obj/structure/tent) in loc
```

2023-06-04 13:49 UTC, fira commented
This is still missing implementation of closable flaps, and possibly tent camouflages if we deem them in-scope

2023-06-05 22:38 UTC, fira commented
Now has curtains and camouflage variants, courtesy of thwomper 

This also refactors weapon camouflage to be map_config based

2023-06-08 20:10 UTC, harryob requested changes

2023-06-09 18:55 UTC, merged