Fix Force Dropship Admin Verb
cmss13-devs/cmss13 pull request #3514
Opened 2023-06-03 08:04 UTC by Drulikar

# About the pull request

This PR fixes the force dropship admin verb that could be used to hijack a dropship. Now it will not runtime, nor require the admin to be adjacent to the console.

For a non-crash, I would have it just open the shuttle manipulator, but that is a verb on the admin datum instead of the client - this verb also doesn't perform any admin permissions checking currently... (it probably should).

# Explain why it's good for the game

Admin verbs should work, otherwise they should be eliminated.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl: Drathek
admin: Fixed force dropship verb requiring the admin to be adjacent to the console (also no longer runtimes, allowing the rest of the hijack to occur normally)
/:cl:

2023-06-03 15:40 UTC, realforest2001 requested changes

2023-06-03 15:40 UTC, realforest2001 commented on code/modules/admin/tabs/event_tab.dm
> +		return
Can you rename the proc to Force Hijack to fit with this please

2023-06-04 07:51 UTC, harryob requested changes

2023-06-04 07:51 UTC, harryob commented on code/modules/admin/tabs/event_tab.dm
> +	if(!confirm) return
```suggestion
	if(!confirm) 
		return
```

2023-06-04 07:51 UTC, harryob commented on code/modules/admin/tabs/event_tab.dm
> +	computer.hijack(usr, force=TRUE)
```suggestion
	computer.hijack(usr, force = TRUE)
```

2023-06-04 10:54 UTC, harryob approved these changes

2023-06-04 11:41 UTC, merged