balance : reduce most of the prices in cigarette vendor
cmss13-devs/cmss13 pull request #3519
Opened 2023-06-03 13:38 UTC by Huffie56

# About the pull request

rifleman shouldn't be so poor they
can't even afford to buy a pack of the
cheapest cigarette and a zippo...

# Explain why it's good for the game
everyone in the marines should have enought money to buy atleas a pack of the cheapest cigarette or cigar and a zippo.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
balance: change price in cigarette vendor lucky_strikes 35=>15, tarbacktube 35=>15, lighter/random 10=>8,lighter/zippo 25=>20
/:cl:

2023-06-03 15:36 UTC, realforest2001 commented
This isn't really balance altering.

2023-06-04 10:47 UTC, morrowwolf requested changes
Change the multiplier for marine money rather than the cost of the things please.

2023-06-04 12:45 UTC, Huffie56 commented
> Change the multiplier for marine money rather than the cost of the things please.

i can't ? can't we use money to buy black market stuff?
way more safer to just reduce items prices?...

2023-06-05 15:15 UTC, fira approved these changes

2023-06-05 16:19 UTC, Huffie56 commented on code/datums/paygrades/factions/uscm/marine.dm
> +	pay_multiplier = 1.6 // the default.
it's been executed.

2023-06-06 00:12 UTC, morrowwolf approved these changes

2023-06-06 00:39 UTC, merged