Fix Map Landing Liughts
cmss13-devs/cmss13 pull request #3543
Opened 2023-06-05 17:47 UTC by Steelpoint

# About the pull request
This PR fixes issues with landing lights on the following maps.
- LV-624
- Solaris Ridge
- Fiorina Science Annex
- Trijent Dam
- Sorokyne Strata
- Kutjevo Refinery

This PR also adds landing lights for LZ2 on Shivas Snowball. LZ1 does not gain any due to its 'non standard landing' nature. For Lv-624, the lower two floodlights have been pushed one tile away from the landing zone for consistency.

Fixes Issue #3427 

# Explain why it's good for the game

Fixes glaring issues with landing lights on many maps being out of order, not working or flashing in a odd way. Addition of landing lights to Shivas Snowball brings it up to standard with every other LZ. 

# Testing Photographs and Procedure
![New LZ 1](https://github.com/cmss13-devs/cmss13/assets/6595389/ff4a4f88-6e15-4fe5-99bf-3393757f1f45)
New LZ1 appearance. 

# Changelog
:cl:
maptweak: Fixed landing strip lights on most maps
/:cl:

2023-06-05 17:47 UTC, Steelpoint commented
First PR in 5 years so be gentle.

2023-06-05 23:25 UTC, Drulikar requested changes
Much better, though many of the landing delays sporadically repeat (as in two delayones next to eachother: e.g. center left for LZ1 soro, and top right for LZ2 soro). It's easiest to identify this problem by using the type filters in strongdmm to only highlight each type individually.
![image](https://github.com/cmss13-devs/cmss13/assets/76988376/f3fab342-6686-4333-85bc-06d731a0fea4)
![image](https://github.com/cmss13-devs/cmss13/assets/76988376/844bef38-09dd-4539-a4e4-0a948bbe90f2)
![image](https://github.com/cmss13-devs/cmss13/assets/76988376/fe41d995-f7bb-42c0-b33c-45803c7e162f)
![image](https://github.com/cmss13-devs/cmss13/assets/76988376/39dcc5f0-cfe2-4d5a-a3d5-15a2f8a766e7)
etc.

2023-06-06 03:16 UTC, Steelpoint commented
I think some of those are due to the landing zones not being big enough for the light pattern to be completed (goes ds1 > 3 > 2 > 1 > repeat), I'll double check the maps to ensure they are as good as I can make.

2023-06-06 04:21 UTC, Steelpoint commented
I've done a second pass, I believe I've fixed the remaining outstanding issues.

I did effect a small change to the LZ's on Desert Dam. Decreasing the LZ size by 1 tile in length at the top.

![Screenshot 2023-06-06 12 20 30](https://github.com/cmss13-devs/cmss13/assets/6595389/08763531-5f9f-4326-9706-346ec358f594)
LZ1

![Screenshot 2023-06-06 12 20 25](https://github.com/cmss13-devs/cmss13/assets/6595389/624a6faf-3b62-43b1-ad0d-01a49edbb36a)
LZ2

2023-06-06 07:07 UTC, Drulikar requested changes
LV624, Kutjevo, and Desert Dam should be good now.

2023-06-06 07:07 UTC, Drulikar commented on maps/map_files/FOP_v3_Sciannex/Fiorina_SciAnnex.dmm
LZ1 is fine.
LZ2 has two errors: 
![Fiorina LZ2](https://github.com/cmss13-devs/cmss13/assets/76988376/fe03d594-d71b-47aa-923b-dadc02b1f857)

2023-06-06 07:18 UTC, Steelpoint commented
Fixed the outstanding issues.

2023-06-06 07:51 UTC, Drulikar approved these changes

2023-06-07 06:34 UTC, merged