Impaler Burrower strain (with fixes)
cmss13-devs/cmss13 pull request #3565
Opened 2023-06-08 11:18 UTC by Unknownity

# About the pull request

First of all, thank you Kugamo for making the sprites for the strain and its effects.

https://streamable.com/4m3rbr (some things are changed since this video)

A burrower strain that can deal damage while burrowed, causing enemies to have to be creative when attacking, removing its weeds will force it to surface.

Impaler abilities:
Burrowed Spikes:
Description: Sends out fast spikes in a direction that hits tile by tile.
Cost: 50 Plasma
Cooldown: 8 Seconds.
Range: 5 Tiles
Damage: 35
Can be used while burrowed.

Sunken Tail:
Description: After a windup, strikes the targeted area damaging anyone in the tile.
Cost: 100 Plasma
Cooldown: 13 seconds.
Range: 7
Damage: 60
Windup: .8 Seconds

Ensconce:
Description: After a windup, go halfway into the ground in a fortified stance (prevents you from moving) which increases your vision range by 3, increases your Burrowed spikes ability range by 2, increases your Sunken Tail ability range by 2, and damage on both abilities by 30.
Modifies Sunken Tail to do an AoE effect:
https://streamable.com/xy0tq1 (middle is full damage + ensconce'ed damage bonus, edges are normal damage)

Cost: None
Cooldown: 3 Seconds
Buffs: Armor deflection increased by 25 and armor explosive resistance increased by 50 and small explosives cannot stun the target while in the stance.

Base Tail Stab:
Can be used while burrowed.

# Explain why it's good for the game

New (actually balanced on launch) xeno content which they need.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl: Unknownity, Kugamo
add: Added new strain for the Burrower, "Impaler".
fix: Fixed burrowed mobs being able to be targeted by sentries, mines and SG autofire.
fix: Fixed burrowed mobs being able to grab mobs on the surface.
fix: Fixed burrowed mobs being able to resist while burrowed.
fix: Fixed burrowers taking damage from direct flame and shrapnel from explosions.
fix: Fixed burrowers being able to get slashed from enemy Xenos on the surface.
fix: Fixed burrowers unburrow stun to now properly target and stun enemy Xenos.
soundadd: Added sounds for base and Impaler burrower for burrowing and unburrowing, added sounds for Impaler burrower's attacks.
imageadd: Added sprites and effects for Impaler burrower by Kugamo.
/:cl:

2023-06-08 12:27 UTC, harryob commented on code/modules/mob/living/carbon/xenomorph/mutators/strains/burrower/impaler.dm
> +		/datum/action/xeno_action/onclick/ensconce
```suggestion
		/datum/action/xeno_action/onclick/place_trap,
	)
	mutator_actions_to_add = list(
		/datum/action/xeno_action/activable/burrowed_spikes,
		/datum/action/xeno_action/activable/sunken_tail,
		/datum/action/xeno_action/onclick/burrow,
		/datum/action/xeno_action/onclick/ensconce,
```

2023-06-08 16:52 UTC, BeagleGaming1 commented on code/game/machinery/doors/airlock_types.dm
> +/obj/structure/machinery/door/airlock/dropship_hatch/initialize_pass_flags(var/datum/pass_flags_container/PF)
```suggestion
/obj/structure/machinery/door/airlock/dropship_hatch/initialize_pass_flags(datum/pass_flags_container/PF)
```
You can't do var/ in these places anymore

2023-06-08 16:52 UTC, BeagleGaming1 commented on code/game/machinery/doors/multi_tile.dm
> +/obj/structure/machinery/door/airlock/multi_tile/almayer/dropshiprear/initialize_pass_flags(var/datum/pass_flags_container/PF)
```suggestion
/obj/structure/machinery/door/airlock/multi_tile/almayer/dropshiprear/initialize_pass_flags(datum/pass_flags_container/PF)
```

2023-06-08 16:52 UTC, BeagleGaming1 commented on code/game/machinery/doors/poddoor.dm
> +/obj/structure/machinery/door/poddoor/shutters/almayer/locked/initialize_pass_flags(var/datum/pass_flags_container/PF)
```suggestion
/obj/structure/machinery/door/poddoor/shutters/almayer/locked/initialize_pass_flags(datum/pass_flags_container/PF)
```

2023-06-08 16:52 UTC, BeagleGaming1 commented on code/game/machinery/doors/shutters.dm
> +/obj/structure/machinery/door/poddoor/shutters/almayer/pressure/initialize_pass_flags(var/datum/pass_flags_container/PF)
```suggestion
/obj/structure/machinery/door/poddoor/shutters/almayer/pressure/initialize_pass_flags(datum/pass_flags_container/PF)
```

2023-06-08 16:52 UTC, BeagleGaming1 commented on code/game/objects/structures.dm
> +/obj/structure/initialize_pass_flags(var/datum/pass_flags_container/PF)
```suggestion
/obj/structure/initialize_pass_flags(datum/pass_flags_container/PF)
```

2023-06-08 16:52 UTC, BeagleGaming1 commented on code/modules/mob/living/carbon/xenomorph/abilities/burrower/burrower_powers.dm
> +/mob/living/carbon/xenomorph/proc/process_burrow_impaler(var/turf/T = get_turf(src))
```suggestion
/mob/living/carbon/xenomorph/proc/process_burrow_impaler(turf/T = get_turf(src))
```

2023-06-08 16:52 UTC, BeagleGaming1 commented on code/modules/mob/living/carbon/xenomorph/abilities/burrower/burrower_powers.dm
> +/datum/action/xeno_action/activable/burrowed_spikes/proc/handle_damage(var/mob/living/carbon/xenomorph/X, target_turfs, telegraph_atom_list, damage)
```suggestion
/datum/action/xeno_action/activable/burrowed_spikes/proc/handle_damage(mob/living/carbon/xenomorph/X, target_turfs, telegraph_atom_list, damage)
```

2023-06-08 16:52 UTC, BeagleGaming1 commented on code/modules/mob/living/carbon/xenomorph/abilities/burrower/burrower_powers.dm
> +/datum/action/xeno_action/activable/sunken_tail/proc/handle_damage(var/mob/living/carbon/xenomorph/X, target_turfs, damage, var/spike_circle = FALSE)
```suggestion
/datum/action/xeno_action/activable/sunken_tail/proc/handle_damage(mob/living/carbon/xenomorph/X, target_turfs, damage, var/spike_circle = FALSE)
```

2023-06-08 16:52 UTC, BeagleGaming1 commented on code/modules/mob/living/carbon/xenomorph/abilities/burrower/burrower_powers.dm
> +/datum/action/xeno_action/onclick/ensconce/proc/fortify_switch(var/mob/living/carbon/xenomorph/X, var/fortify_state)
```suggestion
/datum/action/xeno_action/onclick/ensconce/proc/fortify_switch(mob/living/carbon/xenomorph/X, var/fortify_state)
```

2023-06-08 16:52 UTC, BeagleGaming1 commented on code/modules/mob/living/carbon/xenomorph/abilities/burrower/burrower_powers.dm
> +/datum/action/xeno_action/onclick/ensconce/proc/process_ensconce(var/mob/living/carbon/xenomorph/xeno)
```suggestion
/datum/action/xeno_action/onclick/ensconce/proc/process_ensconce(mob/living/carbon/xenomorph/xeno)
```

2023-06-08 19:24 UTC, BeagleGaming1 commented on code/modules/mob/living/carbon/xenomorph/abilities/burrower/burrower_powers.dm
> +/datum/action/xeno_action/activable/sunken_tail/proc/handle_damage(mob/living/carbon/xenomorph/X, target_turfs, damage, var/spike_circle = FALSE)
```suggestion
/datum/action/xeno_action/activable/sunken_tail/proc/handle_damage(mob/living/carbon/xenomorph/X, target_turfs, damage, spike_circle = FALSE)
```
Guess I missed a few

2023-06-08 19:24 UTC, BeagleGaming1 commented on code/modules/mob/living/carbon/xenomorph/abilities/burrower/burrower_powers.dm
> +/datum/action/xeno_action/onclick/ensconce/proc/fortify_switch(mob/living/carbon/xenomorph/X, var/fortify_state)
```suggestion
/datum/action/xeno_action/onclick/ensconce/proc/fortify_switch(mob/living/carbon/xenomorph/X, fortify_state)
```

2023-06-08 19:28 UTC, BeagleGaming1 commented on colonialmarines.dme
> +#include "code\modules\mob\living\carbon\xenomorph\mutators\strains\burrower\impaler.dm"
Linter also gets angry if this isn't in alphabetical order

2023-06-08 20:01 UTC, BeagleGaming1 commented on code/modules/mob/living/carbon/xenomorph/abilities/burrower/burrower_abilities.dm
>  	var/mob/living/carbon/xenomorph/X = owner
single letter var

2023-06-08 20:01 UTC, BeagleGaming1 commented on code/modules/mob/living/carbon/xenomorph/abilities/burrower/burrower_abilities.dm
>  /datum/action/xeno_action/activable/burrow/use_ability(atom/A)
single letter var

2023-06-08 20:46 UTC, Unknownity commented on code/modules/mob/living/carbon/xenomorph/abilities/burrower/burrower_powers.dm
> +	return
scroll up

2023-06-08 20:48 UTC, Unknownity commented on code/modules/mob/living/living_verbs.dm
> +		var/mob/living/carbon/xenomorph/Xeno = src
meant to not be a snake case iirc (is_xeno and isxeno are different afaik) correct me if wrong

2023-06-09 12:13 UTC, harryob requested changes

2023-06-09 12:13 UTC, harryob commented on code/modules/mob/living/carbon/xenomorph/abilities/burrower/burrower_powers.dm
> +	if(xeno.burrow) return FALSE
```suggestion
	if(!xeno) 
		return
	if(xeno.burrow) 
		return FALSE
```

2023-06-21 22:44 UTC, Venuska1117 commented
Yo, after playing it i found some issues, one of it is...
membranes block your range attack if you are in forify mode.

2023-06-22 10:52 UTC, Unknownity commented
> Yo, after playing it i found some issues, one of it is... membranes block your range attack if you are in forify mode.
> 
> _and i really want to be able use single stab skill when burrowed, aww..._

intended, spikes can only go through window frames/windows and airlocks.
also tail stab not working on regular burrow is also intended based on a previous balance change, I only added it back for Impaler as they aren't entirely underground and provides risk due to being in melee weed removal range (aka they have counterplay)

2023-06-22 11:38 UTC, Venuska1117 commented
> > Yo, after playing it i found some issues, one of it is... membranes block your range attack if you are in forify mode.
> > _and i really want to be able use single stab skill when burrowed, aww..._
> 
> intended, spikes can only go through window frames/windows and airlocks. also tail stab not working on regular burrow is also intended based on a previous balance change, I only added it back for Impaler as they aren't entirely underground and provides risk due to being in melee weed removal range (aka they have counterplay)

yes but the ground tail stab, when you are foryfied don't work if you have membrane in front of you, it think its wall.

2023-06-23 18:28 UTC, morrowwolf reviewed
Heya!

I got some questions for ya I'd like you to fill out:

Gameplay:
Does it feel good to use?
Does it feel good to play against?
Does it affect other systems?

Roleplay:
Does it increase immersion?
Does it increase communication/interaction between players?

Simulation:
Does it fit in the CM universe aesthetically?
Does it fit in the lore of CM?

2023-06-23 21:10 UTC, Unknownity commented
> Heya!
> 
> I got some questions for ya I'd like you to fill out:
> 
> Gameplay: Does it feel good to use? Does it feel good to play against? Does it affect other systems?
> **Its attacks are telegraphed and readable, have time to react against and are only strong when the strain uses the ability which locks them in place which makes them vulnerable to attacks, there are two ways of counterplay against the strain, one is more of a skill equals reward which is sprite click shooting the borrower to damage it, the other is removing the weeds to force it out. Playing against is equal to a boiler, it is annoying but not impossible. as time goes on, players will be able to adapt to the meta against the strain. The strain has been nerfed several times up until this iteration. The only existing issue regarding it is the way how fire affects weeds, it does not instantly remove them which means the borrower has a grace period of being able to move across the flamed tiles before the weeds go away and not be forcibly surfaced, so the only way of instantly flushing them out is through meleeing the tiles, spraying chemicals containing a specific property that removes weeds and explosions. I do not want to change how fire and small explosions affect weeds as that is a massive balance change but If I'm gonna throw my opinion on this is that yes, fire should instantly remove weeds. (except green)**
> Roleplay: Does it increase immersion? Does it increase communication/interaction between players?
> **The strain is more immersive than the original that's for sure, as for the second question I am unable to answer in full confidence due to a lack of observational data, in theory, it should be like a boiler-lite in terms of communication/interaction between the xenomorphs.**
> Simulation: Does it fit in the CM universe aesthetically? Does it fit in the lore of CM?
> **Since Burrowers do not actually exist in the Aliens media, all we have is CM's iteration of what a Burrower is. the original strain of the Burrower is a combat support caste, primarily intended to assist xenomorphs fast traveling around the map with tunnels, fortifying key locations and assisting backliners in general, it is able to solo but not as effective as a lurker against more than 1-2 marines. The Impaler strain is the opposite, instead of combat supporting backliners, it is now a frontline combat support caste (while the original could assist in frontlines, it's usually a waste of their potential). Its advantage is helping in defending the xeno side of the frontline if marines push by slowing them down through its telegraphed attacks and when xenos start advancing, it provides additional pressure to the marines by acting as sort of a mobile environmental hazard.
While the strain is a direct inspiration from the Starcraft lurker, it wouldn't be too far off a xenomorph considering one of their main weapons are their tails, this one simply specialized to ONLY use its tail as its weapon of choice. It only being able to burrow while on weeds is merely a gameplay limitation for balance.**
> Bear in mind, these don't all need to be yes. Just curious what your take on it is.

2023-06-26 12:18 UTC, ihatethisengine commented
I think another way to solve flame vs. weeds issue is just to make burrower vulnerable to fire even if burrowed. So impaler would be forced to disengage, surface and resist. This will create an easy and effective way to fight impalers and probably reduce the amount of salt.

2023-06-27 10:10 UTC, Venuska1117 commented
> I think another way to solve flame vs. weeds issue is just to make impaler vulnerable to fire even if burrowed. So impaler would be forced to disengage, surface and resist. This will create an easy and effective way to fight impalers and probably reduce the amount of salt.

its like said to burn whole fish in water if only their fin stick out of water.|

Just make fire deal damage to them if they on burning tiles but dont ignite burrower (with make more sense)

2023-07-02 15:52 UTC, sleepynecrons approved these changes
sprites approved

2023-07-05 06:22 UTC, morrowwolf requested changes
Alright, this is not gonna be what anyone wants to hear: I'm not sure I like the strain.

I feel it is frustrating to fight.
I feel adding more ranged options for xenos is the opposite of the direction we should be going.
I feel the lurker sounds and inspiration are a little too on the nose for our setting.

Some of this I can overlook. The one thing I can't overlook is another ranged strain for xenos. I'm happy to see spikes or moving around underground as it is but it has to be much closer range.

If you can overcome those requirements we can take a look again. Sadly, this is going to require pretty much an entire rework.

2023-07-05 09:23 UTC, Venuska1117 commented
> Alright, this is not gonna be what anyone wants to hear: I'm not sure I like the strain.
> 
> I feel it is frustrating to fight. I feel adding more ranged options for xenos is the opposite of the direction we should be going. I feel the lurker sounds and inspiration are a little too on the nose for our setting.
> 
> Some of this I can overlook. The one thing I can't overlook is another ranged strain for xenos. I'm happy to see spikes or moving around underground as it is but it has to be much closer range.
> 
> If you can overcome those requirements we can take a look again. Sadly, this is going to require pretty much an entire rework.

this strain was hard to play when it was TM, because marines used granades, flamethrower, and they just obligerated you if you were not careful enough, yes it have ranged skill (the impale), but it make you immobile in one spot, and you cant be behind objects, with make you vonurelable, when you walk it just create 1x1 with is not effective as it sound, when you move while burrowed, spikes wave don't go trough cades, its only good when marines are out of cades, but because of slow attack and attack zone indicator most of time they just avoid it, not to mention if you somehow get out of weeds you are 80% times dead, i saw like 3 impaler burrowers die in like 10min into fight because of nades/mortars/clusterOB (anything that make them go out weeds)

But i can agree that its hard to hit when burrowed it can get increased hit chance when burrower is closer to marines gunfire (more easy to hit)

2023-07-05 19:30 UTC, closed without merging

2023-07-06 20:31 UTC, Comxy commented
NOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO

2023-07-07 08:23 UTC, IsDogHour commented
The best looking addition to the xeno side of CM in a long time gone. How depressing.

2023-07-10 11:33 UTC, MPhonks commented
Actually sad.