Adds smartgun HEAP ammunition + edits Whiteout Terminator loadout to accommodate
cmss13-devs/cmss13 pull request #3572
Opened 2023-06-09 04:27 UTC by VashVandez

# About the pull request

This PR adds a new ammunition type to the M56 smartgun, compatible with all variants: high-explosive armor-piercing (HEAP). Always wondered why the smartgun didn't have this ammunition like other guns do, considering it's more-or-less designed to be the "movie-accurate ammo" that rips things to shreds, at least I think it is. 

To ensure it has a place in the game, this PR also edits the Whiteout Terminator's loadout so that the elite variant of the smartgun comes pre-loaded with this ammunition type, and the Whiteout Terminator themselves now carry this ammo in all their storage containers. 

# Explain why it's good for the game

![fd92c48740bb8074e7593df574d88bb8](https://github.com/cmss13-devs/cmss13/assets/132308648/c9a5120d-c613-40a6-9fb3-415f116c5e69)

It'll ensure that whiteout teams are just ever so slightly more broken than they already are!

Open to suggestions on changes to the ammo stats for balance purposes, though I imagine Whiteout vs Xeno skirmishes are very rare anyway. This ammo does make the smartgun pretty damn busted, though, gotta be honest. Tried it in a private game. 

<summary>Screenshots & Videos</summary>

![nSFNuou](https://github.com/cmss13-devs/cmss13/assets/132308648/30e49fae-8960-4c6f-9800-4ce4e28b2c9f)
![oOu4tBv](https://github.com/cmss13-devs/cmss13/assets/132308648/686940a4-b6d7-4136-ba63-dc21b9310666)

Sprites for the HEAP drums. 

</details>

# Changelog

:cl:
add: adds the HEAP ammunition for the smartgun so the M56 isn't left out of the broken ammo party. 
balance: not at all.
fix: also fixed a minor type in the description for the dirty smartgun drum. 
code: edited various files to include this new ammo/drum type, including editing the elite smartgun and the whiteout terminator loadout. 
imageadd: updated the ammo sprites to include the smartgun HEAP drum, both loaded and empty.
/:cl:

2023-06-09 04:42 UTC, BeagleGaming1 commented
It would be a "spellcheck" instead of a "fix" for the ammo typo

2023-06-09 04:43 UTC, VashVandez commented
yep edited

2023-06-09 10:37 UTC, fira commented
balance: not at all ?

2023-06-09 10:38 UTC, fira commented
i don't know about this in general. it brings no real functionality in regard to current ammo swap and just snowflakes the elite SG. it'd be good to have ammo swapping expanded for this...

2023-06-09 18:57 UTC, Zonespace27 requested changes

2023-06-09 18:57 UTC, Zonespace27 commented on code/game/objects/items/storage/pouch.dm
> +	for(var/i = 1 to storage_slots)
```suggestion
	for(var/i in 1 to storage_slots)
```

2023-06-15 04:57 UTC, morrowwolf commented
This is literally never going to be allowed to be used if we keep buffing these ERTs.

2023-06-15 04:57 UTC, closed without merging