Synthetic maintenance case
cmss13-devs/cmss13 pull request #3582
Opened 2023-06-09 20:23 UTC by Mister-moon1

# About the pull request
Adds a weak form of nano-paste, a tool able to remove shrapnel and a synthetic maintenance case as standard issue to working joe

# Explain why it's good for the game
The boot knife is planned for removal from working joe partially because of the fact it is a weapon, the addition of a tool that can remove shrapnel will allow working joes to combat any friendly fire cases without dying from moving.

Furthermore, a weak form of nano-paste is included in the kit, able to
be used by a medic, in which the synthetic will be brought to a revivable amount of health.

This will be compacted into a small kit which will be standard issue for working joes, the intent is for any situation where a working joe is dead that the kit will be used as a field bandage in a sense where the medic takes it from the joe and repairs them with it

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
add: adds a synthetic maintenance case
add: adds a shrapnel removal tool
add: adds a weak form of nano-paste
/:cl:

2023-06-09 20:26 UTC, BeagleGaming1 requested changes

2023-06-09 20:26 UTC, BeagleGaming1 commented on code/game/objects/items/stacks/nanopaste.dm
> +/obj/item/stack/nanopaste/weak/attack(mob/living/M as mob, mob/user as mob)
single letter var

2023-06-09 20:26 UTC, BeagleGaming1 commented on code/game/objects/items/stacks/nanopaste.dm
> +		var/mob/living/silicon/robot/R = M
single letter var

2023-06-09 20:26 UTC, BeagleGaming1 commented on code/game/objects/items/stacks/nanopaste.dm
> +		var/mob/living/carbon/human/H = M
single letter var

2023-06-09 20:26 UTC, BeagleGaming1 commented on code/game/objects/items/stacks/nanopaste.dm
> +		var/obj/limb/S = H.get_limb(user.zone_selected)
single letter var

2023-06-09 20:30 UTC, BeagleGaming1 commented on code/modules/gear_presets/synths.dm
> +	H.equip_to_slot_or_del(new /obj/item/storage/synthetic_maintenance_case/regular(H), WEAR_IN_BACK)
```suggestion
	new_human.equip_to_slot_or_del(new /obj/item/storage/synthetic_maintenance_case/regular(new_human), WEAR_IN_BACK)
```

2023-06-09 20:44 UTC, BeagleGaming1 commented on code/game/objects/items/storage/toolbox.dm
> +obj/item/storage/synthetic_maintenance_case
```suggestion
/obj/item/storage/synthetic_maintenance_case
```

2023-06-09 22:24 UTC, harryob requested changes

2023-06-09 22:24 UTC, harryob commented on code/game/objects/items/stacks/nanopaste.dm
> +/obj/item/stack/nanopaste/weak/attack(mob/living/Mob as mob, mob/user as mob)
dont copy paste entire procs to change some number - make var/heal_amount on the parent type and adjust it on the subtype, and use heal_amount in the parent attack proc

2023-06-09 22:24 UTC, harryob commented on code/game/objects/items/stacks/nanopaste.dm
> +/obj/item/stack/nanopaste/weak/attack(mob/living/Mob as mob, mob/user as mob)
also this isn’t snakecase

2023-06-10 19:05 UTC, Zonespace27 requested changes

2023-06-10 19:05 UTC, Zonespace27 commented on code/game/objects/items/stacks/nanopaste.dm
> +/obj/item/stack/nanopaste/weak/attack(mob/living/Mob as mob, mob/user as mob)
`as thing` does nothing; args/vars should be lower case

2023-06-10 19:05 UTC, Zonespace27 commented on code/game/objects/items/stacks/nanopaste.dm
> +		return 0
use bool defines

2023-06-10 19:05 UTC, Zonespace27 commented on code/game/objects/items/stacks/nanopaste.dm
> +		if (synth.getBruteLoss() || synth.getFireLoss() )
```suggestion
		if (synth.getBruteLoss() || synth.getFireLoss())
```

2023-06-10 19:05 UTC, Zonespace27 commented on code/game/objects/items/stacks/nanopaste.dm
> +			user.visible_message(SPAN_NOTICE("\The [user] applied some [src] at [synth]'s damaged areas."),\
```suggestion
			user.visible_message(SPAN_NOTICE("[user] applies some [src] on [synth]'s damaged areas."),\
```

2023-06-10 19:05 UTC, Zonespace27 commented on code/game/objects/items/stacks/nanopaste.dm
> +				SPAN_NOTICE("You apply some [src] at [synth]'s damaged areas."))
```suggestion
				SPAN_NOTICE("You apply some [src] on [synth]'s damaged areas."))
```

2023-06-10 19:05 UTC, Zonespace27 commented on code/game/objects/items/stacks/nanopaste.dm
> +			to_chat(user, SPAN_NOTICE("All [synth]'s systems are nominal."))
```suggestion
			to_chat(user, SPAN_NOTICE("All of [synth]'s systems are fully working."))
```

2023-06-10 19:05 UTC, Zonespace27 commented on code/game/objects/items/stacks/nanopaste.dm
> +	if (istype(Mob,/mob/living/carbon/human)) //Repairing robolimbs
ishuman macro

2023-06-10 19:05 UTC, Zonespace27 commented on code/game/objects/items/stacks/nanopaste.dm
> +		if(isspeciessynth(H) && Mob == user && !H.allow_gun_usage)
`!H.allow_gun_usage`
why?

2023-06-10 19:05 UTC, Zonespace27 commented on code/game/objects/items/stacks/nanopaste.dm
> +		var/mob/living/carbon/human/H = Mob
one letter variable

2023-06-10 19:05 UTC, Zonespace27 commented on code/game/objects/items/stacks/nanopaste.dm
> +			to_chat(H, SPAN_WARNING("Your programming forbids you from self-repairing with \the [src]."))
```suggestion
			to_chat(H, SPAN_WARNING("Your programming forbids you from self-repairing with [src]."))
```

2023-06-10 19:05 UTC, Zonespace27 commented on code/game/objects/items/stacks/nanopaste.dm
> +		if (S && (S.status & (LIMB_ROBOT|LIMB_SYNTHSKIN)))
```suggestion
		if(S?.status & (LIMB_ROBOT|LIMB_SYNTHSKIN))
```

2023-06-10 19:05 UTC, Zonespace27 commented on code/game/objects/items/stacks/nanopaste.dm
> +				S.heal_damage(6, 6, robo_repair = 1)
```suggestion
				S.heal_damage(6, 6, robo_repair = TRUE)
```

2023-06-10 19:05 UTC, Zonespace27 commented on code/game/objects/items/stacks/nanopaste.dm
> +				var/user_msg = "You apply some nanite paste at [user == Mob ? "your" : "[Mob]'s"] [S.display_name]."
why are these variables

2023-06-10 19:05 UTC, Zonespace27 commented on code/game/objects/items/stacks/nanopaste.dm
> +				to_chat(user, SPAN_NOTICE("Nothing to fix here."))
```suggestion
				to_chat(user, SPAN_NOTICE("There is nothing to fix here!"))
```

2023-06-10 19:05 UTC, Zonespace27 commented on code/game/objects/items/stacks/nanopaste.dm
> +				var/others_msg = "\The [user] applies some nanite paste at[user != Mob ? " \the [Mob]'s" : " \the"] [S.display_name] with \the [src]."
```suggestion
				var/others_msg = "[user] applies some [src] on [H]'s [S.display_name]."
```

2023-06-10 19:42 UTC, Mister-moon1 commented
After consideration and the fact that 2 nanopaste rolls were going to be in the case, i have lowered the amount to 1 roll and switched it out for normal nanopaste since it will heal for similar amounts

2023-06-18 11:44 UTC, Zonespace27 requested changes

2023-06-18 11:44 UTC, Zonespace27 commented on code/game/objects/items/storage/toolbox.dm
> +/obj/item/storage/synthetic_maintenance_case/regular/fill_preset_inventory()
At this point just remove the subtype

2023-07-01 02:00 UTC, closed without merging