Adds a CL-exclusive pistol, the ES-4.
cmss13-devs/cmss13 pull request #3583
Opened 2023-06-09 23:31 UTC by NewyearnewmeUwu

# About the pull request
This PR adds a CL- and therefore WY - exclusive pistol. The ES-4 is a Weyland Corp manufactures less-lethal pistol that's essentially a reskin of the 88 mod 4 that only fires less-lethal projectiles. Sprites by the fantastic @thwompa 

# Explain why it's good for the game
The pistol uses distinct blue muzzle flashes for its firing so that it's easier to distinguish it from normal guns, and it comes straight from the Aliens RPG. It also looks cool and makes it harder for the CL to get a lethal firearm straight off the bat.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
add: Added the ES-4 electrostatic pistol to the CL's safe.
/:cl:

2023-06-09 23:35 UTC, thwompa commented
lets gooo!!!!

2023-06-12 04:21 UTC, MusselMain commented
seems like a weapon that will fit ML better, allowing CL to be armed shipside, but making sense lore wise. As it wouldn't sense for civilians aboard a military vessel to be armed unless deploying or on code blue/red.

2023-06-12 08:16 UTC, harryob approved these changes
code looks fine

2023-07-17 19:29 UTC, FransFeiffer approved these changes
Sprites are fine, LGTM

2023-07-18 23:26 UTC, Drulikar requested changes

2023-07-18 23:26 UTC, Drulikar commented on code/modules/projectiles/guns/pistols.dm
> +
```suggestion
```

This code is duplicated code in above lines, and yes the code executes both.

2023-07-19 00:10 UTC, merged

2023-07-19 00:54 UTC, cm13live commented
This pull request has been mentioned on **CM-SS13**. Please provide feedback here:

https://forum.cm-ss13.com/t/weapon-restrictions-in-sop/2387/16