Fixes a runtime when observing before roundstart
cmss13-devs/cmss13 pull request #3589
Opened 2023-06-11 00:18 UTC by morrowwolf

# About the pull request

WHAT MODE

HOW DO WE EXIST

# Explain why it's good for the game

Bug bad

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl: Morrow
fix: Fixed a runtime when observing before roundstart
/:cl:

2023-06-11 07:48 UTC, fira requested changes
Nonononono this is a real error, you can't fix it like this (or i'd already have, i'm lazy), because this means people that observed won't know it's a pred round once the game starts... 

you'd need to also call toggle_predator_action on starting the game

2023-06-11 12:44 UTC, morrowwolf commented
My hubris

2023-06-12 08:13 UTC, harryob requested changes
😎

2023-06-12 08:13 UTC, harryob commented on code/modules/mob/dead/observer/observer.dm
> +	if(SSticker.mode && SSticker.mode.flags_round_type & MODE_PREDATOR)
```suggestion
	if(!SSticker.mode)
		SSticker.OnRoundstart(CALLBACK(src, PROC_REF(toggle_predator_action))
		return

	if(SSticker.mode.flags_round_type & MODE_PREDATOR)
```

2023-06-13 06:19 UTC, harryob requested changes

2023-06-13 06:19 UTC, harryob commented on code/modules/mob/dead/observer/observer.dm
> +		SSticker.OnRoundstart(CALLBACK(src, PROC_REF(toggle_predator_action))
```suggestion
		SSticker.OnRoundstart(CALLBACK(src, PROC_REF(toggle_predator_action)))
```

2023-06-14 18:52 UTC, harryob approved these changes

2023-06-14 19:42 UTC, merged