Limits view range of large crate destroy message.
cmss13-devs/cmss13 pull request #3594
Opened 2023-06-11 10:54 UTC by TheGamerdk

# About the pull request

Oversight in message flags, fixes #3387

# Explain why it's good for the game

Bugs aren't so good

</details>

# Changelog

:cl:
fix: Xenos are no longer notified each time a sister destroys a large crate.
/:cl:

2023-06-11 10:55 UTC, harryob approved these changes
evidently this was a hive critical message everyone Needed to know

2023-06-11 13:44 UTC, fira requested changes

2023-06-11 13:44 UTC, fira commented on code/game/objects/structures/crates_lockers/largecrate.dm
> +					  SPAN_DANGER("You smash [src] apart!"), 5, message_flags = CHAT_TYPE_XENO_COMBAT)
Uh wait, there's more, this uses the /mob variant of visible_message() which has a different signature

`/mob/visible_message(message, self_message, blind_message, max_distance, message_flags = CHAT_TYPE_OTHER)`

you need to add the blind_message or a null in there to match, it's all off by one, not juste the message_flags

2023-06-12 07:08 UTC, TheGamerdk commented on code/game/objects/structures/crates_lockers/largecrate.dm
> +					  SPAN_DANGER("You smash [src] apart!"), 5, message_flags = CHAT_TYPE_XENO_COMBAT)
```suggestion
					  SPAN_DANGER("You smash [src] apart!"), null, 5, CHAT_TYPE_XENO_COMBAT)
```

2023-06-12 08:05 UTC, merged