You can now use the Ghost verb when nested and still return to your body when freed
cmss13-devs/cmss13 pull request #3597
Opened 2023-06-11 10:58 UTC by TheGamerdk

# About the pull request

This is just confusing. Fixes #1375

# Explain why it's good for the game

Less confusion good

</details>

# Changelog

:cl:
fix: You'll now be allowed to reenter your nested body when freed, even if you used the ghost verb.
/:cl:

2023-06-11 11:01 UTC, harryob requested changes

2023-06-11 11:01 UTC, harryob commented on code/modules/mob/dead/observer/observer.dm
> +			text_prompt += "\nSince you're nested, you will be given a chance to reenter you body upon being freed."
```suggestion
			text_prompt += "\nSince you're nested, you will be given a chance to reenter your body upon being freed."
```

2023-06-11 11:32 UTC, Huffie56 commented
just want to point out this issue that is related in case you didn't saw it....
unsure if your PR fix it?
https://github.com/cmss13-devs/cmss13/issues/1552

2023-06-11 13:38 UTC, fira requested changes
This is the same way the nests themselves do it, and as noted in the linked issue it appears to sometimes fail for some reason - players in ahelps report they click yes on the nest prompt and can't reenter (i made extra sure, but could never reproduce myself)

This is still a good step forward in being less confusing to people

You should check nest also after the alert to avoid race conditions though

2023-06-11 14:59 UTC, TheGamerdk commented
> This is the same way the nests themselves do it, and as noted in the linked issue it appears to sometimes fail for some reason - players in ahelps report they click yes on the nest prompt and can't reenter (i made extra sure, but could never reproduce myself)
> 
> This is still a good step forward in being less confusing to people
> 
> You should check nest also after the alert to avoid race conditions though

Cursory glance at code shows it should be fine unless your ghost is recreated (which is possible, might be more wise to use the mind, that shouldn't get recreated iirc)

Added a race check condition to the ghostize() call

2023-06-11 19:06 UTC, fira commented on code/modules/mob/dead/observer/observer.dm
> +		var/nest
need typing here to avoid errors

2023-06-11 20:26 UTC, TheGamerdk commented on code/modules/mob/dead/observer/observer.dm
> +		var/nest
```suggestion
		var/obj/structure/bed/nest/nest
```

2023-06-13 08:53 UTC, harryob approved these changes

2023-06-13 09:05 UTC, merged