Sentries now work correctly on dropships
cmss13-devs/cmss13 pull request #3599
Opened 2023-06-11 11:02 UTC by TheGamerdk

# About the pull request

The sentries work by creating bounds and using those to check if anyone is in range. Since X and Y coordinates change when the dropships move, this would break until you redeployed the sentry.

Partially fixes #3554 and fixes #436 (Can't reproduce M56D not working)

# Explain why it's good for the game

Bugs bad.

# Testing Photographs and Procedure

# Changelog

:cl:
fix: Sentries now work correctly on dropships.
/:cl:

2023-06-11 11:17 UTC, Huffie56 commented
sentries and M56D aren't suppose to be assemble or use on the DS.
except if they are modular(the one you need to attach via a work-loader)
![image](https://github.com/cmss13-devs/cmss13/assets/117036822/1707d731-3fac-4dad-91a8-f6c898182148)

2023-06-11 11:17 UTC, TheGamerdk commented
> sentries and M56D aren't suppose to be assemble or use on the DS. except if they are modular(the one you need to attach via a work-loader) ![image](https://user-images.githubusercontent.com/117036822/244932391-1707d731-3fac-4dad-91a8-f6c898182148.png)

That's a different issue, this is just fixing that sentries stop working when their position is changed mid-deployment.

2023-06-11 13:31 UTC, fira requested changes
use SIGNAL_HANDLER annotations for signal enabled procs

2023-06-11 13:56 UTC, morrowwolf commented
This doesn't seem to allow sentries on/in shuttles/vehicles but instead fixes sentries breaking down after shuttle movement. Not a balance issue.

2023-06-11 14:53 UTC, TheGamerdk commented
> use SIGNAL_HANDLER annotations for signal enabled procs

Done

2023-06-12 05:57 UTC, harryob approved these changes

2023-06-12 06:45 UTC, merged