XO message should include code of conduct & MAIN_SHIP_NAME define usage
cmss13-devs/cmss13 pull request #3628
Opened 2023-06-14 12:37 UTC by Drulikar

# About the pull request

This PR addresses an oversight where the entry message for an XO makes no mention of the Commander Code of Conduct, which currently has specifics mentioned for XOs. Feel free to edit this PR to get the message exactly how you want it. It also updates entry messages that referred to the USS Almayer as the define MAIN_SHIP_NAME now.

# Explain why it's good for the game

XO's should be linked to information that is relevant to them.

# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

![image](https://github.com/cmss13-devs/cmss13/assets/76988376/baf1eb66-4226-4c52-ba84-3206a39a212a)

</details>

# Changelog
:cl: Drathek
spellcheck: Added Commander Code of Conduct link to XO entry description and fixed CO capitalization.
code: Replaced sting usage for USS Almayer to MAIN_SHIP_DEFAULT_NAME for Souto ERT, CMB ERT, Provost ERT reporters, XO, and CO. 
/:cl:

2023-06-14 16:40 UTC, morrowwolf requested changes

2023-06-14 16:40 UTC, morrowwolf commented on code/game/jobs/job/command/cic/executive.dm
> +	entry_message_body = "<a href='"+URL_WIKI_XO_GUIDE+"'>You are second in command aboard the USS Almayer,</a> and are in next in the chain of command after the Commanding Officer. You must abide by th
XOs only have to abide by parts of the CO COC. Might want to specify.

2023-06-15 04:54 UTC, morrowwolf requested changes
uuuuh last one I promise 😄

2023-06-15 04:54 UTC, morrowwolf commented on code/game/jobs/job/command/cic/executive.dm
> +	entry_message_body = "<a href='"+URL_WIKI_XO_GUIDE+"'>You are second in command aboard the USS Almayer,</a> and are in next in the chain of command after the Commanding Officer. Where applicable, yo
I believe we have a current_ship define somewhere which we should probably use instead of USS Almayer

2023-06-15 08:03 UTC, Drulikar commented
![image](https://github.com/cmss13-devs/cmss13/assets/76988376/e2ac056f-aee8-467e-849b-4fe33b184622)
![image](https://github.com/cmss13-devs/cmss13/assets/76988376/cc013bba-b45d-42ad-914f-546df5d5482f)
![image](https://github.com/cmss13-devs/cmss13/assets/76988376/80209f18-dac5-4044-a082-2ae897e1c79c)

2023-06-15 11:38 UTC, fira commented
MAIN_SHIP_NAME won't work as intended here because RoleAuthority and job datums are instanciated before SSmapping loads the map config

2023-06-16 07:29 UTC, harryob approved these changes

2023-06-16 08:02 UTC, merged