Xeno Candidate Queue
cmss13-devs/cmss13 pull request #3636
Opened 2023-06-15 05:52 UTC by Drulikar

# About the pull request

This PR changes it so get_alien_candidates is normally a sorted list based on timeofdeath in ascending order and larva spawns now pull candidates out of that list in order. That means that an observer that has yet to play, or was the first to die, and still meets all other criteria to become a larva (not afk, has preferences set to become larva, has been dead long enough, etc) will be chosen before others.

# Explain why it's good for the game

Picking candidates randomly is okay, but it would be more fair to give privilege to those that have been waiting longer.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Example of queen death code (since that was the most altered):
![larva](https://github.com/cmss13-devs/cmss13/assets/76988376/48211b1e-7556-4a41-879f-1dfbfabe8704)

</details>

# Changelog

:cl: Drathek
add: The selection to become a xeno larva is now based on timeofdeath rather than random
/:cl:

2023-06-15 07:12 UTC, ihatethisengine commented
Please speedmerge

2023-06-16 07:06 UTC, harryob requested changes

2023-06-16 07:06 UTC, harryob commented on code/modules/mob/living/carbon/xenomorph/death.dm
> +					while(GLOB.hive_datum[hivenumber].stored_larva > 0 && count <= players_with_xeno_pref.len) // stil some left
```suggestion
					while(GLOB.hive_datum[hivenumber].stored_larva > 0 && count <= length(players_with_xeno_pref)) // still some left
```

2023-06-16 21:02 UTC, morrowwolf commented
Let's give this a try!

2023-06-17 12:47 UTC, ihatethisengine commented
Might be a dumb question and I honestly tried to figure it out on my own, but are you sure it sorts from oldest to newest and not the other way around?

2023-06-17 13:16 UTC, Drulikar commented
> Might be a dumb question and I honestly tried to figure it out on my own, but are you sure it sorts from oldest to newest and not the other way around?

Yes I tested this with dummy clients, and it is in the order that existing ascending compares are.

Tried again with two clients, and it worked as expected:
![image](https://github.com/cmss13-devs/cmss13/assets/76988376/f7e118ef-3481-46dd-8694-011b9911da7b)
![image](https://github.com/cmss13-devs/cmss13/assets/76988376/29f7e1a8-87a8-409a-a3dc-6bc5a7a73fab)

2023-06-18 11:54 UTC, morrowwolf commented
If this feels out of scope feel free to not do it but some people have requested a way to view their spot in queue. 🙏

2023-06-18 12:37 UTC, Drulikar commented
> If this feels out of scope feel free to not do it but some people have requested a way to view their spot in queue. 🙏

![image](https://github.com/cmss13-devs/cmss13/assets/76988376/9853fa9a-369d-4a89-8cc3-c02bd5973dab)

Messages are now sent to all other candidates when either a burst occurs or the core spends a stored larva.

2023-06-18 12:41 UTC, morrowwolf commented
Beautiful!

2023-06-18 13:10 UTC, Drulikar commented
Let me know if you'd rather a different metric to be used to be the sort order (likely a queue time that is at least your ToD). It is more fair the current way I think, but people might get confused when their queue number goes up from players who haven't played yet just observe and elect to be a xeno candidate. Their ToD should be 0 so the front of the queue, but they should still be after all other 0 ToD observers unless the sorting algorithm sometimes re-arranges entries with the same value. Last I looked it does not, but the sort method does change when the list is large (uses binarySort when small, otherwise a timSort).

2023-06-18 14:04 UTC, ihatethisengine commented
I think it's fine, you can add a tip that states that player's place in queue can change because of this and that.

2023-06-18 14:20 UTC, morrowwolf commented
> Let me know if you'd rather a different metric to be used to be the sort order (likely a queue time that is at least your ToD). It is more fair the current way I think, but people might get confused when their queue number goes up from players who haven't played yet just observe and elect to be a xeno candidate. Their ToD should be 0 so the front of the queue, but they should still be after all other 0 ToD observers unless the sorting algorithm sometimes re-arranges entries with the same value. Last I looked it does not, but the sort method does change when the list is large (uses binarySort when small (32), otherwise a timSort).

I'm gonna give this time to cook a bit on the server before merging just to see how the community settles in with it. I do think seeing your time in queue go up may be maddening if they don't realize what is happening. Something like just, how long you've been in queue determines when you get a larva may be better. But again, we'll see how things shake out over this week.

2023-06-18 14:24 UTC, ihatethisengine commented
> Something like just, how long you've been in queue determines when you get a larva may be better.
Then relogging or going AFK for a while will make you lose your place in the queue, which is not good. I think the current system is perfect, it just should explain to the player what's going on and why.

2023-06-18 14:38 UTC, Drulikar commented
An alternative way I could convey it would be to also mention if they are in a different queue:
Primary Queue: Players that haven't played yet.
Secondary Queue: Players that have a ToD.

The current functionality would be the same, it's just a modification to the message where it mentions primary if their ToD is 0 otherwise secondary.

Alternatively I count how many 0 ToD people are ahead of the current player and convey that count in the message.

There'll still be some queue jumps as people AFK/DC and then un-AFK/reconnect, but I think the bulk of queue hops will be from new observers.

2023-06-18 18:19 UTC, Tsurupeta commented
Lavra queue makes it so that if you die somewhere midround, your chances of getting lavra are gone, since there are 10 guys before you and xenos lavra acquisition is nerfed.

2023-06-19 06:57 UTC, ihatethisengine commented
Another suggestion: add a message that states your place in queue after the message «You will now be considered for Xenomorph after unrevivable death events (where possible)» and when you join as observer with respective setting turned on. Waiting for next larva to burst to find out how long else you have to wait is not perfect.

2023-06-19 08:34 UTC, Drulikar commented
I don't A) want players toggling that setting rapidly just so they can constantly ping to see where they are now (It will just make queue numbers that much more inaccurate); and B) don't want to introduce spam reduction code to compensate for that.

2023-06-19 14:34 UTC, morrowwolf commented
I almost never get notified about my place in the larva queue. It may be easier just to broadcast the place in line when we get candidates.

2023-06-19 14:45 UTC, ihatethisengine commented
Yeah I saw my place in line yesterday, but today I haven't yet. Maybe I just missed because of ghost chat. Maybe you should add at least a verb that states your place in line.

2023-06-19 17:02 UTC, Drulikar commented
> Yeah I saw my place in line yesterday, but today I haven't yet. Maybe I just missed it because of ghost chat. Maybe you should add at least a verb that states your place in line.

The queue was removed from test merge yesterday night, so no it would be impossible for you to be notified of it today.

2023-06-20 08:49 UTC, ihatethisengine commented
I don't like the fact you lose your place in queue if you go hugger. It kinda discourages to play hugger at all... Not sure if anything can be done here tho.

2023-06-20 23:02 UTC, Drulikar commented
> I don't like the fact you lose your place in queue if you go hugger. It kinda discourages to play hugger at all... Not sure if anything can be done here tho.

I think its fine. The primary thing I wanted to address with a queue is allowing everyone to be able to play the game. I don't see much desire to be a face hugger early - sure maybe you can get a clutch hug on a survivor - but otherwise its going to be a while before marines drop and you have anything to do. So if you've already played as a xeno atleast once and see the hive has really no caps, you can opt to just immediately play now as a hugger assuming the hive is even bothering to create face huggers.

2023-06-21 14:24 UTC, Venuska1117 commented
After playing a little, i offer to tweak this queue, for example: you have 5 xenos vs 30 marines, xenos capture 10 marines but they loose 1 xeno, for example all dead marines want play xeno after death, now you need wait 11th in queue to get chance to go back, i suggest that people who died as xeno, but they go facehugger and successfuly hug, they will be moved up in queue, because for now its too much waiting to play again, on other hands i believe it should be done this way:
A - people who didnt play yet
B - xeno with died and waited long

Queue look:
ABABABAB - if this still look bad it should move you more in queue if you wait very long after death as xeno, because die like 20minutes in, and need wait till hijack (with is actually just end of round) is kinda sad.

2023-06-21 16:45 UTC, ihatethisengine commented
Yeah, apparently when you hug as facehugger you don't have death time. It's a feature, because you can rejoin as hugger again (or roll xeno), it's a reward for successful hugging. I think it's kinda fair.

2023-06-21 17:16 UTC, IsDogHour commented
> Yeah, apparently when you hug as facehugger you don't have death time. I always thought it's a feature, because you can rejoin as hugger again (or roll xeno), it's a reward for successful hugging. I think it's kinda fair.

The goal of the PR is to allow those who have been waiting longer to have priority for fairness, being able to get priority by playing facehugger is not fair. Also hugging a marine isn't difficult at all when you can go sit by a warrior and hug whatever they catch (There are also a good chunk of xeno players who dislike facehuggers doing exactly this).

2023-06-21 17:23 UTC, ihatethisengine commented
> The goal of the PR is to allow those who have been waiting longer to have priority for fairness, being able to get priority by playing facehugger is not fair. Also hugging a marine isn't difficult at all when you can go sit by a warrior and hug whatever they catch (There are also a good chunk of xeno players who dislike facehuggers doing exactly this).

I don't think they dislike huggers for this, I think they dislike huggers for having a really short stun compared to NPC huggers, that makes nesting more difficult. And it doesn't matter if it's difficult or not, still you kinda worked for this.

2023-06-21 19:04 UTC, Venuska1117 commented
> > Yeah, apparently when you hug as facehugger you don't have death time. I always thought it's a feature, because you can rejoin as hugger again (or roll xeno), it's a reward for successful hugging. I think it's kinda fair.
> 
> The goal of the PR is to allow those who have been waiting longer to have priority for fairness, being able to get priority by playing facehugger is not fair. Also hugging a marine isn't difficult at all when you can go sit by a warrior and hug whatever they catch (There are also a good chunk of xeno players who dislike facehuggers doing exactly this).

it make huggers more usefull, but i am mad that i hugged someone and it got taken away by someone else because of "queue" before queue was a thing, if you hugged person, you have high chance to spawn as larva, with i liked as reward for not dying (huggers are litellary paper, one bullet from any range and you are insta dead)

right now even if you succesfully hug someone, it will just get taken away by "priority"

2023-06-21 19:23 UTC, Venuska1117 commented
In Short - The Longer you are in observers, the longer you wait for queue, even hugging as facehugger don't save you, after you die you are just fucked, thats all you get, you die once, and you will probably dont respawn anymore.

2023-06-22 20:03 UTC, morrowwolf requested changes
Little thing, otherwise looks good

2023-06-22 20:03 UTC, morrowwolf commented on code/__HELPERS/game.dm
> +		if(deathtime < (5 MINUTES) && ( !cur_obs.client.admin_holder || !(cur_obs.client.admin_holder.rights & R_ADMIN)) )
5 minute define please

2023-06-22 20:03 UTC, morrowwolf commented on code/__HELPERS/game.dm
> +		if(cur_obs.client.inactivity / (1 MINUTES) > ALIEN_SELECT_AFK_BUFFER + 5)
1 minute define please

2023-06-23 00:25 UTC, morrowwolf approved these changes

2023-06-23 00:31 UTC, Drulikar commented
Looks like a github hiccup getting dependencies?

2023-06-23 02:18 UTC, merged