removed the ability to plant c4 on zombies
cmss13-devs/cmss13 pull request #3637
Opened 2023-06-15 06:18 UTC by Cthulhu80

# About the pull request

Removes the ability to plant c4 on zombies.

# Explain why it's good for the game

"Player c4d three zombies, says not to do so in the join message as well as other places by backsea (SeniorMod) on 2023-06-15 05:43:53" <- asshole.

# Changelog

:cl:
code: removed the ability to c4 zombies.
/:cl:

2023-06-15 08:10 UTC, harryob requested changes

2023-06-15 08:10 UTC, harryob commented on code/game/objects/items/explosives/plastic.dm
> +	// Apparently this is metagaming? Lol.
delete comment

2023-06-15 08:10 UTC, harryob commented on code/game/objects/items/explosives/plastic.dm
> +		to_chat(user, SPAN_WARNING("[target] skin falls off as you attempt to plant the c4"))
```suggestion
		to_chat(user, SPAN_WARNING("[target]'s skin falls off as you attempt to plant the C4!"))
```

2023-06-28 07:23 UTC, Drulikar approved these changes

2023-06-28 07:32 UTC, Drulikar requested changes
Code as it is fine; but lets just make this an admin toggle instead (so also check if that setting is true before this iszombie check). Not only was the quote regarding an event rule, but this honestly is only an issue for the first few zombies. I don't have any strong feelings one way or another what the default is.

2023-07-06 01:56 UTC, closed without merging