adds a visible line when using iv drips / bloodpacks
cmss13-devs/cmss13 pull request #3645
Opened 2023-06-15 18:24 UTC by realkhad

# About the pull request

https://forum.cm-ss13.com/t/giving-blood-shows-visible-line/2610
adds a line between the person receiving blood and where the blood is coming from, similar to the phone cable

# Explain why it's good for the game

soul :]

# Testing Photographs and Procedure

https://github.com/cmss13-devs/cmss13/assets/54692343/293f0c52-13c4-46cd-859d-e49fd65f9589

# Changelog

:cl:Khadd
add: added a iv tube between the user and the bloodpack / iv drip
imageadd: sprites for the iv tube
/:cl:

2023-06-15 18:31 UTC, cm13live commented
This pull request has been mentioned on **CM-SS13**. Please provide feedback here:

https://forum.cm-ss13.com/t/giving-blood-shows-visible-line/2610/2

2023-06-17 14:57 UTC, harryob requested changes

2023-06-17 14:57 UTC, harryob commented on code/game/machinery/iv_drip.dm
> +		current_beam = null
```suggestion
		QDEL_NULL(current_beam)
```

2023-06-17 14:57 UTC, harryob commented on code/game/objects/items/reagent_containers/blood_pack.dm
> +		current_beam = null
```suggestion
		QDEL_NULL(current_beam)
```

2023-06-17 14:57 UTC, harryob commented on code/game/machinery/iv_drip.dm
> +			current_beam = src.beam(attached, beam_icon)
```suggestion
			current_beam = beam(attached, beam_icon)
```

2023-06-18 14:57 UTC, harryob requested changes
nothing further from me, still needs @cmss13-devs/spriters

2023-06-18 14:57 UTC, harryob commented on code/game/machinery/iv_drip.dm
> +	var/datum/beam/current_beam = null
```suggestion
	var/datum/beam/current_beam
```

2023-06-23 17:36 UTC, morrowwolf requested changes
This is really cool! Great addition.

*Sadly*, the red animated beam can look a little... off when standing above someone. I think it'd be best to just go with the basic black beam.

2023-07-02 16:12 UTC, sleepynecrons requested changes
just use iv_beam for both the connection and when it's active. there's no need to show the blood moving and it just looks like something out of cruelty squad. the iv_beam itself also should just use colors from the iv pole
![image](https://github.com/cmss13-devs/cmss13/assets/106241650/a86cda18-9cb9-48f1-bf72-5de5197d7e2d)
something like on the right

2023-07-04 17:09 UTC, sleepynecrons approved these changes
sprite approved

2023-07-04 17:25 UTC, chapterob commented
> sprite approved

My nigga brother in Christ I had to make a new account to tell you that new sprite sucks

2023-07-04 17:39 UTC, realkhad commented
> just use iv_beam for both the connection and when it's active. there's no need to show the blood moving and it just looks like something out of cruelty squad. the iv_beam itself also should just use colors from the iv pole ![image](https://user-images.githubusercontent.com/106241650/250369645-a86cda18-9cb9-48f1-bf72-5de5197d7e2d.png) something like on the right

the purpose for the animated blood sprite was to show which direction the reagents were going and if there were even any reagents being exchanged (if not it would just turn into the empty iv tube sprite)

2023-07-06 10:13 UTC, Drulikar requested changes
Functionally works, just a couple things to tweak.

2023-07-06 10:13 UTC, Drulikar commented on code/game/machinery/iv_drip.dm
> +	base_pixel_x = 5
```suggestion
	base_pixel_x = 15
	base_pixel_y = -2
```
![image](https://github.com/cmss13-devs/cmss13/assets/76988376/19eace9b-cdf3-4de3-8d17-c1f0753a85f8)

2023-07-06 10:13 UTC, Drulikar commented on code/game/machinery/iv_drip.dm
>  			"You attach \the [src] to \the [over_object].")
Its out of scope for this PR, but it is kinda weird that the IV drip doesn't have a skill check like the blood bag does.

2023-07-06 10:15 UTC, Drulikar commented on code/game/machinery/iv_drip.dm
> +	base_pixel_x = 5
Unfortunately its still kind funky that it'd be so stiff at that point to be straight and then we have a tube that goes too the target.

2023-07-06 17:47 UTC, sleepynecrons commented
> > just use iv_beam for both the connection and when it's active. there's no need to show the blood moving and it just looks like something out of cruelty squad. the iv_beam itself also should just use colors from the iv pole ![image](https://user-images.githubusercontent.com/106241650/250369645-a86cda18-9cb9-48f1-bf72-5de5197d7e2d.png) something like on the right
> 
> the purpose for the animated blood sprite was to show which direction the reagents were going and if there were even any reagents being exchanged (if not it would just turn into the empty iv tube sprite)

i know what the purpose was, it just doesn't look good in-game and you already have a HUD icon telling you if you're having blood transfused

2023-07-08 06:43 UTC, Drulikar approved these changes

2023-07-08 06:51 UTC, merged