You can lean against walls
cmss13-devs/cmss13 pull request #3649
Opened 2023-06-16 07:54 UTC by BeagleGaming1

# About the pull request

Adds the ability to lean against walls, moving your sprite closer to it

# Explain why it's good for the game

It looks cool

# Changelog

:cl:
add: Humans can now lean against walls
/:cl:

2023-06-16 08:12 UTC, harryob commented on code/game/turfs/walls/walls.dm
> +	to_chat(current_human, SPAN_BOLDWARNING(lean_dir)) //someone remind me to remove this if i forget
glare

2023-06-16 09:24 UTC, fira requested changes
What happens if you get flung, abducted, or KD'ed?

2023-06-16 09:24 UTC, fira commented on code/game/turfs/walls/walls.dm
> +		stop_wall_lean()
This is Destroy(), clear the var after so it still works independently of logic or runtimes. In theory you're not even supposed to have side effects such as this in Destroy :S

2023-06-16 09:24 UTC, fira commented on code/modules/mob/mob.dm
> +	if(stat==2)
DEAD

2023-06-16 16:28 UTC, fira commented on code/game/turfs/walls/walls.dm
> +	var/mob/living/leaned_on_by
this looks like it could be used as such but you only use it as human later down

2023-06-16 16:29 UTC, fira commented on code/game/turfs/walls/walls.dm
> +/turf/closed/wall/proc/stop_wall_lean(mob/living/carbon/human/current_human = leaned_on_by)
directly use leaned_on_by if theres no use for the param

2023-06-16 16:32 UTC, fira commented on code/modules/mob/mob_defines.dm
> +	var/turf/closed/wall/leaning_on = null
needs Destroy eg

```
/mob/living/carbon/human/Destroy()
  ......
  if(leaning_on)
    if(leaning_on.leaned_on_by == src)
      leaning_on.stop_wall_lean()
    leaning_on = null
```

or somesuch

2023-06-16 18:34 UTC, fira approved these changes

2023-06-17 06:23 UTC, Zonespace27 requested changes
Only reviewed part of it

Make this a component please

2023-06-17 06:23 UTC, Zonespace27 commented on code/game/turfs/walls/walls.dm
> +	var/mob/living/carbon/human/leaned_on_by
Why can it only be one person?
also weakref this

2023-06-17 06:23 UTC, Zonespace27 commented on code/game/turfs/walls/walls.dm
> +	. = ..()
```suggestion
	return ..()
```

2023-06-17 06:23 UTC, Zonespace27 commented on code/game/turfs/walls/walls.dm
> +	if(!istype(usr, /mob/living/carbon/human))
`ishuman()`

2023-06-17 06:23 UTC, Zonespace27 commented on code/modules/mob/mob.dm
> +		return
these should return `false`, not `null`

2023-07-03 01:54 UTC, closed without merging