Xenos no longer can pull dead xenos
cmss13-devs/cmss13 pull request #3666
Opened 2023-06-18 19:57 UTC by morrowwolf

# About the pull request

This PR makes it so xenos can no longer pull dead xenos (or other non-human typepathed dead mobs)

# Explain why it's good for the game

Recovering corpses for marines is an important part of multiple gameplay loops now. We shouldn't really be seeing stacks of xeno corpses in hives.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl: Morrow
balance: Xenos no longer can pull dead xenos
/:cl:

2023-06-18 20:02 UTC, ihatethisengine commented
You should consider the fact that marines can get powerful stims from the corpses of praetorians and queens, dragging corpses away is the only counterplay in that case.

2023-06-18 22:07 UTC, scoutskywalker commented
I will be sad, haven't made a proper xeno 'cemetery' in a couple months but oh well.

2023-06-19 09:17 UTC, cm13live commented
This pull request has been mentioned on **CM-SS13**. Please provide feedback here:

https://forum.cm-ss13.com/t/whats-with-all-the-xeno-overhauls-lately/2753/22

2023-06-27 17:12 UTC, harryob requested changes

2023-06-27 17:12 UTC, harryob commented on code/modules/mob/living/carbon/xenomorph/attack_alien.dm
> +	if(stat == DEAD && !istype(src, /mob/living/carbon/xenomorph/larva))
don’t use istype(src (ever) just override this hook for larva

2023-06-28 07:52 UTC, Drulikar approved these changes

2023-06-28 08:00 UTC, merged