Burnt matches no longer permanently give you a light source if they naturally burn out
cmss13-devs/cmss13 pull request #3670
Opened 2023-06-18 21:46 UTC by morrowwolf

# About the pull request

Burnt matches no longer permanently give you a light source if they naturally burn out

# Explain why it's good for the game

Bug bad

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl: Morrow
fix: Burnt matches no longer permanently give you a light source if they naturally burn out
/:cl:

2023-06-19 08:32 UTC, fira approved these changes

2023-06-19 09:33 UTC, Zonespace27 requested changes

2023-06-19 09:33 UTC, Zonespace27 commented on code/game/objects/items/tools/flame_tools.dm
> +	if(user)
```suggestion
	if(ismob(loc))
```

2023-06-19 09:33 UTC, Zonespace27 commented on code/game/objects/items/tools/flame_tools.dm
>  		user.SetLuminosity(0, FALSE, src)
And then above here add 'var/mob/user = loc' while removing the arg from the proc

2023-06-19 09:33 UTC, Zonespace27 commented on code/game/objects/items/tools/flame_tools.dm
> +		burn_out(user)
Undo your changes here

2023-07-05 15:03 UTC, morrowwolf commented
Ran into an issue where when dropping it the light wouldn't go out. Left the argument and just added a check after the user check to see if loc is a mob. I'm not sure this is more or less elegant but 🤷

2023-07-06 08:35 UTC, Zonespace27 approved these changes
Sure ig
Luminosity should really depend on a trait or component so multiple sources can exist but thats outta scope

2023-07-06 08:44 UTC, merged