Fixes forsaken and foxtrot announcing their arrival.
cmss13-devs/cmss13 pull request #3673
Opened 2023-06-19 13:43 UTC by TheGamerdk

# About the pull request

I broke this, sorry

# Explain why it's good for the game
Bugs bad

# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog
:cl:
fix: Forsaken no longer announce themselves as a distress signal
/:cl:

2023-06-19 13:58 UTC, harryob requested changes
i like kwargs

2023-06-19 13:58 UTC, harryob commented on code/game/gamemodes/colonialmarines/colonialmarines.dm
> +		SSticker.mode.get_specific_call("Xenomorphs Groundside (Forsaken)", FALSE, FALSE, null, FALSE)
```suggestion
		SSticker.mode.get_specific_call("Xenomorphs Groundside (Forsaken)", FALSE, FALSE, announce_dispatch_message = FALSE)
```

2023-06-19 14:41 UTC, morrowwolf requested changes
Cryo marine ERT as well please 🙏

2023-06-19 17:28 UTC, morrowwolf requested changes
You're getting wacked with the atomize stick.

Put the announcement for foxtrot woken up in another PR *shakes fist at sky*

2023-06-19 17:28 UTC, TheGamerdk commented
> You're getting wacked with the atomize stick.
> 
> Put the announcement for foxtrot woken up in another PR _shakes fist at sky_

owkay

2023-06-20 11:06 UTC, fira approved these changes

2023-06-20 15:43 UTC, merged