Disables marine joins after hijack
cmss13-devs/cmss13 pull request #3689
Opened 2023-06-21 15:18 UTC by realforest2001

# About the pull request
New players joining the round after hijack doesn't really serve a purpose beyond feeding xenos, and just results in confusion for a lot of people. This PR changes it so that the moment the shuttle actually crashes, joins are stopped.

# Explain why it's good for the game

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
add: Stops marines joining after the hijack impacts.
/:cl:

2023-06-21 15:56 UTC, fira approved these changes

2023-06-22 04:10 UTC, Drulikar commented
Though I think this is already basically dead code, the same logic also exists still for `/datum/shuttle/ferry/marine/proc/long_jump_crash()` : https://github.com/cmss13-devs/cmss13/blob/master/code/modules/shuttles/marine_ferry.dm#L508

2023-06-22 04:16 UTC, Drulikar requested changes
Enter_allowed is also an admin intervention aspect of disabling late joins.

It would be better if `/mob/new_player/proc/AttemptLateSpawn` and `/mob/new_player/Topic` check for `EvacuationAuthority.evac_status` before the `enter_allowed` check to just indicate hijack has occurred rather than an admin lock that might be a hijack.

2023-06-22 06:11 UTC, MusselMain commented
Interesting idea, poor solution, every single late join marine has to stare at the big red letters in the spawn menu, stating that the ship is being evacuated, and therefore know exactly what they are going into, and while it may seem silly, some players actively enjoy the challenge of waking up with the limited resources of their cryo survival kit, and trying to either evacuate or find a hold to reinforce. I get the concern, but it honestly seems like it's removing options from players like me who actively enjoy, and look forward to being a cryo marine who wakes up during hijack.

2023-06-22 14:15 UTC, cm13live commented
This pull request has been mentioned on **CM-SS13**. Please provide feedback here:

https://forum.cm-ss13.com/t/please-dont-disable-latejoin-after-hijack/2886/1

2023-06-26 02:03 UTC, Drulikar requested changes

2023-06-26 02:03 UTC, Drulikar commented on code/modules/shuttle/dropship_hijack.dm
> +/datum/dropship_hijack/almayer/proc/get_crashsite_area(ship_section)
You are currently reverting a change to a renamed proc here.

2023-06-26 02:07 UTC, Drulikar commented on code/modules/shuttle/dropship_hijack.dm
> +/datum/dropship_hijack/almayer/proc/get_crashsite_area(ship_section)
Same as the initial var inside; I recommend dealing with conflicts with a 3 way merge tool (vsc supports this if you configure it) so you can view local, remote, and still have a panel to manually write changes that would combine the two blocks.

2023-07-12 01:54 UTC, closed without merging