Fixes a typo that made the game think there's not a CO onboard.
cmss13-devs/cmss13 pull request #3722
Opened 2023-06-25 15:36 UTC by TheGamerdk

# About the pull request

Officer, not Officers

# Explain why it's good for the game

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

bugs bad

# Changelog

:cl:
add: Added something
del: Removed old things
qol: made something easier to use
balance: rebalanced something
fix: The game will no longer falsely claim there is no CO
/:cl:

2023-06-25 15:37 UTC, harryob requested changes

2023-06-25 15:37 UTC, harryob commented on code/controllers/subsystem/ticker.dm
> +			if(player.job == "Commanding Officer")
```suggestion
			if(player.job == JOB_CO)
```
if only someone had used the defines in the first place it would not have happened

2023-06-25 15:37 UTC, harryob commented on code/controllers/subsystem/ticker.dm
> +			if(player.job == "Commanding Officer")
(also fix changelog)

2023-06-26 18:56 UTC, Zonespace27 approved these changes

2023-06-26 19:10 UTC, merged