Lurker no longer decloaks if they pounce onto a dead guy.
cmss13-devs/cmss13 pull request #3724
Opened 2023-06-25 16:35 UTC by TheGamerdk

# About the pull request

Doesn't make sense to lose your cloak for pouncing at a dead guy.

They'll still decloak if it's a living guy hiding under a dead guy.

# Explain why it's good for the game

Inconsistent at best. Bad

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
fix: Lurkers no longer lose their pounce if they happen to end their pounce on a tile with a dead human
/:cl:

2023-06-26 11:02 UTC, Drulikar requested changes

2023-06-26 11:02 UTC, Drulikar commented on code/modules/mob/living/carbon/xenomorph/abilities/lurker/lurker_abilities.dm
> +			if(H.stat == DEAD)
Please also fix the single letter vars here. See https://github.com/cmss13-devs/cmss13/blob/master/.github/guides/STYLES.md#variables
You can use VSC to do this easily by selecting the function, search, enable dropdown for replace, enable word, enable case, and then for H/X and replace with `human`/`xeno` or something.

2023-06-28 06:23 UTC, ihatethisengine commented
Discord broke indentations

2023-06-28 11:01 UTC, TheGamerdk commented
> Discord broke indentations

I saw

2023-06-29 03:18 UTC, Drulikar approved these changes
Changes look good. I even test merged with the new weeded bodies to make sure the interaction was the same.

2023-06-29 03:28 UTC, merged