Fixes being unable to re-enter your body when you're unnested
cmss13-devs/cmss13 pull request #3747
Opened 2023-06-27 21:06 UTC by TheGamerdk

# About the pull request

Turns out the parent call of unbuckle() calls afterbuckle() which deletes the nest and clears ghost_of_buckled_mob, which means it can't set your ghost to can_reenter_corpse = TRUE

# Explain why it's good for the game

Bugs bad

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
fix: You can now re-enter your body when unnested, marine mains, rejoice!
/:cl:

2023-06-28 08:59 UTC, Drulikar requested changes
Code works, though please also consider changing the ghost prompt in `/mob/living/proc/do_ghost()` when you remain in body for the first prompt. (As in get nested > remain > ghost)
It looks like this currently:
![image](https://github.com/cmss13-devs/cmss13/assets/76988376/a537f539-4028-47e3-8231-c297b96cd92c)
And if you changed it to say `text_prompt += "\nSince you're nested, you will get a chance to reenter your body if freed."` it would look like this:
![image](https://github.com/cmss13-devs/cmss13/assets/76988376/8b1f9ccf-3c46-4962-b8a0-a99bab5957cb)

2023-06-28 11:01 UTC, TheGamerdk commented
> Code works, though please also consider changing the ghost prompt in `/mob/living/proc/do_ghost()` when you remain in body for the first prompt. (As in get nested > remain > ghost)
> It looks like this currently:
> ![image](https://user-images.githubusercontent.com/76988376/249410750-a537f539-4028-47e3-8231-c297b96cd92c.png)
> And if you changed it to say `text_prompt += "\nSince you're nested, you will get a chance to reenter your body if freed."` it would look like this:
> ![image](https://user-images.githubusercontent.com/76988376/249411744-8b1f9ccf-3c46-4962-b8a0-a99bab5957cb.png)

That’s a bug with the tgui prompt. It should scale according to contents. Out of scope

2023-06-28 12:05 UTC, Drulikar commented
You are altering the action of ghosting when nested. That is the prompt given to users when doing that action; so it is not out of scope.

Sure updating tgui_alert to adapt to the size isn't very related; but thats not what I requested. The message is needlessly wordy regardless.

2023-06-28 15:57 UTC, TheGamerdk commented
> You are altering the action of ghosting when nested. That is the prompt given to users when doing that action; so it is not out of scope.
> 
> Sure updating tgui_alert to adapt to the size isn't very related; but thats not what I requested. The message is needlessly wordy regardless.

I’m not altering anything about ghosting. I’m only touching nest unbuckling

2023-06-28 20:05 UTC, harryob approved these changes

2023-06-29 02:55 UTC, Drulikar commented
I'll take the GBP for the requested change in a separate PR then.

2023-06-29 03:04 UTC, merged