The acid....
cmss13-devs/cmss13 pull request #3749
Opened 2023-06-27 23:24 UTC by Diegoflores31

# About the pull request

Changes acid splash damage . it will now be reduced with BIO armor and it will escale depending on your xeno TIER . 
formula = 20 + (TIERx5)

Reduces M3 light armor Bio resistance to be MEDIUMLOW instead of MEDIUM HIGH

Increases M3 Heavy armor Bio resistance to be MEDIUMHIGH instead of MEDIUM

# Explain why it's good for the game

Acid blood has been changing numbers pretty frequently over the years i think the issue is that is often too high or too low so now it adjusts depending on your tier so higher castes cant be just killed with knifes winout come consequences.

Acid blood now applies armored damage . this is to encourage heavier armor to those that want to take less damage from this kind of encounters.

Light armor BIO resistance has been reduced . the reasoning being that is the fastest armor available it makes little to no sense that is the one that protects you the most of them ALL variations .

Heavy armor BIO resistance was increased for those that wish to have a tankier playstyle be less affected.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
balance: Acid Splash damage now increases depending on your TIER
balance: Acid Splash damage can be reduced with BIO armor.
balance: Reduced Light armor BIO resistance by 10
balance: Increased Heavy armor BIO resistance by 5
/:cl:

2023-06-28 00:48 UTC, MusselMain commented
does this apply to suicide runners

2023-06-28 02:28 UTC, Diegoflores31 commented
> does this apply to suicide runners

no this is exclusively for acid splash ( the damage you get for shooting xenos too near)

2023-06-28 05:35 UTC, morrowwolf requested changes
Otherwise, willing to TM and try after changes.

2023-06-28 05:35 UTC, morrowwolf commented on code/modules/clothing/suits/marine_armor.dm
> +	armor_bio = CLOTHING_ARMOR_LOW
Make a new very low (5) or revert

2023-06-28 05:35 UTC, morrowwolf commented on code/modules/clothing/suits/marine_armor.dm
> +	armor_bio = CLOTHING_ARMOR_LOW
Also document change

2023-06-28 06:52 UTC, Diegoflores31 commented on code/modules/clothing/suits/marine_armor.dm
> +	armor_bio = CLOTHING_ARMOR_LOW
Will do tomorrow morning when i reach home

2023-06-28 22:44 UTC, Diegoflores31 commented
suggestions applied :3

2023-07-06 10:22 UTC, Drulikar approved these changes
Code changes look fine.

2023-07-11 01:55 UTC, morrowwolf requested changes
I've thought about it, I don't think the tiered acid damage is really great and this is overall a nerf to acid damage in its current state.

Let's remove the tiered change and up the base acid blood damage by 5 and give it a whirl.

2023-07-19 04:54 UTC, merged