Yautja cloak changes
cmss13-devs/cmss13 pull request #3757
Opened 2023-06-28 15:40 UTC by realforest2001

# About the pull request
Makes Yautja cloak permanent and cost no power. Also adds various multipliers for forced decloak source, resulting in differing durations it is unusable.

# Explain why it's good for the game

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
add: Made Yautja cloak cost no power to operate, and created multipliers for disabled duration based upon what caused the Yautja to decloak.
/:cl:

2023-07-05 12:41 UTC, Zonespace27 requested changes
Justify this change

2023-07-19 05:27 UTC, morrowwolf requested changes

2023-07-19 05:27 UTC, morrowwolf commented on code/__DEFINES/combat.dm
> +#define DECLOAK_STANDARD 10 SECONDS
(10 SECONDS)

2023-07-24 17:29 UTC, harryob approved these changes

2023-07-24 18:49 UTC, merged