Marine Body Spray AKA: Reworks Marine Orders
cmss13-devs/cmss13 pull request #3782
Opened 2023-07-01 22:50 UTC by CometBlaze

# About the pull request

SLs are now able to pick between three kinds of body spray laced with experimental stimulants designed to improve the marines' combat performance.

On a more serious note this makes it so orders now act as  a buff aura rather than a short power boost. In order to compensate for their now constant nature, the strength of the mobility and protection auras have been halved, focus has been left as is because it was already weak enough and honestly I would still like to make it stronger, but maybe in another PR.

For the majority of roles the changes end here, however, squads will see another aspect changed in the form of their FTLs. When an SL (or aSL) picks an order, all FTLs currently assigned to that squad will also emit that same aura. This aura has the same exact behaviour as the regular SL's orders with the only difference being that FTLs cannot pick their own orders.

Assuming the maintainer team doesn't shank me for how I coded this there will be a follow up to this PR introducing ~fear RP~ morale de-buffs to marines not within range of a "buff piece" (SL, FTL, CO, etc...)

# Explain why it's good for the game

Provides marine with a mechanical incentive to stick with their SLs which should hopefully lead to better squad cohesion.
Increased squad cohesion should allow for more elaborate tactics to be employed by CIC which should lead to more interesting rounds.
Benefits to squad cohesion also apply to Fireteams, which should allow for even more flexibility in squad tactics.
# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

https://github.com/cmss13-devs/cmss13/assets/59415394/58822eb9-2a6a-4533-9edd-5e71dac03f3b

</details>

# Changelog
:cl: CometBlaze
add: Orders are now buff auras that apply to anyone within 7 tiles of the buff giver and no longer have limited duration. 
balance: Mobility and Protection orders' strength have been halved, Focus remains unchanged.
add: FTLs now act as "order relays" for their SLs, meaning they will also have an aura like the SL, this aura has the same properties as the SL's and remains active for as long as theirs is.
code: Order action buttons have been brought into the modern age and now use a transparent action_icon_state
/:cl:

2023-07-02 00:22 UTC, Ben10083 commented
How does this affect defence placements like the warbanners?

2023-07-02 08:09 UTC, ihatethisengine commented
I think spray should affect only their own squad, to discourage murderballing a bit (otherwise imagine Alpha Charlie Delta SLs sticking together to provide every kind of pheros). And FTL should relay orders only to their respective TL. I think this way it would be perfect.

2023-07-02 09:20 UTC, Weuyn commented
really prefer the current system to passive buffs. Passives aren't as fun

2023-07-02 16:59 UTC, sleepynecrons approved these changes
sprites

2023-07-08 06:00 UTC, nauticall approved these changes
concur, sprites good

2023-07-17 08:07 UTC, Zonespace27 requested changes

2023-07-17 08:07 UTC, Zonespace27 commented on code/modules/mob/living/carbon/human/human_defines.dm
> +	var/marksman_aura_new = 0
code doc these 5 (or more, if you want)

2023-07-17 08:07 UTC, Zonespace27 commented on code/modules/mob/living/carbon/human/human_damage.dm
> +		damage = round(damage * ((ORDER_HOLD_CALC_LEVEL - protection_aura * 0.5) / ORDER_HOLD_CALC_LEVEL))
are you certain this is doing what you want with PEMDAS?

2023-07-17 08:07 UTC, Zonespace27 commented on code/modules/mob/living/carbon/human/powers/issue_order.dm
> +			visible_message(SPAN_WARNING("\The [src] stops issueing orders."), \
issuing

2023-07-17 08:07 UTC, Zonespace27 commented on code/modules/mob/living/carbon/human/powers/issue_order.dm
> +			visible_message(SPAN_BOLDNOTICE("[src] whitdraws their order to [order]!"), SPAN_BOLDNOTICE("You withdraw your order to [order]!"))
withdraws

2023-07-17 08:07 UTC, Zonespace27 commented on code/modules/mob/living/carbon/human/life/handle_orders.dm
> +		for(var/mob/living/carbon/human/H as anything in GLOB.alive_human_list)
this is really expensive to call on every human every life() tick

it's more acceptable for xenoes bc they're rarely dealing with 30+ xenoes, but humans regularly breach 100, along with a not-exactly-free get_dist check

2023-07-30 16:55 UTC, Zonespace27 commented
Ping me when you're ready to work on this again

2023-07-30 16:55 UTC, closed without merging