Fix marines not getting first dibs if they ghost
cmss13-devs/cmss13 pull request #3802
Opened 2023-07-05 09:19 UTC by Drulikar

# About the pull request

This PR fixes an issue where hugged marines that burst were not getting first dibs on the larva if they ghosted. Previously the mind maybe wasn't cleared out to find the ghost mob, but it currently is.

NOTE: The existing check requiring the marine to be nested is still in place to get first dibs. I'm honestly not sure if this check should still exist. On one hand I can agree it might be hard for the marine trying to get help to suddenly become the larva and switch gears - they are still going to be in the mindset of a marine that the larva should die. But its also sort of weird to only get the first dibs if nested. If xenos are unnesting hugged marines just before they pop, thats already a mechanic abuse that should be ahelped; but ideally there wouldn't be anything to be abused. Also, some may consider this kind of larva undesirable anyways so maybe they'd prefer the marine to have it... So let me know if I should just remove the nested check on line 151.

# Explain why it's good for the game

Fixes an unintended consequence of ghosting when hugged that would prevent that marine from getting their first dibs on the larva.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

![dibs](https://github.com/cmss13-devs/cmss13/assets/76988376/84e44345-2b83-473f-9997-f7865bcef1dd)

</details>

# Changelog

:cl: Drathek
fix: Fix ghosting preventing first dibs on the larva in a hugged marine
/:cl:

2023-07-05 12:46 UTC, Zonespace27 requested changes

2023-07-05 12:46 UTC, Zonespace27 commented on code/modules/mob/living/carbon/xenomorph/Embryo.dm
> +				if(cur_obs.ckey == affected_mob.persistent_ckey)
Early continue this pls

2023-07-05 12:46 UTC, Zonespace27 commented on code/modules/mob/living/carbon/xenomorph/Embryo.dm
> +					if(cur_obs.client && cur_obs.client.prefs && (cur_obs.client.prefs.be_special & BE_ALIEN_AFTER_DEATH) && !jobban_isbanned(cur_obs, JOB_XENOMORPH))
```suggestion
					if((cur_obs?.client?.prefs.be_special & BE_ALIEN_AFTER_DEATH) && !jobban_isbanned(cur_obs, JOB_XENOMORPH))
```

2023-07-05 13:16 UTC, Drulikar commented on code/modules/mob/living/carbon/xenomorph/Embryo.dm
> +				if(cur_obs.ckey == affected_mob.persistent_ckey)
Elaborate?

2023-07-05 13:26 UTC, Zonespace27 commented on code/modules/mob/living/carbon/xenomorph/Embryo.dm
> +				if(cur_obs.ckey == affected_mob.persistent_ckey)
(Discussed on discord)

2023-07-13 22:49 UTC, Zonespace27 approved these changes
Lgtm

2023-07-13 22:57 UTC, merged