Disposable Mobs Flag
cmss13-devs/cmss13 pull request #3814
Opened 2023-07-05 18:37 UTC by realforest2001

# About the pull request
Allows admins to toggle a flag as to whether mobs will fit inside disposals tubes.

# Explain why it's good for the game
There are some situations where I can see it being fitting to the situation, and this will also allow a measured level of return for a feature we had to remove due to abuse.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
add: Added an admin toggle flag for fitting mobs into disposals. (Within reason - no queens...)
/:cl:

2023-07-19 11:58 UTC, harryob requested changes

2023-07-19 11:58 UTC, harryob commented on code/modules/recycling/disposal.dm
> +			else if(user.grab_level >= GRAB_AGGRESSIVE)
else if redundant after a return

2023-07-19 11:58 UTC, harryob commented on code/modules/recycling/disposal.dm
> +				if(do_after(user, 20, INTERRUPT_ALL, BUSY_ICON_HOSTILE))
early return

2023-07-19 11:58 UTC, harryob commented on code/modules/recycling/disposal.dm
> +			else
early return

2023-07-22 13:49 UTC, Zonespace27 requested changes

2023-07-22 13:49 UTC, Zonespace27 commented on code/modules/recycling/disposal.dm
> +	var/narrow_tube = FALSE
codedoc

2023-07-22 13:49 UTC, Zonespace27 commented on code/modules/recycling/disposal.dm
> +				if(!do_after(user, 20, INTERRUPT_ALL, BUSY_ICON_HOSTILE))
seconds define

2023-07-22 13:49 UTC, Zonespace27 commented on code/modules/recycling/disposal.dm
> +		to_chat(user, SPAN_WARNING("You need a better grip on [target] to force them into the [src]!"))
```suggestion
		to_chat(user, SPAN_WARNING("You need a better grip on [target] to force them into [src]!"))
```

2023-07-28 22:04 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2023-07-31 12:07 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2023-08-04 05:13 UTC, harryob approved these changes

2023-08-04 05:59 UTC, merged