Thwomper's Synthetic Uniforms(THWOMP SHRAMALERT) & Synth Vendor QOL
cmss13-devs/cmss13 pull request #3824
Opened 2023-07-06 08:46 UTC by QuickLode

# About the pull request

Incorporates Thwomper's Synthetic Uniforms & Vest into the game.
(I tried to be creative with the lore but I'm not paid by the hour man! that UA laborer is.)

Synthetic Vendor QOL making it easier to find and use.

Slight moving of stuff, vestigial stuff moved too. 

# Explain why it's good for the game
THWOMP SHRAMALERT

Gives a UA Colony/Shipside theme.

QOL makes things easier to use.

# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.
tested and everything appears to be working well(tahts how i got the screenshot)
https://cdn.discordapp.com/attachments/777257424590995466/1126429970244325406/image.png
</details>

# Changelog
:cl: QuickLoad, Thwomper
imageadd: Synthetic Uniforms & Vest with United Americas flair and classic jumpsuits which remind you of life on the Frontier. Sprited by THE THWOMPA himself!
qol: Synthetic Vendor is more organized. Removes scrub cap, adds shoe.
/:cl:

2023-07-06 15:51 UTC, sleepynecrons requested changes
all of the outfits look great except for cargo_light. the shading is very flat, lacks contrast and needs a proper outline like the rest of the outfits
![image](https://github.com/cmss13-devs/cmss13/assets/106241650/115cbe1a-8202-4d8a-8a2f-63079b8c4a82)
the jacket tied around the waist is also at inconsistent heights and there is a random pixel on the east/west sprites

2023-07-08 05:56 UTC, nauticall approved these changes
cargo light looks good to me but I'll wait for sleepy to approve too

2023-07-08 05:59 UTC, nauticall requested changes
mb the shading on the shirt still needs work. shading should be darker round the top and more outlined

2023-07-11 02:05 UTC, thwompa commented
should be GOOD2GO(tm patent pending)

2023-07-11 12:18 UTC, nauticall approved these changes
now THAT is spriting :100:

2023-07-11 12:27 UTC, nauticall requested changes

2023-07-11 12:27 UTC, nauticall commented on code/modules/clothing/under/marine_uniform.dm
> +	name = "UA brown utilities"
add \improper before these (same with any non-proper names that begin with a capital letter) and turn it to "UA [color] utility uniform"

`\improper UA gray utilities` results in "That's a UA gray utility uniform." whereas without the `\improper` it just puts "That's UA gray utility uniform."

2023-07-11 12:27 UTC, nauticall commented on code/modules/clothing/under/marine_uniform.dm
> +	name = "UA brown utilities"
once that's done I'll merge it....

2023-07-11 12:35 UTC, nauticall commented on code/modules/clothing/under/marine_uniform.dm
> +	name = "UA brown utilities"
```suggestion
	name = "\improper UA brown utility uniform"
```

2023-07-11 12:35 UTC, nauticall commented on code/modules/clothing/under/marine_uniform.dm
> +	name = "UA gray utilities"
```suggestion
	name = "\improper UA gray utility uniform"
```

2023-07-12 04:35 UTC, nauticall approved these changes
gouda 🧀

2023-07-12 04:44 UTC, merged