SMG Gun+Mag Holster
cmss13-devs/cmss13 pull request #3825
Opened 2023-07-06 09:38 UTC by Steelpoint

# About the pull request

Adds a new holster for the SMG. It can hold a M39 SMG plus two M39 magazines, but the belt can only clip to the armor/suit slot. 

Corpsmen, Comtechs, Specialists and Intelligence Officers can vend one for free. Team Leaders and Squad Leaders can purchase one for 5 and 4 points respectively. Requisitions has access to a supply but with a low amount (akin to G8 pouches). 

# Explain why it's good for the game

The M39 SMG is intended as an inferior firearm to the mainline M41A. The perceived benefit of a M39 would be its lightness compared to the bulkier M41A, however this is not reflected in-game outside of the M39 not confering a movement speed down when wielded, which is shared with many other bulky guns like the M4RA.

The idea around this new holster is that it would give Marines a better reason to consider taking the M39, as Marines in a more support oriented role can access a unique holster that lets them carry additional magazines in addition to the firearm itself. 

Certain roles where free inventory space is at a premium, such as Corpsmen, Comtechs, Specs and IOs, may find new life in picking the SMG, even if it is weaker than a M41A, for the value of having extra ammo storage space. 

(I should note that I'll defer to the maintainers in regards to availability of the holster or if it has to be bought or given for free for certain roles. My belief in giving Corpsmen/Comtechs/IOs/Spec the holster as a free choice is merely that if they were forced to spent their points on the holster than no one would likely buy it) 

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

![Screenshot 2023-07-06 17 17 56](https://github.com/cmss13-devs/cmss13/assets/6595389/15217e97-5a1a-4a8a-8bf4-1520d45355c8)

OBJ sprites and the inventory capacity as seen in game

</details>

# Changelog

:cl:
add: The M39 SMG holster rig has now been issued in limited numbers to select Marine roles. It can holster a SMG and two spare magazines, but it can only clip in to the armor storage slot. 
/:cl:

2023-07-06 09:48 UTC, Zonespace27 commented on code/modules/clothing/suits/marine_armor.dm
> +	slowdown = SLOWDOWN_ARMOR_VERY_LIGHT
You have a polluted master

2023-07-06 09:52 UTC, Steelpoint commented on code/modules/clothing/suits/marine_armor.dm
> +	slowdown = SLOWDOWN_ARMOR_VERY_LIGHT
oh god

2023-07-06 15:57 UTC, sleepynecrons requested changes
use the m39 holster that we already have as a base. sticking the m39 in a pistol holster just looks extremely silly and is visually inconsistent with the other holsters.
![image](https://github.com/cmss13-devs/cmss13/assets/106241650/57ec7ea7-4b56-47f1-95de-0c323b847e70)

2023-07-06 17:22 UTC, Steelpoint commented
> use the m39 holster that we already have as a base. sticking the m39 in a pistol holster just looks extremely silly and is visually inconsistent with the other holsters. ![image](https://user-images.githubusercontent.com/106241650/251505645-57ec7ea7-4b56-47f1-95de-0c323b847e70.png)

I considered that at first, that's even how I initially did it, but the way the code works for the sprites is that the gun is placed behind the sprite not in front of it. So I settled on what is currently being used. 

Outside of a code solution to make the gun sprite appear in front of the rig sprite, which I won't be able to do by myself, I did a hacky fix where I edited the rig sprite to remove the parts of the rig that would be in front of the gun sprite. Not a great solution though.

2023-07-06 17:59 UTC, Steelpoint commented
For the interim I've implemented an alt solution as described above, here is how the sprite looks in game

![Screenshot 2023-07-07 01 58 02](https://github.com/cmss13-devs/cmss13/assets/6595389/0bc1cf7c-5319-45d0-8814-47bfc5bcd224)

2023-07-06 22:11 UTC, sleepynecrons commented
> For the interim I've implemented an alt solution as described above, here is how the sprite looks in game
> 
> ![Screenshot 2023-07-07 01 58 02](https://user-images.githubusercontent.com/6595389/251534516-0bc1cf7c-5319-45d0-8814-47bfc5bcd224.png) ![Screenshot 2023-07-07 02 01 46](https://user-images.githubusercontent.com/6595389/251535669-a795664e-0f01-4d0d-8152-880a730a8730.png)

swap the holster and mag pouches position and it'll be good to go
![image](https://github.com/cmss13-devs/cmss13/assets/106241650/61d3ce14-8f4b-493f-a532-ec3abb7234be)
basically like this

2023-07-07 11:18 UTC, Steelpoint commented
Swapped the sprite around
![Screenshot 2023-07-07 19 17 20](https://github.com/cmss13-devs/cmss13/assets/6595389/6e052b13-296c-4a5d-9cb4-dcd5b751004b)

2023-07-19 06:09 UTC, morrowwolf requested changes

2023-07-19 06:09 UTC, morrowwolf commented on code/game/machinery/vending/vendor_types/intelligence_officer.dm
> +		list("M276 SMG Armor Rig", 0, /obj/item/storage/belt/gun/m39, MARINE_CAN_BUY_ARMOR_SLOT, VENDOR_ITEM_REGULAR),
Make buyable

2023-07-19 06:09 UTC, morrowwolf commented on code/game/machinery/vending/vendor_types/squad_prep/squad_engineer.dm
> +		list("M276 SMG Armor Rig", 0, /obj/item/storage/belt/gun/m39, MARINE_CAN_BUY_ARMOR_SLOT, VENDOR_ITEM_REGULAR),
Make buyable

2023-07-19 06:09 UTC, morrowwolf commented on code/game/machinery/vending/vendor_types/squad_prep/squad_medic.dm
> +		list("M276 SMG Armor Rig", 0, /obj/item/storage/belt/gun/m39, MARINE_CAN_BUY_ARMOR_SLOT, VENDOR_ITEM_REGULAR),
make buyable

2023-07-19 06:09 UTC, morrowwolf commented on code/game/machinery/vending/vendor_types/squad_prep/squad_specialist.dm
> +		list("M276 SMG Armor Rig", 0, /obj/item/storage/belt/gun/m39, MARINE_CAN_BUY_ARMOR_SLOT, VENDOR_ITEM_REGULAR),
make buyable

2023-07-19 06:09 UTC, morrowwolf commented on code/game/objects/items/storage/belt.dm
> +	flags_equip_slot = SLOT_SUIT_STORE
Don't do this here, add this to the base marine armor in marine_armor.dm in "allowed" line 100

2023-07-19 06:09 UTC, morrowwolf commented on code/__DEFINES/vendors.dm
> +#define MARINE_CAN_BUY_ARMOR_SLOT "armor_slot"
Remove since unneeded after requested changes

2023-07-19 06:09 UTC, morrowwolf commented on code/__DEFINES/vendors.dm
> +#define MARINE_CAN_BUY_ALL list(MARINE_CAN_BUY_UNIFORM = 1, MARINE_CAN_BUY_SHOES = 1, MARINE_CAN_BUY_HELMET = 1, MARINE_CAN_BUY_ARMOR = 1, MARINE_CAN_BUY_GLOVES = 1, MARINE_CAN_BUY_EAR = 1, MARINE_CA
Revert since unneeded after requested changes

2023-07-19 06:53 UTC, Steelpoint commented
Requested changes made.

2023-07-25 13:24 UTC, harryob approved these changes
code

2023-08-09 09:50 UTC, nauticall approved these changes
sprites 👍

2023-08-09 10:17 UTC, Steelpoint commented
gonna make a change

2023-08-09 10:23 UTC, Steelpoint commented
Stated to make this replace the current SMG belt, will need to make some changes, shouldn't take too long (famous last words)

2023-08-09 15:59 UTC, Steelpoint commented
This SMG belt now replaces all regular instances of the old SMG belt. Old SMG belt is still in the game, though I believe only PMC's use it now.

2023-08-09 17:31 UTC, Zonespace27 approved these changes

2023-08-09 17:39 UTC, merged