Working Joes can no longer eat
cmss13-devs/cmss13 pull request #3828
Opened 2023-07-06 15:37 UTC by Ben10083

# About the pull request

Mechanically prevents eating and being force-fed as a Joe

# Explain why it's good for the game

While not worried about the Joe itself eating the Burger, it physically does not have anything to feed the burger to (The mouth is mostly aesthetic with a speaker). As such, it makes no sense that you can feed food into a Working Joe, and should not be possible.

# Changelog

:cl:
del: Working Joes can no longer be fed.
/:cl:

2023-07-06 15:43 UTC, Ben10083 commented
![image](https://github.com/cmss13-devs/cmss13/assets/91219575/51f1c9fb-2ad1-4785-b642-16c629a4573f)

2023-07-06 18:11 UTC, BeagleGaming1 approved these changes
Code seems good

2023-07-07 03:11 UTC, BeagleGaming1 requested changes

2023-07-07 03:11 UTC, BeagleGaming1 commented on code/modules/mob/living/carbon/human/species/synthetic.dm
> +  burn_mod = 0.65 // made for hazardous environments, withstanding temperatures up to 1210 degrees
You undid some changes here, and made it 2 spaces instead of a tab

2023-07-07 04:10 UTC, BeagleGaming1 approved these changes

2023-07-07 12:54 UTC, harryob requested changes

2023-07-07 16:18 UTC, harryob approved these changes

2023-07-07 17:20 UTC, merged

2023-07-07 18:38 UTC, Hopekz commented
please do not feed Seegson property