New CAS Weapon: BLU-200 Dragons Breath, thermobaric bomb
cmss13-devs/cmss13 pull request #3832
Opened 2023-07-07 05:39 UTC by blackdragonTOW

# About the pull request

Adds a crowd control option to CAS missile options, to help incentivize people away from CAS Metabuilds.

- Fire equivalent of the Banshee but without the impact damage.
- Implosion from fuel-air bomb pulls nearby units towards the center.
- 500 points (Expensive)

# Explain why it's good for the game

Missiles on CAS are super expensive and rarely make their points back.  In order to give the missile rack some punch and give it capabilities the other higher damage weapons dont have, we give it a bit of CC.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
add: Added new CAS Missile: BLU-200 Dragons Breath
/:cl:

2023-07-07 11:13 UTC, fira commented
This is potentially problematic in FM mode pulling into minirockets - and I don't really see the point of this as a direct-only weapon

2023-07-07 13:10 UTC, MemesLauncher commented
Seems fun and fresh for jtac FM. Wonder how it would interact if two were to land at the same time on opposite direction

2023-07-07 16:12 UTC, Hopekz commented
> This is potentially problematic in FM mode pulling into minirockets - and I don't really see the point of this as a direct-only weapon

It's 500 CAS credit to fire once let people have fun for about 3-4 CAS runs before they go broke similar to how the 4x Gau build can only do a few runs before they're Perma broke

2023-07-19 06:10 UTC, morrowwolf commented
Questionable but let's give it a try at least

2023-07-21 18:13 UTC, morrowwolf commented
This hasn't been nearly as strong in reality as it seemed on paper. More options are good. Will tune more if required.

2023-07-21 18:14 UTC, morrowwolf requested changes

2023-07-21 18:14 UTC, morrowwolf commented on code/modules/cm_marines/dropship_ammo.dm
> +	fire_spread(impact, create_cause_data(initial(name), source_mob), 4, 25, 50, "#c96500") //Very intense but the fire doesn't last very long
Should be using the timers like the others

2023-07-21 18:31 UTC, blackdragonTOW commented
timer added to fire impact, reduced cost to put it in line with other CAS missiles aligning with player feedback.

2023-07-22 08:14 UTC, merged