Adding Coats to the Staff Officer vendor
cmss13-devs/cmss13 pull request #3840
Opened 2023-07-08 11:39 UTC by theselfish

# About the pull request

Title.
![image](https://github.com/cmss13-devs/cmss13/assets/102828457/3f83c54f-3cf0-4227-a1f0-8a1b9b10baf4)
I am willing to toss the Tanker Jacket, as much as I miss it.
I also added the uniform to their required gear for the sake of consistency. 
# Explain why it's good for the game

It gives the SO more options for clothing, as it's cold on the ship.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl: 
add: SOs may now get coats in their vendor.
/:cl:

2023-07-11 13:46 UTC, theselfish commented
@harryob Since no maintainer was pinged.

2023-07-14 10:41 UTC, morrowwolf requested changes
Undo the helmet/hat change. Feel free to give them a *regular* cmcap as an option.

Uniform change fine.

Only service jacket choosable. Dress shouldn't be used regularly and tanker isn't for SOs.

2023-07-14 18:46 UTC, theselfish commented on code/game/machinery/vending/vendor_types/crew/staff_officer.dm
> +		list("Hat", 0, /obj/item/clothing/head/cmcap/ro, MARINE_CAN_BUY_HELMET, VENDOR_ITEM_MANDATORY),
```suggestion
		list("Helmet", 0, /obj/item/clothing/head/helmet/marine/MP/SO, MARINE_CAN_BUY_HELMET, VENDOR_ITEM_MANDATORY),
```

2023-07-14 18:48 UTC, theselfish commented
> Undo the helmet/hat change. Feel free to give them a _regular_ cmcap as an option.
> 
> Uniform change fine.
> 
> Only service jacket choosable. Dress shouldn't be used regularly and tanker isn't for SOs.

The /ro cap is the same as the one they spawn with.
But, doing it as I type.

2023-07-14 18:56 UTC, theselfish commented
The RO's hat is, confusingly under /req.

2023-07-14 18:58 UTC, theselfish commented
@morrowwolf Sorted.

2023-07-15 05:20 UTC, harryob approved these changes

2023-07-15 05:28 UTC, merged