Invisible lurker pushing
cmss13-devs/cmss13 pull request #3857
Opened 2023-07-11 04:47 UTC by morrowwolf

# About the pull request

This PR makes it so when you collide with a human as an invisible lurker you will become visible.

# Explain why it's good for the game

Being pushed by a fast and barely visible xeno is super cheesy.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl: Morrow
balance: Lurkers now lose their invisibility when they run into a person
/:cl:

2023-07-11 08:22 UTC, cm13live commented
This pull request has been mentioned on **CM-SS13**. Please provide feedback here:

https://forum.cm-ss13.com/t/whats-with-all-the-xeno-overhauls-lately/2753/103

2023-07-11 14:23 UTC, TheGamerdk commented
Couldn’t you just make invisible lurkers unable to push people

2023-07-11 23:27 UTC, TheGamerdk commented
> Couldn’t you just make invisible lurkers unable to push people

How is asking this off topic

2023-07-12 02:05 UTC, ThiccFucc commented
:1984:

2023-07-12 05:26 UTC, harryob requested changes

2023-07-12 05:26 UTC, harryob commented on code/modules/mob/living/carbon/xenomorph/castes/Lurker.dm
> +	if(bound_xeno && bound_xeno.stealth)
```suggestion
	if(!bound_xeno || !bound_xeno.stealth)
		return

```

2023-07-12 05:26 UTC, harryob commented on code/modules/mob/living/carbon/xenomorph/castes/Lurker.dm
> +		var/datum/action/xeno_action/onclick/lurker_invisibility/lurker_invisibility_action = get_xeno_action_by_type(bound_xeno, /datum/action/xeno_action/onclick/lurker_invisibility)
```suggestion
	 var/datum/action/xeno_action/onclick/lurker_invisibility/lurker_invisibility_action = get_xeno_action_by_type(bound_xeno, /datum/action/xeno_action/onclick/lurker_invisibility)
```

2023-07-12 05:26 UTC, harryob commented on code/modules/mob/living/carbon/xenomorph/castes/Lurker.dm
> +		if(lurker_invisibility_action)
```suggestion
	if(!lurker_invisibility_action)
		return

```

2023-07-12 05:26 UTC, harryob commented on code/modules/mob/living/carbon/xenomorph/castes/Lurker.dm
> +			lurker_invisibility_action.invisibility_off()
```suggestion
	lurker_invisibility_action.invisibility_off()
```

2023-07-12 06:21 UTC, BeagleGaming1 commented on code/modules/mob/living/carbon/xenomorph/castes/Lurker.dm
> +	 var/datum/action/xeno_action/onclick/lurker_invisibility/lurker_invisibility_action = get_xeno_action_by_type(bound_xeno, /datum/action/xeno_action/onclick/lurker_invisibility)
```suggestion
	 var/datum/action/xeno_action/onclick/lurker_invisibility/lurker_invisibility_action = get_xeno_action_by_type(bound_xeno, /datum/action/xeno_action/onclick/lurker_invisibility_action)
```

2023-07-12 06:27 UTC, BeagleGaming1 commented on code/modules/mob/living/carbon/xenomorph/castes/Lurker.dm
> +	 var/datum/action/xeno_action/onclick/lurker_invisibility/lurker_invisibility_action = get_xeno_action_by_type(bound_xeno, /datum/action/xeno_action/onclick/lurker_invisibility_action)
```suggestion
	var/datum/action/xeno_action/onclick/lurker_invisibility/lurker_invisibility_action = get_xeno_action_by_type(bound_xeno, /datum/action/xeno_action/onclick/lurker_invisibility_action)
```
Real

2023-07-12 21:00 UTC, BeagleGaming1 commented on code/modules/mob/living/carbon/xenomorph/castes/Lurker.dm
> +	var/datum/action/xeno_action/onclick/lurker_invisibility/lurker_invisibility_action = get_xeno_action_by_type(bound_xeno, /datum/action/xeno_action/onclick/lurker_invisibility_action)
```suggestion
	var/datum/action/xeno_action/onclick/lurker_invisibility/lurker_invisibility_action = get_xeno_action_by_type(bound_xeno, /datum/action/xeno_action/onclick/lurker_invisibility)
```

2023-07-12 23:19 UTC, BeagleGaming1 approved these changes
Code seems good, still needs balance approval.

2023-07-14 11:29 UTC, merged