B5 Hammer slowdown
cmss13-devs/cmss13 pull request #3860
Opened 2023-07-11 11:04 UTC by ghostsheet

# About the pull request

This makes Synth b5 breaching hammer, apply a slowdown to (marines) anyone who picks it up but doesn't have the strength to use it.

# Explain why it's good for the game

Synth have been complaining that marines are running off their hammer. 
The visible slowdown should prevent marines from running off with it too often

# Changelog

:cl: ghostsheet
add: B5 Breaching Hammer will now slow down humans who picks it up.
/:cl:

2023-07-13 03:40 UTC, harryob requested changes
not the correct way to handle a slowdown, look at https://github.com/cmss13-devs/cmss13/pull/3392

2023-07-22 08:11 UTC, morrowwolf requested changes

2023-07-22 08:11 UTC, morrowwolf commented on code/game/objects/items/weapons/twohanded.dm
> +		user.emote("pain")
Emoting pain is a bit much, slow down is fine, make effects last less and no daze

2023-07-24 17:32 UTC, harryob requested changes
nit

2023-08-03 08:54 UTC, harryob approved these changes

2023-08-03 09:01 UTC, merged