New UPP guns
cmss13-devs/cmss13 pull request #3865
Opened 2023-07-11 18:47 UTC by CapCamIII

# About the pull request

Adds a bunch of new UPP guns to replace ill-fitting ones, respites others, removes others, also does some balance changes that I feel would be good for the game, nothing too outrageous I believe.

Look at changelog and code for specific changes unless i get asked by a dev to list them here

# Explain why it's good for the game

New UPP guns to replace old things that don't make sense, better sprites, IMO needed balance changes.

# Testing Photographs and Procedure
![image](https://github.com/cmss13-devs/cmss13/assets/103988604/89227b16-94b1-4632-b223-0e5eee6d6547)
Slightly outdated and I forgot Type 23, but mostly correct. Look at imagediff for type 23 sprite

# Changelog

I might have forgotten a thing or two since I've been working on this on and off since April, but from what I can tell mostly there

:cl:
add: Adds 6(8 if you're pedantic) new guns for the UPP, details for each in following lines.
add: Type 19, Replacement for PPsh on colonies and black market.
add: Type 64, replacement for scorpion, full sized SMG, 2 versions, 1 for upp, 1 for not upp
add: HJRA-12, RPG for UPP.
add: Type 73, pistol for higher ranked UPP troops, UPP COs get a Type 74 which has high-impact rounds, replaces PK9 in non-UPP use.
add: NP92, pistol, replaces PK9 in UPP use(mostly), integrally suppressed version called NPZ92 for UPP Commandos.
add: QYJ-72, UPP GPMG, replaces minigun with UPP Minigunners
add: Technically resprites but due to changes closer to replaces N-Y revolver with ZHNK-72
add: Adds a character custom loadout Type 73, 2 mags spare.
add: UPP helmets now work as ear protection, intended use with HJRA-12 RPG
add: UPP officers now have regular UM4 helmets instead of UH7 helmets in their vendors as UH7 looked ugly with their combat gear
del: Removes the PK9 entirely
del: Removes tranqs from UPP Commando loadout
del: Removes HEAP ammo from UPP officers and commandos, replaced with normal and AP mags when applicable
qol: made something easier to use
balance: UPP jackets no longer have massive armor, in exchange they no longer slow and in clothing vendors a light version of UPP armor is vendable
balance: UPP MPs are now armed with a ZHNK-72 belt on their jacket, with an additional shrapnelshot loader in their belt.
balance: Rebalances Type 71 damage/firerate/AP to be a sidegrade of M41A, about equal DPS, higher damage per shot and AP, lower fire rate, carbine is round-about the exact same as M41A however.
balance: Fixes UPP support armor, given to medics on their person and officers in their vendor, lighter version of UPP armor, exchanges protection for speed.
balance: Seperates SVD bullet damage from crude rifle bullet and buffs it as a hard-hitting AP bullet.
balance: Rebalances UPP revolver(now ZHNK-72), much harder hitting and has higher AP, but rarer, shrapnelshot extremely rare and good.
fix: UPP Major now has the correct UPP Commander skillset
fix: UPP Commander skillset can BE
fix: Fixes typepath for UPP support/light armor, actually works now.
spellcheck: Renames SVD to Type 88
spellcheck: Renames UPP Minigunner to UPP Machinegunner
spellcheck: Renames UPP jackets to UL4 all around
soundadd: Adds firing sounds for Type 73 and SVD/UPP MG
imageadd: Resprites the SVD, Type 71, and Type 23
maptweak: Changes instances of skorpion to non-upp type 64, also changes instances of ppsh to type 19
/:cl:

2023-07-11 19:36 UTC, BeagleGaming1 commented
Could you elaborate on what this was?
> qol: made something easier to use

2023-07-11 19:49 UTC, CapCamIII commented
> Could you elaborate on what this was?
> 
> > qol: made something easier to use

I forgot to remove the default CL for QOL

2023-07-24 21:24 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2023-07-26 17:34 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2023-07-27 22:08 UTC, c4xmaniac2 commented
holy shit this looks good

2023-08-02 03:50 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2023-08-02 21:15 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2023-08-07 08:59 UTC, cuberound commented
I think there will be issue if this gets merged without changes in UPP loadout in datums/module/equipment_preset/ . Or the ERT will call bunch of nonexisting guns on spawn. Can be done in separate pull reqest

2023-08-09 03:17 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2023-08-09 12:25 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2023-08-09 17:43 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2023-08-10 00:56 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2023-08-10 13:32 UTC, nauticall approved these changes
these look so much nicer. sprites approved, lets get this IN

2023-08-11 08:15 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2023-08-11 14:27 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2023-08-17 23:24 UTC, Nanu308 approved these changes
mapping lgtm

2023-08-17 23:24 UTC, Nanu308 commented on maps/map_files/Ice_Colony_v3/Shivas_Snowball.dmm
Mapping lgtm

2023-08-17 23:24 UTC, Nanu308 commented on maps/map_files/BigRed/BigRed.dmm
Mapping lgtm

2023-08-17 23:24 UTC, Nanu308 commented on maps/map_files/Sorokyne_Strata/Sorokyne_Strata.dmm
Mapping lgtm

2023-08-22 12:36 UTC, morrowwolf requested changes
No plates.

Do another pass over the black market changes, if I find something stupid in there in like a month I'm gonna be greatly annoyed.

2023-08-22 12:36 UTC, morrowwolf commented on code/modules/projectiles/guns/rifles.dm
> +	var/obj/item/attachable/scope/mini/SCOPE = new(src)
No all caps variable names

2023-08-22 12:36 UTC, morrowwolf commented on code/modules/projectiles/guns/pistols.dm
> +/obj/item/weapon/gun/pistol/t73/leader
If this has high impact rounds it needs to have a far more distinctive firing sound.

2023-08-25 04:05 UTC, Zonespace27 approved these changes

2023-08-25 04:13 UTC, merged