Adds new eggsac carrier sprites.
cmss13-devs/cmss13 pull request #3868
Opened 2023-07-12 11:58 UTC by MPhonks

# About the pull request

Adds new eggsac carrier sprites to the game. Includes unused eggsac overlay sprites for a "growing eggsac" based on how many eggs you have (similar to the hugger overlay, not implemented - no coding experience... :P)

# Explain why it's good for the game

Eggsac Carrier currently has no sprites, there's no differentiating one from a regular carrier.

# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

![grafik](https://github.com/cmss13-devs/cmss13/assets/134622054/3b1c271d-7a0f-4139-97cf-936feddd6ad0)

</details>

# Changelog

:cl: MarpleJones
add: Added Eggsac Carrier sprites to the game.
/:cl:

2023-07-13 17:30 UTC, MPhonks commented
Changed back it back to being an open PR. >:)

2023-07-14 10:06 UTC, harryob requested changes

2023-07-14 10:06 UTC, harryob commented on code/modules/mob/living/carbon/xenomorph/castes/Carrier.dm
> +		if(eggs_dropped == TRUE) //Checks whether or not to announce egg drop.
```suggestion
		if(eggs_dropped) //Checks whether or not to announce egg drop.
```

2023-07-14 10:40 UTC, MPhonks commented
One last sprite change upcoming.

2023-07-14 11:15 UTC, MPhonks commented on code/modules/mob/living/carbon/xenomorph/castes/Carrier.dm
> +		if(eggs_dropped == TRUE) //Checks whether or not to announce egg drop.
Committed and fixed.

2023-07-15 12:31 UTC, nauticall approved these changes
sprites are really nice, approved 👍

2023-07-24 12:22 UTC, merged