Yautja Armory and Ship changes
cmss13-devs/cmss13 pull request #3877
Opened 2023-07-13 17:02 UTC by realforest2001

# About the pull request
- Adds locks on the gladiator doors in Yautja Ship, and adds a plasma rifle armory to the ship locked to Ancient Yautja.
- Reduces amount of healing herbs in the Yautja Ship arena, and makes it clear they're supposed to stay on the ship. Moving most of them to the plasma armory.
- Fixes the "consoles" in the Yautja flight deck being the wrong way around.
- Adds access defines for Yautja ship doors, requiring display of a bracer ID chip.

# Explain why it's good for the game

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
code: Added access defines for Yautja ship.
code: Added rank identifiers on Yautja equipment presets to help set access levels on their bracer chips.
maptweak: Changed the doors on the Yautja ship to be their own subtypes, with certain ones being locked to Yautja or certain Yautja Ranks. Note: These locked doors require a Yautja to display their bracer ID chip.
maptweak: Replaced the unworthy prey section of the Yautja Ship with a secondary armory for plasma rifles, however the door is inaccessible to most Yautja. Intended to make it a bit less obvious admins are spawning them in for the rare times they're used/necessary.
maptweak: Reduces amount of herbs on the Yautja Ship.
maptweak: Fixes the "Consoles" orientation in the Yautja flight deck.
/:cl:

2023-07-17 23:16 UTC, Mister-moon1 commented
As this is the one bringing up the armoury, the plasma charges dont seem to be working as in they cannot be planted on walls, as far as i have tested

2023-07-19 07:13 UTC, Nanu308 reviewed
mapping lgtm

2023-07-24 21:17 UTC, harryob requested changes

2023-07-24 21:17 UTC, harryob commented on code/modules/cm_preds/yaut_items.dm
> +	blood_type = H.blood_type
```suggestion
/obj/item/card/id/bracer_chip/set_user_data(mob/living/carbon/human/human_user)
	if(!istype(human_user))
		return

	registered_name = human_user.real_name
	registered_ref = WEAKREF(human_user)
	registered_gid = human_user.gid
	blood_type = human_user.blood_type
```

2023-07-24 21:59 UTC, merged