Carrier Eggsac Strain can now place eggs on Regular Weeds
cmss13-devs/cmss13 pull request #3891
Opened 2023-07-14 16:12 UTC by Ben10083

# About the pull request

Eggsac Strain can now place eggs on regular weeds instead of only hive weeds

# Explain why it's good for the game

The eggsac strain is designed to be a mobile egg factory, able to place eggs closer to front for player huggers/general captures. However with limitations on only hiveweeds, it really limited the ability of the eggsac strain to utilize their strain's abilities, and the risk of losing a egg to marines forced them to stay at hive, making it a unpopular pick. This gives more purpose to the eggsac, allowing them to place eggs much closer to frontline for ghosts to spawn into/general captures, as well as a improv trap for approaching marines. They still have the risk of giving eggs to marines however, which I feel balances out this buff.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
balance: Carriers with Eggsac strain can now place eggs on regular weeds.
/:cl:

2023-07-16 18:20 UTC, Diegoflores31 commented
while looking at this any chance the egg generation cooldown is reduced a little ? its comically slow currently

2023-07-16 18:32 UTC, Ben10083 commented
> while looking at this any chance the egg generation cooldown is reduced a little ? its comically slow currently

I am sure it can be done, but I don't want to expand the scope of this pr anymore

2023-07-18 20:37 UTC, harryob requested changes

2023-07-18 20:37 UTC, harryob commented on code/modules/mob/living/carbon/xenomorph/egg_item.dm
> +	var/obj/effect/alien/weeds/any_weeds = null
= null is redundant

2023-07-18 22:29 UTC, Ben10083 commented on code/modules/mob/living/carbon/xenomorph/Xenomorph.dm
> +	var/egg_planting_range = 1 //tiles from self you can plant eggs.
Resolved, also had the others near it changed

2023-07-24 22:35 UTC, harryob approved these changes
code looks fine just resolve ur conflicts

2023-07-24 22:44 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2023-07-25 01:54 UTC, merged