Tunnel state fix
cmss13-devs/cmss13 pull request #390
Opened 2022-05-27 01:38 UTC by Shad0vvs

## About The Pull Request

Permissive abilities will still be allowed. (Like observing and such)

## Why It's Good For The Game

Bugfix no more queen ovi/screech in tunnels no more hedge rav spray in tunnels(sorry carnage), etc

## Changelog

:cl:
fix: Prevents Xeno abilities in tunnels.
/:cl:

2022-05-27 03:12 UTC, Carnage068 commented
RUDE AS HELL LOL

2022-05-28 20:58 UTC, Geevies requested changes

2022-05-28 20:58 UTC, Geevies commented on code/modules/mob/living/carbon/xenomorph/XenoProcs.dm
> +	var/turf/T = xeno.loc
```suggestion
```

2022-05-28 20:58 UTC, Geevies commented on code/modules/mob/living/carbon/xenomorph/XenoProcs.dm
> +		if(is_mob_incapacitated() || lying || buckled || evolving || !istype(T))
```suggestion
		if(is_mob_incapacitated() || lying || buckled || evolving || !isturf(loc))
```

2022-05-29 09:34 UTC, merged