Changes to squad color code
cmss13-devs/cmss13 pull request #3908
Opened 2023-07-16 21:50 UTC by BeagleGaming1

# About the pull request

Changes the squad text and equipment colors from a list into a variable that can be edited

# Explain why it's good for the game

This allows the squad information to be edited much easier mid-round, allowing the creation of new squads with new colors, and edits to pre-existing squads.

# Changelog
:cl:
code: Changed squad color code from a list to a variable
/:cl:

2023-07-16 23:39 UTC, BeagleGaming1 commented
I have probably broken so much with this PR. It worked locally but I don't know how it will go with more players

2023-07-18 09:18 UTC, harryob requested changes

2023-07-18 09:18 UTC, harryob commented on code/modules/clothing/gloves/marine_gloves.dm
> +*/
commented code

2023-07-18 09:18 UTC, harryob commented on code/game/jobs/job/marine/squads.dm
> +	chat_color = "#e67d7d"
these might wanna be defines like the minimap colors for visibility idfk tho

2023-07-18 17:10 UTC, harryob approved these changes

2023-07-18 23:04 UTC, BeagleGaming1 commented
Found some bugs from the test merge:
- If squad name is changed, req supply pads break
- If squad name is changed, crew manifest starts to runtime

2023-07-25 01:39 UTC, merged