(Requesting tactical testmerge) Sweeping LV522 Chances + FORECON GL being replaced by FORECON Sniper (Without the sniper)
cmss13-devs/cmss13 pull request #3917
Opened 2023-07-18 05:37 UTC by spartanbobby

# About the pull request

This PR makes alot of small changes to LV522 along with alot of big ones mainly

Blocks off the area north of fitness to prevent a "just go north" meta
Adds a new more central way to the reactor that branches off to 4 flanks should give LZ2 more use since it's a bit more central than LZ1
Adds a new route into the reactor from the SE
Blocks off the small alleyway north of the engineering funnel people into the dorm building
tightens up some parts of the reactor loosens some other parts
removes some detailing in the main hive areas to help builders
Adds new secrets to be found on the map
adds an overextension flank for those very brave marines to use
Changes to LZ2 making it more compressed
Addition of the FORECON Sniper (replacing the FORECON GL)
the FORECON sniper is a unique take on FORECON he spawns away from his fellow survivors next to the corpse of his battle buddy the advantage given to the sniper however is his thermal tarp a subtype of the ghillie suit with a placeholder sprite at the moment that will allow the sniper to hide and stealthily move throughout the colony to hopefully regroup with his squad
the M42A rifle has been removed from the map
Adds a small piece of text explaining that FORECON should probably move west to the crashed dropship to the FORECON intro

# Explain why it's good for the game

Map stuff:
LV522 currently just has a "go north" problem this PR aims to fix that by opening more routes for the marines to go, centralize the main route in an attempt to see more use in the rest of the colony and give LZ2 more use I'd really like to see this test-merged for a few days so see what needs addressing in this new area

the wall north of engineering looks kinda funky but having it there funnels people into the building and into the eastern section of the colony rather than a straight line to the reactor 

The FORECON Sniper:
Currently, FORECON GL is kinda unfitting and also kinda sucks the sniper, on the other hand, would be a perfect fit for FORECON now I'm not going to pretend the sniper isn't kinda OP right now so the FORECON sniper won't actually get his M42A just the ghillie suit that gives him still some uniqueness as a survivor as well as an incentive to survivor beyond the life of the regular sniper (to steal his gun)

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl: SpartanBobby
add: Added a new survivor to LV522 the FORECON sniper he spawns alone his only company being the corpse of his dead battle buddy, good luck
maptweak: Sweeping changes to LV522 including the reactor, north of engineering, LZ1, the entire central area of the map, and north of fitness in an attempt to see more of the colony used and to incentivize flanking
/:cl:

2023-07-22 03:55 UTC, Nanu308 approved these changes

2023-07-22 03:55 UTC, Nanu308 commented on maps/lv522_chances_claim.json
>          580,
Area Issues
![bilde](https://github.com/cmss13-devs/cmss13/assets/59782240/5ef41a51-7d36-4c1d-a1e4-3db79fc51db3)
![bilde](https://github.com/cmss13-devs/cmss13/assets/59782240/abdec39b-52c0-4aee-ba06-a62f4316cf0b)
![bilde](https://github.com/cmss13-devs/cmss13/assets/59782240/bdc0e726-0973-462a-b4c8-a2fbad72186f)
![bilde](https://github.com/cmss13-devs/cmss13/assets/59782240/351f3745-fef5-468e-bcb1-eb89783653e3)

Hull walls, doesnt seem intended.
![bilde](https://github.com/cmss13-devs/cmss13/assets/59782240/9a92ba8d-4c36-4d71-bbb8-c7c50edbbf1e)

Also a lot of areas seem to lack light fixtures 
Imagine this comment is on the .dmm file :D

2023-07-22 03:55 UTC, Nanu308 requested changes
e

2023-07-28 06:38 UTC, harryob requested changes

2023-07-28 06:38 UTC, harryob commented on code/modules/gear_presets/forcon_survivors.dm
> +	faction_group = list(FACTION_USCM, FACTION_SURVIVOR,)
```suggestion
	faction_group = list(FACTION_USCM, FACTION_SURVIVOR)
```

2023-07-28 06:38 UTC, harryob approved these changes

2023-07-28 07:24 UTC, merged