Adds a new jacket for the Commanding Officer
cmss13-devs/cmss13 pull request #3963
Opened 2023-07-21 20:15 UTC by BeagleGaming1

# About the pull request

Adds a jacket for CO

Requested by Dargus / Superreallycoolguy
# Explain why it's good for the game

More clothes and customization

# Changelog
:cl:
add: Added a new CO jacket to the CO vendor
/:cl:

2023-07-26 17:55 UTC, c4xmaniac2 commented
Wholesome speed merge now

2023-07-27 17:24 UTC, harryob requested changes

2023-07-27 17:24 UTC, harryob commented on code/modules/gear_presets/uscm_ship.dm
> +	dress_over = list(/obj/item/clothing/suit/storage/jacket/marine/dress/officer/white, /obj/item/clothing/suit/storage/jacket/marine/dress/officer/black, /obj/item/clothing/suit/storage/jacket/marine/
structure this as a long list
```
list(
    entry,
    entry,
)
```

2023-07-27 19:42 UTC, BeagleGaming1 commented on code/modules/gear_presets/uscm_ship.dm
> +		/obj/item/clothing/suit/storage/jacket/marine/dress/officer/falcon
```suggestion
		/obj/item/clothing/suit/storage/jacket/marine/dress/officer/falcon,
```

2023-07-27 20:52 UTC, morrowwolf requested changes

2023-07-27 20:52 UTC, morrowwolf commented on code/modules/gear_presets/uscm_ship.dm
> +	dress_over = list(
Probably don't want this under dress

2023-07-27 20:53 UTC, morrowwolf commented on code/modules/gear_presets/uscm_ship.dm
> +	dress_over = list(
Actually this entire vendor is really weirdly organized, whatever

2023-07-27 21:01 UTC, merged