More portable cades tweaks and buffs
cmss13-devs/cmss13 pull request #3967
Opened 2023-07-22 20:10 UTC by ihatethisengine

# About the pull request

Despite making a lot of tweaks and changes to portable cades I barely touched them in the game until recently. Now I have more experience and can tweak it again.

1) You can now stack scratched portable cades if their HP > 75%. But this will reduce the health of all barricades in the stack to the level of the most damaged. You can repair stacked cades but it will take longer time.

2) Miniengi pamphlet allows faster repairs but only when cade is folded. 

3) You can quickly collapse portable cades with crowbar if you have at least miniengi skills.

4) You no longer need to have folded portable cade in hand in order to repair it, but if you do, you can move while repairing.

# Explain why it's good for the game

1) It's extremely annoying to repair each individual cade in order to stack them just because it got hit by a stray bullet once. Now you can just ignore minor damage and keep going.

2) Yeah it took 10 second for PFC to repair each single cade. Really long. Now it's 5 seconds, but only when folded and if you have miniengi skills. Makes miniengi pamphlet a bit more relevant.

3) It was intended, but turned out it was a bit inconvenient. It was faster to collapse by hand because you didn't need to deal with tools. Now it requires just a crowbar and slightly faster. Also requires miniengi skill to use crowbar.

4) First was just a bit annoying, second allows more mobility which is the point of portable barricades.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl: ihatethisengine
balance: you can stack scratched portable cades if their HP at least 75%. Doing so will reduce the health of all barricades in the stack to the level of the most damaged.
balance: you can repair stacked portable cades but it will take longer time depending on how many cades in stack.
balance: miniengi skill makes repairs of folded portable cades faster (10 seconds to 5 seconds, same as engineer).
balance: with engineering skill at least of miniengi you can collapse deployed portable barricade with a crowbar (wrench is no longer required, slightly faster (2 sec to 1.5 sec)).
balance: you no longer need to have folded portable cade in hand in order to repair it.
balance: if you have folded portable cade in hand, you can move while repairing it.
/:cl:

2023-07-24 21:52 UTC, harryob approved these changes
code is fine

2023-07-27 11:25 UTC, morrowwolf commented
>You can now stack scratched portable cades if their HP > 75%. But this will reduce the health of all barricades in the stack to the level of the most damaged. You can repair stacked cades but it will take longer time.

This smells like a coder block rather than a real thought out feature. Make the stack store the damage values of the portacades or don't do this at all.

>Miniengi pamphlet allows faster repairs but only when cade is folded.

Why just when folded?

2023-07-27 11:29 UTC, ihatethisengine commented
> Why just when folded?
Don't want to affect actual combat balance, because miniengi pamphlet doesn't allow faster repairs of regular cades. But if you think it's fine then sure, I'll let miniengi to repair unfolded portable cades faster.

2023-07-27 11:43 UTC, morrowwolf commented
> > Why just when folded?
> 
> Don't want to affect actual combat balance, because miniengi pamphlet doesn't allow faster repairs of regular cades. But if you think it's fine then sure, I'll let miniengi to repair unfolded portable cades faster.

Honestly was just curious. This is good reasoning I say keep it.

2023-07-27 13:34 UTC, ihatethisengine commented
> This smells like a coder block rather than a real thought out feature. Make the stack store the damage values of the portacades or don't do this at all.

Quite a task it was, but I think I got it working.

2023-07-29 07:23 UTC, harryob requested changes

2023-07-29 07:23 UTC, harryob commented on code/game/objects/structures/barricade/deployable.dm
> +	var/list/stack_health = list(350)
use initial to get the default health here, not hardcoded. you’ll probably need to do it in init

2023-07-29 07:23 UTC, harryob commented on code/game/objects/structures/barricade/deployable.dm
> +		if(!ismob(src.loc)) //gather from ground
src is implicit just use loc

2023-07-29 07:23 UTC, harryob commented on code/game/objects/structures/barricade/deployable.dm
> +	stack_health = list(350, 350, 350)
same here, you’ll probably need to do it in initialize though

2023-07-30 10:18 UTC, harryob approved these changes

2023-07-30 10:27 UTC, merged