Changes to disarm / CQC code
cmss13-devs/cmss13 pull request #3970
Opened 2023-07-23 00:07 UTC by BeagleGaming1

# About the pull request

It was broken so disarm chance changing for CQC didn't work.
Makes how long disarms stun you for a difference between CQC skills.
Plus general code changes.

# Explain why it's good for the game

bug bad lol

# Changelog

:cl:
add: How long disarm stuns for depends on the difference in CQC skill between the participants
fix: CQC properly affects disarm chance again
/:cl:

2023-07-23 00:08 UTC, JosephBiell commented
I fully agree. Merge it now.

2023-07-23 05:50 UTC, morrowwolf requested changes

2023-07-23 05:50 UTC, morrowwolf commented on code/modules/mob/living/carbon/human/human_attackhand.dm
> +			var/defender_skill_level = skills ? skills.get_skill_level(SKILL_CQC) : 25 //No skills, assume max
Should reference the skill type maximum rather than hardcoded

2023-07-24 22:00 UTC, harryob approved these changes

2023-07-24 23:56 UTC, merged