External webbings
cmss13-devs/cmss13 pull request #3983
Opened 2023-07-24 18:27 UTC by Dorodomki

About the pull request

Makes the External Webbing Work like an Hazard suit, giving it more utility and storage variety

Explain why it's good for the game

it makes play forecon survivor a bit less horrible and makes the external webbing be at the same level with an hazard suit

2023-07-24 21:35 UTC, harryob requested changes

2023-07-24 21:35 UTC, harryob commented on code/modules/clothing/suits/miscellaneous.dm
> +			/obj/item/device/multitool,
```suggestion
		/obj/item/device/multitool,
```

2023-07-27 11:05 UTC, morrowwolf commented
I believe the no guns may be intentional.

2023-07-27 11:27 UTC, morrowwolf requested changes
Remove from staff officer lockers and you're good to go.

2023-07-28 06:34 UTC, closed without merging

2023-07-28 06:35 UTC, harryob commented
#4027