Infection Gamemode Announcement Fix
cmss13-devs/cmss13 pull request #3986
Opened 2023-07-24 22:41 UTC by Ben10083

# About the pull request

Special announcement for infection gamemode for each map. Small touches to gamemode code

Maps to find good announcement text for (not all may be given one)
- [ ] LVL-624
- [ ] CORSAT
- [ ] Solaris Ridge
- [ ] Sorokyne Strata
- [ ] Shivas Snowball
- [ ] Fiorina Cellblocks
- [ ] New Varadero
- [ ] LV-522 Chance's Claim
- [ ] Kutjevo Refinery
- [ ] Trijent Dam

# Explain why it's good for the game

Infection gamemode currently has a placeholder of a bad announcement, this brings it more inline with other gamemodes (COUGH Distress Signal COUGH) and fixes the gamemode code...a bit.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
add: Infection gamemode now has a unique announcement for each map, like Distress Signal
code: elements of distress signal post_setup code moved to parent to be called by all gamemodes
/:cl:

2023-07-24 23:10 UTC, harryob requested changes

2023-07-24 23:10 UTC, harryob commented on code/game/gamemodes/extended/infection.dm
> +		marine_announcement(rendered_announce_text, "[MAIN_SHIP_NAME]"))
```suggestion
		marine_announcement(rendered_announce_text, "[MAIN_SHIP_NAME]")
```

2023-07-25 01:51 UTC, Ben10083 commented
So lore peeps believe that it should be fine to leave the normal announcements as primary announcements for infection. Will leave the code for it to allow for that to change in the future.

2023-07-25 07:25 UTC, harryob approved these changes

2023-07-25 13:16 UTC, merged