Adds a False Testemony charge to Marine Law
cmss13-devs/cmss13 pull request #4009
Opened 2023-07-26 17:05 UTC by Smov1

# About the pull request

 Adds a new Marine Law charge "False Testemony". It was classified as a minor crime and 5 minutes brig timer.

# Explain why it's good for the game

Right now, Marine Law doesn't cover people purposely lying to MPs when they are asked about whether they saw who did what, etc. The closest thing we have is aiding and abetting but that usually only applies when someone actively attempts to help a suspect.

If the person that lied to the MP is proved to have lied, Marine Law should cover this circumstance. 

# Testing Photographs and Procedure

![image](https://github.com/cmss13-devs/cmss13/assets/52742585/751642c0-88a7-4ec7-a553-1487b3650a33)

# Changelog

:cl: smov
add: Adds a new Marine Law charge
/:cl:

2023-07-26 19:33 UTC, morrowwolf commented
Get this approved by Forest.

2023-07-26 21:20 UTC, realforest2001 requested changes

2023-07-26 21:20 UTC, realforest2001 commented on code/modules/law/laws/minor_crime.dm
> +	name = "False Testemony"
```suggestion
/datum/law/minor_law/false_testimony
	name = "False Testimony"
```

2023-07-26 21:20 UTC, realforest2001 commented on code/modules/law/laws/minor_crime.dm
> +	desc = "To intentionally and willingly lie to a MP or deputized officer, during a legal investigation with the intent to disrupt said investigation."
```suggestion
	desc = "To intentionally and willingly lie to an MP, or deputized officer, during a legal investigation with the intent to disrupt said investigation."
```

2023-07-26 21:20 UTC, realforest2001 commented on code/modules/law/laws/minor_crime.dm
> +/datum/law/minor_law/false_testemony
I'm fine with this as a law.

2023-07-27 03:29 UTC, Diegoflores31 commented on code/modules/law/laws/minor_crime.dm
> +	desc = "To intentionally and willingly lie to a MP or deputized officer, during a legal investigation with the intent to disrupt said investigation."
Miranda rights 💀

2023-07-27 10:23 UTC, morrowwolf commented
Make sure to update the ML section on the wiki (or pass it to wiki maintainers at least) when this is merged.

2023-08-04 05:10 UTC, harryob approved these changes

2023-08-04 05:46 UTC, merged