Log Updates
cmss13-devs/cmss13 pull request #4024
Opened 2023-07-27 20:28 UTC by realforest2001

# About the pull request
Adds new and updates old logs.

- Chestbursts now include location data.
- Near miss shots now include the name of the firer.
- Mentor Imaginary Friends now log their speech.
- Ahelps now log to chat when they're deferred to mentors.
- Phonecalls now log speech being relayed through a phone.

# Explain why it's good for the game
Knowledge is power.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
admin: Added logs for speech through telephones and deferring ahelps to mentors.
admin: Chestburst logs now include location data. Mentor Imaginary Friend now logs its speech. Narrow miss shots now log who fired them (where applicable).
/:cl:

2023-07-29 07:52 UTC, harryob requested changes

2023-07-29 07:52 UTC, harryob commented on code/datums/statistics/entities/death_stats.dm
> +	attack_log += "\[[time_stamp()]\] died to [cause_data.cause_name]"
no handling for a lack of cause data

2023-07-29 08:37 UTC, blackdragonTOW commented
Okay, but what do Xenos get?

2023-08-03 16:58 UTC, harryob approved these changes

2023-08-03 18:23 UTC, merged