J.O.E.Y. [Hyperstyled Edition]
cmss13-devs/cmss13 pull request #4042
Opened 2023-07-29 14:08 UTC by thwompa

# About the pull request

Replaces the cigarette vendor in maint bar with the workin' joey prop

# Explain why it's good for the game

_**V1BRANT S0VL**_

![image](https://github.com/cmss13-devs/cmss13/assets/103964974/d0d201a3-24a0-4a39-8353-a400f6f9987a)

# Changelog

:cl: Thwomper
maptweak: added Workin' Joey to maint bar.
/:cl:

2023-07-29 14:32 UTC, Zonespace27 requested changes

2023-07-29 14:32 UTC, Zonespace27 commented on maps/map_files/USS_Almayer/USS_Almayer.dmm
> +	icon = 'icons/obj/structures/props/props.dmi';
Make this a subtype

2023-08-02 03:55 UTC, BeagleGaming1 commented on code/game/objects/structures/props.dm
> +	icon_state = "joey"
```suggestion
	icon_state = "joey"

```

2023-08-02 06:56 UTC, Zonespace27 approved these changes

2023-08-02 07:04 UTC, merged