Standardize hugger attack windup and attack windup duration
cmss13-devs/cmss13 pull request #4044
Opened 2023-07-29 14:34 UTC by Drulikar

# About the pull request

This PR sets the attack windup duration for a player facehugger to 1 second, like it is for a pounce.

# Explain why it's good for the game

Since you can just pounce at point blank, there is zero reason for a point blank attack (that also requires them tackled) to take 6x longer. Any hugger that would do this would obviously be new to the caste for doing it in an inferior way.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

https://github.com/cmss13-devs/cmss13/assets/76988376/c81c1635-42a9-4b6a-8411-e99b562fdb98

</details>

# Changelog

:cl: Drathek
balance: Facehugger attack windup duration is now 1s like the pounce windup.
/:cl:

2023-07-29 23:05 UTC, Zonespace27 requested changes

2023-07-29 23:05 UTC, Zonespace27 commented on code/modules/mob/living/carbon/xenomorph/abilities/facehugger/facehugger_abilities.dm
> +#define FACEHUGGER_WINDUP_DURATION 1 SECONDS
Put this in __defines please, considering its multi-file usage

2023-07-30 08:33 UTC, harryob approved these changes

2023-07-30 08:47 UTC, Zonespace27 approved these changes

2023-08-01 20:31 UTC, merged