Yautja Vision Changes
cmss13-devs/cmss13 pull request #4046
Opened 2023-07-29 17:56 UTC by realforest2001

# About the pull request
This change alters Yautja to fit with the lore on our wiki, giving them natural thermal vision, and a weak night vision capability. To counterbalance this, in order to see clearer with the normal NVGs (which also allow to see the turfs behind other walls), a 5 charge per process fee must be paid, which when operating on the colony results in no natural recharge unless visor is disabled.
I have removed the termal and meson views from the clan mask, as meson was obsolete already and thermal now integrated with species. In doing said integration I have also added a var so different species can have differing inherent sight flags.
I've also updated the checks on the mask for using the visor, as previously you could not change visor setting without bracer, but you could keep the setting of a stolen mask without a bracer.

# Explain why it's good for the game

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
fix: Picking up a Yautja mask now correctly checks for bracers to apply the visor.
add: Added backend for species datums to hold inherent vision flags.
add: Added proc for Yautja mask to pass power drain back to bracers. Added small power drain on use of mask visor, balancing out with colony natural regen to net 0.
add: Added natural thermal vision and very weak night vision to Yautja species, to fit with our wiki lore.
del: Removed Thermal and Meson visors from Yautja mask.
/:cl:

2023-08-04 05:27 UTC, harryob requested changes

2023-08-04 05:27 UTC, harryob commented on code/modules/cm_preds/yaut_mask.dm
> +		STOP_PROCESSING(SSobj, src)
```suggestion
```

2023-08-04 05:27 UTC, harryob commented on code/modules/cm_preds/yaut_mask.dm
> +		return
```suggestion
		return PROCESS_KILL
```

2023-08-04 05:27 UTC, harryob commented on code/modules/cm_preds/yaut_mask.dm
> +		if(istype(visor,/obj/item/clothing/glasses/night/yautja))//To change if any new vision modes are made
```suggestion
		if(istype(visor, /obj/item/clothing/glasses/night/yautja))//To change if any new vision modes are made
```

2023-08-04 05:27 UTC, harryob commented on code/modules/cm_preds/yaut_mask.dm
> +		if(!istype(G,/obj/item/clothing/glasses/night/yautja))
```suggestion
		if(!istype(G, /obj/item/clothing/glasses/night/yautja))
```

2023-08-04 05:27 UTC, harryob commented on code/modules/cm_preds/yaut_mask.dm
> +			if(istype(visor,/obj/item/clothing/glasses/night/yautja))
```suggestion
			if(istype(visor, /obj/item/clothing/glasses/night/yautja))
```

2023-08-12 22:04 UTC, BeagleGaming1 requested changes

2023-08-12 22:04 UTC, BeagleGaming1 commented on code/modules/cm_preds/yaut_mask.dm
> +	var/obj/item/clothing/gloves/yautja/Y = M.gloves
single letter var

2023-08-12 22:04 UTC, BeagleGaming1 commented on code/modules/cm_preds/yaut_mask.dm
> +		if(!istype(G, /obj/item/clothing/glasses/night/yautja))
single letter var

2023-08-12 22:08 UTC, BeagleGaming1 commented on code/modules/cm_preds/yaut_mask.dm
> +	var/obj/item/clothing/gloves/yautja/Y = user.gloves
single letter var

2023-08-12 22:08 UTC, BeagleGaming1 commented on code/modules/cm_preds/yaut_mask.dm
> +	var/obj/item/G = user.glasses
single letter var

2023-08-12 22:09 UTC, BeagleGaming1 approved these changes
Code good

2023-08-12 22:11 UTC, BeagleGaming1 commented on code/modules/cm_preds/yaut_mask.dm
> +		to_chat(human_holder, SPAN_WARNING("Your bracers lack sufficient power to operate the visior."))
```suggestion
		to_chat(human_holder, SPAN_WARNING("Your bracers lack sufficient power to operate the visor."))
```

2023-08-12 22:48 UTC, merged