Yautja Scythe Bleed effect
cmss13-devs/cmss13 pull request #4047
Opened 2023-07-29 19:12 UTC by realforest2001

# About the pull request
Long ago the double-hit on the scythe was intended to be replaced with a bleed effect. Now, at least for humans, it has been done.

# Explain why it's good for the game
Hitting twice with a decently heavy hitting weapon is a bit silly, especially against marines as their health doesn't scale. This will hopefully balance it out the way originally intended.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
add: Yautja scythe now applies a bleed effect on humans rather than hitting twice.
/:cl:

2023-08-01 19:44 UTC, realforest2001 commented
Pending review/discussion on the gimmick of bleeding as it doesn't really have much of an effect beyond the natural bleed

2023-08-02 21:25 UTC, Zonespace27 reviewed
here's the fix

2023-08-02 21:25 UTC, Zonespace27 commented on code/modules/cm_preds/yaut_weapons.dm
> +		return FALSE
```suggestion
		return FALSE
	return TRUE
```

2023-08-02 21:25 UTC, Zonespace27 commented on code/modules/cm_preds/yaut_weapons.dm
> +	..()
```suggestion
	. = ..()
	if(!.)
		return FALSE
```

2023-08-08 20:30 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2023-08-09 13:49 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2023-08-10 15:39 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2023-09-11 06:01 UTC, harryob requested changes

2023-09-28 09:04 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2023-09-30 19:50 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2023-10-27 00:59 UTC, closed without merging