Fix remove iv needing power to operate.
cmss13-devs/cmss13 pull request #4070
Opened 2023-07-31 18:18 UTC by Huffie56

# About the pull request

# Explain why it's good for the game

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
add: Add a skill check to operate IV.
fix: Fix remove iv needing power to operate.
/:cl:

2023-07-31 18:21 UTC, Huffie56 commented
the var to make a check skill can't be use there so i am just going to remove the skill check.....

2023-08-01 00:33 UTC, Drulikar commented
> the var to make a check skill can't be use there so i am just going to remove the skill check.....

That's because the variables have terrible names in this proc. You likely need usr not user.

2023-08-01 09:33 UTC, Huffie56 commented
> > the var to make a check skill can't be use there so i am just going to remove the skill check.....
> 
> That's because the variables have terrible names in this proc. You likely need usr not user.

![image](https://github.com/cmss13-devs/cmss13/assets/117036822/544ea677-c03c-4254-bdf2-d62c34959d5e)

it's not user causing issue it seem it's the skill check... will keep looking into it....

2023-08-01 09:35 UTC, Huffie56 commented
i have no idea on how to fix the check skill issue so i will focus on making IV work without power for now...

2023-08-01 13:52 UTC, realforest2001 requested changes

2023-08-01 13:52 UTC, realforest2001 commented on code/game/machinery/iv_drip.dm
> +*/
```suggestion

		if(!skillcheck(user, SKILL_SURGERY, SKILL_SURGERY_NOVICE))
			to_chat(user, SPAN_WARNING("You don't know how to connect this!"))
			return

```

2023-08-01 13:52 UTC, realforest2001 commented on code/game/machinery/iv_drip.dm
>  		if(H.stat || get_dist(H, src) > 1 || H.blinded || H.lying)
```suggestion
		var/mob/living/carbon/human/user = usr
		if(user.stat || get_dist(user, src) > 1 || user.blinded || user.lying)
```

2023-08-01 13:52 UTC, realforest2001 commented on code/game/machinery/iv_drip.dm
>  			H.visible_message("[H] detaches \the [src] from \the [attached].", \
```suggestion
			user.visible_message("[user] detaches \the [src] from \the [attached].", \
```

2023-08-01 13:52 UTC, realforest2001 commented on code/game/machinery/iv_drip.dm
>  			"You detach \the [src] from \the [attached].")
You'll need to go through and replace the other instances of "H" with "user"

2023-08-01 20:08 UTC, Drulikar commented
> i have no idea on how to fix the check skill issue so i will focus on making IV work without power for now...

As I mentioned, and as you can see from Forest's suggestions, you can't merely copy and paste code and expect every variable to be named the same thing. In your image, each error is because `user` does not exist for the same thing it did from where you copied this code.

![image](https://github.com/cmss13-devs/cmss13/assets/76988376/04a5643c-668b-493f-8807-9056633be190)

2023-08-01 20:58 UTC, Huffie56 commented
will take a look at this in 10h i didn't feel like sinking 1-2h into this today.

2023-08-08 18:03 UTC, realforest2001 requested changes

2023-08-08 18:03 UTC, realforest2001 commented on code/game/machinery/iv_drip.dm
> +				if(user.species && user.species.flags & NO_BLOOD)
```suggestion
				var/mob/living/carbon/human/human_patient = patient
				if(human_patient.species && human_patient.species.flags & NO_BLOOD)
```

2023-08-08 18:04 UTC, realforest2001 approved these changes

2023-08-09 05:41 UTC, Drulikar commented on code/game/machinery/iv_drip.dm
> +			to_chat(user, SPAN_WARNING("You don't know how to connect this!"))
```suggestion
			to_chat(user, SPAN_WARNING("You don't know how to [attached ? "disconnect" : "connect"] this!"))
```

2023-08-09 06:09 UTC, merged