fix having inapropriate ammo in CL lockbox.
cmss13-devs/cmss13 pull request #4071
Opened 2023-07-31 20:08 UTC by Huffie56

# About the pull request

# Explain why it's good for the game
removing the improper ammo to stay consistent
adding a way to buy more ammo so that CL as a way to refill is weapon.
didn't wanted to give it for free in the lockbox.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
balance: adding the possibility to buy "ES-4 stun magazine" for 10 point in the portable vendor.
fix: remove a bunch of ammo that where improper for ES-4 gun that are in the lockbox.
/:cl:

2023-07-31 22:50 UTC, Zonespace27 requested changes
Your PR doesn't explain *why* the CL should lose their roundstart ammo

2023-08-01 00:30 UTC, MusselMain commented
> Your PR doesn't explain _why_ the CL should lose their roundstart ammo

as i mentioned in my bug report: the CL no longer spawns with the 88 Mod4 in their safe, instead spawning with the ES-4 electrostatic pistol, despite this the CL still receives a lockbox full of 88Mod4 rubber and AP ammo, when I asked a mentor where the CL could find a 88 mod4 to use this ammo, they responded with asking a marine to vend them one from a marine prep room, based on this I assume it's an oversight for the CL to have ammo for a weapon they aren't issued, and that they'd have to ask others for. The new sidearm the CL is issued only gets 3 magazines and it seems like there is no other place to find more, this PR not only solves the confusing question of "why would WY issue a nonlethal weapon to the CL, yet give them lethal ammo for a weapon they aren't issued", but also solves the problem of ES-4 ammo being extremely rare.

2023-08-01 07:00 UTC, Zonespace27 commented
> <snip>

No, i'm looking for justification for nuking the lockbox ammo entirely, as this PR does

2023-08-01 07:43 UTC, Huffie56 commented
> > <snip>
> 
> No, i'm looking for justification for nuking the lockbox ammo entirely, as this PR does

i removed /obj/item/storage/lockbox/loyalty/fill_preset_inventory() thinking it would work without it.
just fixed it i added screenshoot in testing if you want to see.
sorry for the confusion i forgot github doesn't test everything...

2023-08-01 07:49 UTC, Zonespace27 commented
> \<snip\>

This still fails to address the issue I raised of a pack of justification.

2023-08-01 08:19 UTC, Huffie56 commented
> > <snip>
> 
> This still fails to address the issue I raised of a pack of justification.

? i am confused i am not removing the lock-box just the ammo in it because it's obsolete considering the new gun CL as.
i don't see any reason to keep random magazine including lethal ammo in a lock-box.
Because if CL need to use them he could just get gun and ammo at requisition.

2023-08-01 14:40 UTC, MusselMain commented
> > <snip>
> 
> No, i'm looking for justification for nuking the lockbox ammo entirely, as this PR does

actually. fair point, having an empty lockbox seems a bit silly.

2023-08-01 14:42 UTC, MusselMain commented on code/game/objects/items/storage/lockbox.dm
> -
> Don't leave this empty else you're just giving an empty box with a lock on it. No issues with giving 2-3 spare mags for ES4 in here. Alternatively, move the ES4 from the CL's safe and put it in here with its current ammo cap.

If the sidearm and ammo is moved to the lockbox, that shouldn't be an issue outside of the closet being easier to break into then the safe

2023-08-01 15:39 UTC, Huffie56 commented on code/game/objects/items/storage/lockbox.dm
> -
i am just going to add 2 spare mags for the ES4
don't want to do any mapping on almayer right now to much PR causing merge conflicts....

2023-08-01 16:40 UTC, Zonespace27 approved these changes

2023-08-02 03:21 UTC, merged