Big red SW caves (gitlab port)
cmss13-devs/cmss13 pull request #408
Opened 2022-05-29 19:17 UTC by PhantomEpicness

## About The Pull Request
Somehow fixed the massive corruptions in this map by reverting and copy pasting changes onto github base. While it was approved on gitlab,  a re review is required since changes may have been lost in the revert.

Big red southwest caves are notoriously underwelming and underdeveloped at best. To make it worse, there is a hive spot slapped there, barely even a screen away from LZ2, which results in an extremely short round if marines land LZ2 with a SW caves hivespot
Furthermore, I added a new area, 'Abandoned mining', which is features a small depot, office and aswell as several small mining structures scattered in the area.
Also features a few goodies for survs who dare to venture here. Notable loot is some "mining explosive" (c4), a few guns and molotov cocktails + an m74 with some baton slugs

This addition also features some unique loot for survivors. Mining explosive is hidden somewhere there. Find it and you can open podlocks!

###The entire added areas. Note the unique terrian patterns compared to the rest of the caves in big red.
<img width="1396" alt="Screenshot_356" src="https://user-images.githubusercontent.com/42422230/170887721-2a5c04f4-190d-4ce7-8d93-1f76d5ece354.png">

## Why It's Good For The Game
reworks a very neglected and underwhelming part of the best map.

## Changelog

:cl: TotalEpicness5
add: Expanded big red's southwestern section.
add: Created 'Abandoned mining caves' an abandoned section of big red SW caves that features new cave networks and a warehouse for tight combat!
add: Moved big red SW caves hive spawn point to Abandoned Mining.
/:cl:

2022-05-29 20:30 UTC, PurpleCIoud commented
I like it

2022-05-29 21:53 UTC, MusselMain commented
Finally, Trijent and Solaris never get any updates (yes I know Solaris has that new Nightmare holds, but I've never seen them so until I see them ingame, I'm gonna assume they're not  merged yet).

2022-06-02 16:02 UTC, PhantomEpicness commented
Ready for review

2022-06-04 01:31 UTC, neroisvcute commented
Love seeing new additions to maps, thanks for making it.

2022-06-04 01:43 UTC, PhantomEpicness commented
- Did nanu changes
- Added some lore papers
- Added additional story stuff

2022-06-04 07:52 UTC, PhantomEpicness commented
Full narrative lore completed

2022-06-09 13:01 UTC, Nanu308 requested changes
Needs to be on the N wall, use Dir 1 and make sure it gets offset ingame onto the wall
![bilde](https://user-images.githubusercontent.com/59782240/172852558-28db79a7-4b61-4dac-beff-05385f1e9353.png)

This looks a bit weird with the wires, add another wire so it ends below them in a "wire knot" as well, ping me on Discord of confused.
![bilde](https://user-images.githubusercontent.com/59782240/172852868-60a6048b-8d4e-4316-b177-07be55eaf351.png)

Switch the floodlight crates out with a couple other things, as they can often times cause issues in their usage due to how certain machinery is handled as invulnerable.
![bilde](https://user-images.githubusercontent.com/59782240/172853171-d812a900-a38c-436b-aed0-a9ef85e9b1ab.png)

2022-06-17 19:05 UTC, Nanu308 requested changes

2022-06-17 19:05 UTC, Nanu308 commented on maps/map_files/BigRed/BigRed.dmm
>  /obj/structure/pipes/standard/simple/hidden/green{
Reactor Insert needs a fix, offset into ETA is messy.

2022-06-19 00:58 UTC, Nanu308 commented
lgtm

2022-06-19 00:58 UTC, merged