Adds campfires
cmss13-devs/cmss13 pull request #4091
Opened 2023-08-02 15:52 UTC by BeagleGaming1

# About the pull request

Adds campfires that provide heating to those nearby, while requiring fuel

Sprites and sound by Thwomper
# Explain why it's good for the game

They look cool and will allow marines, and maps, to have campfires without using braziers

# Changelog

:cl:
add: Adds campfires, craftable with wood
code: Modifies brazier construction code for easier use and mapping
/:cl:

2023-08-02 15:54 UTC, BeagleGaming1 commented
I'll fix the maps later

2023-08-02 22:30 UTC, BeagleGaming1 commented on code/game/objects/structures/props.dm
> +/obj/structure/prop/brazier/campfire
I'm considering moving this code up to `/obj/structure/prop/brazier`

2023-08-03 16:12 UTC, harryob requested changes

2023-08-03 16:12 UTC, harryob commented on code/game/objects/structures/props.dm
> +		if(!do_after(user, 3 SECONDS, INTERRUPT_MOVED, BUSY_ICON_BUILD))
```suggestion
		if(user.action_busy || !do_after(user, 3 SECONDS, INTERRUPT_MOVED, BUSY_ICON_BUILD))
```

2023-08-03 16:12 UTC, harryob commented on code/game/objects/structures/props.dm
> +		if(!do_after(xeno, 1 SECONDS, INTERRUPT_MOVED, BUSY_ICON_HOSTILE))
```suggestion
		if(xeno.action_busy || !do_after(xeno, 1 SECONDS, INTERRUPT_MOVED, BUSY_ICON_HOSTILE))
```

2023-08-04 05:04 UTC, FransFeiffer approved these changes
Sprites look nice, here's a spriter approval 👍

2023-08-04 05:06 UTC, harryob approved these changes

2023-08-04 05:32 UTC, merged