Royal Marines Commando
cmss13-devs/cmss13 pull request #4098
Opened 2023-08-03 05:00 UTC by spartanbobby

# About the pull request

This PR adds the Royal Marines Commando under the TWE as a faction and as an ERT, this PR is part 1 and more is planned to be added the reason why it isn't being added in this PR is that it isn't fully complete and these sprites have been waiting a very long time 

more will be added to the description of this PR at a later date I'm very tired right now

# Explain why it's good for the game

Gives the TWE some representation, adds some cool new faction stuff, an ERT, and equipment

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl: Tiodine Frans Warfan SpartanBobby Twomper Roboticpotato
add: Added Royal marines commando ERT and faction
/:cl:

2023-08-03 05:00 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2023-08-03 05:03 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2023-08-04 05:40 UTC, morrowwolf commented
Specific comms channel
faction_group needs to be updated and made tighter

2023-08-04 06:16 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2023-08-04 06:56 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2023-08-04 14:50 UTC, realforest2001 requested changes

2023-08-04 14:50 UTC, realforest2001 commented on code/game/objects/items/storage/belt.dm
> +
Already defined line 1083

2023-08-05 05:39 UTC, spartanbobby commented
I've removed the map camos and unused weapons, the unused weapons will probably be re-added by me as colony guns since I have no use for them and don't think they fit the royal marines. the map camos will be added when they are more complete later down the line

2023-08-05 19:15 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2023-08-06 08:52 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2023-08-07 14:01 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2023-08-07 18:16 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2023-08-07 22:14 UTC, Warfan1815 commented
Kaga wants the paygrades changed to the versions in my code before pushing: 

`/datum/paygrade/twe/rc1
	paygrade = "TC1"
	name = "Heitai-Marine"
	prefix = "Hti-Mne."

/datum/paygrade/twe/rc2
	paygrade = "TC2"
	name = "Santo-Lance Corporal"
	prefix = "St-LCpl."
	pay_multiplier = 2.1

/datum/paygrade/twe/rc3
	paygrade = "TC3"
	name = "Nito-Corporal"
	prefix = "Nt-Cpl."
	pay_multiplier = 2.2

/datum/paygrade/twe/rc4
	paygrade = "TC4"
	name = "Itto-Sergeant"
	prefix = "Sgt."
	pay_multiplier = 2.3`

2023-08-08 08:05 UTC, spartanbobby commented
> Kaga wants the paygrades changed to the versions in my code before pushing:
> 
> /datum/paygrade/twe/rc1 paygrade = "TC1" name = "Heitai-Marine" prefix = "Hti-Mne."
> 
> /datum/paygrade/twe/rc2 paygrade = "TC2" name = "Santo-Lance Corporal" prefix = "St-LCpl." pay_multiplier = 2.1
> 
> /datum/paygrade/twe/rc3 paygrade = "TC3" name = "Nito-Corporal" prefix = "Nt-Cpl." pay_multiplier = 2.2
> 
> /datum/paygrade/twe/rc4 paygrade = "TC4" name = "Itto-Sergeant" prefix = "Sgt." pay_multiplier = 2.3

Those are really dumb and are remnants from when the TWE was the RESS in our lore but sure I guess

2023-08-09 09:14 UTC, cm13live commented
This pull request has been mentioned on **CM-SS13**. Please provide feedback here:

https://forum.cm-ss13.com/t/three-world-empire-ert/1519/61

2023-08-09 17:43 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2023-08-12 06:15 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2023-08-14 00:19 UTC, Zonespace27 requested changes

2023-08-14 00:19 UTC, Zonespace27 commented on code/datums/emergency_calls/royal_marines.dm
> +				to_chat(mob, SPAN_ROLE_HEADER("You are a skilled marksman in the Royal Marines Commando. Born in the three world empire."))
Twe is a proper noun

2023-08-14 00:19 UTC, Zonespace27 commented on code/datums/emergency_calls/royal_marines.dm
> +		to_chat(M, SPAN_BOLD("You were born in the Three World Empire to a [pick(75;"average", 15;"poor", 10;"well-established")] family."))
Pick weight

2023-08-14 00:19 UTC, Zonespace27 commented on code/datums/emergency_calls/royal_marines.dm
> +		to_chat(M, SPAN_BOLD("You were soon after assigned to a royal marine base on mars to act as support personnel."))
Is royal marine proper?

2023-08-14 00:19 UTC, Zonespace27 commented on code/datums/emergency_calls/royal_marines.dm
> +	to_chat(M, SPAN_BOLD("You are [pick(80;"unaware", 15;"faintly aware", 5;"knowledgeable")] of the xenomorph threat."))
Pick weight

2023-08-14 00:19 UTC, Zonespace27 commented on code/datums/factions/royalmarinescommando.dm
> +		list("VP78 pistol", 20, /obj/item/weapon/gun/pistol/vp78, null, VENDOR_ITEM_REGULAR),
Caps

2023-08-14 00:19 UTC, Zonespace27 commented on code/game/objects/items/devices/radio/encryptionkey.dm
> +	channels = list("Command" = TRUE, "Almayer" = TRUE,)
```suggestion
	channels = list("Command" = TRUE, "Almayer" = TRUE,)

```

2023-08-14 00:19 UTC, Zonespace27 commented on code/game/objects/items/storage/backpack.dm
> +	name = "\improper heavyweight RMC backpack"
Why improper

2023-08-14 00:19 UTC, Zonespace27 commented on code/game/objects/items/storage/belt.dm
> +	for(var/i = 1 to storage_slots)
```suggestion
	for(var/i in 1 to storage_slots)
```

2023-08-14 00:19 UTC, Zonespace27 commented on code/game/objects/items/storage/belt.dm
> +	for(var/i = 1 to storage_slots)
```suggestion
	for(var/i in 1 to storage_slots)
```

2023-08-14 00:19 UTC, Zonespace27 commented on code/game/objects/structures/props.dm
> +	name = "FV150 Shobo MKII"
```suggestion
	name = "\improper FV150 Shobo MKII"
```

2023-08-14 00:19 UTC, Zonespace27 commented on code/modules/clothing/head/head.dm
> +	desc = "A standard military turban found in the royal marines. Considered a rare item these kind of turbans are prized by collectors in the UA."
```suggestion
	desc = "A standard military turban found in the royal marines. Considered a rare item, these kind of turbans are prized by collectors in the UA."
```

2023-08-14 00:19 UTC, Zonespace27 commented on code/modules/clothing/head/helmet.dm
> +	name = "L5A2 ballistic helmet"
Improper

2023-08-14 00:19 UTC, Zonespace27 commented on code/modules/clothing/head/helmet.dm
> +	name = "L5A3 ballistic helmet"
Improper

2023-08-14 00:19 UTC, Zonespace27 commented on code/modules/clothing/masks/gasmask.dm
> +	name = "L7 gasmask"
Improper

2023-08-14 00:19 UTC, Zonespace27 commented on code/modules/gear_presets/royal_marines.dm
> +	new_human.gender = pick(80;MALE,20;FEMALE)
Pick weight

2023-08-14 00:19 UTC, Zonespace27 commented on code/modules/gear_presets/royal_marines.dm
> +	var/headset_type = /obj/item/device/radio/headset/distress/royal_marine
Code doc

2023-08-14 00:19 UTC, Zonespace27 commented on code/modules/projectiles/ammo_datums.dm
> +	var/holo_stacks = 15
Code doc

2023-08-18 18:28 UTC, spartanbobby commented on code/datums/emergency_calls/royal_marines.dm
> +	var/synths = 1
Resolving this because it wasn't even meant to be there and is now gone

2023-08-25 04:18 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2023-08-25 12:38 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2023-08-25 14:08 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2023-08-26 10:37 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2023-08-28 19:16 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2023-08-29 13:09 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2023-09-01 00:30 UTC, morrowwolf requested changes

2023-09-01 09:05 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2023-09-01 09:43 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2023-09-01 11:53 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2023-09-01 12:17 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2023-09-01 23:11 UTC, sleepynecrons approved these changes
sprites LGTM

2023-09-02 04:49 UTC, morrowwolf requested changes
Are there any on_mobs for the weapons on back/suit?

2023-09-02 04:49 UTC, morrowwolf commented on code/game/objects/items/storage/backpack.dm
> +	max_storage_space = 21
Waaaay too big, tone this back

2023-09-02 04:49 UTC, morrowwolf commented on code/modules/gear_presets/royal_marines.dm
> +/datum/equipment_preset/twe/royal_marine/spec/machinegun
Needs smartgun ammo

2023-09-03 00:37 UTC, spartanbobby commented
> Are there any on_mobs for the weapons on back/suit?

None, that's why they cant go on there

2023-09-06 19:38 UTC, harryob requested changes

2023-09-06 19:38 UTC, harryob commented on code/game/objects/items/storage/backpack.dm
> +	can_hold = list(/obj/item/ammo_box/magazine/misc/mre,/obj/item/storage/firstaid/regular,/obj/item/storage/firstaid/adv,/obj/item/storage/firstaid/surgical,/obj/item/device/defibrillator/compact,/obj
```suggestion
	can_hold = list(
		/obj/item/ammo_box/magazine/misc/mre,
		/obj/item/storage/firstaid/regular,
		/obj/item/storage/firstaid/adv,
		/obj/item/storage/firstaid/surgical,
		/obj/item/device/defibrillator/compact,
		/obj/item/tool/surgery/surgical_line,
		/obj/item/tool/surgery/synthgraft,
		/obj/item/storage/box/packet/rmc/he,
		/obj/item/storage/box/packet/rmc/incin
	)
```

long lists should be formatted like this

2023-09-06 19:38 UTC, harryob commented on code/game/objects/items/storage/belt.dm
> +	holster_slots = list( // PLACEHOLDER PLEASE REPLACE
is that so?

2023-09-06 19:38 UTC, harryob commented on code/modules/clothing/shoes/marine_shoes.dm
> +	items_allowed = list(/obj/item/attachable/bayonet, /obj/item/weapon/throwing_knife, /obj/item/weapon/gun/pistol/holdout, /obj/item/weapon/gun/pistol/clfpistol)
```suggestion
	items_allowed = list(
		/obj/item/attachable/bayonet,
		/obj/item/weapon/throwing_knife,
		/obj/item/weapon/gun/pistol/holdout,
		/obj/item/weapon/gun/pistol/clfpistol,
	)
```

2023-09-06 19:38 UTC, harryob commented on code/modules/gear_presets/royal_marines.dm
> +	A.randomize_appearance(new_human)
```suggestion
	var/datum/preferences/placeholder_pref = new()
	placeholder_pref.randomize_appearance(new_human)
```

2023-09-06 19:38 UTC, harryob commented on code/modules/gear_presets/royal_marines.dm
> +	//
who this

2023-09-06 19:38 UTC, harryob commented on code/modules/gear_presets/royal_marines.dm
> +	//
sir ?

2023-09-06 19:38 UTC, harryob commented on code/modules/gear_presets/royal_marines.dm
> +	//
ditto

2023-09-06 19:38 UTC, harryob commented on code/modules/gear_presets/royal_marines.dm
> +	//
ditto

2023-09-06 19:38 UTC, harryob commented on code/modules/gear_presets/royal_marines.dm
> +	//
?

2023-09-06 19:38 UTC, harryob commented on code/modules/gear_presets/royal_marines.dm
> +	//
?

2023-09-06 19:38 UTC, harryob commented on code/modules/gear_presets/royal_marines.dm
> +	//
?

2023-09-06 19:38 UTC, harryob commented on code/modules/gear_presets/royal_marines.dm
> +	//
?

2023-09-06 19:38 UTC, harryob commented on code/datums/emergency_calls/royal_marines.dm
> +	to_chat(M, SPAN_BOLD("Assist the USCMC Force of the [MAIN_SHIP_NAME] however you can."))
```suggestion
/datum/emergency_call/royal_marines/print_backstory(mob/living/carbon/human/spawning_mob)
	to_chat(spawning_mob, SPAN_BOLD("You were born in the Three World Empire to a [pick_weight(list("average" = 75, "poor" = 15, "well-established" = 10))] family."))
	to_chat(spawning_mob, SPAN_BOLD("Joining the Royal Marines gave you a lot of combat experience and useful skills."))
	to_chat(spawning_mob, SPAN_BOLD("You are [pick_weight(list("unaware" = 75, "faintly aware" = 15, "knoledgeable" = 10))] of the xenomorph threat."))
	to_chat(spawning_mob, SPAN_BOLD("You are a citizen of the three world empire and joined the Royal Marines Commando"))
	to_chat(spawning_mob, SPAN_BOLD("You are apart of a jointed UA/TWE taskforce onboard the HMS Patna and Thunderchild."))
	to_chat(spawning_mob, SPAN_BOLD("Under the directive of the RMC high command, you have been assisting USCM forces with maintaining peace in the area."))
	to_chat(spawning_mob, SPAN_BOLD("Assist the USCMC Force of the [MAIN_SHIP_NAME] however you can."))
```

2023-09-06 19:38 UTC, harryob commented on code/datums/emergency_calls/royal_marines.dm
> +	M.transfer_to(mob, TRUE)
```suggestion
/datum/emergency_call/royal_marines/create_member(datum/mind/spawning_mind, turf/override_spawn_loc)
	var/turf/spawn_loc = override_spawn_loc ? override_spawn_loc : get_spawn_point()

	if(!istype(spawn_loc))
		return //Didn't find a useable spawn point.

	var/mob/living/carbon/human/mob = new(spawn_loc)
	spawning_mind.transfer_to(mob, TRUE)
```

2023-09-08 09:28 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2023-09-08 10:26 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2023-09-08 16:28 UTC, harryob approved these changes

2023-09-08 16:37 UTC, merged