Changes to Organ-Stabilizing property
cmss13-devs/cmss13 pull request #4117
Opened 2023-08-06 06:55 UTC by BeagleGaming1

# About the pull request

Changes Organ-Stabilizing from an on/off flag to being dependent on the organs damage

# Explain why it's good for the game

Makes organ damage matter more if you get injured enough

# Changelog

:cl:
balance: Changes organ-stabilizing property to require a higher level for more damaged organs
/:cl:

2023-08-06 10:02 UTC, morrowwolf requested changes
I think having it be a reduction in effect rather than complete turn off would be better. It would be less effective as the organ damage became worse.

Peri should be a way to limp away as someone with organ damage. I'd like a negative effect of some sort associated.

2023-08-12 01:32 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2023-08-12 02:05 UTC, BeagleGaming1 commented on code/modules/organs/organ_internal.dm
> +	// If you lose a vital organ, you die immediately
```suggestion
	/// If you lose a vital organ, you die immediately
```

2023-09-09 08:33 UTC, morrowwolf commented
Gonna come back to this in the future

2023-09-09 08:33 UTC, closed without merging