Crashed UPP Survivors Insert Tweaks
cmss13-devs/cmss13 pull request #4123
Opened 2023-08-06 16:20 UTC by Steelpoint

# About the pull request

Still WIP. Got other stuff I want to do.

Changes based on feedback and personal observations

- Reduced spawns so there is only 1 Medic and 1 Engineer spawn, but they are both now a higher priority to spawn. Spawns should now go SL > Spec > Engi / Medic > Soldiers.
- Decreased chance of a UPP spawning with a Pulse Carbine slightly, due to how weak it is. Now 1/5 chance instead of 1/3.
- UPP SL spawns with a guaranteed set of armour and their beret instead of a officer's jacket. Feels more thematic and the officer's jacket is meant for high ranking officers and not SLs. Might investigate giving them a broken JTAC backpack. 
- Adds some buckshot ammo to the crashed dropship due to low ammo amount given to UPP who spawn with shotgun. UPP Shotgun feels balanced since it has high upfront damage but a low RoF. However low ammo meant a lot of people were ditching them for survivor shotguns. 
- SL and Spec now have driving skills.  

# Explain why it's good for the game

The Medic/Engi changes ensure there is a guarantee of a single Medic and Engineer outside of very lowpop. I was noticing the prior spawn system means you'll see a lot of Medics but rarely a Engineer. This change should also mean more people will spawn as Soldiers instead of 90% of the squad being Medics and Engineers. 

Everything else is self explanatory. 

More stuff to come, thinking off adding supply caches to non-meta hold areas to encourage UPP to explore other areas for supplies. 

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
balance: Balance changes to UPP survivor spawns on Trijent. Guarantee you'll get 1 Medic and 1 Engineer. Some skill changes. More buckshot ammo. 
/:cl:

2023-08-14 18:26 UTC, Steelpoint commented
Ok, I think we're good.

2023-08-23 20:54 UTC, Zonespace27 requested changes
get a mapper to sign off and i'll merge

2023-08-23 20:54 UTC, Zonespace27 commented on code/game/objects/items/devices/radio/headset.dm
> +	name = "UPP headset"
```suggestion
	name = "\improper UPP headset"
```

2023-08-25 04:18 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2023-08-28 07:09 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2023-08-30 19:39 UTC, morrowwolf approved these changes
Looks good let's gooo!

2023-08-30 19:48 UTC, merged