Lights turn on at roundstart
cmss13-devs/cmss13 pull request #4129
Opened 2023-08-07 02:14 UTC by BeagleGaming1

# About the pull request

Lights on the ship are off when the round starts then turn on for 4 to 15 seconds

# Explain why it's good for the game

https://www.youtube.com/watch?v=WCtkibZqSpk

# Changelog

:cl:
add: Ship lights turn on at round start
/:cl:

2023-08-07 02:20 UTC, BeagleGaming1 commented on code/controllers/subsystem/ticker.dm
> +	for(var/obj/structure/machinery/power/apc/apc in machines)
I hope this is the right place to put this

2023-08-08 08:38 UTC, morrowwolf commented
TM'ing so I can see how long 4-15 seconds really is with start up. I'll take a closer look at where in ticker you put this later

2023-08-09 13:41 UTC, harryob requested changes

2023-08-09 13:41 UTC, harryob commented on code/controllers/subsystem/ticker.dm
> +	for(var/obj/structure/machinery/power/apc/apc in machines)
this should be an SSticker.OnRoundstart()

2023-08-09 13:41 UTC, harryob commented on code/modules/power/apc.dm
> +		operating = 0
these should be FALSE/TRUE defines

2023-08-09 13:41 UTC, harryob commented on code/modules/power/apc.dm
> +	operating = 1
as above

2023-08-10 12:31 UTC, morrowwolf requested changes
I think this would be cooler if it was by light rather than by area APC so as to have kind of a delayed flicker to the lighting of each area

2023-09-09 08:33 UTC, closed without merging