Foxtrot cryomarines spawn as freed mobs if not taken
cmss13-devs/cmss13 pull request #4132
Opened 2023-08-07 08:09 UTC by ihatethisengine

# About the pull request

Foxtrot cryomarines spawn as freed mobs if not taken.

# Explain why it's good for the game

It sucks when only 3 cryomarines spawn in because there is not enough candidates. Now people can take cryomarines later.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl: ihatethisengine
add: foxtrot cryomarines spawn as freed mobs if not taken.
/:cl:

2023-08-08 01:07 UTC, cm13live commented
This pull request has been mentioned on **CM-SS13**. Please provide feedback here:

https://forum.cm-ss13.com/t/foxtrot-minimum-deployment-number/3623/2

2023-08-12 18:54 UTC, Zonespace27 requested changes
Lgtm otherwise

2023-08-12 18:54 UTC, Zonespace27 commented on code/datums/emergency_calls/cryo_marines.dm
> +	shipwide_ai_announcement("Successfully deployed [mob_max] Foxtrot marines, of which [length(members)] ready for duty.")
```suggestion
	shipwide_ai_announcement("Successfully deployed [mob_max] Foxtrot marines, of which [length(members)] are ready for duty.")
```

2023-08-12 18:54 UTC, Zonespace27 commented on code/datums/emergency_calls/cryo_marines.dm
> +	// if(length(members))
?

2023-08-12 18:57 UTC, ihatethisengine commented on code/datums/emergency_calls/cryo_marines.dm
> +	// if(length(members))
```suggestion
```

2023-08-12 18:57 UTC, ihatethisengine commented on code/datums/emergency_calls/cryo_marines.dm
> +	// if(length(members))
forgot to delete

2023-08-12 19:51 UTC, Zonespace27 approved these changes
Good for tm

2023-08-17 10:02 UTC, harryob approved these changes

2023-08-17 10:24 UTC, merged