Adds vehicles skill to the Commanding Officer & Auxiliary Support Officer
cmss13-devs/cmss13 pull request #4140
Opened 2023-08-08 15:52 UTC by kirieee

# About the pull request

Adds vehicles skill to the commanding officer, CO survivors, and auxiliary support officer. 

# Explain why it's good for the game

It doesn't make sense that a senior officer like an O4 or an O6 can't at least figure out how to drive a truck. Auxiliary support officers work closely with requisitions and would also likely know how to operate a vehicle. Driving is fun. 

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

</details>

# Changelog

:cl: Tallfission

add: Vehicles skill for Commanding Officer and Auxiliary Support Officer jobs

/:cl:

2023-08-08 17:55 UTC, realforest2001 requested changes
Don't forget Executive Officer.

2023-08-08 18:32 UTC, kirieee commented
XO now has vehicles skill. I debated giving it to CE too but I decided against it

2023-08-08 18:44 UTC, realforest2001 approved these changes

2023-08-09 12:53 UTC, harryob approved these changes

2023-08-09 13:10 UTC, merged