Update chat-dark.scss
cmss13-devs/cmss13 pull request #4151
Opened 2023-08-10 10:16 UTC by blackdragonTOW

Changing Asay back to the Msay color that many were used to for a very long time.

# Explain why it's good for the game

Because this color doesn't blend in with other major chat colors (such as dsay, and others), and it reminds us of simpler times.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
admin: Adjustment of ASay color
/:cl:

2023-08-10 12:40 UTC, realforest2001 requested changes
This is currently making tickets appear brown too, please can you make it so tickets remain purple so they're easier to identify.

2023-08-10 19:48 UTC, blackdragonTOW commented
Removed changes to headminsay colors as those do not alter the asay color of hosts in asay.

Additionally, as it stands before this change, ASay is purple.  Tickets are purple.  There hasn't been confusion about those colors being the same, so the change here is fine.   Tickets are a function of ASay and move through that channel, thus the coloring.
To make tickets and asay separate we would have to add a great deal that would be outside the scope of this color change PR and would need to be atomized with another PR.

2023-08-10 21:13 UTC, blackdragonTOW commented
What if we did.........this....

2023-08-10 21:14 UTC, blackdragonTOW commented
Okay, this should achieve the following goals:
Headmins have different colors in ASay
ASay chat messages are the OG mod colors
Ahelps are still purple
ASay and AHelps are now distinct colors.

2023-08-10 22:04 UTC, realforest2001 approved these changes

2023-08-10 22:04 UTC, realforest2001 commented on code/modules/admin/tabs/admin_tab.dm
>  	if(ishost(usr))
```suggestion
	if(check_rights(R_PERMISSIONS))
```

2023-08-11 11:03 UTC, harryob requested changes

2023-08-11 11:03 UTC, harryob commented on code/modules/admin/tabs/admin_tab.dm
> +	if(check_rights(R_PERMISSIONS))
```suggestion
	if(check_rights(R_PERMISSIONS, show_msg = FALSE))
```
or you'll spam non-permissioned users when they try to talk

2023-08-12 22:37 UTC, harryob approved these changes

2023-08-12 23:32 UTC, merged