Taskboard Request: IOs 2: The smartening
cmss13-devs/cmss13 pull request #416
Opened 2022-06-01 16:36 UTC by CometBlaze

## About The Pull Request

Credits to Casper Evans for doing 90% of the coding work, I just did the mapping and a little bit of clean up.

The long awaited sequel to a beloved classic, now with slightly less nuclear fallout!
As the title implies this PR aims to bring IOs back into rotation without the mess that was DEFCON, to that end, instead of receiving powerful gear as a reward for doing their job, IOs will now be able to purchase extra OBs alongside more points for Req and CAS.

These points can be acquired through a myriad of ways like the obvious intel hunting, but marines will also be rewarded for setting comms and the colony powernet. Don't feel like going all the way to engineering just to get some points? Fear not, retrieving corpses (xeno or marine) will also net you some points, just stick the marines in the morgue and the xenos in one of the containment cells, the bigger the xeno, the more points you get!

The points rewarded by each task are subject to change as testing goes on and of course, any feedback is appreciated.

## Why It's Good For The Game

Provides ambusher castes with another juicy target to harass and gives marines a new playstyle different from the usual pew pew bang.
Encourages marines to pursue other goals that aren't just pushing hive, like setting power and gives xenos another location to attack.
Promotes the use of fulton which means the transport PO gets to click on one more button per trip.
Also a lot of people wanted it, so it must mean it's good, right?

## Changelog

:cl: CasperEvans, CometBlaze
add: IOs are back! You need 5 hours in squad roles to be able to select them
add: Gathering intel, setting communications, enabling colony power and collecting corpses (human or xeno) will now award you tech points, these points can be cashed in for extra points for Req or CAS or for more OBs at any tech console.
add: All maps now have documents and other relevant items scattered about them
add: The old IO office has been refurbished to serve a new purpose: being an office for IOs
add: Data Detectors have been made available to marine vendors
add: ARES now yells at command when comms are estabilished
add: Marines can now get small document pouches from their vendor
balance: Requisitions no longer receives points every 30 minutes
balance: Reduced number of roundstart OBs from 4 to 2
fix: Colonists and colonist corpses no longer show up on the marines' crew monitor
tweak: Filing cabinets now dump their contents when destroyed
/:cl:

2022-06-01 17:12 UTC, Git-Nivrak commented
Holy based

2022-06-02 12:27 UTC, PurpleCIoud commented
Yes!! However with current Xenos, IOs are too weak. I think IOs need Endurance of a survivor or better to not get neurospamed by one xeno.

2022-06-02 13:35 UTC, frozentsbgg commented
Lgtfm. Please. God bless.

2022-06-03 12:12 UTC, fira commented
FINALLY an actual IO integration rework, kudos for that

2022-06-03 14:22 UTC, fira requested changes
Some comments - also we spoke in discord about need of making at least a summary design doc. It needs not be extensive and cover legacy DEFCON/Techwebs mechanics, but at least cover what's new and overall design/intent behind

2022-06-03 14:22 UTC, fira commented on code/modules/objectives/experimental_devices.dm
>  /obj/item/device/mass_spectrometer/adv/objective/Destroy()
This needs to clean up `objective` just above or at least null the reference

2022-06-03 14:22 UTC, fira commented on code/modules/objectives/experimental_devices.dm
> +	var/datum/cm_objective/retrieve_item/device/objective
same etc for all items, needs to clean up. alternatively, consider using a component to be able to make any item an objective

2022-06-03 14:22 UTC, fira commented on code/modules/reagents/chemistry_properties/prop_special.dm
> +	message_staff("The research department has discovered DNA_Disintegrating in [holder.name] adding [OBJECTIVE_ABSOLUTE_VALUE * 2] bonus DEFCON points.")
not defcon

2022-06-04 01:23 UTC, neroisvcute commented
Awesome shit, I’ve missed IO for a long time. Thanks for coding this

2022-06-09 13:02 UTC, Nanu308 commented
So you dont lose GPB from this

2022-06-18 22:42 UTC, stanalbatross commented
I would also disable the passive req money gain in this PR

2022-06-19 02:56 UTC, morrowwolf commented
New line in the job preferences looks real bad as it is.

2022-06-19 05:39 UTC, Lunaslantern commented
I played as an IO in the first test round on 6/18 and have a few notes for you.
- Recommend updating equipment racks with more attachments. Could be balanced by having a specific stock of items similar in nature to the VC gear Racks

- Recommend either switching Mk1 rifle with Mk1 rifle kit or allowing purchase of more mk 1 magazines for IOs in their racks, so they do not need to pile into Req if they all use the MK 1 rifles

- Alternatively recommend using IO racks to store standard ammunition or a standard weapons rack, similar to squad prep rooms

- Recommend that ARES updates Command and Intel channels whenever Intel is input to the console (in addition to the timed announcements of intel he already had), probably best to have it on a 90sec cool down so as to avoid spamming those channels

- Recommend removal or rework of Techwebs console. If it will no longer be used them removal, if used then recommend changing it to different UI

- Recommend creating system similar req computers for using intel points, this console should replace the Techwebs console and have a sister unit located in the CiC for easy use in case the IOs all get eaten by xenos (or they are just feeling lazy)
1. This console should display current amount of intel as well as the rate it is increasing
2. it should also display the available options for the spending of intel 
3. this can be broken down into personnel, munitions and supplies (broken down further in points 4-6 with ideas that do not reflect what is or is not already available for purchase with intel)
4. Personnel tab would contain reinforcements, additional synth, freelancer and Marsoc options
5. Munition tab would contain *limited* spec kits for riflemen, OB rounds of the crews choice, the tank, special ammunition for standard weapons (incin, toxin, etc) and lastely a nuclear device
6. Supplies tab would contain points purchase for Requisitions, PO weapons points, the APC tab and replacement parts for the tank/apc
7. Purchased items would be added to the next raised elevator in Req

While I did not play IO before they were removed, I believe I can see a spot for them in the game at current and the work you have all put into this so far is great. These do not need to be quoted as fact and I will not be upset at all if you cannot or decide not to implement any of these changes. I recognize some of these could be a lot of work, and I really appreciate your effort! Thank you

2022-06-19 07:06 UTC, bardinatavern4 commented
It'd be neat if IOs could somehow benefit from the intel they get. Maybe some extra attachies or higher-end gear if they collect a bunch. Just my 2 cents

2022-06-19 07:54 UTC, Segrain commented on code/modules/cm_tech/techs/marine/tier1/points.dm
> +	var/points_to_give = 7000
That is $700000. Mind the multiplier. No idea what the intended amount is, but it is definitely not _this_.

2022-06-19 07:58 UTC, Segrain commented on code/game/objects/items/fulton.dm
> +	addtimer(CALLBACK(src, .proc/return_fulton, original_location), 10 SECONDS)
Why...?

2022-06-19 17:27 UTC, Lunaslantern commented
Also I completely forgot, but we may want to change the rank for IOs also (unless they are Navy still) I would recommend them be warrant officers, but being LTs just like POs would work fine as well

2022-06-20 07:50 UTC, fira commented on code/game/objects/structures/stool_bed_chair_nest/bed.dm
> +		if(isXeno(C) && C.stat == DEAD && (world.time < (C.timeofdeath + 2 MINUTES)))
Mind that this was part of the original intelwebs capture experiment, not of techwebs or defcon, so you might not want to keep it for what you're doing

2022-06-20 07:50 UTC, fira commented on code/game/objects/items/fulton.dm
> +			LAZYADD(failed_fultons, attached_atom)
sorry, how did you solve it ? i don't understand

2022-06-22 12:47 UTC, stanalbatross commented
You need to make the job setup screen nanoUI wider as it is squashed and too small right now

2022-06-22 12:51 UTC, stanalbatross commented
IOs still use the old "ensign" rank

2022-06-22 13:12 UTC, stanalbatross commented
`(ARES v3.2) ([F](byond:///?src=[0x300008e];track=[0x3000008])) [Command] states, " SYSTEMS REPORT: Colony communications link online."`
document in CL or remove (and get rid of the brackets around ARES)

2022-06-22 13:34 UTC, stanalbatross commented
remove `message_admins()` procs that you used for testing

2022-06-22 13:36 UTC, fira commented on code/modules/objectives/retrieve_items.dm
> +/datum/cm_objective/retrieve_item/fulton/proc/clean_up_fulton()
Ohh yeah, that works, just make objective handles adding to list too then (so it both adds and removes in same place)

You might want to move the list define aswell then so it makes sense (or can make it a GLOBal one, as in `code/_globalvars/lists/`)

2022-06-22 13:43 UTC, stanalbatross commented
intel subsystem and other system both spawning bodies leading to body spam

plz fix

2022-06-22 14:56 UTC, stanalbatross commented
remove being able to drag permadead bodies or document in the CL

2022-06-23 09:16 UTC, morrowwolf commented
Charlie/delta bunks got a bit taken out of their NE wall somehow from this.

2022-06-23 09:39 UTC, sose96 commented
Nice but echo squad has just become escort duty for IO’s which i get, but i think it would be better if perhaps the IO was assigned to a squad or something instead so echo can still be used

2022-06-23 16:43 UTC, Diegoflores31 commented
> Nice but echo squad has just become escort duty for IO’s which i get, but i think it would be better if perhaps the IO was assigned to a squad or something instead so echo can still be used

Echo is optional and their objectives declared by Xo or Co

2022-06-25 13:41 UTC, stanalbatross commented
testmerge again soontm

2022-06-29 12:00 UTC, stanalbatross commented
all marines can see objectives - this should be limited ideally to IOs and command/people in the CIC?

2022-06-29 12:47 UTC, stanalbatross commented
> > all marines can see objectives - this should be limited ideally to IOs and command/people in the CIC?
> 
> That is intentional. My idea is to make it so, although IOs are still the best at it, anyone can help with earning points. I think allowing everyone to view objectives makes it easier to know what needs to be done and also that your contribution is being useful.

might deemphasise communication between IOs and wannabe IOs if the wannabe IOs can operate entirely independently, however

2022-06-29 14:55 UTC, Kraseo commented
in a solaris ridge round at server time 14:30, the 'data' tab in the view objectives interface made tgui crap out whenever it was selected, trying to reference a disk with no colour (trying to find a disk that got deleted somehow maybe?)

https://i.imgur.com/03WTcQq.png

2022-06-29 20:59 UTC, stanalbatross commented
![image](https://user-images.githubusercontent.com/66756236/176543787-c3d316de-ce6d-4768-9ebe-a115a5284494.png)
 fix corpses like this (I am 99% sure the intel system spawns them)

2022-06-29 22:11 UTC, stanalbatross commented
> > 
> 
> Are they spawning on top of each other still?

dunno

also if you removed cas passive point gen you should probably add it back

2022-06-29 22:15 UTC, stanalbatross commented
also make tech purchasing controllable from consoles in the cic like it was back in defcon (so cic officers can buy techs at all times)

2022-06-29 22:43 UTC, stanalbatross commented
> > also make tech purchasing controllable from consoles in the cic like it was back in defcon (so cic officers can buy techs at all times)
> 
> Right now the tech leader can buy tech anywhere by simply going into the IC tab and accessing the tech tree from there, I can add a tech console to CIC so they can rotate leadership more easily if that's what you want

preferably the leader system would be removed and buying would be 100% controlled from a single console in the CIC which any officer could access (but this is just my preference, check with nanu for concrete design stuff)

a tech console is definitely needed in the cic too

2022-06-30 09:32 UTC, Lokiki01 commented
![image](https://user-images.githubusercontent.com/30368011/176643642-3eb776dd-fb42-443d-9ff9-e5dd2f5fa0b7.png)

Fatal bug at objectives UI in data section (Where info about disks should be)

2022-06-30 10:54 UTC, stanalbatross requested changes

2022-06-30 10:54 UTC, stanalbatross commented on code/game/machinery/vending/vendor_types/intelligence_officer.dm
> +		list("APC Circuit Board", 5, /obj/item/circuitboard/apc, null, VENDOR_ITEM_REGULAR),
usually called a power control board or something 

use the actual item name

2022-06-30 10:54 UTC, stanalbatross commented on code/game/machinery/vending/vendor_types/intelligence_officer.dm
> +		list("Large Shotgun Shell Pouch", 10, /obj/item/storage/pouch/shotgun/large, null, VENDOR_ITEM_REGULAR),
you can add more pouches + put pouches in a different section

2022-06-30 10:54 UTC, stanalbatross commented on code/game/machinery/vending/vendor_types/intelligence_officer.dm
> +		list("Vertical Grip", 10, /obj/item/attachable/verticalgrip, null, VENDOR_ITEM_REGULAR)
all attachments were removed from vendors after the update in nov of last year, take these out and make the ammo section more similar to that of PO vendors

2022-06-30 10:54 UTC, stanalbatross commented on code/game/machinery/vending/vendor_types/intelligence_officer.dm
> +		list("Mini Radio Telephone Pack", 0, /obj/item/storage/backpack/marine/satchel/rto/small, MARINE_CAN_BUY_BACKPACK, VENDOR_ITEM_REGULAR),
but why

2022-06-30 10:54 UTC, stanalbatross commented on code/game/machinery/vending/vendor_types/intelligence_officer.dm
> +		list("ACCESSORIES (CHOOSE 1)", 0, null, null, null),
add drop pouch

2022-06-30 10:54 UTC, stanalbatross commented on code/modules/admin/tabs/debug_tab.dm
> +	var/value = tgui_input_list(src, "Choose which tree to enter", "Enter Tree", trees)
make it so that if there is only one tree in list `trees` then you bypass the list

2022-06-30 10:54 UTC, stanalbatross commented on code/modules/admin/tabs/debug_tab.dm
> +	var/value = tgui_input_list(src, "Choose which tree to give points to", "Give Points", trees)
same as above

2022-06-30 10:54 UTC, stanalbatross commented on code/modules/cm_aliens/structures/special/egg_morpher.dm
> +
remove vestiges of xeno tech stuff

2022-07-01 04:19 UTC, JohnDoe50974 commented
> > Tech Tree manipulation has been reworked.
> > You can now purchase techs if you are at least intel trained, this means IOs, SOs and all heads can make purchases. Purchases are no longer made using the View Objectives command in the IC tab, in fact, View Objectives has been removed. This was done in order to incentivise coordination between IO ground teams and whoever is processing intel. The View Objectives UI is now accessed via Tech Control Consoles, you need to be intel trained in order to use the Tech Control Console, this means that anyone with access to the Tech Control Console can purchase techs. There are two Tech Control Consoles in the Almayer, one is in CIC and the other is in the IO Computer Lab.
> 
> On second thought nuking View Objectives was a bit extreme so it's back again, it can only be viewed by those who are intel trained and it can no longer be used to access the tech tree. Instead using the Tech Control Console will now lead directly to the tree, the leadership systems is still gone.

I don't believe this is a good change, it command players are not included in this this will exclude them from the tech loop completely when all of the current purchases are a strategic decision which is what CO/XO is meant to be doing. Giving so many persons access also vastly increases the possible avenues of griefing the system by spending points on unnecessary techs (like, for example, DS budget increase when there is 0 pilots). Please keep the co/xo techweb authority and add another tech control console to CIC.

2022-07-01 09:08 UTC, stanalbatross commented
No need for it to be restricted to one leader, we never had a problem without that during defcon. Just keep tech control inside the cic

2022-07-01 11:39 UTC, tempelers commented
Lowering the price of the DS budget to 10 or 12.5 would be a great change

2022-07-03 19:38 UTC, stanalbatross commented
`ARES v3.2 [Command] states, " 0 tech points available."`
stray space before the number

2022-07-03 23:52 UTC, stanalbatross commented
> `ARES v3.2 [Command] states, " 0 tech points available."` stray space before the number

also this message shouldn't be appearing until after drop time

2022-07-05 21:49 UTC, stanalbatross requested changes

2022-07-05 21:49 UTC, stanalbatross commented on code/modules/mob/living/carbon/xenomorph/attack_alien.dm
> -	if(stat != DEAD || chestburst || spawned_corpse)
this was causing spawned corpse grabbing to fail on live, remove

2022-07-05 21:49 UTC, stanalbatross commented on code/modules/cm_tech/trees/marine.dm
> +		to_chat(M, SPAN_WARNING("You don't have the training to use [src]."))
```suggestion
		to_chat(M, SPAN_WARNING("You don't have the training to use \the [src]."))
```

2022-07-05 21:49 UTC, stanalbatross commented on code/modules/cm_tech/trees/marine.dm
> +	var/name = "ALMAYER TECH LEVEL UPGRADED"
we might want to take a second look at this announcement (Defcon sounds way better imo)

2022-07-05 21:49 UTC, stanalbatross commented on code/modules/cm_tech/trees/marine.dm
> +	desc = "A console used to acquire the means to control the techtree."
sounds very awkward

2022-07-05 21:49 UTC, stanalbatross commented on code/modules/cm_tech/techs/marine/tier2/orbital_ammo.dm
> +	announce_message = "Additional Orbital Bombardment ordnance (HE) have been delivered to Requisitions' ASRS."
"ordnance" is singular so it should be "ordnance has been delivered" or "warheads have been delivered". Not what it currently is.

2022-07-05 21:49 UTC, stanalbatross commented on code/modules/cm_tech/techs/marine/tier1/points.dm
> +	announce_message = "Additional Dropship Part Fabricator Points have been authorised for this operation."
inconsistent capitals

2022-07-05 21:52 UTC, stanalbatross commented
next testmerge soontm, I will try to get people to give more feedback that isn't just "ios cool me likey"

2022-07-07 14:43 UTC, stanalbatross commented
> > The new IO papers that spawn in the bodies can't be moved and bug out on the egg morpher making it impossible for xenos to click the actual eggmorpher to get out huggers ![image](https://user-images.githubusercontent.com/66756236/177579538-1986b9a2-bf24-4c80-a7c4-da2f74d1b673.png)
> 
> The papers aren't supposed to be movable to prevent xenos from hiding the papers or dragging them to some random corner. I could remove the spawners in the corpses to prevent the issue of corpses with papers clogging the mog morpher but I don't think making intel objects draggable by xenos is a good idea.

this comment was taken from a xenomain who was too lazy to make a github account and just DMed the bug to me

I think making the papers spawn *around* the body might be better, like on their tile or offset a bit.

2022-07-07 22:00 UTC, stagda commented
In the last round I noticed that CIC used points to purchase a cluster OB and the announcement said 2 cluster OBs were delivered but there was only one warhead in the crate. Not sure if the announcement needs to be adjusted or code tweaked so correct amount of OBs spawn.

2022-07-10 10:27 UTC, FlamermanGrills commented
I think making the objective tab able to be seen by all marines would be nice to have since if the IOs die it's a big pain to figure out disk and the like.

2022-07-10 12:14 UTC, stanalbatross commented
> I think making the objective tab able to be seen by all marines would be nice to have since if the IOs die it's a big pain to figure out disk and the like.

IOs are meant to be the centre of intel - if they all die it's only natural that it would make intel work much harder. Maybe being able to view them on a computer in the IO lab would work

2022-07-10 19:10 UTC, stanalbatross commented
add a "check objectives" console in the IO room (so that non-IO decoders can do their job a bit better plus help coordinate IOs if they so please)

2022-07-13 22:08 UTC, stanalbatross commented
I think most of the bugs/code issues with this have been ironed out and it is in a mostly ready state

2022-07-19 14:44 UTC, Nanu308 requested changes
Good starting point overall, after seeing it in action across the maps, objectives+costs will most likely be tweaked in a future separate MR.

Good to go for now after Mk1 has been stripped, as we're trying to hinder people going a certain role just for the equipment.

2022-07-19 14:44 UTC, Nanu308 commented on code/modules/reagents/chemistry_properties/prop_special.dm
> +	ai_announcement("NOTICE: $20000 received from USCSS Royce and sent to assets. Shuttle inbound.")
Dont change the AI Announcement text, keep it as is

2022-07-19 14:44 UTC, Nanu308 commented on code/game/machinery/vending/vendor_types/intelligence_officer.dm
> +		list("M41A Pulse Rifle MK1", 30, /obj/item/weapon/gun/rifle/m41aMK1, null, VENDOR_ITEM_RECOMMENDED),
Drop Mk1

2022-07-19 14:44 UTC, Nanu308 commented on code/game/machinery/vending/vendor_types/intelligence_officer.dm
> +		list("M41A MK1 Magazine (10x24mm)", 6, /obj/item/ammo_magazine/rifle/m41aMK1, VENDOR_ITEM_REGULAR),
Drop Mk1

2022-07-19 14:44 UTC, Nanu308 commented on code/game/machinery/vending/vendor_types/intelligence_officer.dm
> +		list("M2 Night Vision Goggles", 20, /obj/item/prop/helmetgarb/helmet_nvg, null, VENDOR_ITEM_RECOMMENDED),
Increase cost to 25 on NVG's

2022-07-21 15:59 UTC, stanalbatross commented
if tpanel isn't fixed by this time tomorrow I will just merge this and we can fix any (unlikely) bugs or issues that do crop up in later PRs

2022-07-24 20:06 UTC, stanalbatross requested changes

2022-07-24 20:06 UTC, stanalbatross commented on html/changelogs/archive/2022-07.yml
> +
fix dis

2022-07-25 12:31 UTC, stanalbatross requested changes

2022-07-25 12:31 UTC, stanalbatross commented on code/controllers/subsystem/communications.dm
> +var/const/INTEL_FREQ	= 1356
change the "tactics" channel in constants.js to "intel" for radio TGUI

2022-07-25 15:49 UTC, stanalbatross commented on code/controllers/subsystem/communications.dm
> +var/const/INTEL_FREQ	= 1356
should be fine then

2022-07-27 11:22 UTC, stanalbatross commented
![image](https://user-images.githubusercontent.com/66756236/181234599-b2b5eedb-61da-43ca-9881-2e58a81eab9d.png)
bit close to the lz innit?
![image](https://user-images.githubusercontent.com/66756236/181234665-a78a13d1-71c3-4993-9453-9e82c5e06b08.png)
landmarks will spawn on top of vial boxes leading to potential confusion
spread them around, leave on the floor and such
![image](https://user-images.githubusercontent.com/66756236/181234783-6ea1e39d-5e77-4e0f-b589-a0f147ca0045.png)
move some of the intel in dorms into EVA
dorms is easy to get to and not very dangerous as marines are usually close by
eva is more out of the way

I'm pretty ok with the rest of BR

2022-07-27 11:25 UTC, stanalbatross commented
I'm fine with LV

2022-07-27 11:27 UTC, stanalbatross commented
![image](https://user-images.githubusercontent.com/66756236/181235820-b1ae3471-878a-47b9-9153-552065ba1cd8.png)
mostly fine with shiva's, you could put a little more intel around the centre of the map here, but it's not a big deal

2022-07-27 11:29 UTC, stanalbatross commented
my one thought about annex is that there aren't enough landmarks

try putting some more in the area between lz1 and lz2, and in lowsec, as well as some far landmarks in fibrebush and servers

map otherwise fine tho

2022-07-27 11:29 UTC, stanalbatross commented
kutjevo has a lot, not sure how it will play out, tldr we will see

2022-07-27 11:30 UTC, stanalbatross commented
trijent could do with more proper intel (not science landmarks) and more far landmarks across the north-south river in labs and medical

2022-07-27 11:31 UTC, stanalbatross commented
![image](https://user-images.githubusercontent.com/66756236/181236552-883d4789-9bb8-4323-aad5-5f302c033ea5.png)
replace some with far landmarks

rest of soro is fine

2022-07-27 11:39 UTC, stanalbatross approved these changes
code fine, I've read the entire thing like twice and for the last few TMs there haven't been any bugs

if something crops up once this is merged it will be dealt with in another PR

2022-08-01 20:32 UTC, merged