attachment obliteration
cmss13-devs/cmss13 pull request #4217
Opened 2023-08-20 18:59 UTC by Diegoflores31

# About the pull request

fixes #4194 
Fixes weird behaviour with underbarrel fire extinguisher being able to be used one handed on some weapons but not on others 

All attachable weapons will now require you to hold them with both hands in order to be used. (( added an exception flag for future attachies that may need it))

standarized error message you receive when you are not wielding an attachment.

# Explain why it's good for the game

realism and standarized behaviour for all attachments 

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
balance: Masterkey and underbarrel extinguisher now must be wielded in order to be used.
fix: Underbarrel extinguisher no longer bypass wielding restrictions on flamers.
/:cl:

2023-08-20 19:09 UTC, Zonespace27 requested changes
Thanks for getting to this before me

2023-08-20 19:09 UTC, Zonespace27 commented on code/modules/projectiles/gun.dm
> +				to_chat(user, SPAN_WARNING("[active_attachable] is empty !"))
?

2023-08-20 19:09 UTC, Zonespace27 commented on code/modules/projectiles/gun.dm
> +					to_chat(user, SPAN_WARNING("You must wield \the [src] to fire \the [active_attachable]!"))
\the is implicit

2023-08-20 19:09 UTC, Zonespace27 commented on code/modules/projectiles/gun.dm
> +			if(active_attachable && active_attachable.flags_attach_features & ATTACH_PROJECTILE)
why do you check it twice

2023-08-20 19:09 UTC, Zonespace27 commented on code/modules/projectiles/gun_attachables.dm
> +		to_chat(user, SPAN_WARNING("You must wield \the [gun] to fire \the [src]!"))
\the is implicit

2023-08-20 19:09 UTC, Zonespace27 commented on code/modules/projectiles/gun_attachables.dm
> +		to_chat(user, SPAN_WARNING("You must wield \the [gun] to fire \the [src]!"))
\the is implict

2023-08-20 19:13 UTC, Diegoflores31 commented on code/modules/projectiles/gun.dm
> +				to_chat(user, SPAN_WARNING("[active_attachable] is empty !"))
oops lol

2023-08-23 20:47 UTC, Zonespace27 requested changes
thought i submitted this earlier

2023-08-25 19:57 UTC, Zonespace27 approved these changes
good

2023-08-25 20:07 UTC, merged