refactor : clean dmi file extract spritten hiden inside other sprites direction. removing sprite change from dmm files.
cmss13-devs/cmss13 pull request #4232
Opened 2023-08-22 15:15 UTC by Huffie56

# About the pull request
clean dmi file extract sprite hidden inside other sprites direction. removing sprite change from dmm files.

# Explain why it's good for the game
it's good for mappers and our common sanity.
sprite shouldn't be hidden into sprite and sprite shouldn't be change in DMM files....

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
refactor: clean dmi file extract sprite hidden inside other sprites direction. removing sprite change from dmm files.
/:cl:

2023-08-22 17:13 UTC, Drulikar requested changes
See my suggestions and repeat. It's not that it was missing new lines, it's that when you use ; that indicates there is supposed to be another var edit on the following line.

2023-08-22 17:13 UTC, Drulikar commented on maps/map_files/FOP_v3_Sciannex/Fiorina_SciAnnex.dmm
>  	dir = 1;
```suggestion
	dir = 1
```

2023-08-22 17:13 UTC, Drulikar commented on maps/map_files/FOP_v3_Sciannex/Fiorina_SciAnnex.dmm
> +
```suggestion
```

2023-08-22 17:13 UTC, Drulikar commented on maps/map_files/FOP_v3_Sciannex/Fiorina_SciAnnex.dmm
>  	dir = 8;
```suggestion
	dir = 8
```

2023-08-22 17:13 UTC, Drulikar commented on maps/map_files/FOP_v3_Sciannex/Fiorina_SciAnnex.dmm
> +
```suggestion
```

2023-08-22 17:13 UTC, Drulikar commented on maps/map_files/FOP_v3_Sciannex/Fiorina_SciAnnex.dmm
> +	dir = 4;
```suggestion
	dir = 4
```

2023-08-22 17:13 UTC, Drulikar commented on maps/map_files/FOP_v3_Sciannex/Fiorina_SciAnnex.dmm
> +
```suggestion
```

2023-08-22 17:13 UTC, Drulikar commented on maps/map_files/FOP_v3_Sciannex/Fiorina_SciAnnex.dmm
> +	dir = 1;
```suggestion
	dir = 1
```

2023-08-22 17:13 UTC, Drulikar commented on maps/map_files/FOP_v3_Sciannex/Fiorina_SciAnnex.dmm
> +
```suggestion
```

2023-08-22 17:13 UTC, Drulikar commented on maps/map_files/FOP_v3_Sciannex/Fiorina_SciAnnex.dmm
>  	dir = 4;
```suggestion
	dir = 4
```

2023-08-22 17:13 UTC, Drulikar commented on maps/map_files/FOP_v3_Sciannex/Fiorina_SciAnnex.dmm
> +
```suggestion
```

2023-08-22 17:13 UTC, Drulikar commented on maps/map_files/FOP_v3_Sciannex/Fiorina_SciAnnex.dmm
>  	dir = 4;
```suggestion
	dir = 4
```

2023-08-22 17:13 UTC, Drulikar commented on maps/map_files/FOP_v3_Sciannex/Fiorina_SciAnnex.dmm
> +
```suggestion
```

2023-08-22 17:13 UTC, Drulikar commented on maps/map_files/FOP_v3_Sciannex/Fiorina_SciAnnex.dmm
>  	dir = 4;
```suggestion
	dir = 4
```

2023-08-22 17:13 UTC, Drulikar commented on maps/map_files/FOP_v3_Sciannex/Fiorina_SciAnnex.dmm
> +
```suggestion
```

2023-08-22 21:04 UTC, Huffie56 commented
i saw in mapbot that i made an oupsy
will fix it later...

2023-08-23 00:26 UTC, Nanu308 requested changes

2023-08-23 00:26 UTC, Nanu308 commented on maps/map_files/FOP_v3_Sciannex/Fiorina_SciAnnex.dmm
![bilde](https://github.com/cmss13-devs/cmss13/assets/59782240/d3875ac5-2dc5-4a48-a371-53bbd801003e)
You're making visual changes to the tiles used. Make sure you keep it the same if this is just a refractor.

2023-08-23 13:12 UTC, Huffie56 commented on maps/map_files/FOP_v3_Sciannex/Fiorina_SciAnnex.dmm
fixed no map change as far as i can tell now.

2023-08-24 08:30 UTC, Huffie56 commented
i remove all the icon-state for floors for fiorina their is like 600 random icon state to handle for the map....

2023-08-26 12:39 UTC, Drulikar commented
Sprites and mapping aren't generally things I can approve/merge but there is nothing obviously wrong with the changes at the moment.

2023-08-26 13:45 UTC, Huffie56 commented
> 

thanks anyway for checking it...

2023-08-31 20:14 UTC, harryob approved these changes
bless you

2023-08-31 20:29 UTC, Huffie56 commented
> bless you

this is a pain to do won't do this every month....

2023-08-31 20:36 UTC, merged