IO/FTL Can Buy Welding Vision + M12 Helm Holds 2 Visors
cmss13-devs/cmss13 pull request #4263
Opened 2023-08-26 08:33 UTC by Steelpoint

# About the pull request

Intel Officers and Fire Team Leaders can now purchase a Welding Visor, the price remains consistant with the welding goggle price (5 for IO, 10 for FTL).

Furthermore, the M12 Helmet (Nominally used by FTL's, IO's and other officers) can have up to two visors inserted instead of only one. Allowing someone to place both a welding visor and a medical visor (or security visor?) inside the helmet. 

# Explain why it's good for the game

Increases gameplay variety for IO's/FTLs wanting a combo of a medical hud and welding visor. Many IOs and FTL's often don't take advantage of their ability to perform engineering work, so rewarding a proactive user with the ability to use a medical and welding visor seems justifiable, especially as they need to expend precious (and limited) points to purchase something that can not be acquired anywhere else on the Almayer. 

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
add: IO's and FTL's can now purchase a 'welding visor' from their vendor. This visor grants whichever helmet it is attached with the ability to flip a protective visor that prevents the user's eyes from taking damage while welding. 
balance: The M12 Helmet, normally used by FTL's and USCM Officers, can mount two visors at once, instead of only one. 
/:cl:

2023-08-27 09:57 UTC, harryob approved these changes

2023-08-27 17:20 UTC, morrowwolf requested changes

2023-08-27 17:20 UTC, morrowwolf commented on code/game/machinery/vending/vendor_types/squad_prep/squad_tl.dm
> -		list("Welding Goggles", 5, /obj/item/clothing/glasses/welding, null, VENDOR_ITEM_REGULAR),
Preferably don't remove these just add another option. I wanted to move away from sci-fi eye pieces but welder goggles fit perfectly in the setting aesthetic.

2023-08-28 04:02 UTC, Steelpoint commented
Requested changes made.

2023-08-28 13:38 UTC, morrowwolf approved these changes

2023-08-28 13:46 UTC, merged