New SO uniform
cmss13-devs/cmss13 pull request #4320
Opened 2023-09-02 20:41 UTC by CapCamIII

# About the pull request

Does new CIC sprites, they look cool.
New cosmetic options with brown gloves and boots
New outfit that looks like the operation uniform gorman wears in the movie
CTs getting actual caps instead of beanies is nice, RO(i'm not calling it QM 🖕) still has a distinct hat to seperate the two out.

# Explain why it's good for the game

New sprites, service uniforms being static to the map makes sense as the operations uniform is what is wore groundside in the movie, service uniform is more of a shipside/non-combat uniform

# Images

![image](https://github.com/cmss13-devs/cmss13/assets/103988604/206fac1f-c84a-4edd-bc98-3f670e92c2e8)

# Changelog

:cl: CapCamIII, AmoryBlaine
add: Adds new service uniform sprite that is standard across maps, sprites by AmoryBlaine
add: Resprites old dress uniform, renames it, adds to XO vendor as a uniform choice as it fits there now, sprites by AmoryBlaine
add: Adds new uniform, command boiler suit like gorman wears in the movie, available in SO locker, SO vendor, XO vendor, CO vendor, sprites by AmoryBlaine
add: Adds new brown versions of gloves and boot to custom loadout, also lowers the price of jungle boots to two, sprites by AmoryBlaine
add: Seperates officer cap and RO cap, officers get officer cap, QM gets RO cap, CTs get req cap, sprites once again by AmoryBlaine
add: UPP boots and gloves use the new brown sprite, as it fits their color scheme and looks cool.
fix: Freelancer leader now spawns with a knife in their boots
imageadd: Resprites patrol cap, officer cap, SEA cap, standard black boot, standard black glove, and formal gloves, sprites by AmoryBlaine
/:cl:

2023-09-02 22:06 UTC, morrowwolf requested changes

2023-09-02 22:06 UTC, morrowwolf commented on code/game/machinery/vending/vendor_types/crew/senior_officers.dm
> +		list("Requsitions Cap", 0, /obj/item/clothing/head/cmcap/req, MARINE_CAN_BUY_MASK, VENDOR_ITEM_REGULAR),
Requisitions

2023-09-04 07:41 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2023-09-04 20:43 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2023-09-08 16:41 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2023-09-08 17:25 UTC, kooarbiter commented
I can't believe nobody's discussing the huge balance change of giving one random ert role a bootknife smh smh

2023-09-08 17:44 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2023-09-09 13:57 UTC, nauticall reviewed
As much as everyone likes to talk about movie accuracy, this is one of the instances where I think an exception should be made. The boiler suits, while they look good, don't represent the idea of an "officer" at all, and if the star wasn't there, people would easily confuse SOs for being maint/cargo techs or janitors. The existing dress shirt + slacks combination, while a bit uptight for a ship's uniform, does the job of distinguishing the SO as an officer and someone to actually at least _try_ to take seriously.

I'm not saying to scrap these boiler uniforms entirely, but they should not be used as staff officer uniforms, sorry. People are not gonna look at them and think, "oh, an officer". If they don't want to look like an officer then they can just wear regular fatigues.

2023-09-09 14:04 UTC, nauticall requested changes
![image](https://github.com/cmss13-devs/cmss13/assets/55491249/2797260a-b5ba-415a-9417-4e5621c5728c)
White uniform lacks contrast here and conflicts with existing styles on whites. Not saying to blacken the edges completely, but make the outlines _slightly_ darker.

![image](https://github.com/cmss13-devs/cmss13/assets/55491249/67a0a095-c4cc-46af-a8d1-59504db72106)
We already have dress blues, they just haven't been added to uniform vendors yet. Making yet another 'dress' uniform for marines will just add to confusion and redundancy.

![image](https://github.com/cmss13-devs/cmss13/assets/55491249/03cb2bae-d102-4a1a-b08d-b350a96434ac)
Boots are too dark. Make them match the brown gloves in palette.

![image](https://github.com/cmss13-devs/cmss13/assets/55491249/06e5eef5-969f-4f68-9e80-8c8df7dd813d)
Palette for the gloves here are all over the place. You'd be better off just having it use the same sprite as the latex gloves, honestly, or at least basing the sprite off those. Both latex and formal cloth gloves are white and smooth-textured.

2023-09-11 07:44 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2023-09-11 13:47 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2023-09-12 21:09 UTC, LC4492 commented
As an idea, I think it would be nice if the Chief Engineer also received a more..."tailored" outfift, of which the beret matched with a possible officer jacket, but this is already good as it is

2023-09-24 06:47 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2023-09-24 19:25 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2023-09-26 10:13 UTC, nauticall approved these changes
👌 sprites good now, cheers

2023-09-26 10:15 UTC, morrowwolf commented
TM'ing just in case of any niche sprite issues

2023-09-26 16:45 UTC, merged