Qol reorganize and update all the squads vendors.
cmss13-devs/cmss13 pull request #4324
Opened 2023-09-03 08:54 UTC by Huffie56

# About the pull request
1-more categories
2-making the same organization in all the squad marines vendors.

# Explain why it's good for the game

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
qol: reorganize and update all the squads vendors.
balance: remove item that shouldn't be to sell for consistency.
balance: add items that could be to sell for consistency.
/:cl:

2023-09-03 08:55 UTC, Huffie56 commented
VERY WIP.

2023-09-03 17:05 UTC, BeagleGaming1 commented
Could you list what items are being added and removed instead of it just being "for consistency"?

2023-09-03 17:13 UTC, Huffie56 commented
> 

yes

2023-09-03 19:27 UTC, Huffie56 commented
i am in need of head dev directions concerning some items that are available freely on the squad prep or in medbay but are costing points in vendor.
wish confuse me greatly 

> Could you list what items are being added and removed instead of it just being "for consistency"?

done

2023-09-04 09:37 UTC, Huffie56 commented
i am in need of head dev directions concerning some items that are available freely on the squad prep or in medbay but are costing points in vendor.
wish confuse me greatly

2023-09-08 12:40 UTC, Huffie56 commented
https://forum.cm-ss13.com/t/trying-to-make-sense-and-add-consistency-to-item-price-and-availability/4026

2023-09-09 02:46 UTC, morrowwolf requested changes
Looks fine otherwise

2023-09-09 02:46 UTC, morrowwolf commented on code/game/machinery/vending/vendor_types/squad_prep/squad_leader.dm
> +		list("Powerloader Certification", 45, /obj/item/pamphlet/skill/powerloader, null, VENDOR_ITEM_REGULAR),
Just kill this meme pamphlet

2023-09-09 02:46 UTC, morrowwolf commented on code/game/machinery/vending/vendor_types/squad_prep/squad_medic.dm
> +		list("Powerloader Certification", 45, /obj/item/pamphlet/skill/powerloader, null, VENDOR_ITEM_REGULAR),
Same here

2023-09-09 02:46 UTC, morrowwolf commented on code/game/machinery/vending/vendor_types/squad_prep/squad_rifleman.dm
>  		list("Powerloader Certification", 45, /obj/item/pamphlet/skill/powerloader, null, VENDOR_ITEM_REGULAR),
Same here

2023-09-09 02:46 UTC, morrowwolf commented on code/game/machinery/vending/vendor_types/squad_prep/squad_smartgunner.dm
> +		list("Powerloader Certification", 45, /obj/item/pamphlet/skill/powerloader, null, VENDOR_ITEM_REGULAR),
Same here

2023-09-09 02:46 UTC, morrowwolf commented on code/game/machinery/vending/vendor_types/squad_prep/squad_specialist.dm
>  		list("Powerloader Certification", 45, /obj/item/pamphlet/skill/powerloader, null, VENDOR_ITEM_REGULAR),
Same here

2023-09-09 02:46 UTC, morrowwolf commented on code/game/machinery/vending/vendor_types/squad_prep/squad_tl.dm
>  		list("Powerloader Certification", 45, /obj/item/pamphlet/skill/powerloader, null, VENDOR_ITEM_REGULAR),
Same here

2023-09-09 12:05 UTC, Huffie56 commented on code/game/machinery/vending/vendor_types/squad_prep/squad_leader.dm
> +		list("Powerloader Certification", 45, /obj/item/pamphlet/skill/powerloader, null, VENDOR_ITEM_REGULAR),
removed

2023-09-09 12:05 UTC, Huffie56 commented on code/game/machinery/vending/vendor_types/squad_prep/squad_medic.dm
> +		list("Powerloader Certification", 45, /obj/item/pamphlet/skill/powerloader, null, VENDOR_ITEM_REGULAR),
removed

2023-09-09 12:05 UTC, Huffie56 commented on code/game/machinery/vending/vendor_types/squad_prep/squad_rifleman.dm
>  		list("Powerloader Certification", 45, /obj/item/pamphlet/skill/powerloader, null, VENDOR_ITEM_REGULAR),
removed

2023-09-09 12:05 UTC, Huffie56 commented on code/game/machinery/vending/vendor_types/squad_prep/squad_specialist.dm
>  		list("Powerloader Certification", 45, /obj/item/pamphlet/skill/powerloader, null, VENDOR_ITEM_REGULAR),
removed

2023-09-09 12:05 UTC, Huffie56 commented on code/game/machinery/vending/vendor_types/squad_prep/squad_tl.dm
>  		list("Powerloader Certification", 45, /obj/item/pamphlet/skill/powerloader, null, VENDOR_ITEM_REGULAR),
removed

2023-09-09 12:05 UTC, Huffie56 commented on code/game/machinery/vending/vendor_types/squad_prep/squad_smartgunner.dm
> +		list("Powerloader Certification", 45, /obj/item/pamphlet/skill/powerloader, null, VENDOR_ITEM_REGULAR),
removed

2023-09-21 08:36 UTC, morrowwolf requested changes

2023-09-21 08:36 UTC, morrowwolf commented on code/game/machinery/vending/vendor_types/squad_prep/squad_engineer.dm
>  		list("Powerloader Certification", 45, /obj/item/pamphlet/skill/powerloader, null, VENDOR_ITEM_REGULAR),
powerloader cert here

2023-09-21 08:49 UTC, Huffie56 commented on code/game/machinery/vending/vendor_types/squad_prep/squad_engineer.dm
>  		list("Powerloader Certification", 45, /obj/item/pamphlet/skill/powerloader, null, VENDOR_ITEM_REGULAR),
removed

2023-09-21 09:01 UTC, merged