Adds CBRN ERT
cmss13-devs/cmss13 pull request #4337
Opened 2023-09-05 02:31 UTC by BeagleGaming1

# About the pull request

Adds the CBRN ERT, with a 10/120 chance of responding to distress signals.

# Explain why it's good for the game

It is a USCM-aligned ERT that could be used for events

# Changelog

:cl:
add: Added CBRN ERT with new gear
add: ERT Squads (Marine Raider and CBRN) get assigned to their squad even if spawned as an ERT, but do not automatically unlock it for overwatch
spellcheck: Corrected spelling of "Intercepted Transmission" for ERTs
/:cl:

2023-09-05 02:31 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2023-09-05 02:38 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2023-09-05 17:15 UTC, BeagleGaming1 commented on code/game/objects/items/devices/radio/headset.dm
> +	desc = "A head given to CBRN marines. Channels are as follows: :g - public, :v - marine command, :a - alpha squad, :b - bravo squad, :c - charlie squad, :d - delta squad, :n - engineering, :m - medb
```suggestion
	desc = "A headset given to CBRN marines. Channels are as follows: :g - public, :v - marine command, :a - alpha squad, :b - bravo squad, :c - charlie squad, :d - delta squad, :n - engineering, :m - medbay, :u - requisitions, :j - JTAC, :t - intel"
```

2023-09-08 09:28 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2023-09-15 01:52 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2023-09-26 09:09 UTC, morrowwolf requested changes
~~This should really be admin spawn only. These guys responding with anti-zed and CBRN gear is just kinda weird.~~

Alright Beagle has convinced me. (for now)

Otherwise, remind me to look at this again Thursday.

2023-09-26 13:37 UTC, BeagleGaming1 commented
Need to do loadout changes after the storage change or

2023-09-26 16:49 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2023-10-02 17:04 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2023-10-03 05:57 UTC, TopHatPenguin commented
@morrowwolf I am unsure on if this is what Beagle convinced you with but nonetheless I'll info dump.

An IC lore reason for them to respond in full CBRN (biohazard protection) gear would be that New Earth is in the HD85512 system which is in the neroid sector. The New Earth colony has an airborne flesh eating bacteria on the planet and has been under a blockade to keep it contained since 2157 after an ICC sanctioned system sterilization (millions are condemned) to keep it under control.

Could be interesting to have a biohazard variation that spawns the ERT with an ICC agent as an embed to assess the situation at hand.



![Neroid Sector Important Places](https://github.com/cmss13-devs/cmss13/assets/29822829/6d30125e-f20f-466b-84f0-79f4ba29211a)

2023-10-07 16:25 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2023-10-07 22:11 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2023-10-08 00:25 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2023-10-08 05:01 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2023-10-08 16:09 UTC, Zonespace27 requested changes

2023-10-08 16:09 UTC, Zonespace27 commented on code/modules/clothing/under/marine_uniform.dm
> +	var/obj/item/clothing/head/linked_hood
Del on destroy

2023-10-08 16:09 UTC, Zonespace27 commented on code/modules/gear_presets/cbrn.dm
> +	var/headset_type = /obj/item/device/radio/headset/distress/cbrn
Code doc

2023-10-08 16:09 UTC, Zonespace27 commented on code/game/objects/prop.dm
> +/obj/item/prop/geiger_counter
Feels like mhelp "what does the geiger counter do" bait, maybe have it say something about the meter being broken when you turn it on?

2023-10-09 16:29 UTC, Zonespace27 approved these changes

2023-10-10 05:30 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2023-10-10 20:15 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2023-10-15 19:38 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2023-10-16 23:49 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2023-10-19 07:12 UTC, harryob requested changes

2023-10-19 07:12 UTC, harryob commented on code/datums/emergency_calls/cbrn.dm
> +
```suggestion
```

2023-10-19 07:12 UTC, harryob commented on code/game/objects/prop.dm
> +		update_icon()
```suggestion
	if(!HAS_TRAIT(attacking_item, TRAIT_TOOL_SCREWDRIVER) && !HAS_TRAIT(attacking_item, TRAIT_TOOL_CROWBAR))
		return

	if(!battery)
		to_chat(user, SPAN_NOTICE("There is no battery for you to remove."))
		return
	to_chat(user, SPAN_NOTICE("You jam [battery] out of [src] with [attacking_item], prying it out irreversibly."))
	user.put_in_hands(battery)
	battery = null
	update_icon()
```

2023-10-19 07:12 UTC, harryob commented on code/modules/clothing/under/marine_uniform.dm
> +	var/obj/item/clothing/under/marine/cbrn/armor = user //I have no idea why this works
that's because the first argument to New of item_actions isn't user, it's target

2023-10-19 07:12 UTC, harryob commented on code/modules/clothing/under/marine_uniform.dm
> +/datum/action/item_action/specialist/toggle_cbrn_hood/New(mob/living/user, obj/item/holder)
first arg should be target (per below)

2023-10-26 21:32 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2023-10-26 21:59 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2023-10-28 11:46 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2023-10-31 22:47 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2023-11-03 14:50 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2023-11-03 17:03 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2023-11-08 00:01 UTC, merged