Uncommented "Observe" verb
cmss13-devs/cmss13 pull request #4345
Opened 2023-09-06 00:46 UTC by BeagleGaming1

# About the pull request

Apparently, there was an exploit with it, but I have been unable to reproduce it, so it is probably fine
(This will most likely need a test merge just in case)

# Explain why it's good for the game

It's qol

# Changelog

:cl:
add: Uncommented the "Observe" verb for ghosts, allowing ghosts to see from a humans hud
/:cl:

2023-09-06 14:53 UTC, harryob requested changes
re-implement autoObserve on the orbit meni

2023-09-06 17:29 UTC, BeagleGaming1 commented
> @BeagleGaming1 please read #615 including the comments

Yes I know the exploit, I am unable to reproduce it

2023-09-08 14:48 UTC, morrowwolf commented
Overlays on items do not seem to be updating, neither does the toggle clothing button in the bottom left 
Anything in hand when you first observe them seems to not render correctly

2023-09-19 09:29 UTC, morrowwolf commented
Alright this has issues but honestly all of HUD code would likely need to be changed. Just going to call this a success with some slight problems for the time being. Seems most exploits have been fixed but we'll keep an eye out.

2023-09-19 09:37 UTC, merged