Surgery in interiors tweak
cmss13-devs/cmss13 pull request #439
Opened 2022-06-06 10:36 UTC by JeserTheFox

## About The Pull Request

Disallowing surgery in interiors outside of interior medical tiles. First PR of the too.

## Why It's Good For The Game

Disallows surgery in vehicles by default.

## Changelog

:cl: Jeser
balance: Surgery in vehicle interiors is now only allowed if the patient is located on interior medical tile.
/:cl:

2022-06-06 10:48 UTC, Git-Nivrak commented
Good change though I still think APC should be removed instead of bandage fixed for the 90000 time

2022-06-07 08:20 UTC, tempelers commented
Good PR. This'll stop the five docs at the FOB plus the synth from all filling up the APC to do surgery.

2022-06-14 18:34 UTC, Geevies requested changes

2022-06-14 18:34 UTC, Geevies commented on code/modules/surgery/surgery_initiator.dm
> +	if(user.z == GLOB.interior_manager.interior_z && !istype(target.loc, /turf/open/shuttle/vehicle/med))
a better solution might be a var on turfs that goes like "supports_surgery" true or false. check if the loc is a turf, then check if it supports surgery

2022-06-17 19:09 UTC, Geevies approved these changes

2022-06-17 22:01 UTC, merged