Xeno IFF Tags
cmss13-devs/cmss13 pull request #44
Opened 2022-04-16 09:01 UTC by Geevies

## About The Pull Request

Add IFF tags that can be forced into a xeno's carapace to grant them IFF. Xeno handler xenos automatically spawn with these set to Marine/WY IFF groups. A multitool can be used to reprogram the IFF tag. All of these use the IFF group of the ID in your ID slot.

## Why It's Good For The Game

Adds new and interesting ways to not shoot your friends.

## Changelog

:cl:
add: Added xeno IFF tags that prevent smart weapons from shooting the implanted xeno. Use a multitool to reprogram these, it uses the IFF group on your ID.
/:cl:

2022-04-18 20:48 UTC, Watermelon914 requested changes

2022-04-18 20:48 UTC, Watermelon914 commented on code/modules/mob/living/carbon/xenomorph/damage_procs.dm
> +		if(HAS_TRAIT(I, TRAIT_TOOL_MULTITOOL) && ishuman(user))
Early return here and use a more detailed variable name for I

2022-04-18 20:48 UTC, Watermelon914 commented on code/modules/mob/living/carbon/xenomorph/items/iff_tag.dm
> +			return
explicitly return false here

2022-04-24 14:09 UTC, stanalbatross requested changes

2022-04-24 14:09 UTC, stanalbatross commented on code/datums/supply_packs/operations.dm
> +	name = "xenomorph IFF tag case (x7 tags)"
```suggestion
	name = "Xenomorph IFF Tag Case (x7 tags)"
```

2022-04-26 18:53 UTC, stanalbatross requested changes

2022-04-26 18:53 UTC, stanalbatross commented on code/modules/mob/living/carbon/xenomorph/items/iff_tag.dm
> +	return ..()
should not be able to put more than one tag into a xeno as it causes large issues + should also not be able to put them in dead xenos

2022-04-27 07:10 UTC, stanalbatross approved these changes

2022-04-27 07:10 UTC, merged