Revives CMB Black Market Investigation
cmss13-devs/cmss13 pull request #4405
Opened 2023-09-12 20:09 UTC by realforest2001

# Revival of #3223 by BeagleGaming1
# About the pull request

Ordering black market goods can either lower or increase a number. At 100, the CMB gets called to investigate and disable the black market.

# Explain why it's good for the game

People can purchase unlimited goods such as weapons or CLF crates. This causes req to have to at least pay attention to what they are buying, and to buy stuff other than clothing or weapons from other factions.

# Changelog

:cl: BeagleGaming1
add: Adds a CMB ERT to investigate the Black Market
add: Adds a [cmb] logo for papers
add: (forest2001) Adds a quiet_launch var for distress beacons, to differentiate between ERTs who should announce their response reception, but not the beacon going out in the first place.
/:cl:

2023-09-13 01:51 UTC, sleepynecrons requested changes
scanner is missing the scanner_on animation the original PR had 
![scanr](https://github.com/cmss13-devs/cmss13/assets/106241650/bcadd2cd-0df3-42af-b66f-9a7a8e5f5b4c)

2023-09-13 22:23 UTC, sleepynecrons approved these changes
sprites ✅

2023-09-14 07:59 UTC, harryob requested changes

2023-09-14 07:59 UTC, harryob commented on code/datums/emergency_calls/inspection.dm
> +	will_spawn_cmb_observer = FALSE
why are these being set in new they're constants

2023-09-14 07:59 UTC, harryob commented on code/modules/gear_presets/cmb.dm
> +	H.equip_to_slot_or_del(new /obj/item/device/cmb_black_market_tradeband, WEAR_IN_BACK) //Tradeband to disable black market
```suggestion
/datum/equipment_preset/cmb/liaison/black_market/load_gear(mob/living/carbon/human/new_human)
	. = ..()
	new_human.equip_to_slot_or_del(new /obj/item/storage/belt/utility/full, WEAR_WAIST) //Tool belt to open ASRS
	new_human.equip_to_slot_or_del(new /obj/item/device/cmb_black_market_tradeband, WEAR_IN_BACK) //Tradeband to disable black market
```

2023-09-14 07:59 UTC, harryob commented on maps/map_files/Ice_Colony_v3/Shivas_Snowball.dmm
undocumented

2023-09-14 07:59 UTC, harryob commented on code/game/objects/effects/spawners/random.dm
undocumented

2023-09-14 07:59 UTC, harryob commented on code/datums/supply_packs/black_market.dm
> -		/obj/item/weapon/banhammer,
undocumented

2023-09-14 07:59 UTC, harryob commented on code/game/objects/items/circuitboards/computer.dm
> +	if(istype(tool, /obj/item/device/cmb_black_market_tradeband))
trait check

2023-09-14 07:59 UTC, harryob commented on code/game/supplyshuttle.dm
> +/datum/controller/supply/proc/black_market_CMB_investigation()
all paths should be snake case including initialisms

2023-09-14 15:28 UTC, realforest2001 commented on maps/map_files/Ice_Colony_v3/Shivas_Snowball.dmm
*pain
I put it in the changelog and didn't save it

2023-09-14 16:55 UTC, harryob approved these changes

2023-09-14 17:03 UTC, merged

2023-09-14 18:48 UTC, kooarbiter commented
time to call in enough black market weapons that a CMB team is codewise forced to arrive, conveniently before the aliens hijack so they have to help out, big brained moment for free ert