Cloaked mobs don't give off visible messages
cmss13-devs/cmss13 pull request #4410
Opened 2023-09-13 23:50 UTC by Zonespace27

# About the pull request
Pretty much the title. Visible messages (visible_message proc) don't give off messages to others if the origin is cloaked.

I'm a bit leery of doing this on `visible_message` so this is gonna need testing first.

# Explain why it's good for the game
Being able to see things like "Unknown peers through the laser designator" while they're invisible is a pretty large tell despite you not having seen them.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Works

</details>

# Changelog

:cl:
balance: Cloaked mobs no longer give off visible messages
/:cl:

2023-09-14 15:25 UTC, realforest2001 requested changes

2023-09-14 15:25 UTC, realforest2001 commented on code/modules/mob/mob.dm
>  		M.show_message(message, SHOW_MESSAGE_VISIBLE, blind_message, SHOW_MESSAGE_AUDIBLE, message_flags)
```suggestion
	if(HAS_TRAIT(src, TRAIT_CLOAKED))
		return FALSE
	var/view_dist = 7
	if(max_distance)
		view_dist = max_distance
	for(var/mob/M as anything in viewers(view_dist, src))
		M.show_message(message, SHOW_MESSAGE_VISIBLE, blind_message, SHOW_MESSAGE_AUDIBLE, message_flags)
	return TRUE
```

2023-09-14 15:25 UTC, realforest2001 commented
Can you add the cloak trait to the changelog/title as it's the main part of this PR

2023-09-14 16:02 UTC, Zonespace27 commented
> Can you add the cloak trait to the changelog/title as it's the main part of this PR

Added to title; changelog isn't needed due to it not being player-facing

2023-09-14 17:52 UTC, realforest2001 approved these changes
lgtm

2023-09-15 07:30 UTC, harryob requested changes

2023-09-15 07:30 UTC, harryob commented on code/modules/mob/living/carbon/xenomorph/castes/Lurker.dm
> +	ADD_TRAIT(bound_xeno, TRAIT_CLOAKED, "lurker_cloak")
trait source defines

2023-09-15 07:30 UTC, harryob commented on code/modules/mob/living/carbon/xenomorph/castes/Lurker.dm
> +	REMOVE_TRAIT(bound_xeno, TRAIT_CLOAKED, "lurker_cloak")
trait source defines

2023-09-15 07:30 UTC, harryob commented on code/modules/cm_preds/yaut_bracers.dm
> +		ADD_TRAIT(M, TRAIT_CLOAKED, "pred_cloak")
trait source defines

2023-09-15 07:30 UTC, harryob commented on code/modules/cm_preds/yaut_bracers.dm
> +	REMOVE_TRAIT(user, TRAIT_CLOAKED, "pred_cloak")
trait source defines

2023-09-24 08:51 UTC, harryob approved these changes

2023-09-24 08:59 UTC, merged