Phone Do not Disturb
cmss13-devs/cmss13 pull request #4427
Opened 2023-09-17 20:48 UTC by realforest2001

# About the pull request
Allows phones to be put on Do Not Disturb, preventing them from being called. This is not possible to toggle on certain phones such as Overwatch.

# Explain why it's good for the game
Sometimes phones get spammed for trolls, other times the relevant people (like CL) are not in their office. This makes it easy to stop wasted calls on empty rooms or busy people.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
add: Added a Do Not Disturb feature for MOST phones. (Overwatch and a couple others excluded).
/:cl:

2023-09-22 02:53 UTC, BeagleGaming1 requested changes

2023-09-22 02:53 UTC, BeagleGaming1 commented on code/modules/cm_phone/phone.dm
> +	var/do_not_disturb = PHONE_DND_OFF
code doc

2023-09-22 02:57 UTC, BeagleGaming1 approved these changes
code good

2023-09-23 07:44 UTC, morrowwolf requested changes

2023-09-23 07:44 UTC, morrowwolf commented on maps/map_files/USS_Almayer/USS_Almayer.dmm
> +	do_not_disturb = -1;
Make a subtype with it being set to -1

2023-09-23 23:33 UTC, Cthulhu80 commented
Currently, when the button is pressed it doesn't change its color or update the button text or have any visible state change in tgui, it just gives you a little message in the chatbox. It feels like it should though...

2023-09-30 19:37 UTC, realforest2001 commented
> Currently, when the button is pressed it doesn't change its color or update the button text or have any visible state change in tgui, It feels like it should though...

The hover-text and the icon on the button do update when the state is changed

2023-09-30 23:21 UTC, Cthulhu80 commented
I didn't notice it in-game when I first commented. I see it in the code.

2023-10-07 15:59 UTC, Zonespace27 approved these changes
I dunno why this has sat so long

2023-10-07 16:07 UTC, merged