Working joe respawns
cmss13-devs/cmss13 pull request #4429
Opened 2023-09-17 23:50 UTC by Ben10083

# About the pull request

Working Joes can respawn after 10 minutes

# Explain why it's good for the game

The restriction on Working Joes being unable to play as Working Joe again (for example if they cryo) is unnecessary. This change allows Joes to spawn after 10 minutes since death (still locked from respawns as before during hijack)

# Changelog

:cl:
add: Working Joes can now respawn after 10 minutes
/:cl:

2023-09-18 00:15 UTC, Ben10083 commented
Tried to find a way so if someone observes in first 10 minutes, they can spawn as Working Joe, no easy way and its pretty niche, so should be fine.

2023-09-18 01:37 UTC, realforest2001 requested changes

2023-09-18 01:37 UTC, realforest2001 commented on code/game/gamemodes/cm_initialize.dm
> +	if(deathtime < JOE_JOIN_DEAD_TIME && !check_client_rights(joe_candidate.client, R_ADMIN, FALSE) && !MODE_HAS_TOGGLEABLE_FLAG(MODE_BYPASS_JOE))
```suggestion
	if(deathtime < JOE_JOIN_DEAD_TIME && !MODE_HAS_TOGGLEABLE_FLAG(MODE_BYPASS_JOE))
```
No freebies just for staff.

2023-09-26 09:21 UTC, morrowwolf commented
Not a fan. Apologies.

2023-09-26 09:21 UTC, closed without merging