Project ARES: Datacore
cmss13-devs/cmss13 pull request #4437
Opened 2023-09-18 03:11 UTC by realforest2001

Moves most information from ARES Interface and APOLLO Interface to the ARES Datacore. Also reorganises the files so the two interfaces are in separate files with all their UI data.

# About the pull request
Centralises most of the information used by the ARES Interface and APOLLO Maintenance Console(s) into a datacore.
Also reorganises the files so the two consoles are in their own individual files with all their UI data rather than having them separate from the UI data which was making it difficult to navigate.

Also adds checks to everywhere I could find missing them for logging to the datacore.

# Explain why it's good for the game
This will help massively for future compatability and updates.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
code: Moved most data storage from ARES Interface and APOLLO consoles to a new ARES datacore datum.
code: Moved the two consoles to separate files for easier navigation, and moved their respective UI data to the files.
add: Added ares_can_log checks to all the places I could find missing them.
/:cl:

2023-09-26 09:26 UTC, morrowwolf requested changes

2023-09-26 09:26 UTC, morrowwolf commented on code/modules/cm_marines/overwatch.dm
> +	if(ares_can_log())
This should really be like inside the proc you are calling if it's required before every time you call the proc

2023-10-07 16:01 UTC, Zonespace27 requested changes

2023-10-07 16:01 UTC, Zonespace27 commented on code/game/machinery/computer/almayer_control.dm
> +			if(ares_can_log())
for all of these, why can't this proc be inside the `log_ares_XXXX` procs?

2023-10-10 00:28 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2023-10-11 00:31 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2023-10-17 14:24 UTC, merged