Adds round end to status tab
cmss13-devs/cmss13 pull request #4460
Opened 2023-09-21 02:47 UTC by BeagleGaming1

# About the pull request

Lets ghosts and new players (lobby) see time to server restart

# Explain why it's good for the game

Lets you see if the automatic round-end timer ran out, and if the server is delayed

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
add: Ghosts and players in lobby can see the time to the server restarting in the status tab
/:cl:

2023-09-22 01:25 UTC, realforest2001 requested changes

2023-09-22 01:25 UTC, realforest2001 commented on code/modules/mob/new_player/new_player.dm
> +			. += "Time To Restart: SOON [SSticker.delay_end ? "(DELAYED)" : "(RESTART NEEDED)"]"
```suggestion
			. += "Time To Restart: SOON [SSticker.delay_end ? "(DELAYED)" : "(MANUAL RESTART NEEDED)"]"
```
Assuming I interpreted this correctly, worth clarifying it needs to be done manually.

2023-09-22 01:25 UTC, realforest2001 commented on code/modules/mob/dead/observer/observer.dm
> +		. += "Time To Restart: [(SSticker.roundend_restart_delay + (SSticker.mode.round_end_time - world.time)) / 10 ]s [SSticker.delay_end ? "(DELAYED)" : ""]"
```suggestion
	if(SSticker.current_state == GAME_STATE_FINISHED)
		var/round_end_timer = "Time To Restart: [(SSticker.roundend_restart_delay + (SSticker.mode.round_end_time - world.time)) / 10 ]s [SSticker.delay_end ? "(DELAYED)" : ""]"
		if(SSticker.mode.round_end_time == 0)
			round_end_timer = "Time To Restart: Ongoing Vote [SSticker.delay_end ? "(DELAYED)" : ""]"
		if(SSticker.mode.round_end_time < 0)
			round_end_timer = "Time To Restart: SOON [SSticker.delay_end ? "(DELAYED)" : "(RESTART NEEDED)"]"
		. += round_end_timer
```
Optional suggestion.

2023-09-22 02:07 UTC, realforest2001 approved these changes

2023-09-23 03:17 UTC, BeagleGaming1 commented
Bruh its like 10s off on live

2023-09-26 10:36 UTC, morrowwolf requested changes
Allegedly weirdness with the timer during TM

2023-10-02 19:16 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2023-10-02 21:35 UTC, closed without merging