UPP Survivors Use Player Names + Radio Change
cmss13-devs/cmss13 pull request #4461
Opened 2023-09-21 05:59 UTC by Steelpoint

# About the pull request

UPP survivors now default to using the players preferred name instead of a random UPP name. 

The UPP radio name is now changed to "173/RECON" from "UPP 173rd Recon". 

# Explain why it's good for the game

The radio change is to make the radio text log less cumbersome to observe. 

The name change was a requested change from the maintainers, as players should be using their preferred name instead of being forced to use a random one.

(On that note, if anyone has the coding skills, please put up a PR to let players select their own name for non-USCM spawns, guaranteed to be approved)

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
balance: UPP survivor radios now have a shorter title.
balance: UPP survivors now default to using your preferred name instead of a random UPP name. 
/:cl:

2023-09-22 02:36 UTC, realforest2001 commented
Neither of these are balance related.
Also the title isn't specific to their own radios, it's just their role identifier. Worth tweaking the CL to reflect this.

2023-09-22 02:46 UTC, Steelpoint commented
Done.

2023-09-23 03:34 UTC, Steelpoint commented
Missed a thing, fixed.

2023-09-26 09:47 UTC, morrowwolf requested changes
Missing synth comm title in synths.dm line 469

2023-09-26 12:12 UTC, Steelpoint commented
Fixed

2023-09-26 18:12 UTC, merged