Less Overpowered Commando ERTs (Marsoc, WY Whiteout, UPP Commandos)
cmss13-devs/cmss13 pull request #4466
Opened 2023-09-21 15:12 UTC by Steelpoint

# About the pull request

This PR adds three new alternative Commando distress calls for admin/staff only usage. These are variants of the Marsoc, WY Whiteout and UPP Commando that use less overpowered gear. 

The non-OP versions are noted in the admin distress call panel as "(Not Overpowered)". The regular, overpowered, ERTs are denoted with the affix of "(!WHITEOUT!)".

Marsoc: Have lost HEAP/Special Explosives/Unique Medical Items
WY Whiteout: Have lost HEAP/Special OP Flamer/Extra OP Smartgun, they are still combat Synthetics
UPP: Have lost their cloaking abilities, they still retain a cloak for the aesthetic but it is non-functional.

# Explain why it's good for the game

Commando ERTs are virtually never used in game outside of zombies or for clean-up after an event due to how oppressively overpowered they are. 

This addition will allow admins/staff to make usage of these unique ERTs more commonly for events without having to worry about them annihilating the entire server. While each ERT is still quite powerful, they are not as destructive. 

I am 100% open to further changes as needed. 

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
add: Less powerful variants of the Commando ERTs (Marsoc, WY Whiteout, UPP Commandos) have been added for admin use.
admin: The powerful versions of commando ERTs are denoted with (!WHITEOUT!) whereas the less powerful are denoted with (Not Overpowered) in the distress call menu.
/:cl:

2023-09-21 15:23 UTC, Steelpoint commented
> > The regular, overpowered, ERTs are denoted with the affix of "(!WHITEOUT!)".
> 
> This seems like it'll be confusing, "Whiteout" is the WY thing, it wouldn't make sense for Marsoc / UPP to have this affix, why not just say it's a "Deathsquad"?

That does sound better than what I thought, done.

2023-09-21 15:35 UTC, BeagleGaming1 requested changes

2023-09-21 15:35 UTC, BeagleGaming1 commented on code/datums/emergency_calls/deathsquad.dm
> +/datum/emergency_call/death_lowthreat
Why not make the lowthreat variants a subtype of the regular one, and just /create_member with weaker gear?

2023-09-21 15:35 UTC, BeagleGaming1 commented on code/datums/emergency_calls/deathsquad.dm
> +/datum/emergency_call/marsoc_lowthreat/create_member(datum/mind/M)
Single letter var

2023-09-21 15:35 UTC, BeagleGaming1 commented on code/datums/emergency_calls/deathsquad.dm
> +	var/mob/living/carbon/human/H = new(spawn_loc)
Single letter var

2023-09-21 15:35 UTC, BeagleGaming1 commented on code/datums/emergency_calls/upp_commando.dm
> +/datum/emergency_call/upp_commando/print_backstory(mob/living/carbon/human/M)
Single letter var

2023-09-21 15:35 UTC, BeagleGaming1 commented on code/datums/emergency_calls/upp_commando.dm
> +	var/mob/living/carbon/human/H = new(spawn_loc)
Single letter var

2023-09-21 15:35 UTC, BeagleGaming1 commented on code/modules/gear_presets/whiteout.dm
> +	var/obj/item/clothing/under/marine/veteran/pmc/commando/M = new()
Single letter var

2023-09-21 15:35 UTC, BeagleGaming1 commented on code/modules/gear_presets/whiteout.dm
> +	var/obj/item/clothing/under/marine/veteran/pmc/commando/M = new()
Single letter var

2023-09-21 15:35 UTC, BeagleGaming1 commented on code/modules/gear_presets/whiteout.dm
> +	var/obj/item/clothing/under/marine/veteran/pmc/commando/M = new()
Single letter var

2023-09-21 16:18 UTC, Steelpoint commented
Tidied up the code. 

References to the overpowered versions of the commandos are now all properly denoted with !DEATHSQUD! whereas the less powerful versions have no unique identifier. This applies to both the distress call and the preset equipment.

2023-09-30 06:02 UTC, morrowwolf requested changes

2023-09-30 06:02 UTC, morrowwolf commented on code/datums/emergency_calls/upp_commando.dm
> +/datum/emergency_call/upp_commando/print_backstory(mob/living/carbon/human/mind)
Accidentally doubled looks like

2023-09-30 06:02 UTC, morrowwolf commented on code/datums/emergency_calls/upp_commando.dm
> +/datum/emergency_call/upp_commando/lowthreat
All of the typepaths that have "lowthreat" need to be snake_case'd so "low_threat"

2023-09-30 06:02 UTC, morrowwolf commented on code/datums/emergency_calls/upp_commando.dm
> +	mob_max = 6
Any of the vars that are the same here as the parent need to be removed. So like /datum/emergency_call/upp_commando already sets the mob_max to 6 and this inherits that so it does not need to be set here. Do a check for these dupes across the changes please.

2023-09-30 08:50 UTC, Steelpoint commented
I believe all requested changes have been made.

2023-11-13 09:10 UTC, harryob approved these changes

2023-11-13 12:37 UTC, merged