IOs Default To Using Intel Channel
cmss13-devs/cmss13 pull request #4474
Opened 2023-09-22 07:59 UTC by Steelpoint

# About the pull request

Intel Officers will now default to speaking into the intel squad channel instead of the Almayer general channel. 

# Explain why it's good for the game

Its best for the Intel squad to speak into the Intel comms. It may also slowly shift the IO culture towards cooperation and communication instead of solo ops. 

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
add: Intel Officers will now default to using the Intel radio channel when communicating. 
/:cl:

2023-09-22 23:36 UTC, morrowwolf commented
Reference #4457 as it will have to be changed here as well once it is merged.

2023-09-23 03:23 UTC, Steelpoint commented
Changes made

2023-09-23 06:38 UTC, morrowwolf requested changes

2023-09-23 06:38 UTC, morrowwolf commented on code/game/objects/items/devices/radio/encryptionkey.dm
> +	channels = list(RADIO_CHANNEL_COMMAND = TRUE, RADIO_CHANNEL_ENGI = TRUE, RADIO_CHANNEL_JTAC = TRUE, RADIO_CHANNEL_MEDSCI = TRUE, SQUAD_MARINE_1 = FALSE, SQUAD_MARINE_2 = FALSE, SQUAD_MARINE_3 = FALS
Remove intel from here and almayer channel should be the first in the list

2023-09-23 06:49 UTC, Steelpoint commented
Requested changes made

2023-09-23 07:51 UTC, merged