SLIDE YOUR ID LIUTENANT
cmss13-devs/cmss13 pull request #4477
Opened 2023-09-23 06:47 UTC by Diegoflores31

# About the pull request

Fixes the "emergency response team" button in the keycard auth device and adds new unique features to it.

the keycard authentication will now show an option to send a distress signal similar to the almayer control console that will allow to call the FIRST distress signal on the almayer winout the need for admin approval . ( only works on red alert)

Mention if you have tested your changes. If you changed a map, make sure you used the mapmerge tool.
If this is an Issue Correction, you can type "Fixes Issue #169420" to link the PR to the corresponding Issue number #169420.

Remember: something that is self-evident to you might not be to others. Explain your rationale fully, even if you feel it goes without saying. -->

# Explain why it's good for the game

Gives more options to lowpop command and provides a unique reward for using the authenticator in CIC instead of callling ERT remotely from lifeboats.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
add: Adds a new way to send a Distress signal with the Keycard authenticator.
fix: Removes non functional "Call ERT" button in Keycard authenticator.
/:cl:

2023-09-23 13:11 UTC, Cthulhu80 commented
If that's the only time is_ert_blocked() is even used you might just want to shove that logic into call_ert() and simply return.

2023-09-24 08:01 UTC, morrowwolf requested changes
Auto ERTs isn't gonna fly.

It still needs admin approval.

2023-09-24 22:45 UTC, Diegoflores31 commented
> Auto ERTs isn't gonna fly.
> 
> It still needs admin approval.

but it only works for the first ERT . cannot be used more than once

2023-09-28 08:53 UTC, morrowwolf reviewed
If you keep it to post hijack and it works the same way for every way to call an ERT it can be a free one but it should give an opportunity for staff to cancel it and extra credit for a button somewhere to pre-toggle it off.

2023-09-28 12:42 UTC, Diegoflores31 commented
Ok

2023-10-02 02:53 UTC, Diegoflores31 commented
> If you keep it to post hijack and it works the same way for every way to call an ERT it can be a free one but it should give an opportunity for staff to cancel it and extra credit for a button somewhere to pre-toggle it off.

Changes applied:
-staff will have 15 seconds to cancel the ERT request . if it goes unanswered for more than that it will automatically approve
-If distress i called before hijack it will just call a standart ERT request,
-minor change applied ( you cant swipe for red alert if the ship is already on red alert)

2023-10-07 16:03 UTC, Zonespace27 requested changes
Follow cthulhu's reviews please

2023-10-07 16:03 UTC, Zonespace27 commented on code/datums/emergency_calls/emergency_call.dm
> +/datum/game_mode/proc/authorized_request_ert(user) // calls the first ERT winout the need of admin approval.
code doc

2023-10-07 16:03 UTC, Zonespace27 commented on code/datums/emergency_calls/emergency_call.dm
> +/datum/game_mode/proc/process_ert_call(user)
code doc

2023-10-15 21:31 UTC, Diegoflores31 commented on code/datums/emergency_calls/emergency_call.dm
> +/datum/game_mode/proc/authorized_request_ert(user) // calls the first ERT winout the need of admin approval.
what code doc ?

2023-10-20 04:53 UTC, realforest2001 commented on code/datums/emergency_calls/emergency_call.dm
> +/datum/game_mode/proc/authorized_request_ert(user) // calls the first ERT winout the need of admin approval.
/// above proc instead of // next to it

2023-10-25 15:56 UTC, realforest2001 commented on code/modules/security_levels/keycard_authentication.dm
> +
```suggestion

if(ert_dispatched)
		to_chat(usr, SPAN_WARNING("A distress beacon has already launched successfully!"))
		return
		
```

2023-11-05 20:49 UTC, Diegoflores31 commented
github web moment 💀

2023-11-10 10:51 UTC, fira requested changes
looks good codewise

2023-11-10 10:51 UTC, fira commented on code/modules/security_levels/keycard_authentication.dm
> -		if(!CONFIG_GET(flag/ert_admin_call_only))
remove the config flag in game_options.dm - it's now unused

2023-11-22 17:38 UTC, fira approved these changes

2023-11-26 21:43 UTC, harryob approved these changes

2023-12-01 19:25 UTC, fira commented
pls fix so we can merge it :(

2023-12-04 00:18 UTC, fira commented
PR been on TM for a long time but players are complaining about ERT calls not going through, but i'm not sure if it's not just actually becuase most people don't know to look in the Keycard auth device or there is a real bug...

I'd like to request the PR to be double checked after all the new merges before it can be put on TM again and hopefully validated for good and merged

2023-12-12 12:58 UTC, fira commented
Testing take 2 to confirm this effectively works as intended

2023-12-19 19:30 UTC, Diegoflores31 commented
There is currently a bug that some times your swipes wont register . I am almost 100% its because of table core . I will probably add some additional features today to make it more intuitive

2023-12-19 22:42 UTC, Drulikar requested changes
I think the issue with this is mostly just confusion/feedback to users.

Consider adding a sound/balloon_alert whenever the keycard_auth activates/times out (I believe that occurs here: https://github.com/cmss13-devs/cmss13/blob/master/code/modules/security_levels/keycard_authentication.dm#L116-L132

Also consider adding a message if a different user tries to authorize the same keycard_auth - or allow the same machine to both initiate and confirm a request if the triggerer/confirmer is a different user.

2024-01-08 01:04 UTC, closed without merging