Minor Item Additions To Synth Vendor
cmss13-devs/cmss13 pull request #4515
Opened 2023-09-26 12:20 UTC by Steelpoint

# About the pull request

Adds several items to synth vendors. Drip vendor can vend a MP uniform and a sechud. Equip vendor can vend a empty first aid kit and fuel cannister. 

# Explain why it's good for the game

Brings equip up to speed with CTs, adds more cosmetic options. 

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
add: Synthetic equipment vendor now can vend fuel cannisters and empty first aid kits.
add: Synthetic cosmetic vendor now can vend a MP uniform and security hud glasses. 
/:cl:

2023-09-26 13:40 UTC, morrowwolf requested changes

2023-09-26 13:40 UTC, morrowwolf commented on code/game/machinery/vending/vendor_types/crew/synthetic.dm
> +		list("Empty Adv Firstaid Kit", 1, /obj/item/storage/firstaid/adv/empty, null, VENDOR_ITEM_REGULAR),
I don't really like that we've started handing these out empty. Let's take this out.

2023-09-27 08:39 UTC, Steelpoint commented
Update, new items added

- All colour variants of the Synthetic armour can be vended in the equipment vendor.
- All colour variants of the standard Marine helmet can be bended in the cosmetic vendor
- The welder chest rig can be vended in the cosmetic vendor
- Did some tidy up of the categories of the cosmetic vendor

2023-09-27 18:31 UTC, morrowwolf requested changes
Otherwise looks fine oh they changed the little buttons on this prompt they're fatter neato

2023-09-27 18:31 UTC, morrowwolf commented on code/game/machinery/vending/vendor_types/crew/synthetic.dm
> +	list("HAT", 0, null, null, null),
Pedantic but "HEADWARE" is likely better

2023-09-28 03:50 UTC, Steelpoint commented
requested changes made

2023-09-28 07:07 UTC, morrowwolf commented on code/game/machinery/vending/vendor_types/crew/synthetic.dm
> +	list("HAT", 0, null, null, null),
TFW

2023-09-28 07:56 UTC, merged