makes LZ detector work while landed
cmss13-devs/cmss13 pull request #4516
Opened 2023-09-26 12:38 UTC by cuberound

# About the pull request

This PR makes it so that LZ detector works all the time not only when in air.

# Explain why it's good for the game

The fact that LZ detector worked only when in air made it near useless, when you are already headed for the LZ what good is it to see it overrun and how is seeing xeno in FOB after you leave it any good. This turns LZ detector into a tool for transport pilot to better evaluate the situation in FOB before taking off from it or heading to it.

# Changelog

:cl:

balance: LZ detector now works even when the DS is stationary

/:cl:

2023-09-28 17:18 UTC, morrowwolf requested changes
Needs to turn off the linked network when the LZ detector is taken off the ship

2023-09-29 17:06 UTC, cuberound commented
I am a fucking bozo, did not test melting it while not installed and was trying to acces properties of fucking NULL xD

2023-10-02 04:09 UTC, morrowwolf requested changes
update_equipment() is called more than just taking it on and off so when you're picking it up and such it will runtime as there's no linked_cam_console at line 529

2023-10-07 14:52 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2023-10-12 19:03 UTC, closed without merging