changed flyby tgui
cmss13-devs/cmss13 pull request #4600
Opened 2023-10-08 10:40 UTC by mullenpaul

# About the pull request

Slight change to the TGUI for dropship flight controls. I've had feedback that it is a bit unintuitive. This change should resolve novice POs accidentally launching flyby in a panic.

# Explain why it's good for the game
Better UIs make everyone happier.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

![image](https://github.com/cmss13-devs/cmss13/assets/101871009/87c93141-1ba8-4cf0-b8d0-3bf54b97844e)

</details>

# Changelog

:cl:
ui: tweaked flyby controls to make them in line with other destinations
/:cl:

2023-10-11 21:45 UTC, harryob requested changes

2023-10-11 21:45 UTC, harryob commented on code/modules/shuttle/computers/dropship_computer.dm
> +			if(dockId == DROPSHIP_FLYBY_ID)
```suggestion
			var/dock_id = params["target"]
			if(dock_id == DROPSHIP_FLYBY_ID)
```

2023-10-11 21:56 UTC, fira approved these changes

2023-10-11 22:06 UTC, merged

2023-10-12 19:41 UTC, IsProbablyCatto commented
Isn't tested. Flyby is now coded as a destination, which lasts 30 seconds instead of 200 seconds.

2023-10-12 20:10 UTC, cuberound commented
jeh none tested it and you just merged it... indeed does not work as intended

2023-10-13 08:46 UTC, mullenpaul commented
> Isn't tested. Flyby is now coded as a destination, which lasts 30 seconds instead of 200 seconds.

This was tested, it introduced a regression.

Flybys we're always coded as destinations. Behind the scenes the shuttle is forced to transit to it's existing landing zone. This work was too change how the UI tells the backend how to do this.

2023-10-14 04:02 UTC, dadlips commented
There is no longer a cancel flyby button, is this intented? Our only option is to wait out the full 200+ seconds, and with a medevac'd marine this can be bad. 
![image](https://github.com/cmss13-devs/cmss13/assets/139605145/3733d5e4-e34b-49d4-8f83-d7f65ac3891f)