MP update
cmss13-devs/cmss13 pull request #463
Opened 2022-06-12 06:38 UTC by Diegoflores31

## About The Pull Request

Sprites: 
-New Taser sprite made by : Youtubeboy139
QoL:
new jittering effects and sway for taser and Stunbaton
Balance:
melee resistance from base MP and warden was lowered but increased Bullet armor instead. why ? because their armor is one of the best armor in the game for Ground fight but the worst for HVH and Mps should be more focused on HVH rather than xeno fighting.
Feature:
Adds the Smart disabler gun : provided only for cadets this weapon is locked to shoot only Precise energy rounds. this is made for to reasons:
 1)encourage people to play normal MP
 2)prevent griefing/baldness or at least make it less ugly
Adds Custom Beretta Pistol to CMP vendor . this weapon has similar stats to the Custom M4A3 but with a little more ammo and increased drip.
## Why It's Good For The Game

MP in general is quite a small playerbase and requires some love . this PR aims to give Mps some QoL effects , new sprites , new weapon for CMP , Cadet loadout changes and MORE !!

## Changelog

:cl:
add: Added Custom Beretta to CMP vendor
add: added Smart disabler gun for MP cadets , this one unlike regular tasers can only hit "wanted" criminals and its not toggleable
qol: new Jittering and Sway effects for stunbaton and disabler gun
balance: all sunglases provide flash protection
balance: MP armor now provides less Melee and more Bullet resistance to make the able to protect the almayer against threats 
fix: blindfold now impairs your vision when used
imageadd: Added a new Sprite for Disabler gun
/:cl:

2022-06-12 07:31 UTC, MusselMain commented
Will the custom Beretta be similar to the Survivor variants? or will it be able to use 9mm ammo? (Survivor Beretta's use a 9mm but it's not interchangeable with M4A3 or 88MOD4 9mm) Either way is fine, I'm just curious.

2022-06-12 17:04 UTC, Diegoflores31 commented
Custom beretta for now its just a variant of normal beretta and uses the same ammo but with better stats. I will check ammo in the future.

2022-06-12 18:53 UTC, hotimep commented
mutiny buff

2022-06-13 12:05 UTC, silencer-pl commented
This MR has all the tells of being made by someone that has not played much MP I'm afraid.

> new jittering effects and sway for taser and Stunbaton

This seems like a feature, not QOL honestly.

> melee resistance from base MP and warden was lowered but increased Bullet armor instead. why ? because their armor is one of the best armor in the game for Ground fight but the worst for HVH and Mps should be more focused on HVH rather than xeno fighting.

**This is a definite and absolute nerf to MPs.**

MP armor is meant to provide blunt force trauma protection because MPs are expected to be hit by fists and melee weapons during riots. This also nerfs Honor Guards who rely on those armor values somewhat. MPs are not "meant" to be HvH focused, the entirety of their expected role involves avoiding lethal combat.

This change makes no sense for both IC and OOC purposes. All it does it makes MPs more susceptible to shipside xenos, weaker to the damage they are most likely to receive IC wise and nerfs HGs. It literally makes every typical use case perform worse.

> Adds the Smart disabler gun : provided only for cadets this weapon is locked to shoot only Precise energy rounds. this is made for to reasons:
> 1)encourage people to play normal MP
> 2)prevent griefing/baldness or at least make it less ugly

Again, all it does is make Cadets worse at their expected role. 

What does having a working taser do with being a "normal" MP?

MPs need to switch to the normal mode regularly when there is no time to mark someone, like during riots. This directly nerfs MP cadets and makes them useless at range without someone marking perps.

This will not encourage RP, this will make Cadets be worse at the thing that they are expected to be learning - enforcing ML and learning procedure. Any reasonable CMP/Warden or MP will dump these roundstart and give cadets normal tasers.

MP Cadets are already expected to follow ML and SOP to the letter and this is just making playing a Cadet even more shit than it already is. Pointless change I'm afraid.

> Adds Custom Beretta Pistol to CMP vendor . this weapon has similar stats to the Custom M4A3 but with a little more ammo and increased drip.

Unnecessary, no other shipside dept head role has this, already has a custom weapon variant that's more fitting, I also want to say that a while ago Nanu said that the custom M4A3s is all they are getting, but I'm not 100% sure on that.

I would really suggest consulting this with some MP regulars because as is, none of these changes is a measurable improvement to MPs and all of your main points are in fact direct nerfs done for not apparent reason.

2022-06-13 16:28 UTC, Diegoflores31 commented
first of all . Mps Never do melee and they do have riot gear  i the imaginary case they need EVEN more armor (they old values al mediumhigh) which means B12 level armor with ligth armor slowdown which is arguably the strongest armor in the game for killing xenos.
2) most of the time mps are engaged is with ranged weapons and since their bullet resistance is shit they get gunned down all the time . I never heard of an mp killed with melee amd even if they somehow manage to die it would be really skill issue .
3) as you mentioned MP CADET is supposed to exist to learn ML and support MPs not be one similar to nurse .

2022-06-13 22:02 UTC, silencer-pl commented
>First of all . Mps Never do melee and they do have riot gear in the imaginary case they need EVEN more armor (their old values are mediumhigh) which means B12 level armor with light armor slowdown which is arguably the strongest armor in the game for killing xenos.

Correct. They get HIT, they do not fight. Their primary function is to ensure the smooth running of things on the ship, where they are way more likely to have to break up a fight than they are to be in a gunfight. 

>2) most of the time mps are actually engaged is with ranged weapons and since their bullet resistance is shit they get gunned down all the time . I never heard of an mp killed with melee and even if they somehow manage to die it would be really skill issue .

Everyone gets gunned down in an instant in HvH. Fighting off hostile humans is NOT what the crux of non event, regular gameplay for MPs is. Their most common combat encounters are:
- Xenos on the ship
- Xenos attacking the CO
- Getting slugged by an angry marine in the face.

Can you see what all of those are in common? You are nerfing MPs in all of these typical use cases for something that happens only in events, at best. 

In the scope of a normal round, an MP getting shot by guns is 99.9% of the time a clear rulebreak and not something that they are intended to worry about.

Hell, even a mutiny, the one sanctioned HvH event that can sort of happen during a normal round is not won, by the MPs anyway, by firepower and toughness but rather at effectively turtling and utilizing crowd control implements they have at their disposal. 

Let me say this again, clearly: You are majorly nerfing MPs for all their typical encounters during a normal round and providing literally nothing in return.

>3) as you mentioned MP CADET is supposed to exist to learn ML and support MPs not to be one. Similar to what nurse does.

No. 

MP Cadets have full responsibilities and expectations of the MP role. Yes, their heads are supposed to recognize that they are still learning and may need instruction, and sending them on hard assignments is obviously a bad idea, but what you're describing here would require a full on SOP/ML modification and specifically creating a unique rule set for Cadets. An MP Cadet may be called to perform any duty a regular MP does and needs fully functioning gear to accomplish that.

There is no current plan to change it or give Cadets more training wheels. I should know, I'm the admin manager and I literally take part in setting policies like that. 

Learning how to use the taser modes is also part of learning how to be an MP.

Again, no one but 0 hour newbs will use that and I can absolutely guarantee you that the instruction for any cadet will start with:

Step One, throw away your dumb training taser.
Step Two. Vend a proper working one from that machine over there.

> you will get shot if marines are rioting

See above. If you are in a situation where the mutineers catch you in a spot where they can freely open fire on you, you better kiss your ass goodbye because they have more guns. Way more guns. Mutinies are won by liberal application of riot control tools like gas grenades etc and a boost in armor values will not change that.

Partially because only dumb marines shoot you in the chest, where the armor actually protects you.

Anyhow, as far as the process of merging or not merging this goes, I am but a voice in the crowd with extensive MP hours, what do I know. But yeah, from that perspective alone: This MR does not in fact include any QOL for MPs, it does not "give them love" because it mostly nerfs or makes their duties harder and is based on an assumption about the MP Cadet that is not actually true. 

I actually missed those the first time, but here's more:

> -MP hats moved from Sectech to MP vendor

MPs already have their default headgear in their class vendor. 

The ones in the secvendors are meant as spares (same as uniforms, basic supplies, etc. partially because MPs can give them away to Marines, partially because by server rules MPs are required to wear departament headgear. What about deputized MPs? Where are they supposed to get their headgear that they are required to use while deputized? All spare departament gear is stored in the secvendors. They are the equivalent of the squad prep/req room uniform and equipment vendor, please leave them where they are. 

> -all sunglases variants now provide flash protection.

- MP QOL Update.
- Flashes are now useless.

Pick one. 

You can literally pick a set of sunglasses as your round start item, this is not space station 13.  Might as well throw away flashes, which means that MPs even faster resort to flashbangs now. Marines are not antagonists that need to arm themselves up against MPs. In a regular round, no violence/arrests happens between the two. Introducing mechanics like this, besides being (and I'm sensing a theme here) an outright nerf to MPs with no compensation whatsoever, reintroduces the antag/sec arms race that is so detrimental to antagonistic RP on ss13 servers. By limiting reliable methods of taking down suspects, you are literally making MPs fall back to more disruptive methods when in a pinch. 

I will say again, this MR clearly is made with no knowledge about how MPs work on CM and I'm somewhat assuming no real consultation with anyone who has any idea how it does, or is in a position to verify your conceptions about the role. 

Anyhow, I'm pretty sure I'm done here and will let the natural process of checks on this PR to go through, my advice would be at least consult MP regulars about changes such as the above so you steer them in the right direction next time.

2022-06-14 01:21 UTC, MusselMain commented
Yeah, now that I am looking harder (when I first looked at this PR I was half asleep and didn't truly breakdown the contents) this is a REALLY BAD IDEA, I'm a MP main who's been playing for 3 years, and I can say with 100% certainty, that giving us a bullet resistance buff at the cost of Melee protection is really stupid. 

The only time guns are ever a problem in a normal round are when you have either:
A: a hostile ERT, which usually doesn't last long anyway because xenos are already aboard 10 times out of 10. Or 
B: Riots, which are very rare and usually consist of 40 to 50 angry marines storming CIC (which will usually end with marines wining because of course 50 people are going to win against 5 to 10,  if you're not using riot gear and playing smart it is a difficult fight). 
HOWEVER in a REGULAR ROUND, the most common issue is either marines/MT's beating a MP for simply playing MP (which this nerf would amplify), also every hijack will be a death sentence for MP's now too as xenos don't shoot bullets, they slash, and spit acid at humans, if you want proof of bullet proof armor being useless in these fights, look at the Bulletproof Vest that use to be in EVERY red alert armory, but was replaced with the M3-VL after everyone realized that bulletproof vests are terrible in 98% of cases. Also anyone who's ever played MP knows that prisoners occasionally start killing each other/trying to breakout, leading to MP's having to step into the cells to solve this issue, which will now be harder to do because of the melee nerf.
Oh, and being a honor guard, where it's incredibly common to see you having to drag a wounded CO out of a fight, now you're even more exposed to a xeno slashing you, meaning you've just invalidated the Honor Guard subclass.

AND THAT'S NOT EVEN TALKING ABOUT THE FLASH/TASER NERF, making all sunglasses effective against flashes, means that anyone and their grandmother can get a pair from loadouts, or from massive surplus that can be located both on the Almayer, and on the many various maps, this both completely invalidates one of the MP's nonlethal options, and also means roles like the CE, CMO and SO's now have no way to nonlethally apprehend a marine without getting gear from the brig, or making their own, SO ONCE AGAIN A TERRIBLE NERF. 
The smart disabler sounds like a awful attempt to make MPC's more beginner friendly, HOWEVER in practice I can guarantee it will prevent MPC's from learning the separate modes and how to use them, as well as meaning that if a MPC is in a scenario where they only have a few seconds to react to a hostile, they now have to mark their target as a suspect, THEN get their disabler, instead of simply grabbing their disabler, switching it to normal (which should take less than a second) and giving the guy a zap before he can respond.
Nerfing the normal mode on normal tasers destroys it's role as a quickdraw nonlethal, I could understand making a change like making it less accurate then smart mode, but nerfing it's fire rate is just a bad idea forcing MP's to rely even more on their lethal sidearm then they already do (as taser shots aren't as fast and many smart suspects will simply outrun/dodge the taser shots).

In the comparison someone made of MPC's to Nurses (in terms of both being designed for new players to learn the roles), I have to HEAVILY DISAGREE, MPC's have identical gear and skills to MP's whereas Nurses have half the gear of Doctors, and can only preform a few incredibly limited operations, this means a Nurse will not be expected to remove a embryo, or mend a bone outside of using the autodoc, because even if they knew how they physically lack the skills. Whereas the MPC role allows players to learn all the tools they have access to as well as learning how to enforce ML. Which makes sense because having access to everything the MP's have means they can learn the proper way to play MP instead of  altering their skills or giving them less effective gear that will just make them struggle at both learning, and playing as a MP, and could EVEN TURN THEM AWAY from playing as a MP, which is a big problem as rounds containing no MP's usually leads to any problems being solved by the SO's/XO/CO/CMO/RO/SEA/CE having to step up to the plate, from which all of them are equipped with flashes as the only nonlethal option (which will be useless if this merges), except for the SEA who can be armed with rubber rounds.

Finally, moving the MP's alternative hats from the Sectech to MP vendor, will not only screw over MP's but SURVIVORS TOO! The number of times where I've butterfingered the menu and selected the wrong loadout option, forcing me to go on a wild goose chase to find the gear I wanted from a different location as a marine is bad enough (thankfully the surplus vendor exists to make SOME of these easier to acquire), and I can see the same happening for MP's if this is merged. How this screws over Survivors, is that Survivors won't be able to get MP helmets or other armored headgear from Sectechs, meaning their already difficult existence is now amplified as some maps lack any armored headgear options aside from Construction Helmets (Solaris, Shiva, LV-624, and Trijent are all great examples of maps where this change will severely affect and hinder Survivors). 

Honestly the only positive changes I see here, are pepper sprays having increased capacity, and the CMP Berretta, which honestly just sounds like an extended clip version of the M4A3 and honestly should just be that, instead of giving the CMP a sidearm that is statistically slower firerate, less damage, less AP, less attachment options and that uses a special type of 9mm ammo that's nowhere but survivors and maybe black market crates. If you really want to make this a thing you'll have to remake the survivor variant of the Beretta, without making it overpowered, so that they are at least comparable.

PLEASE, DO NOT MERGE THIS, anyone who's played MP more then 20 hours KNOWS how bad this so called "Buff" will hurt MP players (/Survivors), I can guarantee that these changes will make playing as a MP/learning as a MPC significantly harder, It's a terrible idea and an will only end in less players choosing MP.

2022-06-14 02:43 UTC, Diegoflores31 commented
i really cannot believe you are all complaining about a reduction of like 5 armor in exchance for 12 bullet . saying that you cannot survive a xeno attack having one of the best armor on the ship and comparable to CO armor ..  just to give some context i will show the stats of the average marine armor and the "new" MP armor and the "old" MP armor so you can see.
        
**Marine MEDIUM armor**
        armor_melee = CLOTHING_ARMOR_MEDIUM
	armor_bullet = CLOTHING_ARMOR_MEDIUM
	armor_laser = CLOTHING_ARMOR_MEDIUMLOW
	armor_energy = CLOTHING_ARMOR_NONE
	armor_bomb = CLOTHING_ARMOR_MEDIUMLOW
	armor_bio = CLOTHING_ARMOR_MEDIUM
	armor_rad = CLOTHING_ARMOR_MEDIUMLOW
	armor_internaldamage = CLOTHING_ARMOR_MEDIUM
	movement_compensation = SLOWDOWN_ARMOR_LIGHT
	storage_slots = 3
	siemens_coefficient = 0.7
	slowdown = SLOWDOWN_ARMOR_MEDIUM
That is the armor stats of a Marine MEDIUM armor. with MEDIUM SLOWDOWN
	
**MP ARMOR** "new"
	armor_melee = CLOTHING_ARMOR_MEDIUM
	armor_bullet = CLOTHING_ARMOR_MEDIUM
	armor_laser = CLOTHING_ARMOR_LOW
	armor_energy = CLOTHING_ARMOR_LOW
	armor_bomb = CLOTHING_ARMOR_MEDIUM
	armor_bio = CLOTHING_ARMOR_MEDIUMLOW
	armor_rad = CLOTHING_ARMOR_MEDIUMLOW
	armor_internaldamage = CLOTHING_ARMOR_MEDIUMLOW
	storage_slots = 2
	slowdown = SLOWDOWN_ARMOR_LIGHT
This is the MP armor which while having pretty much the same stats than a medium armor it lets you walk like it is just a light armor . and if you think thats op . the previous armor is basically CO armor (MediumHIGH melee) with less bullet resistance. saying Mps will get slaughtered despite having Better armor than marines its literally just skill issue .

I have addressed the issue with the precise disabler and made it so it shoot slightly faster than the conventional taser so there is a reward for setting the criminal to arrest and using "precision mode"

2022-06-14 05:03 UTC, c4xmaniac commented
I think the CMP should get the custom beretta because the beretta is dogshit irl and in game, so it’s a noob trap for the CMP. Awesome stealth nerf, good work.

2022-06-14 06:21 UTC, MusselMain commented
> i really cannot believe you are all complaining about a reduction of like 5 armor in exchance for 12 bullet . saying that you cannot survive a xeno attack having one of the best armor on the ship and comparable to CO armor .. just to give some context i will show the stats of the average marine armor and the "new" MP armor and the "old" MP armor so you can see.
> 
> **Marine MEDIUM armor** armor_melee = CLOTHING_ARMOR_MEDIUM armor_bullet = CLOTHING_ARMOR_MEDIUM armor_laser = CLOTHING_ARMOR_MEDIUMLOW armor_energy = CLOTHING_ARMOR_NONE armor_bomb = CLOTHING_ARMOR_MEDIUMLOW armor_bio = CLOTHING_ARMOR_MEDIUM armor_rad = CLOTHING_ARMOR_MEDIUMLOW armor_internaldamage = CLOTHING_ARMOR_MEDIUM movement_compensation = SLOWDOWN_ARMOR_LIGHT storage_slots = 3 siemens_coefficient = 0.7 slowdown = SLOWDOWN_ARMOR_MEDIUM That is the armor stats of a Marine MEDIUM armor. with MEDIUM SLOWDOWN
> 
> **MP ARMOR** "new" armor_melee = CLOTHING_ARMOR_MEDIUM armor_bullet = CLOTHING_ARMOR_MEDIUM armor_laser = CLOTHING_ARMOR_LOW armor_energy = CLOTHING_ARMOR_LOW armor_bomb = CLOTHING_ARMOR_MEDIUM armor_bio = CLOTHING_ARMOR_MEDIUMLOW armor_rad = CLOTHING_ARMOR_MEDIUMLOW armor_internaldamage = CLOTHING_ARMOR_MEDIUMLOW storage_slots = 2 slowdown = SLOWDOWN_ARMOR_LIGHT This is the MP armor which while having pretty much the same stats than a medium armor it lets you walk like it is just a light armor . and if you think thats op . the previous armor is basically CO armor (MediumHIGH melee) with less bullet resistance. saying Mps will get slaughtered despite having Better armor than marines its literally just skill issue .
> 
> I have addressed the issue with the precise disabler and made it so it shoot slightly faster than the conventional taser so there is a reward for setting the criminal to arrest and using "precision mode"

First off, making all sunglasses counter flashes is (as I mentioned earlier) a terrible idea, the only way this can function in a way that works balance wise, is if you either remove loadout sunglasses (and suffer the backlash of angry loadout marines), or make it only apply to specific sunglasses that are harder to obtain, in it's current state it makes the flash, a nonlethal that already has a weakness (it can burn out, has short range, and isn't super effective), into a incredibly situational item.

In case you haven't noticed, every person who has complained so far has some experience playing MP, and the vast majority of the people here have complained about this being a bad idea, please listen to the community, the last time someone pushed a change that the mass majority of players disliked, it ended in a bad change that negatively affected the game and I'd rather not see a armor that has worked perfectly fine for it's intended role and I'd argue fits great as is, get changed in a way that will result in many longer term MP players quitting the role, or having to significantly alter the way they've played for YEARS to fit the new functions. 

Just look at the MP's armor values, they already have weaker acid protection then the average medium armor marine, however they made up for this in combat against xenos by being faster, and having better melee protection then the average marine, your decision is basically turning MP's into more of a pincushion then they already are in fights against xenos (which happen rather often as MP's are expected to handle any sneaky boarder xenos, occasionally do honor guard, and help when the Dropship crashes, and the fact that they WILL be in EVERY ROUND unless there's a event) giving them increased bullet protection that will help them in the rare occasion that a riot or hostile ERT comes aboard is incredibly silly because there's already two armors that are both easily accessible all over the ship that will fill that role better called the M3-VL (which has the same bullet protection as heavy armor/MARSOC armor), and even then I and many other players rarely use them because most HVH battles involve players aiming EVERYWHERE BUT the chest (because very few armors protect all of the arms, or legs), and the Riot Armor, which is extremally strong in riot and boarder situations because of it's full coverage and great melee and bullet armor.

Once again, I want to focus on the "where this will be helpful" part of this change, from my experience gunfights are very rare as attempting to shoot a MP will usually result in severe punishments from marine law for the player who does so, whereas I've seen and experienced a marine or MT trying to stab/bash me at least twice a round, because legally they'll only be arrested for assault, meaning this happens WAY more often then getting shot at ever does. 

The current MP armor is perfect for the role it fits, it is faster then the average marine (meaning it's easier to catch marines), has better melee protection that's on par with heavy armor (MP's will need to protect them against random assaults, or in the case of the warden, violent prisoners), and the only downsides are decreased armor against bullets (which are a very rare concern, I've only been shot 6 times in my 3 years playing and of that 4 of the times were angry PVT's who missed, meaning it really doesn't matter), and decreased acid protection (which is a bit of a concern in most rounds). 
These stats allow MP's to have very clear weaknesses and advantages, acid and bullets can be avoided pretty well with the current MP armor's speed.

NOW ACTUALLY LOOK at what range most of the MP's nonlethal options function at: aside from the Taser (and I guess flashbangs, but using them on anything other then a riot or crackhead holding the CO hostage is a bad idea), every other option requires you to get within 1-2 tiles of your target, Pepperspray: close range, Stun baton: touching range, Flashes: touching range, even the MP's standard disarm is touching range, NOTICE A COMMON FACTOR? Having great melee protection is PERFECT for MP's as they WILL have to get within touching range of their target on a frequent basis which is helped by their increased speed, this also extends to the Honor Guard. When the CO is deploying it's fairly common for them to ask two MP's to join them on the fronline to ensure their body is recovered if they die, for this the CIC armory has two kits containing a Honor Guard MK221 (with a bayonet, and magharness), a Honor Guard Headset (that gives the MP's BIGGER SPEECH OVER COMMS), some buckshot, and some medicine. Now I ask you again: LOOK AT THAT LOADOUT what range do you think it's promoting the MP's be at? CLOSE RANGE (for the less observant, this is proven by the fact that the kit contains shotguns, buckshot, bayonets, and Magharns, which are all tools that are best utilized at close range), which is where the increased Melee protection shines, as it's very common for you to have to drag the CO's body out of the frontline, and having armor that provides great melee protection and great speed is perfect for this as well, as this means you can quickly and safely recover the CO body more efficiently then most other roles can with their armors (WHICH IS WHY MP'S ARE GIVEN HONOR GUARD). 

To make a long story short, weakening the Melee protection on an armor that arguably utilizes it more often then any other role for increased bullet resistance is counterintuitive, WHEN will slightly more bullet protection help? marines who shoot at MP's for no reason usually results in punishments both IC (getting arrested for most of the round) and OOC (potential ban depending on circumstances), if there's a Riot/mutiny switching to Riot armor LIKE EVERY MP who knows what they're doing, is the best call as it's got full body coverage, great melee protection, and great bullet protection all at the cost of only speed, ERT's ALWAYS (I've only seen one exception and it was a admin event) happen after crash, meaning any hostile ERT's are usually the least of your concerns, and in the case of HVH events, they almost always happen o [...]

2022-06-14 17:34 UTC, Diegoflores31 commented
You are literally saying they need CO level armor to survive basic groundside combat and to kill a xeno shipside which is often a single lurker. 
About the sunglasses i get it because marines will pick it as loadout item but about the armor. No you dont need a CO armor to play . Like if you cannot survive a xeno with a upgraded medium armor + the best shotgun available in the station + fireman carry . As i said before it is just a complete skill issue.
PD hitting mps with melee is a rulebreak too . Its called IE

2022-06-14 17:36 UTC, Diegoflores31 commented
> > First of all . Mps Never do melee and they do have riot gear in the imaginary case they need EVEN more armor (their old values are mediumhigh) which means B12 level armor with light armor slowdown which is arguably the strongest armor in the game for killing xenos.
> 
> Correct. They get HIT, they do not fight. Their primary function is to ensure the smooth running of things on the ship, where they are way more likely to have to break up a fight than they are to be in a gunfight.
> 
> > 2. most of the time mps are actually engaged is with ranged weapons and since their bullet resistance is shit they get gunned down all the time . I never heard of an mp killed with melee and even if they somehow manage to die it would be really skill issue .
> 
> Everyone gets gunned down in an instant in HvH. Fighting off hostile humans is NOT what the crux of non event, regular gameplay for MPs is. Their most common combat encounters are:
> 
> * Xenos on the ship
> * Xenos attacking the CO
> * Getting slugged by an angry marine in the face.
> 
> Can you see what all of those are in common? You are nerfing MPs in all of these typical use cases for something that happens only in events, at best.
> 
> In the scope of a normal round, an MP getting shot by guns is 99.9% of the time a clear rulebreak and not something that they are intended to worry about.
> 
> Hell, even a mutiny, the one sanctioned HvH event that can sort of happen during a normal round is not won, by the MPs anyway, by firepower and toughness but rather at effectively turtling and utilizing crowd control implements they have at their disposal.
> 
> Let me say this again, clearly: You are majorly nerfing MPs for all their typical encounters during a normal round and providing literally nothing in return.
> 
> > 3. as you mentioned MP CADET is supposed to exist to learn ML and support MPs not to be one. Similar to what nurse does.
> 
> No.
> 
> MP Cadets have full responsibilities and expectations of the MP role. Yes, their heads are supposed to recognize that they are still learning and may need instruction, and sending them on hard assignments is obviously a bad idea, but what you're describing here would require a full on SOP/ML modification and specifically creating a unique rule set for Cadets. An MP Cadet may be called to perform any duty a regular MP does and needs fully functioning gear to accomplish that.
> 
> There is no current plan to change it or give Cadets more training wheels. I should know, I'm the admin manager and I literally take part in setting policies like that.
> 
> Learning how to use the taser modes is also part of learning how to be an MP.
> 
> Again, no one but 0 hour newbs will use that and I can absolutely guarantee you that the instruction for any cadet will start with:
> 
> Step One, throw away your dumb training taser. Step Two. Vend a proper working one from that machine over there.
> 
> > you will get shot if marines are rioting
> 
> See above. If you are in a situation where the mutineers catch you in a spot where they can freely open fire on you, you better kiss your ass goodbye because they have more guns. Way more guns. Mutinies are won by liberal application of riot control tools like gas grenades etc and a boost in armor values will not change that.
> 
> Partially because only dumb marines shoot you in the chest, where the armor actually protects you.
> 
> Anyhow, as far as the process of merging or not merging this goes, I am but a voice in the crowd with extensive MP hours, what do I know. But yeah, from that perspective alone: This MR does not in fact include any QOL for MPs, it does not "give them love" because it mostly nerfs or makes their duties harder and is based on an assumption about the MP Cadet that is not actually true.
> 
> I actually missed those the first time, but here's more:
> 
> > -MP hats moved from Sectech to MP vendor
> 
> MPs already have their default headgear in their class vendor.
> 
> The ones in the secvendors are meant as spares (same as uniforms, basic supplies, etc. partially because MPs can give them away to Marines, partially because by server rules MPs are required to wear departament headgear. What about deputized MPs? Where are they supposed to get their headgear that they are required to use while deputized? All spare departament gear is stored in the secvendors. They are the equivalent of the squad prep/req room uniform and equipment vendor, please leave them where they are.
> 
> > -all sunglases variants now provide flash protection.
> 
> * MP QOL Update.
> * Flashes are now useless.
> 
> Pick one.
> 
> You can literally pick a set of sunglasses as your round start item, this is not space station 13. Might as well throw away flashes, which means that MPs even faster resort to flashbangs now. Marines are not antagonists that need to arm themselves up against MPs. In a regular round, no violence/arrests happens between the two. Introducing mechanics like this, besides being (and I'm sensing a theme here) an outright nerf to MPs with no compensation whatsoever, reintroduces the antag/sec arms race that is so detrimental to antagonistic RP on ss13 servers. By limiting reliable methods of taking down suspects, you are literally making MPs fall back to more disruptive methods when in a pinch.
> 
> I will say again, this MR clearly is made with no knowledge about how MPs work on CM and I'm somewhat assuming no real consultation with anyone who has any idea how it does, or is in a position to verify your conceptions about the role.
> 
> Anyhow, I'm pretty sure I'm done here and will let the natural process of checks on this PR to go through, my advice would be at least consult MP regulars about changes such as the above so you steer them in the right direction next time.

Mps have spare hats on Sec lockers mostly i wanted to reduce bloat from the sectech that is supposed to sell gear rather than clothing

2022-06-14 18:47 UTC, MusselMain commented
> You are literally saying they need CO level armor to survive basic groundside combat and to kill a xeno shipside which is often a single lurker. About the sunglasses i get it because marines will pick it as loadout item but about the armor. No you dont need a CO armor to play . Like if you cannot survive a xeno with a upgraded medium armor + the best shotgun available in the station + fireman carry . As i said before it is just a complete skill issue. PD hitting mps with melee is a rulebreak too . Its called IE

I see, so you finally admit that this isn't MP's "getting some love" it's a straight up nerf. I find it hilarious that you are defending your change to armor with: "it's only 5 damage", "It's already got the same Melee armor as the CO armor" and "If you can't handle a slight reduction then skill issue", That's. Not. The. Point. The point is that you are making a change that is completely unnecessary, and will benefit MP's in very rare situations, I can't actually tell what your logic is behind this change, either you don't want MP's to have armor that is slightly comparable to CO armor, and in the case of the whole skill issue thing, dodging bullets and winning gunfights is where the skill comes in it allows MP's to have the Speed to avoid ranged attacks from acid to bullets, whereas some melee attacks you physically cannot dodge, especially when it comes to Hijacks (as it's often you'll be fighting on weeds, in tight corridors, and where you can get flanked rather easily, or getting swarmed by angry marines on the dropship). If it's only a slight change, DON"T make the change, it benefits no-one, and your arguments for why it's to be added are all incredibly weak and don't at all reflect the average 50+ hour MP's experience (and I'm not talking hangout in brig all day MP I'm talking always patrolling and usually being the first to know about problems MP). As I mentioned earlier, there's a REASON why they have great melee protection, the same way how there's a reason why MP's are always Honor Guard: Because they have strong melee armor, great shotguns, decent speed, and IC are (supposed to be) loyal to the CO, this change will hinder their ability to preform HG duties significantly, as they already had subpar acid protection, and with your nerf will have armor equivalent to a medium armor marine (making their role as a HG useless as marines can literally do a better job now). I've mentioned it a ton too, but Melee protection is something MP's need because of how often people assault them, which yes, assault is a crime, however in practice if the marine who did it is any role other then a grunt (rifleman), they're let off the hook 9 times out of 10, meaning you're wheeled off to Medbay for getting stabbed to crit by three marines, while they get free because they're RTO's, SG's, and SPEC's, it's a common issue that happens and is rarely ever provoked, but since it happens, having great melee protection can save your ass quite often in those cases. Shootings, on the other hand rarely happen, and when they do, It's either a PVT one handing a M39, or some angry marine who didn't get what he wanted at req, and is usually either shot by the CT, or Disarmed by a MP, it's just not a very useful stat in regular gameplay.

2022-06-15 06:59 UTC, Prymalis commented
Is this a nerf hidden behind a QoL? Do you even play MP regularly? Why do you think do you know better what the role actually needs?

2022-06-17 17:34 UTC, Nanu308 requested changes
Fix aforementioned requests, other things may need changing as well once i see it finalized.

2022-06-17 17:34 UTC, Nanu308 commented on code/game/machinery/vending/vendor_types/crew/senior_officers.dm
> +		list("Beretta Custom Pistol", 0, /obj/item/storage/belt/gun/m4a3/b92fs/custom, MARINE_CAN_BUY_SECONDARY, VENDOR_ITEM_RECOMMENDED),
No need for a special gun

2022-06-17 17:34 UTC, Nanu308 commented on code/modules/clothing/suits/marine_armor.dm
> +	armor_bullet = CLOTHING_ARMOR_MEDIUM
Leave bullet as is and same with melee.

2022-06-17 17:34 UTC, Nanu308 commented on code/modules/clothing/suits/marine_armor.dm
> +	armor_bullet = CLOTHING_ARMOR_MEDIUMHIGH
Leave bullet as is and same with melee.

2022-06-17 17:34 UTC, Nanu308 commented on code/modules/clothing/suits/marine_armor.dm
> +	armor_bullet = CLOTHING_ARMOR_HIGH // Head of security should be able to survive a nurse with a pistol
You can increase the bullet to Medium here since its an M3 Pattern and not M2.

2022-06-17 17:34 UTC, Nanu308 commented on code/modules/clothing/suits/marine_armor.dm
> +	armor_bullet = CLOTHING_ARMOR_HIGH
You can increase the bullet to Medium here since its an M3 Pattern and not M2.

2022-06-17 17:34 UTC, Nanu308 commented on code/modules/clothing/suits/marine_armor.dm
> +	armor_melee = CLOTHING_ARMOR_MEDIUMHIGH
Drop these changes , it can inherit of M3 as it did.

2022-06-17 17:34 UTC, Nanu308 commented on code/modules/clothing/suits/marine_armor.dm
> +	armor_melee = CLOTHING_ARMOR_MEDIUMHIGH //added because of the base MP armor nerf
Drop these changes , it can inherit of M3 as it did. Also no need to comment in the reason, leads to bloat, just a fyi.

2022-06-17 17:34 UTC, Nanu308 commented on code/game/objects/items/storage/belt.dm
> +	new /obj/item/weapon/gun/energy/taser/safe(src)
No need for cadets to be unable to use their tazer in this way, needless handholding.

2022-06-17 17:34 UTC, Nanu308 commented on code/modules/projectiles/guns/energy.dm
> +/obj/item/weapon/gun/energy/taser/safe/use_unique_action()
No need to make a special tazer locked to its own mode

2022-06-17 17:34 UTC, Nanu308 commented on code/modules/projectiles/guns/pistols.dm
> +/obj/item/weapon/gun/pistol/b92fs/custom
No need for a special gun to the CMP, instead look at replacing the normal colony one if the new sprite is good and fitting for the tone/setting.

2022-06-21 22:56 UTC, Diegoflores31 commented
Closing MR . suggestions basically say to delete everything but the jittering effect and they sprites . bad way to spend gbp

2022-06-21 22:56 UTC, closed without merging