trident shuttle now generic
cmss13-devs/cmss13 pull request #4639
Opened 2023-10-11 21:07 UTC by mullenpaul

# About the pull request

I have made the Trident shuttle generic, allowing this to be reused on other mapping projects. We can also have multiple elevators in the same mission.

Trident dam also now has two elevators.

1. LZ1 to Engineering
2. LZ2 to Omega

# Explain why it's good for the game

Other maps will be able to incorporate the Trident elevator shuttle.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
refactor: reworked trident elevators to be reusable on new maps
maptweak: Trident map now has two elevators, lz1 to engineering and lz2 to omega
/:cl:

2023-10-16 16:06 UTC, mullenpaul commented
Code changes done but I need to check a few things before undrafting

2023-10-20 10:26 UTC, harryob requested changes

2023-10-20 10:26 UTC, harryob commented on code/datums/shuttles.dm
> +	elevator_network="B"
```suggestion
	elevator_network = "A"

/datum/map_template/shuttle/trijent_elevator/B
	elevator_network = "B"
```

2023-10-20 10:26 UTC, harryob commented on code/modules/shuttle/computers/trijent_elevator_control.dm
> +		if(shuttle.elevator_network == "" || elev.elevator_network == null)
```suggestion
		if(!shuttle.elevator_network)
```

2023-10-20 10:26 UTC, harryob commented on code/modules/shuttle/shuttles/trijent_elevator.dm
> +	airlock_exit="west"
```suggestion
	name = "occupied"
	id = STAT_TRIJENT_OCCUPIED
	airlock_exit = "west"
```

2023-10-20 10:26 UTC, harryob commented on code/modules/shuttle/shuttles/trijent_elevator.dm
> +	airlock_exit="west"
```suggestion
	name = "empty"
	id = STAT_TRIJENT_EMPTY
	airlock_exit = "west"
```

2023-10-23 10:22 UTC, fira approved these changes

2023-10-23 18:38 UTC, mullenpaul commented
This is working on TM

2023-10-30 10:20 UTC, harryob approved these changes

2023-10-30 10:38 UTC, merged