Makes dartboards functional
cmss13-devs/cmss13 pull request #4677
Opened 2023-10-14 11:19 UTC by VileBeggar

# About the pull request

adds basic functionality to dartboards and makes them craftable with cardboard.
fixes a bug where some signs lose their icon when deconstructed.

# Explain why it's good for the game

the dartboard's been sitting there, looking pretty and doing nothing else for a good while. more intractability with props is always fun to see.
# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

https://github.com/cmss13-devs/cmss13/assets/17518895/d2e2b103-90cf-4fa8-a920-ae22ca9fd250

</details>

# Changelog

:cl:
add: Dartboards are now functional and can be crafted with cardboard.
fix: Fixed an issue with some deconstructed signs losing their icon.
/:cl:

2023-10-15 18:38 UTC, harryob requested changes
very nice stuff all round, just a few nits

2023-10-15 18:38 UTC, harryob commented on code/game/objects/structures/misc.dm
> +	if(contents.len)
```suggestion
	if(length(contents))
```

2023-10-15 18:38 UTC, harryob commented on code/game/objects/structures/misc.dm
> +		if(contents.len != 1)
```suggestion
		if(length(contents) != 1)
```

2023-10-15 18:38 UTC, harryob commented on code/game/objects/structures/misc.dm
> +	for(var/atom/movable/embedded_items in contents)
```suggestion
	for(var/atom/movable/embedded_items as anything in contents)
```
contents can only have /atom/movables in it, so we can skip the typecheck here

2023-10-15 18:38 UTC, harryob commented on code/game/objects/structures/misc.dm
> +		. += SPAN_NOTICE("There [is_are] [contents.len] item\s embedded into [src].")
```suggestion
		. += SPAN_NOTICE("There [is_are] [length(contents)] item\s embedded into [src].")
```

2023-10-15 18:38 UTC, harryob commented on code/game/objects/structures/misc.dm
> +	if(contents.len)
```suggestion
	if(length(contents))
```

2023-10-15 18:38 UTC, harryob commented on code/game/objects/structures/misc.dm
> +		qdel(src)
```suggestion
	if(over_object != usr || !Adjacent(usr))
		return
		
	if(!ishuman(usr))
		return

	visible_message(SPAN_NOTICE("[usr] unsecures [src]."))
	var/obj/item/dartboard/unsecured_board = new(loc)
	usr.put_in_hands(unsecured_board)
	qdel(src)
```

2023-10-15 18:38 UTC, harryob commented on code/game/objects/structures/misc.dm
> +	if(contents.len)
i know it looks more stupid, but we prefer length() to .len as it's faster (by an absurdly small margin) and won't cause runtimes on null (but contents'll never be null sooo 🤷‍♂️)

2023-10-16 04:28 UTC, harryob approved these changes

2023-10-17 00:14 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2023-10-17 17:32 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2023-10-18 21:50 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2023-10-18 22:32 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2023-10-19 19:47 UTC, harryob approved these changes
i need to free you from map conflict hell

2023-10-19 20:54 UTC, merged