Adds Synthetic Manufacturers
cmss13-devs/cmss13 pull request #4685
Opened 2023-10-15 05:49 UTC by Steelpoint

# About the pull request

Allows Synthetic players to select a manufacturer for their Synthetic character.

This currently does not have any tangible in-game effect outside of allowing a Synthetic player to inform themselves of who manufactured them. 

In addition to a broad suite of manufactures (noted in the photos below) I added a 'independent manufacturer' for edge cases. Currently players will default to Weyland-Yutani if they don't select anything. 

# Explain why it's good for the game

Adds a little bit of lore and flavour to a Synthetic players character building.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

![Screenshot 2023-10-15 13 45 29](https://github.com/cmss13-devs/cmss13/assets/6595389/c72c3526-163e-4fcb-82ca-80f9e7f1175e)

</details>

# Changelog

:cl:
add: Synthetics may now select their manufacturer. This currently has no tangible in-game effect. 
/:cl:

2023-10-17 08:24 UTC, Steelpoint commented
Requested changes made.

2023-10-18 19:48 UTC, harryob requested changes

2023-10-18 19:48 UTC, harryob commented on code/modules/client/preferences.dm
> +					var/synth_builder = input(user, "Choose your manufacturer.")  as null|anything in list("Weyland-Yutani", "Borgia Industries", "Hyperdyne Systems", "Lasalle Bionational", "Seegson", "MedTech", "G
tgui_input_list

2023-10-18 19:48 UTC, harryob commented on code/modules/client/preferences_savefile.dm
> +	if(isnull(synth_manufacturer)) synth_manufacturer = initial(synth_manufacturer)
this should use sanitize_inlist() with the above global list

2023-10-18 19:48 UTC, harryob commented on code/modules/client/preferences.dm
> +					var/synth_builder = input(user, "Choose your manufacturer.")  as null|anything in list("Weyland-Yutani", "Borgia Industries", "Hyperdyne Systems", "Lasalle Bionational", "Seegson", "MedTech", "G
this list should be a global list or define so it can be referenced later for sanitizing

2023-11-02 01:00 UTC, closed without merging