Add Non-Hostile UPP ERT
cmss13-devs/cmss13 pull request #4713
Opened 2023-10-18 06:24 UTC by Steelpoint

# About the pull request

Adds a non-hostile UPP ERT alternative to the hostile ERT spawn. Has the same chance to spawn as the hostile version. 

# Explain why it's good for the game

In lore the UPP enjoy a cold war esque relationship with the UA, a possibly neutral ERT helps better reflect this.

Furthermore, as more UPP are added to the game, the need to help shift the community meta regarding UPP away from 100% hostile to 50/50 hostile is going to become more important, this would be 1 small step. 

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
add: UPP ERT's have a chance to be neutral to the USCM.
/:cl:

2023-10-18 22:47 UTC, JackieEstegado commented
You may want to put in an exclusivity check so that a (non admin) UPP ERT of the oppossing friendliness cant spawn if one was spawned earlier (ie by an admin)

2023-10-19 16:05 UTC, fira commented
Funny. A global toggle to ensure consistency might be cool but that means having to hack into ERT code

2023-10-19 19:43 UTC, harryob requested changes

2023-10-19 19:43 UTC, harryob commented on code/datums/emergency_calls/upp.dm
> +	objectives = "Eliminate the UA Forces to ensure the UPP prescence in this sector is continued. Listen to your superior officers and take over the [MAIN_SHIP_NAME] at all costs."
```suggestion
	objectives = "Eliminate the UA Forces to ensure the UPP presence in this sector is continued. Listen to your superior officers and take over the [MAIN_SHIP_NAME] at all costs."
```

2023-10-19 19:43 UTC, harryob commented on code/datums/emergency_calls/upp.dm
> +	objectives = "Eliminate the UA Forces to ensure the UPP prescence in this sector is continued. Listen to your superior officers and take over the [MAIN_SHIP_NAME] at all costs."
```suggestion
	objectives = "Eliminate the UA Forces to ensure the UPP presence in this sector is continued. Listen to your superior officers and take over the [MAIN_SHIP_NAME] at all costs."
```

2023-10-20 10:28 UTC, harryob approved these changes

2023-10-20 11:12 UTC, merged