adds click drag from storage into your hands
cmss13-devs/cmss13 pull request #4722
Opened 2023-10-19 08:24 UTC by harryob

the title really

:cl:
qol: you can now click drag from items in your storage to your hands
/:cl:

2023-10-19 16:00 UTC, fira requested changes

2023-10-19 16:12 UTC, harryob commented on code/_onclick/hud/screen_objects.dm
> +/atom/movable/screen/inventory/New(loc, ...)
yeah totally, my brain was melting with this one

2023-10-19 19:36 UTC, harryob commented on code/_onclick/hud/screen_objects.dm
> +	if(slot_id != "l_hand" && slot_id != "r_hand")
i completely forgot we had them

2023-10-21 22:10 UTC, fira approved these changes

2023-11-01 12:35 UTC, merged