CO Vendor Tweaks
cmss13-devs/cmss13 pull request #4751
Opened 2023-10-21 06:04 UTC by 4hands44

# About the pull request

CO's only having one belt and satchel to choose from is weird and dumb. This PR seeks to Fix this by adding a variety of existing belts to the CO vendor, as well as touches the Weapon Vendor, by adding a variety attachments and equipment, to bring CO in line with SLs, IOs and other Field officer roles.

# Explain why it's good for the game
Gives COs more options for their loadouts

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog
:cl:
add: Added More Attachments, Backpacks, and Belts to the CO arsenals.
add: CO now has an essentials Kit like Other roles, Containing his Designator, and other tools.
add: Re-Adds Bridgecoat to some Officer Dress vendors (Limited to CO(+) and XO currently).
del: Removed Laser designator from CO spawn Preset.
balance: M46c Now Also takes Mk1 UGL, not just the Mk2 one.
balance: CO can now Vend Nightvision and Welding Visors.
balance: Adds grenade packets to CO Vendor.
/:cl:

2023-10-21 12:58 UTC, fira commented on code/game/machinery/vending/vendor_types/crew/commanding_officer.dm
> +		list("M3 Sniper's Smock", 0, /obj/item/storage/backpack/marine/smock, MARINE_CAN_BUY_BACKPACK, VENDOR_ITEM_MANDATORY),
Isn't that kind of out of place?

2023-10-21 13:49 UTC, 4hands44 commented on code/game/machinery/vending/vendor_types/crew/commanding_officer.dm
> +		list("M3 Sniper's Smock", 0, /obj/item/storage/backpack/marine/smock, MARINE_CAN_BUY_BACKPACK, VENDOR_ITEM_MANDATORY),
Could you clarify?

2023-10-22 18:13 UTC, Zonespace27 requested changes

2023-10-22 18:13 UTC, Zonespace27 commented on code/game/machinery/vending/vendor_types/crew/commanding_officer.dm
> +		list("WP Grenade Pack", 15, /obj/item/storage/box/packet/phosphorus, null, VENDOR_ITEM_REGULAR),
split these into their own category

2023-10-22 18:13 UTC, Zonespace27 commented on code/game/machinery/vending/vendor_types/crew/commanding_officer.dm
> +		list("M46C pulse rifle", 0, /obj/effect/essentials_set/co/riflepreset,MARINE_CAN_BUY_SECONDARY, VENDOR_ITEM_MANDATORY),
```suggestion
		list("M46C Pulse Rifle", 0, /obj/effect/essentials_set/co/riflepreset, MARINE_CAN_BUY_SECONDARY, VENDOR_ITEM_MANDATORY),
```

2023-10-22 18:13 UTC, Zonespace27 commented on code/game/machinery/vending/vendor_types/crew/commanding_officer.dm
> +		list("Commanding Officer essentials Kit", 0, /obj/effect/essentials_set/commanding_officer, MARINE_CAN_BUY_ESSENTIALS, VENDOR_ITEM_MANDATORY),
```suggestion
		list("Commanding Officer Essentials Kit", 0, /obj/effect/essentials_set/commanding_officer, MARINE_CAN_BUY_ESSENTIALS, VENDOR_ITEM_MANDATORY),
```

2023-10-22 18:13 UTC, Zonespace27 commented on code/game/machinery/vending/vendor_types/crew/commanding_officer.dm
> +		list("M3 Sniper's Smock", 0, /obj/item/storage/backpack/marine/smock, MARINE_CAN_BUY_BACKPACK, VENDOR_ITEM_MANDATORY),
remove this.

2023-10-22 18:13 UTC, Zonespace27 commented on code/game/machinery/vending/vendor_types/crew/commanding_officer.dm
> +		list("Medkit Pouch", 0, /obj/item/storage/pouch/medkit, MARINE_CAN_BUY_POUCH, VENDOR_ITEM_REGULAR),
revert this

2023-10-22 18:13 UTC, Zonespace27 commented on code/game/machinery/vending/vendor_types/crew/commanding_officer.dm
> +		list("Command Pouch", 0, /obj/item/storage/pouch/pistol/command, MARINE_CAN_BUY_POUCH, VENDOR_ITEM_REGULAR),
remove this

2023-10-22 18:13 UTC, Zonespace27 commented on code/modules/projectiles/guns/rifles.dm
> +		/obj/item/attachable/attached_gun/grenade/mk1,
remove this

2023-10-22 19:08 UTC, Zonespace27 requested changes

2023-10-22 19:08 UTC, Zonespace27 commented on code/game/machinery/vending/vendor_types/crew/commanding_officer.dm
> +		list("Underbarrel Grenade Launcher", 15, /obj/item/attachable/attached_gun/grenade/mk1, null, VENDOR_ITEM_REGULAR),
exchange this for the regular GL instead of the mk1's

2023-10-25 21:42 UTC, Zonespace27 approved these changes

2023-10-25 21:43 UTC, Zonespace27 commented on code/game/machinery/vending/vendor_types/crew/commanding_officer.dm
> +		list("Night Vision Visor", 25, /obj/item/device/helmet_visor/night_vision, null, VENDOR_ITEM_RECOMMENDED),
```suggestion
```
Changed my mind about this

2023-10-25 22:10 UTC, merged