Removes Multi-Broadcast
cmss13-devs/cmss13 pull request #476
Opened 2022-06-14 20:18 UTC by Geevies

## About The Pull Request

Removes the ability to go ,abcd Charge.

## Why It's Good For The Game

It clogs up the channels, and useless info gets spread to all the squads rather than CIC speaking with SLs, who speak with their squads.

## Changelog

:cl:
del: Removed multi-broadcast via ,abcd.
/:cl:

2022-06-14 20:24 UTC, tempelers commented
This is too hurtful to CIC. 99% of the time SLs don't relay information to their squads because they're too busy being PFC+++. It also allows CTs and ROs to relay that a supply is incoming.

Alternatively, I think you can make multi-channel tied to headsets. So nobody but command could do it.

2022-06-14 21:01 UTC, PhantomEpicness commented
Remove it for SOs, keep it for XO,CO and RO because they are roles that actually benefit from it.

2022-06-14 21:04 UTC, c4xmaniac commented
Keep it for XO and CO, bye bye for the rest of them

2022-06-14 21:08 UTC, Unknownity commented
keep for CO,XO,RO and Synth pls

2022-06-14 21:44 UTC, Superreallycoolguy commented
Blessed change, as a CO the amount of times I have threatened to brig/BE COMICALLY UNHELPFUL CIC members (but also heavily including VCs, especially so) of going: ,abcd PUSH! or ,abcd GET HER!!! or my favorite ,abcd YOU ARE DOING GOOD.

This shit getting removed will be more helpful than if it stays, it'll clear up comms so comically and I won't have to nonstop scream at the VC who for some reason uses all comms to just say "MOVE OUT OF THE WAY". Its such a pain in the ass, but for CIC the announcement times were reduced. People said "what about RO and Req"...just ask on single channels as you need to, be real, you are only gonna ask bravo what they need for FOB and sometimes spec ammo from other squads, you don't need to mass broadcast, and if you do, ctrl + c and ctrl v.

thank you Mr Geeves

2022-06-14 22:11 UTC, silencer-pl commented
We did fine before multibroadcast got introduced, and we'll do fine without it again.

Anything to see less ROs, CMOs, and even damn VCs constantly spam either useless or contradictory info and a return to having to be a bit more mindful with your CIC/tablet broadcasts,

2022-06-14 22:23 UTC, hotimep commented
best PR i've ever seen
![charge](https://user-images.githubusercontent.com/59359762/173699202-c57e971a-b989-452f-8718-0efd1cabdf6c.gif)

2022-06-15 01:15 UTC, MusselMain commented
> This is too hurtful to CIC. 99% of the time SLs don't relay information to their squads because they're too busy being PFC+++. It also allows CTs and ROs to relay that a supply drop is incoming.
> 
> Alternatively, I think you can make multi-channel tied to headsets. So nobody but command could do it.

Tbh I never use multicomm as a SO, ususally I just tell SL's first then the sqauds, then again, I've only had to command 1 to 3 squads, so maybe having 4 will be too much for me.

2022-06-15 02:02 UTC, tempelers commented
> > This is too hurtful to CIC. 99% of the time SLs don't relay information to their squads because they're too busy being PFC+++. It also allows CTs and ROs to relay that a supply drop is incoming.
> > Alternatively, I think you can make multi-channel tied to headsets. So nobody but command could do it.
> 
> Tbh I never use multicomm as a SO, ususally I just tell SL's first then the sqauds, then again, I've only had to command 1 to 3 squads, so maybe having 4 will be too much for me.

Every time I've done CIC, I've commanded basically all the squads. Usually whenever play SO, I'm basically the SL because the SL isn't good. I usually only play during lowpop though so, my experiences might not reflect on all.

2022-06-15 03:10 UTC, neroisvcute commented
Based. I remember the days when SL's actually had to pay attention and communicate with their squad. If you want to tell all squads say it in :v. If the SL doesn't do it then bully until they do or stop playing SL. That's how it used to be and how it should be, too many bald and boring SL's. Plus there's fucking RTOs that can help give orders, why even keep RTOs around if all they do is be PFC/engineer++

2022-06-15 05:03 UTC, stanalbatross commented
> I guess this is TM worthy? The reason this was added in the first place was to reduce the tedium of needing to communicate to all 4 squads , as prior to multicast we had to copy and paste the message 4 times. Though this was also before the announcement cooldown timers got halved, however, so might not be as impactful as I think it will be.

No it was after

2022-06-15 06:33 UTC, doomdrvk commented
Absolutely terrible, I use this a lot as a doctor to make sure people know where I am. And yes its very commonly used to shout on all channels what the queen is doing or where she's at.

2022-06-15 06:47 UTC, Prymalis commented
Could this be the start of the ubiqutous access of comms channels by everybody? Too many people have comms access to shit that only ends up cluttering it. To the comment above, if PFCs wanna know where the doc is, they ask their SL. Who should know it from the CMO, who should know it from you. Too convoluted? It's called chain of command, communications shouldn't be minmaxxed.

2022-06-15 07:28 UTC, lcarapaica commented
Good CICs were known before the ,abcd feature for being able to relay information well to all squads, nowadays it's mostly chat spam that feels LRP when it's some pfc blasting into all comms and you can't stop it.
Blessed change, makes people think about who they want their message to be read by rather than being lazy and blasting comms.

2022-06-15 07:34 UTC, tempelers commented
> Good CICs were known before the ,abcd feature for being able to relay information well to all squads, nowadays it's mostly chat spam that feels LRP when it's some pfc blasting into all comms and you can't stop it. Blessed change, makes people think about who they want their message to be read by rather than being lazy and blasting comms.

Just make it so Command can't give Command headsets to anyone. In fact, just remove them from the locker lmao.

2022-06-15 07:39 UTC, JeserTheFox commented
Make it a feature only command headsets are capable of, remove any surplus command headsets.

2022-06-15 14:04 UTC, stagda commented
Is the issue multi-broadcast or too many people having access to too many channels? Multi-broadcast is a useful feature if you are  running certain departments solo.

2022-06-16 09:26 UTC, Don2137 commented
![dreamseeker_BNsxkmaYJY](https://user-images.githubusercontent.com/63935800/174038978-225c71e6-cd33-4b7e-972d-0d8d53c8fe11.png)
Pointless chat spam. Might as well just make a marine common channel at this point if everyone spams squad channels anyway.

2022-06-16 16:41 UTC, tempelers commented
> ![dreamseeker_BNsxkmaYJY](https://user-images.githubusercontent.com/63935800/174038978-225c71e6-cd33-4b7e-972d-0d8d53c8fe11.png) Pointless chat spam. Might as well just make a marine common channel at this point if everyone spams squad channels anyway.

That's vital information. CIC works best when they're directly commanding each squad.

2022-06-16 20:13 UTC, JeserTheFox commented
> ![dreamseeker_BNsxkmaYJY](https://user-images.githubusercontent.com/63935800/174038978-225c71e6-cd33-4b7e-972d-0d8d53c8fe11.png) Pointless chat spam. Might as well just make a marine common channel at this point if everyone spams squad channels anyway.

Yeah, the only not needed message here is "Yeeeaaah", others are valid, tho i do understand how annoying this can be... but only for those who do have access to it.

Alternative is to make multibroadcast have, say, 15 seconds recharge time. Allows you to send vital message instantly to all squads, prevents one person to spam with it.

2022-06-17 20:41 UTC, Shad0vvs approved these changes

2022-06-19 08:59 UTC, stanalbatross requested changes

2022-06-19 08:59 UTC, stanalbatross commented on code/game/objects/items/devices/radio/headset.dm
> +	var/multibroadcast_cooldown = 3 MINUTES
make these "three minutes" "1 minutes" values into defines

2022-06-19 09:14 UTC, stanalbatross approved these changes

2022-06-19 09:15 UTC, merged