Add Item & Footprints offsets
cmss13-devs/cmss13 pull request #4762
Opened 2023-10-21 19:02 UTC by fira

# About the pull request

This:
* Adds transverse offsets to blood footprints
* Adds notable pixel offsets to a few items
* Adds a very slight pixel offset to all items
* Enables rotation for thrown flashlights
* Cause objects exiting a surface (rack/table) to regenerate offset instead of being stuck at center
* Stops random offsets from overwriting mapped offsets

# Explain why it's good for the game

The goal is to have map visuals more organic when we have a lot of objects on the ground - targeting in particular items you find readily in dense areas such as Reqs or a FOB.

Consider this for example, the blood footprints are all aligned, in more extreme situations (eg WO) it makes an actual "grid" which i personally find very immersion breaking
![image](https://github.com/cmss13-devs/cmss13/assets/604624/28b593cf-6c37-468a-98b9-a344911bee9d)

Adding a slight offset helps counter that:
![image](https://github.com/cmss13-devs/cmss13/assets/604624/504d1baf-385c-4774-86f3-6331c4ac87ed)

# Changelog

:cl:
add: Bloody footprints are now slightly offset to break long visual straight lines.
fix: Items do not align back to the center of turfs anymore when picked from a surface (table or rack)
add: Some more items now have offsets on the map display, and they all can be slightly offset.
/:cl:

2023-10-21 22:51 UTC, fira commented on code/game/objects/items.dm
> +	/// How much to offset the item alongside X visually
```suggestion
	/// How much to offset the item alongside Y visually
```

2023-10-26 11:44 UTC, harryob requested changes
1 nit

2023-10-26 11:44 UTC, harryob commented on code/game/objects/items.dm
> +	/// How much to offset the item randomly etiher way alongside Y visually
```suggestion
	/// How much to offset the item randomly either way alongside X visually
	var/ground_offset_x = 0
	/// How much to offset the item randomly either way alongside Y visually
```

2023-10-26 19:54 UTC, harryob approved these changes

2023-10-26 20:19 UTC, merged