Spittin for u
cmss13-devs/cmss13 pull request #4822
Opened 2023-11-02 00:19 UTC by Diegoflores31

# About the pull request

Sentinel
Sentinel slowing spit now has a "combo" mechanic. that works like this:
1)Slow (4 seconds)
2)Super slow (2 seconds) - IF slowed
3)Daze ( 2 seconds)+ funny jitter effect - If super slowed
4)Stun (1.75 seconds) - if both Dazed and Superslowed or already knocked down ( stun doesnt stack) // PD : no its not infinite stun.

old behaviour
Super slow (2.5 seconds)

-No armor spit now only applies a 1.75 second stun instead of 3 seconds and doesnt stack.
-If you are hit with a no armor you will now be only stuned , not stunned and superslowed like before.
-Improved Var names and reduced code lines from slowing spit.

# Explain why it's good for the game

Adds more gaming to sentinels so they can be more usefull as a utility-ranged Caste .

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
add: Sentinel Slowing spit has a chain of effects (slow>superslow>daze>stun)
/:cl:

2023-11-02 01:23 UTC, GoldenDarkness55 commented
Won't this "combo" with any other slow/daze effect leading to weird results? Should also add some kinda indicator for stacking effects like what base prae has for acid hits

2023-11-02 02:21 UTC, Diegoflores31 commented
> Won't this "combo" with any other slow/daze effect leading to weird results? Should also add some kinda indicator for stacking effects like what base prae has for acid hits

teamwork is fun !! i made relatively sure that you cant cheese it too easily but if you teamwork with other sentinels or use your creativity well . thats part of the game . if its found to be too OP it can be adjusted on the go

2023-11-02 11:46 UTC, GoldenDarkness55 commented
> teamwork is fun !! i made relatively sure that you cant cheese it too easily but if you teamwork with other sentinels or use your creativity well . thats part of the game . if its found to be too OP it can be adjusted on the go

It's fun but not if it's unclear, which it would be if it triggered off unrelated abilities/effects applying any of the debuffs. Also 2 sentinels spitting on same target would probably lead to permstuns, not to mention the neuro slash applies daze so you get an instant stun off it. Bruh.

2023-11-02 17:23 UTC, NexusStorm1 commented
What happens if you spit at a target already stunned/knocked down. Do they get stunned for an additional 1.75 seconds, will the combo reset and they'll get slowed, or will the spit have no effect?

2023-11-05 20:34 UTC, Diegoflores31 commented
> > teamwork is fun !! i made relatively sure that you cant cheese it too easily but if you teamwork with other sentinels or use your creativity well . thats part of the game . if its found to be too OP it can be adjusted on the go
> 
> It's fun but not if it's unclear, which it would be if it triggered off unrelated abilities/effects applying any of the debuffs. Also 2 sentinels spitting on same target would probably lead to permstuns, not to mention the neuro slash applies daze so you get an instant stun off it. Bruh.

1- if you are ALONE fighting 2 xenos at the same time ... well skill issue.
2- you have to be superslowed AND dazed . it doesnt work like that

2023-11-05 20:35 UTC, Diegoflores31 commented
> What happens if you spit at a target already stunned/knocked down. Do they get stunned for an additional 1.75 seconds, will the combo reset and they'll get slowed, or will the spit have no effect? Also what exactly is daze? Does it also apply superslow or does it just make them shake around? Because if it's the latter then the 3rd spit becomes the weakest spit in the combo.

no . the stun Resets to 1.75 which means trying to "stack" stuns just wont work .

2023-11-13 11:37 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2023-11-22 17:03 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2023-11-22 23:45 UTC, Zonespace27 requested changes
Balance-wise I'm *alright* with this but it seems hard to communicate to the target or xeno

2023-11-22 23:45 UTC, Zonespace27 commented on code/datums/ammo/xeno.dm
> +			target_human.visible_message(SPAN_DANGER("[target_human] collapses into the ground."))
Collapses to the ground
Also this message doesn't make sense if the target is already prone

2023-11-27 12:36 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2023-12-01 19:23 UTC, fira commented
I'd suggest building on #4842 with a proper combo counter for these, it's much more powerful and robust and allows more interesting interactions than just basing off status values

2023-12-01 23:12 UTC, Diegoflores31 commented
will wait for #4842 to rebuild xeno spit

2024-01-12 01:04 UTC, closed without merging