Pill packets fit in helmets now
cmss13-devs/cmss13 pull request #4841
Opened 2023-11-05 01:34 UTC by Releasethesea

# About the pull request

Makes it so you can put pill packets in your helmet since i didnt know how to originally, for now im only doing this for the helmet, but over the next week or so ill be making it so they can fit in all the marine hats that can fit autoinjectors 

# Explain why it's good for the game

Pill packets shouldve been able to be placed in your helmet, i didnt know how to do this when they were added, this remedies that

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

testing consisted of joining a private server and seeing if they fit in helmets 
# Changelog

:cl:

fix: Makes it so that Pill packets fit in helmets

/:cl:

2023-11-05 01:45 UTC, HeresKozmos commented
This is nice, might make it more worthwhile to take pill packets now.

2023-11-05 23:54 UTC, Zonespace27 requested changes

2023-11-05 23:54 UTC, Zonespace27 commented on code/modules/clothing/head/helmet.dm
> +	/obj/item/storage/pill_bottle/packet ="brutepack (bandages)",
```suggestion
	/obj/item/storage/pill_bottle/packet = "brutepack (bandages)",
```

2023-11-06 02:08 UTC, harryob approved these changes

2023-11-06 02:16 UTC, merged