/tg/ Status Effects Part 2 - datum, KD, KO, Stuns
cmss13-devs/cmss13 pull request #4842
Opened 2023-11-05 13:03 UTC by fira

# About the pull request

Part 2 - this includes porting the actual status_effect datum, modifying it to fit our purposes by backing it with timers similarly to old system, and finally implementing KD, KO and Stun with it.

This contains Part 1 PR so if you want to take a look at it I'd advise checking the last commits or setting up a compare between both branches.

# Explain why it's good for the game

Predictable status timers. Current ones are bogus in their handling of "life tick correction" and will "stack" time even when they're not supposed to.

Also provides a more robust backend for general effects, and integrates status effects into it.

# Testing Photographs and Procedure

Summary testing of buckling interactions, explosion knock times, crawling, resting. Will have to be expanded once part 1 is ready

# Changelog

:cl:
add: Added Buckled, Handcuffed and Legcuffed screen alerts
code: Ported /tg/ status effects backend, modified with timers to let effects end at appropriate time
code: Stun, Knockdown and Knockout now use the new effects backend
balance: Due to backend change, all KO/KD/Stuns may behave differently timing wise. This is of course subject to adjustments.
fix: KO/KD/Stuns do not artificially and randomly ''stack'' due to incorrect timer offset calculation anymore.
fix: Stun now correctly applies Stun reduction values instead of Knockdown values
fix: Crawling can now be interrupted by a normal move, if you are fit enough to do so.
/:cl:

2023-11-05 15:46 UTC, fira commented
FWIW most of the sprites are actually unused, they didn't blend in well with the rest of the UI, so i just left cuff/buckle ones. Might need to cleanup

2023-11-06 09:49 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2023-11-07 14:57 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2023-11-09 21:39 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2023-11-13 12:52 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2023-11-15 21:37 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2023-11-17 09:02 UTC, fira commented
Regression to address, humans can crawl away from explosions AGAIN

2023-11-20 21:47 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2023-11-22 20:21 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2023-11-27 21:16 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2023-11-30 10:59 UTC, fira commented on code/datums/status_effects/_status_effect.dm
> +/// Called whenever the effect is applied in on_created
That's actually a /tg/ mistake but yeah I'll change it

2023-11-30 15:20 UTC, zzzmike reviewed
![image](https://github.com/cmss13-devs/cmss13/assets/85382350/582b818b-b63a-4b88-bb09-807079f40b57) For lines 277 and 287 - I guess all weakens need to be changed to knockdown and/or stun? This should resolve my comment on https://github.com/cmss13-devs/cmss13/issues/5074

2023-11-30 16:59 UTC, fira commented
Yup exactly

Right now Stun is preventing you from taking actions + moving, so Stun + KnockDown is equivalent to old KnockDown functionality. New KD just prevents you from standing and moving (important distinction due to crawling)

2023-12-01 20:08 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2023-12-06 09:12 UTC, harryob requested changes

2023-12-06 09:12 UTC, harryob commented on code/datums/status_effects/debuffs/debuffs.dm
> +//	alert_type = /atom/movable/screen/alert/status_effect/knockdown
still pending sprites or is that gonna be a later pr

2023-12-06 09:12 UTC, harryob commented on code/modules/mob/living/living_health_procs.dm
> +/mob/living/proc/IsKnockOut()
```suggestion

/mob/living/proc/IsKnockOut()
```

2023-12-06 09:12 UTC, harryob commented on code/modules/mob/living/living_health_procs.dm
> +/mob/living/proc/AmountKnockOut() //How much time remains - scaled by GLOBAL_STATUS_MULTIPLIER (normally in multiples of legacy 2 seconds)
```suggestion

/// How much time remains - scaled by GLOBAL_STATUS_MULTIPLIER (normally in multiples of legacy 2 seconds)
/mob/living/proc/AmountKnockOut() 
```

2023-12-06 09:12 UTC, harryob commented on code/modules/mob/living/living_health_procs.dm
> +	return 0
```suggestion
	return 0

```

2023-12-06 09:12 UTC, harryob commented on code/modules/mob/living/living_health_procs.dm
> +/mob/living/proc/AdjustKnockOut(amount, ignore_canstun = FALSE) //Adds to remaining duration
```suggestion

/mob/living/proc/AdjustKnockOut(amount, ignore_canstun = FALSE) //Adds to remaining duration
```

2023-12-06 09:12 UTC, harryob commented on code/modules/mob/living/living_health_procs.dm
> +/mob/living/proc/SetKnockOut(amount, ignore_canstun = FALSE) //Sets remaining duration
```suggestion

/mob/living/proc/SetKnockOut(amount, ignore_canstun = FALSE) //Sets remaining duration
```

2023-12-07 21:30 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2023-12-08 09:24 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2023-12-09 03:10 UTC, private-tristan commented on code/modules/mob/living/carbon/xenomorph/XenoProcs.dm
> +		M.Stun(pounceAction.knockdown_duration) // To replicate legacy bheavior. Otherwise M39 Armbrace users for example can still shoot
bheavior 😭

2023-12-15 15:53 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2023-12-16 13:06 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2023-12-18 21:02 UTC, Zonespace27 approved these changes

2023-12-18 21:02 UTC, Zonespace27 commented on code/datums/status_effects/debuffs/debuffs.dm
> +// /datum/status_effect/incapacitating/unconscious/tick(seconds_between_ticks)
Commented code

2023-12-18 21:02 UTC, Zonespace27 commented on code/datums/status_effects/debuffs/debuffs.dm
> +//	heal_flag_necessary = HEAL_CC_STATUS
.

2023-12-18 21:02 UTC, Zonespace27 commented on code/datums/status_effects/_status_effect.dm
> +//	if(!heal_flag_necessary || (heal_flags & heal_flag_necessary))
.

2023-12-18 21:02 UTC, Zonespace27 commented on code/datums/status_effects/stacking_effect.dm
> +//o	owner.cut_overlay(status_overlay)
.

2023-12-18 21:43 UTC, fira commented
I cut down overlay integration & some other commented code 

Kept the commented rejuvenation flags since it's something we might want short term when adding more effects

2023-12-19 05:46 UTC, merged