Adds possibility to customize crates
cmss13-devs/cmss13 pull request #4868
Opened 2023-11-07 14:54 UTC by fira

# About the pull request

You can now customize non-secure crates using packaging wrap, by tagging them and changing their appearance to a list of common crates. The tag works as a labeler label, and is also displayed in the overwatch supply drop alert.

# Explain why it's good for the game

If anything, it's that these Squad crates are just sitting there unused. I don't know if this feature will be used much by live Reqs.

# Changelog

:cl:
add: You can now use package wrap to change standard crates visuals.
add: You can now label crate with package wrap, which will also be shown during overwatch supply drop alert.
mapadd: Added more packaging wrap to Requisitions.
/:cl:

2023-11-07 20:10 UTC, Zonespace27 requested changes

2023-11-07 20:10 UTC, Zonespace27 commented on code/datums/components/crate_tag.dm
> +/datum/component/crate_tag/proc/notify_squad(datum/source, datum/squad/squad)
///

2023-11-07 20:10 UTC, Zonespace27 commented on code/datums/components/crate_tag.dm
> +/datum/component/crate_tag/InheritComponent(datum/component/C, i_am_original, name, obj/structure/closet/crate/masquarade_type)
one letter vars

2023-11-07 20:10 UTC, Zonespace27 commented on code/modules/cm_tech/droppod/supply.dm
> +	var/obj/structure/package
code doc

2023-11-07 20:10 UTC, Zonespace27 commented on code/modules/cm_tech/droppod/supply.dm
> +	package = null
```suggestion
	package = null
	return ..()
```

2023-11-07 20:10 UTC, Zonespace27 commented on code/modules/recycling/sortingmachinery.dm
> +				var/obj/structure/bigDelivery/P = new /obj/structure/bigDelivery(get_turf(crate.loc))
one letter

2023-11-07 20:10 UTC, Zonespace27 commented on code/modules/recycling/sortingmachinery.dm
> +			if (src.amount > 3 && !crate.opened)
remove src

2023-11-07 20:10 UTC, Zonespace27 commented on code/modules/recycling/sortingmachinery.dm
>  			src.amount -= 3
ditto

2023-11-07 20:10 UTC, Zonespace27 commented on code/modules/recycling/sortingmachinery.dm
> +				src.amount -= 3
ditto

2023-11-07 20:10 UTC, Zonespace27 commented on code/modules/recycling/sortingmachinery.dm
> +				SPAN_NOTICE("You wrap \the [target], leaving [amount] units of paper on \the [src]."),\
\the and \a are unneeded

2023-11-07 20:10 UTC, Zonespace27 commented on code/modules/recycling/sortingmachinery.dm
> +			else if(src.amount < 3)
src

2023-11-07 20:44 UTC, fira commented on code/datums/components/crate_tag.dm
> +/datum/component/crate_tag/InheritComponent(datum/component/C, i_am_original, name, obj/structure/closet/crate/masquarade_type)
It's parent signature

2023-11-07 23:47 UTC, realforest2001 approved these changes

2023-11-08 16:29 UTC, Zonespace27 approved these changes

2023-11-08 17:41 UTC, merged