QoL addition and adjustment to squad role vendors.
cmss13-devs/cmss13 pull request #4876
Opened 2023-11-08 11:15 UTC by Huffie56

# About the pull request

Multiple change that i will detail more now just putting it there so that the bots tell me if it's a disaster.

# Explain why it's good for the game

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
qol: multiple change to make that navigate in the different squad vendor feel more similar.
balance: added an enginiering section to all squad vendor role.
code: made binoculars be their own section for all squad vendor role.
/:cl:

2023-11-08 14:02 UTC, Huffie56 commented
i will update changelog and all when if fixed it. if you know what's wrong tell me...

2023-11-08 14:52 UTC, Birdtalon reviewed
Commas.

2023-11-08 17:10 UTC, Drulikar requested changes
Please stick to maintaining the same access to items in a pr like this, especially with how ambiguous the changelog is. Remove all changes (additional access to NVG) that result in this requiring balance considerations. Keep this as a quality of life update. If you want additional access to NVG to be considered, have that be a PR all by itself.

2023-11-08 18:46 UTC, Huffie56 commented on code/game/machinery/vending/vendor_types/intelligence_officer.dm
>  		list("VP78 Magazine", 5, /obj/item/ammo_magazine/pistol/vp78, null, VENDOR_ITEM_REGULAR)
done thanks

2023-11-08 18:46 UTC, Huffie56 commented on code/game/machinery/vending/vendor_types/squad_prep/squad_engineer.dm
> +		list("VP78 Magazine", 5, /obj/item/ammo_magazine/pistol/vp78, null, VENDOR_ITEM_REGULAR)
done thanks

2023-11-08 18:46 UTC, Huffie56 commented on code/game/machinery/vending/vendor_types/squad_prep/squad_leader.dm
> +		list("VP78 Magazine", 5, /obj/item/ammo_magazine/pistol/vp78, null, VENDOR_ITEM_REGULAR)
done thanks

2023-11-08 18:47 UTC, Huffie56 commented on code/game/machinery/vending/vendor_types/squad_prep/squad_medic.dm
> +		list("VP78 Magazine", 5, /obj/item/ammo_magazine/pistol/vp78, null, VENDOR_ITEM_REGULAR)
done thanks

2023-11-08 18:47 UTC, Huffie56 commented on code/game/machinery/vending/vendor_types/squad_prep/squad_rifleman.dm
> +		list("VP78 Magazine", 5, /obj/item/ammo_magazine/pistol/vp78, null, VENDOR_ITEM_REGULAR)
done thanks

2023-11-08 18:47 UTC, Huffie56 commented on code/game/machinery/vending/vendor_types/squad_prep/squad_smartgunner.dm
> +		list("VP78 Magazine", 5, /obj/item/ammo_magazine/pistol/vp78, null, VENDOR_ITEM_REGULAR)
done thanks

2023-11-08 18:47 UTC, Huffie56 commented on code/game/machinery/vending/vendor_types/squad_prep/squad_specialist.dm
> +		list("VP78 Magazine", 5, /obj/item/ammo_magazine/pistol/vp78, null, VENDOR_ITEM_REGULAR)
done thanks

2023-11-08 18:47 UTC, Huffie56 commented on code/game/machinery/vending/vendor_types/squad_prep/squad_tl.dm
> +		list("VP78 Magazine", 5, /obj/item/ammo_magazine/pistol/vp78, null, VENDOR_ITEM_REGULAR)
done thanks

2023-11-14 05:58 UTC, realforest2001 requested changes
As with the comment above regarding NVGs, please split all the balance changes out of this PR for atomisation purposes.

2023-11-22 08:51 UTC, Huffie56 commented
going to do a PR way smaller and atomized...

2023-11-22 08:52 UTC, closed without merging