New brig remap revive
cmss13-devs/cmss13 pull request #4931
Opened 2023-11-14 20:13 UTC by ItsVyzo

# About the pull request

Fully remaps the brig to feel more interconnected and better use up unused space.

Cryo Room: One room to fit all
APC Room: Central to Brig // Some APCs in different locations for ease of use
CMP Office: Moved
Warden Office: Moved next to CMP's office - new bedroom - oversees courtyard and can check if maint breach happens
Execution: Isolated viewing room, next to perma.
Evidence: Expanded evidence room, with printer, file storage and other detectivey needs.
Armory: Larger in size, added sectech
Equipment room: Larger - more chargers - food machines
Medical room: tiny expansion
Cells: Two new cells
Break room: Take a break - have a donut

# Explain why it's good for the game

Makes it easier to navigate brig (in theory) adds more cells for use, and better uses up empty space in the brig. Interconnects the brig to feel more wholesome.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl: LTNTS
maptweak: remapped brig to be more concise, more interconnected, and easier to navigate. And added more cells for when needed.
qol: adds RiotTech (SecTech but for Riot Control with Rubber Bullets - obvs Code Blue+ only)
qol: CMP's locker requires Armory access to open now
qol: suspects are now colored nardo gray in security list
/:cl:

2023-11-14 20:57 UTC, Releasethesea commented
idk if its my copy or what but its not properly zoned, it also feels a bit too cramped to navigate compared to the current brig, maybe you should have more doors between sections, like through the APC room or something

2023-11-15 14:34 UTC, Nanu308 requested changes
Read Comments and Fix

2023-11-15 14:34 UTC, Nanu308 commented on maps/map_files/USS_Almayer/USS_Almayer.dmm
![bilde](https://github.com/cmss13-devs/cmss13/assets/59782240/e37a9631-d9b3-40a2-82b8-1e1ef226481a)
Look at other cryo rooms, the floor tiles, there's a cool standard to follow :D

2023-11-15 14:34 UTC, Nanu308 commented on maps/map_files/USS_Almayer/USS_Almayer.dmm
![bilde](https://github.com/cmss13-devs/cmss13/assets/59782240/8d15f311-7bbc-4652-a27b-b3f881dff2c4)
Area Issue
![bilde](https://github.com/cmss13-devs/cmss13/assets/59782240/b3d370d6-a614-4500-b742-d6f70de8cbf6)
Area Issue
![bilde](https://github.com/cmss13-devs/cmss13/assets/59782240/f07e196a-acd0-4347-b933-b4d8c8dff3ac)
Area Issue
![bilde](https://github.com/cmss13-devs/cmss13/assets/59782240/ee40b15a-a54a-49aa-8791-0895c0216e76)
AREA ISSUES. FIX!

2023-11-15 14:34 UTC, Nanu308 commented on maps/map_files/USS_Almayer/USS_Almayer.dmm
![bilde](https://github.com/cmss13-devs/cmss13/assets/59782240/eb059f15-909d-4d50-9c30-a258bb0e1fdd)
Tables make it a 1x tile hallway. Too Crowded.
![bilde](https://github.com/cmss13-devs/cmss13/assets/59782240/c791fb9a-2361-4943-8508-9de67485f775)
This area is really boxy now, boxy looks bad, try breaking it up a bit or changing the room's layout.
![bilde](https://github.com/cmss13-devs/cmss13/assets/59782240/d8929d0d-7a74-4c7a-ad4d-e73c55e917a3)
If you're adding APC to other rooms then remove these ones. One APC per area only.
![bilde](https://github.com/cmss13-devs/cmss13/assets/59782240/5f3efdb9-1806-4502-9cf6-9cb74b94da40)
This area looks really bad rn. Too confined and tight, also really boxy.

2023-11-15 14:34 UTC, Nanu308 commented on maps/map_files/USS_Almayer/USS_Almayer.dmm
![bilde](https://github.com/cmss13-devs/cmss13/assets/59782240/078ee8c6-b912-41b9-a7bb-1d18cb5370df)
Evidence Room, no need for the photocopier or toner, takes up needless space and expands the room, making it blocky.

![bilde](https://github.com/cmss13-devs/cmss13/assets/59782240/702702f4-2480-4ba0-bd5f-672fbd5cd4fe)
People gonne stand and work all day? Where them chairs! Also, room's layout here is a bit meh now, probably due to the rooms above.

![bilde](https://github.com/cmss13-devs/cmss13/assets/59782240/64008d02-e185-414e-a912-7c6e1ae131ea)
There's two single doors behind these shutters, looks really weird. Make it a single door entrance or remove it.

2023-11-15 14:34 UTC, Nanu308 commented on maps/map_files/USS_Almayer/USS_Almayer.dmm
![bilde](https://github.com/cmss13-devs/cmss13/assets/59782240/e05f2482-651c-4e38-a44e-5984242fa4b4)
I like the movement of permacells and execution room closer in this case
![bilde](https://github.com/cmss13-devs/cmss13/assets/59782240/6fd8aa28-32e6-4260-a05f-8dcc60f60a89)
This looks pretty aight as well, gj.

2023-11-15 14:34 UTC, Nanu308 commented on maps/map_files/USS_Almayer/USS_Almayer.dmm
**FOR THE ENTIRE BRIG:**
- Go over areas.
- Go over APC placements.
- Go over semiotic symbols and indicators and place them where they are meant to be.
- Check telephone locations.

2023-11-22 03:37 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2023-11-23 03:00 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2023-11-24 10:56 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2023-11-24 10:57 UTC, Nanu308 requested changes

2023-11-24 10:57 UTC, Nanu308 commented on maps/map_files/USS_Almayer/USS_Almayer.dmm
![bilde](https://github.com/cmss13-devs/cmss13/assets/59782240/ecf13937-2c4a-4e43-9cdc-3e0e00e00aff)
![bilde](https://github.com/cmss13-devs/cmss13/assets/59782240/b7d08594-8930-4030-8f47-a463aed08bfb)
![bilde](https://github.com/cmss13-devs/cmss13/assets/59782240/c32a3426-320d-42c8-8b04-7339c3304b25)
APC's should be on "clear" walls aka no light fixtures or semiotics and such when possible. As you can see, it looks really bad in-game otherwise. Go over all the APC's in brig, i just posted some examples here. So either place the Semiotic next to it or offset it so it looks good in-game. 👍 

![bilde](https://github.com/cmss13-devs/cmss13/assets/59782240/66cef747-4585-4423-a860-8da5e55f0cf5)
![bilde](https://github.com/cmss13-devs/cmss13/assets/59782240/919b6645-c7f0-4aa9-ba73-a827fdea622e)
![bilde](https://github.com/cmss13-devs/cmss13/assets/59782240/286d1fe2-8849-4064-8be4-29175e95f4a7)

![bilde](https://github.com/cmss13-devs/cmss13/assets/59782240/0914d9b7-f9ea-49e7-ba58-cf7bbe562ad0)
Double glass walls, same as squad preps.

![bilde](https://github.com/cmss13-devs/cmss13/assets/59782240/61f5e29d-5137-41a0-b384-1bb313a9cf08)
Tiles on floor, need some red.

Other than that, coming together nicely 👌

2023-11-24 17:49 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2023-11-24 22:46 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2023-11-24 22:48 UTC, closed without merging