Allow playing uploaded sounds through the music player w/ Webroot
cmss13-devs/cmss13 pull request #4934
Opened 2023-11-14 22:52 UTC by fira

# About the pull request

Too long have we suffered at the hands of admin auditive abuse. 

The prophet, spookydonut, once said, "You shouldn't be using this lol". And he was right. Using "Play MIDI sound" both reduces usability for our users, and can cause performance issues by freezing up the game for a while as the data is transfered to these 200 poor CM addicts.

So we sought to alienate it with "Play Internet Sound" backed by youtube-dl. Unfortunately, some things are subject to geo blocking or simply not available on Youtube. Thus the regime of terror of Admins continues.

This PR brings us one step closer to our goal: it allows to use the now renamed "Play Admin Sound" to (also) upload a sound file to Webroot and have it played through CDN. It also works with simple transport but that mostly defeats the point.

Also reduced default volume for new players from 50% to 20%... Don't worry, It's still way more than enough to get them to quit the server, i have mine at 2-10% max

# Explain why it's good for the game
* Less new player abuse by reducing default volume
 * More performance by allowing big or custom songs to be backed by CDN
 * Better UX: People can easily see the song name and more easily stop it
 * Admins can now hide the name of played songs if they want to. Don't ask me why.

# Testing Photographs and Procedure
![image](https://github.com/cmss13-devs/cmss13/assets/604624/4f00c45d-76ca-47e2-860a-2f26d55de2a4)
You'll have to believe me on the sound working

# Changelog
:cl:
balance: Default Web Music Player volume is now 20% down from 50%. It was found too effective against new players.
admin: "Play Internet Sound" is now "Play Admin Sound" and optionally allow to hide the track name.
admin: "Play Admin Sound" can now be used with uploaded tracks, which use CDN delivery and the in-chat music player, granting players more control over them.
admin: Removed "Play Midi Sound". 
/:cl:

2023-11-15 06:23 UTC, Zonespace27 commented
After many hours of careful consideration, I have determined the balance is acceptable.

2023-11-15 11:00 UTC, spookydonut requested changes
https://github.com/cmss13-devs/cmss13/pull/4934/files#diff-e4659e01d523f65c28d6386ea09f2556f7ef6989a8b18e654824c7cd99fcafe1L108

delete this

2023-11-15 16:50 UTC, fira commented
> https://github.com/cmss13-devs/cmss13/pull/4934/files#diff-e4659e01d523f65c28d6386ea09f2556f7ef6989a8b18e654824c7cd99fcafe1L108
> 
> delete this

done, removed it, play admin sound now works off simple transport too as a fallback
on the plus side that means people can't misuse the old one

2023-11-22 22:22 UTC, harryob approved these changes

2023-11-22 22:32 UTC, merged