check_grep.sh part ??: adds all global vars to the global controller
cmss13-devs/cmss13 pull request #4940
Opened 2023-11-16 18:14 UTC by harryob

per title really

god willing no player facing changes

2023-11-16 21:47 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2023-11-16 21:48 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2023-11-16 22:34 UTC, fira requested changes
Finally, just found a few minor things to cut pretty much

2023-11-16 22:34 UTC, fira commented on code/modules/shuttles/marine_ferry.dm
> +	if(!(info_tag in GLOB.s_info))
doesnt seem like anything puts anything in this, could probbaly be cut and /proc/loadShuttleInfoDatums too

2023-11-16 22:34 UTC, fira commented on html/changelogs/archive/2020-10.yml
> +  - tweak: Reworked the GLOB.RoleAuthority and rolling of roles. Special roles are now
CL edit

2023-11-16 22:34 UTC, fira commented on html/changelogs/archive/2020-10.yml
> +  - bugfix: Readded Debug GLOB.RoleAuthority verb that was unintentionally deleted some
CL edit

2023-11-16 22:34 UTC, fira commented on code/__DEFINES/atmospherics.dm
> +GLOBAL_VAR_INIT(MAX_EXPLOSION_RANGE, 14)
```suggestion
```

2023-11-16 22:34 UTC, fira commented on code/__HELPERS/cmp.dm
> +GLOBAL_DATUM(cmp_dist_origin, /atom)
```suggestion
```

2023-11-16 22:36 UTC, fira commented on code/_globalvars/global_lists.dm
> +GLOBAL_LIST_EMPTY(z1turfs)
```suggestion
```

2023-11-16 22:36 UTC, fira commented on code/modules/shuttles/marine_ferry.dm
> +	if(!(info_tag in GLOB.s_info))
duplicate

2023-11-16 23:06 UTC, fira approved these changes

2023-11-17 08:27 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2023-11-17 08:36 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2023-11-22 20:52 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2023-11-22 22:11 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2023-11-22 22:36 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2023-11-23 14:02 UTC, fira commented
Let's TM this a few rounds quick to make sure no accident and get it in

2023-11-24 10:25 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2023-11-25 16:23 UTC, merged