Lesser drones now die upon ghosting
cmss13-devs/cmss13 pull request #4978
Opened 2023-11-20 12:40 UTC by Birdtalon

# About the pull request

https://forum.cm-ss13.com/t/ghosted-lesser-drones-should-just-die/4356/10

Lessers now die upon ghosting and are not offered to observers.

# Explain why it's good for the game

Nobody likes trying to join as xeno or see their position in the queue only to see

Lesser Drone (420)
Lesser Drone (69)

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
del: Lesser drones die upon ghosting and are not offered to observers.
/:cl:

2023-11-20 12:44 UTC, fira commented
Might make sense to not gib them if aghosting

2023-11-20 12:52 UTC, Birdtalon commented
> Might make sense to not gib them if aghosting

But where's the fun in that!?

2023-11-20 12:53 UTC, Drulikar commented
If its merely because of the queue, you have the queue message in the status panel. Clicking the join as xeno button does not force an update of your queue (unless you don't have any cached message at all).

2023-11-20 15:21 UTC, ihatethisengine commented
Do the same for facehuggers

2023-11-20 15:34 UTC, Drulikar commented
Will note they already poof after 7 mins #3886

2023-11-22 18:28 UTC, harryob requested changes

2023-11-22 18:28 UTC, harryob commented on code/modules/mob/living/carbon/xenomorph/castes/lesser_drone.dm
> +		src.gib()
```suggestion
		gib()
```

2023-11-22 19:39 UTC, harryob approved these changes

2023-11-22 21:19 UTC, merged