Re-add Small RTO Packs
cmss13-devs/cmss13 pull request #500
Opened 2022-06-18 18:15 UTC by Geevies

## About The Pull Request

Re-adds Small RTO Packs, Req has them in the Misc section, and its also in the squad req vendors, though in much smaller quantity.

## Why It's Good For The Game

It's cool and neat.

## Changelog

:cl:
add: Re-adds Small RTO Packs, Req has them in the Misc section, and its also in the squad req vendors, though in much smaller quantity.
/:cl:

2022-06-18 22:15 UTC, stanalbatross requested changes

2022-06-18 22:15 UTC, stanalbatross commented on code/game/machinery/vending/vendor_types/requisitions.dm
> +		list("Small Radio Telephone Pack", round(scale * 4), /obj/item/storage/backpack/marine/satchel/rto/small, VENDOR_ITEM_REGULAR),
put them in the backpacks section

2022-06-18 22:15 UTC, stanalbatross commented on code/game/machinery/vending/vendor_types/requisitions.dm
> +		list("Small Radio Telephone Pack", round(scale * 1), /obj/item/storage/backpack/marine/satchel/rto/small, VENDOR_ITEM_REGULAR),
ditto

2022-06-19 00:56 UTC, Hatterhat commented
shitty little radio backpack my beloved

2022-06-19 08:55 UTC, stanalbatross approved these changes

2022-06-20 07:27 UTC, fira approved these changes

2022-06-25 09:16 UTC, Nanu308 requested changes

2022-06-25 09:16 UTC, Nanu308 commented on code/game/machinery/vending/vendor_types/requisitions.dm
> +		list("Small Radio Telephone Pack", round(scale * 1), /obj/item/storage/backpack/marine/satchel/rto/small, VENDOR_ITEM_REGULAR),
Main Req only

2022-07-09 19:26 UTC, Nanu308 approved these changes

2022-07-09 19:27 UTC, merged