Project ARES: Added Tech Unlock logs & Reinforced the AI Core walls
cmss13-devs/cmss13 pull request #5006
Opened 2023-11-22 16:56 UTC by realforest2001

# About the pull request
As the title says, you can now view who unlocked techs in the ARES Interface (if you're senior command) & the walls in the core are all reinforced at a minimum.
I have also split the cameras in the core to an indivual network that is not shared with the rest of the ship, and placed a camera console to view this network in CIC, CO's Office, CE's Office and Brig Office

# Explain why it's good for the game

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
add: Added AI Core camera consoles to CE, CO and Brig offices, along with CIC.
add: Added Tech Unlock logs to ARES Interface
maptweak: Reinforced the walls in the AI Core.
/:cl:

2023-11-23 02:30 UTC, Nanu308 commented on maps/map_files/USS_Almayer/USS_Almayer.dmm
Lgtm, consider moving the CO's console that you added cuz rn its behind the safe and that doesn't look too good.

2023-11-23 07:48 UTC, realforest2001 commented on maps/map_files/USS_Almayer/USS_Almayer.dmm
Will think of a better place to put it, though it's technically ON the safe top.

2023-11-29 22:28 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2023-11-29 23:22 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2023-12-14 16:51 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2023-12-25 11:55 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2023-12-26 06:27 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2023-12-29 19:42 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-01-02 16:33 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-01-25 23:30 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-01-27 11:42 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-02-22 16:01 UTC, harryob requested changes

2024-02-22 16:01 UTC, harryob commented on code/game/machinery/ARES/ARES_interface.dm
> +			continue
don't use as anything if you're gonna istype is anyway, that's redundant

2024-03-04 10:13 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-03-07 00:46 UTC, Drulikar requested changes

2024-03-07 00:46 UTC, Drulikar commented on code/modules/cm_tech/tech.dm
> +	return FALSE
This ought to just be a var on the tech https://github.com/cmss13-devs/cmss13/blob/master/.github/guides/STYLES.md#getters-and-setters

2024-03-07 00:46 UTC, Drulikar commented on code/game/machinery/ARES/ARES_interface.dm
>  		if("delete_record")
You have not implemented deleting a record in the `switch(record.record_name)` but currently have the delete button allowed:
![image](https://github.com/cmss13-devs/cmss13/assets/76988376/8624f7de-e98c-47f3-b9fe-7e487c1b9962)

Clicking and confirming a deletion does nothing for the user for this kind of record currently.

2024-03-11 22:08 UTC, Drulikar commented on tgui/packages/tgui/interfaces/AresAdmin.js
> +const TechLogs = (props, context) => {
This page currently has no button.

2024-03-25 19:39 UTC, Drulikar requested changes

2024-03-25 19:39 UTC, Drulikar commented on tgui/packages/tgui/interfaces/AresAdmin.js
> +          </Stack.Item>
This button just crashes the panel (the remote ares panel). You don't pass admin_login as data to this.
![image](https://github.com/cmss13-devs/cmss13/assets/76988376/db0d6851-8620-4c4a-b3eb-ecb20137cda7)

2024-04-03 01:27 UTC, Drulikar approved these changes

2024-04-03 01:33 UTC, merged