DRAFT: G2 Eletroshock grenade
cmss13-devs/cmss13 pull request #5028
Opened 2023-11-25 03:18 UTC by PhantomEpicness

# About the pull request
Adds the G2 electroshock grenade, "Sonic Electric ball breaker" as mentioned in the movies or SEBB for short. It's purpose is to be a tactical option for the marines, as it deals slowdown instead of stun/damage. (unless you stand on top of it)

Only meaningful damage is to marines and especially synths, since a 1.2 Gigavolt charge is probably not healthy for bioelectrics.

Can be used as a mine as well. Uses an effect similar to boiler neuro to have finer control over balance and to prevent stacking. (still wip)

Made a PR so it can be taken a look at by maintainers.

# Explain why it's good for the game
More marine utility weapons and content, we can probably lower the amount of HEDPs slightly to balance it out aswell.

+ lore accurate af, as mentioned in the movie and the 

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl: TotalEpicness5, Triiodine, monkeyfist
add: Adds the G2 electroshock grenade
add: This grenade uses slowdowns
/:cl:

2023-11-25 03:20 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2023-11-26 21:46 UTC, Zonespace27 requested changes
Non-balance

2023-11-26 21:46 UTC, Zonespace27 commented on code/game/objects/items/explosives/grenades/marines.dm
> +		var/damage_applied = damage - dam_factor  //divides damage
reminder to remove

2023-11-26 21:46 UTC, Zonespace27 commented on code/game/objects/items/explosives/grenades/marines.dm
> +	var/time_to_live = 1 SECONDS
unique vars at the bottom

2023-11-26 21:46 UTC, Zonespace27 commented on code/game/objects/items/explosives/mine.dm
> +	desc = "A G2 electroshock grenade planted as a landmine"
```suggestion
	desc = "A G2 electroshock grenade planted as a landmine."
```

2023-11-26 21:46 UTC, Zonespace27 commented on code/game/objects/items/explosives/mine.dm
> +	new /obj/item/explosive/grenade/sebb/primed(src.loc)
not necessarily guaranteed to be a turf

2023-11-26 21:46 UTC, Zonespace27 commented on code/game/objects/items/explosives/mine.dm
> +		disarm()
what's this check for?

2023-12-11 01:04 UTC, closed without merging