GAU Buff - Shooting twice the bullet per bullet
cmss13-devs/cmss13 pull request #5065
Opened 2023-11-29 10:21 UTC by blackdragonTOW

# About the pull request

GAU historically has been a terrible option.  Quad GAU being such a meme that it's mostly a joke.  What if we doubled the ROF of the GUA?

# Explain why it's good for the game

More options other than rockets/lazers please.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
balance: GAU RoF doubled
/:cl:

2023-11-29 10:35 UTC, Birdtalon requested changes
Your entire indentation is using spaces. Please change to using tabs & address your compilation errors.

2023-11-29 10:53 UTC, blackdragonTOW commented
While doing a copy paste I think my tabs got converted to spaces, should be fixed now.

2023-12-03 03:47 UTC, Zonespace27 commented on code/modules/cm_marines/dropship_ammo.dm
> +		for(var/j = 1 to 2) //rather than halving the sleep, were doubling the bullets shot "bang"
```suggestion
		for(var/j in 1 to 2) //rather than halving the sleep, were doubling the bullets shot "bang"
```

2023-12-07 12:44 UTC, Birdtalon approved these changes

2023-12-12 11:58 UTC, merged