fix skull facepaint, masks
cmss13-devs/cmss13 pull request #5091
Opened 2023-12-01 17:59 UTC by irakligabunia

# About the pull request

it fixes the previous PR of adding the skull mask, facepaint

# Explain why it's good for the game

its a fix and sorry, i will test my PR's in the future

# Testing Photographs and Procedure
https://files.catbox.moe/6tyox1.png 

</details>

# Changelog
:cl: stalkerino
fix: fixes the skull facepaint, black mask, blue mask
/:cl:

2023-12-01 18:56 UTC, harryob approved these changes
unbelivlablele... who would have merged this??

2023-12-01 19:14 UTC, fira requested changes
please standardize names with the rest of gear while you're there

2023-12-01 19:14 UTC, fira commented on code/modules/client/preferences_gear.dm
>  	display_name = "Skull Facepaint"
```suggestion
	display_name = "Facepaint, skull"
```

2023-12-01 19:14 UTC, fira commented on code/modules/client/preferences_gear.dm
>  	display_name = "Black Skull Balaclava"
```suggestion
	display_name = "USCM balaclava, black skull"
```

2023-12-01 19:14 UTC, fira commented on code/modules/client/preferences_gear.dm
>  	display_name = "Blue Skull Balaclava"
```suggestion
	display_name = "USCM balaclava, blue skull"
```

2023-12-02 11:58 UTC, fira approved these changes

2023-12-02 21:43 UTC, merged