XvX Slash Damage Nerf
cmss13-devs/cmss13 pull request #51
Opened 2022-04-16 14:23 UTC by Geevies

## About The Pull Request

Reduces the XvX Slash Damage modifier from x2.25 to x0.75.

## Why It's Good For The Game

I noticed that XvX tends to be either: The hives run into eachother and both die damn near instantly because slash damage is super high, or, the hives keep a 4 tile barrier between eachother because TTK is so low and no one wants to engage. With this change, there should be room to skirmish and still survive.

## Changelog

:cl:
balance: The XvX Slash Damage modifier has been lowered to x0.75 from x2.25.
/:cl:

2022-04-16 14:28 UTC, Watermelon914 commented
As the original developer on XvX, the slash damage is that high because it would often take an annoying amount of time to kill a xeno who could just run off and escape.

2022-04-17 11:56 UTC, GoldenDarkness55 commented
Doesnt this make runners deal no damage? Ravs would be essentially unkillable aswell. I do agree TTK's a lil too fast now - 2.00 or 1.75 could work

2022-04-18 10:27 UTC, stanalbatross requested changes
0.75 is likely too low, tune it up a bit.

2022-04-25 08:01 UTC, Nanu308 commented
As Walter stated the opposite would become the issue where neither can kill each other due to the healthpools of xenos, put it at 1.5 instead @Geevies and we can work from that

2022-04-28 21:11 UTC, Shad0vvs approved these changes

2022-04-28 21:12 UTC, merged