Almayer AntiTheft measures.
cmss13-devs/cmss13 pull request #5100
Opened 2023-12-02 01:24 UTC by realforest2001

STOP STEALING SHIT

# About the pull request
Adds a subtype of reinforced hull for the Almayer that changes between indestructible hull and normal reinforced wall after hijack.
Uses this wall type around uniform vendors, the separation wall in the firing range and around engineering storage.

# Explain why it's good for the game

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
add: Added a new almayer hull type (heavy reinforced) which is indestructible by normal means until after hijack collision.
add: Added a new subtype of shutter that automatically opens or closes depending on security level.
maptweak: Maps both of the above around the engineering storeroom. Also adds the walls between the firing ranges and around uniform vendors.
maptweak: Manual control button for shutters over engineering storage in the CEs office.
/:cl:

2023-12-02 01:28 UTC, fira requested changes

2023-12-02 01:28 UTC, fira commented on code/modules/shuttle/dropship_hijack.dm
> +	for(var/turf/closed/wall/almayer/reinforced/temphull/hull in GLOB.hijack_bustable_hull)
as anything

would have been better to use a SSdcs signal here so other objects can use it too

2023-12-02 01:28 UTC, fira commented on code/modules/shuttles/marine_ferry.dm
> +	for(var/turf/closed/wall/almayer/reinforced/temphull/hull in GLOB.hijack_bustable_hull)
as anything

2023-12-02 01:44 UTC, fira approved these changes

2023-12-03 09:21 UTC, realforest2001 commented on code/game/machinery/doors/shutters.dm
> +/obj/structure/machinery/door/poddoor/shutters/almayer/uniform_vendors/antitheft
Yah, pre-existing overrides to damage stuff on /uniform_vendors

2023-12-03 09:23 UTC, realforest2001 commented
> i think making indestructible walls on engineering may not be a good idea. adding too much mechanical protection makes MPs a lil useless dont you think ? . the best would be first to make sure only MTs and CE have access to the Storage room and maybe using reinforced Doors to prevent easy hacking

It already has reinforced doors and MT/CE access only. Insufficient to deter people rushing it at round start, so here we are.

2023-12-03 20:22 UTC, zzzmike commented
> adding too much mechanical protection makes MPs a lil useless dont you think ?

As someone with a lot of MP hours, I'm not concerned at all with this change. There is so, so much more to do.

2023-12-06 15:58 UTC, Nanu308 approved these changes
Mapping seems fine

2023-12-07 20:55 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2023-12-11 01:14 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2023-12-12 11:34 UTC, merged