Modifies and Re-Enables Shivas Snowball
cmss13-devs/cmss13 pull request #5113
Opened 2023-12-03 15:20 UTC by Steelpoint

# About the pull request

This PR re-enables Shivas Snowball, placing it back in to the rotation and allowing it to be played.

This PR also makes several modifications to the map to allow this and fix the issues that resulted in its prior removal. Primarily in relocating the South East LZ to the South West. Overall this results in the eastern half of the map being xeno territory.

The comms towers are also relocated into more sane locations. 

# Explain why it's good for the game

Shivas Snowball is not a bad map, it just needed some changes to allow it to function within the current game mechanics (mainly how comms towers work). I hope these changes will return Shivas to a minimum level of playability. 

# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog
:cl:
mapadd: Shivas Snowball is back in rotation. 
maptweak: The south east landing zone on Shivas has been relocated to the south west, the dig site in the south west has been similarly relocated. 
maptweak: Comms towers on Shivas have been placed in more consistent locations near each other, instead of some of them being on the opposite sides of the map from each other. 
/:cl:

2023-12-03 15:52 UTC, Steelpoint commented
I'm open to making alterations to the positions of the comms towers, I've mostly just retained the current ones minus the removal of the far eastern ones. 

You could argue that despite the comms towers mostly spawning on the western half of the map, the larger distances between the 1 towers and 2 towers means its still quite viable for xenos to contest at least. oen.

2023-12-16 04:51 UTC, Nanu308 requested changes
Double check places that contain multitile sprites that change depending on direction such as double doors in the center, that is offset wrong it seems.

You need to make a smoother transition between the areas ya pasted into each other for the caves and snow SE by the pink house, also to the SW. As right now it comes off as really unnatural looking curves and bends.

![bilde](https://github.com/cmss13-devs/cmss13/assets/59782240/cd8844f7-dfdf-47c4-b6c5-a0939760d7f6)
Check over your vehicle blockers, you have them here, but not west/other areas that can be broken down.

2023-12-17 06:31 UTC, Steelpoint commented
Further changes made, I think.

2023-12-25 07:08 UTC, Nanu308 approved these changes

2023-12-25 07:08 UTC, Nanu308 commented on maps/map_files/Ice_Colony_v3/Shivas_Snowball.dmm
Design improvement seems good and hopefully this makes central colony see more play than before and less of direct lines into the hive, if map still has further issues it can be tweaked or taken out of rotation again but gonne need some live data for that.

Lgtm.

2023-12-26 06:07 UTC, Steelpoint commented
If additional mapping balance changes are needed for game-flow I'd be happy and willing to make those changes, but as noted by Nanu we'd need to see how the game goes with the map first.

2024-01-02 17:06 UTC, merged