fixes telepathically removing accessories
cmss13-devs/cmss13 pull request #513
Opened 2022-06-19 12:00 UTC by stanalbatross

## About The Pull Request

bugfix

## Why It's Good For The Game

## Changelog

:cl:
fix: you can no longer remove accessories from uniforms from unlimited range after you drop it/throw it away
/:cl:

2022-06-19 15:07 UTC, Geevies requested changes

2022-06-19 15:07 UTC, Geevies commented on code/modules/clothing/clothing_accessories.dm
> +	if(!istype(usr, /mob/living))
```suggestion
	if(!isliving(usr))
```

2022-06-19 15:07 UTC, Geevies commented on code/modules/clothing/clothing_accessories.dm
> +	if(!(usr.Adjacent(src)))
```suggestion
	if(!usr.Adjacent(src))
```

2022-06-19 15:11 UTC, Geevies approved these changes

2022-06-21 06:31 UTC, Nanu308 commented
Put Ckey next to the CL at the top, so people can see who added it ingame

2022-06-22 20:31 UTC, stanalbatross commented
> Put Ckey next to the CL at the top, so people can see who added it ingame

🤓

2022-06-24 00:31 UTC, merged