Oppressor cooldown changes
cmss13-devs/cmss13 pull request #5154
Opened 2023-12-07 12:51 UTC by InsaneRed

# About the pull request

Lowers the oppressor tail_abudct (the hook) to 15 seconds of cooldown and makes the windup faster.

Lowers the time needed for the tailsweep windup from 2 to 1
Makes punch shave off cooldown from the abudct for 5 seconds 

All have been tested but i would like this to get testmerged first so i can actually see the results in game, nothing is set in stone and i want to edit this further so the cd / cd reduction isnt too powerful, they're just numbers ive decided were good enough to atleast make the caste decent for the time being.

# Explain why it's good for the game

Oppressor has been a snoozer strain for a while now where you cast an ability, and IF it hits you get to play the game otherwise you wait 20 seconds and thats just not fun. Especially for what the ability is, a 20 second cooldown is not worth it.

 I've talked with a few people that all agree that the downtime for what you "could" do with oppressor is not worth it. And i have to agree with them, the caste feels boring to play and its basically half dead due to the amnout of downtime you have between abilities compared to how everything else works. The idea of this is to make it so its not busted out of its brain but atleast not an observer++ strain so you can feel more involved in the gameplay.

# Testing Photographs and Procedure
</details>

# Changelog

:cl:
balance: Oppressor tail abduct changed to 15 seconds and lowers the windup. Lowers the tail sweep windup from 2 to 1
balance:  Changes around the punch effect so that instead of having to meet demonic standards, you only need to punch to lower your tail/hook on oppressor.
/:cl:

2023-12-07 13:37 UTC, Birdtalon requested changes

2023-12-07 13:37 UTC, Birdtalon commented on code/modules/mob/living/carbon/xenomorph/abilities/praetorian/praetorian_powers.dm
> +	if(abduct_action && abduct_action.action_cooldown_check())
`if(abduct_action && !abduct_action.action_cooldown_check())`

2023-12-07 13:37 UTC, Birdtalon commented on code/modules/mob/living/carbon/xenomorph/abilities/praetorian/praetorian_powers.dm
> +	if(tail_lash_action && tail_lash_action.action_cooldown_check())
`if(tail_lash_action && !tail_lash_action.action_cooldown_check())`

2023-12-07 18:35 UTC, Birdtalon approved these changes
Will need balance approval. But I think a good change to make Oppressor have much less downtime throughout the game and make missing a hook less punishing.

2023-12-08 00:54 UTC, Zonespace27 requested changes

2023-12-08 00:54 UTC, Zonespace27 commented on code/modules/mob/living/carbon/xenomorph/abilities/praetorian/praetorian_abilities.dm
> -	var/windup = 2
Revert this and it's good to go for a TM

2023-12-08 22:53 UTC, Zonespace27 approved these changes
been fine from what i've seen

2023-12-08 23:01 UTC, merged