Ports Mapping Backend updates
cmss13-devs/cmss13 pull request #5165
Opened 2023-12-08 13:28 UTC by fira

# About the pull request

Updates most of mapping backend to /tg/ current:
* Replaces completely map reader which now has explicit TGM support
* Replaces completely reservations backend
* Grafts and updates some missing procs in SSmapping and Shuttles, notably for reservations
* Updates nightmare, map templates, interiors, etc, to match new mapper/reservations code

This shouldn't change much to the game as is, but is meant as a stepping stone toward new features such as planecube that depend on updated mapping code.

Very Testmerge-worth

# Testing
 - [x] General map loading of Ship & Ground
 - [x] Dropship loading and flight
 - [x] Fultons reservation launching
 - [x] Lifeboats launching
 - [x] Vehicle Interiors instanciation
 - [x] Interior reservations freeing
 - [x] Tents templates placement
 - [x] Nightmare inserts loading
 - [ ] Other maps than LV-624
 - [ ] Maploading admin verbs
 - [ ] Mass screenshot verb

# Potential TODO
 - [ ] Find a better cordon turf than outer almayer hull, it looks ugly with eg fultons

# Changelog

:cl:
code: Updated mapping backend from /tg/ upstream.
/:cl:

2023-12-10 11:15 UTC, fira commented
Currently removes Weakrefs for used_turfs reservations because they weren't in /tg/ backend

This doesn't seem to trip C&D so.... I don't know

2023-12-14 13:36 UTC, Huffie56 commented
could it be fixing those two issues?
https://github.com/cmss13-devs/cmss13/issues/2798
https://github.com/cmss13-devs/cmss13/issues/2799

2023-12-15 09:20 UTC, fira commented
#2798 is probably rather an issue with the verb that should our TGMC/CM snowflake delete argument for this, we previously had this issue with nightmare

#2799 could be an old icon issue that happened on old server due to docker container not packing icons

Both are very old issues so hard to tell

2023-12-29 18:08 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-01-02 12:33 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-01-14 11:21 UTC, mullenpaul commented
I'll review this later - I need mapping updated for some of my projects

2024-01-14 21:59 UTC, mullenpaul approved these changes
I've had a look at the code and it generally looks fine. There is a LOT here - how has this been tested? We should run a TM at some point

2024-01-14 21:59 UTC, mullenpaul commented on code/modules/shuttle/shuttles/trijent_elevator.dm
> -/obj/docking_port/mobile/trijent_elevator/linkup(datum/map_template/shuttle/template, obj/docking_port/stationary/dock)
I'm not sure if this should be removed. Was it moved to another proc?

2024-01-18 16:18 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-01-18 23:45 UTC, dadlips commented
I believe this TM has introduced a bug with the dropships where the aft door stays LOCKED, and can't be unlocked from any console. Forest mentioned the dropships seem to think they're in space all the time, and when one took off I did see some space tile oddities I hadn't before.

2024-01-19 20:13 UTC, Vicacrov commented
Tested it on local (start round, simply spawn in):

1. South dropship doors are locked by default, cannot be unlocked
2. The corners of the dropships have space tiles

![image](https://github.com/cmss13-devs/cmss13/assets/49321394/04869054-36a4-477f-af7f-6c44f0ba4e83)

2024-01-23 10:46 UTC, Drulikar requested changes
Please address issues with the dropships (but I believe earlier comments also isolated it to soley this PR)

![image](https://github.com/cmss13-devs/cmss13/assets/76988376/33ac4fa9-ccc9-43a0-ab4f-e66a5cfec321)

Nothing immediately sticks out to me as the issue, but if you can't figure it out I can dig into it more later.

2024-01-23 13:45 UTC, spookydonut approved these changes

2024-01-23 13:48 UTC, Drulikar requested changes
Can also confirm issue 5504 is from this PR on big red (atleast on 515)
![image](https://github.com/cmss13-devs/cmss13/assets/76988376/e217137b-48c9-407a-a383-8f3f0a691c1d)

2024-01-23 13:48 UTC, Drulikar commented on code/game/world.dm
These procs aren't updating the zlevel's bounds resulting in those values remaining as 100x150x1 resulting in bogus values for mass screenshot.

2024-02-21 19:30 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-02-21 19:30 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-02-22 15:46 UTC, harryob approved these changes

2024-02-22 15:55 UTC, merged