Newpizzacutter
cmss13-devs/cmss13 pull request #5178
Opened 2023-12-10 07:21 UTC by Mensla

# About the pull request

# Explain why it's good for the game

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

![image](https://github.com/cmss13-devs/cmss13/assets/102622741/8d8e3232-0f1f-49cc-b897-d94ed0b365cd)
![image](https://github.com/cmss13-devs/cmss13/assets/102622741/590cd27f-b51b-4878-b9a5-6d3427303185)

</details>

# Changelog

:cl:
add: Added new pizza cutter sprites.
/:cl:

2023-12-10 07:28 UTC, Mensla commented
Sorry for the unspaced PR name

2023-12-10 21:33 UTC, fira requested changes
make one subtype of another, that'll be easier to use and more compact
bonus points if you also integrate the old cutter into that
also you could have "wood" matter in the wooden one but that's a meme 👌

2023-12-11 19:39 UTC, Birdtalon commented on code/game/objects/items/tools/kitchen_tools.dm
> +	matter = list("metal" = 12000)
12000 metal isn't that quite a lot?

2023-12-11 19:49 UTC, Mensla commented on code/game/objects/items/tools/kitchen_tools.dm
> +	matter = list("metal" = 12000)
Same as the kitchen knives

2023-12-11 20:22 UTC, Birdtalon commented on code/game/objects/items/tools/kitchen_tools.dm
> +	matter = list("metal" = 12000)
Damn must be quadrillion folded steel.

2023-12-11 23:40 UTC, Mensla commented
I created subtypes (?) and I think they're done correctly. 

Moved the meme pizza cutter under kitchen tools for organization.

2023-12-12 10:01 UTC, Birdtalon commented
> I created subtypes and I think they're done correctly (?).
> 
> Moved the meme pizza cutter under kitchen tools for organization.
> 
> I have zero idea why the compile maps is failing...

maps/map_files/FOP_v3_Sciannex/sprinkles/30.pizzatime.dmm:308:error: undefined type: /obj/item/weapon/pizza_cutter
maps/map_files/FOP_v3_Sciannex/sprinkles/30.pizzatime.dmm:312:error: unknown type

2023-12-12 12:15 UTC, BadAtThisGame302 commented on code/game/objects/items/tools/kitchen_tools.dm
> +	desc = "A circular blade using for cutting pizzas. This one has an authetnic wooden handle."
authentic*

2023-12-12 12:16 UTC, BadAtThisGame302 commented on code/game/objects/items/tools/kitchen_tools.dm
> +	desc = "A circular blade using for cutting pizzas. This one has a cheap plastic handle."
I also think used is better than using here, using doesn't make much sense grammar wise.

2023-12-12 12:16 UTC, BadAtThisGame302 commented on code/game/objects/items/tools/kitchen_tools.dm
> +	desc = "A circular blade using for cutting pizzas. This one has an authetnic wooden handle."
Also the used/using issue as I said above.

2023-12-14 02:50 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2023-12-17 13:42 UTC, nauticall approved these changes

2023-12-26 16:13 UTC, Birdtalon commented
Resolve conflicts please this is ready to merge otherwise.

2024-01-10 01:04 UTC, closed without merging