Modify organization for vendors of the Rifleman and the Team Leader role.
cmss13-devs/cmss13 pull request #5187
Opened 2023-12-11 12:04 UTC by Huffie56

# About the pull request
added binocular to rifleman because he access to the higher tier of it already.
added the advance tier to team leader because their is no reason for rifleman to have it and not their leader.
added the section because it's a section other job have to store engi item(SL and comtech)

# Explain why it's good for the game
better logic on what items are available for marines for binoculars change.
the new section is on other job so it will probably make it better to orient ourself in vendors.
the two new item because i think they aren't OP and are under-used items that some marine might take if they can buy them.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
qol: creating a new section called engineering supplies for the rifleman and the team leader.
balance: added standard binocular to the rifleman vendor at a cost of 5.
balance: added Range Finder and Laser Designator binoculars to Team leader at a cost of 10 and 20.
balance: added ES-11 Mobile Fuel Canister and ME3 hand welder to Team leader and rifleman for 5 each.
/:cl:

2023-12-16 05:31 UTC, Zonespace27 requested changes

2023-12-16 05:31 UTC, Zonespace27 commented on code/game/machinery/vending/vendor_types/squad_prep/squad_rifleman.dm
> +		list("ME3 hand welder", 5, /obj/item/tool/weldingtool/simple, null, VENDOR_ITEM_REGULAR),
Capitalize

2023-12-16 05:31 UTC, Zonespace27 commented on code/game/machinery/vending/vendor_types/squad_prep/squad_tl.dm
> +		list("ME3 hand welder", 5, /obj/item/tool/weldingtool/simple, null, VENDOR_ITEM_REGULAR),
capitalize

2023-12-16 07:51 UTC, Huffie56 commented on code/game/machinery/vending/vendor_types/squad_prep/squad_rifleman.dm
> +		list("ME3 hand welder", 5, /obj/item/tool/weldingtool/simple, null, VENDOR_ITEM_REGULAR),
fixed

2023-12-16 07:51 UTC, Huffie56 commented on code/game/machinery/vending/vendor_types/squad_prep/squad_tl.dm
> +		list("ME3 hand welder", 5, /obj/item/tool/weldingtool/simple, null, VENDOR_ITEM_REGULAR),
fixed

2023-12-30 10:31 UTC, Drulikar approved these changes
Code changes look fine.

/obj/item/tool/weldingtool/simple looks really dumb just colored red; but thats all Stan did for it...

2023-12-30 10:39 UTC, merged