Ds doorgun no longer hits cades
cmss13-devs/cmss13 pull request #5209
Opened 2023-12-12 21:49 UTC by cuberound

Makes DS doorgun able to shoot over cades

# Explain why it's good for the game

right now you can not use DS doorgun without taking out the whole FOB. that is kinda dumb considering that it can not be moved. makes doorgun somewhat viable, at least it will not grief marines

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
balance: DS doorgun can shoot over cades
/:cl:

2023-12-12 22:00 UTC, cuberound commented on code/datums/ammo/bullet/special_ammo.dm
> +	. = ..()
propably... I was not shure, I am not too experienced with dream maker

2023-12-13 14:47 UTC, TheGamerdk commented on code/datums/ammo/bullet/special_ammo.dm
> +	. = ..()
yeah this proc doesn't do anything

2023-12-14 13:29 UTC, fira requested changes

2023-12-14 13:29 UTC, fira commented on code/datums/ammo/bullet/special_ammo.dm
> +	flags_ammo_behavior = AMMO_IGNORE_COVER
```suggestion
	flags_ammo_behavior = AMMO_BALLISTIC | AMMO_IGNORE_COVER
```
flag that was on /datum/ammo/bullet and overriden here

2023-12-15 09:12 UTC, fira approved these changes

2023-12-16 05:34 UTC, merged