Adds  antispam check similar to what sentrygun has to m56d
cmss13-devs/cmss13 pull request #5246
Opened 2023-12-18 14:38 UTC by cuberound

# About the pull request

(doing this on a bench so it will need some cleanup sorry for that) adds check to placing the m56d that checks if there is another m56d in surounding area to prevent mg spam, numbers and stuff are placeholder it will get cleaned up ( I will be happy if you help me with it)

m56d spam has come to be an issue recently, I am part of it and do not want it to end up like omni sentryguns did (compleatly useless garbage) so I try to take better aproach to the balance then just AP or firerate nerf that would not solve the issue

# Explain why it's good for the game

prevents m56d massing and encorages m56d users to spread out and cover diferent chokes instead of hosing down on and obliterating anyone who comes in the way

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
balance: m56d can not be placed within two tiles of another one
/:cl:

2023-12-18 18:20 UTC, Birdtalon requested changes

2023-12-18 18:20 UTC, Birdtalon commented on code/modules/cm_marines/smartgun_mount.dm
> +	var/can_be_near_defense = FALSE
This variable seems pointless if all you're going to do is check `if(!can_be_near_defense)` and it never changes may as well not have it and remove those checks also.

2023-12-18 18:20 UTC, Birdtalon commented on code/modules/cm_marines/smartgun_mount.dm
> +			if(istype(machine, var/obj/structure/machinery/m56d_hmg) || istype(machine, var/obj/structure/machinery/m56d_post)
Missing `)` and check your syntax of `istype()`

https://www.byond.com/docs/ref/#/proc/istype

2023-12-18 18:20 UTC, Birdtalon commented on code/modules/cm_marines/smartgun_mount.dm
> +			if(istype(machine, var/obj/structure/machinery/m56d_hmg) || istype(machine, var/obj/structure/machinery/m56d_post)
Missing `)` and `istype()` as above.

2023-12-19 15:58 UTC, cuberound commented
is 2 enough or should I increase?

2023-12-19 19:27 UTC, ihatethisengine commented
I personally believe you should make it at least 5, 2 is definitely not enough.

2023-12-24 01:13 UTC, Drulikar requested changes
This works except you can skip the check by placing a mount within the not allowed radius and then place the gun on the mount. So the same check has to apply to `m56d_post` as well.

2023-12-24 21:38 UTC, Drulikar requested changes

2023-12-24 21:38 UTC, Drulikar commented on code/modules/cm_marines/smartgun_mount.dm
> +		for(var/obj/structure/machinery/machine in urange(MG.defense_check_range, loc,1))
```suggestion
		for(var/obj/structure/machinery/machine in urange(MG.defense_check_range, loc, TRUE))
```

2023-12-24 21:38 UTC, Drulikar commented on code/modules/cm_marines/smartgun_mount.dm
> +	var/defense_check_range = 5
Autodoc
```suggestion
	///The distance this has to be away from other m56d_hmg and m56d_post to be placed.
	var/defense_check_range = 5
```

2023-12-24 21:38 UTC, Drulikar commented on code/modules/cm_marines/smartgun_mount.dm
>  	var/has_mount = FALSE // Indicates whether the M56D will come with its folding mount already attached
Autodocc
```suggestion
	///How many rounds are in the weapon. This is useful if we break down our guns.
	var/rounds = 0
	///Indicates whether the M56D will come with its folding mount already attached
	var/has_mount = FALSE 
```

2023-12-25 20:26 UTC, Drulikar approved these changes
Code looks fine. Added to TM so we can get more of an idea of its balance. Undraft when you are happy with it.

2023-12-26 15:39 UTC, fira reviewed
i don't think you need to include the POSTS in your range check that's just gonna be confusing

2023-12-27 18:34 UTC, cuberound commented
> i don't think you need to include the POSTS in your range check that's just gonna be confusing
you in fact do, as the post is also m56d just before you use screwdrive to finish it into the stage when it can shoot, so without it you can place down two posts, screw one finished and be unable to finish second one or interact with it at all/ be able to finish it and bypass the checks

2024-01-01 08:50 UTC, Drulikar commented
If it needs tweaking in the future it can be handled then; but this seems reasonable to me when already sentries have a similar mechanic.

2024-01-01 08:58 UTC, merged