New Yautja sounds and pain screams
cmss13-devs/cmss13 pull request #525
Opened 2022-06-19 22:29 UTC by Joelampost

## About The Pull Request

## Why It's Good For The Game
Adds pred pain screams (for some reason preds never have had them) also adds more soul to the game in the form of pred emotes.

## Changelog

:cl:
soundadd: Added Yautja pain screams 
soundadd: Yautja can now mimic xenomorphs with *alienhelp and *aliengrowl 
soundadd: Yautja now have three new soulful emotes to use to create a sense of dread: *click2, *overthere and *comeonout
soundadd: added a new sound for claiming trophies *roar2 

/:cl:
*click2 emotes 

https://user-images.githubusercontent.com/104737973/174502551-8b2ab46f-5dd8-4787-b231-f13c22920a79.mp4

https://user-images.githubusercontent.com/104737973/174502552-beeebad5-71a1-42f6-9912-4aafcfa43f62.mp4

*overthere

https://user-images.githubusercontent.com/104737973/174502605-02bd6469-4219-4eac-9361-c38779908ab0.mp4

*roar2

https://user-images.githubusercontent.com/104737973/174502640-6dae95ba-d659-4f90-96d0-da40327da793.mp4

*comeonout

https://user-images.githubusercontent.com/104737973/174502662-ccf5e68a-bbed-43fe-bd70-77b9cca20c2c.mp4

2022-06-21 06:29 UTC, Nanu308 commented
Put Ckey next to the CL at the top, so people can see who added it ingame

2022-06-24 04:21 UTC, Carnage068 commented
Ngl these are really good sounds. Imo at least.

2022-06-25 21:27 UTC, stanalbatross requested changes

2022-06-25 21:27 UTC, stanalbatross commented on code/modules/cm_preds/yaut_procs.dm
> +					emote("roar2")
it would be cool if you made this a random chance for any of the roars

2022-06-25 21:27 UTC, stanalbatross commented on code/modules/mob/living/carbon/human/emote.dm
> +					playsound(loc, 'sound/voice/pred_pain1.ogg', 50.1)
```suggestion
					playsound(loc, 'sound/voice/pred_pain1.ogg', 50)
```
🙄

2022-06-25 21:27 UTC, stanalbatross commented on code/modules/mob/living/carbon/human/emote.dm
> +					playsound(loc, 'sound/voice/pred_scream1.ogg', 50,1)
```suggestion
					playsound(loc, 'sound/voice/pred_scream1.ogg', 50, 1)
```

2022-06-25 21:27 UTC, stanalbatross commented on code/modules/mob/living/carbon/human/emote.dm
> +		if ("roar2")
```suggestion
		if("roar2")
```
spaces between if () is bad practice. Fix this.

2022-06-25 21:27 UTC, stanalbatross commented on code/modules/mob/living/carbon/human/emote.dm
> +					if(rand(0,100) < 50)
use an if prob here

2022-06-25 21:27 UTC, stanalbatross commented on code/modules/mob/living/carbon/human/emote.dm
> +					if(rand(0,100) < 50)
same

2022-06-25 21:27 UTC, stanalbatross commented on code/modules/mob/living/carbon/human/emote.dm
> +					if(rand(0,100) < 50)
same

2022-06-25 21:31 UTC, SirVerbsAlot commented
dont like the voicelines, these really sound kinda weird and hearing a pred say motherfucker is 😂 material. the rest of the noises are cool af though

2022-06-25 21:39 UTC, Joelampost commented
He is not saying it, he is mimicking a marine.

> dont like the voicelines, these really sound kinda weird and hearing a pred say motherfucker is 😂 material. the rest of the noises are cool af though
H

2022-06-27 13:36 UTC, stanalbatross commented on code/modules/mob/living/carbon/human/emote.dm
> +		if ("alienhelp")
```suggestion
		if("click2")
			if(Pred && src.loc)
				m_type = 1
				spawn(2)
					if(prob(50))
						playsound(src.loc, 'sound/voice/pred_click3.ogg', 50)
					else
						playsound(src.loc, 'sound/voice/pred_click4.ogg', 50)
		if("aliengrowl")
			if(Pred && src.loc)
				m_type = 1
				spawn(2)
					if(prob(50))
						playsound(src.loc, 'sound/voice/alien_growl1.ogg', 50)
					else
						playsound(src.loc, 'sound/voice/alien_growl2.ogg', 50)
		if("alienhelp")
```

2022-06-27 14:36 UTC, stanalbatross approved these changes

2022-06-27 14:36 UTC, merged