added a new panic emote
cmss13-devs/cmss13 pull request #5273
Opened 2023-12-21 20:30 UTC by Cthulhu80

# About the pull request

Created a new emote called panic, it's very similar to scream and inherits virtually all of its properties and methods however the ogg files are of course different. Also added a forced panic emote whenever a warrior lunges and grabs a human mob.

# Explain why it's good for the game

Initially I just wanted to add a forced a scream emote whenever a warrior lunged at a human mob, but I sort of found the existing scream ogg sounds to be kind of lack luster. However, they are iconic in their own right and removing them or modifying them would be a detriment to the game. I chose to create a new emote entirely rather than adding audio files to the existing one. The emote which is similar to scream but the sounds are more "authentic" and erm, immersive. So far it's just two sounds for each gender but this will be changed once I find more audio files to add. 

# Changelog

:cl:
add: added a new panic emote, as well as associated audio files.
code: human mobs now have a forced panic emote whenever they get lunged at and then grabbed by a warrior.
/:cl:

2023-12-21 20:33 UTC, Drulikar requested changes

2023-12-21 20:33 UTC, Drulikar commented on code/modules/mob/living/carbon/human/emote.dm
> +			return get_sfx("pred_pain")
This is inaccessible code.

2023-12-21 21:41 UTC, Drulikar requested changes
Already discussed on discord, but just for parity here:
- The screams need to be much shorter
- The female screams seem especially out of place
- There should be no delay to the start of the clips (trim dead space so when you play the sfx it immediately makes the noise rather than a second later or whatever)

2023-12-21 23:37 UTC, Cthulhu80 commented
> Already discussed on discord, but just for parity here:
> 
> * The screams need to be much shorter
> * The female screams seem especially out of place
> * There should be no delay to the start of the clips (trim dead space so when you play the sfx it immediately makes the noise rather than a second later or whatever)

Put the second sound into the scream list, otherwise removed all the other ones and just have the regular scream emote when the warrior lunges.

2023-12-22 01:09 UTC, Drulikar approved these changes

2023-12-22 08:04 UTC, Birdtalon commented
Can you put in your changelog that you're adding a new sound?

2023-12-22 12:18 UTC, Cthulhu80 commented
> Can you put in your changelog that you're adding a new sound?

Done

2023-12-23 23:06 UTC, merged