Yautja Actions Update (/QOL changes)
cmss13-devs/cmss13 pull request #5294
Opened 2023-12-25 00:58 UTC by BeagleGaming1

# About the pull request

This was hell

Action sprites from https://github.com/Cosmic-Overlord/TerraGov-Marine-Corps/pull/206

# Explain why it's good for the game

Ease of use

# Changelog

:cl: BeagleGaming1, Mr.Crowford
add: Added Yautja action buttons
qol: Added a keybind to control falcon drones
qol: Thwei crystals and healing capsules say how much time until off cooldown
code: Yautja keybinds now redirect to action buttons
code: Changed thwei crystals and healing capsules to cooldowns instead of timers
code: Miscellaneous Yautja-related code cleanup
/:cl:

2023-12-28 17:45 UTC, Cthulhu80 commented on code/modules/cm_preds/yaut_actions.dm
> +			usr.emote(initial(path.key))
https://github.com/cmss13-devs/cmss13/pull/3101

2024-01-01 08:12 UTC, Drulikar requested changes

2024-01-01 08:12 UTC, Drulikar commented on code/modules/cm_preds/yaut_actions.dm
> +/datum/action/predator_action/bracer/control_falcon_drone
Shouldn't this also require visors?

2024-01-01 08:12 UTC, Drulikar commented on code/modules/cm_preds/yaut_weapons.dm
>  	var/list/tether_effects = apply_tether(user, src, range = 6, resistable = FALSE)
This from dropping a combistick results in `/datum/effects/tethering/proc/set_tethered(datum/effects/tethered/T)` throwing `Exception has occurred: Cannot execute null.beam().` when self destructing
![image](https://github.com/cmss13-devs/cmss13/assets/76988376/327ea846-290a-4b72-8942-b07950c0b48d)

2024-01-02 12:38 UTC, nauticall approved these changes
sprites good

2024-01-02 20:34 UTC, Drulikar approved these changes
All issues appear resolved and nothing else sticks out to me as needing changing.

The only thing else you may consider is using hide for the actions instead of add/remove so their positions are more consistent.

2024-01-03 20:30 UTC, merged