new synthtool: autocompressor
cmss13-devs/cmss13 pull request #531
Opened 2022-06-20 14:21 UTC by stanalbatross

## About The Pull Request

Added a machine that automatically does cpr to the synthtool vendor

## Why It's Good For The Game

new synthtool good, can be used to help out synths when they don't have anyone to help them with CPR

## Changelog

:cl:
add: added the autocompressor, a new synthtool that automatically does CPR. Runs on an internal battery, can be attached to people just by clicking on them. Has a high risk of breaking bones if used alongside a person performing CPR.
/:cl:

2022-06-20 16:00 UTC, JohnDoe50974 commented
Based

2022-06-25 18:09 UTC, MiniMeatwad commented
Thought it said air compressor, and that you were just filling people's lungs with air.

2022-06-27 10:36 UTC, Shad0vvs requested changes
> tools/bootstrap/.cache/node-v14.16.1-x64/node.exe

Remove...

2022-06-27 10:48 UTC, Shad0vvs approved these changes

2022-06-27 10:58 UTC, Shad0vvs requested changes
revive_grace_period = 4820
It's too strong on corpses going PAST the revive cap.

2022-06-27 11:23 UTC, stanalbatross commented
> revive_grace_period = 4820 It's too strong on corpses going PAST the revive cap.

yeah I did not intend for this to happen, gonna fix

2022-06-29 12:31 UTC, stanalbatross commented
> revive_grace_period = 4820 It's too strong on corpses going PAST the revive cap.

we were just reading the vvs wrong, doing cpr also does this as revive_grace_period never goes down, it is only compared to timeofdeath

2022-07-23 18:56 UTC, Shad0vvs commented on code/game/objects/items/tools/experimental_tools.dm
> +		message_admins("killed process off non loc")
```suggestion
```

2022-07-23 19:21 UTC, Shad0vvs commented on code/game/objects/items/tools/experimental_tools.dm
> +			var/suff = min(H.getOxyLoss(), 10) //Pre-merge level, less healing, more prevention of dieing.
```suggestion
			var/suff = min(H.getOxyLoss(), 10) //Pre-merge level, less healing, more prevention of dying.
```

2022-07-23 19:22 UTC, Shad0vvs commented
You wanted me to let you know to prevent putting it on perma people.

2022-07-23 20:15 UTC, Shad0vvs approved these changes

2022-07-23 20:15 UTC, merged