Fixes fire alarm closing shutters for adjacent area doors
cmss13-devs/cmss13 pull request #5325
Opened 2023-12-28 00:04 UTC by Cthulhu80

# About the pull request

This looks intentional.... is it even a bug? #4880.

# Explain why it's good for the game

having all adjacent shutters close in a given area just looks a bit silly. 

<img width="994" alt="shutters" src="https://github.com/cmss13-devs/cmss13/assets/122310258/945cc8f8-7180-470b-a199-95899855d4c6">

# Changelog

:cl:
fix: fixes adjacent shutters closing after a fire alarm is pulled.
/:cl:

2023-12-28 08:44 UTC, Huffie56 commented
so yes commenting out looking out work for some situation but on other we need code to look out for adjacent shutter to close.
![image](https://github.com/cmss13-devs/cmss13/assets/117036822/fba43120-f2a5-487c-9259-55df4cb60b45)
let's imagine an extreme example where red is "area A"(red)and is surrounded by other areas with their shutter at their access point(orange).
when i push the fire alarm in area A code need to look to adjacent area to close orange shutter.

2023-12-28 11:54 UTC, Cthulhu80 commented
Said this on discord but, maybe instead we can instead have it so that all connected fire shutters to any adjacent shutter close as well. That way it doesn't look funky and closes all the nearby room shutters.

2023-12-28 12:13 UTC, Drulikar requested changes

2023-12-28 12:13 UTC, Drulikar commented on code/game/machinery/doors/firedoor.dm
> +	// 		areas_added += A
```suggestion
```
Just remove it.

2023-12-28 12:13 UTC, Drulikar commented on code/game/machinery/doors/firedoor.dm
>  	areas_added = list(A)
Refactor out the need for the list `areas_added`

2023-12-29 18:08 UTC, fira approved these changes
probably intended for atmos so who cares

2023-12-30 05:18 UTC, Drulikar requested changes
Works but it is likely desirable to just remove hallways fire alarms because there's just going to still be situations like this where the hallway is just a gigantic region so it having a firealarm affects things super far away - and even then it doesn't share fire doors that are shared by a different area: 
![image](https://github.com/cmss13-devs/cmss13/assets/76988376/6ca476c4-1332-479f-8a6a-6aee197387e9)
![image](https://github.com/cmss13-devs/cmss13/assets/76988376/b8db2d68-5030-41d5-885a-5f827ef4605a)

Technically in this situation it ought to have closed the doors in "Port Fore Lifeboat Fuel Pump" and "Medical Upper" (and maybe others because this area spans a good distance) to be a proper fire barrier. So if you opt to not remove hallway firealarms, then maybe consider adding the old code back but have it fire alarm that entire zone (but no further than it?) but I really do not expect this to work well. Technically the old code would have handled this situation better but obvious that has its own flaws. Alternatively we break up the areas more, and we add a way for firedoors to be linked to multiple areas in sets.

Also the fire alarms themselves don't change state visually in any way (most code bases change them to a flashing red state). We do have a state for this, just this code isn't setting it. 
![image](https://github.com/cmss13-devs/cmss13/assets/76988376/38237f99-fd27-4478-849a-c1ee546e8f3c)

2023-12-30 13:17 UTC, Cthulhu80 commented
> Works but **it is likely desirable to just remove hallways fire alarms** because there's just going to still be situations like this where the hallway is just a gigantic region so it having a firealarm affects things super far away - and even then it doesn't share fire doors that are shared by a different area: 
> 
> ![image](https://github.com/cmss13-devs/cmss13/assets/76988376/6ca476c4-1332-479f-8a6a-6aee197387e9)
> 
> ![image](https://github.com/cmss13-devs/cmss13/assets/76988376/b8db2d68-5030-41d5-885a-5f827ef4605a)
> 
> 
> 
> Technically in this situation it ought to have closed the doors in "Port Fore Lifeboat Fuel Pump" and "Medical Upper" (and maybe others because this area spans a good distance) to be a proper fire barrier. So if you opt to not remove hallway firealarms, then maybe consider adding the old code back but have it fire alarm that entire zone (but no further than it?) but I really do not expect this to work well. Technically the old code would have handled this situation better but obvious that has its own flaws. Alternatively we break up the areas more, and we add a way for firedoors to be linked to multiple areas in sets.
> 
> 
> 
> **Also the fire alarms themselves don't change state visually in any way (most code bases change them to a flashing red state). We do have a state for this, just this code isn't setting it.** Be sure it changes the state of all firealarms in an area if its possible for multiple firealarms to exist in a single area, and be sure it returns back to whatever code green/blue/red state. 
> 
> ![image](https://github.com/cmss13-devs/cmss13/assets/76988376/38237f99-fd27-4478-849a-c1ee546e8f3c)
> 
> 

Sure yeah I can do that, @Huffie56, if u want to remove the hallway fire alarms and shutters. I can finish up the pr after. Feel free to commit your changes to this pr.

2023-12-31 15:27 UTC, Drulikar commented
I'll note its probably fine to leave the shutters in hallways - I'm okay with there being no current way to deploy them. Its just this implementation off fire alarms in hallways isn't desirable to have them deploy so if we only have fire alarms in rooms it should work better with this implementation. But maybe maintainer will think we should find a better code solution to this.

2023-12-31 15:53 UTC, Cthulhu80 commented
> I'll note its probably fine to leave the shutters in hallways - I'm okay with there being no current way to deploy them. Its just this implementation of fire alarms in hallways isn't desirable to have them deploy so if we only have fire alarms in rooms it should work better with this implementation. But maybe maintainer will think we should find a better code solution to this.

I think the optimal solution would have to involve some sort of mapping, which again I don't know how to do. @Huffie56, what do you think?

2023-12-31 17:40 UTC, Huffie56 commented
My personal opinion is that removing current check is fine.

we also need to remind that their isn't only hallway that share emergency shutters.
that's why we had the code check for adjacent area in the first place...

one of the most used example is med bay and the OR's when you pull for treatment center room you want all the emergency for OR's to go down to...

just test in medbay and if you find this ok then go....

if i am not  very clear apology i am a bit tired...

2023-12-31 21:06 UTC, Cthulhu80 commented
I'm going to be gone for a bit @Huffie56, if u want to take this bug over. Closing the pr.

2023-12-31 21:06 UTC, closed without merging