Desk Bell
cmss13-devs/cmss13 pull request #5330
Opened 2023-12-29 00:45 UTC by Birdtalon

# About the pull request

Using my maintainer privilege to add this small feature during the freeze. A desk bell.

Wrench to secure it and use it.
Bell can break at a 1% chance for every 100 rings. In which case a screwdriver will fix it.

![dreamseeker_2023-12-29_00-39-47](https://github.com/cmss13-devs/cmss13/assets/25027759/b33e497a-a7e1-477d-adeb-9dc594b58b77)
![dreamseeker_2023-12-29_00-39-56](https://github.com/cmss13-devs/cmss13/assets/25027759/c4132c47-92d4-48a8-af64-5ce556098907)

Credit:
Modified code and desk_bell.ogg from [Paradise SS13](https://github.com/ParadiseSS13/Paradise)
Sprite from Kat 'APC' Smith - darklordcabbage on discord.

# Explain why it's good for the game

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl: Birdtalon, Kat 'APC' Smith
add: Desk bell for cargo and medbay.
soundadd: Desk bell sound effect.
/:cl:

2023-12-29 00:55 UTC, Cthulhu80 commented on code/modules/paperwork/desk_bell.dm
> +	var/ring_cooldown = 0
COOLDOWN_DECLARE(ring_cooldown)

2023-12-29 00:55 UTC, Cthulhu80 commented on code/modules/paperwork/desk_bell.dm
> +		return FALSE
COOLDOWN_FINISHED(ring_cooldown)

2023-12-29 00:55 UTC, Cthulhu80 commented on code/modules/paperwork/desk_bell.dm
> +	ring_cooldown = world.time + ring_cooldown_length
COOLDOWN_START(src, ring_cooldown, ring_cooldown_length)

2024-01-01 09:45 UTC, JackieEstegado commented
Please for the love of all that is hearing, increase the cooldown to AT LEAST 3 seconds.

2024-01-05 17:25 UTC, Nanu308 approved these changes

2024-01-05 17:25 UTC, Nanu308 commented on maps/map_files/USS_Almayer/USS_Almayer.dmm
mapping lgtm

2024-01-08 19:33 UTC, Birdtalon commented
Have made further map changes @Nanu308 added a couple more bells to various areas at request of the sprite artist.

2024-01-11 15:35 UTC, nauticall requested changes
It's cute, but the bell is _way_ too high off the stand and the stand is also way too big. You only really need a pixel of locomotion for the animation to be visible from a distance, and can achieve that even with a small stand. See below for my recommendation.
<img width="819" alt="image" src="https://github.com/cmss13-devs/cmss13/assets/55491249/95329c29-25b8-4837-946b-8187be484f99">


<img width="157" alt="image" src="https://github.com/cmss13-devs/cmss13/assets/55491249/44368a27-760e-47b2-a6e9-e2a7c3de21d3">

Also note: avoid using diagonals that zig-zag like this. Try using an intermediate color to break up the line instead, or avoid zig-zags entirely and use straight diagonals.

2024-01-11 16:58 UTC, Birdtalon commented
@nauticall thanks for the review, I will pass this onto the spriter and get them to adjust the sprite accordingly.

2024-01-16 23:43 UTC, Nanu308 approved these changes

2024-01-16 23:43 UTC, Nanu308 commented on maps/map_files/USS_Almayer/USS_Almayer.dmm
lgtm

2024-02-01 01:03 UTC, closed without merging