Prescription-eyewear
cmss13-devs/cmss13 pull request #5367
Opened 2024-01-02 11:37 UTC by Staykeu

## About the pull request

Adds the ability to apply lenses from prescription eyewear into HUDs/mesons/specialist optics.

## Explain why it's good for the game

QoL change that makes life easier for those that have characters with impaired vision, allows the use of these eyepieces without obscuring the mask slot, be it reserved for smokes, scarfs, coifs, etc.
# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

N/A

</details>

# Changelog
:cl: Stakeyng
qol: combines prescription glasses and eyewear for varying roles
/:cl:

2024-01-02 11:59 UTC, Drulikar approved these changes
Code changes look fine (its code I wrote) and can confirm working in game.

2024-01-02 12:01 UTC, fira requested changes

2024-01-02 12:01 UTC, fira commented on code/modules/clothing/glasses/glasses.dm
> +		return FALSE
That's redundant

2024-01-02 12:10 UTC, Staykeu commented on code/modules/clothing/glasses/glasses.dm
> +		return FALSE
removed

2024-01-02 12:36 UTC, fira approved these changes

2024-01-02 15:26 UTC, Drulikar requested changes

2024-01-02 15:26 UTC, Drulikar commented on code/modules/clothing/glasses/glasses.dm
> +			offhand.prescription = TRUE
I intended to have them guard against this, but I just didn't place it in the correct spot.
![image](https://github.com/cmss13-devs/cmss13/assets/76988376/b30a0b26-6616-47d4-ba0b-3c93a104aba6)

```suggestion
			if(QDELETED(src) || offhand != user.get_inactive_hand())
				return FALSE
			offhand.prescription = TRUE
```

2024-01-02 16:10 UTC, Drulikar approved these changes
Code changes are fine.

2024-01-06 21:02 UTC, fira approved these changes

2024-01-14 22:38 UTC, merged