does that
cmss13-devs/cmss13 pull request #5380
Opened 2024-01-04 14:20 UTC by Waseemq1235

# About the pull request

Fixes donor helmets not having an accessory slot by making have the garb overlay on by default.

# Explain why it's good for the game

Let them have that slot.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
fix: Fixed donor helmets not having an accessory slot.
/:cl:

2024-01-06 21:00 UTC, fira commented
Isn't that going to mess with visuals for the vast majority of them?

2024-01-06 21:01 UTC, Waseemq1235 commented
> Isn't that going to mess with visuals for the vast majority of them?

They can right click the helmet and toggle garb, it's a lil' verb they get.

2024-01-08 15:41 UTC, fira commented
Yeah i know but what i mean is that given how it is right now i figure the majority are meant to have it disabled

2024-01-11 20:58 UTC, realforest2001 commented
As fira said this is largely intended

2024-01-11 21:00 UTC, Waseemq1235 commented
Sure then I'll change it so it still starts with garb overlay off by default.

2024-01-18 16:11 UTC, harryob requested changes
as above

2024-02-03 00:58 UTC, closed without merging