Tutorial - Basic Medical Items
cmss13-devs/cmss13 pull request #5422
Opened 2024-01-11 09:58 UTC by Steelpoint

# About the pull request

Adds a medical based tutorial aimed at describing every basic medical item a non-Corpsman Marine can access and use, and then describing where they come from and how to store them. 

# Explain why it's good for the game

Educating new players on mechanics is good. 

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
add: Tutorial describing basic medical items, their uses and where to get them has been added. 
/:cl:

2024-01-11 10:10 UTC, Birdtalon requested changes
Couple of things I've noticed from a brief scan. You also need to make sure you include your new .dm file in the .dme
I will try to have a proper look at this soon.

2024-01-11 10:10 UTC, Birdtalon commented on code/datums/tutorial/marine/medical_basic_item.dm
> +	update_objective("")
You only need to call this when you want to update the objective. No need to set it to a blank string every time.

2024-01-11 10:10 UTC, Birdtalon commented on code/datums/tutorial/marine/medical_basic_item.dm
> +	SIGNAL_HANDLER
`SIGNAL_HANDLER` is only needed if you're calling this from a signal using `RegisterSignal()`. Not needed if you're just using a timer to call it.

2024-01-11 10:10 UTC, Birdtalon commented on code/game/machinery/vending/vendor_types/squad_prep/tutorial.dm
> +/obj/structure/machinery/cm_vending/clothing/medic_equip
This typepath should probably explicitly say it's tutorial so someone doesn't use e by accident elsewhere.

2024-01-11 16:29 UTC, Zonespace27 requested changes

2024-01-11 16:29 UTC, Zonespace27 commented on code/datums/tutorial/marine/medical_basic_item.dm
> +	message_to_player("These are <b>Bandages</b>. You can use these to heal <b>Brute</b> damage and stop bleeding. You always want to carry one of these.")
Bandages aren't proper nouns

2024-01-11 16:29 UTC, Zonespace27 commented on code/datums/tutorial/marine/medical_basic_item.dm
> +	message_to_player("These are <b>Ointments</b>. You can use these to heal <b>Burn</b> damage. These are less important to carry, but are useful if you have the space for it.")
Ditto

2024-01-11 16:29 UTC, Zonespace27 commented on code/datums/tutorial/marine/medical_basic_item.dm
> +	message_to_player("These are <b>Splints</b>. You can use these to stabalize <b>fractures</b>. These are very important to use, as a unsplinted fracture can cause permanent injuries.")
Ditto

2024-01-11 16:29 UTC, Zonespace27 commented on code/datums/tutorial/marine/medical_basic_item.dm
> +	update_objective("Eat the food bar when you are ready to continue")
```suggestion
	update_objective("Eat the food bar when you are ready to continue.")
```

2024-01-11 16:29 UTC, Zonespace27 commented on code/datums/tutorial/marine/medical_basic_item.dm
> +	message_to_player("Take this moment to pause and review the previous chat logs, or the medical items on the floor. When you are ready, please take the food bar and eat it.")
```suggestion
	message_to_player("Take this moment to pause and review the previous chat logs or the medical items on the floor. When you are ready, please take the food bar and eat it.")
```

2024-01-11 16:29 UTC, Zonespace27 commented on code/datums/tutorial/marine/medical_basic_item.dm
> +	message_to_player("Good luck Marine")
```suggestion
	message_to_player("Good luck Marine.")
```

2024-01-11 16:29 UTC, Zonespace27 commented on code/datums/tutorial/marine/medical_basic_item.dm
> +	update_objective("Eat the food bar when you are ready to end the tutorial")
```suggestion
	update_objective("Eat the food bar when you are ready to end the tutorial.")
```

2024-01-11 16:29 UTC, Zonespace27 commented on code/datums/tutorial/marine/medical_basic_item.dm
> +	add_to_tracking_atoms(medic_vendor_charlie)
The names are confusing because the NATO alphabet is typically for squads.

2024-01-11 17:15 UTC, Steelpoint commented
requested changes made

2024-01-13 14:37 UTC, Birdtalon requested changes
Overall a good overview of standard medical and the code is good.

Although I personally thought that the pacing might be a little too fast for a new player when describing what the items are.

I also managed to break your tutorial somehow by softlocking myself at the stage where the player has to vend a pull packet pouch and there wasn't any to vend.
![dreamseeker_2024-01-13_14-28-55](https://github.com/cmss13-devs/cmss13/assets/25027759/8d7ff571-b9a3-4cad-943e-5041acd6b42d)

I would like to see a little work on the pacing though so it doesn't feel like information overload and we actually get the player to use more of the items and do stuff within the tutorial. Explain an item or two, then get the player to use them for themselves and see how they work- then move onto the next. The existing medical tutorial is a good example.  This will be more memorable to a player and will flow more easily into the next tutorial and so on and so on.

I'll let you have a think about this and mark your PR as ready for review when you're ready.

2024-01-21 09:21 UTC, Steelpoint commented
I'll reopen once I've got free time to work out the PR and make changes, just closing to stop the auto-close

2024-01-21 09:21 UTC, closed without merging