Makes it possible to view helmet cams of SOs/XOs/COs
cmss13-devs/cmss13 pull request #5433
Opened 2024-01-12 18:02 UTC by TheGamerdk

# About the pull request

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
add: CIC can now view helmet cameras of Command Staff. Literally 1984
/:cl:

2024-01-18 17:29 UTC, harryob requested changes

2024-01-18 17:29 UTC, harryob commented on code/game/machinery/computer/groundside_operations.dm
> +		dat += "</table>"
obviously all of this is copypasta, but i don't see why it couldn't be genericized. make it a proc that accepts a list of humans and returns a formatted html table, give it the squad marinelist in normal usage and the list you make above this for this usecase. the whole co/xo/so text thing can just be replaced by a parameter passed into the proc for a list of jobs

```dm

	if(show_command_squad)
		dat += format_list_of_marines(list(GLOB.marine_leaders[JOB_CO], GLOB.marine_leaders[JOB_XO]) + GLOB.marine_leaders[JOB_SO], list(JOB_CO, JOB_XO, JOB_SO))
	else if(current_squad)
		dat += format_list_of_marines(current_squad.marines_list, list(JOB_SQUAD_LEADER, JOB_SQUAD_SPECIALIST, JOB_SQUAD_MEDIC, JOB_SQUAD_ENGI, JOB_SQUAD_SMARTGUN, JOB_SQUAD_MARINE))

/obj/structure/machinery/computer/groundside_operations/proc/format_list_of_marines(list/mob/living/carbon/human/marine_list, list/jobs_in_order)
		var/list/job_order = list()
		
		for(var/job in jobs_in_order)
			job_order[job] = ""

		var/misc_text = ""
		
		var/living_count = 0
		var/almayer_count = 0
		var/SSD_count = 0
		var/helmetless_count = 0

		for(var/X in marine_list)
			if(!X)
				continue //just to be safe
			var/mob_name = "unknown"
			var/mob_state = ""
			var/role = "unknown"
			var/area_name = "<b>???</b>"
			var/mob/living/carbon/human/H
			if(ishuman(X))
				H = X
				mob_name = H.real_name
				var/area/A = get_area(H)
				var/turf/M_turf = get_turf(H)
				if(A)
					area_name = sanitize_area(A.name)

				if(H.job)
					role = H.job
				else if(istype(H.wear_id, /obj/item/card/id)) //decapitated marine is mindless,
					var/obj/item/card/id/ID = H.wear_id //we use their ID to get their role.
					if(ID.rank)
						role = ID.rank

				switch(H.stat)
					if(CONSCIOUS)
						mob_state = "Conscious"
						living_count++
					if(UNCONSCIOUS)
						mob_state = "<b>Unconscious</b>"
						living_count++
					else
						continue

				if(!is_ground_level(M_turf.z))
					almayer_count++
					continue

				if(!istype(H.head, /obj/item/clothing/head/helmet/marine))
					helmetless_count++
					continue

				if(!H.key || !H.client)
					SSD_count++
					continue

			var/marine_infos = "<tr><td><A href='?src=\ref[src];operation=use_cam;cam_target=\ref[H]'>[mob_name]</a></td><td>[role]</td><td>[mob_state]</td><td>[area_name]</td></tr>"
			if(role in job_order)
				job_order[role] += marine_infos
			else
				misc_text += marine_infos
		dat += "<b>Total: [length(command_marines)] Deployed</b><BR>"
		dat += "<b>Marines detected: [living_count] ([helmetless_count] no helmet, [SSD_count] SSD, [almayer_count] on Almayer)</b><BR>"
		dat += "<center><b>Search:</b> <input type='text' id='filter' value='' onkeyup='updateSearch();' style='width:300px;'></center>"
		dat += "<table id='marine_list' border='2px' style='width: 100%; border-collapse: collapse;' align='center'><tr>"
		dat += "<th>Name</th><th>Role</th><th>State</th><th>Location</th></tr>"
		for(var/job in job_order)
			dat += job_order[job]
		dat += misc_text
		dat += "</table>"
```

2024-01-30 12:11 UTC, Wintermote commented
>Going to rework the whole console at some point. Not proud of this code, give me some ideas
Let us click player icons on the tacmap to instantly overwatch that person (if they're part of the current overwatched squad)

2024-02-13 17:27 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-02-13 17:29 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-02-21 04:16 UTC, harryob approved these changes

2024-02-21 04:41 UTC, merged