Camera Autoname change
cmss13-devs/cmss13 pull request #5456
Opened 2024-01-15 00:19 UTC by realforest2001

# About the pull request
Makes autonaming cameras happen based on a preset variable rather than hardcode.

# Explain why it's good for the game

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
code: Security camera autoname is now determined by a variable rather than hardcode.
/:cl:

2024-01-18 15:30 UTC, harryob requested changes

2024-01-18 15:30 UTC, harryob commented on code/game/machinery/camera/camera.dm
> +		var/area/A = get_area(src)
```suggestion
		var/area/my_area = get_area(src)
```

2024-01-18 15:30 UTC, harryob commented on code/game/machinery/camera/camera.dm
> +						autonumber = max(autonumber, C.autonumber+1)
```suggestion
		if(my_area)
			for(var/obj/structure/machinery/camera/autoname/current_camera in GLOB.machines)
				if(current_camera == src) 
					continue
				var/area/current_camera_area = get_area(current_camera)
				if(current_camera_area.type != my_area.type)
					continue

				if(!current_camera.autonumber)
					continue

				autonumber = max(autonumber, current_camera.autonumber + 1)
```

2024-01-18 15:30 UTC, harryob commented on code/game/machinery/camera/camera.dm
> +			c_tag = "[A.name] #[autonumber]"
```suggestion
			c_tag = "[my_area.name] #[autonumber]"
```

2024-01-18 20:12 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-01-19 14:25 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-01-28 10:25 UTC, Birdtalon approved these changes

2024-01-28 12:06 UTC, merged