Project ARES: Ticket Notifications
cmss13-devs/cmss13 pull request #5510
Opened 2024-01-21 02:39 UTC by realforest2001

# About the pull request
Adds audio notifications for certain ticket interactions, played from APOLLO consoles and WJ PDAs.

# Explain why it's good for the game

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
soundadd: Added pda_ping.ogg, sourced from Paradise SS13 mailapproved.ogg
add: Added notification sounds from certain APOLLO ticket interactions.
add: People making an access ticket request are now notified of the status changes.
/:cl:

2024-01-24 01:12 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-02-22 16:08 UTC, harryob submitted a review, later dismissed

2024-02-22 16:08 UTC, harryob commented on code/game/machinery/ARES/ARES_interface_apollo.dm
> +					continue
this istype is redundant, as you are iterating through the list without `as anything`, so it will *all* be of type /obj/item/card/id

2024-02-22 16:08 UTC, harryob commented on code/game/machinery/ARES/apollo_pda.dm
> +					continue
ditto

2024-03-04 10:53 UTC, Drulikar requested changes

2024-03-04 10:53 UTC, Drulikar commented on code/game/machinery/ARES/ARES_interface_apollo.dm
> +	var/notify_sounds =  TRUE
```suggestion
	var/notify_sounds = TRUE
```

2024-03-04 10:53 UTC, Drulikar commented on code/game/machinery/ARES/ARES_interface_apollo.dm
>  	data["apollo_log"] += datacore.apollo_log
```suggestion
	data["apollo_log"] = datacore.apollo_log
```

2024-03-04 10:53 UTC, Drulikar commented on code/game/machinery/ARES/ARES_interface_apollo.dm
1.
`var/mob/living/carbon/human/operator = usr`
needs to be
`var/mob/living/carbon/human/operator = ui.user`

2. 
All uses of usr in ui_act need to be `operator`

2024-03-04 10:53 UTC, Drulikar commented on code/game/machinery/ARES/ARES_interface_apollo.dm
>  			if(!access_ticket)
```suggestion
			if(!istype(access_ticket))
```

2024-03-11 20:30 UTC, Drulikar commented
usr is still used in ui_act. See previous review.

2024-03-12 00:55 UTC, merged