Gardener QOL changes
cmss13-devs/cmss13 pull request #5514
Opened 2024-01-21 14:29 UTC by InsaneRed

# About the pull request
Gives bigger fruit eaten/destroyed/picked texts as its currently too small to be seen in chat because  is usually always moving and being spammed.
Makes it so you can put fruits next to eachother, but not ontop.

# Explain why it's good for the game

QOL changes good

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog
:cl:
qol: Bigger text when a gardener's fruit gets picked/destroyed/consumed
qol: Gardeners can now put their fruits next to eachother.
grammar: Adds new information to the strain buy text
code: The fruits now get deleted 1 second after they get eaten, instead of 3 seconds.
/:cl:

2024-01-24 20:18 UTC, Birdtalon approved these changes

2024-01-31 03:26 UTC, Drulikar requested changes
Everything else looks fine.

2024-01-31 03:26 UTC, Drulikar commented on code/modules/cm_aliens/structures/fruit.dm
>  	mature = FALSE
Please also set picked true here so the message can be corrected from destroyed to consumed if you eat fruit w/o picking up the fruit.

2024-02-01 00:01 UTC, Drulikar requested changes

2024-02-01 00:01 UTC, Drulikar commented on code/modules/cm_aliens/structures/fruit.dm
> +		to_chat(bound_xeno, SPAN_XENOHIGHDANGER("One of our picked resin fruits has been consumed."))
This isn't the correct place to put this. This means only `/obj/effect/alien/resin/fruit/greater` will indicate they are consumed.

In other words healing fruit now has the consume message, but no other fruit does. Instead this message ought to be in either `finish_consume` or `delete_fruit` or `Destroy`

My recommendation is to make these changes: 
![image](https://github.com/cmss13-devs/cmss13/assets/76988376/a0c9e01f-6576-41f4-9c5d-04294e98fc56)

```suggestion
```

2024-02-01 00:01 UTC, Drulikar commented on code/modules/cm_aliens/structures/fruit.dm
>  	update_icon()
```suggestion
	update_icon()
	if(!QDELETED(bound_xeno))
		to_chat(bound_xeno, SPAN_XENOHIGHDANGER("One of our picked resin fruits has been consumed."))
```

2024-02-01 13:28 UTC, Drulikar approved these changes

2024-02-01 13:37 UTC, merged