Updates Inspection ERTs
cmss13-devs/cmss13 pull request #5521
Opened 2024-01-22 11:48 UTC by realforest2001

# About the pull request
Updates the presets used in inspection ERTs.
Also changes the High Command radio headset to have an alternate version with provost comms. That way junior officers from high command aren't automatically given provost communications.

# Explain why it's good for the game

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
add: Updated the inspection ERTs to be more consistent.
add: Changed the High Command radio headset to not have provost comms, and made an alternate version that keeps it.
/:cl:

2024-01-22 11:49 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-01-22 12:19 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-02-03 21:11 UTC, Drulikar requested changes

2024-02-03 21:11 UTC, Drulikar commented on code/modules/gear_presets/uscm_ship.dm
> +	new_human.equip_to_slot_or_del(new /obj/item/device/radio/headset/almayer/highcom(new_human), WEAR_L_EAR)
This change means this is all they get:
![image](https://github.com/cmss13-devs/cmss13/assets/76988376/03056e6b-76d8-4465-8ae9-571bc80a0fa6)
Just a headset

2024-02-15 06:38 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-03-03 01:02 UTC, closed without merging