Helmet HUDs skip over HUDs that are already in effect on the player
cmss13-devs/cmss13 pull request #5600
Opened 2024-01-31 01:40 UTC by Staykeu

# About the pull request

Makes it so that if you have an active HUD, a helmet visor that does the same thing will not be considered when switching through visors in your helmet.

# Explain why it's good for the game

Visors are usually a pain to switch through when their functionality isn't needed, take for example, the squad optic, which does the same job as the headset (HUD-wise). This change makes it so you don't need to switch through unneeded HUDs.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl: Stakeyng
qol: Removes the need to cycle through helmet visors that contain HUD effects that are already active on your character.
/:cl:

2024-02-01 09:31 UTC, harryob requested changes
for sanity

2024-02-01 09:31 UTC, harryob commented on code/modules/clothing/head/helmet.dm
```suggestion

		return FALSE
```

2024-02-01 20:12 UTC, harryob requested changes

2024-02-01 20:12 UTC, harryob commented on code/modules/clothing/head/helmet.dm
> +		return FALSE
```suggestion
	return FALSE
```

2024-02-01 20:12 UTC, harryob approved these changes
im fine with this but given i my hand in creating the pr we should get someone else to look it over

2024-02-01 20:31 UTC, Drulikar requested changes
This is close, but it doesn't fully handle the situation where the next visor is not valid - it skips disabling the current visor. But this isn't your fault; this is actually fairly complex and probably needs to be refactored because its the logic in toggle_visor that's complicating everything. But I believe my suggestions below address the issue I discovered.

For example, equip a helmet w/ medical visor and squad visor. Remove your headset. Toggle visor to squad. Equip your medical glasses. Try to toggle the visor: Icon will change to no visor, but it fails to remove the squad visor and now thinks it cannot toggle to any visors.

However, this requires modification of lines outside of suggestable scope so best I can streamline this is to provide a patch: 
[patch.diff.txt](https://github.com/cmss13-devs/cmss13/files/14130498/patch.diff.txt)

To apply it copy this file to the root of your fork, then open terminal in VSC and enter `git apply patch.diff.txt`

The changes should result in this: 
![image](https://github.com/cmss13-devs/cmss13/assets/76988376/824193e5-2ace-4e80-97d8-60116cb70e34)

Feel free to ask any questions why I did what I did and to test it.

2024-02-03 16:50 UTC, Drulikar approved these changes

2024-02-03 17:32 UTC, merged