Fixes restocking defibs/power cells cheese
cmss13-devs/cmss13 pull request #563
Opened 2022-06-25 16:32 UTC by stanalbatross

## About The Pull Request

You can no longer restock defibs and power cells if they are not at full charge.

## Why It's Good For The Game

OKAY HOLD YOUR HORSES SALTY MARINE MAINS I SEE YOU EYEING THAT COMMENTS SECTION

This is 100% required in the current state of the game. Medics have it too easy, with incredible ease in resupplying, and shipside is less relevant than ever. Only through making items use their actual INTENDED mechanics to recharge (shock horror, the restocking feature was not intended to make medical vendors an infinite use recharger!) can we slow down gameplay a bit and force medics to put THOUGHT into their supplies/loadout plus cut down on medvendor cheese. 

Also it makes no sense that vendors magically recharge stuff when you put it back into them. It's just the same stuff.

## Changelog

:cl:
fix: You can no longer restock defibs and power cells if they are not at full charge.
/:cl:

2022-06-25 19:51 UTC, Shad0vvs commented
You're insane.

2022-06-25 21:06 UTC, Lafrien commented
So now FoB will be filled with charged defibs on floor and blinking chargers. I don't see much change, except more clunkyness with all items around the floor at FoB. But it surely was wierd to have vendor recharging them magically.

2022-06-26 00:47 UTC, Unknownity commented
> So now FoB will be filled with charged defibs on floor and blinking chargers. I don't see much change, except more clunkyness with all items around the floor at FoB. But it surely was wierd to have vendor recharging them magically.

this is mainly a nerf to power cells as they're never actually charged through normal means

2022-06-26 11:29 UTC, Nanu308 commented
Look into increasing charge rate for items as well with this PR

2022-06-27 09:54 UTC, Superwelder commented
This change is a start but it is only a half-step. In my experience, defibrillator charge is almost never the limiting resource for a medic in terms of dishing out healing. By the time you actually run out of defibrillator charge, there is almost always another defib on offer. Be it from a dead medic or vending them from the vendor. I have had to recharge my defibrillator in a vendor maybe 3 times in the last 3 months while I have taken a dead medic's defib dozens of times in the same span of time. What is really the medic 'cheese' is being able to split any stack of of kits/splints and manufacture ridiculous numbers of said kits/splints instantaneously. That coupled with any marine being able to fill almost any useful injector causes a post-scarcity medical economy in CM. The seeds of this problem were sown when medvendors were made wrench-able way back when. It does not help that currently the synthetics, RTOs, survivors, and of course engineers can all hack said medvendors for anyone to use.

2022-07-05 08:20 UTC, Wintermote commented
I don't think we need to fix duping of minor healing items like splints; these are things that you can already get 20 of them per player very easily, but you'd also never want to - and if we reduce the number of splints available so that each individual one actually matters, it becomes a very serious balance change. I'm not sure it'd be a good idea.

And this is also mostly true of defibs - getting your hands on an extra defib is not usually a problem.

However, what IS a problem, is trying to recharge defibs or batteries instead of hotswapping through a vendor - nobody has the time to waste 5-20 minutes waiting for their defib or battery to recharge, so the actual effect would be disabling defib and battery replenishment entirely, not merely preventing them from being swapped through the vendors.

Additionally, there just aren't any real portable chargers for marines to use. It's already common enough to have ZERO chargers in the fob at all, let alone having to go up to the ship to stick a defib in a charger.

IMO - This needs to go a whole lot further than simply disabling swapping in vendors. Fixing this requires a redo of how batteries and charging work in their entirety.

There needs to be:
1. A way to swap batteries out of defibs and anything else with 'charges'
2. A way to recharge batteries in a timely manner (so that players are not standing around waiting for even 3+ minutes)
4. A way to keep all these batteries organized and available to players
5. A way to carry all these batteries without destroying your ability to carry other gear

I am altogether more of the opinion that charging batteries is an unnecessary "realism" headache for gameplay and we are better off without any of this stuff.

But if it really needs to be done, just changing the vendors is only going to create a huge balance problem. It needs more work than just that.

2022-07-06 20:30 UTC, Geevies requested changes

2022-07-06 20:30 UTC, Geevies commented on code/game/machinery/vending/cm_vending.dm
> +				if(D.dcell.charge < D.dcell.maxcharge)
future-proof this check, add a "does this defib even have a cell", because i bet someone in three years is gonna add a defib with swappable cells

2022-07-06 20:30 UTC, Geevies commented on code/game/machinery/vending/cm_vending.dm
> +					to_chat(user,SPAN_WARNING("\The [item_to_stock] needs to be fully charged to restock it!"))
```suggestion
					to_chat(user, SPAN_WARNING("\The [item_to_stock] needs to be fully charged to restock it!"))
```

2022-07-06 20:30 UTC, Geevies commented on code/game/machinery/vending/cm_vending.dm
> +					to_chat(user,SPAN_WARNING("\The [item_to_stock] needs to be fully charged to restock it!"))
```suggestion
					to_chat(user, SPAN_WARNING("\The [item_to_stock] needs to be fully charged to restock it!"))
```

2022-07-06 20:30 UTC, Geevies commented on code/game/machinery/vending/vending.dm
> +				if(D.dcell.charge < D.dcell.maxcharge)
ditto

2022-07-06 20:30 UTC, Geevies commented on code/game/machinery/vending/vending.dm
> +					to_chat(user,SPAN_WARNING("\The [item_to_stock] needs to be fully charged to restock it!"))
```suggestion
					to_chat(user, SPAN_WARNING("\The [item_to_stock] needs to be fully charged to restock it!"))
```

2022-07-06 20:30 UTC, Geevies commented on code/game/machinery/vending/vending.dm
> +					to_chat(user,SPAN_WARNING("\The [item_to_stock] needs to be fully charged to restock it!"))
```suggestion
					to_chat(user, SPAN_WARNING("\The [item_to_stock] needs to be fully charged to restock it!"))
```

2022-07-15 06:47 UTC, merged