Bipod now gives you an option to switch to full auto when deploying
cmss13-devs/cmss13 pull request #5638
Opened 2024-02-02 10:42 UTC by VileBeggar

# About the pull request

Attaching the bipod to weapons with full auto capability or firearms marked with the GUN_SUPPORT_PLATFORM flag will give the user a button toggle to immediately switch to full auto when deploying the bipod.

![image](https://github.com/cmss13-devs/cmss13/assets/17518895/05af01c5-6b86-48b2-96c6-562f945f1391)

If the full auto switch is turned on, the weapon will simply switch to full auto when the bipod is deployed. If you undeploy it, it will switch back to whatever previous firemode the weapon was in, e.g:

1. You set your pulse rifle to semi auto. 
2. You deploy the bipod. 
3. The pulse rifle is set to full auto. 
4. You undeploy the bipod. 
5. The pulse rifle will switch back to semi auto.

In cases where you switch the weapon's firemode when it's already switched to full auto, it won't revert back to whatever firemode was set before it was deployed, e.g:

1. You set your pulse rifle to semi auto. 
2. You deploy the bipod. 
3. The pulse rifle is set to full auto. 
4. You set your pulse rifle to burst fire.
5. You undeploy the bipod. 
6. The pulse rifle will stay on burst fire.

# Explain why it's good for the game

Quality of life. Less messing around with firemode selectors which is a terrible headache for the HPR, which you usually want to have on full auto 90% of the time. Those who want to stick with the old way don't have to change anything, as the full auto switch is entirely optional.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

https://github.com/cmss13-devs/cmss13/assets/17518895/35bcc6e7-947d-4f82-971f-ac22b723537b

</details>

# Changelog

:cl:
qol: Attaching the bipod to weapons that have full auto (HPR included) will give you a button toggle for immediately switching to full auto when deploying the bipod.
/:cl:

2024-02-02 14:07 UTC, cuberound commented
mby you could rename G to gun and A to action to get rid of single letter vars when you are working on that file, would be nice

2024-02-03 09:24 UTC, harryob requested changes

2024-02-03 09:24 UTC, harryob commented on code/modules/projectiles/gun_attachables.dm
> +		if(usr && (gun == usr.l_hand || gun == usr.r_hand))
i know we're nullchecking this, but usr is always scary and bad in non-verbs. ideally, we pass an (optional) user var to `/attachable/proc/Attach` from `gun/proc/attach_to_gun` which we can drop in as a replacement for usr here

2024-02-03 09:24 UTC, harryob commented on code/modules/projectiles/gun_attachables.dm
> +	playsound(usr, 'sound/weapons/handling/gun_burst_toggle.ogg', 15, 1)
```suggestion
	to_chat(owner, SPAN_NOTICE("[icon2html(holder_gun, usr)] You will [attached_bipod.full_auto_switch? "<B>start</b>" : "<B>stop</b>"] switching to full auto when deploying the bipod."))
	playsound(owner, 'sound/weapons/handling/gun_burst_toggle.ogg', 15, 1)
```

2024-02-05 13:05 UTC, nauticall approved these changes
sprite good 🍋

2024-02-06 01:32 UTC, Drulikar requested changes
Minor nitpick, but it seems to only remember the old state early on or when deployed and then gets stuck remembering that state.

1. Be on automatic fire
2. Enable Full Auto Switch
3. Change to burst fire
4. Deploy (changes to automatic)
5. Retract (returns to burst correctly)
6. Change to automatic fire
7. Deploy
8. Retract (incorrectly returns to burst)
9. Change to semi auto
10. Deploy (changes to automatic)
11. Retract (incorrectly returns to burst)

2024-02-08 23:54 UTC, Drulikar approved these changes

2024-02-14 10:05 UTC, merged