Reactor changes
cmss13-devs/cmss13 pull request #5657
Opened 2024-02-04 01:14 UTC by BeagleGaming1

# About the pull request

Updates reactors, fuel cells, fuel cell recyclers, and a proc that got in the way
plus reactor sprites attempt 2

Reactor sprites originally from Cosmic-Overlord/TerraGov-Marine-Corps#227, modified by me

# Explain why it's good for the game

Adding more complexity and content to reactors makes them more than just a set piece that gets set up and ignored

# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

I didnt test it
</details>

# Changelog
:cl:
balance: Xenos can slash reactors
balance: Reactors that are damaged will still run until reaching weld damage or being manually de-activated
balance: Reactors that are damaged will lose fuel (when applicable) and fail more often when fuel runs out, new cells need to be used to reset the fail rate
balance: Reactors can be damaged by bullets or explosions
code: Updated Power all ship reactors admin button code
imageadd: Updated reactor sprites
maptweak: Minor changes to reactors and surrounding areas
/:cl:

2024-02-04 01:16 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-02-04 02:34 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-02-04 10:07 UTC, nauticall approved these changes
ayep

2024-02-05 10:35 UTC, harryob submitted a review, later dismissed

2024-02-05 10:35 UTC, harryob commented on code/game/machinery/fuelcell_recycler.dm
> +	cell_right = new
```suggestion
	cell_left = new(src)
	cell_right = new(src)
```
shouldn't these be in the recyclers contents?

2024-02-05 10:35 UTC, harryob commented on code/game/machinery/fuelcell_recycler.dm
> +	return(fuel_amount == max_fuel_amount)
```suggestion
	return (fuel_amount == max_fuel_amount)
```

2024-02-05 10:35 UTC, harryob commented on code/game/machinery/fuelcell_recycler.dm
> +/obj/item/fuel_cell/proc/modify_fuel(amount) //increase or decrease fuel as needed
not a dmdoc?

2024-02-05 10:35 UTC, harryob commented on code/game/machinery/fuelcell_recycler.dm
> +	return round(100*fuel_amount/max_fuel_amount)
```suggestion
	return round(100 * fuel_amount/max_fuel_amount)
```

2024-02-06 22:22 UTC, Nanu308 approved these changes
Mapping lgtm

2024-02-08 00:56 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-02-09 01:09 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-02-18 09:44 UTC, Drulikar requested changes

2024-02-18 09:44 UTC, Drulikar commented on code/game/machinery/fusion_engine.dm
> +			to_chat(user, SPAN_WARNING("[src] already has [fusion_cell]. Before you can replace it with [cell] you need to remove it with a wrench."))
It seems this actually wants a crowbar.

2024-02-18 09:45 UTC, Drulikar commented
Messages are also really spammy. This is only 1 reactor damaged: 
![image](https://github.com/cmss13-devs/cmss13/assets/76988376/2bba36f1-e75d-4064-8de4-859bdf9fab74)

2024-02-19 04:32 UTC, Drulikar approved these changes
As far as I can tell this all is working.

2024-02-19 04:41 UTC, merged