Requisition Centralization [Part 1.5] AKA medvendor infinite restock outside medbay cheese removal redux
cmss13-devs/cmss13 pull request #5677
Opened 2024-02-07 05:19 UTC by ItsVyzo

# About the pull request

This PR adds a new structure: the medical supply link port. This is a structure that allows medical vendors to link to the Almayer's internal medical supplies and have larger restocking capabilities. They can be found around the Almayer where existing medical vendors are.

This PR makes it impossible to restock/refill non full stacks at medical vendors which are not linked to a medical supply link port

This PR makes it impossible to restock/refill non full autoinjectors and bottles at medical vendors which are not linked to a medical supply link port

revives #2155

# Explain why it's good for the game

This PR is good for the game because it will get req more involved in the medical supply process, as well as limiting the capability of medics to instantly resupply from a vendor at the fob or in hydro. This makes it so that medics have to more carefully pick their supplies, and plan ahead for resupplying, as well as consider other medics' use of supplies, as nothing is infinite groundside anymore.

Overall, it will make the medic supply gameplay loop more engaging and interesting, as well as reducing marine capability to infinitely heal and resupply themselves groundside.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

🆑 Stan_albatross
balance: medical vendors, excepting nanomeds, can now only refill/restock stacks and autoinjectors/bottles when on special medical supply link ports that can only be found shipside. Sprite by kugamo.
fix: supply pads will no longer generate ambient occlusion.
/:cl:

2024-02-07 06:03 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-02-07 06:23 UTC, Zonespace27 requested changes

2024-02-07 06:23 UTC, Zonespace27 commented on code/game/machinery/vending/vendor_types/medical.dm
> +	layer = 2.1 //It's the floor, man
layers need defines

2024-02-07 06:23 UTC, Zonespace27 commented on code/game/machinery/vending/vendor_types/medical.dm
> +	icon = 'icons/effects/warning_stripes.dmi'
is this correct?

2024-02-07 06:23 UTC, Zonespace27 commented on code/game/machinery/vending/vendor_types/medical.dm
> +/obj/structure/medical_supply_link/proc/do_unclamp_animation()
doc comments please

2024-02-07 06:23 UTC, Zonespace27 commented on code/game/machinery/vending/vendor_types/medical.dm
> +	UnregisterSignal(src, COMSIG_STRUCTURE_UNWRENCHED)
not needed

2024-02-07 06:23 UTC, Zonespace27 commented on code/game/machinery/vending/vendor_types/medical.dm
> +	var/requires_supply_link_port = TRUE
doc comment

2024-02-07 06:23 UTC, Zonespace27 commented on code/game/machinery/vending/vendor_types/medical.dm
> +					to_chat(user, SPAN_WARNING("\The [src] makes a buzzing noise as it rejects \the [restock_stack]. Looks like this vendor cannot restock non-full stacks outside of a medical bay's supply link."))
\the not needed

2024-02-07 06:23 UTC, Zonespace27 commented on code/game/machinery/vending/vendor_types/medical.dm
> +					to_chat(user, SPAN_WARNING("\The [src] makes a buzzing noise as it rejects \the [container.name]. Looks like this vendor cannot refill these outside of a medical bay's supply link."))
ditto

2024-02-07 06:23 UTC, Zonespace27 commented on code/game/machinery/vending/vendor_types/medical.dm
> +/obj/structure/machinery/cm_vending/sorted/medical/proc/get_supply_link()
doc

2024-02-07 06:23 UTC, Zonespace27 commented on code/game/machinery/vending/vendor_types/medical.dm
> +			to_chat(user, SPAN_WARNING("\The [src] makes a buzzing noise as it rejects \the [C.name]. Looks like this vendor cannot refill these outside of a medical bay's supply link."))
\the

2024-02-07 06:23 UTC, Zonespace27 commented on code/game/machinery/vending/vendor_types/medical.dm
> +			to_chat(user, SPAN_WARNING("\The [src] makes a buzzing noise as it rejects \the [S.name]. Looks like this vendor cannot restock non-full stacks outside of a medical bay's supply link."))
\the

2024-02-07 06:23 UTC, Zonespace27 commented on code/game/objects/structures.dm
> +		to_chat(user, SPAN_WARNING("The [src] cannot be [anchored ? "un" : ""]anchored."))
Why did you add this

2024-02-07 06:23 UTC, Zonespace27 commented on code/game/objects/structures.dm
> +				for(var/obj/O in loc)
no one-letter vars

2024-02-07 06:23 UTC, Zonespace27 commented on code/game/objects/structures.dm
> +				for(var/obj/O in loc)
no one-letter vars

2024-02-07 08:20 UTC, ItsVyzo commented on code/game/objects/structures.dm
> +		to_chat(user, SPAN_WARNING("The [src] cannot be [anchored ? "un" : ""]anchored."))
oversight

2024-02-07 08:25 UTC, ItsVyzo commented on code/game/machinery/vending/vendor_types/medical.dm
> +	icon = 'icons/effects/warning_stripes.dmi'
Do you mean grammar, icon or desc?

2024-02-07 08:31 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-02-07 17:58 UTC, Huffie56 commented
from what i can see map wise you changed the floor tiles for no reason?
![image](https://github.com/cmss13-devs/cmss13/assets/117036822/2dfe2697-d662-460e-a128-44d8de75b3e6)
shouldn't be full white when it's close to a wall but half green (part toward the wall) and the rest white...
look at the other vendors around them...

2024-02-07 19:22 UTC, ItsVyzo commented
> from what i can see map wise you changed the floor tiles for no reason?
> 
> ![image](https://github.com/cmss13-devs/cmss13/assets/117036822/2dfe2697-d662-460e-a128-44d8de75b3e6)
> 
> shouldn't be full white when it's close to a wall but half green (part toward the wall) and the rest white...
> 
> look at the other vendors around them...

Floor was not changed. That's a medlink under the vendors and it's not green to allow distinguishing from afar

2024-02-07 19:33 UTC, Drulikar submitted a review, later dismissed
What this PR is doing is good; however I don't want to entirely disable refilling of injectors if not in a port. Rather the vendor should have a pool of reagents that is consumed as autoinjectors are filled.

Additionally I would like the vendor to have a more streamlined means to restock it; e.g. a vendor restock pack that req can order and then can be used on a vendor to restore the stock values (if any need stocking).

Reagents can be a separate restock pack (instead of also being refilled via the supply pack); but ultimately its the same process. I don't want to go so far as trying to get chemistry to actually mix together the reagents but ever chemistry needs more work that could be something for them to do.

So in summary:
- Vendors not in a restock port need to still allow injector refilling, but this pulls from either a reagent amount per type of chemical - or a omni reagent amount that can be used for any chemical.
- Vendors not in a restock port need stocking item(s) that req can order and then be used on a vendor to restock it. Its fine to allow individual items to be inserted into a vendor, but this shouldn't be the only way to restock it.

If these two things are a bit more difficult for you to implement, we can shelve this PR until another PR is put together to address those requests.

2024-02-07 20:18 UTC, Drulikar commented
Also we need to disallow splitting of stacks of items that we can top off (e.g. so you can't vend one trauma kit, split it, top it off, and now have duplicated the stack).

2024-02-15 06:19 UTC, Drulikar commented
Stale exempt because its roadmap - and waiting on me anyways

2024-02-19 04:45 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-02-22 13:50 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-03-08 22:45 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-03-13 15:54 UTC, Nanu308 requested changes

2024-03-13 15:54 UTC, Nanu308 commented on icons/effects/warning_stripes.dmi
![bilde](https://github.com/cmss13-devs/cmss13/assets/59782240/e1e80d9e-466e-4195-bbd7-9bb9352189a7)
![bilde](https://github.com/cmss13-devs/cmss13/assets/59782240/46d139de-eee6-4781-b79a-0cdee89be878)

Why is the turf a part of the structure sprite? This makes the map stuff look really bad in some places.

I want this changed for map aesthetics.

2024-03-14 08:58 UTC, ItsVyzo commented on icons/effects/warning_stripes.dmi
will work on that soon-ish

2024-03-29 09:28 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-03-29 09:42 UTC, ItsVyzo commented on icons/effects/warning_stripes.dmi
resolvedd

2024-04-01 07:39 UTC, Drulikar requested changes
Be sure to update the DMIs and test changes.

2024-04-01 07:39 UTC, Drulikar commented on code/game/machinery/vending/vendor_types/medical.dm
> +
```suggestion
```
Redundant to parent's implementation.

2024-04-01 07:39 UTC, Drulikar commented on code/game/machinery/vending/vendor_types/medical.dm
> +	icon_state = "medlink_unclamped"
```suggestion
	icon_state = "medlink_unclamped"
	var/base_state = "medlink"
```

2024-04-01 07:39 UTC, Drulikar commented on code/game/machinery/vending/vendor_types/medical.dm
> +
```suggestion
```
You aren't doing anything with the proc so what's the point.

2024-04-01 07:39 UTC, Drulikar commented on code/game/machinery/vending/vendor_types/medical.dm
> +		icon_state = "medlink_unclamped"
```suggestion
/obj/structure/medical_supply_link/proc/do_clamp_animation() // clamp and unclamp animations for when vendor is wrench over supply link
	flick("[base_state]_clamping", src)
	addtimer(CALLBACK(src, PROC_REF(update_icon), 2.6 SECONDS))
	update_icon()

/obj/structure/medical_supply_link/proc/do_unclamp_animation()
	flick("[base_state]_unclamping", src)
	addtimer(CALLBACK(src, PROC_REF(update_icon), 2.6 SECONDS))
	update_icon()

/obj/structure/medical_supply_link/update_icon()
	if(locate(/obj/structure/machinery/cm_vending/sorted/medical) in loc)
		icon_state = "[base_state]_clamped"
	else
		icon_state = "[base_state]_unclamped"
```

2024-04-01 07:39 UTC, Drulikar commented on code/game/machinery/vending/vendor_types/medical.dm
> +	icon_state = "medlink_unclamped_notop"
```suggestion
	icon_state = "medlink_notop_unclamped"
	base_state = "medlink_notop"
```
**NOTE:** You must also update the DMI to accommodate this. We need to have the unclamped and clamped be the suffix.

2024-04-01 07:39 UTC, Drulikar commented on code/game/machinery/vending/vendor_types/medical.dm
> +
```suggestion
```
This is all redundant if you do the base_state changes.

2024-04-01 07:39 UTC, Drulikar commented on code/game/machinery/vending/vendor_types/medical.dm
> +	icon_state = "medlink_unclamped_notopg"
```suggestion
	icon_state = "medlink_notopg_unclamped"
	base_state = "medlink_notopg"
```
**NOTE**: You must also update the DMI to accommodate this. We need to have the unclamped and clamped be the suffix.

2024-04-01 07:39 UTC, Drulikar commented on code/game/machinery/vending/vendor_types/medical.dm
> +
```suggestion
```
Redundant to parent's implementation.

2024-04-01 07:39 UTC, Drulikar commented on code/game/machinery/vending/vendor_types/medical.dm
> +
```suggestion
```
This is all redundant if you do the base_state changes.

2024-04-01 07:39 UTC, Drulikar commented on code/game/machinery/vending/vendor_types/medical.dm
> +					to_chat(user, SPAN_WARNING("\The [src] makes a buzzing noise as it rejects [container.name]. Looks like this vendor cannot refill these outside of a medical bay's supply link."))
```suggestion
					to_chat(user, SPAN_WARNING("[src] makes a buzzing noise as it rejects [container.name]. Looks like this vendor cannot refill these outside of a medical bay's supply link."))
```

2024-04-01 07:39 UTC, Drulikar commented on code/game/machinery/vending/vendor_types/medical.dm
> +					to_chat(user, SPAN_WARNING("\The [src] makes a buzzing noise as it rejects [restock_stack]. Looks like this vendor cannot restock non-full stacks outside of a medical bay's supply link."))
```suggestion
					to_chat(user, SPAN_WARNING("[src] makes a buzzing noise as it rejects [restock_stack]. Looks like this vendor cannot restock non-full stacks outside of a medical bay's supply link."))
```

2024-04-01 07:39 UTC, Drulikar commented on code/game/machinery/vending/vendor_types/medical.dm
> +			to_chat(user, SPAN_WARNING("\The [src] makes a buzzing noise as it rejects [C.name]. Looks like this vendor cannot refill these outside of a medical bay's supply link."))
```suggestion
			to_chat(user, SPAN_WARNING("[src] makes a buzzing noise as it rejects [C.name]. Looks like this vendor cannot refill these outside of a medical bay's supply link."))
```

2024-04-01 07:39 UTC, Drulikar commented on code/game/machinery/vending/vendor_types/medical.dm
> +			to_chat(user, SPAN_WARNING("\The [src] makes a buzzing noise as it rejects [S.name]. Looks like this vendor cannot restock non-full stacks outside of a medical bay's supply link."))
```suggestion
			to_chat(user, SPAN_WARNING("[src] makes a buzzing noise as it rejects [S.name]. Looks like this vendor cannot restock non-full stacks outside of a medical bay's supply link."))
```

2024-04-05 08:13 UTC, Drulikar requested changes

2024-04-06 04:45 UTC, Drulikar requested changes

2024-04-06 04:45 UTC, Drulikar commented on code/game/machinery/vending/vendor_types/medical.dm
> +/obj/structure/medical_supply_link/notopg
```suggestion
// --- Green
/obj/structure/medical_supply_link/green
```
Please also repath it in the map too.

2024-04-06 04:45 UTC, Drulikar commented on code/game/machinery/vending/vendor_types/medical.dm
> +	if(locate(/obj/structure/machinery/cm_vending/sorted/medical) in loc)
```suggestion
	var/obj/structure/machinery/cm_vending/sorted/medical/vendor = locate() in loc
	if(vendor && vendor.anchored)
```
Without this the link basically always goes to the clamped state.

2024-04-06 04:45 UTC, Drulikar commented on code/game/machinery/vending/vendor_types/medical.dm
> +	var/linkpoint = locate(/obj/structure/medical_supply_link) in loc
```suggestion
	if(!anchored)
		return FALSE
	var/obj/structure/medical_supply_link/linkpoint = locate() in loc
```

2024-04-06 04:45 UTC, Drulikar commented on code/game/machinery/vending/vendor_types/medical.dm
> +					to_chat(user, SPAN_WARNING("[src] makes a buzzing noise as it rejects [container.name]. Looks like this vendor cannot refill these outside of a medical bay's supply link."))
```suggestion
					to_chat(user, SPAN_WARNING("[src] makes a buzzing noise as it rejects [container.name]. Looks like this vendor cannot refill these without a connected supply link."))
```

2024-04-06 04:45 UTC, Drulikar commented on code/game/machinery/vending/vendor_types/medical.dm
> +					to_chat(user, SPAN_WARNING("[src] makes a buzzing noise as it rejects [restock_stack]. Looks like this vendor cannot restock non-full stacks outside of a medical bay's supply link."))
```suggestion
					to_chat(user, SPAN_WARNING("[src] makes a buzzing noise as it rejects [restock_stack]. Looks like this vendor cannot restock these without a connected supply link."))
```

2024-04-06 04:45 UTC, Drulikar commented on code/game/machinery/vending/vendor_types/medical.dm
> +			to_chat(user, SPAN_WARNING("[src] makes a buzzing noise as it rejects [C.name]. Looks like this vendor cannot refill these outside of a medical bay's supply link."))
```suggestion
			to_chat(user, SPAN_WARNING("[src] makes a buzzing noise as it rejects [C.name]. Looks like this vendor cannot refill these without a connected supply link."))
```

2024-04-06 04:45 UTC, Drulikar commented on code/game/machinery/vending/vendor_types/medical.dm
> +			to_chat(user, SPAN_WARNING("[src] makes a buzzing noise as it rejects [S.name]. Looks like this vendor cannot restock non-full stacks outside of a medical bay's supply link."))
```suggestion
			to_chat(user, SPAN_WARNING("[src] makes a buzzing noise as it rejects [S.name]. Looks like this vendor cannot restock these without a connected supply link."))
```

2024-04-06 04:53 UTC, Drulikar requested changes
Outstanding issues not resolved from zonespace review.

2024-04-06 04:53 UTC, Drulikar commented on code/game/machinery/vending/vendor_types/medical.dm
> +/obj/structure/medical_supply_link/proc/do_clamp_animation() // clamp and unclamp animations for when vendor is wrench over supply link
```suggestion
/// Performs the clamping animation when a structure is anchored in our loc
/obj/structure/medical_supply_link/proc/do_clamp_animation()
	SIGNAL_HANDLER
```

2024-04-06 04:53 UTC, Drulikar commented on code/game/machinery/vending/vendor_types/medical.dm
> +/obj/structure/medical_supply_link/proc/do_unclamp_animation()
```suggestion
/// Performs the unclamping animation when a structure is unanchored in our loc
/obj/structure/medical_supply_link/proc/do_unclamp_animation()
	SIGNAL_HANDLER
```

2024-04-06 04:53 UTC, Drulikar commented on code/game/machinery/vending/vendor_types/medical.dm
> +	var/requires_supply_link_port = TRUE // sets vendor to require medlink to be able to resupply
```suggestion
	/// sets vendor to require a medlink to be able to resupply
	var/requires_supply_link_port = TRUE
```

2024-04-06 04:53 UTC, Drulikar commented on code/game/machinery/vending/vendor_types/medical.dm
> +/obj/structure/machinery/cm_vending/sorted/medical/proc/get_supply_link() // checks supply link location in relation to medvendor
```suggestion
/// checks if there is a supply link in our location and we are anchored to it
/obj/structure/machinery/cm_vending/sorted/medical/proc/get_supply_link()
```

2024-04-06 05:18 UTC, Drulikar approved these changes

2024-04-06 05:53 UTC, sleepynecrons approved these changes
sprites fine

2024-04-06 19:24 UTC, Nanu308 approved these changes

2024-04-06 19:24 UTC, Nanu308 commented on maps/map_files/USS_Almayer/USS_Almayer.dmm
mapping looking great with transparent version 👍

2024-04-07 01:27 UTC, merged