Nearsighted characters now CONFIRMED to always keep their glasses
cmss13-devs/cmss13 pull request #568
Opened 2022-06-25 21:15 UTC by stanalbatross

## About The Pull Request

makes sure that if you are nearsighted, no matter what other stuff you get in your loadout, you always keep a pair of glasses on you.

## Why It's Good For The Game

nearsighted characters should not be losing their glasses if they pick other loadout options, closes #567 

## Changelog

:cl:
fix: fixed nearsighted characters' glasses just deleting if they couldn't equip to your eyes. They will now try go in other spots in your inventory instead.
spellcheck: renamed "big sunglasses" to "shades" to be consistent with the character setup pref
add: added separate loadout options for prescription and non-prescription sunglasses, previously it was just prescription ones, also added a unique desc to prescription sunglasses.
/:cl:

2022-06-26 17:18 UTC, MusselMain commented
Can we make a rare variant for those who've got nearsighted and are playing a role like MP or Doctor? I generally don't use nearsighted, but I've seen enough players who're playing Doctor or medic, wearing glasses instead of healthHUD's/SensorMate's, that I have to mention this.

2022-06-27 12:44 UTC, stanalbatross commented
> Can we make a rare variant for those who've got nearsighted and are playing a role like MP or Doctor? I generally don't use nearsighted, but I've seen enough players who're playing Doctor or medic, wearing glasses instead of healthHUD's/SensorMate's, that I have to mention this.

done in a different way - if you are nearsighted you will get prescription hud versions of your goggles

2022-07-08 14:33 UTC, Shad0vvs requested changes
About half of the sechuds are copy pasted without /perscription versions, please resolveo.

2022-07-08 16:22 UTC, Shad0vvs commented on code/modules/clothing/glasses/glasses.dm
> +prescription = TRUE
```suggestion
    prescription = TRUE

```

2022-07-08 16:25 UTC, Shad0vvs commented on code/modules/clothing/glasses/glasses.dm
> +    prescription = TRUE
```suggestion
	prescription = TRUE
```

2022-07-08 16:30 UTC, Shad0vvs approved these changes

2022-07-08 16:30 UTC, merged