Big red loot nerf + fixes
cmss13-devs/cmss13 pull request #569
Opened 2022-06-25 21:23 UTC by PhantomEpicness

## About The Pull Request
Fixes a large swath of bugs in SW mining caves. 

The loot was never intended to be this much, failure on my part to note that I added survivor loot already and ended up forgetting and adding more and more crates due to the extremely long development of it.

Looking at the loot again, I discovered a key issue in mapping. You either put down merc crates that potentially spawn with something OP or shit, spawn a crate with OP gear or pre place weapons.

To fix this, I made different categories of large weapons crates to introduce some level of control into this, so that loot crates can be balanced properly and be used more flexibly. 

All of these can only spawn 1 specific weapon in a "set" along with its ammo, unless otherwise stated.

- Crap: As it says, assorted garbage sets like dual CMB revolvers, KT-42, and bolt action rifle set.
- Mediocre: Survivor-tier weapons.
- Decent: Marine-tier weapons
- Good:  Marine+ weapons as this also includes some AP mags and sets that come with nades. On par with merc crate due to consistency in weapons.
- Exotic: PMC+ tier powerful weapons as it can contain either a type 23, NSG 23, tac shottie, and MK1 along with an L42 + AP and FP9000 + nade sets. Should be considered better than the merc crate as this one can _consistently_ give you powerful shit
- Funny: Funny sets. Disguised to look like an exotic crate. Quality varies widely and should be "mediocre" tier due to it
 
### *Ok cool but what are the changes?*

- The 4 merc crates were replaced with a decent crate, a mediocre crate, a crap one, and a funny one.
- Lunge mines removed
- Replaced some HGs with Riot combat shotguns (these shoot 20g beanbags so they are useless in real combat)
- Removed some other dumb OP weapons
- Removed ammo from the NSG 23 crate
- Compensated for this by adding a few more HEFA nades. These will truly result in the 12:10 surv major

## Why It's Good For The Game
fixes bugs, massive mapper QoL, less headaches for xenos.

## Changelog

:cl: TotalEpicness
fix: Fixed Big red SW mining caves firealarm and medical cabinet being missaligned
fix: Fixed Big red SW mining caves drill consoles going invisible when weeds touch it
fix: Fixed various other minor bugs in SW mining caves.
qol: Mappers now have varying quality loot crates to place.
balance: Nerfed the loot in big red SW caves.
/:cl:

2022-07-06 18:57 UTC, Nanu308 requested changes

2022-07-12 03:48 UTC, PhantomEpicness commented
did a small rebalance of the "crap" and mediocre set as some of the items were the same between them

2022-07-12 09:54 UTC, stanalbatross requested changes

2022-07-12 09:54 UTC, stanalbatross commented on code/game/objects/structures/crates_lockers/largecrate.dm
> +	var/i = pick(1,5)
pick 1 to 5 but there are 8 options

🤔

2022-07-19 14:08 UTC, closed without merging