Standardizes both Lesser Drone and Facehugger respawn times to 1 Minute
cmss13-devs/cmss13 pull request #5691
Opened 2024-02-09 23:24 UTC by GrrrKitten

# About the pull request

# Explain why it's good for the game

Right now people spam out lessers because 30 seconds respawn time and people who would go hugger don’t want to wait out the 3 minute time on something that can die to a stray bullet so they just go lesser instead.

This change would make dedicated lesser players less annoying from near instant respawning -> tunnel to frontline and while making dying to a stray bullet from 3 screens away as hugger way less frustrating.

# Testing Photographs and Procedure

<details>

pt 1: Facehugger respawn time reduced from 3 minutes to 1 minute
Pt 2: Lesser drone respawn time upped from 30 seconds to 1 minute

<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:

balance: Facehugger respawn time reduced from 3 minutes to 1 minute
balance: Lesser drone respawn time upped from 30 seconds to 1 minute
/:cl:

2024-02-09 23:54 UTC, GrrrKitten commented
realized when testing there is a lil more I gotta do whoopsies

2024-02-19 04:38 UTC, Drulikar requested changes

2024-02-19 04:38 UTC, Drulikar commented on code/__DEFINES/xeno.dm
> +#define JOIN_AS_LESSER_DRONE_DELAY (1 MINUTES)
I am fine with an increased lesser drone delay.

I do not think we need to make face huggers spawn faster when they already can spawn instantly if they successfully hug.

2024-02-19 04:38 UTC, Drulikar commented on code/modules/mob/living/carbon/xenomorph/hive_status.dm
> +		to_chat(user, SPAN_WARNING("You ghosted too recently. You cannot become a lesser drone until 1 minute has passed ([time_left] seconds remaining)."))
Try using `DisplayTimeText` as Beagle had suggested.

2024-02-29 02:39 UTC, closed without merging