Legcuffs work
cmss13-devs/cmss13 pull request #5696
Opened 2024-02-10 21:29 UTC by realforest2001

# About the pull request
Allows legcuffs to function without needing to be beartraps.

# Explain why it's good for the game

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
add: Legcuffs work now.
/:cl:

2024-02-21 04:00 UTC, harryob requested changes

2024-02-21 04:00 UTC, harryob commented on code/game/objects/items/legcuffs.dm
it would be better to genericize this code between handcuffs/legcuffs, instead of copypasta

2024-03-11 16:52 UTC, Nanu308 approved these changes

2024-03-11 16:52 UTC, Nanu308 commented on maps/map_files/BigRed/BigRed.dmm
mapping moment lgtm

2024-05-06 21:51 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-05-06 21:53 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-05-09 20:23 UTC, harryob approved these changes

2024-05-09 20:28 UTC, merged