Seperating every port and starboard into three area each (fore midship aft)
cmss13-devs/cmss13 pull request #5699
Opened 2024-02-11 09:42 UTC by Huffie56

# About the pull request
1-Main idea is to split each Hallway area port and starboard into three areas.(fore midship aft)
2-Clean up the map to remove emergency shutter that are not acting as a frontier between areas.
3-removed unused areas.
4-rebuild structure of hallway area to have /lower and /upper areas.

# Explain why it's good for the game
1-Mainly good to allow better use of health monitor.
2-trying to standardize how emergency shutter are placed on the almayer
3-4 are refactor with no impact on player.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
maptweak: split each Hallway area port and starboard into three areas.(fore midship aft)
maptweak: change the area around north and south west staircase to remove emergency shutters.
maptweak: change the area west of squad preparation room to remove emergency shutter.
maptweak: change the area west of lower engi to make emergency shutter be at the frontier of the area.
/:cl:

2024-02-19 04:45 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-02-20 02:14 UTC, Nanu308 requested changes

2024-02-20 02:14 UTC, Nanu308 commented on code/game/area/almayer.dm
![bilde](https://github.com/cmss13-devs/cmss13/assets/59782240/9a581286-45b5-4bc5-8555-319ee248a839)
Naming Convention, "Port-Fore / Starboard-Fore"

2024-02-20 08:23 UTC, Huffie56 commented on code/game/area/almayer.dm
done

2024-02-22 13:26 UTC, Nanu308 approved these changes
seems fine now

2024-02-22 13:46 UTC, merged