Adds holo-targetting Vulture rounds
cmss13-devs/cmss13 pull request #5719
Opened 2024-02-14 10:19 UTC by VileBeggar

# About the pull request

Adds holo-targetting rounds for the Vulture. Their characteristics are:

- They deal SIGNIFICANTLY LESS damage, down from 400 to 60.
- They cannot penetrate walls nor mobs.
- They do not slow down mobs that are hit.
- When they hit a target, they will "mark them for death", inflicting a holo stack value of 333. This means that they will take 33% more damage from all sources. A balloon alert will be shown to all nearby mobs indicating the mark, along with the holo-target aura itself.

![image](https://github.com/cmss13-devs/cmss13/assets/17518895/094f75ec-2a61-48f1-b080-2d7c6f46643f)

The bullet increases the target's max capacity for holo stacks increases by 233 (to 333 in total). Any holo-targetting rounds that hit the mob will be able utilize this cap increase. The holo stacks will completely deplete after 35-ish seconds from the initial impact. It takes 5 seconds for the stack drain to begin, with every second passing after that removing 10 stacks. Other holo-targetting rounds will not modify the rate of stack depletion, keeping it at a firm 10 stacks per second. They will, however, stop the drain for 5 seconds.

![image](https://github.com/cmss13-devs/cmss13/assets/17518895/ad85d159-344b-407a-8158-23eafbf0824a)

# Explain why it's good for the game

This gun is really fun for the users, encouraging a buddy system that I feel the game desperately needs more of. I will admit that being hit with 400 damage, 50 AP from 2 screens away is not engaging for the opposing side, giving them no counterplay at all.

With these bullets, the Vulture can take a supporting role for the marines instead of being an off-screen death cannon. 33% is a decent damage increase, but it requires multiple marines around the target to truly take advantage of it. Careful positioning is still critical due to the lack of IFF, even more so considering the bullet now lacks penetrative properties. The ammo is still limited as ever, so the sniper team will have to pick their shots. Given how weak the rounds are in comparison to the standard ones, they should rarely be able to snipe off targets on their own (in a rare circumstance that they spot a half-crit xeno, an M4RA with a 4x scope can finish them off just the same). 

Is it weak? Too situational? Maybe, but the weapon is very interesting mechanically and I would just like to see it in play a bit more.

The weapon is still ADMIN-ONLY. This will only give the admins a less blunt variant of the Vulture if they choose to spawn in it.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

How being hit feels:

https://github.com/cmss13-devs/cmss13/assets/17518895/a576629e-7961-4421-9932-d707e12477f1

General test:

https://github.com/cmss13-devs/cmss13/assets/17518895/e2fbb117-1cf9-4945-b87a-d63e68f62a10

Bonus damage testing. The M41A does a base damage of 44. A holo-stack of 333 will result in roughly 44 * 1.33 = 59 damage.

![image](https://github.com/cmss13-devs/cmss13/assets/17518895/d230fc11-34e6-468e-89c3-394696c9b3e1)

</details>

# Changelog

:cl:
add: The Vulture can now be loaded with holo-targetting rounds which have severely hampered ballistic performance, but mark any target that is hit, increasing their damage taken by 33% for a brief period of time.
/:cl:

2024-02-15 06:22 UTC, Zonespace27 requested changes

2024-02-15 06:24 UTC, Zonespace27 reviewed
Interesting concept

2024-02-15 06:24 UTC, Zonespace27 commented on code/datums/components/bonus_damage_stack.dm
> +/datum/component/bonus_damage_stack/Initialize(bonus_damage_stacks, time, bonus_damage_cap_increase, stack_loss_multiplier)
Did you make sure to change all the addcomponent calls of this component?

2024-02-18 11:27 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-02-19 07:18 UTC, Zonespace27 requested changes

2024-02-19 07:18 UTC, Zonespace27 commented on code/datums/ammo/bullet/rifle.dm
> +	var/stack_loss_multiplier = 1
code doc

2024-02-19 07:18 UTC, Zonespace27 commented on code/datums/ammo/bullet/sniper.dm
> +	var/stack_loss_multiplier = 2 // multiplies the default holo stack drain of 5 stacks per second to 10
code doc

2024-02-19 07:18 UTC, Zonespace27 commented on code/datums/ammo/bullet/special_ammo.dm
> +	var/stack_loss_multiplier = 1
.

2024-02-19 07:18 UTC, Zonespace27 commented on code/datums/ammo/shrapnel.dm
> +	var/stack_loss_multiplier = 1
.

2024-02-19 11:09 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-02-19 23:43 UTC, Zonespace27 commented on code/datums/ammo/bullet/rifle.dm
> +	var/holo_stacks = 10 /// inflicts this many holo stacks per bullet hit
```
/// code doc needs to be like this
var/foo /// not like this
```

2024-02-20 19:09 UTC, Zonespace27 approved these changes
Might need some tweaking, but this is an admin item so it's not worth a TM

2024-02-20 19:18 UTC, merged