Brig Area Update/Refactor
cmss13-devs/cmss13 pull request #5723
Opened 2024-02-14 19:26 UTC by ItsVyzo

# About the pull request

Updates Brig Areas to be more concise with new design

# Explain why it's good for the game

People in X area of brig, hiding/dead/dying etc. are much easier to find. Also Mapper OCD

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl: LTNTS
add: brig areas: warden office, MP bunks, starboard hallway, interrogation room, evidence storage
spellcheck: changes brig surgery to brig medical
/:cl:

2024-02-19 04:45 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-02-20 01:29 UTC, Nanu308 requested changes
New Areas but no placed APC's for those areas and rooms that were added?

2024-02-20 16:52 UTC, ItsVyzo commented
> New Areas but no placed APC's for those areas and rooms that were added?

I need to stop forgetting things q=q

fixing

2024-02-24 04:45 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-02-24 04:59 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-02-25 09:10 UTC, Nanu308 requested changes

2024-02-25 09:10 UTC, Nanu308 commented on maps/map_files/USS_Almayer/USS_Almayer.dmm
Needs the rewire semiotic added for the new APC's

2024-02-26 22:09 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-02-27 01:20 UTC, Nanu308 approved these changes
lgtm

2024-02-27 01:25 UTC, merged