Refactor marine_armor.dm and split it into multiples files.
cmss13-devs/cmss13 pull request #5740
Opened 2024-02-17 12:58 UTC by Huffie56

# WIP just here for the test we will see after.

# About the pull request

# Explain why it's good for the game

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
refactor: refactor marine_armor.dm and split it into multiples files.
/:cl:

2024-02-21 03:54 UTC, harryob requested changes

2024-02-21 03:54 UTC, harryob commented on code/modules/clothing/suits/marine_armor/_spe_fire.dm
spe_fire? presumably should be spec

2024-02-21 03:54 UTC, harryob commented on code/modules/clothing/suits/marine_armor/marine_armor.dm
to be pedantic, the parent type file (this one) should have the _marine_armor.dm, and the rest should just be intel.dm, smartgunner.dm, spec_fire.dm, ghillie.dm, ert.dm, etc

2024-02-21 07:59 UTC, Huffie56 commented on code/modules/clothing/suits/marine_armor/marine_armor.dm
i don't know it feel more clear to me when everything is at the same place ....
specially since their is still children of the armor inside parent file...
and also i don't think refactor of it is over...

2024-02-21 09:56 UTC, harryob commented on code/modules/clothing/suits/marine_armor/marine_armor.dm
> i don't know it feel more clear to me when everything is at the same place .... specially since their is still children of the armor inside parent file... and also i don't think refactor of it is over...

they shouldn't be moved, it's just the name of the files. we use _ before the file of the name to indicate that it's the *parent* type, like `code/modules/unit_tests/_unit_tests.dm`, and every unit test is actually in `code/modules/unit_tests/autowiki.dm`

2024-02-21 10:23 UTC, Huffie56 commented on code/modules/clothing/suits/marine_armor/marine_armor.dm
just adding _ in front ok.

2024-02-23 12:17 UTC, SabreML reviewed
I think what Harry meant was to add an underscore to the name of the main 'parent' file (`_marine_armor.dm`), but have the rest be named normally. Like this:
![image](https://github.com/cmss13-devs/cmss13/assets/57483089/03518d8d-5e08-4bb2-871b-bc6b03723ed1)
<hr>

Other than that though, looks good to me!

2024-02-23 12:17 UTC, SabreML commented on code/modules/clothing/suits/marine_armor/_ert.dm
> +//=======================================================================\\
Caps lock was on I think :P
```suggestion
//=============================//PMCs\\==================================\\
//=======================================================================\\
```

2024-02-24 13:16 UTC, SabreML approved these changes

2024-02-24 20:28 UTC, merged