Map: Bigred change south lambda padlock and making it so that lambda as it's seperate elec network
cmss13-devs/cmss13 pull request #5763
Opened 2024-02-20 14:19 UTC by Huffie56

# About the pull request

# Explain why it's good for the game
1-change to south padlock will unlock possibility for an easier push (this choke is very hard to push currently.)
2-seperating the power network of lambda make sense to me and will give player some challenge if they want to secure the area.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
code: Made it so that lambda facility use have a separate electrical network.
refactor: refactored the lambda areas.
maptweak: turned south padlock into a checkpoint.

/:cl:

2024-02-20 20:07 UTC, Huffie56 commented
need to replace the hull wall and add some gore and blood

2024-02-22 21:39 UTC, Huffie56 commented
weird  computer in admin changed dir...

2024-02-25 22:34 UTC, Nanu308 requested changes
![bilde](https://github.com/cmss13-devs/cmss13/assets/59782240/d23e45bb-3c22-4b15-af09-888efab06729)
Move the Vehicle blockers a bit more west as showcased, also, will need to test it as its quite significant gameplay change when it comes to the flow of the map.

2024-03-01 13:23 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-03-31 13:53 UTC, SabreML approved these changes

2024-03-31 13:53 UTC, SabreML commented on code/game/area/BigRed.dm
> +// all the lambda area bellow.
Wouldn't be worth bugging you with a review for something this small:
```suggestion
// Lambda areas below:
```

2024-03-31 14:04 UTC, merged