Vehicle bay elevator stuff
cmss13-devs/cmss13 pull request #5851
Opened 2024-02-29 18:11 UTC by SabreML

# About the pull request

Makes the Vehicle Bay elevator work better.
Specifically:
- Adds some ASRS sound effects, and tweaks the timing of various elements to line up with them.
- Adds the pre-existing vehicle bay elevator shaft sprite for when the elevator has been lowered. (No animation yet though)
- Adds `\proper` to `/turf/open/floor/almayer/empty` and the elevator shaft effect to change the grammar of its examine text:
**Before/After:**
![before](https://github.com/cmss13-devs/cmss13/assets/57483089/d4fbf696-4f2c-47e3-8a7f-8f655112b9ff) ![after](https://github.com/cmss13-devs/cmss13/assets/57483089/1d883dec-306d-4605-88d5-97c1832b7428)
- Fixes(?) the front guard rails not raising when the elevator is lowered.
- Fixes a bug where the shipside docking port for the would fall into the elevator shaft after the elevator left:
![image](https://github.com/cmss13-devs/cmss13/assets/57483089/5cf513a4-118b-4567-8c71-d26d53585542)
- Fixes an oversight where a human falling into the vehicle bay elevator shaft would be teleported to the requisitions elevator.
- Fixes the gear things at the corners of the elevator spinning constantly until it's called back up.

(See comparison videos below)

# Explain why it's good for the game

The vehicle bay elevator doesn't get used often, but it *does* get used. This will hopefully make it feel a bit less janky.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

### Sending the elevator down and up again:
(In-game sound on both videos)

**Before:**

https://github.com/cmss13-devs/cmss13/assets/57483089/5fba87cd-2ef5-42ea-81f7-dc9872e4b622

**After:**

https://github.com/cmss13-devs/cmss13/assets/57483089/3f833e89-3e52-4fee-9f07-2c376ab2000b

</details>

(I've also tested this with #5401, and it seems to work without any issues.)

# Changelog

:cl:
add: Made the vehicle bay elevator look and sound better when in use.
fix: Fixed the vehicle bay elevator's front railings not closing when the elevator was lowered.
fix: Fixed the vehicle bay elevator's docking port falling down the elevator shaft when it was lowered.
fix: Fixed falling into the vehicle bay elevator shaft teleporting players to the requisitions elevator.
/:cl:

2024-03-01 03:05 UTC, Nanu308 approved these changes

2024-03-01 03:05 UTC, Nanu308 commented on maps/map_files/USS_Almayer/USS_Almayer.dmm
mapping lgtm

2024-03-03 12:30 UTC, Drulikar requested changes
Everything here appears to be working; though I think we should also fix a couple other aspects while we're at it:

`/obj/structure/machinery/door_control/railings/use_button` early returns on `if(!is_mainship_level(SSshuttle.vehicle_elevator.z))` even if the railing is down (desiredstate is 1). We should always allow railing to go up.

~~`SSshuttle.vehicle_elevator.timeLeft()` should be changed to `shuttle.has_arrive_time()` so its isn't just always "Moving" (looking for the actual reference to the shuttle atm)

2024-03-03 13:44 UTC, Drulikar approved these changes

2024-03-03 13:52 UTC, merged