Fiorina Nightmare Insert
cmss13-devs/cmss13 pull request #5857
Opened 2024-03-01 18:41 UTC by BadAtThisGame302

# About the pull request

The Fiorina Prison has seen more and more unrest the last few years, quelling it down with the dwindling manpower. One such instance, the CMB picked up a beacon that was sent from the Prison. Thinking it was another riot, they asked for some Riot Control officers and sent them with a CMB Deputy to oversee the pacification of the station.

With no greetings at the LZ, they headed to the Armory to speak to someone in command. What they did not account for was that.. this was no riot, not anymore at least. The Security Hub is littered with both prisoner and Security forces corpses. Some sort of green blood and heavy fortifications. A team member snatched in the darkness and his screams silencing after a couple of seconds prove that... there's nobody left. 

You must survive until the CMB or some other force finds you.. and saves you before it's too late.

# Explain why it's good for the game

Woohooo nightmare insert baby yeayh

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
mapadd: added a new Fiorina nightmare insert with CMB and UA Officers responding to the distress signal.

2024-03-05 07:11 UTC, Nanu308 requested changes

2024-03-05 07:11 UTC, Nanu308 commented on maps/map_files/FOP_v3_Sciannex/standalone/riot_in_progress.dmm
See Discord comment

2024-03-05 07:11 UTC, Nanu308 commented on code/game/objects/effects/landmarks/survivor_spawner.dm
Run the fluff text by the lore team if you haven't already, but from a quick read seems fine. 👍

2024-03-06 00:31 UTC, BadAtThisGame302 commented on code/game/objects/effects/landmarks/survivor_spawner.dm
Kaga fluffed it up, should be good.

2024-03-06 00:31 UTC, BadAtThisGame302 commented on maps/map_files/FOP_v3_Sciannex/standalone/riot_in_progress.dmm
Removed hull walls.

2024-03-06 10:45 UTC, Nanu308 approved these changes
mapping lgtm

2024-03-06 19:34 UTC, harryob approved these changes

2024-03-06 23:57 UTC, Drulikar commented
CI requires fixes from #5891

2024-03-07 12:08 UTC, merged