Adds Professor DUMMY to the Morgue
cmss13-devs/cmss13 pull request #5874
Opened 2024-03-03 22:23 UTC by Vicacrov

# About the pull request

Adds Professor DUMMY (and its tablet) to the morgue's operating room. It is a tool for new nurses(!!) and doctors to learn medical treatment, including surgery. I added it to the morgue so it is not in the way; it can be easily dragged to lower medbay if it medbay wants to use it.

It dusts upon hijack, to avoid either side having a godmoded mob.

# Explain why it's good for the game

It is a tool for new medical personnel to practice on. It can also ease boredom if the round is going too smoothly for marines.

# Testing Photographs and Procedure

Setting up the tablet and hijacking:

<details>
<summary>Screenshots & Videos</summary>

https://github.com/cmss13-devs/cmss13/assets/49321394/563db21d-ebc2-41e0-a8e8-764f9b8aa61b

</details>

# Changelog

:cl:
add: Added Professor DUMMY and its tablet to the Morgue. New nurses and doctors can practice medical treatment on it, including surgery.
/:cl:

2024-03-03 22:24 UTC, ihatethisengine commented
maybe just make it uninteractable on hijack?

2024-03-03 22:25 UTC, Vicacrov commented
> maybe just make it uninteractable on hijack?

Dusting might be a bit jarring, but having a human-looking mob nobody can interact with would be more disruptive, I think.

2024-03-04 04:57 UTC, Drulikar requested changes
This needs to instead be in the SEA vendor where its unhackable and otherwise then falls under the responsibility of the SEA that lent it to someone to use to put it away.

If you also want CMOs to access it, then they'd need a similar situation where only they (or a SEA) can vend it.

As of now, its the responsibility of the admin that spawned it to ensure it doesn't get misused.

2024-03-04 18:25 UTC, Vicacrov commented
Implemented changes:
- Made a new subtype for this dummy as I realised the character setup one was the same.
- Reverted the Morgue changes.
- The dummy now dusts upon hijack impact, not upon hijack start (code bloat on my part).
- Added a special closet to the CMO office, the "professor dummy cabinet".
  - It can be only opened with a CMO or SEA **job**, not access. (Not even a CO ID helps here.)
  - It cannot be flashbanged, slashed, or melted.
  - When the dummy falls out, everyone around the closet gets a warning how it should not be misused - this also covers the edge case where it gets destroyed by unconventional means. Ignorance is not an excuse when you get a red text this big.
  - The closet can store mobs but it fails to close if there is any other mob on its tile but the dummy. (No hiding in the indestructible closet.)

![image](https://github.com/cmss13-devs/cmss13/assets/49321394/395313d0-9c95-4a7c-a75e-585e4c814223)

![image](https://github.com/cmss13-devs/cmss13/assets/49321394/632c6bff-02dc-428b-9d21-4f5acedd9db8)

2024-03-05 07:13 UTC, Nanu308 approved these changes

2024-03-05 07:13 UTC, Nanu308 commented on maps/map_files/USS_Almayer/USS_Almayer.dmm
mapping lgtm

2024-03-05 14:37 UTC, Drulikar requested changes

2024-03-05 14:37 UTC, Drulikar commented on code/modules/mob/living/carbon/human/human_dummy.dm
> +	mob_flags |= EASY_SURGERY
You are missing `huggable = FALSE` like `/datum/equipment_preset/other/professor_dummy/load_race` used to do.

2024-03-05 14:37 UTC, Drulikar commented on code/game/objects/structures/crates_lockers/closets/secure/medical.dm
> +/obj/structure/closet/secure_closet/professor_dummy/emp_act(severity)
ex_act also needs to be implemented the same way. Throw a HE grenade near it and it'll dump the contents out.

2024-03-05 14:37 UTC, Drulikar commented on code/modules/gear_presets/other.dm
> -/datum/equipment_preset/other/professor_dummy
Removing this means it is no longer in the create humans menu; which is generally how its been spawned. It'd probably be better to just keep the preset but have your closest spawn the equipment preset into the closet.

2024-03-05 14:37 UTC, Drulikar commented on code/game/objects/structures/crates_lockers/closets/secure/medical.dm
> +		if(!istype(M, /mob/living/carbon/human/dummy/professor_dummy))
```suggestion
	for(var/mob/current_mob in loc)
		if(!istype(current_mob, /mob/living/carbon/human/dummy/professor_dummy))
```
No single letter vars please: https://github.com/cmss13-devs/cmss13/blob/master/.github/guides/STYLES.md#dont-use-abbreviations

2024-03-05 14:37 UTC, Drulikar commented on code/game/objects/structures/crates_lockers/closets/secure/medical.dm
> +	..()
```suggestion
	return ..()
```
The other implementations are returning TRUE/FALSE/1/0

2024-03-05 14:37 UTC, Drulikar commented on code/game/objects/structures/crates_lockers/closets/secure/medical.dm
> +		return
```suggestion
		return ..()
```
Although nothing normally is returned, since you're returning anyways you may as well.

2024-03-05 14:37 UTC, Drulikar commented on code/modules/mob/living/carbon/human/human_dummy.dm
> +	if(is_mainship_level(z))
A closet's loc is not considered is_mainship_level you need to get_turf

2024-03-05 14:38 UTC, Drulikar commented on code/game/objects/structures/crates_lockers/closets/secure/medical.dm
> +	for(var/mob/living/carbon/human/dummy/professor_dummy/dummy in src)
If there only will ever be one dummy we can instead do something like
```js
var/mob/dummy = locate(/mob/living/carbon/human/dummy/professor_dummy) in src
if(dummy)
	qdel(dummy)
```

2024-03-05 14:41 UTC, Drulikar commented on code/modules/gear_presets/other.dm
> -/datum/equipment_preset/other/professor_dummy
See https://github.com/cmss13-devs/cmss13/blob/master/code/modules/admin/topic/topic_events.dm#L151-L159 how create_humans uses these presets. You likely just need to create the mob, and then `arm_equipment` it.

2024-03-05 14:48 UTC, Drulikar commented on code/modules/gear_presets/other.dm
> -/datum/equipment_preset/other/professor_dummy
If the concern was just not registering the signal for admin spawned; then have the closet register the signal for that spawn on the dummy's behalf (as in we aren't registering a signal on the closet, but the closet's initialize call is having the dummy register the signal)

2024-03-05 15:18 UTC, Drulikar commented on code/modules/gear_presets/other.dm
> -/datum/equipment_preset/other/professor_dummy
Relayed on discord, but putting it here too. Something like
```js
/obj/structure/closet/secure_closet/professor_dummy/Initialize()
    . = ..()
    var/mob/living/carbon/human/dummy/professor_dummy/spawned_dummy = new(src)
    var/datum/equipment_preset/dummy_preset = /datum/equipment_preset/other/professor_dummy
    arm_equipment(spawned_dummy, initial(dummy_preset.name), TRUE, FALSE)
    spawned_dummy.RegisterSignal(SSdcs, COMSIG_GLOB_HIJACK_LANDED, TYPE_PROC_REF(/mob/living/carbon/human/dummy/professor_dummy, destroy_upon_hijack))```
should work. The signal registration here is just if we want only closet dummies to dust; but I don't mind admin spawns having the same signal either if they're on a game level z.

2024-03-05 15:53 UTC, Drulikar requested changes

2024-03-05 15:53 UTC, Drulikar commented on code/game/objects/structures/crates_lockers/closets/secure/medical.dm
> +	spawned_dummy.RegisterSignal(SSdcs, COMSIG_GLOB_HIJACK_LANDED, TYPE_PROC_REF(/mob/living/carbon/human/dummy/professor_dummy, destroy_upon_hijack))
```suggestion
```

2024-03-05 15:53 UTC, Drulikar commented on code/modules/mob/living/carbon/human/human_dummy.dm
> +/mob/living/carbon/human/dummy/professor_dummy/proc/destroy_upon_hijack()
```suggestion
/mob/living/carbon/human/dummy/professor_dummy/Initialize(mapload)
	. = ..()
	RegisterSignal(SSdcs, COMSIG_GLOB_HIJACK_LANDED, PROC_REF(destroy_upon_hijack))

/mob/living/carbon/human/dummy/professor_dummy/proc/destroy_upon_hijack()
```

2024-03-05 16:03 UTC, Drulikar approved these changes

2024-03-05 16:11 UTC, Drulikar commented
Feel free to undraft (Ready for review button near the bottom) when you're happy with it.

2024-03-05 17:04 UTC, merged