Vehicle and hardpoints repair changes
cmss13-devs/cmss13 pull request #588
Opened 2022-06-29 12:16 UTC by JeserTheFox

## About The Pull Request

Instead of repairing 10% of health with timed actions with different timers, it now loops 1 second timed action repair with accordingly adjusted amount repaired for as long as there is fuel (if welder is used) and health is below max health. Engineering level afflicts how much is repaired now. Overall time of repairs should remain more or less the same.

## Why It's Good For The Game

Timed actions with long timers are not good when used for gradual progression process like welding something. Inspired by sandbags refilling rework.

## Changelog

:cl: Jeser
qol: Repairing vehicles and vehicle modules was reworked to be more convenient.
add: Wheels and tracks are being repaired twice slower now, because it was way too fast before.
/:cl:

2022-07-01 16:03 UTC, stanalbatross requested changes
also, this consumes a LOT more fuel than the prior system - roughly 40 fuel to repair 400 part health, for example. Maybe oversight?

2022-07-01 16:03 UTC, stanalbatross commented on code/modules/vehicles/hardpoints/hardpoint.dm
> +		to_chat(user, SPAN_NOTICE("Integrity of \the [src] is now at [SPAN_HELPFUL(round(get_integrity_percent()))]%."))
```suggestion
		to_chat(user, SPAN_NOTICE("The integrity of \the [src] is now at [SPAN_HELPFUL(round(get_integrity_percent()))]%."))
```
```suggestion
		to_chat(user, SPAN_NOTICE("Integrity of \the [src] is now at [SPAN_HELPFUL(round(get_integrity_percent()))]%."))
```

2022-07-01 16:03 UTC, stanalbatross commented on code/modules/vehicles/hardpoints/hardpoint.dm
> +			user.visible_message(SPAN_NOTICE("[user] finishes repairing \the [name]."), SPAN_NOTICE("You finish repairing \the [name]. Integrity of \the module is at [SPAN_HELPFUL(round(get_integrity_percent(
```suggestion
			user.visible_message(SPAN_NOTICE("[user] finishes repairing \the [name]."), SPAN_NOTICE("You finish repairing \the [name]. Integrity of the module is at [SPAN_HELPFUL(round(get_integrity_percent()))]%."))
```
```suggestion
			user.visible_message(SPAN_NOTICE("[user] finishes repairing \the [name]."), SPAN_NOTICE("You finish repairing \the [name]. The integrity of \the module is at [SPAN_HELPFUL(round(get_integrity_percent()))]%."))
```

2022-07-01 16:03 UTC, stanalbatross commented on code/modules/vehicles/hardpoints/hardpoint.dm
> +			user.visible_message(SPAN_NOTICE("[user] stops repairing \the [name]."), SPAN_NOTICE("You stop repairing \the [name]. Integrity of the module is at [SPAN_HELPFUL(round(get_integrity_percent()))]%.
```suggestion
			user.visible_message(SPAN_NOTICE("[user] stops repairing \the [name]."), SPAN_NOTICE("You stop repairing \the [name]. The integrity of the module is at [SPAN_HELPFUL(round(get_integrity_percent()))]%."))
```
```suggestion
			user.visible_message(SPAN_NOTICE("[user] stops repairing \the [name]."), SPAN_NOTICE("You stop repairing \the [name]. Integrity of the module is at [SPAN_HELPFUL(round(get_integrity_percent()))]%."))
```

2022-07-01 16:03 UTC, stanalbatross commented on code/modules/vehicles/hardpoints/hardpoint.dm
> +	user.visible_message(SPAN_NOTICE("[user] stops repairing \the [name]."), SPAN_NOTICE("You stop repairing \the [name]. Integrity of \the module is at [SPAN_HELPFUL(round(get_integrity_percent()))]%."
```suggestion
	user.visible_message(SPAN_NOTICE("[user] stops repairing \the [name]."), SPAN_NOTICE("You stop repairing \the [name]. The integrity of the module is at [SPAN_HELPFUL(round(get_integrity_percent()))]%."))
```
```suggestion
	user.visible_message(SPAN_NOTICE("[user] stops repairing \the [name]."), SPAN_NOTICE("You stop repairing \the [name]. Integrity of \the module is at [SPAN_HELPFUL(round(get_integrity_percent()))]%."))
```

2022-07-01 19:27 UTC, JeserTheFox commented
> also, this consumes a LOT more fuel than the prior system - roughly 40 fuel to repair 400 part health, for example. Maybe oversight?

Increase in fuel consumption is intended, yes.

2022-07-02 15:24 UTC, stanalbatross approved these changes

2022-07-02 15:25 UTC, stanalbatross commented
merging as code + archi approved

2022-07-02 15:25 UTC, merged