Drop Pouch Buff
cmss13-devs/cmss13 pull request #5902
Opened 2024-03-08 04:17 UTC by Staykeu

# About the pull request

The intention behind this PR is to see the drop pouch used more often as a middle ground between the magazine webbing and large webbing. Adds two more small item spaces (one medium item space). The drop pouch carries either two large items (unchanged), four medium sized items, or eight small items. 

# Explain why it's good for the game

The drop pouch is rarely ever used, mostly by smartgunners who need a few extra drums. This should change that. It brings the drop pouch up from a niche "(worse) large pouch but for your webbing slot" to a middler between the magazine webbing and large webbing, mag webbing is still better for packing mags, like it always has been, and large webbing is still better for packing medium sized items, which are most of the items a marine would be packing.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl: Stakeyng
balance: Drop pouch has more space (2 large (unchanged), 4 medium, 8 small)
/:cl:

2024-03-08 04:24 UTC, Drulikar requested changes

2024-03-08 04:24 UTC, Drulikar commented on code/game/objects/items/storage/pouch.dm
Revert the changes to this file

2024-03-08 11:21 UTC, private-tristan commented on code/modules/clothing/under/ties.dm
> +	max_storage_space = 8 //weight system like backpacks, hold enough for 2 medium (normal) size items, or 3 small items, or 6 tiny items
```suggestion
	max_storage_space = 8 //weight system like backpacks, hold enough for 2 medium (normal) size items, or 4 small items, or 8 tiny items
```

2024-03-11 20:38 UTC, Drulikar approved these changes

2024-03-11 20:44 UTC, merged