Changes to SG vendor add more sidearm ammo type and move SG drum from prep directly in is belt.
cmss13-devs/cmss13 pull request #5913
Opened 2024-03-10 10:44 UTC by Huffie56

# About the pull request
Created new belt subtype just for USCM/SG...

# Explain why it's good for the game

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
balance: move the SG drum that is in squad prep ammo vendor directly inside the SG belt.
balance: adding M44 Marksman Speed Loader and SU-6 Smartpistol Magazine in vendor of (rifleman, TL, IO) at a cost of 10 each.
/:cl:

2024-03-10 10:45 UTC, Huffie56 commented
need to still add the option to buy extra SG batteries.

2024-03-11 21:06 UTC, Drulikar requested changes
I am not really keen on the primary goal of this PR: moving the SG drums from prep vendors to the SG vendor. I don't think foxtrot SGs need the additional ammo.

2024-03-11 21:06 UTC, Drulikar commented on code/game/machinery/vending/vendor_types/squad_prep/squad_smartgunner.dm
> +		list("smartgun DV9 battery", 15, /obj/item/smartgun_battery, null, VENDOR_ITEM_REGULAR),
```suggestion
		list("Smartgun DV9 Battery", 15, /obj/item/smartgun_battery, null, VENDOR_ITEM_REGULAR),
```

2024-03-12 07:47 UTC, Huffie56 commented
> I am not really keen on the primary goal of this PR: moving the SG drums from prep vendors to the SG vendor. I don't think foxtrot SGs need the additional ammo.

balance wise if it's better i can move the extra SG drum to req instead of adding it to the SG belt?

2024-03-13 06:31 UTC, Drulikar commented
> balance wise if it's better i can move the extra SG drum to req instead of adding it to the SG belt.

I'd prefer it left as is.

2024-03-13 09:55 UTC, Huffie56 commented on code/game/objects/items/storage/belt.dm
> +
ok

2024-03-13 09:56 UTC, Huffie56 commented on code/game/machinery/vending/vendor_types/squad_prep/squad_smartgunner.dm
ok

2024-03-13 09:57 UTC, Huffie56 commented on code/game/machinery/vending/vendor_types/squad_prep/squad_smartgunner.dm
> +		list("M280 Smartgunner Drum Belt", 0, /obj/item/storage/belt/marine/smartgunner/uscm/filled, MARINE_CAN_BUY_BELT, VENDOR_ITEM_MANDATORY),
ok

2024-03-13 09:58 UTC, Huffie56 commented on code/game/objects/items/storage/belt.dm
> +
ok

2024-03-14 07:30 UTC, Drulikar approved these changes

2024-03-14 07:41 UTC, merged