Dropship doors can now always be broken by queen
cmss13-devs/cmss13 pull request #5917
Opened 2024-03-10 16:17 UTC by ihatethisengine

# About the pull request

This PR is a follow up to https://github.com/cmss13-devs/cmss13/pull/5808 removing a locked check to break the doors.

# Explain why it's good for the game

Now regardless of currently locked or open, the queen can break the doors to prevent further door spamming.

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl: ihatethisengine2
fix: Dropship door prying can now always be performed by queen even if open or not locked
/:cl:

2024-03-10 16:25 UTC, Drulikar requested changes

2024-03-10 16:25 UTC, Drulikar commented on code/game/machinery/doors/multi_tile.dm
>  		open(1)
```suggestion
		open(TRUE)
```

2024-03-10 16:32 UTC, Drulikar approved these changes
Thanks

2024-03-11 06:21 UTC, ihatethisengine commented
Moved the thing up in case someone tries to spam the doors while they are being open (which is not instant).

2024-03-11 20:21 UTC, merged