Weed update
cmss13-devs/cmss13 pull request #5924
Opened 2024-03-11 22:20 UTC by PhantomEpicness

# About the pull request
Makes space weed recognizable with new sprites and actually more impactful to the game.

# Explain why it's good for the game
MPs now can actually spot and see space weed being used by marines. Drug users can puff smoke which gives a small second hand smoke effect to people nearby while significantly impacting the smoke time.

# Testing Photographs and Procedure

![image](https://github.com/cmss13-devs/cmss13/assets/42422230/5ddc513a-ab6e-4734-acaf-fb7b44021d3b)

<details>
<summary>Screenshots & Videos</summary>
![image](https://github.com/cmss13-devs/cmss13/assets/42422230/89feed62-c88c-4a5e-9db2-3083e50e9f73)

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl: totalepicness5
add: New ability for space weed smokers to puff a cloud of smoke at the cost of burning a lot of the blunt. Watch out MPs!
imageadd: Space weed now actually has it's own sprites
/:cl:

2024-03-11 22:45 UTC, Birdtalon requested changes
Not a full review just a few things noticed.

2024-03-11 22:45 UTC, Birdtalon commented on code/game/objects/effects/effect_system/smoke.dm
> +	alpha = 75
Override variables before declaring new ones. Also you don't use this new var.

```suggestion
	opacity = FALSE
	alpha = 75
	var/xeno_affecting = TRUE
```

2024-03-11 22:45 UTC, Birdtalon commented on code/game/objects/items/tools/flame_tools.dm
> +	if(!usr || usr.is_mob_incapacitated(TRUE))
```suggestion
	if(!smoker || smoker.is_mob_incapacitated(TRUE))
```

2024-03-11 22:45 UTC, Birdtalon commented on code/game/objects/items/tools/flame_tools.dm
> +	var/mob/living/carbon/human/H = owner
Please use full named vars not single letters.

2024-03-11 22:56 UTC, sleepynecrons requested changes
blunt_on and blunt_off have swapped animations in righthand_0.dmi 
everything else (sprite-wise) is fine

2024-03-12 02:47 UTC, Zonespace27 requested changes

2024-03-12 02:47 UTC, Zonespace27 commented on code/game/objects/effects/effect_system/smoke.dm
> +		if (affected.internal != null && affected.wear_mask && (affected.wear_mask.flags_inventory & ALLOWINTERNALS))
```suggestion
		if (affected.internal && affected.wear_mask && (affected.wear_mask.flags_inventory & ALLOWINTERNALS))
```

2024-03-12 02:47 UTC, Zonespace27 commented on code/game/objects/effects/effect_system/smoke.dm
> +				affected.coughedtime = 1
world.time will always be < 1
also use a COOLDOWN_ macro

2024-03-12 02:47 UTC, Zonespace27 commented on code/game/objects/items/tools/flame_tools.dm
> +	var/datum/effect_system/smoke_spread/smoke
code doc

2024-03-12 02:47 UTC, Zonespace27 commented on code/game/objects/items/tools/flame_tools.dm
> +	set desc = "Puff a fat cloud"
```suggestion
	set desc = "Puff a fat cloud."
```

2024-03-12 02:47 UTC, Zonespace27 commented on code/game/objects/items/tools/flame_tools.dm
> +	var/datum/effect_system/smoke_spread/smoke = new /datum/effect_system/smoke_spread/weed
why create a new var when `smoke` is already on the object?

2024-03-12 02:47 UTC, Zonespace27 commented on code/game/objects/items/tools/flame_tools.dm
> +	var/datum/effect_system/smoke_spread/smoke
qdel_null on destroy

2024-03-12 02:47 UTC, Zonespace27 commented on code/game/objects/items/tools/flame_tools.dm
> +	smoketime =- 4 MINUTES // Burns it a lot faster when
```suggestion
	smoketime -= 4 MINUTES // Burns it a lot faster when
```
when what

2024-03-12 02:47 UTC, Zonespace27 commented on code/game/objects/items/tools/flame_tools.dm
> +	smoker.visible_message(SPAN_NOTICE("[src] takes a massive breath!"),\
src is a cigarette

2024-03-12 02:47 UTC, Zonespace27 commented on code/game/objects/items/tools/flame_tools.dm
> +	if(!can_puff)
```suggestion
		return
		
	if(smoker.wear_mask != src)
		return
		
	if(!can_puff)
```

2024-03-12 02:47 UTC, Zonespace27 commented on code/game/objects/items/tools/flame_tools.dm
> +		to_chat(smoker,SPAN_NOTICE("Your lungs lack fresh air, chill man."))
add spacing between a comma and the next entry

2024-03-12 02:47 UTC, Zonespace27 commented on code/game/objects/items/tools/flame_tools.dm
> +	if(icon_on == "blunt_off")
this is gross and you shouldn't be checking icon states to see if something is true/false

2024-03-12 02:47 UTC, Zonespace27 commented on code/game/objects/items/tools/flame_tools.dm
> +	button.overlays += IMG
can you not set this on the action itself?

2024-03-12 02:47 UTC, Zonespace27 commented on code/game/objects/items/tools/flame_tools.dm
> +	name = "Puff"
why are you setting this in New() instead of on the action?

2024-03-12 02:47 UTC, Zonespace27 commented on code/game/objects/items/trash.dm
> +	name  = "roach"
```suggestion
	name = "roach"
```

2024-04-01 09:55 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-04-17 01:01 UTC, closed without merging