[Bugfix] Flamer's damage should be approriate for objects that handle it
cmss13-devs/cmss13 pull request #595
Opened 2022-06-30 21:00 UTC by TeDGamer

## About The Pull Request
Instead of objects taking 0 damage, they now take damage similar to the turf. The damage is based on the flamer fuel.

Objects that will now take flame damage approriately:
- Barricades ( /obj/structure/barricade/flamer_fire_act ). Yes, make sure not to flame your own cades
- Thickbush (/obj/structure/flora/jungle/thickbush)
- Alien doors ( /obj/structure/mineral_door/resin)

## Why It's Good For The Game
One of the weird things I see in the game after fixing the flamers melting walls is now doors are left standing. So after an incidenary OB, you would see every xeno wall burn but the doors are strong, so strong they survive if they still have support. This never really made sense to me so I took a look at the code and found that objects have 0 damage which makes no sense imo since there's code to handle damage for certain objects like mentioned above ( doors, thickbush and barricades).

This fixes the issue where resin doors are impossible to burn down. This however introduces barricades being burned ( since it has it's own handler that takes damage ) so flamers need to be more careful not to flame their own cades or at least put out the fire if the barricade is on fire.

## Changelog

:cl: TeDGamer
fix: Flamers should deal non-zero damage to objects appropriately (resin doors, barricades, thickbush ).
/:cl:

2022-06-30 23:21 UTC, sose96 commented
I think it should depend on fire type. 
Basic bitch fire is not going to melt a solid steel/titanium cade, whereas OB giga fire probably would.

2022-07-01 00:07 UTC, TeDGamer commented
> I think it should depend on fire type. Basic bitch fire is not going to melt a solid steel/titanium cade, whereas OB giga fire probably would.

I would assume that's what the burn multiplier would be for. Sadly, I'm not allowed to touch numbers. This is basically just changing what should be a 0 to an actual number like it used to be + modifying it based on the flame due to new fire changes between the cause_data time and now.

Sadly, I'm only contributing to fix the bug, not balance

2022-07-01 07:56 UTC, JeserTheFox commented
Flamer fire still burns resin walls, just slowly, unless it's X napalm or something even stronger.

2022-07-01 10:41 UTC, Nanu308 commented
This in essence is fine for fixing an issue, but numbers may need to see some tweaks further down the line.

2022-07-01 14:54 UTC, TeDGamer commented
> I know for a fact, that flamer fire still burns resin walls and doors, just slowly, unless it's X napalm or something even stronger. Cades also take damage from flames right now.

Yeah I made the resin wall burn change on gitlab. Resin walls are turf so that's the turf code that you see being slightly changed in this PR. That's the burn over time.

For doors, it's likely just the applied effect on the flamer on click similar to how it used to be for walls. Same for cades, just the applied effect of the flamer on hit rather than the fire tile itself damaging objects.

> This in essence is fine for fixing an issue, but numbers may need to see some tweaks further down the line.

Sounds good to me. Should be easy enough to modify the formula of any of the fire_flamer_act specifically to the object itself.

2022-07-05 16:18 UTC, TeDGamer commented
> Flamers already damage marine barricades; unless there's something funny going on this shouldn't change anything with respect to flamers and cades as they already are.

That might on hit. This is DoT.

The PR itself is relatively simple, you can see all I'm changing is 0 damage to objects (mainly relevant to the three posted above: resin doors, barricades, thickbush) to a non-zero value / damage, similar to the turf damage in the same code ( this handles the burning of resin walls )

2022-07-06 20:19 UTC, Geevies requested changes

2022-07-06 20:23 UTC, TeDGamer commented on code/modules/projectiles/guns/flamer/flamer.dm
> +	var/damage = burnlevel*delta_time
Done!

2022-07-07 18:25 UTC, Geevies approved these changes

2022-07-10 12:17 UTC, stanalbatross approved these changes

2022-07-10 12:17 UTC, merged