Converts pyro armour to light and minor GL armour tweaks
cmss13-devs/cmss13 pull request #5970
Opened 2024-03-18 00:31 UTC by Mister-moon1

# About the pull request
Converts pyro's m35 pyrotechnician armour into light armour using the ghillie suit armour values and changes GL's armour to having 5 light range since it should be included with heavy armour, which does have the 5 light range

# Explain why it's good for the game
Pyro is undoubtedly the one spec that will be pointmanning which often requires mobility and ability to chase which is not supported by the slow nature enforced by the current armour, every other spec role other than GL has armour that has light tier slowdown.

With this PR I have matched the stats of pyro armour with the ghillie suit which seems fair considering they both have their utility factors with supply being limited to the spec role

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
balance: stat changed pyro armour and slowdown values to match ghillie armour
balance: increased GL armour light range to properly match other armours like it.
/:cl:

2024-03-18 02:50 UTC, PhantomEpicness commented
Pyro is centered around area control and denial, not the ability to be mobile and chase. Pyros who play it in this role, play it well and when they don't they end up being PFC+ or downright worse for the marines by blocking pushes.

 I feel like this would also be overpowered as it would allow pyros to solo kill xenos by lighting with blue flame and chasing with fire.

Other changes are ok.

2024-03-18 10:04 UTC, irakligabunia commented
> # About the pull request
> Converts pyro's m35 pyrotechnician armour into light armour using the ghillie suit armour values and changes GL's armour to having 5 light range since it should be included with heavy armour, which does have the 5 light range
> 
> # Explain why it's good for the game
> Pyro is undoubtedly the one spec that will be pointmanning, which often requires mobility and ability to chase, which is not supported by the slow nature enforced by the current armour, every other spec role other than GL has armour that has light tier slowdown.
> 
> With this PR I have matched the stats of pyro armour with the ghillie suit which seems fair considering they both have their utility factors with supply being limited to the spec role
> 
> # Testing Photographs and Procedure
> Screenshots & Videos
> # Changelog
> 🆑 balance: stat changed pyro armour and slowdown values to match ghillie armour balance: increased GL armour light range to properly match other armours like it. /:cl:

i like specialists being unique, i dont see why it has to be "meta"
you can just use light armor instead if you're that bothered by it
or just use the normal armor for area denial, like you're supposed to
or for rescuing others

2024-03-18 11:43 UTC, Mister-moon1 commented
The difference is the fact that pyro armour outside the ability is barely better than medium armour which feels like a noob trap already, its not necessarily making it meta but buffing it to be in line with other specialist gear, the armour you have should be the best for your specialist role which isnt reflected by current pyro armour. Considering the fact that pyro already has a tool to instantly put themselves out and they could take ghillie armour it doesnt feel like a big deal

2024-03-20 15:03 UTC, TheManWithNoHands commented
> The difference is the fact that pyro armour outside the ability is barely better than medium armour which feels like a noob trap already

Then make it better medium armor. Just changing the type of armor alone is a much more significant change then aligning the armor values with medium armor. 

As others said pyro is for area denial and not for chasing. A normal PFC with flamer/attachment is much better for the role of chasing. If you where to make pyro more in line with the other specs, you would remove its uniqe playstyle and replace it with one that is already present in game. Your would delet a way of playing in favor for an already existent one.

2024-03-20 21:22 UTC, The-Sun-In-Splendour commented
I was gonna post a massive wall of text on why pyro armour is actually detrimental to use right now but then I made the revelation that even if this PR was merged I would just not use the pyro armour because the ability to burn to death instead of getting capped through a blue wall of death is too good to pass on. I could post it but here's a TL;DR:

1. Not being able to burn to death just makes it way too easy to capture you through flames
2. Having high speed as pyro is extremely important (you need to get in position to flame without FF-ing, and chase if you're a backliner pyro)
3. Area denial is legitimately better done with a flamer sentry than a pyrospec.

2024-03-21 23:56 UTC, TheManWithNoHands commented
Mate, @Mister-moon1 this isnt ideaguys. Dont get so personal. 
But you started so i can go personal too.

Someone mark this as off topic please. I dont know how myself.

1. Yes, high cast Xenos will just tank fire and walk wuickly through it. But i can count the number of those on one hand. Defender, warrior, chrusher, rav, prea. all other regular casts wont risk walking over fire for the chance of getting a kill. And a much lesser chance for a cap.
2. Green fire isnt uniqe to the pyro. EVERY PFC has acces to that over req. Pyro is incredibly un-uniqe in that part. The only advantage they have is that their B-Gel tanks are larger and they have some round start. Yes, even normal flamers shoot B-Gel further then napalm. But even a PFC has the option to get them from req roundstart via bartering or just asking.
3. Pyro has the uniqe playstyle of Area Denial. Even if you suck at it, it is what pyro is best at. Pyro is the only role in game that can easily protect an enitre flank solo. This is big in part to the X-Fuel. A type of Flamer fuel only pyro can use. The only other way of getting similar flammer fuel is via research mid or late round. Thanks to the X-Fuel pyro can hold down large areas with fire, being that it burns for much more damage, and can easily cover a large area. Though to it going in a 3 tile thick line.
4. Pyro can chase, yes. But its not its uiqe playstile. EVERYONE CAN CHASE WITH A FLAMER. And pyro doesnt even have something uniqe to be better at chasing. Every PFC gets an underbarrel extingusher with the flamer from req. And there is only one type of it, pyro doesnt get a better one. So no, that isnt a point for pyro being a chaser, thats something everyone has. The only uniqe flamer fuel pyro has doesnt help with chasing, only helps blocking off a path. But thats are denial again.
5. Your argument that every specialist should be abel to say "everything you can do i can do better" to every pfc is valid... to bad pyro cant chase better. Every tool that pyro ahs for chasing, has a PFC? Underbarrel extinguisher? PFc has it. Guns? PFC has them. Flamer? PFC has them. B-Gel? PFC has them. Ligth armor? Thats specificly for PFC, and not specialist uniqe. The only thing, pyro has over PFC in chasing is a bigger fuel tank... thats it. Fun thing is, PFC have a tool thats better for chasing.
6. PFC can use the fireball nozzel. Allowing them to quickly swap between setting down fire walls and firing fire balls for fleeing target. For exampel, you could load B-Gel into it, and fire slowing and armor reducing fire balls from a range Pyro cannot achive.

So, what uniqe tools has pyro that no other marine can get? Espacially PFC.
They have an Armor that is resistend to fire stacks, even more so then the queen. Their armor can render them imune to burn damage for a short time. They have a larger fuel supply. They have acces to X-Fuel wich is a high damage, high AoE Fuel.
Every other tool Pyro has, is avalibel to even PFC. The Pyro Specialist those not posses a singel uniqe tool to chase with a flamer.
Every PFC has acces to the fire ball nozzel, wich is incredibly good for chasing. The pyro is unabel to use the fire ball nozzel.

I ask you then. Why should the role, with no uniqe ability to chase, get an advantage to chasing?
Your argument of "Everything you can do i can do better", is on its head. Because a PFC, with flamer, their uniqe nozzel, pocket extinguisher and B-Gel 🎵Can do everything better then you🎵

And why making Pyros armor ligth class block the game play style of Area Denial? Honestly, it doesnt change the gameplay style too much, i agree. But thats because the armor is already sucky for being good at Area denial. Like you said, its Medium armor, that is worse then medium armor. Thats why i suggested to give it amror values like medium armor. But you wanted to make it ligth armor so you can chase better.

This isnt about the general playstyle, its about your playstyle. You migth get a lot of kills, but that isnt what makes an Area denial role good. Pyro is abel to stop pushes from the xenos easily thanks to their wide array of fuels to choose from, ability to cover large grounds quickly, and large reserves of fuel for long and sutain Area denial.
Yes you can be good and get a lot of kills. But if you belive kills is what wins games, you are dead wrong.

Sniper picks off low health targets
Heavy sniper focuses on a singel high priority targets(yes they do, thats the reason it has damage ramp up.)
Sadar Focuses on general high priorty targets
Grenadier Focuses on front support via explosive knockback.
And Pyro Keeps entire flanks shut off. 

If you want to come with "i have clips that proof me rigth" (I sadly dont have clips, i just dont record them in anygame. Dont got the hardrive space for that.) I can just as much proof with a varity of matches where i stoped entire pushes singelhandetly as pyro.

But hey, if i missed something go ahead and tell me. Tell me what specific thing i missed that makes pyro better at chasing then a PFC. Something that is not better at Area Denial, and something ONLY pyro has access too.
And no, pyros armor in ligth doesnt count. That your playstyle works with a mainly PFC similar loadout, is proof of that. Being that most of it, every PFC can get. Besides the x-Fuel and large tanks.(Large tanks include backpack. Thats just more fuel.)

2024-03-22 00:13 UTC, TheManWithNoHands commented
Ok, odly personal. Had to holdmyself back not to do the same. 

Pyro has no uniqe tools to chase. Pyros uniqe tools consist of:
1. X-Fuel.  A high damage 
2. Armor that prevents fire stacks and ahs the ability to prevent burn damage for a short ammount of time. 
3. A large supply of fuel via their backpack and generally larger tanks.
4. wide spread B-Gel (i belive it was b-gell. That i aint sure on.)

What do PFC can use to chase with flames? 
First what everyone even pyro spec can use:
1. underbarrel Flamer
2. Underbarrel extinguisher
3. Ligth armor
5. B-Gel

Now what only PFC cna use and not Pyro spec.
1. fire Ball nozzel

Yeah thats it. Fire ball nozzel with B-Gel is incredibly good. It allows PFc to slow xenos down and reduce their armor over a range Pyro cant achive. Much faster too, because the fire ball travels faster then fire walls.

Yes, Pyro CAN chase. But its not what they are best at. Most of their tool kit allows for coverage of large areas and and sustaining doing so. They are bad at targeting singel targets, and they are bad at burst damage. Pyro accels of Denying entry and Damage over time.

Pyro is the only role in the game capabel of singelhanditly stopping pushes and flanks. Yes, ligther armor would help with that. But Pyros armor is medium to balance their power. Being abel to be fully imune to fire stacks, being shortime imune to all burn damage, Abel to reduce armor, slow enemys, denial entry on large areas, and inflict heavy damage over time, is all incredibly strong. To balance all that, you need to somehow keep pyro balanced. Why do you think Pyros armor is the most obvious of them all?

2024-03-22 00:36 UTC, Mister-moon1 commented
I feel like alot of what you argue is irrelevant, green fire and nozzle also is not good, you want xenos in the flamed tiles as long as possible, the reduce in armour only applies if you are standing on the tile, as for chasing, if you use the extinguisher properly then you would have no issue chasing compared to the nozzle,

What really baffles me and makes me question your experience is the fact you say that pyro doesnt deal in burst damage when a large majority of damage done is the initial burst of flame that deals around 180 or so damage, the damage over time, although high at 45 roughly halves when the xeno resists the fire, not accounting for anyone nearby to help

as mentioned prior, i have used walls of fire before, only that xenos just walk though it, fracture your limb, then go back to safety because it really isnt life threatening when relying on damage over time fire,

now what really excels at denying entry is combat technicians because of their little known gimmick called building barricades, pyro compared to this is laughably bad, even through green fire which one would imagine would deter a push, ive seen warriors just lunge through it to attack me to be perfectly fine, mainly because they know noone else can go through it, its a hazard to all parties

2024-03-22 20:34 UTC, The-Sun-In-Splendour commented
Pyro absolutely does NOT maximize in damage over time. Sure, it can come in clutch, especially during strong pushes or against little rounys, but 99% of my kills as pyrospec come from direct hitting a blue flame and instantly evaporating half of a xeno's health. It is 100% burst damage. Pyro is like a sniper but he trades range and IFF for not having to wind up his 200 damage satanizer.

In fact, I don't play chase pyro. I play frontline pyro, and so far the most effective tactic I've found was (direct) blue firing xenos that were either in the middle of an attack, or retreating from getting a bit too injured.

The only times I've had area denial pyro work was during FOB sieges, covering areas for the comtechs to repair. Otherwise, sure, you stop a xeno push... But they're not dying while you're doing that.

2024-03-23 21:33 UTC, Nanu308 commented
Reminder that Github is not the discussion place.

However, i agree with the general sentiment here that this is over the top for what is already a strong spec. If you wish to play it differently, the gear is there to take but then you are making a choice. 

Removing that choice by buffing the already good armor, i don't see as good for the game in this case, especially with how powerful movement speed is in CM.

I'm against this personally, but maybe some other maintainer can argue your case further if someone is for it.

2024-03-26 18:56 UTC, ondrej008 commented
The GL light change seems good.

I don't see the point of the change for pyro armor because what @The-Sun-In-Splendour said can already be done and cannot be done with the existing armor, so even if the PR went through it would still be beneficial to take light armor.

And if you are doing area denial then the movespeed change won't affect you that much.

2024-04-03 03:49 UTC, Drulikar requested changes

2024-04-03 03:49 UTC, Drulikar commented on code/modules/clothing/suits/marine_armor/spec_fire.dm
Drop the changes to the pyro armor and keep the light range increase for grenadier.

2024-04-06 00:06 UTC, Mister-moon1 commented
Have also batched the armour to the light increase to pyro armour considering all medium+ armours were supposed to receive the buff

2024-04-06 07:47 UTC, Drulikar requested changes
Please fix the PR description and change log.

2024-04-06 08:25 UTC, Diegoflores31 commented
> Thspecialist role which isnt reflected by current pyro armour. Considering the fact that pyro already has a tool to instantly put themselves out and they can already take ghillie armour it doesnt feel like a big deal to just have a more convenient version in line with the role

Untrue pyro armor is pretty much one of the only armors in the game that provide hands and feet armor that STACKS with boots and gloves making it insanely tanky against most benos

2024-04-07 16:44 UTC, Drulikar approved these changes

2024-04-07 17:19 UTC, merged