Slightly expands weedible area to of west lZ2 T-comms area
cmss13-devs/cmss13 pull request #5979
Opened 2024-03-19 10:53 UTC by spartanbobby

# About the pull request

Adds another weedable zone west of LZ2 T-comms tower

# Explain why it's good for the game

The weedibility of the area is quite light compared to the other tower and players lack a lot of options other than assaulting from across the river

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl: SpartanBobby
maptweak: New weedable zone west of LZ2 T-comms tower
/:cl:

2024-03-28 11:39 UTC, Nanu308 requested changes

2024-03-28 11:39 UTC, Nanu308 commented on maps/map_files/LV624/LV624.dmm
![bilde](https://github.com/cmss13-devs/cmss13/assets/59782240/6a406838-3727-4af3-8697-2fb5d0341d53)
Fix the small jungle wall and replace with a sand tile, looks better.

Secondly, make the area you changed which would be the "Western Jungle" unweedable by changing the variable of "is_resin_allowed" in the area.dm for lv

2024-03-29 02:10 UTC, spartanbobby commented on maps/map_files/LV624/LV624.dmm
Personally I dont think this is a good idea but we'll see

2024-03-30 08:18 UTC, Nanu308 approved these changes
legod

2024-03-30 08:24 UTC, merged