Allows wardens to heal eachother again at half the health.
cmss13-devs/cmss13 pull request #5982
Opened 2024-03-19 15:34 UTC by InsaneRed

# About the pull request
Allows wardens to heal eachother once again, but for half the health this time.

# Explain why it's good for the game
This was removed because people were dual wardening and keeping eachother alive very well
this should tackle that and hopefully only allow it to be used on crit / near crit situations so.

I hate not being able to save another warden because hes of the same strain
# Testing Photographs and Procedure
i made it so its good
<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
balance: Wardens can heal eachother once again, but only half the health
/:cl:

2024-03-19 15:41 UTC, Birdtalon requested changes

2024-03-19 15:41 UTC, Birdtalon commented on code/modules/mob/living/carbon/xenomorph/abilities/praetorian/praetorian_powers.dm
> +		var/quantity_healed =  heal_amount
Extra unnecessary space.
```suggestion
		var/quantity_healed = heal_amount
```

2024-03-19 15:41 UTC, Birdtalon commented on code/modules/mob/living/carbon/xenomorph/abilities/praetorian/praetorian_powers.dm
> +		targetXeno.flick_heal_overlay(3 SECONDS, "#00B800")//so the visible_message and recovery overlay will warn marines and possibly predators that the xenomorph has been healed!rn marines and possibly
```suggestion
		targetXeno.flick_heal_overlay(3 SECONDS, "#00B800")//so the visible_message and recovery overlay will warn marines and possibly predators that the xenomorph has been healed!
```

2024-03-19 15:41 UTC, Birdtalon commented on code/modules/mob/living/carbon/xenomorph/abilities/praetorian/praetorian_powers.dm
> +
```suggestion
```

2024-03-25 21:17 UTC, Drulikar commented on code/modules/mob/living/carbon/xenomorph/abilities/praetorian/praetorian_powers.dm
>  		to_chat(X, SPAN_XENODANGER("We heal [targetXeno]!"))
Did you intend to change this too?

2024-03-25 21:21 UTC, Drulikar approved these changes

2024-03-25 21:30 UTC, merged