NVO no longer can be used with binoculars/optics
cmss13-devs/cmss13 pull request #5983
Opened 2024-03-19 16:40 UTC by ihatethisengine

# About the pull request
Original NVG won't allow you to use NVO with binos, but when Morrow introduced helmet optics, for some reason he didn't carry over the limitation. I don't know if it was intended or simply was an oversight. Sadly my revert to NVGs (https://github.com/cmss13-devs/cmss13/pull/4807) didn't go through, but I still believe that I was right about points I brought out in the PR, so I am going to address them bit by bit now.

# Explain why it's good for the game
Using nightvision with anything that increases your field of view gives an unreasonable advantage which should be limited only to specs and SGs.

# Testing Photographs and Procedure

<details>
I did test it
</details>

# Changelog

:cl: ihatethisengine
balance: night vision optics no longer can be used with binoculars.
/:cl:

2024-03-19 22:15 UTC, irakligabunia commented
>Original NVG wouldn't allow you to use them with binos, but when Morrow introduced helmet optics, for some reason he didn't carry over the limitation

I'm pretty sure its because NVO's have way worse duration

2024-03-20 03:51 UTC, ihatethisengine commented
NVO has the same duration, but a lot more inconvenient to recharge (I may address this later)

2024-03-20 07:28 UTC, morrowwolf commented
This was not an oversight.

> NVO has the same duration, but a lot more inconvenient to recharge (I may address this later)

Incorrect.

Do with that what you will.

2024-03-20 09:37 UTC, ihatethisengine commented
What exactly is incorrect? 
NVG have 2500 max charge and spend 8 per second, 2500÷8=312.5÷60=5.20 minutes
NVO have 10000 max charge and spend 33 per second, 10000÷33=303.03÷60=5.05 minutes
The difference is literally 9.5 seconds, not that much.

2024-03-20 11:01 UTC, morrowwolf commented
Let me be more precise:
It is *dishonest* to categorize them as even remotely similar in regard to charge duration or usage time. You could take 1-2 giant cells and have your NVGs on pretty much 24/7 for a round. Walking past this by just saying it is "a lot more inconvenient to recharge" is blatantly sidestepping extremely pertinent information on past usage which was left out out of the new item on purpose.

Regarding design thoughts:
Overall I had seriously considered axing the optics as well as the goggles for standard use. SGs would also lose their night vision but would get something on their HUD for tracking targets in the dark. Having it just be an in-built MD feels lazy when you could make it so much cooler with client images and such. Darkness should be scary for marines for both gameplay and thematic reasons.

Secondary to that, giving engineers the ability to create on the fly rechargers via APCs was another thought for making power in general more fun to add to items and play with while giving engineers more utility. While possibly annoying at times consider possible recharge requirements for sentries or flashlights. Inventory and gear management is a fairly unique and important part of the overall game and I think it'd benefit from it.

*body armor light flickers*
"Your light is running low on charge..."
Oh shit...

Hunt that dread feeling.

Xeno main out 🧑‍🚀

2024-03-23 23:59 UTC, Diegoflores31 commented
> Let me be more precise: It is _dishonest_ to categorize them as even remotely similar in regard to charge duration or usage time. You could take 1-2 giant cells and have your NVGs on pretty much 24/7 for a round. Walking past this by just saying it is "a lot more inconvenient to recharge" is blatantly sidestepping extremely pertinent information on past usage which was left out out of the new item on purpose.

but old NVGs , could not use binoculats , had very clear visuals , could be broken in 3 slashes , you had to use your storage to carry cells and lost durability each time the got broken.

2024-04-03 00:50 UTC, Drulikar requested changes
Minor, but you should see if you can also have `/obj/item/clothing/head/helmet/marine/proc/cycle_huds(mob/user)` check whether `can_toggle` returns true with something like
```js
if(!next_visor.can_toggle(user))
	iterator++
	skipped_hud = TRUE
	continue
```

and to the second loop: 
```js
if(!new_visor.can_toggle(user))
	continue
```

Otherwise you get into this state where the visor was selected, but you had the message it won't work, and it won't work when you leave the view again.

![image](https://github.com/cmss13-devs/cmss13/assets/76988376/f4b2088d-1f09-4686-9812-ee92764a65ce)

Alternatively you had the visor try to activate when the view changes back to normal.

Also would be nice if the visors spit out a to_chat if there's nothing to swap to, but up to you if you want to improve that (it'd probably just be a to_chat before the first return FALSE and the final return FALSE in that same proc).

2024-04-03 00:50 UTC, Drulikar commented on code/game/objects/items/devices/helmet_visors.dm
> +		to_chat(user, SPAN_WARNING("You cannot use \the [src] while using optics."))
```suggestion
		to_chat(user, SPAN_WARNING("You cannot use [src] while using optics."))
```

2024-04-03 01:15 UTC, Drulikar commented
This plus the other code suggestion should address all my concerns.
[patch.diff.txt](https://github.com/cmss13-devs/cmss13/files/14845473/patch.diff.txt)

2024-04-04 16:26 UTC, Drulikar approved these changes

2024-04-04 16:31 UTC, merged