Dead OOC (Large Dsay)
cmss13-devs/cmss13 pull request #5984
Opened 2024-03-19 19:19 UTC by Birdtalon

# About the pull request

Some staff use YOOC (Yautja OOC) to talk to ghosts in a larger font which makes no sense. This adds a variant of dsay which is a larger font size for staff to talk to dchat if they need.

ps. also adds a space between the staff rank and the ckey ( because its annoying
![dreamseeker_2024-03-19_19-15-01](https://github.com/cmss13-devs/cmss13/assets/25027759/cd4a791b-133a-4410-a6a9-e428df72e07b)

# Explain why it's good for the game

# Testing Photographs and Procedure

<details>

<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
admin: DOOC - a larger deadsay for staff
fix: Adds a space between staff rank and ckey to match other dsay formatting.
/:cl:

2024-03-19 19:19 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-03-19 19:19 UTC, Birdtalon commented on tgui/packages/tgui-panel/styles/goon/chat-dark.scss
> -
This is a duplicated style definition

2024-03-19 19:23 UTC, Zonespace27 requested changes

2024-03-19 19:23 UTC, Zonespace27 commented on code/modules/admin/verbs/deadsay.dm
> +	if(!src.admin_holder || !(admin_holder.rights & R_MOD))
```suggestion
	if(!admin_holder || !(admin_holder.rights & R_MOD))
```

2024-03-19 19:23 UTC, Zonespace27 commented on code/modules/admin/verbs/deadsay.dm
> +		to_chat(src, "Only administrators may use this command.")
add a SPAN_DANGER?

2024-03-19 19:23 UTC, Zonespace27 commented on code/modules/admin/verbs/deadsay.dm
> +	if (src.handle_spam_prevention(msg,MUTE_DEADCHAT))
```suggestion
	if (handle_spam_prevention(msg, MUTE_DEADCHAT))
```

2024-03-19 19:23 UTC, Zonespace27 commented on code/modules/admin/verbs/deadsay.dm
> +	if(!src.mob)
```suggestion
	if(!mob)
```

2024-03-19 19:23 UTC, Zonespace27 commented on code/modules/admin/verbs/deadsay.dm
> +	for (var/mob/M in GLOB.player_list)
as anything, no one letter vars, etc.

2024-03-19 19:23 UTC, Zonespace27 commented on code/modules/admin/verbs/deadsay.dm
> +	for (var/mob/M in GLOB.player_list)
also GLOB.observer_list may be better here

2024-03-19 19:23 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-03-19 23:14 UTC, Zonespace27 commented on code/modules/admin/verbs/deadsay.dm
> +			continue
```suggestion
```

2024-03-25 21:47 UTC, Drulikar requested changes

2024-03-25 21:47 UTC, Drulikar commented on code/modules/admin/verbs/deadsay.dm
> +	for (var/mob/mob in GLOB.observer_list)
Did you mean to change this to observer? If so the admin check below on 81 I think is moot.

2024-03-25 21:47 UTC, Drulikar commented on code/modules/admin/verbs/deadsay.dm
> +		else if((mob.stat == DEAD || isobserver(mob)) && mob && mob.client && mob.client.prefs && (mob.client.prefs.toggles_chat & CHAT_DEAD)) // show the message to regular ghosts who have deadchat toggle
```suggestion
		else if((mob.stat == DEAD || isobserver(mob)) && mob.client?.prefs && (mob.client.prefs.toggles_chat & CHAT_DEAD)) // show the message to regular ghosts who have deadchat toggled on
```

2024-03-25 21:47 UTC, Drulikar commented on code/modules/admin/verbs/deadsay.dm
> +		if(mob.client && mob.client.admin_holder && (mob.client.admin_holder.rights & R_MOD) && mob.client.prefs && (mob.client.prefs.toggles_chat & CHAT_DEAD)) // show the message to admins who have deadc
```suggestion
		if(mob.client?.admin_holder && (mob.client.admin_holder.rights & R_MOD) && mob.client.prefs && (mob.client.prefs.toggles_chat & CHAT_DEAD)) // show the message to admins who have deadchat toggled on
```

2024-04-10 01:00 UTC, closed without merging