[LV-624] Command Dome - New Comms Array Location
cmss13-devs/cmss13 pull request #5988
Opened 2024-03-20 08:30 UTC by Steelpoint

# About the pull request

This PR rethemes the Gym into a new 'Command Dome', the structure contains amenities expected of a command area, however it is also a new possible spawn location for a comms array. 

It uses the number 1 comms spawn, meaning it shares the spawn location with the Engineering comms spawn. Ergo there is a 50/50 the 1 comms spawns either in south Engineering, or central Command. 

This also adds a rarer alt spawn for the Command Dome that spawns it as a heavily fortified, but breached, area that some survivors used. 

# Explain why it's good for the game

The addition of a second possible colony spawn for a comms array would help make the central colony an actually desirable location to hold and fortify for both sides, and make the colony a possible combat zone.

As it stands, the central colony is rarely a fought over area as both sides normally use it as a transit zone from the FOB to the cave frontline, and any major fighting is usually contained towards the west/east rivers or Engineering, ergo Marines never really fortify the central colony thus it becomes a backline area.

This change would have a chance that both sides now have to fight over the centre of the colony. Thus breathing new life into this area of the map that is so often bypassed. 

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Main Spawn
![Screenshot 2024-03-20 16 21 54](https://github.com/cmss13-devs/cmss13/assets/6595389/1e6abd21-235a-4d15-9b49-18e6a8198787)

Uncommon Alt Spawn
![Screenshot 2024-03-20 16 17 14](https://github.com/cmss13-devs/cmss13/assets/6595389/f1258f81-9b16-49a3-bdac-0846e3d8bdc4)

</details>

# Changelog

:cl:
mapadd: A new 'Command Dome' has replaced the old Gym on LV-624. This dome has a chance to contain a comms array.
mapadd: The Command Dome has a small chance to spawn in a alt configuration that is heavily fortified by the survivors. 
/:cl:

2024-03-28 12:06 UTC, Nanu308 requested changes

2024-03-28 12:06 UTC, Nanu308 commented on maps/map_files/LV624/LV624.dmm
Keep fitness, make command instead a NM insert and work from there 👍

2024-03-28 16:33 UTC, Steelpoint commented on maps/map_files/LV624/LV624.dmm
can do

2024-03-30 08:28 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-04-06 05:49 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-04-06 05:50 UTC, Steelpoint commented
Assuming nothing breaks I'll re-work the PR in <~1week

2024-04-10 10:33 UTC, Steelpoint commented
I've updated this to be a nightmare insert that has a chance to replace the Gym with a Command Dome.

2024-05-01 16:48 UTC, Nanu308 commented
I am back from being dead.

After some further considerations I think the command insert would fit better into the Tcomms location on LV. Having a tcomms so close to Hydro i dont think is a good thing due to how frequent Marines entrench or go to hold Hydro.

Due to that I'd like to see if as a tcomms variant instead 👍

2024-05-01 17:14 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-05-09 12:58 UTC, Steelpoint commented
Will finish this when I have free time to fix mapping issues and make requested changes

2024-05-09 12:58 UTC, closed without merging