flames remove snow !
cmss13-devs/cmss13 pull request #6001
Opened 2024-03-24 14:02 UTC by cuberound

# About the pull request

makes snow scortchable and implements behavior for it ( thank you kugamo for making the LV grass scortchable so that the basework for it exists). intensity numbers might need tweeking if maintainers feel like it, but other than that it works.

# Explain why it's good for the game

removing snow is pain in ass and even more so for marines, explosions can already remove snow and it only makes sance for flames to melt the snow

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
balance: flames melt the snow 
/:cl:

2024-03-29 20:30 UTC, Zonespace27 submitted a review, later dismissed

2024-04-06 09:28 UTC, Drulikar requested changes

2024-04-06 09:28 UTC, Drulikar commented on code/game/turfs/auto_turf.dm
> +	if(bleed_layer == 0)
```suggestion
	if(bleed_layer <= 0)
```

2024-04-06 09:28 UTC, Drulikar commented on code/game/turfs/auto_turf.dm
> +
```suggestion
```

2024-04-06 09:28 UTC, Drulikar commented on code/game/turfs/snow.dm
> +			update_icon(TRUE, FALSE)
```suggestion
			update_icon(update_full = TRUE, skip_sides = FALSE)
		if(20 to 39)
			bleed_layer = max(bleed_layer - 2, 0)
			update_icon(update_full = TRUE, skip_sides = FALSE)
		if(40 to INFINITY)
			bleed_layer = 0
			update_icon(update_full = TRUE, skip_sides = FALSE)
```

2024-04-06 09:28 UTC, Drulikar commented on code/game/turfs/snow.dm
> +	if(bleed_layer == 0)
Unresolved

2024-04-06 11:27 UTC, Drulikar approved these changes
Works. Though I will note it may make sense if adjacent snow tiles melted a layer too - but it doesn't have to. Also the scorch seems to only happen once so if its a deep enough patch of snow and a low enough flame, you'll still have snow remain despite fire continuing to burn on it for a while.

2024-04-07 17:11 UTC, merged