Faster snow removal for bigger xenomorphs
cmss13-devs/cmss13 pull request #6002
Opened 2024-03-24 14:26 UTC by cuberound

# About the pull request

makes the snow removal dependant of xenomorph size, making it 1,5 ( lesser) to 4 times (big xenos) faster ( still takes a while even for the largest xenos to remove deap snow)

# Explain why it's good for the game

removing snow is painful job that makes maps with snow unwanted, huge xenomorphs should not have that hard time showeling some snow out of their way, makes it fair with the flames removing snow PR 

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
balance: greatly decreses snow removal time, now it depends on xenomorph size 
/:cl:

2024-04-02 15:26 UTC, SabreML requested changes
It looks like `/turf/open/snow` isn't actually used anywhere other than a nightmare variant of CORSAT. Everything else uses `/turf/open/auto_turf/snow`, so this needs to be added to that as well.
(I don't know why we have two mostly identical versions of a snow turf)

2024-04-03 02:30 UTC, Drulikar requested changes

2024-04-03 02:30 UTC, Drulikar commented on code/modules/mob/living/carbon/xenomorph/attack_alien.dm
> +		if(!do_after(M, 12/M.mob_size, INTERRUPT_ALL, BUSY_ICON_FRIENDLY))
Division by zero is technically possible.
```suggestion
		var/size = max(M.mob_size, 1)
		if(!do_after(M, 12/size, INTERRUPT_ALL, BUSY_ICON_FRIENDLY))
```

2024-04-04 14:24 UTC, SabreML approved these changes
LGTM!
I was wondering if the time should be changed from `12` to `18` so that it's unchanged for lesser drones (they now have a time of `8` due to a mob size of `MOB_SIZE_XENO_VERY_SMALL`), but I don't think it's that much of an issue.
IMO it can just be changed later on if it seems too fast.

2024-04-06 09:12 UTC, Drulikar approved these changes

2024-04-06 09:17 UTC, merged

2024-04-06 10:27 UTC, RavinHobo commented
crusher snow plough variant when?