Fixes armor light staying on after removal
cmss13-devs/cmss13 pull request #6004
Opened 2024-03-24 19:53 UTC by vero5123

# About the pull request
Fixes #5762, just put a conditional to check if the armor contains a light source that is currently turned on, if so we just turn it off when the user removes it from their inventory.

# Changelog
:cl:
fix: Fixes armor light staying on after removal.

2024-03-24 21:55 UTC, Superwelder commented
Many thanks for looking at my issue!

2024-03-27 14:36 UTC, harryob requested changes
we don't use explicit src

2024-03-27 14:36 UTC, harryob commented on code/game/objects/items.dm
> +				src.turn_light(toggle_on = FALSE)
```suggestion
			if(light_on)
				turn_light(toggle_on = FALSE)
```

2024-04-06 08:36 UTC, vero5123 commented
> Many thanks for looking at my issue! 

Np

2024-04-06 11:08 UTC, harryob approved these changes

2024-04-06 11:42 UTC, merged