Fiorina Riot In Progress: Colonial Marshals & United Americas Police
cmss13-devs/cmss13 pull request #6022
Opened 2024-03-27 10:48 UTC by QuickLode

# About the pull request

Howdy, this PR adds in unique Riot Response flavored CMB Deputies and UA Riot Police to a Survivor Nightmare(thx badatthisgame302) on Fiorina Science Annex. Because this is a survivor nightmare I kept the loadouts very sparse, so you will only find a couple mags of ammo per weapon, and all participants here will likely have to resort to their sidearm. It is implied that by the time players control these characters, they've been surviving for hours if not days. Furthermore, because its a riot response, there are no specialists (engineers, doctors, etc.) to help the support side of things. After all, it is just a riot call..

PS. If you haven't read the Alien: Isolation comic yet, something similar is implied there. :) 

On the CMB side we have 3 variations and a Synthetic. These investigative federal agents are nimble on their feet, but inadequately protected and their weapons are more focused on self defense. They were sent here as emergency back-up to the understaffed prison, and aren't prepared for this scenario. They do however still carry some rubber munitions and crowd control elements.

On the UA side we have 4 variations and a Synthetic. The infamous United Americas Riot Control Police show with four variations. Donned in complete riot gear and with uniformity, they would seem like an unstoppable force to be reckoned with. Unfortunately for them, they're dealing with Xenomorphs - all of their crowd control devices and nonlethal munitions may prove to be very ineffective at dealing with this new threat at hand..

# Explain why it's good for the game

Adding meaningful and fitting equipment really adds to the immersion. Its not just a setting but it envokes the real feeling of "We came here to stop a riot, but we found something much more sinister." By giving players these settings to play with, they'll feel much more at home in the Aliens universe as opposed to the looming feeling of it being "just another round, just another role."

I think CM really benefits from spicing up the loop and nightmares are an excellent example of that. Having lore accurate, flavorful layouts like this where you have a consistent theme going allows for excellent immersion. Even if everyone dies, the Marines stumbling upon the corpses of a horrific incident like this will be a really unique experience, in my opinion.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Basically I created a new file for these fine people and added what I think is thematically fitting for this scenario. I then tested it, fixed bugs, and then tested it again. This happened 3 times until I could no longer find any bugs. 

https://cdn.discordapp.com/attachments/1042176396711170119/1222482124771430460/image.png?ex=66166033&is=6603eb33&hm=69719c33b5d811033f62cba605d5ba6e044c4cdd8f7056c50e49e9523e7ce3f8&
</details>

# Changelog

:cl:
add: Adds 3 variations of CMB Marshal and 4 variations of a UA Riot Police Officer to Fiorina Prison Riot nightmare. These are fine men and women in uniform prepared to engage what they suspect is a riot(or in the case of CMB, assisting their underfunded and understaffed colleagues) however, they find something much more sinister going on..
add: Adds a CMB Investigative Synthetic(r) and a UA Police Synthetic.
add: Allows police baton and telescopic baton to shield clash for intimidation and riot tactics.
add: Allows M81 launcher to utilize less lethal baton round
qol: removes taser from some security synthetics belts, replaced with a more synthetic friendly version
/:cl:

2024-04-05 12:25 UTC, SabreML requested changes
Sorry for the delay!
Just a couple of things at the moment. I'll look through the new equipment presets more thoroughly once the pathing review has been resolved. 👍

2024-04-13 11:07 UTC, Drulikar requested changes

2024-04-13 11:07 UTC, Drulikar commented on code/modules/gear_presets/survivors/fiorina_sciannex/riot_in_progress_insert_fiorina_nightmare.dm
> +	new_human.equip_to_slot_or_del(new /obj/item/ammo_magazine/revolver/cmb, WEAR_IN_BACK)
Why are they getting mags for a pistol they don't have nor can fire?

2024-04-13 11:07 UTC, Drulikar commented on code/modules/gear_presets/survivors/fiorina_sciannex/riot_in_progress_insert_fiorina_nightmare.dm
> +	new_human.equip_to_slot_or_del(new /obj/item/storage/belt/security/MP/full, WEAR_WAIST)
This contains a `/obj/item/weapon/gun/energy/taser` they cannot fire.

2024-04-13 11:07 UTC, Drulikar commented on code/modules/gear_presets/survivors/fiorina_sciannex/riot_in_progress_insert_fiorina_nightmare.dm
> +	new_human.equip_to_slot_or_del(new /obj/item/storage/box/packet/baton_slug, WEAR_IN_BACK)
What are they going to fire slugs from? They cannot fire a `/obj/item/weapon/gun/launcher/grenade/m81/riot`

2024-04-13 11:07 UTC, Drulikar commented on code/modules/gear_presets/survivors/fiorina_sciannex/riot_in_progress_insert_fiorina_nightmare.dm
> +	new_human.equip_to_slot_or_del(new /obj/item/ammo_magazine/rifle/m16, WEAR_IN_BACK)
What m16 can they fire?

2024-04-13 16:38 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-04-17 20:47 UTC, Drulikar requested changes

2024-04-17 20:47 UTC, Drulikar commented on code/game/objects/items/storage/belt.dm
> +	new /obj/item/handcuffs(src)
```suggestion
	new /obj/item/handcuffs(src)

```

2024-04-17 20:47 UTC, Drulikar commented on code/modules/clothing/suits/marine_armor/ert.dm
> +	armor_rad = CLOTHING_ARMOR_NONE
```suggestion
	armor_bullet = CLOTHING_ARMOR_NONE
	armor_laser = CLOTHING_ARMOR_NONE
	armor_energy = CLOTHING_ARMOR_NONE
	armor_bomb = CLOTHING_ARMOR_NONE
	armor_bio = CLOTHING_ARMOR_NONE
	armor_rad = CLOTHING_ARMOR_NONE
```
Missing value resets for laser and bio.

2024-04-18 02:21 UTC, Drulikar approved these changes

2024-04-18 02:26 UTC, merged

2024-04-20 12:33 UTC, Skatuk commented
I'm sorry but this doesn't look good on paper, not a single engineer or medic and all depended on a synthetic to keep them alive. What if that synthetic doesn't spawn since its a WL only? Also once T2's spawn its basically over since they have no cades to be protected by.