Acid runner tweaks
cmss13-devs/cmss13 pull request #6023
Opened 2024-03-27 13:56 UTC by InsaneRed

# About the pull request
Makes it so you no longer get passive acid above 400.
Tailstab no longer applies acid.

# Explain why it's good for the game
In the midst of nothingburgers, people have started complaining about acid runners. And i wanted to touch it up before anyone else did because half of the people complaining have never touched xenomorph in their life

Why didnt you touch the queen screech + acid bomb combo

Because an acider needed to farm one thousand acid, plus a queen, plus her being off ovi, plus coordination which i think all of that teamwork should be rewarded

Why didnt you make the runner bomb stop if he went into crit

With the amount of IFF, Grenades, and all the other doo hickeys we have its kind of impossible to run at marines without instantly getting into crit, and all that effort being wasted because of that doesnt feel good for the runner.

Why did you make it so you dont get passive acid above 400
So people dont stay afk in hive from the start to instantly bomb the front

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
balance: Tailstab no longer applies acid
balance: Passive acid gain for the acider strain now caps at 400.
/:cl:

2024-03-27 14:19 UTC, Birdtalon commented
Acid runner is fine if a manager disagrees with me they can remove this label.

2024-03-27 17:15 UTC, Zonespace27 requested changes

2024-03-27 17:15 UTC, Zonespace27 commented on code/modules/mob/living/carbon/xenomorph/strains/castes/runner/acid.dm
> +		return
You haven't tested this; this will break all the code below it because of this early return

2024-04-03 02:23 UTC, Drulikar commented
I don't think this change is necessary. It also makes the corrosive_acid ability that much more egregiously bad to use and the limit on passive regen is poorly communicated to the player (they'd only tell if they kept a close eye on their status panel and notice it doesn't grow most of the time).

2024-04-03 02:23 UTC, closed without merging