Project ARES: Announcement Signatures
cmss13-devs/cmss13 pull request #6030
Opened 2024-03-27 21:27 UTC by realforest2001

# About the pull request
ARES now logs who sent an announcement and not just the contents of it.

# Explain why it's good for the game

Makes the available information a little more useful. It's all well and good recording what was said, but a little pointless if not including who said it.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
add: Added the name of an announcement sender, if one exists, to ARES logs.
/:cl:

2024-04-13 13:09 UTC, Drulikar requested changes

2024-04-13 13:09 UTC, Drulikar commented on code/defines/procs/announcement.dm
> +				log_ares_security(title, message, signature)
This should be replicated for `/proc/shipwide_ai_announcement(message, title = MAIN_AI_SYSTEM, sound_to_play = sound('sound/misc/interference.ogg'), signature, ares_logging = ARES_LOG_MAIN)` as well 
![image](https://github.com/cmss13-devs/cmss13/assets/76988376/f5052dbb-e742-4801-ad21-ad2d78ebec35)

2024-04-13 13:11 UTC, Drulikar commented on code/defines/procs/announcement.dm
> +				log_ares_security(title, message, signature)
You also may consider updating all other usages of `log_ares_security` wherever applicable you have a user.

2024-04-20 12:33 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-04-20 12:34 UTC, realforest2001 commented
Added the bits for security log, had to update some var names on other UIs to do so mind.

2024-04-20 12:35 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-04-21 04:26 UTC, Drulikar requested changes
In ARES_interface_apollo.dm there is still:
`log_ares_security("Nerve Gas Release", "[last_login] released Nerve Gas from Vent '[sec_vent.vent_tag]'.")`

In ARES_interface_admin.dm there is still:
`log_ares_security("Nerve Gas Release", "[MAIN_AI_SYSTEM] released Nerve Gas from Vent '[sec_vent.vent_tag]'.")`

In apollo_pda.dm there is still:
`log_ares_security("Nerve Gas Release", "[last_login] released Nerve Gas from Vent '[sec_vent.vent_tag]'.")`

In biohazard_lockdown.dm there is still:
`var/ares_log = "[user.name] triggered Medical Research Biohazard Containment Lockdown."`
`log = "[key_name(user)] triggered research bio lockdown! (Using a custom announcement)."`
`ares_log = "[MAIN_AI_SYSTEM] triggered Medical Research Biohazard Containment Lockdown."`
`log = "[key_name(user)] lifted research bio lockdown!"`
`ares_log = "[user.name] lifted Medical Research Biohazard Containment Lockdown."`
`ares_log = "[MAIN_AI_SYSTEM] lifted Medical Research Biohazard Containment Lockdown."`
`log_ares_security("Containment Lockdown", ares_log)`

2024-04-21 04:26 UTC, Drulikar commented on code/game/machinery/ARES/ARES_interface.dm
In this file there is still:
`log_ares_security("Nerve Gas Release", "[last_login] released Nerve Gas from Vent '[sec_vent.vent_tag]'.")`

2024-04-21 04:26 UTC, Drulikar commented on code/defines/procs/announcement.dm
In this file there is still:
`log_ares_security("[MAIN_AI_SYSTEM] Security Update", message)`
`log_ares_announcement("[MAIN_AI_SYSTEM] Comms Update", message)`
`log_ares_announcement("[title] Shipwide Update", message)`

2024-05-01 07:38 UTC, Drulikar requested changes
Merge with master and you will find more procs you need to update as a result of https://github.com/cmss13-devs/cmss13/pull/6173

2024-05-02 01:49 UTC, Drulikar approved these changes
![image](https://github.com/cmss13-devs/cmss13/assets/76988376/8c1a9797-9755-49f6-b67e-cda128c73070)

2024-05-02 01:53 UTC, merged