Xenothumbs Minor Event Button Comeback
cmss13-devs/cmss13 pull request #6034
Opened 2024-03-28 05:36 UTC by PhantomEpicness

# About the pull request
Working version that is TMable for april fools. 

Revived and fixed up https://gitlab.com/cmdevs/colonial-warfare/-/merge_requests/1915/diffs#9ec310cca070259d82839a4a70e89dd858ded438_958_958

https://github.com/cmss13-devs/cmss13/pull/2997

All credit to Vanagandr, I just ported and fixed up from gitlab.

Additions
- Attempt at making vendors and such working
- Xenos can drive vehicles (untested in new pr)
- xenos can heal

todos:
- MGs (i had to strip it out entirely because it rebasing screwed it up so badly)
- shotgun pumping for funny

Original description
> TL;DR: https://streamable.com/rlvs86
> 
> Mainly this allows xenos to pick up items. They can then use most of them.
> 
> Ex. a xeno can't flip a plasteel cade open - but if she has a toolbelt and time to work, she can unwrench it.
> 
> They can fumble about but a lot of QoL and objects (middleclick container open, click-dragging containers, tables, etc.) were never designed to be interacted with by xenos so item interactions are a bit clunky.
> 
> They can't strip clothing and gear from people.
> 
> They *can* strip and attach attachments but can't aim down scopes.
> 
> They *can* FF.
> 
> They *can't* use MGs.
> 
> IFF works, roughly, not picking up on specific hives but allowing them to shoot past other xenos and hit humans.
> 
> They pass spec checks and can clumsily handle medic gear.
> 
> needless to say this is all colossally imbalanced and has potential for fuckery limited only by the xeno's imagination and whether the thing they're messing with makes an explicit ishuman() check. Or is a structure. They can't hand-interact with structures, so they can shove shells into a mortar but can't change its coords.
> 
> Cosmetically, gun inhands don't line up with xenos. Tweaked it a bit to center it horizontally but lining inhands up with hands for every xeno and xenonid sprite is a bit more hassle than seems worthwhile ATM.
> 

# Explain why it's good for the game
TM funny

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:  Vanagandr, totalepicness
add: Added a button to event panel to give xenomorphs opposable thumbs and firearms permits, to individuals, to hives, or to all xenos everywhere. They're clumsy, though, and have issues with fine manipulation sometimes. Remember that warriors cannot throw objects and make for poor grenadiers.
add: Xenos with opposable thumbs can use buckles and drive vehicles (:
/:cl:

2024-03-28 14:44 UTC, harryob requested changes

2024-03-31 08:57 UTC, hry-gh requested changes
some more minor nits. it'd be nice to get this actually merged so we don't have to do this next year, given it's behind a verb

2024-03-31 08:57 UTC, hry-gh commented on code/game/machinery/vending/cm_vending.dm
> +	var/mob/living/carbon/user = usr
```suggestion
	var/mob/living/carbon/user = ui.user
```

2024-03-31 08:57 UTC, hry-gh commented on code/modules/cm_marines/smartgun_mount.dm
> +	if(!ishuman(user) || !HAS_TRAIT(user,TRAIT_OPPOSABLE_THUMBS))
```suggestion
	if(!ishuman(user) || !HAS_TRAIT(user, TRAIT_OPPOSABLE_THUMBS))
```

2024-03-31 08:57 UTC, hry-gh commented on code/modules/projectiles/gun_helpers.dm
> +	if(!ishuman(usr) && !HAS_TRAIT(usr, TRAIT_OPPOSABLE_THUMBS))
bump, just 

```suggestion
	if(!ishuman(user) && !HAS_TRAIT(user, TRAIT_OPPOSABLE_THUMBS))
```

2024-03-31 08:57 UTC, hry-gh commented on code/modules/projectiles/gun_helpers.dm
> +	if(!ishuman(usr) && !HAS_TRAIT(user, TRAIT_OPPOSABLE_THUMBS))
```suggestion
	if(!ishuman(user) && !HAS_TRAIT(user, TRAIT_OPPOSABLE_THUMBS))
```

2024-03-31 08:57 UTC, hry-gh commented on code/modules/vehicles/interior/interactable/seats.dm
> +		else if(!HAS_TRAIT(user, TRAIT_OPPOSABLE_THUMBS))
```suggestion
		if(!HAS_TRAIT(user, TRAIT_OPPOSABLE_THUMBS))
```

2024-03-31 22:23 UTC, hry-gh requested changes
mb

2024-03-31 22:23 UTC, hry-gh commented on code/modules/projectiles/gun_helpers.dm
> +	if(!ishuman(user) && !HAS_TRAIT(user, TRAIT_OPPOSABLE_THUMBS))
```suggestion
	if(!ishuman(usr) && !HAS_TRAIT(usr, TRAIT_OPPOSABLE_THUMBS))
```

2024-04-06 11:09 UTC, harryob approved these changes

2024-04-06 11:51 UTC, merged