No More Prep Raiding
cmss13-devs/cmss13 pull request #6083
Opened 2024-04-05 01:20 UTC by MobiusWon

# About the pull request

- Removes access to Marine Prep and Marine Prep Ammo vendors for Cargo Technicians (CT). 
- Doubles ammo in Marine Prep and Cargo Weapons to compensate changes and eliminate the need for Cargo Techs to pilfer Marine Prep of all its ammo. 
- Quartermaster (QM) is unchanged.

# Explain why it's good for the game

**I would consider this a HOTFIX**, Maintainers update the title as you see fit, I just didn't want to be _that guy_.

### PRIORITY ISSUE: 
By mid-round of medium pop or higher the ColMarTech Automated Weapons Rack is void of almost if not all ammo. This is a priority to fix because it _ruins_ the new player experience as they have no ammo to use for their primary ammo before deploying. This causes frustration and can/has led to new players quitting CM before they even got to start. The root causes of this is are:
A. CTs raiding the Marine Preps after first drop for more ammo.
B. The round scale not reflecting the current population changes and/or ammo expenditures.

To fix this CT access has been removed from the Weapons Rack to eliminate the possibility of CTs pilfering the ammo from new players. To compensate, Regular Ammo in Requisitions has been _doubled_ there should no longer be a need to raid Marine Prep for ammo. The QM still has access to the vendor for edge cases where access to the Weapons Rack is needed, but they should not abuse this retention of access.

### SECONDARY ISSUE:
There should be no reason for CTs to have to raid the Marine Preps for ammo in the first place, logically this makes no sense. Requisitions is the nexus of all weapons and ammo on the Almayer. For **Regular Ammo** the logistical difficulty should be _getting_ the ammo to the frontlines for resupply, not artificial scarcity of the ammo.

This PR will ideally fix this issue as the round start regular ammo count has been doubled. **This value is subject to change.**

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>
I tested it, they don't have access and the round scale is updated to the new values.
</details>

# Changelog

:cl: NervanCatos
balance: removes CT access to marine prep weapons racks, doubles ammo count of all regular ammo in req to compensate.
/:cl:

2024-04-05 01:23 UTC, ihatethisengine commented
yeah this sucks a lot to latejoin and find NO AMMO WHATSOEVER in your squad prep. Honestly I think we should put the ammo in personal vendors instead.

2024-04-05 09:03 UTC, lcarapaica commented
I don't see the point in removing CT access from the squad prep vendors, if there's enough ammo inside requisitions there is no reason for them to use the squad one and thereby fixes your concern, CT's are NOT meant to only operate inside requisitions, but go around the ship obtaining anything and getting it where it needs to be, **vendors not having sufficient ammo has been a known issue for a while and it's good you're addressing it but it's a numbers issue.**

> the logistical difficulty should be getting the ammo to the frontlines for resupply, not artificial scarcity of the ammo.

From experience, double the ammo in the req vendors might not be enough (that vendor has always had this issue) and you're artificially creating scarcity for cargo techs where they can't get regular ammo because the main vendor ran out and they have no way to get more.

> A. CTs raiding the Marine Preps after first drop for more ammo.

Never been an issue for years, this problem started when vendor numbers were tweaked and it upset the balance, does not address the fact that most ammo boxes are filled by PFC's for their personal use and those that like to assemble crates pre-drop, I really suggest this PR be tested **without the ID modifications**

2024-04-05 10:56 UTC, Blundir commented
Also this pr cuts one of the main things CT's do post drop, there is not that much marines post drop to begin with, why cut job of someone else?

2024-04-05 11:07 UTC, TheManWithNoHands commented
This will have ripple effects you will need to adress. 
Making ammo overall more scarse for REQ, but the consuption of ammo at FOB and Front stays the same.
Forcing REQ to spend money late OP to buy regular Ammo, because the largest ammount of ammo on the Almayer is locked of to them. Or, just move the raiding of prep from mid to late round, because the QM will just do it inseatd. Just moving the porblem, not solving it.

This also cuts shot REQs acces to mutlipel other supplys besides ammo. Ie.Large ammounts of medical supplys via pouches, heavy weapon ammo, foldabel baricades, flares and everything marines drop in prep.

You will need to increase latejoin scaling for req vendors as well, and increase on not just the ammo but support items too start OP.

Also, REQ is half the reason why squad prep vendors are just completly empty. A lot of players empty out vendors to fill up boxes on their own to bring to the front. So cutting CTs acces to prep alone wont fully fix the problem.

2024-04-05 11:15 UTC, cuberound commented
I think that freeing CTs from doing this job could allow for other, more enjoyable, jobs to be given to CTs

2024-04-05 11:20 UTC, Blundir commented
> I think that freeing CTs from doing this job could allow for other, more enjoyable, jobs to be given to CTs

There is simply not much things to do beyond that, and i can't see any new req game mechanics coming anytime soon

2024-04-05 12:05 UTC, MobiusWon commented
@All, My point is there should be **no reason** for CTs to raid Marine prep _in the first place_. Their access is removed from prep to eliminate any possibility of late join Marines not having ammo in their own prep. If doubling the ammo in req isn’t enough I can quadruple it, as I said in the PR: regular ammo should not be artificially scarce, the difficulty should be getting it to the frontlines.

2024-04-05 12:07 UTC, MobiusWon commented
> I don't see the point in removing CT access from the squad prep vendors, if there's enough ammo inside requisitions there is no reason for them to use the squad one and thereby fixes your concern, CT's are NOT meant to only operate inside requisitions, but go around the ship obtaining anything and getting it where it needs to be, **vendors not having sufficient ammo has been a known issue for a while and it's good you're addressing it but it's a numbers issue.**
> 
> > the logistical difficulty should be getting the ammo to the frontlines for resupply, not artificial scarcity of the ammo.
> 
> From experience, double the ammo in the req vendors might not be enough (that vendor has always had this issue) and **you're artificially creating scarcity that ruins the new cargo tech player experience as they have no ammo to use for the supply drops, where they can't get regular ammo because the main vendor ran out and they have no way to get more. This causes frustration and can/will lead to new players quitting CM/REQ before they even got to start.**
> 
> > A. CTs raiding the Marine Preps after first drop for more ammo.
> 
> Never been an issue for years, this problem started when vendor numbers were tweaked and it upset the balance, does not address the fact that most ammo boxes are filled by PFC's for their personal use and those that like to assemble crates pre-drop, I really suggest this PR be tested **without the ID modifications**.

Testing this without ID modification will result in CTs still raiding Marine Prep.

2024-04-05 14:47 UTC, ihatethisengine commented
Problem is not that CTs raid preps because they need to. Problem is that CTs raid preps because they CAN. Sorry, if I latejoin at 00:40 and there is no ammo in prep, I highly doubt they did this because they had no other choice.

2024-04-05 15:12 UTC, MobiusWon commented
> Problem is not that CTs raid preps because they need to. Problem is that CTs raid preps because they CAN. Sorry, if I latejoin at 00:40 and there is no ammo in prep, I highly doubt they did this because they had no other choice.

I agree entirely with everything stated here. This is why I removed their access.

2024-04-05 21:24 UTC, Diegoflores31 commented
from what i know prep "raiding" rn is pretty much part of the CT gameplay. if you are going to take away CT access from Prep you should give them back their gameplay in another form like for example . ramdom crates with ammo in maintenance or something.

2024-04-05 21:31 UTC, MobiusWon commented
> from what i know prep "raiding" rn is pretty much part of the CT gameplay. if you are going to take away CT access from Prep you should give them back their gameplay in another form like for example . ramdom crates with ammo in maintenance or something.

The prep raid gameplay is dumb. 

For the random crates “WYCI”.

2024-04-06 00:52 UTC, GrrrKitten commented
> from what i know prep "raiding" rn is pretty much part of the CT gameplay. if you are going to take away CT access from Prep you should give them back their gameplay in another form like for example . ramdom crates with ammo in maintenance or something.

raiding prep isn't fun. its boring and takes a while. snatching up flares and MRE's is one thing, but having to deprive new players of ammo shouldn't be considered 'core gameplay' of CT.

2024-04-06 01:09 UTC, Drulikar requested changes
This is an okay stopgap for now, but this will be changing again in the future.

2024-04-06 01:09 UTC, Drulikar commented on code/game/machinery/vending/vendor_types/requisitions.dm
> +		list("M4A3 Magazine (9mm)", round(scale * 200), /obj/item/ammo_magazine/pistol, VENDOR_ITEM_REGULAR),
You can double it but I don't think it needs to be quadruple.

2024-04-06 01:09 UTC, Drulikar commented on code/game/machinery/vending/vendor_types/squad_prep/squad_prep.dm
> +		list("M41A Magazine (10x24mm)", round(scale * 50), /obj/item/ammo_magazine/rifle, VENDOR_ITEM_REGULAR),
This does not need to change.

2024-04-06 01:53 UTC, MobiusWon commented
> This is an okay stopgap for now, but this will be changing again in the future.

This is expected. It’s a stopgap measure.

2024-04-06 08:22 UTC, Drulikar approved these changes

2024-04-06 08:28 UTC, merged