Fixes notifications emitting light
cmss13-devs/cmss13 pull request #6088
Opened 2024-04-05 20:50 UTC by vero5123

# About the pull request
Fixes #5985, albeit there might be a better approach.

# Explain why it's good for the game
bug fix, tested it with the steps listed in the issue. Worked as far as I could tell.

# Changelog
:cl:
fix: Notifications should no longer emit light.
/:cl:

2024-04-06 10:51 UTC, harryob reviewed
don't do this - just cut the underlays of the alert_overlay

2024-04-06 10:51 UTC, harryob requested changes
^

2024-04-06 20:28 UTC, vero5123 commented
hehe, yeah.

2024-04-08 09:26 UTC, harryob approved these changes

2024-04-08 09:31 UTC, merged