The Audio Update Pt. 1: Third Coming
cmss13-devs/cmss13 pull request #614
Opened 2022-07-03 13:54 UTC by nauticall

## About The Pull Request
See https://gitlab.com/cmdevs/colonial-warfare/-/merge_requests/1688 for the original thing as well as sound samples.

**Before I get assassinated by maintainers, let it be known that Github literally prohibits me from reopening #283 because I force-pushed to it while it was closed.** So I had to make a new PR for this if this is to be reopened and all. Funky!

The culmination of like 20 combined hours of combing the A:CM sound library and cherrypicking sounds to implement into CM. The files were all numbered (not labeled) so it was an absolute pain to sort through everything and see which ones fit where.

Some of the sounds may be controversial, so let me know if anything seems better off as it was old.\

Per developer and community request this version does not come with a bloated changelog, extra voice lines, that beefy hijack thing, or that funky acid sound.

**7/3/2022:** Reopened! The bugs addressed in #283 have been fixed and addressed, and sounds that were not supposed to be there were removed.

## Why It's Good For The Game

This PR aims to bring a fresh coat of paint to the sounds you've spent years listening to over and over again. More stuff has more bass, no longer sounds like a watermelon being slapped with a stick, and overall gives better sound quality, hopefully leading to more immersion.

Hopefully.

I intend for this PR to be testmerged so that people can judge what sounds they like, what sounds they don't like, and what they'd like added.

In the future I'd like to expand on even more sounds, but this PR is a bit bloated as-is already.

## Changelog

:cl:
add: Added more than 150 new sounds into the game; most were ported from A:CM and stock SS13.
add: New firing sounds for the M37, Mk221/Mk210, M4A3, and 88 Mod 4.
add: New sounds for shotgun shell loading, glass breaking, explosions, and explosions greater than 300 power, e.g. OBs and max caps.
add: Added various new interaction noises, particularly when damaging barricades, prying doors, and picking up/dropping items.
add: Several tools now have pickup and drop sounds. In addition to the toolbelt tools, these also include binoculars and fire extinguishers.
/:cl:

2022-07-03 17:12 UTC, stanalbatross requested changes

2022-07-03 17:12 UTC, stanalbatross commented on code/game/objects/items/devices/defibrillator.dm
> -		w_class = SIZE_LARGE
WHYYYYYYYYYYYYYYYYYYYYY

2022-07-03 17:28 UTC, stanalbatross commented
some of the sounds also seem to be delayed on playing (particularly the "opening pouches" and "opening defibs" sound)

this is a bit inconsistent

2022-07-03 18:18 UTC, stanalbatross commented
cade hitting sounds were reported as being hard to notice and a bit quiet

2022-07-04 02:31 UTC, nauticall commented
> some of the sounds also seem to be delayed on playing (particularly the "opening pouches" and "opening defibs" sound)

They're totally fine on my end, I don't know what's going on with that >.>

2022-07-05 01:29 UTC, AGasCanister commented
experienced some sounds and I can say it's beautiful, I really liked them
though I must say placing items or taking items out of tables is a bit weird

2022-07-05 07:26 UTC, Wintermote commented
Some sounds were very quiet, and other sounds very loud - maybe needs loudness normalization; it might also be a problem with how the sounds are played in-game rather than anything with the audio directly.

Biggest change I noticed and liked were the sounds for moving tools around and drawing/wielding guns

2022-07-06 14:01 UTC, stanalbatross commented
the sound of xenos breaking chairs is quite weird

2022-07-06 14:28 UTC, stanalbatross commented
rob warraker says : I hate that every single action a marine does makes a sound

2022-07-06 14:29 UTC, stanalbatross commented
glass breaking is too loud

2022-07-06 14:31 UTC, stanalbatross commented
new explosions sound good; new shotgun sounds described as less impactful

2022-07-06 14:49 UTC, stanalbatross commented
wallace haar says : the overabundance of sound makes it less impactful

2022-07-06 14:50 UTC, stanalbatross commented
lumdor says : the new slash sounds are less meaty

2022-07-06 15:38 UTC, stanalbatross commented
the fact that moving items around in storage always makes a sound does get annoying

2022-07-06 17:10 UTC, stanalbatross commented
xeno door forcing keeps playing way longer after the action ends

2022-07-07 07:06 UTC, Agameofscones commented
personal takes:

Most noises that you are using from AvP are from a old stock pack from the early 2000s. I strongly recommend reverting them. They do _not_ sound good. They also remove some iconic noises from the CM audioscape (something something I did this to the smartgun and don't want it to happen again). Also we already have a custom 88m4 firing sound, I don't think it needs replacing.

Explosions are muffled. Ours aren't good persay, but this is not an upgrade.

RE: sound delays, could be filesize.
Make sure all sounds are normalized to **-8db**

Consider getting coder support to make it so items don't play their drop sound when being placed into bags.

New barricade damage sounds are kinda, eeeeh.

2022-07-07 07:13 UTC, nauticall commented
> **_Most_** noises that you are using from AvP are from a old stock pack from the early 2000s. I strongly recommend reverting them. They do _not_ sound good. They also remove some iconic noises from the CM audioscape (something something I did this to the smartgun and don't want it to happen again). Also we already have a custom 88m4 firing sound, I don't think it needs replacing.

Most game-ripped sounds were taken from A:CM. If you can state which ones in particular sound bad I'll be happy to have a look, but unless A:CM reused a lot of its sounds from AVP I didn't take anything from AVP at all.

2022-07-10 15:23 UTC, nauticall commented
Changelog 7/10:
- Reverted the following sounds: barricade damage, resin breaking, M37 shotgun.
- Added new shotgun pump sounds. Let me know if these are iffy.
- Made it so the "drop" sound only plays when actually dropping something on the floor, not moving it into a container.
- While we're at it, made the defibrillator now *properly* use the empty state when it's empty (i.e. flashing red light).

2022-07-10 21:49 UTC, Diegoflores31 commented
> most of sounds are a lil to quiet and will make a HUGE difference when you hear a legacy sound 
> xenos breaking barricades its very silent and affects balance

2022-07-23 08:32 UTC, stanalbatross commented
a few people have complained about the new pooling sound

2022-08-04 22:59 UTC, stanalbatross commented
fix conflict

2022-09-01 13:04 UTC, stanalbatross commented
requires sound review from @Agameofscones

2022-09-20 23:02 UTC, Agameofscones approved these changes
nice

2022-09-21 06:19 UTC, morrowwolf approved these changes
CODE LOOKS GOOD, IT IS TIME

2022-09-21 06:19 UTC, merged