Smoke Flamer
cmss13-devs/cmss13 pull request #6146
Opened 2024-04-14 21:55 UTC by iloveloopers

setting as draft until foam flamer is merged (or not)

# About the pull request
adds a new flamer fuel tank that turns any reagent inside into chemsmoke when fired
only 1 reagent allowed inside the tank so its not overpowered
cannot be used with the nozzle
the smoke will always have a set ammount of units in it (somewhat high) so that it works effectively with the on_touch reactions

# Explain why it's good for the game
more flamer fuel variety
new ways to apply anti-xeno chems

# Testing Photographs and Procedure

https://www.youtube.com/watch?v=ePTXqXiK330

# Changelog

:cl:
add: Adds in a new incinerator smoke tank, that turns any reagent inside it into chemsmoke when fired.
/:cl:

2024-04-19 02:05 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-04-19 16:34 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-04-24 03:26 UTC, Drulikar requested changes

2024-04-24 03:26 UTC, Drulikar commented on code/modules/projectiles/guns/flamer/flamer.dm
> +	var/use_multiplier = 2 // if you want to increase the ammount of units drained from the tank
```suggestion
	var/smoke_range = 5 // the max range the smoke will travel
	var/distance = 0 // the distance traveled
	var/use_multiplier = 3 // if you want to increase the ammount of units drained from the tank
```

2024-04-24 03:26 UTC, Drulikar commented on code/modules/projectiles/gun_attachables.dm
> +		to_chat(user, SPAN_WARNING("\The [src] can't be used with this fuel tank!"))
```suggestion
		to_chat(user, SPAN_WARNING("[src] can't be used with this fuel tank!"))
```

2024-04-24 03:26 UTC, Drulikar commented on code/modules/projectiles/magazines/flamer.dm
> +	if(!to_add.intensityfire && to_add.id != "stablefoam" && !is_smoke_tank)
```suggestion
	if(!to_add.intensityfire && to_add.id != "stablefoam" && !istype(src, /obj/item/ammo_magazine/flamer_tank/smoke))
```
Its not as clean but via short-circuiting it reduces how much type checking is done is most scenarios.

2024-04-24 21:22 UTC, Skatuk commented
So you know the disrupting research property, can it be combined with it somehow?

2024-04-25 16:24 UTC, iloveloopers commented
> So you know the disrupting research property, can it be combined with it somehow?

if you have a chemical with the disrupting property, you can fill the smoke tank with it and it will work

2024-05-10 04:41 UTC, Drulikar approved these changes
I've not been made aware of any issues with this PR nor has it received any player feedback, but should something come up feel free to open another PR.

2024-05-10 04:46 UTC, merged