Falling Falcons: Paratroopers Edition
cmss13-devs/cmss13 pull request #6150
Opened 2024-04-15 06:16 UTC by ihatethisengine

# About the pull request
Replaces rappel system with paradrop system. You still need the harness on your belt to paradrop (successfully). You also can drop objects from the above, but in most cases it's not a great idea (they can break). Crates can be paradropped too, so this can be an interensting alternative to req drops. In order for marines to paradrop, PO needs to choose a flare on the console and lock the paradrop system to the signal. After that the aft hatch will be open and you are free to jump! Just don't forget the harness.

# Explain why it's good for the game
It's cooler than rappel.

# Testing Photographs and Procedure

<details>

https://github.com/cmss13-devs/cmss13/assets/115417687/53ec9ddb-5ff5-4af2-9df5-17835e5bc2bc

https://github.com/cmss13-devs/cmss13/assets/115417687/f296c1c7-1cfe-4f8f-89c0-233f612d8542

https://github.com/cmss13-devs/cmss13/assets/115417687/579dac1c-9248-4a7c-b0f7-c9466a131335

</details>

# Changelog

:cl: ihatethisengine
add: Added paradropping
del: Removed rappeling
/:cl:

2024-04-15 13:23 UTC, fira submitted a review, later dismissed

2024-04-15 14:31 UTC, ihatethisengine commented on code/game/turfs/transit.dm
> +	Stun(3) // 3 seconds
it doesnt really matter you are dead

2024-04-15 16:34 UTC, ihatethisengine commented on tgui/packages/tgui/interfaces/MfdPanels/ParadropPanel.tsx
> +                : 'Paradropping not available.'}
why did you resolve it it's a fair question

2024-04-16 03:37 UTC, ihatethisengine commented
My parachute sprites are being held hostage but I should sort it out soon

2024-04-17 17:00 UTC, LC4492 commented
As I commented before down on discord in the contributor's channel, wouldn't be better if the marines also had the possibility of attaching the parachute on their armor (like a poncho), so they wouldn't need to sacrifice their back slot? Good PR anyway

2024-04-17 17:36 UTC, ihatethisengine commented
> As I commented before down on discord in the contributor's channel, wouldn't be better if the marines also had the possibility of attaching the parachute on their armor (like a poncho), so they wouldn't need to sacrifice their back slot? Good PR anyway

You don't really need to sacrifice anything, you can jump with items in your hands, just like you could with rappel.

2024-04-21 07:58 UTC, Drulikar requested changes

2024-04-21 07:58 UTC, Drulikar commented on code/__DEFINES/equipment.dm
> +/// Overrides smartgunner no being able to wear backpacks
```suggestion
/// Overrides smartgunner not being able to wear backpacks
```

2024-04-21 07:58 UTC, Drulikar commented on code/game/turfs/transit.dm
> +			valid_turfs += T
```suggestion
		for(var/turf/turf as anything in RANGE_TURFS(crosser.get_paradrop_scatter(), location))
			var/area/turf_area = get_area(turf)
			if(!turf_area || CEILING_IS_PROTECTED(turf_area.ceiling, CEILING_PROTECTION_TIER_1))
				continue
			if(turf.density)
				continue
			var/found_dense = FALSE
			for(var/atom/turf_atom in turf)
				if(turf_atom.density && turf_atom.can_block_movement)
					found_dense = TRUE
					break
			if(found_dense)
				continue
			if(protected_by_pylon(TURF_PROTECTION_MORTAR, turf))
				continue
			valid_turfs += turf
```

2024-04-21 07:58 UTC, Drulikar commented on code/game/turfs/transit.dm
> +	src.overlays += cables
```suggestion
	overlays += cables
```

2024-04-21 07:58 UTC, Drulikar commented on code/game/turfs/transit.dm
> +	src.forceMove(target)
```suggestion
	overlays += chute
	pixel_z = 360
	forceMove(target)
```

2024-04-21 07:58 UTC, Drulikar commented on code/game/turfs/transit.dm
> +	src.explosion_throw(200) // give it a bit of a kick
```suggestion
	explosion_throw(200) // give it a bit of a kick
```

2024-04-21 08:21 UTC, Drulikar requested changes
Also consider expending the parachute on land; or put it in a state where you have to re-pack it.

2024-04-21 08:21 UTC, Drulikar commented on code/game/turfs/transit.dm
> +	return 4
Please also do the same for `/obj/structure/largecrate`

2024-04-24 03:10 UTC, Drulikar requested changes

2024-04-24 03:10 UTC, Drulikar commented on code/game/turfs/transit.dm
> +/obj/item/handle_airdrop(turf/target, dropship_name)
Also please have primed grenades or planted c4 just qdel themselves as if they exploded mid-air including custom grenades even if they may have set a long timer.

2024-04-24 21:45 UTC, ihatethisengine commented on code/game/turfs/transit.dm
> +/obj/item/handle_airdrop(turf/target, dropship_name)
done, tested by jumping with active hefa

2024-04-25 04:48 UTC, Drulikar approved these changes

2024-05-10 09:22 UTC, nauticall approved these changes

2024-05-10 09:49 UTC, merged