Fixes delaying round start not showing on the timer.
cmss13-devs/cmss13 pull request #6166
Opened 2024-04-18 21:24 UTC by realforest2001

# About the pull request

As title

# Explain why it's good for the game

It's not always clear if it's been delayed or somehow broken anymore.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
fix: Delaying round start now shows on the timer again.
/:cl:

2024-04-20 04:33 UTC, Drulikar requested changes
You likely want to also change `/mob/new_player/get_status_tab_items()` too then because at the moment, this only affects admins who observe before game start.

2024-04-20 04:33 UTC, Drulikar commented on code/modules/mob/dead/observer/observer.dm
> +			. += "Time To Start: [round(time_remaining)]s [SSticker.delay_start ? "(DELAYED)" : ""]"
```suggestion
			. += "Time To Start: [round(time_remaining)]s[SSticker.delay_start ? " (DELAYED)" : ""]"
```

2024-04-20 12:18 UTC, realforest2001 commented
No idea how I missed new_player

2024-04-21 07:05 UTC, Drulikar approved these changes

2024-04-21 07:05 UTC, Drulikar commented on code/modules/mob/new_player/new_player.dm
> +		. += "Time To Start: [round(time_remaining)]s"[SSticker.delay_start ? " (DELAYED)" : ""]"
```suggestion
		. += "Time To Start: [round(time_remaining)]s[SSticker.delay_start ? " (DELAYED)" : ""]"
```

2024-04-21 07:13 UTC, merged