Fixes boilers slowing themselves
cmss13-devs/cmss13 pull request #6177
Opened 2024-04-21 15:35 UTC by Git-Nivrak

# About the pull request

# Explain why it's good for the game

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
fix: Fixes boilers slowing themselves by using long range sight while resting.
/:cl:

2024-04-21 17:00 UTC, fira requested changes

2024-04-21 17:00 UTC, fira commented on code/modules/mob/living/carbon/xenomorph/abilities/general_abilities.dm
> +	if(xeno && !xeno.is_mob_incapacitated() && !xeno.buckled && xeno.check_state())
```suggestion
	if(xeno?.check_state())
```

already includes buckled & incapacitated

2024-04-21 21:58 UTC, Drulikar commented
It doesn't need much, but not a very good precedent for basically every field in the PR description to be empty.

2024-04-21 22:05 UTC, Drulikar requested changes
Please also improve PR description.

2024-04-21 22:05 UTC, Drulikar commented on code/modules/mob/living/carbon/xenomorph/abilities/general_abilities.dm
> +	if(xeno?.check_state())
This results in resting always spamming you with `We cannot do this in our current state.`

As long as the ability properly ends when resting, just the check_state when trying to use_ability is likely sufficient.

2024-04-23 05:48 UTC, Drulikar approved these changes

2024-04-23 05:53 UTC, merged