Tacmap and command announcements for survivors
cmss13-devs/cmss13 pull request #6192
Opened 2024-04-25 14:53 UTC by Git-Nivrak

# About the pull request
Allows survivors to view tacmap and hear command announcements once they get IFF and marine headsets.

# Explain why it's good for the game
When you redeploy as a survivor (which is what you do 90%) it is extremely painful to play without knowing what's going on, no announcements, no tacmap no anything. It is also makes sense that you will have access to those once temporarily enlisting with the marines and having the proper equipment.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
add: Survivors can now view tacmap after being given IFF and receive command announcements with IFF and a marine headset.
/:cl:

2024-04-26 00:41 UTC, Drulikar requested changes
Currently only announcements work.

Tactical map update messages and accessing the marine tacmap do not work.

![image](https://github.com/cmss13-devs/cmss13/assets/76988376/44135916-cda8-46d6-8759-c2c1dd341147)
![image](https://github.com/cmss13-devs/cmss13/assets/76988376/6c39b73c-074e-4c59-b682-fdfc26118a09)

Various changes would have to be made for all faction checks throughout minimap.dm. It was kinda intentionally hardcoded to marine/normal hive. But look at uses of `FACTION_MARINE` in that file and consider if they aren't either marine or normal hive to check their IFF tag is marine, and if so consider their faction marine in that case.

The act for `if("selectAnnouncement")` is also where that tactical map update in progress message would get sent.

2024-04-26 00:41 UTC, Drulikar commented on code/modules/mob/living/carbon/human/human.dm
> +	if(faction == FACTION_MARINE || (FACTION_MARINE in wear_id.faction_group))
```suggestion
	if(faction == FACTION_MARINE || (FACTION_MARINE in wear_id?.faction_group))
```
Ever you take off your id, this runtimes: 
![image](https://github.com/cmss13-devs/cmss13/assets/76988376/ad257792-8d6a-44b3-87fa-8d1fbdf021f4)

2024-04-27 17:06 UTC, Git-Nivrak commented
Going to atomize this to only announcements
There appears to be more to the tacmap than just changing the faction checks and so I will rather deal with at a different time

2024-05-01 07:10 UTC, Drulikar approved these changes

2024-05-01 07:16 UTC, merged