pointing at an item in your hands shows it off
cmss13-devs/cmss13 pull request #6207
Opened 2024-04-28 22:33 UTC by AndroBetel

# About the pull request

just like that "Show held item" verb

# Explain why it's good for the game

it's hard for me personally to find that verbs in object tab sooooo

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

yep...

</details>

# Changelog

:cl:
qol: Pointing at an item in your hands shows it off.
/:cl:

2024-04-28 23:26 UTC, ihatethisengine commented
there is a keybind for it lmao but good pr

2024-04-28 23:50 UTC, AndroBetel commented
>there is a keybind for it lmao but good pr

i only have so much keys on my keyboard

2024-05-02 13:01 UTC, fira requested changes

2024-05-02 13:01 UTC, fira commented on code/modules/mob/living/carbon/human/human.dm
> +	..()
```suggestion
	return ..()
```

2024-05-02 21:56 UTC, HumiliatedGoblin commented
would it be possible to make this for equipped things, like armor, belts and backpacks too?

2024-05-03 03:21 UTC, ihatethisengine commented
> would it be possible to make this for equipped things, like armor, belts and backpacks too?

To use "show held item" verb on items you don't hold?

2024-05-03 05:00 UTC, Drulikar approved these changes

2024-05-03 06:13 UTC, merged