Xeno Crit Grace Period + Fix
cmss13-devs/cmss13 pull request #622
Opened 2022-07-04 16:40 UTC by Geevies

## About The Pull Request

Gives xenos a grace period of 1 second after reaching crit health before falling into crit. Also fixes them getting rooted in place if they fall into crit.

## Why It's Good For The Game

Was too punishing going from a variable grace period caused by Life ticks to absolutely no grace period at all, plus the buggy crit root thingy.

## Changelog

:cl:
add: Xenos now have a one second grace period before falling into crit.
/:cl:

2022-07-05 07:34 UTC, Wintermote commented
So this basically just undoes the fix applied earlier?

I don't think this is right, it's returning us to unintended behaviour - being able to fight/run away while actually at negative hp and in crit. The whole point of entering crit is that you don't get to run away.

Your "grace period" is not fighting at low hp and going to negative in the first place.

2022-07-05 11:02 UTC, JackieEstegado commented
If you are gonna give an extra second of mobility to xenos when going crit then you should atleast restrict it by not allowing ability usage during that time, so runners and lurkers don't just pounce off-screen while crit. Maybe even add a small slowdown.

2022-07-05 12:27 UTC, AGasCanister commented
give them a funny sound when in their grace period!!
https://www.youtube.com/watch?v=DcgwjseQldM

2022-07-05 15:10 UTC, c4xmaniac commented
A second is a pretty big grace period especially with byond ticks on high pop, it’ll be more like 2-3. I’m not sure why it was fixed and now it’s being unfixed, if you go into crit you should be punished for it, not given an extra amount of time to just leap away to safety.

2022-07-05 16:59 UTC, DesertFox2 commented
I'm against this, this just returns us to having ballsy runners, lurkers, and other xenos who can simply just dash offscreen for what is effectively 2-3 beyond seconds. Why are we undoing the previous fix?

2022-07-05 17:54 UTC, stanalbatross commented
The previous change showed how important the randomness of lifeticks was to xeno durability, this merely adds back a less random, more consistent version of it to undo the nerf to xeno durability in that PR. Xeno durability is going to get buffed back up to the prior level either way

2022-07-07 00:32 UTC, Wintermote commented
I don't understand what is random about "if you hit negative hp you go into crit immediately"

This change doesn't take away randomness - it introduces it with byond tick lag. The exact opposite of what you're arguing.

2022-07-09 21:56 UTC, stanalbatross requested changes
make warding pheros buff the length of the period (cool idea)

2022-07-09 21:56 UTC, stanalbatross commented on code/modules/mob/living/carbon/xenomorph/life.dm
> +	if(isXenoRunner(src) && layer != initial(layer)) //Unhide
do for larvas as well since they can hide

2022-07-09 21:58 UTC, stanalbatross commented
document sound stuff in cl too

2022-07-12 05:38 UTC, RadiationFan commented
Xeno survivability is pretty important to game balance, especially when talking about t3s, who are the primary beneficiaries of delayed deaths. I like the idea of warding giving significantly higher grace periods. Perhaps xenos will remember to turn on warding now.

2022-07-12 23:49 UTC, Nanu308 commented
This by itself is fine, timers will need adjustment especially with warding as byond ticks/lags can greatly change the intended timer of crit to go into effect.

2022-07-13 18:32 UTC, stanalbatross approved these changes

2022-07-13 18:33 UTC, merged