Watcher nerf
cmss13-devs/cmss13 pull request #6237
Opened 2024-05-03 19:16 UTC by Git-Nivrak

# About the pull request
Watcher facehugger strain now takes damage off weeds the same as the base variant 

# Explain why it's good for the game
It's a straight up upgrade to the base variant + Metagaming afk marines \ open cades from ghost is cancer

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
balance: Watcher strain now takes damage off weeds
/:cl:

2024-05-03 19:48 UTC, HeresKozmos commented
Watcher's entire gimmick is losing the ability to hide while gaining the ability to move off weeds without taking damage, this PR literally just makes the strain entirely pointless since it removes the main effect of the strain.

2024-05-03 19:56 UTC, InsaneRed commented
Theres no good argument as to why a free role that can permanetly change the round of somebody, which cost no resources basically to be moveable off weeds without any consequences, this strain is literally just an upgrade and this is required. hiding or not doesnt matter when youre ghosted and just go watch the afk marine.

2024-05-03 20:20 UTC, Butlerblock commented
Horrible design idea, but might cut down on metagaming: What if huggers and lessers had a 20-30 second minimum incubation time inwhich they're forced to sit in hive with no dchat or ghosting. There would be no hive-limit and no ghost-time requirement to start incubation, but would automatically spawn the hugger/lesser once the players ghost-cooldown and the hive's limits become available.

2024-05-04 00:01 UTC, Drulikar commented
> Horrible design idea, but might cut down on metagaming: What if huggers and lessers had a 20-30 second minimum incubation time inwhich they're forced to sit in hive with no dchat or ghosting. There would be no hive-limit and no ghost-time requirement to start incubation, but would automatically spawn the hugger/lesser once the players ghost-cooldown and the hive's limits become available.

Not a discussion for here, but if you've read some of Harry and my messages on discord & forums, you'll know that something along the lines of this will be implemented for the entire hive. As in to be in the xenomorph queue, you will become a ghost of some kind tethered to that hive's weeds/xenos. This will include lessers & huggers.

2024-05-04 00:03 UTC, Drulikar requested changes
Please instead make this so the watcher hugger has the toggle zoom ability. When that ability is active, health decrease off of weeds halts (but you do not heal either) and you are anchored in place. Otherwise without the toggle_zoom ability you will lose health off weeds just like regular hugger.

2024-05-04 09:42 UTC, Drulikar requested changes

2024-05-04 09:42 UTC, Drulikar commented on code/modules/mob/living/carbon/xenomorph/abilities/facehugger/facehugger_powers.dm
> +		REMOVE_TRAIT(facehugger, TRAIT_IMMOBILIZED, TRAIT_SOURCE_ABILITY("Long-Range Sight"))
Two things:
- There are more ways for the ability to be toggled off than clicking the button (e.g. resting). You need to instead hook this logic instead into `/mob/living/carbon/xenomorph/proc/zoom_in()` and `/mob/living/carbon/xenomorph/proc/zoom_out()`
- TRAIT_IMMOBILIZED does not currently prevent pouncing - so you can just pouce to move around.

2024-05-04 09:42 UTC, Drulikar commented on code/modules/mob/living/carbon/xenomorph/strains/castes/facehugger/watcher.dm
>  		bound_xeno.adjustBruteLoss(1)
```suggestion
	// Sap health if we're standing, not on weeds, and not zoomed out
	if(bound_xeno.body_position != STANDING_UP)
		return
	if(bound_xeno.is_zoomed)
		return
	if(locate(/obj/effect/alien/weeds) in get_turf(bound_xeno))
		return
	bound_xeno.adjustBruteLoss(1)
```
This check has become unwieldly. https://github.com/cmss13-devs/cmss13/blob/master/.github/guides/STYLES.md#use-early-returns Also its slightly better to check easy checks before more complicated check, so do the is_zoomed check earlier.

2024-05-05 02:42 UTC, Drulikar approved these changes

2024-05-05 02:42 UTC, Drulikar commented on code/modules/mob/living/carbon/xenomorph/abilities/facehugger/facehugger_powers.dm
> +
```suggestion
```

2024-05-05 02:42 UTC, Drulikar commented on code/modules/mob/living/carbon/xenomorph/abilities/ability_helper_procs.dm
> +	for (var/datum/action/xeno_action/onclick/toggle_long_range/action in actions)
This is a weird way to do this, but using `get_xeno_action_by_type` isn't much better so its whatever.

2024-05-05 02:57 UTC, merged