Xenos cannot pylon working comms anymore
cmss13-devs/cmss13 pull request #6241
Opened 2024-05-05 17:00 UTC by ihatethisengine

# About the pull request
First of all, it looks like a simple oversight. You cannot turn on a pyloned comms tower, but for some reason it works the other way around — you can pylon a working tower. Don't think this was intended. 

Secondly, I think it's a little too boring that you can get both pylon and working comms if you have corrupted xenos. It would be more interesting if you needed to choose between these options.

# Explain why it's good for the game
Consistency, balance, important choices.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl: ihatethisengine
balance: only disabled comms can be pyloned
/:cl:

2024-05-05 19:49 UTC, HeresKozmos commented
Seems pretty cool.

2024-05-06 08:15 UTC, Drulikar requested changes
I could be wrong, but this is not a repeating call to `handle_xeno_acquisition` (except if those timers are used below). This is the proc called for the signal `COMSIG_WEEDNODE_GROWTH` or a re-call using one of the addtimers a little further down. You likely need to in this situation either add a signal for the tower going inoperable, or for you to add a timer to recheck again later.

2024-05-06 08:15 UTC, Drulikar commented on code/game/machinery/telecomms/presets.dm
> +	if(!inoperable() || on)
```suggestion
	if(operable())
```
Not sure I see the point of testing `on` we only care about whether its operable.

2024-05-06 09:33 UTC, ihatethisengine commented
What about this?

2024-05-10 07:52 UTC, Drulikar requested changes
This works, but means that this proc is now very spammable (e.g. toggling the power on and off at the apc). The timers should then be considered unique and allowed to override one another else you can create lots of timers that are redundant: 
![image](https://github.com/cmss13-devs/cmss13/assets/76988376/8e6fbbf1-d03d-4a98-8082-d675633f1862)

2024-05-11 12:25 UTC, Drulikar approved these changes

2024-05-11 12:30 UTC, merged