Infection icon now has lower alpha if the human is dead
cmss13-devs/cmss13 pull request #6254
Opened 2024-05-07 03:41 UTC by ihatethisengine

# About the pull request
So this was bothering me for a long time and now I finally found a simple solution.

I cannot make 5 new sprites to display that hugged person is dead.

I cannot change the color of the sprite, as you need to know which hive larva belongs to.

But I can lower alpha! Simple solution.

# Explain why it's good for the game
Makes it less confused for both xenos and observers to figure if the hugged person is dead. Sometimes xenos ignore people who stepped in a resin trap because they assume that the person is dead, why would the person be lying in the middle of nowhere otherwise?

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
add: Added something
del: Removed old things
qol: made something easier to use
balance: rebalanced something
fix: fixed a few things
spellcheck: fixed a few typos
ui: changed something relating to user interfaces
code: changed some code
refactor: refactored some code
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
mapadd: added a new map or section to a map
maptweak: tweaked a map
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

2024-05-07 03:41 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-05-07 03:43 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-05-07 03:44 UTC, ihatethisengine commented
Unreal conflict with my own PR

2024-05-07 03:47 UTC, ihatethisengine commented
Thanks for helping me with the conflict, web-editor :roll_eyes:

2024-05-07 21:01 UTC, HeresKozmos commented
Pretty neat.

2024-05-10 04:28 UTC, realforest2001 approved these changes

2024-05-10 05:04 UTC, Drulikar requested changes
This needs to also reset the alpha if they then are revived. Simple solution would be to else set the alpha to full.

2024-05-10 10:12 UTC, ihatethisengine commented on code/datums/mob_hud.dm
> +
```suggestion
				if(stat == DEAD || status_flags & FAKEDEATH)
					holder2.alpha = 100
					holder3.alpha = 100
				else
					holder2.alpha = 255
					holder3.alpha = 255
```

2024-05-10 11:20 UTC, Drulikar approved these changes
I will note is also leaves the death icon transparent if they are a xeno host, but this is probably fine.
![image](https://github.com/cmss13-devs/cmss13/assets/76988376/d1dcea3a-2f35-4264-b64b-c4ffb0c4798e)

2024-05-10 11:26 UTC, merged