Project ARES: Almayer Sentries
cmss13-devs/cmss13 pull request #6268
Opened 2024-05-09 14:38 UTC by realforest2001

# About the pull request

Changes the sprites for the sentry deployment systems aboard the USS Almayer to use a custom floor based holder, rather than a floating wall mount.

Also adds mini sentry deployers, along with an AI-Core subtype that autodeploys on lockdown.

# Explain why it's good for the game

Currently the sentry deployment system sprites are designed as if they're mounted to walls, and they usually are, but on the Almayer they're essentially floating next to the fuel pumps. This changes that.

Also it allows the AI Core to be protected from xenos without subjecting non-existant joes to melee combat.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
imageadd: added sprites for floor-mounted sentry deployment systems.
add: Added mini-sentry deployment systems, and an AI Core subtype.
/:cl:

2024-05-14 10:52 UTC, Drulikar requested changes
They push you off of them when they deploy, but they don't have density: 
![image](https://github.com/cmss13-devs/cmss13/assets/76988376/34789d28-9d60-46c1-ac28-afb9a1ee6735)

Also kinda minor, but their examine icon is odd: 
![image](https://github.com/cmss13-devs/cmss13/assets/76988376/4dab0185-9c4f-4e53-9916-8a1b2fc89b24)

Then again, a regular sentry isn't much better...
 
![image](https://github.com/cmss13-devs/cmss13/assets/76988376/0bf9a2bc-4696-44d9-af36-1b038f699ba4)

2024-05-14 10:52 UTC, Drulikar commented on code/game/machinery/sentry_holder.dm
> +			//to_chat(user, SPAN_WARNING("[src] is non-functional."))
```suggestion
```

2024-05-19 21:41 UTC, sleepynecrons requested changes
the colors should be consistent with the rappel hatch

also there should be a deploying animation unless i'm missing something

2024-05-19 22:47 UTC, realforest2001 commented
Colours I'll change when I have time, hopefully tomorrow. As for animation the current deploy system doesn't use one so I haven't made one. I'd have to animate and delay everything on both systems otherwise.

2024-05-19 22:47 UTC, realforest2001 commented
Examine icons I can't do much about, they're kinda borked on just about everything in the game

2024-05-24 05:55 UTC, sleepynecrons approved these changes
sprites

2024-05-25 13:33 UTC, Drulikar approved these changes

2024-05-25 13:33 UTC, Drulikar commented on code/game/machinery/sentry_holder.dm
> +				step(M, get_dir(src,deployed_turret))
```suggestion
		for(var/mob/blocking_mob in deployed_turret.loc)
			if(deployed_turret.loc == loc)
				step(blocking_mob, deployed_turret.dir)
			else
				step(blocking_mob, get_dir(src, deployed_turret))
```

2024-05-25 13:42 UTC, merged