Whiskey Outpost for burrower add the ability to make tunnel but remove the ability to burrow.
cmss13-devs/cmss13 pull request #6283
Opened 2024-05-13 11:49 UTC by Huffie56

# About the pull request
For burrower remove the ability to burrow.
add back the ability to make tunnel

# Explain why it's good for the game
The idea in adding the ability to add tunnels is to help xeno going faster to the moving frontline.

burrowing would be too powerfull with this ability so i am removing it.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
balance: for burrower in whiskey outpost add the ability to make tunnel but remove the ability to burrow.
/:cl:

2024-05-14 08:04 UTC, Drulikar requested changes
I am not very keen on this change; but regardless if you wanted to do this, then you must increase access to plastic explosives for WO vendors.

2024-05-14 09:28 UTC, ihatethisengine commented
I think this change is good. Tunnels will make it easier to travel on WO, and without burrowing you won't have cheese tunnels in your rear.

2024-05-27 09:38 UTC, Huffie56 commented
should be fine i left drop pouch as it as it's use outside of dropping with a DS with it.
decided to group all the change on a single PR to avoid merge conflicts.
hope it's not to bad it's been a while since i touch code.

2024-06-03 17:01 UTC, Drulikar approved these changes

2024-06-03 17:06 UTC, merged