CIC Vendor Expansion (Part 2)
cmss13-devs/cmss13 pull request #6301
Opened 2024-05-17 09:49 UTC by SpypigDev

# About The Pull Request
Follow up PR to [#4707](https://github.com/cmss13-devs/cmss13/pull/4707). Aims to expand XO vendors to bring them up to date with modern combat meta, as well as clean up my SO vendor update in the process.
- Added gear specializations to the XO weapons vendor, offering the essentials set of either a Medic or Engineer
- Adds a Magharn to rail attachments section in the XO weapons vendor
- Expanded belt/pouch options in the XO weapons vendor
- Added the 'other gear' section in the XO vendor, with various combat supplies

Misc.
- Fixed XO/SO vendor code so that selecting the autoinjector pouch gives you a full one, rather than empty
- ~~Increased XO policing skillset from 1, to 2, so they can actually use the MP belt they are offered~~ (Already done in #6781 )
- Unified the SO armory vendor code into the regular SO vendor file, rather than having two seperate

# Explain why it's good for the game

The XO gear vendors have sat untouched in the code for quite some time, and have been left to fall behind the quickly changing meta of CM. With a more updated selection of modern gear, XOs will no longer be significantly out-geared by their Staff Officers when it comes to organizing their combat kits, especially during hijack. 

XOs will be brought up to par with the gear diversity that SOs have enjoyed for some months now.

# Testing Photographs and Procedure

Select photos of the updated XO vendor menus, where changes have been made

<details>

![Screenshot 2024-05-17 160207](https://github.com/cmss13-devs/cmss13/assets/31124786/bc48f7e7-a6d4-44a6-91c8-7e9090ab83a8)

![Screenshot 2024-05-17 160216](https://github.com/cmss13-devs/cmss13/assets/31124786/b48ebdd3-7f3a-42cb-9411-ae5385c9273d)

![Screenshot 2024-05-17 160228](https://github.com/cmss13-devs/cmss13/assets/31124786/f2b14ecb-ff72-4437-ad24-3692e0447d13)

![Screenshot 2024-05-17 160236](https://github.com/cmss13-devs/cmss13/assets/31124786/f07ff972-ed74-478e-9eec-e2080c128f60)

</details>

# Changelog
:cl:
refactor: SO armory vendor code refactored into the main SO gear vendor code
balance: XO weapon and clothing vendors fitted with a more modernized equipment set
balance: XO weapon vendor now offers Medic or Engineer essentials sets
fix: Vending an autoinjector pouch as SO or XO now produces a full pouch, rather than empty
balance: SO's mod88 removed from cryo spawn and moved to their vendor instead
/:cl:

2024-05-30 23:06 UTC, Nanu308 reviewed
mapping itself is fine

2024-05-30 23:06 UTC, Nanu308 commented on maps/map_files/USS_Almayer/USS_Almayer.dmm
mapping itself is fine

2024-06-12 02:57 UTC, Drulikar commented
Stale exempt until it can be balance/code reviewed. Sorry just a lot going on right now.

2024-07-09 23:46 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-07-15 06:26 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-07-18 20:03 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-07-19 03:26 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-07-19 05:16 UTC, Drulikar requested changes
Feel free to undraft when you're happy with the vendor contents. If both are going to have essential kits, likely their vendors should be very similar just minus anything XO might get in their other vendor.

2024-07-19 21:06 UTC, Drulikar requested changes
Mentioned in DMs: 
- Consider adding `/obj/item/storage/belt/gun/utility/full` to XO since SO is offered it.
- Consider adding `/obj/item/attachable/bayonet` to XO since SO is offered it.
- Consider removing `/obj/item/storage/belt/gun/m4a3/mod88` from SO cryo spawn to instead offer it with with their other pistol belt options in their vendor.

2024-07-24 05:06 UTC, deathrobotpunch commented
one thing I would like to see is a flash added to the SO vendor like every other head of staff.

2024-08-03 04:34 UTC, Drulikar approved these changes

2024-08-03 04:42 UTC, Drulikar approved these changes

2024-08-03 04:42 UTC, Drulikar commented on code/game/machinery/vending/vendor_types/crew/senior_officers.dm
> +		list("M276 Holster Toolrig", 0, /obj/item/storage/belt/gun/utility/full, MARINE_CAN_BUY_BELT, VENDOR_ITEM_REGULAR),
```suggestion
		list("M276 Holster Toolrig (Full)", 0, /obj/item/storage/belt/gun/utility/full, MARINE_CAN_BUY_BELT, VENDOR_ITEM_REGULAR),
```

2024-08-03 04:42 UTC, Drulikar commented on code/game/machinery/vending/vendor_types/crew/staff_officer.dm
> +		list("M276 Holster Toolrig", 0, /obj/item/storage/belt/gun/utility/full, MARINE_CAN_BUY_BELT, VENDOR_ITEM_REGULAR),
```suggestion
		list("M276 Holster Toolrig (Full)", 0, /obj/item/storage/belt/gun/utility/full, MARINE_CAN_BUY_BELT, VENDOR_ITEM_REGULAR),
```

2024-08-03 04:51 UTC, merged