Queen qol
cmss13-devs/cmss13 pull request #6336
Opened 2024-05-26 10:39 UTC by Git-Nivrak

# About the pull request
Improves anti bodyblock and changes some prefixes

# Explain why it's good for the game
Prefix wise the matriarch was an ancient empress\queen which sounds better than "Prime Empress" (given you are playing a queen and not an empress but that's another story)
As for the anti-bodyblock you shouldn't have to be worrying about that when playing Queen even with the shove unless you are ready to shove anyone instantly even half a second of bodyblock can make a difference and is just annoying, It is technically a buff so I will list it as balance

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
add: Changed Queen playtime prefixes
balance: Queen will now automatically knock over allied xenomorphs in her way
/:cl:

2024-05-26 14:12 UTC, InsaneRed commented
This is going to cause issues when you eventually try to eat bullets for allied and knock them down on accident.

2024-05-26 16:03 UTC, neeshacark commented
now im not familiar with how your codebase manages this but i feel like these two changes should definitely not be the same pr

2024-05-27 00:52 UTC, iloveloopers commented
could the bump shove be extended to hive leaders?

2024-05-27 01:48 UTC, Zonespace27 requested changes
Atomize the queen name change into its own PR (none of this is QOL)

2024-06-11 01:07 UTC, closed without merging