Misc polish and qol - Surgery, construction, plasteel.
cmss13-devs/cmss13 pull request #6340
Opened 2024-05-27 08:08 UTC by hislittlecuzingames

# About the pull request

Minor QOL and balance change. Surgery, construction, plasteel.

# Explain why it's good for the game

Allows surgery and construction to be done in shallow water and shallow puddles. My rule was "There can only be one 'full' water tile in the shortest path across the depth of the puddle. if the shortest path is 2 or more 'full' water tiles, it's too deep to do surgery."
Select "long" puddles allow it if they're still only 1 tile at most for the shortest path. 
My lore imagination says "okay, this is ankle-deep water, maybe shin-deep, but not knee-deep, so a roller bed should be mostly unobstructed, and the water isn't flowing. Beachheads have waves, but not puddles. Ponds are too deep."

Gives Com Tech's 40 plasteel instead of 30. This makes it an even 5 plasteel doors (instead of 3 doors and 6 leftover plasteel)
I think com techs are tedious enough as it is to play for many players, so just allowing that to be an even number and not have leftover materials will make it just a little easier on the com techs, and lower population com techs to get that little edge when there's only like 2~3 in the game. 
Plus you pretty much can't find plasteel almost anywhere in maps, so you just have that extra 6 the rest of the match. I don't think it'd be fair to lower price of plasteel to 5 points in prep locker/vendors, so I just gave extra.

I am open to top maintainers' thoughts on 40 plasteel. I'm bad at math and only just realised 32 plasteel would be the next highest number to not have left over plasteel. 
Realising this, I still believe 40 is fair, but if it is thought to be too powerful, let me know why. Com tech mains may be too powerful with 2 extra plasteel doors instead of 1 extra. 

# Testing Photographs and Procedure

I allowed surgery in another PR. 

demonstration of 40 plasteel. 

<details>

https://github.com/cmss13-devs/cmss13/assets/142365554/803939bf-f7dc-4c15-9074-ff7cffd3f778

</details>

# Changelog

:cl:
qol: Surgery and construction allowed on select small puddles. 
balance: Com Techs get 40 plasteel instead of 30.
/:cl:

2024-05-27 13:35 UTC, Osmos123 commented
I wonder if you could adjust it in another way by making the plasteel doors cost 10 plasteel instead of 8. That way it will divide evenly with either the 30 or the increase to 40 that you suggested. Purchasing more plasteel in the vendor by 10 will also make sure you will not have any left over plasteel.

2024-05-27 17:16 UTC, hislittlecuzingames commented
> I wonder if you could adjust it in another way by making the plasteel doors cost 10 plasteel instead of 8. That way it will divide evenly with either the 30 or the increase to 40 that you suggested. Purchasing more plasteel in the vendor by 10 will also make sure you will not have any left over plasteel.

I want to improve the qol of com tech.

2024-05-27 21:57 UTC, Diegoflores31 commented
> I wonder if you could adjust it in another way by making the plasteel doors cost 10 plasteel instead of 8. That way it will divide evenly with either the 30 or the increase to 40 that you suggested. Purchasing more plasteel in the vendor by 10 will also make sure you will not have any left over plasteel.

10 plasteel per cade is insane . you would be better off making rwalls lmao

2024-05-30 15:55 UTC, Zonespace27 requested changes

2024-05-30 15:55 UTC, Zonespace27 commented on code/game/turfs/floors/desert.dm
> +	supports_surgery = TRUE
```suggestion
	icon_state = "shore_edge1"
	
/turf/open/desert/desert_shore/shore_edge1/can_surgery
	allow_construction = TRUE
	supports_surgery = TRUE

/turf/open/desert/desert_shore/shore_corner1
	name = "shore"
	icon_state = "shore_corner1"
	
/turf/open/desert/desert_shore/shore_corner1/can_surgery
	allow_construction = TRUE
	supports_surgery = TRUE

/turf/open/desert/desert_shore/shore_corner2
	name = "shore"
	icon_state = "shore_corner2"
	
/turf/open/desert/desert_shore/shore_corner2/can_surgery
	allow_construction = TRUE
	supports_surgery = TRUE
```

2024-05-30 15:55 UTC, Zonespace27 commented on code/game/turfs/open.dm
> +/turf/open/gm/river/can_surgery
```suggestion
	minimap_color = MINIMAP_WATER
	
/turf/open/gm/river/can_surgery
```

2024-05-30 15:55 UTC, Zonespace27 commented on code/game/turfs/floors/desert.dm
> +/turf/open/gm/river/desert/shallow/can_surgery
```suggestion
	icon_overlay = "_shallow"
	
/turf/open/gm/river/desert/shallow/can_surgery
```

2024-05-30 15:55 UTC, Zonespace27 commented on code/game/turfs/open.dm
> +/turf/open/gm/coast/can_surgery
```suggestion
	supports_surgery = FALSE
	
/turf/open/gm/coast/can_surgery
```

2024-05-30 15:55 UTC, Zonespace27 commented on code/game/turfs/open.dm
> +/turf/open/gm/coast/beachcorner2/can_surgery
```suggestion
	icon_state = "beachcorner2"
	
/turf/open/gm/coast/beachcorner2/can_surgery
```

2024-05-30 15:55 UTC, Zonespace27 commented on code/game/turfs/open.dm
> +/turf/open/gm/coast/beachcorner/can_surgery
```suggestion
	icon_state = "beachcorner"
	
/turf/open/gm/coast/beachcorner/can_surgery
```

2024-05-30 15:55 UTC, Zonespace27 commented on code/game/machinery/vending/vendor_types/squad_prep/squad_engineer.dm
> -		/obj/item/stack/sheet/plasteel/medium_stack,
make this change its own PR.

2024-05-30 21:41 UTC, hislittlecuzingames commented on code/game/machinery/vending/vendor_types/squad_prep/squad_engineer.dm
> -		/obj/item/stack/sheet/plasteel/medium_stack,
reverted change to make new pr

2024-06-04 21:15 UTC, hislittlecuzingames commented
@Zonespace27 @Nanu308 
Changes have been made appropriately according to feedback. 
Looking forward to the next bit of feedback.

2024-06-16 21:11 UTC, Zonespace27 approved these changes
code is fine

2024-06-19 00:19 UTC, Drulikar requested changes
In general I don't see much point to this PR. Why should very specific locations allow construction and surgery? All this does is introduce inconsistency.

2024-06-19 00:19 UTC, Drulikar commented on maps/map_files/Sorokyne_Strata/Sorokyne_Strata.dmm
Doesn't make really any sense that you'd be allowed to construct or do surgery on hot springs.

2024-06-19 00:19 UTC, Drulikar commented on maps/map_files/Kutjevo/Kutjevo.dmm
Changes are incomplete 
![image](https://github.com/cmss13-devs/cmss13/assets/76988376/76c4ee74-dbbd-47e1-b0f9-a0d1b4193d24)

2024-06-19 00:19 UTC, Drulikar commented on maps/map_files/DesertDam/Desert_Dam.dmm
Whats special about the left lake that it allows surgery but the others don't? 
![image](https://github.com/cmss13-devs/cmss13/assets/76988376/85bbb744-59e2-45fb-8bae-93bfb5b52031)

2024-06-19 13:45 UTC, hislittlecuzingames commented on maps/map_files/Sorokyne_Strata/Sorokyne_Strata.dmm
They don't appear to be hot; I'm not sure how one would make said distinction unless they read the lore. 
If someone can walk in it without getting hurt, then it would make sense that someone could lay on a rollerbed where only the wheels are in the water. 

Last night on Desert Dam, I was watching a medic explain that shallow puddles doesn't let people do surgery. 

It's just small water puddles. 
The consistency is when water is a maximum of one "full" water tile on the shortest distance across the body of water.
I was imagining that puddles were there for visual flare. 
Some puddles are in really gameplay inconvenient spots like the area around an FOB, or a safe wall near major combat zones.

I'm not sure if I'm explaining myself coherently.

2024-06-19 14:09 UTC, hislittlecuzingames commented on maps/map_files/DesertDam/Desert_Dam.dmm
The other ponds are more than 1 tile "deep".

I decided to just allow surgery on all the ponds to avoid confusion. 
I assume it'll just be changed that way in a few months anyway.

2024-06-19 16:35 UTC, Drulikar commented on maps/map_files/Sorokyne_Strata/Sorokyne_Strata.dmm
Don't allow surgery on hot springs. Its not some niche lore thing. The entire icy environment is lush from the hot springs. The area is called hot springs. They intended to be hot springs.

2024-06-19 21:12 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-06-20 16:12 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-06-20 16:16 UTC, hislittlecuzingames commented
In files changed, I see some deleted sections. 
I looked all over, but didn't see any "missing tiles" in Strong DMM. 

They may all exist in Kutjevo only.

2024-06-20 17:04 UTC, hislittlecuzingames commented
I have to redo the merge conflicts and use the hook. 
https://github.com/cmss13-devs/cmss13/blob/master/tools/hooks/README.md

2024-07-08 01:00 UTC, closed without merging