Vampire nerf
cmss13-devs/cmss13 pull request #6342
Opened 2024-05-27 13:58 UTC by InsaneRed

# About the pull request

Tile clicking with tailjab now slows you instead of stunning.
Sprite clicking with tailjab now knocks you down.

# Explain why it's good for the game
A caste that already has healing, acid runner speed, very low cooldowns, dash, execute that heals even more and more does not need an auto aimed ability that stuns you just because you clicked near the marine.

This aims to still keep the tileclick useful (it slows now) as to not completetly remove the hand holding, but rewarding people more for sprite clicking by adding the stun ontop of the extra damage it already has.

Theres a difference between making the game accessible to newer players and completely removing any resemblance of skill / effort required to *do* well.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
balance: Vampire Tail Jab no longer stuns for clicking on the mobs tile, rather it slows them.
balance: Vampire Tail Jab stuns on sprite click.
spellcheck: Vampire lurkers no longer "throw it back" after hitting somebody with their Tail Jab
/:cl:

2024-05-27 18:30 UTC, neeshacark commented
![image](https://github.com/cmss13-devs/cmss13/assets/44718209/af884430-c6a0-47a5-bfb0-27bf411946c3)

owl is of the opinion this nerf doesnt do shit

2024-05-27 21:21 UTC, InsaneRed commented
i think these will be enough to make it fair, just remember that xenos are supposed to be stronger and i tried to stay faithful to that and neutral despite all my hatred against the strain. My main issue is that aimbot just makes the caste less fun to fight against.

Its supposed to be a fast fighter with lower cd and if i touch any of those i think it would break the caste too much in terms of making it useless.

2024-05-28 08:52 UTC, Drulikar requested changes

2024-05-28 08:52 UTC, Drulikar commented on code/modules/mob/living/carbon/xenomorph/abilities/lurker/lurker_powers.dm
> +	if(!step_away(hit_target, xeno))
As mentioned on discord try instead `step` here likely in `stab_direction`. If `step` returns false entering this code you'll likely want that to induce `hit_target.apply_effect(0.5, WEAKEN)` if `if (hit_target.mob_size < MOB_SIZE_BIG)`

Reference https://github.com/cmss13-devs/cmss13/blob/5197640b085c59240d1449588371d3cc7bb3b01f/code/datums/ammo/ammo.dm#L138 for what all occurs for knockback/slamming.

2024-06-04 15:10 UTC, closed without merging