Vampire tail jab changes (try 2)
cmss13-devs/cmss13 pull request #6376
Opened 2024-06-04 16:37 UTC by Red-byte3D

# About the pull request
Makes tail jab only knock you down if you hit an obstacle.

# Explain why it's good for the game

A caste that already has healing, acid runner speed, very low cooldowns, dash, execute that heals even more and more does not need an auto aimed ability that stuns you just because you clicked near the marine.

Theres a difference between making the game accessible to newer players and completely removing any resemblance of skill / effort required to do well.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
balance: Vampire tail jab now only stuns if you knockback an enemy into an obstacle.
spellcheck: Vampire lurkers no longer "throw it back" after hitting somebody with their Tail Jab
/:cl:

2024-06-04 16:55 UTC, vero5123 reviewed
<img width="675" alt="Screen Shot 2024-06-04 at 12 46 23 PM" src="https://github.com/cmss13-devs/cmss13/assets/73014819/17c39851-af57-499c-b4cb-3bd783718cb3">

2024-06-04 16:55 UTC, vero5123 commented on code/modules/mob/living/carbon/xenomorph/abilities/lurker/lurker_powers.dm
> +	hit_target.apply_effect(0.5, SLOW)
```suggestion
	hit_target.Slow(0.5)
```

2024-06-04 16:55 UTC, vero5123 commented on code/modules/mob/living/carbon/xenomorph/abilities/lurker/lurker_powers.dm
> +			hit_target.apply_effects(0.5, SLOW)
```suggestion
			hit_target.Slow(0.5)
```

2024-06-04 16:55 UTC, vero5123 commented on code/modules/mob/living/carbon/xenomorph/abilities/lurker/lurker_powers.dm
> +			hit_target.apply_effect(0.5, WEAKEN)
```suggestion
			hit_target.KnockDown(0.5)
```

2024-06-04 16:55 UTC, vero5123 commented on code/modules/mob/living/carbon/xenomorph/abilities/lurker/lurker_powers.dm
> +		playsound(hit_target.loc, "punch", 25, 1)
```suggestion
		playsound(hit_target, "punch", 25, 1)
```

2024-06-04 19:01 UTC, vero5123 commented on code/modules/mob/living/carbon/xenomorph/abilities/lurker/lurker_powers.dm
> +		playsound(hit_target.loc, "punch", 25, 1)
```suggestion
		playsound(hit_target, "punch", 25, 1)
```

2024-06-04 20:05 UTC, vero5123 commented
Balance aside, I feel like it would be a little more satisfying if smaller mobs actually got tossed onto the wall. 
Without flinging the mob 

https://github.com/cmss13-devs/cmss13/assets/73014819/e9435885-2d22-48fc-9830-2e8777e71350

throwing the mob

https://github.com/cmss13-devs/cmss13/assets/73014819/8206ae5b-4895-445a-8d40-e5f1e4331211

For reference I used the throw_carbon() proc.

2024-06-09 00:35 UTC, Diegoflores31 commented
this PR is basically removing Tail jab completely and making it a normal tail stab ??? having to rely on walls to do damage is a bad balance take .

2024-06-09 06:49 UTC, Drulikar commented
> this PR is basically removing Tail jab completely and making it a normal tail stab ??? having to rely on walls to do damage is a bad balance take .

Of note, the ability still does its normal damage, its just a bit extra damage for slamming into a wall exactly like bullets that knockback mobs into an obstacle small some damage. The removal is the stun and making that only occur for wall slam.

2024-06-17 13:28 UTC, Diegoflores31 commented
> Of note, the ability still does its normal damage, its just a bit extra damage for slamming into a wall exactly like bullets that knockback mobs into an obstacle small some damage. The removal is the stun and making that only occur for wall slam.

This ability damage is the same damage than a a lurker tail stab and you cant target target it to limbs so the damage is very low even on direct hit. Considering it pushes you only 1 tile away . The situations where you somehow pull a stun is very scarce and the caste should not be relying on it to be able to kill a marine that can stun and kill you extremely quick.

2024-06-19 07:19 UTC, Drulikar requested changes

2024-06-19 07:19 UTC, Drulikar commented on code/modules/mob/living/carbon/xenomorph/abilities/lurker/lurker_powers.dm
> +		return
Why would we not perform damage if we're on the same tile? The only thing that should be skipped is the wallslam part of the code. We have yet to apply the slow, animation, damage, log, etc. yet.

2024-06-19 08:20 UTC, Drulikar commented
Also take into consideration that this will make execute harder to pull off too since that requires knock down or unconscious.

2024-06-19 13:04 UTC, Red-byte3D commented
> Also take into consideration that this will make execute harder to pull off too since that requires knock down or unconscious.

does not matter in the contextg of execute, you can only really reliably execute somebody if they are crit or letting you

2024-06-19 16:07 UTC, Drulikar commented
> > Also take into consideration that this will make execute harder to pull off too since that requires knock down or unconscious.
> 
> does not matter in the contextg of execute, you can only really reliably execute somebody if they are crit or letting you

I repeat, an execute can only be performed when the target is unconscious or knocked out. It *does* matter. The code isn't looking for "crit" or "they are letting you". 

https://github.com/cmss13-devs/cmss13/blob/d28283bae1c987f8e27e3e66d8459ee91a7b3e7f/code/modules/mob/living/carbon/xenomorph/abilities/lurker/lurker_powers.dm#L327-L329

2024-06-21 15:10 UTC, Drulikar approved these changes
Don't stress about what I was asking about; its simply that I was under the impression you could try to combo these together since I thought the KnockDown applied that trait that headbite is looking for.

But if it needs further tweaks I will consider making it part of a combo for example say you can only headbite as a follow up to jab or rush something, especially since there's now a visual indicator when they're a headbite eligible target - so now I could make more complicated requirements and still have that intuited by the player.

2024-06-21 15:16 UTC, merged

2024-06-21 18:30 UTC, Diegoflores31 commented
> But if it needs further tweaks I will consider making it part of a combo for example say you can only headbite as a follow up to jab or rush something, especially since there's now a visual indicator when they're a headbite eligible target - so now I could make more complicated requirements and still have that intuited by the player.

You cant headbite people unless they are inconcious.
Its not a part of the combo at all nor used to do damage , its just an ability to "glory kill" the marine when its already critted

2024-06-21 19:53 UTC, Drulikar commented
It not *currently* part of a combo.