Show facehugger limit when examining eggs/morphers
cmss13-devs/cmss13 pull request #6386
Opened 2024-06-06 03:10 UTC by zzzmike

# About the pull request

When you examine a hive core, it tells you the lesser drone limit, and the current amount of lesser drones. This adds a similar behavior for eggs and morphers with regards to playable facehuggers.

# Explain why it's good for the game

Helpful for ghosts to decide whether to play hugger, drone, neither, or just for information.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
qol: examining eggs/morphers tells you current number of huggers and the limit
/:cl:

2024-06-08 07:26 UTC, harryob requested changes

2024-06-08 07:26 UTC, harryob commented on code/modules/cm_aliens/structures/egg.dm
> +		var/datum/hive_status/hive = GLOB.hive_datum[XENO_HIVE_NORMAL]
```suggestion
		var/datum/hive_status/hive = GLOB.hive_datum[hivenumber]
```

2024-06-08 07:26 UTC, harryob commented on code/modules/cm_aliens/structures/special/egg_morpher.dm
> +		. += "Current facehugger limit: <b>[current_hugger_count]/[hive.playable_hugger_limit]</b>"
```suggestion
		var/current_hugger_count = linked_hive.get_current_playable_facehugger_count();
		. += "Current facehugger limit: <b>[current_hugger_count]/[hive.playable_hugger_limit]</b>"
```

2024-06-08 07:26 UTC, harryob commented on code/modules/mob/living/carbon/xenomorph/hive_status.dm
> +endproc
huh?

```suggestion
```

2024-06-12 00:59 UTC, vero5123 commented on code/modules/mob/living/carbon/xenomorph/hive_status.dm
> +		if(isfacehugger(mob))
```suggestion
	for(var/mob/xeno_mob as anything in totalXenos)
		if(isfacehugger(xeno_mob))
```

2024-06-19 01:45 UTC, Drulikar requested changes
To use the same formatting as lesser examines.

![image](https://github.com/cmss13-devs/cmss13/assets/76988376/73c7dbc0-885c-4f1a-aad5-748b69903e25)

2024-06-19 01:45 UTC, Drulikar commented on code/modules/cm_aliens/structures/egg.dm
> +		. += "Current facehugger limit: <b>[current_hugger_count]/[hive.playable_hugger_limit]</b>"
```suggestion
		. += "There are currently [SPAN_NOTICE("[current_hugger_count]")] facehuggers in the hive. The hive can support [SPAN_NOTICE("[hive.playable_hugger_limit]")] facehuggers."
```

2024-06-19 01:45 UTC, Drulikar commented on code/modules/cm_aliens/structures/special/egg_morpher.dm
> +		. += "Current facehugger limit: <b>[current_hugger_count]/[linked_hive.playable_hugger_limit]</b>"
```suggestion
		. += "There are currently [SPAN_NOTICE("[current_hugger_count]")] facehuggers in the hive. The hive can support [SPAN_NOTICE("[linked_hive.playable_hugger_limit]")] facehuggers."
```

2024-06-19 23:44 UTC, Drulikar approved these changes

2024-06-19 23:48 UTC, merged