Improvements to box vending in Requisitions
cmss13-devs/cmss13 pull request #6397
Opened 2024-06-07 13:39 UTC by ThePiachu

# About the pull request

Fixes Issue #6096

Some small improvements around the code that handles Requisitions' ammo box vendor filling logic. It now handles boxes that use handfuls (shotgun boxes) and also checks the vendor's inventory for if the boxes already exist to let the devs order them neatly as needed.

Also neatly added the various boxes to Requisitions' vendors that were auto-populated before.

# Explain why it's good for the game

It makes the vendors nicer to use and keeps the ammo boxes consistent.

# Testing Photographs and Procedure

- Check Requisitions' vendors
- Vend shotgun ammo boxes big and small to see the ratios are maitained

<details>
<summary>Screenshots & Videos</summary>

![image](https://github.com/cmss13-devs/cmss13/assets/964559/695302b3-c62a-4d0b-98a1-0cb1b50d557a)

</details>

# Changelog

:cl ThePiachu:
qol: Shotgun ammo boxes now behave like other ammo boxes in the Requisitions' vendors.
code: Ammo box maping code now handles pre-populated boxes in vendors, letting devs order them more neatly than before.
/:cl:

2024-06-16 10:20 UTC, harryob requested changes

2024-06-16 10:20 UTC, harryob commented on code/game/machinery/vending/cm_vending.dm
> +	if(box_list.len > 0)
```suggestion
	if(length(box_list))
```

2024-06-16 10:20 UTC, harryob commented on code/game/machinery/vending/cm_vending.dm
> +					LP[2] = tmp_item[2] //Update box amount
```suggestion
			for(var/list/product as anything in listed_products)
				if(tmp_item[3] == product[3]) //We found a box we already have!
					product[2] = tmp_item[2] //Update box amount
```

2024-07-02 06:52 UTC, Drulikar commented
stale exempt until reviewed

2024-07-03 17:52 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-07-04 11:48 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-07-07 06:07 UTC, harryob requested changes

2024-07-07 06:07 UTC, harryob commented on code/game/machinery/vending/cm_vending.dm
> +	if(tmp_list.len > 0)
```suggestion
	if(length(tmp_list))
```

2024-07-07 06:08 UTC, harryob approved these changes

2024-07-07 06:44 UTC, merged