fence nerf + fuel cell recycler is now destroyable
cmss13-devs/cmss13 pull request #6471
Opened 2024-06-15 05:17 UTC by iloveloopers

# About the pull request
fuel cell recycler can now be destroyed, never seen this machine ever used and i don't think its important enough to be indestructible (probably)
fences are now a 2 tap hit to be destroyed by any xeno (or 1 tap + pounce)

# Explain why it's good for the game
less stupid crap blocking your movement
fences were super nerfed for xenos and just turned into more annoying movement blockers that don't provide cover

# Testing Photographs and Procedure

https://github.com/cmss13-devs/cmss13/assets/140007537/db66e5cf-095e-4a72-9a47-5bfe4c386c37

# Changelog

:cl:
balance: Fence health nerfed, now can be 2 tapped by xenos
qol: Fuel cell recyclers are now destroyable
/:cl:

2024-06-15 07:23 UTC, Tyranicranger4 commented
> qol: Fuel cell recyclers are now destroyable

*Marine support nerf under the QOL tag? It's more likely than you might think.*

Generators slowly break down after a certain amount of time has passed, *or* when a xeno destroys them. In either of these cases the fuel cells lose charge; in the case of xenos breaking them they usually lose all of it. There's only 1, maybe 2 fuel cell recyclers on each of the maps. If these are made destroyable and xenos destroy them - which they will - then you've effectively made colony power impossible to sustain for the rest of the game.

Just make them not block movement.

2024-06-15 08:27 UTC, Zonespace27 requested changes
Fuel cell chargers shouldn't be fully destructible

2024-06-15 17:06 UTC, iloveloopers commented
done

2024-06-15 20:02 UTC, wshuwshuwshi commented
I'm 100% game for fuel cell rechargers being destructable assuming that you can build new ones. If you can build new ones then the problem of them being removed from the round is nullified.

2024-06-20 08:33 UTC, Drulikar approved these changes

2024-06-20 08:47 UTC, merged