makes xenos take damage when patting fire on ground
cmss13-devs/cmss13 pull request #6484
Opened 2024-06-16 14:14 UTC by cuberound

# About the pull request

patting fire on ground now slightly harms the xeno

# Explain why it's good for the game

fire patting nerfed the area denial aspect of fire greatly, watching xenomorph just extinqish fuel covered ground with few pats and walk thrue it also looks stupid. this adds MINOR damage to patting fire, making use of flames and tacticly patting them more rewarding. being harmed to save fellow sister feels better then just clicking a tile bunch with no risk at all. 

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
balance: patting fire on ground harms the xeno, more intense fire means more harm
/:cl:

2024-06-16 17:19 UTC, kiVts commented on code/_onclick/xeno.dm
> +						if(!(src.fire_immunity & FIRE_IMMUNITY_NO_DAMAGE))
```suggestion
						if(!(caste.fire_immunity & FIRE_IMMUNITY_NO_DAMAGE) || fire.tied_reagent.fire_penetrating)
```
essentially you dont need src, fireimmunity flags are in caste datums, and check if the fire is firepen regardless

2024-06-16 17:20 UTC, kiVts commented on code/_onclick/xeno.dm
> +							src.apply_damage(fire.burnlevel, BURN,fire)
```suggestion
							apply_damage(fire.burnlevel, BURN,fire)
```

2024-06-16 17:42 UTC, HeresKozmos commented
Why is this necessary? Patting fire is the only reliable way outside of skills on cooldown to remove fire.

2024-06-16 18:33 UTC, cuberound commented
> Why is this necessary? Patting fire is the only reliable way outside of skills on cooldown to remove fire.

fire is supposed to serve area denial, and 4 taps to remove it is far from that role, the damage is negligable anyway unless you are trying to put out ob flames, but that is already writen in the pr...

2024-06-17 22:27 UTC, Git-Nivrak commented
Damage calculations to pat a single tile of fire:
Normal fire - Intensity 30 Burn Time 20: 120 damage
Green Fire - Intensity 15 Burn Time 50: 150 damage
Blue Fire - Intensity 40 Burn Time 40: 220 damage
High-Combustion Napalm - Intensity 45 Burn Time 10: 90 damage 
Sticky-Napalm: Intensity 15 Burn Time 50: 150 damage

Idk how you would consider this damage minor

2024-06-19 08:20 UTC, cuberound commented
> Damage calculations to pat a single tile of fire: Normal fire - Intensity 30 Burn Time 20: 120 damage Green Fire - Intensity 15 Burn Time 50: 150 damage Blue Fire - Intensity 40 Burn Time 40: 220 damage High-Combustion Napalm - Intensity 45 Burn Time 10: 90 damage Sticky-Napalm: Intensity 15 Burn Time 50: 150 damage
> 
> Idk how you would consider this damage negligible by any measure

you need to take into account the duration lost in the time it takes to pat goes more like 
90
60 (you did not take into accunt that you remove 10 stacks from green flame not 5)
200 - 240
45
100 / 60 (no idea what that fuel is and it it has the armor stuff that makes it 10 duration per pat)
only blue flame goes above getting shot by a burst from rifle damage. it is negligible as long as you are removing it for others and that is what this aims for, if you cooperate one can remove flaems and other attack, but if you go in solo it is rather silly that you can pat out whole burst out of flamethrower without taking any harm

2024-06-19 08:22 UTC, cuberound commented
and in emrgency you can still run thrue the fire and get patted on the other side, that does not harm them only you

2024-06-19 15:26 UTC, Red-byte3D commented
with how many fire sources and the ability to use greenflame (for everyone now instead of just pyro) ontop of having big ot rocket flames this is just another useless nerf that will gimp xenos even further.

2024-06-19 19:44 UTC, cuberound commented
> with how many fire sources and the ability to use greenflame (for everyone now instead of just pyro) ontop of having big ot rocket flames this is just another useless nerf that will gimp xenos even further. And dont forget the fact mortar incin spam exists.

as said above several times, green flame is the easiest one to remove I do not know why I have to tell it everyone individualy. mortar has limited ammo, and if you do not start imidietly but wait for a while and do not rush it drone can pat its way past seven tiles of green flame, if that feels too little the damage can be halved. but patting fire should not be free flames are supposed to be area denial, and three second slowdown of single enemy is far from that

2024-06-19 20:44 UTC, Drulikar requested changes

2024-06-19 20:44 UTC, Drulikar commented on code/_onclick/xeno.dm
> +							apply_damage(fire.burnlevel, BURN,fire)
Make it a prob or like greatly reduce the damage dealt.

2024-06-19 20:48 UTC, Drulikar commented on code/_onclick/xeno.dm
> +							apply_damage(fire.burnlevel, BURN,fire)
Fire itself is just `burnlevel*FIRE_DAMAGE_PER_LEVEL` where FIRE_DAMAGE_PER_LEVEL is 3.

Technically it ought to use `check_fire_intensity_resistance()` too but its not really used.

2024-06-19 22:37 UTC, Drulikar requested changes

2024-06-19 22:37 UTC, Drulikar commented on code/_onclick/xeno.dm
> +							apply_damage(max(fire.burnlevel/2-check_fire_intensity_resistance() , 0), BURN,fire)
```suggestion
						if(!(caste.fire_immunity & FIRE_IMMUNITY_NO_DAMAGE) || fire.tied_reagent?.fire_penetrating)
							var/firedamage = max(fire.burnlevel - check_fire_intensity_resistance(), 0) * 0.5
							apply_damage(firedamage, BURN, fire)
```

2024-06-20 08:19 UTC, Drulikar approved these changes

2024-06-20 08:23 UTC, merged