Adds complete vent system to Fiorina
cmss13-devs/cmss13 pull request #6500
Opened 2024-06-17 19:24 UTC by HeresKozmos

# About the pull request

Adds a complete vent system to Fiorina.

# Explain why it's good for the game

Unlike most other maps, Fiorina doesn't have a vent system at all; which this fixes and brings it in line with the other maps.

To stop you from going from one edge of the map to the other, each major area has its own closed loop vent system; for example you can only enter a vent inside of Engineering and exit from somewhere else inside Engineering. I've added grates where possible to help with identifying and locating pipes so you don't have to rip up the entire floor.

The main point of this PR is to bring it up to the same level that large maps like Chance's Claim or New Varadero have when it comes to vent availability.

# Testing Photographs and Procedure

This is an image of Fiorina with no turf, you can zoom in and follow the pipes to look at where they go to and from:
![Fiorina Vent System - Turfless](https://github.com/cmss13-devs/cmss13/assets/31109792/fce6dd32-cd2c-434c-82b1-b75077e2672f)

# Changelog

:cl:
maptweak: Adds closed loop vent systems to each major area in Fiorina.
maptweak: Changes some floors to include grates to make pipes visible/easier to locate.
maptweak: Moved a few minor map props to make space for vents a short distance from their original spots.
/:cl:

2024-06-27 03:24 UTC, Drulikar commented
Stale exempt until mapping reviewed.

2024-07-10 15:37 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-07-18 00:28 UTC, Nanu308 requested changes

2024-07-18 00:28 UTC, Nanu308 commented on maps/map_files/FOP_v3_Sciannex/Fiorina_SciAnnex.dmm
![image](https://github.com/user-attachments/assets/bb7d70e0-d635-4650-9899-fd99809c5f17)
![image](https://github.com/user-attachments/assets/add00e4e-429a-4bc5-80da-1d2f2f1541ab)
![image](https://github.com/user-attachments/assets/0b71cb35-1d96-43b8-b503-c2829d5d8511)
![image](https://github.com/user-attachments/assets/84a1dae3-e1f6-4503-b28d-30295e52748c)
![image](https://github.com/user-attachments/assets/3bbee0bc-adae-4721-aed5-68eb7b97486e)
![image](https://github.com/user-attachments/assets/a3ed5ad4-1239-4c71-8a4a-e0e26d34a178)

Only one entrance per vent. You're using two threeway's for no raisin!!!

![image](https://github.com/user-attachments/assets/37f61359-23ac-490e-ba60-7b1b36c04831)
Missing pipe

![image](https://github.com/user-attachments/assets/beeed939-d6a2-4592-8557-c2db6b5db027)
Don't run pipes under walls

![image](https://github.com/user-attachments/assets/5b7560de-84c0-4401-a480-ed53895cc89e)
You also has a lot of redundancy in your pipe system, tldr. it looping into itself and having several way to reach the same spot. It's fine to a certain degree, but I'd say cut a few of these pathways and in some other areas.

One scrubber and one vent pump per room is the standard, look at the Almayer as an example. Of course, is the room massive you can add in another set of two and so forth.

2024-07-19 01:55 UTC, closed without merging