Nuclear Authentication Disks reduce Nuclear Weapon decryption time.
cmss13-devs/cmss13 pull request #6511
Opened 2024-06-19 21:39 UTC by blackdragonTOW

# About the pull request

Adds a simple 30% reduction in what ever decryption time is left when we use a Nuclear Authentication Disk on a nuke.

Note: Has no effect on the admin spawned nuke which does not have a decryption timer.

# Explain why it's good for the game

Presently our maps have Nuclear Authentication Disks, and when found it's treated with some semblance of gravity, but in actuality they do nothing.  This rewards finding such an important object and in the occasion that the disk is found and the End Game for the round is also a decryption nuke.

# Testing Photographs and Procedure
Tested with all listed fail states contained within /obj/structure/machinery/nuclearbomb/tech/attackby()

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
add: Nuclear Authentication Disks now reduce remaining decryption time by 30%.
/:cl:

2024-06-19 21:44 UTC, vero5123 commented
lord, you need to do early returns man.

2024-06-19 22:04 UTC, blackdragonTOW commented
> lord, you need to do early returns man.

Yeahhhh, still learning, tried it another way that should be easier to read.

2024-06-19 22:36 UTC, Drulikar requested changes
As mentioned on the discord; maybe tie this instead into self destruction. E.g. 50% faster or just instant SD or something. Already xenos struggle to get to a nuke fast enough. If marines are able to manage to get objectives to get a SD online, then this would encourage people to actually go for that; whereas now SD is really rare.

2024-06-20 13:43 UTC, Steelpoint commented
Maybe the disk allows you to set a custom detonation timer? Instead of a flat 60 seconds, you can set it to detonate either instantly or up to several minutes slower than normal?

2024-06-21 01:32 UTC, blackdragonTOW commented
> Maybe the disk allows you to set a custom detonation timer? Instead of a flat 60 seconds, you can set it to detonate either instantly or up to several minutes slower than normal?

Likely would get shotdown faster than just the decrypt timer.  Marines wont set it longer than 60s and making it shorter than 60s would be "unfair" according to our resident xeno experts. 

Regardless changing this to making the reactors behave differently during SD is way off Theme for what this sets out to do so I'll just kill it here.

2024-06-21 01:32 UTC, closed without merging