HoT Healer
cmss13-devs/cmss13 pull request #654
Opened 2022-07-10 18:59 UTC by Geevies

## About The Pull Request

Healer drones now apply healing instantly, but the range has been dropped to touching range again. The healing effect takes 10 seconds, providing the target with 20 health every 2 seconds. This effect can be stacked.

Additionally, heal overlays now properly align with the xeno sprite.

## Why It's Good For The Game

The current way healer drones have to channel before delivering the healing makes it an extremely static role, this should make it more dynamic and fun as you can do drive-by heals. The amount of heals you can deliver is limited by the massive amount of damage you take providing them.

## Changelog

:cl:
balance: Healer drones now apply healing instantly, but the range has been dropped to touching range again. The healing effect takes 10 seconds, providing the target with 20 health every 2 seconds. This effect can be stacked.
fix: Health overlays now properly align with xeno sprites.
/:cl:

2022-07-13 02:31 UTC, Nanu308 commented
Numbers may require tweaking down the line, as old Queen heal issues can occur.

2022-07-13 18:27 UTC, stanalbatross requested changes
put the range check over all other to_chat giving checks for the heal

2022-07-13 18:29 UTC, stanalbatross requested changes
the stacking does seem a little busted from local testing

this will be merged AFTER crit grace, so you can prevent drones from getting crit grace if they go into crit via self damage

2022-07-13 18:44 UTC, Geevies commented
fixed range check, discussed the other changes, decided it's PROBABLY fine? we can testmerge to confirm

2022-07-16 11:05 UTC, BKryth commented
You can spam heal to the point it kills yourself

2022-07-22 09:45 UTC, stanalbatross approved these changes

2022-07-22 09:45 UTC, merged

2022-07-23 18:18 UTC, ZxggyTheFilmMaker commented
Please bring back old healer drone. the new one is literally effective. how. for starts, i can only heal 4 times max and go critical. secondly, i have to be close up, and lastly, how am i suppose to constantly heal if im at risk of being at low health at most times and have to focus on recovering myself. new healer drone isnt effective anymore.

2022-07-24 03:02 UTC, ZxggyTheFilmMaker commented
And im not the only one who feels this way.
![Capture1](https://user-images.githubusercontent.com/109871901/180630340-a7b72a7e-35c2-4cc2-adcd-e7e869c7592b.PNG)
![Capture2](https://user-images.githubusercontent.com/109871901/180630344-284972e1-fc16-4dd6-bc17-1387ee52d5c0.PNG)

2022-07-24 03:02 UTC, ZxggyTheFilmMaker commented
im sorry but healer drone sucks now and now no one plays it anymore. nice job dev. you ruined healer drone. :|