adds colony self destruct mechanisms to big red, desert dam and lv
cmss13-devs/cmss13 pull request #6540
Opened 2024-06-23 16:14 UTC by AndroBetel

# About the pull request

adds self-destruct mechanisms to big red ETA, desert dam lab and LV lab (LV one is a rare nightmare insert)
they are activated using nuclear disks, which are made unacidable

![image](https://github.com/cmss13-devs/cmss13/assets/44546836/89787c1b-3705-4377-9a46-1b3513386e8e)

# Explain why it's good for the game

this pr was inspired by battlefield levolution system, as it allows players to single-handedly change entire locations (not without some set-up, of course)
i find map interactivity in CM lacking, so this pr also adds said interactivity to some maps

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
add: Adds colony self-destruct mechanisms to Big Red, LV-624 and Desert Dam, activated via nuclear disks.
/:cl:

2024-06-23 18:10 UTC, kiVts commented on code/game/machinery/colony_selfdestruct.dm
> +		icon_state = "selfdestructboom"
```suggestion

	if(timeleft <= 0)
		icon_state = "selfdestructboom"
		return
		
	if(timeleft < stage_3)
		icon_state = "selfdestruct4"
		return
		
	if(timeleft < stage_2)
		icon_state = "selfdestruct3"
		return
		
	if(timeleft < stage_1)
		icon_state = "selfdestruct2"
		return
		
	if(timeleft < initial(timeleft))
		icon_state = "selfdestruct1"
```

this looks generally less confusing, dont you think? 

also could be else if spam

2024-06-23 22:12 UTC, Zonespace27 requested changes

2024-06-23 22:12 UTC, Zonespace27 commented on code/game/machinery/colony_selfdestruct.dm
> +	var/explosionpower = 1200
cod edoc

2024-06-23 22:12 UTC, Zonespace27 commented on code/game/machinery/colony_selfdestruct.dm
> +	if(user.is_mob_incapacitated() || get_dist(src, user) > 1 || isRemoteControlling(user))
i think we have an in_range proc

2024-06-23 22:12 UTC, Zonespace27 commented on code/game/machinery/colony_selfdestruct.dm
> +		if(do_after(user, 150 * user.get_skill_duration_multiplier(SKILL_ENGINEER), INTERRUPT_NO_NEEDHAND, BUSY_ICON_HOSTILE))
SECONDS macro

2024-06-23 22:12 UTC, Zonespace27 commented on code/game/machinery/colony_selfdestruct.dm
> +	explosiontime = world.time + timeleft
use a timer

2024-06-23 22:12 UTC, Zonespace27 commented on code/game/machinery/colony_selfdestruct.dm
> +	var/obj/item/disk/nuclear/dat_disk
null on destroy

2024-06-23 22:12 UTC, Zonespace27 commented on code/game/machinery/colony_selfdestruct.dm
> +		if(do_after(user, 150 * user.get_skill_duration_multiplier(SKILL_ENGINEER), INTERRUPT_NO_NEEDHAND, BUSY_ICON_HOSTILE))
seconds macro

2024-06-23 22:12 UTC, Zonespace27 commented on code/game/machinery/colony_selfdestruct.dm
> +		if(do_after(user, 150 * user.get_skill_duration_multiplier(SKILL_ENGINEER), INTERRUPT_NO_NEEDHAND, BUSY_ICON_HOSTILE))
early return

2024-07-10 15:37 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-07-18 00:32 UTC, Nanu308 commented
Fix up your PR and resolve prior reviews, and I'll map review it.

2024-07-28 13:46 UTC, Nanu308 reviewed
mapping lgtm

2024-07-28 13:46 UTC, Nanu308 commented on maps/map_files/LV624/science/10.selfdestruct.dmm
mapping lgtm

2024-07-28 13:46 UTC, Nanu308 commented on maps/map_files/DesertDam/Desert_Dam.dmm
mapping lgtm

2024-07-28 13:46 UTC, Nanu308 commented on maps/map_files/BigRed/BigRed.dmm
mapping lgtm

2024-08-23 15:12 UTC, closed without merging