Hivelord meson vision
cmss13-devs/cmss13 pull request #6570
Opened 2024-06-26 07:00 UTC by Git-Nivrak

# About the pull request
Gives hivelords meson vision

# Explain why it's good for the game
Makes it easier to see how what you are designing is coming together, which should be a thing for a caste that is entirely focused on building.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
balance: Hivelords now have meson vision
/:cl:

2024-06-26 10:11 UTC, JackieEstegado commented
Make this toggle-able, hard to see lines of vision with meson, which is pretty important for the hivelord, and may as well do this for burrower too.

2024-06-26 23:53 UTC, HeresKozmos commented
cool and based

2024-06-27 06:38 UTC, Diegoflores31 commented
based

2024-07-05 01:50 UTC, Zonespace27 commented
How does this affect resin whisperer?

2024-07-05 07:54 UTC, JackieEstegado commented
Tested it, resin whisperer strain can build with meson on tiles it doesn't have LOS on, but can't with meson off.

2024-07-05 08:57 UTC, Git-Nivrak commented
💀

2024-07-05 09:35 UTC, Git-Nivrak commented
Fixed

2024-07-08 12:43 UTC, Zonespace27 requested changes

2024-07-08 12:43 UTC, Zonespace27 commented on code/modules/mob/living/carbon/xenomorph/strains/castes/hivelord/resin_whisperer.dm
> +	if(!(target_turf in view(10, owner)))
Ideally do a range check or a raycast or something instead of a view(10)

2024-07-10 12:17 UTC, Zonespace27 approved these changes
I don't like the view check but there's not a better way that I know of

2024-07-10 15:16 UTC, merged