m56d ammo for m56 cupola
cmss13-devs/cmss13 pull request #6578
Opened 2024-06-27 08:43 UTC by cuberound

# About the pull request

changes ammo of m56 cupola of a tank to m56d ammo rather then normal smartgun ammo. it was leftover propably from some super old smartgun behavior. current ammo was 30 dmg 0 ap with 2 shots per second, for reference m4ra with iff scope has slightly better firerate with 36 dmg 40 ap with ap ammo and 48 dmg with 5 ap with normal ammo and you can hold it in hand not have it mounted on a tank.  now it has 35 dmg with 50 ap, 

# Explain why it's good for the game

with other stats still worse then if you were to move m56d around but it is not COMPLETE trap anymore, you are still better off leaving the tank and carring m56d around but at least it can harm the enemy

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
balance: m56 cupola uses m56d ammo rather then standard sg ammo
/:cl:

2024-07-14 15:25 UTC, Drulikar commented
Stale exempt until reviewed

2024-07-19 03:11 UTC, Drulikar approved these changes

2024-07-19 03:21 UTC, Drulikar requested changes

2024-07-19 03:21 UTC, Drulikar commented on code/modules/vehicles/hardpoints/hardpoint_ammo/cupola_ammo.dm
> +	default_ammo = /datum/ammo/bullet/machinegun
This ammo throws runtimes 3 times every fire because of the iff trait it has.

2024-07-19 08:05 UTC, cuberound commented
damn okey fixed it, it is still weaker then normal m56d but it is stronger then throwing rocks hopefuly

2024-07-19 20:29 UTC, Drulikar approved these changes

2024-07-19 21:09 UTC, merged