Changes the tank's primary flamer back to a 5-tile radius blue flame glob
cmss13-devs/cmss13 pull request #6579
Opened 2024-06-27 22:13 UTC by VileBeggar

# About the pull request

the tank's primary flamer weapon (the "DRG-N Offensive Flamer Unit") now fires a fuel glob that spreads to a 5-tile wide circle, just like it used to before. i've changed it to burn out much quicker than regular blue flames, along with it spawning a harmless smoke cloud for cosmetic effect. my reasoning behind this is that the tank does not have a way of extinguishing the flames on its own, and with how quickly it can fire off flame rounds it could potentially stall pushes for a really, really long time. that kind of ruins the "offensive" part of the weapon imo. 

i am also unsure of why this glob radius got removed. i couldn't find anything relating to it's removal, nor if it was intended or not. it might be worthwhile to lower the radius by one tile (imo this a bit too much range) but for now i'm just reverting it to how it was before.

i at least think this is how it acted before (barring the short duration, that's just something i changed). i'm just working off what i have since i don't have any memories of the tank from back then.

<details>
<summary>old picture for reference</summary>

![image](https://github.com/cmss13-devs/cmss13/assets/17518895/8b21eb74-d7fd-4ef1-a701-0580786e51bc)

</details>

# Explain why it's good for the game

currently the primary flamer just fires 1 tile of blue flame which is very underwhelming for what is supposed to be a primary weapon for the tank. it might need a few tweaks but with these changes it will be a very potent weapon, fit for being a proper primary.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

https://github.com/cmss13-devs/cmss13/assets/17518895/b9150aa4-0722-431e-9377-61bd1ab36674

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
balance: The DRG-N Offensive Flamer Unit now fires a 5-tile wide glob of short-duration blue flame, similar to how it acted previously.
/:cl:

2024-06-27 22:26 UTC, Drulikar requested changes
Make it 3 wide like you had earlier.

As far as blame, this is where drop_flame logic for it was removed:
https://github.com/cmss13-devs/cmss13/pull/775/files#diff-8c3c674141299020e3caecb9ec366533746827ff837813e652aa775db1f096c7L2921-R2926

2024-07-05 02:02 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-07-05 09:20 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-07-19 01:00 UTC, Drulikar approved these changes

2024-07-19 01:08 UTC, merged