Port WHO to TGUI
cmss13-devs/cmss13 pull request #6583
Opened 2024-06-28 13:51 UTC by blackcrystall

# About the pull request

Just QoL

# Explain why it's good for the game

Argghhh. just TGUI new panel? No benefits on round, but for visual and maybe a little bit server, because it don't generate every time for you who list

# Changelog

:cl: Blackcrystalic
qol: port who/staffwho to TGUI
/:cl:

2024-07-03 17:52 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-07-04 14:21 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-07-10 18:48 UTC, harryob requested changes
just this, rest seems alright

2024-07-10 18:48 UTC, harryob commented on code/controllers/subsystem/who.dm
> +	for(var/i in 10 to length(counted_factions) - 2)
why magic number here?

2024-07-16 13:54 UTC, Zonespace27 submitted a review, later dismissed
[0001-tgui-who-update.patch](https://github.com/user-attachments/files/16249978/0001-tgui-who-update.patch)

Apply this patch and it should be good to go

2024-07-20 19:52 UTC, harryob approved these changes

2024-07-21 03:34 UTC, merged