Hardcode Rework
cmss13-devs/cmss13 pull request #6586
Opened 2024-06-28 14:18 UTC by blackcrystall

# About the pull request

Added ECHO support to sounds (byond function implementation to be accessible), some changes from one letter vars.

Rework of admin shoot the ship pannel, so now it's not hardoced

# Explain why it's good for the game

Just backend rework, almost same

:cl: BlackCrystalic
add: Byond backed function of sound ECHO ported
refactor: refactor of weaponhits hardcode
/:cl:

2024-07-02 07:17 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-07-04 14:22 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-07-06 07:38 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-07-06 10:31 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-07-16 10:00 UTC, harryob requested changes
otherwise looks fine

2024-07-16 10:00 UTC, harryob commented on code/modules/almayer/weaponhits.dm
> +	var/list/echo_list = new(18)
```suggestion
	var/list/echo_list = new /list(18)
```

2024-08-01 05:23 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-08-03 19:08 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-08-05 15:21 UTC, harryob approved these changes

2024-08-05 15:29 UTC, merged