White corpsman helmet
cmss13-devs/cmss13 pull request #6593
Opened 2024-06-29 01:26 UTC by Blundir

# About the pull request

Adds white corpsman helmet, which is mostly insprited by Aliens Dark Descent analogue and historical counterparts

<details>

![image](https://github.com/cmss13-devs/cmss13/assets/100090741/90cd03cc-e003-48b2-bef7-20abdb3cbd13)

![image](https://github.com/cmss13-devs/cmss13/assets/100090741/b78031ea-f27f-41d9-9dac-0b4769bd0e36)

</details>

Has identical stats, just a reskin.

# Explain why it's good for the game

More lore friendly customization - good.

Sprites by Crowford, discord @sir.crow.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

![dreamseeker_QYcvBP3544](https://github.com/cmss13-devs/cmss13/assets/100090741/4b557358-51c3-4c79-99da-09f9c3090f06)

![4NW2tY3jF7](https://github.com/cmss13-devs/cmss13/assets/100090741/c31a43e5-c358-49ee-957d-641e72fcc5b6)

</details>

# Changelog

:cl:
add: white corpsman helmet
/:cl:

2024-06-29 03:02 UTC, hislittlecuzingames commented
guess I'll get capped more than normal. 

👍

2024-06-29 04:02 UTC, Git-Nivrak commented
Speedmerge

2024-06-29 06:24 UTC, s5nt commented
good pr but its pretty much a "TARGET ME!" beacon

2024-06-29 08:10 UTC, Steelpoint commented
Corpsman will simply have a choice between making themselves very visible or fairly hidden to a xenomorph, this isn't a nerf since the choice remains optional and non-corpsman helmets are freely issued at squad reqs.

2024-06-29 13:26 UTC, Zonespace27 requested changes

2024-06-29 13:26 UTC, Zonespace27 commented on code/game/machinery/vending/vendor_types/squad_prep/squad_medic.dm
> +		list("M10 white corpsman helmet", 0, /obj/item/clothing/head/helmet/marine/medic/white, MARINE_CAN_BUY_HELMET, VENDOR_ITEM_REGULAR),
Capitalize

2024-06-29 14:20 UTC, Zonespace27 approved these changes
Code seems fine

2024-07-01 03:06 UTC, Nomoresolvalou commented
I think you should also add this to the synth snowflake vendor, since they also have the normal corpsman helmet there as well.

2024-07-02 14:37 UTC, Blundir commented
> I think you should also add this to the synth snowflake vendor, since they also have the normal corpsman helmet there as well.

Done

2024-07-06 07:37 UTC, harryob approved these changes

2024-07-06 07:50 UTC, merged