Vampire Lurker Changes (TailStab/Armour/Speed)
cmss13-devs/cmss13 pull request #6597
Opened 2024-06-30 08:22 UTC by Steelpoint

# About the pull request

Vampire re-gains its Tail Stab stun on hit

Vampire has had its armour reduced from 20 to 10

Vampire no longer gains any speed-boost over the default Lurker. 

# Explain why it's good for the game

The recent changes to the Vampire strain of the Lurker have, I feel, missed the true reasons as to why the strain is seen as more oppressive than you would expect from a T2 strain. Under the control of the best players, the strain's dominance is due to its ability to move at incredible speeds off-weeds and shrug off significant damage thanks to its high armour whilst having the ability to easily disengage from combat.

The removal of its tail-stab stun failed to touch the real issues plaguing the strain and simply made the strain significantly harder for a new player to get engaged with, as the micro-stun played a important role in the Vampire's combo of landing hits. Whilst the stun removal had absolutely zero impact on a higher skilled players ability to dominate with the role as the reasons why they are allowed to dominate were left untouched.

By making my proposed changes, a Vampire Lurker is now much easier for a Marine to track and shoot, instead of moving basically as fast as a Runner, plus its lack of armour AND the fact it has less health than a stock Lurker makes it take damage much faster, especially from weapons with armour penetration. Its tiny amount of armour offers a small amount of defence but not enough to make it very tanky.

Its health is as such where two point-blank buckshots will crit it, and a single PB will leave it on the verge of crit. Not too dissimilar to the base Lurker. 

I believe this change will reign in some of the more excessive gameplay elements from the most skilled players whilst not overly harming the roles ability to function AND making it easier for new players to get into the role. 

(I should note that removing or reducing the range of its leap ability would further eliminate these issues but I will await feedback before making any change here, as this may have harsher implications for the role)

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
balance: The Vampire Lurker has re-gained its tail-stab stun.
balance: To compensate, the Vampire Lurker no longer gains any speed-boost bonus over the default Lurker, and its armour has been reduced from 20 to 10. 
/:cl:

2024-06-30 09:05 UTC, VileBeggar commented
you should update the strain description in vampire.dm to match the changes

2024-06-30 09:10 UTC, Steelpoint commented
Done

2024-07-11 23:28 UTC, Steelpoint commented
Stale Comment

2024-08-01 09:49 UTC, Drulikar requested changes

2024-08-01 09:49 UTC, Drulikar commented on code/modules/mob/living/carbon/xenomorph/strains/castes/lurker/vampire.dm
> +	description = "You lose all of your abilities and you forefeit a chunk of your health and damage in exchange for a small amount of armor, increased attack speed, and brand new abilities that make yo
what about the tail jab is aoe?

2024-08-01 09:49 UTC, Drulikar commented on code/modules/mob/living/carbon/xenomorph/strains/castes/lurker/vampire.dm
> +	lurker.armor_modifier += XENO_ARMOR_MOD_SMALL
I'm skeptical this needs to change, especially with proposed changes.

2024-08-01 09:49 UTC, Drulikar commented on code/modules/mob/living/carbon/xenomorph/abilities/lurker/lurker_powers.dm
Keep existing behavior for a non-sprite click, otherwise apply WEAKEN for sprite click

2024-08-01 09:49 UTC, Drulikar commented on code/modules/mob/living/carbon/xenomorph/abilities/lurker/lurker_powers.dm
> -	if(!step(hit_target, direction))
We should only enter this block if `hit_target.mob_size < MOB_SIZE_BIG` and if not just slow them. (meaning the else slow should be tabbed out 1 level)

2024-08-11 14:43 UTC, closed without merging