[Solaris Ridge] Aesthetic Update V2
cmss13-devs/cmss13 pull request #6602
Opened 2024-07-01 17:35 UTC by Steelpoint

# About the pull request

Continuation of this PR: https://github.com/cmss13-devs/cmss13/pull/6152

--
Effects a significant aesthetic makeover over parts of Solaris Ridge.

This PR focuses more on the Northern half of the colony. I intend to followup in the future with doing more work on the southern half and the caves. 
--

# Explain why it's good for the game

I feel a long term goal of mapping should be to enhance our older maps to make them look far more "alive", lived in and aesthetically pleasing. But keeping the spirit of the similar layout of the original map.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
maptweak: A significant amount of aesthetic upgrades to Solaris Ridge have been added.
/:cl:

2024-07-10 15:37 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-07-11 02:39 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-07-18 00:46 UTC, Nanu308 requested changes
See comments, yet to finish review on main map changes

2024-07-18 00:46 UTC, Nanu308 commented on maps/map_files/BigRed/standalone/medbay-v3.dmm
lgtm

2024-07-18 00:46 UTC, Nanu308 commented on maps/map_files/BigRed/standalone/crashlanding-offices.dmm
lgtm

2024-07-18 00:46 UTC, Nanu308 commented on maps/map_files/BigRed/standalone/crashlanding-eva.dmm
lgtm

2024-07-18 00:46 UTC, Nanu308 commented on maps/map_files/BigRed/sprinkles/40.viro_open.dmm
lgtm

2024-07-18 00:46 UTC, Nanu308 commented on maps/map_files/BigRed/sprinkles/70.se-checkpoint.dmm
lgtm

2024-07-18 00:46 UTC, Nanu308 commented on maps/map_files/BigRed/sprinkles/40.admin_pmc.dmm
![image](https://github.com/user-attachments/assets/80cc128d-8bde-431b-8c9b-9cdc41af1cfe)
Remove this one corpse and it will be pretty much perf.

2024-07-18 00:46 UTC, Nanu308 commented on maps/map_files/BigRed/sprinkles/35.filtration_restored.dmm
lgtm

2024-07-18 00:46 UTC, Nanu308 commented on maps/map_files/BigRed/sprinkles/25.lz1containers_scramble.dmm
![image](https://github.com/user-attachments/assets/53f921f7-8ef9-43a7-8e9f-f0d8e4e645d5)
Not a fan of the new tiles selected to showcase outline of the containers. Warning stripes would be better

2024-07-18 00:46 UTC, Nanu308 commented on maps/map_files/BigRed/sprinkles/20.lz1entrance_v2.dmm
![image](https://github.com/user-attachments/assets/5e69bf91-318e-4fe1-b78e-87db5e475b7f)
Change the tiles next to concrete, make it soil or some other weedable form. This really clashes look wise right here, minor thing tho.

2024-07-18 00:46 UTC, Nanu308 commented on maps/map_files/BigRed/sprinkles/10.prison_breakout.dmm
Nicely done, good improvement overall here.

2024-07-18 16:52 UTC, Steelpoint commented
First round of requested changes have been made.

2024-07-28 13:29 UTC, Nanu308 requested changes
See Comments

2024-07-28 13:29 UTC, Nanu308 commented on maps/map_files/BigRed/BigRed.dmm
![bilde](https://github.com/user-attachments/assets/fb8ebb88-7cdb-485c-9948-192dd21a5b1b)
![bilde](https://github.com/user-attachments/assets/85295e4e-b3e1-49d0-affe-0dd3ef34e123)
![bilde](https://github.com/user-attachments/assets/7af1279d-b775-44e1-83e3-cb2663e6136c)
![bilde](https://github.com/user-attachments/assets/f7a8ab4e-1050-419a-babc-b86f188a2580)

Extend concrete here. Might as well fix this to look better while at it.

![bilde](https://github.com/user-attachments/assets/769ccb9c-a29b-4029-ae92-3872caf2e044)
![bilde](https://github.com/user-attachments/assets/04e37cbc-2814-4bc2-872b-ca307cf37e37)
For under the lockdown pods/shutter things you use warning stripes and stick to concrete, do this across the map. For under doors you can keep it as is.

![bilde](https://github.com/user-attachments/assets/ee5368d4-85b8-4172-895f-adc4a22874ad)
![bilde](https://github.com/user-attachments/assets/4afb14b8-cdf0-49fc-ae2a-50d0df661696)
![bilde](https://github.com/user-attachments/assets/4d9987f9-8bf0-4242-b8c6-d04520160128)
Extend the warning stripes like i showcase here for ur map changes.

![bilde](https://github.com/user-attachments/assets/7e67b384-6b3e-4209-bc17-1978e0a0bc3b)
Warning stripes for the containers instead of the colored tileset.

2024-07-29 08:48 UTC, Steelpoint commented
Requested changes made.

2024-08-11 14:43 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-09-01 17:25 UTC, Nanu308 approved these changes
mapping lgtm, might need some further concrete spots to make it visually more in line but good for now

2024-09-01 17:30 UTC, merged

2024-09-01 17:59 UTC, Steelpoint commented
I'll almost certainly do more touch-ups in the future in-between my UPP map PR.