Charger Crusher Return
cmss13-devs/cmss13 pull request #661
Opened 2022-07-11 20:07 UTC by PhantomEpicness

Due to github fuckery, I was forced to make a new PR

old PR: https://github.com/cmss13-devs/cmss13/pull/14
## About The Pull Request

Old momentum crusher has returned in form of the "Charger" crusher. The basis is simple, hold move key and destroy shit.

Passive: Directional armor. Charger has 50 frontal armor, 35 side armor, and 25 rear armor. Because of this ability, charger crusher is unable to direction lock itself.

Active: Charge
Enables charging in which you will become a living train and ram shit at the cost of being plasma heavy. Upon reaching maximum momentum, you will roar and deal full damage.

Active: Tumble
 Clicking to the side of where the crusher is facing will launch it 2 tiles to the side in the clicked direction. Hitting a human will knock them over. This ability can be used while charge to quickly offset yourself. However, it will reset your momentum to 0.

Active: Ram

An ability that allows you to fling a person in front of you for a short distance. Has a 2 second stun and a longer 10 second cooldown. Subject to change and/or removal.

Active: Charger stomp. Unlike the base crusher, it does not stun, but does heavy damage to any human unfortunate enough to be under the charger, it also applies a mild screen shake to any humans in view and can be used to help escape.

Credit to original charger devs, lumdor and donk!

## Why It's Good For The Game

design doc: https://github.com/cmss13-devs/cmss13-design-docs/pull/9

_tl:dr_ 
Charger breathes new life into normal crusher by bringing back its most requested features pre-moba features in form of a strain. The caste design is much more simple compared to other xeno castes. One simple, yet tried and true fun combo exists, charging.
## Changelog

:cl: TotalEpicness, TheDonkified and Lumdor
add: Added charger strain for crusher.
experiment: Charger functions very similarly to old crusher. Hold movement key and after a while you gain momentum to ram humans and certain objects. Behavior upon collision with different things are subject to change.
Passive: Directional armor. Charger has 50 frontal armor, 35 side armor, and 25 rear armor. Because of this ability, charger crusher is unable to direction lock itself.
experiment: Active 1: Toggle Charging. Use this ability to toggle charging on and off.
experiment: Active 2: Tumble. Clicking to the side of where the crusher is facing will launch it 2 tiles to the side in the clicked direction. Hitting a human will knock them over. This ability can be used while charge to quickly offset yourself. However, it will reset your momentum to 0.
add: Tumble now has cool sound effects and a spin.
sprite: Added tumble ability sprites
tweak: Charger now takes 3 full hits to destroy a normal wall instead of destroying it in pretty much one. Xeno walls take half damage
experiment: Active 3: Charger stomp. Unlike the base crusher, it does not stun, but does heavy damage to any human unfortunate enough to be under the charger, it also applies a mild screen shake to any humans in view and can be used to help escape.
add: Xenos blocking a charger's path when charger get pushed to the side, if no clear path to move to exists, they get flicker stunned so that charger may charge.
/:cl:

2022-07-11 20:09 UTC, PhantomEpicness commented
Charger changelog
- return of base Crusher
- bonus charging armor removal
- Ram is now a 2 tile ranged warrior fling with a 2 second stun. No more mini base charge.
- fixed macro bugs, if you think macros should be rebinded, let me know
- slight health nerf and frontal armor bonus is now 25 
I am also currently working on a small shield bonus that your recieve when hitting max momentum that lasts a few seconds. This is a solution that will give charger a bit more survivability and slightly lower the risk of charging without making it excessively tanky like it was previously.
this won't make it to this TM however, as I need to see if it's even needed.

2022-07-12 15:19 UTC, novaepee commented
I can ensure you that all marines shall hate Ram. Over at TGMC, crusher has a similar ability, and good crusher players fish new marine players out of barricades.

2022-07-13 17:52 UTC, Chainsawicus commented
> A small shield bonus that you recieve when hitting max momentum that lasts a few seconds. This solution will give charger a bit more survivability and slightly lower the risk of charging without making it excessively tanky like it was previously. this won't make it to this TM however, as I need to see if it's even required.

No more shields... please...

In seriousness, since shields as a whole are being toned down or flat out removed in certain cases soon, I think you should look to alternative methods of survivability, as there's no guarantee that charger would be able to keep its shields.

2022-07-13 18:59 UTC, PhantomEpicness commented
> > A small shield bonus that you recieve when hitting max momentum that lasts a few seconds. This solution will give charger a bit more survivability and slightly lower the risk of charging without making it excessively tanky like it was previously. this won't make it to this TM however, as I need to see if it's even required.
> 
> No more shields... please...
> 
> In seriousness, since shields as a whole are being toned down or flat out removed in certain cases soon, I think you should look to alternative methods of survivability, as there's no guarantee that charger would be able to keep its shields.

Yeah now that it was brought up to me that shields were being done away with, I have considered other options.

2022-07-15 14:17 UTC, stanalbatross commented
![image](https://user-images.githubusercontent.com/66756236/179242021-2a90f18e-5608-4072-9a48-4ee50dab7feb.png)
fix

2022-07-25 21:30 UTC, stanalbatross commented on code/modules/mob/living/carbon/human/human_damage.dm
> +
remove commented out code all over the pr once you're done with the final implementation

2022-07-27 00:06 UTC, PhantomEpicness commented
Changes:

- frenzy NO LONGER affects charger at all. 
- fixed macros, they should be assigned to correct keys in order now
- 5 less back armor. Note that frontal and side armor has been changed to compensate for 5 less base armor, effectively only lowering back armor.
- hp increase 760 > 780
- fling stun removed
- fling distance 2 > 3
- changed description to a more accurate one:

> Your charge is now momentum based, the further you go, the more damage and speed you will get until you achieve max momentum when you roar. Your armor is now directional, being the toughest on the front, weaker on the sides and weakest at the back. Your shield is also removed. In return you gain more health, gain an ability to tumble to avoid enemies, and gain an ability to forcefully move enemies via ramming. Finally, you trade being able to resist slowdowns from tall autospitters for being unaffected by frenzy pheros.

2022-08-01 15:21 UTC, stanalbatross commented
fine in its current implementation just needs code review

2022-08-01 16:52 UTC, Carnage068 commented
let's gooooo

2022-08-01 22:37 UTC, stanalbatross requested changes

2022-08-01 22:37 UTC, stanalbatross commented on code/game/objects/structures/crates_lockers/closets.dm
> +	if(health == 0)
```suggestion
	if(health <= 0)
```
sanity

2022-08-01 22:37 UTC, stanalbatross commented on code/game/objects/structures/girders.dm
> +	if(health == 0)
```suggestion
	if(health <= 0)
```

2022-08-01 22:37 UTC, stanalbatross commented on code/modules/mob/living/carbon/human/human_damage.dm
> +*/
remove

2022-08-01 22:37 UTC, stanalbatross commented on code/modules/mob/living/carbon/xenomorph/abilities/crusher/crusher_abilities.dm
> +/datum/action/xeno_action/activable/tumble/proc/handle_mob_collision(mob/living/carbon/human/Human)
need a sanity check to see if the arg being parsed actually is a human

2022-08-01 22:37 UTC, stanalbatross commented on code/modules/mob/living/carbon/xenomorph/abilities/crusher/crusher_powers.dm
> +/datum/action/xeno_action/onclick/crusher_stomp/charger/use_ability(atom/Target)
needs a target sanity check

2022-08-01 22:37 UTC, stanalbatross commented on code/modules/mob/living/carbon/xenomorph/abilities/crusher/crusher_powers.dm
> +		to_chat(Human, SPAN_XENOHIGHDANGER("You are BRUTALLY crushed an stompted on by [Xeno] !!!"))
```suggestion
		to_chat(Human, SPAN_XENOHIGHDANGER("You are BRUTALLY crushed and stomped on by [Xeno]!!!"))
```

2022-08-01 22:37 UTC, stanalbatross commented on code/modules/mob/living/carbon/xenomorph/abilities/crusher/crusher_powers.dm
> +		//to_chat(H, SPAN_XENOHIGHDANGER("You are slowed as [X] knocks you off balance!"))
zoink this commented stuff

2022-08-01 22:37 UTC, stanalbatross commented on code/modules/mob/living/carbon/xenomorph/mutators/strains/crusher/charger.dm
> +	C.ignore_aura = "frenzy" // no funny crushers going 7 morbillion kilometers per second
make this known to the crushers

2022-08-01 22:37 UTC, stanalbatross commented on code/modules/mob/living/carbon/xenomorph/mutators/strains/crusher/charger.dm
> +	health -= CCA.momentum * 40 //Usually knocks it down.
use a define

2022-08-01 22:37 UTC, stanalbatross commented on code/modules/mob/living/carbon/xenomorph/mutators/strains/crusher/charger.dm
> +	health -= CCA.momentum * 40 //Usually knocks it down.
as above

2022-08-01 22:37 UTC, stanalbatross commented on code/modules/mob/living/carbon/xenomorph/mutators/strains/crusher/charger.dm
> +		CCA.lose_momentum(1) //Lose one turf worth of speed
use defines for these loss amounts

2022-08-01 22:37 UTC, stanalbatross commented on code/modules/mob/living/carbon/xenomorph/mutators/strains/crusher/charger.dm
> +			SPAN_XENODANGER("You smash straight into [src]!")
```suggestion
			SPAN_DANGER("[X] smashes straight into \the [src]!"),
			SPAN_XENODANGER("You smash straight into \the [src]!")
```

2022-08-01 22:37 UTC, stanalbatross commented on code/modules/mob/living/carbon/xenomorph/mutators/strains/crusher/charger.dm
> +			SPAN_XENODANGER("You smash straight into [src]!")
\the

2022-08-01 22:37 UTC, stanalbatross commented on code/modules/mob/living/carbon/xenomorph/mutators/strains/crusher/charger.dm
> +			SPAN_XENOWARNING("You ram into [src] and skid to a halt!")
\the

2022-08-01 22:37 UTC, stanalbatross commented on code/modules/mob/living/carbon/xenomorph/mutators/strains/crusher/charger.dm
> +		SPAN_XENODANGER("You ram [src]!")
\the

2022-08-01 22:37 UTC, stanalbatross commented on code/modules/mob/living/carbon/xenomorph/mutators/strains/crusher/charger.dm
> +			SPAN_XENODANGER("You ram [src]!")
\the

2022-08-01 22:37 UTC, stanalbatross commented on code/modules/mob/living/carbon/xenomorph/mutators/strains/crusher/charger.dm
> +			to_chat(world, "TEST STEST")
💀

2022-08-01 22:37 UTC, stanalbatross commented on code/modules/mob/living/carbon/xenomorph/mutators/strains/crusher/charger.dm
> +		SPAN_XENODANGER("You ram [src]!")
\the

2022-08-01 22:37 UTC, stanalbatross commented on code/modules/mob/living/carbon/xenomorph/mutators/strains/crusher/charger.dm
> +		SPAN_XENODANGER("You ram [src]!")
\the

2022-08-04 00:39 UTC, PhantomEpicness commented on code/modules/mob/living/carbon/human/human_damage.dm
> +*/
done

2022-08-04 01:16 UTC, PhantomEpicness commented on code/modules/mob/living/carbon/xenomorph/mutators/strains/crusher/charger.dm
> +	C.ignore_aura = "frenzy" // no funny crushers going 7 morbillion kilometers per second
stated in strain desc

2022-08-07 20:05 UTC, stanalbatross commented
fix conflicts + do suggestions

2022-08-22 19:24 UTC, Carnage068 commented
we back in this

2022-08-26 00:10 UTC, stanalbatross requested changes

2022-08-26 00:10 UTC, stanalbatross commented on code/modules/defenses/bell_tower.dm
> +		to_chat(to_apply, SPAN_WARNING("You ignore some weird noises as you charge."))
return under here

2022-08-26 00:10 UTC, stanalbatross commented on code/modules/mob/living/carbon/xenomorph/abilities/crusher/crusher_abilities.dm
> +/datum/action/xeno_action/activable/tumble/proc/handle_mob_collision(mob/living/carbon/human/Human)
do

2022-08-26 00:10 UTC, stanalbatross commented on code/modules/mob/living/carbon/xenomorph/mutators/strains/crusher/charger.dm
> +			SPAN_XENODANGER("You smash straight into [src]!")
missed

2022-08-26 00:10 UTC, stanalbatross commented on code/modules/mob/living/carbon/xenomorph/mutators/strains/crusher/charger.dm
> +			SPAN_XENOWARNING("You ram into [src] and skid to a halt!")
missed

2022-08-27 02:01 UTC, PhantomEpicness commented
Issue:

Alacrit fruit makes crusher go frenzy speed

2022-08-27 10:02 UTC, Misttyy commented
I really like charger except for one thing.

I've noticed a bit, and talked with other marine players to confirm it wasn't a one off thing. One charger ram can give someone 7-8 bleeds, or make them bleed across their entire body. This feels very excessive.

2022-08-28 15:49 UTC, stanalbatross approved these changes
any further issues with alacrit can be looked at with balance to the fruit itself

2022-08-28 18:21 UTC, PhantomEpicness commented
Made alacrit fruit work 

> I really like charger except for one thing.
> 
> I've noticed a bit, and talked with other marine players to confirm it wasn't a one off thing. One charger ram can give someone 7-8 bleeds, or make them bleed across their entire body. This feels very excessive.

It does overall damage instead of targeted damage. This prevents getting organ damage/fracs on one charge or stupid insta delimbs.

Unless you want the latter, this is how it's going to be.

2022-08-28 18:50 UTC, Carnage068 commented
> Made alacrit fruit work on charger, but it wanes when charging


THANK YOU.

2022-08-30 19:46 UTC, PhantomEpicness commented
ready for merge

2022-08-31 07:55 UTC, nauticall approved these changes
Sprites are fine, at least the ones on this PR. If there'll be new sprites on the CM xeno side as well they'll need another looking at

2022-08-31 17:00 UTC, stanalbatross requested changes

2022-08-31 17:00 UTC, stanalbatross commented on code/datums/effects/xeno_strains/xeno_speed.dm
> +		to_chat(affected_mob, SPAN_XENOWARNING("Your bowels are evacuated as you charge!"))
better message please.

2022-08-31 17:00 UTC, stanalbatross commented on code/datums/effects/xeno_strains/xeno_speed.dm
> +	return ..()
newline below

2022-08-31 17:16 UTC, merged

2022-08-31 18:35 UTC, Carnage068 commented
Welp its back now, we did it.

2022-09-01 02:53 UTC, Wintermote commented
> It does overall damage instead of targeted damage. This prevents getting organ damage/fracs on one charge or stupid insta delimbs.
> 
> Unless you want the latter, this is how it's going to be.

Still seems very weird. You're being hit by a blunt object, so getting bleeds on every body part just doesn't thematically fit. Like I'd expect that from a ravager ability, not the crusher.

2022-09-01 04:41 UTC, PhantomEpicness commented
> > It does overall damage instead of targeted damage. This prevents getting organ damage/fracs on one charge or stupid insta delimbs.
> > Unless you want the latter, this is how it's going to be.
> 
> Still seems very weird. You're being hit by a blunt object, so getting bleeds on every body part just doesn't thematically fit. Like I'd expect that from a ravager ability, not the crusher.
![Screenshot_419](https://user-images.githubusercontent.com/42422230/187832508-14555ce1-ccfd-4779-b555-e1d4656b1ade.png)

I looked deeper and brute damage over 10 has a random chance of causing bleeding. This is a product of human damage code and reworking damage is not the scope of this PR.

What we can do however, which I will note for the eventual balance patch, is lower the limb spread chance. This will focus the damage on fewer limbs, causing less overall damage but more focused damage, which I have tried to avoid because one hit massive organ damage is not fun.

2022-09-01 19:51 UTC, Carnage068 commented
> What we can do however, which I will note for the eventual balance patch, is lower the limb spread chance. This will focus the damage on fewer limbs, causing less overall damage, and therefore less overall bleeding, but more focused damage, which I have tried to avoid because one hit massive organ damage is not fun.

Or you can just lower the charge damage a bit overall. Would probably help, considering that some people are getting one shot without being hit by a full charge, and sometimes one shot without even getting hit by charge at all.

2022-09-01 19:56 UTC, PhantomEpicness commented
> > What we can do however, which I will note for the eventual balance patch, is lower the limb spread chance. This will focus the damage on fewer limbs, causing less overall damage, and therefore less overall bleeding, but more focused damage, which I have tried to avoid because one hit massive organ damage is not fun.
> 
> Or you can just lower the charge damage a bit overall. Would probably help, considering that some people are getting one shot without being hit by a full charge, and sometimes one shot without even getting hit by charge at all.

agreed

2022-09-01 22:38 UTC, c4xmaniac commented
Consider making the charger crusher faster, at least getting up to full momentum. It really takes a long time, and its really easy to stop the crusher from getting up to to charge speed. Its on the cusp of being fun/good, but its not there yet imo.

2022-09-01 23:04 UTC, Carnage068 commented
> Consider making the charger crusher faster, at least getting up to full momentum. It really takes a long time, and its really easy to stop the crusher from getting up to to charge speed. Its on the cusp of being fun/good, but its not there yet imo.

It's supposed to need room to start up a full charge. Being able to bodyblock it to prevent it from getting to that speed is just called good counterplay. At the same time, it shouldn't be almost completely immobile when it IS bodyblocked though. It would just make things too binary. One of the differences between Charger and Base Crusher is that it's supposed to be faster, not just sometimes, but in general. Or at least, that's what was fun for me. Being fast is just fun.