The great research hugboxing
cmss13-devs/cmss13 pull request #6625
Opened 2024-07-05 20:29 UTC by iloveloopers

# About the pull request
removes the ability to buy clearance papers
clearance cards now give credits instead
cards no longer lose their value when scanned by the wrong person

# Explain why it's good for the game
less opportunities for bald researchers to waste the team's hard earned credits

# Testing Photographs and Procedure
i tested it and it works

# Changelog

:cl:
del: Removed buying clearance papers.
qol: Clearance cards now give their equivalent clearance in credits.
qol: Clearance cards no longer lose their value when scanned by the wrong person.
/:cl:

2024-07-06 03:13 UTC, TheManWithNoHands commented
Dont remove buying chem papers. It can often come in clutch when IOs already piked the colonie clean.
Great source of legendary propertys.

Dont remove tools just because some dont know how to use it.

2024-07-06 03:34 UTC, iloveloopers commented
Right, because rolling the dice on RNG clearance papers in hopes of getting a legendary is peak game design. 99% of the time they aren't bought at all and the 1% is bald researchers screwing up their team by wasting credits on it.

2024-07-14 05:42 UTC, Drulikar requested changes

2024-07-14 05:42 UTC, Drulikar commented on code/modules/reagents/chemical_research/Chemical-Research.dm
> +	var/credits_gained = 0 //credits gained from survivor clearance cards
Either autodoc it properly with `///` or name it better

2024-07-14 05:42 UTC, Drulikar commented on code/game/machinery/computer/research.dm
> +	GLOB.chemical_data.credits_gained = max(GLOB.chemical_data.credits_gained, card.credits_to_give)
```suggestion
	if(credits_to_add)
		GLOB.chemical_data.update_credits(credits_to_add)
		GLOB.chemical_data.credits_gained += credits_to_add
```
Existing way seems needlessly convoluted for what you're trying to accomplish of just limiting the bonus to the best card swiped.

2024-07-14 05:42 UTC, Drulikar commented on code/game/machinery/computer/research.dm
> +	msg_admin_niche("[key_name(user)] has swiped a clearance card and given [credits_to_add] credits to research.")
```suggestion
	msg_admin_niche("[key_name(user)] has swiped a clearance card to give [credits_to_add] credits to research.")
```

2024-07-14 05:42 UTC, Drulikar commented on code/game/machinery/computer/research.dm
> +	visible_message(SPAN_NOTICE("[user] swipes their ID card on \the [src], granting [credits_to_add] credits."))
```suggestion
	visible_message(SPAN_NOTICE("[user] swipes their ID card on [src], granting [credits_to_add] credits."))
```

2024-07-14 22:23 UTC, iloveloopers commented
its jover

2024-07-14 22:23 UTC, closed without merging