Lets xenos drag and drop themselves into a vent crawl
cmss13-devs/cmss13 pull request #6635
Opened 2024-07-06 11:20 UTC by GrrrKitten

# About the pull request

Pt1 of making vents cooler to use

# Explain why it's good for the game

QOL, it feels like this is just how it should be, not sure why its not like this already

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

</details>

# Changelog

:cl: Grrr Kitten
qol: xenos can now drag and drop themselves to vent crawl
/:cl:

2024-07-06 11:22 UTC, RainbowStalin commented
Finaly a way to get into vents without using the verbs.

2024-07-06 11:41 UTC, TheManWithNoHands commented
> Finaly a way to get into vents without using the verbs.

Verb? Isnt it just alt + M1.

2024-07-06 15:20 UTC, GrrrKitten commented
> > Finaly a way to get into vents without using the verbs.
> 
> 
> 
> Verb? Isnt it just alt + M1.

I didn't know this, why must there be so much esoteric knowledge behind dumb binds. 

Anyways I'm keeping this up as it doesn't hurt to have more options

2024-07-06 18:43 UTC, vero5123 commented
~money~

2024-07-07 17:20 UTC, harryob requested changes

2024-07-07 17:20 UTC, harryob commented on code/game/objects/structures/pipes/vents/vents.dm
> +	if(dropvent in range(1))
```suggestion
	if(get_dist(src, user) <= 1)
```

2024-07-07 17:20 UTC, harryob commented on code/game/objects/structures/pipes/vents/vents.dm
> +/obj/structure/pipes/vents/MouseDrop_T(obj/structure/pipes/vents/dropvent, mob/living/carbon/xenomorph/user)
isn't dropvent here the atom being dropped (aka the user)?

```suggestion
/obj/structure/pipes/vents/MouseDrop_T(atom/dropping, mob/living/carbon/xenomorph/user)
```

2024-07-07 17:20 UTC, harryob commented on code/game/objects/structures/pipes/vents/vents.dm
> +	if(!isxeno(user) || !user.check_state() || !user.can_ventcrawl())
```suggestion
	if(!isxeno(user) || !user.check_state() || !user.can_ventcrawl() || dropping != user)
```

2024-07-22 01:02 UTC, closed without merging

2024-07-27 13:43 UTC, Drulikar commented
Feel free to ask for reopen when above can be addressed.