autoclimbable handrails
cmss13-devs/cmss13 pull request #6652
Opened 2024-07-07 21:53 UTC by cuberound

# About the pull request

you do climb when you collide with handrail, rejoice.  this makes handrails lot less of an obsticle for both huge xenos and highly rained and agile marines

# Explain why it's good for the game

handrails can be major pain in ass for both marines and xenos, especily as they are used near ledges so you auto climb from one side to other but have to manualy climb back. they are also sometimes hard to spot and can get you stuck and killed, generly getting stoped by railing that you did not see feels like shit as both sides can shoot or slash it down in seconds. I am gona put this as QOL but if you think it is balance then so be it

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
qol: handrails are autoclimbable
/:cl:

2024-07-19 02:36 UTC, Drulikar requested changes

2024-07-19 02:36 UTC, Drulikar commented on code/game/objects/structures/barricade/handrail.dm
> +					climber.apply_damage(15,BRUTE)
This is too much damage, probably doesn't need to always happen (prob 25 or something), should ensure `no_limb_loss` is set, and needs to induce movement delay (really goofy how fast you just vault any rails in sequence).

Req is going to get really bloody with this PR. I highly recommend you consider downloading strongdmm to edit req's railing to not have this behavior either with a var edit or a new subtype.

![the worst vaulter](https://github.com/user-attachments/assets/a6eef130-d777-44f6-afec-0c6e3168b401)

2024-07-19 02:36 UTC, Drulikar commented on code/game/objects/structures/barricade/handrail.dm
> +		if(!xenomorph.stat) //No dead xenos jumpin on the bed~
```suggestion
		if(xenomorph.stat == CONSCIOUS) //No dead xenos jumpin on the bed~
```

2024-07-19 02:36 UTC, Drulikar commented on code/game/objects/structures/barricade/handrail.dm
> +	..()
A normal crusher using the charge ability will double deconstruct this handrail. Consider just returning after the earlier `deconstruct(FALSE)`

2024-07-27 05:44 UTC, Drulikar requested changes

2024-07-27 05:44 UTC, Drulikar commented on code/game/objects/structures/barricade/handrail.dm
> +							climber.apply_damage(15,BRUTE,no_limb_loss = TRUE)
See https://github.com/cmss13-devs/cmss13/actions/runs/10111981060/job/27965048466?pr=6652#step:8:20

Basically either you need to type `climber` as a `/mob/living/carbon/human` or you add the missing arguments to `/mob/living/proc/apply_damage`

2024-07-27 05:49 UTC, Drulikar commented on code/game/objects/structures/barricade/handrail.dm
> +		if(!xenomorph.stat) //No dead xenos jumpin on the bed~
Application of this suggestion was reverted so is still outstanding.

2024-07-27 05:50 UTC, Drulikar requested changes

2024-07-27 05:50 UTC, Drulikar commented on code/game/objects/structures/barricade/handrail.dm
> +					climber.client.move_delay += 3 DECISECONDS
```suggestion
					climber.client?.move_delay += 3 DECISECONDS
```
Mobs won't always have clients.

2024-07-29 09:27 UTC, Drulikar commented on code/game/objects/structures/barricade/handrail.dm
> +					climber.apply_damage(15,BRUTE)
15 damage is still too much even with 25 prob. Try something more like 5.

2024-07-29 09:36 UTC, Drulikar requested changes

2024-07-29 09:36 UTC, Drulikar commented on code/game/objects/structures/barricade/handrail.dm
> +					climber.client?.move_delay += 3 DECISECONDS
This needs to be moved before the `do_climb` else it will never take effect until after all the do_afters are complete (what we're trying to delay)

2024-08-03 16:42 UTC, Git-Nivrak commented
This makes it so you auto climb even when pushed which shouldn't be a thing

2024-08-04 16:13 UTC, Drulikar requested changes
- if someone else can push you over a railing, the collide should just behave as normal preventing you from moving that direction
- if you don't want to make railing exceptions via mapping edits, consider instead making a z level check for the Almayer to prevent the auto vaulting of railings on that z level (or maybe only if it's hijack?)

2024-08-24 10:23 UTC, harryob commented
pr seems to be stale, let us know if you want it re-opening, or just make a fresh pr for it

2024-11-07 21:24 UTC, Drulikar approved these changes

2024-11-09 02:22 UTC, merged