Re: Made APC's Directional to reduce lines of code, Use and Adds Updatepaths.txt file.
cmss13-devs/cmss13 pull request #6686
Opened 2024-07-11 10:11 UTC by Venuska1117

# About the pull request

This PR add directional APC's and Updatepath.txt

# Explain why it's good for the game

Reduces lines of codes in mapping, i know there is already code in apc.dm to make them have pixel_y or pixel_x offset.

Mainly issue is: in map editor they have var edited offsets, with mean it not only override code that already exist, but also occupy more space, with new code it should do same in exchange for less lines of code. (i didnt remove directional code for other stuff like broken APC's etc.)

# Changelog
It do not change anything on maps itself, just replaces paths.

2024-07-14 09:53 UTC, blackdragonTOW commented
Hello! Please remember to attach screenshots of your altered sprites in the PR description!!

2024-07-18 00:57 UTC, Nanu308 requested changes
From looking at the map diff bot, you seem to have removed some APC's entirely. Were these apc's doubled in an area?

2024-07-19 15:21 UTC, Venuska1117 commented
> From looking at the map diff bot, you seem to have removed some APC's entirely. Were these apc's doubled in an area?

yeah, the new checking system did not allow me to commit, beacause there were duplicated APC's, nanomeds etc.

2024-07-25 06:27 UTC, nauticall approved these changes
sproites

2024-07-28 09:11 UTC, Drulikar commented
Wires are still incorrect. E.g. 
![image](https://github.com/user-attachments/assets/24c252d1-5ee5-424c-a8a5-85c9f74e05d5)

And no, this is not the case on master:
![image](https://github.com/user-attachments/assets/54ad79af-e8f6-4449-9852-e27f3df6493c)

The reasoning is because in the DMI you reversed all directions for the apcs and wires. So if you are certain thats how you want them in the dmi, you must ensure every apc accounts for the change.

2024-07-29 12:49 UTC, Drulikar requested changes

2024-07-29 12:49 UTC, Drulikar commented on tools/UpdatePaths/Scripts/6686-apc-replacement.txt
Why did you opt to eliminate all start_charge values?

2024-07-29 13:29 UTC, Venuska1117 commented on tools/UpdatePaths/Scripts/6686-apc-replacement.txt
by default apc.dm have start_charge 90 (with mean 90%)
![image](https://github.com/user-attachments/assets/c25e4e76-72c1-4e8c-b602-322c1fc4d24f)

so i don't need to edit them, only if i need to add apc's with 0% of power (like no_power ones)

2024-08-01 08:26 UTC, Drulikar requested changes

2024-08-01 08:26 UTC, Drulikar commented on code/modules/power/apc.dm
Is there any reason to keep `directional` as part of the path? You altered the behavior of `/obj/structure/machinery/power/apc` anyways so not like there's any unique behavior for the directional subtypes.

Also `/obj/structure/machinery/power/apc/nocharge` has no use now so should just be removed.

2024-08-01 08:26 UTC, Drulikar commented on maps/map_files/LV522_Chances_Claim/LV522_Chances_Claim.dmm
Chances claim used to use `/obj/structure/machinery/power/apc/weak` which has a capacity of 1000. They are now using apcs with cells with 5000 capacity. Since there are 56 APCs that have a 90% charge here, consider either keeping the `weak` variant, or make a variant or var edit all the chances claims apcs that were weak to have 1/5 the starting charge.

2024-08-06 20:03 UTC, Venuska1117 commented on maps/map_files/LV522_Chances_Claim/LV522_Chances_Claim.dmm
i changed in .txt file, now they are replaced with start_charge = 20 (20% from 5000) so its back to 1000.

2024-08-06 20:06 UTC, Venuska1117 commented on code/modules/power/apc.dm
the `directional` part of path is for people who will intend to map in future, most of that have edit of pix_x and pix_y (depending with direction you want them) to make more easy to understand as mapper without need to check code every time you want to do some inserts/mapping. _(they are visible in mapping to be moved in direction, so giving them `directional` in path name make it more readable)_

2024-08-06 20:08 UTC, Venuska1117 commented on maps/map_files/LV522_Chances_Claim/LV522_Chances_Claim.dmm
if hyper ones for CORSAT need be start_charge = 300 (so it go back to 30000 if used on apc/upgraded)

2024-08-06 20:15 UTC, Drulikar commented on maps/map_files/LV522_Chances_Claim/LV522_Chances_Claim.dmm
CORSAT doesn't need to change; as I said before I think it was more a lore reason for them to have higher tech stuff. My feedback here was on Chances Claim's weakones since basically every APC is powered now and powered with significantly more power than they used to.

2024-08-06 20:16 UTC, Drulikar commented on code/modules/power/apc.dm
Directional in the path suggests that there's *non* directional apcs which is not that case. I would rather the unnecessary path removed. APCs have always had a concept of needing to face a certain direction; they'd just pixel shift before and now they actually have a sprite.

2024-08-06 23:52 UTC, Drulikar requested changes
Otherwise everything else looks fine

2024-08-06 23:52 UTC, Drulikar commented on maps/map_files/Sorokyne_Strata/Sorokyne_Strata.dmm
![image](https://github.com/user-attachments/assets/61244ba8-9247-4246-b7df-7b6b075cc91a)
![image](https://github.com/user-attachments/assets/b029b7a8-07de-4f87-a4e7-e6b07d70becd)

I believe this is fixed in #6071 but in the interim can you fix this one and maybe consider adding that non-dirt turf for the other tcoms?

2024-08-06 23:52 UTC, Drulikar commented on maps/map_files/FOP_v2_Cellblocks/Prison_Station_FOP.dmm
Near showers in the north high security checkpoint there is an east facing APC that should be south facing or moved:
![image](https://github.com/user-attachments/assets/1f680e57-017c-476c-9d48-57f20cb44f0b)
![image](https://github.com/user-attachments/assets/0697cd23-b8e1-447e-86d7-0448bddadf9b)

2024-08-06 23:52 UTC, Drulikar commented on maps/map_files/FOP_v2_Cellblocks/Prison_Station_FOP.dmm
The Medium-Security Cellblock East APC near the ship is south facing and floating. It should be moved somewhere else.
![image](https://github.com/user-attachments/assets/65af4a54-0a03-4f75-b440-f4597003b210)
![image](https://github.com/user-attachments/assets/28446bdc-2055-4589-b23b-35b38b286720)

2024-08-07 13:43 UTC, Venuska1117 commented on maps/map_files/Sorokyne_Strata/Sorokyne_Strata.dmm
yes it was fixed in #6071 i tough it was something on my side (but with this i am sure its not that) as for non-dirt turf, i will see what i can do.

2024-08-07 16:31 UTC, Drulikar commented on maps/map_files/Sorokyne_Strata/Sorokyne_Strata.dmm
For the non-dirt turf you just need to do the same as you did in 6071. I was just saying for both of those fixes to also be in this pr

2024-08-07 16:39 UTC, Drulikar commented on maps/map_files/Sorokyne_Strata/Sorokyne_Strata.dmm
Specifically this fix: 
![IMG_1426](https://github.com/user-attachments/assets/27350ebc-b7d4-4fe6-91e6-ce7924dd4c04)

2024-08-07 19:43 UTC, Drulikar approved these changes

2024-08-07 19:49 UTC, merged