Autocannon & Minigun IFF, code cleanup, new sounds
cmss13-devs/cmss13 pull request #6688
Opened 2024-07-11 19:02 UTC by TheManWithNoHands

# About the pull request

* Adds IFF to the Autocannon
* Adds IFF to the Minigun
* Adds hitsound for Autocannon Flakbullets
* Puts Minigun bullet code into the tank ammo file, for organisation.

# Explain why it's good for the game

Autocannon and Minigun for the Tank are lacking IFF for no good reason. Its a left over from old code and isnt adjusted for its current state.
This should make the Minigun and Autocanon less ass to use, because rigth now its not that fun.
The autocannon keeps FF on the AOE of its shots, so you still cant use it blindly.
The minigun is currently just a worse choice over the autocannon. So to not fully put it down like old space yeller, it also needs IFF.
Needs some more buffs as well, but i cant manage to code them in yet.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

</details>

# Changelog

:cl: TheManWithNoHands
balance: Adds IFF to Autocannon & Minigun
code: Places minigun aMmo in the Tank ammo File
soundadd: adds a hit sound for 20mm flak
/:cl:

2024-07-29 19:37 UTC, Drulikar commented
stale exempt until reviewed

2024-08-17 23:39 UTC, kiVts submitted a review, later dismissed

2024-08-17 23:39 UTC, kiVts commented on code/datums/ammo/bullet/tank.dm
> +/datum/ammo/bullet/tank/minigun/proc/setup_hvh_damage()
Every proc that is registered in register signal must have SIGNAL_HANDLER on the top.

2024-08-17 23:39 UTC, kiVts commented on code/datums/ammo/bullet/tank.dm
> +	sound_hit  = list('sound/weapons/sting_boom_small1.ogg')
add the path to file in get_sfx and link it here instead, look at how other sound_hit is done, this is mostly for consistency though.

2024-08-18 03:55 UTC, TheManWithNoHands commented
How the hell did i start a review by answering someone.

2024-08-23 11:55 UTC, Blundir approved these changes

2024-08-23 12:55 UTC, harryob requested changes

2024-08-23 12:55 UTC, harryob commented on code/datums/ammo/bullet/tank.dm
> +//Autocannon Ammo//
```suggestion
//Autocannon Ammo//
```

2024-08-23 12:55 UTC, harryob approved these changes

2024-08-23 13:31 UTC, merged