Disablers can no longer execute people
cmss13-devs/cmss13 pull request #6696
Opened 2024-07-12 16:57 UTC by zzzmike

# About the pull request

Disablers can't execute people anymore.

# Explain why it's good for the game

This doesn't really make sense to be in the game, I've never seen anyone intentionally try to execute with a disabler before, it's always some poor newbie MP who does it by accident and gets PTSD afterwards.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
del: Disablers can't execute people anymore
/:cl:

2024-07-12 17:12 UTC, iloveloopers commented
Removes soul

2024-07-21 05:28 UTC, zzzmike commented
> Removes soul

Erm actually it preserves soul (of the character getting accidentally executed) 🤓

2024-07-29 20:28 UTC, Drulikar requested changes

2024-07-29 20:28 UTC, Drulikar commented on code/modules/projectiles/guns/energy.dm
> +	flags_gun_features = GUN_CANT_EXECUTE
You need to retain the gun features from parent. So either

`flags_gun_features = GUN_UNUSUAL_DESIGN|GUN_CAN_POINTBLANK|GUN_CANT_EXECUTE`
or
`flags_gun_features = parent_type::flags_gun_features | GUN_CANT_EXECUTE`
But I will note its not the norm to do the latter at least yet (515 feature).

2024-07-29 23:14 UTC, zzzmike commented
thanks, also do you know why the bot removed the stale flag? was it because I made a comment ~20 hours earlier?

2024-07-30 02:23 UTC, Drulikar commented
> thanks, also do you know why the bot removed the stale flag? was it because I made a comment ~20 hours earlier?

Yes the stale workflow is just trying to detect inactivity

2024-07-30 02:25 UTC, Drulikar approved these changes

2024-07-30 02:52 UTC, merged

2024-07-30 09:26 UTC, RavinHobo commented
1984