New Pizza Cutters
cmss13-devs/cmss13 pull request #6697
Opened 2024-07-12 23:55 UTC by Mensla

# About the pull request

Re-trying this PR as last time I got caught up with IRL stuff and let it rot.

Adds two new pizza cutter sprites, one with a plastic handle and one with a wooden handle. Adds item sprites and hand-holding sprites.

No more comically large pizza cutter as they're now appropriately sized sprites in your hand.

# Explain why it's good for the game

Allows for people to use a normal and non-memey pizza cutter. 

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

![image](https://github.com/cmss13-devs/cmss13/assets/102622741/8d8e3232-0f1f-49cc-b897-d94ed0b365cd)
![image](https://github.com/cmss13-devs/cmss13/assets/102622741/590cd27f-b51b-4878-b9a5-6d3427303185)

</details>

# Changelog

:cl:
add: Added new pizza cutter sprites.
/:cl:

2024-07-12 23:55 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-07-15 16:47 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-07-18 01:00 UTC, Nanu308 requested changes
Fix the errors from the pipeline/CI

2024-07-18 20:37 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-07-21 02:19 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-07-21 19:55 UTC, Mensla reviewed
Should be good to go, just needs reviewing now

2024-07-22 12:48 UTC, Nanu308 reviewed
mapping lgtm

2024-08-06 01:12 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-08-06 16:59 UTC, Drulikar requested changes

2024-08-06 16:59 UTC, Drulikar commented on code/game/objects/items/tools/kitchen_tools.dm
> +	edge = 1
```suggestion
	edge = TRUE
```

2024-08-06 16:59 UTC, Drulikar commented on code/game/objects/items/tools/kitchen_tools.dm
> +	edge = 1
```suggestion
```
Can just be removed to be inherited from parent.

2024-08-06 16:59 UTC, Drulikar commented on code/game/objects/items/tools/kitchen_tools.dm
> +	sharp = IS_SHARP_ITEM_ACCURATE
```suggestion
```
Can just be removed to be inherited from parent.

2024-08-10 14:55 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-08-10 17:51 UTC, Drulikar approved these changes

2024-08-17 15:37 UTC, nauticall approved these changes

2024-08-21 00:36 UTC, Zonespace27 approved these changes

2024-08-21 00:53 UTC, merged