HPR Starts With Bipod Attached
cmss13-devs/cmss13 pull request #6715
Opened 2024-07-15 09:41 UTC by Steelpoint

# About the pull request

See title. The HPR will now spawn in with a Bipod attached to it. 

# Explain why it's good for the game

The concept of the HPR having access to a unique auto-fire function, with a very high ROF, is not at all advertised to the average player, this is a concept wherein many people are left unaware of this function until it is revealed to them by a third party. This is common testimony from those who discuss the HPR and its bipod function.

Forcing the HPR to spawn with a bipod attached to it, will resolve the manner as it will expose far more people to the ability for the weapon to fire on auto-fire and thus reveal an entirely new and unique way to make usage of the firearm to people who may never have discovered it.

Considering the bipod is a fairly common attachment that is not often selected, and the Almayer has a very limited supply of HPRs, I do not believe this will have any real impact on attachment availability.  

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
add: The Heavy Pulse Rifle (M41AE2) will now start with a pre-attached bipod. To better inform players of its unique auto-fire function. 
/:cl:

2024-07-15 19:11 UTC, TheManWithNoHands commented
Can you at least reveal that uniqe thing the HPR does as well?

2024-07-16 14:20 UTC, Zonespace27 approved these changes

2024-07-17 09:51 UTC, ihatethisengine commented
The bipod is so unbalanced that it should be revised or removed rather than made more common.

2024-07-18 01:57 UTC, TheManWithNoHands commented
Why not jut put the bipod in its kit, like how its done with the HPR kit the SL can take.

2024-07-18 07:20 UTC, Steelpoint commented
I can fix the SL kit.

In terms of why I'm preferring it to start attached, its due to the fact that people are simply unaware of this facet of the HPR until told about it in OOC/deadchat/Discord. If the attachment starts attached people will notice the auto-fire HUD icon, and if they remove it they will notice it is gone. If the attachment starts detached, people will just throw it away.

2024-07-18 19:21 UTC, Drulikar requested changes
Please remove `new /obj/item/attachable/bipod` from:
- /obj/item/storage/box/guncase/lmg/fill_preset_inventory()
- /obj/item/storage/box/kit/heavy_support/fill_preset_inventory()

2024-07-19 14:29 UTC, Steelpoint commented
Requested changes made.

2024-07-19 20:27 UTC, Drulikar approved these changes

2024-07-19 21:01 UTC, merged