language tweaks
cmss13-devs/cmss13 pull request #672
Opened 2022-07-12 19:40 UTC by stanalbatross

## About The Pull Request

removes random officer languages (the uscm does not have the time, effort, or resources to train all their officers in 5000 different languages before deploying them)

gives the upp faction a random chance to speak Russian or Chinese each round - this is because they speak and use both languages. The battallion in the area would either be Russian-speaking or Chinese-speaking

## Why It's Good For The Game

better roleplay, immersion, realism, and sovl

## Changelog

:cl:
del: removed officers knowing languages that they would absolutely not have the time to learn before being deployed, instead take these languages in the character setup screen
del: removed the automatic ability of CLs to speak Japanese - not all WY employees would speak Japanese, if you want to roleplay as a Japanese speaker CL take the language from the setup screen
add: added a random chance per round for the UPP to either speak Chinese or Russian, to reflect the composition of real UPP battallions.
/:cl:

2022-07-12 19:44 UTC, Geevies commented
most tested PR of 2022

2022-07-30 11:43 UTC, JeserTheFox approved these changes

2022-07-30 15:19 UTC, Geevies requested changes
edit savefiles too

2022-07-30 15:19 UTC, Geevies commented on code/modules/gear_presets/uscm_event.dm
> +	. = ..()
```suggestion
```

2022-08-06 08:10 UTC, Geevies approved these changes

2022-08-06 08:11 UTC, merged