Drone devices removal
cmss13-devs/cmss13 pull request #6724
Opened 2024-07-16 10:24 UTC by cuberound

# About the pull request

removes unused shit

# Explain why it's good for the game

cleaner code

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
del:/obj/item/device/gripper and /obj/item/device/matter_decompiler removed
/:cl:

2024-07-16 21:32 UTC, TheManWithNoHands commented
I still member the little drone from comtecs. Sad to see its left overs going to pass on.
Sadge.

2024-07-18 01:02 UTC, Nanu308 requested changes
Add in a prop subtype that uses the sprite for it, we mappers like to keep thing looking the same.

2024-07-18 10:47 UTC, Zonespace27 commented on code/game/objects/prop.dm
> +/obj/item/prop/griper
misspelled.

2024-07-18 17:50 UTC, cuberound commented on code/game/objects/prop.dm
> +/obj/item/prop/griper
right, fixed now

2024-07-21 11:58 UTC, realforest2001 approved these changes

2024-07-28 13:33 UTC, Nanu308 reviewed
mapping lgtm

2024-07-30 20:41 UTC, merged