M47A2 Offensive Handgun
cmss13-devs/cmss13 pull request #6734
Opened 2024-07-17 06:50 UTC by zc-byte-boxer

# About the pull request

Adds the M47A2 offensive sidearm, a limited service 1911 variant used by limited USMC units, including FORECON. It finally adds a new, less ostentatious CO sidearm, and adds a unique sidearm for those on the backline.

# Explain why it's good for the game

Well, I concepted this pistol mainly as a new weapon for the commanding officer role that'd be more... less than the Mateba or Deagle. I'm very proud of the sprites I've got going with this, and since the lore fits, and it's a bit less powerful than the Mateba or Deagle, I'd like to include this as a non wl-exclusive item so more people may use it.

The intended design is to have a long-lasting sidearm that is sufficent for covering you in an emergency. It has damage inbetween the M44 and mod88, a slow RPM (help conserve that big magazine), low recoil, medium scatter, 14 rounds, and limited availability

# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

https://github.com/user-attachments/assets/db1100bd-771a-4ce2-892a-d291331cd489
</details>

# Changelog

:cl: Byte-Boxer
add: Added the M47A2 Offensive Handgun. It's a mix of the 1911 and Hush Puppy pistol for usage by specialized marine units within the USCM. It spawns as the default pistol for IOs, is available to the CO, has a 20% FORECON spawn, and spawns in limited numbers (the same as the MOU) in req.
add: Added the M47A2 HP, AP, Impact, and regular magazines. Due to combat messages these use their own bullet, too. Although, the base shares its bullets with the 1911.
code: Added a new reload volume setting for coders with their guns. I added it so I could make the 1911 reload real load, so people hear its awesomeness.
code: Changed some backend code for IOs to be simpler.
soundadd: New sounds for the M47A2 pulled from Call of Duty: Black Ops
/:cl:

2024-07-17 09:37 UTC, harryob requested changes
otherwise seems fine

2024-07-17 09:37 UTC, harryob commented on code/modules/projectiles/gun.dm
> +	if((reload_sound && reload_volume))
```suggestion
	if(reload_sound && reload_volume)
```

2024-07-17 21:51 UTC, zc-byte-boxer commented
Assuming the workflows pass, could we get a TM for this so I can get the balance worked out for this? Sorry about being pushy.

@harryob @Drulikar

2024-07-17 22:07 UTC, zc-byte-boxer commented
That should resolve the signal error.

2024-07-22 03:31 UTC, Diegoflores31 commented on code/modules/projectiles/guns/pistols.dm
> +// A version of the M1911 for COs and FORECON.
Forecom quite literally already spawns with a m1911

2024-07-22 03:31 UTC, Diegoflores31 commented on code/modules/projectiles/guns/revolvers.dm
> +	unacidable = TRUE
undocumented change

2024-07-22 03:31 UTC, Diegoflores31 commented on code/modules/projectiles/guns/pistols.dm
> +	unacidable = TRUE
undocumented change

2024-07-22 03:31 UTC, Diegoflores31 commented on code/modules/projectiles/guns/pistols.dm
> +	desc_lore = "The feeding ramp is polished to a mirror sheen, with a reinforced slide, and tightened locking mechanisms in the frame for added precision. The thumb safety is extended to make it easie
USCM not USMC

2024-07-22 03:31 UTC, Diegoflores31 commented on code/datums/ammo/bullet/pistol.dm
> +	damage_falloff = DAMAGE_FALLOFF_TIER_5
undocumented ?

2024-07-22 03:39 UTC, Diegoflores31 commented
I personally dont think this weapon fits . and it is probably bloat 
rather VP78 could use some refreshment or if you really want to add a weapon you could add the M4A4 that Exists in the lore https://avp.fandom.com/wiki/M4A4_Pistol

2024-07-23 01:15 UTC, zc-byte-boxer commented on code/modules/projectiles/guns/revolvers.dm
> +	unacidable = TRUE
added. thanks for da reminder

2024-07-23 01:15 UTC, zc-byte-boxer commented on code/modules/projectiles/guns/pistols.dm
> +	desc_lore = "The feeding ramp is polished to a mirror sheen, with a reinforced slide, and tightened locking mechanisms in the frame for added precision. The thumb safety is extended to make it easie
added. thanks for da reminder

2024-07-23 01:15 UTC, zc-byte-boxer commented on code/modules/projectiles/guns/pistols.dm
> +	unacidable = TRUE
added. thanks for da reminder

2024-08-03 06:59 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-08-03 15:46 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-08-07 03:14 UTC, Blundir requested changes
needs some shading, details work, attachment position tweaked, make a new sprite for magazine or at least tweak current one, elaborated in dm

2024-08-21 11:57 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-10-26 15:02 UTC, Blundir commented
let me know when you'd return to it

2024-10-26 15:02 UTC, closed without merging