Forecon ERT Adjustments
cmss13-devs/cmss13 pull request #6739
Opened 2024-07-17 16:27 UTC by Steelpoint

# About the pull request

Forecon ERTs will return to the USCM ERT station if spawned via shuttle.

The Forecon Medic/Engineer spawn has been adjusted. It now has a unique icon, a unique job name, and its toolset has been expanded to compensate for items I forgot to add, such as a medivisor and a lifesaver belt. 

This PR also adds a new full variant of a lifesaver belt for the Forecon Tech, furnished with necessary field equipment.

# Explain why it's good for the game

This PR essentially is adding features that I overlooked during my initial PR, or are otherwise better emphasising what certain roles do. 

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
add: Force reconnaissance response teams will now use the USS Kurtz as their home base when departing from the USS Almayer on their response shuttle.
balance: The ERT Forecon Medic/Engineer spawn has been reworked into the 'Reconnaissance Support Technician' to better reflect its design as a combination of a Corpsman and a Comtech. 
add: Per the above, the Support Tech now spawns with a unique and full lifesaver belt and some form of a medical visor. 
imageadd: The Support Tech has a unique HUD icon to better denote its role. 

/:cl:

2024-07-25 12:42 UTC, nauticall approved these changes
sprite (singular) 👍

2024-07-28 10:46 UTC, Drulikar requested changes
May be worth making another pass on what items they spawn with. Though I think the only issue may be with marksman:
![image](https://github.com/user-attachments/assets/97ee8d66-70fa-4765-bea6-4e2ab13f7b21)

2024-08-11 15:12 UTC, Steelpoint commented
Fixed the issue and did a bit of tidying up.

2024-08-21 00:39 UTC, Zonespace27 approved these changes

2024-08-21 01:02 UTC, merged