Elite Mercenary Non-Deathsquad Version
cmss13-devs/cmss13 pull request #6757
Opened 2024-07-18 16:04 UTC by Steelpoint

# About the pull request

Alt to: https://github.com/cmss13-devs/cmss13/pull/6740

Adds a new non-Deathsquad varient of the Elite Mercenary ERT. 

These mercenaries lack Deathsquad tier armour and Whiteout weapons. Their armour is now akin to Medium Marine armour but with Light movement speed, and they use mostly common or UPP style weapons. 

# Explain why it's good for the game

Opens up the opportunity for these rarely used ERTs to be used more often for admin events. 

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
add: The Elite Mercenary emergency response team has been split into a Deathsquad and non-Deathsquad version. Previously this ERT only functioned with Deathsquad weapons/armour. 
admin: The Elite Mercenary Deathsquad version can be denoted with the title of (!DEATHSQUAD!). The non-Deathsquad version possess weapons and armour similar to a typical Marine, albeit they still possess night vision optics. 
/:cl:

2024-07-30 19:21 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-08-11 14:45 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-08-23 12:52 UTC, harryob requested changes

2024-08-23 12:52 UTC, harryob commented on code/modules/gear_presets/_select_equipment.dm
> +/datum/equipment_preset/proc/spawn_merc_elite_weapon_lowthreat(atom/M, ammo_amount = 12, shotgun_chance = 50, spawn_belt = 1)
why is this defined so high up instead of on `/datum/equipment_preset/other/elite_merc`

2024-08-23 12:52 UTC, harryob commented on code/modules/gear_presets/_select_equipment.dm
> +/datum/equipment_preset/proc/spawn_merc_elite_weapon_lowthreat(atom/M, ammo_amount = 12, shotgun_chance = 50, spawn_belt = 1)
also given you're only piping humans into this, you can just type it appropriately

2024-08-23 12:52 UTC, harryob commented on code/modules/gear_presets/_select_equipment.dm
> +			if(ishuman(M))
redundant, type is known

2024-08-23 12:52 UTC, harryob commented on code/modules/gear_presets/_select_equipment.dm
> +	if(!M) return
no inline control

2024-08-25 10:51 UTC, closed without merging