energy gun fixes
cmss13-devs/cmss13 pull request #678
Opened 2022-07-13 20:47 UTC by stanalbatross

## About The Pull Request

closes #594 

## Why It's Good For The Game

## Changelog

:cl:
add: energy weapons, provided they have a charge meter, now tell you how many shots they have left on examine and when you fire them
fix: taser overlays now update properly again
/:cl:

2022-07-14 08:21 UTC, MusselMain commented
Many thanks, these always sucked to work with as a MP, and were more complicated, gud change.

2022-07-23 19:31 UTC, Shad0vvs commented on code/modules/projectiles/guns/energy.dm
> +		if(skilllock && !skillcheck(user, SKILL_POLICE, SKILL_POLICE_SKILLED))
```suggestion
		if(skilllock && !skillcheck(user, SKILL_POLICE, skilllock))
```

2022-07-23 19:32 UTC, Shad0vvs requested changes
Synthflash uses normal flash animation so it transforms in your hand, otherwise good to go.

2022-07-23 20:00 UTC, Shad0vvs approved these changes

2022-07-23 20:06 UTC, merged