Minimap/orbit icons resprite and remake
cmss13-devs/cmss13 pull request #6791
Opened 2024-07-25 23:55 UTC by Blundir

# About the pull request

Visually redoes how minimap and orbit icons look.

The ones that were redone look like this (old ones on the right, new ones on the left)

<details>
![image](https://github.com/user-attachments/assets/e3b3e0d3-6f9c-4eee-8347-d8ef7c3747d4)
</details>

Adds support and new icons for all factions that have special huds, adds yautja unique icons.

All sprites by me.

# Explain why it's good for the game

Current icons are very hard to tell apart, especially orbit icons, some colors are extremely off, orbit icons do not utilize backgrounds at all (it's just plain color fill), also some things there aren't working correctly at all, resulting in many icons being gray mess (shipside)

Here is an example of current icons:
<details>

![image](https://github.com/user-attachments/assets/0e7d6201-249b-494f-9fbb-62af9256c03d)

![image](https://github.com/user-attachments/assets/136ad322-0963-4ab4-a1fe-923af3520c1d)

![hTH7SC46jJ](https://github.com/user-attachments/assets/9155f6a2-c9ea-42a6-b5b2-2d152a717637)

![U3hYykHC7u](https://github.com/user-attachments/assets/b569c4fe-f11b-48f4-bb3d-bcfc228e7659)

</details>

I overhaul them to looks something like this

<details>

![chrome_4IcDecN80W](https://github.com/user-attachments/assets/7254271c-6a25-41f2-adb7-206c4e4ee2cc)

![image](https://github.com/user-attachments/assets/92bc8efc-aefa-47d5-8e89-6d46dcbf684f)

![image](https://github.com/user-attachments/assets/d37b7787-552e-4e3d-80a1-a2b506c59a08)

![PYlGchbRLX](https://github.com/user-attachments/assets/b8ac13cf-5f04-4520-86e7-1cab59e862bb)

</details>

# Testing Photographs and Procedure

<details>

![3SCyS7VqhF](https://github.com/user-attachments/assets/19a01ae6-2ea8-4150-ab68-42edf4749221)

![vNWh6gJtUV](https://github.com/user-attachments/assets/3a017ff8-db07-442d-95e1-9239bdac85d9)

![gXkkL9QxGG](https://github.com/user-attachments/assets/1dd2dd87-da26-4002-80af-e22d7a6d9487)

![dreammaker_2SkTzjlmAW](https://github.com/user-attachments/assets/35ec94c1-873d-4196-ae49-f6aa8c0a69de)

![dreammaker_zmQ9lWMm3B](https://github.com/user-attachments/assets/f4713d72-94c1-4e39-b4db-ff9d159d8286)

</details>

# Changelog

:cl:
add: minimap icons for all factions, roles, etc
code: tweaked how icons are assembled, added support for custom icon background on equipment preset
mapadd: added a new map or section to a map
/:cl:

2024-07-30 19:21 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-10-27 07:07 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-10-27 22:06 UTC, harryob requested changes
for the typescript error

2024-10-27 22:06 UTC, harryob commented on tgui/packages/tgui/interfaces/Orbit/index.tsx
>    if (!icon || !icons[icon]) {
```suggestion
  if (!icon || !icons[icon] || !background_icon || !icons[background_icon]) {
```

2024-10-27 22:29 UTC, harryob approved these changes

2024-10-27 22:34 UTC, merged