Resprite of old guns
cmss13-devs/cmss13 pull request #6804
Opened 2024-07-26 17:49 UTC by Blundir

# About the pull request

Resprites PPSh, M60, MAC-15, Basira bolt action rifle, S&W revolver

Resprites PPSh and M60 mags

Gives S&W revolver actual in hand sprites and belt icon (it had literally none)

Resprites inhands sprites of guns above except mac15, they are the same.

# Explain why it's good for the game

Ancient sprites bad, missing icons bad.

Before:
![dreamseeker_kQ1mLJNs5n](https://github.com/user-attachments/assets/3d591df7-6727-4b43-82a5-549dbba6546d)

After:
![dreamseeker_cBcoztKNf3](https://github.com/user-attachments/assets/ec087c12-5e4b-4067-9127-d400827bcbd4)

# Changelog

:cl:
fix: s&w revolver now had belt/pouch and inhand icons
imageadd: resprite of mac15, m60, ppsh, s&w revolver, basira bolt action rifle
/:cl:

2024-07-27 02:33 UTC, efzapa commented
wood on the rifle is too shiny but thats just me, could make it look like the PPSh

2024-08-03 06:59 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-08-04 13:02 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-08-06 22:52 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-08-13 06:50 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-08-21 01:24 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-08-21 01:52 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-08-21 12:07 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-08-21 12:31 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-08-22 16:20 UTC, harryob requested changes

2024-08-22 16:20 UTC, harryob commented on code/modules/projectiles/gun_attachables.dm
> +	..()
despite this file being full of them, these new overrides are pointless, delete it

2024-08-22 16:20 UTC, harryob commented on code/modules/projectiles/gun_attachables.dm
> +	..()
ditto

2024-08-23 12:56 UTC, harryob approved these changes
i have eyes to see and those look nicer

2024-08-23 13:19 UTC, merged