adds distinct color to CLF and UPP special channels
cmss13-devs/cmss13 pull request #6818
Opened 2024-07-29 22:10 UTC by CapCamIII

# About the pull request

Gives the unique CLF and UPP department channels unique colors.

# Explain why it's good for the game

This will hopefully incentivize the use of these special channels by making them distinct and harder to tune out compared to the previous system of them being the exact same color.

# Testing Photographs and Procedure

![image](https://github.com/user-attachments/assets/044732ce-5606-4f13-b8b6-8a6f6aec8940)

# Changelog

:cl:
add: UPP and CLF department channels now have distinct chat colors
/:cl:

2024-07-30 20:31 UTC, realforest2001 approved these changes

2024-07-31 14:19 UTC, harryob approved these changes

2024-08-01 05:24 UTC, Drulikar requested changes
Otherwise looks fine

2024-08-01 05:24 UTC, Drulikar commented on code/controllers/subsystem/communications.dm
> +		"[CLF_FREQ]" = "clfradio",
This is duplicated on line 275

2024-08-01 20:02 UTC, Drulikar approved these changes

2024-08-01 20:11 UTC, merged