Pred sound tweaks
cmss13-devs/cmss13 pull request #682
Opened 2022-07-15 08:35 UTC by Joelampost

## About The Pull Request
Adds more predator pain screams and tweaked the roar2 emote to sound closer to its intended sound.

## Why It's Good For The Game
Having only two pain screams for preds is terrible for your ears so I added more variety. 

## Changelog

:cl: Joe Lampost

soundadd: added three new pain screams for preds, tweaked roar2.
:cl:

2022-07-15 10:43 UTC, stanalbatross requested changes

2022-07-15 10:43 UTC, stanalbatross commented on code/game/sound.dm
> +				S = pick('sound/voice/pred_pain1.ogg','sound/voice/pred_pain2.ogg','sound/voice/pred_pain3.ogg','sound/voice/pred_pain4.ogg','sound/voice/pred_pain_rare1.ogg')
you need to use weights in this pick() like the male_pain pick() to make the rare pain actually rare

2022-07-15 14:04 UTC, stanalbatross approved these changes
code approved, sound needs approval tho

2022-07-23 11:07 UTC, stanalbatross requested changes
do changes to predpain4 i told you about in the disc

2022-07-26 23:12 UTC, closed without merging

2022-07-26 23:18 UTC, Joelampost commented
I messed up the re-basing and as these changes are not urgent I decided to just close this PR.