Shrapnel smooth movement
cmss13-devs/cmss13 pull request #6821
Opened 2024-07-30 04:41 UTC by Doubleumc

# About the pull request

Shrapnel movement is now smoothed by an `animate()`.

This is a follow on from https://github.com/cmss13-devs/cmss13/pull/4986 , attempting to resolve the performance issue that forced shrapnel to be excluded: https://github.com/cmss13-devs/cmss13/pull/4986#issuecomment-1827089416

Reduced appearance churn by using a `mutable_appearance` for intermediate changes. Doesn't animate `alpha` when not necessary.

# Explain why it's good for the game

Smoother apparent movement for shrapnel gives a more appealing look.

# Testing Photographs and Procedure

Works without issue on my local machine. Unable to test at appropriate scale. One TM and one cluster OB should give a definitive answer.

# Changelog

:cl:
code: shrapnel smoothly animates their movement
/:cl:

2024-08-01 13:22 UTC, Drulikar approved these changes
fps for me seems approximately the same. Self cpu of animate_flight does increase by .24 (or  0.0000064205232035814 per call) but *shrug*

2024-08-01 19:19 UTC, Doubleumc commented
I don't think local testing can determine anything beyond "this does/doesn't horrifically break something". The issue with shrapnel only showed up during a cluster OB when there were 100+ people on the server. The best I can figure is it had something to do with the amount of appearance data being sent out so that's what I focused on reducing. Don't have any tools that can test that, though.

2024-08-03 00:48 UTC, Doubleumc commented
Looks like the same outcome as the last time it was tried: cluster OBs cause the projectile system to chug.
![image](https://github.com/user-attachments/assets/97829bf0-0b14-48bd-83e7-92bad53ac8c6)
![image](https://github.com/user-attachments/assets/80d03b64-fa5c-49af-9e22-6b5c116c8642)
Unfortunate, but was worth a shot.

2024-08-03 01:14 UTC, Drulikar commented
Feel free to close if you aren't happy with the result or don't see any way to salvage it.

2024-08-04 08:57 UTC, Drulikar requested changes
This drastically reduces the damage delt by a cluster and just visually doesn't really have much happening at all.

2024-08-04 19:47 UTC, Doubleumc commented
Apparently I didn't actually submit my initial comment update, fixed now.

> This drastically reduces the damage delt by a cluster and just visually doesn't really have much happening at all.

I'm not sure what you mean by drastically reducing damage. The only shrapnel being replaced is this and its subtypes:
https://github.com/cmss13-devs/cmss13/blob/6a72a9851ab3e0aa3a6502c94c5e5833ab77328f/code/datums/ammo/shrapnel.dm#L125-L128
Each cluster OB explosion is 350 damage. It can generate up to 18 shrapnel of this kind, for at most 18 damage if it all hits something and isn't immediately absorbed by armor.

I'm not sure what you mean by not much happening visually. The exact same amount of shrapnel is generated, spreading out in approximately the same way, travelling approximately the same distance. The only thing you'd miss is a shrapnel hitting something and it popping up a hit marker.
Cluster OB on master:
![image](https://github.com/user-attachments/assets/dfd5ccdb-7d21-4fce-8c46-dcabad8bdc1f)
Cluster OB on particles experiment:
![image](https://github.com/user-attachments/assets/f5723ea1-ecd3-4316-be82-eed011171c59)

2024-08-05 06:21 UTC, Drulikar approved these changes
Code looks fine, and seems to test and look fine. But will be on TM for people to get a feel for whether its too costly for client fps over the old.

2024-08-07 20:40 UTC, merged