Xeno-based Hellhound
cmss13-devs/cmss13 pull request #684
Opened 2022-07-15 17:54 UTC by Geevies

## About The Pull Request

Refactors hellhounds to be based on xeno code. They share many similarities with runners and warriors now. They also regenerate health while standing, but get it much faster while resting. They do not need weeds to heal.

## Why It's Good For The Game

It's neat.

## Changelog

:cl:
refactor: Hellhounds are now based on xeno code, making them far less terrible to play as.
add: Forsaken and Yautja hives now never delay round end, Corrupted don't count as hostile xenos as long as they're allied to marines, as far as round-end is concerned.
/:cl:

2022-07-18 18:43 UTC, Agameofscones approved these changes
[Lester]: Looks like you mashed some poor feller's dog, Corporal.

[Vehicle Crewman]: That ain't no dog. It's a Hellhound, Lester. They shouldn't be out this far unless... oh shit.

Sprites approved.

2022-08-05 20:57 UTC, stanalbatross requested changes

2022-08-05 20:57 UTC, stanalbatross commented on code/modules/cm_preds/yaut_items.dm
> +	for(var/mob/living/carbon/Xenomorph/Hellhound/H as anything in GLOB.hellhound_list)
more specific var name

2022-08-05 20:57 UTC, stanalbatross commented on code/modules/mob/dead/observer/observer.dm
> +	var/mob/M = src
var name again

2022-08-05 20:57 UTC, stanalbatross commented on code/modules/mob/living/carbon/xenomorph/castes/Hellhound.dm
> +			snift \
```suggestion
			sniff \
```

2022-08-05 21:07 UTC, merged