Supply vendors tweaks and fixes
cmss13-devs/cmss13 pull request #685
Opened 2022-07-15 18:26 UTC by JeserTheFox

## About The Pull Request

1. Fixed not being able to restock shotgun ammo boxes in APC and Req vendors.
2. Made possible restocking marine armors in uniform vendors.
3. Minor tweaks of content in Dropship Pilot, Dropship Crew Chief, Vehicle Crewman and Squad Specialist vendors.
4. Vendors intended to be indestructible are actually indestructible now.
5. It is possible to restock "/empty" ammo boxes now. (The handmade from cardboard ones).
6. Req vendor can restock flamer fueltanks now.

## Why It's Good For The Game

Fixes, a bit more loadout options, slight QoL of supply staff.

## Changelog

:cl: Jeser
add: Minor content tweaks in Dropship Pilot, Dropship Crew Chief, Vehicle Crewman and Squad Specialist vendors.
add: APC Supply and Requisitions Ammunition vendors support restocking with handmade ammo boxes. (The ones made out of cardboard). Same requirements as for regular ammo boxes apply.
add: Requisitions Ammunition vendor supports restocking flamer fueltanks now.
add: Uniform vendors now support restocking armor in them.
fix: Fixed not being able to restock shotgun shells boxes in APC Supply and Requisitions Ammunition vendors.
/:cl:

2022-07-15 19:24 UTC, sose96 commented
What are the dcc/pilot tweaks?

2022-07-26 08:29 UTC, stanalbatross requested changes

2022-07-26 08:29 UTC, stanalbatross commented on code/modules/vehicles/interior/interactable/vendors.dm
> +						to_chat(user, SPAN_WARNING("\The [FT] contains not standard fuel."))
```suggestion
						to_chat(user, SPAN_WARNING("\The [FT] contains non-standard fuel."))
```

2022-07-26 08:29 UTC, stanalbatross commented on code/modules/vehicles/interior/interactable/vendors.dm
> +						to_chat(user, SPAN_WARNING("[A] isn't full. Fill it before you can restock it."))
```suggestion
						to_chat(user, SPAN_WARNING("\The [A] isn't full. Fill it before you can restock it."))
```

2022-07-26 08:29 UTC, stanalbatross commented on code/modules/vehicles/interior/interactable/vendors.dm
> +					to_chat(user, SPAN_WARNING("[A] is not full."))
```suggestion
					to_chat(user, SPAN_WARNING("[\The A] isn't full."))
```

2022-07-26 08:29 UTC, stanalbatross commented on code/modules/vehicles/interior/interactable/vendors.dm
> +							to_chat(user, SPAN_WARNING("Not all magazines in [A] are full."))
```suggestion
							to_chat(user, SPAN_WARNING("Not all magazines in \the [A] are full."))
```

2022-07-26 08:29 UTC, stanalbatross commented on code/modules/vehicles/interior/interactable/vendors.dm
> +					to_chat(user, SPAN_WARNING("[A] is not full."))
```suggestion
					to_chat(user, SPAN_WARNING("\The [A] isn't full."))
```

2022-07-26 08:29 UTC, stanalbatross commented on code/modules/vehicles/interior/interactable/vendors.dm
> +					to_chat(user, SPAN_WARNING("[item_to_stock] is not full."))
```suggestion
					to_chat(user, SPAN_WARNING("\The [item_to_stock] is not full."))
```

2022-07-26 08:29 UTC, stanalbatross commented on code/modules/vehicles/interior/interactable/vendors.dm
> +				var/obj/item/weapon/melee/claymore/mercsword/machete/Mac = locate(/obj/item/weapon/melee/claymore/mercsword/machete) in item_to_stock
```suggestion
				var/obj/item/weapon/melee/claymore/mercsword/machete/mac = locate(/obj/item/weapon/melee/claymore/mercsword/machete) in item_to_stock
```
snake_case to be used

2022-07-26 08:29 UTC, stanalbatross commented on code/modules/projectiles/ammunition.dm
> +					to_chat(user, SPAN_WARNING("[W] is not full."))
```suggestion
					to_chat(user, SPAN_WARNING("\The [W] is not full."))
```

2022-07-26 08:29 UTC, stanalbatross commented on code/game/machinery/vending/vendor_types/requisitions.dm
> +			SPAN_NOTICE("You stock [src] with \a [R[1]]."))
```suggestion
			user.visible_message(SPAN_NOTICE("[user] stocks \the [src] with \a [R[1]]."),
			SPAN_NOTICE("You stock \the [src] with \a [R[1]]."))
```

2022-07-26 08:29 UTC, stanalbatross commented on code/game/machinery/vending/vendor_types/requisitions.dm
> +							to_chat(user, SPAN_WARNING("Not all magazines in [A] are full."))
```suggestion
							to_chat(user, SPAN_WARNING("Not all magazines in \the [A] are full."))
```

2022-07-26 08:29 UTC, stanalbatross commented on code/game/machinery/vending/vendor_types/requisitions.dm
> +						to_chat(user, SPAN_WARNING("[A] isn't full. Fill it before you can restock it."))
```suggestion
						to_chat(user, SPAN_WARNING("\The [A] isn't full. You need to fill it before you can restock it."))
```

2022-07-26 08:29 UTC, stanalbatross commented on code/game/machinery/vending/vendor_types/requisitions.dm
> +						to_chat(user, SPAN_WARNING("\The [FT] contains not standard fuel."))
```suggestion
						to_chat(user, SPAN_WARNING("\The [FT] contains non-standard fuel."))
```

2022-07-26 08:29 UTC, stanalbatross commented on code/game/machinery/vending/vendor_types/requisitions.dm
> +					to_chat(user, SPAN_WARNING("[item_to_stock] is not full."))
```suggestion
					to_chat(user, SPAN_WARNING("\The [item_to_stock] is not full."))
```

2022-07-26 08:29 UTC, stanalbatross commented on code/game/machinery/vending/vendor_types/requisitions.dm
> +					to_chat(user, SPAN_WARNING("[B] is being stored in [SPAN_HELPFUL("stacks of 3")] for convenience. Add to \the [B] stack to make it a stack of 3 before restocking."))
```suggestion
					to_chat(user, SPAN_WARNING("[B]s are being stored in [SPAN_HELPFUL("stacks of 3")] for convenience. Add to \the [B] stack to make it a stack of 3 before restocking."))
```

2022-07-26 08:29 UTC, stanalbatross commented on code/game/machinery/vending/vendor_types/requisitions.dm
> +						to_chat(user, SPAN_WARNING("\The [FT] contains not standard fuel."))
```suggestion
						to_chat(user, SPAN_WARNING("\The [FT] contains non-standard fuel."))
```
there MUST be a better way to handle this than repeating the same code three times

possibly a can_restock proc on the item that returns true or false?

2022-07-30 12:44 UTC, stanalbatross approved these changes

2022-07-30 12:47 UTC, merged