Fixes flashlight medical use being broken
cmss13-devs/cmss13 pull request #6865
Opened 2024-08-03 10:59 UTC by VileBeggar

# About the pull request

makes it so you can check eyes with flashlights instead of being told that "You don't have the dexterity for this."
fixes #6769
fixes #5353 

# Explain why it's good for the game

bug fix!

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

https://github.com/user-attachments/assets/97bd2147-ce75-4800-a6d5-17f59c918a65

</details>

# Changelog

:cl:
fix: You can use flashlights to check if mobs are dead once again
/:cl:

2024-08-05 16:39 UTC, kiVts requested changes

2024-08-05 16:39 UTC, kiVts commented on code/game/objects/items/devices/flashlight.dm
> +		if((!(ishuman(user) || SSticker) && SSticker.mode.name != "monkey"))
```suggestion
		if(!(ishuman(user) || SSticker) && SSticker.mode.name != "monkey")
```

2024-08-05 22:41 UTC, kiVts commented
this is also covered by the #6691

2024-08-06 08:58 UTC, VileBeggar commented
huh, if that's the case then i don't see a reason for this to be up. cheers

2024-08-06 08:58 UTC, closed without merging