Adds giant lizards to LV-624
cmss13-devs/cmss13 pull request #6882
Opened 2024-08-05 18:34 UTC by VileBeggar

# About the pull request

### **SPRITES DONE BY @SubjectD9341 (GODBLESS THEIR SOUL!!!!)**

still not done 100% but it's almost there. made as a draft PR so i can push myself to finish it
adds giant lizards to LV624, which are slightly more sophisticated simplemobs with a couple of neat features:

### 1. Taming
<details>

<summary>Taming Summary</summary>

the lizards by default will not seek to harm you, UNLESS you intrude in their personal space. they will let you know when you get to close, either by growling or attacking you if you get too close.

BUT, there is a way to bypass this. by offering specific food (any type of butchered meat, xeno fruit or any snack in your MRE), they'll calm down and become friendly to you and YOUR ENTIRE FACTION.

https://github.com/user-attachments/assets/ed46c1e2-639d-4eec-bc7a-22b502fd5d7c

if tame, they will completely refuse to engage in combat with you and your faction. at most they will run away from you if you hurt them badly enough. why? it's because ~~i'm a bit lazy to code in a better system right now~~ they love you, and are unable to process the thought of betrayal! :D

this works for ALL FACTIONS, including xenos. the only food that xenos are able to offer it are resin fruits on account of them not being to pick up anything else.

if you try taking away its food (and you're not its friend) though it'll get pissed the fuck off and proceed to immediately maul you

https://github.com/user-attachments/assets/3ff69173-c1c1-47bf-8857-c2179301c268

</details>

### 2. Combat
<details>
<summary>Combat Summary</summary>
the lizards have slightly better combat AI than most simplemobs. they will try to skirmish against their opponent. every time they hit someone, there's a chance they'll try to move outside of their vision before engaging again. in addition, they will keep trying to pounce at their target in order to tear their throats out. they are not a big threat to anyone with a rifle, as you can easily mow them down

https://github.com/user-attachments/assets/1d011aa1-d06b-4a1a-9920-13325f75bff8

unlike other simple mobs, **THEY WILL NOT STOP HURTING YOU UNTIL YOU STOP BREATHING.** regular simple mobs will stop  attacking mobs that are not conscious, but these guys will rip you apart if you're on the ground.

https://github.com/user-attachments/assets/62bb559d-3765-4dde-a0c2-d815e10ea87c

if they take too much damage, they will start retreating from combat entirely, refusing to stop moving until there are no hostiles present in their view.

combined, this makes them a mild threat alone, and a slightly more terrifying threat when in packs. however, they're not much of a threat to the "perfect lifeform", outside of the short stun that a pounce can inflict. it will be hard to kill them, though, as they're much faster than most xenos.

https://github.com/user-attachments/assets/de331d1d-a215-44c0-b33d-e70e5452d30d

</details>

### 3. Misc
<details>
<summary>Misc Summary</summary>

this is where i list some neat features n tidbits that aren't really that big in themselves:

- unlike literally every other simplemob these guys can be set on fire and will actually take damage from it
- petting it while its friendly to you will make it want to lay down and sleep
- every lizard has an aggression value which gets higher whenever it takes damage. if you anger them and they start combat, and do your best at not harming them, they'll calm down and go back to minding their own business
- they heal 5% of their hp per Life() tick if they're resting. this is their main way of healing, but you can use bandages to heal them up yourself if you feel like it
- if there's a friendly mob on their tile and they're resting, they'll refuse to get up (they enjoy the warmth, i suppose)
- this is all simplemob code and is prone to exploding 50% of the time
- it can be allied to HUMANS and XENOS at the same time. additionally, it handles human factions and not humans as a whole. if survivors feed a lizard, it does not mean it'll be friendly to marines.
- they will NEVER attack monkeys in order to stop them from devastating small host populations
- more to come...

</details>

# Explain why it's good for the game

adds a bit of life to a jungle planet that's supposedly supposed to be filled with life, alongside making for some unique interactions for both marines and xenos. 

# Testing Photographs and Procedure
they're kinda all in the summary. it's still simplemob code and is by proxy extremely unstable and buggy but i have tried to remove most of the bugs (and i do have to say i've succeeded)

</details>

# Changelog

:cl: VileBeggar, SubjectD9341  
add: LV-624 now contains giant lizards. You can feed them with specific food items in order to make them non-hostile to your faction.
code: Simple mobs can now process fire, though the functionality is turned off by default.
/:cl:

2024-08-05 18:49 UTC, Skatuk commented
So when can I ride them as a horse update coming out so I can outrun the xeno's?

2024-08-06 02:53 UTC, TheManWithNoHands commented
Will the big jamaican menace come follow his small pack?
Great jagras when.

2024-08-08 13:50 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-08-09 17:06 UTC, RoboticVodka commented
If I might raise the concern the sprites are a direct reference to Jagras from Monster Hunter. 
![MHRise-Jagras_Render_001](https://github.com/user-attachments/assets/e70ae163-66f6-4c5b-8e32-ca86a2885f12)

2024-08-09 17:11 UTC, Nanu308 commented
Yo monsterhunter in CM, chat is this real?

2024-08-22 16:24 UTC, Blundir approved these changes

2024-08-22 16:37 UTC, harryob requested changes

2024-08-22 16:37 UTC, harryob commented on code/_onclick/item_attack.dm
> +					M.handle_blood_splatter(get_dir(user.loc, M.loc))
typically blood stuff is done in /mob/type/apply_damage(), does this need to be here?

2024-08-22 16:37 UTC, harryob commented on code/modules/mob/living/living_health_procs.dm
> +		health = maxHealth
i know we do this earlier in the proc, but typechecking src is kinda always wrong. can you override rejuvenate() for /mob/living/simple_animal and just set health = maxHealth before calling parent?

2024-08-22 16:37 UTC, harryob commented on code/modules/mob/living/simple_animal/hostile/retaliate/giant_lizard.dm
> +	SL = new /image('icons/mob/hud/hud.dmi', "slept_icon_centered")
```suggestion
	var/image/sleeping_icon = new /image('icons/mob/hud/hud.dmi', "slept_icon_centered")
```

2024-08-22 16:37 UTC, harryob commented on code/modules/mob/living/simple_animal/hostile/retaliate/giant_lizard.dm
> +	sleep_overlay = SL
```suggestion
	sleeping_icon.pixel_x = 20
	if(sleep_overlay)
		return
	sleep_overlay = sleeping_icon
```

2024-08-22 16:37 UTC, harryob commented on code/modules/mob/living/simple_animal/hostile/retaliate/giant_lizard.dm
> +	if(!is_retreating && on_fire && !client)
```suggestion
	if(is_retreating || !on_fire || client)
		return
```

2024-08-22 16:37 UTC, harryob commented on code/modules/mob/living/simple_animal/hostile/retaliate/giant_lizard.dm
> +		COOLDOWN_START(src, calm_cooldown, 8 SECONDS)
```suggestion

	//forget EVERYTHING. we need to stop the flames!!!
	stance = HOSTILE_STANCE_ALERT
	target_mob = null
	food_target = null
	is_eating = FALSE
	manual_emote("hisses in agony!")
	playsound(src, "giant_lizard_hiss", 40)
	MoveTo(null, 9, TRUE, 4 SECONDS, FALSE)
	COOLDOWN_START(src, calm_cooldown, 8 SECONDS)
```

2024-08-22 16:37 UTC, harryob commented on code/modules/mob/living/simple_animal/hostile/retaliate/giant_lizard.dm
> +	if(aggression_value > 0) aggression_value--
```suggestion
	if(aggression_value > 0) 
		aggression_value--
```

2024-08-22 16:37 UTC, harryob commented on code/modules/mob/living/simple_animal/hostile/retaliate/giant_lizard.dm
> +	if(!client)
invert this to reduce nesting

2024-08-22 16:37 UTC, harryob commented on code/modules/mob/living/simple_animal/hostile/retaliate/giant_lizard.dm
> +		return TRUE
```suggestion
	if(!ismob(food.loc))
		return

	var/mob/living/food_holder = food.loc
	stop_moving()
	COOLDOWN_START(src, food_cooldown, 15 SECONDS)
	food_target = null
	is_eating = FALSE
	//snagging the food while you're right next to the mob makes it very angry
	if(get_dist(src, food_holder) <= 2 && !(food_holder.faction in faction_group))
		Retaliate()
		return TRUE

	growl(food.loc)
	stance = HOSTILE_STANCE_IDLE
	return TRUE
```

2024-08-22 16:37 UTC, harryob commented on code/modules/mob/living/simple_animal/hostile/retaliate/giant_lizard.dm
> +	if(!enemies.len)
```suggestion
	if(!length(enemies))
```

2024-08-22 16:37 UTC, harryob commented on code/modules/mob/living/simple_animal/hostile/retaliate/giant_lizard.dm
> +	else if(target.stat != DEAD)
```suggestion
	if(target in friends)
		return FALSE
	if(target.stat != DEAD)
```
else is redundant because the previous condition returns

2024-08-22 16:37 UTC, harryob commented on code/modules/mob/living/simple_animal/simple_animal.dm
> +	//LETTING SIMPLE ANIMALS ATTACK? WHAT COULD GO WRONG. Defaults to zero so Ian can still be cuddly
codedocs go before the comment, https://github.com/cmss13-devs/cmss13/blob/master/.github/guides/AUTODOC.md

2024-08-23 14:13 UTC, VileBeggar commented on code/modules/mob/living/simple_animal/hostile/retaliate/giant_lizard.dm
> +	stop_automated_movement = 1
10+ year old code

2024-08-24 09:50 UTC, harryob approved these changes

2024-08-24 09:56 UTC, merged