Gives researchers access to the Kitchen
cmss13-devs/cmss13 pull request #6883
Opened 2024-08-05 20:22 UTC by doganesi

# About the pull request

Gives researchers access to the Kitchen

# Explain why it's good for the game

There's not always someone with Kitchen access nearby or a Mess Tech awake when you need to grab something like universal enzyme for a research chem. And if there is someone with access on the ship, it's like pulling teeth to try to get them to open the door for you. This makes it so researchers no longer have to stand around like sad puppies in front of the kitchen waiting for someone to walk by.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl: Asmocard
qol: Gave researchers access to Almayer kitchen
/:cl:

2024-08-05 20:26 UTC, kiVts commented
you're better off adding the items you take/need from kitchen either in research or somewhere across the ship, research having access to kitchen isnt really fitting, but if you insist

2024-08-05 20:31 UTC, doganesi commented
> you're better off adding the items you take/need from kitchen either in research or somewhere across the ship, 
I thought about it, maybe, you usually don't need all that much of enzyme or pepper or whatever else you might need
> research having access to kitchen isnt really fitting, but if you insist
I guess, but then I'd also say DCC getting kitchen access also doesnt make much sense

2024-08-06 02:03 UTC, TheManWithNoHands commented
> I guess, but then I'd also say DCC getting kitchen access also doesnt make much sense

They what? Why is that a thing.

2024-08-22 16:04 UTC, harryob requested changes
i'm not really interested in this, and i don't think it's a great approach to logistics issues. it is also weird that DCCs would have access here. add alternate routes to getting enzyme

2024-10-05 21:14 UTC, efzapa commented
peppercorn plant that you can grind is one idea

as for enzyme I am sure you can somehow tie that into chem shenanigans

2024-10-06 05:04 UTC, harryob commented
stale, closing. feel free to make a new pr which addresses requested changes

2024-10-06 05:04 UTC, closed without merging