improvements to research datum
cmss13-devs/cmss13 pull request #6885
Opened 2024-08-05 22:35 UTC by kiVts

# About the pull request
Ever since the init argument pr I had common sense take over, so we are now here. This makes it *much* easier to add technology that doesnt spawn something. eg techtree upgrades while also stopping the init var nonsense, THIS is how it should have been.

Merge after anti caustic armor so I can adapt it easily

# Explain why it's good for the game

If someone adds upgrade that does something that requires non physical items, they can now.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
code: Research datum now supports more broad ideas in the future.
/:cl:

2024-08-22 16:15 UTC, harryob approved these changes

2024-08-22 16:16 UTC, harryob requested changes
actually, why not just have the default implementation new the held typepath, and just override it for the ones you give extra new() args to, so the autodoc ones?

2024-08-22 20:44 UTC, kiVts commented
Good catch

2024-08-23 09:15 UTC, harryob requested changes

2024-08-23 09:15 UTC, harryob commented on code/datums/research_upgrade_datum.dm
> +	return
```suggestion
```

2024-08-23 09:15 UTC, harryob approved these changes

2024-08-23 09:30 UTC, merged