Keycard authentication device now reqires two users to activate events
cmss13-devs/cmss13 pull request #6903
Opened 2024-08-08 23:47 UTC by cuberound

# About the pull request

it is  writen down that two are reqired to activate red and so on but one can swipe twice fast and it work. this fixes it

# Explain why it's good for the game

bugfix and has rp incentive to get second man to start redalert

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
fix: two persons are needed to activate red, ert and emergency acces using cards
/:cl:

2024-08-09 15:37 UTC, Ben10083 commented
Want to point out that in event of unable to get 2 users, you can go to ARES and call for redalert/evac/distress-signal

2024-08-12 02:24 UTC, Zonespace27 requested changes

2024-08-12 02:24 UTC, Zonespace27 commented on code/modules/security_levels/keycard_authentication.dm
> +						to_chat(usr, "Your ID is rejected, as it is the one that triggered the event!")
use a SPAN

2024-08-12 02:24 UTC, Zonespace27 commented on code/modules/security_levels/keycard_authentication.dm
> +						to_chat(usr, "Your ID is rejected, as it is the one that triggered the event!")
don't use usr

2024-08-16 19:38 UTC, harryob approved these changes

2024-08-16 19:51 UTC, merged