Mines Boom 2: non-electric booglaoo
cmss13-devs/cmss13 pull request #6906
Opened 2024-08-09 09:46 UTC by LynxSolstice

# About the pull request

This PR is a revival of the original PR here: (https://github.com/cmss13-devs/cmss13/pull/3615). 
It adds antitank mines as an alternative/additive to claymores that target larger xenos. As well as a framework for making more bury-able mines.

# Explain why it's good for the game

It offers a defensive/ambush utility to engineers that can be countered by xenos (dug up and acid'd) but that deters T3s.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

(https://youtube.com/shorts/xxPc8FdskgU?si=u1o5WEUvECt-D6ho)

</details>

# Changelog

:cl:LynxSolstice
add: Adds anti tank mines and the framework for creating more bury-able mine types.
balance: Adds M19 Antitank mines to the engineer vendor, the req vendor with a scale of (round * 2), adds the M19 antitank mine.
spellcheck: ((title suggested by Silencer_pl)) Added descriptions for the Antitank Mine.
code: Original code by Totalepicness5, maintenance of the code by LynxSolstice.
refactor: Mine code flesh out more. (Refactor by Totalepicness5)
imageadd: Adds a sprite for an unburied and a buried Antitank Mine (Sprites by Thwomper)
/:cl:

2024-08-09 18:08 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-08-09 22:38 UTC, TheManWithNoHands commented
Badass, although i suggest renaming them. They dont seem to cause much AP damage at all and mainly stun after all.
The name shouldnt confuse people what the mines do.

2024-08-10 01:23 UTC, LynxSolstice commented
> Badass, although i suggest renaming them. They dont seem to cause much AP damage at all and mainly stun after all. The name shouldnt confuse people what the mines do.

They do infact do a LOT of AP damage, just not so much against the big T3s, is all
(the claymore has 60 explosive power, the Antitank mine, 150)

2024-08-10 05:43 UTC, LynxSolstice commented
https://youtu.be/2ZByfXpnNok

2024-08-11 01:10 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-08-12 05:37 UTC, Blundir approved these changes

2024-08-22 14:33 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-08-27 02:39 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-10-06 05:50 UTC, harryob requested changes
address ci fail

2024-10-13 03:52 UTC, LynxSolstice commented
> address ci fail

Will work on addressing this.

2024-10-13 04:28 UTC, LynxSolstice commented
Passed CI

2024-12-10 17:26 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-12-17 09:58 UTC, LynxSolstice commented
Fixing conflicts

2025-01-30 15:29 UTC, harryob commented
fix conflicts

2025-02-19 01:08 UTC, closed without merging