UPP MMG | UPP Flag
cmss13-devs/cmss13 pull request #6915
Opened 2024-08-10 17:51 UTC by Steelpoint

# About the pull request

Adds in two features from this now auto-closed PR: https://github.com/cmss13-devs/cmss13/pull/5945

Adds the T37 MMG for the UPP, their alternative version to the USCM M2C. The T37 is a stationary weapon, meaning it can not be moved, it has a slower rate-of-fire but it can sustain firing for significantly longer before it will overheat. 

Adds a cosmetic UPP flag for mapping purposes. 

# Explain why it's good for the game

Useful features for mapping or events. 

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
add: Adds the T37 Medium Machine Gun to the UPP's arsenal. The T37 is an alternative variant of the M2C HMG, it is a stationary emplacement (that can not be redeployed) that has a slower rate of fire compared to the M2C, but it can fire for a far longer period of time before overheating. 
add: A UPP flag has been added for mappers. 
/:cl:

2024-08-10 18:07 UTC, Blundir requested changes
The gun and the ammo box is literally slight M2C tweak, find or make an actual sprite for both, we have special sprites for upp ammo boxes and special palette for upp guns.

2024-08-11 12:10 UTC, Steelpoint commented
Moving the UPP Map to a separate PR.

2024-08-12 22:01 UTC, Waseemq1235 commented
Just a heads-up: the MMG values I used in PR #5945 were tested but not extensively.

2024-08-13 08:43 UTC, Steelpoint commented
> Just a heads-up: the MMG values I used in PR #5945 were tested but not extensively.

We'll likely get some chances to see it in action if the PR gets merged so a future balance PR can be done if its excessive.

As it stands, it trades huge burst damage for sustained suppressing fire, plus the lack of being able to move the weapon, and the fact you'll only see these guns being placed by mappers and admins, not players, makes it easier to balance and less oppressive.

2024-08-14 16:11 UTC, Steelpoint commented
Love it, thank you.

2024-08-22 19:09 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-08-26 13:10 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-10-26 15:31 UTC, harryob requested changes

2024-10-26 15:31 UTC, harryob commented on code/modules/cm_marines/m2c.dm
> +	if(istype(O, /obj/item/ammo_magazine/m2c/t37))
are we overriding this whole proc just to change this line? ideally we would change the parent proc in /obj/structure/machinery/m56d_hmg/auto like:

```dm

if(istype(O, /obj/item/ammo_magazine)
	var/obj/item/ammo_magazine/magazine = O
	
	if(magazine.default_ammo != ammo)
		return
```

2024-10-26 15:31 UTC, harryob commented on code/modules/cm_marines/m2c.dm
> +	var/obj/item/ammo_magazine/m2c/t37/AM = new /obj/item/ammo_magazine/m2c/t37(src.loc)
```suggestion
	var/obj/item/ammo_magazine/m2c/t37/AM = new(loc)
```

2024-10-26 15:31 UTC, harryob commented on code/modules/cm_marines/m2c.dm
> +		..()
```suggestion
	return ..()
```
previous condition returns so you don't need the else

2024-11-29 13:12 UTC, Steelpoint commented
I'll fix this up (later).

2024-11-29 13:12 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-12-11 08:19 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-12-11 14:11 UTC, cuberound commented on code/modules/cm_marines/m2c.dm
> +        return
dd

2024-12-16 13:04 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-12-16 13:14 UTC, harryob approved these changes

2024-12-16 13:20 UTC, merged