SHARP Rifle Revived
cmss13-devs/cmss13 pull request #6938
Opened 2024-08-12 19:58 UTC by Nomoresolvalou

# About the pull request

This PR is a revival of PR https://github.com/cmss13-devs/cmss13/pull/2000

This PR adds in the P9 SHARP Rifle Operator as a subvariant of the Grenadier spec. specialists can choose either the Heavy Grenadier or the SHARP Operator spec sets, you cannot have both a GL and SHARP, in the same way you cannot have AMR and Sniper (excluding foxtrot spawns).

the SHARP is a magazine fed rifle, using three different dart types as ammunition
The first two dart types are explosive, and incendiary darts. These both work in similar ways. On hitting an enemy with either of these types of dart, the dart will embed inside them (dealing minor damage) and then, if the target does not have IFF, will explode after a short delay. This delay is either 1 second, or 5 seconds, which you can toggle by pressing the toggle firemode key. The key difference between the two darts, is that explosive will explode (no way), and incendiary will form a cloud of phosphorous smoke around the target, the same as a normal WP grenade.

However, if you have bad aim and miss your target, the darts will embed into the ground. after 5 seconds, the dart will arm itself and become a mine. Mines have IFF, and will last for 5 minutes before disarming and becoming inert. These mines upgrade every thirty seconds, with 4 levels in total.

The final dart type is flechette. these work differently from the other two dart types, as they cannot become mines. on hitting a tile, the dart will split into a number of flechette projectiles in front of it, similar to how AGM grenades function. sprite clicking an enemy with these is most optimal, as it ensures all the projectiles hit. Flechette darts also have a faster firing rate than that of the other two dart types.

# Explain why it's good for the game

I think the SHARP rifle adds a unique gameplay style to the game. Mines are a pretty overlooked weapon in the marine arsenal. the SHARP has a high skill ceiling, figuring out where and when to best place your mines, since they don't last forever. At the same time it has effective offensive capability, best paired with teammates to help capitalize on your SHARP hits. The SHARP is an effective sidegrade to the classic GL specialist.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

</details>

# Changelog

:cl: Nomoresolvalou, TheManWithNoHands, Triiodine, Shad0vvs
add: Added SHARP Operator spec, P9 SHARP rifle, and SHARP ammo belt
soundadd: Added SHARP gun sounds
imageadd: Added SHARP rifle and ammo sprites (by Triiodine and TheManWithNoHands)
:cl:

2024-08-12 19:59 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-08-12 20:27 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-08-14 12:42 UTC, Blundir requested changes
Overall sprites look fine, magazine colores might use a tweak, magazine positions, also the attachments offsets are off, explosion sound needs to be changed, elaborated in discord

2024-08-15 11:03 UTC, Blundir approved these changes

2024-08-17 07:40 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-08-17 07:59 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-08-17 15:08 UTC, Zonespace27 requested changes
https://github.com/cmss13-devs/cmss13/pull/6933

2024-08-21 11:58 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-08-22 15:03 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-08-22 16:11 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-08-22 19:09 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-08-22 21:31 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-08-23 13:36 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-08-23 14:41 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-08-24 10:46 UTC, harryob requested changes

2024-08-24 10:46 UTC, harryob commented on code/game/objects/items/explosives/mine.dm
> +	set waitfor = 0
```suggestion
	set waitfor = FALSE

```

2024-08-24 10:46 UTC, harryob commented on code/game/objects/items/explosives/mine.dm
> +		src.try_to_prime(mob)
```suggestion
		try_to_prime(mob)
```

2024-08-24 10:46 UTC, harryob commented on code/game/objects/items/explosives/mine.dm
> +	set waitfor = 0
```suggestion
	set waitfor = FALSE

```

2024-08-24 10:46 UTC, harryob commented on code/game/objects/items/explosives/mine.dm
> +		var/datum/effect_system/smoke_spread/phosphorus/smoke = new /datum/effect_system/smoke_spread/phosphorus
```suggestion
		var/datum/effect_system/smoke_spread/phosphorus/smoke = new()
```

2024-08-24 10:46 UTC, harryob commented on code/game/objects/items/shards.dm
> +	garbage = TRUE
```suggestion
	garbage = TRUE
	var/damage_on_move = 3
	var/count = 1
```

2024-08-24 10:46 UTC, harryob commented on code/modules/projectiles/guns/specialist/sharp.dm
> +	for(var/obj/item/ammo_magazine/handful/H in user.loc)
single letter var

2024-08-24 10:46 UTC, harryob commented on code/modules/projectiles/guns/specialist/sharp.dm
> +	var/mine_level = 0
new var declarations should go after overrides

2024-08-24 10:46 UTC, harryob commented on code/modules/projectiles/guns/specialist/sharp.dm
> +/datum/ammo/rifle/sharp/explosive/on_hit_mob(mob/living/M, obj/projectile/P)
single letter vars

2024-08-24 10:46 UTC, harryob commented on code/modules/projectiles/guns/specialist/sharp.dm
> +	if(!M || M == P.firer) return
```suggestion
	if(!M || M == P.firer) 
		return
```
no in line control statements

2024-08-24 10:46 UTC, harryob commented on code/modules/projectiles/guns/specialist/sharp.dm
> +/datum/ammo/rifle/sharp/explosive/drop_dart(loc, obj/projectile/P, mob/shooter)
single letter

2024-08-24 10:46 UTC, harryob commented on code/modules/projectiles/guns/specialist/sharp.dm
> +	if(!M || M == P.firer) return
no in line control statements

2024-08-24 10:46 UTC, harryob commented on code/modules/projectiles/guns/specialist/sharp.dm
> +/datum/ammo/rifle/sharp/incendiary/on_hit_mob(mob/living/M, obj/projectile/P)
single letter

2024-08-24 10:46 UTC, harryob commented on code/modules/projectiles/guns/specialist/sharp.dm
> +	if(ismob(M))
single letter var

2024-08-24 10:46 UTC, harryob commented on code/modules/projectiles/guns/specialist/sharp.dm
> +	if(!M || M == P.firer) return
in line control statements

2024-08-24 10:46 UTC, harryob commented on code/modules/projectiles/guns/specialist/sharp.dm
> +/datum/ammo/rifle/sharp/flechette/on_hit_mob(mob/living/M, obj/projectile/P)
single letter var

2024-08-24 10:46 UTC, harryob commented on code/modules/projectiles/guns/specialist/sharp.dm
> +	if(!M) return
in line control statements

2024-08-24 10:46 UTC, harryob commented on code/modules/projectiles/guns/specialist/sharp.dm
> +	var/obj/effect/overlay/O = new /obj/effect/overlay(loc)
single letter var

2024-09-13 01:57 UTC, kiVts commented on code/modules/projectiles/guns/specialist/sharp.dm
> +	user.balloon_alert(user, "[icon2html(src, user)] Explosive ammo will blow up in [explosion_delay_sharp ? SPAN_BOLD("five seconds") : SPAN_BOLD("one second")].")
```suggestion
	user.balloon_alert(user, "Explosive ammo will blow up in [explosion_delay_sharp ? SPAN_BOLD("five seconds") : SPAN_BOLD("one second")].")
```

2024-09-13 01:59 UTC, kiVts commented on code/modules/projectiles/guns/specialist/sharp.dm
> +	user.balloon_alert(user, "Explosive ammo will blow up in [explosion_delay_sharp ? SPAN_BOLD("five seconds") : SPAN_BOLD("one second")].")
```suggestion
	user.balloon_alert(user, "explosive ammo will blow up in [explosion_delay_sharp ? SPAN_BOLD("five seconds") : SPAN_BOLD("one second")].")
```
Woops

2024-09-20 15:24 UTC, chefoxara commented
bring the fire delay back to 1 sec, this shit cant stunlock unless the xeno ur shooting is really dumb tbh.

2024-09-20 15:44 UTC, Nomoresolvalou commented
I don’t really want to have it stunlock that easily. It is still incredibly easy to hit a xeno with at least two darts if you are pursuing them, which is enough to kill, which is why I upped the detonation time. It gives xenos a small time to react, which was a point of frustration before. Of course if they don’t then you can hit them with another dart and they die.

2024-09-20 18:45 UTC, NancokPS2 commented
> I don’t really want to have it stunlock that easily. It is still incredibly easy to hit a xeno with at least two darts if you are pursuing them, which is enough to kill, which is why I upped the detonation time. It gives xenos a small time to react, which was a point of frustration before. Of course if they don’t then you can hit them with another dart and they die.

I had heard of that change, and sorry if i'm missing something. But that doesn't really address the stunlock part, right?  
I mean, does the hit xeno have any options to deal with the dart at all? If not, what would increasing the detonation time change?  
  
If the xeno could resist to try and pull it out, or otherwise perform some action to avoid the strong stun, then sure. But it still means certain death with as little as one dart, or 2 if the spec is alone.

2024-09-20 19:15 UTC, chefoxara commented
> I don’t really want to have it stunlock that easily. It is still incredibly easy to hit a xeno with at least two darts if you are pursuing them, which is enough to kill, which is why I upped the detonation time. It gives xenos a small time to react, which was a point of frustration before. Of course if they don’t then you can hit them with another dart and they die.

im very good with aim and i cant chainstun most xenos since the grenade code sucks and they miss alot for no reason (I AM SPRITE CLICKING BY THE WAY) 
ive also never seen anyone else chainstun xenos while observing, personally i managed to stun a woyer 2 times on my own and then i had to pull out a shotgun to kill em, and that was cause they were stuck up against a comms tower and couldnt flee
so shrug
the stun aint that long anyways, they get up within a sec or so. unless it was buffed from the last time i played spec.

i wouldnt remove the stuns cause GL (sharp) is literally for that, and anyways specs are meant to be somewhat powerful and excel in fighting what they are meant to be fighting (in this case T1 and T2s)

2024-09-20 19:53 UTC, NancokPS2 commented
As long as the fire rate is similar to the stun time, stunlocking is pretty much guaranteed.  
  
Even if you had the time to move 1 tile before being hit again, you still have to keep in mind movement acceleration is a thing. It would take a pretty bad spec to miss a slowed down xeno that moved a single tile.
  
Scout has a similar gameplay loop, but their stuns are range based AND his gun deals way less damage. This is leagues better than that.

2024-09-20 21:07 UTC, chefoxara commented
> As long as the fire rate is similar to the stun time, stunlocking is pretty much guaranteed.

GL can stunlock too and no one had problems with that, just fire grenades infront of retreating T2-T1 xeno, it gets stunned, spam them+ marines shooting it = it dies
sharp is a bit more multifunctional than GL but then again you can just load batons into the GL launcher and chainstun xenos too, so???? last time i played normal GL i did that and killed a burrower and some runners???

> Even if you had the time to move 1 tile before being hit again, you still have to keep in mind movement acceleration is a thing. It would take a pretty bad spec to miss a slowed down xeno that moved a single tile.
  i cant seem to manage this, shooting a sent when there was a one sec detonation time, once it gets stunned, gets up, retreats, i hit it again, it gets up again, goes into the darkness and i cant chase cause im wearing GL armor, curious! my aim aint bad., hm!!

> Scout has a similar gameplay loop, but their stuns are range based AND his gun deals way less damage. This is leagues better than that. And unlike the scout, grenadier is encouraged to not go solo.
dunno how much the nades deal but a good scout can deal 170dmg per burst + setting the xeno (one incen round in the chamber) on fire with their normal ammo or 120 + stunning

> My main issue with the SHARP is that it is a ranged way to secure kills on T2s like the SADAR, but without any of the risks or ammo limitations. There's no counterplay other than not showing up where the spec may be. And unlike the SADAR, the spec doesn't have to call everyone to go away before firing, which would expose them and give you time to run.

sadar doesnt have to call everyone away most of the time, they just push their way thro most of the time or get a good position in a push, or rush in after a screech..  also the sharp spec FF sucks,, always breaks a bone (or so i was told) and gives you ultrashrap which you need to stand around for 10 secs or so to pull it out.
there are ammo limitations, but the ammo is cheap, so you rarely run into them yes..
there is a counterplay, its called T3s.

we can agree to disagree. ig

2024-09-20 21:15 UTC, Nomoresolvalou commented
At this point it is going to be incredibly difficult to make everyone happy with this weapon, which I believe to be the case with most additions. People already stand on two opposite sides of "useless gun" and "OP gun", and any changes I make will make one side reinforce their belief in that. What I hope to do is to keep both of these sides in mind, and based on my observations, make the gun as balanced as I can.

Currently from what I can tell, a large point of issue is that, from the xeno point of view, getting hit with an HEDP means you have a very high chance of dying. I attempted to address this by upping the lower det time to 2.5 seconds, to at least give the xenos a bit of a chance to run away, get behind cover, have teammates run to bodyblock for them, etc. With this in mind, a xeno stunned by the SHARP can have another HEDP implanted for basically free with the current fire rate. So as it currently stands, I am open to lowering the fire rate even more to prevent this, but as of now, I will leave this section of the gun unchanged until I get some further observations.

2024-09-20 21:18 UTC, chefoxara commented
> At this point it is going to be incredibly difficult to make everyone happy with this weapon, which I believe to be the case with most additions. People already stand on two opposite sides of "useless gun" and "OP gun", and any changes I make will make one side reinforce their belief in that. What I hope to do is to keep both of these sides in mind, and based on my observations, make the gun as balanced as I can.
i see alot of marines calling it a bad gun lel

2024-09-20 22:43 UTC, NancokPS2 commented
The reason why it is so polarizing is because it excels at a very annoying gameplay loop.  
It is bad for setting traps because getting a xeno at the exact time frame that the explosive is upgraded before it expires is dumb luck.  
It is bad for demolishing structures because worse explosive power (and afaik it doesn't detonate on structures (?))  
Its main strength is stun-locking. Avoiding the main role of this spec which is to spam AoE and flush out xenos from fortifications.  
  
So yeah, it is good precisely at the worst thing it could be good at.  
  
And no, the default GL is not the same, you can run from grenades if you're paying attention, you can't run away from a dart once fired. Avoiding the attack is on the spec's ability to aim, not on your ability to dodge.

2024-09-22 14:16 UTC, GoldenDarkness55 commented
Spot-the-pixel is absolutely godawful, claymores were already bad enough but the darts are even easier to obscure with random debris. Mines aside, the embedded darts are just an attempt at obscuring grenades, it's not visually clear as opposed to HEDPs. Ruins the visual clarity of the game and its mechanics.

The base idea of a gun that works on sprite hits isn't bad, but that encroaches on the AGM-F grenade niche, can't you just get rid of the new ammo system and make this use some kinda rebalanced AGMs instead? If it really has to explode maybe add one that delivers a weak explosion in a frontal cone?
Utterly cancerous to play against in current state and a plain bad feature.

2024-09-22 18:34 UTC, chefoxara commented
"but the darts are even easier to obscure with random debris."
why dont we move xeno traps above the object layer too then ? 🤔 

game is stun based, ofc its "cancer" when muhrines get the ability to stun you (meanwhile you can tackle spam everyone to death) 
🤷 
really dont wanna see this get nerfed into the ground over cope like the tank or some other shit

2024-09-24 22:46 UTC, NancokPS2 commented
> "but the darts are even easier to obscure with random debris." why dont we move xeno traps above the object layer too then ? 🤔
> 
> game is stun based, ofc its "cancer" when muhrines get the ability to stun you (meanwhile you can tackle spam everyone to death) 🤷 really dont wanna see this get nerfed into the ground over cope like the tank or some other shit
  
You cannot compare xeno stuns to marine stuns.  

Marines have several times the DPS per fighter than xenos do. As a result xenos need stuns to be able to survive. It is simply a requirement if marines are going to have that amount of stackable DPS.    
Additionally, each xeno is worth at least 3 marines. So yes, xenos should in average be able to kill at least 3 marines per life. So "equal terms" is actually unbalanced.
  
Unless you want xenos to kill marines in 3 slashes or so to keep parity with time to kill. I imagine you'd prefer that it stays as it is.

2024-09-25 19:19 UTC, chefoxara commented
> double current xeno numbers

would be fire

>You cannot compare xeno stuns to marine stuns.
i just did

> Specs are the only ones that should be able to threaten a T2 or higher in 1v1.
yea they are doing just that, threatening and sometimes killing T2-T3s 
GL is for clearing walls and killing T1s T2s, sharp is the same thing but instead of clearing he has area denial
:>

2024-09-26 13:06 UTC, HaultyAnonie commented
![image](https://github.com/user-attachments/assets/5b315c33-b6ca-4f69-ac53-0e9bd103cef6)

The `m` in `magazine` for the Flechette magazine is the only one capitalized and I don't know if that's on purpose. SPEC VENDOR.

2024-09-26 13:25 UTC, chefoxara commented
wanted to say that HE should be red and INC should be yellow, actually since incen sets things on blue fire why not make it blue.
pls

2024-09-26 15:41 UTC, Nomoresolvalou commented
> wanted to say that HE should be red and INC should be yellow
HE and incend are already red and yellow respectively, to reflect the colors of the grenades.

2024-09-26 20:48 UTC, chefoxara commented
> > wanted to say that HE should be red and INC should be yellow
> 
> HE and incend are already red and yellow respectively, to reflect the colors of the grenades.

i swear it used to be swapped around.. maybe im just imagining things lol.

2024-09-27 02:41 UTC, Nomoresolvalou commented
> i swear it used to be swapped around.. maybe im just imagining things lol.

no it was like that by accident
I fixed it a couple commits ago cause it peeved me

2024-09-27 12:07 UTC, chefoxara commented
> > i swear it used to be swapped around.. maybe im just imagining things lol.
> 
> no it was like that by accident I fixed it a couple commits ago cause it peeved me

aaah.
ok
thank you

2024-10-01 14:46 UTC, Red-byte3D commented
Completely ignoring every single person in this thread because they have no idea what they are talking about, why are you allowing embeds on xenos? This basically guarantees that as long as a sharp is in the screen you cannot punish the group of marines who are walking by. 

IF the xeno pushes, youre going to get a nade embedded in you which does damage and stuns you. The timer doesnt help because if you've already taken damage, the delayed damage means you're just going to die.

IF you cant push you cant punish marines.

Remember that the game is supposed to favor xenos because they are outnumbered and have to go in close to do anything in most cases, barring three castes and one strain. And go back in several times. This is the reason why specs such as sadar or sniper have some sort of a charge up or smoke to deter off immediate response to the stun / give the xenos a chance to react.

5 minutes is a long ass time that you are denying an area for, there is literally nothing else in the game that does this much damage / stun / area denial barring sentries, claymores and mines are easily counterable by the fact that in majority of the cases they are placed, there is nobody else around them. They're a put down and forget kind of deal where as this weapon is actively denying pushes, xenomorphs and areas WITH the full force of a few marine squads behind them.

Can you in any way justify a spec being this strong? There is not one other spec that is this powerful against literally every single caste in the game, barring maybe runners because you'd be wasting ammo trying to hit them, except it isnt a waste because a 5 minute timer implies it will eventually hit something.

Calling this a grenadier "side-grade" is absoloutetly lunatic too. Grenadier spec has WAY MORE LIMITED AMMO, compared to this, and every grenade you fire needs to be thought about, because if you miss its gone. When you're in the frontline, every sharp nade you put down doesnt miss untill 5 minutes pass. it has way too much ammo for what it can do.

Personally speaking this weapon should've never been re-introduced, we already just had a spec weapon added and marines are already getting too many stuff while nobody is balancing the xenomorph side, other then some guy who wants to nerf screech for some reason?

But heres some recommendations anyway;

1.) Too much ammo, nerf the amount gotten from req crates or absoloutetly high up the prices. The reason AOE stuns or stuns in general is hard to come by in marine side is because if a xeno gets stunned it will be %90 easier to kill. This is the reason why i nerfed scout getting 5 mags per crate, yes scout is powerful but there needs to be some sort of gamble for it to be able to be that powerful, that being you run out of mags faster but in return you're doing all that stunning to tier 1/2. As it stands, theres basically no gamble in this and youre always just winning.

2.) Remove embeds, its pretty disadvantaging to add that kind of damage / stun effect when it can already nade off every single choke, removing embeds will make it actually punishable so the spec isnt always going get one lucky hit and get you killed. When you push a spec, be it pyro, grenadier or sadar, theres mechanical restrictions so theres actualyl a chance for you to push them. Grenadier has a range lock and a chance to do big ff's, You cant its it own counter so the spec isnt always guaranteed to kill the xeno pushing it. This has absoloutetly no downside.

3.) I understand that you want to make this more like a "mine" weapon but i think you should look into making it power faster but lasting shorter. maybe 30 seconds to a minute where its not so horribly oppressive that you cant even push any chokes or adding an active grenade limit like suggested before. Also a big part of why shrapnel weapons were nerfed in the past were because the amount of dps they did was just not fair, take a look into that please and make sure its not too good.
(This would be partially solved by lowering the ammo)

2024-10-01 18:46 UTC, Nomoresolvalou commented
> 5 minutes is a long ass time that you are denying an area for, there is literally nothing else in the game that does this much damage / stun / area denial barring sentries, claymores and mines are easily counterable by the fact that in majority of the cases they are placed, there is nobody else around them. They're a put down and forget kind of deal where as this weapon is actively denying pushes, xenomorphs and areas WITH the full force of a few marine squads behind them.

Xenos can destroy the mines with acid spit and acid spray. Additionally, I believe you ignored one of the biggest parts of how xenos counter the SHARP, which is by using the mines against the marines. If the SHARP user misses a xeno or places a mine on the front, any xeno that has explosive resistance or can spit acid can detonate the mine on the marines. a misplaced mine can deal a real number on any marines that are nearby, so the SHARP needs to think about where they put their mines, unless they want to deal massive damage to their own side. I've seen a video of a cloaked lurker intentionally exploding a mine to kill a marine. I rarely ever see a SHARP mine actually last the full 5 minutes. They either get destroyed instantly by the xenos walking on it before it can level up, or the xenos acid it.

I have noticed that SHARP specs rarely if ever run out of ammo, so I'll consider reducing the ammo req gets.

> Grenadier has a range lock and a chance to do big ff's, You cant its it own counter so the spec isnt always guaranteed to kill the xeno pushing it. This has absoloutetly no downside.

The SHARP does actually have a range lock, same as the GL, it's just that you can click outside of the range lock to shoot at the target.
As for the downsides, again, the mines can fuck marines up real bad if misplaced. Secondly, another downside is that it has no IFF. GL can shoot over the entire frontline to stun xenos, and the SHARP can't do that. Hitting a marine with your dart deals a lot of damage, and frequently leads to a fracture, and requires the marine to take the time to yank the dart out, which takes a good bit longer than normal shrap removal. You need to think about how you use your darts. If you shoot recklessly you're going to hit marines, or your mines are going to be bad and blow marines up, or you're going to hit an explosive resistant xeno and turn it into a literal walking timebomb on the front.

2024-10-01 21:55 UTC, Red-byte3D commented
> > 5 minutes is a long ass time that you are denying an area for, there is literally nothing else in the game that does this much damage / stun / area denial barring sentries, claymores and mines are easily counterable by the fact that in majority of the cases they are placed, there is nobody else around them. They're a put down and forget kind of deal where as this weapon is actively denying pushes, xenomorphs and areas WITH the full force of a few marine squads behind them.
> 
> Xenos can destroy the mines with acid spit and acid spray. Additionally, I believe you ignored one of the biggest parts of how xenos counter the SHARP, which is by using the mines against the marines. If the SHARP user misses a xeno or places a mine on the front, any xeno that has explosive resistance or can spit acid can detonate the mine on the marines. a misplaced mine can deal a real number on any marines that are nearby, so the SHARP needs to think about where they put their mines, unless they want to deal massive damage to their own side. I've seen a video of a cloaked lurker intentionally exploding a mine to kill a marine. I rarely ever see a SHARP mine actually last the full 5 minutes. They either get destroyed instantly by the xenos walking on it before it can level up, or the xenos acid it.
> 
> I have noticed that SHARP specs rarely if ever run out of ammo, so I'll consider reducing the ammo req gets.
> 
> > Grenadier has a range lock and a chance to do big ff's, You cant its it own counter so the spec isnt always guaranteed to kill the xeno pushing it. This has absoloutetly no downside.
> 
> The SHARP does actually have a range lock, same as the GL, it's just that you can click outside of the range lock to shoot at the target. As for the downsides, again, the mines can fuck marines up real bad if misplaced. Secondly, another downside is that it has no IFF. GL can shoot over the entire frontline to stun xenos, and the SHARP can't do that. Hitting a marine with your dart deals a lot of damage, and frequently leads to a fracture, and requires the marine to take the time to yank the dart out, which takes a good bit longer than normal shrap removal. You need to think about how you use your darts. If you shoot recklessly you're going to hit marines, or your mines are going to be bad and blow marines up, or you're going to hit an explosive resistant xeno and turn it into a literal walking timebomb on the front.

There is a total of 3 xenomorphs, 2 not counting queen, these being crusher / oppressor that can walk over the grenade without being stunned, not including hedgehog because its situational and depends on your armor.

Ammo needs an abosloute nerf, im glad you agree. i dont think it having 10 shots per mag is a big deal but +50 per crate buy is absoloute bonkers and needs a nerf, dont listen to the guy above, nothing that decreases your max health is in any way fun. Remember that xenomorphs already have to deal with a shit ton of burst damage and rely on said spongeyness.

Since its being tested, i would also recommend being able to just slash thme to blow them up, atleast givei t a few rounds of test merge to see how much of a difference it makes.

Overall the biggest issue is the ammo economy, if you want to give it this much ammo, you have to lower everything else to counter it. But personally if i were you as i said i'd just lower the per crate req buy to maybe 24(?) ammo just like HEDP boxes.

I still think dart-sticking needs a proper look because its a type of damage that nothing else does in a delayed big burst way that xenomorph health pool is not-up-to-date to be able to handle. I think you can reward a direct stick, by just a delayed-decent stun that doesnt deal any damage.

2024-10-05 13:02 UTC, realforest2001 commented on code/modules/projectiles/guns/specialist/sharp.dm
> +	indestructible = TRUE
```suggestion
	explo_proof = TRUE
```

2024-10-10 12:48 UTC, chefoxara commented
> Possibility to toggle IFF? (mutiny related business) Attachments: rail flashlight and magnets?

did you even play with the gun or atleast read the description lol

2024-10-11 22:29 UTC, NancokPS2 commented
I think the admins made it pretty clear that they do not care about opinions on the git threads. Your best bet is (supossedly) the discord.

2024-10-12 13:03 UTC, GoldenDarkness55 commented
> I think the admins made it pretty clear that they do not care about opinions on the git threads. Your best bet is (supossedly) the discord.

Im aware. The author should be based and close the PR himself, realizing the introduction of this gun is a mistake.
Can always take it to bully tgcm with another bad feature so as not to waste the work done.

2024-10-12 13:14 UTC, chefoxara commented
xeno agent ^

W gun fun to use and can do alot if properly used, xeethe

if you dont like spot a pixel gameplay maybe we should remove both xeno and marine traps all together !

2024-10-12 14:43 UTC, realforest2001 commented on code/game/objects/items/shards.dm
> +/obj/item/sharp
Bit concerned this typepath might be a bit too ambiguous

2024-10-26 11:28 UTC, harryob requested changes
address forest reviews + ci fail

2024-10-26 15:29 UTC, Blundir requested changes
and fix the suit storage being broken

2024-10-26 15:36 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-12-15 22:31 UTC, harryob commented
pr's had requested changes for a month and a bit with merge conflicts. let me know when you want to keep working on this and we cna reopen it

2024-12-15 22:31 UTC, closed without merging