First Pack - New "in_hands" icon sprites for objects, small changes and fixes
cmss13-devs/cmss13 pull request #6951
Opened 2024-08-15 01:51 UTC by LC4492

# About the pull request

This series of PRs is oriented on adding and updating "in_hands" icon sprites that you can find in-game. Each pack of this series will contain 10 unique new icons (without counting the variations for each item, such as the different camos that depend on the map being played). Below, there's a full list of the icons that this pack adds to the game:

Clipboard
Binoculars (All camos)
Mortar Shells (All types)
Space Cleaner Spray
Plant B Gone Spray
Plastic stack
Anesthetic and OT canister tanks
Flashlight
Lantern
Mortar (All camos)

# Explain why it's good for the game

Do I really need to fill this one?

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

![image](https://github.com/user-attachments/assets/ba6947a0-1652-4f97-b402-86711ecf6f93)

![image](https://github.com/user-attachments/assets/13a8ae8c-7b50-4fcd-82bf-beaddde1ddda)

![image](https://github.com/user-attachments/assets/4db68e5c-b2ce-4860-bef1-988e1778e1c8)

![image](https://github.com/user-attachments/assets/a34f7431-13af-46e7-b116-8fbc9859b10f)

![image](https://github.com/user-attachments/assets/a0b73401-77b3-4670-95c2-556e0178bd9e)

![image](https://github.com/user-attachments/assets/70f8c015-35a4-4e3d-a44a-342066d97874)

![image](https://github.com/user-attachments/assets/c1e4022b-9793-4b43-83ae-1bf78e8a2627)

![image](https://github.com/user-attachments/assets/6a331bac-0ddf-45c4-ab1e-77e9baba8bec)

</details>

# Changelog

:cl:
spellcheck: Fixed typos in the "items" file, where on the proc to "zoom", the text had an extra "the" that resulted in a wrong display on chat.
code: Changed the combat flashlight's light range to 6 tiles instead of the normal 5, to make it actually a little better than a normal flashlight. Added a yellowish light color to the lantern (which can be found in colonies), to make it more unique.
imageadd: Added ten new and updated "in_hands" icon sprites, with the list being: Clipboard, binoculars (All camos), mortar Shells (All types), space cleaner spray, plant B gone spray, plastic stack, anesthetic and OT canister tanks, flashlight, lantern and mortar (All camos).
/:cl:

2024-08-15 01:51 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-08-15 02:14 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-08-19 11:03 UTC, Blundir requested changes
some unneeded changes from another pr, as well some sprites mistakes, elaborated in discord

2024-08-21 00:58 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-09-08 03:08 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-11-07 02:48 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-11-25 20:27 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-11-29 12:03 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-12-10 17:49 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-12-11 17:17 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-12-13 22:49 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-12-16 03:55 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-12-16 18:07 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-12-18 15:00 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-12-19 05:45 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-12-19 07:19 UTC, Blundir requested changes
discussed various needed changes in dm

2024-12-21 18:42 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-12-27 16:36 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-12-27 18:11 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-12-27 18:19 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-12-29 02:44 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-12-29 21:06 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-12-31 12:50 UTC, Blundir approved these changes

2024-12-31 14:41 UTC, harryob requested changes

2024-12-31 14:41 UTC, harryob commented on code/game/objects/items/tools/flame_tools.dm
> +		holder.update_inv_r_hand()
you have no check that the holder here is a mob. this could also just be burning out on the floor

2024-12-31 14:41 UTC, harryob commented on code/game/objects/items/tools/flame_tools.dm
> +		holder.update_inv_r_hand()
and chaser 
![image](https://github.com/user-attachments/assets/9461de7f-1a48-4d8e-8f4b-70dd89f8cfd5)

2024-12-31 17:38 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-12-31 17:55 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-12-31 19:50 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-12-31 20:11 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-12-31 22:11 UTC, Red-byte3D commented
![image](https://github.com/user-attachments/assets/e72a0be4-970b-421d-b469-12687d228ab8)
not sure if it was a thing before but monkey had an item on its hand (radiation hood) and it looked like this

2024-12-31 23:14 UTC, LC4492 commented
> ![image](https://private-user-images.githubusercontent.com/47158596/399528467-e72a0be4-970b-421d-b469-12687d228ab8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU2ODM3MjksIm5iZiI6MTczNTY4MzQyOSwicGF0aCI6Ii80NzE1ODU5Ni8zOTk1Mjg0NjctZTcyYTBiZTQtOTcwYi00MjFkLWI0NjktMTI2ODdkMjI4YWI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjMxVDIyMTcwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0ZTJjYjI2MjAwYzVlOGQ0ZWI3NjFjNzNjYjI1MWQ5YmFlZjVlZmVkMmYxNDZhNmQ2ODM5YjMyODk2MzIxNDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.J5crZ5ZTMB9AwmgpfDAxo-0PZi6Xh-MWM0a-giWaUWk) not sure if it was a thing before but monkey had an item on its hand (radiation hood) and it looked like this

Uh.... I don't recall doing in_hands for the radiation hood

2025-01-02 20:56 UTC, harryob approved these changes

2025-01-02 21:06 UTC, merged