Provost Rankpansion
cmss13-devs/cmss13 pull request #6982
Opened 2024-08-19 09:37 UTC by ItsVyzo

# About the pull request
This added the missing Provost positions from the Provost Office hierarchy and gives more options for a more appropriate response when handling ML issues ICly including a Deputy Marshal and Provost Chief Inspector.

# Explain why it's good for the game
rank under-response is better than rank over-response for roleplay and immersion

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
add: Provost Chief Inspector
add: missing Provost Presets per ML Hierarchy
imageadd: added PCI sprites
imageadd: PCI and Dep. Marshal HUD icons
/:cl:

2024-08-19 09:53 UTC, realforest2001 requested changes

2024-08-19 09:53 UTC, realforest2001 commented on code/datums/paygrades/factions/uscm/provost.dm
> +	prefix = "Deputy Marshal"
```suggestion
	prefix = "Dep. Marshal"
```

2024-08-19 09:53 UTC, realforest2001 commented on code/modules/clothing/under/marine_uniform.dm
> +	desc = "The crisp uniform of a chief member of the Provost Office."
```suggestion
	name = "\improper Provost Command Uniform"
	desc = "The crisp uniform of a commanding member of the Provost Office."
```

2024-08-19 09:53 UTC, realforest2001 commented on code/modules/clothing/suits/marine_coat.dm
> +	name = "\improper Chief Provost Jacket"
```suggestion
	name = "\improper Provost Command Jacket"
```

2024-08-19 09:53 UTC, realforest2001 commented on code/modules/clothing/head/head.dm
> +	name = "\improper USCM chief provost beret"
```suggestion
	name = "\improper USCM provost command beret"
```

2024-08-19 09:53 UTC, realforest2001 commented on code/modules/clothing/head/head.dm
> +	desc = "A beret with the USCM Military Police insignia emblazoned on it."
```suggestion
```
Doesn't need an independent definition of desc as it inherits an identical one already.

2024-08-19 10:09 UTC, realforest2001 requested changes

2024-08-19 10:09 UTC, realforest2001 commented on code/datums/factions/uscm.dm
> +			if(JOB_PROVOST_MARSHAL, JOB_PROVOST_CMARSHAL, JOB_PROVOST_FMARSHAL, JOB_PROVOST_SMARSHAL)
```suggestion
			if(JOB_PROVOST_MARSHAL, JOB_PROVOST_CMARSHAL, JOB_PROVOST_SMARSHAL)
```

2024-08-19 10:09 UTC, realforest2001 commented on code/datums/paygrades/factions/uscm/provost.dm
> +
```suggestion
```

2024-08-19 10:09 UTC, realforest2001 commented on code/game/jobs/job/special/provost.dm
> +
```suggestion
```

2024-08-19 10:09 UTC, realforest2001 commented on code/modules/cm_marines/marines_consoles.dm
> +				JOB_PROVOST_DMARSHAL = 04,//Grade O6
```suggestion
				JOB_PROVOST_MARSHAL = 02,//Grade O7
				JOB_PROVOST_DMARSHAL = 03,//Grade O6
```

2024-08-19 10:09 UTC, realforest2001 commented on code/modules/gear_presets/uscm_event.dm
> +
```suggestion
```

2024-08-19 10:09 UTC, realforest2001 commented on code/modules/gear_presets/uscm_event.dm
> +	name = "Provost Sector Marshal (MO8)"
```suggestion
	name = "Provost Sector Marshal (MO9)"
```

2024-08-19 10:09 UTC, realforest2001 commented on code/modules/gear_presets/uscm_event.dm
> +	rank = "Provost Chief Inspector"
```suggestion
	rank = JOB_PROVOST_CINSPECTOR
```

2024-08-19 10:09 UTC, realforest2001 commented on code/modules/gear_presets/uscm_event.dm
> +	rank = "Provost Deputy Marshal"
```suggestion
	rank = JOB_PROVOST_DMARSHAL
```

2024-08-19 10:13 UTC, realforest2001 commented on code/__DEFINES/job.dm
> +
```suggestion
#define JOB_PROVOST_CINSPECTOR "Provost Chief Inspector"
#define JOB_PROVOST_UNDERCOVER "Provost Undercover Inspector"

```

2024-08-19 10:13 UTC, realforest2001 commented on code/datums/factions/uscm.dm
> +				border_rk = "command"
```suggestion
			if(JOB_PROVOST_UNDERCOVER)
				marine_rk = "pvuc"
				border_rk = "command"
			if(JOB_PROVOST_CINSPECTOR)
				marine_rk = "pvci"
				border_rk = "command"
```

2024-08-19 10:19 UTC, realforest2001 approved these changes

2024-08-19 19:01 UTC, Blundir approved these changes

2024-08-21 01:06 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-08-21 21:25 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-08-22 16:20 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-08-22 22:56 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-08-23 12:57 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-08-23 13:41 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-08-23 14:28 UTC, merged