Pill packet boxes
cmss13-devs/cmss13 pull request #6991
Opened 2024-08-20 16:33 UTC by Nomoresolvalou

# About the pull request

Adds pill packet boxes into weychems. They are the exact same as pill bottle boxes, but they contain empty pill packets instead of pill bottles.
Also prevents players from attempting to change pill packet color, as it would break the sprite.

currently using a placeholder sprite for the packet box.

# Explain why it's good for the game

When research runs out of plastic to make injectors for their stims, they usually start pumping out hundreds of individual pills and stuffing them into crates. Now they are able to fill individual pill packets instead to send off instead, which should make things neater in research. Being added to weychems in general, the chemline could also make use of them if any non-medics want a tiny bit of custom chems to run around with. 

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
add: Added a new type of box, pill packet box, to weychem vendors
ui: You can no longer change pill packet color inside the chemmaster (it broke the sprite)
/:cl:

2024-08-22 14:33 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-08-22 14:59 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-08-23 09:59 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-08-23 14:45 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-10-07 15:56 UTC, harryob commented
conflicts with #7021 😦

2024-10-07 16:01 UTC, harryob approved these changes
code is fine though

2024-10-26 01:54 UTC, nauticall requested changes
would strongly prefer that you to use the base `box` sprite and then paint something resembling a pill or w/e on that instead of the placeholder sprite.

2025-01-09 09:02 UTC, Blundir commented
notify me when you'd want to continue it

2025-01-09 09:02 UTC, closed without merging