Changes the M44 heavy speed loader to be more clear
cmss13-devs/cmss13 pull request #7001
Opened 2024-08-22 10:57 UTC by efzapa

# About the pull request

Changes the M44 heavy speed loader to be more clear on what the round actually does, since the name "heavy" can be easily mistaken for an AP round. (imo Marksman and Heavy damage values should be swapped but eh)

Remember: something that is self-evident to you might not be to others. Explain your rationale fully, even if you feel it goes without saying. -->

# Explain why it's good for the game

Having clear descriptions of what bullets do is good.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
qol: Changes the M44 heavy speed loader description to reflect it's actual use-case.
/:cl:

2024-08-22 10:59 UTC, Mister-moon1 commented on code/modules/projectiles/magazines/revolvers.dm
> +	desc = "A revolver speed loader containing heavy bullets. While less heavy hitting than the traditional roundsS, these are more accurate."
rounds has a double S on the end

Probably use "While less damaging than traditional rounds" for conciseness too

2024-08-22 11:21 UTC, ItsVyzo requested changes

2024-08-22 11:21 UTC, ItsVyzo commented on code/modules/projectiles/magazines/revolvers.dm
> +	desc = "A revolver speed loader containing heavy bullets. While less damaging overall than the traditional rounds, these are more accurate."
`desc = "A revolver speed loader containing heavy bullets. While less damaging overall than the traditional rounds, they are more accurate."`

Change these to they, more grammatically accurate

2024-08-23 09:51 UTC, harryob approved these changes

2024-08-23 10:03 UTC, merged