Human vs human AA tower
cmss13-devs/cmss13 pull request #7013
Opened 2024-08-23 12:00 UTC by SerheyKr

# About the pull request

Splitting the work on HvH gamemode to more PRs for easier reviews

# Explain why it's good for the game

Adding AA towers to protect some area from CAS attacks

# Testing Photographs and Procedure
Some codesprites

<details>
<summary>Screenshots & Videos</summary>
![aa_upp](https://github.com/user-attachments/assets/b45c8c33-d9ed-4116-bd65-de797d88c750)
![aa_uscm](https://github.com/user-attachments/assets/c7f6f632-afd5-4a17-9e6b-20ab3e91c633)
![aa_off](https://github.com/user-attachments/assets/42667900-30e0-4672-92ac-7f54cf1ff9c8)
![aa_destroyed](https://github.com/user-attachments/assets/ac72432c-f46c-407e-8d84-06f3a97d8be4)

</details>

# Changelog

:cl: Sergeys
add Added Anti Air tower to UPP and USCM factions
imageadd AA tower image
/:cl:

2024-08-27 05:22 UTC, kiVts requested changes

2024-08-27 05:22 UTC, kiVts commented on code/modules/defenses/aa_tower.dm
> +/obj/structure/machinery/defenses/planetary_anti_air/attackby(obj/item/O as obj, mob/user as mob)
no one letter vars

2024-08-27 05:22 UTC, kiVts commented on code/modules/defenses/aa_tower.dm
> +	var/turf/T = get_turf(src)
no one letter vars

2024-08-27 05:22 UTC, kiVts commented on code/modules/defenses/aa_tower.dm
> +	for(var/turf/A as anything in RANGE_TURFS(covered_range, loc))
no one letter vars

2024-08-27 05:22 UTC, kiVts commented on code/modules/shuttle/shuttles/dropship.dm
> +			for(var/mob/M in internal_turf)
no one letter vars

2024-08-27 05:22 UTC, kiVts commented on code/modules/shuttle/shuttles/dropship.dm
> +			for(var/mob/M in internal_turf)
no one letter vars

2024-08-27 05:22 UTC, kiVts commented on code/modules/defenses/aa_tower.dm
> +	for(var/turf/A as anything in RANGE_TURFS(covered_range, loc))
no one letter vars

2024-08-27 05:22 UTC, kiVts commented on code/modules/defenses/aa_tower.dm
> +/obj/structure/machinery/defenses/planetary_anti_air/proc/get_protection_level(turf/TU)
no one(two in this case) letter vars

2024-08-27 05:22 UTC, kiVts commented on code/modules/defenses/aa_tower.dm
> +			if(do_after(user, 20 * user.get_skill_duration_multiplier(SKILL_CONSTRUCTION), INTERRUPT_ALL|BEHAVIOR_IMMOBILE, BUSY_ICON_FRIENDLY, src))
early return

2024-08-27 05:22 UTC, kiVts commented on code/modules/defenses/aa_tower.dm
> +				var/mob/living/carbon/human/H = user
no one letter vars

2024-08-27 05:22 UTC, kiVts commented on code/modules/defenses/aa_tower.dm
> +	var/luminosity_strength = 2
var declarations after var overrides

2024-08-27 05:22 UTC, kiVts commented on code/modules/defenses/aa_tower.dm
> +	var/linked_turfs_covered = list()
if you declare a list then you cast it as list, e.g. `var/list/this = list()`

2024-08-27 05:22 UTC, kiVts commented on code/modules/defenses/aa_tower.dm
> +		var/turf/T = get_turf(src)
no one letter vars

2024-08-27 05:22 UTC, kiVts commented on code/game/turfs/turf.dm
> +	for (var/obj/structure/machinery/defenses/planetary_anti_air/planetary_aa in src.linked_aa)
```suggestion
	for (var/obj/structure/machinery/defenses/planetary_anti_air/planetary_aa in linked_aa)
```
only need to do src.var in initialize proc, do that to every var that has src.var in this pr

2024-12-15 19:03 UTC, harryob requested changes
im so sorry this got forgotten

2024-12-15 19:03 UTC, harryob commented on code/modules/defenses/aa_tower.dm
> +	last_fired = world.time
needs to be refactored into 3 procs and called with addtimers (sorry)

2024-12-15 19:03 UTC, harryob commented on code/modules/defenses/aa_tower.dm
> +/obj/structure/machinery/defenses/planetary_anti_air/attackby(obj/item/object as obj, mob/user as mob)
```suggestion
/obj/structure/machinery/defenses/planetary_anti_air/attackby(obj/item/object, mob/user)
```
ik this is copypaste but those are always redundant in procs

2024-12-15 19:03 UTC, harryob commented on code/modules/defenses/aa_tower.dm
> +					return
```suggestion
					return

				user_human.electrocute_act(20, src)//god bless him for stupid move
				return
```
previous conditons returns, else isnt necessary

2024-12-15 19:03 UTC, harryob commented on code/modules/defenses/aa_tower.dm
> +			return
```suggestion

		var/turf/turf_under_aa = get_turf(src)
		var/area/area = get_area(turf_under_aa)
		if(CEILING_IS_PROTECTED(area.ceiling, CEILING_PROTECTION_TIER_1) || !is_ground_level(turf_under_aa.z))
			to_chat(user, SPAN_RED("You realize how bad of an idea this is and quickly stop."))
			return

		var/turf/open/floor = get_turf(src)
		if(!floor.allow_construction)
			to_chat(user, SPAN_WARNING("You cannot secure \the [src] here, find a more secure surface!"))
			return FALSE
		user.visible_message(SPAN_NOTICE("[user] begins securing [src] to the ground."),
		SPAN_NOTICE("You begin securing [src] to the ground."))

		if(!do_after(user, anchor_time * user.get_skill_duration_multiplier(SKILL_CONSTRUCTION), INTERRUPT_ALL|BEHAVIOR_IMMOBILE, BUSY_ICON_BUILD, src))
			return
		user.visible_message(SPAN_NOTICE("[user] secures [src] to the ground."),
		SPAN_NOTICE("You secure [src] to the ground."))
		anchored = TRUE
		playsound(loc, 'sound/items/Ratchet.ogg', 25, 1)
		return
```

2024-12-15 19:03 UTC, harryob commented on code/modules/defenses/aa_tower.dm
> +		update_icon()
```suggestion
	if(health >= health_max * 0.15)
		return

	visible_message(SPAN_DANGER("[icon2html(src, viewers(src))] [src] cracks and breaks apart!"))
	stat |= DEFENSE_DAMAGED
	turned_on = FALSE
	remove_protected_area()
	set_light(0)
	update_icon()
```

2024-12-15 19:25 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2025-01-30 15:24 UTC, harryob commented
stale with requested changes dating back to august, address and re-open if you're still interested

2025-01-30 15:24 UTC, closed without merging

2025-01-30 19:34 UTC, SerheyKr commented
> stale with requested changes dating back to august, address and re-open if you're still interested

I resolved them, just did not marked as resolved because it's up to person who requested them(Or at least I thinked so)