Using a multitool to find an APC now highlights the APC
cmss13-devs/cmss13 pull request #7020
Opened 2024-08-23 19:29 UTC by TheGamerdk

# About the pull request

Makes the find-APC function more useful.

# Explain why it's good for the game

Very convenient. Lasts for 1.4 seconds (scan cooldown is 1.5 seconds)
Clientside, respects darkness.
You still get the 'X units in Y direction' thing

![image](https://github.com/user-attachments/assets/5049bc9d-1cf1-401a-8e4f-2a02732fc6f9)

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Spawned in, tried to use multitool, saw green.
Turned off lights, did not see green.
Joined with second client, used multitool. Only saw it on 1 client.
Left after clicking multitool, rejoined to make sure highlight still gone. (Client gets deleted when disconnecting)

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
add: APCs are now highlighted when found via a Multitool/Security Access Tuner. 
/:cl:

2024-08-23 20:16 UTC, harryob approved these changes

2024-08-24 11:00 UTC, harryob requested changes
same thing

2024-08-24 11:00 UTC, harryob commented on code/game/objects/items/devices/multitool.dm
> +			apc_appearance.appearance = APC
```suggestion
			var/mutable_appearance/apc_appearance = new(APC)
```

2024-08-24 11:05 UTC, harryob approved these changes

2024-08-24 15:03 UTC, TheGamerdk commented
> same thing

true that

2024-08-24 17:24 UTC, merged