Fixes giant lizard code breaking when disarmed
cmss13-devs/cmss13 pull request #7025
Opened 2024-08-24 18:15 UTC by VileBeggar

# About the pull request

stops the code from breaking when getting pushed
what did i learn? NEVER TRUST BYOND'S INBUILT PATHFINDING PROCS TO WORK 

# Explain why it's good for the game

bug bad

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
fix: Giant lizards no longer become paralyzed after getting disarmed.
/:cl:

2024-09-10 08:41 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-09-14 13:41 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-10-08 13:10 UTC, harryob requested changes
so sorry did forget about this one

2024-10-08 13:10 UTC, harryob commented on code/modules/mob/living/simple_animal/hostile/retaliate/giant_lizard.dm
> +					break
iterating through a list like this already typechecks, so is redundant. but you can also just do this

```suggestion
			var/is_meat = locate(/datum/reagent/nutriment/meat) in food.reagents.reagent_list
```

2024-10-08 13:10 UTC, harryob commented on code/modules/mob/living/simple_animal/hostile/retaliate/giant_lizard.dm
> +				return
```suggestion
	if(!prob(break_stuff_probability))
		return

	for(var/obj/structure/obstacle in view(1, src))
		if(is_type_in_list(obstacle, destruction_targets))
			AttackingTarget(obstacle)
			return
```

2024-10-09 08:50 UTC, harryob approved these changes

2024-10-09 08:55 UTC, merged