Fix: desert flora can now be cut down
cmss13-devs/cmss13 pull request #703
Opened 2022-07-18 18:20 UTC by JohnDoe50974

## About The Pull Request
Desert tallgrass and bushes (the orange-map thematic ones, found on Kutjevo and Trijent) could not have been cut with machetes/knives beforehand. This fixes that.

## Why It's Good For The Game
Bugfix good!

## Changelog

:cl: 50RemAndCounting
fix: Kutjevo/Trijent tallgrass and other flora can now be properly cut away with machetes and other bladed equipment.
/:cl:

2022-07-18 18:39 UTC, Agameofscones requested changes
discard changes to maps.txt, otherwise lgtm

2022-07-18 18:52 UTC, JohnDoe50974 commented
> discard changes to maps.txt, otherwise lgtm

Fixed

2022-07-18 21:17 UTC, Superwelder commented
This makes me happy. Even when Kutjevo was added, we could chop the grass on LV so the discrepancy has always existed. Props for making it happen.

2022-07-19 18:51 UTC, stanalbatross requested changes

2022-07-19 18:51 UTC, stanalbatross commented on code/game/objects/structures/flora.dm
> +	cut_level = PLANT_CUT_MACHETE
this needs to be on the parent obj not the /corner subtype

2022-07-19 19:00 UTC, stanalbatross approved these changes

2022-07-19 19:01 UTC, merged