Tank Artillery Module Buff
cmss13-devs/cmss13 pull request #7043
Opened 2024-08-26 15:56 UTC by MPhonks

# About the pull request

This PR aims to make the artillery module feel slightly better to use by increasing the view distance to be that comparable of a sniper specialist whilst also doubling hardpoint accuracy for use with weapons such as the minigun or cupola at longer ranges.

# Explain why it's good for the game

Pushes the idea of mixing and matching various tank builds together. Makes the artillery module slightly more satisfying to use.

# Testing Photographs and Procedure

N/A

# Changelog

:cl: MarpleJones
balance: The tank's artillery module now doubles hardpoint accuracy.
balance: Changes the tank's artillery module's view_tile offset from 7 to 8.
/:cl:

2024-08-26 22:35 UTC, TheManWithNoHands commented
All the hardpoints currently have almost perfect accuracy. They legit can barley have more. All this does is break some mechanics, mainly the LTAA minigun with its windup that decreases scatter.

2024-08-27 00:10 UTC, MPhonks commented
@TheManWithNoHands 
#> All the hardpoints weapons currently have almost perfect accuracy. They legit can barley have more. All this does is break some mechanics, mainly the LTAA minigun with its windup that decreases scatter.
>
> Good buff idea, but for the wrong weapons. They dont need it. Cupola has scatter of 3 my man.

I've attached two comparison videos with the LTAA Minigun and Artillery Module, pre- and postbuff, to the PR. During my private playtests I didn't notice anything breaking, but maybe I've overseen something and it doesn't behave as it should internally? By comparison, the IWSA increases accuracy by 1.67.

2024-08-27 02:18 UTC, TheManWithNoHands commented
> @TheManWithNoHands
> 
> > All the hardpoints weapons currently have almost perfect accuracy. They legit can barley have more. All this does is break some mechanics, mainly the LTAA minigun with its windup that decreases scatter.
> > Good buff idea, but for the wrong weapons. They dont need it. Cupola has scatter of 3 my man.
> 
> I've attached two comparison videos with the LTAA Minigun and Artillery Module, pre- and postbuff, to the PR. During my private playtests I didn't notice anything breaking, but maybe I've overseen something and it doesn't behave as it should internally? By comparison, the IWSA increases accuracy by 1.67.

the videos are broken. Use links.

2024-09-14 05:44 UTC, kiVts requested changes

2024-09-14 05:44 UTC, kiVts commented on code/modules/vehicles/hardpoints/support/artillery.dm
> +		"accuracy" = 2,
Dont need the comma

2024-10-16 16:14 UTC, Nanu308 commented
> All the hardpoints weapons currently have almost perfect accuracy. They legit can barley have more. All this does is break some mechanics, mainly the LTAA minigun with its windup that decreases scatter.
> 
> Good buff idea, but for the wrong weapons. They dont need it. Cupola has scatter of 3 my man.

I agree with this, going to DNM it for now.

2024-10-27 22:20 UTC, harryob commented
pr appears to have been untouched on do not merge for a couple weeks with an outstanding requested change, feel free to ask us to reopen/make a new pr once you've discussed it with nanu

2024-10-27 22:20 UTC, closed without merging