Synthetic Type Selection
cmss13-devs/cmss13 pull request #7046
Opened 2024-08-26 23:19 UTC by Katskan

# About the pull request

Enables selection from one of 2 basic archetypes for synthetic characters. The archetypes are called "support" and "industrial". Essentially the support is currently how you spawn as shipside, and industrial is how you spawn as colonial. Both types can be picked regardless of spawning on the ship or the colony, it is up to the character rather than the slot. 

# Explain why it's good for the game

Allows for people to keep a more consistent character which has better RP capability. Certain nightmare spawns (and high population rounds) have shown having more shipside type synthetics isn't a significant round impact and allowing for more consistency lets people RP their character without having to go out of their way to avoid using any of the mechanical aspects in their RP. 

# Changelog

DRAFT: Work In Progress

:cl:
balance: allows ship and colony type synthetics to pick their archetype (see above for archetypes)
/:cl:

2024-08-27 04:48 UTC, Zonespace27 requested changes

2024-08-27 04:48 UTC, Zonespace27 commented on code/game/jobs/job/civilians/support/synthetic.dm
> +#define INDUSTRIAL_VARIANT "Industrial Synthetic"
Undef these

2024-08-27 04:48 UTC, Zonespace27 commented on code/game/jobs/job/civilians/support/synthetic.dm
> +	var/standard = TRUE
Code doc

2024-10-17 06:47 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-10-24 17:25 UTC, closed without merging