Project ARES: Interface Data Proc
cmss13-devs/cmss13 pull request #7061
Opened 2024-08-29 13:06 UTC by realforest2001

# About the pull request

Adds a centralised proc for getting all the interface data, this will make the UI's much more flexible and massively reduces the amount of duplicate code.

# Explain why it's good for the game

Code efficiency, allowing future flexible development.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
code: Overhauled the backend code for the various ARES related UIs, centralising most interface data to one proc.
/:cl:

2024-09-07 23:23 UTC, Nanu308 commented on maps/map_files/USS_Almayer/USS_Almayer.dmm
Mapping lgtm

2024-10-05 11:08 UTC, harryob requested changes

2024-10-05 11:08 UTC, harryob commented on code/game/machinery/ARES/ARES_interface_data.dm
> +			continue
```suggestion
	for(var/datum/ares_ticket/maintenance/maint_ticket as anything in link.tickets_maintenance)
```
`as anything` OR checking the type in the loop, not both

2024-10-26 11:40 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-12-15 19:57 UTC, harryob approved these changes

2024-12-15 21:31 UTC, merged