Join as freed mob no longer runtimes
cmss13-devs/cmss13 pull request #7064
Opened 2024-08-29 22:49 UTC by kiVts

# About the pull request

This would runtime if anyone pressed it and there is no freed mobs
found when doing the spawn_member pr
# Explain why it's good for the game

runtimes bad

# Changelog

:cl:
code: Join as freed mobs will now notify the user if there is no freed mobs to take.
/:cl:

2024-08-29 22:51 UTC, harryob requested changes

2024-08-29 22:51 UTC, harryob commented on code/modules/mob/dead/observer/observer.dm
> +		to_chat(src, SPAN_WARNING("There is no Freed Mobs available."))
```suggestion
		to_chat(src, SPAN_WARNING("There are no Freed Mobs available."))
```
i hate english

2024-08-29 22:52 UTC, harryob approved these changes

2024-09-04 17:18 UTC, realforest2001 approved these changes

2024-09-07 20:43 UTC, merged