Allows Xenos to feed Captures with fruit resin
cmss13-devs/cmss13 pull request #7081
Opened 2024-09-02 06:06 UTC by Diegoflores31

# About the pull request
Allows Xenomorphs to feed resin fruit to nested humans. this provides 30 points of heal and injects them with 10 units of fruit resin.
adds a sound for the mentioned interaction

sound source: ( copyright free)
https://pixabay.com/service/license-summary/

# Explain why it's good for the game

With how hard it is to capture someone it very anoying that often they will die from injuries . this lore accurate method provides xenos with a niche option to prevent captures from diying from medium injuries while captured.

This can prove usefull specially when a human or monkey has been slashed by mistake in the process of being nested.

Tt only works on nested humans and its tweaked to prevent Accidental ODs. (( this does not heal organ damage nor restore blood . if a human is fucked up this wont revive them)

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
balance: Xenomorphs can feed nested humans with resin fruit to heal them.
soundadd: added a sound for fruit forced feeding
/:cl:

2024-09-02 13:46 UTC, Contrabang commented on code/modules/cm_aliens/structures/fruit.dm
> +		if(HAS_TRAIT(humanus, TRAIT_NESTED) && humanus.stat == !DEAD) // if they are not nested or dead they cant be feed.
```suggestion
		if(HAS_TRAIT(humanus, TRAIT_NESTED) && humanus.stat != DEAD) // if they are not nested or dead they cant be feed.
```

2024-09-03 00:20 UTC, deathrobotpunch commented on code/modules/cm_aliens/structures/fruit.dm
> +		if(HAS_TRAIT(humanus, TRAIT_NESTED) && humanus.stat == !DEAD) // if they are not nested or dead they cant be feed.
can’t be feed

2024-09-03 00:21 UTC, deathrobotpunch commented on code/modules/cm_aliens/structures/fruit.dm
> +		if(HAS_TRAIT(humanus, TRAIT_NESTED) && humanus.stat == !DEAD) // if they are not nested or dead they cant be feed.
also it’s can’t not cant

2024-09-05 06:59 UTC, zzzmike commented
Interesting idea for sure, which part of the code prevents ODs though?

2024-10-28 09:14 UTC, Nanu308 commented
Against this, especially with the egg morpher potentially seeing more play with the PR that changes it (on phone can't link it)

Might be too much for xeno captures with prior pr mentioned.

2024-11-26 05:15 UTC, Drulikar requested changes
- When a marine is fed like this, they need to no longer be possible to gain stacks from (e.g. acid runner). Maybe consider adding/altering a var that indicates whether they can still grant stacks. Just make sure they are only granted that flag through this method (nested feeding)
- Consider if you want this to be possible w/ human allies if not nested (I'm not sure)

2024-11-26 05:15 UTC, Drulikar commented on code/modules/cm_aliens/structures/fruit.dm
> +			return
Early return if `humanus` is DEAD rather than check it twice

2024-11-26 05:15 UTC, Drulikar commented on code/modules/cm_aliens/structures/fruit.dm
> +		if(HAS_TRAIT(humanus, TRAIT_NESTED) && humanus.stat != DEAD) // if they are not nested or dead they cant be feed.
Early return if `humanus` is DEAD rather than check it twice

2024-11-26 05:15 UTC, Drulikar commented on code/modules/cm_aliens/structures/fruit.dm
> +	if(istype(affected_xeno, /mob/living/carbon/human))
```suggestion
	if(ishuman(affected) && !istype(affected:species, /datum/species/synthetic))
```

2024-11-26 05:15 UTC, Drulikar commented on code/modules/cm_aliens/structures/fruit.dm
> +	if(istype(user, /mob/living/carbon/xenomorph))
```suggestion
	if(isxeno(user))
```

2024-11-26 05:15 UTC, Drulikar commented on code/modules/cm_aliens/structures/fruit.dm
> +
```suggestion
```

2024-11-26 05:15 UTC, Drulikar commented on code/modules/cm_aliens/structures/fruit.dm
>  /obj/item/reagent_container/food/snacks/resin_fruit/attack(mob/living/carbon/xenomorph/affected_xeno, mob/user)
The first argument is not correct (its not always a xeno being affected). Refactor back to `mob/` and correct the variable name (not always a xeno).

2024-11-29 14:27 UTC, Diegoflores31 commented
Just make sure they are only granted that flag through this method (nested feeding)
> * Consider if you want this to be possible w/ human allies if not nested (I'm not sure)

We had a PR that make acid runners unable to get stacks from capped host from what i am aware

2024-12-05 05:45 UTC, Drulikar commented
> Just make sure they are only granted that flag through this method (nested feeding)
> 
> We had a PR that make acid runners unable to get stacks from capped host from what i am aware

While they are nested - yes.

2025-01-23 11:33 UTC, closed without merging