Psychic Radiance for humans
cmss13-devs/cmss13 pull request #7087
Opened 2024-09-02 18:23 UTC by realforest2001

# About the pull request

Well, they can talk 1:1. Why not this.

# Explain why it's good for the game

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
add: Added psychic radiance for humans.
/:cl:

2024-09-02 18:25 UTC, Git-Nivrak commented
While at it please make it so it only appears for ghosts in range as it gets really annoying real fast when there is multiple people speaking in huge purple movimg characters in your chat regardless of where you are without being able to turn it off

2024-09-10 09:08 UTC, harryob requested changes

2024-09-10 09:08 UTC, harryob commented on code/modules/mob/living/carbon/human/powers/human_powers.dm
> +	var/whisper = strip_html(input("Message:", "Psychic Radiance") as text|null)
tgui_input_text

2024-09-10 09:08 UTC, harryob commented on code/modules/mob/living/carbon/human/powers/human_powers.dm
> +			rendered_message = SPAN_XENOLEADER("PsychicRadiance: [src.real_name][human_track] to [targetstring], <span class='normal'>'[SPAN_PSYTALK(whisper)]'</span>")
```suggestion
			rendered_message = SPAN_XENOLEADER("PsychicRadiance: [real_name][human_track] to [targetstring], <span class='normal'>'[SPAN_PSYTALK(whisper)]'</span>")
```

2024-10-05 10:50 UTC, harryob approved these changes

2024-10-05 11:57 UTC, merged