Automatic emotes are no longer are affected by emote cooldown (baton edition for now)
cmss13-devs/cmss13 pull request #7121
Opened 2024-09-05 20:15 UTC by zzzmike

# About the pull request

The intent behind this is to not have automatic emotes trigger, and be affected by, emote cooldown. Starting with automatic baton emote for now. Might change this if someone points out a better way to fix this for all automatic emotes.

# Explain why it's good for the game

Emote cooldown is designed to stop players spamming them and being LRP, it should never affect automatic emotes. It doesn't make sense that automatic emotes can't happen because you did a manual one a few seconds ago.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
sounddel: automatic emotes are not affected by emote cooldown (baton edition for now)
/:cl:

2024-09-10 09:13 UTC, harryob requested changes
non-intentional emotes shouldn't impacted by cooldown anyway, we shouldn't have to do funny trait stuff like this, check `/mob/proc/emote`

2024-09-11 10:41 UTC, zzzmike commented
> non-intentional emotes shouldn't impacted by cooldown anyway, we shouldn't have to do funny trait stuff like this, check `/mob/proc/emote`

it's bugged, throws the 'you just did an emote' error when getting hit by a baton multiple times quickly @harryob

2024-09-11 10:53 UTC, zzzmike commented
it's bugged then, throws a 'you just did an emote' error when getting hit by baton multiple times quickly

2024-10-26 20:34 UTC, harryob commented
seems to be stale, feel free to make an issue report if you're not interested in this and i can try to take a look more thoroughly at some point

2024-10-26 20:34 UTC, closed without merging