Yautja Scimitar alternative style.
cmss13-devs/cmss13 pull request #7126
Opened 2024-09-07 05:55 UTC by JustLat

# About the pull request

Adds an alternative style for the scimitar weapon through a radial system much like the glaive and scythe.

# Explain why it's good for the game

This allows for more customization for Yautjas and allows them to pick which sprite they want to use.

# Testing Photographs and Procedure

<details>

<summary>Screenshots & Videos</summary>

https://github.com/user-attachments/assets/fe3dd142-3566-491e-8e54-625e84e8746f

![Screenshot_1](https://github.com/user-attachments/assets/97592de3-d4bd-4022-abe2-aa2213d07851)

![Screenshot_2](https://github.com/user-attachments/assets/5fc21d8a-b93e-40ee-be9d-88633f245e3d)

![Screenshot_3](https://github.com/user-attachments/assets/8ab2548a-3d40-4902-b214-af19eb52f8ca)

</details>

# Changelog

:cl:
add: adds alt sprite style for scimitars, similar to war glaive and scythe
/:cl:

2024-09-07 05:55 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-09-09 18:04 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-10-02 18:39 UTC, Blundir approved these changes

2024-10-02 18:39 UTC, Blundir commented
Doesn't touch the files that i touch in reorganization, good to merge

2024-10-05 10:35 UTC, harryob requested changes

2024-10-05 10:35 UTC, harryob commented on code/modules/cm_preds/yaut_weapons.dm
> +	attack_verb = list("sliced", "slashed", "jabbed", "torn", "gored")
```suggestion
```

2024-10-05 10:35 UTC, harryob approved these changes

2024-10-05 10:44 UTC, merged