Fixes for calculating collisions in LinkBlocked and Enter
cmss13-devs/cmss13 pull request #7138
Opened 2024-09-09 06:01 UTC by boskoramen

# About the pull request

Refactors logic and updates documentation for turf/Enter() and LinkBlocked() procs. Fixes a few bugs or weird behaviors with old logic.

# Explain why it's good for the game

Multitile collision behavior is pretty wonky, this should make tank act as expected when running into multiple blockers and with things that are bordering an edge like barricades

Also fixes issue with not being able to climb diagonally (and other issues that may have been caused by LinkBlocked returning TRUE when it should not be)

# Testing Photographs and Procedure

Tested with tank, climbing diagonally, and walking around barricades.

<details>
<summary>Screenshots & Videos</summary>

![Test video with tank](https://cdn.discordapp.com/attachments/745447048261795890/1282576390256066664/Desktop_2024.09.08_-_22.19.51.04.mp4)

</details>

# Changelog

:cl:
fix: Can now climb on windows diagonally if there are no actual movement blockers
fix: Multitile vehicles should now properly handle situations where a border object (e.g. indestructible window) was blocking its mo
refactor: Cleaned up logic for detecting if a link is blocked or for checking collisions during movement
/:cl:

2024-09-13 06:52 UTC, boskoramen commented
didn't realize you can rebase onto master in github

2024-10-06 05:32 UTC, harryob requested changes
also, ci fail

2024-10-06 05:32 UTC, harryob commented on .vscode/tasks.json
> +            "label": "run local server"
this is equivalent to the dreammaker - dreamdaemon target?

2024-10-06 05:41 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-12-15 22:29 UTC, harryob requested changes
stale, merge conflicts, etc. would be happy to try and get this moved through if you'd like to keep working on it, just let me know

2024-12-15 22:29 UTC, closed without merging