WIP : Adds Painkiller Addictions
cmss13-devs/cmss13 pull request #7141
Opened 2024-09-09 22:56 UTC by Diegoflores31

# About the pull request

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
add: Adds Opioid addiction "virus"
balance: Opioid painkillers can generate addiction (tramadol , oxycodone , Sleen)
/:cl:

2024-09-09 23:42 UTC, Korey45 commented
This would very highly value a section in "Why its good for the game". It's going to be absolutely dogpiled and hated without a good enough reason, Showcase or not.

2024-09-10 00:10 UTC, vero5123 reviewed
Very cool pr, hopefully it gets merged.

2024-09-10 00:10 UTC, vero5123 commented on code/datums/diseases/addiction.dm
> +				var/message = SPAN_DANGER( pick("I am not strong enough , I NEED IT", "If I dont get some soon, I dont know what is going to happen.", "I cant think straight. I need it", "I cant handle this pain
```suggestion
				var/message = SPAN_DANGER( pick("I am not strong enough, I NEED IT!", "If I don't get some soon, I don't know what is going to happen.", "I cant think straight. I need it.", "I cant handle this pain anymore, I need it now." ) )
```

2024-09-10 00:10 UTC, vero5123 commented on code/datums/diseases/addiction.dm
> +				var/message = SPAN_DANGER( pick("I NEED IT NOW", "If I dont get some soon, I dont know what is going to happen.", "I cant think straight. I need it", "I cant handle the pain anymore." ) )
```suggestion
				var/message = SPAN_DANGER( pick("I NEED IT NOW!", "If I don't get some soon, I don't know what is going to happen.", "I cant think straight. I need it", "I cant handle the pain anymore." ) )
```

2024-09-10 00:10 UTC, vero5123 commented on code/modules/reagents/chemistry_properties/prop_negative.dm
> +	description = "This chemical contains opiate traces , making it highly addictive"
```suggestion
	description = "This chemical contains opiate traces, making it highly addictive."
```

2024-09-10 00:10 UTC, vero5123 commented on code/modules/reagents/chemistry_reagents/other.dm
> +	description = " A favorite of marine medics, it is an illicit mixture of name brand lime soda and oxycodone, known for it's distinct green color.The chemical flavoring increase the painkilling power
```suggestion
	description = " A favorite of marine medics, it is an illicit mixture of name brand lime soda and oxycodone, known for its distinct green color. The chemical flavoring increase the painkilling power, usually used by junkies as a replacement of the real deal."
```

2024-09-10 00:17 UTC, vero5123 commented on code/datums/diseases/addiction.dm
> +				return
![1GrrAjNOAE-1](https://github.com/user-attachments/assets/0c2192ae-26fa-44b2-9dd5-2a4a72bba3e6)

2024-09-10 02:28 UTC, SASoperative commented
How exactly would you seek medical help shipside for this? Because if it is just a basic medical antidote like normal SS13 viruses, and not some form of surgery, or machine needed, than what is to stop the cure from being deployed planetside or with combat medics? Not like I would like that because playing a combat medic can already be hell as is in its current state. 

I also do not see any additional notes about the vendor changes removing Oxycodone bottles, or the changing of tramadol from basic medical kits to paracetamol, or the variable changes that make painkillers overall weaker. 

I know that you attempted to make a PR for another change earlier, did you forget to split or revert those changes before starting this one? 
I say this because the commits are from yesterday, but the PR for this addiction change was made today.

2024-09-10 02:33 UTC, Diegoflores31 commented
> If you cant be bothered to justify the merits of your changes, the community will not understand your changes.
> 
> Please dont be lazy, and actually fill out the PR template?

as on the main tittle i am still kinda finishing up the PR . i just uploaded it because i wanted to show it to other contribs 
this is just a showcase of the code untill i finish it off

2024-09-10 02:35 UTC, Diegoflores31 commented
> I know that you attempted to make a PR for another change earlier, did you forget to split or revert those changes before starting this one? I say this because the commits are from yesterday, but the PR for this addiction change was made today.

they are files from another PR that got mixed up . they are being deleted , its written on the description

![image](https://github.com/user-attachments/assets/9ac12fa6-7264-4734-86e2-ccbb2d33cd48)

2024-09-10 02:38 UTC, SASoperative commented
> > I know that you attempted to make a PR for another change earlier, did you forget to split or revert those changes before starting this one? I say this because the commits are from yesterday, but the PR for this addiction change was made today.
> 
> they are files from another PR that got mixed up . they are being deleted , its written on the description
> 
> ![image](https://private-user-images.githubusercontent.com/47069269/365871452-9ac12fa6-7264-4734-86e2-ccbb2d33cd48.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5MzYwMDIsIm5iZiI6MTcyNTkzNTcwMiwicGF0aCI6Ii80NzA2OTI2OS8zNjU4NzE0NTItOWFjMTJmYTYtNzI2NC00NzM0LTg2ZTItY2NiYjJkMzNjZDQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEwVDAyMzUwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0MzdlMmMyMWI5NzI4NzVjMzIwZjNhMThlM2E5Mzc3OWM0OGFhYTk3MTc3M2NlYWE5Yzg3YWU1M2ZkZjZkY2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RUG508lz1My0KgEf9QuR7b2sISn3mmnjZMQcaEG_H0M)

Understood, I was uncertain on what that exactly meant by files needing polish implied. 
My apologies.

2024-09-10 03:38 UTC, Zonespace27 requested changes
![image](https://github.com/user-attachments/assets/665b3669-3984-402c-8557-e4a33a539604)

this section exists for a reason, fill it out before marking it as "ready"; if it's not ready, that's what drafting's for

2024-09-10 04:03 UTC, Derunner commented
Medicord wants to know your exact location

2024-09-10 04:48 UTC, Diegoflores31 commented
> this section exists for a reason, fill it out before marking it as "ready"; if it's not ready, that's what drafting's for

i wanted to but the draft button didnt appear on my screen

2024-09-10 05:54 UTC, efzapa commented
far better than flat organ damage, very based

2024-09-10 12:10 UTC, TheManWithNoHands commented
Very cool. But SAS is rigth, the additcion needs a cure that is avalibel only with proper medical treatment, and not just more drugs.
If marines can just slip their no addiction juice in the unga bottle, that makes it kinda useless.

(Custom research chems excluded, also make sure the anti addicting property works for this btw. Sounds like a buff to stims, but it aint. Cause that means you would have to decide between stim without painkilling, or using up two property slots. Wich is a fun choice.)

Legit, if you want some ideas, look at TGMC medical system. They tried to reduce blind premedding like you currently are. They reworked their medical system a LOT for that.
Good idea to see what solutions they came up with. Migth be worth yoinking some of their ideas. Like, they made changes to what organ dmg causes, to allow chems to cause organ dmg while keeping it interesting. For exmp heart dmg lowers your robustness, kenshi style. Aka, you go pain crit faster. Or kindey/liver (i forgot wich one) dmg decreases how well chems work.
Def worth a peek.

2024-09-10 13:24 UTC, Katskan commented
I'd love to have a conversation with you about IRL pain medications that would do a great job of offering new options and depth to gameplay as well as have their own up and downsides, without disrupting gameplay too terribly much. 

An example is the distinction between narcotic and non-narcotic painkillers. Narcs could be made to cause respiratory depression in the form of oxygen damage which is manageable with dexalin for lower strength meds and needs dex+ for higher strength surgical meds. Non-narcotics have other effects, such as toradol which has an anti-platelet effect, resulting in faster bleeding, or ketamine with dissociative and hallucinogenic effects. There's a lot of options to expand with that have built-in pros and cons without using the addiction system.

2024-09-10 16:35 UTC, vero5123 commented on code/modules/reagents/chemistry_reagents/other.dm
> +	description = " A favorite of marine medics, it is an illicit mixture of name brand lime soda and oxycodone, known for its distinct green color. The chemical flavoring increase the painkilling power
```suggestion
	description = "A favorite of marine medics, it is an illicit mixture of name brand lime soda and oxycodone, known for its distinct green color. The chemical flavoring increase the painkilling power, usually used by junkies as a replacement of the real deal."
```

2024-09-10 16:35 UTC, vero5123 commented on code/datums/diseases/addiction.dm
> +				var/message = SPAN_DANGER( pick("I NEED IT NOW!", "If I don't get some soon, I don't know what is going to happen.", "I cant think straight. I need it", "I cant handle the pain anymore." ) )
```suggestion
				var/message = SPAN_DANGER( pick("I NEED IT NOW!", "If I don't get some soon, I don't know what is going to happen.", "I cant think straight. I need it.", "I cant handle the pain anymore." ) )
```

2024-09-10 18:43 UTC, Steelpoint commented
You know, under "realistic" circumstances, opioid addiction is a very long-term issue to resolve. People who are have abused opioids can reach a point where conventional painkillers are nearly useless for genuine pain-relief, in some cases you are left with someone who literally can not be relieved of pain even if given some of the strongest medications available, which sucks if you also have chronic (or very acute) pain. 

At that point you might need medications like methadone or buprenorphine to be used as treatment options for opioid addition, which are also fairly strong painkillers in their own right. 

Of course, at this point we may as well make it that Doctors need to write a prescription for Tramadol or Oxycodone and you need to get two Nurses to sign out every single tablet of said medications from a special vendor before they can give 1 pill to a Marine. I look forward to the Provost fax regarding a miscount of the Oxycodone medication. 

All this is saying, is this level of complication in regards to painkiller addiction really necessary for Colonial Marines? A (relativity) fast paced combat game. If half the Marine force is suddenly unable to use painkillers, that might have a disruptive effect on the game. 

Perhaps if this was a optional penalty you could take as a Rifleman or shipside roleplay role, but something forced on everyone? I'm not so sure.

2024-09-10 19:20 UTC, TheManWithNoHands commented
> You know, under "realistic" circumstances, opioid addiction is a very long-term issue to resolve. People who are have abused opioids can reach a point where conventional painkillers are nearly useless for genuine pain-relief, in some cases you are left with someone who literally can not be relieved of pain even if given some of the strongest medications available, which sucks if you also have chronic (or very acute) pain.

My guy, its a punishment for exsessive premedding. That the punishment is called opioid addiction is IC flavor.
Dont start pulling out those arguments. You been dev long enough to know how silly those are.

2024-09-11 00:00 UTC, Korey45 commented
Pre-medicating isn't even an issue in the first place. I don't know why that's a valid reason. Its not been explained at all why its an issue.

2024-09-11 02:53 UTC, frozentsbgg commented
We have like six different levels of painkillers holding over from a system that was removed.
I'm all for attempts to bring back addiction. 
There should be a functional difference between Tramadol and oxytocin from a painkiller and downside perspective.

2024-09-11 11:29 UTC, TheManWithNoHands commented
> Pre-medicating isn't even an issue in the first place. I don't know why that's a valid reason. Its not been explained at all why its an issue.

Looks more like an attempt to make the medical system more interesting then a respons to a direct problem. We have a pretty simple med system after all.

2024-09-22 22:50 UTC, Venuska1117 commented
**_We are space marines, you overdosed marine?! 
GET YOUR ASS BACK TO SHIP AND GO TO AUTOSURGERY MACHINE FOR OD TRETAMENT!_**

_*cough*_  my idea to solve this issue is to give autosurgery machine that i forgot name, ability to cure OD's, because if you make chemical, people will just put it in their "Own Mix of chems" and it will remove need to go shipside for OD healing, but thats my idea. (there are some groundsite too)

2024-09-22 23:37 UTC, TheManWithNoHands commented
> __cough__ my idea to solve this issue is to give autosurgery machine that i forgot name

You mean the dialysis mashine?
That already cures OD.
Yb removing all chems.

2024-10-16 16:05 UTC, Nanu308 commented
Painkiller addiction was attempted in the far past and was really bad for Marines and a directly unfun gameplay mechanic to deal with. Going to place DNM on it due to that.

2024-10-27 22:17 UTC, harryob commented
pr is blocked and untouched for two weeks, feel free to ask us to reopen/make a new pr if you work it out with nanu

2024-10-27 22:17 UTC, closed without merging