Adds a version of the CO armor without pauldrons
cmss13-devs/cmss13 pull request #7143
Opened 2024-09-10 13:16 UTC by TheGamerdk

# About the pull request

This is based on the old sprite, and is a stat-identical version of the normal CO armor, minus the pauldrons.

Nessie is behind this, please refer criticism that way. (Unless it's the code, that's on me)

# Explain why it's good for the game

More choices for drip baby!

# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

![image](https://github.com/user-attachments/assets/dd9a32fe-c8fa-40f3-98a2-d98438e74b21)

Can only pick 1:
![image](https://github.com/user-attachments/assets/5640c65e-1b14-4809-8f4a-09ce823c25cc)

Worn:
![image](https://github.com/user-attachments/assets/9c4557b8-934a-4a28-bba8-877a4ffe7b07)

</details>

# Changelog
:cl:
add: COs have a new variant of their armor to choose from
/:cl:

2024-09-10 13:35 UTC, Contrabang commented on code/game/machinery/vending/vendor_types/crew/commanding_officer.dm
> +		list("Commanding Officer's M3 Armor (No Pauldrons)", 0, /obj/item/clothing/suit/storage/marine/MP/CO, MARINE_CAN_BUY_ARMOR, VENDOR_ITEM_MANDATORY),
```suggestion
		list("Commanding Officer's M3 Armor (No Pauldrons)", 0, /obj/item/clothing/suit/storage/marine/MP/CO/no_pauldrons, MARINE_CAN_BUY_ARMOR, VENDOR_ITEM_MANDATORY),
```

2024-09-10 13:40 UTC, TheGamerdk commented on code/game/machinery/vending/vendor_types/crew/commanding_officer.dm
> +		list("Commanding Officer's M3 Armor (No Pauldrons)", 0, /obj/item/clothing/suit/storage/marine/MP/CO, MARINE_CAN_BUY_ARMOR, VENDOR_ITEM_MANDATORY),
i forgot to push my last commit, oops

2024-09-10 18:30 UTC, Blundir requested changes
I do not really support it for consistency reasons, if you want to make pauldron-less version, use the main CO armor for it, the previous officer armor was a placeholder, inform the spriter

2024-09-11 09:36 UTC, TheGamerdk commented
> I do not really support it for consistency reasons, if you want to make pauldron-less version, use the main CO armor for it, the previous officer armor was a placeholder, inform the spriter

Updated the sprites. I can update the in-game example screenshots if you want, but seems unnecessary

2024-09-18 01:10 UTC, efzapa commented
wouldn't it be better to just make it togglable like how you can roll down your uniform since there is no stat difference anyways

no need for item bloat here tbh

2024-12-10 17:26 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-12-16 10:53 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-12-16 11:24 UTC, Blundir approved these changes

2024-12-16 11:34 UTC, merged