Fax Responders
cmss13-devs/cmss13 pull request #7164
Opened 2024-09-14 19:52 UTC by realforest2001

# About the pull request

This project is intended to update and overhaul the fax machines, in regards to who can contact who and how. I have implemented some of these changes within this PR already, but more is to come.
It also adds a dedicated role for responding to faxes, split into subsidiary jobs for each main faction (USCM/USCM Provost/WY/TWE/UPP/CLF/CMB)
This role is experimental, and will either be a dedicated staff role, or potentially opened up to players. The method of this opening however is still to be determined, whether it will act like a traditional whitelist, or be operated differently is as of yet unknown.
There is a wiki page for the fax responder role that can be found here: [https://cm-ss13.com/wiki/Fax_Responder](url).

# Explain why it's good for the game

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
add: Added unique identifier to all fax machines.
add: Added a new way to contact fax machines directly, titled Specific Machine Code in the select department setting.
add: Added a Fax Responder role, broken down into subsidiary jobs for each faction. This is currently experimental in handling, and access is restricted.
/:cl:

2024-09-24 20:48 UTC, Drulikar commented on code/modules/gear_presets/fax_responders.dm
> +		uniform.sensor_faction = FACTION_NEUTRAL
```suggestion
```
Removed in https://github.com/cmss13-devs/cmss13/pull/7205

2024-10-05 12:07 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-10-08 05:39 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-10-17 23:48 UTC, Nanu308 approved these changes
neat map, lgtm

2024-10-24 17:29 UTC, Rem1-code commented
USCM HC fax responder is locked out of the remote monitoring computer, and doesn't seem to have access to any paperwork prefabs.

2024-10-25 02:34 UTC, realforest2001 commented
> New setup is **great** and gives a lot of awareness to better prepare faxes ahead of time. Small bugs for your consideration, monitoring camera:
> 
> * Planetary spawnzones sometimes are completely frozen and you can't move. 'riding' the DS down circumvents this.
> * You collide with objects(thankfully, they do not collide with you.) - so you cannot move past mobs but they can move past you. ...Unfortunately you do collide with walls and doors - which means you can open doors up like a ghost.
> 
> Happened on Fiorina and LV-624 respectively once each, so didn't get to test reproducability

I've not noticed any collisions, please let me know if you replicate this.
As for not being able to move the remote cameras, you can't move them unless they are or will be within 5 tiles of a friendly camera. This means no spying on remote parts of the colony unless a camera friendly to you is already there.

2024-11-13 08:36 UTC, MPhonks commented
I can imagine something of a smaller alert similar to when CIC staff or SEA latejoins for the role in common chat made by ARES, "Fax Tubes for USCM Provost have been recalibrated." If you send a fax before then, you could get a warning that it may not be answered. With a fax operator, you can be pretty sure it'll get adressed. Very much a QOL for any roleplaying since there'd be confirmation that what you're writing isn't going to be a timewaste.

2024-11-16 02:21 UTC, realforest2001 commented on code/__DEFINES/mode.dm
> +#define FACTION_LIST_HUMANOID list(FACTION_MARINE, FACTION_PMC, FACTION_WY, FACTION_WY_DEATHSQUAD, FACTION_CLF, FACTION_CONTRACTOR, FACTION_MARSHAL, FACTION_UPP, FACTION_FREELANCER, FACTION_SURVIVOR,
Remind me to put FACTION_FAX back into this before merge, it's removed for TM compat with hunting grounds.

2024-11-17 22:39 UTC, realforest2001 commented on code/__DEFINES/mode.dm
>  #define FACTION_LIST_HUMANOID list(FACTION_MARINE, FACTION_PMC, FACTION_WY, FACTION_WY_DEATHSQUAD, FACTION_CLF, FACTION_CONTRACTOR, FACTION_MARSHAL, FACTION_UPP, FACTION_FREELANCER, FACTION_SURVIVOR,
```suggestion
#define FACTION_LIST_HUMANOID list(FACTION_MARINE, FACTION_PMC, FACTION_WY, FACTION_WY_DEATHSQUAD, FACTION_CLF, FACTION_CONTRACTOR, FACTION_MARSHAL, FACTION_UPP, FACTION_FREELANCER, FACTION_SURVIVOR, FACTION_NEUTRAL, FACTION_COLONIST, FACTION_MERCENARY, FACTION_DUTCH, FACTION_HEFA, FACTION_GLADIATOR, FACTION_PIRATE, FACTION_PIZZA, FACTION_SOUTO, FACTION_YAUTJA, FACTION_ZOMBIE, FACTION_TWE, FACTION_FAX)
```

2024-11-19 10:26 UTC, harryob requested changes

2024-11-19 10:26 UTC, harryob commented on code/modules/client/client_procs.dm
> +
```suggestion
```
🙂

2024-11-19 10:26 UTC, harryob commented on code/game/gamemodes/cm_initialize.dm
> +			//FAX RESPONDER INITIATLIZE\\
```suggestion
			//FAX RESPONDER INITIALIZE\\
```
🤓

2024-11-19 10:26 UTC, harryob commented on code/game/gamemodes/cm_initialize.dm
> +
```suggestion
```

2024-11-19 13:40 UTC, merged