Full-Auto Smartguns
cmss13-devs/cmss13 pull request #717
Opened 2022-07-19 18:57 UTC by Geevies

## About The Pull Request

Smartguns can now only fire in full-auto mode. They no longer scatter over time when firing in full auto mode.

## Why It's Good For The Game

Prevents people from breaking their mice by spam-clicking in single fire mode to get more DPS with no scatter.

## Changelog

:cl:
balance: Smartguns now only have a full-auto firing mode, but full-auto no longer causes scatter over time.
/:cl:

2022-07-19 19:19 UTC, Segrain requested changes

2022-07-19 19:19 UTC, Segrain commented on code/modules/projectiles/guns/smartgun.dm
>  						/obj/item/attachable/burstfire_assembly,
```suggestion
```
No burst - no need for BFA.

2022-07-19 19:21 UTC, stanalbatross requested changes

2022-07-19 19:21 UTC, stanalbatross commented on code/modules/projectiles/gun_helpers.dm
> +		to_chat(usr, SPAN_NOTICE("[src] can only be fired in full auto mode!"))
```suggestion
		to_chat(usr, SPAN_NOTICE("\The [src] can only be fired in full auto mode!"))
```

2022-07-19 19:21 UTC, stanalbatross commented on code/modules/projectiles/gun_helpers.dm
>  		to_chat(usr, SPAN_NOTICE("[src] can only be fired in bursts!"))
```suggestion
		to_chat(usr, SPAN_NOTICE("\The [src] can only be fired in bursts!"))
```

2022-07-20 02:11 UTC, MusselMain commented
Holy shit is this a marine buff?? (but for real this is a good change, I use to get sticky keys warnings constantly while playing SG).

2022-07-20 09:18 UTC, Chainsawicus commented
![image](https://user-images.githubusercontent.com/103772903/179945955-15956bc3-71a2-40d5-a579-ebc7f740468a.png)

fa_delay should be increased to match fire_delay, otherwise you're just nerfing the Smartgun.

2022-07-20 12:21 UTC, hotimep commented
![smartgun](https://user-images.githubusercontent.com/59359762/179980351-8a9e1f6f-45b2-44c2-ad98-5be04c9055fa.gif)

2022-07-20 13:08 UTC, NexusStorm1 commented
If you're just removing single fire, then it's a HUGE nerf for smartgun. Full auto is only 300 RPM while single fire can reach up to 600 RPM, so this is technically a 50% DPS nerf. I think most people who click normally can reach 7-8 cps, so why not make the full-auto RPM reflect that (420-480 RPM)?

2022-07-20 20:08 UTC, stanalbatross requested changes
make full auto fire faster, to a similar level as what can be reached while naturally clicking in single fire (which I believe is around 450-500 rpm)

2022-07-23 03:02 UTC, PhantomEpicness commented
Good. Currently, it simply encourages scroll wheel SG gaming. Why was full auto nerfed in the first place? Literally, no reason to do it.

2022-07-25 12:43 UTC, stanalbatross approved these changes
if sg is too strong after this it can be tweaked down

2022-07-25 12:43 UTC, merged