Adds a preference to show your tag as Queen
cmss13-devs/cmss13 pull request #7190
Opened 2024-09-20 20:27 UTC by Git-Nivrak

# About the pull request
Adds a preference to show your tag as queen

# Explain why it's good for the game
Initially this was added to protect queen players however some people don't mind it and actually want to show off their name and they should be able to do that.
# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog
:cl:
qol: Added a preference to show your tag as Queen, turned off by default.
/:cl:

2024-09-21 22:03 UTC, KingOnBudget commented
Other xenos should be able do this too imo

2024-09-23 07:42 UTC, harryob requested changes

2024-09-23 07:42 UTC, harryob commented on code/modules/client/preferences_savefile.dm
> +	show_queen_name = sanitize_integer(show_queen_name, 0, 1, 1)
the last arg is the default, so this defaults to on

```suggestion
	show_queen_name = sanitize_integer(show_queen_name, FALSE, TRUE, FALSE)
```

2024-09-24 17:25 UTC, harryob approved these changes

2024-09-24 17:33 UTC, merged