Solar Devils (PVE ERT) Changes, Alt IFF Component
cmss13-devs/cmss13 pull request #7193
Opened 2024-09-22 06:33 UTC by private-tristan

# About the pull request
Solar Devils ERT has gotten a large bunch of changes
from biggest to smallest:

Ports #4723's Alternative IFF component it's a component now and can be added to any gun to prevent it from shooting if there's a target with IFF in it.
Solar Devils smartgunner now uses the alt IFF, and is unable to shoot if there is an IFF target in the way.
Solar devils smartgunner now does 25% more damage. (20 -> 25 on AP | 30 -> 37.5 on regular)
All Solar Devils are now capable of using the smartgun if the smartgunner dies.
replaced 2 cells in engi kits with breaching charges
Solar Devils are properly outfitted with shielded welders, causing them to not take eye damage when used.
Solar Devils MK1 mags hold 99 bullets instead of 95
Slightly increased the chance of headgear spawning

Huge thanks to https://github.com/cmss13-devs/cmss13-pve/pull/418 from Doubleumc for existing so I could copy code from it. 

I still need to figure out why the platoon leader refuses to spawn the medkits in backpack for some ungodly reason.

# Explain why it's good for the game
PVE ERT... Must be accurate to PVE. 
SG now has PVE IFF
SG now mimics PVE's absurdly damaging SG without actually doing 60~ damage per shot
99 round mag is sovl

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
add: Solar Devils (PVE) ERT SG now has alternative IFF, and is unable to shoot if an allied target is in the way. It also does 25% more damage.
add: Solar Devils come with shielded blowtorches, causing no eye damage when used
balance: Solar Devils get 99 round MK1 mags instead of 95.
balance: All Solar Devils know how to use smartguns
balance: Replaced 2 cells in the Solar Devil engi kit with breaching charges
Code: Alternative IFF component can be added to any gun to prevent it from shooting past allies
/:cl:

2024-09-22 18:59 UTC, private-tristan commented
> Consider trying to get approval for a balance change to make Mk1 mags 99 by default instead.

I'd really rather not have adminspawn-only ERTs have balance changes for the rest of the game. Mk1 is already (practically) a direct upgrade to the Mk2, and doesn't need a buff.

Thank you for pointing out the Platoon Leader's med skill, I spent way too long staring at the code wondering why it wouldn't work. In PVE the platoon leader has corpsman level skills to treat IB and use pills/kits.

2024-09-23 02:34 UTC, Steelpoint commented
Could make the 99-rnd M41A Mk1 mags be something that all M41A Mk1s can have, but you need to use a screwdriver to add the space for the extra 4 rounds. But if you do this there is a small chance of a jam or something when you fire a fresh magazine. Might be a lot of effort for what is basically 4 extra bullets.

Since the Solar Devils are admin only you get a lot more leeway in how you balance them, but if they are too strong, they become rare to see. I'd say on a power ranking the current iteration of Solar Devils are at the same level as a friendly UPP ERT, perhaps a stepping stone beneath the W-Y PMC ERT. 

I don't believe this change will drastically change how strong the Solar Devils are. 

The IFF change is great, and at the very least it could allow more in-game testing of the two different IFF systems in the future.

2024-10-26 17:26 UTC, harryob requested changes
1 nit otherwise fine

2024-10-26 17:26 UTC, harryob commented on code/modules/projectiles/guns/smartgun.dm
> +	AddComponent(/datum/component/iff_fire_prevention)
do this in Initialize directly

2024-10-28 16:30 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-10-31 16:36 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-10-31 17:13 UTC, harryob commented on code/modules/projectiles/guns/smartgun.dm
> +	AddComponent(/datum/component/iff_fire_prevention)
as in the addcomponent, the rest is in the right place

2024-10-31 22:04 UTC, Nanu308 commented
>PVE ERT... Must be accurate to PVE.

No, it needs to be balanced for PvP. 

Regarding Mk1, the reason in code it was set to 95 instead of 99 is meant to reference the issues Marines had with the M16 and the early 20-round magazines in Vietnam, and it jamming. So they would under-load the magazine to have less jamming occur (18 Rounds). Making a new mk1 just to get it to have 99, is imo quite unneeded. 

Lower the dmg on the SG substantially, rest of the balance changes are fine imo and porting this IFF allows for some testing related to it for PvP CM which i am interested in trying at a later stage.

2024-12-30 23:35 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-12-31 00:01 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-12-31 01:32 UTC, private-tristan commented
Updated the PR now that  #7600 is merged, Solar devils SG is now locked to frontline mode

2024-12-31 16:40 UTC, private-tristan commented
Unsure how to make the balloon alert from activating frontline mode on the PVE SG not cause a runtime due to having no viewer(?)

2025-01-30 15:31 UTC, harryob approved these changes
works for me

2025-01-30 15:41 UTC, merged