Verifying if the queen is dead on check_bloc
cmss13-devs/cmss13 pull request #7225
Opened 2024-09-26 21:07 UTC by Ibessas

# About the pull request
Fixes Issue #7223

Verifying if the queen is dead on check_bloc to prevent playing the sound.
Tested on almayer with dead queen body, dead drone body ade dead crusher body

# Explain why it's good for the game

Fixing bug to improve game quality

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.
Test: https://www.youtube.com/watch?v=kn_JU-B11pg
</details>

# Changelog

:cl:
fix:Verifying if the queen is dead on check_bloc
:cl:

2024-09-28 05:19 UTC, private-tristan commented
uhh... if another queen evos won't it make the other queen corpse start knocking down again/

2024-09-28 15:21 UTC, Ibessas commented
> uhh... if another queen evos won't it make the other queen corpse start knocking down again/

Looking after it

2024-09-29 01:13 UTC, ihatethisengine commented
Just check mob's state instead???

queen.stat == DEAD

2024-09-30 09:44 UTC, realforest2001 requested changes
As suggested, this needs to be checking if the queen is dead AND unregistering the signal if she is.
`if(is_dead())
	UnregisterSignal(src, COMSIG_MOVABLE_PRE_MOVE)
	return
	`

2024-09-30 09:45 UTC, realforest2001 commented on code/modules/mob/living/carbon/xenomorph/castes/Queen.dm
>  	SIGNAL_HANDLER
```suggestion
	SIGNAL_HANDLER
	if(is_dead())
		UnregisterSignal(src, COMSIG_MOVABLE_PRE_MOVE)
		return
		
```

2024-09-30 12:11 UTC, Ibessas commented on code/modules/mob/living/carbon/xenomorph/castes/Queen.dm
> +		if(xeno.hivenumber == hivenumber && hive.living_xeno_queen)
Done, thanks for the suggestion!

2024-10-06 17:01 UTC, realforest2001 approved these changes

2024-10-26 20:21 UTC, harryob commented
by the way, you need to mark your prs as ready to review when you'd like a maintainer to look over and merge

![CleanShot 2024-10-26 at 21 21 34@2x](https://github.com/user-attachments/assets/85112307-a903-4fc5-b40f-4854ea208e0e)

2024-10-26 20:24 UTC, harryob requested changes
> What a problem to unreg signal on proc death?

as mentioned, just put the UnregisterSignal line in /mob/living/carbon/xenomorph/queen/death()

2024-10-26 22:22 UTC, harryob approved these changes

2024-10-26 22:36 UTC, merged