Anchorpoint ERT Station
cmss13-devs/cmss13 pull request #7238
Opened 2024-09-29 11:34 UTC by Steelpoint

# About the pull request

Adds a ERT station for CMB aligned ERT's to return to, or for admin events. The station contains a CMB fax. Anchorpoint is designed to appear larger than it actually is. 

In-game image in screenshot section.

# Explain why it's good for the game

Gives more love to the CMB so they have somewhere official to land. Can also be used for setting up ERTs for events or for holding prisioners. 

Also has a CMB fax for roleplay oppertunities. 

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

![anchorpoint](https://github.com/user-attachments/assets/99ed84ce-2a99-4142-bc70-47d35f9790ec)

</details>

# Changelog

:cl:
mapadd: Anchorpoint has been added as a CMB ERT station. CMB aligned ERT's will return to this station when leaving the USS Almayer. The station also contained a CMB fax machine. 
/:cl:

2024-09-29 11:36 UTC, Steelpoint commented
I was going to have the station contain three landing pads, so multiple ships can land on the same ERT station. However, the game will only ever use 1 of the landing pads when someone leaves on a CMB shuttle, meaning multiple Anchorpoints will be spawned for every CMB shuttle that leave. 

So I've only made one of the landing pads work.

2024-09-29 21:20 UTC, Nanu308 requested changes

2024-09-29 21:20 UTC, Nanu308 commented on maps/templates/lazy_templates/anchorpoint_ert_station.dmm
Requires more work, not up to standard compared to the other ERT stations.

2024-09-30 02:52 UTC, Steelpoint commented on maps/templates/lazy_templates/anchorpoint_ert_station.dmm
In what way? More rooms? More details? Bigger? Smaller? In comparison to some of the ERT stations this map meets similar standards of size, contents, detailing and room.

2024-09-30 08:53 UTC, Steelpoint commented
I've gone ahead and made some cosmetic changes. I'm not really sure exactly what is not "up to standard" so I'll either leave this as it stands or wait for further direction.

2024-10-13 22:01 UTC, LC4492 commented
I suppose you should make a more complex containment site, maybe even with a smaller-sized court. It also should look more CMB-oriented, try looking at Hybrisa's CMB Local Department for inspiration.

2024-10-27 02:14 UTC, closed without merging