adds blinking laser to mortar impact on UPP vs USCM gamemode
cmss13-devs/cmss13 pull request #7239
Opened 2024-09-29 11:52 UTC by cuberound

# About the pull request

humans need more telegraphing for firesupport as they are slow and get harmed a lot by it, impact goes by sounds start playing, 2,5 seconds pass, light starts flashing for one second, light stops flashing and second after that round hits.

# Explain why it's good for the game

trying to make mortar more fair in upcoming UPP vs USCM gamemode

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
balance: add flashing light to mortar impacts for UPP vs USCM gamemode
/:cl:

2024-10-23 05:17 UTC, Wintermote commented
If you wanted to make this more thematic and less gamey, it could be tied into a player's helmet HUD; if they wear the HUD, they get a flashing indication where the mortar will land, and if they don't wear it, then it's just normal mortar warnings.

2024-10-24 18:32 UTC, harryob requested changes

2024-10-24 18:32 UTC, harryob commented on code/modules/cm_marines/equipment/mortar/mortars.dm
> +	if(GLOB.master_mode == "Faction Clash UPP CM")
this does not exist on master

2024-11-19 09:33 UTC, harryob requested changes

2024-11-19 09:33 UTC, harryob commented on code/modules/cm_marines/equipment/mortar/mortars.dm
> +	if(GLOB.master_mode == "Faction Clash UPP CM")
```suggestion
	if(GLOB.master_mode == /datum/game_mode/extended/faction_clash/cm_vs_upp::name)
```

2024-11-19 13:36 UTC, harryob approved these changes

2024-11-19 13:50 UTC, merged