WIP Yautja Clan TGUI Menu
cmss13-devs/cmss13 pull request #7242
Opened 2024-09-29 19:52 UTC by realforest2001

# About the pull request

Converts the Clan UI to TGUI. Hopefully.

# Explain why it's good for the game

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
ui: Converted Yautja Clan UI to TGUI.
/:cl:

2024-10-01 06:55 UTC, harryob requested changes, later dismissed
why is this reverting https://github.com/cmss13-devs/cmss13/pull/4620

2024-10-05 00:29 UTC, realforest2001 commented
> why is this reverting #4620

Unintended

2024-12-25 01:21 UTC, realforest2001 commented
Selecting clan will pick the clan above it in the list

2025-01-02 21:27 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2025-01-27 17:07 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2025-02-10 18:13 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2025-03-17 19:43 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2025-05-09 18:04 UTC, cm13-github commented
<!-- tgs_test_merge_comment -->
## Test merge deployment history:

<details><summary>Test Merge Deployed @ 05/09/2025 18:03:50 +00:00:</summary>

##### Server Instance

[CM13 Live](https://github.com/cmss13-devs/cmss13/deployments/activity_log?environment=TGS%3A+CM13+Live)

##### Revision
Origin: 4a4d5467e0889a350de3b6dfef2d9bc91300eee2
Pull Request: 53452939fb2a5a349da6b3835ff1e91f2f5df61e
Server: 633e5cdf8ed9f3192774c1ef4a1cfb86da89156b
</details>

2025-06-06 20:57 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2025-10-17 04:38 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2026-03-24 19:29 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2026-04-21 17:44 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2026-05-09 06:31 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2026-07-26 02:31 UTC, closed without merging