Abominations (Predaliens) can no longer be gibbed
cmss13-devs/cmss13 pull request #7253
Opened 2024-09-30 21:40 UTC by private-tristan

# About the pull request

See title. the code is the same that prevents queen from gibbing.

# Explain why it's good for the game
Killing a queen is a p. big feat for marines, and marines get to parade the body around or send it to research for points, but abominations don't have the same gib protection despite being super rare to see in a round, and killing it just for it to gib instead of leaving a corpse kinda sucks.

# Testing Photographs and Procedure

Tested and works 

# Changelog

:cl
qol: Abominations (Predaliens) are now gib immune
/:cl:

2024-10-02 01:18 UTC, kiVts approved these changes

2024-10-05 10:56 UTC, harryob requested changes

2024-10-05 10:56 UTC, harryob commented on code/modules/mob/living/carbon/xenomorph/castes/Predalien.dm
> +	death(cause, 1)
```suggestion
	death(cause, gibbed = TRUE)
```

2024-10-05 15:48 UTC, harryob approved these changes

2024-10-05 16:22 UTC, merged