Lobby xeno late join queue information
cmss13-devs/cmss13 pull request #7261
Opened 2024-10-02 04:02 UTC by Drulikar

# About the pull request

This PR adds some xeno queue information when late joining as a xeno from the lobby. It also streamlines the late join xeno from lobby process somewhat (automatically offers observation if there are no afk xenos, and automatically turns on xeno candidacy preference if done so).

There is also misc refactoring and additional autodoc comments for related variables.

# Explain why it's good for the game

Better new player experience and a bit more information for a player on the lobby to determine whether they want to wait in the xeno queue or late join as a marine.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

![example](https://github.com/user-attachments/assets/1293a06e-af0e-40a6-b65d-47ffd9d58227)

</details>

# Changelog

:cl: Drathek
add: Added xeno queue information when attempting a xeno late join from the lobby
qol: Streamlined the xeno late join process from lobby (offers observation and sets xeno preference)
/:cl:

2024-10-02 04:34 UTC, ihatethisengine commented
now let me see the same number as a xeno who just died

2024-10-02 05:30 UTC, Drulikar commented
> now let me see the same number as a xeno who just died

Ok. 
![image](https://github.com/user-attachments/assets/9e54a29a-cfbb-4447-bd3d-f543383e88bb)

2024-10-05 10:39 UTC, harryob requested changes
nits

2024-10-05 10:39 UTC, harryob commented on code/game/gamemodes/cm_initialize.dm
> +				candidate_new_player.larva_queue_cached_message = "Your position would be [position]\th in the larva queue if you observed and were elgible to be a xeno. \
```suggestion
				candidate_new_player.larva_queue_cached_message = "Your position would be [position]\th in the larva queue if you observed and were eligible to be a xeno. \
```

2024-10-05 10:39 UTC, harryob commented on code/modules/mob/new_player/new_player.dm
> +		observer.forceMove(O.loc)
```suggestion
	var/obj/effect/landmark/observer_start/spawn_point = SAFEPICK(GLOB.observer_starts)
	if(istype(spawn_point))
		to_chat(src, SPAN_NOTICE("Now teleporting."))
		observer.forceMove(spawn_point.loc)
```

2024-10-05 10:39 UTC, harryob commented on code/modules/mob/new_player/new_player.dm
> +	var/mob/dead/observer/observer = new /mob/dead/observer(get_turf(pick(GLOB.latejoin)), client.prefs.preview_dummy)
```suggestion
	var/mob/dead/observer/observer = new(get_turf(pick(GLOB.latejoin)), client.prefs.preview_dummy)
```

2024-10-07 03:29 UTC, harryob approved these changes

2024-10-07 03:34 UTC, merged