Fix Xeno huds Alpha Invisibility
cmss13-devs/cmss13 pull request #7271
Opened 2024-10-05 12:44 UTC by Venuska1117

# About the pull request

Makes xeno huds visible for xenos that use alpha to become invisible.

# Explain why it's good for the game

Makes xenos like lurkers more "visible" to other sisters around, now you can see their HUD's and help them when they are in critical, i seen few times that lurkers died near sisters in critical because they were invisible and hard to spot.

# Testing Photographs and Procedure

<details>
<summary>Click HERE to see Videos.</summary>

Before:

https://github.com/user-attachments/assets/b9dc2ca3-53c3-417f-8929-8a637af90acb

After: 

https://github.com/user-attachments/assets/cb9e8f06-e4fc-42d3-bd77-f1b864790cdf

</details>

# Changelog

:cl: Harry, Venuska1117
code: Makes all xeno huds ignore alpha, it makes them visible during invisibility.
/:cl:

2024-10-05 14:33 UTC, RainbowStalin commented
Does this also apply for enemy hives?

2024-10-05 16:02 UTC, Venuska1117 commented
> Does this also apply for enemy hives?

![image](https://github.com/user-attachments/assets/73b8414d-105d-4f07-b9b9-d78b11e304bf)

Yes, because they all share same HEALTH_HUD_XENO, from what i remember it apply on enemy burrowers too.

![image](https://github.com/user-attachments/assets/f9dd0926-65b3-4b98-9896-73aca90d4a74)

There is photo taken from master branch.

2024-10-06 01:44 UTC, ihatethisengine commented
I am pretty sure there was a PR like this years ago (maybe on gitlab) and it was rejected

2024-10-06 13:55 UTC, Unknownity commented
> I am pretty sure there was a PR like this years ago (maybe on gitlab) and it was rejected

https://gitlab.com/cmdevs/colonial-warfare/-/merge_requests/1810

closed on the basis of XvX and HvH issues

2024-10-31 20:46 UTC, Drulikar requested changes
I'm not terribly opposed to this, but I still think the current behavior is preferred over marginally nerfing stealth for xenos. If you are certain you want to move forward with this, consider exploring how you might get the hud unique per hive and ally status to add/remove that hud from that hive. It'll be a moderately sized endeavor to accomplish I think.

Alternatively, make a new hud for all xenos that indicates they are low health but is otherwise hidden. This hud can be the one that uses RESET_ALPHA and it can be as simple as maybe a border around the xeno health bar or something (or even a duplicate of the health HUD, but I think it would be more interesting the other way to help all xenos not just stealthed ones).

2024-11-03 12:03 UTC, closed without merging

2024-11-03 12:03 UTC, Venuska1117 commented
i will re-open this PR after i find a way to make it better.