Fixes Yautja Gear Tracker runtime
cmss13-devs/cmss13 pull request #7272
Opened 2024-10-05 16:55 UTC by realforest2001

# About the pull request

Runtimes bad.

# Explain why it's good for the game

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
fix: Fixes runtime from null areas.
/:cl:

2024-10-06 05:11 UTC, harryob requested changes
null checks everywhere aren't how we deal with runtimes - only the dead_yautja and tracked_item one could be null (as get_area() only fails for items in null space, like after being qdeld). make those respect being nullspaced correctly, and remove the other nullchecks

2024-10-09 09:58 UTC, realforest2001 commented on code/modules/cm_preds/yaut_procs.dm
> +	if(!(location?.flags_area & AREA_YAUTJA_GROUNDS))
```suggestion
	if(!(location.flags_area & AREA_YAUTJA_GROUNDS))
```

2024-10-09 09:58 UTC, realforest2001 commented on code/modules/cm_preds/thrall_procs.dm
> +	if(!(location?.flags_area & AREA_YAUTJA_GROUNDS))
```suggestion
	if(!(location.flags_area & AREA_YAUTJA_GROUNDS))
```

2024-10-09 20:07 UTC, harryob approved these changes

2024-10-09 20:12 UTC, merged