Removes ABR40 from contractor loadouts
cmss13-devs/cmss13 pull request #7286
Opened 2024-10-07 19:00 UTC by CapCamIII

# About the pull request

ABR40 no longer spawns in contractor standard loadouts

# Explain why it's good for the game

The ABR-40 sucks as its balanced as a survivor weapon, so getting it instead of an actual rifle or a shotgun in turn also sucks

# Changelog

:cl:
del: VAISO and VAIPO standards can no longer spawn with the ABR40
/:cl:

2024-10-08 05:21 UTC, Diegoflores31 commented
cant you just buff the VAIPO version ? they have their own subtype , its not the same that the surv one which means you can tweak it winout affecting surv balance

2024-10-08 07:38 UTC, cuberound commented
funny enough the tactical is curently the same as surv one plust attachments perhaps, but yes buffing their subtype instead of removing it might be better decision

2024-10-10 14:01 UTC, Blundir submitted a review, later dismissed
I agree, we have a whole unique version sitting in a closet, just make it better instead of straight removal

2024-10-26 11:40 UTC, harryob requested changes

2024-10-26 11:40 UTC, harryob commented on code/modules/projectiles/guns/rifles.dm
> +	update_attachable(Integrated.slot)
```suggestion
	var/obj/item/attachable/magnetic_harness/integrated = new(src)
	integrated.flags_attach_features &= ~ATTACH_REMOVABLE
	integrated.hidden = TRUE
	integrated.Attach(src)
	update_attachable(integrated.slot)
```

2024-10-26 11:40 UTC, harryob approved these changes

2024-10-26 11:54 UTC, merged