Makes Resin Salve only go on CD after successful activations, not attempted ones
cmss13-devs/cmss13 pull request #7301
Opened 2024-10-12 12:26 UTC by Tyranicranger4

# About the pull request

#6847 introduced a cooldown to the healer drone's salve ability. Specifically, it was set to apply on an attempted activation of the ability, not just on a successful activation of it. 

This has made the usage of the ability, and thus healer in general, feel more clunky. It's not an ability like warrior's lunge where the way the cooldown is applied has considerable balancing concerns, so this moves the cooldown to successful activations only.

Also removes the notification for the resin salve cooldown expiring. It's a 0.5 second cooldown, it doesn't need a notification.

# Explain why it's good for the game

QoL. Makes the main ability of the healer caste feel less clunky and overall nicer to use.
Considering that the old version of this ability didn't even have a cooldown, I don't see this affecting balance in any meaningful way.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

https://streamable.com/wuyf3t

</details>

# Changelog

:cl:
qol: Makes Resin Salve only go on CD after successful activations, not attempted ones
qol: Removes the chat notification for Resin Salve going off CD (it's a 0.5 second CD)
/:cl:

2024-10-26 15:40 UTC, harryob requested changes

2024-10-26 15:40 UTC, harryob commented on code/modules/mob/living/carbon/xenomorph/strains/castes/drone/healer.dm
> +	for(var/datum/action/xeno_action/activable/apply_salve/source_action in usr.actions)
```suggestion
	for(var/datum/action/xeno_action/activable/apply_salve/source_action in actions)
```

2024-12-15 21:14 UTC, harryob commented
you still need to commit the change here

2024-12-16 01:48 UTC, Tyranicranger4 commented
Totally didn't forget about this PR 😄

2024-12-16 09:06 UTC, harryob approved these changes

2024-12-16 09:45 UTC, merged