Medic qol: Build Your Own Revival Mix!
cmss13-devs/cmss13 pull request #7322
Opened 2024-10-16 07:37 UTC by SpypigDev

# About the pull request
Adds a new type of chem dispenser around the Almayer, usable by Medics to fill their own custom revival mix canisters.

Places 2 pressurized chem dispensers in Medbay lobby, and one in each squad HM prep rooms

Vendors stock basic chemicals, and only allow pressurized reagent canisters to be connected

# Explain why it's good for the game

Pressurized reagent canisters are an extremely important aspect of HM gameplay, and this PR acts to remedy the following issues:
- Reagent canisters are really annoying to refill during an operation (since you need a Doctor to do it for you), and are even more annoying to customize before drop, since Medbay staff are usually extremely busy
- Serves to reduce gear overcrowding in HM vendors, eliminating the need to stock a dozen different varieties of Revival Mix, allowing Medics to build their own canister types with ease, and to match their own unique playstyle 

# Testing Photographs and Procedure

![Screenshot 2024-10-16 174055](https://github.com/user-attachments/assets/3ac29c91-49f6-4122-b5f3-0bb9e3f18cd8)

![Screenshot 2024-10-16 174430](https://github.com/user-attachments/assets/cb9d36ce-824f-476f-84b5-97ba4d872d16)

# Changelog
:cl:
add: Pressurized Chemical Dispenser
/:cl:

2024-10-16 08:02 UTC, tallfission commented
the one thing that might make me play medic again.........

2024-10-16 10:21 UTC, Kyogon commented
As a medic main (when I am on marine side that is..) this would make prep so much less of a pain. I love this.

And to those worried about chemline being impacted: It won't affect chemline's main purpose at all, being mixed chemicals. All these options are available in bottle form in vendors already, this just makes it less annoying and finicky.

And considering we've had rounds where most of the medics don't even deploy due to prolonged prep, this is sorely needed.

2024-10-16 10:47 UTC, SweaterKittens commented
> And to those worried about chemline being impacted: It won't affect chemline's main purpose at all, being mixed chemicals. All these options are available in bottle form in vendors already, this just makes it less annoying and finicky.

With the current state of the vendor/dispenser resource generation, someone asking for their tank to be filled with 500u of Bicaridine or something can hinder the chemline drastically. This lets medics get their tanks set up with out slowing the line to a halt which will be nice, and doctors can focus on high-tier meds or adding custom ingredients if they're wanted.

2024-10-26 11:17 UTC, harryob requested changes
i'm aware these nits make it inconsistent but the old code is WRONG

2024-10-26 11:17 UTC, harryob commented on code/modules/reagents/chemistry_machinery/chem_dispenser.dm
> +		icon_state = (beaker?"[base_state]1":"[base_state]0")
```suggestion
		icon_state = (beaker ? "mixer1_b" : "mixer0_b")
	else if(stat & NOPOWER)
		icon_state = (beaker ? "[base_state]1_nopower" : "[base_state]0_nopower")
	else
		icon_state = (beaker ? "[base_state]1" : "[base_state]0")
```

2024-10-26 11:17 UTC, harryob commented on code/modules/reagents/chemistry_machinery/chem_dispenser.dm
> +		if(pressurized_only && !istype(attacking_object,/obj/item/reagent_container/glass/pressurized_canister))
```suggestion
		if(pressurized_only && !istype(attacking_object, /obj/item/reagent_container/glass/pressurized_canister))
```

2024-10-26 11:17 UTC, harryob commented on code/modules/reagents/chemistry_machinery/chem_dispenser.dm
> +	)
```suggestion
	ui_title = "Chem Dispenser 4000"
	req_skill_level = SKILL_MEDICAL_MEDIC
	accept_beaker_only = FALSE
	pressurized_only = TRUE
	dispensable_reagents = list(
		"bicaridine",
		"kelotane",
		"anti_toxin",
		"dexalin",
		"inaprovaline",
		"adrenaline",
		"peridaxon",
		"tramadol",
		"tricordrazine",
	)
	
	var/base_state = "mixer"
```

2024-10-27 21:45 UTC, harryob approved these changes

2024-10-27 21:55 UTC, merged