Ammo box changes
cmss13-devs/cmss13 pull request #734
Opened 2022-07-23 11:27 UTC by JeserTheFox

## About The Pull Request

1. Ammo boxes now support stacking! Compact storaging is best storaging! 2 per tile for regular ammo boxes, 4 per tile for misc ammo boxes (nail ammo ones have no stacking because of snowflake sprite, god I hate it so much).
2. Reworked explosion when flaming ammo boxes. Boxes explosion now scales with amount of rounds inside. Our very safe cardboard ammo boxes prevent explosion if amount of rounds inside does not hit a certain threshold. (Eliminates the use of rounds boxes and 1 round inside as improvised grenades). Fully loaded boxes now explode harder than before, however.
3. Boxes now have burning time, which is reduced depending on amount of bullets inside. If box is going to blow up, it gets different overlay on it.
4. New sprites: "burning" and "burning going to explode" overlays animations, new marking overlay for flare box to be easily identifiable.

Regular boxes stacking:
![dreamseeker_6t3LFPkbJ0](https://user-images.githubusercontent.com/43144601/180602873-da26a4de-a63f-4290-acc7-951ad00b80a4.gif)
Miscellaneous supplies boxes stacking:
![dreamseeker_mNl5kkJNki](https://user-images.githubusercontent.com/43144601/180602878-72a1ecc5-2672-452b-8eca-37c3ab1508cc.gif)
Lower than explosion threshold ammo amount box on fire:
![dreamseeker_S6XoUWCIgY](https://user-images.githubusercontent.com/43144601/180602914-4d6cdbfe-c0f5-489e-981f-b6baef2f96d4.gif)
Flare box on fire:
![dreamseeker_W9R6QaHuYZ](https://user-images.githubusercontent.com/43144601/180602933-bc5f0d7a-7617-4919-9515-db91b6ab4a84.gif)
Full ammo boxes on fire:
![dreamseeker_fJC6DrIGHG](https://user-images.githubusercontent.com/43144601/180602937-4a3d7fc7-a275-4b2d-9312-8a87a260f58e.gif)

## Why It's Good For The Game

Fixes exploitable mechanic, more QoL, more cool animations and explosions!

## Changelog

:cl: Jeser
qol: Supply and logistics workers, rejoice! Ammo boxes became stackable. Regular ammo boxes can be stacked up to 2 per tile, miscellaneous supply boxes (flares and MREs, currently) up to 4 per tile. No stacking for nail gun ammo, because of a snowflake sprite.
qol: Added flare box overlay to make it easier to separate MRE from flare boxes.
balance: Reworked how explosion happens when flaming ammo boxes. 
code: Explosion level scales with amount of rounds inside. Boxes will not explode until amount of rounds inside won't reach a certain threshold. Fully filled boxes explode harder now. 
code: After being flamed, boxes now spend some time being on fire before they will be deleted or explode, during which they receive a new on fire overlay. This time is also based on amount of ammo in the box. If the box is going to blow up, overlay will be slightly different to indicate that.
soundadd: New sprites include burning and burning, going to explode overlays as well as M94 flare box markings overlay.
/:cl:

2022-07-25 12:22 UTC, stanalbatross requested changes

2022-07-25 12:22 UTC, stanalbatross commented on code/modules/projectiles/ammunition.dm
> +/obj/item/ammo_magazine/flamer_fire_act(var/damage, var/datum/cause_data/flame_cause_data)
flamer fuel tanks should not explode

2022-07-25 12:22 UTC, stanalbatross commented on code/modules/projectiles/ammunition.dm
> +/obj/item/ammo_box/proc/apply_fire_overlay(var/will_explode = FALSE)
maybe this should change colour with the colour of the fire like how burning mobs do?

2022-07-25 12:22 UTC, stanalbatross commented on code/modules/projectiles/ammunition.dm
> +	if(limit_per_tile == 4)	//misc boxes (mre, flares etc)
there has got to be a better way

use subtyping procs etc

2022-07-25 12:22 UTC, stanalbatross commented on code/modules/projectiles/ammunition.dm
> +	else if(istype(src, /obj/item/ammo_box/magazine/smg/nailgun))	//this snowflake again
as above

2022-07-25 12:22 UTC, stanalbatross commented on code/modules/projectiles/ammunition.dm
> +				host_box.visible_message(SPAN_WARNING("\The [src] catches on fire and ammunition starts cooking off! Its gonna blow!"))
```suggestion
				host_box.visible_message(SPAN_WARNING("\The [src] catches on fire and ammunition starts cooking off! It's gonna blow!"))
```

2022-07-25 12:22 UTC, stanalbatross commented on code/modules/projectiles/ammunition.dm
> +				visible_message(SPAN_WARNING("\The [src] catches on fire and ammunition starts cooking off! Its gonna blow!"))
```suggestion
				visible_message(SPAN_WARNING("\The [src] catches on fire and ammunition starts cooking off! It's gonna blow!"))
```

2022-07-25 12:22 UTC, stanalbatross commented on code/modules/projectiles/ammunition.dm
> +		to_chat(user, SPAN_DANGER("It's on fire and can explode!"))
```suggestion
		to_chat(user, SPAN_DANGER("It's on fire and might explode!"))
```

2022-07-25 12:22 UTC, stanalbatross commented on code/modules/projectiles/ammunition.dm
> +		to_chat(user, SPAN_DANGER("It's on fire and can explode!"))
```suggestion
		to_chat(user, SPAN_DANGER("It's on fire and might explode!"))
```

2022-07-25 12:22 UTC, stanalbatross commented on code/modules/projectiles/ammunition.dm
> +		to_chat(user, SPAN_DANGER("It's on fire and can explode!"))
```suggestion
		to_chat(user, SPAN_DANGER("It's on fire and might explode!"))
```

2022-07-25 12:22 UTC, stanalbatross commented on code/modules/projectiles/ammunition.dm
> +			to_chat(user, SPAN_WARNING("You can't deploy different size boxes in one place."))
```suggestion
			to_chat(user, SPAN_WARNING("You can't deploy different size boxes in one place!"))
```

2022-07-25 12:22 UTC, stanalbatross commented on code/modules/projectiles/ammunition.dm
> +			to_chat(user, SPAN_WARNING("There is a maximum possible amount of boxes deployed here already."))
```suggestion
			to_chat(user, SPAN_WARNING("You can't cram any more boxes in here!"))
```

2022-07-25 12:22 UTC, stanalbatross commented on code/modules/projectiles/ammunition.dm
> +/obj/item/ammo_box/magazine/flamer_fire_act(var/damage, var/datum/cause_data/flame_cause_data)
this is full of duped code from /ammo_box/flamer_fire_act() and needs to be separated out into procs on /ammo_box (such as for getting severity, and for igniting)

2022-07-25 12:22 UTC, stanalbatross commented on code/modules/projectiles/ammunition.dm
> +/obj/item/ammo_box/magazine/apply_fire_overlay(var/will_explode = FALSE)
why more duped code

2022-07-25 12:22 UTC, stanalbatross commented on code/modules/projectiles/ammunition.dm
> +			to_chat(usr, SPAN_DANGER("It's on fire and can explode!"))
```suggestion
			to_chat(usr, SPAN_DANGER("It's on fire and might explode!"))
```

2022-07-25 12:22 UTC, stanalbatross commented on code/modules/projectiles/ammunition.dm
> +		visible_message(SPAN_NOTICE("[usr] picks up [name]."))
```suggestion
		visible_message(SPAN_NOTICE("[usr] picks up the [name]."))
```

2022-07-25 12:22 UTC, stanalbatross commented on code/modules/projectiles/ammunition.dm
> +		to_chat(user, SPAN_DANGER("It's on fire and can explode!"))
```suggestion
		to_chat(user, SPAN_DANGER("It's on fire and might explode!"))
```

2022-07-25 12:22 UTC, stanalbatross commented on code/modules/projectiles/ammunition.dm
> +		to_chat(user, SPAN_DANGER("It's on fire and can explode!"))
```suggestion
		to_chat(user, SPAN_DANGER("It's on fire and might explode!"))
```

2022-07-25 12:22 UTC, stanalbatross commented on code/modules/projectiles/ammunition.dm
> +		to_chat(user, SPAN_DANGER("It's on fire and can explode!"))
```suggestion
		to_chat(user, SPAN_DANGER("It's on fire and might explode!"))
```

2022-07-25 12:22 UTC, stanalbatross commented on code/modules/projectiles/ammunition.dm
> +		offset_y += -2
same issues as earlier

2022-07-25 12:22 UTC, stanalbatross commented on code/modules/projectiles/ammunition.dm
> +		to_chat(user, SPAN_DANGER("It's on fire and can explode!"))
```suggestion
		to_chat(user, SPAN_DANGER("It's on fire and might explode!"))
```

2022-07-25 12:22 UTC, stanalbatross commented on code/modules/projectiles/ammunition.dm
> +		to_chat(user, SPAN_DANGER("It's on fire and can explode!"))
```suggestion
		to_chat(user, SPAN_DANGER("It's on fire and might explode!"))
```

2022-07-25 12:22 UTC, stanalbatross commented on code/modules/projectiles/ammunition.dm
> +			visible_message(SPAN_WARNING("\The [src] catches on fire and ammunition starts cooking off! Its gonna blow!"))
```suggestion
			visible_message(SPAN_WARNING("\The [src] catches on fire and ammunition starts cooking off! It's gonna blow!"))
```

2022-07-25 12:22 UTC, stanalbatross commented on code/modules/projectiles/ammunition.dm
> +/obj/item/ammo_box/rounds/flamer_fire_act(var/damage, var/datum/cause_data/flame_cause_data)
get rid of this duped code

2022-07-25 12:22 UTC, stanalbatross commented on code/modules/projectiles/ammunition.dm
> +/obj/item/ammo_box/magazine/misc/flares/flamer_fire_act(var/damage, var/datum/cause_data/flame_cause_data)
there is still some duped code in here

2022-07-25 17:43 UTC, stanalbatross requested changes

2022-07-25 17:43 UTC, stanalbatross commented on code/modules/projectiles/ammunition.dm
> +			return
all of this can easily be put into the parent

2022-07-27 11:13 UTC, stanalbatross requested changes

2022-07-27 11:13 UTC, stanalbatross commented on code/modules/projectiles/ammunition.dm
> +	return
this code is STILL duped in three different places

2022-07-27 11:13 UTC, stanalbatross commented on code/modules/projectiles/ammunition.dm
> +	return
duped here

2022-07-27 11:13 UTC, stanalbatross commented on code/modules/projectiles/ammunition.dm
> +	return
and here

all this stuff can be put into a single proc

2022-07-30 12:40 UTC, stanalbatross requested changes
look into reducing the intensity of the explosions of single magazines/handfuls

otherwise fine

2022-07-30 12:40 UTC, stanalbatross commented on code/modules/projectiles/ammo_boxes.dm
> +			to_chat(user, SPAN_NOTICE("You retrieve a [AM] from \the [src]."))
```suggestion
			to_chat(user, SPAN_NOTICE("You retrieve \a [AM] from \the [src]."))
```

2022-07-30 12:40 UTC, stanalbatross commented on code/modules/projectiles/ammo_boxes.dm
> +			addtimer(CALLBACK(src, .proc/explode, src), rand(1, 6) SECONDS)
it seems to just qdel before it ever does the flare thing

2022-08-04 23:07 UTC, stanalbatross approved these changes

2022-08-11 20:39 UTC, JeserTheFox commented
Fixed merge conflict.

2022-08-12 01:14 UTC, nauticall approved these changes
sprites look good! approved

2022-08-12 01:25 UTC, merged