More items count as helmet accessories
cmss13-devs/cmss13 pull request #7355
Opened 2024-10-21 14:50 UTC by Staykeu

# About the pull request

Makes it so glasses, patches, card packs, candles, walkmans and their tapes are considered helmet accessories. I am by no means a coder, so I'm sure there's a mistake in here, otherwise, this has been tested and should work as intended.

# Explain why it's good for the game

Stylet; purely for customization

# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog
:cl: Stakeyng
qol: more items count as helmet accessories (Multiple glasses, walkman/cassettes/cassette pouch, playing cards, uniform patches, candle)
/:cl:

2024-10-21 17:19 UTC, TheManWithNoHands commented
Helmet garb sprites for glasses are missing.

Also you need to ad the glasses to the list of allowed items in helmet slots.
code/module/clothing/head/helmet.dm 
under Line 248

2024-10-22 01:53 UTC, Strobia commented
CAN U PLEASE INCLUDE PINS !!!!!!!!!!!!!!

2024-10-26 11:26 UTC, harryob requested changes

2024-10-26 11:26 UTC, harryob commented on code/game/objects/items/devices/walkman.dm
> +	flags_obj = OBJ_IS_HELMET_GARB
put this on `/obj/item/device/cassette_tape` instead of changing every cassette tape individually

2024-10-26 11:26 UTC, harryob commented on code/modules/clothing/glasses/glasses.dm
> +	flags_obj = OBJ_IS_HELMET_GARB
this is on the parent type, so will be inherited and not needed

2024-10-26 12:39 UTC, harryob approved these changes

2024-10-26 13:09 UTC, merged