faction console and landing zones
cmss13-devs/cmss13 pull request #7370
Opened 2024-10-24 17:43 UTC by cuberound

# About the pull request

adds option for separate faction shuttle flgiht consoles and LZs

# Explain why it's good for the game

curently it is imposible to easily have shuttle with diferent LZs than marine LZs and ERT LZs, this adds faction LZs for future faction ships

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
add: faction shuttle computers functionality
/:cl:

2024-10-27 15:05 UTC, realforest2001 commented on code/modules/shuttle/computers/dropship_computer.dm
> +			continue
I would add a var check here for override, rather than hard coding it being impossible to share LZs

2024-10-28 08:32 UTC, harryob requested changes

2024-10-28 08:32 UTC, harryob commented on code/modules/shuttle/computers/dropship_computer.dm
> +
```suggestion
	var/faction = FACTION_MARINE
	
	/// If this computer should respect the faction variable of destination LZ
	var/use_factions = TRUE

```

2024-10-28 08:32 UTC, harryob commented on code/modules/shuttle/computers/dropship_computer.dm
> +		if(dock.faction != faction)
```suggestion
		if(use_factions && dock.faction != faction)
```

2024-10-28 08:42 UTC, merged