Makes the Light Replacer more normally attainable
cmss13-devs/cmss13 pull request #7381
Opened 2024-10-25 10:13 UTC by TheKillfish

# About the pull request

Adds the Light Replacer to both ComTech and normal tool storage vendors, and adds it to the autolathe recipe list.

# Explain why it's good for the game

The Light Replacer is a niche but handy tool for lighting places a bit more effectively than flares or flashlights can (provided the local APC is still functioning or that there even is one) but has very limited avaliability. Though not a major issue, it'd be nicer to have a way of replacing/aquiring one than having to steal one of the limited few from Upper Engineering, hunting for one groundside, or bugging your local engineers for theirs if they aren't using it (most of whom probably ditched it in their prep area anyway). Plus, it'd make sense that tool vendors would have them in stock and that the autolathe can print replacements.

# Testing Photographs and Procedure
Added it to autolathe recipes and vendors. Found out it didn't have material costs, so added matter values.

# Changelog

:cl: Killfish
add: Added the Light Replacer to tool storage and to the autolathe.
/:cl:

2024-10-25 14:02 UTC, TheKillfish commented
Blundir suggested broken light recycling, so I've done that now.

2024-10-26 10:42 UTC, harryob requested changes

2024-10-26 10:42 UTC, harryob commented on code/modules/power/lighting.dm
> +		src.visible_message(SPAN_DANGER("The [name] shatters."),SPAN_DANGER("You hear a small glass object shatter."))
```suggestion
		visible_message(SPAN_DANGER("[src] shatters."), SPAN_DANGER("You hear a small glass object shatter."))
```

2024-10-26 10:42 UTC, harryob commented on code/game/objects/items/devices/lightreplacer.dm
> +		playsound(src.loc, 'sound/machines/ding.ogg', 5, 1)
```suggestion
		playsound(src, 'sound/machines/ding.ogg', 5, 1)
```

2024-10-26 10:42 UTC, harryob commented on code/game/objects/items/devices/lightreplacer.dm
> +		playsound(src.loc, 'sound/machines/click.ogg', 25, 1)
```suggestion
		playsound(src, 'sound/machines/click.ogg', 25, 1)
```

2024-10-26 10:42 UTC, harryob commented on code/game/objects/items/devices/lightreplacer.dm
> +	playsound(src.loc, 'sound/machines/click.ogg', 25, 1)
```suggestion
	playsound(src, 'sound/machines/click.ogg', 25, 1)
```

2024-10-26 10:42 UTC, harryob commented on code/game/objects/items/devices/lightreplacer.dm
> +			to_chat(user, SPAN_NOTICE("You insert the [L.name] into the [src.name] for recycling."))
```suggestion
			to_chat(user, SPAN_NOTICE("You insert [L] into [src] for recycling."))
```

2024-10-26 10:42 UTC, harryob commented on code/game/objects/items/devices/lightreplacer.dm
> +				to_chat(user, SPAN_NOTICE("You insert the [L.name] into the [src.name]. You have [uses] lights remaining."))
```suggestion
				to_chat(user, SPAN_NOTICE("You insert [L] into [src]. You have [uses] lights remaining."))
```

2024-10-26 10:42 UTC, harryob commented on code/game/objects/items/devices/lightreplacer.dm
> +		return
```suggestion

	playsound(src.loc, 'sound/machines/click.ogg', 25, 1)
	recycle += 1
```
the else clause is redundant as the previous condition returns

2024-11-19 09:33 UTC, closed without merging