Pred bug fixes
cmss13-devs/cmss13 pull request #745
Opened 2022-07-25 14:38 UTC by Joelampost

## About The Pull Request
Fixes the predator end of round bug were predators that self destruct are counted as alive at round end.

Fixed anchored items from appearing on the predator gear tracker 

## Why It's Good For The Game
It fixes two bugs

## Changelog 

:cl: Joe Lampost
fix: Made the predator self destruct actually gib the pred and kill them instead of the fake gib that was added.
fix: Removed anchored items from showing up on the gear tracker
/:cl:

2022-07-25 17:43 UTC, Shad0vvs approved these changes

2022-07-26 17:03 UTC, Geevies requested changes

2022-07-26 17:03 UTC, Geevies commented on code/modules/cm_preds/yaut_bracers.dm
> +		if(I.anchored)
this should be above the honorable carrier check because it'll make the processing a bit faster

2022-07-27 17:04 UTC, Geevies requested changes
they could have a valid reason to attack as simple mob, don't harass them over it

2022-07-27 17:04 UTC, Geevies commented on code/modules/cm_preds/yaut_weapons.dm
> +		return
```suggestion
	if(isanimal(target))
		return
```

2022-07-27 17:06 UTC, merged