anti c4 gamemode flag
cmss13-devs/cmss13 pull request #7459
Opened 2024-10-31 20:26 UTC by cuberound

# About the pull request

adds togglable flag that prevents c4s to be planeted on humans when it is on gamemode

# Explain why it's good for the game

c4ing bodies of other side SUCKS and is hated by every side, if you want it for zombies, go ahead I place it on HvH

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
add: toggleble flag to prevent c4s on human for gamemodes
/:cl:

2024-11-12 09:18 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-11-19 13:54 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-11-19 18:56 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-12-11 17:17 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-12-15 20:49 UTC, harryob requested changes

2024-12-15 20:49 UTC, harryob commented on code/game/gamemodes/round_modifiers.dm
> +	modifier_desc = "Prevents c4 explosives from being planted on dead body."
am i crazy or do the top two not have an implementation on this branch

2024-12-16 09:22 UTC, harryob approved these changes

2024-12-16 09:57 UTC, merged