CC Ovi Fix
cmss13-devs/cmss13 pull request #7487
Opened 2024-11-04 03:41 UTC by BOBAMAx

# About the pull request

You can now ovi/build hives anywhere in the atmospheric processor on CC

# Explain why it's good for the game

being able to ovi and build the core in caves is good

# Testing Photographs and Procedure

# Changelog

:cl: BOBAMA
fix: You can now go on Ovi and build Hive Cores anywhere in the Atmospheric Processor on Chance's Claim
/:cl:

2024-11-04 05:40 UTC, Drulikar requested changes
These are the areas you altered (including by inheritance): 
![image](https://github.com/user-attachments/assets/c0c6cfac-06b5-4d3b-b3d7-069e4b6cef71)

You will likely want to include `north_east_street` as well if you're going to have an island out there that can be ovi (`atmos/cargo_intake`).

Of note, if a map does not specify any unoviable_timer, it will at a minimum include places w/ queen spawn landmarks so thats why there were any places.

2024-11-04 09:14 UTC, BOBAMAx commented
just made it it's own container area that's a child of outdoors/colony_streets. both those yellow areas are actually the same area, so that island is probably just another oversight from the rework as it used to be directly connected to the reactor. Doesn't make any sense to be a child of atmos as it's not in atmos. Also I feel bad I've autorequested nanu like 4 times this week lol.

![cc](https://github.com/user-attachments/assets/83c78877-6174-4d19-b474-205076e5ce22)

2024-11-04 23:42 UTC, Drulikar approved these changes

2024-11-05 01:45 UTC, Drulikar commented
Double checked: 
![image](https://github.com/user-attachments/assets/91ce9247-801f-4d28-ac0e-7eaac9067ff9)

2024-11-05 03:54 UTC, merged