Predator mask attachments!!!
cmss13-devs/cmss13 pull request #7494
Opened 2024-11-04 18:52 UTC by Nomoresolvalou

# About the pull request

Adds in a brand new accessory for predator masks. Simply select if you want it on your preference menu (0 for no accessory, 1 for the accessory) then you will receive it when you claim your equipment. The accessory uses the same style as your mask.

# Explain why it's good for the game

More customization options for yautja is cool, and Thwomp's sprite for the horns is cool as hell. Also, it will be incredibly easy to add in more accessories in the future, just add in the sprites (need to be 32x64 to align correctly onmob) then change the number prompt on the preferences menu, and you're good to go.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>
here's the bone style of the accessory with one of the masks

![image](https://github.com/user-attachments/assets/d86dbe38-9b23-4884-a681-356c2508fef6)

</details>

# Changelog

:cl: Nomoresolvalou, Thwomper
add: Adds a new predator mask accessory
ui: added a selection for mask accessories in yautja prefs
code: infrastructure for adding in new mask accessories
imageadd: added Thwomp's cool as hell horn sprites

/:cl:

2024-11-06 00:37 UTC, Blundir approved these changes

2024-11-06 16:48 UTC, harryob requested changes

2024-11-06 16:48 UTC, harryob commented on code/modules/client/preferences.dm
> +					if(new_predator_accessory_type) predator_accessory_type = floor(text2num(new_predator_accessory_type))
```suggestion
					if(new_predator_accessory_type)
						predator_accessory_type = floor(text2num(new_predator_accessory_type))
```
also validate this is between 0-1. and it should be sanitized. and it should be saved in prefs

2024-11-06 16:58 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-11-07 07:21 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-11-07 14:53 UTC, harryob approved these changes

2024-11-07 14:58 UTC, merged