Nukes Le'pro
cmss13-devs/cmss13 pull request #7499
Opened 2024-11-05 00:40 UTC by Joelampost

# About the pull request
Removes Le'pro from code adds random names for admin spawned preds

# Explain why it's good for the game
Having names for preds spawned by admins is better than it being le'pro

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
add: Added first names for spawned preds
add: Added last names for spawned preds
/:cl:

2024-11-05 01:16 UTC, deathrobotpunch commented
le pro

2024-11-06 17:03 UTC, harryob requested changes

2024-11-06 17:03 UTC, harryob commented on code/_globalvars/lists/names.dm
> +GLOBAL_LIST_INIT(pred_last_names, list("Tha'jo", "ba'ytui", "Thwa'dtei-t'all", "vah'ka"))
isn't it two 's/-s  max

also
```suggestion
GLOBAL_LIST_INIT(pred_last_names, list("Tha'jo", "Ba'ytui", "Thwa'dtei-t'all", "Vah'ka"))
```

2024-11-06 22:42 UTC, harryob approved these changes

2024-11-06 22:47 UTC, merged