Adds a preference for queen auto shove
cmss13-devs/cmss13 pull request #7502
Opened 2024-11-05 07:23 UTC by Red-byte3D

# About the pull request

Makes it so you can toggle the queens automatic shove, this shoulda been how it was from the start

# Explain why it's good for the game

its annoying as fuck to be a warden or stay close to the queen when you constantly get beaten up like youre in an abusive household THIS SHOULD BE ADDED TO THE KING TOO!! BUT ITS ON TM!!!

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
feature: New preference toggle that allows Queen's to pick if they want to automatically shove people they step on or not
/:cl:

2024-11-05 07:34 UTC, Drulikar requested changes

2024-11-05 14:11 UTC, ihatethisengine commented
Wouldn't it be better if autoshove just worked on disarm intent, so you could switch to it on the fly? Or at least make it a toggleable ability. I doubt anyone is going to go in the preferences every time there is a friendly pocket warden around.

2024-11-05 14:14 UTC, ihatethisengine commented on code/modules/mob/living/carbon/xenomorph/castes/Queen.dm
> +		if(xeno.hivenumber == hivenumber && (queen.client?.prefs?.toggle_prefs & TOGGLE_AUTO_SHOVE))
```suggestion
		if(xeno.hivenumber == hivenumber && queen.a_intent == INTENT_DISARM)
```

2024-11-05 14:14 UTC, ihatethisengine commented on code/modules/mob/living/carbon/xenomorph/castes/Queen.dm
> +		if(xeno.hivenumber == hivenumber && (queen.client?.prefs?.toggle_prefs & TOGGLE_AUTO_SHOVE))
Not a review, just an alternative suggestion.

2024-11-06 03:42 UTC, Red-byte3D commented
> Wouldn't it be better if autoshove just worked on disarm intent, so you could switch to it on the fly? Or at least make it a toggleable ability. I doubt anyone is going to go in the preferences every time there is a friendly pocket warden around.

yes im switching to this

2024-11-06 09:17 UTC, Drulikar approved these changes

2024-11-07 02:59 UTC, merged

2024-11-09 19:31 UTC, Yellows91 commented
Does this mean when you have AUTO TACKLE set as OFF that if you swap to DISARM INTENT then you will be able to turn it on for a bit till you swap back over to any other intent?

2024-11-10 07:10 UTC, Drulikar commented
> Does this mean when you have AUTO TACKLE set as OFF that if you swap to DISARM INTENT then you will be able to turn it on for a bit till you swap back over to any other intent?

Intent does not matter.