Weyland-Yutani Intranet Terminal
cmss13-devs/cmss13 pull request #7511
Opened 2024-11-06 02:51 UTC by realforest2001

# About the pull request

Adds a console for navigating the Weyland-Yutani Intranet. As of the moment it's quite barebones, but can be used by the Liaison to control their hidden containment cell.

# Explain why it's good for the game

Makes the containment cell controls more secure, and gives the CL's desk a functional computer.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
add: Added a Weyland-Yutani Intranet Terminal to the CLs office.
/:cl:

2024-11-06 03:17 UTC, deathrobotpunch commented
a few ideas:
remove the personnel console and add that to the console.
add the containment cell cameras to the console as well.
maybe allow it to function as an ATM as well

2024-11-06 16:18 UTC, thevandie commented
Reordered the desk buttons? What was moved and where are they now?

2024-11-07 00:31 UTC, Nanu308 approved these changes
Mapping is fine, cool flasher

2024-11-09 02:34 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-11-11 20:06 UTC, fighterslam commented
Forest requested I put suggestions somewhere he can find/remember them such as the discord, but I figure this works, too.
Liaison-facing changes/additions:

1. Adding the ability to see published research chemicals from the console could be a nice touch. Full DB access is probably too much, especially since the console is just across the hall, but the ability to see their points & published material could be nice. 

2. The ability to see received or sent faxes, preferably with the ability to print them at the photocopier or delete them from the system records, could be a nice touch. 

3. Listening devices are neat. The ability to track those (in the same way the crew monitor does it - just report what area it's in, not a specific tile) or remotely toggle their microphones/rename them could be a good feature. 

4. This is a silly idea, but maybe a word-editor program of some kind. Type up your faxes in the computer and print them out, then send via fax machine! So modern! 

5. Another silly idea. Maybe a way to track W-Y Xenomorphs? The Liaison has the ability to add the W-Y faction to Xenomorph IFF tags, making that a function could be neat. I can also see this being a responder/admin-only feature aswell. 

6. Maybe the Lawyer or Security beacons could be moved to the console instead of the briefcase? Or maybe the briefcase just gives you a 'token' and you have to insert it into the terminal in order for it to actually send out the request. Granted, this does inherently nerf the beacon's usefulness so maybe not. 

7. Perhaps some sort of integration with the Apollo Link Console? Maybe the ability to make a maintenance ticket? Unsure if this is really worth implementing, but maybe you'll think of a better way to do this or get inspiration. 

<hr>
Admin/Responder-facing changes

1. In the same vein, for PMCs, fax responders, etc the ability to check the Liaison's tracker implant could be neat - access level four, perhaps? 

2.  The ability to revoke a Liaison's access to the intranet in the event some Junior goes rogue could be neat. "Your contract has been terminated" vibes.

3. Maybe a PMC/Corporate Security 'overwatch' or tac-map function could be a neat addition. I don't think this is something the Liaison should normally have access to, given they're just a fancy company rep, but it's an idea regardless.

2024-11-12 14:18 UTC, kocial commented
I think this broke CEs ability to release nerve gas

2024-11-15 23:51 UTC, realforest2001 commented on tgui/packages/tgui/interfaces/WYComputer.jsx
> +    <Window theme={themecolor} width={800} height={725}>
```suggestion

  return (
    <Window theme='weyland' width={800} height={725}>
```

2024-11-27 08:04 UTC, fighterslam commented
Another potential idea: It might be neat if you had access to a list of colonists (the dead corpses) or some sort of locator or ID for the colony manager if a corpse for them is spawned in. Something like a personnel file, maybe? "Colony Administrator: Jane Middle-Manager Doe"

2024-12-12 19:44 UTC, fighterslam commented
Another idea for a potential addition: Escape Pod request button. Sends a request to the admins that they can approve/deny to unlock the CL's escape pod, without needing shipwide evacuation to be called.

2024-12-15 21:33 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-12-28 20:04 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-12-28 20:28 UTC, kiVts requested changes
will look at the tgui at a later date

2024-12-28 20:28 UTC, kiVts commented on code/game/machinery/computer/wy_computer.dm
> +/obj/structure/machinery/computer/wy_intranet/attack_hand(mob/user as mob)
```suggestion
/obj/structure/machinery/computer/wy_intranet/attack_hand(mob/user)
```

2024-12-28 20:28 UTC, kiVts commented on code/game/machinery/computer/wy_computer.dm
> +	var/list/obj/structure/machinery/targets = list()
null on destroy

2024-12-31 16:28 UTC, realforest2001 commented
A bit feature bare at the moment. waiting on #5265

2025-01-23 20:19 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2025-01-27 16:45 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2025-02-05 21:23 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2025-02-10 19:00 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2025-02-17 23:37 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2025-04-10 10:08 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2025-04-10 11:18 UTC, cm13-github commented
<!-- tgs_test_merge_comment -->
## Test merge deployment history:

<details><summary>Test Merge Deployed @ 04/10/2025 11:18:18 +00:00:</summary>

##### Server Instance

[CM13 Live](https://github.com/cmss13-devs/cmss13/deployments/activity_log?environment=TGS%3A+CM13+Live)

##### Revision
Origin: 06b76886f7fda4a59c6aa96047573a50fd9f156b
Pull Request: 05c160eb3ae4e142a037ba14f9d38a7148499e10
Server: 0143f1892b9bbe7cfe11efd5b2c2df95e1519a95
</details>

2025-04-25 16:00 UTC, Detective-Google approved these changes
code looks ok, have not reviewed the tgui so that needs looked over.

2025-06-01 00:55 UTC, closed without merging