Human Resprites & Tweaks - Marines looking awesome
cmss13-devs/cmss13 pull request #7521
Opened 2024-11-07 01:12 UTC by Nanu308

# About the pull request
Fixes, tweaks and resprites the body types and muscularity plus the skin tones for humans in the game. Female torso's are now a thing as well, as that is brought back.

# Explain why it's good for the game
Visually better and tweaked skin tones to look better plus female torso added.

# Testing Photographs and Procedure
![oomanExamples](https://github.com/user-attachments/assets/a9dd93d3-a386-44b9-bbda-6c06035403e7)

# Changelog

:cl: Nanu, Wei, Spartanbobby, HarryOb
imageadd: Fixes, tweaks and resprites the body types and muscularity plus the skin tones for humans in the game. Female torso's are now a thing as well, as that is brought back. Sprites created by Wei.
/:cl:

2024-11-07 01:22 UTC, sleepynecrons commented
upvoted

2024-11-07 05:21 UTC, Red-byte3D commented
wheres my bbl marine sprite i dont feel represented

2024-11-07 16:59 UTC, irakligabunia commented
hello where are the sprites without the bras and undergarments i need it to review the spriting work quality and the coloring
thanks
sincerely; pewds

2024-11-08 00:10 UTC, Drulikar requested changes
I'm not sure why but the first time you open the body picker now and change the body presentation, it changes focus back to the slot UI. It will keep doing this until you pick a color?
![why'](https://github.com/user-attachments/assets/d07ab16c-cc49-45ec-9398-5ccc1bd4acb6)

2024-11-09 08:54 UTC, Drulikar approved these changes
Not sure about that weird focus bug. Its like the `winset(user, ui.window.id, "focus=true")` just gets ignored... or the `prefs.ShowChoices(ui.user)` *actually* focuses its window later than normal despite `tgui_interact` getting called after it.

2024-11-09 09:16 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-11-09 09:27 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-11-10 07:17 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-11-10 07:19 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-11-29 12:03 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2025-01-03 21:21 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2025-01-03 21:47 UTC, harryob approved these changes

2025-01-03 22:16 UTC, Blundir requested changes
please get rid of light contrasting pixels on female body torso south direction

2025-01-03 23:28 UTC, Blundir approved these changes

2025-01-03 23:42 UTC, merged