implements a picker for character traits
cmss13-devs/cmss13 pull request #7526
Opened 2024-11-07 14:36 UTC by harryob

we're almost there! only maybe 1-2 more individual prs and then i can make ANOTHER pr JUST to tgui the human screen. kino! kino?

https://github.com/user-attachments/assets/014faf38-1c9a-4bbe-8cd4-d5dea28d1282

after this video i made it so the buttons appeared disappeared when at the cap but i couldn't be bothered to rerecord

:cl:
ui: added a new tgui to select character traits. it's quite similar to the old one
/:cl:

2024-11-07 16:30 UTC, cuberound commented
OMG IT IS TGUI LOBBY TIME

2024-11-07 16:54 UTC, irakligabunia commented
kino called they said movie

2024-11-07 19:30 UTC, TheManWithNoHands commented
kino indeed.
Finally character set up wont look like its from 1997.

2024-11-07 23:50 UTC, Drulikar requested changes
- Traits that are incompatible with other traits ought to be conveyed in some way. E.g. all these buttons are enabled, but nothing happens if you click them since you already have a prosthetic: 
![image](https://github.com/user-attachments/assets/09a7038f-c1ff-419e-865e-ed15250f824e)
- Every launch of the game seems you're given 2 points so you can keep adding more (Does not seem to be an issue on master).
![image](https://github.com/user-attachments/assets/6bb90e80-f4be-42d4-8ae4-c4d844fc3a46)
And it will go negative :p but this likely won't be possible once above is fixed: 
![image](https://github.com/user-attachments/assets/08f6540d-f11b-4ca5-a934-6dd5be4ece59)

2024-11-07 23:50 UTC, Drulikar commented on code/modules/client/preferences.dm
Where we have `// Refresh pickers` in this file, we should also do this new picker. Likely at this point you should just make a proc so shove them all into that proc.

2024-11-07 23:50 UTC, Drulikar commented on code/modules/client/traits_picker.dm
> +	var/datum/preferences/prefs = user.client.prefs
```suggestion
	var/datum/preferences/prefs = user.client?.prefs
```
Also do you want a prefs null test here?

2024-11-07 23:50 UTC, Drulikar commented on code/modules/client/traits_picker.dm
> +	var/datum/preferences/prefs = ui.user.client.prefs
```suggestion
	var/datum/preferences/prefs = ui.user.client?.prefs
```

Also do you want a prefs null test here?

2024-11-07 23:50 UTC, Drulikar commented on code/modules/client/preferences.dm
> -			trait_points -= character_trait.cost
This is likely the logic not retained causing the issue w/ more trait points each launch.

2024-11-08 09:41 UTC, deathrobotpunch commented
Forrest, can you make it so character impairments don’t cost points?

2024-11-08 09:43 UTC, harryob commented
> Forrest, can you make it so character impairments don’t cost points?

who are you talking to?

2024-11-08 09:45 UTC, deathrobotpunch commented
> who are you talking to?

¯\_(ツ)_/¯ I imagine things

2024-11-09 09:16 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-11-09 21:03 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-11-10 07:07 UTC, Drulikar approved these changes

2024-11-10 07:12 UTC, merged