UPP synth HvH job addition
cmss13-devs/cmss13 pull request #7537
Opened 2024-11-08 12:41 UTC by cuberound

# About the pull request
adds job for synth so it shows up in char setup and lobby joining
# Explain why it's good for the game
fixes oversidght that was missed in all the definitions of jobs, already had cryo preset but no datum/job

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
fix: makes UPP synth lobby joinable for events
/:cl:

2024-11-09 04:07 UTC, Nanu308 approved these changes
lgtm

2024-11-10 23:01 UTC, Nanu308 requested changes
i want my spacebars

2024-11-10 23:01 UTC, Nanu308 commented on code/__DEFINES/job.dm
> +#define UPP_JOB_LIST list(JOB_UPP, JOB_UPP_ENGI, JOB_UPP_MEDIC, JOB_UPP_SPECIALIST, JOB_UPP_LEADER, JOB_UPP_POLICE, JOB_UPP_LT_OFFICER, JOB_UPP_LT_DOKTOR, JOB_UPP_SUPPLY, JOB_UPP_SRLT_OFFICER, JOB_UP
```suggestion
#define UPP_JOB_LIST list(JOB_UPP, JOB_UPP_ENGI, JOB_UPP_MEDIC, JOB_UPP_SPECIALIST, JOB_UPP_LEADER, JOB_UPP_POLICE, JOB_UPP_LT_OFFICER, JOB_UPP_LT_DOKTOR, JOB_UPP_SUPPLY, JOB_UPP_SRLT_OFFICER, JOB_UPP_KPT_OFFICER, JOB_UPP_KOL_OFFICER, JOB_UPP_SUPPORT_SYNTH, JOB_UPP_COMMISSAR)
```

2024-11-12 08:56 UTC, harryob approved these changes

2024-11-12 09:04 UTC, merged