Updates spawn message for preds
cmss13-devs/cmss13 pull request #7539
Opened 2024-11-08 17:08 UTC by Joelampost

# About the pull request
Changes the spawn message for preds (council approved)

# Explain why it's good for the game
putting forward to preds that dying is a part of the game and not something to be ashamed of is good

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl: Joe Lampost
Code: Changes the spawn message for predators
/:cl:

2024-11-08 22:33 UTC, efzapa commented
This could be potentially misleading as the Honor Code specified that a death is only Honorable in the case that you destroy yourself and your gear.

Failing to so such is defined as dishonorable, as dying is such.

![Screenshot_20241108_173211_Firefox.jpg](https://github.com/user-attachments/assets/4b4597e7-0e00-4482-b432-440331bf2872)


Though take my input with a grain of salt since I don't even have the WL, just relaying what I know

2024-11-09 04:06 UTC, Nanu308 requested changes

2024-11-09 04:06 UTC, Nanu308 commented on code/game/jobs/job/antag/other/pred.dm
> +	to_chat(new_predator, SPAN_NOTICE("Follow the guidance of your elders and expirenced hunters."))
grammer experienced

2024-11-09 20:41 UTC, harryob approved these changes
honour with a u are we back british bros

2024-11-09 20:50 UTC, merged