Changes Spotter sight for Night vision Binoculars
cmss13-devs/cmss13 pull request #7543
Opened 2024-11-09 09:09 UTC by Diegoflores31

# About the pull request

-removes spotter sight
-Spotter binos now have integrated NVs . currently with unlimited battery on a experimental blueish color as i was told green is anoying on the eyes.

-binos support custom matrix colors in another PR i will make it a preference so the color of all NVGs can be set on player preferences.
 
 
# Explain why it's good for the game

Promotes Spotter teamwork instead of using the kit for PFCing , I also plan to add this to the AMR/M42A scope.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
balance: Spotter designator now has integrated Night Vision
removal: Removes M41 Spotter sight
/:cl:

2024-11-09 09:21 UTC, Diegoflores31 commented
![image](https://github.com/user-attachments/assets/73da2d72-1735-499b-a8dc-178b477f0289)

2024-11-09 14:12 UTC, Red-byte3D commented
There's literally 0 reason to make this change, shit like this already hurts peoples eyes immensely, i remember taking a break from pred because the same filter quite literally made it so my eyes started watering up. Annoying change just so you can change stuff

2024-11-09 14:56 UTC, Deathrobotpunchalt commented
NV filter is aids

2024-11-09 15:09 UTC, irakligabunia commented
being blind in real life whilst playing this game is like the  worst fate ever because PRs like this exist to make you even blinder

2024-11-09 22:49 UTC, SASoperative commented
I actually think this would be healthy addition for marines, however, I would prefer it if it kept the current form of NVGs that aliens tend to have, solely due to how harsh the NVG overlay can be on the eyes.

2024-11-09 23:00 UTC, Diegoflores31 commented
> I actually think this would be healthy addition for marines, however, I would prefer it if it kept the current form of NVGs that aliens tend to have, solely due to how harsh the NVG overlay can be on the eyes.

the matrix has to stay . the reason for it is to "show" that marine NV arent perfect as the natural NV that aliens have .
I did hear the complains about being a strain in the eyes . i will soon implement a prefference option so you can chance the colors of all NVGS  and make the blur more translucent

2024-11-09 23:15 UTC, SASoperative commented
> > I actually think this would be healthy addition for marines, however, I would prefer it if it kept the current form of NVGs that aliens tend to have, solely due to how harsh the NVG overlay can be on the eyes.
> 
> the matrix has to stay . the reason for it is to "show" that marine NV arent perfect as the natural NV that aliens have . I did hear the complains about being a strain in the eyes . i will soon implement a prefference option so you can chance the colors of all NVGS and make the blur more translucent

I believe that would be a healthy alternative, my main complaint is just the strain it can provide on the eyes, more so with extensive or extended use. Would this change in the future be applicable or planned to be applicable to the scopes when they are altered, or the helmet mounted NVGs? It would be a very nice QoL feature to have for more than a spotter if you do it!

2024-11-10 05:05 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-11-10 05:15 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-11-10 05:30 UTC, Diegoflores31 commented
> I believe that would be a healthy alternative, my main complaint is just the strain it can provide on the eyes, more so with extensive or extended use. Would this change in the future be applicable or planned to be applicable to the scopes when they are altered, or the helmet mounted NVGs? It would be a very nice QoL feature to have for more than a spotter if you do it!

Done ! , all NVGs now have preference in colors . there is 5 colors to choose from . I will probably also add this preference for CAS cameras too

2024-11-12 08:15 UTC, joookschad commented
Can you show how the NVG's look with each preference?

2024-12-15 18:42 UTC, harryob requested changes
this why it's good for the game does not justify this change- remove changing the spotter sight. pref is fine

2025-01-01 18:22 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2025-01-04 21:06 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2025-01-13 15:25 UTC, harryob requested changes

2025-01-13 15:25 UTC, harryob commented on code/_globalvars/global_lists.dm
> +GLOBAL_LIST_INIT(nvg_color_list, list("Green", "White", "YELLOW", "Orange", "Red", "Blue"))
why is yellow capitalised

2025-01-13 15:25 UTC, harryob commented on code/modules/client/preferences.dm
> +							night_vision_color = NV_COLOR_GREEN
don't save this separate to the pref, just make an assoc list of "Green" = NV_COLOR_GREEN, etc, and look that up instead on liek 335 of helmetgarb.dm

2025-01-20 04:54 UTC, kiVts requested changes

2025-01-20 04:54 UTC, kiVts commented on code/modules/client/preferences_savefile.dm
> +	if(!night_vision_color) night_vision_color = NV_COLOR_GREEN
no inline ifs

2025-01-20 06:45 UTC, Diegoflores31 commented on code/modules/client/preferences_savefile.dm
> +	if(!night_vision_color) night_vision_color = NV_COLOR_GREEN
i just deleted it . i realize is not necesary anyways

2025-01-23 11:45 UTC, harryob commented
![YdA8qgDhQhio0DmO@2x](https://github.com/user-attachments/assets/525b7cc3-40d7-4973-a924-c1af68b6b4b5)

2025-01-25 02:20 UTC, kiVts approved these changes

2025-01-25 02:29 UTC, merged