Adds ability for admins to end round with a custom ending + upp ending icon
cmss13-devs/cmss13 pull request #7548
Opened 2024-11-09 15:58 UTC by Blundir

# About the pull request

Mostly a port of [https://github.com/tgstation/TerraGov-Marine-Corps/pull/1511](https://github.com/tgstation/TerraGov-Marine-Corps/pull/1511/files)

Round end now has the actual text of the round end result 

![dreamseeker_yIuIyWkNga](https://github.com/user-attachments/assets/831b662f-4c1c-45b8-98a0-be31d6518320)

Upp vs USCM mode now has some bits of code behind them so the round end music and icon triggers correctly

![dreamseeker_UFkKF4efBg](https://github.com/user-attachments/assets/7a0711e8-66b6-4523-bb95-929ee4b686e2)

# Testing Photographs and Procedure

<details>

![WPxQcvzEPX](https://github.com/user-attachments/assets/e31ab3f1-55d5-4a82-993d-27906bad3bbe)

</details>

# Changelog

:cl:
add: added ability for admins to end round with a custom ending result 
add: round ending result is now shown in chat
add: some simple UPP vs USCM factions clash round end code that can now be triggered by admins
/:cl:

2024-11-11 08:07 UTC, kiVts requested changes

2024-11-11 08:07 UTC, kiVts commented on code/game/gamemodes/extended/cm_vs_upp.dm
> +	return 1
```suggestion
	return TRUE
```

2024-11-11 08:07 UTC, kiVts commented on code/game/gamemodes/extended/cm_vs_upp.dm
> +	var/sound/S = sound(musical_track, channel = SOUND_CHANNEL_LOBBY)
single letter var

2024-11-11 08:07 UTC, kiVts commented on code/modules/admin/tabs/round_tab.dm
> +			return
```suggestion

	if(winstate == "Custom")
		winstate = tgui_input_text(usr, "Please enter a custom round end state.", "End Round", timeout = 0)
	if(!winstate)
		return
```

2024-11-26 17:49 UTC, realforest2001 commented
Off TM due to conflict with #7600

2024-11-29 08:16 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-11-29 08:25 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-12-30 23:35 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2025-01-17 12:53 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2025-01-17 17:40 UTC, closed without merging

2025-01-18 12:23 UTC, Blundir commented
integrated into another pr