Project Sugarwater P2: Comprehensive HM Tutorials
cmss13-devs/cmss13 pull request #7555
Opened 2024-11-10 06:09 UTC by SpypigDev

# About the pull request

Project Outline
<details><summary>Hospital Corpsman Basic Tutorial</summary>
// ------------ CONTENTS ------------ //<br>
//<br>
// Section 0 - Equipment and You<br>
//<br>
// Section 1 - Basic Damage Treatment<br>
// 1.1 Brute Damage<br>
// 1.2 Burn Damage<br>
// 1.3 Treating Bleeding<br>
// 1.4 Shrapnel Removal<br>
// 1.5 Bone Fractures<br>
//<br>
// Section 2 - Intermediate Damage Treatment<br>
// 2.1 Pain Levels<br>
// 2.2 Toxin Damage<br>
// 2.3 Overdoses<br>
//<br>
</details>
<details><summary>Hospital Corpsman Intermediate Tutorial</summary>

// ------------ CONTENTS ------------ //
//
// Section 1 - Stabilizing Types of Organ Damage
// 1.1 Internal Organ Damage (Chest)
// 1.2 Heart Damage
// 1.3 Lung Damage
// 1.4 Internal Organ Damage (Head)
// 1.5 Liver and Kidney Damage
//
// Section 2 - Revivals
// 2.1 Defibrillations
// 2.2 Revival Conditions
// 2.3 Delivering CPR
// 2.4 Assisted Revivals
//
// Section 3 - Field Surgery
// 3.1 Surgical Damage Treatment
// 3.2 Internal Bleeding
//
// Section 4 - Medical Evacuations, Stasis
//
</details>

# Explain why it's good for the game
More people must play medic
# Testing Photographs and Procedure

Screenshots & Videos

![image](https://github.com/user-attachments/assets/0d04df98-7f32-4f62-8d4b-1be4426d34dc)
Sandbox mode in action

# Changelog
:cl: Spypig23, detectivegoogle, harryob
add: HM Tutorials
mapadd: Added medical-themed 7x7 and 15x10 tutorial maps
refactor: Reworked code for roller beds, bodybags, and stasis bags to allow continuous tracking
fix: IA pill bottles and Vials now display working icons in vendor UI
fix: Surgery area covered warnings no longer trigger when not doing invasive surgery
ui: Added support for tutorial subsections
/:cl:

2024-11-14 05:59 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-11-14 06:25 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-11-29 13:04 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-12-01 16:22 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-12-27 18:12 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-12-28 05:53 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2025-01-27 18:19 UTC, Nanu308 approved these changes
Mapping lgtm

2025-01-29 00:59 UTC, Zonespace27 reviewed
Everything but the tutorials

2025-01-29 00:59 UTC, Zonespace27 commented on code/__DEFINES/dcs/signals/atom/signals_obj.dm
> +/// from /proc/vendor_successful_vend() : (datum/source, obj/structure/machinery/cm_vending/vendor, obj/item/new_item, mob/living/carbon/human/user)
datum/source usually isn't included in these comments

2025-01-29 00:59 UTC, Zonespace27 commented on code/_globalvars/bitfields.dm
> +	"FAKESOUL" = FAKESOUL
```suggestion
	"FAKESOUL" = FAKESOUL,
```

2025-01-29 00:59 UTC, Zonespace27 commented on code/datums/tutorial/_tutorial.dm
> +/datum/tutorial/proc/left_align_message_to_player(message)
this should be documented

2025-01-29 00:59 UTC, Zonespace27 commented on code/datums/mob_hud.dm
> +						var/mob/dead/observer/G = get_ghost(FALSE, TRUE)
line 459 and 460 can be compacted together

2025-01-29 00:59 UTC, Zonespace27 commented on code/game/machinery/vending/vendor_types/medical.dm
> +/obj/structure/machinery/cm_vending/sorted/medical/tutorial
please try and figure out a better way of doing this

2025-01-29 00:59 UTC, Zonespace27 commented on code/game/objects/items/devices/defibrillator.dm
> +		if(!(target.status_flags & FAKESOUL)) // Makes sure we dont accidentally expose something for what it truly is
can be compacted

2025-01-29 00:59 UTC, Zonespace27 commented on code/game/objects/items/devices/flashlight.dm
> +	SEND_SIGNAL(user, COMSIG_LIVING_PENLIGHT_USED, being)
the signal's name sounds like the being should be the target

2025-01-29 00:59 UTC, Zonespace27 commented on code/game/objects/items/bodybag.dm
> +	if(src.contents.len == 0)
use length() not len, also no need for src

2025-01-29 00:59 UTC, Zonespace27 commented on code/game/objects/items/bodybag.dm
>  /obj/item/bodybag/proc/deploy_bodybag(mob/user, atom/location)
why change this at all?

2025-01-29 00:59 UTC, Zonespace27 commented on code/game/objects/items/bodybag.dm
>  	..()
same here

2025-01-29 00:59 UTC, Zonespace27 commented on code/game/objects/items/bodybag.dm
> +			undeployed = new item_path(src.contents)
no need for src

2025-01-29 00:59 UTC, Zonespace27 commented on code/game/objects/items/bodybag.dm
>  		if(!ishuman(usr)) return
don't oneline this stuff

2025-01-29 00:59 UTC, Zonespace27 commented on code/game/objects/items/bodybag.dm
> +		else if(length(contents) > 1) return 0
ditto

2025-01-29 00:59 UTC, Zonespace27 commented on code/game/objects/structures/crates_lockers/closets.dm
> +	if(!istype(src, /obj/structure/closet/bodybag)) // accounts for bodybag refactor
this is a hack

2025-01-29 00:59 UTC, Zonespace27 commented on code/game/objects/structures/stool_bed_chair_nest/bed.dm
> +/obj/structure/bed/roller/MouseDrop(atom/over_object)
why get rid of attackby() functionality?

2025-01-29 00:59 UTC, Zonespace27 commented on code/game/objects/structures/stool_bed_chair_nest/bed.dm
> +		var/mob/living/carbon/human/H = over_object
no one letter vars

2025-01-29 00:59 UTC, Zonespace27 commented on code/game/objects/structures/stool_bed_chair_nest/bed.dm
> +				SPAN_WARNING("You grab [src] from the floor!!"))
!!

2025-01-29 00:59 UTC, Zonespace27 commented on code/game/objects/structures/stool_bed_chair_nest/bed.dm
> +		if(src.contents.len == 0)
no src, use length()

2025-01-29 00:59 UTC, Zonespace27 commented on code/game/objects/structures/stool_bed_chair_nest/bed.dm
> +			if (H==usr && !H.is_mob_incapacitated() && Adjacent(H) && in_range(src, over_object))
```suggestion
			if (H == usr && !H.is_mob_incapacitated() && Adjacent(H) && in_range(src, over_object))
```

2025-01-29 00:59 UTC, Zonespace27 commented on code/game/objects/structures/stool_bed_chair_nest/bed.dm
> +	if(src.contents.len == 0)
src, length()

2025-01-29 00:59 UTC, Zonespace27 commented on code/game/objects/structures/stool_bed_chair_nest/bed.dm
> +/obj/item/roller/proc/deploy_roller(mob/user, atom/location)
code doc

2025-01-29 00:59 UTC, Zonespace27 commented on code/game/objects/structures/stool_bed_chair_nest/bed.dm
> +	var/prop
code doc

2025-01-29 00:59 UTC, Zonespace27 commented on code/game/objects/structures/stool_bed_chair_nest/bed.dm
> +		to_chat(user, SPAN_NOTICE("[src]'s beacon locked on default setting!"))
```suggestion
		to_chat(user, SPAN_NOTICE("[src]'s beacon is locked in the [stretcher_activated ? "\"on\" : "\"off\""] position."))
```

2025-01-29 00:59 UTC, Zonespace27 commented on code/modules/gear_presets/other.dm
> +	var/mob_name = "Dummy"
why is this a var

2025-01-29 00:59 UTC, Zonespace27 commented on code/modules/mob/living/carbon/human/human_attackhand.dm
> +					var/successful
default value

2025-01-29 00:59 UTC, Zonespace27 commented on code/modules/mob/living/carbon/human/human_attackhand.dm
> +					var/successful
also this doesn't need to be a var

2025-01-29 00:59 UTC, Zonespace27 commented on code/modules/mob/living/carbon/human/human_dummy.dm
> +	if((round(health*100/species.total_health, 10)) >= 70)
```suggestion
	if((round(health * 100 / species.total_health, 10)) >= 70)
```

2025-01-29 00:59 UTC, Zonespace27 commented on code/modules/mob/living/living_health_procs.dm
why the changes here

2025-01-29 00:59 UTC, Zonespace27 commented on code/modules/mob/living/living_healthscan.dm
> +		if(!(target_mob.status_flags & FAKESOUL))
compact these lines

2025-01-29 00:59 UTC, Zonespace27 commented on code/modules/surgery/surgery_initiator.dm
> +		if(blocker && tool.sharp)
why

2025-02-02 03:58 UTC, Zonespace27 commented on code/datums/tutorial/_tutorial.dm
> +	var/datum/callback/next_tutorial_step
code doc

2025-02-02 03:58 UTC, Zonespace27 commented on code/datums/tutorial/_tutorial.dm
> +/datum/tutorial/proc/manual_message_to_player(message)
code doc

2025-02-02 03:58 UTC, Zonespace27 commented on code/datums/tutorial/_tutorial.dm
> +	var/datum/weakref/tutorial
code doc

2025-02-02 03:58 UTC, Zonespace27 commented on code/datums/tutorial/_tutorial.dm
> +/datum/tutorial/proc/register_tutorial_step(datum/callback/callback)
code doc

2025-02-02 03:58 UTC, Zonespace27 commented on code/datums/tutorial/_tutorial.dm
> +/datum/tutorial/proc/handle_tutorial_step()
code doc

2025-02-02 04:02 UTC, Zonespace27 commented on code/datums/tutorial/_tutorial.dm
> +/datum/tutorial/proc/handle_tutorial_step()
also pressing this button as the tutorial ends runtimes

2025-02-02 04:28 UTC, Zonespace27 reviewed
Basic tutorial. If I commented on spelling/punctuation/etc. I didn't go through to fix every scenario of it, you'll need to do that yourself.

2025-02-02 04:28 UTC, Zonespace27 commented on code/datums/tutorial/marine/role_specific/hospital_corpsman_basic.dm
> +
You should remove the surgery mode button

2025-02-02 04:28 UTC, Zonespace27 commented on code/datums/tutorial/marine/role_specific/hospital_corpsman_basic.dm
> +/datum/tutorial/marine/role_specific/hospital_corpsman_basic/proc/scanner_2()
You're missing SIGNAL_HANDLERs throughout

2025-02-02 04:28 UTC, Zonespace27 commented on code/datums/tutorial/marine/role_specific/hospital_corpsman_basic.dm
> +	manual_message_to_player("Next, you should get to know a Medics second best friend on the field, the <b>HealthMate HUD</b>.")
```suggestion
	manual_message_to_player("Next, you should get to know a Medic's second best friend on the field, the <b>HealthMate HUD</b>.")
```

2025-02-02 04:28 UTC, Zonespace27 commented on code/datums/tutorial/marine/role_specific/hospital_corpsman_basic.dm
> +	manual_message_to_player("As you progress through the following sections of the tutorial, pay attention to how the Dummys healthbar changes with different injuries.")
```suggestion
	manual_message_to_player("As you progress through the following sections of the tutorial, pay attention to how the Dummy's healthbar changes with different injuries.")
```
should dummy be capitalized?

2025-02-02 04:28 UTC, Zonespace27 commented on code/datums/tutorial/marine/role_specific/hospital_corpsman_basic.dm
> +	manual_message_to_player("While not as detailed as a Health Analyzer scan, your <b>HealthMate HUD</b> will display a healthbar over the head of any injured Marine, which will indicate their general
health anaylzer isn't a proper noun

2025-02-02 04:28 UTC, Zonespace27 commented on code/datums/tutorial/marine/role_specific/hospital_corpsman_basic.dm
> +	manual_message_to_player("When someone does not have a healthbar over their head, or when their healthbar disappears, that means they are <b>Fully Healthy</b>.")
fully healthy not proper noun

2025-02-02 04:28 UTC, Zonespace27 commented on code/datums/tutorial/marine/role_specific/hospital_corpsman_basic.dm
> +			message_to_player("Dont feed yourself the pill, try again.")
```suggestion
			message_to_player("Don't feed yourself the pill, try again.")
```

2025-02-02 04:28 UTC, Zonespace27 commented on code/datums/tutorial/marine/role_specific/hospital_corpsman_basic.dm
> +/datum/tutorial/marine/role_specific/hospital_corpsman_basic/proc/handle_pill_bottle(target, name, maptext, iconnumber, pill)
Eating the pill instead of giving it to the dummy will cause there to be two bottles for a short time

2025-02-02 04:28 UTC, Zonespace27 commented on code/datums/tutorial/marine/role_specific/hospital_corpsman_basic.dm
> +* NOT FOR USE OUTSIDE OF TUTORIAL SYSTEM
why add this line

2025-02-02 04:28 UTC, Zonespace27 commented on code/datums/tutorial/marine/role_specific/hospital_corpsman_basic.dm
> +	handle_pill_bottle(marine_dummy, "Bicaridine", "Bi", "11", /obj/item/reagent_container/pill/bicaridine)
if you feed yourself multiple pills in a row you have to click through a billion lines of repeated dialog

2025-02-02 04:28 UTC, Zonespace27 commented on code/datums/tutorial/marine/role_specific/hospital_corpsman_basic.dm
> +	update_objective("Pick up, and inject the Dummy with the Bicaridine Autoinjector")
objectives should end in a period, no need for the comma, autoinjector isn't a proper noun.

2025-02-02 04:28 UTC, Zonespace27 commented on code/datums/tutorial/marine/role_specific/hospital_corpsman_basic.dm
> +	manual_message_to_player("Medicines can also be directly injected into the bloodstream using <b>Autoinjectors</b>, allowing the medication to begin work immediately, without the need to be digested
```suggestion
	manual_message_to_player("Medicines can also be directly injected into the bloodstream using <b>Autoinjectors</b>, allowing the medication to begin work immediately without the need to be digested first.")
```

2025-02-02 04:28 UTC, Zonespace27 commented on code/datums/tutorial/marine/role_specific/hospital_corpsman_basic.dm
> +	manual_message_to_player("Click on the <b>Bicaridine Autoinjector</b> with an empty hand to pick it up, and then click on the Dummy while standing next to it to administer an injection")
```suggestion
	manual_message_to_player("Click on the <b>Bicaridine Autoinjector</b> with an empty hand to pick it up, and then click on the Dummy while standing next to it to administer an injection.")
```

2025-02-02 04:28 UTC, Zonespace27 commented on code/datums/tutorial/marine/role_specific/hospital_corpsman_basic.dm
> +	marine_dummy.apply_damage(10, BRUTE, "chest", 0, 0)
this can cause bleeding

2025-02-02 04:28 UTC, Zonespace27 commented on code/datums/tutorial/marine/role_specific/hospital_corpsman_basic.dm
Overall: This tutorial is LUDICROUSLY long. Might be better to split it into a couple?

2025-02-02 04:28 UTC, Zonespace27 commented on code/datums/tutorial/marine/role_specific/hospital_corpsman_basic.dm
> +	manual_message_to_player("It seems that our friend Pvt Dummy is suddenly injured. Use your <b>Health Analyzer</b> to scan them.")
```suggestion
	manual_message_to_player("It seems that our friend PVT Dummy is suddenly injured. Use your <b>Health Analyzer</b> to scan them.")
```

2025-02-05 10:40 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2025-02-05 12:50 UTC, Blundir approved these changes

2025-02-06 02:46 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2025-02-10 18:13 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2025-02-12 01:12 UTC, Zonespace27 requested changes
General code

2025-02-12 01:12 UTC, Zonespace27 commented on code/datums/tutorial/marine/role_specific/hospital_corpsman_basic.dm
> +	var/list/vendor_failsafe = list()
code doc

2025-02-12 01:12 UTC, Zonespace27 commented on code/datums/tutorial/_tutorial.dm
> +	var/handle_helper_status = 0
ditto

2025-02-12 01:12 UTC, Zonespace27 commented on code/game/objects/items/devices/flashlight.dm
> +	SEND_SIGNAL(user, COMSIG_LIVING_PENLIGHT_USED, being)
USED_PENLIGHT would be better

2025-02-12 01:12 UTC, Zonespace27 commented on code/game/objects/structures/crates_lockers/closets.dm
> +/obj/structure/closet/proc/open()
why change this?

2025-02-12 01:12 UTC, Zonespace27 commented on code/game/objects/structures/stool_bed_chair_nest/bed.dm
> +		if(length(contents) == 0)
```suggestion
		if(!length(contents))
```

2025-02-12 01:12 UTC, Zonespace27 commented on code/game/objects/structures/stool_bed_chair_nest/bed.dm
> +	if(foldabletype && !buckled_mob && !buckled_bodybag)
early return

2025-02-12 01:12 UTC, Zonespace27 commented on code/game/objects/structures/stool_bed_chair_nest/bed.dm
> +		if (istype(over_object, /mob/living/carbon/human))
early return

2025-02-12 01:12 UTC, Zonespace27 commented on code/game/objects/structures/stool_bed_chair_nest/bed.dm
> +		var/obj/item/roller/rollerholder = locate(foldabletype) in src.contents
src not needed

2025-02-12 01:12 UTC, Zonespace27 commented on code/game/objects/structures/stool_bed_chair_nest/bed.dm
> +				user.visible_message(SPAN_WARNING("[user] grabs [src] from the floor!"),
why is this a warning

2025-02-12 01:12 UTC, Zonespace27 commented on code/game/objects/structures/stool_bed_chair_nest/bed.dm
> +	if(length(contents) == 0)
```suggestion
	if(!length(contents))
```

2025-02-12 01:12 UTC, Zonespace27 commented on code/game/objects/structures/stool_bed_chair_nest/bed.dm
> +	var/obj/structure/bed/roller/roller = locate(rollertype) in src.contents
src not needed

2025-02-12 01:12 UTC, Zonespace27 commented on code/game/objects/structures/stool_bed_chair_nest/bed.dm
> +	var/prop
```suggestion
	var/prop = FALSE
```

2025-02-12 01:12 UTC, Zonespace27 commented on code/modules/asset_cache/asset_list_items.dm
> +		/obj/item/reagent_container/glass/beaker/vial,
not needed - line 291 already covers this

2025-02-12 01:12 UTC, Zonespace27 commented on code/modules/maptext_alerts/screen_alerts.dm
> +	fade_out_delay = null // is meant to be manually deleted by players in tutorial
```suggestion
	fade_out_delay = 0 // is meant to be manually deleted by players in tutorial
```

2025-02-12 01:12 UTC, Zonespace27 commented on code/modules/mob/living/carbon/human/human_dummy.dm
> +/mob/living/carbon/human/realistic_dummy/med_hud_set_health()
I don't think this is the right proc to hook into

2025-02-12 01:12 UTC, Zonespace27 commented on code/game/objects/items/bodybag.dm
> +	if(length(contents) == 0)
!length

2025-02-12 01:12 UTC, Zonespace27 commented on code/game/objects/items/bodybag.dm
> +	var/obj/structure/closet/bodybag/deployed = locate(unfolded_path) in src.contents
src not needed

2025-02-12 01:12 UTC, Zonespace27 commented on code/game/objects/items/bodybag.dm
> +/obj/structure/closet/bodybag/dump_contents()
add a return

2025-02-12 01:12 UTC, Zonespace27 commented on code/game/objects/items/bodybag.dm
> +			return 0
FALSE

2025-02-12 01:12 UTC, Zonespace27 commented on code/game/objects/items/bodybag.dm
> +		if(!(undeployed))
```suggestion
		if(!undeployed)
```

2025-02-12 01:12 UTC, Zonespace27 requested changes
General code

2025-02-12 01:22 UTC, Zonespace27 requested changes
Partial review of intermediate

2025-02-12 01:22 UTC, Zonespace27 commented on code/datums/tutorial/marine/role_specific/hospital_corpsman_intermediate.dm
> +	var/obj/limb/chest/mob_chest
code doc

2025-02-12 01:22 UTC, Zonespace27 commented on code/datums/tutorial/marine/role_specific/hospital_corpsman_intermediate.dm
> +	message_to_player("Before you're ready to take on the world as a Marine Hospital Corpsman, you should probably put some clothes on...")
```suggestion
	message_to_player("Before you're ready to take on the world as a Marine Hospital Corpsman, you should probably put some clothes on.")
```

2025-02-12 01:22 UTC, Zonespace27 commented on code/datums/tutorial/marine/role_specific/hospital_corpsman_intermediate.dm
> +	message_to_player("Healthy -> Slighty Bruised -> Bruised -> Ruptured / Broken")
```suggestion
	message_to_player("Healthy -> Slightly Bruised -> Bruised -> Ruptured / Broken")
```

2025-02-12 01:22 UTC, Zonespace27 commented on code/datums/tutorial/marine/role_specific/hospital_corpsman_intermediate.dm
> +	message_to_player("Each increase in organ damage severity will produce similarly life-threatening side effects on the body.")
```suggestion
	message_to_player("Each increase in organ damage severity will produce life-threatening side effects on the body.")
```

2025-02-12 01:22 UTC, Zonespace27 commented on code/datums/tutorial/marine/role_specific/hospital_corpsman_intermediate.dm
> +/datum/tutorial/marine/role_specific/hospital_corpsman_intermediate/proc/organ_tutorial()
From here to the stethoscope, there's a lot of text being vomited at the player without any interaction.

2025-02-12 01:22 UTC, Zonespace27 commented on code/datums/tutorial/marine/role_specific/hospital_corpsman_basic.dm
> +	message_to_player("Pvt Dummy is suffering from <b>Oxygen Damage</b>!")
you didn't fix the other cases of Pvt

2025-02-12 01:22 UTC, Zonespace27 commented on code/datums/tutorial/marine/role_specific/hospital_corpsman_intermediate.dm
> +/datum/tutorial/marine/role_specific/hospital_corpsman_intermediate
This tutorial is too long. Full stop. Split it out into multiple.

2025-02-12 01:22 UTC, Zonespace27 commented on code/datums/tutorial/marine/role_specific/hospital_corpsman_intermediate.dm
> +			message_to_player("Well done! If you check the <b>Chat-Box</b> on the right of your screen, you will now see the following message from your <b>Stethoscope</b>:")
```suggestion
			message_to_player("Well done! If you check the <b>Chat Box</b> on the right of your screen, you will now see the following message from your <b>Stethoscope</b>:")
```

2025-02-12 01:22 UTC, Zonespace27 commented on code/datums/tutorial/marine/role_specific/hospital_corpsman_intermediate.dm
> +			message_to_player("This means that all internal organs in Pvt Dummys chest are <b>Fully Healthy</b>!")
```suggestion
			message_to_player("This means that all internal organs in PVT Dummy's chest are <b>Fully Healthy</b>!")
```

2025-02-12 01:47 UTC, BAKACIRNONINE commented
Do we have the part for Suffocation? (https://cm-ss13.com/wiki/Guide_to_Medicine#Suffocation)

2025-02-12 02:52 UTC, BAKACIRNONINE commented
I think the medical sandbox should include a mass cas scenario: many PVTs to be treated are thrown to your side (up to 8). Most of them are hard crits, some are dead or even close to Perma
Learners should learn to judge treatment priorities independently. The most common solution is to prioritize HC companions and easy-to-recover Hard Crit Pvts. These patients can help CPR dead Patients, which is crucial for treating patients close to Perma and 500 burn.

2025-02-12 04:07 UTC, BAKACIRNONINE commented
> > I think the medical sandbox should include a mass cas scenario: many PVTs to be treated are thrown to your side (up to 8). Most of them are hard crits, some are dead or even close to Perma. (Hard Crit caused by damage over 150, oxy over 50, pain) Learners should learn to judge treatment priorities independently. The most common solution is prioritizing HC companions and easy-to-recover Hard Crit Pvts. These patients can help CPR dead Patients, which is crucial for treating patients close to Perma and 500 burn.
> > HM, is a remarkable job that prevents death and cures people. Or use your mysterious 'Zap' magic to turn a group of PVTs into a veritable army of the undead
> 
> I have already coded this
Sorry, I didn't see it here ‘#define TUTORIAL_HM_PHASE_NIGHTMARE 3	//! Simulates a Mass-Casualty event, 3-5 patients with severe damage levels“ 
Just in case, do you think we need to teach or mention separately about the Hard Crit?
Thanks for your work!

2025-03-07 02:33 UTC, Zonespace27 commented on tgui/packages/tgui/interfaces/TutorialMenu.tsx
> +                          <Box bold>Tutorial Subsections</Box>
should not appear if there aren't any subsections

2025-03-07 03:00 UTC, Zonespace27 requested changes
Tutorial #1

2025-03-16 17:25 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2025-03-18 05:38 UTC, closed without merging