Synthetic Overwatch And Leadership
cmss13-devs/cmss13 pull request #7563
Opened 2024-11-11 03:11 UTC by Katskan

# About the pull request

Restores leadership to synthetics, gives G1/2 overwatch and leadership skill. 

# Explain why it's good for the game

Gives back the green pointing arrow, enables some of the rare but expected synthetic tasks regarding CIC functions and computers.

# Testing Photographs and Procedure
Runs on local

# Changelog

:cl:
balance: Restores G3 synthetic leadership 2, adds leader 1 and overwatch to G1/2, 
/:cl:

2024-11-11 04:55 UTC, Nanu308 requested changes
Getting overwatch is fine, not a fan of giving leadership. If needed split up the two requirements same with funny green arrow

2024-11-19 14:22 UTC, Katskan commented
Updated change notes

2024-12-08 21:23 UTC, Nanu308 commented
Balance approved

2024-12-15 19:17 UTC, harryob approved these changes

2024-12-15 20:07 UTC, merged