Yautja fluff content update + hugger tank update
cmss13-devs/cmss13 pull request #7580
Opened 2024-11-13 00:44 UTC by Blundir

# About the pull request

Adds gigantic amount of assets for decorations, items, machinery etc for yautja

Mostly a port of thing that i was working on from https://github.com/Cosmic-Overlord/TerraGov-Marine-Corps

Also contains a port of https://github.com/tgstation/TerraGov-Marine-Corps/pull/12776
Which adds a living huggers and dead larva in destroyed tanks

# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

![StrongDMM_tbf3jvtCfT](https://github.com/user-attachments/assets/e92249f7-de2a-48b1-acc6-d4f34ed70986)

![StrongDMM_ezBUFFT9Gn](https://github.com/user-attachments/assets/28397f9d-41fd-48a6-b724-3bb876acd8b6)

![dreamseeker_VWcT6Ci6Wy](https://github.com/user-attachments/assets/d640874b-c010-4e36-982a-dd843e406a83)

![dreamseeker_zHRBACuntx](https://github.com/user-attachments/assets/7e2c2c69-6e5b-4a37-8515-b8cb93df296c)

![dreamseeker_TDZMDY5WPX](https://github.com/user-attachments/assets/ee91494c-49de-4e7e-85c2-aa5e9f846ee2)

![dreamseeker_nKXFRO5MKF](https://github.com/user-attachments/assets/26683f03-eb46-48ed-bc80-1ea19689b531)

![dreamseeker_Y5xZZ5ix6n](https://github.com/user-attachments/assets/cb536aff-219b-4897-8883-e4aa0387e000)

</details>

# Changelog

:cl:
add: hugger and larva tanks now actually have an alive hugger and a dead larva inside them on destroy
add: yautja: beds, chairs, microwaves, soda/chem/booze dispensers, sleeper/scanner/autodoc, freezer, refrigerator, air tank, computer, vendors, gibber, food grinder, hugger tank, closet, water/fuel tanks, juicer assets and objects
add: unique yautja full set of normal tools, replaced tools in yautja toolbelt with them
add: yautja windows 
add: yautja new statues
add: decorative xeno skulls for yautja locations
fix: preds not being able to use chem master and chem dispenser on their ship
fix: preds not having access to vendors on their ship
mapadd: added tons of new assets on LV624, New Varadero, Trijent Dam, Yautja ship
/:cl:

2024-12-28 04:55 UTC, nauticall requested changes
![image](https://github.com/user-attachments/assets/4589ed9a-3849-4f2c-a81a-a19db199fa10)
only real suggestion (sort of) is to darken the sprite on the backrests of these chairs to provide better contrast -- they look a bit flat otherwise without it. rest is good

2024-12-28 13:28 UTC, nauticall approved these changes
it is what it is

2024-12-28 23:34 UTC, kiVts requested changes

2024-12-28 23:34 UTC, kiVts commented on code/game/objects/structures/misc.dm
> +	return FALSE
signle letter vars

2024-12-28 23:34 UTC, kiVts commented on code/game/objects/structures/misc.dm
> +		to_chat(loc, SPAN_DANGER("[src] shatters!"))
visisble_message()

2024-12-28 23:34 UTC, kiVts commented on code/modules/cm_preds/yaut_items.dm
> +	icon = 'icons/obj/items/hunter/pred_gear.dmi'
\improper for these

2024-12-29 00:59 UTC, kiVts commented on code/game/objects/structures/misc.dm
> +			playsound(src.loc, 'sound/effects/Glasshit.ogg', 25, 1)
```suggestion
		return TRUE

	return FALSE

/obj/structure/xenoautopsy/tank/bullet_act(obj/projectile/Proj)
	bullet_ping(Proj)
	if(Proj.ammo.damage)
		take_damage(floor(Proj.ammo.damage / 2))
		if(Proj.ammo.damage_type == BRUTE)
			playsound(loc, 'sound/effects/Glasshit.ogg', 25, 1)
```

2024-12-29 01:00 UTC, kiVts approved these changes

2024-12-29 01:00 UTC, kiVts approved these changes
code^

2024-12-29 02:22 UTC, Nanu308 approved these changes
mapping approved, old ship deleted.
Overall improvement to detailing and more custom pred sprites are good.

2024-12-29 02:39 UTC, merged