Xeno Directional Attack IFF pref
cmss13-devs/cmss13 pull request #760
Opened 2022-07-27 20:21 UTC by PhantomEpicness

## About The Pull Request

Adds a preference to check that checks if a friendly xenomorph is caught in a directional attack.

This is enabled by default.

## Why It's Good For The Game

massive qol + no more accidentally knocking down friendly xenos when trying to cap

## Changelog

:cl: totalepicness
qol: Added a preference to enable a check that disables a friendly xeno from being caught in a directional attack. This is enabled by default
/:cl:

2022-08-01 10:26 UTC, stanalbatross requested changes

2022-08-01 10:26 UTC, stanalbatross commented on code/modules/client/preferences.dm
> +	var/toggle_prefs = TOGGLE_MIDDLE_MOUSE_CLICK|TOGGLE_DIRECTIONAL_ATTACK|TOGGLE_MEMBER_PUBLIC|TOGGLE_DIR_ASSIST_IFF // flags in #define/mode.dm
if you are making it on by default you should update savefiles

2022-08-01 10:26 UTC, stanalbatross commented on code/_onclick/xeno.dm
> +				if (X.hivenumber == src.hivenumber)
make this a can_not_harm check

2022-08-01 10:26 UTC, stanalbatross commented on code/_onclick/xeno.dm
> +				var/mob/living/carbon/Xenomorph/X = L
better var name needed for `X`

2022-08-16 00:37 UTC, closed without merging

2022-08-16 01:42 UTC, PhantomEpicness commented
racist bot