Loadout Customization - Items expanded & more...
cmss13-devs/cmss13 pull request #7614
Opened 2024-11-18 16:50 UTC by Zenith00000

# About the pull request

Adds a lot of new things, around 90+ completely new items, and various other items added, as well as many changes and price revisions. Also things like WY-patches, Freelancer patches are now added to the loadout of PMC's, Freelancer and other appropriate factions.

Basically I wanted to greatly expand the loadout menu, with much more choice and interesting things to pick, there should be more interesting loadouts we'll see. I've also added a "Civilian only" tab, which restricts some of the gear to appropriate roles, like survivors, CL and the Reporter.

<details>

<summary>Everything that's added</summary>

# Equipment List

## Eyewear:

- Eyepatch, black flipped
- Eyepatch, white
- Eyepatch, white flipped
- Eyepatch, green
- Eyepatch, green flipped
- Ballistic goggles, red
- Prescription ballistic goggles, red
- Ballistic goggles, blue
- Prescription ballistic goggles, blue
- Ballistic goggles, purple
- Prescription ballistic goggles, purple
- Ballistic goggles, yellow
- Prescription ballistic goggles, yellow
- Ballistic goggles, M1A1 blue
- Prescription ballistic goggles, M1A1 blue
- Polarized Ballistic goggles, M1A1 blue
- Prescription Polarized ballistic goggles, M1A1 blue
- Polarized Ballistic goggles, M1A1 orange
- Prescription Polarized ballistic goggles, M1A1 orange
- BiMex tactical shades, black
- BiMex tactical shades, yellow
- BiMex tactical shades, bronze
- Rounded Prescription Glasses
- Suntex-Sightware rounded shades, pink
- Suntex-Sightware rounded shades, green
- Suntex-Sightware rounded shades, sunrise
- Suntex-Sightware rounded shades, sunset
- Suntex-Sightware rounded shades, nightblue
- Suntex-Sightware rounded shades, midnight
- Suntex-Sightware rounded shades, bloodred

## Civilian Shades (restricted):

- BiMax personal shades
- BiMax personal shades, red
- BiMax personal shades, orange
- BiMax personal shades, yellow
- BiMax personal shades, green
- BiMax personal shades, blue

## Masks and Scarves:

- Smock, classic
- Smock, jungle
- Smock, snow
- Smock, desert
- Smock, urban
- Smock, black
- Keffiyeh
- Keffiyeh, white
- Keffiyeh, red
- Keffiyeh, green
- Keffiyeh, black
- Keffiyeh, blue
- Neckerchief, tan
- Neckerchief, gray
- Neckerchief, green
- Neckerchief, black
- Neckerchief, alpha
- Neckerchief, bravo
- Neckerchief, charlie
- Neckerchief, delta
- Neckerchief, echo
- Neckerchief, foxtrot

## Helmet Accessories:

- Desert Helmet netting
- Jungle Helmet netting
- Jungle Rain cover
- Urban Rain cover

## Facepaint & Bodypaint:

- Fullbody paint, snow
- Fullbody paint, desert
- Fullbody paint, jungle
- Fullbody paint, urban

## Bayonets, Weapons & Tools:

- Colonial Companion Mk. II (Swiss army knife tool)
- S&W .38 model 37 Custom revolver
- Antique bayonet
- L5 Bayonet
- M5 'Raven's Claw' tactical bayonet
- M5 'Raven's Claw' tactical bayonet, red
- M5 'Raven's Claw' tactical bayonet, blue
- M5 'Raven's Claw' tactical bayonet, black
- T9 tactical bayonet
- T9 tactical bayonet, blue

## Patches (USCM):

- Falling Falcons UA shoulder patch
- Falling Falcons large chest patch
- Falling Falcons shoulder patch, Alpha
- Falling Falcons shoulder patch, Bravo
- Falling Falcons shoulder patch, Charlie
- Falling Falcons shoulder patch, Delta
- Falling Falcons shoulder patch, Echo
- United Americas shoulder patch

## Civilian Patches (restricted):

- Weyland-Yutani shoulder patch
- Weyland-Yutani shoulder patch, white
- Weyland-Yutani Fury '161' patch
- Three World Empire shoulder patch
- Union of Progressive Peoples shoulder patch, gold
- Sons of Mars shoulder patch
- Old Freelancer shoulder patch
- Field Medic shoulder patch

## Miscellaneous (Boots, Gloves & Accessories):

- Grey combat boots
- Urban pattern combat boots
- Grey combat gloves
- Black Webbing

</details>

Also adds various things to the loadout menu, and adjusts the prices, above is all of the new stuff added sprite-wise.

# Explain why it's good for the game

More customization is good, as well as options for civilians. Things that were missing like faction patches and black webbing. Most of the stuff isn't too far from the current gear loadouts, it shouldn't be too much of an issue.

# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

![loadoutmenu](https://github.com/user-attachments/assets/822d66de-832b-4f50-9022-021770799b9d)

![loadoutground](https://github.com/user-attachments/assets/ad98c140-419d-4d1a-a105-3adaa34f140f)

![somegear](https://github.com/user-attachments/assets/34c27b96-67c7-4a62-8eeb-19031ddc66ec)

</details>

# Changelog

:cl: Zenith, Crowford, Frans_Feiffer, VaNdU-jr, cuberound, armolitskiy, mikoka wei

add: Added many new loadout items, and more other loadout items previously missing

/:cl:

2024-11-19 07:25 UTC, Wintermote commented
Would be nice if the vast majority, or all, purely cosmetic items like scarves, berets, or goggles, only cost 1 point instead of 2-3.

Seems like it'll happen eventually anyway as the scope of cosmetic attachments and items increases. As it is right now though - TWE shoulder patch (1) + beret (3)? Then you can forget having your RMC bayonet (4) to go with it, even though it'd be thematically appropriate.

Just seems oddly and unnecessarily restrictive for stuff that doesn't influence gameplay much/at all.

2024-11-19 16:30 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-11-19 16:54 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-11-19 18:53 UTC, Zenith00000 commented
> Would be nice if the vast majority, or all, purely cosmetic items like scarves, berets, or goggles, only cost 1 point instead of 2-3.
> 
> Seems like it'll happen eventually anyway as the scope of cosmetic attachments and items increases. As it is right now though - TWE shoulder patch (1) + beret (3)? Then you can forget having your RMC bayonet (4) to go with it, even though it'd be thematically appropriate.
> 
> Just seems oddly and unnecessarily restrictive for stuff that doesn't influence gameplay much/at all.

I'd agree, but there's probably a reason why the prices were set the way they are. I'm guessing because they don't want marines running around with every cosmetic, making it more about picking your favorites rather then everything possible. I do see both sides though and I'll consider it after getting some more feedback.

2024-11-23 12:09 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-11-27 02:57 UTC, fluffe9911 commented
Squad colored smock when?

2024-11-27 10:03 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-12-04 10:19 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-12-14 05:25 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-12-15 21:54 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-12-15 23:32 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-12-16 03:55 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-12-16 12:44 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-12-16 23:50 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-12-27 18:12 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-12-28 13:37 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-12-31 17:38 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-12-31 19:23 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-12-31 19:50 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2025-01-02 21:10 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2025-01-10 11:06 UTC, Blundir requested changes
a lot of things needs to be tweaked, discussed in dms

2025-01-13 11:04 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2025-01-13 12:09 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2025-01-14 21:19 UTC, Staykeu commented
> I think you accidentally put the plushies in civilian (restricted). Used to be able to have these in my loadout :( ![image](https://private-user-images.githubusercontent.com/44538569/403141194-ef569144-976c-403d-b95a-ff5a411d94c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY4ODk4NTMsIm5iZiI6MTczNjg4OTU1MywicGF0aCI6Ii80NDUzODU2OS80MDMxNDExOTQtZWY1NjkxNDQtOTc2Yy00MDNkLWI5NWEtZmY1YTQxMWQ5NGM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTE0VDIxMTkxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0OTBmYjQyMTExMGQwOTZiYWY1NTU3NGMyZjFlODQ0ZDA5NTJkYTA4YTA4NDZiNTU4ZTg4MDY3ZTFmODY0MzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.bzta1GtbXMj0V6l8miPo4f6s_tGihaadUh78YQnMPA4)

If it's a mistake it's a damn good one

2025-01-15 01:44 UTC, Blundir commented
> I think you accidentally put the plushies in civilian (restricted). Used to be able to have these in my loadout :( ![image](https://private-user-images.githubusercontent.com/44538569/403141194-ef569144-976c-403d-b95a-ff5a411d94c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY5MDU3NjgsIm5iZiI6MTczNjkwNTQ2OCwicGF0aCI6Ii80NDUzODU2OS80MDMxNDExOTQtZWY1NjkxNDQtOTc2Yy00MDNkLWI5NWEtZmY1YTQxMWQ5NGM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTE1VDAxNDQyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwNmUyNDYxZTNkMmI5YmU0Y2U0Yzg3ODZmYWJlNGQ4MWE0YjIyNzZkMWEyMGRlMzlmYzM4ZjI2OGEyYmI4Y2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.OB0b5OkPdthbfxRnD3SJJWGNyGZYhcs3z2ifM9Nvu50)

Not a mistake

2025-01-15 02:33 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2025-01-15 06:01 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2025-01-15 06:38 UTC, MistChristmas commented
Wasn't me but an SO noticed that most of their list is missing after the one patch.
![image](https://github.com/user-attachments/assets/247db244-aaf2-4b43-bb56-68e771a36966)

2025-01-15 07:09 UTC, Zenith00000 commented
> Wasn't me but an SO noticed that most of their list is missing after the one patch. ![image](https://private-user-images.githubusercontent.com/7815982/403280061-247db244-aaf2-4b43-bb56-68e771a36966.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY5MjQyNjUsIm5iZiI6MTczNjkyMzk2NSwicGF0aCI6Ii83ODE1OTgyLzQwMzI4MDA2MS0yNDdkYjI0NC1hYWYyLTRiNDMtYmI1Ni02OGU3NzFhMzY5NjYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDExNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAxMTVUMDY1MjQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTBhOWQ1NzkxOGIxYjY2MGEyZDk1MzU0ZjFiMTYwMmMzODQ5MGQ2MDQzZWRmZDAxZWJmN2Y2MWIyNzY2OTI0ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.6wQ8kgzoaG7PRoDmZ4F37P_cAGYHIdQwq-lapH2T7Rc)

By list you mean just the patches right? I'm aware of them missing from some vendors, It should be fixed next time I can update the PR, along with some other fixes and tweaks.

2025-01-15 07:21 UTC, Segrain commented on code/datums/tutorial/marine/reqs_line.dm
> +		/obj/item/clothing/accessory/storage/webbing/black = list("Black Webbing", "Normal black webbing", "Blk Web"),
So `black webbing` is...

2025-01-15 07:25 UTC, Segrain requested changes

2025-01-15 07:25 UTC, Segrain commented on code/modules/client/preferences_gear.dm
> +/datum/gear/weapon/type_80_Bayonet
```suggestion
/datum/gear/weapon/type_80_bayonet
```
Likewise for all below. No capitals in type paths, please.

2025-01-15 07:49 UTC, MistChristmas commented
> > Wasn't me but an SO noticed that most of their list is missing after the one patch. ![image](https://private-user-images.githubusercontent.com/7815982/403280061-247db244-aaf2-4b43-bb56-68e771a36966.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY5MjQyNjUsIm5iZiI6MTczNjkyMzk2NSwicGF0aCI6Ii83ODE1OTgyLzQwMzI4MDA2MS0yNDdkYjI0NC1hYWYyLTRiNDMtYmI1Ni02OGU3NzFhMzY5NjYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDExNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAxMTVUMDY1MjQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTBhOWQ1NzkxOGIxYjY2MGEyZDk1MzU0ZjFiMTYwMmMzODQ5MGQ2MDQzZWRmZDAxZWJmN2Y2MWIyNzY2OTI0ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.6wQ8kgzoaG7PRoDmZ4F37P_cAGYHIdQwq-lapH2T7Rc)
> 
> By list you mean just the patches right? I'm aware of them missing from some vendors, It should be fixed next time I can update the PR, along with some other fixes and tweaks.

If you look at the image. It's everything after the first patch. Where you added a new patches. 
No idea if the issue can be replicated yet.

2025-01-15 08:50 UTC, MistChristmas commented on code/game/machinery/vending/vendor_types/crew/staff_officer.dm
> +		list("Falling Falcons UA Shoulder Patch", 1, /obj/item/clothing/accessory/patch/falconalt, VENDOR_ITEM_REGULAR),
The lack of null in these is probably what breaks the vendors causing the rest of the items to not appear. I presume this isn't actually isolated to SO.

2025-01-15 17:52 UTC, Zenith00000 commented on code/game/machinery/vending/vendor_types/crew/staff_officer.dm
> +		list("Falling Falcons UA Shoulder Patch", 1, /obj/item/clothing/accessory/patch/falconalt, VENDOR_ITEM_REGULAR),
Yeah it's just the SO and CO vendors, fixed it don't worry.

2025-01-16 05:52 UTC, HaultyAnonie commented
Where's the normal bimex in the loadout selection.
it's shown in the PR but it's not on loadout
![image](https://github.com/user-attachments/assets/00394bd0-ba0b-4959-86af-19e0c858d9ec)

2025-01-16 10:28 UTC, Zenith00000 commented
> Where's the normal bimex in the loadout selection. it's shown in the PR but it's not on loadout ![image](https://private-user-images.githubusercontent.com/131271192/403706967-00394bd0-ba0b-4959-86af-19e0c858d9ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzcwMjM0OTIsIm5iZiI6MTczNzAyMzE5MiwicGF0aCI6Ii8xMzEyNzExOTIvNDAzNzA2OTY3LTAwMzk0YmQwLWJhMGItNDk1OS04NmFmLTE5ZTBjODU4ZDllYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDExNlQxMDI2MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYTdjYTgxNjBjYThiNWQ3ZWJlNzUyYmQ4MzA0YjE4YWE2ZDc0M2Y0NDg3N2MzY2JhNDBhY2RkZDdiZDkyMDczJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9._7YG6HGbRBfiPJHJbr0InilFCP8ZSDqU_5v2CY2S2qs)

Blundir wanted me to remove the old Bimex completely, but I just moved them to civilian only, same with the plushes. I could move the old Bimex back, but the plushes will stay under civilian only for now I think.

2025-01-16 15:57 UTC, loleo14 commented
So random question, what happened to the color specific Neckerchief's?

2025-01-16 17:16 UTC, Blundir commented
> So random question, what happened to the color specific Neckerchief's?

Now they work the same as other squad specific clothing

2025-01-17 05:11 UTC, HaultyAnonie commented
> > Where's the normal bimex in the loadout selection. it's shown in the PR but it's not on loadout ![image](https://private-user-images.githubusercontent.com/131271192/403706967-00394bd0-ba0b-4959-86af-19e0c858d9ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzcwMjM0OTIsIm5iZiI6MTczNzAyMzE5MiwicGF0aCI6Ii8xMzEyNzExOTIvNDAzNzA2OTY3LTAwMzk0YmQwLWJhMGItNDk1OS04NmFmLTE5ZTBjODU4ZDllYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDExNlQxMDI2MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYTdjYTgxNjBjYThiNWQ3ZWJlNzUyYmQ4MzA0YjE4YWE2ZDc0M2Y0NDg3N2MzY2JhNDBhY2RkZDdiZDkyMDczJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9._7YG6HGbRBfiPJHJbr0InilFCP8ZSDqU_5v2CY2S2qs)
> 
> Blundir wanted me to remove the old Bimex completely, but I just moved them to civilian only, same with the plushes. I could move the old Bimex back, but the plushes will stay under civilian only for now I think.

Thank you so much. Poor Bimex... It's a legendary mythic

2025-01-20 03:31 UTC, Staykeu commented
Custom bayonets aren't able to be mounted onto weapons.

2025-01-20 05:29 UTC, Zenith00000 commented
> Custom bayonets aren't able to be mounted onto weapons, no idea if that's intentional or not. If it isn't they probably shouldn't be labeled as bayonets.

What weapons we talking about here specifically? Because they are attachable, what makes you think they aren't? Tested it just now, can't find any issues, you'd have to be more specific because I don't think it's broken.

2025-01-24 23:14 UTC, Staykeu commented
Sorry I got back so late, I found that specifically the red raven's claw bayonet cannot be attached to the MK1 Pulse Rifle, maybe I messed it up, maybe it's fixed, I have no clue.

2025-01-25 01:34 UTC, Zenith00000 commented
> > What weapons we talking about here specifically?
> 
> Sorry I got back so late, I found that specifically the red raven's claw bayonet cannot be attached to the MK1 Pulse Rifle, maybe I messed it up, maybe it's fixed, I have no clue.

Thanks, I've actually missed a lot of guns, so I've added it to every gun that supports a bayonet now, appreciate it, I overlooked everything other then the standard marine guns.

2025-01-31 01:17 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2025-01-31 02:36 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2025-02-06 23:40 UTC, ATP2333REAL commented
when merge this?

2025-02-07 09:29 UTC, Blundir commented
> when merge this?

When ready

2025-02-08 09:38 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2025-02-08 11:01 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2025-02-11 23:32 UTC, HaultyAnonie commented
The O.G Bimex glasses are missing from the loadout menu again, is that on purpose this time?

2025-02-12 06:21 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2025-02-12 07:16 UTC, Zenith00000 commented
> The O.G Bimex glasses are missing from the loadout menu again, is that on purpose this time?

Yeah sorry once again, but talk to Blundir if you want it returned.

2025-02-12 07:17 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2025-02-13 01:37 UTC, cm13-github commented
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
CM13 Live

##### Revision
Origin: 8fde04edfa037e0e0ad1a4ee6b2c5cb661e30130
Pull Request: 9f6e36c8d38cb884fec40c33d9e822122412bb4d
Server: 46172eeae6604a1c4fa7d0c121070780ea0cca41

##### Comment

</details>

2025-02-15 14:20 UTC, Blundir approved these changes

2025-02-15 14:45 UTC, hry-gh approved these changes
we really need to unfuck storage code at some point

2025-02-15 14:57 UTC, merged