Yet Another Attempt To Fix Vamp
cmss13-devs/cmss13 pull request #7650
Opened 2024-11-22 04:00 UTC by ihatethisengine

# About the pull request
Tail jab loses all damage (except slight dmg on wall slam), regains short stun (slightly longer on wall slam). 
Vamp can no longer heal while on fire (balance approved: https://github.com/cmss13-devs/cmss13/pull/7135).
Vamp loses 5 armor (20 > 15).

Healer drone's sacrifice now extinguishes the target (balance approved: https://github.com/cmss13-devs/cmss13/pull/7135).

# Explain why it's good for the game

To understand the reasoning behind this PR you must read all 300 messages in this thread: https://forum.cm-ss13.com/t/please-nerf-vampire-lurkers-or-do-something-holy-shit/8658

But tl;dr:
Vamp is probably the ONLY caste in the game who can use ALL of its abilities **IN AN INSTANCE**. There is no delay between different abilities' uses, so you can use them all at the same time (only limiter is click delay I guess), which leads to insane DMG output in an instance. You can instantly unleash tailjab, rush, flurry and even land a slash on top of this with no delays. Every other caste needs to spend at least some time in engagement to land their combo. Tailjab's extra damage from direct click made it even worse (imagine adding aim assist, and then additionally reward player for direct click on top of that, what a joke). Removing DMG from one of the abilities should negate this issue at least partly.

On the other hand, insanered's stun removal didn't solve the actual problem (the insane dmg is still there), but made the caste harder to play for greenish players or players with bad ping, no stuns makes it harder for them to engage shotgun users. So I am reverting this.

Vamp armor always seemed weird to me, given its speed. Too tanky. I'd nerf it even more honestly, but need to see how it performs.

Everything regarding fire is carried over from ghostsheet PR.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl: ihatethisengine
balance: Tail jab loses all damage (except slight dmg on wall slam), regains short stun (slightly longer on wall slam). 
balance: Vamp can no longer heal while on fire
balance: Vamp loses 5 armor (20 > 15).
balance: Healer drone's sacrifice now extinguishes the target.
/:cl:

2024-11-22 15:15 UTC, Red-byte3D commented
the entire reason i removed the stun was that because you do not need to aim it at all, i dont think it needs ot come back

2024-11-23 05:57 UTC, Drulikar requested changes
I think this is going too far with the nerfs. I will not approve this without the tailstab doing some damage.

Revert all changes to tail jab and instead just remove the extra damage on sprite click.

2024-12-15 22:29 UTC, DorfGuy1 commented
For the love of god, dont' give them stuns. They don't need it. Having to charge your tailstrike and a little damage is worth way less than a stun.

2025-01-19 08:51 UTC, ihatethisengine commented
Rush putting you on top of your target just like pounce felt clunky (and made combo execution annoying), so I made sure you land next to the resting target instead of on top of them.

2025-01-20 02:26 UTC, ihatethisengine reviewed
a bit more consistent.

2025-01-20 02:26 UTC, ihatethisengine commented on code/modules/mob/living/carbon/xenomorph/abilities/lurker/lurker_powers.dm
> +	if(target in new_loc) //don't wanna jump on top of them
```suggestion
	if(target.Adjacent(xeno)) //don't wanna jump on top of them, strike when within the reach
```

2025-01-22 20:46 UTC, Mister-moon1 commented
After testing the changes, i cannot say the rush change feels good, i think it would be better staying as not needing to target a mob as the marine only sees guaranteed hits while the vamp player experiences every missed ability usage, this just makes it more frustrating in the eyes of both sides rather than achieving it's goal of reducing mobility with rush as an ability.

I would recommend maybe a cooldown increase instead and reverting it to 4 tiles or maybe a short windup before the rush happens

2025-01-24 07:20 UTC, BlitzArde commented
I've played a lot of vamp lurker thus far and have no trouble using the rush to hit Marines consistently, however, I do find it a bit disappointing that I can no longer use rush to break windows quicker or quickly vault over window frames/barricades. Please do not add a windup to the rush I beg...

2025-02-11 00:58 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2025-02-14 09:10 UTC, hry-gh requested changes

2025-02-14 09:10 UTC, hry-gh commented on code/modules/mob/living/carbon/xenomorph/abilities/general_abilities.dm
> +	var/list/pounce_end_callbacks = null // Callbacks to call when the pounce (throw) ends
```suggestion
	/// Callbacks to call when the pounce (throw) ends
	var/list/pounce_end_callbacks = null
```

2025-02-14 09:10 UTC, hry-gh commented on code/modules/mob/living/carbon/xenomorph/abilities/general_abilities.dm
> +	var/list/pounce_end_callbacks = null // Callbacks to call when the pounce (throw) ends
when is this ever used

2025-02-17 20:48 UTC, ihatethisengine commented on code/modules/mob/living/carbon/xenomorph/abilities/general_abilities.dm
> +	var/list/pounce_end_callbacks = null // Callbacks to call when the pounce (throw) ends
https://github.com/cmss13-devs/cmss13/pull/7650/files#diff-731c63cbde0bacf61511200742fbd91dbd38d0d3b4336b54f4cb6542e3869a42R444 here

2025-02-17 20:50 UTC, ihatethisengine commented
I'll resolve the conflicts in a few days

2025-04-11 00:41 UTC, closed without merging

2025-04-11 10:01 UTC, Drulikar commented
Let us know when you come back with the milk.