SG Balance adjustments
cmss13-devs/cmss13 pull request #766
Opened 2022-07-28 17:46 UTC by Shad0vvs

## About The Pull Request

## Why It's Good For The Game

Bugfix + needed balance change as SG's are too strong at the moment.

## Changelog

:cl:
balance: Smartgun firerate adjusted to ~400 RPM, Full auto scatter peak set to 80 shots, Scatter amount set to 8.
fix: Fixed WO Terminator's dirty smartgun flags.
/:cl:

2022-07-28 19:09 UTC, stanalbatross commented on code/modules/projectiles/guns/smartgun.dm
> +	fa_max_scatter = SCATTER_AMOUNT_NONE
why

2022-07-28 19:10 UTC, stanalbatross requested changes

2022-07-28 19:10 UTC, stanalbatross commented on code/__DEFINES/weapon_stats.dm
>  #define FIRE_DELAY_TIER_SMG	1.3
```suggestion
#define FIRE_DELAY_TIER_10 	1
#define FIRE_DELAY_TIER_SG 	1.5
#define FIRE_DELAY_TIER_SMG	1.3
```

2022-07-28 19:42 UTC, Shad0vvs commented on code/modules/projectiles/guns/smartgun.dm
> +	fa_max_scatter = SCATTER_AMOUNT_NONE
You wanted the terminator ones to frag?

2022-07-29 07:58 UTC, stanalbatross approved these changes

2022-07-29 07:59 UTC, stanalbatross commented
this should be a nice middleground + not too strong

2022-07-29 20:35 UTC, merged