USCM HvH spec rework
cmss13-devs/cmss13 pull request #7661
Opened 2024-11-23 15:42 UTC by cuberound

# About the pull request

if gamemode has flag all spec kits are replaced with b18

# Explain why it's good for the game

specs are bad design for normal game, even worse for HvH

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
balance: USCM specs on HvH are replced with b18s
/:cl:

2024-12-11 17:18 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-12-13 08:31 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-12-16 10:03 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-12-16 10:58 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-12-28 20:39 UTC, kiVts requested changes

2024-12-28 20:39 UTC, kiVts commented on code/game/gamemodes/round_modifiers.dm
> +	modifier_desc = "Reduces damage and stun from explosions."
This has no effect

2024-12-28 20:39 UTC, kiVts commented on code/modules/cm_marines/specialist.dm
> +		available_vendor_num = 0
```suggestion
/datum/specialist_set/heavy/post_round_start()
	if(SSticker && MODE_HAS_MODIFIER(/datum/gamemode_modifier/heavy_specialists))
		available_vendor_num = 4
```

set available vendor num to zero on the datum itself

2024-12-28 20:39 UTC, kiVts commented on code/modules/cm_marines/specialist.dm
> +	name = "Heavy Armor Set (HvH Only)"
```suggestion
	name = "Heavy Armor Set"
```

2025-01-23 20:19 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2025-01-23 21:56 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2025-01-23 22:18 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2025-01-23 22:48 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2025-02-13 20:15 UTC, kiVts commented on code/modules/cm_marines/specialist.dm
> +
```suggestion
```

2025-02-13 20:16 UTC, kiVts approved these changes

2025-02-13 20:31 UTC, merged