Some changes to broadcasting
cmss13-devs/cmss13 pull request #7662
Opened 2024-11-23 15:51 UTC by ihatethisengine

# About the pull request
I was writing this thing and accidentally closed my browser, so I'll be brief.
1) You can use the camera with one hand. You still need to turn it on. It keeps broadcasting even if dropped, but loses range. Xeno can turn the camera off by slashing it.
2) You can unanchor TV with a wrench.
3) Broadcasting camera cant take photos anymore.

# Explain why it's good for the game
1) More convenient.
2) If no MT is around you can still have an audience.
3) I don't think it was very convenient anyway, just use reg camera for photos if you wanna.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl: ihatethisengine
add: You can use the camera with one hand. You still need to turn it on. It keeps broadcasting even if dropped, but loses range. Xeno can turn the camera off by slashing it.
add: You can unanchor TV with a wrench
/:cl:

2024-11-23 15:54 UTC, thevandie commented
I pretty much always carried a default camera as a backup anyways, so yeah good change 👍

2024-11-23 16:16 UTC, cuberound commented
eh kinda sad that you can not take pictures, this makes creating fax news harder then curent camera as you have to drop cammera to take pictures

2024-11-23 16:23 UTC, ihatethisengine commented
> eh kinda sad that you can not take pictures, this makes creating fax news harder then curent camera as you have to drop cammera to take pictures

I can just make reg camera useable with one hand if this is such a big deal

2024-11-29 12:10 UTC, harryob requested changes

2024-11-29 12:10 UTC, harryob commented on code/game/machinery/computer/camera_console.dm
> +		src.stat |= MAINT
src.stat -> stat

2024-11-29 12:10 UTC, harryob commented on code/game/machinery/computer/camera_console.dm
> +		src.stat &= ~MAINT
ditto

2024-11-29 12:10 UTC, harryob commented on code/game/machinery/computer/camera_console.dm
> +	if(src.stat & MAINT)
ditto

2024-11-29 12:53 UTC, harryob approved these changes

2024-11-29 13:01 UTC, merged