(WIP) Fax Machine Changes
cmss13-devs/cmss13 pull request #7678
Opened 2024-11-25 21:43 UTC by realforest2001

# About the pull request

Adds a few features to fax machines. This PR is currently a work in progress.

# Explain why it's good for the game

Mostly quality of life, it will grow from what it is now.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
add: Added a button to certain fax machines to send priority faxes, with additional audio cues.
fix: Fax machine receiving a fax now plays the correct sound.
/:cl:

2024-11-26 09:54 UTC, L0pz commented
Oh is this to solve how CIC straight up doesn't notice it when they receive a fax?

2024-11-26 15:26 UTC, harryob requested changes

2024-11-26 15:26 UTC, harryob commented on code/game/machinery/fax_machine.dm
> +			to_chat(user, SPAN_NOTICE("You take \the [original_fax.name] out of \the [src]."))
```suggestion
			to_chat(user, SPAN_NOTICE("You take the [original_fax.name] out of [src]."))
```

2024-11-26 15:26 UTC, harryob commented on code/game/machinery/fax_machine.dm
> +					to_chat(user, SPAN_NOTICE("You put \the [original_fax.name] into \the [src]."))
```suggestion
					to_chat(user, SPAN_NOTICE("You put the [original_fax.name] into [src]."))
```

2024-11-26 15:26 UTC, harryob commented on code/game/machinery/fax_machine.dm
> +					to_chat(user, SPAN_NOTICE("\The [src] jammed! It can only accept up to five papers at once."))
```suggestion
					to_chat(user, SPAN_NOTICE("[src] jammed! It can only accept up to five papers at once."))
```

2024-11-26 15:26 UTC, harryob commented on code/game/machinery/fax_machine.dm
> +			to_chat(user, SPAN_NOTICE("You take \the [scan] out of \the [src]."))
```suggestion
			to_chat(user, SPAN_NOTICE("You take [scan] out of [src]."))
```

2024-12-01 14:25 UTC, realforest2001 commented
Will be stealing an idea from #7706

2024-12-26 09:03 UTC, Nanu308 approved these changes
mapping lgtm

2024-12-31 16:34 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2025-01-01 18:01 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2025-01-01 18:22 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2025-01-01 18:30 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2025-01-02 21:10 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2025-01-05 17:00 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2025-01-25 09:29 UTC, harryob approved these changes

2025-01-25 09:54 UTC, merged