Praetorian Dancer Dodge now creates Afterimage(s).
cmss13-devs/cmss13 pull request #7714
Opened 2024-12-01 19:25 UTC by Venuska1117

# About the pull request

Add "afterimage" effect to Dancer "Dodge" skill

**Make sure to TMs it first, i was testing it alone, and i have suspicion that it will break something**

# Explain why it's good for the game

Add Afterimage effect to Dancer prae Dodge, it lack any indication that it uses "Dodge", this PR is to give prae dancer visual indication of dodge ability, and make them look like they are "Hard to Shoot".

(this is intended to be only visuals)

# Important Info for adminbus:

**Changing (adding) color in VV apply on afterimages.**

**Changing .dmi apply changes to afterimages.**

_(see vids below to know what i am talking about here)_

# Demonstration Video:

<details>
<summary>Click HERE to see Video</summary>

Final Version: 

https://github.com/user-attachments/assets/9fa1c2bb-d582-49d0-b4af-c1839900d62c

|
**BELOW FOR ADMINS:**
|

VV "Color" change support:

https://github.com/user-attachments/assets/5d05acb5-a9f1-4a75-8023-1c419cf828df

Custom .dmi Sprite support:

https://github.com/user-attachments/assets/23ac862b-66ea-4e8c-bb4f-42a8d519e8a2

</details>

# Changelog
:cl: Venuska1117
add: Add "Afterimage" effect to Dancer Praetorian "Dodge" ability.
/:cl:

2024-12-01 19:56 UTC, Diegoflores31 commented
can you make the after image pixel shift in random directions ? to give the illusion that it is "dodging"

2024-12-01 19:57 UTC, Diegoflores31 commented
please add a video of the prae using this ability while being shot by a sentry

2024-12-01 20:07 UTC, Venuska1117 commented
> please add a video of the prae using this ability while being shot by a sentry

Added

2024-12-01 20:28 UTC, Zenith00000 commented
Perhaps make the effect cut off sooner, it lasts too long. Also perhaps make it have less opacity as well, I can see this being a bit confusing for marines in the dark with the long lingering after-image. Either way looks good, I like it.

2024-12-01 21:17 UTC, Venuska1117 commented
> Perhaps make the effect cut off sooner, it lasts too long. Also perhaps make it have less opacity as well, I can see this being a bit confusing for marines in the dark with the long lingering after-image. Either way looks good, I like it.

this effect last the same duration of dodge ability, but opacity can be changed.

2024-12-01 22:09 UTC, Red-byte3D commented
feature tag

2024-12-01 22:41 UTC, TheManWithNoHands commented
> this effect last the same duration of dodge ability, but opacity can be changed.

More the duration the after images are visible before they are completly faded.
Imagine a dancer going quickly in circels, and you have a hard time seeing what an after image is and what not.
Just try to shorten the time the afterimages are visible. Or their "lifetime" so to speak.

Would be a cool ability to creat after images to confuse marines. But that be a completly diffrent ability. One i kinda want now.

2024-12-01 22:42 UTC, Venuska1117 commented
> > this effect last the same duration of dodge ability, but opacity can be changed.
> 
> More the duration the after images are visible before they are completly faded. Imagine a dancer going quickly in circels, and you have a hard time seeing what an after image is and what not. Just try to shorten the time the afterimages are visible. Or their "lifetime" so to speak.
> 
> Would be a cool ability to creat after images to confuse marines. But that be a completly diffrent ability. One i kinda want now.

Isnt that, what dance supposed to do?

2024-12-01 22:46 UTC, TheManWithNoHands commented
> Isnt that, what dance supposed to do?

I mean yeah. But the VFX is just supposed to be a visual indicator and not the actual part of the ability that make em hard to hit. Rigth?

2024-12-01 22:48 UTC, Venuska1117 commented
> > Isnt that, what dance supposed to do?
> 
> I mean yeah. But the VFX is just supposed to be a visual indicator and not the actual part of the ability that make em hard to hit. Rigth?

its visual effect, yeah, i fixed mouse opacity issue so you CANNOT target afterimages, they are visuals made to confuse marines, not to avoid damage or take bullets.

2024-12-15 19:59 UTC, harryob requested changes

2024-12-15 19:59 UTC, harryob commented on code/modules/mob/living/carbon/xenomorph/abilities/praetorian/praetorian_powers.dm
> +	spawn create_afterimage_sequence(dodge_user, duration)
what's spawn here for? if you want to invoke it async, use INVOKE_ASYNC

2024-12-15 19:59 UTC, harryob commented on code/modules/mob/living/carbon/xenomorph/abilities/praetorian/praetorian_powers.dm
> +		dodge_user.pixel_y -= random_offset_y
these really should be timers

2025-01-16 02:17 UTC, Drulikar requested changes

2025-01-16 02:17 UTC, Drulikar commented on code/modules/mob/living/carbon/xenomorph/abilities/praetorian/praetorian_powers.dm
> +	var/original_sprite_y = dodge_user.pixel_y
Any reason why you didn't just use `initial`?

2025-01-16 02:17 UTC, Drulikar commented on code/modules/mob/living/carbon/xenomorph/abilities/praetorian/praetorian_powers.dm
> +	addtimer(CALLBACK(src, PROC_REF(create_afterimage_sequence), dodge_user, duration, original_sprite_x, original_sprite_y))
A zero length timer should just be INVOKE_ASYNC. Regardless, it shouldn't need to be a timer or INVOKE_ASYNC once the sleeps and spawns and such are properly removed.

Not a single one of these arguments need to be passed either. `dodge_user` is just `owner`, `duration` is `duration`, the original pixel_x and pixel_y values can be gotten from `initial`

2025-01-16 02:17 UTC, Drulikar commented on code/modules/mob/living/carbon/xenomorph/abilities/praetorian/praetorian_powers.dm
> +	pixel_y += random_offset_y
`reset_position_to_original` and `apply_offset` probably should be defined somewhere else. They also can be much more generic e.g. as low as `/obj/proc/`.

`pixel_x = original_sprite_x` can just instead be `pixel_x = initial(pixel_x)` same for pixel_y.

2025-01-16 02:17 UTC, Drulikar commented on code/modules/mob/living/carbon/xenomorph/abilities/praetorian/praetorian_powers.dm
> +
Don't use strings for proc refs, you should have used `TYPE_PROC_REF(/obj/effect/overlay/afterimage, fade_out_afterimage)`. Regardless, why didn't you just use the `fading_duration` argument when creating an `/obj/effect/afterimage`

2025-01-16 02:17 UTC, Drulikar commented on code/modules/mob/living/carbon/xenomorph/abilities/praetorian/praetorian_powers.dm
> +	addtimer(CALLBACK(dodge_user, "reset_position_to_original", original_sprite_x, original_sprite_y), 2 DECISECONDS)
Shouldn't be necessary to specify `original_sprite_x` or `original_sprite_y`. Additionally, don't use strings for proc refs, you should have used `TYPE_PROC_REF(/mob/living/carbon/xenomorph, reset_position_to_original)`. Though if its made more generic this would need to change.

2025-01-16 02:17 UTC, Drulikar commented on code/modules/mob/living/carbon/xenomorph/abilities/praetorian/praetorian_powers.dm
> +		sleep(afterimage_interval)
A looping timer would handle your entire loop and remove the need for sleep. Just have it decrement how many iterations it still needs to perform.

2025-01-23 13:46 UTC, Venuska1117 commented
I will re-open it after fix

2025-01-23 13:46 UTC, closed without merging