Flag for no shipmap and some minor improvements in gamemode system
cmss13-devs/cmss13 pull request #7731
Opened 2024-12-03 15:46 UTC by blackcrystall

# About the pull request
Adding bad code
And removing some bad code

Added something with minimum and maximum number of players for game mode and voting fix, we still need a callback even if the vote failed or there are no options and we cancel it, because it can make players ask for admin intervention if something went wrong to restart the voting chain... such as no game mode or map options or no one just voted for it, also added a minimum and maximum number of players for a game mode, so we can limit some game modes in the future to a maximum number of players and a minimum number of players

Game no more load ship map on WO&XvX (so we don't delete it later)
Unification of the style of round end code and processes (friendlier code for modification and adding new functionality)

# Explain why it's good for the game
Less bugs is better! Cleaner code is better!

# Changelog

:cl:
code: Stop us from loading shipmap on WO&XvX
code: Don't delete anymore gamemode on failed checks for round start
code: Gamemode round end code style unification and procs
code: Gamemode min and max players lock for voting options
fix: Vote restart chain break if no options or nobody voted
/:cl:

2024-12-15 20:46 UTC, harryob requested changes
sorry this took so long. thiso ld code was insane i forgot that WO did that

2024-12-15 20:46 UTC, harryob commented on code/game/gamemodes/colonialmarines/whiskey_outpost.dm
> +//			SSitem_cleanup.delete_almayer()
```suggestion
```

2025-01-31 20:43 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2025-02-01 16:07 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2025-02-02 04:16 UTC, blackcrystall commented
Okay, nevermind... I don't think that I going to resolve after conflct issues, because there no point in doing such

2025-02-02 04:16 UTC, closed without merging