vaiso and chem retrieval erts can now use their shuttles
cmss13-devs/cmss13 pull request #7735
Opened 2024-12-04 10:42 UTC by harryob

thanks drathek for cracking open the debugger for me

:cl:
fix: pmc goon squads and vaiso squads can now correctly use their shuttles to return home
/:cl:

2024-12-11 22:25 UTC, kiVts requested changes
consistency sake

2024-12-11 22:25 UTC, kiVts commented on code/datums/emergency_calls/contractor.dm
> +	M.transfer_to(H)
```suggestion
	M.transfer_to(H, TRUE)
```

2024-12-11 22:25 UTC, kiVts commented on code/datums/emergency_calls/pmc.dm
> +	M.transfer_to(H)
```suggestion
	M.transfer_to(H, TRUE)
```

2024-12-12 10:40 UTC, fira approved these changes

2024-12-13 18:57 UTC, merged