Adds a fax machine to requisitions
cmss13-devs/cmss13 pull request #7739
Opened 2024-12-04 17:58 UTC by L0pz

# About the pull request

Adds a fax machine to requisitions

# Explain why it's good for the game

I've always found it weird how an entire department doesn't have a singular fax machine. Especially since req can use them to ask for unique equipment, which they currently have to do via the public fax machine In the meeting hall.

# Testing Photographs and Procedure

<details>
<summary>

![image](https://github.com/user-attachments/assets/0bb32e94-0d25-42b0-b4ca-c2644051ce95)

</summary>

</details>

# Changelog

:cl:
add: Added a fax machine to requisitions. It's a girl, by the way.
/:cl:

2024-12-04 23:15 UTC, efzapa reviewed
the `desc` vars need quotes around them, that's what's causing it to fail

2024-12-05 06:38 UTC, Nanu308 requested changes

2024-12-05 06:38 UTC, Nanu308 commented on maps/map_files/USS_Almayer/USS_Almayer.dmm
> +	desc = The beloved fax machine of the Requisitions department. Be sure to make a convincing argument when you ask high command for a crate of lunge mines.;
quotation marks required for text strings. Repeat for other errors. Also no need to reference lunge mines.

2024-12-06 04:45 UTC, DexterDude commented
I don't think you removing the SEA fax machine was intentional, you should probably fix that.

2024-12-06 14:22 UTC, L0pz commented
> I don't think you removing the SEA fax machine was intentional, you should probably fix that.

Wait shit I thought I had fixed that

2024-12-08 01:35 UTC, Nanu308 approved these changes
Le fine

2024-12-08 01:51 UTC, merged