Ship Operations Synthetic
cmss13-devs/cmss13 pull request #7743
Opened 2024-12-05 02:16 UTC by QuickLode

# About the pull request
This PR adds a ship oriented Synthetic who is playable if there is no Survivor Synthetic present.

Issue at hand was although Synthetics readily accept RP, they are not able to easily go out of their way to initiate it due to their responsibilities outside of 3 phases: Pre-drop, Surgery, Post-drop.

This is a push to better incentivize the availability of Synthetics to RP. Currently they are burdened with a multitude of responsibilities compared to other roles which are able to prioritize RP. This effectively bridges that gap significantly, and encourages RP whilst by having 1 Synthetic operate more in-line with the bridge officer / ship maintenance synthetic within the bounds of lore.

BIG Thanks to Drathek for the role authority code!!!

Great suggestion by Beagle!!

# Explain why it's good for the game

Conducive to RP availability and pretty healthy for immersion within lore. Does not change the overall amount of Synthetics.
# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

![image](https://github.com/user-attachments/assets/7ae830f4-0e7f-4ddb-b83d-2d98006f8391)

![image](https://github.com/user-attachments/assets/d1b51c8c-fc1e-4c05-8556-1f57a72fc946)

![image](https://github.com/user-attachments/assets/c61b9f65-0093-428f-94f0-e9b75b813c32)

![image](https://github.com/user-attachments/assets/5cadf7d3-b005-47b6-a17b-70b606514631)

built ok 
</details>

# Changelog
:cl:
add: Adds the Ship Operations Synthetic. This ship-oriented Synthetic assists the USS Almayer with various tasks and improves the atmosphere of the vessel, they maintain the entire ship and act as its pilot. This role is enabled if there is no Survivor Synthetic present. Huge thanks to Drathek for roleauthority code!
add: Changes role selection color of WJ to be slightly darker to differentiate from Synthetics.
code: restructured lobby role selection menu to accomadate new role
/:cl:

2024-12-05 04:41 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-12-05 04:47 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-12-05 04:49 UTC, Diegoflores31 commented
i genuinely dont see where is the RP incentive and what kind of implementation there is to prevent this from just being a powercreep ? they way i see it this just allows for synths to steal the very little amount of work and responsability that shipside roles have . 
surgery ? with the synth instead of the docs because faster surgery
chemline? nah go with synth and he will use research juice instead
need something build ? synth
req ? synth

2024-12-05 13:54 UTC, TheGamerdk commented on code/game/jobs/slot_scaling.dm
> +	return job_slot_formula(playercount,100,1,1,2)
Old code / undocumented?

2024-12-06 02:33 UTC, Drulikar commented on code/game/jobs/slot_scaling.dm
> +	return job_slot_formula(playercount,100,1,1,2)
Fix this

2024-12-06 02:34 UTC, Drulikar requested changes

2024-12-06 02:34 UTC, Drulikar commented on code/game/jobs/job/civilians/support/synthetic.dm
> +	total_positions = 1
`/datum/job/civilian/synthetic` must then be reduced to 1

2024-12-06 02:34 UTC, Drulikar commented on code/__DEFINES/mode.dm
>  GLOBAL_LIST_INIT(ROLES_MISC, list(JOB_SYNTH, JOB_WORKING_JOE, JOB_SEA, JOB_CORPORATE_LIAISON, JOB_COMBAT_REPORTER, JOB_MESS_SERGEANT, JOB_WO_CORPORATE_LIAISON, JOB_WO_SYNTH))
Remove this line the linter is telling you about.

2024-12-06 03:17 UTC, Drulikar commented on code/game/jobs/job/civilians/support/synthetic.dm
> +	total_positions = 1
Likely also need to reduce `/proc/synth_slot_formula(playercount)` 's `max` argument from 2 to 1.

2024-12-16 03:55 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-12-16 07:56 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-12-16 08:40 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-12-16 10:29 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-12-16 12:44 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-12-16 14:18 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-12-18 21:03 UTC, realforest2001 commented
![image](https://github.com/user-attachments/assets/c61b2460-fa56-4552-a92c-f888af2df9a5)
Survivor Synth and Ship Operations synth.

2024-12-30 20:54 UTC, Drulikar approved these changes

2024-12-30 21:01 UTC, merged