XM-VESG-1 Flamer Nozzle or: How I Learned to Stop Worrying and Love the Burning Naphtha
cmss13-devs/cmss13 pull request #775
Opened 2022-07-29 22:14 UTC by Geevies

## About The Pull Request

Adds the XM-VESG-1 Flamer Nozzle, an attachment for the standard M240A1 incinerator unit. It allows the flamethrower to launch a fireball up to five tiles away from the user. It burns three units of fuel each use, and has a three second cooldown, independent of the flamethrower's.

Resprites the M240A1 and M240-T incinerator units, by Triiodine.

Special thanks to Kaga and Sargeantmuffinman for helping me get the name and description sorted.

## Why It's Good For The Game

It's pretty cool and gives mini-pyros the ability to blast something without leaving a trail of fire in the way.

## Changelog

:cl: Geeves, Triiodine
add: Adds the XM-VESG-1 Flamer Nozzle, an attachment for the standard M240A1 incinerator unit. Available in Req and Squad-Req as an underbarrel attachment.
imageadd: Resprites the M240A1 and M240-T incinerator units.
/:cl:

2022-07-31 10:54 UTC, Segrain commented on code/modules/projectiles/gun_attachables.dm
> +	return "It has [icon2html(src)] [name] ([current_rounds]/[max_rounds]) mounted underneath.<br>"
```suggestion
	return "It has [icon2html(src)] [name] ([internal_extinguisher.reagents.total_volume]/[internal_extinguisher.max_water]) mounted underneath.<br>"
```

2022-08-01 10:00 UTC, stanalbatross requested changes
fix being able to chungus the flamer

2022-08-06 22:46 UTC, stanalbatross requested changes

2022-08-06 22:46 UTC, stanalbatross commented on code/modules/projectiles/gun_attachables.dm
> +	return "It has [icon2html(src)] [name] ([internal_extinguisher.reagents.total_volume]/[internal_extinguisher.max_water]) mounted underneath.<br>"
```suggestion
	return "It has \a [icon2html(src)] [name] ([internal_extinguisher.reagents.total_volume]/[internal_extinguisher.max_water]) mounted underneath.<br>"
```

2022-08-06 22:46 UTC, stanalbatross commented on code/modules/projectiles/gun_attachables.dm
> +	return "It has [icon2html(src)] [name] mounted beneath the barrel.<br>"
```suggestion
	return "It has \a [icon2html(src)] [name] mounted beneath the barrel.<br>"
```

2022-08-06 22:46 UTC, stanalbatross commented on code/modules/projectiles/gun_attachables.dm
> +	to_chat(user, SPAN_WARNING("The gauge reads: <b>[round(gun.current_mag.get_ammo_percent())]</b>% fuel remains!"))
```suggestion
	to_chat(user, SPAN_WARNING("The gauge reads: <b>[round(gun.current_mag.get_ammo_percent())]</b>% fuel remaining!"))
```

2022-08-06 22:46 UTC, stanalbatross commented on code/modules/projectiles/gun_attachables.dm
> +	gun.muzzle_flash(Get_Angle(user_turf, target), user)
does the flamer get one?

2022-08-11 21:29 UTC, Sargeantmuffinman commented
The range is of it is too low.
4 tiles isn't enough to have the flamethrower attachment turn it into an offensive weapon.
Having it being able to be scaled by the fuel itself would be cool but probably out of scope of this PR.

I suggest upping the range to 6 tiles as that's one less than the 7 tile screen range.

2022-08-13 12:46 UTC, Sargeantmuffinman commented
It doesn't work with custom fuel.

2022-08-14 13:48 UTC, Geevies commented
> It doesn't work with custom fuel.

as far as i can tell, all the reagent code checks out, so it's something to do with custom chems, which is out of scope for this PR

2022-08-15 22:07 UTC, stanalbatross requested changes

2022-08-15 22:07 UTC, stanalbatross commented on code/modules/projectiles/gun_attachables.dm
> +	gun.muzzle_flash(Get_Angle(user_turf, target), user)
this just makes it do a generic muzzle flash when firing so either make a unique sprite (greyscale and colourswap based on reagent colour) or don't use it

2022-08-15 22:07 UTC, stanalbatross commented on code/modules/projectiles/guns/flamer/flamer.dm
> +	muzzle_flash(Get_Angle(get_turf(user), target), user)
same

2022-08-15 22:12 UTC, stanalbatross commented
> It doesn't work with custom fuel.

worked fine with a vved hydrogen on local

2022-08-16 13:25 UTC, Sargeantmuffinman commented
> > It doesn't work with custom fuel.
> 
> worked fine with a vved hydrogen on local

Try using a research generated one. Probably should have specified that we used that.

2022-08-20 10:56 UTC, Ticker175 commented
Sorry for the late comment but I was testing the nossle a week or so ago with coustom research chems and discovered that with the nossle attachment enabled, coustom chems do not work at all.

With a coustom chem tank loaded and the nossle enabled, the flamer will fire a projectile that creates a 1x1 normal fire where it lands for about half a second then it goes out. Tested with multiple diffrent research chems over multiple rounds


another thing that is most likely a research issue but I’ll mention nonetheless is that coustom chems are VERY weak and desperately need a buff, not only is their damage terrible but the effects of flowing is so so so limited with a max range of 4, the effects of viscious make the flamer 1 tile and there for literally unusable (it does (apparently) increase damage but it’s not even noticeable), the effects of fueling and oxidising are also extremely weak and fire pen is so weak it’s hard to even tell if it does ANY damage to fire proof xenos

2022-09-02 21:05 UTC, stanalbatross approved these changes

2022-09-04 07:21 UTC, nauticall approved these changes
Sprites look a-ok to me 👍

2022-09-15 19:31 UTC, Nanu308 commented
Might see future tweaks to range or its availability, approved.

2022-09-15 19:31 UTC, merged