Almayer Fitness Revamp - A Fully Working Gym
cmss13-devs/cmss13 pull request #7753
Opened 2024-12-06 17:14 UTC by Zenith00000

This PR adds a new section to the "Fitness" area, making it into a true "Gym", with actual working machines, sounds and a much needed visual improvement.

# Explain why it's good for the game

This would benefit the game by increasing RP potential and finally making use of the previously neglected Gym area. It adds much-needed visual appeal and functionality to the Gym, replacing the bare-bones setup we currently have.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

![Gym1](https://github.com/user-attachments/assets/2cdcb04d-5920-45f1-8fd6-8f036eca1a71)

![Gym3](https://github.com/user-attachments/assets/4bb61c2c-d7f1-4565-8dec-a4032c6cf495)

![Gym4](https://github.com/user-attachments/assets/3dad5c48-afed-4a3b-a350-e89775c17be7)

</details>

# Changelog

:cl:

code: working Gym machine code - ported from Paradise
soundadd: added some new sounds to go with the Gym equipment
imageadd: added some fitness related sprites, dumbbells, lifters and weight machines
maptweak: revamped the Almayer Fitness area

/:cl:

2024-12-07 08:26 UTC, Steelpoint commented
You removed the civilian clothing vendors from the area without placing them anywhere else.

2024-12-07 18:42 UTC, Zenith00000 commented
> You removed the civilian clothing vendors from the area without placing them anywhere else.

I know. Aren't they unnecessary though since they're only used on Greenshift right? Can only be accessed by Command and such? I was given the suggestion by Bobby to remove them completely. If they serve an actual purpose beyond Greenshift, then I don't see why they can't just be spawned in during an actual Greenshift, if not I'll add them back.

2024-12-07 18:52 UTC, Steelpoint commented
You should ask Nanu their thoughts. Personally, I would consider it akin to removing the dress vendors.

If you do proceed you should update the changelog to reflect the removal

2024-12-08 01:37 UTC, Nanu308 approved these changes

2024-12-08 01:37 UTC, Nanu308 commented on maps/map_files/USS_Almayer/USS_Almayer.dmm
mapping looks fine

2024-12-10 17:27 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-12-16 23:45 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-12-19 11:58 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-12-20 07:43 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-12-27 18:12 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-12-28 13:31 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-12-30 10:49 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2025-01-02 13:43 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2025-01-02 22:28 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2025-01-17 23:52 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2025-01-18 04:36 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2025-01-30 16:12 UTC, harryob requested changes

2025-01-30 16:12 UTC, harryob commented on code/game/objects/structures/gym.dm
> +		if(user.loc != src.loc)
```suggestion
		if(user.loc != loc)
```

2025-01-30 16:12 UTC, harryob commented on code/game/objects/structures/gym.dm
> +		playsound(user, 'sound/effects/spring.ogg', 40, TRUE, 2)
this should be using animation steps

2025-01-30 16:12 UTC, harryob commented on code/game/objects/structures/gym.dm
> +	while(lifts++ < 6)
why not

```suggestion
	for(var/lift in 1 to 6)
```

2025-01-30 16:12 UTC, harryob commented on code/game/objects/structures/gym.dm
> +	var/lifts = 0
```suggestion
```

2025-01-30 16:12 UTC, harryob commented on code/game/objects/structures/gym.dm
> +	while(reps++ < 6)
for(var/reps in 1 to 6)

2025-01-30 16:12 UTC, harryob commented on code/game/objects/structures/gym.dm
> +	sleep(3)
animation steps

2025-01-30 16:12 UTC, harryob commented on code/game/objects/structures/gym.dm
> +	var/list/hit_sounds = list('sound/weapons/genhit1.ogg', 'sound/weapons/genhit2.ogg', 'sound/weapons/genhit3.ogg',\
structure as long list

2025-01-30 16:12 UTC, harryob commented on code/game/objects/structures/gym.dm
> +/obj/structure/weightmachine/proc/AnimateMachine(mob/living/user)
snake case

2025-01-30 16:12 UTC, harryob commented on code/game/objects/structures/gym.dm
> +		to_chat(user, "It's already in use - wait a bit.")
SPAN_WARNING

2025-01-30 16:12 UTC, harryob commented on code/game/objects/structures/gym.dm
> +		user.visible_message("<B>[user] is [bragmessage]!</B>")
SPAN_BOLD, not <B>

2025-01-30 16:12 UTC, harryob commented on code/game/objects/structures/gym.dm
> +		to_chat(user, finishmessage)
SPAN_NOTICE

2025-01-31 03:45 UTC, Zenith00000 commented on code/game/objects/structures/gym.dm
> +		playsound(user, 'sound/effects/spring.ogg', 40, TRUE, 2)
may need help with these lasts bit of code, but I'll look tomorrow or so, thanks.

2025-02-05 21:23 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2025-02-25 23:11 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2025-03-16 00:03 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2025-03-18 17:28 UTC, realforest2001 approved these changes
Code looks fine

2025-03-20 15:53 UTC, Detective-Google commented on code/game/objects/structures/gym.dm
> +	M.visible_message(SPAN_DANGER("[M] slices \the [src] apart!"),
fix up the single letter vars 
https://github.com/cmss13-devs/cmss13/blob/master/.github/guides/STYLES.md#dont-use-abbreviations

2025-03-28 00:31 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2025-03-30 23:23 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2025-03-31 00:11 UTC, Detective-Google commented on code/game/objects/structures/gym.dm
> +		sleep(9 DECISECONDS)
this needs to use addtimer instead of sleep()

2025-03-31 00:13 UTC, Detective-Google commented on code/game/objects/structures/gym.dm
> +			return
need to replace the single letter variables https://github.com/cmss13-devs/cmss13/blob/master/.github/guides/STYLES.md#dont-use-abbreviations

2025-03-31 00:16 UTC, Detective-Google commented on code/game/objects/structures/gym.dm
> +		animate_machine(user)
this proc doesn't seem to do anything? it just returns at line 41.

2025-03-31 02:21 UTC, Zenith00000 commented on code/game/objects/structures/gym.dm
> +		animate_machine(user)
Hmm removing this line breaks the whole thing for some reason, it must do something?

2025-03-31 02:24 UTC, Zenith00000 commented on code/game/objects/structures/gym.dm
> +		sleep(9 DECISECONDS)
Also changing this to addtimer instead of sleep breaks it, although perhaps I'm just not understanding what you need me to do.

2025-03-31 02:32 UTC, Zenith00000 commented on code/game/objects/structures/gym.dm
> +		sleep(9 DECISECONDS)
Actually forget what I said, still works.

2025-03-31 02:53 UTC, Detective-Google commented on code/game/objects/structures/gym.dm
> +			if(A.loc == src.loc)
more 1 letter vars

2025-03-31 02:55 UTC, Detective-Google commented on code/game/objects/structures/gym.dm
> +			sleep(3 DECISECONDS)
still a lot of sleeps around

2025-03-31 02:57 UTC, Detective-Google commented on code/game/objects/structures/gym.dm
> +		addtimer(9 DECISECONDS)
not how addtimer works, I suggest looking at an example in code to learn, the timers used in the tutorial files (code/datums/tutorial) are relatively easy to understand.

2025-03-31 04:06 UTC, Zenith00000 commented on code/game/objects/structures/gym.dm
> +		addtimer(9 DECISECONDS)
Argh, just can't figure it out, I'm not a coder so I've really no clue what the hell any of this means.

2025-03-31 04:10 UTC, Zenith00000 commented on code/game/objects/structures/gym.dm
> +		addtimer(9 DECISECONDS)
Also what's the need to change from sleep? It seems like a simpler solution, but then again I've no clue, just basing this off how many words used.

2025-03-31 04:42 UTC, Detective-Google commented on code/game/objects/structures/gym.dm
> +		addtimer(9 DECISECONDS)
byond processes things in a set order, we have a fancy system called the Master Controller that is designed to schedule events, subsystems, timers, etc in a way that minimizes lag and stops everything breaking if something hangs, because Sleep() is a byond inbuilt proc, it tramples all over the master controller scheduling and can't be controlled, whereas our addtimer properly respects it, therefore sleep should be avoided wherever it is feasibly possible to do so, I don't see any reason sleep is necessary here. 

Addtimer is pretty simply honestly, you make the thing you want to happen at the end of the timer it's own proc, and it gets called when the timer ends. it just looks intimidating.

2025-03-31 05:08 UTC, Zenith00000 commented on code/game/objects/structures/gym.dm
> +		addtimer(9 DECISECONDS)
I tried doing like `	addtimer(CALLBACK(src, PROC_REF(animate_machine), user), 9 DECISECONDS)` but it just infinitely looped, I don't know how to do it right to be honest...

2025-04-02 20:57 UTC, Detective-Google requested changes
Gonna be on hold until those sleep()s get taken care of.

2025-04-11 02:21 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2025-04-11 17:34 UTC, LC4492 commented
> Gonna be on hold until those sleep()s get taken care of.

I suppose that, given you are requesting such to be done, would be helpful to explain how could he do it instead!

2025-04-19 15:50 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2025-04-20 04:59 UTC, Detective-Google reviewed
during my testing the animations on the machines did not sync with the animations on the player

2025-04-20 14:13 UTC, Zenith00000 commented
> during my testing the animations on the machines did not sync with the animations on the player

What do you mean? I don't think the animations were supposed to be completely in sync, as it wouldn't give the effect of the player "lifting", rather it would look like the machine is lifting them perhaps.

2025-04-20 14:41 UTC, Detective-Google commented
> > during my testing the animations on the machines did not sync with the animations on the player
> 
> What do you mean? I don't think the animations were supposed to be completely in sync, as it wouldn't give the effect of the player "lifting", rather it would look like the machine is lifting them perhaps.

https://github.com/user-attachments/assets/4e2b9868-54c1-48be-ba4f-148bf98385af

2025-04-20 21:58 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2025-05-05 00:45 UTC, closed without merging