Adds the CIA, Removes UAAC-TIS
cmss13-devs/cmss13 pull request #7757
Opened 2024-12-07 15:30 UTC by nauticall

# About the pull request

Adds the CIA, the intelligence agency that needs to introduction. Featuring a briefcase full of goodies, covert operations, and several disguises, CIA agents can be planted into various places or even into the USCM.

This PR fully replaces the UAAC-TIS intelligence officers formerly in the game. Nobody really used them (save for _a select few_) and I figured it'd be better to go out with the American Gestapo and in with actual spies.

Note that this is admin spawn only for now. In the future it's possible additional covers, ERT roles or even 

The following CIA covers have been added:

- Intelligence Analyst: The classic "tourist" business casual look of Vietnam-era CIA. Casual clothing, civilian rank, modifiable job.
- USCM Liaison: A CIA agent disguised as an intelligence liaison for the Corps. Military clothing, can be either O-2 (1st Lieutenant) or O-3 (Captain).
- Marine Raider: A CIA agent operating as a Marine Raider. They're on the same side, just possibly with differing objectives.
- UPP Soldier: A CIA agent disguised as a UPP grunt.
- UPP Senior Officer: A CIA agent disguised as a UPP _Starshiy Leytenant_.
- CLF Engineer: A CIA agent disguised as a CLF engineer/field technician.

All of the above come with the CIA briefcase, a device capable of procuring various goods and weaponry for use in spycraft. The briefcase includes things like:
- Abduction and sedation weapons like chloroform, a tranq gun, and handcuffs.
- Basic stationery (pen and paper).
- Marine armor and clothing, for when shit hits the fan.
- Extra magazines.
- Hacking stuff.
- Radio keys for various factions, including the CIA's own radio channel.
- Listening bugs.
- A USCM codebook for verifying you are actually with the government, in case anyone has doubts.

# Explain why it's good for the game

Spycraft! I believe adding CIA adds a ton of roleplay potential with these people as well as the ability to carry out actual (admin-sanctioned) antaggery like abducting people or interrogating others in a subtle, government-sanctioned way.

# The Elephant

CIA agents, naturally, work for the government of the United Americas, and nobody else. The USCM and CIA are fighting for the same team, but CIA might have interests that differ slightly or are above the paygrades of most marines, hence why they might go undercover. The USCM generally doesn't give much of a damn if they suspect CIA in their ranks, and if a CIA agent is found out by the Marines, nothing really ought to happen - analysts can provide valuable intelligence and aid USCM in their objectives, in the end.

For obvious reasons no CIA agent should ever say "I am with the CIA." If not outright disguised, it's up to the individual (or the admin) to fabricate a cover story, like "I'm an intelligence analyst working for ARMAT" or "I'm part of a battlefield survey team to improve logistics." You can modify your ID accordingly to suit your cover. Be creative, and be subtle.

# Screenshots
<details>
<summary>Screenshots & Videos</summary>

![image](https://github.com/user-attachments/assets/debdc096-633a-4821-81a2-df3c99979514)
![image](https://github.com/user-attachments/assets/59120e6a-6e41-4aef-ba78-3c529f1cd78d)
![image](https://github.com/user-attachments/assets/53b8679c-6099-4ea9-b1b7-4a21b323b729)
![image](https://github.com/user-attachments/assets/7b8c119b-6b1f-4b3b-8fe1-e34f5462ce0c)
![image](https://github.com/user-attachments/assets/3d6e92e0-c394-4f9a-a4f5-306cb1d38e2f)

</details>

# Changelog

:cl:
add: Adds CIA agents to the game. These are disguised as either civilians, liaisons, or people in other factions and have a plethora of tools to achieve any objectives they might be assigned to.
del: Deletes the UAAC-TIS from the game.
/:cl:

2024-12-08 20:29 UTC, RoboticVodka commented
Notably we do have the DNOP-CIU that fits the exact niche of the CIA per this old lore-tidbit if it's still considered canon: https://discord.com/channels/150315577943130112/942220424912203846/1007434833980555274 

I may also suggest if you stay with CIA though you put together an OWLF loadout as they're a part of the CIA. At least all the clothes exist (mask, hood, vest, and uniform) to make a full loadout just not weapons or any particular armor. Could give them some EMPs, some kinda of future-ish looking gun, motion detector, ETC and they'd probably be set.

2024-12-09 13:21 UTC, harryob requested changes
goated

2024-12-09 13:21 UTC, harryob commented on code/datums/skills/uscm.dm
> +/datum/skills/CIA
```suggestion
/datum/skills/cia
```

2024-12-09 13:21 UTC, harryob commented on code/game/objects/items/devices/portable_vendor.dm
> +	if(covert) return
```suggestion
	if(covert)
		return
```

2024-12-09 13:21 UTC, harryob commented on code/modules/gear_presets/cia.dm
> +	skills = /datum/skills/CIA
```suggestion
	skills = /datum/skills/cia
```

2024-12-09 13:21 UTC, harryob commented on code/modules/gear_presets/cia.dm
> +	skills = /datum/skills/CIA
```suggestion
	skills = /datum/skills/cia
```

2024-12-09 13:21 UTC, harryob commented on code/modules/gear_presets/cia.dm
> +	skills = /datum/skills/CIA
```suggestion
	skills = /datum/skills/cia
```

2024-12-09 13:21 UTC, harryob commented on code/modules/gear_presets/cia.dm
> +	skills = /datum/skills/CIA
```suggestion
	skills = /datum/skills/cia
```

2024-12-09 13:21 UTC, harryob commented on code/modules/gear_presets/cia.dm
> +	skills = /datum/skills/CIA
```suggestion
	skills = /datum/skills/cia
```

2024-12-09 13:21 UTC, harryob commented on code/modules/gear_presets/cia.dm
> +	M.attach_accessory(new_human, W)
```suggestion
	var/obj/item/clothing/under/colonist/clf/uniform = new()
	var/obj/item/clothing/accessory/storage/webbing/webbing = new()
	uniform.attach_accessory(new_human, webbing)
```

2024-12-09 13:21 UTC, harryob commented on code/modules/gear_presets/cia.dm
> +	new_human.equip_to_slot_or_del(M, WEAR_BODY)
```suggestion
	new_human.equip_to_slot_or_del(uniform, WEAR_BODY)
```

2024-12-10 12:04 UTC, harryob approved these changes

2024-12-11 16:48 UTC, harryob approved these changes

2024-12-11 16:56 UTC, merged