Embedding Demo
cmss13-devs/cmss13 pull request #776
Opened 2022-07-29 23:53 UTC by Kaga-404

## About The Pull Request

Experimental project related to the admin-spawnable disposable AT weapons, giving them a rare chance to embed upon impact with a softer-than-intended target. Credit to Stan for the anti-vehicle internal damage code.

## Why It's Good For The Game

This project explores some potential depth for the embedding system and throwing/dropping/volatile items, while also leading into the possibility of back-end updates for some outdated systems handling various mechanics (particularly shrapnel, embedding & embedded objects, attack/attackby/afterattack).

It is still largely a set of proof of concepts, but should be functional to serve as a rare bit of fun and creative immersive gameplay during events.

## Changelog

:cl: Kaga
add: Added in a new type of embedded shrapnel, unexploded ordnance. Currently only the event-related AT Rockets can rarely (5%) cause it when hitting unintended soft targets (human mobs) directly. Moving with one embedded has a small chance to detonate it with each step, but it can be yanked out as with other embedded objects.
add: Unexploded Anti-Tank Rockets can be manually detonated in various ways as a makeshift weapon or tool. While significantly weaker than proper rockets, they detonate in a contained direction when used. Despite the potential uses, they are highly unstable and prone to accidental detonations with each interaction. Exercise caution when handling them!
/:cl:

2022-07-29 23:57 UTC, Diegoflores31 commented
> ## About The Pull Request
> Experimental project related to the admin-spawnable disposable AT weapons, giving them a rare chance to embed upon impact with a softer-than-intended target. Credit to Stan for the anti-vehicle internal damage code.
> 
> ## Why It's Good For The Game
> This project explores some potential depth for the embedding system and throwing/dropping/volatile items, while also leading into the possibility of back-end updates for some outdated systems handling various mechanics (particularly shrapnel, embedding & embedded objects, attack/attackby/afterattack).
> 
> It is still largely a set of proof of concepts, but should be functional to serve as a rare bit of fun and creative immersive gameplay during events.
> 
> ## Changelog
> 🆑 Kaga add: Added in a new type of embedded shrapnel, unexploded ordnance. Currently only the event-related AT Rockets can rarely (5%) cause it when hitting unintended soft targets (human mobs) directly. Moving with one embedded has a small chance to detonate it with each step, but it can be yanked out as with other embedded objects. add: Unexploded Anti-Tank Rockets can be manually detonated in various ways as a makeshift weapon or tool. While significantly weaker than proper rockets, they detonate in a contained direction when used. Despite the potential uses, they are highly unstable and prone to accidental detonations with each interaction. Exercise caution when handling them! /🆑

very insane but if you increase the chance a lil more it would be a good deterret for not using the AT for people instead of vehicles

2022-08-08 10:18 UTC, stanalbatross requested changes

2022-08-08 10:18 UTC, stanalbatross commented on code/game/objects/items/shards.dm
> +		visible_message(SPAN_DANGER("You hear the click of a mechanism triggering inside [src] as [user] drops it. Uh oh."))
```suggestion
		visible_message(SPAN_DANGER("You hear the click of a mechanism triggering inside \the [src] as [user] drops it. Uh oh."))
```

2022-08-08 10:18 UTC, stanalbatross commented on code/game/objects/items/shards.dm
> +	if(!detonating && !thrown && !cause && prob(50))
make this prob(50) a var on the rocket

2022-08-08 10:18 UTC, stanalbatross commented on code/game/objects/items/shards.dm
> +	spawn(1)
use callback timer if you're gonna do this imo

2022-08-08 10:18 UTC, stanalbatross commented on code/game/objects/items/shards.dm
> +		to_chat(user, SPAN_WARNING("Your attempt to throw [src] was interrupted!"))
\the [src]

2022-08-08 10:18 UTC, stanalbatross commented on code/game/objects/items/shards.dm
> +			embedded_mob.visible_message(SPAN_DANGER("The [src] sticking out of [embedded_mob] suddenly explodes!"))
```suggestion
			to_chat(embedded_mob, SPAN_DANGER("\The [src] sticking out of you jostles roughly against your innards! Oh no."))
			embedded_mob.visible_message(SPAN_DANGER("\The [src] sticking out of [embedded_mob] suddenly explodes!"))
```

2022-08-08 10:18 UTC, stanalbatross commented on code/modules/mob/living/carbon/human/human.dm
>  		if(istype(W, /obj/item/shard/shrapnel))
```suggestion
		if(istype(W, /obj/item/large_shrapnel))
			var/obj/item/large_shrapnel/embedded = W
			embedded.on_embedded_movement(src)
		else if(istype(W, /obj/item/shard/shrapnel))
```

2022-08-20 10:44 UTC, stanalbatross approved these changes

2022-08-20 10:44 UTC, merged