Removes Dancer Praetorian acid and readds miss cooldown
cmss13-devs/cmss13 pull request #7765
Opened 2024-12-08 14:58 UTC by Lagomorphica

# Removes Dancer Praetorian acid and readds miss cooldown

This PR re-adds the miss-delay on Dancer Praetorian impale and tail-trip with a slightly lower value than what it originally had, alongside removing the acid.

# Explain why it's good for the game

Dancer praetorian is by design not supposed to have acid - the text you get when you pick it says that it's acid is supposed to be removed. It's also extremely unfun for a caste that is designed to delete one person to also instantly melt your equipment immediately after you die.

While the impale and tail-trip had their cooldown removed to buff dancer a while ago, it took what was designed to be a skill-based, instant-delete button caste into a caste that had a microstun that let you immediately use impale without tagging your target. Yes it's a T3 and it's supposed to be strong and fun but you can spam the ability and trip over someone with your dodge through mobs, then immediately impale them without thinking. The original cooldown was a bit too long in my opinion, so midway through making this PR I decided to lower it slightly.

# Testing Photographs and Procedure
N/A

<details>
<summary>Screenshots & Videos</summary>

N/A

</details>

# Changelog

:cl:
balance: Dancer praetorian has lost it's acid.
balance: Dancer praetorian tail-trip and impale now have a small cooldown on miss.
/:cl:

2024-12-08 16:11 UTC, Red-byte3D commented
was going to do this anyway,  good change

2024-12-13 12:15 UTC, harryob requested changes

2024-12-13 12:15 UTC, harryob commented on code/modules/mob/living/carbon/xenomorph/abilities/praetorian/praetorian_abilities.dm
> +	var/click_miss_cooldown = 10
defining these without using them won't do anything - the warrior implementation contains a check in /lunge/use_ability() that actually applies this cooldown

![image](https://github.com/user-attachments/assets/01b8870c-2a56-4986-b021-1fd6cec11418)

2024-12-15 22:38 UTC, harryob approved these changes
code

2025-01-16 00:18 UTC, Drulikar approved these changes

2025-01-16 00:18 UTC, Drulikar commented on code/modules/mob/living/carbon/xenomorph/abilities/praetorian/praetorian_abilities.dm
> +	var/impale_click_miss_cooldown = 15
```suggestion
	var/impale_click_miss_cooldown = 1.5 SECONDS
```

2025-01-16 00:18 UTC, Drulikar commented on code/modules/mob/living/carbon/xenomorph/abilities/praetorian/praetorian_abilities.dm
> +	var/tail_click_miss_cooldown = 15
```suggestion
	var/tail_click_miss_cooldown = 1.5 SECONDS
```

2025-01-16 00:25 UTC, Drulikar commented on code/modules/mob/living/carbon/xenomorph/abilities/praetorian/praetorian_powers.dm
> +		apply_cooldown_override(impale_click_miss_cooldown)
```suggestion
		apply_cooldown_override(impale_click_miss_cooldown)
		update_button_icon()
```

2025-01-16 00:25 UTC, Drulikar commented on code/modules/mob/living/carbon/xenomorph/abilities/praetorian/praetorian_powers.dm
> +		apply_cooldown_override(tail_click_miss_cooldown)
```suggestion
		apply_cooldown_override(tail_click_miss_cooldown)
		update_button_icon()
```

2025-01-16 00:28 UTC, Drulikar commented
Icons are now responsive.

2025-01-16 02:21 UTC, merged