req console tgui
cmss13-devs/cmss13 pull request #7774
Opened 2024-12-10 11:44 UTC by harryob

title

https://github.com/user-attachments/assets/fbf3b6ab-b892-47e3-9ce7-3b81ca7ae19c

https://github.com/user-attachments/assets/28b389ad-29ba-42b1-a35f-9d2e53be07c8

:cl:
add: the req ordering console has a new ui
/:cl:

2024-12-12 09:25 UTC, fira reviewed
DM looks good to me and what little i can decently review of UI template

Personal opinions:
 - The UI is a kinda big
 - The UI is a kinda awesome
 - Don't think the max button is really useful, but it clutters a bit, unless you just want to encourage meme mistakes which I'd 100% agree on 😏 
 - Otherwise I'd advocate ` X  -  [0] + `  instead of ` |< << [0] >> >|  `
 - Alternatively (additionally?) could just use a text field

2024-12-12 14:01 UTC, harryob commented
> * Don't think the max button is really useful, but it clutters a bit, unless you just want to encourage meme mistakes which I'd 100% agree on 😏
> * Otherwise I'd advocate `X  -  [0] +`  instead of `|< << [0] >> >| `
> * Alternatively (additionally?) could just use a text field

did all of these!

2024-12-15 06:25 UTC, Nanu308 approved these changes
mapping lgtm

2024-12-15 06:25 UTC, Nanu308 commented on maps/map_files/BigRed/BigRed.dmm
mapping lgtm

2024-12-15 06:25 UTC, Nanu308 commented on maps/map_files/BigRed/sprinkles/30.cargo_containers.dmm
mapping lgtm

2024-12-15 06:25 UTC, Nanu308 commented on maps/map_files/USS_Almayer/USS_Almayer.dmm
mapping lgtm

2024-12-15 06:25 UTC, Nanu308 commented on maps/tents/tent_reqs.dmm
mapping lgtm

2024-12-17 03:38 UTC, realforest2001 approved these changes

2024-12-22 01:45 UTC, ihatethisengine commented
![2024-12-22_04-43-58](https://github.com/user-attachments/assets/7a9cbffb-164f-4090-8d0d-5ffcbce49048)
bugged as hell, it keeps sending the same orders, probably because there were more pending orders than slots on the platform

2024-12-24 21:46 UTC, realforest2001 requested changes
Enjoy my super helpful review

2024-12-24 21:46 UTC, realforest2001 commented on maps/map_files/USS_Almayer/USS_Almayer.dmm
> +	req_one_access_txt = "90;91;92"
No

2024-12-24 21:46 UTC, realforest2001 commented on maps/map_files/USS_Almayer/USS_Almayer.dmm
> +	req_one_access_txt = "90;91;92"
No

2024-12-24 21:46 UTC, realforest2001 commented on maps/map_files/USS_Almayer/USS_Almayer.dmm
> +	req_one_access_txt = "90;91;92"
No

2024-12-24 21:46 UTC, realforest2001 commented on maps/map_files/USS_Almayer/USS_Almayer.dmm
> +	req_one_access_txt = "200;91;92"
No

2024-12-24 21:46 UTC, realforest2001 commented on maps/map_files/USS_Almayer/USS_Almayer.dmm
> +	req_one_access_txt = "200;91;92"
No

2024-12-31 17:38 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2025-01-01 10:36 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2025-01-01 18:22 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2025-01-01 19:54 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2025-01-05 16:29 UTC, realforest2001 approved these changes

2025-01-05 16:42 UTC, merged