Post dmi reorg fixes
cmss13-devs/cmss13 pull request #7782
Opened 2024-12-10 22:43 UTC by Blundir

# About the pull request

Fixes oversights from https://github.com/cmss13-devs/cmss13/pull/7021

# Changelog

:cl:
fix: broken icons
/:cl:

2024-12-12 21:35 UTC, Drulikar requested changes

2024-12-12 21:35 UTC, Drulikar commented on code/modules/cm_marines/Donator_Items.dm
`/obj/item/clothing/head/helmet/marine/fluff/sas_legion/select_gamemode_skin(expected_type, list/override_icon_state, list/override_protection)` is defined twice in this file, you likely intended one to instead be `/obj/item/clothing/suit/storage/marine/light/fluff/sas_legion/select_gamemode_skin(expected_type, list/override_icon_state, list/override_protection)`

2024-12-12 21:35 UTC, Drulikar commented on code/game/objects/items/storage/belt.dm
`if(gun_has_gamemode_skin & current_gun.map_specific_decoration)` should instead be `if(gun_has_gamemode_skin && current_gun.map_specific_decoration)`

2024-12-13 04:05 UTC, Drulikar requested changes
on mob sprite (head slot) for `/obj/item/clothing/head/helmet/skullcap` (can be found on corpses) is still honked: 
![image](https://github.com/user-attachments/assets/7fb43006-2205-45c2-b10f-a8098d6f9090)

2024-12-13 04:37 UTC, Drulikar requested changes

2024-12-13 04:37 UTC, Drulikar commented on code/modules/clothing/head/head.dm
Most headbands are using their on mob sprite as their item sprite: 
![image](https://github.com/user-attachments/assets/baccb8e2-72b5-4d10-9cc1-89d4c9363d50)

2024-12-13 04:37 UTC, Drulikar commented on code/modules/clothing/head/head.dm
on mob sprite (head slot) for `/obj/item/clothing/head/helmet/skullcap` (can be found on corpses) is still honked: 
![image](https://github.com/user-attachments/assets/7fb43006-2205-45c2-b10f-a8098d6f9090)
(reposted this so its in a resolvable comment)

2024-12-13 13:05 UTC, Blundir commented on code/modules/clothing/head/head.dm
was like this before, but gonna fix it

2024-12-13 15:53 UTC, Drulikar requested changes

2024-12-13 15:53 UTC, Drulikar commented on code/modules/clothing/head/head.dm
- On trijent dam (desert) `/obj/item/clothing/head/headband/red` is recolored to be dark grey as item, and matches when worn on the head. However, as a garb it will then be red.
- On trijent dam (desert) `/obj/item/clothing/head/headband` is recolored to be white/tan as item, and matches when worn on the head. However, as a garb it will then be green.

![image](https://github.com/user-attachments/assets/acf87a2a-33e3-4887-b77a-ecf01fda8da0)

2024-12-13 16:26 UTC, Blundir commented on code/modules/clothing/head/head.dm
made map specific helmet garb files and made headband sprites to match the `WEAR_HEAD` counterpart

2024-12-16 03:55 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-12-16 04:02 UTC, Drulikar submitted a review, later dismissed
Don't forget about riot shield issues from https://github.com/cmss13-devs/cmss13/pull/6649#discussion_r1884405985
- `/obj/item/weapon/shield/riot` right hand incorrect for east/west
As far as I see all other shields are correct.

2024-12-16 04:19 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-12-16 04:44 UTC, Blundir commented
shield fixed

2024-12-17 17:42 UTC, Red-byte3D commented
![image](https://github.com/user-attachments/assets/6c6e5031-8a59-44db-a9eb-ad3ad1a39661)

2024-12-17 17:42 UTC, Blundir commented
not caused by reorg tho

2024-12-17 17:44 UTC, Red-byte3D commented
> not caused by reorg tho

just assumed, thermal optics also have their sprites broken where should i put these instead

2024-12-17 17:45 UTC, Blundir commented
> > not caused by reorg tho
> 
> just assumed, thermal optics also have their sprites broken where should i put these instead

yeah these were me, i'll fix them

2024-12-18 14:48 UTC, harryob approved these changes

2024-12-18 14:55 UTC, merged