OB crate addition
cmss13-devs/cmss13 pull request #781
Opened 2022-07-30 12:36 UTC by JeserTheFox

1. Added OB ammo crate, capable of storing OB warheads and fuel only.
2. Added sprites for it.

## Why It's Good For The Game

Prevents Req from spending wasting 20 minutes dragging warheads and fuel from Req/ASRS to OB room.

## Changelog

:cl: Jeser
add: Added OB ammo crate capable of storing OB warheads and fuel only. New OBs come in this crate now.
imageadd: Added sprites for OB ammo crate.
/:cl:

2022-08-01 23:26 UTC, Agameofscones reviewed
Sprites look good to me

2022-08-01 23:27 UTC, Agameofscones approved these changes
nice coode

2022-08-04 08:39 UTC, stanalbatross requested changes

2022-08-04 08:39 UTC, stanalbatross commented on code/game/objects/structures/crates_lockers/secure_crates.dm
> +		return 0
return FALSE

2022-08-04 08:39 UTC, stanalbatross commented on code/game/objects/structures/crates_lockers/secure_crates.dm
> +	return 1
bools instead of numbers

if these actually use numbers and not booleans then refactor to use defines

2022-08-04 19:46 UTC, stanalbatross approved these changes

2022-08-04 19:46 UTC, merged