Fixes the NailGun Again
cmss13-devs/cmss13 pull request #7815
Opened 2024-12-13 19:16 UTC by Lukas-Seltz

# About the pull request

# Explain why it's good for the game

# Testing Photographs and Procedure

# Changelog

:cl:
fix: Fixed the CE vendor to be able to vend out what you should be able to. 
/:cl:

2024-12-13 20:11 UTC, fira commented
Won't that
 1. Let you buy 99 of these
 2. Prevent you eventually from using Dress Vendor
?
This one is handled specially

2024-12-14 01:35 UTC, Lukas-Seltz commented
> Won't that
> 
> 1. Let you buy 99 of these
> 2. Prevent you eventually from using Dress Vendor
>    ?
>    This one is handled specially

The problem is that with the old one, it links the Laser Designator and the Nail gun. I am working to figure out a better way to do it.

2024-12-14 11:18 UTC, fira commented
We merged multi-vending a while back so you could just bundle it in KIT with the PDA by making it a list

2024-12-14 11:18 UTC, fira commented
Example `list("Standard Marine Apparel", 0, list(/obj/item/clothing/under/marine, /obj/item/clothing/shoes/marine/knife, /obj/item/clothing/gloves/marine, /obj/item/device/radio/headset/almayer/marine), MARINE_CAN_BUY_UNIFORM, VENDOR_ITEM_MANDATORY),`

2024-12-14 15:46 UTC, Lukas-Seltz commented
While true I do not see a need to bundle the PDA and nail gun together

2024-12-14 17:30 UTC, fira commented
Well the need is just avoiding adding a MARINE_CAN_BUY_NAILGUN overspecific entry to every human in the game

2024-12-15 22:35 UTC, harryob requested changes
firas changes

2024-12-28 18:25 UTC, kiVts requested changes

2024-12-28 18:25 UTC, kiVts commented on code/game/machinery/vending/vendor_types/crew/senior_officers.dm
> +		list("Standard Equipment", 0, list(/obj/item/clothing/gloves/yellow, /obj/item/device/radio/headset/almayer/ce,  /obj/item/clothing/shoes/marine, /obj/item/clothing/glasses/welding, /obj/item/devic
```suggestion
		list("Standard Equipment", 0, list(/obj/item/clothing/gloves/yellow, /obj/item/device/radio/headset/almayer/ce,  /obj/item/clothing/shoes/marine, /obj/item/clothing/glasses/welding, /obj/item/device/working_joe_pda/uscm, /obj/item/weapon/gun/smg/nailgun/compact/tactical), MARINE_CAN_BUY_SHOES, VENDOR_ITEM_MANDATORY),
```

2024-12-28 18:27 UTC, kiVts approved these changes

2024-12-28 18:59 UTC, merged