[WIP] Overwatch can hear speech and see emotes
cmss13-devs/cmss13 pull request #7827
Opened 2024-12-15 15:18 UTC by ihatethisengine

# About the pull request
Overwatch consoles let you hear speech and see emotes around the marine you are overwatching. His speech will also appear as langchat over the console.

Why WIP? Needs some polishing and bug hunting, also need to port this to groundconsole because for some reason it's not a subtype??? 

# Explain why it's good for the game
It was in the movie. And we have to make observer+ role a bit more interesting. If there are any balance concerns I can make it work only when colony comms are online.

# Testing Photographs and Procedure

<details>
One day I'll record something, really lazy rn though
</details>

# Changelog

:cl: ihatethisengine
add: Overwatch can hear speech and see emotes.
/:cl:

2024-12-15 18:32 UTC, harryob requested changes

2024-12-15 18:32 UTC, harryob commented on code/modules/cm_marines/overwatch.dm
> +			return helm
```suggestion
	if(!current_squad)
		return

	if(istype(target) && istype(target.head, /obj/item/clothing/head/helmet/marine))
		var/obj/item/clothing/head/helmet/marine/helm = target.head
		return helm
```

2024-12-15 18:32 UTC, harryob commented on code/modules/cm_marines/overwatch.dm
> +/obj/structure/machinery/computer/overwatch/proc/get_helm_from_target(mob/living/carbon/human/H)
```suggestion
/obj/structure/machinery/computer/overwatch/proc/get_helm_from_target(mob/living/carbon/human/target)
```

2024-12-15 18:53 UTC, ihatethisengine commented
It's a draft why are you suggesting changes :sob:

2024-12-15 19:10 UTC, harryob commented
> It's a draft why are you suggesting changes 😭

do what i want

2024-12-19 14:20 UTC, harryob approved these changes

2024-12-19 14:21 UTC, harryob requested changes
jk - also most of the logic in the transfer speech/transfer emote procs are identical barring the checks on prefs - no way to reduce these down?

2024-12-19 14:21 UTC, harryob commented on code/game/machinery/computer/groundside_operations.dm
> +		langchat_speech(emote, get_mobs_in_view(7, src), null, null, TRUE, LANGCHAT_FAST_POP, list("emote"))
one nit - please use named args instead of passing null for your langchat_speech calls

2024-12-19 15:09 UTC, ihatethisengine commented
> also most of the logic in the transfer speech/transfer emote procs are identical barring the checks on prefs - no way to reduce these down?

Don't really see a way because emotes and speech use different sets of args. I can move Z check into a different proc but even then I would have to check if this is not an audible emote to pass it anyway.

2024-12-19 20:25 UTC, harryob approved these changes

2024-12-19 20:32 UTC, merged