[TM ONLY] EVENT WL MERRY CHIRMSTIKMASM
cmss13-devs/cmss13 pull request #7830
Opened 2024-12-16 15:48 UTC by irakligabunia

# About the pull request

this lets a person play every WL if they have 1 WL

# Explain why it's good for the game

GLOBALISM PLOT BY THE PREDS UNCOVERED
In all seriousness, I want people to try being in eachother's shoes. This is pending event approval, as I want to host it on christmas
(7th of January)

# Testing Photographs and Procedure
god told me this would work

</details>

# Changelog

:cl: stalkerino
add: lets people play all WLs if they have 1 WL
/:cl:

2024-12-16 15:48 UTC, irakligabunia commented
will test branch today

2024-12-16 18:29 UTC, irakligabunia commented
@Joelampost get the FUCK out of my PR an d my council

2024-12-16 19:13 UTC, Strobia commented
Finally access to pred 2.0 ( synthetic )

2024-12-16 21:25 UTC, Lukas-Seltz commented
ermm you missed a Whitelist

2024-12-16 21:31 UTC, Strobia commented
no we dont give a dam about the fax ''whitelist'' go sit afk in dchat and reply to a message noone readin

2024-12-17 00:13 UTC, Lukas-Seltz commented
Then this PR does not fit the description you have put on it

2024-12-17 00:21 UTC, Lukas-Seltz commented
To be clear Fax responder is a whitelist and should be added to the Mix to make everything far. You can't exclude one whitelist from it. This is in no way meant to be rude

2024-12-17 08:08 UTC, Drulikar requested changes
I see you didn't test :P

With the suggested changes:
![image](https://github.com/user-attachments/assets/06f05da9-004f-4c50-b87d-55ab957b0f41)
Though I'll note doing it how you're doing it will be a bit funky:
- The whitelist panel will incorrectly toggle on these now grouped whitelists when *reading* their value
- The whitelist panel will only *write* the value(s) you select but the player being modified will only have the whitelist you just wrote. When the game restarts or ultimately whitelists are re-read, then they will have the grouped whitelists again.

So that's to say:
- If you're going to use the whitelist panel, but sure to only assign values you want to linger
- When updating whitelists using the whitelist panel, they won't get access to the other whitelists until the next round.

Also worth noting in case you intended otherwise: The automatic staff whitelist for working joe does not grant them the other whitelists with this code. They would have to explicitly be whitelisted for working joe to get the other whitelists.

2024-12-17 22:49 UTC, Drulikar commented
https://github.com/cmss13-devs/cmss13/pull/7840 was required for the linters

2025-01-16 03:28 UTC, Drulikar commented
Event over.

2025-01-16 03:28 UTC, closed without merging