Xeno strain resetting
cmss13-devs/cmss13 pull request #7841
Opened 2024-12-17 18:16 UTC by Git-Nivrak

# About the pull request
Allows xenos to reset their strain, first use is free after that it can be used every 40 minutes

# Explain why it's good for the game
Allows players to change their strain if they do not enjoy playing it anymore or the round has went on for long enough it became basically useless - happier players >> profit. (You could also make a point for new players that accidently clicked a strain out of curiosity and now want to reset it)

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
add: Xenomorphs can now reset their strain, first use is free then it can be done once every 40 minutes.
/:cl:

2024-12-20 00:37 UTC, Drulikar requested changes
As mentioned on discord: This is ripe for bugs and exploitation.
- Just recreate the xeno. Look at de-evolve to see what all ought to be transfered
- Consider just refactoring de-evolve at this point since there's 3 places that effectively want the same code: deevolve verb, queen deevolve action, and now this.

2024-12-31 19:44 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-12-31 19:50 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2025-01-03 18:38 UTC, harryob requested changes

2025-01-03 18:38 UTC, harryob commented on code/modules/mob/living/carbon/xenomorph/strains/xeno_strain.dm
> +	if(alert(usr, "Are you sure?", "Reset Strain", "Yes", "No") != "Yes")
tgui_alert liberal

2025-01-03 18:38 UTC, harryob commented on code/modules/mob/living/carbon/xenomorph/Xenomorph.dm
> +	var/next_strain_reset
cooldown_declare

2025-01-03 18:38 UTC, harryob commented on code/modules/mob/living/carbon/xenomorph/strains/xeno_strain.dm
> +	if(world.time < next_strain_reset)
cooldown_finished

2025-01-03 18:38 UTC, harryob commented on code/modules/mob/living/carbon/xenomorph/strains/xeno_strain.dm
> +	if(!can_take_strain(reset=TRUE))
```suggestion
	if(!can_take_strain(reset = TRUE))
```
not python

2025-01-03 18:38 UTC, harryob commented on code/modules/mob/living/carbon/xenomorph/strains/xeno_strain.dm
> +		new_xeno.next_strain_reset = world.time + 40 MINUTES
cooldown_start

2025-01-03 18:38 UTC, harryob commented on code/modules/mob/living/carbon/xenomorph/strains/xeno_strain.dm
> +	if(new_xeno)
early return

2025-01-06 11:25 UTC, harryob approved these changes

2025-01-06 11:37 UTC, merged