Field Doctor
cmss13-devs/cmss13 pull request #7857
Opened 2024-12-19 13:05 UTC by Ansekishokuu

# About the pull request

Just like the PR that split Pilot Officers, this PR aims to make a Field Doctor occupation, so whoever rolls it gets to deploy instead of arguing between who wants to deploy.

Doctor and Field Doctor are identical, one has no advantage over the other and they share the same skills.

There is a 5 hour requirement on medical roles to be a Field Doctor right now, rather than a jokingly low 1 hour on normal Doctor role because it needs more skill and knowledge. I can lower this if this is a problem, though i think it is within reason.
I also might need some suggestions on the Field Doctor's shortened job name when they talk over comms, if the current one is a problem that is.

# Explain why it's good for the game

Being a FOB doctor requires more in game knowledge and skill.
How it usually goes is that either the FOB doctor has good knowledge on what they are doing OR knows nothing and ruins the round of the person who just came to get some fracs fixed and come out with more fracs, an OD, and organ damage.

It makes no sense that whoever gets to ask for permission to the CMO first gets to deploy, it's just a race not determined by a fair job roll.
Or even worse, they argue over the deployment and it usually ends in a grudge between two people, and other doctors that are not interested in being a shipside doctor goes cryoing, leaving the almayer with no doctor.

# Testing Photographs and Procedure

Here is the job icon for the field doctor, inspired from both WO field doctor and normal doctor job icons.

![image](https://github.com/user-attachments/assets/250f3aa1-b0ef-4e8d-aa98-1f2c1da679db)

# Changelog

:cl: Ansekishoku
add: A new Field Doctor job to end the arguments between doctors about who wants to deploy.
/:cl:

2024-12-19 13:07 UTC, Git-Nivrak commented
They should have basuc firearms training if they are going to deploy to an active AO

2024-12-19 13:10 UTC, Blundir requested changes
ideally change the cross color, not the border color, also make sure to add unique minimap icons, currently there is none

2024-12-19 13:13 UTC, Ansekishokuu commented
> They should have basic firearms training if they are going to deploy to an active AO

Doctors dont, so i didnt add it.
I also was planning to add a light armor at first, but then i went with the "if i dont change things too much, it wont cause problems with people complaining about it" mentality.

2024-12-19 16:48 UTC, Lukas-Seltz commented
> > They should have basic firearms training if they are going to deploy to an active AO
> 
> 
> 
> Doctors dont, so i didnt add it.
> 
> I also was planning to add a light armor at first, but then i went with the "if i dont change things too much, it wont cause problems with people complaining about it" mentality.
> 
> 
> 
> Though i can add those if we really want it.

I understand where you are coming from with the firearm's training but if they are field Doctor they are going to be trained in the bare minimum at least for firearms so I agree with them having at least firearm one and giving them light armor is good. Since if they can go to req and get it anyways. (What I do as FOB doc)

You are a Field Surgeon the Colonial Marines wouldn't send you to the colony without knowing how to shoot a gun. 

I know this is a little long but I have one more thing to say. Whether you are a doctor or a rifleman you have gone through basic training and in basic training for both they teach you at minimum how to clean, shoot, and maintain you rifle or sidearm.

2024-12-19 21:22 UTC, Blundir approved these changes

2024-12-19 23:36 UTC, efzapa commented
> > > They should have basic firearms training if they are going to deploy to an active AO
> > 
> > 
> > 
> > Doctors dont, so i didnt add it.
> > 
> > I also was planning to add a light armor at first, but then i went with the "if i dont change things too much, it wont cause problems with people complaining about it" mentality.
> > 
> > 
> > 
> > Though i can add those if we really want it.
> 
> I understand where you are coming from with the firearm's training but if they are field Doctor they are going to be trained in the bare minimum at least for firearms so I agree with them having at least firearm one and giving them light armor is good. Since if they can go to req and get it anyways. (What I do as FOB doc)
> 
> You are a Field Surgeon the Colonial Marines wouldn't send you to the colony without knowing how to shoot a gun. 
> 
> I know this is a little long but I have one more thing to say. Whether you are a doctor or a rifleman you have gone through basic training and in basic training for both they teach you at minimum how to clean, shoot, and maintain you rifle or sidearm.

thing being, a Field Doctor shouldn't even be using a weapon in the first place, this would just make them a Corpman+ role

If there is any scenario where a Field Doctor has to shoot something, the op is probably FUBAR anyways.

2024-12-27 18:12 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-12-28 12:07 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-12-29 02:24 UTC, Nanu308 approved these changes
mapping lgtm

2024-12-29 02:24 UTC, Nanu308 commented on maps/map_files/USS_Almayer/USS_Almayer.dmm
mapping lgtm

2024-12-30 10:49 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-12-30 20:15 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-12-31 17:38 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2025-01-01 13:07 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2025-01-01 20:24 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2025-01-02 00:48 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2025-01-16 03:01 UTC, Drulikar approved these changes

2025-01-16 06:57 UTC, Drulikar requested changes

2025-01-16 06:57 UTC, Drulikar commented on code/game/jobs/job/civilians/support/field_doctor.dm
> +	entry_message_body = "You are a <a href='"+WIKI_PLACEHOLDER+"'>Field Doctor</a> tasked with keeping the marines healthy and strong in the field. Usually in the form of surgery."
The wiki will need to have Field Deployment amended if/when this is merged, but this entry message needs to make an attempt to convey that:
- The Almayer medbay takes priority (as in it must not be unmanned)
- CMO as their superior can still establish rules for deployment
- Deployment can only occur to a secure location (not first drop)

2025-01-16 13:29 UTC, SubjectD9341 commented
Having a single doc deploy and take all patients groundside while all others stay shipside and fiddle with their thumbs waiting for the occasional hugged patient is already incredibly unfun. This behavior absolutely shouldn't be streamlined into a mechanic in-game.

2025-01-16 14:16 UTC, Ansekishokuu commented
> Having a single doc deploy and take all patients groundside while all others stay shipside and fiddle with their thumbs waiting for the occasional hugged patient is already incredibly unfun. This behavior absolutely shouldn't be streamlined into a mechanic in-game.

I am aware of this, i have also talked with maintainers about this. This PR has been on hold for a month of long thought process; and still is. The latest conclusion was that unless transportation was made reliable, doctor deployment cant be thrown out the window.

Also, i am aware of your concern but thats more of a doctor gameplay issue than a field doc issue, this being streamlined doesnt change anything other than the explanation i made multiple times and will paste here too:

The PR was to make people who want to deploy roll the field doc role instead of hogging the shipside doctor role.

2025-01-17 03:06 UTC, Drulikar requested changes

2025-01-17 03:06 UTC, Drulikar commented on code/game/jobs/job/civilians/support/field_doctor.dm
> +	entry_message_body = "You are a <a href='"+WIKI_PLACEHOLDER+"'>Field Doctor</a> tasked with keeping the marines healthy and strong in the field. Usually in the form of surgery. You must stay onboard
```suggestion
	entry_message_body = "You are a <a href='"+WIKI_PLACEHOLDER+"'>Field Doctor</a> tasked with keeping the marines healthy and strong in the field, usually in the form of surgery. You must stay onboard the Almayer medical bay if there are no other doctors present and until the FOB is secured. Your superiors may also delay your deployment to the field."
```

2025-01-17 03:37 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2025-01-17 04:10 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2025-01-17 09:27 UTC, Drulikar approved these changes

2025-01-31 01:17 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2025-02-12 11:30 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2025-02-17 23:32 UTC, merged