Thrall Overhaul
cmss13-devs/cmss13 pull request #7880
Opened 2024-12-22 04:19 UTC by Nomoresolvalou

This PR is going to majorly buff yautja thralls.
Here is the list of things thralls will get:
thrall armor is buffed to no longer be complete ass
thralls wearing their bracer will no longer be slowed down by weeds, trigger traps, or be affected by acid splashes on melee hits
thralls will be able to create a crystal similar to the pred thwei crystal, loaded with a special chem that will make them stun resistant, move faster, not take organ damage, and in addition to all the things thwei already does, it acts as a painkiller.

for the predator that thralls someone, they will now have two new ways to threaten their slave. First they can remotely stun their thrall (10 second stun).
and if they're really being a shitter then you can remotely set their bracer to SD (will also stun them so they can't run into anyone) and gib them just like how normal pred SD works

As a disclaimer, I have not been able to test the new features that the thrall bracer provides, as for some reason putting a bracer on in a local host causes the game to crash. I have no idea why this happens but just from looking at the code it SHOULD work. Testing will be needed to verify this however.

# Explain why it's good for the game

Currently thralls kind of suck. Their armor barely protects them from anything, and they die to practically everything since they can't use guns. Becoming a thrall is literally just a death sentence. One warrior grab and you're dead.
This PR should bring thrall up to not OP levels, but something where you can actually stand a chance fighting something for your master instead of falling over after taking three bullets.

Currently the armor buff is slight, so I am open to increasing the armor even more if it is deemed necessary.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl: Nomoresolvalou

balance: thrall armor increased
add: thralls can now create crystals of stimulant to aid them in combat
balance: thralls are no longer slowed by weeds, trigger traps, or hit by acid splashes on xeno melee hits.
add: predators can now remotely stun and self destruct their thralls

/:cl:

2024-12-22 06:58 UTC, efzapa commented on code/modules/reagents/chemistry_reagents/medical.dm
> +/datum/reagent/medical/thwie/thwong //OP yautja thrall chem
`/datum/reagent/medical/thwei/thwong`

2024-12-22 21:41 UTC, Diegoflores31 commented
we have currently a human subtype called "human hero" consider using that instead of crystals and stuff you were adding.

additionally remote SD may not be good considering it takes away all the "gear recovery" part . consider either removing it or making it only works while they are alive

2024-12-22 22:17 UTC, irakligabunia commented
Council only approves this if the following happens:
1. The stims are removed in exchange for being a hero mob

2. The remote SD stays.

2024-12-22 22:28 UTC, Nomoresolvalou commented
Alright so I’ll check out the hero mob stuff, as this is the first time hearing about its existence.

and preventing gun usage should be simple as well.

2024-12-22 22:39 UTC, squidqueen commented
Presumably the council will still want them to have a thewi human flavoured even if they're a hero mob correct stalkerino? Given that preds get it too and the stabilizer crystal is kinda needed for how damaging a frac is to a human?

2024-12-23 08:06 UTC, Diegoflores31 commented
> Presumably the council will still want them to have a thewi human flavoured even if they're a hero mob correct stalkerino? Given that preds get it too and the stabilizer crystal is kinda needed for how damaging a frac is to a human?
 
Human heros cant get fractures

2024-12-23 08:10 UTC, Diegoflores31 commented
> and preventing gun usage should be simple as well.

I recomend you making a subtype of the Hero mob called thrall for easier balancing

2024-12-23 09:09 UTC, squidqueen commented
The only issue with reassigning a species, doesn't it like automatically change your name, flavour text and hair along with deleting your items?

2024-12-23 09:38 UTC, Diegoflores31 commented
> The only issue with reassigning a species, doesn't it like automatically change your name, flavour text and hair along with deleting your items?

not necesarily . there are ways to export all of those from your original character . tho it would be funny if your name changed to whatever name your pred master gave you

2025-01-28 21:26 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2025-02-04 01:48 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2025-02-05 04:07 UTC, kiVts requested changes

2025-02-05 04:07 UTC, kiVts commented on code/game/objects/items/reagent_containers/autoinjectors.dm
> +/obj/item/reagent_container/hypospray/autoinjector/yautja/thrall/attack(mob/M as mob, mob/user as mob)
never need `as mob`, also single letter vars

2025-02-05 04:07 UTC, kiVts commented on code/modules/cm_preds/thrall_procs.dm
> +		var/turf/T = get_turf(thrall)
single letter var

2025-02-05 04:07 UTC, kiVts commented on code/modules/reagents/chemistry_reagents/medical.dm
> +
remove the spaces, this messes with git blame (whoever uses that anyways)

2025-02-05 04:07 UTC, kiVts commented on code/modules/cm_aliens/structures/trap.dm
> +				L.visible_message(SPAN_WARNING("[L] trips on [src]!"),\
harry just pr`ed removal of all \ in visible message, dont add those

2025-02-05 21:12 UTC, Red-byte3D commented on code/game/objects/items/reagent_containers/autoinjectors.dm
> +
leftover i asusme

2025-02-05 21:12 UTC, Red-byte3D commented on code/modules/cm_preds/thrall_items.dm
> +	name = "thrall bracers"
should be singular probably since its one bracer that goes on one hand?

2025-02-05 21:12 UTC, Red-byte3D commented on code/modules/reagents/chemistry_reagents/medical.dm
> +
leftover i assume

2025-02-06 04:28 UTC, Nomoresolvalou commented on code/modules/cm_preds/thrall_items.dm
> +	name = "thrall bracers"
they actually go on both hands. You can see them both on the sprite, they're like gloves. the normal yautja bracers are also plural in the code

![image](https://github.com/user-attachments/assets/8ac9c093-db7a-48ff-b087-348e8a09073c)

2025-02-06 18:45 UTC, kiVts requested changes

2025-02-06 18:45 UTC, kiVts commented on code/modules/cm_preds/thrall_procs.dm
> +	if(alert("Are you sure you want to detonate this [thrall.species]'s bracer? There is no stopping this process","Explosive Bracers", "Yes", "No") == "Yes")
tgui alert

2025-02-07 07:40 UTC, Git-Nivrak requested changes

2025-02-07 07:40 UTC, Git-Nivrak commented on code/modules/cm_aliens/structures/trap.dm
> +			if(ishuman(victim))
Any reason this isn't ishumanstrict? you seem to return on every other case

2025-02-07 07:40 UTC, Git-Nivrak commented on code/modules/cm_preds/thrall_procs.dm
> +	else
return when it fails and remove the last else

2025-02-07 07:40 UTC, Git-Nivrak commented on code/modules/cm_preds/thrall_procs.dm
> +	if(tgui_alert(thrall, "Are you sure you want to detonate this [thrall.species]'s bracer? There is no stopping this process","Self Destruct Thrall", list("Yes", "No")) == "Yes")
Return if the answer is no, remove the code below from the if

2025-02-07 07:40 UTC, Git-Nivrak commented on code/modules/cm_preds/thrall_procs.dm
> +		if(thrall.stat != DEAD)
same here, return if dead

2025-02-07 19:41 UTC, Nomoresolvalou commented on code/modules/cm_aliens/structures/trap.dm
> +			if(ishuman(victim))
huh, I didn't know ishuman_strict was a thing. I'll replace that then.

2025-02-08 09:32 UTC, Git-Nivrak approved these changes

2025-02-08 09:58 UTC, merged