Corporate Dome Nightmare Insert Expansion
cmss13-devs/cmss13 pull request #7893
Opened 2024-12-23 08:17 UTC by BOBAMAx

# About the pull request

Adds engi, medic, and TL to corp dome nightmare insert. Changes some other fluff stuff like factions so they appear in the WY tab and the MD in the insert doesn't ping on goons. Adds flavor uniforms for goon med and engi with different armbands

# Explain why it's good for the game

engis and medics and TLs incentivize people to stick together and cooperate with their fellow man instead of hiding or running off or whatever. facilitates more interesting roleplay. Everything else is minor detailing and fluff like faction tabs and alt uniform sprites.

# Testing Photographs and Procedure

<details>
<summary>In game</summary>

![gooning](https://github.com/user-attachments/assets/9f16d8e7-ed98-4c8f-bae8-37dba5662ef4)

</details>

# Changelog

:cl:
add: Goon Medic
imageadd: New alt uniforms for goon techs and medics
maptweak: Corporate Dome nightmare insert now has a medic, engi, and TL.
/:cl:

2024-12-23 22:09 UTC, thevandie commented
I have sprites for this that you should add!

2024-12-27 18:14 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-12-27 22:17 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2025-01-01 20:24 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2025-01-02 08:01 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2025-01-04 10:53 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2025-01-04 23:49 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2025-01-13 17:40 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2025-01-13 18:49 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2025-01-13 23:05 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2025-01-15 06:26 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2025-01-16 02:25 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2025-01-16 07:26 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2025-01-17 03:37 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2025-01-18 01:33 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2025-01-18 01:33 UTC, realforest2001 requested changes

2025-01-18 01:33 UTC, realforest2001 commented on maps/map_files/LV624/standalone/corporatedome.dmm
> +	icon = 'icons/mob/humans/onmob/clothing/uniforms/uniforms_by_faction/WY.dmi';
What's going on here

2025-01-18 01:33 UTC, realforest2001 commented on maps/map_files/LV624/standalone/corporatedome.dmm
> +	icon = 'icons/mob/humans/onmob/clothing/head/hats_by_faction/WY.dmi';
And here

2025-01-18 01:33 UTC, realforest2001 commented on maps/map_files/LV624/standalone/corporatedome.dmm
> +	icon = 'icons/mob/humans/onmob/clothing/uniforms/uniforms_by_faction/WY.dmi';
And here

2025-01-18 01:33 UTC, realforest2001 commented on maps/map_files/LV624/standalone/corporatedome.dmm
> +	icon = 'icons/mob/humans/onmob/clothing/feet.dmi'
And here

2025-01-18 01:33 UTC, realforest2001 commented on maps/map_files/LV624/standalone/corporatedome.dmm
> +	icon = 'icons/mob/humans/onmob/clothing/head/hats_by_faction/WY.dmi';
And here

2025-01-18 01:33 UTC, realforest2001 commented on maps/map_files/LV624/standalone/corporatedome.dmm
> +	icon = 'icons/mob/humans/onmob/clothing/uniforms/uniforms_by_faction/WY.dmi';
And here

2025-01-18 01:33 UTC, realforest2001 commented on maps/map_files/LV624/standalone/corporatedome.dmm
> +	icon = 'icons/mob/humans/onmob/clothing/masks/masks_by_faction/WY.dmi';
And here

2025-01-18 01:33 UTC, realforest2001 commented on maps/map_files/LV624/standalone/corporatedome.dmm
> +	icon = 'icons/mob/humans/onmob/clothing/feet.dmi';
And here

2025-01-18 01:33 UTC, realforest2001 commented on maps/map_files/LV624/standalone/corporatedome.dmm
> +	icon = 'icons/mob/humans/onmob/clothing/uniforms/uniforms_by_faction/WY.dmi';
And here

2025-01-18 01:33 UTC, realforest2001 commented on maps/map_files/LV624/standalone/corporatedome.dmm
> +	icon = 'icons/mob/humans/onmob/clothing/head/formal_hats.dmi';
And here

2025-01-18 19:44 UTC, Nanu308 approved these changes
mapping is fine

2025-01-31 01:17 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2025-01-31 18:35 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2025-02-06 10:42 UTC, realforest2001 approved these changes

2025-02-07 09:50 UTC, Blundir approved these changes

2025-02-07 10:01 UTC, merged