MRE Big Content Update: Cornbread Edition
cmss13-devs/cmss13 pull request #7895
Opened 2024-12-23 14:16 UTC by Blundir

# About the pull request

This pr aims to bring more content to existing MRE, also adding numerous factional rations, which include:

- PMC - expensive white ration with luxurious foods and new mini wy cigarette packets
- WY general - far less expensive ration for security and colonists, comes packed with simpler meals and also this https://avp.fandom.com/wiki/Bug_Juice
- WY emergency food packets - inspired by Seven Oceans emergency sea rations, a highly nutritious dry cookie like bricks

<details>
  <summary>Irl thing</summary>

![image](https://github.com/user-attachments/assets/fac5e5a3-8087-4cfd-8cc1-6b2146f0270d)

</details>

- TWE - slightly inspired by British ration, another expensive ration, comes with mechanically unique paste tube that has vegemite/fruit spread inside
- UPP - irl Russian inspired ration with canned food mainly, with added can openerer mechanics and some iconic foods
- CLF - improvised food packet as opposed to a coherent ration
- Generic ration - Insprired by https://en.wikipedia.org/wiki/First_Strike_Ration, a more private market oriented ration with similar contents to a normal MRE, for use for neutral factions like Freelancers and Private Military Contractors

![image](https://github.com/user-attachments/assets/d9ad4721-7188-46b9-9131-c5f0b5a7cd59)

![dreammaker_5SJewgwUYv](https://github.com/user-attachments/assets/33e5fd85-f155-48a2-a104-1fab85741449)

In addition to all that, rations themselves were reworked on backend, now food items have "taste", previously all food was either pure nutrient/salt/sugar and had no description to it, now every mre food item has a new unique description and custom reagent contents which gives more direct taste when eating the ration, as opposed to "You taste Nutrients"

This pr also reverts https://github.com/cmss13-devs/cmss13/pull/7111, gives some mres to req vendor instead.

This pr deletes a placeholder for WY mre box replacing it with actual WY rations, and deletes USCM tray boxes, replacing them with an actual MRE.

<details>
  <summary>Checklist on progress</summary>

**USCM**
- [x] new meals
- [x] dedicated cheese spread
- [x] dedicated beverage bag
- [x] spoon

**PMC**
- [x] main meals
- [x] side meals
- [x] deserts
- [x] drinks (one of drinks inspired by drink from here https://github.com/cmss13-devs/cmss13-pve/pull/581)
- [x] unique small cigarette packets for WY gold and Executive black packets
- [x] storage box 

**WY**
- [x] main meals
- [x] storage box 
- [x] drinks (will add this to it https://avp.fandom.com/wiki/Bug_Juice)

**WY emergency**
- [x] main thing
- [x] storage box 

**TWE**
- [x] main meals
- [x] side meals
- [x] deserts
- [x] drinks
- [x] storage box
- [x] vegemite/jam spread tube mechanics

**UPP**
- [x] side meals
- [x] deserts
- [x] drinks
- [x] storage box
- [x] tin can and can opening mechanics

**CLF**
- [x] the main thing

**Generic ration**

- [x] main meals
- [x] drinks
- [x] storage box

</details>

New USCM food sprites, cheese spread, spoon, beverage by **Nauticall**

All new ration sprites, all pmc, upp and twe packet/tube/cans sprites, can opener sprites by **Crowford**, discord tag **sir.crow**

Some new TWE food sprites (energy bar, tea) from **Triiodine**

All new inhands by **LC4492**

All new floor boxes and cig packets sprites by me

# Explain why it's good for the game

More lore props, content, variety and potential rp

# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

![image](https://github.com/user-attachments/assets/7b19efde-8741-454f-b66b-678cef0ed193)

![image](https://github.com/user-attachments/assets/44c80bf1-caee-4927-b78f-459f693ec22b)

![image](https://github.com/user-attachments/assets/3b5eb231-8880-4a0b-9e55-ed2907050f26)

![image](https://github.com/user-attachments/assets/eeb984e4-5c51-4ad2-b320-36caa914795a)

![dreamseeker_SJlyQmwGDS](https://github.com/user-attachments/assets/7cfc4a84-90db-4129-8425-5368fa3c0672)

![dreamseeker_zcBZsFh8Np](https://github.com/user-attachments/assets/fb014138-1ff8-4930-8297-f5cc55ad2cda)

</details>

# Changelog
:cl: Blundir, Crowford, Nauticall, Cuberound, Triiodine, LC4492
add: added UPP, WY, PMC, TWE, WY emergency, Generic food rations, floor boxes for them
add: USCM MRE now has cheese spread in multiple variations, beverage bag in multiple variations (you need to pour water into it)
add: balaji imperial 4 packs and matches, matches added to WY vendor, both matches and cigs can appear in TWE ration
add: USCM MRE now has an iconic MRE spoon
add: added numerous new mains, sides, snacks and desserts to USCM MRE 
add: all ration food now has unique descriptions and reagents inside them having custom reagents now displays food taste correctly
add: new rations to loadouts that should logically have them
del: WY brand MRE box got removed and replaced with an actual WY rations
del: USCM tray boxes got removed and replaced with an actual MREs
del: remove MRE from prep vendors
refactor: mre backend changed severely and moved to separate .dm files
del: core nutrient reagent is no longer used for mre foods, apart from some exceptions
maptweak: added new rations around the maps where they logically make sense
/:cl:

2024-12-23 14:27 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-12-23 19:01 UTC, Staykeu commented
absolutely badass PR

give the MRE spoon an in-helmet sprite, make it a helmet accessory and it'll be insane

2024-12-23 22:44 UTC, efzapa commented
let the CL be able to print WY MREs :)

2024-12-23 22:50 UTC, Blundir commented
> let the CL be able to print WY MREs :)

i'm gonna give CL like 2 normal WY ration, but printing? no

2024-12-24 20:23 UTC, Blacklist897 commented on code/game/objects/items/reagent_containers/food/mre_food.dm
> +	desc = "You can't even taste processed meat taste under all those sprices!"
spices

2024-12-24 20:25 UTC, Blacklist897 commented on code/game/objects/items/reagent_containers/food/mre_food.dm
> +	desc = "Contains a very salty food spread, good to combine with a sandwich, not everyone is fond of the taste and looks of it tho."
might be best to change the "tho"

2024-12-30 10:49 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-12-31 14:09 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-12-31 19:50 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2025-01-01 23:12 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2025-01-02 21:27 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2025-01-05 03:46 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2025-01-13 11:04 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2025-01-16 13:34 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2025-01-31 01:17 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2025-02-15 16:02 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2025-02-19 16:13 UTC, Git-Nivrak requested changes

2025-02-19 16:13 UTC, Git-Nivrak commented on code/game/objects/items/reagent_containers/food/cans.dm
> +	if(istype(opening_tool, /obj/item/tool/kitchen/can_opener))
Looks at how surgery does it with defines instead of istyping everything

2025-02-19 16:13 UTC, Git-Nivrak commented on code/game/objects/items/reagent_containers/food/cans.dm
> +	if(do_after(user, opening_time, INTERRUPT_ALL, BUSY_ICON_GENERIC))
if(!do_after)
    return

2025-02-19 16:13 UTC, Git-Nivrak commented on code/game/objects/items/reagent_containers/food/cans.dm
> +		if(prob(25) && istype(opening_tool, /obj/item/attachable/bayonet || /obj/item/tool/kitchen/knife  || /obj/item/weapon/sword/machete))
you can't do this (/obj/item/attachable/bayonet || /obj/item/tool/kitchen/knife || /obj/item/weapon/sword/machete)

2025-02-19 16:13 UTC, Git-Nivrak commented on code/game/objects/items/reagent_containers/food/cans.dm
> +		user.update_inv_r_hand()
Is this necessary?
`update_inv_r_hand` `update_inv_l_hand`

2025-02-19 16:13 UTC, Git-Nivrak commented on code/game/objects/items/reagent_containers/food/cans.dm
> +	if(!open)
if(open)
    return

2025-02-19 16:13 UTC, Git-Nivrak commented on code/modules/reagents/chemistry_reagents/food.dm
> +	if(!.) return
no inline control statements

2025-02-21 12:57 UTC, Git-Nivrak approved these changes
Code fine (needs sprite approval)

2025-02-21 15:15 UTC, Git-Nivrak commented
Might need to address some more chems appearing in research recipes

2025-02-22 14:37 UTC, JackieEstegado commented on code/modules/reagents/chemistry_reagents/food.dm
> +
```suggestion
flags = REAGENT_NO_GENERATION

```

2025-02-22 14:37 UTC, JackieEstegado commented on code/modules/reagents/chemistry_reagents/food.dm
> +
flags = REAGENT_NO_GENERATION

2025-02-22 14:49 UTC, JackieEstegado commented on code/modules/reagents/chemistry_reagents/food.dm
> +
So I dont spam the page, here are all the reagents that shouldnt be in chem recipes (due to there being no bulk source of them other than MREs (which you would need hundreds of to make even a single pillbottle of whatever its ingredient of)) and need fixing.

coconutmilk
tea_leaves
coco_drink_hazelnut
coco_drink

2025-02-22 16:54 UTC, Blundir commented on code/modules/reagents/chemistry_reagents/food.dm
> +
REAGENT_NO_GENERATION has nothing to do with recipes, it's about them generating in botany

2025-02-25 22:22 UTC, Nanu308 approved these changes
awesome mapping details

2025-02-25 23:43 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2025-02-25 23:47 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2025-02-27 16:49 UTC, nauticall approved these changes
oh yeah baby

2025-02-27 18:11 UTC, merged