Fix of starting overload on reactor message
cmss13-devs/cmss13 pull request #7912
Opened 2024-12-25 04:52 UTC by blackcrystall

# About the pull request
... title said everything

# Changelog

:cl: BlackCrystalic
fix: starting of reactor overload message now give right info
/:cl:

Closes #7847

2024-12-28 14:09 UTC, fira requested changes

2024-12-28 14:09 UTC, fira commented on code/game/machinery/fusion_engine.dm
>  		set_overloading(!overloaded)
I understand your changes, but similarly this would mean these are also inverted

2024-12-28 14:09 UTC, fira commented on code/game/machinery/fusion_engine.dm
>  		set_overloading(!overloaded)
diff hates me. the two ones below set_overloading() since it'll change its state

2024-12-31 11:50 UTC, harryob approved these changes

2024-12-31 12:21 UTC, merged