Shivas Panic Room Insert Changes
cmss13-devs/cmss13 pull request #7922
Opened 2024-12-27 12:20 UTC by BOBAMAx

# About the pull request

Changes the presets of the survivors that spawn in the panic room insert on Shivas. Inspired by [this scene from Aliens: Dark Descent](https://youtu.be/QMCG9A80L50&t=2074)

# Explain why it's good for the game

When I asked people what their least favorite nightmare insert was, this one was the most common answer. The most common complaints were that it was boring and could never spawn engineers. This is an attempt to give it more sovl and adding a chance for an engineer, with a guarantee of an engineer if you have at least 5 survivors.

# Testing Photographs and Procedure

<details>
<summary>Screenshot</summary>

![image](https://github.com/user-attachments/assets/62ec0177-e1b9-4c15-8dc2-a82c712a6df4)

</details>

# Changelog

:cl:
maptweak: changed the presets on the shiva's panic room insert to have an engineer and 1 pmc
/:cl:

2024-12-30 10:39 UTC, Nanu308 requested changes
Mapping itself is fine, needs a balance approval/look at for the PMC addition and gear

2024-12-30 22:45 UTC, BOBAMAx commented on maps/Nightmare/maps/Ice_Colony_v3/nightmare.json
> -		"chance": 0.5,
unintentional from forcing it for testing. Will remove.

2025-02-12 17:33 UTC, Git-Nivrak commented
Only real PMC gear here is the armor so I would say it is fine

2025-02-12 17:33 UTC, Git-Nivrak approved these changes

2025-02-12 17:46 UTC, merged