Project Youngblood (Testing Needed)
cmss13-devs/cmss13 pull request #7925
Opened 2024-12-27 17:17 UTC by Joelampost

# About the pull request
This PR introduces a role for non-whitelisted players on CM, allowing them to play as predators in the hunting grounds. This provides an opportunity for players who might want to apply for the whitelist or simply experience a role they haven't played before.

Players rolling for the role will need 40 hours as any marine in a squad AND 40 hours as any xeno role.

This PR will need ironing out before it is ready to be merged.

Mapping changes:

1.  I have expanded the predship Z level to 80x70 to accommodate the youngblood area.
2. Greatly expanded the fighting pit as another is located in the lower deck (youngblood area), expanded the room outwards by two tiles also. Screenshots are provided.
3. The lower deck of the ship is lit with red light.
4. Removed the globe in the cockpit replaced it with the console that calls the youngblood ERT.

List of things youngbloods cannot do:

1. Youngbloods cannot use the plasma caster (as completing the blooding trial grants them this in lore).
2. Youngbloods cannot use the relay beacon or NORMAL teleporters on the clan ship I have made separate ones for them to use.
3. Youngbloods cannot use self destruct ANYWHERE as they are only meant for the hunting grounds. The hunting grounds does not allow self destruct in the first place so the only reason that a youngblood would be SDing is if they intended to grief.
4. They can't use any of the consoles relating to the hunting grounds as they are supposed to be supervised by whitelisted players or an admin.

List of things youngbloods can do:

1. Choose their own armour set and colour from the same preference menu as the hunting grounds erts (whitelisted players cannot see this menu). No names or flavour text because i don't trust CM players not to name their pred something stupid.
2. They every other bracer ability that was not mentioned in what they cannot do.
3. If they survive whitelisted players will be encouraged to return them to the clanship to roleplay.

Fali safes:

1. Whitelisted players can use a button on their bracer to instantly kill any Youngblood alive if they eg: break character, break the honour code or insult a blooded member. This is intended as a last resort warnings should be given out before anyone presses this button. I don't want to see whitelisted players instantly killing a youngblood for one minor insult. 
2. A new ERT job ban is in place for youngbloods for obvious reasons.
3. If any whitelisted predator player takes a youngblood into the main part of the game they will be removed from the whitelist.
4. On spawning youngbloods are told what they cannot do in terms of roleplay and the honour code.

# Explain why it's good for the game
It introduces people who have never played predator to what the whitelist is about and sharing is good. With the failsafe's in place i don't see anything major going wrong as they are mechanically unable to effect the round in anyway.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

 Lower ship younblood spawn and prep with night vison on

![image](https://github.com/user-attachments/assets/e4da9b9a-2474-46ad-94cb-3752944907eb)

Lower ship younblood spawn and prep with night vison off
![image](https://github.com/user-attachments/assets/34bc53e8-6f5e-40df-96d9-d6c15760b8ca)

New fighting pit and ladders
![image](https://github.com/user-attachments/assets/fc2bc422-75e8-4c50-bc34-33f70e4db9bf)

</details>

# Changelog

:cl: Joe Lampost, Forrest2001
add: A role for non-whitelisted players to play predator.
add: A new console and ert have been added relating to spawning youngbloods.
add: Feral xenos on the hunting grounds now drop weeds when they spawn.
add: A kill button for whitelisted pred players to instantly kill any youngblood acting out of line.
code: Predator teleporting now has checks.
mapadd: added a lower deck on the pred ship for youngbloods.
maptweak: tweaked the fighting pit area of the predship.
admin: Adds a new roleban relating to youngbloods.
/:cl:

2024-12-27 20:28 UTC, irakligabunia commented
fuck you lampsot

2024-12-29 02:46 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-12-29 03:03 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-12-30 18:47 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-12-31 02:38 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2025-01-01 18:22 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2025-01-01 18:22 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2025-01-01 22:50 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2025-01-27 17:40 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2025-01-27 18:05 UTC, Nanu308 requested changes
see comments

2025-01-27 18:05 UTC, Nanu308 commented on maps/predship/huntership.dmm
Space tiles under some windows. Overall good improvement to predship.
![image](https://github.com/user-attachments/assets/a236b76f-d9d7-4071-a18a-41f0b7b4244a)

2025-01-27 18:05 UTC, Nanu308 commented on maps/templates/lazy_templates/pred/jungle_moon.dmm
lgtm

2025-01-29 08:48 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2025-01-29 20:56 UTC, Nanu308 approved these changes
mapping lgtm

2025-01-31 01:17 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2025-01-31 02:17 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2025-01-31 10:38 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2025-01-31 10:51 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2025-02-06 16:12 UTC, Git-Nivrak requested changes

2025-02-06 16:12 UTC, Git-Nivrak commented on code/game/machinery/vending/vendor_types/antag/antag_predator.dm
> +	if(user.faction == FACTION_YAUTJA_YOUNG)
Put this logic under `allowed()` (override the proc and make sure to call the parent) and return false on anything other than `FACTION_YAUTJA` rather than checking for youngblood

2025-02-06 16:12 UTC, Git-Nivrak commented on code/modules/clans/client.dm
> +				ranks -= CLAN_RANK_ADMIN && CLAN_RANK_YOUNG // Admin rank should not and cannot be obtained from here, Youngblood is only for non-WL players
```suggestion
				ranks -= list(CLAN_RANK_ADMIN, CLAN_RANK_YOUNG) // Admin rank should not and cannot be obtained from here, Youngblood is only for non-WL players
```

2025-02-06 16:12 UTC, Git-Nivrak commented on code/modules/cm_preds/yaut_items.dm
> +		if(!blooding_type::blooding_name)
```suggestion
		if(!blooding_type.blooding_name)
```

2025-02-06 16:12 UTC, Git-Nivrak commented on code/modules/cm_preds/yaut_items.dm
> +		un_blooded[blooding_type::blooding_name] = blooding_type
```suggestion
		un_blooded[blooding_type.blooding_name] = blooding_type
```

2025-02-07 06:08 UTC, Git-Nivrak requested changes

2025-02-07 06:08 UTC, Git-Nivrak commented on code/datums/emergency_calls/emergency_call.dm
> +	var/time_required_for_youngblood = 40 HOURS
Should be defined on the young blood datum

2025-02-07 06:08 UTC, Git-Nivrak commented on code/datums/emergency_calls/pred_hunt/hunting_calls.dm
> +			continue
You should move the WL and Jban check to be the first thing on the for loop, otherwise it won't do anything

2025-02-07 06:08 UTC, Git-Nivrak commented on code/game/machinery/vending/vendor_types/antag/antag_predator.dm
> +	return TRUE
This is the exact same as `/obj/structure/machinery/cm_vending/clothing/yautja/can_access_to_vend`, redundant

2025-02-11 19:23 UTC, Git-Nivrak approved these changes

2025-02-11 19:39 UTC, merged