Nightmare Insert: Hybrisa - IASF Outpost Souter
cmss13-devs/cmss13 pull request #7954
Opened 2024-12-31 05:17 UTC by Steelpoint

# About the pull request

Adds the Imperial Army Space Force Outpost Souter to Hybrisa Prospera. In-lore, this is intended to represent the period of time prior to the withdrawal of the IASF from the colony due to political pressure from the Company. 

Outpost Souter is a smaller, ancillary, basing for a single UD4-UK Dropship and a small detachment of ISAF personnel. The primary, and larger, base would be further west of the colony, as represented by the (blocked off) escape tunnel network under the base.

This insert will over right the Company Offices, located outside of the space port. The concept being that the Company knocked down the outpost and replaced it with an office building. 

The insert is currently set to occur at a 25% chance, this can be changed if desired. 

Furthermore, this insert does not add new IASF survivors or corpse spawners. This would require the work of a spriter, and would be a future project if anyone wants to pursue it. 

# Explain why it's good for the game

More variation on a map, gives more backstory hints as well. 

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

![twe](https://github.com/user-attachments/assets/ee18319d-6aeb-4e96-8564-d3017a171fdd)

</details>

# Changelog

:cl:
mapadd: IASF Outpost Souter has been added as a nightmare insert for Hybrisa Prospera. Part of the larger detachment of Imperial Armed Space Forces that defended the colony. The IASF had been forced to withdraw prior to the events of the xenomorph outbreak, however this insert represents a timeline where the IASF had not fully completed their withdrawal. 
code: Added a set of transparent versions of the TWE cosmetic Dropship for mappers to use. 
/:cl:

2025-01-27 17:56 UTC, Nanu308 requested changes
See Comments

2025-01-27 17:56 UTC, Nanu308 commented on maps/map_files/LV759_Hybrisa_Prospera/standalone/twe_airbase.dmm
Good job overall 👍 

If nooping turf, might as well noop area as well. 
![image](https://github.com/user-attachments/assets/fe7e9349-b928-436b-9e96-01653ab58899)

Invis walls, I do not see the reason for them? Please explain why they're needed if so
![image](https://github.com/user-attachments/assets/d3feb1cb-487a-407d-9b99-d2b79dc458d8)

Someone has given me notice that the TWE Guns might be a bit too strong to find for survs. I'll check them before final review, but other than these small things, looking good.

2025-01-27 17:56 UTC, Nanu308 commented on maps/Nightmare/maps/LV759_Hybrisa_Prospera/nightmare.json
25% Might be a bit high, will keep in back of head for final review

2025-01-28 00:09 UTC, Steelpoint commented on maps/map_files/LV759_Hybrisa_Prospera/standalone/twe_airbase.dmm
I'll make the nooping changes soon.

Regarding the I-Walls, re-reviewing the rational there is no obvious reason for its inclusion. It was intended more as a OOC/Mapping concept to better identify that the stairs are intended to lead to off-map/different z-level, but this was just another one of my weird esoteric ideas I forgot to fix. I'll remove the I-walls.

The TWE firearms. From my testing they are essentially equilivant to Marine rifles, except without any 2-handed slowdown. I'd be happy to reduce the amount of ammo, or remove the weapons and replace with regular P90's or similar weapons found on the map.

2025-01-28 11:58 UTC, Steelpoint commented
I've addressed the main issues.

- I can adjust the % chance for this to occur to whatever value is desired.
- I can adjust the presence of TWE firearms as required. TWE guns are generally as strong as USCM firearms but with little to now movement slowdown on wielding them. If this is too much, I can either reduce the amount of ammo, guns, or replace them with P90s and similar map-friendly equilivants.

2025-01-30 17:27 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2025-01-30 22:28 UTC, Nanu308 commented
> I've addressed the main issues.
> 
>     * I can adjust the % chance for this to occur to whatever value is desired.
> 
>     * I can adjust the presence of TWE firearms as required. TWE guns are generally as strong as USCM firearms but with little to no movement slowdown on wielding them. If this is too much, I can either reduce the amount of ammo, guns, or replace them with P90s and similar map-friendly equilivants.

Will merge for now, in future i might go over ammo amount etc. when time after seeing effects of survs/marines using the equipment.

2025-01-30 22:29 UTC, Nanu308 approved these changes
approved mapping

2025-02-01 03:42 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2025-02-05 21:23 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2025-02-06 08:16 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2025-02-21 03:50 UTC, Drulikar approved these changes

2025-02-21 03:58 UTC, merged