Tgui crewmanifest
cmss13-devs/cmss13 pull request #7955
Opened 2024-12-31 06:47 UTC by nauticall

# About the pull request

Modifies the Crew Manifest from its current iteration to a shiny, dynamically-updating TGUI version. Style and backend shamelessly ripped and cannibalized from Aurora. Squads and departments are color coded, leaders are highlighted, and status is represented with a marker that displays status when moused-over (e.g. Active, Inactive or Deceased).

# Explain why it's good for the game

Who doesn't like sleek things that do stuff better? This new manifest is prettier, refreshes automatically, and uses TGUI, which is nice.

# Testing Photographs and Procedure
![image](https://github.com/user-attachments/assets/5c0a3467-2f28-40b2-a116-0b6797a4f91b)
![image](https://github.com/user-attachments/assets/102b99de-42c5-47ac-bb28-f80b4350ad26)
![image](https://github.com/user-attachments/assets/20ccc4ff-ff1b-4c99-a066-cd4e3109cdb2)
![image](https://github.com/user-attachments/assets/01b55a02-5ba0-4add-95a9-20dc78a9cb3b)

# Changelog

:cl:
ui: Changed the crew manifest to TGUI.
/:cl:

2024-12-31 16:09 UTC, realforest2001 commented
Needs to account for specialist assignments 
![image](https://github.com/user-attachments/assets/5720977f-02b1-4af8-adae-6288142ea9d5)

2024-12-31 17:39 UTC, zzzmike commented
Currently, there's no scroll bar on the right, and you also can't middle click to bring up the scroll icon. This makes it a lot more difficult to scroll if your mouse wheel is finnicky, would it be possible to add one or both of these?

2025-01-01 06:09 UTC, nauticall commented
![image](https://github.com/user-attachments/assets/cf767f5b-f139-4f1e-a57e-c38de9124b59)
![image](https://github.com/user-attachments/assets/d08be9f7-a8fd-42c0-bf3e-a1a0ebbff7ae)
![image](https://github.com/user-attachments/assets/144f7062-af77-41c9-9809-44cf73778c8a)

fixed the spec stuff, and added both scroll bar + search bar functionality :3

2025-01-02 16:26 UTC, nauticall commented
![image](https://github.com/user-attachments/assets/ac0060dd-9db7-4659-a5ac-2d684d959d9b)

2025-01-02 20:31 UTC, harryob requested changes
nitpicks

2025-01-02 20:31 UTC, harryob commented on code/datums/crew_manifest.dm
> +			data[entry_dept] += list(entry)
```suggestion
			LAZYADD(data[entry_dept], list(entry))
```

2025-01-02 20:31 UTC, harryob commented on code/datums/crew_manifest.dm
> +			data["Miscellaneous"] += list(entry)
ditto

2025-01-03 20:32 UTC, harryob requested changes

2025-01-03 20:32 UTC, harryob commented on code/datums/crew_manifest.dm
> +				data[entry_dept] = list()
```suggestion
```
this is what the lazyadd does

2025-01-03 20:32 UTC, harryob commented on code/datums/crew_manifest.dm
> +				data["Miscellaneous"] = list()
```suggestion
```

2025-01-04 10:42 UTC, harryob approved these changes

2025-01-04 11:50 UTC, merged