bouncing bettys the unbreaking
cmss13-devs/cmss13 pull request #798
Opened 2022-08-02 01:03 UTC by johnravioliUSA

## About The Pull Request
(This PR is a carbon copy of #773 but instead of being batshit broken on my end, this is more up to date. my bad for making a commit 3 months ago and never using it LOL ok heres the updated one)

This PR adds in a new landmine, exclusively able to be bought from squad engineer vendors, or combat technician vendors for 30 points. It can be obtained through requisitions, although a limited amount exist there.
Requisitions has 2 at the start of a round, but it scales with the pop, so 2 on low, 4 on high. This is because it is effectively a better claymore, so that's why it's halved.

The mine itself is based off the bouncing betty, a mostly shrapnel based mine, which is what I replicated. Once detonated, the bounding mine has 48 pieces of shrapnel that shoot out compared to the claymore's 12 in one direction. This is prone to changes as it might be too powerful, who knows. The mine itself is capable of dealing massive amounts of damage to back liners, ideally runners or lurkers. It can crit them if they get RNG'd, but there is basically no way of it insta killing unless you're wounded already.

You can only plant these on actual ground, not the floor of colony buildings or the Almayer itself. There is a 50/50 chance of when you disarm it that you will blow up, this is only when you don't have the faction's IFF (I.e. you are CLF disarming a USCM mine).

Demonstration: the pause in the video is a runtime error, which probably effected the explosion. Besides that you'd have to see that for yourself.

https://streamable.com/e2m85b

https://streamable.com/e9mcuj (Older video with older stats, that were changed. imagine this but smaller, like 50% the size of this shit)

## Why It's Good For The Game

The bouncing betty is canon in Aliens lore, as it is a marine landmine. Besides that, I believe that more variety in some of the items is better, because the claymore isn't the only landmine that a marine force would use. I think this would go nicely for something like backline defense, defending the FOB from being harassed by lurkers and runners by strategically putting landmines around in the jungle, or desert, whatever the case may be. Would probably make for some interesting gameplay, that's all I got to say.
Would also make HvH more hectic with more things you can give marines AND UPP / CLF

## Changelog

:cl:
add: The M5 Bounding Mine aka Bouncing Betties. These mines can be obtained from req or engineer prep vendors. The mine itself is a low power shrapnel landmine that shoots out a lot of shrapnel in a 360 degree angle when you step on it. Sprites by Frans_Feiffer
/:cl:

2022-08-02 01:23 UTC, sose96 commented
I hope this makes it in, I'd love to make some minefield nightmare inserts.

2022-08-02 02:14 UTC, Agameofscones approved these changes
sprites lgtm

2022-08-09 15:53 UTC, stanalbatross requested changes

2022-08-09 15:53 UTC, stanalbatross commented on ColonialMarinesALPHA.dme
> -#include "code\__DEFINES\text.dm"
keep in original place

2022-08-09 15:53 UTC, stanalbatross commented on ColonialMarinesALPHA.dme
> +#include "code\datums\beam.dm"
keep in original place

2022-08-09 15:53 UTC, stanalbatross commented on code/game/machinery/vending/vendor_types/squad_prep/squad_engineer.dm
>  		list("M40 MFHS Metal Foam Grenade", 5, /obj/item/explosive/grenade/metal_foam, null, VENDOR_ITEM_REGULAR),
5 comes after 4

2022-08-09 15:53 UTC, stanalbatross commented on code/game/objects/items/explosives/mine.dm
> +		user.visible_message(SPAN_NOTICE("[user] stops deploying [src]."), \
\the [src]

2022-08-09 15:53 UTC, stanalbatross commented on code/game/objects/items/explosives/mine.dm
> +		SPAN_NOTICE("You finish deploying [src]."))
\the

2022-08-09 15:53 UTC, stanalbatross commented on code/game/objects/items/explosives/mine.dm
> +		to_chat(user, SPAN_WARNING("You can't plant a mine here."))
\a [src]

2022-08-09 15:53 UTC, stanalbatross commented on code/game/objects/items/explosives/mine.dm
> +		to_chat(user, SPAN_WARNING("There already is a mine at this position!"))
is already a mine

2022-08-09 15:53 UTC, stanalbatross commented on code/game/objects/items/explosives/mine.dm
> +				user.visible_message(SPAN_WARNING("[user] stops disarming [src]."), \
\the [src]

2022-08-09 15:53 UTC, stanalbatross commented on code/game/objects/items/explosives/mine.dm
> +			if(!do_after(user, 3 SECONDS, INTERRUPT_NO_NEEDHAND, BUSY_ICON_FRIENDLY))
should probably be interrupt all

2022-08-09 15:53 UTC, stanalbatross commented on code/game/objects/items/explosives/mine.dm
> +			SPAN_NOTICE("You finish disarming [src]."))
\the [src]

2022-08-10 19:31 UTC, PhantomEpicness commented
seems like there is a lot of unnecessary copy and pasting of code where existing code could have simply been reworked to be more modular and therefore easier to make new mines in the future.

 I also happened to be working on a project like this in the past, check out PhantomEpicness/AntiTankMine for an example of a rework, feel free to copy from there if you want.

2022-08-12 17:31 UTC, johnravioliUSA commented
I wasn't intending to rework something, just adding something that seemed cool. But I will take a look at it nethertheless

2022-08-13 21:25 UTC, stanalbatross requested changes

2022-08-13 21:25 UTC, stanalbatross commented on code/game/objects/items/storage/boxes.dm
> +/obj/item/storage/box/explosive_mines/fill_preset_inventory()
```suggestion
/obj/item/storage/box/explosive_mines/bounding/fill_preset_inventory()
```

2022-08-13 21:26 UTC, stanalbatross requested changes
make it so that you can order them from ASRS for twice the price of regular claymores

2022-08-13 21:48 UTC, johnravioliUSA commented
> make it so that you can order them from ASRS for twice the price of regular claymores

done

2022-08-15 14:43 UTC, stanalbatross commented on code/game/objects/items/explosives/mine.dm
> +				SPAN_NOTICE("You start disarming [src]."))
```suggestion
				SPAN_NOTICE("You start disarming \the [src]."))
```

2022-08-17 23:53 UTC, monkeysfist101 requested changes
While the icons are fine on their own, they don't fit the setting. Please alter the appearance, name, and description, to reflect the G2 Electroshock Grenade (Sonic Electronic Ball Breakers)

The mechanics are fine, but please modify the explosion effects as well. I'll look into getting you the sound effects.

Thanks!

https://avp.fandom.com/wiki/G2_Electroshock_Grenade

2022-08-18 01:15 UTC, johnravioliUSA commented
> While the icons are fine on their own, they don't fit the setting. Please alter the appearance, name, and description, to reflect the G2 Electroshock Grenade (Sonic Electronic Ball Breakers)
> 
> The mechanics are fine, but please modify the explosion effects as well. I'll look into getting you the sound effects.
> 
> Thanks!
> 
> https://avp.fandom.com/wiki/G2_Electroshock_Grenade

I will do this sooner or later, because I'm busy and not able to do them like I did before (i was on summer break). Expect it to be done within a week or so.

2022-08-18 01:47 UTC, monkeysfist101 commented
> > While the icons are fine on their own, they don't fit the setting. Please alter the appearance, name, and description, to reflect the G2 Electroshock Grenade (Sonic Electronic Ball Breakers)
> > The mechanics are fine, but please modify the explosion effects as well. I'll look into getting you the sound effects.
> > Thanks!
> > https://avp.fandom.com/wiki/G2_Electroshock_Grenade
> 
> I will do this sooner or later, because I'm busy and not able to do them like I did before (i was on summer break). Expect it to be done within a week or so.

Awesome. Just let me know how I can help.

2022-09-03 00:30 UTC, closed without merging

2022-09-13 00:46 UTC, PhantomEpicness commented
Added to list of PRs I will revive at a later date.

Will include this into my AT mine PR whenever I feel like working on it again.