Tunnel Trap Deletion
cmss13-devs/cmss13 pull request #810
Opened 2022-08-04 18:03 UTC by Geevies

## About The Pull Request

Placing a trap then building a tunnel now destroys the trap.

## Why It's Good For The Game

a

## Changelog

:cl:
fix: Building a tunnel over a trap now destroys the trap.
/:cl:

2022-08-04 22:23 UTC, DylonBR commented
PIG nerf

2022-08-04 22:58 UTC, stanalbatross requested changes
we love readable code

2022-08-04 22:58 UTC, stanalbatross commented on code/modules/cm_aliens/structures/tunnel.dm
> +	if(resin_trap) qdel(resin_trap)
```suggestion
	if(resin_trap) 
		qdel(resin_trap)
```

2022-08-06 09:23 UTC, stanalbatross approved these changes

2022-08-06 09:23 UTC, merged

2022-08-09 11:46 UTC, SarahJohnson489 commented
Feedback:

Weed a room
Place a resin hole by the door
Destroy the hole and the weed tile under it leaving a 1x1 hole
Place a resin node to replace the weed
Attempt to place a resin hole

"You can't place a resin hole on a resin node!" "You can't place a resin hole on a resin node!"
"You can't place a resin hole on a resin node!" "You can't place a resin hole on a resin node!"
"You can't place a resin hole on a resin node!" "You can't place a resin hole on a resin node!"
"You can't place a resin hole on a resin node!" "You can't place a resin hole on a resin node!"


Grenades, CAS, wildin marine knives, c4, flames, a massive amount of sources cause non-orthagonal weed breakage while now results in denying burrowers tiles to place resin holes because of the change. Which is actually really kinda important given the extremely positional nature of Resin Hole placement. Needs a revert quickly.

2022-08-22 09:01 UTC, DeafeningAAA commented
I remember talkin jeser out of adding this exact thing 2 years ago
The issue this change causes can be summed up like this:
>Random drone weeds an area
>Places weed nodes in a bunch of trap-friendly spots
>Someone else, playing burrower, can no longer access said trap spots, until marines destroy the nodes

Just revert. Placing traps on top of nodes was never a problem to begin with.