Resin building on dead log
cmss13-devs/cmss13 pull request #812
Opened 2022-08-06 06:18 UTC by morrowwolf

## About The Pull Request

Building a resin wall (or other closed turf) on a dead body will be logged. If this is meta'd by people then we can go harder but this seems to solve the basic issue for now.

## Why It's Good For The Game

Server logs good.

## Changelog

:cl: Morrow
admin: Resin walls on dead bodies will now be logged.
/:cl:

2022-08-06 06:34 UTC, morrowwolf commented
> Should only apply to revivable or otherwise not-perma'd bodies. See
> 
> https://github.com/cmss13-devs/cmss13/blob/63d5f92f34e0c821ff959eb6ff21b6fc8dc42ae1/code/modules/mob/living/living.dm#L671
> where that variable is set under what conditions.

There's an argument perma bodies shouldn't be walled off either as they may have critical gear of some sort. Hopefully a bit of common sense with the log will handle most things.

2022-08-06 09:32 UTC, stanalbatross requested changes

2022-08-06 09:32 UTC, stanalbatross commented on code/modules/mob/living/carbon/xenomorph/Powers.dm
> +				msg_admin_niche("[src.ckey]/([src]) has built a closed resin structure, [new_resin.name], on top of a dead human, [enclosed_human.ckey]/([enclosed_human]), at [new_resin.x],[new_resin.y],[new_res
add a JMP link

2022-08-07 08:42 UTC, morrowwolf commented
> > > Should only apply to revivable or otherwise not-perma'd bodies. See
> > > https://github.com/cmss13-devs/cmss13/blob/63d5f92f34e0c821ff959eb6ff21b6fc8dc42ae1/code/modules/mob/living/living.dm#L671
> > > 
> > > where that variable is set under what conditions.
> > 
> > 
> > There's an argument perma bodies shouldn't be walled off either as they may have critical gear of some sort. Hopefully a bit of common sense with the log will handle most things.
> 
> Do you want pre-bursted bodies trigging the logging too? Or are those not a var/mob/living/carbon/human/enclosed_human ?

I really want to avoid over complicating this. It's a tool.

2022-08-08 12:45 UTC, stanalbatross approved these changes

2022-08-08 12:46 UTC, stanalbatross commented
can be changed later down the line if needed

2022-08-08 12:46 UTC, merged