bodyscanner no longer sends you to the nighmare dimension
cmss13-devs/cmss13 pull request #821
Opened 2022-08-07 23:53 UTC by Diegoflores31

## About The Pull Request

PR adds a check after you try to get inside of the bodyscanner so you cant enter while its occupied . sending the previous user into the nightmare realm

## Why It's Good For The Game

Closes #790 

## Changelog

:cl:
fix: Bodyscanner no longer dissapears marines if they hop inside at the same time.
/:cl:

2022-08-08 08:54 UTC, JeserTheFox commented on code/game/machinery/adv_med.dm
> +		if (src.occupant)
```suggestion
		if (occupant)
```

2022-08-08 10:47 UTC, spookydonut commented on code/game/machinery/adv_med.dm
> +			to_chat(usr, SPAN_NOTICE(" <B>The scanner is already occupied!</B>"))
dont think you're meant to use <b>

2022-08-08 17:25 UTC, Diegoflores31 commented
suggestions applied

2022-08-10 09:52 UTC, stanalbatross requested changes

2022-08-10 09:52 UTC, stanalbatross commented on code/game/machinery/adv_med.dm
> +			to_chat(usr, SPAN_NOTICE(" <B>The scanner is already occupied!</B>"))
```suggestion
			to_chat(usr, SPAN_NOTICE("<B>The scanner is already occupied!</B>"))
```
use BOLDNOTICE

2022-08-12 21:06 UTC, stanalbatross commented on code/game/machinery/adv_med.dm
> +			to_chat(usr, SPAN_NOTICE("<B>The scanner is already occupied!</B>"))
```suggestion
			to_chat(usr, SPAN_BOLDNOTICE("The scanner is already occupied!"))
```

2022-08-14 17:54 UTC, merged