Lobby Hive Leader Viewing
cmss13-devs/cmss13 pull request #827
Opened 2022-08-09 11:04 UTC by Geevies

## About The Pull Request

![image](https://user-images.githubusercontent.com/22774890/183632628-5f9c5811-ac62-41fb-b7c7-96a5b5ad306d.png)

## Why It's Good For The Game

Xeno players have been asking for this for a while, especially with how much power a Queen has over a round.

## Changelog

:cl:
add: You can now see who's playing the Queen / her hive leaders from the lobby.
/:cl:

2022-08-09 11:53 UTC, c4xmaniac commented
XX prime queen nerf

2022-08-10 16:55 UTC, stanalbatross commented
All new player facing UIs must be TGUI

2022-08-15 22:39 UTC, stanalbatross reviewed
I can write a nicer version of the tgui probably

2022-08-15 22:39 UTC, stanalbatross commented on code/modules/mob/living/carbon/xenomorph/Xenomorph.dm
> +	full_designation = "[name_client_prefix][nicknumber][name_client_postfix]"
put maturity in maybe?

2022-08-20 05:37 UTC, morrowwolf commented
Drafting til TGUI

2022-08-21 15:29 UTC, Geevies commented on code/modules/mob/living/carbon/xenomorph/Xenomorph.dm
> +	full_designation = "[name_client_prefix][nicknumber][name_client_postfix]"
nah, i think it's fine as-is

2022-08-25 17:33 UTC, stanalbatross requested changes

2022-08-25 17:33 UTC, stanalbatross commented on code/modules/mob/new_player/new_player.dm
> +	. = list()
data = list()

hijacking . makes it harder to read

2022-09-03 10:41 UTC, Geevies commented on code/modules/mob/new_player/new_player.dm
> +		output += "<a href='byond://?src=\ref[src];lobby_choice=hiveleaders'>View Hive Leaders</A><br><br>"
that'd mean we have to update everyone in the lobby's thing to consider whether mainhive exists, so nah

2022-09-03 12:30 UTC, stanalbatross commented on code/modules/mob/new_player/new_player.dm
> +		output += "<a href='byond://?src=\ref[src];lobby_choice=hiveleaders'>View Hive Leaders</A><br><br>"
but that already happens with join the hunt and pred rounds 🤔

2022-09-03 22:43 UTC, stanalbatross approved these changes

2022-09-11 00:54 UTC, merged