Gib Check
cmss13-devs/cmss13 pull request #85
Opened 2022-04-18 14:33 UTC by realforest2001

## About The Pull Request
Fixes Queen Gib to check for larva both before initiation and after, to prevent hugged humans being gibbed after infection when started before.

## Why It's Good For The Game

## Changelog

:cl:
fix: Queen Gib no longer works on hugged marines pre-infection, and checks are now made through a handler proc.
/:cl:

2022-04-18 15:03 UTC, stanalbatross requested changes

2022-04-18 15:03 UTC, stanalbatross commented on code/modules/mob/living/carbon/xenomorph/castes/Queen.dm
> +			to_chat(src, SPAN_XENOWARNING("The host will soon bare a child of the hive!"))
```suggestion
			to_chat(src, SPAN_XENOWARNING("The host will soon bear a child of the hive!"))
```

2022-04-18 23:18 UTC, stanalbatross commented
![image](https://user-images.githubusercontent.com/66756236/163891627-25ec755d-2a3f-4952-ba78-ec94691232d0.png)
![image](https://user-images.githubusercontent.com/66756236/163891672-46f50823-d8f3-481b-b787-d6e53b3e8e32.png)

if you could, can you also fix this crash when gibbing an alive person (it also makes the death message not show up in dchat)

2022-04-20 21:30 UTC, Watermelon914 commented on code/modules/mob/living/carbon/xenomorph/castes/Queen.dm
> +					return FALSE
make H a more detailed variable name

2022-05-04 23:09 UTC, Carnage068 commented
no offense or anything but when would this even happen in game?

2022-05-05 20:11 UTC, stanalbatross commented
![image](https://user-images.githubusercontent.com/66756236/167017353-dcead3e2-1272-4f47-b310-64b514748666.png)
issue still happening
![image](https://user-images.githubusercontent.com/66756236/167017443-38e9f8fc-de10-4c8b-884e-f1358b6146b5.png)
likely a problem with cause_data there

2022-05-05 20:29 UTC, realforest2001 commented
Sigh. No idea why it keeps freaking out, this cause_data stuff is a pain.

2022-05-05 20:29 UTC, realforest2001 commented
> no offense or anything but when would this even happen in game?

I've witnessed it more than once, which is enough reason to fix it. Even if it never happened, no reason to make sure it's checking things properly anyway.

2022-05-05 21:00 UTC, stanalbatross commented
> Sigh. No idea why it keeps freaking out, this cause_data stuff is a pain.

mostly because it's string data rather than datums as you have create_cause_data("xyz") all over there

2022-05-14 09:23 UTC, Watermelon914 commented
keep your title names descriptive please

2022-05-14 09:24 UTC, Watermelon914 commented on code/modules/mob/living/carbon/xenomorph/castes/Queen.dm
> +	if(istype(Host))
use snake_case for variable names, avoid PascalCase

2022-06-18 00:31 UTC, closed without merging