reverts blowtorches no longer causing eye damage ever
cmss13-devs/cmss13 pull request #877
Opened 2022-08-16 13:09 UTC by stanalbatross

## About The Pull Request

welding screen var turned to OFF

## Why It's Good For The Game

**gameplay**

cutting out an entire game mechanic solely because of a little quirk on the sprite is not good. There was no reason to remove the need for welding protection and it makes the entire system deprecated and useless - as well as nullifying several other interesting mechanics such as synth welding protection

you should also be more vulnerable while welding and not able to see everything around you with ease.

**realism**

a tiny little glass screen on a welder CANNOT protect you from the massive light caused by the torch. The light will go _around_ the screen and directly into your eyes.

I know that in alien isolation it works like that, but due to gameplay concerns this should not be a thing. If it really matters then change the sprite to not have the transparent gap in the screen.

## Changelog

:cl:
del: blowtorches no longer always protect you from eye damage
/:cl:

2022-08-16 13:59 UTC, Lagomorphica commented
can we improve the combat tech helmet sprite so it doesn't look like a soiled diaper on your head at least bro.. please...

2022-08-16 15:31 UTC, VagabondZero79 commented
Why not just make a seperate better blowtorch that requires eye protection?

2022-08-16 15:46 UTC, c4xmaniac commented
Yeah it’s pretty dumb I was able to fully set up power on LV as a surv with 0 protection and 0 side effects. I was an engie surv, normally you’d only be able to fix half the power before going blind.

2022-08-16 16:31 UTC, stanalbatross commented
> Why not just make a seperate better blowtorch that requires eye protection?

because that's powercreep

2022-08-16 16:33 UTC, Blithering commented
How about leaving the eyeprot on the default mini-welder, but removing it from the high capacity industrial welder, so its a sidegrade  instead of a direct upgrade?

2022-08-16 16:38 UTC, stanalbatross commented
> How about leaving the eyeprot on the default mini-welder, but removing it from the high capacity industrial welder, so its a sidegrade instead of a direct upgrade?

welder should always require protection

2022-08-16 17:53 UTC, FoxyStalin commented
Really do not know how that buff made it in in the first place.  'Was in the movies' does not mean 'good for gameplay'.

Revert acid blood buff while we're at it.

2022-08-16 18:02 UTC, Lumdor commented
To appease lore lovers just have a smaller welder with the shield on it that can only weld and un-weld doors and has a very low fuel capacity. Then leave the other welders with the requirement of needing eye protection for everything.

2022-08-16 21:33 UTC, Listaless commented
Yeah let's revert the wall slashing change from almost a year ago while were at it, as you know it completely invalidates using acid on walls because slashing them is simply faster, you can stack up on top of each other to do it as well not to mention half the fucking xeno caste can do it as well.

2022-08-16 21:35 UTC, hotimep commented
can we remove warriors i dont like them either

2022-08-16 23:58 UTC, Agameofscones commented
> can we improve the combat tech helmet sprite so it doesn't look like a soiled diaper on your head at least bro.. please...

your wish will be granted.

2022-08-17 10:09 UTC, Waseemq1235 commented
`The light will go around the screen and directly into your eyes.`

Unless your screen has the gravitational pull of a mini black hole that can bend the trajectory of transverse waves travelling at the speed of light, this makes no sense.

2022-08-17 16:54 UTC, Geevies requested changes

2022-08-17 16:56 UTC, Geevies requested changes

2022-08-17 16:56 UTC, Geevies commented on code/game/machinery/camera/camera.dm
> +		if(!HAS_TRAIT(W, TRAIT_TOOL_BLOWTORCH))
wherever this is the case, an error message should be displayed to the user

2022-08-18 00:17 UTC, Superwelder commented
I like that idea behind a new welder with the built in eye protection from Lumdor but I am uncomfortable with forcing new players to now memorize what each specific type of welder can weld and if they need protection to use it. Availability also is an awkward proposition. Where would you put these new welders around the map? The engineering places that have welders would naturally have eye protection to go with them. Maybe it could go a step further and weld those select items like doors and vents much faster than a standard welder with a useful description to match it. Maybe the shielded welder would be something the lathe could make when hacked similar to the 40u blowtorch.

2022-08-19 17:56 UTC, Geevies commented
posting here so you don't forget the sprites

2022-08-19 18:04 UTC, c4xmaniac commented
What is the point of a welder that does nothing but weld doors and vents, it will never be used.

2022-08-26 22:17 UTC, RadiationFan commented
Please don't. Torches as a whole are annoying enough as it is. For marines, getting a techhelmet isnt hard, persay, but it is another inconvenience that mini engies and M2C users will have to go through. 

If anything, make the process of welding more realistic by adding in a welder setup like the real world, a proper generator with a welding box, welding wire or rod, and leads. Have it weld crazy fast, and multiple different stages at once, repairs crumbling cades and holes in walls, that would actually make welding an interesting, and realistic experience. You could use the spriting from telephones as leads, would just have to sprite a welder/welding supplies.

2022-08-26 22:23 UTC, stanalbatross commented
> If anything, make the process of welding more realistic by adding in a welder setup like the real world, a proper generator with a welding box, welding wire or rod, and leads. Have it weld crazy fast, and multiple different stages at once, repairs crumbling cades and holes in walls, that would actually make welding an interesting, and realistic experience. You could use the spriting from telephones as leads, would just have to sprite a welder/welding supplies.

sounds like a fun project you could code

2022-08-26 22:46 UTC, RadiationFan commented
> > If anything, make the process of welding more realistic by adding in a welder setup like the real world, a proper generator with a welding box, welding wire or rod, and leads. Have it weld crazy fast, and multiple different stages at once, repairs crumbling cades and holes in walls, that would actually make welding an interesting, and realistic experience. You could use the spriting from telephones as leads, would just have to sprite a welder/welding supplies.
> 
> sounds like a fun project you could code

You asked for input...

2022-08-26 22:55 UTC, stanalbatross commented
> Please don't. Torches as a whole are annoying enough as it is. For marines, getting a techhelmet isnt hard, persay, but it is another inconvenience that mini engies and M2C users will have to go through.

regards to this, as I explained earlier : `you should also be more vulnerable while welding and not able to see everything around you with ease.`

PFCs and miniengies should have to go out of their way to get welding equipment, it should not be super easy

2022-08-28 15:54 UTC, Geevies approved these changes

2022-08-28 15:54 UTC, Geevies commented on code/game/machinery/vending/vendor_types/engineering.dm
> +		list("ME3 hand welder", round(scale * 2), /obj/item/tool/weldingtool/simple, VENDOR_ITEM_REGULAR),
```suggestion
		list("ME3 Hand Welder", round(scale * 2), /obj/item/tool/weldingtool/simple, VENDOR_ITEM_REGULAR),
```

2022-08-28 15:54 UTC, Geevies commented on code/game/machinery/vending/vendor_types/engineering.dm
> +		list("ME3 hand welder", round(scale * 2), /obj/item/tool/weldingtool/simple, VENDOR_ITEM_REGULAR)
```suggestion
		list("ME3 Hand Welder", round(scale * 2), /obj/item/tool/weldingtool/simple, VENDOR_ITEM_REGULAR)
```

2022-08-28 15:56 UTC, merged