fixes incredibly strong phone line
cmss13-devs/cmss13 pull request #893
Opened 2022-08-18 20:39 UTC by TheBoondock

## About The Pull Request
In proc Moved() of tether codes any obj is converted into a subtype of atom/movable/ therefore any and all objects are moveable. This pr simply add an early return if the the tether is connected to a strcuture (which most are anchored)
I have attempted to allow it o move unanchored objects but was unable to do so advices are welcomed for such implementation
Fixes #366

## Why It's Good For The Game
Bus gone is good!

## Changelog

:cl:
fix: due to unintended materials being used in phone lines resulting in them being incredibly strong, the mistakes have been found and all current phone lines are recalled and replaced with weaker one to save on cost, they will now break if pulling a heavy objects.
/:cl:

2022-08-23 19:07 UTC, stanalbatross requested changes

2022-08-23 19:07 UTC, stanalbatross commented on code/datums/effects/tether.dm
> +		if(BigBoi.anchored)
snake_case

2022-08-23 22:15 UTC, TheBoondock commented on code/datums/effects/tether.dm
> +		if(BigBoi.anchored)
Wut?

2022-08-24 07:22 UTC, stanalbatross commented on code/datums/effects/tether.dm
> +		if(BigBoi.anchored)
Variable names must use snake_case

2022-09-02 13:16 UTC, morrowwolf requested changes

2022-09-02 13:16 UTC, morrowwolf commented on code/datums/effects/tether.dm
> +		var/obj/structure/Big_boi = tethered.affected_atom
nitpick but snake_case is not capitalized throughout. Also this variable could be named way better.

2022-09-02 13:17 UTC, morrowwolf commented on code/datums/effects/tether.dm
> +		var/obj/structure/Big_boi = tethered.affected_atom
Oh and make sure to put your ckey next to the :cl: tag

2022-09-13 01:26 UTC, merged