Xeno strain purchase and evolving changes
cmss13-devs/cmss13 pull request #9
Opened 2022-04-15 00:13 UTC by Shad0vvs

## About The Pull Request

## Why It's Good For The Game

> add: Added basic checks to strain purchasing so you must be at full hp/not stunned/resting/in a stance/etc to purchase.

The above prevents strain purchasing (as there was only an isdead check before) while low hp/crit/etc so that you cannot abuse, for example; godcrest bug and/or purchasing acid runner strain to get out of crit.

> tweak: Made it so you cannot utilize abilities while evolving as a xeno.

The above prevents ability while in the evolve state so you cannot abuse, for example; pounce as a runner while evolving and then getting another pounce as a lurker.
Probably also good so a xeno in front of you does not quickly evolve in the middle of a fight while you're fighting it and get a free heal on a newmob.

## Changelog

:cl:
add: Added basic checks to strain purchasing so you must be at full hp/not stunned/resting/in a stance/etc to purchase.
tweak: Made it so you cannot utilize abilities while evolving as a xeno.
/:cl:

2022-04-15 08:38 UTC, stanalbatross requested changes

2022-04-15 08:38 UTC, stanalbatross commented on code/modules/mob/living/carbon/xenomorph/XenoMutatorSets.dm
> +		to_chat(usr, "There are no avaliable strains.")
```suggestion
		to_chat(usr, "There are no available strains.")
```

2022-04-15 08:38 UTC, stanalbatross commented on code/modules/mob/living/carbon/xenomorph/XenoMutatorSets.dm
> +		return
should this not be return false?

2022-04-15 16:30 UTC, stanalbatross approved these changes

2022-04-16 09:47 UTC, Watermelon914 requested changes

2022-04-16 09:47 UTC, Watermelon914 commented on code/modules/mob/living/carbon/xenomorph/XenoMutatorSets.dm
> +	var/mob/living/carbon/Xenomorph/X = usr
please make your variable names more detailed

2022-04-16 21:24 UTC, stanalbatross approved these changes
var name confirmed to be explicit

2022-04-17 16:27 UTC, Geevies approved these changes

2022-04-17 16:29 UTC, merged