No more suicide bomb mice
cmss13-devs/cmss13 pull request #902
Opened 2022-08-19 21:08 UTC by morrowwolf

## About The Pull Request

Previously people were planting custom C4 on simple mobs and then picking them up and placing them in storage containers allowing another person to then use a signaler to blow the capped person up in the hive.

## Why It's Good For The Game

This is not an intentional usage for custom C4 and was a way to get around checks.

## Changelog

:cl: Morrow
fix: You can no longer use picked up simple mobs to get around the C4 limits.
/:cl:

2022-08-19 22:00 UTC, DylonBR commented
insanely cringe PR

2022-08-20 11:23 UTC, stanalbatross approved these changes

2022-08-21 13:41 UTC, stanalbatross requested changes
make them totally unable to be picked up instead of changing w_class

2022-08-21 22:15 UTC, stanalbatross approved these changes

2022-08-21 22:40 UTC, merged