Water Tank QoL
cmss13-devs/cmss13 pull request #904
Opened 2022-08-20 06:17 UTC by PhantomEpicness

## About The Pull Request

In yet another very funny story of "fixing" a problem illogically that simply creates more, we have watertanks.

Sometime in the past someone abused them to block xenos as they weren't destroyable by them?

So what did a dev do?

_Make them destructable?_

Nope, that's too simple. Instead, we go to the almayer and permanently anchor the watertanks there! Fixed!

Hilariously, not even all of them were anchored.

This PR makes so they are slashable and can be destroyed by bullets as well.

## Why It's Good For The Game

qol bugfix
## Changelog

:cl:totalepicness

qol: Liquid tanks are now destroyable by bullets and xenos alike
qol: Water tanks can now be wrenched and unwrenched at will.
fix: Fixed the random anchored watertanks in Almayer
fix: Fixed anchored OT custom reagent tanks in OT fuel room

/:cl:

2022-08-20 10:46 UTC, stanalbatross requested changes

2022-08-20 10:46 UTC, stanalbatross commented on code/game/objects/structures/reagent_dispensers.dm
> +		message_staff("[key_name_admin(Proj.firer)] fired a projectile at [name] in [loc.loc.name] ([loc.x],[loc.y],[loc.z]) (<A HREF='?_src_=admin_holder;[HrefToken(forceGlobal = TRUE)];adminplayerobserve
make this an attack log or niche log

2022-08-20 10:46 UTC, stanalbatross commented on code/game/objects/structures/reagent_dispensers.dm
> +		Destroy()
you make a proc for healthcheck, use it

2022-08-20 10:46 UTC, stanalbatross commented on maps/map_files/USS_Almayer/USS_Almayer.dmm
> +	anchored = 0
remove instance just replace with base path like you did above

2022-08-20 10:46 UTC, stanalbatross commented on maps/map_files/USS_Almayer/USS_Almayer.dmm
> +	anchored = 0
''

2022-08-20 20:51 UTC, nuklearcellphoneg commented
Thank you, this will save me the ten minutes of dragging the unanchored one upstairs downstairs

2022-08-22 19:10 UTC, stanalbatross requested changes

2022-08-22 19:10 UTC, stanalbatross commented on code/game/objects/structures/reagent_dispensers.dm
> +	var/slashable = FALSE
you haven't even implemented attack_alien

2022-09-01 03:34 UTC, Wintermote commented
PR's like this are a godsend.

2022-09-06 20:56 UTC, stanalbatross requested changes

2022-09-06 20:56 UTC, stanalbatross commented on code/game/objects/structures/reagent_dispensers.dm
> +	var/slashable = FALSE
this ia a base var on structure do not make a snowflake one

2022-09-06 20:56 UTC, stanalbatross commented on code/game/objects/structures/reagent_dispensers.dm
> +
```suggestion
```

2022-09-06 20:56 UTC, stanalbatross commented on code/game/objects/structures/reagent_dispensers.dm
> +		Destroy()
qdel

2022-09-06 20:56 UTC, stanalbatross commented on code/game/objects/structures/reagent_dispensers.dm
> +	SPAN_DANGER("You slash [src]!"), null, 5, CHAT_TYPE_XENO_COMBAT)
\the

2022-09-14 07:40 UTC, stanalbatross commented on code/game/objects/structures/reagent_dispensers.dm
> +		Destroy()
You need to remove the destroy line

2022-09-14 07:41 UTC, stanalbatross requested changes
Do not call destroy

2022-09-15 00:02 UTC, PhantomEpicness commented on code/game/objects/structures/reagent_dispensers.dm
> +		Destroy()
meant to remove it lol

2022-09-15 00:02 UTC, PhantomEpicness commented
> Do not call destroy
meant to remove it lol

fixed

2022-09-16 16:17 UTC, stanalbatross approved these changes

2022-09-16 16:17 UTC, merged