Cryomarine Stuff
cmss13-devs/cmss13 pull request #905
Opened 2022-08-20 09:47 UTC by Geevies

## About The Pull Request

The Reserves squad is now called Foxtrot. Their brown color has been brightened a bit, the radio color as well. They also no longer break the crew manifest.

You can now call the reserves in-game via the tech tree, it's a Tier 3 tech that costs 10 points, but increases by 5 each time it's called. The squad contains a squad leader, medics, engineers, and privates.

The tech points required to go up a tier has been reduced to 5 from 15.

## Why It's Good For The Game

Foxtrot is a cooler name than Reserves, and exists within the actual games. The brown was a bit muddy and made it look like they didn't have a squad at all, so the brighter one resolves that.

Calling the cryomarines via the tech tree is cool, and keeps people in the game in longer games.

The tech points required to transition was too much, I've been told, so knocking it down to 5 seems fine to me.

## Changelog

:cl:
fix: The Reserves squad is now called Foxtrot. Their brown color has been brightened a bit, the radio color as well. They also no longer break the crew manifest.
add: You can now call the reserves in-game via the tech tree, it's a Tier 3 tech that costs 10 points, but increases by 5 each time it's called. The squad contains a squad leader, medics, engineers, and privates.
balance: The tech points required to go up a tier has been reduced to 5 from 15.
/:cl:

2022-08-21 16:31 UTC, hotimep commented
foxtrot squad will be real in 3 minutes

2022-08-27 09:15 UTC, stanalbatross approved these changes

2022-08-27 09:15 UTC, stanalbatross commented on code/__DEFINES/job.dm
> +#define SQUAD_MARINE_CRYO				"Foxtrot"
IMO this change just makes the reserves squad more confusing 
it should still be called reserves
or just put the cryorines into random squads

2022-08-28 18:35 UTC, PhantomEpicness commented
INCREDIBLY based

2022-09-01 03:31 UTC, Wintermote commented
Cryomarines in the past were way too expensive for what they delivered.

How many marines is this spawning? Ideally you can get 2 purchases with a good budget supply from intel, but if we're talking 4 marines each time like it used to be, that simply isn't going to be enough to matter.

Marines need somewhere in the range of 8-12 for the number of reinforcements to matter. Especially if there's only a handful of specialists like medics or engineers in the group. It should also scale depending on total players. An extra 12 or 15 marines when there were only 30 marines to start with is way too much, and 6 marines for a round that started with 60+ is way too little

Imo the sweet spot is a 15-20% reinforcement amount. That should be enough to give marines a bit more staying power or recover and counter attack when necessary.

Anyway, good PR. It is, imo, one of the most important changes for making intel collection not feel underwhelming/useless. Yeah more ammo for CAS/Mortar is nice, but you really do not feel that compared to knowing you got some more marines back into the round. The hope of IO's collecting enough intel for cryomarines imo keeps some people spectating the round after they die instead of quitting and coming back in an hour.

2022-09-06 02:46 UTC, FoxyStalin commented
The Cryomarine's headset is a little bit bugged, in order to get the SL tracker you have to take your headset off and put it back on.

2022-09-08 00:28 UTC, Diegoflores31 commented
would be good if there was a lil bit more marines but appart from that very nice stuff . this will make long rounds less boring

2022-09-10 04:07 UTC, morrowwolf approved these changes
Code LGTM, needs architect approval

2022-09-10 04:09 UTC, morrowwolf requested changes
Wait I lied, fix the headset bug where they need to re-equip the headset for tracking to work.

2022-09-14 18:30 UTC, closed without merging