M2C Ammo type fix
cmss13-devs/cmss13 pull request #939
Opened 2022-08-25 09:36 UTC by Mister-moon1

## About The Pull Request
Fixes the type of ammo the M2C box mags uses, changing it from smartgun ammo to regular machinegun ammo

## Why It's Good For The Game
The M2C doesnt use smartgun ammo it uses 10x28mm tungsten

## Changelog

:cl:
Fix: Ammo type of M2C changed to be that of the M56D
/:cl:

2022-08-25 10:43 UTC, Mister-moon1 commented
i was initially mistaken due to spaghetti code but i found that the m2c should be using /datum/ammo/bullet/machinegun/auto as its default ammo type and not /datum/ammo/bullet/machinegun, this has now been corrected

2022-08-30 10:30 UTC, stanalbatross requested changes
also needs the caliber var set or it makes () caliber rounds

I can confirm this will not affect the damage of the gun

2022-08-30 12:59 UTC, Mister-moon1 commented
It should bare a caliber type now and shouldnt show up as () anymore if it all goes correctly

2022-08-30 14:03 UTC, stanalbatross approved these changes

2022-08-30 14:04 UTC, merged