limb printer update
cmss13-devs/cmss13 pull request #957
Opened 2022-08-28 15:03 UTC by stanalbatross

## About The Pull Request

## Why It's Good For The Game

## Changelog

:cl:
ui: the limb printer now uses tgui
ui: the signaller tgui now uses sliders rather than knobs
add: gave the limb printer some love. It now has a unique sprite when printing, can eject metal, has a max metal limit of 500, and starts with 125 metal instead of 1000. It can no longer accept meat (was not used for anything) and its backend code is much better now.
/:cl:

2022-08-29 21:27 UTC, stanalbatross commented
> Is it still going to cost 125 metal to print a limb? If so, this means that between the four limb printers in medbay field docs could only print ~4 limbs at round start. Given that xenos target feet/legs and delimbs are quite common this feels like it may be a balance adjustment as it will require more metal to be diverted to medbay for limb printing instead of FOB as rounds go on.
> 
> Not saying it's a bad change, just that if the above is accurate, maybe a balance tag should be applied to this PR?

true, my intention with reducing the metal count a bit was to require docs to scav a bit for metal (they only get 4 limbs round-start instead of 32)

2022-09-04 23:26 UTC, monkeysfist101 requested changes
Stray pixel in the top left on one animation frame. Fix it and the sprites will be good.
![image](https://user-images.githubusercontent.com/12722743/188337520-65f6b6fc-39d1-47ae-b839-a707e1f158cd.png)

2022-09-04 23:30 UTC, Agameofscones approved these changes
sprites and mapping are GOOD

2022-09-05 13:08 UTC, stanalbatross commented
> Stray pixel in the top left on one animation frame. Fix it and the sprites will be good. ![image](https://user-images.githubusercontent.com/12722743/188337520-65f6b6fc-39d1-47ae-b839-a707e1f158cd.png)

icondiffbot error, there wasn't one in the actual dmi (I checked)

2022-09-12 14:36 UTC, spookydonut requested changes

2022-09-12 14:36 UTC, spookydonut commented on code/game/machinery/autodoc.dm
> +				break
do the maths properly this is awful

2022-09-12 14:36 UTC, spookydonut commented on code/game/machinery/bioprinter.dm
> +			products += bp_recipe
why not use a GLOB ?

2022-09-26 09:05 UTC, spookydonut approved these changes

2022-09-26 09:06 UTC, merged