Removes Warrior Shield, Implements Lifesteal and Cooldown on Slash Reductions.
cmss13-devs/cmss13 pull request #973
Opened 2022-08-31 10:06 UTC by usnpeepoo

## About The Pull Request

Warrior slash shield has been removed, in place for it is lifesteal from slashes and a slight cooldown reduction per slash. Warrior also gains 50 more health. The lifesteal is comparable to shield, but requires 4 slashes to gain. The %ge of health gained increases with more marines near the warrior by 3 tiles up to a maximum of 9 (2 marines = 2% more lifesteal). This increased health shows a glow, and a cue in chat when it happens. Warrior also gains a very slight cooldown reduction per slash (0.30 seconds worth).
Huge thanks to Nivrak for allowing me to reuse their lifesteal PR, and helping me with the visual cue for it.

## Why It's Good For The Game

Warriors shield is unhealthy for current CM gameplay, and this PR hopes to fix it through something similar to berserkers system of life steal. With shields, warriors have an invisible (to marines) extra health bar, that is permanent and always recoupable. By removing it, and implementing life steal and slash cooldown reduction warriors no longer have the points mentioned above, rather they are rewarded more intuitively for hitting abilities, finding opportunities to hit their slashes a lot more, and being rewarded for doing so without giving them a shield. By allowing warrior to heal and acquire stronger heals by being more risky with their abilities, and also giving them less cooldowns to initiate fights with per slash, warriors are now able to fit the role of a frontline-ambusher caste that can continue fighting through the use of its abilities while dealing with the issue with shields being in that role.

This PR also aims to be in line with the xeno shield design doc, and seeks to bring one of the goals to light by making warrior buff itself in a different way than simply shields. 
You can read the design doc here, https://github.com/cmss13-devs/cmss13-design-docs/blob/main/xeno/shields.md.

## Changelog

:cl:
balance: Removed shielding slash from warrior, Health increased from 450 to 550, Warrior slashes now heal for (7 + 1 per enemy within 3 tiles, up to 2)% of missing health with a minimum of 17 and a maximum of 40.
balance: Warriors slash now reduces cooldowns from all abilities by 0.30 seconds worth. 
code: Gave cooldowns to warriors agility mode, Allows you to punch while in the mode, and Nerfed its speed.
/:cl:

2022-08-31 10:09 UTC, stanalbatross commented on code/modules/mob/living/carbon/xenomorph/castes/Warrior.dm
> +	for(var/mob/M as anything in mobs_in_range)
more detailed var name for M

2022-08-31 10:09 UTC, stanalbatross commented on code/modules/mob/living/carbon/xenomorph/castes/Warrior.dm
> +			bound_xeno.visible_message(SPAN_DANGER("[bound_xeno.name]'s glows as it heals even more from its injuries!."), SPAN_XENODANGER("You glow as your heal even more from your injuries!"))
```suggestion
			bound_xeno.visible_message(SPAN_DANGER("[bound_xeno.name] glows as it heals even more from its injuries!."), SPAN_XENODANGER("You glow as you heal even more from your injuries!"))
```

2022-09-01 19:55 UTC, Carnage068 commented
Holy fucking shit, this actually sounds like a really good idea. To me, at least. It sounds like it would push Warrior further in the direction of a frontline ambusher, instead of just an ambusher, and having higher risk + reward always sounds like a plus in my book. It's also just a lot more interesting and nuanced than a flat shield is.

2022-09-01 22:25 UTC, Carnage068 commented
FUCK YEAH

2022-09-04 01:22 UTC, PhantomEpicness commented
W pr

2022-09-12 04:46 UTC, Shad0vvs commented on code/modules/mob/living/carbon/xenomorph/abilities/warrior/warrior_abilities.dm
>  	var/mob/living/carbon/Xenomorph/X = owner
```suggestion
```

2022-09-12 04:51 UTC, Shad0vvs requested changes
### Possible balance/consistency concerns to consider @ balance reviewer:
It appears the lifesteal regen can be done while the xeno is on fire, this is inconsistent with any other heal ability.
Agility state check is currently set to permissive. (Probably not a big deal)

### Requested changes.
Add `/datum/action/xeno_action/onclick/toggle_agility` to base actions line ~50 on Warrior.dm so we have it in our top left verbs.
Remove all of can_use_action() in warrior_abilities.dm ~line 10, the checks are redundant.
(You probably also need to rebase since I can punch from 2 tiles away)
Maybe add a message for if(agility) on the other abilities to_chat saying that you can't do this while on all fours or something like that.

2022-09-12 20:19 UTC, Carnage068 commented
Hold up since when the hell was it getting Agility back? Not that I have a problem with it of course, bringing back old content is great.

2022-09-19 02:49 UTC, Shad0vvs approved these changes

2022-10-06 19:02 UTC, Weuyn commented
I think the green glow is too much. What was wrong with tge little vibrate they did when they got the shield? That was fine imo.

2022-10-07 00:00 UTC, usnpeepoo commented
> I think the green glow is too much. They just end up green all the time and it looks weird. Maybe just a jiggle like the do atm when they get the shield but only if they get a lot of health back? Not if its just 1 or 2 marines.

it is currently the old shield slash jitter, and the glow has been reduced by a lot and the warden heal icon has been added onto it, so when a warrior gets extra lifesteal it's still visible

2022-10-10 23:06 UTC, usnpeepoo commented
i shouldve searched up a how to rebase tutorial

2022-10-12 00:16 UTC, usnpeepoo commented
squash commits (it squashed every merged pr for the last 2 weeks into this PR)

never again

2022-10-12 00:16 UTC, closed without merging