Passable lz floodlight
cmss13-devs/cmss13 pull request #995
Opened 2022-09-04 10:26 UTC by Lengord

## About The Pull Request
Added passable lz variant of floodlight.
Ps. Irc it vas Vampmare who asked for sprite a year ago. I still have the sprite so why not? 

## Why It's Good For The Game
No more pinky toe injury.

## Changelog

:cl:
add: Passable floodlight
/:cl:

2022-09-04 10:26 UTC, Lengord commented
![Без імені](https://user-images.githubusercontent.com/57796873/188308861-2cae5ca3-5ab4-4d63-8c39-9a2024c7e232.png)

2022-09-04 10:29 UTC, JohnDoe50974 commented
Vampmare has been gone for much longer than a year though?

2022-09-04 10:31 UTC, Lengord commented
Oh, what can i say, time run fast.

2022-09-04 18:12 UTC, stanalbatross commented on code/game/machinery/floodlight.dm
> +	density = 0
```suggestion
	density = FALSE
```

2022-09-04 18:12 UTC, stanalbatross requested changes
You should probably add these to the actual maps as well

2022-09-04 18:58 UTC, Lengord commented
> You should probably add these to the actual maps as well

replace on all maps?

2022-09-04 21:53 UTC, stanalbatross commented
> > You should probably add these to the actual maps as well
> 
> replace on all maps?

where you see fit, so yeah probably

2022-09-04 23:15 UTC, Agameofscones approved these changes
LGTM

2022-09-05 13:52 UTC, Lengord commented
changed floodlites on LZ's, hope nothing is broken

2022-09-07 18:46 UTC, Lengord commented
i didn't know such thing as StrongDMM exist, i can discard map changes and redo with StrongDMM. About weird looking stuff, i didn't touch anything it's stock, but can change them if needed?

2022-09-07 18:51 UTC, stanalbatross requested changes
strongdmm style must be used for the files, default byond editor bad

2022-09-14 22:56 UTC, stanalbatross approved these changes
code is fine can be put on maps later

2022-09-14 22:57 UTC, merged